// AUTO-GENERATED from include/battle_gfx_sfx_util.h by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/include/battle_gfx_sfx_util.h
// Generated: 2026-04-26

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'AllocateBattleSpritesData', ret: "void", arity: 0, params: "void" },
  { name: 'FreeBattleSpritesData', ret: "void", arity: 0, params: "void" },
  { name: 'ChooseMoveAndTargetInBattlePalace', ret: "u16", arity: 0, params: "void" },
  { name: 'SpriteCB_WaitForBattlerBallReleaseAnim', ret: "void", arity: 1, params: "struct Sprite *sprite" },
  { name: 'SpriteCB_TrainerSlideIn', ret: "void", arity: 1, params: "struct Sprite *sprite" },
  { name: 'InitAndLaunchChosenStatusAnimation', ret: "void", arity: 2, params: "bool8 isStatus2, u32 status" },
  { name: 'TryHandleLaunchBattleTableAnimation', ret: "bool8", arity: 5, params: "u8 activeBattler, u8 atkBattler, u8 defBattler, u8 tableId, u16 argument" },
  { name: 'InitAndLaunchSpecialAnimation', ret: "void", arity: 4, params: "u8 activeBattler, u8 atkBattler, u8 defBattler, u8 tableId" },
  { name: 'IsMoveWithoutAnimation', ret: "bool8", arity: 2, params: "u16 move, u8 animationTurn" },
  { name: 'IsBattleSEPlaying', ret: "bool8", arity: 1, params: "u8 battler" },
  { name: 'BattleLoadOpponentMonSpriteGfx', ret: "void", arity: 2, params: "struct Pokemon *mon, u8 battler" },
  { name: 'BattleLoadPlayerMonSpriteGfx', ret: "void", arity: 2, params: "struct Pokemon *mon, u8 battler" },
  { name: 'BattleGfxSfxDummy2', ret: "void", arity: 1, params: "u16 species" },
  { name: 'DecompressTrainerFrontPic', ret: "void", arity: 2, params: "u16 frontPicId, u8 battler" },
  { name: 'DecompressTrainerBackPic', ret: "void", arity: 2, params: "u16 backPicId, u8 battler" },
  { name: 'BattleGfxSfxDummy3', ret: "void", arity: 1, params: "u8 gender" },
  { name: 'FreeTrainerFrontPicPalette', ret: "void", arity: 1, params: "u16 frontPicId" },
  { name: 'BattleLoadAllHealthBoxesGfx', ret: "bool8", arity: 1, params: "u8 state" },
  { name: 'LoadBattleBarGfx', ret: "void", arity: 1, params: "u8 unused" },
  { name: 'BattleInitAllSprites', ret: "bool8", arity: 2, params: "u8 *state1, u8 *battler" },
  { name: 'ClearSpritesHealthboxAnimData', ret: "void", arity: 0, params: "void" },
  { name: 'CopyAllBattleSpritesInvisibilities', ret: "void", arity: 0, params: "void" },
  { name: 'CopyBattleSpriteInvisibility', ret: "void", arity: 1, params: "u8 battler" },
  { name: 'HandleSpeciesGfxDataChange', ret: "void", arity: 3, params: "u8 battlerAtk, u8 battlerDef, bool8 castform" },
  { name: 'BattleLoadSubstituteOrMonSpriteGfx', ret: "void", arity: 2, params: "u8 battler, bool8 loadMonSprite" },
  { name: 'LoadBattleMonGfxAndAnimate', ret: "void", arity: 3, params: "u8 battler, bool8 loadMonSprite, u8 spriteId" },
  { name: 'TrySetBehindSubstituteSpriteBit', ret: "void", arity: 2, params: "u8 battler, u16 move" },
  { name: 'ClearBehindSubstituteBit', ret: "void", arity: 1, params: "u8 battler" },
  { name: 'HandleLowHpMusicChange', ret: "void", arity: 2, params: "struct Pokemon *mon, u8 battler" },
  { name: 'BattleStopLowHpSound', ret: "void", arity: 0, params: "void" },
  { name: 'GetMonHPBarLevel', ret: "u8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'HandleBattleLowHpMusicChange', ret: "void", arity: 0, params: "void" },
  { name: 'SetBattlerSpriteAffineMode', ret: "void", arity: 1, params: "u8 affineMode" },
  { name: 'LoadAndCreateEnemyShadowSprites', ret: "void", arity: 0, params: "void" },
  { name: 'SpriteCB_SetInvisible', ret: "void", arity: 1, params: "struct Sprite *sprite" },
  { name: 'SetBattlerShadowSpriteCallback', ret: "void", arity: 2, params: "u8 battler, u16 species" },
  { name: 'HideBattlerShadowSprite', ret: "void", arity: 1, params: "u8 battler" },
  { name: 'FillAroundBattleWindows', ret: "void", arity: 0, params: "void" },
  { name: 'ClearTemporarySpeciesSpriteData', ret: "void", arity: 2, params: "u8 battler, bool8 dontClearSubstitute" },
  { name: 'AllocateMonSpritesGfx', ret: "void", arity: 0, params: "void" },
  { name: 'FreeMonSpritesGfx', ret: "void", arity: 0, params: "void" },
  { name: 'ShouldPlayNormalMonCry', ret: "bool32", arity: 1, params: "struct Pokemon *mon" },
] as const;
