// AUTO-GENERATED from include/pokemon.h by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/include/pokemon.h
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
/** Raw expr: `(max(sizeof(struct PokemonSubstruct0),     \` */
export const NUM_SUBSTRUCT_BYTES_EXPR = "(max(sizeof(struct PokemonSubstruct0),     \\";
export const SPINDA_SPOT_WIDTH = 16;
export const SPINDA_SPOT_HEIGHT = 16;
export const NUM_UNOWN_FORMS = 28;

// ─── Enums ───────────────────────────────────────────────────────────────────
export const ENUM_MON_0 = {
  MON_DATA_PERSONALITY: 0,
  MON_DATA_OT_ID: 1,
  MON_DATA_NICKNAME: 2,
  MON_DATA_LANGUAGE: 3,
  MON_DATA_SANITY_IS_BAD_EGG: 4,
  MON_DATA_SANITY_HAS_SPECIES: 5,
  MON_DATA_SANITY_IS_EGG: 6,
  MON_DATA_OT_NAME: 7,
  MON_DATA_MARKINGS: 8,
  MON_DATA_CHECKSUM: 9,
  MON_DATA_ENCRYPT_SEPARATOR: 10,
  MON_DATA_SPECIES: 11,
  MON_DATA_HELD_ITEM: 12,
  MON_DATA_MOVE1: 13,
  MON_DATA_MOVE2: 14,
  MON_DATA_MOVE3: 15,
  MON_DATA_MOVE4: 16,
  MON_DATA_PP1: 17,
  MON_DATA_PP2: 18,
  MON_DATA_PP3: 19,
  MON_DATA_PP4: 20,
  MON_DATA_PP_BONUSES: 21,
  MON_DATA_COOL: 22,
  MON_DATA_BEAUTY: 23,
  MON_DATA_CUTE: 24,
  MON_DATA_EXP: 25,
  MON_DATA_HP_EV: 26,
  MON_DATA_ATK_EV: 27,
  MON_DATA_DEF_EV: 28,
  MON_DATA_SPEED_EV: 29,
  MON_DATA_SPATK_EV: 30,
  MON_DATA_SPDEF_EV: 31,
  MON_DATA_FRIENDSHIP: 32,
  MON_DATA_SMART: 33,
  MON_DATA_POKERUS: 34,
  MON_DATA_MET_LOCATION: 35,
  MON_DATA_MET_LEVEL: 36,
  MON_DATA_MET_GAME: 37,
  MON_DATA_POKEBALL: 38,
  MON_DATA_HP_IV: 39,
  MON_DATA_ATK_IV: 40,
  MON_DATA_DEF_IV: 41,
  MON_DATA_SPEED_IV: 42,
  MON_DATA_SPATK_IV: 43,
  MON_DATA_SPDEF_IV: 44,
  MON_DATA_IS_EGG: 45,
  MON_DATA_ABILITY_NUM: 46,
  MON_DATA_TOUGH: 47,
  MON_DATA_SHEEN: 48,
  MON_DATA_OT_GENDER: 49,
  MON_DATA_COOL_RIBBON: 50,
  MON_DATA_BEAUTY_RIBBON: 51,
  MON_DATA_CUTE_RIBBON: 52,
  MON_DATA_SMART_RIBBON: 53,
  MON_DATA_TOUGH_RIBBON: 54,
  MON_DATA_STATUS: 55,
  MON_DATA_LEVEL: 56,
  MON_DATA_HP: 57,
  MON_DATA_MAX_HP: 58,
  MON_DATA_ATK: 59,
  MON_DATA_DEF: 60,
  MON_DATA_SPEED: 61,
  MON_DATA_SPATK: 62,
  MON_DATA_SPDEF: 63,
  MON_DATA_MAIL: 64,
  MON_DATA_SPECIES_OR_EGG: 65,
  MON_DATA_IVS: 66,
  MON_DATA_CHAMPION_RIBBON: 67,
  MON_DATA_WINNING_RIBBON: 68,
  MON_DATA_VICTORY_RIBBON: 69,
  MON_DATA_ARTIST_RIBBON: 70,
  MON_DATA_EFFORT_RIBBON: 71,
  MON_DATA_MARINE_RIBBON: 72,
  MON_DATA_LAND_RIBBON: 73,
  MON_DATA_SKY_RIBBON: 74,
  MON_DATA_COUNTRY_RIBBON: 75,
  MON_DATA_NATIONAL_RIBBON: 76,
  MON_DATA_EARTH_RIBBON: 77,
  MON_DATA_WORLD_RIBBON: 78,
  MON_DATA_UNUSED_RIBBONS: 79,
  MON_DATA_MODERN_FATEFUL_ENCOUNTER: 80,
  MON_DATA_KNOWN_MOVES: 81,
  MON_DATA_RIBBON_COUNT: 82,
  MON_DATA_RIBBONS: 83,
  MON_DATA_ATK2: 84,
  MON_DATA_DEF2: 85,
  MON_DATA_SPEED2: 86,
  MON_DATA_SPATK2: 87,
  MON_DATA_SPDEF2: 88,
} as const;
export const ENUM_MON_1 = {
  MON_SPR_GFX_MODE_NORMAL: 0,
  MON_SPR_GFX_MODE_BATTLE: 1,
  MON_SPR_GFX_MODE_FULL_PARTY: 2,
} as const;
export const ENUM_MON_2 = {
  MON_SPR_GFX_MANAGER_A: 0,
  MON_SPR_GFX_MANAGER_B: 1,
  MON_SPR_GFX_MANAGERS_COUNT: 2,
} as const;

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'ZeroBoxMonData', ret: "void", arity: 1, params: "struct BoxPokemon *boxMon" },
  { name: 'ZeroMonData', ret: "void", arity: 1, params: "struct Pokemon *mon" },
  { name: 'ZeroPlayerPartyMons', ret: "void", arity: 0, params: "void" },
  { name: 'ZeroEnemyPartyMons', ret: "void", arity: 0, params: "void" },
  { name: 'CreateMon', ret: "void", arity: 8, params: "struct Pokemon *mon, u16 species, u8 level, u8 fixedIV, u8 hasFixedPersonality, u32 fixedPersonality, u8 otIdType, u32 fixedOtId" },
  { name: 'CreateBoxMon', ret: "void", arity: 8, params: "struct BoxPokemon *boxMon, u16 species, u8 level, u8 fixedIV, u8 hasFixedPersonality, u32 fixedPersonality, u8 otIdType, u32 fixedOtId" },
  { name: 'CreateMonWithNature', ret: "void", arity: 5, params: "struct Pokemon *mon, u16 species, u8 level, u8 fixedIV, u8 nature" },
  { name: 'CreateMonWithGenderNatureLetter', ret: "void", arity: 7, params: "struct Pokemon *mon, u16 species, u8 level, u8 fixedIV, u8 gender, u8 nature, u8 unownLetter" },
  { name: 'CreateMaleMon', ret: "void", arity: 3, params: "struct Pokemon *mon, u16 species, u8 level" },
  { name: 'CreateMonWithIVsPersonality', ret: "void", arity: 5, params: "struct Pokemon *mon, u16 species, u8 level, u32 ivs, u32 personality" },
  { name: 'CreateMonWithIVsOTID', ret: "void", arity: 5, params: "struct Pokemon *mon, u16 species, u8 level, u8 *ivs, u32 otId" },
  { name: 'CreateMonWithEVSpread', ret: "void", arity: 5, params: "struct Pokemon *mon, u16 species, u8 level, u8 fixedIV, u8 evSpread" },
  { name: 'CreateBattleTowerMon', ret: "void", arity: 2, params: "struct Pokemon *mon, struct BattleTowerPokemon *src" },
  { name: 'CreateBattleTowerMon_HandleLevel', ret: "void", arity: 3, params: "struct Pokemon *mon, struct BattleTowerPokemon *src, bool8 lvl50" },
  { name: 'CreateApprenticeMon', ret: "void", arity: 3, params: "struct Pokemon *mon, const struct Apprentice *src, u8 monId" },
  { name: 'CreateMonWithEVSpreadNatureOTID', ret: "void", arity: 7, params: "struct Pokemon *mon, u16 species, u8 level, u8 nature, u8 fixedIV, u8 evSpread, u32 otId" },
  { name: 'ConvertPokemonToBattleTowerPokemon', ret: "void", arity: 2, params: "struct Pokemon *mon, struct BattleTowerPokemon *dest" },
  { name: 'ShouldIgnoreDeoxysForm', ret: "bool8", arity: 2, params: "u8 caseId, u8 battler" },
  { name: 'SetDeoxysStats', ret: "void", arity: 0, params: "void" },
  { name: 'GetUnionRoomTrainerPic', ret: "u16", arity: 0, params: "void" },
  { name: 'GetUnionRoomTrainerClass', ret: "u16", arity: 0, params: "void" },
  { name: 'CreateEnemyEventMon', ret: "void", arity: 0, params: "void" },
  { name: 'CalculateMonStats', ret: "void", arity: 1, params: "struct Pokemon *mon" },
  { name: 'BoxMonToMon', ret: "void", arity: 2, params: "const struct BoxPokemon *src, struct Pokemon *dest" },
  { name: 'GetLevelFromMonExp', ret: "u8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'GetLevelFromBoxMonExp', ret: "u8", arity: 1, params: "struct BoxPokemon *boxMon" },
  { name: 'GiveMoveToMon', ret: "u16", arity: 2, params: "struct Pokemon *mon, u16 move" },
  { name: 'GiveMoveToBattleMon', ret: "u16", arity: 2, params: "struct BattlePokemon *mon, u16 move" },
  { name: 'SetMonMoveSlot', ret: "void", arity: 3, params: "struct Pokemon *mon, u16 move, u8 slot" },
  { name: 'SetBattleMonMoveSlot', ret: "void", arity: 3, params: "struct BattlePokemon *mon, u16 move, u8 slot" },
  { name: 'GiveMonInitialMoveset', ret: "void", arity: 1, params: "struct Pokemon *mon" },
  { name: 'GiveBoxMonInitialMoveset', ret: "void", arity: 1, params: "struct BoxPokemon *boxMon" },
  { name: 'MonTryLearningNewMove', ret: "u16", arity: 2, params: "struct Pokemon *mon, bool8 firstMove" },
  { name: 'DeleteFirstMoveAndGiveMoveToMon', ret: "void", arity: 2, params: "struct Pokemon *mon, u16 move" },
  { name: 'DeleteFirstMoveAndGiveMoveToBoxMon', ret: "void", arity: 2, params: "struct BoxPokemon *boxMon, u16 move" },
  { name: 'CalculateBaseDamage', ret: "s32", arity: 8, params: "struct BattlePokemon *attacker, struct BattlePokemon *defender, u32 move, u16 sideStatus, u16 powerOverride, u8 typeOverride, u8 battlerIdAtk, u8 battlerIdDef" },
  { name: 'CountAliveMonsInBattle', ret: "u8", arity: 1, params: "u8 caseId" },
  { name: 'GetDefaultMoveTarget', ret: "u8", arity: 1, params: "u8 battler" },
  { name: 'GetMonGender', ret: "u8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'GetBoxMonGender', ret: "u8", arity: 1, params: "struct BoxPokemon *boxMon" },
  { name: 'GetGenderFromSpeciesAndPersonality', ret: "u8", arity: 2, params: "u16 species, u32 personality" },
  { name: 'SetMultiuseSpriteTemplateToPokemon', ret: "void", arity: 2, params: "u16 speciesTag, u8 battlerPosition" },
  { name: 'SetMultiuseSpriteTemplateToTrainerBack', ret: "void", arity: 2, params: "u16 trainerPicId, u8 battlerPosition" },
  { name: 'SetMultiuseSpriteTemplateToTrainerFront', ret: "void", arity: 2, params: "u16 trainerPicId, u8 battlerPosition" },
  { name: 'GetMonData3', ret: "u32", arity: 3, params: "struct Pokemon *mon, s32 field, u8 *data" },
  { name: 'GetMonData2', ret: "u32", arity: 2, params: "struct Pokemon *mon, s32 field" },
  { name: 'GetBoxMonData3', ret: "u32", arity: 3, params: "struct BoxPokemon *boxMon, s32 field, u8 *data" },
  { name: 'GetBoxMonData2', ret: "u32", arity: 2, params: "struct BoxPokemon *boxMon, s32 field" },
  { name: 'SetMonData', ret: "void", arity: 3, params: "struct Pokemon *mon, s32 field, const void *dataArg" },
  { name: 'SetBoxMonData', ret: "void", arity: 3, params: "struct BoxPokemon *boxMon, s32 field, const void *dataArg" },
  { name: 'CopyMon', ret: "void", arity: 3, params: "void *dest, void *src, size_t size" },
  { name: 'GiveMonToPlayer', ret: "u8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'CalculatePlayerPartyCount', ret: "u8", arity: 0, params: "void" },
  { name: 'CalculateEnemyPartyCount', ret: "u8", arity: 0, params: "void" },
  { name: 'GetMonsStateToDoubles', ret: "u8", arity: 0, params: "void" },
  { name: 'GetMonsStateToDoubles_2', ret: "u8", arity: 0, params: "void" },
  { name: 'GetAbilityBySpecies', ret: "u8", arity: 2, params: "u16 species, u8 abilityNum" },
  { name: 'GetMonAbility', ret: "u8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'CreateSecretBaseEnemyParty', ret: "void", arity: 1, params: "struct SecretBase *secretBaseRecord" },
  { name: 'GetSecretBaseTrainerPicIndex', ret: "u8", arity: 0, params: "void" },
  { name: 'GetSecretBaseTrainerClass', ret: "u8", arity: 0, params: "void" },
  { name: 'IsPlayerPartyAndPokemonStorageFull', ret: "bool8", arity: 0, params: "void" },
  { name: 'IsPokemonStorageFull', ret: "bool8", arity: 0, params: "void" },
  { name: 'GetSpeciesName', ret: "void", arity: 2, params: "u8 *name, u16 species" },
  { name: 'CalculatePPWithBonus', ret: "u8", arity: 3, params: "u16 move, u8 ppBonuses, u8 moveIndex" },
  { name: 'RemoveMonPPBonus', ret: "void", arity: 2, params: "struct Pokemon *mon, u8 moveIndex" },
  { name: 'RemoveBattleMonPPBonus', ret: "void", arity: 2, params: "struct BattlePokemon *mon, u8 moveIndex" },
  { name: 'CopyPlayerPartyMonToBattleData', ret: "void", arity: 2, params: "u8 battler, u8 partyIndex" },
  { name: 'ExecuteTableBasedItemEffect', ret: "bool8", arity: 4, params: "struct Pokemon *mon, u16 item, u8 partyIndex, u8 moveIndex" },
  { name: 'PokemonUseItemEffects', ret: "bool8", arity: 5, params: "struct Pokemon *mon, u16 item, u8 partyIndex, u8 moveIndex, bool8 usedByAI" },
  { name: 'HealStatusConditions', ret: "bool8", arity: 4, params: "struct Pokemon *mon, u32 battlePartyId, u32 healMask, u8 battler" },
  { name: 'GetItemEffectParamOffset', ret: "u8", arity: 3, params: "u16 itemId, u8 effectByte, u8 effectBit" },
  { name: 'GetNature', ret: "u8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'GetNatureFromPersonality', ret: "u8", arity: 1, params: "u32 personality" },
  { name: 'GetEvolutionTargetSpecies', ret: "u16", arity: 3, params: "struct Pokemon *mon, u8 mode, u16 evolutionItem" },
  { name: 'HoennPokedexNumToSpecies', ret: "u16", arity: 1, params: "u16 hoennNum" },
  { name: 'NationalPokedexNumToSpecies', ret: "u16", arity: 1, params: "u16 nationalNum" },
  { name: 'NationalToHoennOrder', ret: "u16", arity: 1, params: "u16 nationalNum" },
  { name: 'SpeciesToNationalPokedexNum', ret: "u16", arity: 1, params: "u16 species" },
  { name: 'SpeciesToHoennPokedexNum', ret: "u16", arity: 1, params: "u16 species" },
  { name: 'HoennToNationalOrder', ret: "u16", arity: 1, params: "u16 hoennNum" },
  { name: 'SpeciesToCryId', ret: "u16", arity: 1, params: "u16 species" },
  { name: 'DrawSpindaSpots', ret: "void", arity: 4, params: "u16 species, u32 personality, u8 *dest, bool8 isFrontPic" },
  { name: 'EvolutionRenameMon', ret: "void", arity: 3, params: "struct Pokemon *mon, u16 oldSpecies, u16 newSpecies" },
  { name: 'GetPlayerFlankId', ret: "u8", arity: 0, params: "void" },
  { name: 'GetLinkTrainerFlankId', ret: "u16", arity: 1, params: "u8 linkPlayerId" },
  { name: 'GetBattlerMultiplayerId', ret: "s32", arity: 1, params: "u16 id" },
  { name: 'GetTrainerEncounterMusicId', ret: "u8", arity: 1, params: "u16 trainerOpponentId" },
  { name: 'ModifyStatByNature', ret: "u16", arity: 3, params: "u8 nature, u16 stat, u8 statIndex" },
  { name: 'AdjustFriendship', ret: "void", arity: 2, params: "struct Pokemon *mon, u8 event" },
  { name: 'MonGainEVs', ret: "void", arity: 2, params: "struct Pokemon *mon, u16 defeatedSpecies" },
  { name: 'GetMonEVCount', ret: "u16", arity: 1, params: "struct Pokemon *mon" },
  { name: 'RandomlyGivePartyPokerus', ret: "void", arity: 1, params: "struct Pokemon *party" },
  { name: 'CheckPartyPokerus', ret: "u8", arity: 2, params: "struct Pokemon *party, u8 selection" },
  { name: 'CheckPartyHasHadPokerus', ret: "u8", arity: 2, params: "struct Pokemon *party, u8 selection" },
  { name: 'UpdatePartyPokerusTime', ret: "void", arity: 1, params: "u16 days" },
  { name: 'PartySpreadPokerus', ret: "void", arity: 1, params: "struct Pokemon *party" },
  { name: 'TryIncrementMonLevel', ret: "bool8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'CanMonLearnTMHM', ret: "u32", arity: 2, params: "struct Pokemon *mon, u8 tm" },
  { name: 'CanSpeciesLearnTMHM', ret: "u32", arity: 2, params: "u16 species, u8 tm" },
  { name: 'GetMoveRelearnerMoves', ret: "u8", arity: 2, params: "struct Pokemon *mon, u16 *moves" },
  { name: 'GetLevelUpMovesBySpecies', ret: "u8", arity: 2, params: "u16 species, u16 *moves" },
  { name: 'GetNumberOfRelearnableMoves', ret: "u8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'SpeciesToPokedexNum', ret: "u16", arity: 1, params: "u16 species" },
  { name: 'IsSpeciesInHoennDex', ret: "bool32", arity: 1, params: "u16 species" },
  { name: 'ClearBattleMonForms', ret: "void", arity: 0, params: "void" },
  { name: 'GetBattleBGM', ret: "u16", arity: 0, params: "void" },
  { name: 'PlayBattleBGM', ret: "void", arity: 0, params: "void" },
  { name: 'PlayMapChosenOrBattleBGM', ret: "void", arity: 1, params: "u16 songId" },
  { name: 'CreateTask_PlayMapChosenOrBattleBGM', ret: "void", arity: 1, params: "u16 songId" },
  { name: 'IsHMMove2', ret: "bool32", arity: 1, params: "u16 move" },
  { name: 'IsMonSpriteNotFlipped', ret: "bool8", arity: 1, params: "u16 species" },
  { name: 'GetMonFlavorRelation', ret: "s8", arity: 2, params: "struct Pokemon *mon, u8 flavor" },
  { name: 'GetFlavorRelationByPersonality', ret: "s8", arity: 2, params: "u32 personality, u8 flavor" },
  { name: 'IsTradedMon', ret: "bool8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'IsOtherTrainer', ret: "bool8", arity: 2, params: "u32 otId, u8 *otName" },
  { name: 'MonRestorePP', ret: "void", arity: 1, params: "struct Pokemon *mon" },
  { name: 'BoxMonRestorePP', ret: "void", arity: 1, params: "struct BoxPokemon *boxMon" },
  { name: 'SetMonPreventsSwitchingString', ret: "void", arity: 0, params: "void" },
  { name: 'SetWildMonHeldItem', ret: "void", arity: 0, params: "void" },
  { name: 'IsMonShiny', ret: "bool8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'IsShinyOtIdPersonality', ret: "bool8", arity: 2, params: "u32 otId, u32 personality" },
  { name: 'BattleAnimateFrontSprite', ret: "void", arity: 4, params: "struct Sprite *sprite, u16 species, bool8 noCry, u8 panMode" },
  { name: 'DoMonFrontSpriteAnimation', ret: "void", arity: 4, params: "struct Sprite *sprite, u16 species, bool8 noCry, u8 panModeAnimFlag" },
  { name: 'PokemonSummaryDoMonAnimation', ret: "void", arity: 3, params: "struct Sprite *sprite, u16 species, bool8 oneFrame" },
  { name: 'StopPokemonAnimationDelayTask', ret: "void", arity: 0, params: "void" },
  { name: 'BattleAnimateBackSprite', ret: "void", arity: 2, params: "struct Sprite *sprite, u16 species" },
  { name: 'GetOpposingLinkMultiBattlerId', ret: "u8", arity: 2, params: "bool8 rightSide, u8 multiplayerId" },
  { name: 'FacilityClassToPicIndex', ret: "u16", arity: 1, params: "u16 facilityClass" },
  { name: 'PlayerGenderToFrontTrainerPicId', ret: "u16", arity: 1, params: "u8 playerGender" },
  { name: 'HandleSetPokedexFlag', ret: "void", arity: 3, params: "u16 nationalNum, u8 caseId, u32 personality" },
  { name: 'HasTwoFramesAnimation', ret: "bool8", arity: 1, params: "u16 species" },
  { name: 'DestroyMonSpritesGfxManager', ret: "void", arity: 1, params: "u8 managerId" },
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'sprite.h',
] as const;
