// AUTO-GENERATED from include/tv.h by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/include/tv.h
// Generated: 2026-04-26

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'ClearTVShowData', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutBreakingNewsOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutBattleSeminarOnAir', ret: "void", arity: 5, params: "u16 foeSpecies, u16 species, u8 moveIndex, const u16 *movePtr, u16 betterMove" },
  { name: 'TryPutFrontierTVShowOnAir', ret: "void", arity: 2, params: "u16 winStreak, u8 facilityAndMode" },
  { name: 'DoTVShow', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowInSearchOfTrainers', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutTreasureInvestigatorsOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutLotteryWinnerReportOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutTrainerFanClubOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyPlantedBerries', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyPickedBerries', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyBattlePoints', ret: "void", arity: 1, params: "u16 delta" },
  { name: 'HideBattleTowerReporter', ret: "void", arity: 0, params: "void" },
  { name: 'ReceiveTvShowsData', ret: "void", arity: 3, params: "void *src, u32 size, u8 playersLinkId" },
  { name: 'TryPutSpotTheCutiesOnAir', ret: "void", arity: 2, params: "struct Pokemon *pokemon, u8 ribbonMonDataIdx" },
  { name: 'GetPlayerIDAsU32', ret: "u32", arity: 0, params: "void" },
  { name: 'IsPokeNewsActive', ret: "bool8", arity: 1, params: "u8 newsKind" },
  { name: 'SanitizeTVShowLocationsForRuby', ret: "void", arity: 1, params: "TVShow *shows" },
  { name: 'CountDigits', ret: "size_t", arity: 1, params: "int value" },
  { name: 'GetRibbonCount', ret: "u8", arity: 1, params: "struct Pokemon *pokemon" },
  { name: 'AlertTVThatPlayerPlayedSlotMachine', ret: "void", arity: 1, params: "u16 nCoinsSpent" },
  { name: 'AlertTVThatPlayerPlayedRoulette', ret: "void", arity: 1, params: "u16 nCoinsSpent" },
  { name: 'TryPutFindThatGamerOnAir', ret: "void", arity: 1, params: "u16 nCoinsPaidOut" },
  { name: 'TryPutSecretBaseSecretsOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutTodaysRivalTrainerOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutTrendWatcherOnAir', ret: "void", arity: 1, params: "const u16 *words" },
  { name: 'ReceivePokeNewsData', ret: "void", arity: 3, params: "void *src, u32 size, u8 playersLinkId" },
  { name: 'DeactivateAllNormalTVShows', ret: "void", arity: 0, params: "void" },
  { name: 'RecordFishingAttemptForTV', ret: "void", arity: 1, params: "bool8 caughtFish" },
  { name: 'IncrementDailySlotsUses', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyRouletteUses', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyWildBattles', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyBerryBlender', ret: "void", arity: 0, params: "void" },
  { name: 'SanitizeTVShowsForRuby', ret: "void", arity: 1, params: "TVShow *shows" },
  { name: 'TryPutSafariFanClubOnAir', ret: "void", arity: 2, params: "u8 monsCaught, u8 pokeblocksUsed" },
  { name: 'Put3CheersForPokeblocksOnTheAir', ret: "bool8", arity: 5, params: "const u8 *partnersName, u8 flavor, u8 color, u8 sheen, u8 language" },
  { name: 'SetPokemonAnglerSpecies', ret: "void", arity: 1, params: "u16 species" },
  { name: 'UpdateTVShowsPerDay', ret: "void", arity: 1, params: "u16 days" },
  { name: 'TryPutPokemonTodayOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutSecretBaseVisitOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'PutBattleUpdateOnTheAir', ret: "void", arity: 4, params: "u8 opponentLinkPlayerId, u16 move, u16 speciesPlayer, u16 speciesOpponent" },
  { name: 'BravoTrainerPokemonProfile_BeforeInterview1', ret: "void", arity: 1, params: "u16 move" },
  { name: 'InterviewBefore', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewAfter', ret: "void", arity: 0, params: "void" },
  { name: 'UpdateTVScreensOnMap', ret: "void", arity: 2, params: "int width, int height" },
  { name: 'ConvertIntToDecimalString', ret: "void", arity: 2, params: "u8 varIdx, int value" },
  { name: 'TryPutSmartShopperOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'ShouldAirFrontierTVShow', ret: "bool8", arity: 0, params: "void" },
  { name: 'BravoTrainerPokemonProfile_BeforeInterview2', ret: "void", arity: 1, params: "u8 contestStandingPlace" },
  { name: 'ContestLiveUpdates_Init', ret: "void", arity: 1, params: "u8 round1Placing" },
  { name: 'ContestLiveUpdates_SetRound2Placing', ret: "void", arity: 1, params: "u8 round2Placing" },
  { name: 'ContestLiveUpdates_SetWinnerAppealFlag', ret: "void", arity: 1, params: "u8 flag" },
  { name: 'ContestLiveUpdates_SetWinnerMoveUsed', ret: "void", arity: 1, params: "u16 move" },
  { name: 'ContestLiveUpdates_SetLoserData', ret: "void", arity: 2, params: "u8 flag, u8 loser" },
  { name: 'ResetGabbyAndTy', ret: "void", arity: 0, params: "void" },
  { name: 'CheckForPlayersHouseNews', ret: "u8", arity: 0, params: "void" },
  { name: 'IsGabbyAndTyShowOnTheAir', ret: "bool8", arity: 0, params: "void" },
] as const;
