// Porté 1:1 (généré via scripts/gen-reset-all-berries.cjs) depuis :
//   D:/Projet 1/decomps/pokeemeraude/data/scripts/new_game.inc
//   (EventScript_ResetAllBerries — les baies initiales d'une save fraîche).
// Le type de baie = ITEM_TO_BERRY(ITEM_X_BERRY) est résolu en number à la
// génération (= val items.h - FIRST_BERRY_INDEX + 1) ; l'item d'origine est en
// commentaire. Évite toute dépendance à decomp-bridge (= zéro risque de cycle TDZ).
// Re-générer : node scripts/gen-reset-all-berries.cjs

import { PlantBerryTree } from '../pokemon/berry';
import {
  BERRY_STAGE_BERRIES,
  BERRY_TREE_ROUTE_102_ORAN,
  BERRY_TREE_ROUTE_102_PECHA,
  BERRY_TREE_ROUTE_104_ORAN_2,
  BERRY_TREE_ROUTE_104_PECHA,
  BERRY_TREE_ROUTE_104_ORAN_1,
  BERRY_TREE_ROUTE_104_CHERI_2,
  BERRY_TREE_ROUTE_104_CHERI_1,
  BERRY_TREE_ROUTE_104_LEPPA,
  BERRY_TREE_ROUTE_116_PINAP_1,
  BERRY_TREE_ROUTE_116_CHESTO_1,
  BERRY_TREE_ROUTE_116_CHESTO_2,
  BERRY_TREE_ROUTE_116_PINAP_2,
  BERRY_TREE_ROUTE_115_KELPSY_1,
  BERRY_TREE_ROUTE_115_KELPSY_2,
  BERRY_TREE_ROUTE_115_KELPSY_3,
  BERRY_TREE_ROUTE_115_BLUK_1,
  BERRY_TREE_ROUTE_115_BLUK_2,
  BERRY_TREE_ROUTE_103_CHERI_1,
  BERRY_TREE_ROUTE_103_LEPPA,
  BERRY_TREE_ROUTE_103_CHERI_2,
  BERRY_TREE_ROUTE_110_NANAB_1,
  BERRY_TREE_ROUTE_110_NANAB_2,
  BERRY_TREE_ROUTE_110_NANAB_3,
  BERRY_TREE_ROUTE_117_WEPEAR_3,
  BERRY_TREE_ROUTE_117_WEPEAR_2,
  BERRY_TREE_ROUTE_117_WEPEAR_1,
  BERRY_TREE_ROUTE_112_RAWST_2,
  BERRY_TREE_ROUTE_112_PECHA_2,
  BERRY_TREE_ROUTE_112_PECHA_1,
  BERRY_TREE_ROUTE_112_RAWST_1,
  BERRY_TREE_ROUTE_111_RAZZ_1,
  BERRY_TREE_ROUTE_111_RAZZ_2,
  BERRY_TREE_ROUTE_111_ORAN_1,
  BERRY_TREE_ROUTE_111_ORAN_2,
  BERRY_TREE_ROUTE_114_PERSIM_2,
  BERRY_TREE_ROUTE_114_PERSIM_3,
  BERRY_TREE_ROUTE_114_PERSIM_1,
  BERRY_TREE_ROUTE_118_SITRUS_1,
  BERRY_TREE_ROUTE_118_SITRUS_2,
  BERRY_TREE_ROUTE_119_POMEG_1,
  BERRY_TREE_ROUTE_119_POMEG_2,
  BERRY_TREE_ROUTE_119_POMEG_3,
  BERRY_TREE_ROUTE_119_HONDEW_1,
  BERRY_TREE_ROUTE_119_HONDEW_2,
  BERRY_TREE_ROUTE_119_SITRUS,
  BERRY_TREE_ROUTE_119_LEPPA,
  BERRY_TREE_ROUTE_120_ASPEAR_1,
  BERRY_TREE_ROUTE_120_ASPEAR_2,
  BERRY_TREE_ROUTE_120_ASPEAR_3,
  BERRY_TREE_ROUTE_120_PECHA_1,
  BERRY_TREE_ROUTE_120_PECHA_2,
  BERRY_TREE_ROUTE_120_PECHA_3,
  BERRY_TREE_ROUTE_120_WEPEAR,
  BERRY_TREE_ROUTE_120_PINAP,
  BERRY_TREE_ROUTE_120_NANAB,
  BERRY_TREE_ROUTE_120_RAZZ,
  BERRY_TREE_ROUTE_121_PERSIM,
  BERRY_TREE_ROUTE_121_ASPEAR,
  BERRY_TREE_ROUTE_121_RAWST,
  BERRY_TREE_ROUTE_121_CHESTO,
  BERRY_TREE_ROUTE_121_NANAB_1,
  BERRY_TREE_ROUTE_121_NANAB_2,
  BERRY_TREE_ROUTE_123_LEPPA_1,
  BERRY_TREE_ROUTE_123_LEPPA_2,
  BERRY_TREE_ROUTE_123_POMEG_3,
  BERRY_TREE_ROUTE_123_POMEG_4,
  BERRY_TREE_ROUTE_123_GREPA_1,
  BERRY_TREE_ROUTE_123_GREPA_2,
  BERRY_TREE_ROUTE_123_QUALOT_4,
  BERRY_TREE_ROUTE_123_QUALOT_1,
  BERRY_TREE_ROUTE_123_POMEG_1,
  BERRY_TREE_ROUTE_123_POMEG_2,
  BERRY_TREE_ROUTE_123_GREPA_3,
  BERRY_TREE_ROUTE_123_GREPA_4,
  BERRY_TREE_ROUTE_123_QUALOT_2,
  BERRY_TREE_ROUTE_123_QUALOT_3,
  BERRY_TREE_ROUTE_123_PECHA,
  BERRY_TREE_ROUTE_123_SITRUS,
  BERRY_TREE_ROUTE_123_RAWST,
  BERRY_TREE_ROUTE_130_LIECHI,
} from '../decomp-data/include/constants/berry-data';

/** Table 1:1 EventScript_ResetAllBerries : [berryTreeId, berryType, stade].
 *  berryType = ITEM_TO_BERRY(item) résolu à la génération (item en commentaire). */
const sResetAllBerries: ReadonlyArray<readonly [number, number, number]> = [
  [BERRY_TREE_ROUTE_102_ORAN, 7, BERRY_STAGE_BERRIES], // ITEM_ORAN_BERRY
  [BERRY_TREE_ROUTE_102_PECHA, 3, BERRY_STAGE_BERRIES], // ITEM_PECHA_BERRY
  [BERRY_TREE_ROUTE_104_ORAN_2, 7, BERRY_STAGE_BERRIES], // ITEM_ORAN_BERRY
  [BERRY_TREE_ROUTE_104_PECHA, 3, BERRY_STAGE_BERRIES], // ITEM_PECHA_BERRY
  [BERRY_TREE_ROUTE_104_ORAN_1, 7, BERRY_STAGE_BERRIES], // ITEM_ORAN_BERRY
  [BERRY_TREE_ROUTE_104_CHERI_2, 1, BERRY_STAGE_BERRIES], // ITEM_CHERI_BERRY
  [BERRY_TREE_ROUTE_104_CHERI_1, 1, BERRY_STAGE_BERRIES], // ITEM_CHERI_BERRY
  [BERRY_TREE_ROUTE_104_LEPPA, 6, BERRY_STAGE_BERRIES], // ITEM_LEPPA_BERRY
  [BERRY_TREE_ROUTE_116_PINAP_1, 20, BERRY_STAGE_BERRIES], // ITEM_PINAP_BERRY
  [BERRY_TREE_ROUTE_116_CHESTO_1, 2, BERRY_STAGE_BERRIES], // ITEM_CHESTO_BERRY
  [BERRY_TREE_ROUTE_116_CHESTO_2, 2, BERRY_STAGE_BERRIES], // ITEM_CHESTO_BERRY
  [BERRY_TREE_ROUTE_116_PINAP_2, 20, BERRY_STAGE_BERRIES], // ITEM_PINAP_BERRY
  [BERRY_TREE_ROUTE_115_KELPSY_1, 22, BERRY_STAGE_BERRIES], // ITEM_KELPSY_BERRY
  [BERRY_TREE_ROUTE_115_KELPSY_2, 22, BERRY_STAGE_BERRIES], // ITEM_KELPSY_BERRY
  [BERRY_TREE_ROUTE_115_KELPSY_3, 22, BERRY_STAGE_BERRIES], // ITEM_KELPSY_BERRY
  [BERRY_TREE_ROUTE_115_BLUK_1, 17, BERRY_STAGE_BERRIES], // ITEM_BLUK_BERRY
  [BERRY_TREE_ROUTE_115_BLUK_2, 17, BERRY_STAGE_BERRIES], // ITEM_BLUK_BERRY
  [BERRY_TREE_ROUTE_103_CHERI_1, 1, BERRY_STAGE_BERRIES], // ITEM_CHERI_BERRY
  [BERRY_TREE_ROUTE_103_LEPPA, 6, BERRY_STAGE_BERRIES], // ITEM_LEPPA_BERRY
  [BERRY_TREE_ROUTE_103_CHERI_2, 1, BERRY_STAGE_BERRIES], // ITEM_CHERI_BERRY
  [BERRY_TREE_ROUTE_110_NANAB_1, 18, BERRY_STAGE_BERRIES], // ITEM_NANAB_BERRY
  [BERRY_TREE_ROUTE_110_NANAB_2, 18, BERRY_STAGE_BERRIES], // ITEM_NANAB_BERRY
  [BERRY_TREE_ROUTE_110_NANAB_3, 18, BERRY_STAGE_BERRIES], // ITEM_NANAB_BERRY
  [BERRY_TREE_ROUTE_117_WEPEAR_3, 19, BERRY_STAGE_BERRIES], // ITEM_WEPEAR_BERRY
  [BERRY_TREE_ROUTE_117_WEPEAR_2, 19, BERRY_STAGE_BERRIES], // ITEM_WEPEAR_BERRY
  [BERRY_TREE_ROUTE_117_WEPEAR_1, 19, BERRY_STAGE_BERRIES], // ITEM_WEPEAR_BERRY
  [BERRY_TREE_ROUTE_112_RAWST_2, 4, BERRY_STAGE_BERRIES], // ITEM_RAWST_BERRY
  [BERRY_TREE_ROUTE_112_PECHA_2, 3, BERRY_STAGE_BERRIES], // ITEM_PECHA_BERRY
  [BERRY_TREE_ROUTE_112_PECHA_1, 3, BERRY_STAGE_BERRIES], // ITEM_PECHA_BERRY
  [BERRY_TREE_ROUTE_112_RAWST_1, 4, BERRY_STAGE_BERRIES], // ITEM_RAWST_BERRY
  [BERRY_TREE_ROUTE_111_RAZZ_1, 16, BERRY_STAGE_BERRIES], // ITEM_RAZZ_BERRY
  [BERRY_TREE_ROUTE_111_RAZZ_2, 16, BERRY_STAGE_BERRIES], // ITEM_RAZZ_BERRY
  [BERRY_TREE_ROUTE_111_ORAN_1, 7, BERRY_STAGE_BERRIES], // ITEM_ORAN_BERRY
  [BERRY_TREE_ROUTE_111_ORAN_2, 7, BERRY_STAGE_BERRIES], // ITEM_ORAN_BERRY
  [BERRY_TREE_ROUTE_114_PERSIM_2, 8, BERRY_STAGE_BERRIES], // ITEM_PERSIM_BERRY
  [BERRY_TREE_ROUTE_114_PERSIM_3, 8, BERRY_STAGE_BERRIES], // ITEM_PERSIM_BERRY
  [BERRY_TREE_ROUTE_114_PERSIM_1, 8, BERRY_STAGE_BERRIES], // ITEM_PERSIM_BERRY
  [BERRY_TREE_ROUTE_118_SITRUS_1, 10, BERRY_STAGE_BERRIES], // ITEM_SITRUS_BERRY
  [BERRY_TREE_ROUTE_118_SITRUS_2, 10, BERRY_STAGE_BERRIES], // ITEM_SITRUS_BERRY
  [BERRY_TREE_ROUTE_119_POMEG_1, 21, BERRY_STAGE_BERRIES], // ITEM_POMEG_BERRY
  [BERRY_TREE_ROUTE_119_POMEG_2, 21, BERRY_STAGE_BERRIES], // ITEM_POMEG_BERRY
  [BERRY_TREE_ROUTE_119_POMEG_3, 21, BERRY_STAGE_BERRIES], // ITEM_POMEG_BERRY
  [BERRY_TREE_ROUTE_119_HONDEW_1, 24, BERRY_STAGE_BERRIES], // ITEM_HONDEW_BERRY
  [BERRY_TREE_ROUTE_119_HONDEW_2, 24, BERRY_STAGE_BERRIES], // ITEM_HONDEW_BERRY
  [BERRY_TREE_ROUTE_119_SITRUS, 10, BERRY_STAGE_BERRIES], // ITEM_SITRUS_BERRY
  [BERRY_TREE_ROUTE_119_LEPPA, 6, BERRY_STAGE_BERRIES], // ITEM_LEPPA_BERRY
  [BERRY_TREE_ROUTE_120_ASPEAR_1, 5, BERRY_STAGE_BERRIES], // ITEM_ASPEAR_BERRY
  [BERRY_TREE_ROUTE_120_ASPEAR_2, 5, BERRY_STAGE_BERRIES], // ITEM_ASPEAR_BERRY
  [BERRY_TREE_ROUTE_120_ASPEAR_3, 5, BERRY_STAGE_BERRIES], // ITEM_ASPEAR_BERRY
  [BERRY_TREE_ROUTE_120_PECHA_1, 3, BERRY_STAGE_BERRIES], // ITEM_PECHA_BERRY
  [BERRY_TREE_ROUTE_120_PECHA_2, 3, BERRY_STAGE_BERRIES], // ITEM_PECHA_BERRY
  [BERRY_TREE_ROUTE_120_PECHA_3, 3, BERRY_STAGE_BERRIES], // ITEM_PECHA_BERRY
  [BERRY_TREE_ROUTE_120_WEPEAR, 19, BERRY_STAGE_BERRIES], // ITEM_WEPEAR_BERRY
  [BERRY_TREE_ROUTE_120_PINAP, 20, BERRY_STAGE_BERRIES], // ITEM_PINAP_BERRY
  [BERRY_TREE_ROUTE_120_NANAB, 18, BERRY_STAGE_BERRIES], // ITEM_NANAB_BERRY
  [BERRY_TREE_ROUTE_120_RAZZ, 16, BERRY_STAGE_BERRIES], // ITEM_RAZZ_BERRY
  [BERRY_TREE_ROUTE_121_PERSIM, 8, BERRY_STAGE_BERRIES], // ITEM_PERSIM_BERRY
  [BERRY_TREE_ROUTE_121_ASPEAR, 5, BERRY_STAGE_BERRIES], // ITEM_ASPEAR_BERRY
  [BERRY_TREE_ROUTE_121_RAWST, 4, BERRY_STAGE_BERRIES], // ITEM_RAWST_BERRY
  [BERRY_TREE_ROUTE_121_CHESTO, 2, BERRY_STAGE_BERRIES], // ITEM_CHESTO_BERRY
  [BERRY_TREE_ROUTE_121_NANAB_1, 18, BERRY_STAGE_BERRIES], // ITEM_NANAB_BERRY
  [BERRY_TREE_ROUTE_121_NANAB_2, 18, BERRY_STAGE_BERRIES], // ITEM_NANAB_BERRY
  [BERRY_TREE_ROUTE_123_LEPPA_1, 6, BERRY_STAGE_BERRIES], // ITEM_LEPPA_BERRY
  [BERRY_TREE_ROUTE_123_LEPPA_2, 6, BERRY_STAGE_BERRIES], // ITEM_LEPPA_BERRY
  [BERRY_TREE_ROUTE_123_POMEG_3, 21, BERRY_STAGE_BERRIES], // ITEM_POMEG_BERRY
  [BERRY_TREE_ROUTE_123_POMEG_4, 21, BERRY_STAGE_BERRIES], // ITEM_POMEG_BERRY
  [BERRY_TREE_ROUTE_123_GREPA_1, 25, BERRY_STAGE_BERRIES], // ITEM_GREPA_BERRY
  [BERRY_TREE_ROUTE_123_GREPA_2, 25, BERRY_STAGE_BERRIES], // ITEM_GREPA_BERRY
  [BERRY_TREE_ROUTE_123_QUALOT_4, 23, BERRY_STAGE_BERRIES], // ITEM_QUALOT_BERRY
  [BERRY_TREE_ROUTE_123_QUALOT_1, 23, BERRY_STAGE_BERRIES], // ITEM_QUALOT_BERRY
  [BERRY_TREE_ROUTE_123_POMEG_1, 21, BERRY_STAGE_BERRIES], // ITEM_POMEG_BERRY
  [BERRY_TREE_ROUTE_123_POMEG_2, 21, BERRY_STAGE_BERRIES], // ITEM_POMEG_BERRY
  [BERRY_TREE_ROUTE_123_GREPA_3, 25, BERRY_STAGE_BERRIES], // ITEM_GREPA_BERRY
  [BERRY_TREE_ROUTE_123_GREPA_4, 25, BERRY_STAGE_BERRIES], // ITEM_GREPA_BERRY
  [BERRY_TREE_ROUTE_123_QUALOT_2, 23, BERRY_STAGE_BERRIES], // ITEM_QUALOT_BERRY
  [BERRY_TREE_ROUTE_123_QUALOT_3, 23, BERRY_STAGE_BERRIES], // ITEM_QUALOT_BERRY
  [BERRY_TREE_ROUTE_123_PECHA, 3, BERRY_STAGE_BERRIES], // ITEM_PECHA_BERRY
  [BERRY_TREE_ROUTE_123_SITRUS, 10, BERRY_STAGE_BERRIES], // ITEM_SITRUS_BERRY
  [BERRY_TREE_ROUTE_123_RAWST, 4, BERRY_STAGE_BERRIES], // ITEM_RAWST_BERRY
  [BERRY_TREE_ROUTE_130_LIECHI, 36, BERRY_STAGE_BERRIES], // ITEM_LIECHI_BERRY
];

/** 1:1 décomp `EventScript_ResetAllBerries` (appelé en fin de
 *  EventScript_ResetAllMapFlags au new game) : plante les baies fixes
 *  initiales via setberrytree → PlantBerryTree(id, berry, stage, FALSE). */
export function ResetAllBerries(): void {
  for (const [treeId, berry, stage] of sResetAllBerries) {
    // 1:1 décomp ScrCmd_setberrytree : PlantBerryTree(treeId, berry, stage, FALSE).
    PlantBerryTree(treeId, berry, stage, false);
  }
}
