// AUTO-GENERATED from include/constants/event_object_movement.h by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/include/constants/event_object_movement.h
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
export const MOVEMENT_TYPE_NONE = 0;
export const MOVEMENT_TYPE_LOOK_AROUND = 1;
export const MOVEMENT_TYPE_WANDER_AROUND = 2;
export const MOVEMENT_TYPE_WANDER_UP_AND_DOWN = 3;
export const MOVEMENT_TYPE_WANDER_DOWN_AND_UP = 4;
export const MOVEMENT_TYPE_WANDER_LEFT_AND_RIGHT = 5;
export const MOVEMENT_TYPE_WANDER_RIGHT_AND_LEFT = 6;
export const MOVEMENT_TYPE_FACE_UP = 7;
export const MOVEMENT_TYPE_FACE_DOWN = 8;
export const MOVEMENT_TYPE_FACE_LEFT = 9;
export const MOVEMENT_TYPE_FACE_RIGHT = 10;
export const MOVEMENT_TYPE_PLAYER = 11;
export const MOVEMENT_TYPE_BERRY_TREE_GROWTH = 12;
export const MOVEMENT_TYPE_FACE_DOWN_AND_UP = 13;
export const MOVEMENT_TYPE_FACE_LEFT_AND_RIGHT = 14;
export const MOVEMENT_TYPE_FACE_UP_AND_LEFT = 15;
export const MOVEMENT_TYPE_FACE_UP_AND_RIGHT = 16;
export const MOVEMENT_TYPE_FACE_DOWN_AND_LEFT = 17;
export const MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT = 18;
export const MOVEMENT_TYPE_FACE_DOWN_UP_AND_LEFT = 19;
export const MOVEMENT_TYPE_FACE_DOWN_UP_AND_RIGHT = 20;
export const MOVEMENT_TYPE_FACE_UP_LEFT_AND_RIGHT = 21;
export const MOVEMENT_TYPE_FACE_DOWN_LEFT_AND_RIGHT = 22;
export const MOVEMENT_TYPE_ROTATE_COUNTERCLOCKWISE = 23;
export const MOVEMENT_TYPE_ROTATE_CLOCKWISE = 24;
export const MOVEMENT_TYPE_WALK_UP_AND_DOWN = 25;
export const MOVEMENT_TYPE_WALK_DOWN_AND_UP = 26;
export const MOVEMENT_TYPE_WALK_LEFT_AND_RIGHT = 27;
export const MOVEMENT_TYPE_WALK_RIGHT_AND_LEFT = 28;
export const MOVEMENT_TYPE_WALK_SEQUENCE_UP_RIGHT_LEFT_DOWN = 29;
export const MOVEMENT_TYPE_WALK_SEQUENCE_RIGHT_LEFT_DOWN_UP = 30;
export const MOVEMENT_TYPE_WALK_SEQUENCE_DOWN_UP_RIGHT_LEFT = 31;
export const MOVEMENT_TYPE_WALK_SEQUENCE_LEFT_DOWN_UP_RIGHT = 32;
export const MOVEMENT_TYPE_WALK_SEQUENCE_UP_LEFT_RIGHT_DOWN = 33;
export const MOVEMENT_TYPE_WALK_SEQUENCE_LEFT_RIGHT_DOWN_UP = 34;
export const MOVEMENT_TYPE_WALK_SEQUENCE_DOWN_UP_LEFT_RIGHT = 35;
export const MOVEMENT_TYPE_WALK_SEQUENCE_RIGHT_DOWN_UP_LEFT = 36;
export const MOVEMENT_TYPE_WALK_SEQUENCE_LEFT_UP_DOWN_RIGHT = 37;
export const MOVEMENT_TYPE_WALK_SEQUENCE_UP_DOWN_RIGHT_LEFT = 38;
export const MOVEMENT_TYPE_WALK_SEQUENCE_RIGHT_LEFT_UP_DOWN = 39;
export const MOVEMENT_TYPE_WALK_SEQUENCE_DOWN_RIGHT_LEFT_UP = 40;
export const MOVEMENT_TYPE_WALK_SEQUENCE_RIGHT_UP_DOWN_LEFT = 41;
export const MOVEMENT_TYPE_WALK_SEQUENCE_UP_DOWN_LEFT_RIGHT = 42;
export const MOVEMENT_TYPE_WALK_SEQUENCE_LEFT_RIGHT_UP_DOWN = 43;
export const MOVEMENT_TYPE_WALK_SEQUENCE_DOWN_LEFT_RIGHT_UP = 44;
export const MOVEMENT_TYPE_WALK_SEQUENCE_UP_LEFT_DOWN_RIGHT = 45;
export const MOVEMENT_TYPE_WALK_SEQUENCE_DOWN_RIGHT_UP_LEFT = 46;
export const MOVEMENT_TYPE_WALK_SEQUENCE_LEFT_DOWN_RIGHT_UP = 47;
export const MOVEMENT_TYPE_WALK_SEQUENCE_RIGHT_UP_LEFT_DOWN = 48;
export const MOVEMENT_TYPE_WALK_SEQUENCE_UP_RIGHT_DOWN_LEFT = 49;
export const MOVEMENT_TYPE_WALK_SEQUENCE_DOWN_LEFT_UP_RIGHT = 50;
export const MOVEMENT_TYPE_WALK_SEQUENCE_LEFT_UP_RIGHT_DOWN = 51;
export const MOVEMENT_TYPE_WALK_SEQUENCE_RIGHT_DOWN_LEFT_UP = 52;
export const MOVEMENT_TYPE_COPY_PLAYER = 53;
export const MOVEMENT_TYPE_COPY_PLAYER_OPPOSITE = 54;
export const MOVEMENT_TYPE_COPY_PLAYER_COUNTERCLOCKWISE = 55;
export const MOVEMENT_TYPE_COPY_PLAYER_CLOCKWISE = 56;
export const MOVEMENT_TYPE_TREE_DISGUISE = 57;
export const MOVEMENT_TYPE_MOUNTAIN_DISGUISE = 58;
export const MOVEMENT_TYPE_COPY_PLAYER_IN_GRASS = 59;
export const MOVEMENT_TYPE_COPY_PLAYER_OPPOSITE_IN_GRASS = 60;
export const MOVEMENT_TYPE_COPY_PLAYER_COUNTERCLOCKWISE_IN_GRASS = 61;
export const MOVEMENT_TYPE_COPY_PLAYER_CLOCKWISE_IN_GRASS = 62;
export const MOVEMENT_TYPE_BURIED = 63;
export const MOVEMENT_TYPE_WALK_IN_PLACE_DOWN = 64;
export const MOVEMENT_TYPE_WALK_IN_PLACE_UP = 65;
export const MOVEMENT_TYPE_WALK_IN_PLACE_LEFT = 66;
export const MOVEMENT_TYPE_WALK_IN_PLACE_RIGHT = 67;
export const MOVEMENT_TYPE_JOG_IN_PLACE_DOWN = 68;
export const MOVEMENT_TYPE_JOG_IN_PLACE_UP = 69;
export const MOVEMENT_TYPE_JOG_IN_PLACE_LEFT = 70;
export const MOVEMENT_TYPE_JOG_IN_PLACE_RIGHT = 71;
export const MOVEMENT_TYPE_RUN_IN_PLACE_DOWN = 72;
export const MOVEMENT_TYPE_RUN_IN_PLACE_UP = 73;
export const MOVEMENT_TYPE_RUN_IN_PLACE_LEFT = 74;
export const MOVEMENT_TYPE_RUN_IN_PLACE_RIGHT = 75;
export const MOVEMENT_TYPE_INVISIBLE = 76;
export const MOVEMENT_TYPE_WALK_SLOWLY_IN_PLACE_DOWN = 77;
export const MOVEMENT_TYPE_WALK_SLOWLY_IN_PLACE_UP = 78;
export const MOVEMENT_TYPE_WALK_SLOWLY_IN_PLACE_LEFT = 79;
export const MOVEMENT_TYPE_WALK_SLOWLY_IN_PLACE_RIGHT = 80;
export const NUM_MOVEMENT_TYPES = 81;
export const MOVEMENT_ACTION_FACE_DOWN = 0;
export const MOVEMENT_ACTION_FACE_UP = 1;
export const MOVEMENT_ACTION_FACE_LEFT = 2;
export const MOVEMENT_ACTION_FACE_RIGHT = 3;
export const MOVEMENT_ACTION_WALK_SLOW_DOWN = 4;
export const MOVEMENT_ACTION_WALK_SLOW_UP = 5;
export const MOVEMENT_ACTION_WALK_SLOW_LEFT = 6;
export const MOVEMENT_ACTION_WALK_SLOW_RIGHT = 7;
export const MOVEMENT_ACTION_WALK_NORMAL_DOWN = 8;
export const MOVEMENT_ACTION_WALK_NORMAL_UP = 9;
export const MOVEMENT_ACTION_WALK_NORMAL_LEFT = 10;
export const MOVEMENT_ACTION_WALK_NORMAL_RIGHT = 11;
export const MOVEMENT_ACTION_JUMP_2_DOWN = 12;
export const MOVEMENT_ACTION_JUMP_2_UP = 13;
export const MOVEMENT_ACTION_JUMP_2_LEFT = 14;
export const MOVEMENT_ACTION_JUMP_2_RIGHT = 15;
export const MOVEMENT_ACTION_DELAY_1 = 16;
export const MOVEMENT_ACTION_DELAY_2 = 17;
export const MOVEMENT_ACTION_DELAY_4 = 18;
export const MOVEMENT_ACTION_DELAY_8 = 19;
export const MOVEMENT_ACTION_DELAY_16 = 20;
export const MOVEMENT_ACTION_WALK_FAST_DOWN = 21;
export const MOVEMENT_ACTION_WALK_FAST_UP = 22;
export const MOVEMENT_ACTION_WALK_FAST_LEFT = 23;
export const MOVEMENT_ACTION_WALK_FAST_RIGHT = 24;
export const MOVEMENT_ACTION_WALK_IN_PLACE_SLOW_DOWN = 25;
export const MOVEMENT_ACTION_WALK_IN_PLACE_SLOW_UP = 26;
export const MOVEMENT_ACTION_WALK_IN_PLACE_SLOW_LEFT = 27;
export const MOVEMENT_ACTION_WALK_IN_PLACE_SLOW_RIGHT = 28;
export const MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_DOWN = 29;
export const MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_UP = 30;
export const MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_LEFT = 31;
export const MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_RIGHT = 32;
export const MOVEMENT_ACTION_WALK_IN_PLACE_FAST_DOWN = 33;
export const MOVEMENT_ACTION_WALK_IN_PLACE_FAST_UP = 34;
export const MOVEMENT_ACTION_WALK_IN_PLACE_FAST_LEFT = 35;
export const MOVEMENT_ACTION_WALK_IN_PLACE_FAST_RIGHT = 36;
export const MOVEMENT_ACTION_WALK_IN_PLACE_FASTER_DOWN = 37;
export const MOVEMENT_ACTION_WALK_IN_PLACE_FASTER_UP = 38;
export const MOVEMENT_ACTION_WALK_IN_PLACE_FASTER_LEFT = 39;
export const MOVEMENT_ACTION_WALK_IN_PLACE_FASTER_RIGHT = 40;
export const MOVEMENT_ACTION_RIDE_WATER_CURRENT_DOWN = 41;
export const MOVEMENT_ACTION_RIDE_WATER_CURRENT_UP = 42;
export const MOVEMENT_ACTION_RIDE_WATER_CURRENT_LEFT = 43;
export const MOVEMENT_ACTION_RIDE_WATER_CURRENT_RIGHT = 44;
export const MOVEMENT_ACTION_WALK_FASTER_DOWN = 45;
export const MOVEMENT_ACTION_WALK_FASTER_UP = 46;
export const MOVEMENT_ACTION_WALK_FASTER_LEFT = 47;
export const MOVEMENT_ACTION_WALK_FASTER_RIGHT = 48;
export const MOVEMENT_ACTION_SLIDE_DOWN = 49;
export const MOVEMENT_ACTION_SLIDE_UP = 50;
export const MOVEMENT_ACTION_SLIDE_LEFT = 51;
export const MOVEMENT_ACTION_SLIDE_RIGHT = 52;
export const MOVEMENT_ACTION_PLAYER_RUN_DOWN = 53;
export const MOVEMENT_ACTION_PLAYER_RUN_UP = 54;
export const MOVEMENT_ACTION_PLAYER_RUN_LEFT = 55;
export const MOVEMENT_ACTION_PLAYER_RUN_RIGHT = 56;
export const MOVEMENT_ACTION_START_ANIM_IN_DIRECTION = 57;
export const MOVEMENT_ACTION_JUMP_SPECIAL_DOWN = 58;
export const MOVEMENT_ACTION_JUMP_SPECIAL_UP = 59;
export const MOVEMENT_ACTION_JUMP_SPECIAL_LEFT = 60;
export const MOVEMENT_ACTION_JUMP_SPECIAL_RIGHT = 61;
export const MOVEMENT_ACTION_FACE_PLAYER = 62;
export const MOVEMENT_ACTION_FACE_AWAY_PLAYER = 63;
export const MOVEMENT_ACTION_LOCK_FACING_DIRECTION = 64;
export const MOVEMENT_ACTION_UNLOCK_FACING_DIRECTION = 65;
export const MOVEMENT_ACTION_JUMP_DOWN = 66;
export const MOVEMENT_ACTION_JUMP_UP = 67;
export const MOVEMENT_ACTION_JUMP_LEFT = 68;
export const MOVEMENT_ACTION_JUMP_RIGHT = 69;
export const MOVEMENT_ACTION_JUMP_IN_PLACE_DOWN = 70;
export const MOVEMENT_ACTION_JUMP_IN_PLACE_UP = 71;
export const MOVEMENT_ACTION_JUMP_IN_PLACE_LEFT = 72;
export const MOVEMENT_ACTION_JUMP_IN_PLACE_RIGHT = 73;
export const MOVEMENT_ACTION_JUMP_IN_PLACE_DOWN_UP = 74;
export const MOVEMENT_ACTION_JUMP_IN_PLACE_UP_DOWN = 75;
export const MOVEMENT_ACTION_JUMP_IN_PLACE_LEFT_RIGHT = 76;
export const MOVEMENT_ACTION_JUMP_IN_PLACE_RIGHT_LEFT = 77;
export const MOVEMENT_ACTION_FACE_ORIGINAL_DIRECTION = 78;
export const MOVEMENT_ACTION_NURSE_JOY_BOW_DOWN = 79;
export const MOVEMENT_ACTION_ENABLE_JUMP_LANDING_GROUND_EFFECT = 80;
export const MOVEMENT_ACTION_DISABLE_JUMP_LANDING_GROUND_EFFECT = 81;
export const MOVEMENT_ACTION_DISABLE_ANIMATION = 82;
export const MOVEMENT_ACTION_RESTORE_ANIMATION = 83;
export const MOVEMENT_ACTION_SET_INVISIBLE = 84;
export const MOVEMENT_ACTION_SET_VISIBLE = 85;
export const MOVEMENT_ACTION_EMOTE_EXCLAMATION_MARK = 86;
export const MOVEMENT_ACTION_EMOTE_QUESTION_MARK = 87;
export const MOVEMENT_ACTION_EMOTE_HEART = 88;
export const MOVEMENT_ACTION_REVEAL_TRAINER = 89;
export const MOVEMENT_ACTION_ROCK_SMASH_BREAK = 90;
export const MOVEMENT_ACTION_CUT_TREE = 91;
export const MOVEMENT_ACTION_SET_FIXED_PRIORITY = 92;
export const MOVEMENT_ACTION_CLEAR_FIXED_PRIORITY = 93;
export const MOVEMENT_ACTION_INIT_AFFINE_ANIM = 94;
export const MOVEMENT_ACTION_CLEAR_AFFINE_ANIM = 95;
export const MOVEMENT_ACTION_HIDE_REFLECTION = 96;
export const MOVEMENT_ACTION_SHOW_REFLECTION = 97;
export const MOVEMENT_ACTION_WALK_DOWN_START_AFFINE = 98;
export const MOVEMENT_ACTION_WALK_DOWN_AFFINE = 99;
export const MOVEMENT_ACTION_ACRO_WHEELIE_FACE_DOWN = 100;
export const MOVEMENT_ACTION_ACRO_WHEELIE_FACE_UP = 101;
export const MOVEMENT_ACTION_ACRO_WHEELIE_FACE_LEFT = 102;
export const MOVEMENT_ACTION_ACRO_WHEELIE_FACE_RIGHT = 103;
export const MOVEMENT_ACTION_ACRO_POP_WHEELIE_DOWN = 104;
export const MOVEMENT_ACTION_ACRO_POP_WHEELIE_UP = 105;
export const MOVEMENT_ACTION_ACRO_POP_WHEELIE_LEFT = 106;
export const MOVEMENT_ACTION_ACRO_POP_WHEELIE_RIGHT = 107;
export const MOVEMENT_ACTION_ACRO_END_WHEELIE_FACE_DOWN = 108;
export const MOVEMENT_ACTION_ACRO_END_WHEELIE_FACE_UP = 109;
export const MOVEMENT_ACTION_ACRO_END_WHEELIE_FACE_LEFT = 110;
export const MOVEMENT_ACTION_ACRO_END_WHEELIE_FACE_RIGHT = 111;
export const MOVEMENT_ACTION_ACRO_WHEELIE_HOP_FACE_DOWN = 112;
export const MOVEMENT_ACTION_ACRO_WHEELIE_HOP_FACE_UP = 113;
export const MOVEMENT_ACTION_ACRO_WHEELIE_HOP_FACE_LEFT = 114;
export const MOVEMENT_ACTION_ACRO_WHEELIE_HOP_FACE_RIGHT = 115;
export const MOVEMENT_ACTION_ACRO_WHEELIE_HOP_DOWN = 116;
export const MOVEMENT_ACTION_ACRO_WHEELIE_HOP_UP = 117;
export const MOVEMENT_ACTION_ACRO_WHEELIE_HOP_LEFT = 118;
export const MOVEMENT_ACTION_ACRO_WHEELIE_HOP_RIGHT = 119;
export const MOVEMENT_ACTION_ACRO_WHEELIE_JUMP_DOWN = 120;
export const MOVEMENT_ACTION_ACRO_WHEELIE_JUMP_UP = 121;
export const MOVEMENT_ACTION_ACRO_WHEELIE_JUMP_LEFT = 122;
export const MOVEMENT_ACTION_ACRO_WHEELIE_JUMP_RIGHT = 123;
export const MOVEMENT_ACTION_ACRO_WHEELIE_IN_PLACE_DOWN = 124;
export const MOVEMENT_ACTION_ACRO_WHEELIE_IN_PLACE_UP = 125;
export const MOVEMENT_ACTION_ACRO_WHEELIE_IN_PLACE_LEFT = 126;
export const MOVEMENT_ACTION_ACRO_WHEELIE_IN_PLACE_RIGHT = 127;
export const MOVEMENT_ACTION_ACRO_POP_WHEELIE_MOVE_DOWN = 128;
export const MOVEMENT_ACTION_ACRO_POP_WHEELIE_MOVE_UP = 129;
export const MOVEMENT_ACTION_ACRO_POP_WHEELIE_MOVE_LEFT = 130;
export const MOVEMENT_ACTION_ACRO_POP_WHEELIE_MOVE_RIGHT = 131;
export const MOVEMENT_ACTION_ACRO_WHEELIE_MOVE_DOWN = 132;
export const MOVEMENT_ACTION_ACRO_WHEELIE_MOVE_UP = 133;
export const MOVEMENT_ACTION_ACRO_WHEELIE_MOVE_LEFT = 134;
export const MOVEMENT_ACTION_ACRO_WHEELIE_MOVE_RIGHT = 135;
export const MOVEMENT_ACTION_ACRO_END_WHEELIE_MOVE_DOWN = 136;
export const MOVEMENT_ACTION_ACRO_END_WHEELIE_MOVE_UP = 137;
export const MOVEMENT_ACTION_ACRO_END_WHEELIE_MOVE_LEFT = 138;
export const MOVEMENT_ACTION_ACRO_END_WHEELIE_MOVE_RIGHT = 139;
export const MOVEMENT_ACTION_WALK_NORMAL_DIAGONAL_UP_LEFT = 140;
export const MOVEMENT_ACTION_WALK_NORMAL_DIAGONAL_UP_RIGHT = 141;
export const MOVEMENT_ACTION_WALK_NORMAL_DIAGONAL_DOWN_LEFT = 142;
export const MOVEMENT_ACTION_WALK_NORMAL_DIAGONAL_DOWN_RIGHT = 143;
export const MOVEMENT_ACTION_WALK_SLOW_DIAGONAL_UP_LEFT = 144;
export const MOVEMENT_ACTION_WALK_SLOW_DIAGONAL_UP_RIGHT = 145;
export const MOVEMENT_ACTION_WALK_SLOW_DIAGONAL_DOWN_LEFT = 146;
export const MOVEMENT_ACTION_WALK_SLOW_DIAGONAL_DOWN_RIGHT = 147;
export const MOVEMENT_ACTION_LOCK_ANIM = 148;
export const MOVEMENT_ACTION_UNLOCK_ANIM = 149;
export const MOVEMENT_ACTION_WALK_LEFT_AFFINE = 150;
export const MOVEMENT_ACTION_WALK_RIGHT_AFFINE = 151;
export const MOVEMENT_ACTION_LEVITATE = 152;
export const MOVEMENT_ACTION_STOP_LEVITATE = 153;
export const MOVEMENT_ACTION_STOP_LEVITATE_AT_TOP = 154;
export const MOVEMENT_ACTION_FIGURE_8 = 155;
export const MOVEMENT_ACTION_FLY_UP = 156;
export const MOVEMENT_ACTION_FLY_DOWN = 157;
export const MOVEMENT_ACTION_STEP_END = 254;
export const MOVEMENT_ACTION_NONE = 255;
export const ANIM_STD_FACE_SOUTH = 0;
export const ANIM_STD_FACE_NORTH = 1;
export const ANIM_STD_FACE_WEST = 2;
export const ANIM_STD_FACE_EAST = 3;
export const ANIM_STD_GO_SOUTH = 4;
export const ANIM_STD_GO_NORTH = 5;
export const ANIM_STD_GO_WEST = 6;
export const ANIM_STD_GO_EAST = 7;
export const ANIM_STD_GO_FAST_SOUTH = 8;
export const ANIM_STD_GO_FAST_NORTH = 9;
export const ANIM_STD_GO_FAST_WEST = 10;
export const ANIM_STD_GO_FAST_EAST = 11;
export const ANIM_STD_GO_FASTER_SOUTH = 12;
export const ANIM_STD_GO_FASTER_NORTH = 13;
export const ANIM_STD_GO_FASTER_WEST = 14;
export const ANIM_STD_GO_FASTER_EAST = 15;
export const ANIM_STD_GO_FASTEST_SOUTH = 16;
export const ANIM_STD_GO_FASTEST_NORTH = 17;
export const ANIM_STD_GO_FASTEST_WEST = 18;
export const ANIM_STD_GO_FASTEST_EAST = 19;
export const ANIM_STD_COUNT = 20;
/** Raw expr: `(ANIM_STD_COUNT + 0)` */
export const ANIM_RUN_SOUTH_EXPR = "(ANIM_STD_COUNT + 0)";
/** Raw expr: `(ANIM_STD_COUNT + 1)` */
export const ANIM_RUN_NORTH_EXPR = "(ANIM_STD_COUNT + 1)";
/** Raw expr: `(ANIM_STD_COUNT + 2)` */
export const ANIM_RUN_WEST_EXPR = "(ANIM_STD_COUNT + 2)";
/** Raw expr: `(ANIM_STD_COUNT + 3)` */
export const ANIM_RUN_EAST_EXPR = "(ANIM_STD_COUNT + 3)";
/** Raw expr: `(ANIM_STD_COUNT + 0)` */
export const ANIM_BUNNY_HOP_BACK_WHEEL_SOUTH_EXPR = "(ANIM_STD_COUNT + 0)";
/** Raw expr: `(ANIM_STD_COUNT + 1)` */
export const ANIM_BUNNY_HOP_BACK_WHEEL_NORTH_EXPR = "(ANIM_STD_COUNT + 1)";
/** Raw expr: `(ANIM_STD_COUNT + 2)` */
export const ANIM_BUNNY_HOP_BACK_WHEEL_WEST_EXPR = "(ANIM_STD_COUNT + 2)";
/** Raw expr: `(ANIM_STD_COUNT + 3)` */
export const ANIM_BUNNY_HOP_BACK_WHEEL_EAST_EXPR = "(ANIM_STD_COUNT + 3)";
/** Raw expr: `(ANIM_STD_COUNT + 4)` */
export const ANIM_BUNNY_HOP_FRONT_WHEEL_SOUTH_EXPR = "(ANIM_STD_COUNT + 4)";
/** Raw expr: `(ANIM_STD_COUNT + 5)` */
export const ANIM_BUNNY_HOP_FRONT_WHEEL_NORTH_EXPR = "(ANIM_STD_COUNT + 5)";
/** Raw expr: `(ANIM_STD_COUNT + 6)` */
export const ANIM_BUNNY_HOP_FRONT_WHEEL_WEST_EXPR = "(ANIM_STD_COUNT + 6)";
/** Raw expr: `(ANIM_STD_COUNT + 7)` */
export const ANIM_BUNNY_HOP_FRONT_WHEEL_EAST_EXPR = "(ANIM_STD_COUNT + 7)";
/** Raw expr: `(ANIM_STD_COUNT + 8)` */
export const ANIM_STANDING_WHEELIE_BACK_WHEEL_SOUTH_EXPR = "(ANIM_STD_COUNT + 8)";
/** Raw expr: `(ANIM_STD_COUNT + 9)` */
export const ANIM_STANDING_WHEELIE_BACK_WHEEL_NORTH_EXPR = "(ANIM_STD_COUNT + 9)";
/** Raw expr: `(ANIM_STD_COUNT + 10)` */
export const ANIM_STANDING_WHEELIE_BACK_WHEEL_WEST_EXPR = "(ANIM_STD_COUNT + 10)";
/** Raw expr: `(ANIM_STD_COUNT + 11)` */
export const ANIM_STANDING_WHEELIE_BACK_WHEEL_EAST_EXPR = "(ANIM_STD_COUNT + 11)";
/** Raw expr: `(ANIM_STD_COUNT + 12)` */
export const ANIM_STANDING_WHEELIE_FRONT_WHEEL_SOUTH_EXPR = "(ANIM_STD_COUNT + 12)";
/** Raw expr: `(ANIM_STD_COUNT + 13)` */
export const ANIM_STANDING_WHEELIE_FRONT_WHEEL_NORTH_EXPR = "(ANIM_STD_COUNT + 13)";
/** Raw expr: `(ANIM_STD_COUNT + 14)` */
export const ANIM_STANDING_WHEELIE_FRONT_WHEEL_WEST_EXPR = "(ANIM_STD_COUNT + 14)";
/** Raw expr: `(ANIM_STD_COUNT + 15)` */
export const ANIM_STANDING_WHEELIE_FRONT_WHEEL_EAST_EXPR = "(ANIM_STD_COUNT + 15)";
/** Raw expr: `(ANIM_STD_COUNT + 16)` */
export const ANIM_MOVING_WHEELIE_SOUTH_EXPR = "(ANIM_STD_COUNT + 16)";
/** Raw expr: `(ANIM_STD_COUNT + 17)` */
export const ANIM_MOVING_WHEELIE_NORTH_EXPR = "(ANIM_STD_COUNT + 17)";
/** Raw expr: `(ANIM_STD_COUNT + 18)` */
export const ANIM_MOVING_WHEELIE_WEST_EXPR = "(ANIM_STD_COUNT + 18)";
/** Raw expr: `(ANIM_STD_COUNT + 19)` */
export const ANIM_MOVING_WHEELIE_EAST_EXPR = "(ANIM_STD_COUNT + 19)";
/** Raw expr: `(ANIM_STD_COUNT + 0)` */
export const ANIM_GET_ON_OFF_POKEMON_SOUTH_EXPR = "(ANIM_STD_COUNT + 0)";
/** Raw expr: `(ANIM_STD_COUNT + 1)` */
export const ANIM_GET_ON_OFF_POKEMON_NORTH_EXPR = "(ANIM_STD_COUNT + 1)";
/** Raw expr: `(ANIM_STD_COUNT + 2)` */
export const ANIM_GET_ON_OFF_POKEMON_WEST_EXPR = "(ANIM_STD_COUNT + 2)";
/** Raw expr: `(ANIM_STD_COUNT + 3)` */
export const ANIM_GET_ON_OFF_POKEMON_EAST_EXPR = "(ANIM_STD_COUNT + 3)";
/** Raw expr: `(ANIM_STD_COUNT + 0)` */
export const ANIM_NURSE_BOW_EXPR = "(ANIM_STD_COUNT + 0)";
export const ANIM_FIELD_MOVE = 0;
export const ANIM_STAY_STILL = 0;
export const ANIM_REMOVE_OBSTACLE = 1;
export const ANIM_TAKE_OUT_ROD_SOUTH = 0;
export const ANIM_TAKE_OUT_ROD_NORTH = 1;
export const ANIM_TAKE_OUT_ROD_WEST = 2;
export const ANIM_TAKE_OUT_ROD_EAST = 3;
export const ANIM_PUT_AWAY_ROD_SOUTH = 4;
export const ANIM_PUT_AWAY_ROD_NORTH = 5;
export const ANIM_PUT_AWAY_ROD_WEST = 6;
export const ANIM_PUT_AWAY_ROD_EAST = 7;
export const ANIM_HOOKED_POKEMON_SOUTH = 8;
export const ANIM_HOOKED_POKEMON_NORTH = 9;
export const ANIM_HOOKED_POKEMON_WEST = 10;
export const ANIM_HOOKED_POKEMON_EAST = 11;
export const COPY_MOVE_NONE = 0;
export const COPY_MOVE_FACE = 1;
export const COPY_MOVE_WALK = 2;
export const COPY_MOVE_WALK_FAST = 3;
export const COPY_MOVE_WALK_FASTER = 4;
export const COPY_MOVE_SLIDE = 5;
export const COPY_MOVE_JUMP_IN_PLACE = 6;
export const COPY_MOVE_JUMP = 7;
export const COPY_MOVE_JUMP2 = 8;
export const COPY_MOVE_EMPTY_1 = 9;
export const COPY_MOVE_EMPTY_2 = 10;

// ─── Compléments (unification lot 17a, 2026-07-10) — rapatriés de engine/field/object-event-graphics-info.ts ───

/** 1:1 décomp `include/constants/event_object_movement.h` SHADOW_SIZE_*. */
export const SHADOW_SIZE_S = 0;
export const SHADOW_SIZE_M = 1;
export const SHADOW_SIZE_L = 2;
export const SHADOW_SIZE_XL = 3;

/** 1:1 décomp TRACKS_*. */
export const TRACKS_NONE = 0;
export const TRACKS_FOOT = 1;
export const TRACKS_BIKE_TIRE = 2;
export const TRACKS_SLITHER = 3;
