// AUTO-GENERATED from include/constants/weather.h by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/include/constants/weather.h
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
export const WEATHER_NONE = 0;
export const WEATHER_SUNNY_CLOUDS = 1;
export const WEATHER_SUNNY = 2;
export const WEATHER_RAIN = 3;
export const WEATHER_SNOW = 4;
export const WEATHER_RAIN_THUNDERSTORM = 5;
export const WEATHER_FOG_HORIZONTAL = 6;
export const WEATHER_VOLCANIC_ASH = 7;
export const WEATHER_SANDSTORM = 8;
export const WEATHER_FOG_DIAGONAL = 9;
export const WEATHER_UNDERWATER = 10;
export const WEATHER_SHADE = 11;
export const WEATHER_DROUGHT = 12;
export const WEATHER_DOWNPOUR = 13;
export const WEATHER_UNDERWATER_BUBBLES = 14;
export const WEATHER_ABNORMAL = 15;
export const WEATHER_ROUTE119_CYCLE = 20;
export const WEATHER_ROUTE123_CYCLE = 21;
export const COORD_EVENT_WEATHER_SUNNY_CLOUDS = 1;
export const COORD_EVENT_WEATHER_SUNNY = 2;
export const COORD_EVENT_WEATHER_RAIN = 3;
export const COORD_EVENT_WEATHER_SNOW = 4;
export const COORD_EVENT_WEATHER_RAIN_THUNDERSTORM = 5;
export const COORD_EVENT_WEATHER_FOG_HORIZONTAL = 6;
export const COORD_EVENT_WEATHER_FOG_DIAGONAL = 7;
export const COORD_EVENT_WEATHER_VOLCANIC_ASH = 8;
export const COORD_EVENT_WEATHER_SANDSTORM = 9;
export const COORD_EVENT_WEATHER_SHADE = 10;
export const COORD_EVENT_WEATHER_DROUGHT = 11;
export const COORD_EVENT_WEATHER_ROUTE119_CYCLE = 20;
export const COORD_EVENT_WEATHER_ROUTE123_CYCLE = 21;
export const TERRA_CAVE_LOCATIONS_START = 1;
/** Raw expr: `(TERRA_CAVE_LOCATIONS_START + 0)` */
export const ABNORMAL_WEATHER_ROUTE_114_NORTH_EXPR = "(TERRA_CAVE_LOCATIONS_START + 0)";
/** Raw expr: `(TERRA_CAVE_LOCATIONS_START + 1)` */
export const ABNORMAL_WEATHER_ROUTE_114_SOUTH_EXPR = "(TERRA_CAVE_LOCATIONS_START + 1)";
/** Raw expr: `(TERRA_CAVE_LOCATIONS_START + 2)` */
export const ABNORMAL_WEATHER_ROUTE_115_WEST_EXPR = "(TERRA_CAVE_LOCATIONS_START + 2)";
/** Raw expr: `(TERRA_CAVE_LOCATIONS_START + 3)` */
export const ABNORMAL_WEATHER_ROUTE_115_EAST_EXPR = "(TERRA_CAVE_LOCATIONS_START + 3)";
/** Raw expr: `(TERRA_CAVE_LOCATIONS_START + 4)` */
export const ABNORMAL_WEATHER_ROUTE_116_NORTH_EXPR = "(TERRA_CAVE_LOCATIONS_START + 4)";
/** Raw expr: `(TERRA_CAVE_LOCATIONS_START + 5)` */
export const ABNORMAL_WEATHER_ROUTE_116_SOUTH_EXPR = "(TERRA_CAVE_LOCATIONS_START + 5)";
/** Raw expr: `(TERRA_CAVE_LOCATIONS_START + 6)` */
export const ABNORMAL_WEATHER_ROUTE_118_EAST_EXPR = "(TERRA_CAVE_LOCATIONS_START + 6)";
/** Raw expr: `(TERRA_CAVE_LOCATIONS_START + 7)` */
export const ABNORMAL_WEATHER_ROUTE_118_WEST_EXPR = "(TERRA_CAVE_LOCATIONS_START + 7)";
export const TERRA_CAVE_LOCATIONS = 8;
/** Raw expr: `(TERRA_CAVE_LOCATIONS_START + TERRA_CAVE_LOCATIONS)` */
export const MARINE_CAVE_LOCATIONS_START_EXPR = "(TERRA_CAVE_LOCATIONS_START + TERRA_CAVE_LOCATIONS)";
/** Raw expr: `(MARINE_CAVE_LOCATIONS_START + 0)` */
export const ABNORMAL_WEATHER_ROUTE_105_NORTH_EXPR = "(MARINE_CAVE_LOCATIONS_START + 0)";
/** Raw expr: `(MARINE_CAVE_LOCATIONS_START + 1)` */
export const ABNORMAL_WEATHER_ROUTE_105_SOUTH_EXPR = "(MARINE_CAVE_LOCATIONS_START + 1)";
/** Raw expr: `(MARINE_CAVE_LOCATIONS_START + 2)` */
export const ABNORMAL_WEATHER_ROUTE_125_WEST_EXPR = "(MARINE_CAVE_LOCATIONS_START + 2)";
/** Raw expr: `(MARINE_CAVE_LOCATIONS_START + 3)` */
export const ABNORMAL_WEATHER_ROUTE_125_EAST_EXPR = "(MARINE_CAVE_LOCATIONS_START + 3)";
/** Raw expr: `(MARINE_CAVE_LOCATIONS_START + 4)` */
export const ABNORMAL_WEATHER_ROUTE_127_NORTH_EXPR = "(MARINE_CAVE_LOCATIONS_START + 4)";
/** Raw expr: `(MARINE_CAVE_LOCATIONS_START + 5)` */
export const ABNORMAL_WEATHER_ROUTE_127_SOUTH_EXPR = "(MARINE_CAVE_LOCATIONS_START + 5)";
/** Raw expr: `(MARINE_CAVE_LOCATIONS_START + 6)` */
export const ABNORMAL_WEATHER_ROUTE_129_WEST_EXPR = "(MARINE_CAVE_LOCATIONS_START + 6)";
/** Raw expr: `(MARINE_CAVE_LOCATIONS_START + 7)` */
export const ABNORMAL_WEATHER_ROUTE_129_EAST_EXPR = "(MARINE_CAVE_LOCATIONS_START + 7)";
export const MARINE_CAVE_LOCATIONS = 8;
/** Raw expr: `(MARINE_CAVE_LOCATIONS + TERRA_CAVE_LOCATIONS)` */
export const ABNORMAL_WEATHER_LOCATIONS_EXPR = "(MARINE_CAVE_LOCATIONS + TERRA_CAVE_LOCATIONS)";
export const ABNORMAL_WEATHER_NONE = 0;
