// AUTO-GENERATED par scripts/extract-battle-anim-tables.mjs — NE PAS EDITER.
// 1:1 decomp data/battle_anim_scripts.s : les 4 tables de POINTEURS de scripts
// d'anim (noms de labels, dans l'ordre des index B_ANIM_*/move IDs).

export const gBattleAnims_Moves: ReadonlyArray<string> = [
  'Move_NONE', 'Move_POUND', 'Move_KARATE_CHOP', 'Move_DOUBLE_SLAP', 'Move_COMET_PUNCH', 'Move_MEGA_PUNCH',
  'Move_PAY_DAY', 'Move_FIRE_PUNCH', 'Move_ICE_PUNCH', 'Move_THUNDER_PUNCH', 'Move_SCRATCH', 'Move_VICE_GRIP',
  'Move_GUILLOTINE', 'Move_RAZOR_WIND', 'Move_SWORDS_DANCE', 'Move_CUT', 'Move_GUST', 'Move_WING_ATTACK',
  'Move_WHIRLWIND', 'Move_FLY', 'Move_BIND', 'Move_SLAM', 'Move_VINE_WHIP', 'Move_STOMP',
  'Move_DOUBLE_KICK', 'Move_MEGA_KICK', 'Move_JUMP_KICK', 'Move_ROLLING_KICK', 'Move_SAND_ATTACK', 'Move_HEADBUTT',
  'Move_HORN_ATTACK', 'Move_FURY_ATTACK', 'Move_HORN_DRILL', 'Move_TACKLE', 'Move_BODY_SLAM', 'Move_WRAP',
  'Move_TAKE_DOWN', 'Move_THRASH', 'Move_DOUBLE_EDGE', 'Move_TAIL_WHIP', 'Move_POISON_STING', 'Move_TWINEEDLE',
  'Move_PIN_MISSILE', 'Move_LEER', 'Move_BITE', 'Move_GROWL', 'Move_ROAR', 'Move_SING',
  'Move_SUPERSONIC', 'Move_SONIC_BOOM', 'Move_DISABLE', 'Move_ACID', 'Move_EMBER', 'Move_FLAMETHROWER',
  'Move_MIST', 'Move_WATER_GUN', 'Move_HYDRO_PUMP', 'Move_SURF', 'Move_ICE_BEAM', 'Move_BLIZZARD',
  'Move_PSYBEAM', 'Move_BUBBLE_BEAM', 'Move_AURORA_BEAM', 'Move_HYPER_BEAM', 'Move_PECK', 'Move_DRILL_PECK',
  'Move_SUBMISSION', 'Move_LOW_KICK', 'Move_COUNTER', 'Move_SEISMIC_TOSS', 'Move_STRENGTH', 'Move_ABSORB',
  'Move_MEGA_DRAIN', 'Move_LEECH_SEED', 'Move_GROWTH', 'Move_RAZOR_LEAF', 'Move_SOLAR_BEAM', 'Move_POISON_POWDER',
  'Move_STUN_SPORE', 'Move_SLEEP_POWDER', 'Move_PETAL_DANCE', 'Move_STRING_SHOT', 'Move_DRAGON_RAGE', 'Move_FIRE_SPIN',
  'Move_THUNDER_SHOCK', 'Move_THUNDERBOLT', 'Move_THUNDER_WAVE', 'Move_THUNDER', 'Move_ROCK_THROW', 'Move_EARTHQUAKE',
  'Move_FISSURE', 'Move_DIG', 'Move_TOXIC', 'Move_CONFUSION', 'Move_PSYCHIC', 'Move_HYPNOSIS',
  'Move_MEDITATE', 'Move_AGILITY', 'Move_QUICK_ATTACK', 'Move_RAGE', 'Move_TELEPORT', 'Move_NIGHT_SHADE',
  'Move_MIMIC', 'Move_SCREECH', 'Move_DOUBLE_TEAM', 'Move_RECOVER', 'Move_HARDEN', 'Move_MINIMIZE',
  'Move_SMOKESCREEN', 'Move_CONFUSE_RAY', 'Move_WITHDRAW', 'Move_DEFENSE_CURL', 'Move_BARRIER', 'Move_LIGHT_SCREEN',
  'Move_HAZE', 'Move_REFLECT', 'Move_FOCUS_ENERGY', 'Move_BIDE', 'Move_METRONOME', 'Move_MIRROR_MOVE',
  'Move_SELF_DESTRUCT', 'Move_EGG_BOMB', 'Move_LICK', 'Move_SMOG', 'Move_SLUDGE', 'Move_BONE_CLUB',
  'Move_FIRE_BLAST', 'Move_WATERFALL', 'Move_CLAMP', 'Move_SWIFT', 'Move_SKULL_BASH', 'Move_SPIKE_CANNON',
  'Move_CONSTRICT', 'Move_AMNESIA', 'Move_KINESIS', 'Move_SOFT_BOILED', 'Move_HI_JUMP_KICK', 'Move_GLARE',
  'Move_DREAM_EATER', 'Move_POISON_GAS', 'Move_BARRAGE', 'Move_LEECH_LIFE', 'Move_LOVELY_KISS', 'Move_SKY_ATTACK',
  'Move_TRANSFORM', 'Move_BUBBLE', 'Move_DIZZY_PUNCH', 'Move_SPORE', 'Move_FLASH', 'Move_PSYWAVE',
  'Move_SPLASH', 'Move_ACID_ARMOR', 'Move_CRABHAMMER', 'Move_EXPLOSION', 'Move_FURY_SWIPES', 'Move_BONEMERANG',
  'Move_REST', 'Move_ROCK_SLIDE', 'Move_HYPER_FANG', 'Move_SHARPEN', 'Move_CONVERSION', 'Move_TRI_ATTACK',
  'Move_SUPER_FANG', 'Move_SLASH', 'Move_SUBSTITUTE', 'Move_STRUGGLE', 'Move_SKETCH', 'Move_TRIPLE_KICK',
  'Move_THIEF', 'Move_SPIDER_WEB', 'Move_MIND_READER', 'Move_NIGHTMARE', 'Move_FLAME_WHEEL', 'Move_SNORE',
  'Move_CURSE', 'Move_FLAIL', 'Move_CONVERSION_2', 'Move_AEROBLAST', 'Move_COTTON_SPORE', 'Move_REVERSAL',
  'Move_SPITE', 'Move_POWDER_SNOW', 'Move_PROTECT', 'Move_MACH_PUNCH', 'Move_SCARY_FACE', 'Move_FAINT_ATTACK',
  'Move_SWEET_KISS', 'Move_BELLY_DRUM', 'Move_SLUDGE_BOMB', 'Move_MUD_SLAP', 'Move_OCTAZOOKA', 'Move_SPIKES',
  'Move_ZAP_CANNON', 'Move_FORESIGHT', 'Move_DESTINY_BOND', 'Move_PERISH_SONG', 'Move_ICY_WIND', 'Move_DETECT',
  'Move_BONE_RUSH', 'Move_LOCK_ON', 'Move_OUTRAGE', 'Move_SANDSTORM', 'Move_GIGA_DRAIN', 'Move_ENDURE',
  'Move_CHARM', 'Move_ROLLOUT', 'Move_FALSE_SWIPE', 'Move_SWAGGER', 'Move_MILK_DRINK', 'Move_SPARK',
  'Move_FURY_CUTTER', 'Move_STEEL_WING', 'Move_MEAN_LOOK', 'Move_ATTRACT', 'Move_SLEEP_TALK', 'Move_HEAL_BELL',
  'Move_RETURN', 'Move_PRESENT', 'Move_FRUSTRATION', 'Move_SAFEGUARD', 'Move_PAIN_SPLIT', 'Move_SACRED_FIRE',
  'Move_MAGNITUDE', 'Move_DYNAMIC_PUNCH', 'Move_MEGAHORN', 'Move_DRAGON_BREATH', 'Move_BATON_PASS', 'Move_ENCORE',
  'Move_PURSUIT', 'Move_RAPID_SPIN', 'Move_SWEET_SCENT', 'Move_IRON_TAIL', 'Move_METAL_CLAW', 'Move_VITAL_THROW',
  'Move_MORNING_SUN', 'Move_SYNTHESIS', 'Move_MOONLIGHT', 'Move_HIDDEN_POWER', 'Move_CROSS_CHOP', 'Move_TWISTER',
  'Move_RAIN_DANCE', 'Move_SUNNY_DAY', 'Move_CRUNCH', 'Move_MIRROR_COAT', 'Move_PSYCH_UP', 'Move_EXTREME_SPEED',
  'Move_ANCIENT_POWER', 'Move_SHADOW_BALL', 'Move_FUTURE_SIGHT', 'Move_ROCK_SMASH', 'Move_WHIRLPOOL', 'Move_BEAT_UP',
  'Move_FAKE_OUT', 'Move_UPROAR', 'Move_STOCKPILE', 'Move_SPIT_UP', 'Move_SWALLOW', 'Move_HEAT_WAVE',
  'Move_HAIL', 'Move_TORMENT', 'Move_FLATTER', 'Move_WILL_O_WISP', 'Move_MEMENTO', 'Move_FACADE',
  'Move_FOCUS_PUNCH', 'Move_SMELLING_SALT', 'Move_FOLLOW_ME', 'Move_NATURE_POWER', 'Move_CHARGE', 'Move_TAUNT',
  'Move_HELPING_HAND', 'Move_TRICK', 'Move_ROLE_PLAY', 'Move_WISH', 'Move_ASSIST', 'Move_INGRAIN',
  'Move_SUPERPOWER', 'Move_MAGIC_COAT', 'Move_RECYCLE', 'Move_REVENGE', 'Move_BRICK_BREAK', 'Move_YAWN',
  'Move_KNOCK_OFF', 'Move_ENDEAVOR', 'Move_ERUPTION', 'Move_SKILL_SWAP', 'Move_IMPRISON', 'Move_REFRESH',
  'Move_GRUDGE', 'Move_SNATCH', 'Move_SECRET_POWER', 'Move_DIVE', 'Move_ARM_THRUST', 'Move_CAMOUFLAGE',
  'Move_TAIL_GLOW', 'Move_LUSTER_PURGE', 'Move_MIST_BALL', 'Move_FEATHER_DANCE', 'Move_TEETER_DANCE', 'Move_BLAZE_KICK',
  'Move_MUD_SPORT', 'Move_ICE_BALL', 'Move_NEEDLE_ARM', 'Move_SLACK_OFF', 'Move_HYPER_VOICE', 'Move_POISON_FANG',
  'Move_CRUSH_CLAW', 'Move_BLAST_BURN', 'Move_HYDRO_CANNON', 'Move_METEOR_MASH', 'Move_ASTONISH', 'Move_WEATHER_BALL',
  'Move_AROMATHERAPY', 'Move_FAKE_TEARS', 'Move_AIR_CUTTER', 'Move_OVERHEAT', 'Move_ODOR_SLEUTH', 'Move_ROCK_TOMB',
  'Move_SILVER_WIND', 'Move_METAL_SOUND', 'Move_GRASS_WHISTLE', 'Move_TICKLE', 'Move_COSMIC_POWER', 'Move_WATER_SPOUT',
  'Move_SIGNAL_BEAM', 'Move_SHADOW_PUNCH', 'Move_EXTRASENSORY', 'Move_SKY_UPPERCUT', 'Move_SAND_TOMB', 'Move_SHEER_COLD',
  'Move_MUDDY_WATER', 'Move_BULLET_SEED', 'Move_AERIAL_ACE', 'Move_ICICLE_SPEAR', 'Move_IRON_DEFENSE', 'Move_BLOCK',
  'Move_HOWL', 'Move_DRAGON_CLAW', 'Move_FRENZY_PLANT', 'Move_BULK_UP', 'Move_BOUNCE', 'Move_MUD_SHOT',
  'Move_POISON_TAIL', 'Move_COVET', 'Move_VOLT_TACKLE', 'Move_MAGICAL_LEAF', 'Move_WATER_SPORT', 'Move_CALM_MIND',
  'Move_LEAF_BLADE', 'Move_DRAGON_DANCE', 'Move_ROCK_BLAST', 'Move_SHOCK_WAVE', 'Move_WATER_PULSE', 'Move_DOOM_DESIRE',
  'Move_PSYCHO_BOOST', 'Move_COUNT', 'because last move is Psycho Boost',
];

export const gBattleAnims_StatusConditions: ReadonlyArray<string> = [
  'Status_Poison', 'Status_Confusion', 'Status_Burn', 'Status_Infatuation', 'Status_Sleep', 'Status_Paralysis',
  'Status_Freeze', 'Status_Curse', 'Status_Nightmare',
];

export const gBattleAnims_General: ReadonlyArray<string> = [
  'General_CastformChange', 'General_StatsChange', 'General_SubstituteFade', 'General_SubstituteAppear', 'General_PokeblockThrow', 'General_ItemKnockoff',
  'General_TurnTrap', 'General_HeldItemEffect', 'General_SmokeballEscape', 'General_FocusBand', 'General_Rain', 'General_Sun',
  'General_Sandstorm', 'General_Hail', 'General_LeechSeedDrain', 'General_MonHit', 'General_ItemSteal', 'General_SnatchMove',
  'General_FutureSightHit', 'General_DoomDesireHit', 'General_FocusPunchSetUp', 'General_IngrainHeal', 'General_WishHeal',
];

export const gBattleAnims_Special: ReadonlyArray<string> = [
  'Special_LevelUp', 'Special_SwitchOutPlayerMon', 'Special_SwitchOutOpponentMon', 'Special_BallThrow', 'Special_BallThrowWithTrainer', 'Special_SubstituteToMon',
  'Special_MonToSubstitute',
];
