// AUTO-GENERATED from src/contest_util.c by extract-decomp-task-machines.mjs
// Do not edit manually — re-run `npm run extract:task-machines` to refresh.
//
// Generated: 2026-04-26
// Stats: 36 Task_, 3 CB2_, 6 SpriteCB_

export const TASKS = {
  "Task_ShowContestResults": {
    callsTo: ["ClearContinueGameWarpStatus2","GetContestWinnerSaveIdx","IncrementGameStat","InterviewAfter","InterviewBefore","IsLinkTaskFinished","PlayBGM","SaveContestWinner","SaveLinkContestResults","SetContinueGameWarpStatusToDynamicWarp","SetLinkStandbyCallback","ShowLinkResultsTextBox","TryGainNewFanFromCounter","TrySavingData","VarGet","VarSet"],
    taskTransitions: ["Task_AnnouncePreliminaryResults","Task_WaitForLinkPartnersBeforeResults"],
    dataReads: ["tState"],
    dataWrites: ["tState"],
    externalChecks: { paletteFade: true },
    lineCount: 72,
    bodyC: "u16 var;\n\n    if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n    {\n        switch (gTasks[taskId].tState)\n        {\n        case 0:\n            SaveLinkContestResults();\n            if (gContestFinalStandings[gContestPlayerMonIndex] == 0)\n            {\n                IncrementGameStat(GAME_STAT_WON_LINK_CONTEST);\n                gSpecialVar_0x8005 = TVSHOW_CONTEST_LIVE_UPDATES;\n                InterviewBefore();\n                if (gSpecialVar_Result != TRUE)\n                    InterviewAfter();\n            }\n\n            TryGainNewFanFromCounter(FANCOUNTER_FINISHED_CONTEST);\n            SaveContestWinner(gSpecialVar_ContestRank);  \n            SaveContestWinner(CONTEST_SAVE_FOR_ARTIST);\n            gCurContestWinnerIsForArtist = TRUE;\n            gCurContestWinnerSaveIdx = GetContestWinnerSaveIdx(CONTEST_SAVE_FOR_ARTIST, FALSE);\n            var = VarGet(VAR_CONTEST_HALL_STATE);\n            VarSet(VAR_CONTEST_HALL_STATE, 0);\n            SetContinueGameWarpStatusToDynamicWarp();\n            TrySavingData(SAVE_LINK);\n            ClearContinueGameWarpStatus2();\n            VarSet(VAR_CONTEST_HALL_STATE, var);\n            gTasks[taskId].tState++;\n            break;\n        case 1:\n            gTasks[taskId].tState++;\n            if (!(gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS))\n                gTasks[taskId].tState = 100;\n            break;\n        case 2:\n            if (IsLinkTaskFinished())\n            {\n                SetLinkStandbyCallback();\n                gTasks[taskId].tState++;\n            }\n            return;\n        case 3:\n            if (IsLinkTaskFinished() == TRUE)\n            {\n                PlayBGM(MUS_CONTEST_RESULTS);\n                gPaletteFade.bufferTransferDisabled = FALSE;\n                gTasks[taskId].tState++;\n                break;\n            }\n            return;\n        }\n    }\n\n    if (!gPaletteFade.active)\n    {\n        gTasks[taskId].tState = 0;\n        if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n        {\n            ShowLinkResultsTextBox(gText_CommunicationStandby);\n            gTasks[taskId].func = Task_WaitForLinkPartnersBeforeResults;\n        }\n        else\n        {\n            IncrementGameStat(GAME_STAT_ENTERED_CONTEST);\n            if (gContestFinalStandings[gContestPlayerMonIndex] == 0)\n                IncrementGameStat(GAME_STAT_WON_CONTEST);\n\n            SaveContestWinner(gSpecialVar_ContestRank);  \n            SaveContestWinner(CONTEST_SAVE_FOR_ARTIST);\n            gCurContestWinnerIsForArtist = TRUE;\n            gCurContestWinnerSaveIdx = GetContestWinnerSaveIdx(CONTEST_SAVE_FOR_ARTIST, FALSE);\n            TryGainNewFanFromCounter(FANCOUNTER_FINISHED_CONTEST);\n            gTasks[taskId].func = Task_AnnouncePreliminaryResults;\n        }\n    }",
  },
  "Task_WaitForLinkPartnersBeforeResults": {
    callsTo: ["CreateTask"],
    taskTransitions: ["TaskDummy"],
    lineCount: 5,
    bodyC: "if (gReceivedRemoteLinkPlayers)\n    {\n        CreateTask(Task_CommunicateMonIdxsForResults, 0);\n        gTasks[taskId].func = TaskDummy;\n    }",
  },
  "Task_CommunicateMonIdxsForResults": {
    callsTo: ["SetTaskFuncWithFollowupFunc"],
    lineCount: 1,
    bodyC: "SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateMonIdxs, Task_WaitForLinkPartnerMonIdxs);",
  },
  "Task_WaitForLinkPartnerMonIdxs": {
    callsTo: ["DestroyTask","HideLinkResultsTextBox","IsLinkTaskFinished"],
    taskTransitions: ["Task_AnnouncePreliminaryResults"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 6,
    bodyC: "if (IsLinkTaskFinished())\n    {\n        DestroyTask(taskId);\n        gTasks[sContestResults->data->showResultsTaskId].func = Task_AnnouncePreliminaryResults;\n        HideLinkResultsTextBox();\n    }",
  },
  "Task_AnnouncePreliminaryResults": {
    callsTo: ["CreateTask","DrawResultsTextWindow","StartTextBoxSlideIn"],
    taskTransitions: ["Task_ShowPreliminaryResults"],
    dataReads: ["tState"],
    dataWrites: ["tState","tTimer"],
    lineCount: 38,
    bodyC: "s16 x;\n\n    if (gTasks[taskId].tState == 0)\n    {\n        CreateTask(Task_FlashStarsAndHearts, 20);\n        x = DrawResultsTextWindow(gText_AnnouncingResults, sContestResults->data->slidingTextBoxSpriteId);\n        StartTextBoxSlideIn(x, TEXT_BOX_Y, 120, 1088);\n        gTasks[taskId].tState++;\n    }\n    else if (gTasks[taskId].tState == 1)\n    {\n         \n        if (sContestResults->data->slidingTextBoxState == SLIDING_TEXT_OFFSCREEN)\n        {\n            gTasks[taskId].tTimer = 0;\n            gTasks[taskId].tState++;\n        }\n    }\n    else if (gTasks[taskId].tState == 2)\n    {\n        if (++gTasks[taskId].tTimer == 21)\n        {\n            gTasks[taskId].tTimer = 0;\n            gTasks[taskId].tState++;\n        }\n    }\n    else if (gTasks[taskId].tState == 3)\n    {\n        x = DrawResultsTextWindow(gText_PreliminaryResults, sContestResults->data->slidingTextBoxSpriteId);\n        StartTextBoxSlideIn(x, TEXT_BOX_Y, -1, 1088);\n        gTasks[taskId].tState++;\n    }\n    else if (gTasks[taskId].tState == 4)\n    {\n        if (sContestResults->data->slidingTextBoxState == SLIDING_TEXT_ARRIVED)\n        {\n            gTasks[taskId].tState = 0;\n            gTasks[taskId].func = Task_ShowPreliminaryResults;\n        }\n    }",
  },
  "Task_ShowPreliminaryResults": {
    callsTo: ["StartTextBoxSlideOut","UpdateContestResultBars"],
    taskTransitions: ["Task_AnnounceRound2Results"],
    dataReads: ["tCounter","tState"],
    dataWrites: ["tCounter","tState"],
    lineCount: 23,
    bodyC: "switch (gTasks[taskId].tState)\n    {\n    case 0:\n        if (!sContestResults->data->pointsFlashing)\n        {\n            UpdateContestResultBars(FALSE, gTasks[taskId].tCounter++);\n            if (sContestResults->data->numBarsUpdating == 0)\n                gTasks[taskId].tState = 2;\n            else\n                gTasks[taskId].tState++;\n        }\n        break;\n    case 1:\n        if (sContestResults->data->numBarsUpdating == 0)\n            gTasks[taskId].tState = 0;\n        break;\n    case 2:\n        StartTextBoxSlideOut(1088);\n        gTasks[taskId].tState = 0;\n        gTasks[taskId].tCounter = 0;\n        gTasks[taskId].func = Task_AnnounceRound2Results;\n        break;\n    }",
  },
  "Task_AnnounceRound2Results": {
    callsTo: ["DrawResultsTextWindow","StartTextBoxSlideIn"],
    taskTransitions: ["Task_ShowRound2Results"],
    dataWrites: ["tTimer"],
    lineCount: 14,
    bodyC: "s16 x;\n\n    if (sContestResults->data->slidingTextBoxState == SLIDING_TEXT_OFFSCREEN)\n    {\n        if (++gTasks[taskId].tTimer == 21)\n        {\n            gTasks[taskId].tTimer = 0;\n            x = DrawResultsTextWindow(gText_Round2Results, sContestResults->data->slidingTextBoxSpriteId);\n            StartTextBoxSlideIn(x, TEXT_BOX_Y, -1, 1088);\n        }\n    }\n    else if (sContestResults->data->slidingTextBoxState == SLIDING_TEXT_ARRIVED)\n    {\n        gTasks[taskId].func = Task_ShowRound2Results;\n    }",
  },
  "Task_ShowRound2Results": {
    callsTo: ["StartTextBoxSlideOut","UpdateContestResultBars"],
    taskTransitions: ["Task_AnnounceWinner"],
    dataReads: ["tCounter","tState"],
    dataWrites: ["tCounter","tState"],
    lineCount: 22,
    bodyC: "switch (gTasks[taskId].tState)\n    {\n    case 0:\n        if (!sContestResults->data->pointsFlashing)\n        {\n            UpdateContestResultBars(TRUE, gTasks[taskId].tCounter++);\n            if (sContestResults->data->numBarsUpdating == 0)\n                gTasks[taskId].tState = 2;\n            else\n                gTasks[taskId].tState++;\n        }\n        break;\n    case 1:\n        if (sContestResults->data->numBarsUpdating == 0)\n            gTasks[taskId].tState = 0;\n        break;\n    case 2:\n        StartTextBoxSlideOut(1088);\n        gTasks[taskId].tState = 0;\n        gTasks[taskId].func = Task_AnnounceWinner;\n        break;\n    }",
  },
  "Task_AnnounceWinner": {
    callsTo: ["BounceMonIconInBox","ConvertInternationalContestantName","CreateTask","DrawResultsTextWindow","GET_CONTEST_WINNER_ID","StartTextBoxSlideIn","StringCopy","StringExpandPlaceholders"],
    taskTransitions: ["Task_ShowWinnerMonBanner"],
    dataReads: ["tState"],
    dataWrites: ["tFinalStanding","tMonIndex","tState","tTimer"],
    lineCount: 57,
    bodyC: "int i;\n    switch (gTasks[taskId].tState)\n    {\n    case 0:\n        if (sContestResults->data->slidingTextBoxState == SLIDING_TEXT_OFFSCREEN)\n            gTasks[taskId].tState++;\n        break;\n    case 1:\n        if (++gTasks[taskId].tTimer == 31)\n        {\n            gTasks[taskId].tTimer = 0;\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 2:\n        for (i = 0; i < CONTESTANT_COUNT; i++)\n        {\n            u8 newTaskId = CreateTask(Task_DrawFinalStandingNumber, 10);\n            gTasks[newTaskId].tFinalStanding = gContestFinalStandings[i];\n            gTasks[newTaskId].tMonIndex = i;\n        }\n        gTasks[taskId].tState++;\n        break;\n    case 3:\n        if (sContestResults->data->numStandingsPrinted == CONTESTANT_COUNT)\n        {\n            if (++gTasks[taskId].tTimer == 31)\n            {\n                gTasks[taskId].tTimer = 0;\n                CreateTask(Task_StartHighlightWinnersBox, 10);\n                gTasks[taskId].tState++;\n                GET_CONTEST_WINNER_ID(i);\n                BounceMonIconInBox(i, 14);\n            }\n        }\n        break;\n    case 4:\n        if (++gTasks[taskId].tTimer == 21)\n        {\n            u8 winnerTextBuffer[100];\n            s16 x;\n            gTasks[taskId].tTimer = 0;\n            GET_CONTEST_WINNER_ID(i);\n            StringCopy(gStringVar1, gContestMons[i].trainerName);\n            ConvertInternationalContestantName(gStringVar1);\n            StringCopy(gStringVar2, gContestMons[i].nickname);\n            StringExpandPlaceholders(winnerTextBuffer, gText_ContestantsMonWon);\n            x = DrawResultsTextWindow(winnerTextBuffer, sContestResults->data->slidingTextBoxSpriteId);\n            StartTextBoxSlideIn(x, TEXT_BOX_Y, -1, 1088);\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 5:\n        gTasks[taskId].tState = 0;\n        gTasks[taskId].func = Task_ShowWinnerMonBanner;\n        break;\n    }",
  },
  "Task_ShowWinnerMonBanner": {
    callsTo: ["CreateSprite","CreateTask","GET_CONTEST_WINNER_ID","GetMonSpritePalStructFromOtIdPersonality","HandleLoadSpecialPokePic_2","HandleLoadSpecialPokePic_DontHandleDeoxys","LoadCompressedSpritePalette","LoadCompressedSpriteSheet","SetMultiuseSpriteTemplateToPokemon","WIN_RANGE"],
    taskTransitions: ["Task_SetSeenWinnerMon"],
    dataReads: ["tCounter","tState"],
    dataWrites: ["data[3]","tCounter","tState","tTimer"],
    lineCount: 92,
    bodyC: "int i;\n    u8 spriteId;\n    u16 species;\n    u32 otId;\n    u32 personality;\n    const struct CompressedSpritePalette *pokePal;\n\n    switch (gTasks[taskId].tState)\n    {\n    case 0:\n        gBattle_WIN0H = WIN_RANGE(0, DISPLAY_WIDTH);\n        gBattle_WIN0V = WIN_RANGE(DISPLAY_HEIGHT / 2, DISPLAY_HEIGHT / 2);\n\n        GET_CONTEST_WINNER_ID(i);\n        species = gContestMons[i].species;\n        personality = gContestMons[i].personality;\n        otId = gContestMons[i].otId;\n        if (i == gContestPlayerMonIndex)\n        {\n            HandleLoadSpecialPokePic_2(\n                &gMonFrontPicTable[species],\n                gMonSpritesGfxPtr->sprites.ptr[B_POSITION_OPPONENT_LEFT],\n                species,\n                personality);\n        }\n        else\n        {\n            HandleLoadSpecialPokePic_DontHandleDeoxys(\n                &gMonFrontPicTable[species],\n                gMonSpritesGfxPtr->sprites.ptr[B_POSITION_OPPONENT_LEFT],\n                species,\n                personality);\n        }\n\n        pokePal = GetMonSpritePalStructFromOtIdPersonality(species, otId, personality);\n        LoadCompressedSpritePalette(pokePal);\n        SetMultiuseSpriteTemplateToPokemon(species, B_POSITION_OPPONENT_LEFT);\n        gMultiuseSpriteTemplate.paletteTag = pokePal->tag;\n        spriteId = CreateSprite(&gMultiuseSpriteTemplate, DISPLAY_WIDTH + 32, DISPLAY_HEIGHT / 2, 10);\n        gSprites[spriteId].data[1] = species;\n        gSprites[spriteId].oam.priority = 0;\n        gSprites[spriteId].callback = SpriteCB_WinnerMonSlideIn;\n        sContestResults->data->winnerMonSpriteId = spriteId;\n        LoadCompressedSpriteSheet(&sSpriteSheet_Confetti);\n        LoadCompressedSpritePalette(&sSpritePalette_Confetti);\n        CreateTask(Task_CreateConfetti, 10);\n        gTasks[taskId].tState++;\n        break;\n    case 1:\n        if (++gTasks[taskId].data[3] == 1)\n        {\n            u8 counter;\n            gTasks[taskId].data[3] = 0;\n            gTasks[taskId].tCounter += 2;\n            if (gTasks[taskId].tCounter > 32)\n                gTasks[taskId].tCounter = 32;\n\n            counter = gTasks[taskId].tCounter;\n            gBattle_WIN0V = WIN_RANGE(DISPLAY_HEIGHT / 2 - counter, DISPLAY_HEIGHT / 2 + counter);\n            if (counter == 32)\n                gTasks[taskId].tState++;\n        }\n        break;\n    case 2:\n        if (sContestResults->data->winnerMonSlidingState == SLIDING_MON_ENTERED)\n            gTasks[taskId].tState++;\n        break;\n    case 3:\n        if (++gTasks[taskId].tTimer == 121)\n        {\n            gTasks[taskId].tTimer = 0;\n            gSprites[sContestResults->data->winnerMonSpriteId].callback = SpriteCB_WinnerMonSlideOut;\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 4:\n        if (sContestResults->data->winnerMonSlidingState == SLIDING_MON_EXITED)\n        {\n            u8 top = (gBattle_WIN0V >> 8);\n            top += 2;\n            if (top > DISPLAY_HEIGHT / 2)\n                top = DISPLAY_HEIGHT / 2;\n\n            gBattle_WIN0V = WIN_RANGE(top, DISPLAY_HEIGHT - top);\n            if (top == DISPLAY_HEIGHT / 2)\n                gTasks[taskId].tState++;\n        }\n        break;\n    case 5:\n        if (sContestResults->data->winnerMonSlidingState == SLIDING_MON_EXITED)\n        {\n            sContestResults->data->destroyConfetti = TRUE;\n            gTasks[taskId].tState = 0;\n            gTasks[taskId].func = Task_SetSeenWinnerMon;\n        }\n        break;\n    }",
  },
  "Task_SetSeenWinnerMon": {
    callsTo: ["GetSetPokedexFlag","JOY_NEW","SpeciesToNationalPokedexNum"],
    taskTransitions: ["Task_TryDisconnectLinkPartners"],
    dataWrites: ["data[10]"],
    externalChecks: { joyButtons: ["NEW:A_BUTTON"] },
    lineCount: 14,
    bodyC: "int i, nationalDexNum;\n\n    if (JOY_NEW(A_BUTTON))\n    {\n        if (!(gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK))\n        {\n            for (i = 0; i < CONTESTANT_COUNT; i++)\n            {\n                nationalDexNum = SpeciesToNationalPokedexNum(gContestMons[i].species);\n                GetSetPokedexFlag(nationalDexNum, FLAG_SET_SEEN);\n            }\n        }\n\n        gTasks[taskId].data[10] = 0;\n        gTasks[taskId].func = Task_TryDisconnectLinkPartners;\n    }",
  },
  "Task_TryDisconnectLinkPartners": {
    callsTo: ["SetCloseLinkCallback","ShowLinkResultsTextBox"],
    taskTransitions: ["Task_TrySetContestInterviewData","Task_WaitForLinkPartnersDisconnect"],
    dataReads: ["data[10]"],
    lineCount: 13,
    bodyC: "if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n    {\n        if (!gTasks[taskId].data[10])\n        {\n            ShowLinkResultsTextBox(gText_CommunicationStandby);\n            SetCloseLinkCallback();\n            gTasks[taskId].func = Task_WaitForLinkPartnersDisconnect;\n        }\n    }\n    else\n    {\n        gTasks[taskId].func = Task_TrySetContestInterviewData;\n    }",
  },
  "Task_WaitForLinkPartnersDisconnect": {
    callsTo: ["DestroyWirelessStatusIndicatorSprite","HideLinkResultsTextBox"],
    taskTransitions: ["Task_TrySetContestInterviewData"],
    lineCount: 7,
    bodyC: "if (!gReceivedRemoteLinkPlayers)\n    {\n        if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS)\n            DestroyWirelessStatusIndicatorSprite();\n\n        HideLinkResultsTextBox();\n        gTasks[taskId].func = Task_TrySetContestInterviewData;\n    }",
  },
  "Task_TrySetContestInterviewData": {
    callsTo: ["BeginHardwarePaletteFade","BravoTrainerPokemonProfile_BeforeInterview2"],
    taskTransitions: ["Task_EndShowContestResults"],
    lineCount: 4,
    bodyC: "if (!(gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK))\n        BravoTrainerPokemonProfile_BeforeInterview2(gContestFinalStandings[gContestPlayerMonIndex]);\n\n    BeginHardwarePaletteFade(0xFF, 0, 0, 16, 0);\n    gTasks[taskId].func = Task_EndShowContestResults;",
  },
  "Task_EndShowContestResults": {
    callsTo: ["BlendPalettes","DestroyTask","FreeAllWindowBuffers","FreeContestResults","SetGpuReg","SetMainCallback2"],
    cb2Transitions: ["CB2_ReturnToFieldContinueScriptPlayMapMusic"],
    dataReads: ["tTimer"],
    dataWrites: ["tTimer"],
    terminalMarkers: ["DestroyTask"],
    externalChecks: { paletteFade: true },
    lineCount: 23,
    bodyC: "if (!gPaletteFade.active)\n    {\n        if (gTasks[taskId].tTimer == 0)\n        {\n            DestroyTask(sContestResults->data->highlightWinnerTaskId);\n            BlendPalettes(PALETTES_BG, 16, RGB_BLACK);\n            gTasks[taskId].tTimer++;\n        }\n        else if (gTasks[taskId].tTimer == 1)\n        {\n            BlendPalettes(PALETTES_OBJECTS, 16, RGB_BLACK);\n            gTasks[taskId].tTimer++;\n        }\n        else\n        {\n            SetGpuReg(REG_OFFSET_BLDCNT, 0);\n            SetGpuReg(REG_OFFSET_BLDY, 0);\n            DestroyTask(taskId);\n            FreeAllWindowBuffers();\n            SetMainCallback2(CB2_ReturnToFieldContinueScriptPlayMapMusic);\n            FreeContestResults();\n        }\n    }",
  },
  "Task_SlideContestResultsBg": {
    lineCount: 6,
    bodyC: "gBattle_BG3_X += 2;\n    gBattle_BG3_Y += 1;\n    if (gBattle_BG3_X > 255)\n        gBattle_BG3_X -= 255;\n    if (gBattle_BG3_Y > 255)\n        gBattle_BG3_Y -= 255;",
  },
  "Task_FlashStarsAndHearts": {
    callsTo: ["BG_PLTT_ID","BlendPalette","RGB"],
    dataReads: ["tCoeff","tDecreasing"],
    dataWrites: ["tCoeff","tDecreasing","tDelay"],
    lineCount: 19,
    bodyC: "if (++gTasks[taskId].tDelay == 2)\n    {\n        gTasks[taskId].tDelay = 0;\n        if (!gTasks[taskId].tDecreasing)\n            gTasks[taskId].tCoeff++;\n        else\n            gTasks[taskId].tCoeff--;\n\n        if (gTasks[taskId].tCoeff == 16)\n            gTasks[taskId].tDecreasing = TRUE;\n        else if (gTasks[taskId].tCoeff == 0)\n            gTasks[taskId].tDecreasing = FALSE;\n\n        BlendPalette(BG_PLTT_ID(6) + 11, 1, gTasks[taskId].tCoeff, RGB(30, 22, 11));\n        BlendPalette(BG_PLTT_ID(6) + 8, 1, gTasks[taskId].tCoeff, RGB_WHITE);\n        BlendPalette(BG_PLTT_ID(6) + 14, 1, gTasks[taskId].tCoeff, RGB(30, 29, 29));\n    }\n\n    if (gTasks[taskId].tCoeff == 0)\n        sContestResults->data->pointsFlashing = FALSE;\n    else\n        sContestResults->data->pointsFlashing = TRUE;",
  },
  "Task_DrawFinalStandingNumber": {
    callsTo: ["DestroyTask","PlaySE","WriteSequenceToBgTilemapBuffer"],
    dataReads: ["tFinalStanding","tMonIndex","tState"],
    dataWrites: ["data[11]","tState"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 18,
    bodyC: "u16 firstTileNum;\n\n    if (gTasks[taskId].tState == 0)\n    {\n        gTasks[taskId].data[11] = (3 - gTasks[taskId].tFinalStanding) * 40;\n        gTasks[taskId].tState++;\n    }\n    else if (gTasks[taskId].tState == 1)\n    {\n        if (--gTasks[taskId].data[11] == -1)\n        {\n            firstTileNum = gTasks[taskId].tFinalStanding * 2 + 0x5043;\n            WriteSequenceToBgTilemapBuffer(2, firstTileNum, 1, gTasks[taskId].tMonIndex * 3 + 5, 2, 1, 17, 1);\n            WriteSequenceToBgTilemapBuffer(2, firstTileNum + 0x10, 1, gTasks[taskId].tMonIndex * 3 + 6, 2, 1, 17, 1);\n            sContestResults->data->numStandingsPrinted++;\n            DestroyTask(taskId);\n            PlaySE(SE_CONTEST_PLACE);\n        }\n    }",
  },
  "Task_StartHighlightWinnersBox": {
    callsTo: ["CopyToBgTilemapBufferRect_ChangePalette","GET_CONTEST_WINNER_ID"],
    taskTransitions: ["Task_HighlightWinnersBox"],
    dataWrites: ["data[10]","data[12]"],
    lineCount: 7,
    bodyC: "int i;\n    GET_CONTEST_WINNER_ID(i);\n    CopyToBgTilemapBufferRect_ChangePalette(2, i * 0xC0 + 0x100 + sContestResults->tilemapBuffers[2], 0, i * 3 + 4, 32, 3, 9);\n    gTasks[taskId].data[10] = i;\n    gTasks[taskId].data[12] = 1;\n    gTasks[taskId].func = Task_HighlightWinnersBox;\n    sContestResults->data->highlightWinnerTaskId = taskId;",
  },
  "Task_HighlightWinnersBox": {
    callsTo: ["BG_PLTT_ID","BlendPalette","RGB"],
    dataReads: ["data[12]"],
    dataWrites: ["data[11]","data[12]","data[13]"],
    lineCount: 15,
    bodyC: "if (++gTasks[taskId].data[11] == 1)\n    {\n        gTasks[taskId].data[11] = 0;\n        BlendPalette(BG_PLTT_ID(9) + 1, 1, gTasks[taskId].data[12], RGB(13, 28, 27));\n        if (gTasks[taskId].data[13] == 0)\n        {\n            if (++gTasks[taskId].data[12] == 16)\n                gTasks[taskId].data[13] = 1;\n        }\n        else\n        {\n            if (--gTasks[taskId].data[12] == 0)\n                gTasks[taskId].data[13] = 0;\n        }\n    }",
  },
  "Task_CreateConfetti": {
    callsTo: ["CreateSprite","DestroyTask","Random"],
    dataWrites: ["data[0]"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 15,
    bodyC: "if (++gTasks[taskId].data[0] == 5)\n    {\n        gTasks[taskId].data[0] = 0;\n        if (sContestResults->data->confettiCount < 40)\n        {\n            u8 spriteId = CreateSprite(&sSpriteTemplate_Confetti, (Random() % DISPLAY_WIDTH) - 20, 44, 5);\n            gSprites[spriteId].data[0] = Random() % 512;\n            gSprites[spriteId].data[1] = (Random() % 24) + 16;\n            gSprites[spriteId].data[2] = (Random() % 256) + 48;\n            gSprites[spriteId].oam.tileNum += Random() % 17;\n            sContestResults->data->confettiCount++;\n        }\n    }\n\n    if (sContestResults->data->destroyConfetti)\n        DestroyTask(taskId);",
  },
  "Task_BounceMonIconInBox": {
    callsTo: ["LoadContestMonIcon"],
    dataReads: ["tBounced","tMonIndex","tNumFrames","tSpecies","tTimer"],
    dataWrites: ["tTimer"],
    lineCount: 7,
    bodyC: "u8 monIndex = gTasks[taskId].tMonIndex;\n    if (gTasks[taskId].tTimer++ == gTasks[taskId].tNumFrames)\n    {\n        gTasks[taskId].tTimer = 0;\n        LoadContestMonIcon(gTasks[taskId].tSpecies, monIndex, gTasks[taskId].tBounced, FALSE, gContestMons[monIndex].personality);\n        gTasks[taskId].tBounced ^= 1;\n    }",
  },
  "Task_UpdateContestResultBar": {
    callsTo: ["DestroyTask","FillBgTilemapBufferRect_Palette0"],
    dataReads: ["tDecreasing","tMonId","tTarget"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 51,
    bodyC: "int i;\n    bool32 minMaxReached = FALSE;\n    bool32 targetReached = FALSE;\n    u8 monId = gTasks[taskId].tMonId;\n    s16 target = gTasks[taskId].tTarget;\n    s16 decreasing = gTasks[taskId].tDecreasing;\n\n     \n    if (decreasing)\n    {\n        if (sContestResults->data->barLength[monId] <= 0)\n            minMaxReached = TRUE;\n    }\n    else\n    {\n        if (sContestResults->data->barLength[monId] >= MAX_BAR_LENGTH)\n            minMaxReached = TRUE;\n    }\n\n    if (sContestResults->data->barLength[monId] == target)\n        targetReached = TRUE;\n\n    if (!targetReached)\n    {\n         \n        if (minMaxReached)\n            sContestResults->data->barLength[monId] = target;\n        else if (decreasing)\n            sContestResults->data->barLength[monId]--;\n        else\n            sContestResults->data->barLength[monId]++;\n    }\n\n     \n    if (!minMaxReached && !targetReached)\n    {\n        u8 tileOffset;\n        u16 tileNum;\n        for (i = 0; i < NUM_BAR_SEGMENTS; i++)\n        {\n            if (sContestResults->data->barLength[monId] >= (i + 1) * BAR_SEGMENT_LENGTH)\n                tileOffset = 8;  \n            else if (sContestResults->data->barLength[monId] >= i * BAR_SEGMENT_LENGTH)\n                tileOffset = sContestResults->data->barLength[monId] % 8;  \n            else\n                tileOffset = 0;  \n\n             \n             \n            if (tileOffset < 4)\n                tileNum = 0x504C + tileOffset;\n            else\n                tileNum = 0x5057 + tileOffset;\n\n            FillBgTilemapBufferRect_Palette0(2, tileNum, i + 7, monId * 3 + 6, 1, 1);\n        }\n    }\n\n    if (targetReached)\n    {\n        sContestResults->data->numBarsUpdating--;\n        DestroyTask(taskId);\n    }",
  },
  "Task_StartContest": {
    callsTo: ["DestroyTask","SetMainCallback2"],
    cb2Transitions: ["CB2_SetStartContestCallback"],
    terminalMarkers: ["DestroyTask"],
    externalChecks: { paletteFade: true },
    lineCount: 5,
    bodyC: "if (!gPaletteFade.active)\n    {\n        DestroyTask(taskId);\n        SetMainCallback2(CB2_SetStartContestCallback);\n    }",
  },
  "Task_StartShowContestResults": {
    callsTo: ["DestroyTask","SetMainCallback2"],
    cb2Transitions: ["CB2_StartShowContestResults"],
    terminalMarkers: ["DestroyTask"],
    externalChecks: { paletteFade: true },
    lineCount: 5,
    bodyC: "if (!gPaletteFade.active)\n    {\n        DestroyTask(taskId);\n        SetMainCallback2(CB2_StartShowContestResults);\n    }",
  },
  "Task_StartCommunication": {
    callsTo: ["CreateContestMonFromParty","SetTaskFuncWithFollowupFunc"],
    taskTransitions: ["Task_LinkContest_StartCommunicationEm"],
    lineCount: 10,
    bodyC: "if (gLinkContestFlags & LINK_CONTEST_FLAG_HAS_RS_PLAYER)\n    {\n        CreateContestMonFromParty(gContestMonPartyIndex);\n        SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateMonsRS, Task_StartCommunicateRngRS);\n    }\n    else\n    {\n        CreateContestMonFromParty(gContestMonPartyIndex);\n        gTasks[taskId].func = Task_LinkContest_StartCommunicationEm;\n    }",
  },
  "Task_StartCommunicateRngRS": {
    callsTo: ["SetTaskFuncWithFollowupFunc"],
    lineCount: 1,
    bodyC: "SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateRngRS, Task_StartCommunicateLeaderIdsRS);",
  },
  "Task_StartCommunicateLeaderIdsRS": {
    callsTo: ["SetTaskFuncWithFollowupFunc"],
    lineCount: 1,
    bodyC: "SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateLeaderIdsRS, Task_StartCommunicateCategoryRS);",
  },
  "Task_StartCommunicateCategoryRS": {
    callsTo: ["SetTaskFuncWithFollowupFunc"],
    lineCount: 1,
    bodyC: "SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateCategoryRS, Task_LinkContest_SetUpContestRS);",
  },
  "Task_LinkContest_SetUpContestRS": {
    callsTo: ["CalculateRound1Points","LinkContest_GetLeaderIndex","SetTaskFuncWithFollowupFunc","memset"],
    lineCount: 18,
    bodyC: "u8 i;\n    u8 categories[CONTESTANT_COUNT];\n    u8 leaderIds[CONTESTANT_COUNT];\n\n    memset(categories, 0, sizeof(categories));\n    memset(leaderIds, 0, sizeof(leaderIds));\n\n    for (i = 0; i < gNumLinkContestPlayers; i++)\n        categories[i] = gTasks[taskId].data[i + 1];\n\n     \n    for (i = 0; i < gNumLinkContestPlayers && categories[0] == categories[i]; i++)\n        ;\n\n    if (i == gNumLinkContestPlayers)\n        gSpecialVar_0x8004 = FALSE;  \n    else\n        gSpecialVar_0x8004 = TRUE;  \n\n    for (i = 0; i < gNumLinkContestPlayers; i++)\n        leaderIds[i] = gTasks[taskId].data[i + 5];\n\n    gContestLinkLeaderIndex = LinkContest_GetLeaderIndex(leaderIds);\n    CalculateRound1Points(gSpecialVar_ContestCategory);\n    SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateRound1Points, Task_LinkContest_CalculateTurnOrderRS);",
  },
  "Task_LinkContest_CalculateTurnOrderRS": {
    callsTo: ["SetTaskFuncWithFollowupFunc","SortContestants"],
    lineCount: 2,
    bodyC: "SortContestants(FALSE);\n    SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateTurnOrder, Task_LinkContest_FinalizeConnection);",
  },
  "Task_LinkContest_FinalizeConnection": {
    callsTo: ["DestroyTask","IsLinkTaskFinished","ScriptContext_Enable","SetDynamicWarp","StringGet_Nickname","UnlockPlayerFieldControls"],
    taskTransitions: ["Task_LinkContest_Disconnect"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 15,
    bodyC: "int i;\n\n    if (gSpecialVar_0x8004 == TRUE)\n    {\n         \n        if (IsLinkTaskFinished())\n            gTasks[taskId].func = Task_LinkContest_Disconnect;\n    }\n    else\n    {\n         \n        for (i = 0; i < CONTESTANT_COUNT; i++)\n            StringGet_Nickname(gContestMons[i].nickname);\n\n        DestroyTask(taskId);\n        SetDynamicWarp(0, gSaveBlock1Ptr->location.mapGroup, gSaveBlock1Ptr->location.mapNum, WARP_ID_NONE);\n        UnlockPlayerFieldControls();\n        ScriptContext_Enable();\n    }",
  },
  "Task_LinkContest_Disconnect": {
    callsTo: ["SetCloseLinkCallback"],
    taskTransitions: ["Task_LinkContest_WaitDisconnect"],
    lineCount: 2,
    bodyC: "SetCloseLinkCallback();\n    gTasks[taskId].func = Task_LinkContest_WaitDisconnect;",
  },
  "Task_LinkContest_WaitDisconnect": {
    callsTo: ["DestroyTask","ScriptContext_Enable","UnlockPlayerFieldControls"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 6,
    bodyC: "if (!gReceivedRemoteLinkPlayers)\n    {\n        DestroyTask(taskId);\n        UnlockPlayerFieldControls();\n        ScriptContext_Enable();\n    }",
  },
  "Task_ShowContestEntryMonPic": {
    callsTo: ["ClearToTransparentAndRemoveWindow","CreateWindowFromRect","DestroySprite","DestroyTask","FreeOamMatrix","FreeSpritePaletteByTag","GetSpritePaletteTagByPaletteNum","SetStandardWindowBorderStyle"],
    dataReads: ["data[5]"],
    terminalMarkers: ["DestroyTask","DestroySprite"],
    lineCount: 27,
    bodyC: "struct Task *task = &gTasks[taskId];\n    struct Sprite *sprite;\n\n    switch(task->data[0])\n    {\n    case 0:\n        task->data[0]++;\n        break;\n    case 1:\n        task->data[5] = CreateWindowFromRect(10, 3, 8, 8);\n        SetStandardWindowBorderStyle(task->data[5], TRUE);\n        task->data[0]++;\n        break;\n    case 2:\n        break;\n    case 3:\n        sprite = &gSprites[task->data[2]];\n        FreeSpritePaletteByTag(GetSpritePaletteTagByPaletteNum(sprite->oam.paletteNum));\n\n        if(sprite->oam.affineMode)\n            FreeOamMatrix(sprite->oam.matrixNum);\n\n        DestroySprite(sprite);\n        task->data[0]++;\n        break;\n    case 4:\n        ClearToTransparentAndRemoveWindow(gTasks[taskId].data[5]);\n        DestroyTask(taskId);\n        break;\n    }",
  },
  "Task_LinkContestWaitForConnection": {
    callsTo: ["DestroyTask","IsLinkTaskFinished","ScriptContext_Enable","SetLinkStandbyCallback"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 20,
    bodyC: "switch (gTasks[taskId].data[0])\n    {\n    case 0:\n        if (IsLinkTaskFinished())\n        {\n            SetLinkStandbyCallback();\n            gTasks[taskId].data[0]++;\n        }\n        break;\n    case 1:\n        gTasks[taskId].data[0]++;\n        break;\n    default:\n        if (IsLinkTaskFinished() == 1)\n        {\n            ScriptContext_Enable();\n            DestroyTask(taskId);\n        }\n        break;\n    }",
  },
} as const;

export const CB2S = {
  "CB2_StartShowContestResults": {
    callsTo: ["AllocContestResults","BeginNormalPaletteFade","CalculateContestantsResultData","CreateResultsTextWindowSprites","CreateTask","FreeAllSpritePalettes","InitContestResultsDisplay","LoadAllContestMonIconPalettes","LoadAllContestMonIcons","LoadAllContestMonNames","LoadContestResultsBgGfx","PlayBGM","ResetPaletteFade","ResetSpriteData","ResetTasks","ScanlineEffect_Clear","SetMainCallback2","SetVBlankCallback","TryCreateWirelessSprites","WIN_RANGE","memset"],
    cb2Transitions: ["CB2_ShowContestResults"],
    lineCount: 30,
    bodyC: "gPaletteFade.bufferTransferDisabled = TRUE;\n    SetVBlankCallback(NULL);\n    AllocContestResults();\n    InitContestResultsDisplay();\n    ScanlineEffect_Clear();\n    ResetPaletteFade();\n    ResetSpriteData();\n    ResetTasks();\n    FreeAllSpritePalettes();\n    LoadContestResultsBgGfx();\n    LoadAllContestMonIconPalettes();\n    LoadAllContestMonIcons(0, TRUE);\n    LoadAllContestMonNames();\n    memset(sContestResults->data, 0, sizeof(*sContestResults->data));\n    memset(sContestResults->monResults, 0, sizeof(*sContestResults->monResults));\n    CreateResultsTextWindowSprites();\n    TryCreateWirelessSprites();\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_BLACK);\n    gPaletteFade.bufferTransferDisabled = FALSE;\n    sContestResults->data->showResultsTaskId = CreateTask(Task_ShowContestResults, 5);\n    SetMainCallback2(CB2_ShowContestResults);\n    gBattle_WIN1H = WIN_RANGE(0, DISPLAY_WIDTH);\n    gBattle_WIN1V = WIN_RANGE(DISPLAY_HEIGHT - 32, DISPLAY_HEIGHT);\n    CreateTask(Task_SlideContestResultsBg, 20);\n    CalculateContestantsResultData();\n    if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS)\n        gPaletteFade.bufferTransferDisabled = TRUE;\n    else\n        PlayBGM(MUS_CONTEST_RESULTS);\n\n    SetVBlankCallback(VBlankCB_ShowContestResults);",
  },
  "CB2_ShowContestResults": {
    callsTo: ["AnimateSprites","BuildOamBuffer","CopyBgTilemapBufferToVram","RunTasks","UpdatePaletteFade"],
    externalChecks: { waitForVBlank: true },
    lineCount: 6,
    bodyC: "AnimateSprites();\n    BuildOamBuffer();\n    RunTasks();\n    UpdatePaletteFade();\n    CopyBgTilemapBufferToVram(1);\n    CopyBgTilemapBufferToVram(2);",
  },
  "CB2_SetStartContestCallback": {
    callsTo: ["SetMainCallback2"],
    cb2Transitions: ["CB2_StartContest"],
    lineCount: 1,
    bodyC: "SetMainCallback2(CB2_StartContest);",
  },
} as const;

export const SPRITE_CBS = {
  "SpriteCB_TextBoxSlideIn": {
    spriteTransitions: ["SpriteCB_EndTextBoxSlideIn"],
    lineCount: 14,
    bodyC: "int i;\n\n    s16 delta = sprite->sDistance + sprite->sSlideIncrement;\n    sprite->x -= delta >> 8;\n    sprite->sDistance += sprite->sSlideIncrement;\n    sprite->sDistance &= 0xFF;\n\n     \n    if (sprite->x < sprite->sTargetX)\n        sprite->x = sprite->sTargetX;\n\n    for (i = 0; i < 3; i++)\n    {\n        struct Sprite *sprite2 = &gSprites[sprite->data[i]];\n        sprite2->x = sprite->x + sprite->x2 + (i + 1) * 64;\n    }\n\n    if (sprite->x == sprite->sTargetX)\n        sprite->callback = SpriteCB_EndTextBoxSlideIn;",
  },
  "SpriteCB_EndTextBoxSlideIn": {
    callsTo: ["StartTextBoxSlideOut"],
    lineCount: 6,
    bodyC: "sContestResults->data->slidingTextBoxState = SLIDING_TEXT_ARRIVED;\n    if ((u16)sprite->sSlideOutTimer != 0xFFFF)\n    {\n        if (--sprite->sSlideOutTimer == -1)\n            StartTextBoxSlideOut(sprite->sSlideIncrement);\n    }",
  },
  "SpriteCB_TextBoxSlideOut": {
    callsTo: ["EndTextBoxSlideOut"],
    lineCount: 13,
    bodyC: "int i;\n    s16 delta;\n\n    delta = sprite->sDistance + sprite->sSlideIncrement;\n    sprite->x -= delta >> 8;\n    sprite->sDistance += sprite->sSlideIncrement;\n    sprite->sDistance &= 0xFF;\n    for (i = 0; i < 3; i++)\n    {\n        struct Sprite *sprite2 = &gSprites[sprite->data[i]];\n        sprite2->x = sprite->x + sprite->x2 + (i + 1) * 64;\n    }\n\n    if (sprite->x + sprite->x2 < -224)\n        EndTextBoxSlideOut(sprite);",
  },
  "SpriteCB_WinnerMonSlideIn": {
    callsTo: ["PlayCry_Normal"],
    spriteTransitions: ["SpriteCallbackDummy"],
    lineCount: 23,
    bodyC: "if (sprite->data[0] < 10)\n    {\n        if (++sprite->data[0] == 10)\n        {\n            PlayCry_Normal(sprite->data[1], 0);\n            sprite->data[1] = 0;\n        }\n    }\n    else\n    {\n        s16 delta = sprite->data[1] + 0x600;\n        sprite->x -= delta >> 8;\n        sprite->data[1] += 0x600;\n        sprite->data[1] &= 0xFF;\n        if (sprite->x < DISPLAY_WIDTH / 2)\n            sprite->x = DISPLAY_WIDTH / 2;\n\n        if (sprite->x == DISPLAY_WIDTH / 2)\n        {\n            sprite->callback = SpriteCallbackDummy;\n            sprite->data[1] = 0;\n            sContestResults->data->winnerMonSlidingState = SLIDING_MON_ENTERED;\n        }\n    }",
  },
  "SpriteCB_WinnerMonSlideOut": {
    spriteTransitions: ["SpriteCallbackDummy"],
    lineCount: 10,
    bodyC: "s16 delta = sprite->data[1] + 0x600;\n    sprite->x -= delta >> 8;\n    sprite->data[1] += + 0x600;\n    sprite->data[1] &= 0xFF;\n    if (sprite->x < -32)\n    {\n        sprite->callback = SpriteCallbackDummy;\n        sprite->invisible = TRUE;\n        sContestResults->data->winnerMonSlidingState = SLIDING_MON_EXITED;\n    }",
  },
  "SpriteCB_Confetti": {
    callsTo: ["DestroySprite","Sin"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 15,
    bodyC: "s16 delta;\n\n    sprite->data[3] += sprite->data[0];\n    sprite->x2 = Sin(sprite->data[3] >> 8, sprite->data[1]);\n    delta = sprite->data[4] + sprite->data[2];\n    sprite->x += delta >> 8;\n    sprite->data[4] += sprite->data[2];\n    sprite->data[4] &= 0xff;\n\n    sprite->y++;\n    if (sContestResults->data->destroyConfetti)\n        sprite->invisible = TRUE;\n\n    if (sprite->x > DISPLAY_WIDTH + 8 || sprite->y > 116)\n    {\n        DestroySprite(sprite);\n        sContestResults->data->confettiCount--;\n    }",
  },
} as const;
