// AUTO-GENERATED from src/contest.c by extract-decomp-task-machines.mjs
// Do not edit manually — re-run `npm run extract:task-machines` to refresh.
//
// Generated: 2026-04-26
// Stats: 56 Task_, 2 CB2_, 6 SpriteCB_

export const TASKS = {
  "Task_StartContestWaitFade": {
    taskTransitions: ["Task_TryStartLinkContest"],
    dataWrites: ["data[0]"],
    externalChecks: { paletteFade: true },
    lineCount: 5,
    bodyC: "if (!gPaletteFade.active)\n    {\n        gTasks[taskId].data[0] = 0;\n        gTasks[taskId].func = Task_TryStartLinkContest;\n    }",
  },
  "Task_TryStartLinkContest": {
    callsTo: ["ContestPrintLinkStandby","CreateTask","IsLinkTaskFinished","SetLinkStandbyCallback"],
    taskTransitions: ["TaskDummy1","Task_WaitToRaiseCurtainAtStart"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]"],
    externalChecks: { paletteFade: true },
    lineCount: 37,
    bodyC: "if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n    {\n        if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS)\n        {\n            switch (gTasks[taskId].data[0])\n            {\n            case 0:\n                ContestPrintLinkStandby();\n                gTasks[taskId].data[0]++;\n                 \n            case 1:\n                if (IsLinkTaskFinished())\n                {\n                    SetLinkStandbyCallback();\n                    gTasks[taskId].data[0]++;\n                }\n                return;\n            case 2:\n                if (IsLinkTaskFinished() != TRUE)\n                    return;\n                gTasks[taskId].data[0]++;\n                break;\n            }\n        }\n\n        if (!gPaletteFade.active)\n        {\n            gPaletteFade.bufferTransferDisabled = FALSE;\n            if (!(gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS))\n                ContestPrintLinkStandby();\n            CreateTask(Task_CommunicateMonIdxs, 0);\n            gTasks[taskId].data[0] = 0;\n            gTasks[taskId].func = TaskDummy1;\n        }\n    }\n    else\n    {\n        gTasks[taskId].func = Task_WaitToRaiseCurtainAtStart;\n    }",
  },
  "Task_CommunicateMonIdxs": {
    callsTo: ["SetTaskFuncWithFollowupFunc"],
    lineCount: 1,
    bodyC: "SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateMonIdxs, Task_EndCommunicateMonIdxs);",
  },
  "Task_EndCommunicateMonIdxs": {
    taskTransitions: ["Task_ReadyStartLinkContest"],
    dataWrites: ["data[0]"],
    lineCount: 2,
    bodyC: "gTasks[taskId].data[0] = 1;\n    gTasks[taskId].func = Task_ReadyStartLinkContest;",
  },
  "Task_ReadyStartLinkContest": {
    callsTo: ["DestroyTask","GetMultiplayerId"],
    taskTransitions: ["Task_WaitToRaiseCurtainAtStart"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 8,
    bodyC: "gTasks[taskId].data[0]--;\n    if (gTasks[taskId].data[0] <= 0)\n    {\n        GetMultiplayerId();   \n        DestroyTask(taskId);\n        gTasks[eContest.mainTaskId].func = Task_WaitToRaiseCurtainAtStart;\n        gRngValue = gContestRngValue;\n    }",
  },
  "Task_WaitToRaiseCurtainAtStart": {
    taskTransitions: ["Task_RaiseCurtainAtStart"],
    dataWrites: ["data[0]","data[1]"],
    externalChecks: { paletteFade: true },
    lineCount: 7,
    bodyC: "gPaletteFade.bufferTransferDisabled = FALSE;\n    if (!gPaletteFade.active)\n    {\n        gTasks[taskId].data[0] = 0;\n        gTasks[taskId].data[1] = 0;\n        gTasks[taskId].func = Task_RaiseCurtainAtStart;\n    }",
  },
  "Task_RaiseCurtainAtStart": {
    callsTo: ["GetGpuReg","PlaySE12WithPanning","SetGpuReg","SlideApplauseMeterIn","UpdateContestantBoxOrder"],
    taskTransitions: ["Task_DisplayAppealNumberText"],
    dataReads: ["data[0]","data[1]"],
    dataWrites: ["data[0]","data[1]"],
    lineCount: 40,
    bodyC: "switch (gTasks[taskId].data[0])\n    {\n    case 0:\n        if (gTasks[taskId].data[1]++ <= 60)\n            break;\n        gTasks[taskId].data[1] = 0;\n        PlaySE12WithPanning(SE_CONTEST_CURTAIN_RISE, 0);\n        gTasks[taskId].data[0]++;\n        break;\n    case 1:\n        *(s16 *)&gBattle_BG1_Y += 7;\n        if ((s16)gBattle_BG1_Y <= DISPLAY_HEIGHT)\n            break;\n        gTasks[taskId].data[0]++;\n        break;\n    case 2:\n        UpdateContestantBoxOrder();\n        gTasks[taskId].data[0]++;\n        break;\n    case 3:\n    {\n        u16 bg0Cnt = GetGpuReg(REG_OFFSET_BG0CNT);\n        u16 bg2Cnt = GetGpuReg(REG_OFFSET_BG2CNT);\n        ((struct BgCnt *)&bg0Cnt)->priority = 0;\n        ((struct BgCnt *)&bg2Cnt)->priority = 0;\n        SetGpuReg(REG_OFFSET_BG0CNT, bg0Cnt);\n        SetGpuReg(REG_OFFSET_BG2CNT, bg2Cnt);\n        SlideApplauseMeterIn();\n        gTasks[taskId].data[0]++;\n        break;\n    }\n    case 4:\n    default:\n        if (eContest.applauseMeterIsMoving)\n            break;\n        gTasks[taskId].data[0] = 0;\n        gTasks[taskId].data[1] = 0;\n        gTasks[taskId].func = Task_DisplayAppealNumberText;\n        break;\n    }",
  },
  "Task_DisplayAppealNumberText": {
    callsTo: ["ContestClearGeneralTextWindow","ContestDebugDoPrint","Contest_IsMonsTurnDisabled","Contest_RunTextPrinters","Contest_StartTextPrinter","ConvertIntToDecimalStringN","DmaCopy32Defvars","StringCopy","StringExpandPlaceholders"],
    taskTransitions: ["Task_TryShowMoveSelectScreen"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]"],
    lineCount: 24,
    bodyC: "if (gTasks[taskId].data[0] == 0)\n    {\n        gBattle_BG0_Y = 0;\n        gBattle_BG2_Y = 0;\n        ContestDebugDoPrint();\n        DmaCopy32Defvars(3, gPlttBufferUnfaded, eContestTempSave.cachedPlttBufferUnfaded, PLTT_SIZE);\n        ConvertIntToDecimalStringN(gStringVar1, eContest.appealNumber + 1, STR_CONV_MODE_LEFT_ALIGN, 1);\n        if (!Contest_IsMonsTurnDisabled(gContestPlayerMonIndex))\n            StringCopy(gDisplayedStringBattle, gText_AppealNumWhichMoveWillBePlayed);\n        else\n            StringCopy(gDisplayedStringBattle, gText_AppealNumButItCantParticipate);\n        ContestClearGeneralTextWindow();\n        StringExpandPlaceholders(gStringVar4, gDisplayedStringBattle);\n        Contest_StartTextPrinter(gStringVar4, TRUE);\n        gTasks[taskId].data[0]++;\n    }\n    else\n    {\n        if (!Contest_RunTextPrinters())\n        {\n            gTasks[taskId].data[0] = 0;\n            gTasks[taskId].func = Task_TryShowMoveSelectScreen;\n        }\n    }",
  },
  "Task_TryShowMoveSelectScreen": {
    callsTo: ["Contest_IsMonsTurnDisabled","JOY_NEW","PlaySE","SetBottomSliderHeartsInvisibility"],
    taskTransitions: ["Task_SelectedMove","Task_ShowMoveSelectScreen"],
    externalChecks: { joyButtons: ["NEW:A_BUTTON"] },
    lineCount: 13,
    bodyC: "if ((JOY_NEW(A_BUTTON)) || (gMain.newKeys == B_BUTTON))\n    {\n        PlaySE(SE_SELECT);\n        if (!Contest_IsMonsTurnDisabled(gContestPlayerMonIndex))\n        {\n            SetBottomSliderHeartsInvisibility(TRUE);\n            gTasks[taskId].func = Task_ShowMoveSelectScreen;\n        }\n        else\n        {\n             \n            gTasks[taskId].func = Task_SelectedMove;\n        }\n    }",
  },
  "Task_ShowMoveSelectScreen": {
    callsTo: ["AreMovesContestCombo","Contest_PrintTextToBg0WindowAt","DrawMoveSelectArrow","FillWindowPixelBuffer","IsContestantAllowedToCombo","PIXEL_FILL","PrintContestMoveDescription","StringCopy"],
    taskTransitions: ["Task_HandleMoveSelectInput"],
    lineCount: 28,
    bodyC: "u8 i;\n    u8 moveName[32];\n\n    gBattle_BG0_Y = DISPLAY_HEIGHT;\n    gBattle_BG2_Y = DISPLAY_HEIGHT;\n\n    for (i = 0; i < MAX_MON_MOVES; i++)\n    {\n        u16 move = gContestMons[gContestPlayerMonIndex].moves[i];\n        u8 *moveNameBuffer = moveName;\n\n        if (eContestantStatus[gContestPlayerMonIndex].prevMove != MOVE_NONE\n            && IsContestantAllowedToCombo(gContestPlayerMonIndex)\n            && AreMovesContestCombo(eContestantStatus[gContestPlayerMonIndex].prevMove, move)\n            && eContestantStatus[gContestPlayerMonIndex].hasJudgesAttention)\n        {\n             \n            moveNameBuffer = StringCopy(moveName, gText_ColorLightShadowDarkGray);\n        }\n        else if (move != MOVE_NONE\n                 && eContestantStatus[gContestPlayerMonIndex].prevMove == move\n                 && gContestMoves[move].effect != CONTEST_EFFECT_REPETITION_NOT_BORING)\n        {\n             \n            moveNameBuffer = StringCopy(moveName, gText_ColorBlue);\n        }\n        moveNameBuffer = StringCopy(moveNameBuffer, gMoveNames[move]);\n\n        FillWindowPixelBuffer(i + MOVE_WINDOWS_START, PIXEL_FILL(0));\n        Contest_PrintTextToBg0WindowAt(i + MOVE_WINDOWS_START, moveName, 5, 1, FONT_NARROW);\n    }\n\n    DrawMoveSelectArrow(eContest.playerMoveChoice);\n    PrintContestMoveDescription(gContestMons[gContestPlayerMonIndex].moves[eContest.playerMoveChoice]);\n    gTasks[taskId].func = Task_HandleMoveSelectInput;",
  },
  "Task_HandleMoveSelectInput": {
    callsTo: ["ContestClearGeneralTextWindow","Contest_IsMonsTurnDisabled","Contest_StartTextPrinter","ConvertIntToDecimalStringN","DrawMoveSelectArrow","EraseMoveSelectArrow","JOY_NEW","PlaySE","PrintContestMoveDescription","SetBottomSliderHeartsInvisibility","StringCopy","StringExpandPlaceholders"],
    taskTransitions: ["Task_SelectedMove","Task_TryShowMoveSelectScreen"],
    externalChecks: { joyButtons: ["NEW:A_BUTTON"] },
    lineCount: 58,
    bodyC: "u8 numMoves = 0;\n    s32 i;\n\n    for (i = 0; i < MAX_MON_MOVES; i++)\n    {\n        if (gContestMons[gContestPlayerMonIndex].moves[i] != MOVE_NONE)\n            numMoves++;\n    }\n\n    if (JOY_NEW(A_BUTTON))\n    {\n        PlaySE(SE_SELECT);\n        gTasks[taskId].func = Task_SelectedMove;\n    }\n    else\n    {\n        switch (gMain.newAndRepeatedKeys)\n        {\n        case B_BUTTON:\n             \n            PlaySE(SE_SELECT);\n            SetBottomSliderHeartsInvisibility(FALSE);\n            ConvertIntToDecimalStringN(gStringVar1, eContest.appealNumber + 1, STR_CONV_MODE_LEFT_ALIGN, 1);\n            if (!Contest_IsMonsTurnDisabled(gContestPlayerMonIndex))\n                StringCopy(gDisplayedStringBattle, gText_AppealNumWhichMoveWillBePlayed);\n            else\n                StringCopy(gDisplayedStringBattle, gText_AppealNumButItCantParticipate);\n            ContestClearGeneralTextWindow();\n            StringExpandPlaceholders(gStringVar4, gDisplayedStringBattle);\n            Contest_StartTextPrinter(gStringVar4, FALSE);\n            gBattle_BG0_Y = 0;\n            gBattle_BG2_Y = 0;\n            gTasks[taskId].func = Task_TryShowMoveSelectScreen;\n            break;\n        case DPAD_LEFT:\n        case DPAD_RIGHT:\n            break;\n        case DPAD_UP:\n            EraseMoveSelectArrow(eContest.playerMoveChoice);\n            if (eContest.playerMoveChoice == 0)\n                eContest.playerMoveChoice = numMoves - 1;\n            else\n                eContest.playerMoveChoice--;\n            DrawMoveSelectArrow(eContest.playerMoveChoice);\n            PrintContestMoveDescription(gContestMons[gContestPlayerMonIndex].moves[eContest.playerMoveChoice]);\n            if (numMoves > 1)\n                PlaySE(SE_SELECT);\n            break;\n        case DPAD_DOWN:\n            EraseMoveSelectArrow(eContest.playerMoveChoice);\n            if (eContest.playerMoveChoice == numMoves - 1)\n                eContest.playerMoveChoice = 0;\n            else\n                eContest.playerMoveChoice++;\n            DrawMoveSelectArrow(eContest.playerMoveChoice);\n            PrintContestMoveDescription(gContestMons[gContestPlayerMonIndex].moves[eContest.playerMoveChoice]);\n            if (numMoves > 1)\n                PlaySE(SE_SELECT);\n            break;\n        }\n    }",
  },
  "Task_SelectedMove": {
    callsTo: ["ContestPrintLinkStandby","CreateTask","GetAllChosenMoves","GetChosenMove","SetBottomSliderHeartsInvisibility","SetTaskFuncWithFollowupFunc"],
    taskTransitions: ["TaskDummy1","Task_HideMoveSelectScreen"],
    lineCount: 16,
    bodyC: "if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n    {\n        u16 move = GetChosenMove(gContestPlayerMonIndex);\n        u8 taskId2;\n\n        eContestantStatus[gContestPlayerMonIndex].currMove = move;\n        taskId2 = CreateTask(Task_LinkContest_CommunicateMoveSelections, 0);\n        SetTaskFuncWithFollowupFunc(taskId2, Task_LinkContest_CommunicateMoveSelections, Task_EndCommunicateMoveSelections);\n        gTasks[taskId].func = TaskDummy1;\n        ContestPrintLinkStandby();\n        SetBottomSliderHeartsInvisibility(FALSE);\n    }\n    else\n    {\n        GetAllChosenMoves();\n        gTasks[taskId].func = Task_HideMoveSelectScreen;\n    }",
  },
  "Task_EndCommunicateMoveSelections": {
    callsTo: ["DestroyTask"],
    taskTransitions: ["Task_HideMoveSelectScreen"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 2,
    bodyC: "DestroyTask(taskId);\n    gTasks[eContest.mainTaskId].func = Task_HideMoveSelectScreen;",
  },
  "Task_HideMoveSelectScreen": {
    callsTo: ["ContestClearGeneralTextWindow","Contest_SetBgCopyFlags","CopyWindowToVram","DmaCopy32Defvars","FillWindowPixelBuffer","LoadPalette","PIXEL_FILL","PutWindowTilemap","SetBottomSliderHeartsInvisibility"],
    taskTransitions: ["Task_HideApplauseMeterForAppealStart"],
    dataWrites: ["data[0]","data[1]"],
    lineCount: 17,
    bodyC: "s32 i;\n\n    ContestClearGeneralTextWindow();\n    gBattle_BG0_Y = 0;\n    gBattle_BG2_Y = 0;\n    SetBottomSliderHeartsInvisibility(FALSE);\n\n    for (i = 0; i < MAX_MON_MOVES; i++)\n    {\n        FillWindowPixelBuffer(MOVE_WINDOWS_START + i, PIXEL_FILL(0));\n        PutWindowTilemap(MOVE_WINDOWS_START + i);\n        CopyWindowToVram(MOVE_WINDOWS_START + i, COPYWIN_GFX);\n    }\n    Contest_SetBgCopyFlags(0);\n     \n    DmaCopy32Defvars(3, gPlttBufferFaded, eContestTempSave.cachedPlttBufferFaded, PLTT_SIZE);\n    LoadPalette(eContestTempSave.cachedPlttBufferUnfaded, 0, PLTT_SIZE);\n    gTasks[taskId].data[0] = 0;\n    gTasks[taskId].data[1] = 0;\n    gTasks[taskId].func = Task_HideApplauseMeterForAppealStart;",
  },
  "Task_HideApplauseMeterForAppealStart": {
    callsTo: ["AnimateSliderHearts","SlideApplauseMeterOut"],
    taskTransitions: ["Task_WaitHideApplauseMeterForAppealStart"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]","data[1]"],
    lineCount: 10,
    bodyC: "if (++gTasks[taskId].data[0] > 2)\n    {\n        gTasks[taskId].data[0] = 0;\n        if (++gTasks[taskId].data[1] == 2)\n        {\n            SlideApplauseMeterOut();\n            AnimateSliderHearts(SLIDER_HEART_ANIM_DISAPPEAR);\n            gTasks[taskId].func = Task_WaitHideApplauseMeterForAppealStart;\n        }\n    }",
  },
  "Task_WaitHideApplauseMeterForAppealStart": {
    taskTransitions: ["Task_AppealSetup"],
    lineCount: 2,
    bodyC: "if (!eContest.applauseMeterIsMoving && !eContest.sliderHeartsAnimating)\n        gTasks[taskId].func = Task_AppealSetup;",
  },
  "Task_AppealSetup": {
    callsTo: ["GetChosenMove","IsPlayerLinkLeader"],
    taskTransitions: ["Task_DoAppeals"],
    dataReads: ["data[0]"],
    dataWrites: ["tState"],
    lineCount: 15,
    bodyC: "if (++gTasks[taskId].data[0] > 19)\n    {\n        eContest.turnNumber = 0;\n        eContest.unusedRng = gRngValue;\n        if ((gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK) && IsPlayerLinkLeader())\n        {\n            s32 i;\n\n            for (i = 0; i + gNumLinkContestPlayers < CONTESTANT_COUNT; i++)\n            {\n                eContestantStatus[gNumLinkContestPlayers + i].currMove = GetChosenMove(gNumLinkContestPlayers + i);\n            }\n        }\n        gTasks[taskId].tState = APPEALSTATE_START_TURN;\n        gTasks[taskId].func = Task_DoAppeals;\n    }",
  },
  "Task_DoAppeals": {
    callsTo: ["AnimateAudience","BlendAudienceBackground","BlinkContestantBox","CalculateAppealMoveImpact","ClearMoveAnimData","ContestClearGeneralTextWindow","ContestDebugDoPrint","ContestDebugPrintBitStrings","ContestPrintLinkStandby","Contest_RunTextPrinters","Contest_StartTextPrinter","CreateContestantBoxBlinkSprites","CreateContestantSprite","CreateTask","DestroySprite","DoJudgeSpeechBubble","DoMoveAnim","DrawStatusSymbol","DrawStatusSymbols","DrawUnnervedSymbols","FreeSpriteOamMatrix","IsPlayerLinkLeader","PlayFanfare","PlaySE","PrintAppealMoveResultText","SanitizeMove","SetContestLiveUpdateFlags","SetMoveAnimAttackerData","SetMoveSpecificAnimData","SetMoveTargetPosition","SetTaskFuncWithFollowupFunc","ShowAndUpdateApplauseMeter","ShowHideNextTurnGfx","SlideApplauseMeterOut","StartStopFlashJudgeAttentionEye","StopFlashJudgeAttentionEye","StringCopy","StringExpandPlaceholders","UpdateAppealHearts","UpdateApplauseMeter","UpdateConditionStars","gAnimScriptCallback","memset"],
    taskTransitions: ["Task_FinishRoundOfAppeals"],
    dataReads: ["data[11]","data[1]","tCounter","tMonSpriteId","tState"],
    dataWrites: ["data[11]","data[1]","tCounter","tMonSpriteId","tState"],
    terminalMarkers: ["DestroySprite","FreeSpriteOamMatrix"],
    externalChecks: { paletteFade: true },
    lineCount: 697,
    bodyC: "u8 spriteId;\n    s32 i;\n    u8 contestant = eContest.currentContestant;\n    s8 r3;\n\n    switch (gTasks[taskId].tState)\n    {\n    case APPEALSTATE_START_TURN:\n        ContestDebugDoPrint();\n        for (i = 0; eContest.turnNumber != eContestAppealResults.turnOrder[i]; i++)\n            ;\n        eContest.currentContestant = i;\n        contestant = eContest.currentContestant;\n        if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n        {\n            u8 taskId2;\n\n            eContest.waitForLink = TRUE;\n            if (IsPlayerLinkLeader())\n                CalculateAppealMoveImpact(eContest.currentContestant);\n            taskId2 = CreateTask(Task_LinkContest_CommunicateAppealsState, 0);\n            SetTaskFuncWithFollowupFunc(taskId2, Task_LinkContest_CommunicateAppealsState, Task_EndWaitForLink);\n            ContestPrintLinkStandby();\n            gTasks[taskId].tState = APPEALSTATE_WAIT_LINK;\n        }\n        else\n        {\n            CalculateAppealMoveImpact(eContest.currentContestant);\n            gTasks[taskId].tState = APPEALSTATE_CHECK_SKIP_TURN;\n        }\n        return;\n    case APPEALSTATE_WAIT_LINK:\n        if (!eContest.waitForLink)\n            gTasks[taskId].tState = APPEALSTATE_CHECK_SKIP_TURN;\n        return;\n    case APPEALSTATE_CHECK_SKIP_TURN:\n        SetContestLiveUpdateFlags(contestant);\n        ContestDebugPrintBitStrings();\n        if (eContestantStatus[contestant].numTurnsSkipped != 0\n            || eContestantStatus[contestant].noMoreTurns)\n        {\n            gTasks[taskId].tState = APPEALSTATE_PRINT_SKIP_TURN_MSG;\n        }\n        else\n        {\n            ContestClearGeneralTextWindow();\n            gTasks[taskId].tCounter = 0;\n            gTasks[taskId].tState = APPEALSTATE_SLIDE_MON_IN;\n        }\n        return;\n    case APPEALSTATE_SLIDE_MON_IN:\n        for (i = 0; i < CONTESTANT_COUNT; i++)\n            gBattleMonForms[i] = 0;\n        memset(gContestResources->moveAnim, 0, sizeof(*gContestResources->moveAnim));\n        SetMoveAnimAttackerData(eContest.currentContestant);\n        spriteId = CreateContestantSprite(\n            gContestMons[eContest.currentContestant].species,\n            gContestMons[eContest.currentContestant].otId,\n            gContestMons[eContest.currentContestant].personality,\n            eContest.currentContestant);\n        gSprites[spriteId].x2 = 120;\n        gSprites[spriteId].callback = SpriteCB_MonSlideIn;\n        gTasks[taskId].tMonSpriteId = spriteId;\n        gBattlerSpriteIds[gBattlerAttacker] = spriteId;\n        BlinkContestantBox(CreateContestantBoxBlinkSprites(eContest.currentContestant), FALSE);\n        gTasks[taskId].tState = APPEALSTATE_WAIT_SLIDE_MON;\n        return;\n    case APPEALSTATE_WAIT_SLIDE_MON:\n        spriteId = gTasks[taskId].tMonSpriteId;\n        if (gSprites[spriteId].callback == SpriteCallbackDummy)\n        {\n             \n            if (!eContestGfxState[contestant].boxBlinking)\n                gTasks[taskId].tState = APPEALSTATE_PRINT_USED_MOVE_MSG;\n        }\n        return;\n    case APPEALSTATE_PRINT_USED_MOVE_MSG:\n        if (eContestantStatus[contestant].nervous)\n        {\n            gTasks[taskId].tState = APPEALSTATE_PRINT_TOO_NERVOUS_MSG;\n        }\n        else\n        {\n            ContestClearGeneralTextWindow();\n            StringCopy(gStringVar1, gContestMons[contestant].nickname);\n            if (eContestantStatus[contestant].currMove < MOVES_COUNT)\n                StringCopy(gStringVar2, gMoveNames[eContestantStatus[contestant].currMove]);\n            else\n                StringCopy(gStringVar2, sInvalidContestMoveNames[eContestantStatus[contestant].moveCategory]);\n            StringExpandPlaceholders(gStringVar4, gText_MonAppealedWithMove);\n            Contest_StartTextPrinter(gStringVar4, TRUE);\n            gTasks[taskId].tState = APPEALSTATE_WAIT_USED_MOVE_MSG;\n        }\n        return;\n    case APPEALSTATE_WAIT_USED_MOVE_MSG:\n        if (!Contest_RunTextPrinters())\n        {\n            eContest.moveAnimTurnCount = 0;\n            gTasks[taskId].tState = APPEALSTATE_MOVE_ANIM;\n        }\n        return;\n    case APPEALSTATE_MOVE_ANIM:\n        {\n            u16 move = SanitizeMove(eContestantStatus[eContest.currentContestant].currMove);\n            SetMoveSpecificAnimData(eContest.currentContestant);\n            SetMoveAnimAttackerData(eContest.currentContestant);\n            SetMoveTargetPosition(move);\n            DoMoveAnim(move);\n            gTasks[taskId].tState = APPEALSTATE_WAIT_MOVE_ANIM;\n        }\n        return;\n    case APPEALSTATE_WAIT_MOVE_ANIM:\n        gAnimScriptCallback();\n        if (!gAnimScriptActive)\n        {\n            ClearMoveAnimData(contestant);\n            if (eContest.moveAnimTurnCount != 0)\n            {\n                gTasks[taskId].tCounter = 0;\n                gTasks[taskId].tState = APPEALSTATE_MOVE_ANIM_MULTITURN;\n            }\n            else\n            {\n                if (!eContestantStatus[contestant].hasJudgesAttention)\n                    StopFlashJudgeAttentionEye(contestant);\n                DrawUnnervedSymbols();\n                gTasks[taskId].tState = APPEALSTATE_TRY_PRINT_MOVE_RESULT;\n            }\n        }\n        return;\n    case APPEALSTATE_MOVE_ANIM_MULTITURN:\n        if (gTasks[taskId].tCounter++ > 30)\n        {\n            gTasks[taskId].tCounter = 0;\n            gTasks[taskId].tState = APPEALSTATE_MOVE_ANIM;\n        }\n        return;\n    case APPEALSTATE_TRY_PRINT_MOVE_RESULT:\n        gTasks[taskId].data[1] = 0;\n        if (eContestantStatus[contestant].effectStringId != CONTEST_STRING_NONE)\n        {\n            PrintAppealMoveResultText(contestant, eContestantStatus[contestant].effectStringId);\n            eContestantStatus[contestant].effectStringId = CONTEST_STRING_NONE;\n            gTasks[taskId].tState = APPEALSTATE_WAIT_MOVE_RESULT_MSG;\n        }\n        else\n        {\n            if (eContestantStatus[contestant].effectStringId2 != CONTEST_STRING_NONE)\n            {\n                for (i = 0; i < CONTESTANT_COUNT; i++)\n                {\n                    if (i != contestant && eContestantStatus[i].effectStringId != CONTEST_STRING_NONE)\n                        break;\n                }\n                if (i == CONTESTANT_COUNT)\n                {\n                    PrintAppealMoveResultText(contestant, eContestantStatus[contestant].effectStringId2);\n                    eContestantStatus[contestant].effectStringId2 = CONTEST_STRING_NONE;\n                    gTasks[taskId].tState = APPEALSTATE_WAIT_MOVE_RESULT_MSG;\n                }\n                else\n                {\n                    gTasks[taskId].tState = APPEALSTATE_CHECK_TURN_ORDER_MOD;\n                }\n            }\n            else\n            {\n                gTasks[taskId].tState = APPEALSTATE_CHECK_TURN_ORDER_MOD;\n            }\n        }\n        return;\n    case APPEALSTATE_WAIT_MOVE_RESULT_MSG:\n        if (!Contest_RunTextPrinters())\n            gTasks[taskId].tState = APPEALSTATE_TRY_PRINT_MOVE_RESULT;\n        return;\n    case APPEALSTATE_CHECK_TURN_ORDER_MOD:\n        if (eContestantStatus[contestant].turnOrderModAction == 1)\n        {\n            DoJudgeSpeechBubble(JUDGE_SYMBOL_NUMBER_ONE);\n        }\n        else if (eContestantStatus[contestant].turnOrderModAction == 2)\n        {\n            DoJudgeSpeechBubble(JUDGE_SYMBOL_NUMBER_FOUR);\n        }\n        else if (eContestantStatus[contestant].turnOrderModAction == 3)\n        {\n            DoJudgeSpeechBubble(JUDGE_SYMBOL_QUESTION_MARK);\n        }\n        else\n        {\n            gTasks[taskId].tState = APPEALSTATE_TRY_SHOW_NEXT_TURN_GFX;\n            return;\n        }\n        gTasks[taskId].tState = APPEALSTATE_WAIT_JUDGE_TURN_ORDER;\n        return;\n    case APPEALSTATE_WAIT_JUDGE_TURN_ORDER:\n        if (!eContest.waitForJudgeSpeechBubble)\n            gTasks[taskId].tState = APPEALSTATE_TRY_SHOW_NEXT_TURN_GFX;\n        return;\n    case APPEALSTATE_TRY_SHOW_NEXT_TURN_GFX:\n        ShowHideNextTurnGfx(TRUE);\n        gTasks[taskId].tState = APPEALSTATE_UPDATE_MOVE_USERS_HEARTS;\n        return;\n    case APPEALSTATE_UPDATE_MOVE_USERS_HEARTS:\n        UpdateAppealHearts(0, eContestantStatus[contestant].appeal, contestant);\n        gTasks[taskId].tState = APPEALSTATE_WAIT_MOVE_USERS_HEARTS;\n        return;\n    case APPEALSTATE_WAIT_MOVE_USERS_HEARTS:\n        if (!eContestGfxState[eContest.currentContestant].updatingAppealHearts)\n            gTasks[taskId].tState = APPEALSTATE_TRY_JUDGE_STAR;\n        return;\n    case APPEALSTATE_TRY_JUDGE_STAR:\n        if (eContestantStatus[contestant].conditionMod == CONDITION_GAIN)\n            DoJudgeSpeechBubble(JUDGE_SYMBOL_STAR);\n        gTasks[taskId].tState = APPEALSTATE_WAIT_JUDGE_STAR;\n        return;\n    case APPEALSTATE_WAIT_JUDGE_STAR:\n        if (!eContest.waitForJudgeSpeechBubble)\n            gTasks[taskId].tState = APPEALSTATE_UPDATE_MOVE_USERS_STARS;\n        return;\n    case APPEALSTATE_UPDATE_MOVE_USERS_STARS:\n        if (UpdateConditionStars(contestant, TRUE))\n        {\n            gTasks[taskId].tCounter = 0;\n            gTasks[taskId].tState = APPEALSTATE_WAIT_MOVE_USERS_STARS;\n        }\n        else\n        {\n            gTasks[taskId].tState = APPEALSTATE_UPDATE_MOVE_USERS_STATUS;\n        }\n        return;\n    case APPEALSTATE_WAIT_MOVE_USERS_STARS:\n        if (++gTasks[taskId].tCounter > 20)\n        {\n            gTasks[taskId].tCounter = 0;\n            gTasks[taskId].tState = APPEALSTATE_UPDATE_MOVE_USERS_STATUS;\n        }\n        return;\n    case APPEALSTATE_UPDATE_MOVE_USERS_STATUS:\n        if (DrawStatusSymbol(contestant))\n            PlaySE(SE_CONTEST_ICON_CHANGE);\n        gTasks[taskId].tState = APPEALSTATE_UPDATE_OPPONENTS;\n        return;\n    case APPEALSTATE_UPDATE_OPPONENTS:\n        gTasks[taskId].data[1] = 0;\n        gTasks[taskId].tState = APPEALSTATE_UPDATE_OPPONENT;\n        return;\n    case APPEALSTATE_UPDATE_OPPONENT:\n        {\n             \n            s32 j = 0;\n\n            r3 = FALSE;  \n            for (i = gTasks[taskId].data[1]; i < CONTESTANT_COUNT; i++)\n            {\n                r3 = FALSE;\n                for (j = 0; j < CONTESTANT_COUNT; j++)\n                {\n                    if (j != contestant && gContestantTurnOrder[j] == i\n                        && eContestantStatus[j].effectStringId != CONTEST_STRING_NONE)\n                    {\n                        r3 = TRUE;\n                        break;\n                    }\n                }\n                if (r3)\n                    break;\n            }\n            if (r3)\n            {\n                 \n                gTasks[taskId].data[1] = gContestantTurnOrder[j];\n                PrintAppealMoveResultText(j, eContestantStatus[j].effectStringId);\n                eContestantStatus[j].effectStringId = CONTEST_STRING_NONE;\n                gTasks[taskId].tState = APPEALSTATE_WAIT_OPPONENT_RESPONSE_MSG;\n            }\n            else\n            {\n                 \n                gTasks[taskId].data[1] = 0;\n                gTasks[taskId].tCounter = 0;\n                gTasks[taskId].tState = APPEALSTATE_TRY_PRINT_SKIP_NEXT_TURN_MSG;\n                DrawStatusSymbols();\n            }\n        }\n        return;\n    case APPEALSTATE_WAIT_OPPONENT_RESPONSE_MSG:\n         \n         \n        if (!Contest_RunTextPrinters())\n            gTasks[taskId].tState = APPEALSTATE_UPDATE_OPPONENT_HEARTS;\n        return;\n    case APPEALSTATE_UPDATE_OPPONENT_HEARTS:\n        for (i = 0; gTasks[taskId].data[1] != gContestantTurnOrder[i]; i++)\n            ;\n        UpdateAppealHearts(eContestantStatus[i].appeal + eContestantStatus[i].jam, -eContestantStatus[i].jam, i);\n        gTasks[taskId].tState = APPEALSTATE_WAIT_OPPONENT_HEARTS;\n        return;\n    case APPEALSTATE_WAIT_OPPONENT_HEARTS:\n        for (i = 0; gTasks[taskId].data[1] != gContestantTurnOrder[i]; i++)\n            ;\n        if (!eContestGfxState[i].updatingAppealHearts)\n            gTasks[taskId].tState = APPEALSTATE_UPDATE_OPPONENT_STARS;\n        return;\n    case APPEALSTATE_UPDATE_OPPONENT_STARS:\n        for (i = 0; gTasks[taskId].data[1] != gContestantTurnOrder[i]; i++)\n            ;\n        if (UpdateConditionStars(i, TRUE))\n        {\n            gTasks[taskId].tCounter = 0;\n            gTasks[taskId].tState = APPEALSTATE_WAIT_OPPONENT_STARS;\n        }\n        else\n        {\n            gTasks[taskId].tState = APPEALSTATE_UPDATE_OPPONENT_STATUS;\n        }\n        return;\n    case APPEALSTATE_WAIT_OPPONENT_STARS:\n        if (++gTasks[taskId].tCounter > 20)\n        {\n            gTasks[taskId].tCounter = 0;\n            gTasks[taskId].tState = APPEALSTATE_UPDATE_OPPONENT_STATUS;\n        }\n        return;\n    case APPEALSTATE_UPDATE_OPPONENT_STATUS:\n        for (i = 0; i < CONTESTANT_COUNT; i++)\n        {\n            if (gContestantTurnOrder[i] == gTasks[taskId].data[1])\n                break;\n        }\n        if (DrawStatusSymbol(i))\n            PlaySE(SE_CONTEST_ICON_CHANGE);\n        else\n            PlaySE(SE_CONTEST_ICON_CLEAR);\n        if (eContestantStatus[i].judgesAttentionWasRemoved)\n        {\n            StopFlashJudgeAttentionEye(i);\n            eContestantStatus[i].judgesAttentionWasRemoved = FALSE;\n        }\n        gTasks[taskId].data[1]++;\n        gTasks[taskId].tState = APPEALSTATE_UPDATE_OPPONENT;\n        return;\n    case APPEALSTATE_TRY_PRINT_SKIP_NEXT_TURN_MSG:\n        if (gTasks[taskId].tCounter++ > 9)\n        {\n            gTasks[taskId].tCounter = 0;\n            if (eContestantStatus[contestant].numTurnsSkipped != 0\n                || eContestantStatus[contestant].turnSkipped)\n            {\n                ContestClearGeneralTextWindow();\n                StringCopy(gStringVar1, gContestMons[contestant].nickname);\n                StringExpandPlaceholders(gStringVar4, gText_MonCantAppealNextTurn);\n                Contest_StartTextPrinter(gStringVar4, TRUE);\n            }\n            gTasks[taskId].tState = APPEALSTATE_WAIT_SKIP_NEXT_TURN_MSG;\n        }\n        return;\n    case APPEALSTATE_WAIT_SKIP_NEXT_TURN_MSG:\n        if (!Contest_RunTextPrinters())\n        {\n            if (!eContestantStatus[contestant].usedComboMove)\n                gTasks[taskId].tState = APPEALSTATE_CHECK_REPEATED_MOVE;\n            else\n                gTasks[taskId].tState = APPEALSTATE_PRINT_COMBO_MSG;\n        }\n        return;\n    case APPEALSTATE_PRINT_COMBO_MSG:\n    {\n        s8 completedCombo = eContestantStatus[contestant].completedCombo;\n        if (eContestantStatus[contestant].completedCombo)\n        {\n             \n\n             \n             \n             \n            ContestClearGeneralTextWindow();\n            if (completedCombo == 1)\n                Contest_StartTextPrinter(gText_AppealComboWentOverWell, TRUE);\n            else if (completedCombo == 2)\n                Contest_StartTextPrinter(gText_AppealComboWentOverVeryWell, TRUE);\n            else\n                Contest_StartTextPrinter(gText_AppealComboWentOverExcellently, TRUE);\n\n            DoJudgeSpeechBubble(JUDGE_SYMBOL_TWO_EXCLAMATIONS);\n            gTasks[taskId].tCounter = 0;\n            gTasks[taskId].tState = APPEALSTATE_WAIT_JUDGE_COMBO;\n        }\n        else\n        {\n             \n            ContestClearGeneralTextWindow();\n            StringCopy(gStringVar1, gContestMons[contestant].nickname);\n            StringExpandPlaceholders(gStringVar4, gText_JudgeLookedAtMonExpectantly);\n            Contest_StartTextPrinter(gStringVar4, TRUE);\n            DoJudgeSpeechBubble(JUDGE_SYMBOL_ONE_EXCLAMATION);\n            gTasks[taskId].tCounter = 0;\n            gTasks[taskId].tState = APPEALSTATE_WAIT_JUDGE_COMBO;\n        }\n        return;\n    }\n    case APPEALSTATE_WAIT_JUDGE_COMBO:\n        if (!eContest.waitForJudgeSpeechBubble)\n        {\n            StartStopFlashJudgeAttentionEye(eContest.currentContestant);\n            gTasks[taskId].tState = APPEALSTATE_TRY_UPDATE_HEARTS_FROM_COMBO;\n        }\n        return;\n    case APPEALSTATE_TRY_UPDATE_HEARTS_FROM_COMBO:\n        if (!Contest_RunTextPrinters())\n        {\n            if (++gTasks[taskId].tCounter > 50)\n            {\n                if (!eContestantStatus[contestant].hasJudgesAttention)\n                {\n                    UpdateAppealHearts(\n                        eContestantStatus[contestant].appeal,\n                        eContestantStatus[contestant].comboAppealBonus,\n                        contestant);\n                    eContestantStatus[contestant].appeal += eContestantStatus[contestant].comboAppealBonus;\n                }\n                gTasks[taskId].tState = APPEALSTATE_WAIT_HEARTS_FROM_COMBO;\n            }\n        }\n        return;\n    case APPEALSTATE_WAIT_HEARTS_FROM_COMBO:\n        if (!eContestGfxState[contestant].updatingAppealHearts)\n        {\n            gTasks[taskId].tCounter = 0;\n            gTasks[taskId].tState = APPEALSTATE_CHECK_REPEATED_MOVE;\n        }\n        return;\n    case APPEALSTATE_CHECK_REPEATED_MOVE:\n        if (eContestantStatus[contestant].repeatedMove)\n        {\n            ContestClearGeneralTextWindow();\n            StringCopy(gStringVar1, gContestMons[contestant].nickname);\n            StringExpandPlaceholders(gStringVar4, gText_RepeatedAppeal);\n            Contest_StartTextPrinter(gStringVar4, TRUE);\n            gTasks[taskId].tCounter = 0;\n            DoJudgeSpeechBubble(JUDGE_SYMBOL_SWIRL);\n            gTasks[taskId].tState = APPEALSTATE_WAIT_JUDGE_REPEATED_MOVE;\n        }\n        else\n        {\n            gTasks[taskId].tState = APPEALSTATE_UPDATE_CROWD;\n        }\n        return;\n    case APPEALSTATE_WAIT_JUDGE_REPEATED_MOVE:\n        if (!eContest.waitForJudgeSpeechBubble)\n            gTasks[taskId].tState = APPEALSTATE_UPDATE_HEARTS_FROM_REPEAT;\n        return;\n    case APPEALSTATE_UPDATE_HEARTS_FROM_REPEAT:\n        if (!Contest_RunTextPrinters())\n        {\n            UpdateAppealHearts(eContestantStatus[contestant].appeal, -eContestantStatus[contestant].repeatJam, contestant);\n            eContestantStatus[contestant].appeal -= eContestantStatus[contestant].repeatJam;\n            gTasks[taskId].tState = APPEALSTATE_WAIT_HEARTS_FROM_REPEAT;\n        }\n        return;\n    case APPEALSTATE_WAIT_HEARTS_FROM_REPEAT:\n        ContestDebugDoPrint();\n        if (!eContestGfxState[contestant].updatingAppealHearts)\n        {\n            gTasks[taskId].tCounter = 0;\n            ContestClearGeneralTextWindow();\n            gTasks[taskId].tState = APPEALSTATE_UPDATE_CROWD;\n        }\n        return;\n    case APPEALSTATE_UPDATE_CROWD:\n        if (eContestExcitement.frozen && contestant != eContestExcitement.freezer)\n        {\n            gTasks[taskId].tState = APPEALSTATE_PRINT_CROWD_WATCHES_MSG;\n        }\n        else\n        {\n            r3 = eContestExcitement.moveExcitement;  \n            if (eContestantStatus[contestant].overrideCategoryExcitementMod)\n            {\n                r3 = 1;\n                StringCopy(gStringVar3, gMoveNames[eContestantStatus[contestant].currMove]);\n            }\n            else\n            {\n                StringCopy(gStringVar3, sContestConditions[gContestMoves[eContestantStatus[contestant].currMove].contestCategory]);\n            }\n\n            if (r3 > 0 && eContestantStatus[contestant].repeatedMove)\n                r3 = 0;\n\n            ContestClearGeneralTextWindow();\n            StringCopy(gStringVar1, gContestMons[contestant].nickname);\n            eContest.applauseLevel += r3;\n            if (eContest.applauseLevel < 0)\n                eContest.applauseLevel = 0;\n            if (r3 == 0)\n            {\n                gTasks[taskId].tState = APPEALSTATE_SLIDE_APPLAUSE_OUT;\n            }\n            else\n            {\n                if (r3 < 0)\n                    StringExpandPlaceholders(gStringVar4, gText_MonsXDidntGoOverWell);\n                else if (r3 > 0 && eContest.applauseLevel <= 4)\n                    StringExpandPlaceholders(gStringVar4, gText_MonsXWentOverGreat);\n                else\n                    StringExpandPlaceholders(gStringVar4, gText_MonsXGotTheCrowdGoing);\n                Contest_StartTextPrinter(gStringVar4, TRUE);\n                gTasks[taskId].tCounter = 0;\n                gTasks[taskId].data[11] = 0;\n                if (r3 < 0)\n                    gTasks[taskId].tState = APPEALSTATE_DO_CROWD_UNEXCITED;\n                else\n                    gTasks[taskId].tState = APPEALSTATE_DO_CROWD_EXCITED;\n            }\n        }\n        return;\n    case APPEALSTATE_DO_CROWD_UNEXCITED:\n        switch (gTasks[taskId].tCounter)\n        {\n        case 0:\n            BlendAudienceBackground(-1, 1);\n            PlayFanfare(MUS_TOO_BAD);\n            gTasks[taskId].tCounter++;\n            break;\n        case 1:\n            if (!eContest.waitForAudienceBlend && !Contest_RunTextPrinters())\n            {\n                ShowAndUpdateApplauseMeter(-1);\n                gTasks[taskId].tCounter++;\n            }\n            break;\n        case 2:\n            if (!eContest.isShowingApplauseMeter)\n            {\n                if (gTasks[taskId].data[11]++ > 29)\n                {\n                    gTasks[taskId].data[11] = 0;\n                    BlendAudienceBackground(-1, -1);\n                    gTasks[taskId].tCounter++;\n                }\n            }\n            break;\n        case 3:\n            if (!gPaletteFade.active)\n            {\n                gTasks[taskId].tCounter = 0;\n                gTasks[taskId].data[11] = 0;\n                gTasks[taskId].tState = APPEALSTATE_WAIT_EXCITEMENT_HEARTS;\n            }\n            break;\n        }\n        return;\n    case APPEALSTATE_DO_CROWD_EXCITED:\n        switch (gTasks[taskId].tCounter)\n        {\n        case 0:\n            if (!Contest_RunTextPrinters())\n            {\n                BlendAudienceBackground(1, 1);\n                gTasks[taskId].tCounter++;\n            }\n            break;\n        case 1:\n            if (!eContest.waitForAudienceBlend)\n            {\n                AnimateAudience();\n                PlaySE(SE_M_ENCORE2);\n                ShowAndUpdateApplauseMeter(1);\n                gTasks[taskId].tCounter++;\n            }\n            break;\n        case 2:\n            if (!eContest.isShowingApplauseMeter)\n            {\n                if (gTasks[taskId].data[11]++ > 29)\n                {\n                    gTasks[taskId].data[11] = 0;\n                    UpdateAppealHearts(eContestantStatus[contestant].appeal, eContestExcitement.excitementAppealBonus, contestant);\n                    eContestantStatus[contestant].appeal += eContestExcitement.excitementAppealBonus;\n                    gTasks[taskId].tCounter++;\n                }\n            }\n            break;\n        case 3:\n            if (!eContestGfxState[contestant].updatingAppealHearts)\n            {\n                if (!eContest.animatingAudience)\n                {\n                    BlendAudienceBackground(1, -1);\n                    gTasks[taskId].tCounter++;\n                }\n            }\n            break;\n        case 4:\n            if (!gPaletteFade.active)\n            {\n                gTasks[taskId].tCounter = 0;\n                gTasks[taskId].data[11] = 0;\n                gTasks[taskId].tState = APPEALSTATE_WAIT_EXCITEMENT_HEARTS;\n            }\n            break;\n        }\n        return;\n    case APPEALSTATE_WAIT_EXCITEMENT_HEARTS:\n        if (!eContestGfxState[contestant].updatingAppealHearts)\n        {\n            ContestClearGeneralTextWindow();\n            gTasks[taskId].tState = APPEALSTATE_SLIDE_APPLAUSE_OUT;\n        }\n        return;\n    case APPEALSTATE_PRINT_CROWD_WATCHES_MSG:\n        ContestClearGeneralTextWindow();\n        StringCopy(gStringVar3, gContestMons[eContestExcitement.freezer].nickname);\n        StringCopy(gStringVar1, gContestMons[contestant].nickname);\n        StringCopy(gStringVar2, gMoveNames[eContestantStatus[contestant].currMove]);\n        StringExpandPlaceholders(gStringVar4, gText_CrowdContinuesToWatchMon);\n        Contest_StartTextPrinter(gStringVar4, TRUE);\n        gTasks[taskId].tState = APPEALSTATE_PRINT_MON_MOVE_IGNORED_MSG;\n        return;\n    case APPEALSTATE_PRINT_MON_MOVE_IGNORED_MSG:\n        if (!Contest_RunTextPrinters())\n        {\n            ContestClearGeneralTextWindow();\n            StringExpandPlaceholders(gStringVar4, gText_MonsMoveIsIgnored);\n            Contest_StartTextPrinter(gStringVar4, TRUE);\n            gTasks[taskId].tState = APPEALSTATE_WAIT_MON_MOVE_IGNORED_MSG;\n        }\n        return;\n    case APPEALSTATE_WAIT_MON_MOVE_IGNORED_MSG:\n        if (!Contest_RunTextPrinters())\n        {\n            ContestClearGeneralTextWindow();\n            gTasks[taskId].tState = APPEALSTATE_SLIDE_APPLAUSE_OUT;\n        }\n        return;\n    case APPEALSTATE_PRINT_TOO_NERVOUS_MSG:\n        if (eContestantStatus[contestant].hasJudgesAttention)\n            eContestantStatus[contestant].hasJudgesAttention = FALSE;\n        StartStopFlashJudgeAttentionEye(contestant);\n        StringCopy(gStringVar1, gContestMons[contestant].nickname);\n        StringCopy(gStringVar2, gMoveNames[eContestantStatus[contestant].currMove]);\n        StringExpandPlaceholders(gStringVar4, gText_MonWasTooNervousToMove);\n        Contest_StartTextPrinter(gStringVar4, TRUE);\n        gTasks[taskId].tState = APPEALSTATE_WAIT_TOO_NERVOUS_MSG;\n        return;\n    case APPEALSTATE_WAIT_TOO_NERVOUS_MSG:\n        if (!Contest_RunTextPrinters())\n            gTasks[taskId].tState = APPEALSTATE_SLIDE_APPLAUSE_OUT;\n        return;\n    case APPEALSTATE_SLIDE_APPLAUSE_OUT:\n        SlideApplauseMeterOut();\n        gTasks[taskId].tState = APPEALSTATE_WAIT_SLIDE_APPLAUSE;\n        return;\n    case APPEALSTATE_WAIT_SLIDE_APPLAUSE:\n        if (!eContest.applauseMeterIsMoving)\n        {\n            if (eContest.applauseLevel > 4)\n            {\n                eContest.applauseLevel = 0;\n                UpdateApplauseMeter();\n            }\n            gTasks[taskId].tState = APPEALSTATE_SLIDE_MON_OUT;\n        }\n        return;\n    case APPEALSTATE_SLIDE_MON_OUT:\n        spriteId = gTasks[taskId].tMonSpriteId;\n        gSprites[spriteId].callback = SpriteCB_MonSlideOut;\n        gTasks[taskId].tState = APPEALSTATE_FREE_MON_SPRITE;\n        return;\n    case APPEALSTATE_FREE_MON_SPRITE:\n        spriteId = gTasks[taskId].tMonSpriteId;\n        if (gSprites[spriteId].invisible)\n        {\n            FreeSpriteOamMatrix(&gSprites[spriteId]);\n            DestroySprite(&gSprites[spriteId]);\n            gTasks[taskId].tState = APPEALSTATE_START_TURN_END_DELAY;\n        }\n        return;\n    case APPEALSTATE_START_TURN_END_DELAY:\n        gTasks[taskId].tCounter = 0;\n        gTasks[taskId].tState = APPEALSTATE_TURN_END_DELAY;\n        return;\n    case APPEALSTATE_PRINT_SKIP_TURN_MSG:\n        ContestClearGeneralTextWindow();\n        StringCopy(gStringVar1, gContestMons[contestant].nickname);\n        StringExpandPlaceholders(gStringVar4, gText_MonWasWatchingOthers);\n        Contest_StartTextPrinter(gStringVar4, TRUE);\n        gTasks[taskId].tState = APPEALSTATE_WAIT_SKIP_TURN_MSG;\n        return;\n    case APPEALSTATE_WAIT_SKIP_TURN_MSG:\n        if (!Contest_RunTextPrinters())\n            gTasks[taskId].tState = APPEALSTATE_TURN_END_DELAY;\n        return;\n    case APPEALSTATE_TURN_END_DELAY:\n        if (++gTasks[taskId].tCounter > 29)\n        {\n            gTasks[taskId].tCounter = 0;\n            gTasks[taskId].tState = APPEALSTATE_START_NEXT_TURN;\n        }\n        return;\n    case APPEALSTATE_START_NEXT_TURN:\n        if (++eContest.turnNumber == CONTESTANT_COUNT)\n        {\n            gTasks[taskId].tState = 0;\n            gTasks[taskId].data[1] = 0;\n            gTasks[taskId].tMonSpriteId = 0;\n            gTasks[taskId].func = Task_FinishRoundOfAppeals;\n        }\n        else\n        {\n            gTasks[taskId].tState = APPEALSTATE_START_TURN;\n        }\n        return;\n    }",
  },
  "Task_EndWaitForLink": {
    callsTo: ["DestroyTask"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 2,
    bodyC: "eContest.waitForLink = FALSE;\n    DestroyTask(taskId);",
  },
  "Task_FinishRoundOfAppeals": {
    callsTo: ["ContestPrintLinkStandby","CreateTask","IsPlayerLinkLeader","RankContestants","SetAttentionLevels","SetTaskFuncWithFollowupFunc"],
    taskTransitions: ["Task_ReadyUpdateHeartSliders"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]"],
    lineCount: 33,
    bodyC: "switch (gTasks[taskId].data[0])\n    {\n    case 0:\n        if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n        {\n            u8 taskId2;\n\n            eContest.waitForLink = TRUE;\n            if (IsPlayerLinkLeader())\n            {\n                RankContestants();\n                SetAttentionLevels();\n            }\n            taskId2 = CreateTask(Task_LinkContest_CommunicateAppealsState, 0);\n            SetTaskFuncWithFollowupFunc(taskId2, Task_LinkContest_CommunicateAppealsState, Task_EndWaitForLink);\n            ContestPrintLinkStandby();\n            gTasks[taskId].data[0] = 1;\n        }\n        else\n        {\n            RankContestants();\n            SetAttentionLevels();\n            gTasks[taskId].data[0] = 2;\n        }\n        break;\n    case 1:\n        if (!eContest.waitForLink)\n            gTasks[taskId].data[0] = 2;\n        break;\n    case 2:\n        gTasks[taskId].data[0] = 0;\n        gTasks[taskId].func = Task_ReadyUpdateHeartSliders;\n        break;\n    }",
  },
  "Task_ReadyUpdateHeartSliders": {
    callsTo: ["ShowHideNextTurnGfx"],
    taskTransitions: ["Task_UpdateHeartSliders"],
    dataWrites: ["data[0]","data[1]"],
    lineCount: 4,
    bodyC: "ShowHideNextTurnGfx(FALSE);\n    gTasks[taskId].data[0] = 0;\n    gTasks[taskId].data[1] = 0;\n    gTasks[taskId].func = Task_UpdateHeartSliders;",
  },
  "Task_UpdateHeartSliders": {
    callsTo: ["AnimateSliderHearts","UpdateHeartSliders"],
    taskTransitions: ["Task_WaitForHeartSliders"],
    dataReads: ["data[0]","data[1]"],
    dataWrites: ["data[0]","data[1]"],
    lineCount: 27,
    bodyC: "switch (gTasks[taskId].data[0])\n    {\n    case 0:\n        if (++gTasks[taskId].data[1] > 20)\n        {\n            AnimateSliderHearts(SLIDER_HEART_ANIM_APPEAR);\n            gTasks[taskId].data[1] = 0;\n            gTasks[taskId].data[0]++;\n        }\n        break;\n    case 1:\n        if (!eContest.sliderHeartsAnimating)\n        {\n            if (++gTasks[taskId].data[1] > 20)\n            {\n                gTasks[taskId].data[1] = 0;\n                gTasks[taskId].data[0]++;\n            }\n        }\n        break;\n    case 2:\n        UpdateHeartSliders();\n        gTasks[taskId].data[0] = 0;\n        gTasks[taskId].data[1] = 0;\n        gTasks[taskId].func = Task_WaitForHeartSliders;\n        break;\n    }",
  },
  "Task_WaitForHeartSliders": {
    callsTo: ["SlidersDoneUpdating"],
    taskTransitions: ["Task_RestorePlttBufferUnfaded"],
    lineCount: 2,
    bodyC: "if (SlidersDoneUpdating())\n        gTasks[taskId].func = Task_RestorePlttBufferUnfaded;",
  },
  "Task_RestorePlttBufferUnfaded": {
    callsTo: ["DmaCopy32Defvars"],
    taskTransitions: ["Task_WaitPrintRoundResult"],
    dataWrites: ["data[0]","data[1]"],
    lineCount: 4,
    bodyC: "DmaCopy32Defvars(3, eContestTempSave.cachedPlttBufferUnfaded, gPlttBufferUnfaded, PLTT_SIZE);\n    gTasks[taskId].data[0] = 0;\n    gTasks[taskId].data[1] = 2;\n    gTasks[taskId].func = Task_WaitPrintRoundResult;",
  },
  "Task_WaitPrintRoundResult": {
    taskTransitions: ["Task_PrintRoundResultText"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]","data[1]"],
    lineCount: 6,
    bodyC: "if (++gTasks[taskId].data[0] > 2)\n    {\n        gTasks[taskId].data[0] = 0;\n        if (--gTasks[taskId].data[1] == 0)\n            gTasks[taskId].func = Task_PrintRoundResultText;\n    }",
  },
  "Task_PrintRoundResultText": {
    callsTo: ["ContestClearGeneralTextWindow","ContestDebugDoPrint","Contest_RunTextPrinters","Contest_StartTextPrinter","StringCopy","StringExpandPlaceholders"],
    taskTransitions: ["Task_ReUpdateHeartSliders"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]"],
    lineCount: 18,
    bodyC: "if (gTasks[taskId].data[0] == 0)\n    {\n        u8 attention = eContestantStatus[gContestPlayerMonIndex].attentionLevel;\n\n        ContestClearGeneralTextWindow();\n        StringCopy(gStringVar1, gContestMons[gContestPlayerMonIndex].nickname);\n        StringExpandPlaceholders(gStringVar4, sRoundResultTexts[attention]);\n        Contest_StartTextPrinter(gStringVar4, TRUE);\n        gTasks[taskId].data[0]++;\n    }\n    else\n    {\n        if (!Contest_RunTextPrinters())\n        {\n            gTasks[taskId].data[0] = 0;\n            gTasks[taskId].func = Task_ReUpdateHeartSliders;\n            ContestDebugDoPrint();\n        }\n    }",
  },
  "Task_ReUpdateHeartSliders": {
    callsTo: ["UpdateHeartSliders"],
    taskTransitions: ["Task_WaitForHeartSlidersAgain"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]"],
    lineCount: 6,
    bodyC: "if (gTasks[taskId].data[0]++ > 29)\n    {\n        gTasks[taskId].data[0] = 0;\n        UpdateHeartSliders();  \n        gTasks[taskId].func = Task_WaitForHeartSlidersAgain;\n    }",
  },
  "Task_WaitForHeartSlidersAgain": {
    callsTo: ["SlidersDoneUpdating"],
    taskTransitions: ["Task_DropCurtainAtRoundEnd"],
    dataWrites: ["data[0]"],
    lineCount: 5,
    bodyC: "if (SlidersDoneUpdating())\n    {\n        gTasks[taskId].data[0] = 0;\n        gTasks[taskId].func = Task_DropCurtainAtRoundEnd;\n    }",
  },
  "Task_DropCurtainAtRoundEnd": {
    callsTo: ["SetBgForCurtainDrop"],
    taskTransitions: ["Task_StartDropCurtainAtRoundEnd"],
    lineCount: 2,
    bodyC: "SetBgForCurtainDrop();\n    gTasks[taskId].func = Task_StartDropCurtainAtRoundEnd;",
  },
  "Task_UpdateContestantBoxOrder": {
    callsTo: ["UpdateContestantBoxOrder"],
    taskTransitions: ["Task_TryStartNextRoundOfAppeals"],
    lineCount: 2,
    bodyC: "UpdateContestantBoxOrder();\n    gTasks[taskId].func = Task_TryStartNextRoundOfAppeals;",
  },
  "Task_TryStartNextRoundOfAppeals": {
    callsTo: ["GetGpuReg","SetGpuReg","SlideApplauseMeterIn"],
    taskTransitions: ["Task_EndAppeals","Task_StartNewRoundOfAppeals"],
    lineCount: 16,
    bodyC: "vu16 sp0 = GetGpuReg(REG_OFFSET_BG0CNT);\n    vu16 sp2 = GetGpuReg(REG_OFFSET_BG2CNT);\n    ((vBgCnt *)&sp0)->priority = 0;\n    ((vBgCnt *)&sp2)->priority = 0;\n    SetGpuReg(REG_OFFSET_BG0CNT, sp0);\n    SetGpuReg(REG_OFFSET_BG2CNT, sp2);\n    eContest.appealNumber++;\n    if (eContest.appealNumber == CONTEST_NUM_APPEALS)\n    {\n        gTasks[taskId].func = Task_EndAppeals;\n    }\n    else\n    {\n        SlideApplauseMeterIn();\n        gTasks[taskId].func = Task_StartNewRoundOfAppeals;\n    }",
  },
  "Task_StartNewRoundOfAppeals": {
    taskTransitions: ["Task_DisplayAppealNumberText"],
    lineCount: 2,
    bodyC: "if (!eContest.applauseMeterIsMoving)\n        gTasks[taskId].func = Task_DisplayAppealNumberText;",
  },
  "Task_EndAppeals": {
    callsTo: ["BravoTrainerPokemonProfile_BeforeInterview1","CalculateContestLiveUpdateData","CalculateFinalScores","ContestClearGeneralTextWindow","ContestDebugPrintBitStrings","Contest_StartTextPrinter","SetConestLiveUpdateTVData","StringExpandPlaceholders"],
    taskTransitions: ["Task_WaitForOutOfTimeMsg"],
    dataWrites: ["data[2]"],
    lineCount: 22,
    bodyC: "s32 i;\n\n    gBattle_BG0_Y = 0;\n    gBattle_BG2_Y = 0;\n    for (i = 0; i < CONTESTANT_COUNT; i++)\n        gContestMonAppealPointTotals[i] = eContestantStatus[i].pointTotal;\n    CalculateFinalScores();\n    ContestClearGeneralTextWindow();\n    if (!(gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK))\n    {\n        BravoTrainerPokemonProfile_BeforeInterview1(eContestantStatus[gContestPlayerMonIndex].prevMove);\n    }\n    else\n    {\n        CalculateContestLiveUpdateData();\n        SetConestLiveUpdateTVData();\n        ContestDebugPrintBitStrings();\n    }\n    gContestRngValue = gRngValue;\n    StringExpandPlaceholders(gStringVar4, gText_AllOutOfAppealTime);\n    Contest_StartTextPrinter(gStringVar4, TRUE);\n    gTasks[taskId].data[2] = 0;\n    gTasks[taskId].func = Task_WaitForOutOfTimeMsg;",
  },
  "Task_WaitForOutOfTimeMsg": {
    callsTo: ["Contest_RunTextPrinters","PlaySE12WithPanning","SetBgForCurtainDrop"],
    taskTransitions: ["Task_DropCurtainAtAppealsEnd"],
    dataWrites: ["data[0]"],
    lineCount: 9,
    bodyC: "if (!Contest_RunTextPrinters())\n    {\n        SetBgForCurtainDrop();\n        gBattle_BG1_X = 0;\n        gBattle_BG1_Y = DISPLAY_HEIGHT;\n        PlaySE12WithPanning(SE_CONTEST_CURTAIN_FALL, 0);\n        gTasks[taskId].data[0] = 0;\n        gTasks[taskId].func = Task_DropCurtainAtAppealsEnd;\n    }",
  },
  "Task_DropCurtainAtAppealsEnd": {
    taskTransitions: ["Task_TryCommunicateFinalStandings"],
    dataWrites: ["data[0]"],
    lineCount: 8,
    bodyC: "gBattle_BG1_Y -= 7;\n    if ((s16)gBattle_BG1_Y < 0)\n        gBattle_BG1_Y = 0;\n    if (gBattle_BG1_Y == 0)\n    {\n        gTasks[taskId].func = Task_TryCommunicateFinalStandings;\n        gTasks[taskId].data[0] = 0;\n    }",
  },
  "Task_TryCommunicateFinalStandings": {
    callsTo: ["BeginNormalPaletteFade"],
    taskTransitions: ["Task_CommunicateFinalStandings","Task_ContestReturnToField"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]"],
    lineCount: 13,
    bodyC: "if (gTasks[taskId].data[0]++ >= 50)\n    {\n        gTasks[taskId].data[0] = 0;\n        if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n        {\n            gTasks[taskId].func = Task_CommunicateFinalStandings;\n        }\n        else\n        {\n            BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_BLACK);\n            gTasks[taskId].func = Task_ContestReturnToField;\n        }\n    }",
  },
  "Task_CommunicateFinalStandings": {
    callsTo: ["ContestPrintLinkStandby","CreateTask","SetBottomSliderHeartsInvisibility","SetTaskFuncWithFollowupFunc"],
    taskTransitions: ["TaskDummy1"],
    lineCount: 5,
    bodyC: "u8 taskId2 = CreateTask(Task_LinkContest_CommunicateFinalStandings, 0);\n\n    SetTaskFuncWithFollowupFunc(taskId2, Task_LinkContest_CommunicateFinalStandings, Task_EndCommunicateFinalStandings);\n    gTasks[taskId].func = TaskDummy1;\n    ContestPrintLinkStandby();\n    SetBottomSliderHeartsInvisibility(FALSE);",
  },
  "Task_EndCommunicateFinalStandings": {
    callsTo: ["BeginNormalPaletteFade","DestroyTask"],
    taskTransitions: ["Task_ContestReturnToField"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 3,
    bodyC: "DestroyTask(taskId);\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_BLACK);\n    gTasks[eContest.mainTaskId].func = Task_ContestReturnToField;",
  },
  "Task_ContestReturnToField": {
    callsTo: ["DestroyTask","FreeAllWindowBuffers","FreeContestResources","FreeMonSpritesGfx","SetMainCallback2"],
    cb2Transitions: ["CB2_ReturnToField"],
    terminalMarkers: ["DestroyTask"],
    externalChecks: { paletteFade: true },
    lineCount: 9,
    bodyC: "if (!gPaletteFade.active)\n    {\n        DestroyTask(taskId);\n        gFieldCallback = FieldCB_ContestReturnToField;\n        FreeAllWindowBuffers();\n        FreeContestResources();\n        FreeMonSpritesGfx();\n        SetMainCallback2(CB2_ReturnToField);\n    }",
  },
  "Task_UpdateAppealHearts": {
    callsTo: ["ContestBG_FillBoxWithTile","DestroyTask","GetAppealHeartTileOffset","PlaySE","m4aMPlayImmInit","m4aMPlayPitchControl"],
    dataReads: ["tContestant","tDelayTimer","tHeartsDelta","tHeartsSign","tNumHearts"],
    dataWrites: ["tDelayTimer","tHeartsDelta","tHeartsSign","tNumHearts"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 84,
    bodyC: "u8 contestant = gTasks[taskId].tContestant;\n    s16 startHearts = gTasks[taskId].tNumHearts;\n    s16 heartsDelta = gTasks[taskId].tHeartsDelta;\n\n    if (++gTasks[taskId].tDelayTimer > 14)\n    {\n        u16 heartOffset;\n        u8 newNumHearts;\n        u8 pitchMod;\n        bool8 onSecondLine;\n\n        gTasks[taskId].tDelayTimer = 0;\n        if (gTasks[taskId].tHeartsDelta == 0)\n        {\n             \n            DestroyTask(taskId);\n            eContestGfxState[contestant].updatingAppealHearts = FALSE;\n            return;\n        }\n        else if (startHearts == 0)\n        {\n            if (heartsDelta < 0)\n            {\n                 \n                heartOffset = GetAppealHeartTileOffset(contestant) + 2;\n                gTasks[taskId].tHeartsDelta++;\n            }\n            else\n            {\n                 \n                heartOffset = GetAppealHeartTileOffset(contestant);\n                gTasks[taskId].tHeartsDelta--;\n            }\n            newNumHearts = gTasks[taskId].tNumHearts++;\n        }\n        else\n        {\n            if (gTasks[taskId].tHeartsSign < 0)\n            {\n                 \n                if (heartsDelta < 0)\n                {\n                     \n                    newNumHearts = gTasks[taskId].tNumHearts++;\n                    gTasks[taskId].tHeartsDelta++;\n                    heartOffset = GetAppealHeartTileOffset(contestant) + 2;\n                }\n                else\n                {\n                     \n                    newNumHearts = --gTasks[taskId].tNumHearts;\n                    heartOffset = 0;\n                    gTasks[taskId].tHeartsDelta--;\n                }\n            }\n            else\n            {\n                 \n                if (heartsDelta < 0)\n                {\n                     \n                    newNumHearts = --gTasks[taskId].tNumHearts;\n                    heartOffset = 0;\n                    gTasks[taskId].tHeartsDelta++;\n                }\n                else\n                {\n                     \n                    newNumHearts = gTasks[taskId].tNumHearts++;\n                    gTasks[taskId].tHeartsDelta--;\n                    heartOffset = GetAppealHeartTileOffset(contestant);\n                }\n            }\n        }\n        pitchMod = newNumHearts;\n        onSecondLine = FALSE;\n\n         \n        if (newNumHearts > 7)\n        {\n            onSecondLine = TRUE;\n            newNumHearts -= 8;\n        }\n        ContestBG_FillBoxWithTile(0, heartOffset, newNumHearts + 22, gContestantTurnOrder[contestant] * 5 + 2 + onSecondLine,  1, 1, 17);\n        if (heartsDelta > 0)\n        {\n            PlaySE(SE_CONTEST_HEART);\n            m4aMPlayImmInit(&gMPlayInfo_SE1);\n            m4aMPlayPitchControl(&gMPlayInfo_SE1, TRACKS_ALL, pitchMod * 256);\n        }\n        else\n        {\n            PlaySE(SE_BOO);\n        }\n\n        if (!onSecondLine && newNumHearts == 0 && heartOffset == 0)\n            gTasks[taskId].tHeartsSign = -gTasks[taskId].tHeartsSign;\n    }",
  },
  "Task_StopFlashJudgeAttentionEye": {
    callsTo: ["BG_PLTT_ID","BlendPalette","DestroyTask","RGB"],
    dataReads: ["data[0]"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 9,
    bodyC: "u8 contestant = gTasks[taskId].data[0];\n\n    if (gTasks[eContest.judgeAttentionTaskId].data[contestant * 4 + 0] == 0\n     || gTasks[eContest.judgeAttentionTaskId].data[contestant * 4 + 0] == 0xFF)\n    {\n        gTasks[eContest.judgeAttentionTaskId].data[contestant * 4 + 0] = 0xFF;\n        gTasks[eContest.judgeAttentionTaskId].data[contestant * 4 + 1] = 0;\n        BlendPalette(BG_PLTT_ID(5 + eContest.prevTurnOrder[contestant]) + 6, 2, 0, RGB(31, 31, 18));\n        DestroyTask(taskId);\n    }",
  },
  "Task_FlashJudgeAttentionEye": {
    callsTo: ["BG_PLTT_ID","BlendPalette","RGB"],
    lineCount: 16,
    bodyC: "u8 i;\n\n    for (i = 0; i < CONTESTANT_COUNT; i++)\n    {\n        u8 offset = i * 4;\n\n        if (gTasks[taskId].data[offset + 0] != 0xFF)\n        {\n            if (gTasks[taskId].data[offset + 1] == 0)\n                gTasks[taskId].data[offset + 0]++;\n            else\n                gTasks[taskId].data[offset + 0]--;\n\n            if (gTasks[taskId].data[offset + 0] == 16\n             || gTasks[taskId].data[offset + 0] == 0)\n                gTasks[taskId].data[offset + 1] ^= 1;\n\n            BlendPalette(BG_PLTT_ID(5 + eContest.prevTurnOrder[i]) + 6, 2, gTasks[taskId].data[offset + 0], RGB(31, 31, 18));\n        }\n    }",
  },
  "Task_UnusedBlend": {
    callsTo: ["BG_PLTT_ID","BlendPalette","RGB"],
    lineCount: 21,
    bodyC: "u8 i;\n\n    for (i = 0; i < CONTESTANT_COUNT; i++)\n    {\n        u8 idx = i * 4;\n\n         \n        if (gTasks[taskId].data[idx] != 0xFF)\n        {\n            if (++gTasks[taskId].data[idx + 2] > 2)\n            {\n                gTasks[taskId].data[idx + 2] = 0;\n\n                if (gTasks[taskId].data[idx + 1] == 0)\n                    gTasks[taskId].data[idx]++;\n                else\n                    gTasks[taskId].data[idx]--;\n\n                if (gTasks[taskId].data[idx] == 16\n                 || gTasks[taskId].data[idx] == 0)\n                    gTasks[taskId].data[idx + 1] ^= 1;\n\n                BlendPalette(BG_PLTT_ID(5 + i) + 10,     1, gTasks[taskId].data[idx + 0], RGB(31, 31, 18));\n                BlendPalette(BG_PLTT_ID(5 + i) + 12 + i, 1, gTasks[taskId].data[idx + 0], RGB(31, 31, 18));\n            }\n        }\n    }",
  },
  "Task_ApplauseOverflowAnimation": {
    callsTo: ["BlendPalette","DestroyTask","OBJ_PLTT_ID"],
    dataReads: ["data[2]","data[3]","data[4]"],
    dataWrites: ["data[0]","data[3]","data[4]"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 18,
    bodyC: "if (++gTasks[taskId].data[0] == 1)\n    {\n        gTasks[taskId].data[0] = 0;\n\n         \n        if (gTasks[taskId].data[3] == 0)\n            gTasks[taskId].data[4]++;\n        else\n            gTasks[taskId].data[4]--;\n\n        BlendPalette(OBJ_PLTT_ID(gTasks[taskId].data[2]) + 8, 1, gTasks[taskId].data[4], RGB_WHITE);\n\n         \n        if (gTasks[taskId].data[4] == 0 || gTasks[taskId].data[4] == 16)\n        {\n            gTasks[taskId].data[3] ^= 1;\n\n             \n            if (eContest.applauseLevel < 5)\n            {\n                BlendPalette(OBJ_PLTT_ID(gTasks[taskId].data[2]) + 8, 1, 0, RGB_RED);\n                DestroyTask(taskId);\n            }\n        }\n    }",
  },
  "Task_SlideApplauseMeterIn": {
    callsTo: ["DestroyTask"],
    dataReads: ["data[10]"],
    dataWrites: ["data[10]"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 11,
    bodyC: "struct Sprite *sprite = &gSprites[eContest.applauseMeterSpriteId];\n\n    gTasks[taskId].data[10] += 1664;\n    sprite->x2 += gTasks[taskId].data[10] >> 8;\n    gTasks[taskId].data[10] = gTasks[taskId].data[10] & 0xFF;\n    if (sprite->x2 > 0)\n        sprite->x2 = 0;\n    if (sprite->x2 == 0)\n    {\n        eContest.applauseMeterIsMoving = FALSE;\n        DestroyTask(taskId);\n    }",
  },
  "Task_SlideApplauseMeterOut": {
    callsTo: ["DestroyTask"],
    dataReads: ["data[10]"],
    dataWrites: ["data[10]"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 12,
    bodyC: "struct Sprite *sprite = &gSprites[eContest.applauseMeterSpriteId];\n\n    gTasks[taskId].data[10] += 1664;\n    sprite->x2 -= gTasks[taskId].data[10] >> 8;\n    gTasks[taskId].data[10] = gTasks[taskId].data[10] & 0xFF;\n    if (sprite->x2 < -70)\n        sprite->x2 = -70;\n    if (sprite->x2 == -70)\n    {\n        sprite->invisible = TRUE;\n        eContest.applauseMeterIsMoving = FALSE;\n        DestroyTask(taskId);\n    }",
  },
  "Task_ShowAndUpdateApplauseMeter": {
    callsTo: ["DestroyTask","SlideApplauseMeterIn","UpdateApplauseMeter"],
    dataReads: ["data[10]","data[11]"],
    dataWrites: ["data[10]","data[11]"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 22,
    bodyC: "switch (gTasks[taskId].data[10])\n    {\n    case 0:\n        SlideApplauseMeterIn();\n        gTasks[taskId].data[10]++;\n        break;\n    case 1:\n        if (!eContest.applauseMeterIsMoving)\n        {\n            gTasks[taskId].data[10]++;\n        }\n        break;\n    case 2:\n        if (gTasks[taskId].data[11]++ > 20)\n        {\n            gTasks[taskId].data[11] = 0;\n            UpdateApplauseMeter();\n            eContest.isShowingApplauseMeter = FALSE;\n            DestroyTask(taskId);\n        }\n        break;\n    }",
  },
  "Task_AnimateAudience": {
    callsTo: ["BG_SCREEN_ADDR","DestroyTask","RequestDma3Copy"],
    dataReads: ["tCycles","tDelay","tFrame"],
    dataWrites: ["tCycles","tDelay","tFrame"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 19,
    bodyC: "if (gTasks[taskId].tDelay++ > 6)\n    {\n        gTasks[taskId].tDelay = 0;\n        if (gTasks[taskId].tFrame == 0)\n        {\n            RequestDma3Copy(eContestAudienceFrame2_Gfx, (void *)(BG_SCREEN_ADDR(4)), 0x1000, 1);\n        }\n        else\n        {\n            RequestDma3Copy(eUnzippedContestAudience_Gfx, (void *)(BG_SCREEN_ADDR(4)), 0x1000, 1);\n            gTasks[taskId].tCycles++;\n        }\n\n        gTasks[taskId].tFrame ^= 1;\n\n        if (gTasks[taskId].tCycles == 9)\n        {\n            eContest.animatingAudience = FALSE;\n            DestroyTask(taskId);\n        }\n    }",
  },
  "Task_BlendAudienceBackground": {
    callsTo: ["BG_PLTT_ID","BlendPalette","DestroyTask"],
    dataReads: ["tBlendCoeff","tBlendColor","tBlendDelay","tBlendDir","tTargetBlendCoeff"],
    dataWrites: ["tBlendCoeff","tBlendDelay"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 15,
    bodyC: "if (gTasks[taskId].tBlendDelay++ >= 0)\n    {\n        gTasks[taskId].tBlendDelay = 0;\n        if (gTasks[taskId].tBlendDir > 0)\n            gTasks[taskId].tBlendCoeff++;\n        else\n            gTasks[taskId].tBlendCoeff--;\n\n        BlendPalette(BG_PLTT_ID(1) + 1,  1, gTasks[taskId].tBlendCoeff, gTasks[taskId].tBlendColor);\n        BlendPalette(BG_PLTT_ID(1) + 10, 1, gTasks[taskId].tBlendCoeff, gTasks[taskId].tBlendColor);\n\n        if (gTasks[taskId].tBlendCoeff == gTasks[taskId].tTargetBlendCoeff)\n        {\n            DestroyTask(taskId);\n            eContest.waitForAudienceBlend = FALSE;\n        }\n    }",
  },
  "Task_StartDropCurtainAtRoundEnd": {
    callsTo: ["PlaySE12WithPanning"],
    taskTransitions: ["Task_UpdateCurtainDropAtRoundEnd"],
    lineCount: 4,
    bodyC: "gBattle_BG1_X = 0;\n    gBattle_BG1_Y = DISPLAY_HEIGHT;\n    PlaySE12WithPanning(SE_CONTEST_CURTAIN_FALL, 0);\n    gTasks[taskId].func = Task_UpdateCurtainDropAtRoundEnd;",
  },
  "Task_UpdateCurtainDropAtRoundEnd": {
    taskTransitions: ["Task_ResetForNextRound"],
    dataWrites: ["data[0]","data[1]","data[2]"],
    lineCount: 9,
    bodyC: "if ((s16)(gBattle_BG1_Y -= 7) < 0)\n        gBattle_BG1_Y = 0;\n    if (gBattle_BG1_Y == 0)\n    {\n        gTasks[taskId].data[0] = 0;\n        gTasks[taskId].data[1] = 0;\n        gTasks[taskId].data[2] = 0;\n        gTasks[taskId].func = Task_ResetForNextRound;\n    }",
  },
  "Task_ResetForNextRound": {
    callsTo: ["ContestPrintLinkStandby","CreateTask","DrawConditionStars","DrawContestantWindows","DrawStatusSymbols","FillContestantWindowBgs","IsPlayerLinkLeader","SetContestantStatusesForNextRound","SetTaskFuncWithFollowupFunc","ShowHideNextTurnGfx","SwapMoveDescAndContestTilemaps","UpdateBlendTaskContestantsData","UpdateSliderHeartSpriteYPositions"],
    taskTransitions: ["Task_WaitRaiseCurtainAtRoundEnd"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]"],
    lineCount: 43,
    bodyC: "s32 i;\n\n    switch (gTasks[taskId].data[0])\n    {\n    case 0:\n        for (i = 0; i < CONTESTANT_COUNT; i++)\n            eContest.prevTurnOrder[i] = gContestantTurnOrder[i];\n        FillContestantWindowBgs();\n        UpdateBlendTaskContestantsData();\n        DrawConditionStars();\n        DrawContestantWindows();\n        ShowHideNextTurnGfx(TRUE);\n        UpdateSliderHeartSpriteYPositions();\n        gTasks[taskId].data[0] = 1;\n        break;\n    case 1:\n        if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n        {\n            u8 taskId2;\n\n            eContest.waitForLink = TRUE;\n            if (IsPlayerLinkLeader())\n                SetContestantStatusesForNextRound();\n            taskId2 = CreateTask(Task_LinkContest_CommunicateAppealsState, 0);\n            SetTaskFuncWithFollowupFunc(taskId2, Task_LinkContest_CommunicateAppealsState, Task_EndWaitForLink);\n            ContestPrintLinkStandby();\n            gTasks[taskId].data[0] = 2;\n        }\n        else\n        {\n            SetContestantStatusesForNextRound();\n            gTasks[taskId].data[0] = 3;\n        }\n        break;\n    case 2:\n        if (!eContest.waitForLink)\n            gTasks[taskId].data[0] = 3;\n        break;\n    case 3:\n        DrawStatusSymbols();\n        SwapMoveDescAndContestTilemaps();\n        gTasks[taskId].data[0] = 0;\n        gTasks[taskId].func = Task_WaitRaiseCurtainAtRoundEnd;\n        break;\n    }",
  },
  "Task_UpdateRaiseCurtainAtRoundEnd": {
    taskTransitions: ["Task_UpdateContestantBoxOrder"],
    lineCount: 2,
    bodyC: "if ((s16)(gBattle_BG1_Y += 7) > DISPLAY_HEIGHT)\n        gTasks[taskId].func = Task_UpdateContestantBoxOrder;",
  },
  "Task_WaitRaiseCurtainAtRoundEnd": {
    taskTransitions: ["Task_StartRaiseCurtainAtRoundEnd"],
    dataReads: ["data[0]","data[1]","data[2]"],
    dataWrites: ["data[0]","data[1]","data[2]"],
    lineCount: 27,
    bodyC: "if (gTasks[taskId].data[2] < 10)\n    {\n        gTasks[taskId].data[2]++;\n    }\n    else\n    {\n        if (gTasks[taskId].data[1] == 0)\n        {\n            if (gTasks[taskId].data[0] == 16)\n                gTasks[taskId].data[1]++;\n            else\n                gTasks[taskId].data[0]++;\n        }\n        else\n        {\n            if (gTasks[taskId].data[0] == 0)\n            {\n                gTasks[taskId].data[1] = 0;\n                gTasks[taskId].data[2] = 0;\n                gTasks[taskId].func = Task_StartRaiseCurtainAtRoundEnd;\n            }\n            else\n            {\n                gTasks[taskId].data[0]--;\n            }\n        }\n    }",
  },
  "Task_StartRaiseCurtainAtRoundEnd": {
    callsTo: ["PlaySE12WithPanning"],
    taskTransitions: ["Task_UpdateRaiseCurtainAtRoundEnd"],
    dataReads: ["data[2]"],
    dataWrites: ["data[2]"],
    lineCount: 10,
    bodyC: "if (gTasks[taskId].data[2] < 10)\n    {\n        gTasks[taskId].data[2]++;\n    }\n    else\n    {\n        gTasks[taskId].data[2] = 0;\n        PlaySE12WithPanning(SE_CONTEST_CURTAIN_RISE, 0);\n        gTasks[taskId].func = Task_UpdateRaiseCurtainAtRoundEnd;\n    }",
  },
  "Task_WaitForSliderHeartAnim": {
    callsTo: ["DestroyTask","FreeSpriteOamMatrix"],
    dataWrites: ["tAnimId"],
    terminalMarkers: ["DestroyTask","FreeSpriteOamMatrix"],
    lineCount: 13,
    bodyC: "s32 i;\n\n    if (gSprites[eContestGfxState[0].sliderHeartSpriteId].affineAnimEnded)\n    {\n        if ((u8)gTasks[taskId].tAnimId == SLIDER_HEART_ANIM_DISAPPEAR)\n        {\n            for (i = 0; i < CONTESTANT_COUNT; i++)\n                gSprites[eContestGfxState[i].sliderHeartSpriteId].invisible = TRUE;\n        }\n        for (i = 0; i < CONTESTANT_COUNT; i++)\n            FreeSpriteOamMatrix(&gSprites[eContestGfxState[i].sliderHeartSpriteId]);\n        eContest.sliderHeartsAnimating = FALSE;\n        DestroyTask(taskId);\n    }",
  },
} as const;

export const CB2S = {
  "CB2_StartContest": {
    callsTo: ["AllocContestResources","AllocZeroed","AllocateMonSpritesGfx","BeginFastPaletteFade","ClearBattleMonForms","CreateTask","CreateWirelessStatusIndicatorSprite","FREE_AND_SET_NULL","FreeAllSpritePalettes","InitContestInfoBgs","InitContestResources","InitContestWindows","LoadWirelessStatusIndicatorSpriteGfx","ResetPaletteFade","ResetSpriteData","ResetTasks","ScanlineEffect_Clear","SetBgForCurtainDrop","SetMainCallback2","SetVBlankCallback","SetupContestGpuRegs","SetupContestGraphics"],
    cb2Transitions: ["CB2_ContestMain"],
    lineCount: 50,
    bodyC: "switch (gMain.state)\n    {\n    case 0:\n        sContestBgCopyFlags = 0;\n        AllocContestResources();\n        AllocateMonSpritesGfx();\n        FREE_AND_SET_NULL(gMonSpritesGfxPtr->firstDecompressed);\n        gMonSpritesGfxPtr->firstDecompressed = AllocZeroed(0x4000);\n        SetVBlankCallback(NULL);\n        InitContestInfoBgs();\n        InitContestWindows();\n        SetupContestGpuRegs();\n        ScanlineEffect_Clear();\n        ResetPaletteFade();\n        gPaletteFade.bufferTransferDisabled = TRUE;\n        ResetSpriteData();\n        ResetTasks();\n        FreeAllSpritePalettes();\n        gReservedSpritePaletteCount = 4;\n        eContestDebugMode = CONTEST_DEBUG_MODE_OFF;\n        ClearBattleMonForms();\n        InitContestResources();\n        gMain.state++;\n        break;\n    case 1:\n        gMain.state++;\n        break;\n    case 2:\n        if (SetupContestGraphics(&eContest.contestSetupState))\n        {\n            eContest.contestSetupState = 0;\n            gMain.state++;\n        }\n        break;\n    case 3:\n        SetBgForCurtainDrop();\n        gBattle_BG1_X = 0;\n        gBattle_BG1_Y = 0;\n        BeginFastPaletteFade(2);\n        gPaletteFade.bufferTransferDisabled = FALSE;\n        SetVBlankCallback(VBlankCB_Contest);\n        eContest.mainTaskId = CreateTask(Task_StartContestWaitFade, 10);\n        SetMainCallback2(CB2_ContestMain);\n        if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS)\n        {\n            LoadWirelessStatusIndicatorSpriteGfx();\n            CreateWirelessStatusIndicatorSprite(8, 8);\n        }\n        break;\n    }",
  },
  "CB2_ContestMain": {
    callsTo: ["AnimateSprites","BuildOamBuffer","CopyBgTilemapBufferToVram","RunTasks","UpdatePaletteFade"],
    externalChecks: { waitForVBlank: true },
    lineCount: 11,
    bodyC: "s32 i;\n\n    AnimateSprites();\n    RunTasks();\n    BuildOamBuffer();\n    UpdatePaletteFade();\n\n    for (i = 0; i < 4; i++)\n    {\n        if ((sContestBgCopyFlags >> i) & 1)\n            CopyBgTilemapBufferToVram(i);\n    }\n    sContestBgCopyFlags = 0;",
  },
} as const;

export const SPRITE_CBS = {
  "SpriteCB_MonSlideIn": {
    spriteTransitions: ["SpriteCallbackDummy"],
    lineCount: 12,
    bodyC: "if (sprite->x2 != 0)\n    {\n        sprite->x2 -= 2;\n    }\n    else\n    {\n        if (++sprite->data[0] == 31)\n        {\n            sprite->data[0] = 0;\n            sprite->callback = SpriteCallbackDummy;\n        }\n    }",
  },
  "SpriteCB_MonSlideOut": {
    spriteTransitions: ["SpriteCallbackDummy"],
    lineCount: 6,
    bodyC: "sprite->x2 -= 6;\n    if (sprite->x + sprite->x2 < -32)\n    {\n        sprite->callback = SpriteCallbackDummy;\n        sprite->invisible = TRUE;\n    }",
  },
  "SpriteCB_UpdateHeartSlider": {
    spriteTransitions: ["SpriteCallbackDummy"],
    lineCount: 9,
    bodyC: "if (sprite->x2 == sprite->sTargetX)\n    {\n        eContestGfxState[sprite->sContestant].sliderUpdating = FALSE;\n        sprite->callback = SpriteCallbackDummy;\n    }\n    else\n    {\n        sprite->x2 += sprite->sMoveX;\n    }",
  },
  "SpriteCB_BlinkContestantBox": {
    spriteTransitions: ["SpriteCB_EndBlinkContestantBox"],
    lineCount: 10,
    bodyC: "if (sprite->affineAnimEnded)\n    {\n        u8 spriteId2 = sprite->data[0];\n\n        if (gSprites[spriteId2].affineAnimEnded)\n        {\n            sprite->invisible = TRUE;\n            gSprites[spriteId2].invisible = TRUE;\n            sprite->callback = SpriteCB_EndBlinkContestantBox;\n        }\n    }",
  },
  "SpriteCB_EndBlinkContestantBox": {
    callsTo: ["DestroyContestantBoxBlinkSprites","ResetBlendForContestantBoxBlink"],
    lineCount: 3,
    bodyC: "eContestGfxState[sprite->data[1]].boxBlinking = FALSE;\n    DestroyContestantBoxBlinkSprites(sprite->data[0]);\n    ResetBlendForContestantBoxBlink();",
  },
  "SpriteCB_JudgeSpeechBubble": {
    spriteTransitions: ["SpriteCallbackDummy"],
    lineCount: 7,
    bodyC: "if (sprite->data[1]++ > 84)\n    {\n        sprite->data[1] = 0;\n        sprite->invisible = TRUE;\n        sprite->callback = SpriteCallbackDummy;\n        eContest.waitForJudgeSpeechBubble = FALSE;\n    }",
  },
} as const;
