// AUTO-GENERATED from src/intro.c by extract-decomp-task-machines.mjs
// Do not edit manually — re-run `npm run extract:task-machines` to refresh.
//
// Generated: 2026-04-27
// Stats: 33 Task_, 2 CB2_, 21 SpriteCB_

export const TASKS = {
  "Task_Scene1_Load": {
    callsTo: ["BGCNT_CHARBASE","BGCNT_PRIORITY","BGCNT_SCREENBASE","BG_CHAR_ADDR","BG_PLTT_ID","BG_SCREEN_ADDR","CpuCopy16","CreateGameFreakLogoSprites","CreateWaterDrop","DmaClear16","IntroResetGpuRegs","LZ77UnCompVram","LoadCompressedSpriteSheet","LoadPalette","LoadSpritePalettes","MOD","OBJ_PLTT_ID","PLTT_SIZEOF","Random","SetGpuReg","SetVBlankCallback"],
    taskTransitions: ["Task_Scene1_FadeIn"],
    lineCount: 36,
    bodyC: "SetVBlankCallback(NULL);\n    sIntroCharacterGender = MOD(Random(), GENDER_COUNT);\n    IntroResetGpuRegs();\n    SetGpuReg(REG_OFFSET_BG3VOFS, 0);\n    SetGpuReg(REG_OFFSET_BG2VOFS, 80);\n    SetGpuReg(REG_OFFSET_BG1VOFS, 24);\n    SetGpuReg(REG_OFFSET_BG0VOFS, 40);\n    LZ77UnCompVram(sIntro1Bg_Gfx, (void *)VRAM);\n    LZ77UnCompVram(sIntro1Bg0_Tilemap, (void *)(BG_CHAR_ADDR(2)));\n    DmaClear16(3, BG_SCREEN_ADDR(17), BG_SCREEN_SIZE);\n    LZ77UnCompVram(sIntro1Bg1_Tilemap, (void *)(BG_SCREEN_ADDR(18)));\n    DmaClear16(3, BG_SCREEN_ADDR(19), BG_SCREEN_SIZE);\n    LZ77UnCompVram(sIntro1Bg2_Tilemap, (void *)(BG_SCREEN_ADDR(20)));\n    DmaClear16(3, BG_SCREEN_ADDR(21), BG_SCREEN_SIZE);\n    LZ77UnCompVram(sIntro1Bg3_Tilemap, (void *)(BG_SCREEN_ADDR(22)));\n    DmaClear16(3, BG_SCREEN_ADDR(23), BG_SCREEN_SIZE);\n    LoadPalette(sIntro1Bg_Pal, BG_PLTT_ID(0), sizeof(sIntro1Bg_Pal));\n    SetGpuReg(REG_OFFSET_BG3CNT, BGCNT_PRIORITY(3) | BGCNT_CHARBASE(0) | BGCNT_SCREENBASE(22) | BGCNT_16COLOR | BGCNT_TXT256x512);\n    SetGpuReg(REG_OFFSET_BG2CNT, BGCNT_PRIORITY(2) | BGCNT_CHARBASE(0) | BGCNT_SCREENBASE(20) | BGCNT_16COLOR | BGCNT_TXT256x512);\n    SetGpuReg(REG_OFFSET_BG1CNT, BGCNT_PRIORITY(1) | BGCNT_CHARBASE(0) | BGCNT_SCREENBASE(18) | BGCNT_16COLOR | BGCNT_TXT256x512);\n    SetGpuReg(REG_OFFSET_BG0CNT, BGCNT_PRIORITY(0) | BGCNT_CHARBASE(0) | BGCNT_SCREENBASE(16) | BGCNT_16COLOR | BGCNT_TXT256x512);\n    LoadCompressedSpriteSheet(sSpriteSheet_WaterDropsAndLogo);\n    LoadCompressedSpriteSheet(sSpriteSheet_FlygonSilhouette);\n    LoadSpritePalettes(sSpritePalettes_Intro1);\n    LoadCompressedSpriteSheet(sSpriteSheet_Sparkle);\n    LoadSpritePalettes(sSpritePalette_Sparkle);\n    CpuCopy16(&gPlttBufferUnfaded[OBJ_PLTT_ID(0)], &gPlttBufferUnfaded[OBJ_PLTT_ID(15) + 0], PLTT_SIZEOF(16 - 0));\n    CpuCopy16(&gPlttBufferUnfaded[OBJ_PLTT_ID(0)], &gPlttBufferUnfaded[OBJ_PLTT_ID(14) + 1], PLTT_SIZEOF(16 - 1) + 1);  \n    CpuCopy16(&gPlttBufferUnfaded[OBJ_PLTT_ID(0)], &gPlttBufferUnfaded[OBJ_PLTT_ID(13) + 2], PLTT_SIZEOF(16 - 2));\n    CpuCopy16(&gPlttBufferUnfaded[OBJ_PLTT_ID(0)], &gPlttBufferUnfaded[OBJ_PLTT_ID(12) + 3], PLTT_SIZEOF(16 - 3));\n    CpuCopy16(&gPlttBufferUnfaded[OBJ_PLTT_ID(0)], &gPlttBufferUnfaded[OBJ_PLTT_ID(11) + 4], PLTT_SIZEOF(16 - 4));\n    CpuCopy16(&gPlttBufferUnfaded[OBJ_PLTT_ID(0)], &gPlttBufferUnfaded[OBJ_PLTT_ID(10) + 5], PLTT_SIZEOF(16 - 5));\n    CpuCopy16(&gPlttBufferUnfaded[OBJ_PLTT_ID(0)], &gPlttBufferUnfaded[OBJ_PLTT_ID( 9) + 6], PLTT_SIZEOF(16 - 6));\n    CreateGameFreakLogoSprites(DISPLAY_WIDTH / 2, DISPLAY_HEIGHT / 2, 0);\n    gTasks[taskId].sBigDropSpriteId = CreateWaterDrop(236, -14, 0x200, 1, 0x78, FALSE);\n    gTasks[taskId].func = Task_Scene1_FadeIn;",
  },
  "Task_Scene1_FadeIn": {
    callsTo: ["BeginNormalPaletteFade","ResetSerial","SetGpuReg","SetVBlankCallback","m4aSongNumStart"],
    taskTransitions: ["Task_Scene1_WaterDrops"],
    lineCount: 7,
    bodyC: "BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_BLACK);\n    SetVBlankCallback(VBlankCB_Intro);\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_0 | DISPCNT_OBJ_1D_MAP | DISPCNT_BG_ALL_ON | DISPCNT_OBJ_ON);\n    gTasks[taskId].func = Task_Scene1_WaterDrops;\n    gIntroFrameCounter = 0;\n    m4aSongNumStart(MUS_INTRO);\n    ResetSerial();",
  },
  "Task_Scene1_WaterDrops": {
    callsTo: ["CreateTask","CreateWaterDrop"],
    taskTransitions: ["Task_Scene1_PanUp"],
    dataWrites: ["tBg1PosHi","tBg1PosLo","tBg2PosHi","tBg2PosLo","tBg3PosHi","tBg3PosLo"],
    lineCount: 24,
    bodyC: "if (gIntroFrameCounter == TIMER_BIG_DROP_START)\n        gSprites[gTasks[taskId].sBigDropSpriteId].sState = 1;\n\n    if (gIntroFrameCounter == TIMER_LOGO_APPEAR)\n        CreateTask(Task_BlendLogoIn, 0);\n\n    if (gIntroFrameCounter == TIMER_BIG_DROP_FALLS)\n        gSprites[gTasks[taskId].sBigDropSpriteId].sState = 2;\n\n    if (gIntroFrameCounter == TIMER_LOGO_BLEND_OUT)\n        CreateTask(Task_BlendLogoOut, 0);\n\n    if (gIntroFrameCounter == TIMER_SMALL_DROP_1)\n        CreateWaterDrop(48, 0, 0x400, 5, 0x70, TRUE);\n\n    if (gIntroFrameCounter == TIMER_SMALL_DROP_2)\n        CreateWaterDrop(200, 60, 0x400, 9, 0x80, TRUE);\n\n    if (gIntroFrameCounter == TIMER_SPARKLES)\n        CreateTask(Task_CreateSparkles, 0);\n\n    if (gIntroFrameCounter > TIMER_SPARKLES)\n    {\n        gTasks[taskId].tBg2PosHi = 80;\n        gTasks[taskId].tBg2PosLo = 0;\n        gTasks[taskId].tBg1PosHi = 24;\n        gTasks[taskId].tBg1PosLo = 0;\n        gTasks[taskId].tBg3PosHi = 40;\n        gTasks[taskId].tBg3PosLo = 0;\n        gTasks[taskId].func = Task_Scene1_PanUp;\n    }",
  },
  "Task_CreateSparkles": {
    callsTo: ["CreateSprite","DestroyTask"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 18,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n    if (++tTimer & 1)\n        tTimerSteps++;\n\n    switch (tState)\n    {\n    case 0:\n        CreateSprite(&sSpriteTemplate_Sparkle, sSparkleCoords[tNumSparkles][0], sSparkleCoords[tNumSparkles][1] + tTimerSteps, 0);\n        tState++;\n        tDelay = 12;\n        tNumSparkles++;\n        break;\n    case 1:\n        if (--tDelay == 0)\n            tState = 0;\n        break;\n    }\n\n    if (tTimerSteps > 60)\n        DestroyTask(taskId);",
  },
  "Task_Scene1_PanUp": {
    callsTo: ["BeginNormalPaletteFade","CreateSprite","SetGpuReg"],
    taskTransitions: ["Task_Scene1_End"],
    dataReads: ["tBg1PosHi","tBg1PosLo","tBg2PosHi","tBg2PosLo","tBg3PosHi","tBg3PosLo"],
    dataWrites: ["tBg1PosHi","tBg1PosLo","tBg2PosHi","tBg2PosLo","tBg3PosHi","tBg3PosLo"],
    lineCount: 32,
    bodyC: "if (gIntroFrameCounter < TIMER_END_PAN_UP)\n    {\n        s32 offset;\n\n         \n        offset = (gTasks[taskId].tBg2PosHi << 16) + (u16)gTasks[taskId].tBg2PosLo;\n        offset -= 0x6000;\n        gTasks[taskId].tBg2PosHi = offset >> 16;\n        gTasks[taskId].tBg2PosLo = offset;\n        SetGpuReg(REG_OFFSET_BG2VOFS, gTasks[taskId].tBg2PosHi);\n\n         \n        offset = (gTasks[taskId].tBg1PosHi << 16) + (u16)gTasks[taskId].tBg1PosLo;\n        offset -= 0x8000;\n        gTasks[taskId].tBg1PosHi = offset >> 16;\n        gTasks[taskId].tBg1PosLo = offset;\n        SetGpuReg(REG_OFFSET_BG1VOFS, gTasks[taskId].tBg1PosHi);\n\n         \n        offset = (gTasks[taskId].tBg3PosHi << 16) + (u16)gTasks[taskId].tBg3PosLo;\n        offset -= 0xC000;\n        gTasks[taskId].tBg3PosHi = offset >> 16;\n        gTasks[taskId].tBg3PosLo = offset;\n        SetGpuReg(REG_OFFSET_BG0VOFS, gTasks[taskId].tBg3PosHi);\n\n        if (gIntroFrameCounter == TIMER_FLYGON_SILHOUETTE_APPEAR)\n        {\n             \n            u8 spriteId = CreateSprite(&sSpriteTemplate_FlygonSilhouette, 120, DISPLAY_HEIGHT, 10);\n            gSprites[spriteId].invisible = TRUE;\n        }\n    }\n    else\n    {\n        if (gIntroFrameCounter > TIMER_END_SCENE_1)\n        {\n             \n            BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_WHITEALPHA);\n            gTasks[taskId].func = Task_Scene1_End;\n        }\n    }",
  },
  "Task_Scene1_End": {
    taskTransitions: ["Task_Scene2_Load"],
    lineCount: 2,
    bodyC: "if (gIntroFrameCounter > TIMER_START_SCENE_2)\n        gTasks[taskId].func = Task_Scene2_Load;",
  },
  "Task_Scene2_Load": {
    callsTo: ["FreeAllSpritePalettes","IntroResetGpuRegs","LoadIntroPart2Graphics","ResetSpriteData","SetVBlankCallback"],
    taskTransitions: ["Task_Scene2_CreateSprites"],
    lineCount: 9,
    bodyC: "IntroResetGpuRegs();\n    SetVBlankCallback(NULL);\n    ResetSpriteData();\n    FreeAllSpritePalettes();\n    gIntroCredits_MovingSceneryVBase = 0;\n    gIntroCredits_MovingSceneryVOffset = 0;\n    sFlygonYOffset = 0;\n    LoadIntroPart2Graphics(1);\n    gTasks[taskId].func = Task_Scene2_CreateSprites;",
  },
  "Task_Scene2_CreateSprites": {
    callsTo: ["ARRAY_COUNT","BeginNormalPaletteFade","CreateBicycleBgAnimationTask","CreateIntroBrendanSprite","CreateIntroFlygonSprite","CreateIntroMaySprite","CreateSprite","LoadCompressedSpriteSheet","LoadSpritePalettes","SetIntroPart2BgCnt","SetVBlankCallback"],
    taskTransitions: ["Task_Scene2_BikeRide"],
    dataWrites: ["tBgAnimTaskId","tFlygonSpriteId","tPlayerSpriteId"],
    lineCount: 29,
    bodyC: "u8 spriteId;\n\n     \n    if (sIntroCharacterGender == MALE)\n        LoadCompressedSpriteSheet(gSpriteSheet_IntroBrendan);\n    else\n        LoadCompressedSpriteSheet(gSpriteSheet_IntroMay);\n\n    LoadCompressedSpriteSheet(gSpriteSheet_IntroBicycle);\n    LoadCompressedSpriteSheet(gSpriteSheet_IntroFlygon);\n\n     \n    for (spriteId = 0; spriteId < ARRAY_COUNT(sSpriteSheet_RunningPokemon) - 1; spriteId++)\n        LoadCompressedSpriteSheet(&sSpriteSheet_RunningPokemon[spriteId]);\n\n    LoadSpritePalettes(gSpritePalettes_IntroPlayerFlygon);\n    LoadSpritePalettes(sSpritePalettes_RunningPokemon);\n\n     \n    CreateSprite(&sSpriteTemplate_Manectric, DISPLAY_WIDTH + 32, 128, 0);\n    CreateSprite(&sSpriteTemplate_Torchic, DISPLAY_WIDTH + 48, 110, 1);\n\n    if (sIntroCharacterGender == MALE)\n        spriteId = CreateIntroBrendanSprite(DISPLAY_WIDTH + 32, 100);\n    else\n        spriteId = CreateIntroMaySprite(DISPLAY_WIDTH + 32, 100);\n\n    gSprites[spriteId].callback = SpriteCB_PlayerOnBicycle;\n    gSprites[spriteId].anims = sAnims_PlayerBicycle;\n    gTasks[taskId].tPlayerSpriteId = spriteId;\n    CreateSprite(&sSpriteTemplate_Volbeat, DISPLAY_WIDTH + 32, 80, 4);\n    spriteId = CreateIntroFlygonSprite(-64, 60);\n    gSprites[spriteId].callback = SpriteCB_Flygon;\n    gTasks[taskId].tFlygonSpriteId = spriteId;\n\n     \n    BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_WHITEALPHA);\n    SetVBlankCallback(VBlankCB_Intro);\n    gTasks[taskId].tBgAnimTaskId = CreateBicycleBgAnimationTask(1, 0x4000, 0x400, 0x10);\n    SetIntroPart2BgCnt(1);\n    gTasks[taskId].func = Task_Scene2_BikeRide;",
  },
  "Task_Scene2_BikeRide": {
    callsTo: ["BeginNormalPaletteFade","CycleSceneryPalette","DestroyTask","Sin"],
    taskTransitions: ["Task_Scene2_End"],
    dataReads: ["tBgAnimTaskId","tFlygonSpriteId","tFlygonTimer","tPlayerSpriteId"],
    dataWrites: ["tFlygonTimer"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 28,
    bodyC: "u16 offset;\n\n    if (gIntroFrameCounter == TIMER_TORCHIC_EXIT)\n    {\n         \n        gIntroCredits_MovingSceneryState = INTROCRED_SCENERY_FROZEN;\n        DestroyTask(gTasks[taskId].tBgAnimTaskId);\n    }\n\n    if (gIntroFrameCounter > TIMER_END_SCENE_2)\n    {\n         \n        BeginNormalPaletteFade(PALETTES_ALL, 8, 0, 16, RGB_WHITEALPHA);\n        gTasks[taskId].func = Task_Scene2_End;\n    }\n\n     \n     \n    if (gIntroFrameCounter == TIMER_PLAYER_DRIFT_BACK)\n        gSprites[gTasks[taskId].tPlayerSpriteId].sState = 1;\n    if (gIntroFrameCounter == TIMER_PLAYER_MOVE_FORWARD)\n        gSprites[gTasks[taskId].tPlayerSpriteId].sState = 0;\n    if (gIntroFrameCounter == TIMER_FLYGON_ENTER)\n        gSprites[gTasks[taskId].tFlygonSpriteId].sState = 1;\n    if (gIntroFrameCounter == TIMER_PLAYER_MOVE_BACKWARD)\n        gSprites[gTasks[taskId].tPlayerSpriteId].sState = 2;\n    if (gIntroFrameCounter == TIMER_PLAYER_HOLD_POSITION)\n        gSprites[gTasks[taskId].tPlayerSpriteId].sState = 3;\n    if (gIntroFrameCounter == TIMER_PLAYER_EXIT)\n        gSprites[gTasks[taskId].tPlayerSpriteId].sState = 4;\n\n     \n    offset = Sin(gTasks[taskId].tFlygonTimer >> 2 & 0x7F, 48);\n    sFlygonYOffset = offset;\n    if (gTasks[taskId].tFlygonTimer < 512)\n        gTasks[taskId].tFlygonTimer++;\n\n     \n    CycleSceneryPalette(0);",
  },
  "Task_Scene2_End": {
    taskTransitions: ["Task_Scene3_Load"],
    lineCount: 2,
    bodyC: "if (gIntroFrameCounter > TIMER_START_SCENE_3)\n        gTasks[taskId].func = Task_Scene3_Load;",
  },
  "Task_Scene3_Load": {
    callsTo: ["BGCNT_CHARBASE","BGCNT_PRIORITY","BGCNT_SCREENBASE","BG_CHAR_ADDR","BG_PLTT_ID","BeginNormalPaletteFade","FreeAllSpritePalettes","IntroResetGpuRegs","LZ77UnCompVram","LoadPalette","PanFadeAndZoomScreen","ResetSpriteData","SetGpuReg","m4aSongNumStart"],
    taskTransitions: ["Task_Scene3_SpinPokeball"],
    dataWrites: ["data[3]","tAlpha","tZoomDiv","tZoomDivSpeed"],
    lineCount: 17,
    bodyC: "IntroResetGpuRegs();\n    LZ77UnCompVram(sIntroPokeball_Gfx, (void *)VRAM);\n    LZ77UnCompVram(sIntroPokeball_Tilemap, (void *)(BG_CHAR_ADDR(1)));\n    LoadPalette(sIntroPokeball_Pal, BG_PLTT_ID(0), sizeof(sIntroPokeball_Pal));\n    gTasks[taskId].tAlpha = 0;\n    gTasks[taskId].tZoomDiv = 0;\n    gTasks[taskId].tZoomDivSpeed = 0;\n    gTasks[taskId].data[3] = 0;\n    PanFadeAndZoomScreen(DISPLAY_WIDTH / 2, DISPLAY_HEIGHT / 2, 0, 0);\n    ResetSpriteData();\n    FreeAllSpritePalettes();\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_WHITEALPHA);\n    SetGpuReg(REG_OFFSET_BG2CNT, BGCNT_PRIORITY(3) | BGCNT_CHARBASE(0) | BGCNT_SCREENBASE(8) | BGCNT_256COLOR | BGCNT_AFF256x256);\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_1 | DISPCNT_OBJ_1D_MAP | DISPCNT_BG2_ON | DISPCNT_OBJ_ON);\n    gTasks[taskId].func = Task_Scene3_SpinPokeball;\n    gIntroFrameCounter = 0;\n    m4aSongNumStart(MUS_INTRO_BATTLE);",
  },
  "Task_Scene3_SpinPokeball": {
    callsTo: ["BeginNormalPaletteFade","PanFadeAndZoomScreen","SAFE_DIV"],
    taskTransitions: ["Task_Scene3_WaitGroudon"],
    dataReads: ["tAlpha","tZoomDiv","tZoomDivSpeed"],
    dataWrites: ["tAlpha","tZoomDiv","tZoomDivSpeed"],
    lineCount: 13,
    bodyC: "gTasks[taskId].tAlpha += 0x400;\n\n    if (gTasks[taskId].tZoomDiv <= 0x6BF)\n    {\n        gTasks[taskId].tZoomDiv += gTasks[taskId].tZoomDivSpeed;\n        gTasks[taskId].tZoomDivSpeed += 2;\n    }\n    else\n    {\n        gTasks[taskId].func = Task_Scene3_WaitGroudon;\n    }\n\n    PanFadeAndZoomScreen(DISPLAY_WIDTH / 2, DISPLAY_HEIGHT / 2, SAFE_DIV(0x10000, gTasks[taskId].tZoomDiv), gTasks[taskId].tAlpha);\n\n    if (gIntroFrameCounter == TIMER_POKEBALL_FADE)\n        BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_WHITEALPHA);",
  },
  "Task_Scene3_WaitGroudon": {
    taskTransitions: ["Task_Scene3_LoadGroudon"],
    lineCount: 2,
    bodyC: "if (gIntroFrameCounter > TIMER_START_LEGENDARIES)\n        gTasks[taskId].func = Task_Scene3_LoadGroudon;",
  },
  "Task_Scene3_LoadGroudon": {
    callsTo: ["BG_CHAR_ADDR","BG_SCREEN_ADDR","CpuCopy16","FreeAllSpritePalettes","GET_TRUE_SPRITE_INDEX","IntroResetGpuRegs","LZDecompressVram","LoadCompressedSpritePaletteUsingHeap","LoadCompressedSpriteSheetUsingHeap","ResetSpriteData"],
    taskTransitions: ["Task_Scene3_InitGroudonBg"],
    externalChecks: { paletteFade: true },
    lineCount: 15,
    bodyC: "if (!gPaletteFade.active)\n    {\n        IntroResetGpuRegs();\n        ResetSpriteData();\n        FreeAllSpritePalettes();\n        gReservedSpritePaletteCount = 8;\n        LZDecompressVram(gIntroGroudon_Gfx, (void *)VRAM);\n        LZDecompressVram(gIntroGroudon_Tilemap, (void *)(BG_CHAR_ADDR(3)));\n        LZDecompressVram(gIntroLegendBg_Gfx, (void *)(BG_CHAR_ADDR(1)));\n        LZDecompressVram(gIntroGroudonBg_Tilemap, (void *)(BG_SCREEN_ADDR(28)));\n        LoadCompressedSpriteSheetUsingHeap(&gBattleAnimPicTable[GET_TRUE_SPRITE_INDEX(ANIM_TAG_ROCKS)]);\n        LoadCompressedSpritePaletteUsingHeap(&gBattleAnimPaletteTable[GET_TRUE_SPRITE_INDEX(ANIM_TAG_ROCKS)]);\n        CpuCopy16(gIntro3Bg_Pal, gPlttBufferUnfaded, sizeof(gIntro3Bg_Pal));\n        gTasks[taskId].func = Task_Scene3_InitGroudonBg;\n    }",
  },
  "Task_Scene3_InitGroudonBg": {
    callsTo: ["BGCNT_CHARBASE","BGCNT_PRIORITY","BGCNT_SCREENBASE","BeginNormalPaletteFade","PanFadeAndZoomScreen","SetGpuReg"],
    taskTransitions: ["Task_Scene3_NarrowWindow"],
    dataReads: ["tScreenX","tScreenY","tZoom"],
    dataWrites: ["tScreenX","tScreenY","tWinPos","tZoom"],
    lineCount: 28,
    bodyC: "SetGpuReg(REG_OFFSET_WIN0H, DISPLAY_WIDTH);\n    SetGpuReg(REG_OFFSET_WIN0V, DISPLAY_HEIGHT);\n    SetGpuReg(REG_OFFSET_WININ, WININ_WIN0_ALL);\n    SetGpuReg(REG_OFFSET_WINOUT, 0);\n    SetGpuReg(REG_OFFSET_BG2CNT, BGCNT_PRIORITY(0)\n                               | BGCNT_CHARBASE(0)\n                               | BGCNT_SCREENBASE(24)\n                               | BGCNT_256COLOR\n                               | BGCNT_WRAP\n                               | BGCNT_AFF512x512);\n    SetGpuReg(REG_OFFSET_BG1CNT, BGCNT_PRIORITY(1)\n                               | BGCNT_CHARBASE(1)\n                               | BGCNT_SCREENBASE(28)\n                               | BGCNT_16COLOR\n                               | BGCNT_TXT256x256);\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_1\n                                | DISPCNT_OBJ_1D_MAP\n                                | DISPCNT_BG1_ON\n                                | DISPCNT_BG2_ON\n                                | DISPCNT_OBJ_ON\n                                | DISPCNT_WIN0_ON);\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_WHITEALPHA);\n    gTasks[taskId].tWinPos = 0;\n    gTasks[taskId].tScreenX = 0xFFA0;\n    gTasks[taskId].tScreenY = 0xFF51;\n    gTasks[taskId].tZoom = 0x100;\n    PanFadeAndZoomScreen(gTasks[taskId].tScreenX, gTasks[taskId].tScreenY, gTasks[taskId].tZoom, 0);\n    gTasks[taskId].func = Task_Scene3_NarrowWindow;",
  },
  "Task_Scene3_NarrowWindow": {
    callsTo: ["SetGpuReg","WIN_RANGE"],
    taskTransitions: ["Task_Scene3_EndNarrowWindow"],
    dataReads: ["tWinPos"],
    dataWrites: ["tWinPos"],
    lineCount: 10,
    bodyC: "if (gTasks[taskId].tWinPos != NARROW_HEIGHT)\n    {\n        gTasks[taskId].tWinPos += 4;\n        SetGpuReg(REG_OFFSET_WIN0V, (gTasks[taskId].tWinPos * 256) - (gTasks[taskId].tWinPos - DISPLAY_HEIGHT));\n    }\n    else\n    {\n        SetGpuReg(REG_OFFSET_WIN0V, WIN_RANGE(NARROW_HEIGHT, DISPLAY_HEIGHT - NARROW_HEIGHT));\n        gTasks[taskId].func = Task_Scene3_EndNarrowWindow;\n    }",
  },
  "Task_Scene3_EndNarrowWindow": {
    taskTransitions: ["Task_Scene3_StartGroudon"],
    lineCount: 1,
    bodyC: "gTasks[taskId].func = Task_Scene3_StartGroudon;",
  },
  "Task_Scene3_StartGroudon": {
    callsTo: ["ScanlineEffect_InitWave"],
    taskTransitions: ["Task_Scene3_Groudon"],
    dataWrites: ["tState"],
    lineCount: 3,
    bodyC: "gTasks[taskId].tState = 0;\n    gTasks[taskId].func = Task_Scene3_Groudon;\n    ScanlineEffect_InitWave(0, DISPLAY_HEIGHT, 4, 4, 1, SCANLINE_EFFECT_REG_BG1HOFS, FALSE);",
  },
  "Task_Scene3_Groudon": {
    callsTo: ["BG_PLTT_ID","BeginNormalPaletteFade","CpuCopy16","CreateGroudonRockSprites","INTRO3_RAW_PTR","PLTT_SIZEOF","PanFadeAndZoomScreen","PlayCryInternal","Sin"],
    taskTransitions: ["Task_Scene3_LoadKyogre"],
    externalChecks: { paletteFade: true },
    lineCount: 101,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n    tTimer++;\n    if ((tState >= 1 && tState <= 7) && tTimer % 2 == 0)\n        tYShake ^= 3;\n    PanFadeAndZoomScreen(tScreenX, tScreenY + tYShake, tZoom, 0);\n    switch (tState)\n    {\n    case 0:\n        tScreenX += 16;\n        if (tScreenX == 160)\n        {\n            tState++;\n            tDelay = 2;\n            tPalIdx = 0x1E2;\n            CreateGroudonRockSprites(taskId);\n        }\n        break;\n    case 1:\n        if (--tDelay == 0)\n        {\n            tDelay = 2;\n            CpuCopy16(INTRO3_RAW_PTR(tPalIdx), &gPlttBufferFaded[BG_PLTT_ID(1) + 15], PLTT_SIZEOF(1));\n            tPalIdx += 2;\n            if (tPalIdx == 0x1EC)\n                tState++;\n        }\n        break;\n    case 2:\n        if (--tDelay == 0)\n        {\n            tDelay = 2;\n            tState++;\n        }\n        break;\n    case 3:\n        if (--tDelay == 0)\n        {\n            tDelay = 2;\n            CpuCopy16(INTRO3_RAW_PTR(tPalIdx), &gPlttBufferFaded[BG_PLTT_ID(1) + 15], PLTT_SIZEOF(1));\n            tPalIdx -= 2;\n            if (tPalIdx == 0x1E0)\n            {\n                tDelay = 8;\n                tState++;\n            }\n        }\n        break;\n    case 4:\n        if (--tDelay == 0)\n        {\n            tScreenX = -96;\n            tScreenY = 169;\n            tDelay = 3;\n            tState++;\n        }\n        break;\n    case 5:\n        if (--tDelay == 0)\n        {\n            tScreenX = 80;\n            tScreenY = 41;\n            tDelay = 16;\n            PlayCryInternal(SPECIES_GROUDON, 0, 100, CRY_PRIORITY_NORMAL, CRY_MODE_NORMAL);\n            tState++;\n        }\n        break;\n    case 6:\n        if (--tDelay == 0)\n        {\n            tScreenX = 80;\n            tScreenY = 40;\n            tState++;\n        }\n        break;\n    case 7:\n        tScreenX += 4;\n        tScreenY += 4;\n        tTrigIdx += 0x666;\n        tZoom = Sin((tTrigIdx & 0xFF00) >> 8, 64) + 256;\n        if (tScreenX == 120)\n        {\n            BeginNormalPaletteFade(PALETTES_ALL & ~1, 3, 0, 16, RGB_WHITE);\n            tZoom = 256;\n            tYShake = 0;\n            tState++;\n        }\n        break;\n    case 8:\n        if (tZoom)\n            tZoom -= 8;\n        else\n            tState++;\n        break;\n    case 9:\n        if (!gPaletteFade.active)\n        {\n            gTasks[taskId].func = Task_Scene3_LoadKyogre;\n            gScanlineEffect.state = 3;\n        }\n        break;\n    }",
  },
  "Task_Scene3_LoadKyogre": {
    callsTo: ["BG_CHAR_ADDR","BG_SCREEN_ADDR","BeginNormalPaletteFade","LZDecompressVram","LoadCompressedSpriteSheet","LoadSpritePalette","PanFadeAndZoomScreen","ResetSpriteData","ScanlineEffect_InitWave"],
    taskTransitions: ["Task_Scene3_Kyogre"],
    dataReads: ["tScreenX","tScreenY","tZoom"],
    dataWrites: ["tDelay","tScreenX","tScreenY","tState","tZoom"],
    lineCount: 15,
    bodyC: "ResetSpriteData();\n    LZDecompressVram(gIntroKyogre_Gfx, (void *)VRAM);\n    LZDecompressVram(gIntroKyogre_Tilemap, (void *)(BG_CHAR_ADDR(3)));\n    LZDecompressVram(gIntroKyogreBg_Tilemap, (void *)(BG_SCREEN_ADDR(28)));\n    LoadCompressedSpriteSheet(sSpriteSheet_Bubbles);\n    LoadSpritePalette(sSpritePalette_Bubbles);\n    BeginNormalPaletteFade(PALETTES_ALL & ~1, 0, 16, 0, RGB_WHITEALPHA);\n    gTasks[taskId].func = Task_Scene3_Kyogre;\n    gTasks[taskId].tState = 0;\n    gTasks[taskId].tScreenX = 336;\n    gTasks[taskId].tScreenY = 80;\n    gTasks[taskId].tDelay = 16;\n    gTasks[taskId].tZoom = 256;\n    PanFadeAndZoomScreen(gTasks[taskId].tScreenX, gTasks[taskId].tScreenY, gTasks[taskId].tZoom, 0);\n    ScanlineEffect_InitWave(0, DISPLAY_HEIGHT, 4, 4, 1, SCANLINE_EFFECT_REG_BG1VOFS, FALSE);",
  },
  "Task_Scene3_Kyogre": {
    callsTo: ["BG_PLTT_ID","BeginNormalPaletteFade","Cos","CpuCopy16","CreateKyogreBubbleSprites_Body","CreateKyogreBubbleSprites_Fins","INTRO3_RAW_PTR","PLTT_SIZEOF","PanFadeAndZoomScreen","PlayCryInternal","Sin"],
    taskTransitions: ["Task_Scene3_LoadClouds1"],
    dataWrites: ["tScreenX","tScreenY"],
    externalChecks: { paletteFade: true },
    lineCount: 138,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n    PanFadeAndZoomScreen(tScreenX, tScreenY, tZoom, 0);\n\n    switch (tState)\n    {\n    case 0:\n        if (--tDelay != 0)\n            break;\n        tState++;\n    case 1:\n        tTrigIdx += 4;\n        gTasks[taskId].tScreenX = 344 - Sin(tTrigIdx, 0x100);\n        gTasks[taskId].tScreenY = 84 - Cos(tTrigIdx, 0x40);\n        if (tTrigIdx == 64)\n        {\n            tDelay = 0x19;\n            tPalIdx = 1;\n            tState++;\n            CreateKyogreBubbleSprites_Body(0);\n        }\n        break;\n    case 2:\n        if (--tDelay == 0)\n        {\n            gTasks[taskId].tScreenX += 256;\n            gTasks[taskId].tScreenY -= 258;\n            tDelay = 8;\n            tState++;\n            CreateKyogreBubbleSprites_Body(0);\n            CreateKyogreBubbleSprites_Fins();\n        }\n        break;\n    case 3:\n        if (--tDelay == 0)\n        {\n            gTasks[taskId].tScreenX -= 256;\n            gTasks[taskId].tScreenY += 258;\n            tDelay = 8;\n            tState++;\n        }\n        break;\n    case 4:\n        if (--tDelay == 0)\n        {\n            gTasks[taskId].tScreenY -= 252;\n            tDelay = 8;\n            tState++;\n        }\n        break;\n    case 5:\n        if (--tDelay == 0)\n        {\n            gTasks[taskId].tScreenY += 252;\n            if (tPalIdx != 0)\n            {\n                tDelay = 12;\n                tPalIdx--;\n                tState = 2;\n            }\n            else\n            {\n                tDelay = 1;\n                tState++;\n                PlayCryInternal(SPECIES_KYOGRE, 0, 120, CRY_PRIORITY_NORMAL, CRY_MODE_NORMAL);\n            }\n        }\n        break;\n    case 6:\n        if (--tDelay == 0)\n        {\n            tDelay = 4;\n            tPalIdx = 0x1EA;\n            tState++;\n        }\n        break;\n    case 7:\n        if (--tDelay == 0)\n        {\n            tDelay = 4;\n            CpuCopy16(INTRO3_RAW_PTR(tPalIdx), &gPlttBufferFaded[BG_PLTT_ID(2) + 15], PLTT_SIZEOF(1));\n            tPalIdx -= 2;\n            if (tPalIdx == 0x1E0)\n                tState++;\n        }\n        break;\n    case 8:\n        if (--tDelay == 0)\n        {\n            tDelay = 4;\n            tPalIdx = 0x1E2;\n            tState++;\n        }\n        break;\n    case 9:\n        if (--tDelay == 0)\n        {\n            tDelay = 4;\n            CpuCopy16(INTRO3_RAW_PTR(tPalIdx), &gPlttBufferFaded[BG_PLTT_ID(2) + 15], PLTT_SIZEOF(1));\n            tPalIdx += 2;\n            if (tPalIdx == 0x1EE)\n            {\n                tDelay = 16;\n                tState++;\n            }\n        }\n        break;\n    case 10:\n        if (--tDelay == 0)\n        {\n            tTrigIdx = 0;\n            tState++;\n            CreateKyogreBubbleSprites_Body(taskId);\n        }\n        break;\n    case 11:\n        tTrigIdx += 4;\n        tZoom -= 8;\n        gTasks[taskId].tScreenX = Sin(tTrigIdx, 0x3C) + 88;\n        if (tTrigIdx == 64)\n        {\n            BeginNormalPaletteFade(PALETTES_ALL & ~1, 3, 0, 16, RGB_WHITE);\n            tState++;\n        }\n        break;\n    case 12:\n        tTrigIdx += 4;\n        tZoom -= 8;\n        gTasks[taskId].tScreenX = Sin(tTrigIdx, 0x14) + 128;\n        if (tTrigIdx == 128)\n            tState++;\n        break;\n    case 13:\n        if (!gPaletteFade.active)\n        {\n            gTasks[taskId].func = Task_Scene3_LoadClouds1;\n            gScanlineEffect.state = 3;\n        }\n        break;\n    }",
  },
  "Task_Scene3_LoadClouds1": {
    callsTo: ["BGCNT_CHARBASE","BGCNT_PRIORITY","BGCNT_SCREENBASE","BG_CHAR_ADDR","BG_SCREEN_ADDR","BLDALPHA_BLEND","LZDecompressVram","SetGpuReg"],
    taskTransitions: ["Task_Scene3_LoadClouds2"],
    lineCount: 38,
    bodyC: "SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_TGT1_BG0\n                               | BLDCNT_TGT1_BG1\n                               | BLDCNT_TGT1_BG2\n                               | BLDCNT_EFFECT_LIGHTEN);\n    SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(31, 31));\n    SetGpuReg(REG_OFFSET_BLDY, 31);\n    SetGpuReg(REG_OFFSET_BG0CNT, BGCNT_PRIORITY(0)\n                               | BGCNT_CHARBASE(0)\n                               | BGCNT_SCREENBASE(24)\n                               | BGCNT_16COLOR\n                               | BGCNT_TXT512x256);\n    SetGpuReg(REG_OFFSET_BG1CNT, BGCNT_PRIORITY(0)\n                               | BGCNT_CHARBASE(1)\n                               | BGCNT_SCREENBASE(26)\n                               | BGCNT_16COLOR\n                               | BGCNT_TXT512x256);\n    SetGpuReg(REG_OFFSET_BG2CNT, BGCNT_PRIORITY(2)\n                               | BGCNT_CHARBASE(1)\n                               | BGCNT_SCREENBASE(28)\n                               | BGCNT_16COLOR\n                               | BGCNT_TXT256x256);\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_0\n                                | DISPCNT_OBJ_1D_MAP\n                                | DISPCNT_BG0_ON\n                                | DISPCNT_BG1_ON\n                                | DISPCNT_BG2_ON\n                                | DISPCNT_OBJ_ON\n                                | DISPCNT_WIN0_ON);\n    SetGpuReg(REG_OFFSET_BG0HOFS, 80);\n    SetGpuReg(REG_OFFSET_BG0VOFS, 0);\n    SetGpuReg(REG_OFFSET_BG1HOFS, -80);\n    SetGpuReg(REG_OFFSET_BG1VOFS, 0);\n    SetGpuReg(REG_OFFSET_BG2HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG2VOFS, 0);\n    LZDecompressVram(gIntroClouds_Gfx, (void *)VRAM);\n    LZDecompressVram(gIntroClouds_Gfx, (void *)(BG_CHAR_ADDR(1)));\n    LZDecompressVram(gIntroCloudsSun_Tilemap, (void *)(BG_SCREEN_ADDR(28)));\n    gTasks[taskId].func = Task_Scene3_LoadClouds2;",
  },
  "Task_Scene3_LoadClouds2": {
    callsTo: ["BG_CHAR_ADDR","BG_SCREEN_ADDR","LZDecompressVram"],
    taskTransitions: ["Task_Scene3_InitClouds"],
    lineCount: 3,
    bodyC: "LZDecompressVram(gIntroCloudsLeft_Tilemap, (void *)(BG_CHAR_ADDR(3)));\n    LZDecompressVram(gIntroCloudsRight_Tilemap, (void *)(BG_SCREEN_ADDR(26)));\n    gTasks[taskId].func = Task_Scene3_InitClouds;",
  },
  "Task_Scene3_InitClouds": {
    callsTo: ["SetGpuReg"],
    taskTransitions: ["Task_Scene3_Clouds"],
    dataWrites: ["tCloudPos","tState"],
    lineCount: 6,
    bodyC: "SetGpuReg(REG_OFFSET_BLDCNT, 0);\n    SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n    SetGpuReg(REG_OFFSET_BLDY, 0);\n    gTasks[taskId].func = Task_Scene3_Clouds;\n    gTasks[taskId].tState = 0;\n    gTasks[taskId].tCloudPos = 16;",
  },
  "Task_Scene3_Clouds": {
    callsTo: ["BeginNormalPaletteFade","RGB","SetGpuReg"],
    taskTransitions: ["Task_Scene3_LoadLightning"],
    externalChecks: { paletteFade: true },
    lineCount: 22,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n     \n    SetGpuReg(REG_OFFSET_BG0HOFS, (tCloudPos >> 8));\n    SetGpuReg(REG_OFFSET_BG1HOFS, -(tCloudPos >> 8));\n\n    switch (tState)\n    {\n    case 0:\n         \n         \n        if (--tCloudPos == 0)\n        {\n             \n            BeginNormalPaletteFade(PALETTES_ALL & ~1, 0, 16, 0, RGB_WHITEALPHA);\n            tCloudPos = 80 << 8;\n            tState++;\n        }\n        break;\n    case 1:\n         \n        if (tCloudPos == 40 << 8)\n            BeginNormalPaletteFade(PALETTES_BG & ~1, 3, 0, 16, RGB(9, 10, 10));\n\n         \n        if (tCloudPos != 0)\n            tCloudPos -= 128;\n        else if (!gPaletteFade.active)\n            gTasks[taskId].func = Task_Scene3_LoadLightning;\n        break;\n    }",
  },
  "Task_Scene3_LoadLightning": {
    callsTo: ["BG_CHAR_ADDR","BG_SCREEN_ADDR","LZDecompressVram","LoadCompressedSpriteSheetUsingHeap","LoadSpritePalettes","SetGpuReg"],
    taskTransitions: ["Task_Scene3_Lightning"],
    dataWrites: ["tDelay","tState","tTimer"],
    lineCount: 16,
    bodyC: "LZDecompressVram(gIntroRayquaza_Tilemap, (void *)(BG_SCREEN_ADDR(28)));\n    LZDecompressVram(gIntroRayquazaClouds_Tilemap, (void *)(BG_CHAR_ADDR(3)));\n    LZDecompressVram(gIntroRayquaza_Gfx, (void *)(BG_CHAR_ADDR(1)));\n    LZDecompressVram(gIntroRayquazaClouds_Gfx, (void *)VRAM);\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_0\n                                | DISPCNT_OBJ_1D_MAP\n                                | DISPCNT_BG0_ON\n                                | DISPCNT_BG2_ON\n                                | DISPCNT_OBJ_ON\n                                | DISPCNT_WIN0_ON);\n    gTasks[taskId].func = Task_Scene3_Lightning;\n    gTasks[taskId].tState = 0;\n    gTasks[taskId].tDelay = 1;\n    gTasks[taskId].tTimer = 0;\n    LoadCompressedSpriteSheetUsingHeap(sSpriteSheet_Lightning);\n    LoadSpritePalettes(sSpritePalette_Lightning);",
  },
  "Task_Scene3_Lightning": {
    callsTo: ["CreateSprite","StartSpriteAnim"],
    taskTransitions: ["Task_Scene3_LoadRayquazaAttack"],
    lineCount: 33,
    bodyC: "s16 *data = gTasks[taskId].data;\n    u8 spriteId;\n\n    switch (tState)\n    {\n    case 0:\n        if (--tDelay == 0)\n        {\n             \n            CreateSprite(&sSpriteTemplate_Lightning, 200, 48, 0);\n            spriteId = CreateSprite(&sSpriteTemplate_Lightning, 200, 80, 1);\n            StartSpriteAnim(&gSprites[spriteId], 1);\n            spriteId = CreateSprite(&sSpriteTemplate_Lightning, 200, 112, 2);\n            StartSpriteAnim(&gSprites[spriteId], 2);\n            tState++;\n            tDelay = 72;\n        }\n        break;\n    case 1:\n        if (--tDelay == 0)\n        {\n             \n            CreateSprite(&sSpriteTemplate_Lightning, 40, 48, 0);\n            spriteId = CreateSprite(&sSpriteTemplate_Lightning, 40, 80, 1);\n            StartSpriteAnim(&gSprites[spriteId], 1);\n            spriteId = CreateSprite(&sSpriteTemplate_Lightning, 40, 112, 2);\n            StartSpriteAnim(&gSprites[spriteId], 2);\n            tState++;\n            tDelay = 48;\n        }\n        break;\n    case 2:\n        if (--tDelay == 0)\n            gTasks[taskId].func = Task_Scene3_LoadRayquazaAttack;\n        break;\n    }",
  },
  "Task_Scene3_LoadRayquazaAttack": {
    callsTo: ["BeginNormalPaletteFade","CreateTask","LoadCompressedSpriteSheet","LoadSpritePalettes","RGB","SetGpuReg"],
    taskTransitions: ["Task_Scene3_Rayquaza"],
    dataWrites: ["data[1]","data[2]","data[3]","data[4]","tRayquazaTaskId","tState"],
    lineCount: 18,
    bodyC: "u8 attackTaskId;\n\n    LoadCompressedSpriteSheet(sSpriteSheet_RayquazaOrb);\n    LoadSpritePalettes(sSpritePalette_RayquazaOrb);\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_0\n                                | DISPCNT_OBJ_1D_MAP\n                                | DISPCNT_BG0_ON\n                                | DISPCNT_BG2_ON\n                                | DISPCNT_OBJ_ON\n                                | DISPCNT_WIN0_ON);\n    gTasks[taskId].func = Task_Scene3_Rayquaza;\n    BeginNormalPaletteFade(PALETTES_BG & ~(0x21), 0, 16, 0, RGB(9, 10, 10));\n    gTasks[taskId].tState = 0;\n    gTasks[taskId].data[1] = 0xA8;\n    gTasks[taskId].data[2] = -0x10;\n    gTasks[taskId].data[3] = -0x88;\n    gTasks[taskId].data[4] = -0x10;\n    attackTaskId = CreateTask(Task_RayquazaAttack, 0);\n    gTasks[attackTaskId].tRayquazaTaskId = taskId;",
  },
  "Task_Scene3_Rayquaza": {
    taskTransitions: ["Task_EndIntroMovie"],
    externalChecks: { paletteFade: true },
    lineCount: 40,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n    if (tTimer % 2 == 0)\n        data[6] ^= 2;\n\n    tTimer++;\n\n    switch(tState)\n    {\n    case 0:\n        if ((tTimer & 1) != 0)\n        {\n            data[1] -= 2;\n            data[2]++;\n            data[3] += 2;\n            data[4]++;\n        }\n        if (data[1] == 0x68)\n        {\n            tState++;\n            data[5] = 1;\n        }\n        break;\n    case 1:\n        tState++;\n        data[5] = 4;\n        break;\n    case 2:\n        data[1] += 4;\n        data[2] -= 2;\n        data[3] -= 4;\n        data[4] -= 2;\n        if (!gPaletteFade.active)\n        {\n            data[5] = 0x8C;\n            tState++;\n        }\n        break;\n    case 3:\n        if (--data[5] == 0)\n            gTasks[taskId].func = Task_EndIntroMovie;\n        break;\n    }",
  },
  "Task_EndIntroMovie": {
    callsTo: ["DestroyTask","SetMainCallback2"],
    cb2Transitions: ["MainCB2_EndIntro"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 2,
    bodyC: "DestroyTask(taskId);\n    SetMainCallback2(MainCB2_EndIntro);",
  },
  "Task_RayquazaAttack": {
    callsTo: ["BG_PLTT_ID","BeginNormalPaletteFade","BlendPalette","CpuCopy16","CreateSprite","DestroyTask","INTRO3_RAW_PTR","PLTT_SIZEOF","PlaySE","RGB"],
    terminalMarkers: ["DestroyTask"],
    externalChecks: { paletteFade: true },
    lineCount: 89,
    bodyC: "u8 spriteId;\n    s16 *data = gTasks[taskId].data;\n    data[2]++;\n\n    switch(tState)\n    {\n    case 0:\n        if ((data[2] & 1) != 0)\n        {\n            CpuCopy16(INTRO3_RAW_PTR(0x1A2 + data[1] * 2), &gPlttBufferFaded[BG_PLTT_ID(5) + 14], PLTT_SIZEOF(1));\n            data[1]++;\n        }\n        if (data[1] == 6)\n        {\n            tState++;\n            data[1] = 0;\n            data[3] = 10;\n        }\n        break;\n    case 1:\n        if (data[3] == 0)\n        {\n            if ((data[2] & 1) != 0)\n            {\n                CpuCopy16(INTRO3_RAW_PTR(0x1A2 + data[1] * 2), &gPlttBufferFaded[BG_PLTT_ID(5) + 8], PLTT_SIZEOF(1));\n                data[1]++;\n            }\n            if (data[1] == 6)\n            {\n                tState++;\n                data[3] = 10;\n            }\n        }\n        else\n        {\n            data[3]--;\n        }\n        break;\n    case 2:\n        if (data[3] == 0)\n        {\n            if ((data[2] & 1) != 0)\n            {\n                CpuCopy16(INTRO3_RAW_PTR(0x182 + data[1] * 2), &gPlttBufferFaded[BG_PLTT_ID(5) + 12], PLTT_SIZEOF(1));\n                data[1]++;\n            }\n            if (data[1] == 6)\n            {\n                spriteId = CreateSprite(&sSpriteTemplate_RayquazaOrb, 120, 88, 15);\n                PlaySE(SE_INTRO_BLAST);\n                gSprites[spriteId].invisible = TRUE;\n                gSprites[spriteId].data[3] = tRayquazaTaskId;\n                tState++;\n                data[3] = 16;\n            }\n        }\n        else\n        {\n            data[3]--;\n        }\n        break;\n    case 3:\n        if ((data[2] & 1) != 0)\n        {\n            if (--data[3] != 0)\n            {\n                BlendPalette(BG_PLTT_ID(5), 16, data[3], RGB(9, 10, 10));\n                CpuCopy16(INTRO3_RAW_PTR(428), &gPlttBufferFaded[BG_PLTT_ID(5) + 14], PLTT_SIZEOF(1));\n                CpuCopy16(INTRO3_RAW_PTR(428), &gPlttBufferFaded[BG_PLTT_ID(5) + 8], PLTT_SIZEOF(1));\n                CpuCopy16(INTRO3_RAW_PTR(396), &gPlttBufferFaded[BG_PLTT_ID(5) + 12], PLTT_SIZEOF(1));\n            }\n            else\n            {\n                tState++;\n                data[3] = 53;\n            }\n        }\n        break;\n    case 4:\n        if (--data[3] == 0)\n        {\n            BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_WHITE);\n            tState++;\n        }\n        break;\n    case 5:\n        if (!gPaletteFade.active)\n            DestroyTask(taskId);\n        break;\n    }",
  },
  "Task_BlendLogoIn": {
    callsTo: ["ARRAY_COUNT","DestroyTask","SetGpuReg"],
    dataReads: ["data[1]","tState"],
    dataWrites: ["data[1]","tState"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 38,
    bodyC: "switch (gTasks[taskId].tState)\n    {\n    case 0:\n    default:\n        SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_EFFECT_BLEND\n                                   | BLDCNT_TGT2_BG0\n                                   | BLDCNT_TGT2_BG1\n                                   | BLDCNT_TGT2_BG2\n                                   | BLDCNT_TGT2_BG3\n                                   | BLDCNT_TGT2_OBJ\n                                   | BLDCNT_TGT2_BD);\n        SetGpuReg(REG_OFFSET_BLDALPHA, gTitleScreenAlphaBlend[31]);\n        SetGpuReg(REG_OFFSET_BLDY, 0);\n        gTasks[taskId].data[1] = ARRAY_COUNT(gTitleScreenAlphaBlend);\n        gTasks[taskId].tState++;\n        break;\n    case 1:\n        if (gTasks[taskId].data[1] != 0)\n        {\n            u8 tmp;\n\n            gTasks[taskId].data[1]--;\n            tmp = gTasks[taskId].data[1] / 2;\n            SetGpuReg(REG_OFFSET_BLDALPHA, gTitleScreenAlphaBlend[tmp]);\n        }\n        else\n        {\n            SetGpuReg(REG_OFFSET_BLDALPHA, gTitleScreenAlphaBlend[0]);\n            gTasks[taskId].data[1] = ARRAY_COUNT(gTitleScreenAlphaBlend) / 4;\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 2:\n        SetGpuReg(REG_OFFSET_BLDCNT, 0);\n        SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n        SetGpuReg(REG_OFFSET_BLDY, 0);\n        DestroyTask(taskId);\n        break;\n    }",
  },
  "Task_BlendLogoOut": {
    callsTo: ["ARRAY_COUNT","DestroyTask","SetGpuReg"],
    dataReads: ["data[1]","tState"],
    dataWrites: ["data[1]","tState"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 45,
    bodyC: "switch (gTasks[taskId].tState)\n    {\n    case 0:\n    default:\n        SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_EFFECT_BLEND\n                                   | BLDCNT_TGT2_BG0\n                                   | BLDCNT_TGT2_BG1\n                                   | BLDCNT_TGT2_BG2\n                                   | BLDCNT_TGT2_BG3\n                                   | BLDCNT_TGT2_OBJ\n                                   | BLDCNT_TGT2_BD);\n        SetGpuReg(REG_OFFSET_BLDALPHA, gTitleScreenAlphaBlend[0]);\n        SetGpuReg(REG_OFFSET_BLDY, 0);\n        gTasks[taskId].data[1] = 0;\n        gTasks[taskId].tState++;\n        break;\n    case 1:\n        if (gTasks[taskId].data[1] < (int)ARRAY_COUNT(gTitleScreenAlphaBlend) - 2)\n        {\n            u8 tmp;\n\n            gTasks[taskId].data[1]++;\n            tmp = gTasks[taskId].data[1] / 2;\n            SetGpuReg(REG_OFFSET_BLDALPHA, gTitleScreenAlphaBlend[tmp]);\n        }\n        else\n        {\n            SetGpuReg(REG_OFFSET_BLDALPHA, gTitleScreenAlphaBlend[31]);\n            gTasks[taskId].data[1] = ARRAY_COUNT(gTitleScreenAlphaBlend) / 4;\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 2:\n        if (gTasks[taskId].data[1] != 0)\n        {\n            gTasks[taskId].data[1]--;\n        }\n        else\n        {\n            SetGpuReg(REG_OFFSET_BLDCNT, 0);\n            SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n            SetGpuReg(REG_OFFSET_BLDY, 0);\n            DestroyTask(taskId);\n        }\n        break;\n    }",
  },
} as const;

export const CB2S = {
  "CB2_InitCopyrightScreenAfterBootup": {
    callsTo: ["GetSaveBlocksPointersBaseOffset","InitHeap","LoadGameSave","ResetMenuAndMonGlobals","Sav2_ClearSetDefault","Save_ResetSaveCounters","SetPokemonCryStereo","SetSaveBlocksPointers","SetUpCopyrightScreen"],
    lineCount: 11,
    bodyC: "if (!SetUpCopyrightScreen())\n    {\n        SetSaveBlocksPointers(GetSaveBlocksPointersBaseOffset());\n        ResetMenuAndMonGlobals();\n        Save_ResetSaveCounters();\n        LoadGameSave(SAVE_NORMAL);\n        if (gSaveFileStatus == SAVE_STATUS_EMPTY || gSaveFileStatus == SAVE_STATUS_CORRUPT)\n            Sav2_ClearSetDefault();\n        SetPokemonCryStereo(gSaveBlock2Ptr->optionsSound);\n        InitHeap(gHeap, HEAP_SIZE);\n    }",
  },
  "CB2_InitCopyrightScreenAfterTitleScreen": {
    callsTo: ["SetUpCopyrightScreen"],
    lineCount: 1,
    bodyC: "SetUpCopyrightScreen();",
  },
} as const;

export const SPRITE_CBS = {
  "SpriteCB_Sparkle": {
    callsTo: ["DestroySprite"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 2,
    bodyC: "if (++sprite->sTimer == 12)\n        DestroySprite(sprite);",
  },
  "SpriteCB_Volbeat": {
    callsTo: ["Cos","DestroySprite","Sin"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 80,
    bodyC: "sprite->sCosYIdx += 4;\n    switch (sprite->sState)\n    {\n    case VOLBEAT_WAIT_ENTER:\n        if (++sprite->sStateDelay < 180)\n            break;\n        sprite->sState++;\n         \n    case VOLBEAT_ENTER:\n        sprite->x -= 4;\n        if (sprite->x == 60)\n        {\n            sprite->sState = VOLBEAT_WAIT_STATE;\n            sprite->sStateDelay = 20;\n            sprite->sNextState = VOLBEAT_ZIP_BACKWARD;\n        }\n        break;\n    case VOLBEAT_ZIP_BACKWARD:\n        sprite->x += 8;\n        sprite->y -= 2;\n        if (sprite->x == 124)\n        {\n            sprite->sState = VOLBEAT_WAIT_STATE;\n            sprite->sStateDelay = 20;\n            sprite->sNextState = VOLBEAT_ZIP_DOWN;\n        }\n        break;\n    case VOLBEAT_ZIP_DOWN:\n        sprite->y += 4;\n        if (sprite->y == 80)\n        {\n            sprite->sState = VOLBEAT_WAIT_STATE;\n            sprite->sStateDelay = 10;\n            sprite->sNextState = VOLBEAT_ZIP_FORWARD;\n        }\n        break;\n    case VOLBEAT_ZIP_FORWARD:\n        sprite->x -= 8;\n        sprite->y -= 2;\n        if (sprite->x == 60)\n        {\n            sprite->sState = VOLBEAT_WAIT_STATE;\n            sprite->sStateDelay = 10;\n            sprite->sNextState = VOLBEAT_INIT_FIGURE_8;\n        }\n        break;\n    case VOLBEAT_INIT_FIGURE_8:\n        sprite->x += 60;\n        sprite->sSinXIdx = 0xC0;\n        sprite->sSinYIdx = 0x80;\n        sprite->sFig8Loops = 3;\n        sprite->sState++;\n         \n    case VOLBEAT_FIGURE_8:\n        sprite->x2 = Sin((u8)sprite->sSinXIdx, 0x3C);\n        sprite->y2 = Sin((u8)sprite->sSinYIdx, 0x14);\n        sprite->sSinXIdx += 2;\n        sprite->sSinYIdx += 4;\n        if ((sprite->sSinXIdx & 0xFF) == 64)\n        {\n            sprite->hFlip = FALSE;\n            if (--sprite->sFig8Loops == 0)\n            {\n                sprite->x += sprite->x2;\n                sprite->x2 = 0;\n                sprite->sState++;\n            }\n        }\n        break;\n    case VOLBEAT_EXIT:\n        sprite->x -= 2;\n        sprite->y2 = Sin((u8)sprite->sSinYIdx, 0x14);\n        sprite->sSinYIdx += 4;\n        if (sprite->x < -16)\n            DestroySprite(sprite);\n        break;\n    case VOLBEAT_WAIT_STATE:\n         \n        sprite->y2 = Cos((u8)sprite->sCosYIdx, 2);\n        if (!--sprite->sStateDelay)\n            sprite->sState = sprite->sNextState;\n        break;\n    }",
  },
  "SpriteCB_Torchic": {
    callsTo: ["StartSpriteAnim"],
    lineCount: 72,
    bodyC: "switch (sprite->sState)\n    {\n    case 0:\n        if (gIntroFrameCounter == TIMER_TORCHIC_ENTER)\n        {\n            StartSpriteAnim(sprite, TORCHIC_ANIM_RUN);\n            sprite->sState++;\n        }\n        break;\n    case 1:\n        if (gIntroFrameCounter == TIMER_PLAYER_HOLD_POSITION)\n        {\n            StartSpriteAnim(sprite, TORCHIC_ANIM_WALK);\n            sprite->sState++;\n        }\n        else\n        {\n            sprite->sMoveTimer += 64;\n            if (sprite->sMoveTimer & 0xFF00)\n            {\n                sprite->x--;\n                sprite->sMoveTimer &= 0xFF;\n            }\n        }\n        break;\n    case 2:\n        if (gIntroFrameCounter != TIMER_TORCHIC_SPEED_UP)\n        {\n            sprite->sMoveTimer += 32;\n            if (sprite->sMoveTimer & 0xFF00)\n            {\n                sprite->x++;\n                sprite->sMoveTimer &= 0xFF;\n            }\n        }\n        else\n        {\n            StartSpriteAnim(sprite, TORCHIC_ANIM_RUN);\n            sprite->sState++;\n            sprite->sDelay = 80;\n        }\n        break;\n    case 3:\n        if (--sprite->sDelay)\n        {\n            sprite->sMoveTimer += 64;\n            if (sprite->sMoveTimer & 0xFF00)\n            {\n                sprite->x--;\n                sprite->sMoveTimer &= 0xFF;\n            }\n        }\n        else\n        {\n            StartSpriteAnim(sprite, TORCHIC_ANIM_TRIP);\n            sprite->sState++;\n        }\n        break;\n    case 4:\n        if (sprite->animEnded)\n            sprite->x += 4;\n\n        if (sprite->x > 336)\n        {\n            StartSpriteAnim(sprite, TORCHIC_ANIM_RUN);\n            sprite->sState++;\n        }\n        break;\n    case 5:\n        if (gIntroFrameCounter >= TIMER_TORCHIC_EXIT)\n            sprite->x -= 2;\n        break;\n    }",
  },
  "SpriteCB_Manectric": {
    callsTo: ["Cos","DestroySprite","Sin"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 37,
    bodyC: "switch (sprite->sState)\n    {\n    case 0:\n        if (gIntroFrameCounter == TIMER_MANECTRIC_ENTER)\n            sprite->sState++;\n        break;\n    case 1:\n        sprite->x -= 2;\n        if (gIntroFrameCounter != TIMER_MANECTRIC_RUN_CIRCULAR)\n            break;\n\n         \n        sprite->y -= 12;\n        sprite->sSinIdx = 0x80;\n        sprite->sCosIdx = 0;\n        sprite->sState++;\n         \n    case 2:\n        if (sprite->x + sprite->x2 <= -32)\n        {\n             \n            DestroySprite(sprite);\n        }\n        else\n        {\n             \n            if ((sprite->sSinIdx & 0xFF) < 64)\n            {\n                sprite->x2 = Sin((u8)sprite->sSinIdx, 16);\n            }\n            else\n            {\n                if ((sprite->sSinIdx & 0xFF) == 64)\n                    sprite->x -= 48;\n                sprite->x2 = Sin((u8)sprite->sSinIdx, 64);\n            }\n            sprite->sSinIdx++;\n            sprite->y2 = Cos((u8)sprite->sCosIdx, 12);\n            sprite->sCosIdx++;\n        }\n        break;\n    }",
  },
  "SpriteCB_GroudonRocks": {
    lineCount: 23,
    bodyC: "sprite->sTimer++;\n    if (sprite->sTimer % 2 == 0)\n        sprite->y2 ^= 3;\n\n    switch(sprite->sState)\n    {\n    case 0:\n         \n        sprite->sSpeed += sGroudonRockData[sprite->sRockId][2];\n        sprite->y -= (sprite->sSpeed & 0xFF00) >> 8;\n        sprite->sSpeed &= 0xFF;\n\n         \n        if (gTasks[sprite->sTaskId].tState > 7)\n            sprite->sState++;\n        break;\n    case 1:\n         \n        if (sprite->x < DISPLAY_WIDTH / 2)\n            sprite->x -= 2;\n        else\n            sprite->x += 2;\n\n        if (sprite->y < DISPLAY_HEIGHT / 2)\n            sprite->y -= 2;\n        else\n            sprite->y += 2;\n        break;\n    }",
  },
  "SpriteCB_KyogreBubbles": {
    callsTo: ["DestroySprite","Sin","StartSpriteAnim"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 33,
    bodyC: "switch(sprite->sState)\n    {\n    case 0:\n        if (sprite->sDelay == 0)\n        {\n             \n            sprite->sSinIdx = (sprite->sSinIdx + 11) & 0xFF;\n            sprite->x2 = Sin(sprite->sSinIdx, 4);\n            sprite->sBaseY += 48;\n            sprite->y2 = -(sprite->sBaseY >> 8);\n            if (sprite->animEnded)\n                DestroySprite(sprite);\n        }\n        else if (--sprite->sDelay == 0)\n        {\n             \n            StartSpriteAnim(sprite, 0);\n            sprite->invisible = FALSE;\n        }\n\n         \n         \n        if (gTasks[sprite->sTaskId].tState > 11)\n            sprite->sState++;\n        break;\n    case 1:\n         \n        if (sprite->x < DISPLAY_WIDTH / 2)\n            sprite->x -= 3;\n        else\n            sprite->x += 3;\n\n        if (sprite->y < DISPLAY_HEIGHT / 2)\n            sprite->y -= 3;\n        else\n            sprite->y += 3;\n\n        if ((u16)(sprite->y - 20) > DISPLAY_HEIGHT - 20)\n            DestroySprite(sprite);\n        break;\n    }",
  },
  "SpriteCB_Lightning": {
    callsTo: ["BG_PLTT_ID","CpuCopy16","DestroySprite","INTRO3_RAW_PTR","PLTT_SIZEOF"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 26,
    bodyC: "if (sprite->animEnded)\n        sprite->invisible = TRUE;\n\n    switch(sprite->sState)\n    {\n    case 0:\n        sprite->sPalIdx = 0x1C2;\n        sprite->sState++;\n    case 1:\n        CpuCopy16(INTRO3_RAW_PTR(sprite->sPalIdx), &gPlttBufferFaded[BG_PLTT_ID(5) + 13], PLTT_SIZEOF(1));\n        sprite->sPalIdx += 2;\n        if (sprite->sPalIdx != 0x1CE)\n            break;\n        sprite->sPalIdx = 0x1CC;\n        sprite->sDelay = 4;\n        sprite->sState++;\n    case 2:\n        if (--sprite->sDelay == 0)\n        {\n            sprite->sDelay = 4;\n            CpuCopy16(INTRO3_RAW_PTR(sprite->sPalIdx), &gPlttBufferFaded[BG_PLTT_ID(5) + 13], PLTT_SIZEOF(1));\n            sprite->sPalIdx -= 2;\n            if (sprite->sPalIdx == 0x1C0)\n                DestroySprite(sprite);\n        }\n        break;\n    }",
  },
  "SpriteCB_WaterDrop_Ripple": {
    callsTo: ["DestroySprite","SetOamMatrix"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 22,
    bodyC: "u8 palNum;\n\n    if (sprite->data[2] >= 192)\n    {\n        if (sprite->data[3] != 0)\n        {\n            sprite->data[3]--;\n        }\n        else\n        {\n            sprite->invisible = FALSE;\n            SetOamMatrix(sprite->data[1], sprite->data[2], 0, 0, sprite->data[2]);\n            sprite->data[2] = (sprite->data[2] * 95) / 100;\n            palNum = (sprite->data[2] - 192) / 128 + 9;\n            if (palNum > 15)\n                palNum = 15;\n            sprite->oam.paletteNum = palNum;\n        }\n    }\n    else\n    {\n        DestroySprite(sprite);\n    }",
  },
  "SpriteCB_WaterDropHalf": {
    callsTo: ["CalcCenterToCornerVec","SPRITE_SHAPE","SPRITE_SIZE","StartSpriteAnim"],
    spriteTransitions: ["SpriteCB_WaterDrop_Ripple"],
    lineCount: 20,
    bodyC: "if (gSprites[sprite->data[7]].data[7] != 0)\n    {\n        sprite->invisible = TRUE;\n        sprite->x += sprite->x2;\n        sprite->y += sprite->y2;\n        StartSpriteAnim(sprite, DROP_ANIM_RIPPLE);\n        sprite->data[2] = 1024;\n        sprite->data[3] = 8 * (sprite->data[1] & 3);\n        sprite->callback = SpriteCB_WaterDrop_Ripple;\n        sprite->oam.shape = SPRITE_SHAPE(64x32);\n        sprite->oam.size = SPRITE_SIZE(64x32);\n        CalcCenterToCornerVec(sprite, SPRITE_SHAPE(64x32), SPRITE_SIZE(64x32), ST_OAM_AFFINE_ERASE);\n    }\n    else\n    {\n        sprite->x2 = gSprites[sprite->data[7]].x2;\n        sprite->y2 = gSprites[sprite->data[7]].y2;\n        sprite->x = gSprites[sprite->data[7]].x;\n        sprite->y = gSprites[sprite->data[7]].y;\n    }",
  },
  "SpriteCB_WaterDrop": {
    spriteTransitions: ["SpriteCB_WaterDrop_Slide"],
    lineCount: 2,
    bodyC: "if (sprite->sState != 0)\n        sprite->callback = SpriteCB_WaterDrop_Slide;",
  },
  "SpriteCB_WaterDrop_Slide": {
    callsTo: ["SetOamMatrix"],
    spriteTransitions: ["SpriteCB_WaterDrop_ReachLeafEnd"],
    lineCount: 44,
    bodyC: "if (sprite->x <= 116)\n    {\n        sprite->y += sprite->y2;\n        sprite->y2 = 0;\n        sprite->x += 4;\n        sprite->x2 = -4;\n        sprite->data[4] = 128;\n        sprite->callback = SpriteCB_WaterDrop_ReachLeafEnd;\n    }\n    else\n    {\n        u16 data2;\n        u16 data3;\n        u16 data4;\n        s16 sin1;\n        s16 sin2;\n        s16 sin3;\n        s16 sin4;\n        s16 var1;\n        s16 var2;\n        s16 var3;\n        s16 var4;\n        s16 temp;\n\n        data4 = sprite->data[4];\n        sin1 = gSineTable[(u8)data4];\n        sin2 = gSineTable[(u8)(data4 + 64)];\n        sprite->data[4] += 2;\n        sprite->y2 = sin1 / 32;\n        sprite->x--;\n        if (sprite->x & 1)\n            sprite->y++;\n        temp = -sin2 / 16;\n        data2 = sprite->data[2];\n        data3 = sprite->data[3];\n        sin3 = gSineTable[(u8)(temp - 16)];\n        sin4 = gSineTable[(u8)(temp + 48)];\n        var1 = sin4 * data2 / 256;\n        var2 = -sin3 * data3 / 256;\n        var3 = sin3 * data2 / 256;\n        var4 = sin4 * data3 / 256;\n        SetOamMatrix(sprite->data[1], data2, 0, 0, data3);\n        SetOamMatrix(sprite->data[1] + 1, var1, var3, var2, var4);\n        SetOamMatrix(sprite->data[1] + 2, var1, var3, var2 * 2, var4 * 2);\n    }",
  },
  "SpriteCB_WaterDrop_ReachLeafEnd": {
    callsTo: ["SetOamMatrix"],
    spriteTransitions: ["SpriteCB_WaterDrop_DangleFromLeaf"],
    lineCount: 16,
    bodyC: "SetOamMatrix(sprite->data[1], sprite->data[6] + 64, 0, 0, sprite->data[6] + 64);\n    SetOamMatrix(sprite->data[1] + 1, sprite->data[6] + 64, 0, 0, sprite->data[6] + 64);\n    SetOamMatrix(sprite->data[1] + 2, sprite->data[6] + 64, 0, 0, sprite->data[6] + 64);\n    if (sprite->data[4] != MAX_SPRITES)\n    {\n        u16 sinIdx;\n        sprite->data[4] -= 8;\n        sinIdx = sprite->data[4];\n        sprite->x2 = gSineTable[(u8)(sinIdx + 64)] / 64;\n        sprite->y2 = gSineTable[(u8)sinIdx] / 64;\n    }\n    else\n    {\n        sprite->data[4] = 0;\n        sprite->callback = SpriteCB_WaterDrop_DangleFromLeaf;\n    }",
  },
  "SpriteCB_WaterDrop_DangleFromLeaf": {
    spriteTransitions: ["SpriteCB_WaterDrop_Fall"],
    lineCount: 12,
    bodyC: "if (sprite->data[0] != 2)\n    {\n        s16 r2;\n\n        sprite->data[4] += 8;\n        r2 = gSineTable[(u8)sprite->data[4]] / 16 + 64;\n        sprite->x2 = gSineTable[(u8)(r2 + 64)] / 64;\n        sprite->y2 = gSineTable[(u8)r2] / 64;\n    }\n    else\n    {\n        sprite->callback = SpriteCB_WaterDrop_Fall;\n    }",
  },
  "SpriteCB_WaterDrop_Fall": {
    callsTo: ["CalcCenterToCornerVec","SPRITE_SHAPE","SPRITE_SIZE","StartSpriteAnim"],
    spriteTransitions: ["SpriteCB_WaterDrop_Ripple"],
    lineCount: 18,
    bodyC: "if (sprite->y < sprite->data[5])\n    {\n        sprite->y += 4;\n    }\n    else\n    {\n        sprite->data[7] = 1;\n        sprite->invisible = TRUE;\n        sprite->x += sprite->x2;\n        sprite->y += sprite->y2;\n        StartSpriteAnim(sprite, DROP_ANIM_RIPPLE);\n        sprite->data[2] = 1024;\n        sprite->data[3] = 8 * (sprite->data[1] & 3);\n        sprite->callback = SpriteCB_WaterDrop_Ripple;\n        sprite->oam.shape = SPRITE_SHAPE(64x32);\n        sprite->oam.size = SPRITE_SIZE(64x32);\n        CalcCenterToCornerVec(sprite, SPRITE_SHAPE(64x32), SPRITE_SIZE(64x32), ST_OAM_AFFINE_ERASE);\n    }",
  },
  "SpriteCB_WaterDropShort": {
    callsTo: ["CalcCenterToCornerVec","SPRITE_SHAPE","SPRITE_SIZE","StartSpriteAnim"],
    spriteTransitions: ["SpriteCB_WaterDrop_Ripple"],
    lineCount: 18,
    bodyC: "if (sprite->y < sprite->data[5])\n    {\n        sprite->y += 4;\n    }\n    else\n    {\n        sprite->data[7] = 1;\n        sprite->invisible = TRUE;\n        sprite->x += sprite->x2;\n        sprite->y += sprite->y2;\n        StartSpriteAnim(sprite, DROP_ANIM_RIPPLE);\n        sprite->data[2] = 1024;\n        sprite->data[3] = 8 * (sprite->data[1] & 3);\n        sprite->callback = SpriteCB_WaterDrop_Ripple;\n        sprite->oam.shape = SPRITE_SHAPE(64x32);\n        sprite->oam.size = SPRITE_SIZE(64x32);\n        CalcCenterToCornerVec(sprite, SPRITE_SHAPE(64x32), SPRITE_SIZE(64x32), ST_OAM_AFFINE_ERASE);\n    }",
  },
  "SpriteCB_PlayerOnBicycle": {
    callsTo: ["Random","StartSpriteAnimIfDifferent"],
    lineCount: 45,
    bodyC: "switch (sprite->sState)\n    {\n    case 0:\n         \n        StartSpriteAnimIfDifferent(sprite, 0);\n        sprite->x--;\n        break;\n    case 1:\n         \n        StartSpriteAnimIfDifferent(sprite, 0);\n        if (gIntroFrameCounter & 7)\n            return;\n        sprite->x++;\n        break;\n    case 2:\n         \n        if (sprite->x <= 120 || gIntroFrameCounter & 7)\n            sprite->x++;\n        break;\n    case 3:\n         \n        break;\n    case 4:\n         \n        if (sprite->x > -32)\n            sprite->x -= 2;\n        break;\n    }\n\n    if (gIntroFrameCounter & 7)\n        return;\n\n     \n    if (sprite->y2 != 0)\n    {\n         \n        sprite->y2 = 0;\n    }\n    else\n    {\n         \n        switch (Random() & 3)\n        {\n        case 0:\n            sprite->y2 = -1;\n            break;\n        case 1:\n            sprite->y2 = 1;\n            break;\n        case 2:\n        case 3:\n            sprite->y2 = 0;\n            break;\n        }\n    }",
  },
  "SpriteCB_Flygon": {
    callsTo: ["Sin"],
    lineCount: 23,
    bodyC: "switch (sprite->sState)\n    {\n    case 0:\n        break;\n    case 1:\n        if (sprite->x2 + sprite->x < DISPLAY_WIDTH + 64)\n            sprite->x2 += 8;\n        else\n            sprite->sState = 2;\n        break;\n    case 2:\n        if (sprite->x2 + sprite->x > 120)\n            sprite->x2 -= 1;\n        else\n            sprite->sState = 3;\n        break;\n    case 3:\n        if (sprite->x2 > 0)\n            sprite->x2 -= 2;\n        break;\n    }\n    sprite->y2 = Sin((u8)sprite->sSinIdx, 8) - sFlygonYOffset;\n    sprite->sSinIdx += 4;",
  },
  "SpriteCB_LogoLetter": {
    callsTo: ["CpuCopy16","DestroySprite","OBJ_PLTT_ID","PLTT_SIZEOF","StartSpriteAffineAnim"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 87,
    bodyC: "switch (sprite->sState)\n    {\n    case 0:\n        if (sprite->sTimer != 0)\n        {\n            sprite->sTimer--;\n        }\n        else\n        {\n             \n            sprite->invisible = FALSE;\n            StartSpriteAffineAnim(sprite, 1);\n            sprite->sState++;\n        }\n        break;\n    case 1:\n        if (gIntroFrameCounter == TIMER_LOGO_LETTERS_COLOR)\n        {\n             \n            sprite->sState++;\n            sprite->sTimer = COLOR_CHANGES;\n            sprite->sColorDelay = 2;\n        }\n        break;\n    case 2:\n         \n        if (sprite->sColorDelay == 0)\n        {\n            sprite->sColorDelay = 2;\n            if (sprite->sTimer != 0)\n            {\n                CpuCopy16(&gIntroGameFreakTextFade_Pal[sprite->sTimer],      &gPlttBufferFaded[OBJ_PLTT_ID(1) + 15], PLTT_SIZEOF(1));\n                CpuCopy16(&gIntroGameFreakTextFade_Pal[sprite->sTimer + 16], &gPlttBufferFaded[OBJ_PLTT_ID(1) + 4], PLTT_SIZEOF(1));\n                CpuCopy16(&gIntroGameFreakTextFade_Pal[sprite->sTimer + 32], &gPlttBufferFaded[OBJ_PLTT_ID(1) + 10], PLTT_SIZEOF(1));\n                sprite->sTimer--;\n            }\n            else\n            {\n                CpuCopy16(&gIntroGameFreakTextFade_Pal[sprite->sTimer],      &gPlttBufferFaded[OBJ_PLTT_ID(1) + 15], PLTT_SIZEOF(1));\n                CpuCopy16(&gIntroGameFreakTextFade_Pal[sprite->sTimer + 16], &gPlttBufferFaded[OBJ_PLTT_ID(1) + 4], PLTT_SIZEOF(1));\n                CpuCopy16(&gIntroGameFreakTextFade_Pal[sprite->sTimer + 32], &gPlttBufferFaded[OBJ_PLTT_ID(1) + 10], PLTT_SIZEOF(1));\n                sprite->sState++;\n            }\n        }\n        else\n        {\n            sprite->sColorDelay--;\n        }\n        break;\n    case 3:\n         \n        if (sprite->sColorDelay != 0)\n        {\n            sprite->sColorDelay--;\n        }\n        else\n        {\n            sprite->sColorDelay = 2;\n            if (sprite->sTimer <= COLOR_CHANGES)\n            {\n                CpuCopy16(&gIntroGameFreakTextFade_Pal[sprite->sTimer],      &gPlttBufferFaded[OBJ_PLTT_ID(1) + 15], PLTT_SIZEOF(1));\n                CpuCopy16(&gIntroGameFreakTextFade_Pal[sprite->sTimer + 16], &gPlttBufferFaded[OBJ_PLTT_ID(1) + 4], PLTT_SIZEOF(1));\n                CpuCopy16(&gIntroGameFreakTextFade_Pal[sprite->sTimer + 32], &gPlttBufferFaded[OBJ_PLTT_ID(1) + 10], PLTT_SIZEOF(1));\n                sprite->sTimer++;\n            }\n            else\n            {\n                sprite->sState++;\n            }\n        }\n        break;\n    case 4:\n        if (gIntroFrameCounter == TIMER_LOGO_DISAPPEAR)\n        {\n             \n            StartSpriteAffineAnim(sprite, 2);\n            sprite->oam.objMode = ST_OAM_OBJ_BLEND;\n            sprite->sState++;\n        }\n        break;\n    case 5:\n         \n        sprite->sLetterX += sGameFreakLettersMoveSpeed[sprite->sLetterId];\n        sprite->x2 = (sprite->sLetterX & 0xFF00) >> 8;\n        if (sprite->sLetterId < 4)\n        {\n             \n            s16 temp = sprite->x2;\n            sprite->x2 = -temp;\n        }\n        if (sprite->affineAnimEnded)\n            DestroySprite(sprite);\n        break;\n    }",
  },
  "SpriteCB_GameFreakLogo": {
    callsTo: ["DestroySprite","StartSpriteAffineAnim"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 21,
    bodyC: "switch(sprite->sState)\n    {\n    case 0:\n        if (gIntroFrameCounter == TIMER_LOGO_APPEAR)\n        {\n            sprite->invisible = FALSE;\n            sprite->sState++;\n        }\n        break;\n    case 1:\n        if (gIntroFrameCounter == TIMER_LOGO_DISAPPEAR)\n        {\n             \n            StartSpriteAffineAnim(sprite, 3);\n            sprite->sState++;\n        }\n        break;\n    case 2:\n        if (sprite->affineAnimEnded)\n            DestroySprite(sprite);\n        break;\n    }",
  },
  "SpriteCB_FlygonSilhouette": {
    callsTo: ["CalcCenterToCornerVec","Cos","Q_8_8_TO_INT","SPRITE_SHAPE","SPRITE_SIZE","SetOamMatrix","Sin"],
    lineCount: 51,
    bodyC: "sprite->sTimer++;\n\n    if (sprite->sState != 0)\n    {\n        s16 sin;\n        s16 cos;\n\n        s16 a, b, c, d;\n         \n        sin = gSineTable[(u8)sprite->sRot];\n        cos = gSineTable[(u8)(sprite->sRot + 64)];\n         \n        d = Q_8_8_TO_INT( cos * sprite->sScale);\n        c = Q_8_8_TO_INT(-sin * sprite->sScale);\n        b = Q_8_8_TO_INT( sin * sprite->sScale);\n        a = Q_8_8_TO_INT( cos * sprite->sScale);\n\n        SetOamMatrix(1, a, b, c, d);\n    }\n\n    switch (sprite->sState)\n    {\n    case 0:\n    default:\n        sprite->oam.affineMode = ST_OAM_AFFINE_DOUBLE;\n        sprite->oam.matrixNum = 1;\n        CalcCenterToCornerVec(sprite, SPRITE_SHAPE(64x32), SPRITE_SIZE(64x32), ST_OAM_AFFINE_DOUBLE);\n        sprite->invisible = FALSE;\n        sprite->sState = 1;\n        sprite->sScale = 128;\n        sprite->sRot = 0;\n        sprite->sPos = 0;\n        break;\n    case 1:\n        sprite->x2 = -Sin((u8)sprite->sPos, 140);\n        sprite->y2 = -Sin((u8)sprite->sPos, 120);\n        sprite->sScale += 7;\n        sprite->sPos += 3;\n        if (sprite->x + sprite->x2 <= -16)\n        {\n            sprite->oam.priority = 3;\n            sprite->sState++;\n            sprite->x = 20;\n            sprite->y = 40;\n            sprite->sScale = 512;\n            sprite->sRot = 0;\n            sprite->sPos = 16;\n        }\n        break;\n    case 2:\n        sprite->x2 = Sin((u8)sprite->sPos, 34);\n        sprite->y2 = -Cos((u8)sprite->sPos, 60);\n        sprite->sScale += 2;\n        if (sprite->sTimer % 5 == 0)\n            sprite->sPos++;\n        break;\n    }",
  },
  "SpriteCB_RayquazaOrb": {
    callsTo: ["CalcCenterToCornerVec","SPRITE_SHAPE","SPRITE_SIZE","SetOamMatrix"],
    lineCount: 27,
    bodyC: "u16 foo;\n    switch (sprite->sState)\n    {\n    case 0:\n    default:\n        sprite->invisible = FALSE;\n        sprite->oam.affineMode = ST_OAM_AFFINE_DOUBLE;\n        sprite->oam.matrixNum = 18;\n        CalcCenterToCornerVec(sprite, SPRITE_SHAPE(64x64), SPRITE_SIZE(64x64), ST_OAM_AFFINE_DOUBLE);\n        sprite->data[1] = 0;\n        sprite->sState = 1;\n         \n    case 1:\n        sprite->data[7]++;\n        if (sprite->data[7] & 1)\n        {\n            sprite->invisible = TRUE;\n        }\n        else\n        {\n            sprite->invisible = FALSE;\n            if (sprite->data[1] < 64)\n                sprite->data[1]++;\n        }\n        foo = 256 - gSineTable[(u8)sprite->data[1]] / 2;\n        SetOamMatrix(18, foo, 0, 0, foo);\n        break;\n    }",
  },
} as const;
