// AUTO-GENERATED from src/main_menu.c by extract-decomp-task-machines.mjs
// Do not edit manually — re-run `npm run extract:task-machines` to refresh.
//
// Generated: 2026-04-27
// Stats: 47 Task_, 4 CB2_, 2 SpriteCB_

export const TASKS = {
  "Task_MainMenuCheckSaveFile": {
    callsTo: ["CreateMainMenuErrorWindow","IsMysteryGiftEnabled","IsWirelessAdapterConnected","SetGpuReg"],
    taskTransitions: ["Task_MainMenuCheckBattery","Task_WaitForSaveFileErrorWindow"],
    dataWrites: ["tMenuType"],
    externalChecks: { paletteFade: true },
    lineCount: 63,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n    if (!gPaletteFade.active)\n    {\n        SetGpuReg(REG_OFFSET_WIN0H, 0);\n        SetGpuReg(REG_OFFSET_WIN0V, 0);\n        SetGpuReg(REG_OFFSET_WININ, WININ_WIN0_BG0 | WININ_WIN0_OBJ);\n        SetGpuReg(REG_OFFSET_WINOUT, WINOUT_WIN01_BG0 | WINOUT_WIN01_OBJ | WINOUT_WIN01_CLR);\n        SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_EFFECT_DARKEN | BLDCNT_TGT1_BG0);\n        SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n        SetGpuReg(REG_OFFSET_BLDY, 7);\n\n        if (IsWirelessAdapterConnected())\n            tWirelessAdapterConnected = TRUE;\n        switch (gSaveFileStatus)\n        {\n            case SAVE_STATUS_OK:\n                tMenuType = HAS_SAVED_GAME;\n                if (IsMysteryGiftEnabled())\n                    tMenuType++;\n                gTasks[taskId].func = Task_MainMenuCheckBattery;\n                break;\n            case SAVE_STATUS_CORRUPT:\n                CreateMainMenuErrorWindow(gText_SaveFileErased);\n                tMenuType = HAS_NO_SAVED_GAME;\n                gTasks[taskId].func = Task_WaitForSaveFileErrorWindow;\n                break;\n            case SAVE_STATUS_ERROR:\n                CreateMainMenuErrorWindow(gText_SaveFileCorrupted);\n                gTasks[taskId].func = Task_WaitForSaveFileErrorWindow;\n                tMenuType = HAS_SAVED_GAME;\n                if (IsMysteryGiftEnabled() == TRUE)\n                    tMenuType++;\n                break;\n            case SAVE_STATUS_EMPTY:\n            default:\n                tMenuType = HAS_NO_SAVED_GAME;\n                gTasks[taskId].func = Task_MainMenuCheckBattery;\n                break;\n            case SAVE_STATUS_NO_FLASH:\n                CreateMainMenuErrorWindow(gJPText_No1MSubCircuit);\n                gTasks[taskId].tMenuType = HAS_NO_SAVED_GAME;\n                gTasks[taskId].func = Task_WaitForSaveFileErrorWindow;\n                break;\n        }\n        if (sCurrItemAndOptionMenuCheck & OPTION_MENU_FLAG)    \n        {\n            switch (tMenuType)   \n            {\n                case HAS_NO_SAVED_GAME:\n                case HAS_SAVED_GAME:\n                    sCurrItemAndOptionMenuCheck = tMenuType + 1;\n                    break;\n                case HAS_MYSTERY_GIFT:\n                    sCurrItemAndOptionMenuCheck = 3;\n                    break;\n                case HAS_MYSTERY_EVENTS:\n                    sCurrItemAndOptionMenuCheck = 4;\n                    break;\n            }\n        }\n        sCurrItemAndOptionMenuCheck &= ~OPTION_MENU_FLAG;   \n        tCurrItem = sCurrItemAndOptionMenuCheck;\n        tItemCount = tMenuType + 2;\n    }",
  },
  "Task_WaitForSaveFileErrorWindow": {
    callsTo: ["ClearMainMenuWindowTilemap","ClearWindowTilemap","IsTextPrinterActive","JOY_NEW","RunTextPrinters"],
    taskTransitions: ["Task_MainMenuCheckBattery"],
    externalChecks: { joyButtons: ["NEW:A_BUTTON"], msgBoxIsCancel: true },
    lineCount: 7,
    bodyC: "RunTextPrinters();\n    if (!IsTextPrinterActive(7) && (JOY_NEW(A_BUTTON)))\n    {\n        ClearWindowTilemap(7);\n        ClearMainMenuWindowTilemap(&sWindowTemplates_MainMenu[7]);\n        gTasks[taskId].func = Task_MainMenuCheckBattery;\n    }",
  },
  "Task_MainMenuCheckBattery": {
    callsTo: ["CreateMainMenuErrorWindow","RtcGetErrorStatus","SetGpuReg"],
    taskTransitions: ["Task_DisplayMainMenu","Task_WaitForBatteryDryErrorWindow"],
    externalChecks: { paletteFade: true },
    lineCount: 19,
    bodyC: "if (!gPaletteFade.active)\n    {\n        SetGpuReg(REG_OFFSET_WIN0H, 0);\n        SetGpuReg(REG_OFFSET_WIN0V, 0);\n        SetGpuReg(REG_OFFSET_WININ, WININ_WIN0_BG0 | WININ_WIN0_OBJ);\n        SetGpuReg(REG_OFFSET_WINOUT, WINOUT_WIN01_BG0 | WINOUT_WIN01_OBJ | WINOUT_WIN01_CLR);\n        SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_EFFECT_DARKEN | BLDCNT_TGT1_BG0);\n        SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n        SetGpuReg(REG_OFFSET_BLDY, 7);\n\n        if (!(RtcGetErrorStatus() & RTC_ERR_FLAG_MASK))\n        {\n            gTasks[taskId].func = Task_DisplayMainMenu;\n        }\n        else\n        {\n            CreateMainMenuErrorWindow(gText_BatteryRunDry);\n            gTasks[taskId].func = Task_WaitForBatteryDryErrorWindow;\n        }\n    }",
  },
  "Task_WaitForBatteryDryErrorWindow": {
    callsTo: ["ClearMainMenuWindowTilemap","ClearWindowTilemap","IsTextPrinterActive","JOY_NEW","RunTextPrinters"],
    taskTransitions: ["Task_DisplayMainMenu"],
    externalChecks: { joyButtons: ["NEW:A_BUTTON"], msgBoxIsCancel: true },
    lineCount: 7,
    bodyC: "RunTextPrinters();\n    if (!IsTextPrinterActive(7) && (JOY_NEW(A_BUTTON)))\n    {\n        ClearWindowTilemap(7);\n        ClearMainMenuWindowTilemap(&sWindowTemplates_MainMenu[7]);\n        gTasks[taskId].func = Task_DisplayMainMenu;\n    }",
  },
  "Task_DisplayMainMenu": {
    callsTo: ["AddScrollIndicatorArrowPair","AddTextPrinterParameterized3","BG_PLTT_ID","ChangeBgY","CopyWindowToVram","DrawMainMenuWindowBorder","FillWindowPixelBuffer","LoadPalette","MainMenu_FormatSavegameText","PIXEL_FILL","PLTT_SIZEOF","PutWindowTilemap","RGB","SetGpuReg"],
    taskTransitions: ["Task_HighlightSelectedMainMenuItem","Task_ScrollIndicatorArrowPairOnMainMenu"],
    dataReads: ["tMenuType"],
    dataWrites: ["tArrowTaskIsScrolled"],
    externalChecks: { paletteFade: true },
    lineCount: 125,
    bodyC: "s16 *data = gTasks[taskId].data;\n    u16 palette;\n\n    if (!gPaletteFade.active)\n    {\n        SetGpuReg(REG_OFFSET_WIN0H, 0);\n        SetGpuReg(REG_OFFSET_WIN0V, 0);\n        SetGpuReg(REG_OFFSET_WININ, WININ_WIN0_BG0 | WININ_WIN0_OBJ);\n        SetGpuReg(REG_OFFSET_WINOUT, WINOUT_WIN01_BG0 | WINOUT_WIN01_OBJ | WINOUT_WIN01_CLR);\n        SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_EFFECT_DARKEN | BLDCNT_TGT1_BG0);\n        SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n        SetGpuReg(REG_OFFSET_BLDY, 7);\n\n        palette = RGB_BLACK;\n        LoadPalette(&palette, BG_PLTT_ID(15) + 14, PLTT_SIZEOF(1));\n\n        palette = RGB_WHITE;\n        LoadPalette(&palette, BG_PLTT_ID(15) + 10, PLTT_SIZEOF(1));\n\n        palette = RGB(12, 12, 12);\n        LoadPalette(&palette, BG_PLTT_ID(15) + 11, PLTT_SIZEOF(1));\n\n        palette = RGB(26, 26, 25);\n        LoadPalette(&palette, BG_PLTT_ID(15) + 12, PLTT_SIZEOF(1));\n\n         \n         \n        if (gSaveBlock2Ptr->playerGender == MALE)\n        {\n            palette = RGB(4, 16, 31);\n            LoadPalette(&palette, BG_PLTT_ID(15) + 1, PLTT_SIZEOF(1));\n        }\n        else\n        {\n            palette = RGB(31, 3, 21);\n            LoadPalette(&palette, BG_PLTT_ID(15) + 1, PLTT_SIZEOF(1));\n        }\n\n        switch (gTasks[taskId].tMenuType)\n        {\n            case HAS_NO_SAVED_GAME:\n            default:\n                FillWindowPixelBuffer(0, PIXEL_FILL(0xA));\n                FillWindowPixelBuffer(1, PIXEL_FILL(0xA));\n                AddTextPrinterParameterized3(0, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuNewGame);\n                AddTextPrinterParameterized3(1, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuOption);\n                PutWindowTilemap(0);\n                PutWindowTilemap(1);\n                CopyWindowToVram(0, COPYWIN_GFX);\n                CopyWindowToVram(1, COPYWIN_GFX);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[0], MAIN_MENU_BORDER_TILE);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[1], MAIN_MENU_BORDER_TILE);\n                break;\n            case HAS_SAVED_GAME:\n                FillWindowPixelBuffer(2, PIXEL_FILL(0xA));\n                FillWindowPixelBuffer(3, PIXEL_FILL(0xA));\n                FillWindowPixelBuffer(4, PIXEL_FILL(0xA));\n                AddTextPrinterParameterized3(2, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuContinue);\n                AddTextPrinterParameterized3(3, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuNewGame);\n                AddTextPrinterParameterized3(4, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuOption);\n                MainMenu_FormatSavegameText();\n                PutWindowTilemap(2);\n                PutWindowTilemap(3);\n                PutWindowTilemap(4);\n                CopyWindowToVram(2, COPYWIN_GFX);\n                CopyWindowToVram(3, COPYWIN_GFX);\n                CopyWindowToVram(4, COPYWIN_GFX);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[2], MAIN_MENU_BORDER_TILE);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[3], MAIN_MENU_BORDER_TILE);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[4], MAIN_MENU_BORDER_TILE);\n                break;\n            case HAS_MYSTERY_GIFT:\n                FillWindowPixelBuffer(2, PIXEL_FILL(0xA));\n                FillWindowPixelBuffer(3, PIXEL_FILL(0xA));\n                FillWindowPixelBuffer(4, PIXEL_FILL(0xA));\n                FillWindowPixelBuffer(5, PIXEL_FILL(0xA));\n                AddTextPrinterParameterized3(2, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuContinue);\n                AddTextPrinterParameterized3(3, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuNewGame);\n                AddTextPrinterParameterized3(4, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuMysteryGift);\n                AddTextPrinterParameterized3(5, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuOption);\n                MainMenu_FormatSavegameText();\n                PutWindowTilemap(2);\n                PutWindowTilemap(3);\n                PutWindowTilemap(4);\n                PutWindowTilemap(5);\n                CopyWindowToVram(2, COPYWIN_GFX);\n                CopyWindowToVram(3, COPYWIN_GFX);\n                CopyWindowToVram(4, COPYWIN_GFX);\n                CopyWindowToVram(5, COPYWIN_GFX);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[2], MAIN_MENU_BORDER_TILE);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[3], MAIN_MENU_BORDER_TILE);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[4], MAIN_MENU_BORDER_TILE);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[5], MAIN_MENU_BORDER_TILE);\n                break;\n            case HAS_MYSTERY_EVENTS:\n                FillWindowPixelBuffer(2, PIXEL_FILL(0xA));\n                FillWindowPixelBuffer(3, PIXEL_FILL(0xA));\n                FillWindowPixelBuffer(4, PIXEL_FILL(0xA));\n                FillWindowPixelBuffer(5, PIXEL_FILL(0xA));\n                FillWindowPixelBuffer(6, PIXEL_FILL(0xA));\n                AddTextPrinterParameterized3(2, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuContinue);\n                AddTextPrinterParameterized3(3, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuNewGame);\n                AddTextPrinterParameterized3(4, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuMysteryGift2);\n                AddTextPrinterParameterized3(5, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuMysteryEvents);\n                AddTextPrinterParameterized3(6, FONT_NORMAL, 0, 1, sTextColor_Headers, TEXT_SKIP_DRAW, gText_MainMenuOption);\n                MainMenu_FormatSavegameText();\n                PutWindowTilemap(2);\n                PutWindowTilemap(3);\n                PutWindowTilemap(4);\n                PutWindowTilemap(5);\n                PutWindowTilemap(6);\n                CopyWindowToVram(2, COPYWIN_GFX);\n                CopyWindowToVram(3, COPYWIN_GFX);\n                CopyWindowToVram(4, COPYWIN_GFX);\n                CopyWindowToVram(5, COPYWIN_GFX);\n                CopyWindowToVram(6, COPYWIN_GFX);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[2], MAIN_MENU_BORDER_TILE);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[3], MAIN_MENU_BORDER_TILE);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[4], MAIN_MENU_BORDER_TILE);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[5], MAIN_MENU_BORDER_TILE);\n                DrawMainMenuWindowBorder(&sWindowTemplates_MainMenu[6], MAIN_MENU_BORDER_TILE);\n                tScrollArrowTaskId = AddScrollIndicatorArrowPair(&sScrollArrowsTemplate_MainMenu, &sCurrItemAndOptionMenuCheck);\n                gTasks[tScrollArrowTaskId].func = Task_ScrollIndicatorArrowPairOnMainMenu;\n                if (sCurrItemAndOptionMenuCheck == 4)\n                {\n                    ChangeBgY(0, 0x2000, BG_COORD_ADD);\n                    ChangeBgY(1, 0x2000, BG_COORD_ADD);\n                    tIsScrolled = TRUE;\n                    gTasks[tScrollArrowTaskId].tArrowTaskIsScrolled = TRUE;\n                }\n                break;\n        }\n        gTasks[taskId].func = Task_HighlightSelectedMainMenuItem;\n    }",
  },
  "Task_HighlightSelectedMainMenuItem": {
    callsTo: ["HighlightSelectedMainMenuItem"],
    taskTransitions: ["Task_HandleMainMenuInput"],
    dataReads: ["tCurrItem","tIsScrolled","tMenuType"],
    lineCount: 2,
    bodyC: "HighlightSelectedMainMenuItem(gTasks[taskId].tMenuType, gTasks[taskId].tCurrItem, gTasks[taskId].tIsScrolled);\n    gTasks[taskId].func = Task_HandleMainMenuInput;",
  },
  "Task_HandleMainMenuInput": {
    callsTo: ["HandleMainMenuInput"],
    taskTransitions: ["Task_HighlightSelectedMainMenuItem"],
    lineCount: 2,
    bodyC: "if (HandleMainMenuInput(taskId))\n        gTasks[taskId].func = Task_HighlightSelectedMainMenuItem;",
  },
  "Task_HandleMainMenuAPressed": {
    callsTo: ["BG_PLTT_ID","BeginNormalPaletteFade","ChangeBgY","ClearStdWindowAndFrame","DestroyTask","FreeAllWindowBuffers","IsWirelessAdapterConnected","RemoveScrollIndicatorArrowPair","SetGpuReg","SetMainCallback2"],
    taskTransitions: ["Task_DisplayMainMenuInvalidActionError","Task_NewGameBirchSpeech_Init"],
    cb2Transitions: ["CB2_ContinueSavedGame","CB2_InitEReader","CB2_InitMysteryEventMenu","CB2_InitMysteryGift","CB2_InitOptionMenu"],
    dataReads: ["tCurrItem","tMenuType","tScrollArrowTaskId","tWirelessAdapterConnected"],
    dataWrites: ["tCurrItem","tMenuType"],
    terminalMarkers: ["DestroyTask"],
    externalChecks: { paletteFade: true },
    lineCount: 168,
    bodyC: "bool8 wirelessAdapterConnected;\n    u8 action;\n\n    if (!gPaletteFade.active)\n    {\n        if (gTasks[taskId].tMenuType == HAS_MYSTERY_EVENTS)\n            RemoveScrollIndicatorArrowPair(gTasks[taskId].tScrollArrowTaskId);\n        ClearStdWindowAndFrame(0, TRUE);\n        ClearStdWindowAndFrame(1, TRUE);\n        ClearStdWindowAndFrame(2, TRUE);\n        ClearStdWindowAndFrame(3, TRUE);\n        ClearStdWindowAndFrame(4, TRUE);\n        ClearStdWindowAndFrame(5, TRUE);\n        ClearStdWindowAndFrame(6, TRUE);\n        ClearStdWindowAndFrame(7, TRUE);\n        wirelessAdapterConnected = IsWirelessAdapterConnected();\n        switch (gTasks[taskId].tMenuType)\n        {\n            case HAS_NO_SAVED_GAME:\n            default:\n                switch (gTasks[taskId].tCurrItem)\n                {\n                    case 0:\n                    default:\n                        action = ACTION_NEW_GAME;\n                        break;\n                    case 1:\n                        action = ACTION_OPTION;\n                        break;\n                }\n                break;\n            case HAS_SAVED_GAME:\n                switch (gTasks[taskId].tCurrItem)\n                {\n                    case 0:\n                    default:\n                        action = ACTION_CONTINUE;\n                        break;\n                    case 1:\n                        action = ACTION_NEW_GAME;\n                        break;\n                    case 2:\n                        action = ACTION_OPTION;\n                        break;\n                }\n                break;\n            case HAS_MYSTERY_GIFT:\n                switch (gTasks[taskId].tCurrItem)\n                {\n                    case 0:\n                    default:\n                        action = ACTION_CONTINUE;\n                        break;\n                    case 1:\n                        action = ACTION_NEW_GAME;\n                        break;\n                    case 2:\n                        action = ACTION_MYSTERY_GIFT;\n                        if (!wirelessAdapterConnected)\n                        {\n                            action = ACTION_INVALID;\n                            gTasks[taskId].tMenuType = HAS_NO_SAVED_GAME;\n                        }\n                        break;\n                    case 3:\n                        action = ACTION_OPTION;\n                        break;\n                }\n                break;\n            case HAS_MYSTERY_EVENTS:\n                switch (gTasks[taskId].tCurrItem)\n                {\n                    case 0:\n                    default:\n                        action = ACTION_CONTINUE;\n                        break;\n                    case 1:\n                        action = ACTION_NEW_GAME;\n                        break;\n                    case 2:\n                        if (gTasks[taskId].tWirelessAdapterConnected)\n                        {\n                            action = ACTION_MYSTERY_GIFT;\n                            if (!wirelessAdapterConnected)\n                            {\n                                action = ACTION_INVALID;\n                                gTasks[taskId].tMenuType = HAS_NO_SAVED_GAME;\n                            }\n                        }\n                        else if (wirelessAdapterConnected)\n                        {\n                            action = ACTION_INVALID;\n                            gTasks[taskId].tMenuType = HAS_SAVED_GAME;\n                        }\n                        else\n                        {\n                            action = ACTION_EREADER;\n                        }\n                        break;\n                    case 3:\n                        if (wirelessAdapterConnected)\n                        {\n                            action = ACTION_INVALID;\n                            gTasks[taskId].tMenuType = HAS_MYSTERY_GIFT;\n                        }\n                        else\n                        {\n                            action = ACTION_MYSTERY_EVENTS;\n                        }\n                        break;\n                    case 4:\n                        action = ACTION_OPTION;\n                        break;\n                }\n                break;\n        }\n        ChangeBgY(0, 0, BG_COORD_SET);\n        ChangeBgY(1, 0, BG_COORD_SET);\n        switch (action)\n        {\n            case ACTION_NEW_GAME:\n            default:\n                gPlttBufferUnfaded[0] = RGB_BLACK;\n                gPlttBufferFaded[0] = RGB_BLACK;\n                gTasks[taskId].func = Task_NewGameBirchSpeech_Init;\n                break;\n            case ACTION_CONTINUE:\n                gPlttBufferUnfaded[0] = RGB_BLACK;\n                gPlttBufferFaded[0] = RGB_BLACK;\n                SetMainCallback2(CB2_ContinueSavedGame);\n                DestroyTask(taskId);\n                break;\n            case ACTION_OPTION:\n                gMain.savedCallback = CB2_ReinitMainMenu;\n                SetMainCallback2(CB2_InitOptionMenu);\n                DestroyTask(taskId);\n                break;\n            case ACTION_MYSTERY_GIFT:\n                SetMainCallback2(CB2_InitMysteryGift);\n                DestroyTask(taskId);\n                break;\n            case ACTION_MYSTERY_EVENTS:\n                SetMainCallback2(CB2_InitMysteryEventMenu);\n                DestroyTask(taskId);\n                break;\n            case ACTION_EREADER:\n                SetMainCallback2(CB2_InitEReader);\n                DestroyTask(taskId);\n                break;\n            case ACTION_INVALID:\n                gTasks[taskId].tCurrItem = 0;\n                gTasks[taskId].func = Task_DisplayMainMenuInvalidActionError;\n                gPlttBufferUnfaded[BG_PLTT_ID(15) + 1] = RGB_WHITE;\n                gPlttBufferFaded[BG_PLTT_ID(15) + 1] = RGB_WHITE;\n                SetGpuReg(REG_OFFSET_BG2HOFS, 0);\n                SetGpuReg(REG_OFFSET_BG2VOFS, 0);\n                SetGpuReg(REG_OFFSET_BG1HOFS, 0);\n                SetGpuReg(REG_OFFSET_BG1VOFS, 0);\n                SetGpuReg(REG_OFFSET_BG0HOFS, 0);\n                SetGpuReg(REG_OFFSET_BG0VOFS, 0);\n                BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_BLACK);\n                return;\n        }\n        FreeAllWindowBuffers();\n        if (action != ACTION_OPTION)\n            sCurrItemAndOptionMenuCheck = 0;\n        else\n            sCurrItemAndOptionMenuCheck |= OPTION_MENU_FLAG;   \n    }",
  },
  "Task_HandleMainMenuBPressed": {
    callsTo: ["DestroyTask","FreeAllWindowBuffers","RemoveScrollIndicatorArrowPair","SetMainCallback2"],
    cb2Transitions: ["CB2_InitTitleScreen"],
    dataReads: ["tScrollArrowTaskId"],
    dataWrites: ["tMenuType"],
    terminalMarkers: ["DestroyTask"],
    externalChecks: { paletteFade: true },
    lineCount: 9,
    bodyC: "if (!gPaletteFade.active)\n    {\n        if (gTasks[taskId].tMenuType == HAS_MYSTERY_EVENTS)\n            RemoveScrollIndicatorArrowPair(gTasks[taskId].tScrollArrowTaskId);\n        sCurrItemAndOptionMenuCheck = 0;\n        FreeAllWindowBuffers();\n        SetMainCallback2(CB2_InitTitleScreen);\n        DestroyTask(taskId);\n    }",
  },
  "Task_DisplayMainMenuInvalidActionError": {
    callsTo: ["BeginNormalPaletteFade","CreateMainMenuErrorWindow","FillBgTilemapBufferRect_Palette0","IsTextPrinterActive","JOY_NEW","PlaySE","RunTextPrinters"],
    taskTransitions: ["Task_HandleMainMenuBPressed"],
    dataReads: ["tCurrItem","tMenuType"],
    dataWrites: ["tCurrItem"],
    externalChecks: { paletteFade: true, msgBoxIsCancel: true },
    lineCount: 35,
    bodyC: "switch (gTasks[taskId].tCurrItem)\n    {\n        case 0:\n            FillBgTilemapBufferRect_Palette0(0, 0, 0, 0, DISPLAY_TILE_WIDTH, DISPLAY_TILE_HEIGHT);\n            switch (gTasks[taskId].tMenuType)\n            {\n                case 0:\n                    CreateMainMenuErrorWindow(gText_WirelessNotConnected);\n                    break;\n                case 1:\n                    CreateMainMenuErrorWindow(gText_MysteryGiftCantUse);\n                    break;\n                case 2:\n                    CreateMainMenuErrorWindow(gText_MysteryEventsCantUse);\n                    break;\n            }\n            gTasks[taskId].tCurrItem++;\n            break;\n        case 1:\n            if (!gPaletteFade.active)\n                gTasks[taskId].tCurrItem++;\n            break;\n        case 2:\n            RunTextPrinters();\n            if (!IsTextPrinterActive(7))\n                gTasks[taskId].tCurrItem++;\n            break;\n        case 3:\n            if (JOY_NEW(A_BUTTON | B_BUTTON))\n            {\n                PlaySE(SE_SELECT);\n                BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_BLACK);\n                gTasks[taskId].func = Task_HandleMainMenuBPressed;\n            }\n    }",
  },
  "Task_NewGameBirchSpeech_Init": {
    callsTo: ["AddBirchSpeechObjects","BG_PLTT_ID","BG_SCREEN_ADDR","BeginNormalPaletteFade","FreeAllSpritePalettes","InitBgFromTemplate","LZ77UnCompVram","LoadPalette","PLTT_SIZEOF","PlayBGM","ResetAllPicSprites","ResetSpriteData","ScanlineEffect_Stop","SetGpuReg","ShowBg"],
    taskTransitions: ["Task_NewGameBirchSpeech_WaitToShowBirch"],
    dataWrites: ["data[3]","tBG1HOFS","tPlayerSpriteId","tTimer"],
    lineCount: 28,
    bodyC: "SetGpuReg(REG_OFFSET_DISPCNT, 0);\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_ON | DISPCNT_OBJ_1D_MAP);\n    InitBgFromTemplate(&sBirchBgTemplate);\n    SetGpuReg(REG_OFFSET_WIN0H, 0);\n    SetGpuReg(REG_OFFSET_WIN0V, 0);\n    SetGpuReg(REG_OFFSET_WININ, 0);\n    SetGpuReg(REG_OFFSET_WINOUT, 0);\n    SetGpuReg(REG_OFFSET_BLDCNT, 0);\n    SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n    SetGpuReg(REG_OFFSET_BLDY, 0);\n\n    LZ77UnCompVram(sBirchSpeechShadowGfx, (void *)VRAM);\n    LZ77UnCompVram(sBirchSpeechBgMap, (void *)(BG_SCREEN_ADDR(7)));\n    LoadPalette(sBirchSpeechBgPals, BG_PLTT_ID(0), 2 * PLTT_SIZE_4BPP);\n    LoadPalette(sBirchSpeechPlatformBlackPal, BG_PLTT_ID(0) + 1, PLTT_SIZEOF(8));\n    ScanlineEffect_Stop();\n    ResetSpriteData();\n    FreeAllSpritePalettes();\n    ResetAllPicSprites();\n    AddBirchSpeechObjects(taskId);\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_BLACK);\n    gTasks[taskId].tBG1HOFS = 0;\n    gTasks[taskId].func = Task_NewGameBirchSpeech_WaitToShowBirch;\n    gTasks[taskId].tPlayerSpriteId = SPRITE_NONE;\n    gTasks[taskId].data[3] = 0xFF;\n    gTasks[taskId].tTimer = 0xD8;\n    PlayBGM(MUS_ROUTE122);\n    ShowBg(0);\n    ShowBg(1);",
  },
  "Task_NewGameBirchSpeech_WaitToShowBirch": {
    callsTo: ["NewGameBirchSpeech_StartFadeInTarget1OutTarget2","NewGameBirchSpeech_StartFadePlatformOut"],
    taskTransitions: ["Task_NewGameBirchSpeech_WaitForSpriteFadeInWelcome"],
    dataReads: ["tBirchSpriteId","tTimer"],
    dataWrites: ["tTimer"],
    lineCount: 17,
    bodyC: "u8 spriteId;\n\n    if (gTasks[taskId].tTimer)\n    {\n        gTasks[taskId].tTimer--;\n    }\n    else\n    {\n        spriteId = gTasks[taskId].tBirchSpriteId;\n        gSprites[spriteId].x = 136;\n        gSprites[spriteId].y = 60;\n        gSprites[spriteId].invisible = FALSE;\n        gSprites[spriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n        NewGameBirchSpeech_StartFadeInTarget1OutTarget2(taskId, 10);\n        NewGameBirchSpeech_StartFadePlatformOut(taskId, 20);\n        gTasks[taskId].tTimer = 80;\n        gTasks[taskId].func = Task_NewGameBirchSpeech_WaitForSpriteFadeInWelcome;\n    }",
  },
  "Task_NewGameBirchSpeech_WaitForSpriteFadeInWelcome": {
    callsTo: ["AddTextPrinterForMessage","BG_PLTT_ID","CopyWindowToVram","InitWindows","LoadMainMenuWindowFrameTiles","LoadMessageBoxGfx","NewGameBirchSpeech_ClearWindow","NewGameBirchSpeech_ShowDialogueWindow","PutWindowTilemap","StringExpandPlaceholders"],
    taskTransitions: ["Task_NewGameBirchSpeech_ThisIsAPokemon"],
    dataReads: ["tBirchSpriteId","tIsDoneFadingSprites","tTimer"],
    dataWrites: ["tTimer"],
    lineCount: 21,
    bodyC: "if (gTasks[taskId].tIsDoneFadingSprites)\n    {\n        gSprites[gTasks[taskId].tBirchSpriteId].oam.objMode = ST_OAM_OBJ_NORMAL;\n        if (gTasks[taskId].tTimer)\n        {\n            gTasks[taskId].tTimer--;\n        }\n        else\n        {\n            InitWindows(sNewGameBirchSpeechTextWindows);\n            LoadMainMenuWindowFrameTiles(0, 0xF3);\n            LoadMessageBoxGfx(0, BIRCH_DLG_BASE_TILE_NUM, BG_PLTT_ID(15));\n            NewGameBirchSpeech_ShowDialogueWindow(0, 1);\n            PutWindowTilemap(0);\n            CopyWindowToVram(0, COPYWIN_GFX);\n            NewGameBirchSpeech_ClearWindow(0);\n            StringExpandPlaceholders(gStringVar4, gText_Birch_Welcome);\n            AddTextPrinterForMessage(TRUE);\n            gTasks[taskId].func = Task_NewGameBirchSpeech_ThisIsAPokemon;\n        }\n    }",
  },
  "Task_NewGameBirchSpeech_ThisIsAPokemon": {
    callsTo: ["AddTextPrinterWithCallbackForMessage","RunTextPrintersAndIsPrinter0Active","StringExpandPlaceholders"],
    taskTransitions: ["Task_NewGameBirchSpeech_MainSpeech"],
    externalChecks: { paletteFade: true },
    lineCount: 7,
    bodyC: "if (!gPaletteFade.active && !RunTextPrintersAndIsPrinter0Active())\n    {\n        gTasks[taskId].func = Task_NewGameBirchSpeech_MainSpeech;\n        StringExpandPlaceholders(gStringVar4, gText_ThisIsAPokemon);\n        AddTextPrinterWithCallbackForMessage(TRUE, NewGameBirchSpeech_WaitForThisIsPokemonText);\n        sBirchSpeechMainTaskId = taskId;\n    }",
  },
  "Task_NewGameBirchSpeech_MainSpeech": {
    callsTo: ["AddTextPrinterForMessage","RunTextPrintersAndIsPrinter0Active","StringExpandPlaceholders"],
    taskTransitions: ["Task_NewGameBirchSpeech_AndYouAre"],
    lineCount: 6,
    bodyC: "if (!RunTextPrintersAndIsPrinter0Active())\n    {\n        StringExpandPlaceholders(gStringVar4, gText_Birch_MainSpeech);\n        AddTextPrinterForMessage(TRUE);\n        gTasks[taskId].func = Task_NewGameBirchSpeech_AndYouAre;\n    }",
  },
  "Task_NewGameBirchSpeechSub_InitPokeBall": {
    callsTo: ["CreatePokeballSpriteToReleaseMon"],
    taskTransitions: ["Task_NewGameBirchSpeechSub_WaitForLotad"],
    dataReads: ["tLotadSpriteId"],
    dataWrites: ["tTimer"],
    lineCount: 8,
    bodyC: "u8 spriteId = gTasks[sBirchSpeechMainTaskId].tLotadSpriteId;\n\n    gSprites[spriteId].x = 100;\n    gSprites[spriteId].y = 75;\n    gSprites[spriteId].invisible = FALSE;\n    gSprites[spriteId].data[0] = 0;\n\n    CreatePokeballSpriteToReleaseMon(spriteId, gSprites[spriteId].oam.paletteNum, 112, 58, 0, 0, 32, PALETTES_BG, SPECIES_LOTAD);\n    gTasks[taskId].func = Task_NewGameBirchSpeechSub_WaitForLotad;\n    gTasks[sBirchSpeechMainTaskId].tTimer = 0;",
  },
  "Task_NewGameBirchSpeechSub_WaitForLotad": {
    callsTo: ["DestroyTask"],
    dataReads: ["tLotadSpriteId","tTimer"],
    dataWrites: ["tTimer"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 21,
    bodyC: "s16 *data = gTasks[taskId].data;\n    struct Sprite *sprite = &gSprites[gTasks[sBirchSpeechMainTaskId].tLotadSpriteId];\n\n    switch (tState)\n    {\n        case 0:\n            if (sprite->callback != SpriteCallbackDummy)\n                return;\n            sprite->oam.affineMode = ST_OAM_AFFINE_OFF;\n            break;\n        case 1:\n            if (gTasks[sBirchSpeechMainTaskId].tTimer >= 96)\n            {\n                DestroyTask(taskId);\n                if (gTasks[sBirchSpeechMainTaskId].tTimer < 0x4000)\n                    gTasks[sBirchSpeechMainTaskId].tTimer++;\n            }\n            return;\n    }\n    tState++;\n    if (gTasks[sBirchSpeechMainTaskId].tTimer < 0x4000)\n        gTasks[sBirchSpeechMainTaskId].tTimer++;",
  },
  "Task_NewGameBirchSpeech_AndYouAre": {
    callsTo: ["AddTextPrinterForMessage","RunTextPrintersAndIsPrinter0Active","StringExpandPlaceholders"],
    taskTransitions: ["Task_NewGameBirchSpeech_StartBirchLotadPlatformFade"],
    lineCount: 7,
    bodyC: "if (!RunTextPrintersAndIsPrinter0Active())\n    {\n        sStartedPokeBallTask = FALSE;\n        StringExpandPlaceholders(gStringVar4, gText_Birch_AndYouAre);\n        AddTextPrinterForMessage(TRUE);\n        gTasks[taskId].func = Task_NewGameBirchSpeech_StartBirchLotadPlatformFade;\n    }",
  },
  "Task_NewGameBirchSpeech_StartBirchLotadPlatformFade": {
    callsTo: ["NewGameBirchSpeech_StartFadeOutTarget1InTarget2","NewGameBirchSpeech_StartFadePlatformIn","RunTextPrintersAndIsPrinter0Active"],
    taskTransitions: ["Task_NewGameBirchSpeech_SlidePlatformAway"],
    dataReads: ["tBirchSpriteId","tLotadSpriteId"],
    dataWrites: ["tTimer"],
    lineCount: 9,
    bodyC: "if (!RunTextPrintersAndIsPrinter0Active())\n    {\n        gSprites[gTasks[taskId].tBirchSpriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n        gSprites[gTasks[taskId].tLotadSpriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n        NewGameBirchSpeech_StartFadeOutTarget1InTarget2(taskId, 2);\n        NewGameBirchSpeech_StartFadePlatformIn(taskId, 1);\n        gTasks[taskId].tTimer = 64;\n        gTasks[taskId].func = Task_NewGameBirchSpeech_SlidePlatformAway;\n    }",
  },
  "Task_NewGameBirchSpeech_SlidePlatformAway": {
    callsTo: ["SetGpuReg"],
    taskTransitions: ["Task_NewGameBirchSpeech_StartPlayerFadeIn"],
    dataReads: ["tBG1HOFS"],
    dataWrites: ["tBG1HOFS"],
    lineCount: 10,
    bodyC: "if (gTasks[taskId].tBG1HOFS != -60)\n    {\n        gTasks[taskId].tBG1HOFS -= 2;\n        SetGpuReg(REG_OFFSET_BG1HOFS, gTasks[taskId].tBG1HOFS);\n    }\n    else\n    {\n        gTasks[taskId].tBG1HOFS = -60;\n        gTasks[taskId].func = Task_NewGameBirchSpeech_StartPlayerFadeIn;\n    }",
  },
  "Task_NewGameBirchSpeech_StartPlayerFadeIn": {
    callsTo: ["NewGameBirchSpeech_StartFadeInTarget1OutTarget2","NewGameBirchSpeech_StartFadePlatformOut"],
    taskTransitions: ["Task_NewGameBirchSpeech_WaitForPlayerFadeIn"],
    dataReads: ["tBirchSpriteId","tBrendanSpriteId","tIsDoneFadingSprites","tLotadSpriteId","tTimer"],
    dataWrites: ["tPlayerGender","tPlayerSpriteId","tTimer"],
    lineCount: 22,
    bodyC: "if (gTasks[taskId].tIsDoneFadingSprites)\n    {\n        gSprites[gTasks[taskId].tBirchSpriteId].invisible = TRUE;\n        gSprites[gTasks[taskId].tLotadSpriteId].invisible = TRUE;\n        if (gTasks[taskId].tTimer)\n        {\n            gTasks[taskId].tTimer--;\n        }\n        else\n        {\n            u8 spriteId = gTasks[taskId].tBrendanSpriteId;\n\n            gSprites[spriteId].x = 180;\n            gSprites[spriteId].y = 60;\n            gSprites[spriteId].invisible = FALSE;\n            gSprites[spriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n            gTasks[taskId].tPlayerSpriteId = spriteId;\n            gTasks[taskId].tPlayerGender = MALE;\n            NewGameBirchSpeech_StartFadeInTarget1OutTarget2(taskId, 2);\n            NewGameBirchSpeech_StartFadePlatformOut(taskId, 1);\n            gTasks[taskId].func = Task_NewGameBirchSpeech_WaitForPlayerFadeIn;\n        }\n    }",
  },
  "Task_NewGameBirchSpeech_WaitForPlayerFadeIn": {
    taskTransitions: ["Task_NewGameBirchSpeech_BoyOrGirl"],
    dataReads: ["tIsDoneFadingSprites","tPlayerSpriteId"],
    lineCount: 5,
    bodyC: "if (gTasks[taskId].tIsDoneFadingSprites)\n    {\n        gSprites[gTasks[taskId].tPlayerSpriteId].oam.objMode = ST_OAM_OBJ_NORMAL;\n        gTasks[taskId].func = Task_NewGameBirchSpeech_BoyOrGirl;\n    }",
  },
  "Task_NewGameBirchSpeech_BoyOrGirl": {
    callsTo: ["AddTextPrinterForMessage","NewGameBirchSpeech_ClearWindow","StringExpandPlaceholders"],
    taskTransitions: ["Task_NewGameBirchSpeech_WaitToShowGenderMenu"],
    lineCount: 4,
    bodyC: "NewGameBirchSpeech_ClearWindow(0);\n    StringExpandPlaceholders(gStringVar4, gText_Birch_BoyOrGirl);\n    AddTextPrinterForMessage(TRUE);\n    gTasks[taskId].func = Task_NewGameBirchSpeech_WaitToShowGenderMenu;",
  },
  "Task_NewGameBirchSpeech_WaitToShowGenderMenu": {
    callsTo: ["NewGameBirchSpeech_ShowGenderMenu","RunTextPrintersAndIsPrinter0Active"],
    taskTransitions: ["Task_NewGameBirchSpeech_ChooseGender"],
    lineCount: 5,
    bodyC: "if (!RunTextPrintersAndIsPrinter0Active())\n    {\n        NewGameBirchSpeech_ShowGenderMenu();\n        gTasks[taskId].func = Task_NewGameBirchSpeech_ChooseGender;\n    }",
  },
  "Task_NewGameBirchSpeech_ChooseGender": {
    callsTo: ["Menu_GetCursorPos","NewGameBirchSpeech_ClearGenderWindow","NewGameBirchSpeech_ProcessGenderMenuInput","NewGameBirchSpeech_StartFadeOutTarget1InTarget2","PlaySE"],
    taskTransitions: ["Task_NewGameBirchSpeech_SlideOutOldGenderSprite","Task_NewGameBirchSpeech_WhatsYourName"],
    dataReads: ["tPlayerGender","tPlayerSpriteId"],
    dataWrites: ["tPlayerGender"],
    lineCount: 25,
    bodyC: "int gender = NewGameBirchSpeech_ProcessGenderMenuInput();\n    int gender2;\n\n    switch (gender)\n    {\n        case MALE:\n            PlaySE(SE_SELECT);\n            gSaveBlock2Ptr->playerGender = gender;\n            NewGameBirchSpeech_ClearGenderWindow(1, 1);\n            gTasks[taskId].func = Task_NewGameBirchSpeech_WhatsYourName;\n            break;\n        case FEMALE:\n            PlaySE(SE_SELECT);\n            gSaveBlock2Ptr->playerGender = gender;\n            NewGameBirchSpeech_ClearGenderWindow(1, 1);\n            gTasks[taskId].func = Task_NewGameBirchSpeech_WhatsYourName;\n            break;\n    }\n    gender2 = Menu_GetCursorPos();\n    if (gender2 != gTasks[taskId].tPlayerGender)\n    {\n        gTasks[taskId].tPlayerGender = gender2;\n        gSprites[gTasks[taskId].tPlayerSpriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n        NewGameBirchSpeech_StartFadeOutTarget1InTarget2(taskId, 0);\n        gTasks[taskId].func = Task_NewGameBirchSpeech_SlideOutOldGenderSprite;\n    }",
  },
  "Task_NewGameBirchSpeech_SlideOutOldGenderSprite": {
    callsTo: ["NewGameBirchSpeech_StartFadeInTarget1OutTarget2"],
    taskTransitions: ["Task_NewGameBirchSpeech_SlideInNewGenderSprite"],
    dataReads: ["tBrendanSpriteId","tMaySpriteId","tPlayerGender","tPlayerSpriteId"],
    dataWrites: ["tIsDoneFadingSprites","tPlayerSpriteId"],
    lineCount: 20,
    bodyC: "u8 spriteId = gTasks[taskId].tPlayerSpriteId;\n    if (gTasks[taskId].tIsDoneFadingSprites == 0)\n    {\n        gSprites[spriteId].x += 4;\n    }\n    else\n    {\n        gSprites[spriteId].invisible = TRUE;\n        if (gTasks[taskId].tPlayerGender != MALE)\n            spriteId = gTasks[taskId].tMaySpriteId;\n        else\n            spriteId = gTasks[taskId].tBrendanSpriteId;\n        gSprites[spriteId].x = DISPLAY_WIDTH;\n        gSprites[spriteId].y = 60;\n        gSprites[spriteId].invisible = FALSE;\n        gTasks[taskId].tPlayerSpriteId = spriteId;\n        gSprites[spriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n        NewGameBirchSpeech_StartFadeInTarget1OutTarget2(taskId, 0);\n        gTasks[taskId].func = Task_NewGameBirchSpeech_SlideInNewGenderSprite;\n    }",
  },
  "Task_NewGameBirchSpeech_SlideInNewGenderSprite": {
    taskTransitions: ["Task_NewGameBirchSpeech_ChooseGender"],
    dataReads: ["tIsDoneFadingSprites","tPlayerSpriteId"],
    lineCount: 14,
    bodyC: "u8 spriteId = gTasks[taskId].tPlayerSpriteId;\n\n    if (gSprites[spriteId].x > 180)\n    {\n        gSprites[spriteId].x -= 4;\n    }\n    else\n    {\n        gSprites[spriteId].x = 180;\n        if (gTasks[taskId].tIsDoneFadingSprites)\n        {\n            gSprites[spriteId].oam.objMode = ST_OAM_OBJ_NORMAL;\n            gTasks[taskId].func = Task_NewGameBirchSpeech_ChooseGender;\n        }\n    }",
  },
  "Task_NewGameBirchSpeech_WhatsYourName": {
    callsTo: ["AddTextPrinterForMessage","NewGameBirchSpeech_ClearWindow","StringExpandPlaceholders"],
    taskTransitions: ["Task_NewGameBirchSpeech_WaitForWhatsYourNameToPrint"],
    lineCount: 4,
    bodyC: "NewGameBirchSpeech_ClearWindow(0);\n    StringExpandPlaceholders(gStringVar4, gText_Birch_WhatsYourName);\n    AddTextPrinterForMessage(TRUE);\n    gTasks[taskId].func = Task_NewGameBirchSpeech_WaitForWhatsYourNameToPrint;",
  },
  "Task_NewGameBirchSpeech_WaitForWhatsYourNameToPrint": {
    callsTo: ["RunTextPrintersAndIsPrinter0Active"],
    taskTransitions: ["Task_NewGameBirchSpeech_WaitPressBeforeNameChoice"],
    lineCount: 2,
    bodyC: "if (!RunTextPrintersAndIsPrinter0Active())\n        gTasks[taskId].func = Task_NewGameBirchSpeech_WaitPressBeforeNameChoice;",
  },
  "Task_NewGameBirchSpeech_WaitPressBeforeNameChoice": {
    callsTo: ["BeginNormalPaletteFade","JOY_NEW"],
    taskTransitions: ["Task_NewGameBirchSpeech_StartNamingScreen"],
    externalChecks: { joyButtons: ["NEW:A_BUTTON","NEW:B_BUTTON"] },
    lineCount: 5,
    bodyC: "if ((JOY_NEW(A_BUTTON)) || (JOY_NEW(B_BUTTON)))\n    {\n        BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_BLACK);\n        gTasks[taskId].func = Task_NewGameBirchSpeech_StartNamingScreen;\n    }",
  },
  "Task_NewGameBirchSpeech_StartNamingScreen": {
    callsTo: ["DestroyTask","DoNamingScreen","FreeAllWindowBuffers","FreeAndDestroyMonPicSprite","NewGameBirchSpeech_SetDefaultPlayerName","Random"],
    dataReads: ["tLotadSpriteId"],
    terminalMarkers: ["DestroyTask"],
    externalChecks: { paletteFade: true },
    lineCount: 8,
    bodyC: "if (!gPaletteFade.active)\n    {\n        FreeAllWindowBuffers();\n        FreeAndDestroyMonPicSprite(gTasks[taskId].tLotadSpriteId);\n        NewGameBirchSpeech_SetDefaultPlayerName(Random() % NUM_PRESET_NAMES);\n        DestroyTask(taskId);\n        DoNamingScreen(NAMING_SCREEN_PLAYER, gSaveBlock2Ptr->playerName, gSaveBlock2Ptr->playerGender, 0, 0, CB2_NewGameBirchSpeech_ReturnFromNamingScreen);\n    }",
  },
  "Task_NewGameBirchSpeech_SoItsPlayerName": {
    callsTo: ["AddTextPrinterForMessage","NewGameBirchSpeech_ClearWindow","StringExpandPlaceholders"],
    taskTransitions: ["Task_NewGameBirchSpeech_CreateNameYesNo"],
    lineCount: 4,
    bodyC: "NewGameBirchSpeech_ClearWindow(0);\n    StringExpandPlaceholders(gStringVar4, gText_Birch_SoItsPlayer);\n    AddTextPrinterForMessage(TRUE);\n    gTasks[taskId].func = Task_NewGameBirchSpeech_CreateNameYesNo;",
  },
  "Task_NewGameBirchSpeech_CreateNameYesNo": {
    callsTo: ["CreateYesNoMenuParameterized","RunTextPrintersAndIsPrinter0Active"],
    taskTransitions: ["Task_NewGameBirchSpeech_ProcessNameYesNoMenu"],
    lineCount: 5,
    bodyC: "if (!RunTextPrintersAndIsPrinter0Active())\n    {\n        CreateYesNoMenuParameterized(2, 1, 0xF3, 0xDF, 2, 15);\n        gTasks[taskId].func = Task_NewGameBirchSpeech_ProcessNameYesNoMenu;\n    }",
  },
  "Task_NewGameBirchSpeech_ProcessNameYesNoMenu": {
    callsTo: ["Menu_ProcessInputNoWrapClearOnChoose","NewGameBirchSpeech_StartFadeOutTarget1InTarget2","NewGameBirchSpeech_StartFadePlatformIn","PlaySE"],
    taskTransitions: ["Task_NewGameBirchSpeech_BoyOrGirl","Task_NewGameBirchSpeech_SlidePlatformAway2"],
    dataReads: ["tPlayerSpriteId"],
    lineCount: 14,
    bodyC: "switch (Menu_ProcessInputNoWrapClearOnChoose())\n    {\n        case 0:\n            PlaySE(SE_SELECT);\n            gSprites[gTasks[taskId].tPlayerSpriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n            NewGameBirchSpeech_StartFadeOutTarget1InTarget2(taskId, 2);\n            NewGameBirchSpeech_StartFadePlatformIn(taskId, 1);\n            gTasks[taskId].func = Task_NewGameBirchSpeech_SlidePlatformAway2;\n            break;\n        case MENU_B_PRESSED:\n        case 1:\n            PlaySE(SE_SELECT);\n            gTasks[taskId].func = Task_NewGameBirchSpeech_BoyOrGirl;\n    }",
  },
  "Task_NewGameBirchSpeech_SlidePlatformAway2": {
    callsTo: ["SetGpuReg"],
    taskTransitions: ["Task_NewGameBirchSpeech_ReshowBirchLotad"],
    dataReads: ["tBG1HOFS"],
    dataWrites: ["tBG1HOFS"],
    lineCount: 9,
    bodyC: "if (gTasks[taskId].tBG1HOFS)\n    {\n        gTasks[taskId].tBG1HOFS += 2;\n        SetGpuReg(REG_OFFSET_BG1HOFS, gTasks[taskId].tBG1HOFS);\n    }\n    else\n    {\n        gTasks[taskId].func = Task_NewGameBirchSpeech_ReshowBirchLotad;\n    }",
  },
  "Task_NewGameBirchSpeech_ReshowBirchLotad": {
    callsTo: ["AddTextPrinterForMessage","NewGameBirchSpeech_ClearWindow","NewGameBirchSpeech_StartFadeInTarget1OutTarget2","NewGameBirchSpeech_StartFadePlatformOut","StringExpandPlaceholders"],
    taskTransitions: ["Task_NewGameBirchSpeech_WaitForSpriteFadeInAndTextPrinter"],
    dataReads: ["tBirchSpriteId","tBrendanSpriteId","tIsDoneFadingSprites","tLotadSpriteId","tMaySpriteId"],
    lineCount: 22,
    bodyC: "u8 spriteId;\n\n    if (gTasks[taskId].tIsDoneFadingSprites)\n    {\n        gSprites[gTasks[taskId].tBrendanSpriteId].invisible = TRUE;\n        gSprites[gTasks[taskId].tMaySpriteId].invisible = TRUE;\n        spriteId = gTasks[taskId].tBirchSpriteId;\n        gSprites[spriteId].x = 136;\n        gSprites[spriteId].y = 60;\n        gSprites[spriteId].invisible = FALSE;\n        gSprites[spriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n        spriteId = gTasks[taskId].tLotadSpriteId;\n        gSprites[spriteId].x = 100;\n        gSprites[spriteId].y = 75;\n        gSprites[spriteId].invisible = FALSE;\n        gSprites[spriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n        NewGameBirchSpeech_StartFadeInTarget1OutTarget2(taskId, 2);\n        NewGameBirchSpeech_StartFadePlatformOut(taskId, 1);\n        NewGameBirchSpeech_ClearWindow(0);\n        StringExpandPlaceholders(gStringVar4, gText_Birch_YourePlayer);\n        AddTextPrinterForMessage(TRUE);\n        gTasks[taskId].func = Task_NewGameBirchSpeech_WaitForSpriteFadeInAndTextPrinter;\n    }",
  },
  "Task_NewGameBirchSpeech_WaitForSpriteFadeInAndTextPrinter": {
    callsTo: ["NewGameBirchSpeech_StartFadeOutTarget1InTarget2","NewGameBirchSpeech_StartFadePlatformIn","RunTextPrintersAndIsPrinter0Active"],
    taskTransitions: ["Task_NewGameBirchSpeech_AreYouReady"],
    dataReads: ["tBirchSpriteId","tIsDoneFadingSprites","tLotadSpriteId"],
    dataWrites: ["tTimer"],
    lineCount: 14,
    bodyC: "if (gTasks[taskId].tIsDoneFadingSprites)\n    {\n        gSprites[gTasks[taskId].tBirchSpriteId].oam.objMode = ST_OAM_OBJ_NORMAL;\n        gSprites[gTasks[taskId].tLotadSpriteId].oam.objMode = ST_OAM_OBJ_NORMAL;\n        if (!RunTextPrintersAndIsPrinter0Active())\n        {\n            gSprites[gTasks[taskId].tBirchSpriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n            gSprites[gTasks[taskId].tLotadSpriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n            NewGameBirchSpeech_StartFadeOutTarget1InTarget2(taskId, 2);\n            NewGameBirchSpeech_StartFadePlatformIn(taskId, 1);\n            gTasks[taskId].tTimer = 64;\n            gTasks[taskId].func = Task_NewGameBirchSpeech_AreYouReady;\n        }\n    }",
  },
  "Task_NewGameBirchSpeech_AreYouReady": {
    callsTo: ["AddTextPrinterForMessage","NewGameBirchSpeech_StartFadeInTarget1OutTarget2","NewGameBirchSpeech_StartFadePlatformOut","StringExpandPlaceholders"],
    taskTransitions: ["Task_NewGameBirchSpeech_ShrinkPlayer"],
    dataReads: ["tBirchSpriteId","tBrendanSpriteId","tIsDoneFadingSprites","tLotadSpriteId","tMaySpriteId","tTimer"],
    dataWrites: ["tPlayerSpriteId","tTimer"],
    lineCount: 25,
    bodyC: "u8 spriteId;\n\n    if (gTasks[taskId].tIsDoneFadingSprites)\n    {\n        gSprites[gTasks[taskId].tBirchSpriteId].invisible = TRUE;\n        gSprites[gTasks[taskId].tLotadSpriteId].invisible = TRUE;\n        if (gTasks[taskId].tTimer)\n        {\n            gTasks[taskId].tTimer--;\n            return;\n        }\n        if (gSaveBlock2Ptr->playerGender != MALE)\n            spriteId = gTasks[taskId].tMaySpriteId;\n        else\n            spriteId = gTasks[taskId].tBrendanSpriteId;\n        gSprites[spriteId].x = 120;\n        gSprites[spriteId].y = 60;\n        gSprites[spriteId].invisible = FALSE;\n        gSprites[spriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n        gTasks[taskId].tPlayerSpriteId = spriteId;\n        NewGameBirchSpeech_StartFadeInTarget1OutTarget2(taskId, 2);\n        NewGameBirchSpeech_StartFadePlatformOut(taskId, 1);\n        StringExpandPlaceholders(gStringVar4, gText_Birch_AreYouReady);\n        AddTextPrinterForMessage(TRUE);\n        gTasks[taskId].func = Task_NewGameBirchSpeech_ShrinkPlayer;\n    }",
  },
  "Task_NewGameBirchSpeech_ShrinkPlayer": {
    callsTo: ["BeginNormalPaletteFade","FadeOutBGM","InitSpriteAffineAnim","RunTextPrintersAndIsPrinter0Active","StartSpriteAffineAnim"],
    taskTransitions: ["Task_NewGameBirchSpeech_WaitForPlayerShrink"],
    dataReads: ["tIsDoneFadingSprites","tPlayerSpriteId"],
    lineCount: 17,
    bodyC: "u8 spriteId;\n\n    if (gTasks[taskId].tIsDoneFadingSprites)\n    {\n        gSprites[gTasks[taskId].tPlayerSpriteId].oam.objMode = ST_OAM_OBJ_NORMAL;\n        if (!RunTextPrintersAndIsPrinter0Active())\n        {\n            spriteId = gTasks[taskId].tPlayerSpriteId;\n            gSprites[spriteId].oam.affineMode = ST_OAM_AFFINE_NORMAL;\n            gSprites[spriteId].affineAnims = sSpriteAffineAnimTable_PlayerShrink;\n            InitSpriteAffineAnim(&gSprites[spriteId]);\n            StartSpriteAffineAnim(&gSprites[spriteId], 0);\n            gSprites[spriteId].callback = SpriteCB_MovePlayerDownWhileShrinking;\n            BeginNormalPaletteFade(PALETTES_BG, 0, 0, 16, RGB_BLACK);\n            FadeOutBGM(4);\n            gTasks[taskId].func = Task_NewGameBirchSpeech_WaitForPlayerShrink;\n        }\n    }",
  },
  "Task_NewGameBirchSpeech_WaitForPlayerShrink": {
    taskTransitions: ["Task_NewGameBirchSpeech_FadePlayerToWhite"],
    dataReads: ["tPlayerSpriteId"],
    lineCount: 3,
    bodyC: "u8 spriteId = gTasks[taskId].tPlayerSpriteId;\n\n    if (gSprites[spriteId].affineAnimEnded)\n        gTasks[taskId].func = Task_NewGameBirchSpeech_FadePlayerToWhite;",
  },
  "Task_NewGameBirchSpeech_FadePlayerToWhite": {
    callsTo: ["BeginNormalPaletteFade","SetGpuReg"],
    taskTransitions: ["Task_NewGameBirchSpeech_Cleanup"],
    dataReads: ["tPlayerSpriteId"],
    externalChecks: { paletteFade: true },
    lineCount: 9,
    bodyC: "u8 spriteId;\n\n    if (!gPaletteFade.active)\n    {\n        spriteId = gTasks[taskId].tPlayerSpriteId;\n        gSprites[spriteId].callback = SpriteCB_Null;\n        SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_ON | DISPCNT_OBJ_1D_MAP);\n        BeginNormalPaletteFade(PALETTES_OBJECTS, 0, 0, 16, RGB_WHITEALPHA);\n        gTasks[taskId].func = Task_NewGameBirchSpeech_Cleanup;\n    }",
  },
  "Task_NewGameBirchSpeech_Cleanup": {
    callsTo: ["DestroyTask","FreeAllWindowBuffers","FreeAndDestroyMonPicSprite","ResetAllPicSprites","SetMainCallback2"],
    cb2Transitions: ["CB2_NewGame"],
    dataReads: ["tLotadSpriteId"],
    terminalMarkers: ["DestroyTask"],
    externalChecks: { paletteFade: true },
    lineCount: 8,
    bodyC: "if (!gPaletteFade.active)\n    {\n        FreeAllWindowBuffers();\n        FreeAndDestroyMonPicSprite(gTasks[taskId].tLotadSpriteId);\n        ResetAllPicSprites();\n        SetMainCallback2(CB2_NewGame);\n        DestroyTask(taskId);\n    }",
  },
  "Task_NewGameBirchSpeech_FadeOutTarget1InTarget2": {
    callsTo: ["DestroyTask","SetGpuReg"],
    dataReads: ["tAlphaCoeff1","tAlphaCoeff2","tDelay","tDelayTimer","tMainTask"],
    dataWrites: ["tAlphaCoeff1","tAlphaCoeff2","tDelayTimer"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 18,
    bodyC: "int alphaCoeff2;\n\n    if (gTasks[taskId].tAlphaCoeff1 == 0)\n    {\n        gTasks[gTasks[taskId].tMainTask].tIsDoneFadingSprites = TRUE;\n        DestroyTask(taskId);\n    }\n    else if (gTasks[taskId].tDelayTimer)\n    {\n        gTasks[taskId].tDelayTimer--;\n    }\n    else\n    {\n        gTasks[taskId].tDelayTimer = gTasks[taskId].tDelay;\n        gTasks[taskId].tAlphaCoeff1--;\n        gTasks[taskId].tAlphaCoeff2++;\n        alphaCoeff2 = gTasks[taskId].tAlphaCoeff2 << 8;\n        SetGpuReg(REG_OFFSET_BLDALPHA, gTasks[taskId].tAlphaCoeff1 + alphaCoeff2);\n    }",
  },
  "Task_NewGameBirchSpeech_FadeInTarget1OutTarget2": {
    callsTo: ["DestroyTask","SetGpuReg"],
    dataReads: ["tAlphaCoeff1","tAlphaCoeff2","tDelay","tDelayTimer","tMainTask"],
    dataWrites: ["tAlphaCoeff1","tAlphaCoeff2","tDelayTimer"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 18,
    bodyC: "int alphaCoeff2;\n\n    if (gTasks[taskId].tAlphaCoeff1 == 16)\n    {\n        gTasks[gTasks[taskId].tMainTask].tIsDoneFadingSprites = TRUE;\n        DestroyTask(taskId);\n    }\n    else if (gTasks[taskId].tDelayTimer)\n    {\n        gTasks[taskId].tDelayTimer--;\n    }\n    else\n    {\n        gTasks[taskId].tDelayTimer = gTasks[taskId].tDelay;\n        gTasks[taskId].tAlphaCoeff1++;\n        gTasks[taskId].tAlphaCoeff2--;\n        alphaCoeff2 = gTasks[taskId].tAlphaCoeff2 << 8;\n        SetGpuReg(REG_OFFSET_BLDALPHA, gTasks[taskId].tAlphaCoeff1 + alphaCoeff2);\n    }",
  },
  "Task_NewGameBirchSpeech_FadePlatformIn": {
    callsTo: ["BG_PLTT_ID","DestroyTask","LoadPalette","PLTT_SIZEOF"],
    dataReads: ["tDelay","tDelayBefore","tDelayTimer","tPalIndex"],
    dataWrites: ["tDelayBefore","tDelayTimer","tPalIndex"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 18,
    bodyC: "if (gTasks[taskId].tDelayBefore)\n    {\n        gTasks[taskId].tDelayBefore--;\n    }\n    else if (gTasks[taskId].tPalIndex == 8)\n    {\n        DestroyTask(taskId);\n    }\n    else if (gTasks[taskId].tDelayTimer)\n    {\n        gTasks[taskId].tDelayTimer--;\n    }\n    else\n    {\n        gTasks[taskId].tDelayTimer = gTasks[taskId].tDelay;\n        gTasks[taskId].tPalIndex++;\n        LoadPalette(&sBirchSpeechBgGradientPal[gTasks[taskId].tPalIndex], BG_PLTT_ID(0) + 1, PLTT_SIZEOF(8));\n    }",
  },
  "Task_NewGameBirchSpeech_FadePlatformOut": {
    callsTo: ["BG_PLTT_ID","DestroyTask","LoadPalette","PLTT_SIZEOF"],
    dataReads: ["tDelay","tDelayBefore","tDelayTimer","tPalIndex"],
    dataWrites: ["tDelayBefore","tDelayTimer","tPalIndex"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 18,
    bodyC: "if (gTasks[taskId].tDelayBefore)\n    {\n        gTasks[taskId].tDelayBefore--;\n    }\n    else if (gTasks[taskId].tPalIndex == 0)\n    {\n        DestroyTask(taskId);\n    }\n    else if (gTasks[taskId].tDelayTimer)\n    {\n        gTasks[taskId].tDelayTimer--;\n    }\n    else\n    {\n        gTasks[taskId].tDelayTimer = gTasks[taskId].tDelay;\n        gTasks[taskId].tPalIndex--;\n        LoadPalette(&sBirchSpeechBgGradientPal[gTasks[taskId].tPalIndex], BG_PLTT_ID(0) + 1, PLTT_SIZEOF(8));\n    }",
  },
  "Task_NewGameBirchSpeech_ReturnFromNamingScreenShowTextbox": {
    callsTo: ["NewGameBirchSpeech_ShowDialogueWindow"],
    taskTransitions: ["Task_NewGameBirchSpeech_SoItsPlayerName"],
    dataReads: ["tTimer"],
    dataWrites: ["tTimer"],
    lineCount: 5,
    bodyC: "if (gTasks[taskId].tTimer-- <= 0)\n    {\n        NewGameBirchSpeech_ShowDialogueWindow(0, 1);\n        gTasks[taskId].func = Task_NewGameBirchSpeech_SoItsPlayerName;\n    }",
  },
} as const;

export const CB2S = {
  "CB2_MainMenu": {
    callsTo: ["AnimateSprites","BuildOamBuffer","RunTasks","UpdatePaletteFade"],
    externalChecks: { waitForVBlank: true },
    lineCount: 4,
    bodyC: "RunTasks();\n    AnimateSprites();\n    BuildOamBuffer();\n    UpdatePaletteFade();",
  },
  "CB2_InitMainMenu": {
    callsTo: ["InitMainMenu"],
    lineCount: 1,
    bodyC: "InitMainMenu(FALSE);",
  },
  "CB2_ReinitMainMenu": {
    callsTo: ["InitMainMenu"],
    lineCount: 1,
    bodyC: "InitMainMenu(TRUE);",
  },
  "CB2_NewGameBirchSpeech_ReturnFromNamingScreen": {
    callsTo: ["ARRAY_COUNT","AddBirchSpeechObjects","BG_PLTT_ID","BG_SCREEN_ADDR","BeginNormalPaletteFade","CopyWindowToVram","CreateTask","DmaFill16","DmaFill32","FreeAllSpritePalettes","InitBgFromTemplate","InitBgsFromTemplates","InitWindows","LZ77UnCompVram","LoadMainMenuWindowFrameTiles","LoadMessageBoxGfx","LoadPalette","PLTT_SIZEOF","PutWindowTilemap","ResetAllPicSprites","ResetBgsAndClearDma3BusyFlags","ResetPaletteFade","ResetSpriteData","ResetTasks","ScanlineEffect_Stop","SetGpuReg","SetMainCallback2","SetVBlankCallback","ShowBg"],
    cb2Transitions: ["CB2_MainMenu"],
    lineCount: 71,
    bodyC: "u8 taskId;\n    u8 spriteId;\n    u16 savedIme;\n\n    ResetBgsAndClearDma3BusyFlags(0);\n    SetGpuReg(REG_OFFSET_DISPCNT, 0);\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_ON | DISPCNT_OBJ_1D_MAP);\n    InitBgsFromTemplates(0, sMainMenuBgTemplates, ARRAY_COUNT(sMainMenuBgTemplates));\n    InitBgFromTemplate(&sBirchBgTemplate);\n    SetVBlankCallback(NULL);\n    SetGpuReg(REG_OFFSET_BG2CNT, 0);\n    SetGpuReg(REG_OFFSET_BG1CNT, 0);\n    SetGpuReg(REG_OFFSET_BG0CNT, 0);\n    SetGpuReg(REG_OFFSET_BG2HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG2VOFS, 0);\n    SetGpuReg(REG_OFFSET_BG1HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG1VOFS, 0);\n    SetGpuReg(REG_OFFSET_BG0HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG0VOFS, 0);\n    DmaFill16(3, 0, VRAM, VRAM_SIZE);\n    DmaFill32(3, 0, OAM, OAM_SIZE);\n    DmaFill16(3, 0, PLTT, PLTT_SIZE);\n    ResetPaletteFade();\n    LZ77UnCompVram(sBirchSpeechShadowGfx, (u8 *)VRAM);\n    LZ77UnCompVram(sBirchSpeechBgMap, (u8 *)(BG_SCREEN_ADDR(7)));\n    LoadPalette(sBirchSpeechBgPals, BG_PLTT_ID(0), 2 * PLTT_SIZE_4BPP);\n    LoadPalette(&sBirchSpeechBgGradientPal[1], BG_PLTT_ID(0) + 1, PLTT_SIZEOF(8));\n    ResetTasks();\n    taskId = CreateTask(Task_NewGameBirchSpeech_ReturnFromNamingScreenShowTextbox, 0);\n    gTasks[taskId].tTimer = 5;\n    gTasks[taskId].tBG1HOFS = -60;\n    ScanlineEffect_Stop();\n    ResetSpriteData();\n    FreeAllSpritePalettes();\n    ResetAllPicSprites();\n    AddBirchSpeechObjects(taskId);\n    if (gSaveBlock2Ptr->playerGender != MALE)\n    {\n        gTasks[taskId].tPlayerGender = FEMALE;\n        spriteId = gTasks[taskId].tMaySpriteId;\n    }\n    else\n    {\n        gTasks[taskId].tPlayerGender = MALE;\n        spriteId = gTasks[taskId].tBrendanSpriteId;\n    }\n    gSprites[spriteId].x = 180;\n    gSprites[spriteId].y = 60;\n    gSprites[spriteId].invisible = FALSE;\n    gTasks[taskId].tPlayerSpriteId = spriteId;\n    SetGpuReg(REG_OFFSET_BG1HOFS, -60);\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_BLACK);\n    SetGpuReg(REG_OFFSET_WIN0H, 0);\n    SetGpuReg(REG_OFFSET_WIN0V, 0);\n    SetGpuReg(REG_OFFSET_WININ, 0);\n    SetGpuReg(REG_OFFSET_WINOUT, 0);\n    SetGpuReg(REG_OFFSET_BLDCNT, 0);\n    SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n    SetGpuReg(REG_OFFSET_BLDY, 0);\n    ShowBg(0);\n    ShowBg(1);\n    savedIme = REG_IME;\n    REG_IME = 0;\n    REG_IE |= 1;\n    REG_IME = savedIme;\n    SetVBlankCallback(VBlankCB_MainMenu);\n    SetMainCallback2(CB2_MainMenu);\n    InitWindows(sNewGameBirchSpeechTextWindows);\n    LoadMainMenuWindowFrameTiles(0, 0xF3);\n    LoadMessageBoxGfx(0, BIRCH_DLG_BASE_TILE_NUM, BG_PLTT_ID(15));\n    PutWindowTilemap(0);\n    CopyWindowToVram(0, COPYWIN_FULL);",
  },
} as const;

export const SPRITE_CBS = {
  "SpriteCB_Null": {
    lineCount: 0,
    bodyC: "",
  },
  "SpriteCB_MovePlayerDownWhileShrinking": {
    lineCount: 4,
    bodyC: "u32 y;\n\n    y = (sprite->y << 16) + sprite->data[0] + 0xC000;\n    sprite->y = y >> 16;\n    sprite->data[0] = y;",
  },
} as const;
