// AUTO-GENERATED from src/roulette.c by extract-decomp-task-machines.mjs
// Do not edit manually — re-run `npm run extract:task-machines` to refresh.
//
// Generated: 2026-04-26
// Stats: 32 Task_, 2 CB2_, 26 SpriteCB_

export const TASKS = {
  "Task_SpinWheel": {
    callsTo: ["Cos2","Sin2"],
    lineCount: 14,
    bodyC: "s16 sin;\n    s16 cos;\n\n    if (sRoulette->wheelDelayTimer++ == sRoulette->wheelDelay)\n    {\n        sRoulette->wheelDelayTimer = 0;\n        if ((sRoulette->wheelAngle -= sRoulette->wheelSpeed) < 0)\n            sRoulette->wheelAngle = 360 - sRoulette->wheelSpeed;\n    }\n    sin = Sin2(sRoulette->wheelAngle);\n    cos = Cos2(sRoulette->wheelAngle);\n    sin = sin / 16;\n    sRoulette->wheelRotation.a = sRoulette->wheelRotation.d = cos / 16;\n    sRoulette->wheelRotation.b =  sin;\n    sRoulette->wheelRotation.c = -sin;",
  },
  "Task_StartPlaying": {
    callsTo: ["BLDALPHA_BLEND","DrawGridBackground","HideWheelBalls","ResetBallDataForNewSpin","ResetHits","SetBallCounterNumLeft","SetGpuReg","StartTaskAfterDelayOrInput","UpdatePaletteFade"],
    dataWrites: ["tBallNum"],
    lineCount: 14,
    bodyC: "if (UpdatePaletteFade() == 0)\n    {\n        SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_EFFECT_NONE |\n                                     BLDCNT_TGT2_BG2 |\n                                     BLDCNT_TGT2_BD);\n        SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(8, 8));\n        gTasks[taskId].tBallNum = 0;\n        ResetBallDataForNewSpin(taskId);\n        ResetHits();\n        HideWheelBalls();\n        DrawGridBackground(SELECTION_NONE);\n        SetBallCounterNumLeft(BALLS_PER_ROUND);\n        StartTaskAfterDelayOrInput(taskId, Task_ContinuePlaying, NO_DELAY, A_BUTTON | B_BUTTON);\n    }",
  },
  "Task_AskKeepPlaying": {
    callsTo: ["AddTextPrinterParameterized","CopyWindowToVram","DisplayYesNoMenuDefaultYes","DoYesNoFuncWithChoice","DrawStdWindowFrame"],
    lineCount: 5,
    bodyC: "DisplayYesNoMenuDefaultYes();\n    DrawStdWindowFrame(sTextWindowId, FALSE);\n    AddTextPrinterParameterized(sTextWindowId, FONT_NORMAL, Roulette_Text_KeepPlaying, 0, 1, TEXT_SKIP_DRAW, 0);\n    CopyWindowToVram(sTextWindowId, COPYWIN_FULL);\n    DoYesNoFuncWithChoice(taskId, &sYesNoTable_KeepPlaying);",
  },
  "Task_ContinuePlaying": {
    callsTo: ["ClearStdWindowAndFrame"],
    taskTransitions: ["Task_SelectFirstEmptySquare"],
    lineCount: 2,
    bodyC: "ClearStdWindowAndFrame(0, TRUE);\n    gTasks[taskId].func = Task_SelectFirstEmptySquare;",
  },
  "Task_StopPlaying": {
    callsTo: ["DestroyTask","ExitRoulette"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 2,
    bodyC: "DestroyTask(sRoulette->spinTaskId);\n    ExitRoulette(taskId);",
  },
  "Task_StartHandleBetGridInput": {
    callsTo: ["UpdateGridSelectionRect"],
    taskTransitions: ["Task_HandleBetGridInput"],
    dataReads: ["tSelectionId"],
    lineCount: 5,
    bodyC: "sRoulette->selectionRectDrawState = SELECT_STATE_DRAW;\n    UpdateGridSelectionRect(gTasks[taskId].tSelectionId);\n    sRoulette->wheelDelay = 2;\n    sRoulette->wheelDelayTimer = 0;\n    gTasks[taskId].func = Task_HandleBetGridInput;",
  },
  "Task_SelectFirstEmptySquare": {
    callsTo: ["DrawGridBackground","FlashSelectionOnWheel","ResetBallDataForNewSpin","SetMultiplierSprite"],
    taskTransitions: ["Task_StartHandleBetGridInput"],
    dataReads: ["tSelectionId"],
    dataWrites: ["data[1]","tSelectionId"],
    lineCount: 24,
    bodyC: "s16 i;\n\n    if (sRoulette->hitFlags & F_ORANGE_ROW)\n    {\n         \n        for (i = SQU_GREEN_WYNAUT; i < SQU_GREEN_MAKUHITA; i++)\n        {\n            if (!(sRoulette->hitFlags & sGridSelections[i].flag))\n                break;\n        }\n    }\n    else\n    {\n         \n         \n        for (i = SQU_ORANGE_WYNAUT; i <= SQU_ORANGE_MAKUHITA; i++)  \n        {\n            if (!(sRoulette->hitFlags & sGridSelections[i].flag))\n                break;\n        }\n    }\n    gTasks[taskId].tSelectionId = i;\n    ResetBallDataForNewSpin(taskId);\n    DrawGridBackground(gTasks[taskId].tSelectionId);\n    SetMultiplierSprite(gTasks[taskId].tSelectionId);\n    FlashSelectionOnWheel(gTasks[taskId].tSelectionId);\n    gTasks[taskId].data[1] = 0;\n    gTasks[taskId].func = Task_StartHandleBetGridInput;",
  },
  "Task_StartSpin": {
    callsTo: ["IncrementDailyRouletteUses"],
    taskTransitions: ["Task_SlideGridOffscreen"],
    dataWrites: ["data[1]"],
    lineCount: 9,
    bodyC: "IncrementDailyRouletteUses();\n    sRoulette->selectionRectDrawState = SELECT_STATE_ERASE;\n    if (sRoulette->minBet == 1)\n        sRoulette->wheelDelay = 1;\n    else\n        sRoulette->wheelDelay = 0;\n    sRoulette->wheelDelayTimer = 0;\n    gTasks[taskId].data[1] = 32;\n    gTasks[taskId].func = Task_SlideGridOffscreen;",
  },
  "Task_PlaceBet": {
    callsTo: ["GetMultiplier","SetCreditDigits","SetMultiplierSprite"],
    taskTransitions: ["Task_StartSpin"],
    dataReads: ["tCoins","tSelectionId"],
    dataWrites: ["tCoins","tMultiplier"],
    lineCount: 7,
    bodyC: "sRoulette->betSelection[sRoulette->curBallNum] = gTasks[taskId].tSelectionId;\n    gTasks[taskId].tMultiplier = GetMultiplier(sRoulette->betSelection[sRoulette->curBallNum]);\n    SetMultiplierSprite(sRoulette->betSelection[sRoulette->curBallNum]);\n    if ((gTasks[taskId].tCoins -= sRoulette->minBet) < 0)\n        gTasks[taskId].tCoins = 0;\n    SetCreditDigits(gTasks[taskId].tCoins);\n    gTasks[taskId].func = Task_StartSpin;",
  },
  "Task_HandleBetGridInput": {
    callsTo: ["JOY_NEW","PlaySE","ProcessBetGridInput","UpdateGridSelectionRect","m4aSongNumStart"],
    taskTransitions: ["Task_PlaceBet"],
    dataReads: ["data[1]","tSelectionId"],
    dataWrites: ["data[1]"],
    externalChecks: { joyButtons: ["NEW:A_BUTTON"] },
    lineCount: 29,
    bodyC: "ProcessBetGridInput(taskId);\n\n     \n    switch (gTasks[taskId].data[1])\n    {\n    case 0:\n        UpdateGridSelectionRect(gTasks[taskId].tSelectionId);\n        gTasks[taskId].data[1]++;\n        break;\n    case 30:\n        UpdateGridSelectionRect(SELECTION_NONE);\n        gTasks[taskId].data[1]++;\n        break;\n    case 59:\n        gTasks[taskId].data[1] = 0;\n        break;\n    default:\n        gTasks[taskId].data[1]++;\n    }\n\n    if (JOY_NEW(A_BUTTON))\n    {\n        if (sRoulette->hitFlags & sGridSelections[gTasks[taskId].tSelectionId].flag)\n        {\n             \n            PlaySE(SE_BOO);\n        }\n        else\n        {\n            m4aSongNumStart(SE_SHOP);\n            gTasks[taskId].func = Task_PlaceBet;\n        }\n    }",
  },
  "Task_SlideGridOffscreen": {
    callsTo: ["ShowHideGridBalls","ShowHideGridIcons"],
    taskTransitions: ["Task_InitBallRoll"],
    dataReads: ["data[1]"],
    dataWrites: ["data[1]"],
    lineCount: 14,
    bodyC: "if (gTasks[taskId].data[1]-- > 0)\n    {\n         \n        if (gTasks[taskId].data[1] > 2)\n            gSpriteCoordOffsetX += 2;\n\n         \n        if ((sRoulette->gridX += 4) == 104)\n            gSprites[sRoulette->spriteIds[SPR_MULTIPLIER]].callback = &SpriteCallbackDummy;\n    }\n    else\n    {\n        ShowHideGridIcons(TRUE, -1);\n        ShowHideGridBalls(TRUE, -1);\n        gTasks[taskId].func = Task_InitBallRoll;\n        gTasks[taskId].data[1] = 0;\n    }",
  },
  "Task_InitBallRoll": {
    callsTo: ["GetRandomForBallTravelDistance","Random","S16TOPOSFLOAT"],
    taskTransitions: ["Task_RollBall"],
    dataReads: ["tBallNum","tTotalBallNum"],
    lineCount: 33,
    bodyC: "u8 randTravelMod;\n    s8 randTravelDist;\n    s8 startAngleId;\n    u16 travelDist = 0;\n    u16 rand;\n    u16 randmod;\n    u16 startAngles[4] = {0, 180, 90, 270};  \n\n    rand = Random();\n    randmod = rand % 100;\n    sRoulette->curBallSpriteId = gTasks[taskId].tBallNum;\n     \n    sRoulette->ballState = sRoulette->hitSlot = sRoulette->stuckHitSlot = 0;\n    randTravelMod = GetRandomForBallTravelDistance(gTasks[taskId].tTotalBallNum, rand);\n    randTravelDist = (rand % randTravelMod) - (randTravelMod / 2);\n\n    if (gLocalTime.hours < 13)\n        startAngleId = 0;\n    else\n        startAngleId = 1;\n\n    if (randmod < 80)\n        startAngleId *= 2;\n    else\n        startAngleId = (1 - startAngleId) * 2;\n\n    sRoulette->ballTravelDist = travelDist = sRouletteTables[sRoulette->tableId].baseTravelDist + randTravelDist;\n\n    travelDist = S16TOPOSFLOAT(travelDist) / 5.0f;\n    sRoulette->ballTravelDistFast = travelDist * 3;\n    sRoulette->ballTravelDistSlow = sRoulette->ballTravelDistMed = travelDist;\n\n    sRoulette->ballAngle = S16TOPOSFLOAT(startAngles[(rand & 1) + startAngleId]);\n    sRoulette->ballAngleSpeed = S16TOPOSFLOAT(sRouletteTables[sRoulette->tableId].ballSpeed);\n    sRoulette->ballAngleAccel = ((sRoulette->ballAngleSpeed * 0.5f) - sRoulette->ballAngleSpeed) / S16TOPOSFLOAT(sRoulette->ballTravelDistFast);\n    sRoulette->ballDistToCenter = 68.0f;\n    sRoulette->ballFallAccel = 0.0f;\n    sRoulette->ballFallSpeed = -(8.0f / S16TOPOSFLOAT(sRoulette->ballTravelDistFast));\n    sRoulette->varA0 = 36.0f;\n    gTasks[taskId].func = Task_RollBall;",
  },
  "Task_RollBall": {
    callsTo: ["SetBallCounterNumLeft","m4aSongNumStart"],
    taskTransitions: ["Task_RecordBallHit"],
    spriteTransitions: ["SpriteCB_RollBall_Start"],
    dataReads: ["tBallNum","tTotalBallNum"],
    dataWrites: ["tBallNum","tTotalBallNum"],
    lineCount: 8,
    bodyC: "sRoulette->ballRolling = TRUE;\n    sRoulette->ball = &gSprites[sRoulette->spriteIds[sRoulette->curBallSpriteId]];\n    sRoulette->ball->callback = SpriteCB_RollBall_Start;\n    gTasks[taskId].tBallNum++;\n    gTasks[taskId].tTotalBallNum++;\n    SetBallCounterNumLeft(BALLS_PER_ROUND - gTasks[taskId].tBallNum);\n    m4aSongNumStart(SE_ROULETTE_BALL);\n    gTasks[taskId].func = Task_RecordBallHit;",
  },
  "Task_RecordBallHit": {
    callsTo: ["DrawGridBackground","IsHitInBetSelection","JOY_NEW","RecordHit","RouletteFlash_Enable","ShowHideGridBalls","ShowHideGridIcons"],
    taskTransitions: ["Task_SlideGridOnscreen"],
    dataReads: ["data[1]","tBallNum","tWinningSquare"],
    dataWrites: ["data[1]","tWonBet"],
    externalChecks: { joyButtons: ["NEW:A_BUTTON"] },
    lineCount: 35,
    bodyC: "if (sRoulette->ballState != BALL_STATE_ROLLING)\n    {\n         \n        if (sRoulette->ballStuck)\n        {\n            if (sRoulette->ballUnstuck)\n            {\n                sRoulette->ballUnstuck = FALSE;\n                sRoulette->ballStuck = FALSE;\n            }\n        }\n        else\n        {\n            if (gTasks[taskId].data[1] == 0)\n            {\n                bool8 won = IsHitInBetSelection(RecordHit(taskId, sRoulette->hitSlot), sRoulette->betSelection[sRoulette->curBallNum]);\n                gTasks[taskId].tWonBet = won;\n                if (won == TRUE)\n                    RouletteFlash_Enable(&sRoulette->flashUtil, F_FLASH_OUTER_EDGES);\n            }\n            if (gTasks[taskId].data[1] <= 60)\n            {\n                if (JOY_NEW(A_BUTTON))\n                    gTasks[taskId].data[1] = 60;\n                gTasks[taskId].data[1]++;\n            }\n            else\n            {\n                DrawGridBackground(sRoulette->betSelection[sRoulette->curBallNum]);\n                ShowHideGridIcons(FALSE, gTasks[taskId].tWinningSquare);\n                ShowHideGridBalls(FALSE, gTasks[taskId].tBallNum - 1);\n                gTasks[taskId].data[1] = 32;\n                gTasks[taskId].func = Task_SlideGridOnscreen;\n            }\n        }\n    }",
  },
  "Task_SlideGridOnscreen": {
    callsTo: ["ShowHideWinSlotCursor"],
    taskTransitions: ["Task_FlashBallOnWinningSquare"],
    dataReads: ["data[1]","tWinningSquare"],
    dataWrites: ["data[1]","tWonBet"],
    lineCount: 16,
    bodyC: "if (gTasks[taskId].data[1]-- > 0)\n    {\n         \n        if (gTasks[taskId].data[1] > 2)\n            gSpriteCoordOffsetX -= 2;\n\n         \n        if ((sRoulette->gridX -= 4) == 104)\n            gSprites[sRoulette->spriteIds[SPR_MULTIPLIER]].callback = SpriteCB_GridSquare;\n    }\n    else\n    {\n        ShowHideWinSlotCursor(gTasks[taskId].tWinningSquare);\n        if (gTasks[taskId].tWonBet == TRUE)\n            gTasks[taskId].data[1] = 121;\n        else\n            gTasks[taskId].data[1] = 61;\n        gTasks[taskId].func = Task_FlashBallOnWinningSquare;\n    }",
  },
  "Task_FlashBallOnWinningSquare": {
    callsTo: ["ShowHideGridBalls","ShowHideGridIcons","StartTaskAfterDelayOrInput"],
    dataReads: ["data[1]","tBallNum","tWinningSquare"],
    dataWrites: ["data[1]"],
    lineCount: 18,
    bodyC: "if (gTasks[taskId].data[1]-- > 1)\n    {\n        switch (gTasks[taskId].data[1] % 16)\n        {\n        case 8:\n             \n            ShowHideGridIcons(FALSE, -1);\n            ShowHideGridBalls(FALSE, -1);\n            break;\n        case 0:\n             \n            ShowHideGridIcons(FALSE, gTasks[taskId].tWinningSquare);\n            ShowHideGridBalls(FALSE, gTasks[taskId].tBallNum - 1);\n            break;\n        }\n    }\n    else\n    {\n        StartTaskAfterDelayOrInput(taskId, Task_PrintSpinResult, 30, 0);\n    }",
  },
  "Task_TryIncrementWins": {
    callsTo: ["GetGameStat","IsFanfareTaskInactive","IsSEPlaying","SetGameStat","StartTaskAfterDelayOrInput"],
    dataReads: ["tConsecutiveWins","tWonBet"],
    dataWrites: ["tConsecutiveWins"],
    lineCount: 21,
    bodyC: "switch (gTasks[taskId].tWonBet)\n    {\n    case TRUE:\n    case 2:  \n        if (IsFanfareTaskInactive())\n        {\n            u32 wins = GetGameStat(GAME_STAT_CONSECUTIVE_ROULETTE_WINS);\n            if (wins < ++gTasks[taskId].tConsecutiveWins)\n                SetGameStat(GAME_STAT_CONSECUTIVE_ROULETTE_WINS, gTasks[taskId].tConsecutiveWins);\n            StartTaskAfterDelayOrInput(taskId, Task_PrintPayout, NO_DELAY, A_BUTTON | B_BUTTON);\n        }\n        break;\n    case FALSE:\n    default:\n        if (!IsSEPlaying())\n        {\n            gTasks[taskId].tConsecutiveWins = 0;\n            StartTaskAfterDelayOrInput(taskId, Task_EndTurn, NO_DELAY, A_BUTTON | B_BUTTON);\n        }\n        break;\n    }",
  },
  "Task_PrintSpinResult": {
    callsTo: ["AddTextPrinterParameterized","CopyWindowToVram","DrawStdWindowFrame","PlayFanfare","m4aSongNumStart"],
    taskTransitions: ["Task_TryIncrementWins"],
    dataReads: ["tWonBet"],
    dataWrites: ["data[1]","tMultiplier"],
    lineCount: 29,
    bodyC: "switch (gTasks[taskId].tWonBet)\n    {\n    case TRUE:\n    case 2:  \n        if (gTasks[taskId].tMultiplier == MAX_MULTIPLIER)\n        {\n            PlayFanfare(MUS_SLOTS_JACKPOT);\n            DrawStdWindowFrame(sTextWindowId, FALSE);\n            AddTextPrinterParameterized(sTextWindowId, FONT_NORMAL, Roulette_Text_Jackpot, 0, 1, TEXT_SKIP_DRAW, NULL);\n            CopyWindowToVram(sTextWindowId, COPYWIN_FULL);\n        }\n        else\n        {\n            PlayFanfare(MUS_SLOTS_WIN);\n            DrawStdWindowFrame(sTextWindowId, FALSE);\n            AddTextPrinterParameterized(sTextWindowId, FONT_NORMAL, Roulette_Text_ItsAHit, 0, 1, TEXT_SKIP_DRAW, NULL);\n            CopyWindowToVram(sTextWindowId, COPYWIN_FULL);\n        }\n        break;\n    case FALSE:\n    default:\n        m4aSongNumStart(SE_FAILURE);\n        DrawStdWindowFrame(sTextWindowId, FALSE);\n        AddTextPrinterParameterized(sTextWindowId, FONT_NORMAL, Roulette_Text_NothingDoing, 0, 1, TEXT_SKIP_DRAW, NULL);\n        CopyWindowToVram(sTextWindowId, COPYWIN_FULL);\n        break;\n    }\n    gTasks[taskId].data[1] = 0;\n    gTasks[taskId].func = Task_TryIncrementWins;",
  },
  "Task_GivePayout": {
    callsTo: ["SetCreditDigits","StartTaskAfterDelayOrInput","m4aSongNumStart","m4aSongNumStop"],
    dataReads: ["data[7]","tCoins","tPayout"],
    dataWrites: ["data[7]","tCoins","tPayout"],
    lineCount: 26,
    bodyC: "switch (gTasks[taskId].data[7])\n    {\n    case 0:\n        gTasks[taskId].tCoins++;\n        m4aSongNumStart(SE_PIN);\n        SetCreditDigits(gTasks[taskId].tCoins);\n        if (gTasks[taskId].tCoins >= MAX_COINS)\n        {\n            gTasks[taskId].tPayout = 0;\n        }\n        else\n        {\n            gTasks[taskId].tPayout--;\n            gTasks[taskId].data[7]++;\n        }\n        break;\n    case 3:\n        m4aSongNumStop(SE_PIN);\n        gTasks[taskId].data[7] = 0;\n        break;\n    default:\n        gTasks[taskId].data[7]++;\n        break;\n    }\n    if (gTasks[taskId].tPayout == 0)\n        StartTaskAfterDelayOrInput(taskId, Task_EndTurn, NO_DELAY, A_BUTTON | B_BUTTON);",
  },
  "Task_PrintPayout": {
    callsTo: ["AddTextPrinterParameterized","ConvertIntToDecimalStringN","CopyWindowToVram","DrawStdWindowFrame","StringExpandPlaceholders"],
    taskTransitions: ["Task_GivePayout"],
    dataReads: ["tMultiplier"],
    dataWrites: ["data[7]","tPayout"],
    lineCount: 8,
    bodyC: "ConvertIntToDecimalStringN(gStringVar1, (sRoulette->minBet * gTasks[taskId].tMultiplier), STR_CONV_MODE_LEFT_ALIGN, 2);\n    StringExpandPlaceholders(gStringVar4, Roulette_Text_YouveWonXCoins);\n    DrawStdWindowFrame(sTextWindowId, FALSE);\n    AddTextPrinterParameterized(sTextWindowId, FONT_NORMAL, gStringVar4, 0, 1, TEXT_SKIP_DRAW, NULL);\n    CopyWindowToVram(sTextWindowId, COPYWIN_FULL);\n    gTasks[taskId].tPayout = (sRoulette->minBet * gTasks[taskId].tMultiplier);\n    gTasks[taskId].data[7] = 0;\n    gTasks[taskId].func = Task_GivePayout;",
  },
  "Task_EndTurn": {
    callsTo: ["RouletteFlash_Stop"],
    taskTransitions: ["Task_TryPrintEndTurnMsg"],
    dataReads: ["tWinningSquare"],
    lineCount: 4,
    bodyC: "RouletteFlash_Stop(&sRoulette->flashUtil, 0xFFFF);\n    sRoulette->flashUtil.palettes[FLASH_ICON].available = sRoulette->flashUtil.palettes[FLASH_ICON_2].available = sRoulette->flashUtil.palettes[FLASH_ICON_3].available = FALSE;\n    gSprites[sRoulette->spriteIds[SPR_WHEEL_ICONS + sGridSelections[gTasks[taskId].tWinningSquare].spriteIdOffset]].invisible = TRUE;\n    gTasks[taskId].func = Task_TryPrintEndTurnMsg;",
  },
  "Task_TryPrintEndTurnMsg": {
    callsTo: ["AddTextPrinterParameterized","CopyWindowToVram","DrawGridBackground","DrawStdWindowFrame","StartTaskAfterDelayOrInput"],
    taskTransitions: ["Task_AskKeepPlaying"],
    dataReads: ["tCoins"],
    dataWrites: ["tBallNum","tCoins","tSelectionId"],
    lineCount: 39,
    bodyC: "u8 i = 0;\n    gTasks[taskId].tSelectionId = i;\n    sRoulette->betSelection[sRoulette->curBallNum] = SELECTION_NONE;\n    DrawGridBackground(SELECTION_NONE);\n    gSprites[sRoulette->spriteIds[SPR_WIN_SLOT_CURSOR]].invisible = TRUE;\n    for (i = 0; i < NUM_BOARD_POKES; i++)\n    {\n        gSprites[sRoulette->spriteIds[i + SPR_POKE_HEADERS]].oam.tileNum =\n            gSprites[sRoulette->spriteIds[i + SPR_POKE_HEADERS]].sheetTileStart\n            + (*gSprites[sRoulette->spriteIds[i + SPR_POKE_HEADERS]].anims)->type;\n    }\n    if (gTasks[taskId].tCoins >= sRoulette->minBet)\n    {\n        if (gTasks[taskId].tBallNum == BALLS_PER_ROUND)\n        {\n             \n            DrawStdWindowFrame(sTextWindowId, FALSE);\n            AddTextPrinterParameterized(sTextWindowId, FONT_NORMAL, Roulette_Text_BoardWillBeCleared, 0, 1, TEXT_SKIP_DRAW, NULL);\n            CopyWindowToVram(sTextWindowId, COPYWIN_FULL);\n            StartTaskAfterDelayOrInput(taskId, Task_ClearBoard, NO_DELAY, A_BUTTON | B_BUTTON);\n        }\n        else if (gTasks[taskId].tCoins == MAX_COINS)\n        {\n             \n            DrawStdWindowFrame(sTextWindowId, FALSE);\n            AddTextPrinterParameterized(sTextWindowId, FONT_NORMAL, Roulette_Text_CoinCaseIsFull, 0, 1, TEXT_SKIP_DRAW, NULL);\n            CopyWindowToVram(sTextWindowId, COPYWIN_FULL);\n            StartTaskAfterDelayOrInput(taskId, Task_AskKeepPlaying, NO_DELAY, A_BUTTON | B_BUTTON);\n        }\n        else\n        {\n             \n            gTasks[taskId].func = Task_AskKeepPlaying;\n        }\n    }\n    else\n    {\n         \n        DrawStdWindowFrame(sTextWindowId, FALSE);\n        AddTextPrinterParameterized(sTextWindowId, FONT_NORMAL, Roulette_Text_NoCoinsLeft, 0, 1, TEXT_SKIP_DRAW, NULL);\n        CopyWindowToVram(sTextWindowId, COPYWIN_FULL);\n        StartTaskAfterDelayOrInput(taskId, Task_StopPlaying, 60, A_BUTTON | B_BUTTON);\n    }",
  },
  "Task_ClearBoard": {
    callsTo: ["AddTextPrinterParameterized","CopyWindowToVram","DrawGridBackground","DrawStdWindowFrame","HideWheelBalls","ResetBallDataForNewSpin","ResetHits","SetBallCounterNumLeft","StartTaskAfterDelayOrInput"],
    taskTransitions: ["Task_AskKeepPlaying"],
    dataWrites: ["tBallNum","tCoins"],
    lineCount: 22,
    bodyC: "u8 i = 0;\n\n    gTasks[taskId].tBallNum = 0;\n    ResetBallDataForNewSpin(taskId);\n    ResetHits();\n    HideWheelBalls();\n    DrawGridBackground(SELECTION_NONE);\n    SetBallCounterNumLeft(BALLS_PER_ROUND);\n\n    for (i = 0; i < NUM_ROULETTE_SLOTS; i++)\n    {\n        gSprites[sRoulette->spriteIds[i + SPR_WHEEL_ICONS]].invisible = FALSE;\n    }\n\n    if (gTasks[taskId].tCoins == MAX_COINS)\n    {\n        DrawStdWindowFrame(sTextWindowId, FALSE);\n        AddTextPrinterParameterized(sTextWindowId, FONT_NORMAL, Roulette_Text_CoinCaseIsFull, 0, 1, TEXT_SKIP_DRAW, NULL);\n        CopyWindowToVram(sTextWindowId, COPYWIN_FULL);\n        StartTaskAfterDelayOrInput(taskId, Task_AskKeepPlaying, NO_DELAY, A_BUTTON | B_BUTTON);\n    }\n    else\n    {\n        gTasks[taskId].func = Task_AskKeepPlaying;\n    }",
  },
  "Task_ExitRoulette": {
    callsTo: ["DestroyTask","FreeAllSpritePalettes","FreeRoulette","ResetAllBgsCoordinates","ResetPaletteFade","ResetSpriteData","ResetVramOamAndBgCntRegs","SetGpuReg","SetMainCallback2","SetVBlankCallback","UpdatePaletteFade"],
    cb2Transitions: ["CB2_ReturnToField"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 17,
    bodyC: "if (UpdatePaletteFade() == 0)\n    {\n        SetVBlankCallback(NULL);\n        gSpriteCoordOffsetX = gSpriteCoordOffsetY = 0;\n        ResetVramOamAndBgCntRegs();\n        ResetAllBgsCoordinates();\n        SetGpuReg(REG_OFFSET_BLDCNT, 0);\n        SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n        SetGpuReg(REG_OFFSET_BLDY, 0);\n        FreeAllSpritePalettes();\n        ResetPaletteFade();\n        ResetSpriteData();\n        FreeRoulette();\n        gFieldCallback = FieldCB_ContinueScriptHandleMusic;\n        SetMainCallback2(CB2_ReturnToField);\n        DestroyTask(taskId);\n    }",
  },
  "Task_WaitForNextTask": {
    callsTo: ["JOY_NEW","PlaySE"],
    taskTransitions: ["sRoulette"],
    lineCount: 11,
    bodyC: "if (sRoulette->taskWaitDelay == 0 || JOY_NEW(sRoulette->taskWaitKey))\n    {\n        gTasks[taskId].func = sRoulette->nextTask;\n        if (sRoulette->taskWaitKey > 0)\n            PlaySE(SE_SELECT);\n        sRoulette->nextTask = NULL;\n        sRoulette->taskWaitKey = 0;\n        sRoulette->taskWaitDelay = 0;\n    }\n    if (sRoulette->taskWaitDelay != NO_DELAY)\n        sRoulette->taskWaitDelay--;",
  },
  "Task_ShowMinBetYesNo": {
    callsTo: ["DisplayYesNoMenuDefaultYes","DoYesNoFuncWithChoice"],
    lineCount: 2,
    bodyC: "DisplayYesNoMenuDefaultYes();\n    DoYesNoFuncWithChoice(taskId, &sYesNoTable_AcceptMinBet);",
  },
  "Task_FadeToRouletteGame": {
    callsTo: ["DestroyTask","SetMainCallback2","SetVBlankCallback"],
    cb2Transitions: ["CB2_LoadRoulette"],
    terminalMarkers: ["DestroyTask"],
    externalChecks: { paletteFade: true },
    lineCount: 6,
    bodyC: "if (!gPaletteFade.active)\n    {\n        SetVBlankCallback(NULL);\n        SetMainCallback2(CB2_LoadRoulette);\n        DestroyTask(taskId);\n    }",
  },
  "Task_AcceptMinBet": {
    callsTo: ["BeginNormalPaletteFade","ClearStdWindowAndFrame","FreeAllWindowBuffers","HideCoinsWindow","UpdatePaletteFade"],
    taskTransitions: ["Task_FadeToRouletteGame"],
    lineCount: 7,
    bodyC: "ClearStdWindowAndFrame(0, TRUE);\n    HideCoinsWindow();\n    FreeAllWindowBuffers();\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_BLACK);\n    gPaletteFade.delayCounter = gPaletteFade.multipurpose2;\n    UpdatePaletteFade();\n    gTasks[taskId].func = Task_FadeToRouletteGame;",
  },
  "Task_DeclineMinBet": {
    callsTo: ["ClearStdWindowAndFrame","DestroyTask","HideCoinsWindow","UnlockPlayerFieldControls"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 4,
    bodyC: "ClearStdWindowAndFrame(0, FALSE);\n    HideCoinsWindow();\n    UnlockPlayerFieldControls();\n    DestroyTask(taskId);",
  },
  "Task_NotEnoughForMinBet": {
    callsTo: ["ClearStdWindowAndFrame","DestroyTask","HideCoinsWindow","JOY_NEW","UnlockPlayerFieldControls"],
    dataReads: ["data[0]"],
    dataWrites: ["data[0]"],
    terminalMarkers: ["DestroyTask"],
    lineCount: 9,
    bodyC: "gTasks[taskId].data[0]++;\n    if (JOY_NEW(A_BUTTON | B_BUTTON))\n    {\n        gSpecialVar_0x8004 = 1;\n        HideCoinsWindow();\n        ClearStdWindowAndFrame(0, TRUE);\n        UnlockPlayerFieldControls();\n        DestroyTask(taskId);\n    }",
  },
  "Task_PrintMinBet": {
    callsTo: ["AddTextPrinterParameterized","ConvertIntToDecimalStringN","CopyWindowToVram","DrawStdWindowFrame","GET_MIN_BET_ID","JOY_NEW","StringExpandPlaceholders"],
    taskTransitions: ["Task_ShowMinBetYesNo"],
    lineCount: 10,
    bodyC: "if (JOY_NEW(A_BUTTON | B_BUTTON))\n    {\n        u32 minBet = sTableMinBets[GET_MIN_BET_ID(gSpecialVar_0x8004)];\n        ConvertIntToDecimalStringN(gStringVar1, minBet, STR_CONV_MODE_LEADING_ZEROS, 1);\n        StringExpandPlaceholders(gStringVar4, Roulette_Text_PlayMinimumWagerIsX);\n        DrawStdWindowFrame(0, FALSE);\n        AddTextPrinterParameterized(0, FONT_NORMAL, gStringVar4, 0, 1, TEXT_SKIP_DRAW, NULL);\n        CopyWindowToVram(0, COPYWIN_FULL);\n        gTasks[taskId].func = Task_ShowMinBetYesNo;\n    }",
  },
  "Task_PrintRouletteEntryMsg": {
    callsTo: ["AddTextPrinterParameterized","ConvertIntToDecimalStringN","CopyWindowToVram","DrawStdWindowFrame","GET_MIN_BET_ID","PrintCoinsString","StringExpandPlaceholders"],
    taskTransitions: ["Task_NotEnoughForMinBet","Task_PrintMinBet","Task_ShowMinBetYesNo"],
    dataReads: ["tCoins"],
    dataWrites: ["data[0]","tCoins"],
    lineCount: 32,
    bodyC: "s32 minBet;\n    PrintCoinsString(gTasks[taskId].tCoins);\n    minBet = sTableMinBets[GET_MIN_BET_ID(gSpecialVar_0x8004)];\n    ConvertIntToDecimalStringN(gStringVar1, minBet, STR_CONV_MODE_LEADING_ZEROS, 1);\n\n    if (gTasks[taskId].tCoins >= minBet)\n    {\n        if ((gSpecialVar_0x8004 & ROULETTE_SPECIAL_RATE) && (gSpecialVar_0x8004 & 1))\n        {\n             \n            DrawStdWindowFrame(0, FALSE);\n            AddTextPrinterParameterized(0, FONT_NORMAL, Roulette_Text_SpecialRateTable, 0, 1, TEXT_SKIP_DRAW, NULL);\n            CopyWindowToVram(0, COPYWIN_FULL);\n            gTasks[taskId].func = Task_PrintMinBet;\n        }\n        else\n        {\n             \n            StringExpandPlaceholders(gStringVar4, Roulette_Text_PlayMinimumWagerIsX);\n            DrawStdWindowFrame(0, FALSE);\n            AddTextPrinterParameterized(0, FONT_NORMAL, gStringVar4, 0, 1, TEXT_SKIP_DRAW, NULL);\n            CopyWindowToVram(0, COPYWIN_FULL);\n            gTasks[taskId].func = Task_ShowMinBetYesNo;\n        }\n    }\n    else\n    {\n         \n        StringExpandPlaceholders(gStringVar4, Roulette_Text_NotEnoughCoins);\n        DrawStdWindowFrame(0, FALSE);\n        AddTextPrinterParameterized(0, FONT_NORMAL, gStringVar4, 0, 1, TEXT_SKIP_DRAW, NULL);\n        CopyWindowToVram(0, COPYWIN_FULL);\n        gTasks[taskId].func = Task_NotEnoughForMinBet;\n        gTasks[taskId].tCoins = 0;\n        gTasks[taskId].data[0] = 0;\n    }",
  },
} as const;

export const CB2S = {
  "CB2_Roulette": {
    callsTo: ["AnimateSprites","BuildOamBuffer","RouletteFlash_Run","RunTasks"],
    externalChecks: { waitForVBlank: true },
    lineCount: 5,
    bodyC: "RunTasks();\n    AnimateSprites();\n    BuildOamBuffer();\n    if (sRoulette->flashUtil.enabled)\n        RouletteFlash_Run(&sRoulette->flashUtil);",
  },
  "CB2_LoadRoulette": {
    callsTo: ["AddTextPrinterParameterized","AlertTVThatPlayerPlayedRoulette","AnimateSprites","BG_PLTT_ID","BLDALPHA_BLEND","BeginHardwarePaletteFade","BuildOamBuffer","CopyBgTilemapBufferToVram","CopyToBgTilemapBuffer","CopyWindowToVram","CreateGridBallSprites","CreateGridSprites","CreateInterfaceSprites","CreateTask","CreateWheelBallSprites","CreateWheelCenterSprite","CreateWheelIconSprites","DeactivateAllTextPrinters","DecompressAndCopyTileDataToVram","DrawGridBackground","DrawStdWindowFrame","EnableInterrupts","FreeTempTileDataBuffersIfPossible","GetCoins","InitRouletteBgAndWindows","InitRouletteTableData","LoadOrFreeMiscSpritePalettesAndSheets","LoadPalette","ResetAllBgsCoordinates","ResetPaletteFade","ResetSpriteData","ResetTasks","ResetTempTileDataBuffers","ResetVramOamAndBgCntRegs","ScanlineEffect_Stop","SetBallCounterNumLeft","SetCreditDigits","SetGpuReg","SetMainCallback2","SetMultiplierSprite","SetVBlankCallback","SetVBlankHBlankCallbacksToNull","ShowBg"],
    cb2Transitions: ["CB2_Roulette"],
    externalChecks: { waitForVBlank: true },
    lineCount: 80,
    bodyC: "u8 taskId;\n\n    switch (gMain.state)\n    {\n    case 0:\n        SetVBlankCallback(NULL);\n        ScanlineEffect_Stop();\n        SetVBlankHBlankCallbacksToNull();\n        ResetVramOamAndBgCntRegs();\n        ResetAllBgsCoordinates();\n        break;\n    case 1:\n        InitRouletteBgAndWindows();\n        DeactivateAllTextPrinters();\n        SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_EFFECT_NONE |\n                                     BLDCNT_TGT2_BG2 |\n                                     BLDCNT_TGT2_BD);\n        SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(10, 6));\n        break;\n    case 2:\n        ResetPaletteFade();\n        ResetSpriteData();\n        ResetTasks();\n        ResetTempTileDataBuffers();\n        break;\n    case 3:\n        LoadPalette(&sWheel_Pal, BG_PLTT_ID(0), 14 * PLTT_SIZE_4BPP);\n        DecompressAndCopyTileDataToVram(1, gRouletteMenu_Gfx, 0, 0, 0);\n        DecompressAndCopyTileDataToVram(2, gRouletteWheel_Gfx, 0, 0, 0);\n        break;\n    case 4:\n        if (FreeTempTileDataBuffersIfPossible())\n            return;\n\n        InitRouletteTableData();\n        CopyToBgTilemapBuffer(2, sWheel_Tilemap, 0, 0);\n        break;\n    case 5:\n        LoadOrFreeMiscSpritePalettesAndSheets(FALSE);\n        CreateWheelBallSprites();\n        CreateWheelCenterSprite();\n        CreateInterfaceSprites();\n        CreateGridSprites();\n        CreateGridBallSprites();\n        CreateWheelIconSprites();\n        break;\n    case 6:\n        AnimateSprites();\n        BuildOamBuffer();\n        SetCreditDigits(GetCoins());\n        SetBallCounterNumLeft(BALLS_PER_ROUND);\n        SetMultiplierSprite(SELECTION_NONE);\n        DrawGridBackground(SELECTION_NONE);\n        DrawStdWindowFrame(sTextWindowId, FALSE);\n        AddTextPrinterParameterized(sTextWindowId, FONT_NORMAL, Roulette_Text_ControlsInstruction, 0, 1, TEXT_SKIP_DRAW, NULL);\n        CopyWindowToVram(sTextWindowId, COPYWIN_FULL);\n        gSpriteCoordOffsetX = -60;\n        gSpriteCoordOffsetY = 0;\n        break;\n    case 7:\n        SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_0 |\n                                      DISPCNT_OBJ_1D_MAP |\n                                      DISPCNT_OBJ_ON);\n        CopyBgTilemapBufferToVram(1);\n        CopyBgTilemapBufferToVram(2);\n        ShowBg(0);\n        ShowBg(1);\n        ShowBg(2);\n        break;\n    case 8:\n        EnableInterrupts(INTR_FLAG_VBLANK);\n        SetVBlankCallback(VBlankCB_Roulette);\n        BeginHardwarePaletteFade(0xFF, 0, 16, 0, 1);\n        taskId = sRoulette->playTaskId = CreateTask(Task_StartPlaying, 0);\n        gTasks[taskId].tBallNum = BALLS_PER_ROUND;\n        gTasks[taskId].tCoins = GetCoins();\n        AlertTVThatPlayerPlayedRoulette(GetCoins());\n        sRoulette->spinTaskId = CreateTask(Task_SpinWheel, 1);\n        SetMainCallback2(CB2_Roulette);\n        return;\n    }\n    gMain.state++;",
  },
} as const;

export const SPRITE_CBS = {
  "SpriteCB_WheelIcon": {
    callsTo: ["Cos2","Sin2"],
    lineCount: 16,
    bodyC: "s16 cos;\n    s16 sin;\n    u32 matrixNum;\n    s16 angle = sRoulette->wheelAngle + sprite->data[0];\n    if (angle >= 360)\n        angle -= 360;\n    sin = Sin2(angle);\n    cos = Cos2(angle);\n    sprite->x2 =  sin * sprite->data[1] >> 12;\n    sprite->y2 = -cos * sprite->data[1] >> 12;\n    matrixNum = sprite->oam.matrixNum;\n    sin /= 16;\n    gOamMatrices[matrixNum].d = cos /= 16;\n    gOamMatrices[matrixNum].a = cos;\n    gOamMatrices[matrixNum].b = sin;\n    gOamMatrices[matrixNum].c = -sin;",
  },
  "SpriteCB_GridSquare": {
    lineCount: 1,
    bodyC: "sprite->x2 = sRoulette->gridX;",
  },
  "SpriteCB_WheelCenter": {
    lineCount: 6,
    bodyC: "u32 matrixNum = sprite->oam.matrixNum;\n    struct OamMatrix *matrix = &gOamMatrices[0];\n    matrix[matrixNum].d = sRoulette->wheelRotation.a;\n    matrix[matrixNum].a = sRoulette->wheelRotation.a;\n    matrix[matrixNum].b = sRoulette->wheelRotation.b;\n    matrix[matrixNum].c = sRoulette->wheelRotation.c;",
  },
  "SpriteCB_BallLandInSlot": {
    callsTo: ["Cos2","Sin2"],
    lineCount: 9,
    bodyC: "s16 sin, cos;\n    sprite->sBallAngle = sRoulette->wheelAngle + sprite->sBallWheelAngle;\n    if (sprite->sBallAngle >= 360)\n        sprite->sBallAngle -= 360;\n    sin = Sin2(sprite->sBallAngle);\n    cos = Cos2(sprite->sBallAngle);\n    sprite->x2 =  sin * sprite->sBallDistToCenter >> 12;\n    sprite->y2 = -cos * sprite->sBallDistToCenter >> 12;\n    sprite->y2 += gSpriteCoordOffsetY;",
  },
  "SpriteCB_UnstickBall_ShroomishBallFall": {
    callsTo: ["LandBall","UpdateBallPos"],
    lineCount: 27,
    bodyC: "UpdateBallPos(sprite);\n    sprite->data[2]++;\n    if (sprite->sBallDistToCenter < -132 || sprite->sBallDistToCenter > 80)\n        sprite->invisible = TRUE;\n    else\n        sprite->invisible = FALSE;\n\n    if (sprite->data[2] >= DEGREES_PER_SLOT)\n    {\n        if (!sprite->sStuckOnWheelLeft)\n        {\n            if (sRoulette->ballDistToCenter <= sRoulette->varA0 - 2.0f)\n            {\n                LandBall()\n                sRoulette->ballFallAccel = sRoulette->ballFallSpeed = 0.0f;\n                sRoulette->ballAngleSpeed = -1.0f;\n            }\n        }\n        else\n        {\n            if (sRoulette->ballDistToCenter >= sRoulette->varA0 - 2.0f)\n            {\n                LandBall()\n                sRoulette->ballFallAccel = sRoulette->ballFallSpeed = 0.0f;\n                sRoulette->ballAngleSpeed = -1.0f;\n            }\n        }\n    }",
  },
  "SpriteCB_UnstickBall_Shroomish": {
    callsTo: ["UpdateBallPos"],
    spriteTransitions: ["SpriteCB_UnstickBall_ShroomishBallFall"],
    lineCount: 41,
    bodyC: "f32 slotOffset, ballFallDist, ballFallSpeed;\n    UpdateBallPos(sprite);\n\n    switch (sprite->sBallAngle)\n    {\n    case 0:\n        if (sprite->sStuckOnWheelLeft != TRUE)\n        {\n            slotOffset = sprite->data[7];\n            ballFallDist = (slotOffset * sRouletteTables[sRoulette->tableId].randDistanceHigh + (sRouletteTables[sRoulette->tableId].randDistanceLow - 1));\n            ballFallSpeed = (slotOffset / sRouletteTables[sRoulette->tableId].shroomish.fallSlowdown);\n        }\n        else\n        {\n            return;\n        }\n        break;\n    case 180:\n        if (sprite->sStuckOnWheelLeft)\n        {\n            slotOffset = sprite->data[7];\n            ballFallDist = (slotOffset * sRouletteTables[sRoulette->tableId].randDistanceHigh + (sRouletteTables[sRoulette->tableId].randDistanceLow - 1));\n            ballFallSpeed = -(slotOffset / sRouletteTables[sRoulette->tableId].shroomish.fallSlowdown);\n        }\n        else\n        {\n            return;\n        }\n        break;\n    default:\n        return;\n    }\n    sRoulette->varA0 = sRoulette->ballDistToCenter;\n    sRoulette->ballFallSpeed = ballFallSpeed;\n    sRoulette->ballFallAccel = -((ballFallSpeed * 2.0f) / ballFallDist + (2.0f / (ballFallDist * ballFallDist)));\n    sRoulette->ballAngleSpeed = 0.0f;\n    sprite->animPaused = FALSE;\n    sprite->animNum = 0;\n    sprite->animBeginning = TRUE;\n    sprite->animEnded = FALSE;\n    sprite->callback = SpriteCB_UnstickBall_ShroomishBallFall;\n    sprite->data[2] = 0;",
  },
  "SpriteCB_UnstickBall_TaillowDrop": {
    callsTo: ["LandBall"],
    lineCount: 7,
    bodyC: "sprite->y2 = (s16)(sprite->data[2] * 0.05f * sprite->data[2]) - 45;\n    sprite->data[2]++;\n    if (sprite->data[2] >= DEGREES_PER_SLOT && sprite->y2 >= 0)\n    {\n        LandBall()\n        sRoulette->ballUnstuck = TRUE;\n    }",
  },
  "SpriteCB_UnstickBall_TaillowPickUp": {
    callsTo: ["m4aSongNumStart"],
    spriteTransitions: ["SpriteCB_UnstickBall_TaillowDrop"],
    lineCount: 32,
    bodyC: "if (sprite->data[2]++ < 45)\n    {\n        sprite->y2--;\n        if (sprite->data[2] == 45)\n        {\n            if (gSprites[sRoulette->spriteIds[SPR_CLEAR_MON]].animCmdIndex == 1)\n                sprite->y2++;\n        }\n    }\n    else\n    {\n        if (sprite->data[2] < sprite->data[7])\n        {\n            if (gSprites[sRoulette->spriteIds[SPR_CLEAR_MON]].animDelayCounter == 0)\n            {\n                if (gSprites[sRoulette->spriteIds[SPR_CLEAR_MON]].animCmdIndex == 1)\n                    sprite->y2++;\n                else\n                    sprite->y2--;\n            }\n        }\n        else\n        {\n            sprite->animPaused = FALSE;\n            sprite->animNum = 1;\n            sprite->animBeginning = TRUE;\n            sprite->animEnded = FALSE;\n            sprite->data[2] = 0;\n            sprite->callback = SpriteCB_UnstickBall_TaillowDrop;\n            m4aSongNumStart(SE_BALL_THROW);\n        }\n    }",
  },
  "SpriteCB_UnstickBall_Taillow": {
    callsTo: ["UpdateBallPos"],
    spriteTransitions: ["SpriteCB_UnstickBall_TaillowPickUp"],
    lineCount: 18,
    bodyC: "UpdateBallPos(sprite);\n\n    switch (sprite->sBallAngle)\n    {\n    case 90:\n        if (sprite->sStuckOnWheelLeft != TRUE)\n        {\n            sprite->callback = &SpriteCB_UnstickBall_TaillowPickUp;\n            sprite->data[2] = 0;\n        }\n        break;\n    case 270:\n        if (sprite->sStuckOnWheelLeft)\n        {\n            sprite->callback = &SpriteCB_UnstickBall_TaillowPickUp;\n            sprite->data[2] = 0;\n        }\n        break;\n    }",
  },
  "SpriteCB_UnstickBall": {
    callsTo: ["CreateShroomishSprite","CreateTaillowSprite","UpdateBallPos"],
    spriteTransitions: ["SpriteCB_UnstickBall_Shroomish","SpriteCB_UnstickBall_Taillow"],
    lineCount: 13,
    bodyC: "UpdateBallPos(sprite);\n    switch (sRoulette->useTaillow)\n    {\n    default:\n    case FALSE:\n        CreateShroomishSprite(sprite);\n        sprite->callback = SpriteCB_UnstickBall_Shroomish;\n        break;\n    case TRUE:\n        CreateTaillowSprite(sprite);\n        sprite->callback = SpriteCB_UnstickBall_Taillow;\n        break;\n    }",
  },
  "SpriteCB_RollBall_TryLandAdjacent": {
    callsTo: ["LandBall","SetBallStuck","UpdateBallPos","m4aSongNumStart"],
    lineCount: 16,
    bodyC: "UpdateBallPos(sprite);\n\n    if (sprite->data[2]-- == 16)\n        sRoulette->ballFallSpeed *= -1.0f;\n\n    if (sprite->data[2] == 0)\n    {\n        if (!sprite->sStillStuck)\n        {\n             \n            LandBall()\n        }\n        else\n        {\n             \n            sprite->animPaused = TRUE;\n            m4aSongNumStart(SE_BALL_BOUNCE_1);\n            SetBallStuck(sprite);\n        }\n    }",
  },
  "SpriteCB_RollBall_TryLand": {
    callsTo: ["LandBall","Random","UpdateBallPos","UpdateSlotBelowBall","m4aSongNumStart"],
    spriteTransitions: ["SpriteCB_RollBall_TryLandAdjacent"],
    lineCount: 50,
    bodyC: "UpdateBallPos(sprite);\n    sprite->data[2] = 0;\n    UpdateSlotBelowBall(sprite);\n    if (!(sRouletteSlots[sRoulette->hitSlot].flag & sRoulette->hitFlags))\n    {\n         \n        LandBall()\n    }\n    else\n    {\n         \n        u8 slotId;\n        u32 fallRight;\n        m4aSongNumStart(SE_BALL_BOUNCE_1);\n        fallRight = Random() & 1;\n        if (fallRight)\n        {\n            sRoulette->ballAngleSpeed = 0.0f;\n            sRoulette->stuckHitSlot = slotId = (sRoulette->hitSlot + 1) % NUM_ROULETTE_SLOTS;\n        }\n        else  \n        {\n            f32 temp;\n            sRoulette->ballAngleSpeed = (temp = sRouletteTables[sRoulette->tableId].var1C) * 2.0f;\n            slotId = (sRoulette->hitSlot + NUM_ROULETTE_SLOTS - 1) % NUM_ROULETTE_SLOTS;\n            sRoulette->stuckHitSlot = sRoulette->hitSlot;\n        }\n        if (sRouletteSlots[slotId].flag & sRoulette->hitFlags)\n        {\n             \n            sprite->sStillStuck = TRUE;\n            sprite->data[2] = sRouletteTables[sRoulette->tableId].randDistanceLow;\n        }\n        else\n        {\n            sprite->sStillStuck = FALSE;\n            if (sRoulette->tableId)\n            {\n                sprite->data[2] = sRouletteTables[sRoulette->tableId].randDistanceHigh;\n            }\n            else\n            {\n                sprite->data[2] = sRouletteTables[sRoulette->tableId].randDistanceLow;\n                if (fallRight)\n                    sRoulette->ballAngleSpeed = 0.5f;\n                else\n                    sRoulette->ballAngleSpeed = -1.5f;\n            }\n        }\n        sRoulette->ballFallSpeed = 0.085f;\n        sprite->callback = SpriteCB_RollBall_TryLandAdjacent;\n        sprite->sState = 5;\n    }",
  },
  "SpriteCB_RollBall_Slow": {
    callsTo: ["GetBallDistanceToSlotMidpoint","UpdateBallPos","UpdateSlotBelowBall"],
    spriteTransitions: ["SpriteCB_RollBall_TryLand"],
    lineCount: 24,
    bodyC: "UpdateBallPos(sprite);\n    if (sRoulette->ballAngleSpeed > 0.5f)\n        return;\n\n    UpdateSlotBelowBall(sprite);\n    if (GetBallDistanceToSlotMidpoint(sprite) == 0)\n    {\n         \n        sRoulette->ballAngleAccel = 0.0f;\n        sRoulette->ballAngleSpeed -= (f32)(sRouletteTables[sRoulette->tableId].wheelSpeed)\n            / (sRouletteTables[sRoulette->tableId].wheelDelay + 1);\n        sprite->sState = 4;\n        sprite->callback = SpriteCB_RollBall_TryLand;\n    }\n    else\n    {\n        if (sRoulette->ballAngleAccel != 0.0f)\n        {\n            if (sRoulette->ballAngleSpeed < 0.0f)\n            {\n                sRoulette->ballAngleAccel = 0.0f;\n                sRoulette->ballAngleSpeed = 0.0f;\n                sRoulette->ballFallSpeed /= 1.2;\n            }\n        }\n    }",
  },
  "SpriteCB_RollBall_Medium": {
    callsTo: ["UpdateBallPos"],
    spriteTransitions: ["SpriteCB_RollBall_Slow"],
    lineCount: 10,
    bodyC: "UpdateBallPos(sprite);\n    if (sRoulette->ballDistToCenter > 40.0f)\n        return;\n\n    sRoulette->ballFallSpeed = -(4.0f / (f32)(sRoulette->ballTravelDistSlow));\n    sRoulette->ballAngleAccel = -(sRoulette->ballAngleSpeed / (f32)(sRoulette->ballTravelDistSlow));\n    sprite->animNum = 2;\n    sprite->animBeginning = TRUE;\n    sprite->animEnded = FALSE;\n    sprite->sState = 3;\n    sprite->callback = SpriteCB_RollBall_Slow;",
  },
  "SpriteCB_RollBall_Fast": {
    callsTo: ["UpdateBallPos","m4aSongNumStartOrChange"],
    spriteTransitions: ["SpriteCB_RollBall_Medium"],
    lineCount: 11,
    bodyC: "UpdateBallPos(sprite);\n    if (sRoulette->ballDistToCenter > 60.0f)\n        return;\n\n    m4aSongNumStartOrChange(SE_ROULETTE_BALL2);\n    sRoulette->ballFallSpeed = -(20.0f / (f32)(sRoulette->ballTravelDistMed));\n    sRoulette->ballAngleAccel = ((1.0f - sRoulette->ballAngleSpeed) / (f32)(sRoulette->ballTravelDistMed));\n    sprite->animNum = 1;\n    sprite->animBeginning = TRUE;\n    sprite->animEnded = FALSE;\n    sprite->sState = 2;\n    sprite->callback = SpriteCB_RollBall_Medium;",
  },
  "SpriteCB_RollBall_Start": {
    callsTo: ["UpdateBallPos"],
    spriteTransitions: ["SpriteCB_RollBall_Fast"],
    lineCount: 5,
    bodyC: "sprite->sState = 1;\n    sprite->data[2] = 0;\n    UpdateBallPos(sprite);\n    sprite->invisible = FALSE;\n    sprite->callback = SpriteCB_RollBall_Fast;",
  },
  "SpriteCB_ShroomishExit": {
    callsTo: ["DestroySprite"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 12,
    bodyC: "if (sprite->data[1]++ >= sprite->data[3])\n    {\n        sprite->x -= 2;\n        if (sprite->x < -16)\n        {\n            if (!sRoulette->ballUnstuck)\n                sRoulette->ballUnstuck = TRUE;\n            DestroySprite(sprite);\n            sRoulette->shroomishShadowTimer = 0;\n            sRoulette->shroomishShadowAlpha = sShroomishShadowAlphas[0];\n        }\n    }",
  },
  "SpriteCB_ShroomishShakeScreen": {
    callsTo: ["DestroySprite"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 22,
    bodyC: "int screenShakeIdx;\n    u16 screenShakeOffsets[][4] = {\n        {-1, 0, 1, 0},\n        {-2, 0, 2, 0},\n        {-3, 0, 3, 0},\n    };\n\n    if (sprite->data[1]++ < sprite->data[3])\n    {\n        if (sprite->data[1] & 1)\n        {\n             \n            gSpriteCoordOffsetY = screenShakeOffsets[sprite->data[2] / 2][sprite->data[7]];\n            screenShakeIdx = sprite->data[7] + 1;\n            sprite->data[7] = screenShakeIdx - ((screenShakeIdx / 4) * 4);\n        }\n         \n        sprite->invisible ^= 1;\n    }\n    else\n    {\n        gSpriteCoordOffsetY = 0;\n        gSprites[sRoulette->spriteIds[SPR_CLEAR_MON]].animPaused = FALSE;\n        DestroySprite(sprite);\n    }",
  },
  "SpriteCB_ShroomishFall": {
    callsTo: ["ARRAY_COUNT","m4aSongNumStart"],
    spriteTransitions: ["SpriteCB_ShroomishExit"],
    lineCount: 17,
    bodyC: "f32 timer;\n    sprite->data[1]++;\n    timer = sprite->data[1];\n    sprite->y2 = timer * 0.039f * timer;\n    sRoulette->shroomishShadowAlpha = sShroomishShadowAlphas[(sRoulette->shroomishShadowTimer - 1) / 2];\n    if (sRoulette->shroomishShadowTimer < ARRAY_COUNT(sShroomishShadowAlphas) * 2 - 1)\n        sRoulette->shroomishShadowTimer++;\n    if (sprite->data[1] > 60)\n    {\n        sprite->data[1] = 0;\n        sprite->callback = SpriteCB_ShroomishExit;\n        gSprites[sprite->sMonShadowSpriteId].callback  = SpriteCB_ShroomishExit;\n        gSprites[sprite->sMonShadowSpriteId].data[1] = -2;\n        gSprites[sprite->sBallShadowSpriteId].invisible = FALSE;\n        gSprites[sprite->sBallShadowSpriteId].callback  = SpriteCB_ShroomishShakeScreen;\n        m4aSongNumStart(SE_M_STRENGTH);\n    }",
  },
  "SpriteCB_Shroomish": {
    callsTo: ["m4aSongNumStart"],
    spriteTransitions: ["SpriteCallbackDummy"],
    lineCount: 38,
    bodyC: "if (sprite->data[7] == 0)\n    {\n         \n         \n        if (!sRoulette->ball->sStuckOnWheelLeft)\n        {\n            if (sRoulette->ball->sBallAngle != sRouletteTables[sRoulette->tableId].shroomish.startAngle)\n                return;\n        }\n        else\n        {\n            if (sRoulette->ball->sBallAngle != sRouletteTables[sRoulette->tableId].shroomish.startAngle + 180)\n                return;\n        }\n\n        sprite->invisible = FALSE;\n        sprite->data[7]++;\n        m4aSongNumStart(SE_FALL);\n        sRoulette->shroomishShadowTimer = 1;\n        sRoulette->shroomishShadowAlpha = sShroomishShadowAlphas[0];\n    }\n    else\n    {\n        sRoulette->shroomishShadowAlpha = sShroomishShadowAlphas[(sRoulette->shroomishShadowTimer - 1) / 2];\n        if (sRoulette->shroomishShadowTimer < 19)\n            sRoulette->shroomishShadowTimer++;\n\n         \n         \n         \n        if (!sRoulette->ball->sStuckOnWheelLeft)\n        {\n            if (sRoulette->ball->sBallAngle != sRouletteTables[sRoulette->tableId].shroomish.dropAngle)\n                return;\n        }\n        else\n        {\n            if (sRoulette->ball->sBallAngle != sRouletteTables[sRoulette->tableId].shroomish.dropAngle + 180)\n                return;\n        }\n\n        gSprites[sprite->sMonSpriteId].callback  = SpriteCB_ShroomishFall;\n        gSprites[sprite->sMonSpriteId].invisible = FALSE;\n        sprite->callback  = &SpriteCallbackDummy;\n        sprite->data[7] = 0;\n    }",
  },
  "SpriteCB_TaillowShadow_Flash": {
    lineCount: 1,
    bodyC: "sprite->invisible ^= 1;",
  },
  "SpriteCB_Taillow_FlyAway": {
    callsTo: ["DestroySprite","FreeOamMatrix","m4aSongNumStop"],
    spriteTransitions: ["SpriteCallbackDummy"],
    terminalMarkers: ["DestroySprite"],
    lineCount: 14,
    bodyC: "if (sprite->y > -16)\n    {\n        sprite->y--;\n    }\n    else\n    {\n        sprite->callback = SpriteCallbackDummy;\n        sprite->invisible = TRUE;\n        sprite->animPaused = TRUE;\n        m4aSongNumStop(SE_TAILLOW_WING_FLAP);\n        DestroySprite(sprite);\n        FreeOamMatrix(gSprites[sRoulette->spriteIds[SPR_CLEAR_MON_SHADOW_1]].oam.matrixNum);\n        DestroySprite(&gSprites[sRoulette->spriteIds[SPR_CLEAR_MON_SHADOW_1]]);\n    }",
  },
  "SpriteCB_Taillow_PickUpBall": {
    callsTo: ["StartSpriteAnim","m4aSongNumStart"],
    spriteTransitions: ["SpriteCB_Taillow_FlyAway"],
    lineCount: 28,
    bodyC: "if (sprite->data[1] >= 0)\n    {\n        sprite->data[1]--;\n        sprite->y--;\n        if (sprite->data[1] == 0 && sprite->animCmdIndex == 1)\n            sprite->y2++;\n    }\n    else\n    {\n        if (sprite->data[3] >= 0)\n        {\n            sprite->data[3]--;\n            if (sprite->animDelayCounter == 0)\n            {\n                if (sprite->animCmdIndex == 1)\n                    sprite->y2++;\n                else\n                    sprite->y2--;\n            }\n        }\n        else\n        {\n            m4aSongNumStart(SE_FALL);\n            StartSpriteAnim(sprite, sRoulette->ball->sStuckOnWheelLeft + 4);\n            sprite->callback = SpriteCB_Taillow_FlyAway;\n            gSprites[sprite->sMonShadowSpriteId].affineAnimPaused = FALSE;\n        }\n    }",
  },
  "SpriteCB_Taillow_FlyIn": {
    callsTo: ["IsSEPlaying","PlayCry_Normal","StartSpriteAnim","m4aMPlayPanpotControl","m4aSongNumStartOrChange"],
    spriteTransitions: ["SpriteCB_Taillow_PickUpBall"],
    lineCount: 40,
    bodyC: "s8 xMoveOffsets[2] = {-1, 1};\n    s8 yMoveOffsets[][2] = {\n        {2, 0},\n        {2, 0},\n        {2, -1},\n        {2, -1},\n        {2, -1},\n        {2, -1},\n        {2, -2},\n        {2, -2},\n    };\n\n    if (sprite->data[1]-- > 7)\n    {\n        sprite->x += xMoveOffsets[sRoulette->ball->sStuckOnWheelLeft] * 2;\n        if (IsSEPlaying())\n        {\n            s8 pan = -((116 - sprite->x) / 2);\n            m4aMPlayPanpotControl(&gMPlayInfo_SE1, TRACKS_ALL, pan);\n            m4aMPlayPanpotControl(&gMPlayInfo_SE2, TRACKS_ALL, pan);\n        }\n    }\n    else\n    {\n        if (sprite->data[1] >= 0)\n        {\n            sprite->x += xMoveOffsets[sRoulette->ball->sStuckOnWheelLeft] * yMoveOffsets[7 - sprite->data[1]][0];\n            sprite->y += yMoveOffsets[7 - sprite->data[1]][1];\n        }\n        else\n        {\n            m4aSongNumStartOrChange(SE_TAILLOW_WING_FLAP);\n            if (sRoulette->ball->sStuckOnWheelLeft == 0)\n                PlayCry_Normal(SPECIES_TAILLOW, 63);\n            else\n                PlayCry_Normal(SPECIES_TAILLOW, -63);\n            StartSpriteAnim(sprite, sRoulette->ball->sStuckOnWheelLeft + 2);\n            sprite->data[1] = 45;\n            sprite->callback = SpriteCB_Taillow_PickUpBall;\n        }\n    }",
  },
  "SpriteCB_TaillowShadow_FlyIn": {
    spriteTransitions: ["SpriteCB_TaillowShadow_Flash"],
    lineCount: 10,
    bodyC: "s8 moveDir[2] = {-1, 1};\n\n    if (sprite->data[1]-- >= 0)\n    {\n        sprite->x += moveDir[sRoulette->ball->sStuckOnWheelLeft] * 2;\n        gSprites[sprite->sMonShadowSpriteId].invisible ^= 1;\n    }\n    else\n    {\n        sprite->callback = SpriteCB_TaillowShadow_Flash;\n    }",
  },
  "SpriteCB_Taillow": {
    callsTo: ["m4aSongNumStart"],
    lineCount: 27,
    bodyC: "if (sRoulette->ball->sStuckOnWheelLeft == FALSE)\n    {\n        if (sRoulette->ball->sBallAngle == sRouletteTables[sRoulette->tableId].taillow.rightStartAngle + 90)\n        {\n            gSprites[sprite->sMonShadowSpriteId].data[1] = 52;\n            gSprites[sprite->sMonSpriteId].data[1] = 52;\n        }\n        else\n        {\n            return;\n        }\n    }\n    else\n    {\n        if (sRoulette->ball->sBallAngle == sRouletteTables[sRoulette->tableId].taillow.leftStartAngle + 270)\n        {\n            gSprites[sprite->sMonShadowSpriteId].data[1] = 46;\n            gSprites[sprite->sMonSpriteId].data[1] = 46;\n        }\n        else\n        {\n            return;\n        }\n    }\n    gSprites[sprite->sMonShadowSpriteId].callback = SpriteCB_TaillowShadow_FlyIn;\n    gSprites[sprite->sMonSpriteId].callback = SpriteCB_Taillow_FlyIn;\n    m4aSongNumStart(SE_FALL);",
  },
} as const;
