// AUTO-GENERATED from include/metatile_behavior.h by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/include/metatile_behavior.h
// Generated: 2026-04-26

// ─── Enums ───────────────────────────────────────────────────────────────────
export const ENUM_BRIDGE_0 = {
  BRIDGE_TYPE_OCEAN: 0,
  BRIDGE_TYPE_POND_LOW: 1,
  BRIDGE_TYPE_POND_MED: 2,
  BRIDGE_TYPE_POND_HIGH: 3,
} as const;

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'MetatileBehavior_IsATile', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsEncounterTile', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsJumpEast', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsJumpWest', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsJumpNorth', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsJumpSouth', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPokeGrass', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSandOrDeepSand', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsDeepSand', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsReflective', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsIce', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsWarpDoor', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsDoor', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsEscalator', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsLadder', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsNonAnimDoor', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsDeepSouthWarp', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSurfableWaterOrUnderwater', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsEastArrowWarp', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsWestArrowWarp', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsNorthArrowWarp', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSouthArrowWarp', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsForcedMovementTile', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsIce_2', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsTrickHouseSlipperyFloor', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsWalkNorth', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsWalkSouth', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsWalkWest', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsWalkEast', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsNorthwardCurrent', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSouthwardCurrent', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsWestwardCurrent', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsEastwardCurrent', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSlideNorth', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSlideSouth', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSlideWest', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSlideEast', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsCounter', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPlayerFacingTVScreen', ret: "bool8", arity: 2, params: "u8 metatileBehavior, u8 playerDir" },
  { name: 'MetatileBehavior_IsPC', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsCableBoxResults1', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsOpenSecretBaseDoor', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseCave', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseTree', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseShrub', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBasePC', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsRecordMixingSecretBasePC', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseTrainerSpot', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseImpassable', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseDecorationBase', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBasePoster', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsNormal', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseNorthWall', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_HoldsSmallDecoration', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_HoldsLargeDecoration', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseHole', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseBalloon', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseBreakableDoor', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseSoundMat', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseGlitterMat', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseSandOrnament', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseShieldOrToyTV', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPlayerRoomPCOn', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_HasRipples', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPuddle', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsTallGrass', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsLongGrass', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsBerryTreeSoil', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsAshGrass', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsFootprints', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsBridgeOverWater', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_GetBridgeType', ret: "u8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsBridgeOverWaterNoEdge', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsLandWildEncounter', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsWaterWildEncounter', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsIndoorEncounter', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsMountain', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsDiveable', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsUnableToEmerge', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsShallowFlowingWater', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsThinIce', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsCrackedIce', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsDeepOrOceanWater', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSurfableAndNotWaterfall', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsEastBlocked', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsWestBlocked', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsNorthBlocked', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSouthBlocked', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsShortGrass', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsHotSprings', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsWaterfall', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsFortreeBridge', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPacifidlogVerticalLogTop', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPacifidlogVerticalLogBottom', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPacifidlogHorizontalLogLeft', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPacifidlogHorizontalLogRight', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPacifidlogLog', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsTrickHousePuzzleDoor', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsRegionMap', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsClosedSootopolisDoor', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSkyPillarClosedDoor', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsRoulette', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPokeblockFeeder', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseJumpMat', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSecretBaseSpinMat', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsLavaridgeB1FWarp', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsLavaridge1FWarp', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsAquaHideoutWarp', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsUnionRoomWarp', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsMossdeepGymWarp', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSurfableFishableWater', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsMtPyreHole', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsCrackedFloorHole', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsCrackedFloor', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsMuddySlope', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsBumpySlope', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsIsolatedVerticalRail', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsIsolatedHorizontalRail', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsVerticalRail', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsHorizontalRail', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsSeaweed', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsRunningDisallowed', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsCuttableGrass', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsRunningShoesManual', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPictureBookShelf', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsBookShelf', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPokeCenterBookShelf', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsVase', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsTrashCan', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsShopShelf', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsBlueprint', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsBattlePyramidWarp', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsPlayerFacingWirelessBoxResults', ret: "bool8", arity: 2, params: "u8 tile, u8 playerDir" },
  { name: 'MetatileBehavior_IsCableBoxResults2', ret: "bool8", arity: 2, params: "u8 tile, u8 playerDir" },
  { name: 'MetatileBehavior_IsQuestionnaire', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsLongGrass_Duplicate', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsLongGrassSouthEdge', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
  { name: 'MetatileBehavior_IsTrainerHillTimer', ret: "bool8", arity: 1, params: "u8 metatileBehavior" },
] as const;
