// AUTO-GENERATED from sound\voicegroups\drumsets\frlg_fanfare_2.inc by extract-voicegroups-m4a.mjs
// Generated: 2026-04-27
import type { VoiceGroup } from '../voice-types';

export const VOICEGROUP: VoiceGroup = {
  name: "frlg_fanfare_drumset_2",
  voices: [
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound_no_resample","baseKey":64,"pan":64,"sampleSymbol":"DirectSoundWaveData_sc88pro_jingle_bell","envelope":{"attack":255,"decay":0,"sustain":255,"release":0}},
  ] as VoiceGroup['voices'],
};
