// AUTO-GENERATED from sound\voicegroups\drumsets\frlg.inc by extract-voicegroups-m4a.mjs
// Generated: 2026-04-27
import type { VoiceGroup } from '../voice-types';

export const VOICEGROUP: VoiceGroup = {
  name: "frlg_drumset",
  voices: [
    {"type":"directsound_no_resample","baseKey":64,"pan":64,"sampleSymbol":"DirectSoundWaveData_drum_and_percussion_kick","envelope":{"attack":255,"decay":0,"sustain":255,"release":0}},
    {"type":"directsound_no_resample","baseKey":64,"pan":64,"sampleSymbol":"DirectSoundWaveData_sd90_solo_snare","envelope":{"attack":255,"decay":180,"sustain":175,"release":228}},
    {"type":"directsound_no_resample","baseKey":64,"pan":64,"sampleSymbol":"DirectSoundWaveData_sd90_solo_snare","envelope":{"attack":255,"decay":0,"sustain":255,"release":242}},
    {"type":"directsound_no_resample","baseKey":64,"pan":54,"sampleSymbol":"DirectSoundWaveData_sc88pro_tr909_hand_clap","envelope":{"attack":255,"decay":255,"sustain":255,"release":127}},
    {"type":"directsound_no_resample","baseKey":64,"pan":64,"sampleSymbol":"DirectSoundWaveData_sc88pro_orchestra_snare","envelope":{"attack":255,"decay":0,"sustain":255,"release":242}},
    {"type":"directsound","baseKey":64,"pan":24,"sampleSymbol":"DirectSoundWaveData_sd90_ambient_tom","envelope":{"attack":255,"decay":0,"sustain":255,"release":226}},
    {"type":"directsound_no_resample","baseKey":64,"pan":80,"sampleSymbol":"DirectSoundWaveData_sc88pro_orchestra_snare","envelope":{"attack":255,"decay":0,"sustain":255,"release":242}},
    {"type":"directsound","baseKey":68,"pan":34,"sampleSymbol":"DirectSoundWaveData_sd90_ambient_tom","envelope":{"attack":255,"decay":0,"sustain":255,"release":226}},
    {"type":"directsound_no_resample","baseKey":60,"pan":64,"sampleSymbol":"DirectSoundWaveData_sc88pro_rnd_snare","envelope":{"attack":255,"decay":0,"sustain":255,"release":242}},
    {"type":"directsound","baseKey":72,"pan":44,"sampleSymbol":"DirectSoundWaveData_sd90_ambient_tom","envelope":{"attack":255,"decay":0,"sustain":255,"release":226}},
    {"type":"directsound_no_resample","baseKey":60,"pan":64,"sampleSymbol":"DirectSoundWaveData_sc88pro_rnd_snare","envelope":{"attack":255,"decay":0,"sustain":255,"release":242}},
    {"type":"directsound","baseKey":76,"pan":84,"sampleSymbol":"DirectSoundWaveData_sd90_ambient_tom","envelope":{"attack":255,"decay":0,"sustain":255,"release":226}},
    {"type":"directsound","baseKey":80,"pan":94,"sampleSymbol":"DirectSoundWaveData_sd90_ambient_tom","envelope":{"attack":255,"decay":0,"sustain":255,"release":226}},
    {"type":"directsound_no_resample","baseKey":33,"pan":89,"sampleSymbol":"DirectSoundWaveData_sc88pro_orchestra_cymbal_crash","envelope":{"attack":255,"decay":235,"sustain":0,"release":231}},
    {"type":"directsound","baseKey":84,"pan":104,"sampleSymbol":"DirectSoundWaveData_sd90_ambient_tom","envelope":{"attack":255,"decay":0,"sustain":255,"release":235}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound","baseKey":63,"pan":64,"sampleSymbol":"DirectSoundWaveData_sc88pro_orchestra_cymbal_crash","envelope":{"attack":255,"decay":235,"sustain":0,"release":231}},
    {"type":"directsound_no_resample","baseKey":64,"pan":24,"sampleSymbol":"DirectSoundWaveData_dance_drums_ride_bell","envelope":{"attack":255,"decay":165,"sustain":103,"release":231}},
    {"type":"directsound_no_resample","baseKey":64,"pan":34,"sampleSymbol":"DirectSoundWaveData_sc88pro_tambourine","envelope":{"attack":255,"decay":127,"sustain":77,"release":204}},
    {"type":"directsound_no_resample","baseKey":64,"pan":14,"sampleSymbol":"DirectSoundWaveData_trinity_cymbal_crash","envelope":{"attack":255,"decay":231,"sustain":0,"release":188}},
    {"type":"directsound_no_resample","baseKey":64,"pan":89,"sampleSymbol":"DirectSoundWaveData_sd90_cowbell","envelope":{"attack":255,"decay":0,"sustain":255,"release":242}},
    {"type":"directsound_no_resample","baseKey":64,"pan":29,"sampleSymbol":"DirectSoundWaveData_sc88pro_orchestra_cymbal_crash","envelope":{"attack":255,"decay":235,"sustain":0,"release":231}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound_no_resample","baseKey":64,"pan":54,"sampleSymbol":"DirectSoundWaveData_sc88pro_orchestra_cymbal_crash","envelope":{"attack":255,"decay":235,"sustain":0,"release":231}},
    {"type":"directsound_no_resample","baseKey":64,"pan":54,"sampleSymbol":"DirectSoundWaveData_sc88pro_orchestra_cymbal_crash","envelope":{"attack":8,"decay":0,"sustain":255,"release":216}},
    {"type":"directsound_no_resample","baseKey":64,"pan":94,"sampleSymbol":"DirectSoundWaveData_unused_heart_of_asia_indian_drum","envelope":{"attack":255,"decay":0,"sustain":255,"release":0}},
    {"type":"directsound_no_resample","baseKey":64,"pan":34,"sampleSymbol":"DirectSoundWaveData_sc88pro_mute_high_conga","envelope":{"attack":255,"decay":0,"sustain":255,"release":0}},
    {"type":"directsound_no_resample","baseKey":64,"pan":34,"sampleSymbol":"DirectSoundWaveData_sc88pro_open_low_conga","envelope":{"attack":255,"decay":0,"sustain":255,"release":0}},
    {"type":"directsound_no_resample","baseKey":64,"pan":90,"sampleSymbol":"DirectSoundWaveData_sc88pro_open_low_conga","envelope":{"attack":255,"decay":0,"sustain":255,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound_no_resample","baseKey":64,"pan":39,"sampleSymbol":"DirectSoundWaveData_sd90_open_triangle","envelope":{"attack":255,"decay":242,"sustain":103,"release":188}},
    {"type":"directsound_no_resample","baseKey":64,"pan":79,"sampleSymbol":"DirectSoundWaveData_sd90_open_triangle","envelope":{"attack":255,"decay":242,"sustain":103,"release":188}},
    {"type":"directsound_no_resample","baseKey":64,"pan":39,"sampleSymbol":"DirectSoundWaveData_sd90_open_triangle","envelope":{"attack":255,"decay":165,"sustain":103,"release":188}},
    {"type":"directsound_no_resample","baseKey":64,"pan":24,"sampleSymbol":"DirectSoundWaveData_sc88pro_jingle_bell","envelope":{"attack":255,"decay":0,"sustain":255,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound_no_resample","baseKey":64,"pan":104,"sampleSymbol":"DirectSoundWaveData_ethnic_flavours_atarigane","envelope":{"attack":255,"decay":0,"sustain":255,"release":0}},
    {"type":"directsound","baseKey":63,"pan":64,"sampleSymbol":"DirectSoundWaveData_sc88pro_taiko","envelope":{"attack":255,"decay":0,"sustain":255,"release":0}},
    {"type":"directsound","baseKey":50,"pan":84,"sampleSymbol":"DirectSoundWaveData_ethnic_flavours_kotsuzumi","envelope":{"attack":255,"decay":0,"sustain":255,"release":0}},
    {"type":"directsound","baseKey":64,"pan":84,"sampleSymbol":"DirectSoundWaveData_ethnic_flavours_kotsuzumi","envelope":{"attack":255,"decay":0,"sustain":255,"release":0}},
  ] as VoiceGroup['voices'],
};
