// AUTO-GENERATED from sound\voicegroups\route119.inc by extract-voicegroups-m4a.mjs
// Generated: 2026-04-26
import type { VoiceGroup } from '../voice-types';

export const VOICEGROUP: VoiceGroup = {
  name: "route119",
  voices: [
    {"type":"keysplit_all","subVoicegroupName":"voicegroup_rs_drumset"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1_alt","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":0,"length":2,"envelope":{"attack":0,"decay":7,"sustain":3,"release":3}},
    {"type":"square_1_alt","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":0,"length":2,"envelope":{"attack":0,"decay":1,"sustain":4,"release":1}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound","baseKey":60,"pan":0,"sampleSymbol":"DirectSoundWaveData_sc88pro_glockenspiel","envelope":{"attack":255,"decay":204,"sustain":51,"release":242}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound","baseKey":60,"pan":0,"sampleSymbol":"DirectSoundWaveData_sc88pro_harp","envelope":{"attack":255,"decay":242,"sustain":0,"release":242}},
    {"type":"directsound","baseKey":60,"pan":0,"sampleSymbol":"DirectSoundWaveData_sc88pro_timpani","envelope":{"attack":255,"decay":0,"sustain":193,"release":239}},
    {"type":"keysplit","subVoicegroupName":"voicegroup_strings_keysplit","splitTableSymbol":"keysplit_strings"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"keysplit","subVoicegroupName":"voicegroup_trumpet_keysplit","splitTableSymbol":"keysplit_trumpet"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"keysplit","subVoicegroupName":"voicegroup_tuba_keysplit","splitTableSymbol":"keysplit_tuba"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"keysplit","subVoicegroupName":"voicegroup_french_horn_keysplit","splitTableSymbol":"keysplit_french_horn"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"unknown","raw":"60, 0, ProgrammableWaveData_2, 0, 7, 15, 0"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_2_alt","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":3,"length":0,"envelope":{"attack":4,"decay":4,"sustain":0,"release":0}},
    {"type":"square_1_alt","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":0,"length":3,"envelope":{"attack":0,"decay":3,"sustain":6,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1_alt","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":0,"length":0,"envelope":{"attack":0,"decay":3,"sustain":3,"release":0}},
    {"type":"unknown","raw":"60, 0, ProgrammableWaveData_6, 0, 7, 12, 1"},
    {"type":"square_2_alt","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":1,"length":0,"envelope":{"attack":1,"decay":4,"sustain":3,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_2_alt","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":0,"length":0,"envelope":{"attack":2,"decay":4,"sustain":0,"release":0}},
  ] as VoiceGroup['voices'],
};
