// AUTO-GENERATED from sound\voicegroups\vs_aqua_magma.inc by extract-voicegroups-m4a.mjs
// Generated: 2026-04-27
import type { VoiceGroup } from '../voice-types';

export const VOICEGROUP: VoiceGroup = {
  name: "vs_aqua_magma",
  voices: [
    {"type":"keysplit_all","subVoicegroupName":"voicegroup_rs_drumset"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_2","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":0,"length":0,"envelope":{"attack":1,"decay":7,"sustain":1,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":0,"length":0,"envelope":{"attack":1,"decay":7,"sustain":1,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound","baseKey":60,"pan":0,"sampleSymbol":"DirectSoundWaveData_sc88pro_tubular_bell","envelope":{"attack":255,"decay":250,"sustain":0,"release":242}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound","baseKey":60,"pan":0,"sampleSymbol":"DirectSoundWaveData_sc88pro_organ2","envelope":{"attack":255,"decay":0,"sustain":255,"release":127}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound","baseKey":60,"pan":0,"sampleSymbol":"DirectSoundWaveData_sc88pro_accordion","envelope":{"attack":255,"decay":0,"sustain":255,"release":165}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound","baseKey":60,"pan":0,"sampleSymbol":"DirectSoundWaveData_sc88pro_fingered_bass","envelope":{"attack":255,"decay":253,"sustain":0,"release":149}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound","baseKey":60,"pan":0,"sampleSymbol":"DirectSoundWaveData_sc88pro_synth_bass","envelope":{"attack":255,"decay":252,"sustain":0,"release":115}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound","baseKey":60,"pan":0,"sampleSymbol":"DirectSoundWaveData_sc88pro_harp","envelope":{"attack":255,"decay":246,"sustain":0,"release":235}},
    {"type":"directsound","baseKey":60,"pan":0,"sampleSymbol":"DirectSoundWaveData_sc88pro_timpani","envelope":{"attack":255,"decay":246,"sustain":0,"release":226}},
    {"type":"keysplit","subVoicegroupName":"voicegroup_strings_keysplit","splitTableSymbol":"keysplit_strings"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"keysplit","subVoicegroupName":"voicegroup_tuba_keysplit","splitTableSymbol":"keysplit_tuba"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"keysplit","subVoicegroupName":"voicegroup_french_horn_keysplit","splitTableSymbol":"keysplit_french_horn"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_2","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":1,"decay":7,"sustain":1,"release":0}},
    {"type":"unknown","raw":"60, 0, ProgrammableWaveData_3, 0, 7, 15, 2"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":1,"decay":7,"sustain":1,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"unknown","raw":"60, 0, ProgrammableWaveData_6, 0, 7, 15, 2"},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"square_1","baseKey":60,"panSweep":0,"sweep":0,"squarePattern":2,"length":0,"envelope":{"attack":0,"decay":15,"sustain":0,"release":0}},
    {"type":"directsound","baseKey":60,"pan":0,"sampleSymbol":"DirectSoundWaveData_trinity_big_boned","envelope":{"attack":255,"decay":0,"sustain":255,"release":127}},
  ] as VoiceGroup['voices'],
};
