// AUTO-GENERATED from src/battle_anim_throw.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 78

export const ENGINE_FUNCTIONS = {
  "AnimTask_FlashHealthboxOnLevelUp": {
    returnType: "void",
    params: "u8 taskId",
    lineCount: 3,
    bodyC: "gTasks[taskId].data[10] = gBattleAnimArgs[0];\n    gTasks[taskId].data[11] = gBattleAnimArgs[1];\n    gTasks[taskId].func = AnimTask_FlashHealthboxOnLevelUp_Step;",
  },
  "AnimTask_FlashHealthboxOnLevelUp_Step": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BlendPalette","DestroyAnimVisualTask","IndexOfSpritePaletteTag","OBJ_PLTT_ID","RGB"],
    lineCount: 30,
    bodyC: "u8 paletteNum;\n    u32 paletteOffset, colorOffset;\n\n    gTasks[taskId].data[0]++;\n    if (gTasks[taskId].data[0]++ >= gTasks[taskId].data[11])\n    {\n        gTasks[taskId].data[0] = 0;\n        paletteNum = IndexOfSpritePaletteTag(TAG_HEALTHBOX_PALS_1);\n        colorOffset = gTasks[taskId].data[10] == 0 ? 6 : 2;\n        switch (gTasks[taskId].data[1])\n        {\n        case 0:\n            gTasks[taskId].data[2] += 2;\n            if (gTasks[taskId].data[2] > 16)\n                gTasks[taskId].data[2] = 16;\n\n            paletteOffset = OBJ_PLTT_ID(paletteNum);\n            BlendPalette(paletteOffset + colorOffset, 1, gTasks[taskId].data[2], RGB(20, 27, 31));\n            if (gTasks[taskId].data[2] == 16)\n                gTasks[taskId].data[1]++;\n            break;\n        case 1:\n            gTasks[taskId].data[2] -= 2;\n            if (gTasks[taskId].data[2] < 0)\n                gTasks[taskId].data[2] = 0;\n\n            paletteOffset = OBJ_PLTT_ID(paletteNum);\n            BlendPalette(paletteOffset + colorOffset, 1, gTasks[taskId].data[2], RGB(20, 27, 31));\n            if (gTasks[taskId].data[2] == 0)\n                DestroyAnimVisualTask(taskId);\n            break;\n        }\n    }",
  },
  "AnimTask_FreeBallGfx": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask","FreeBallGfx","ItemIdToBallId"],
    lineCount: 3,
    bodyC: "u8 ballId = ItemIdToBallId(gLastUsedItem);\n    FreeBallGfx(ballId);\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_FreeHealthboxPalsForLevelUp": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask","FreeHealthboxPalsForLevelUp"],
    lineCount: 2,
    bodyC: "FreeHealthboxPalsForLevelUp(gBattleAnimAttacker);\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_FreePokeblockGfx": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask","FreeSpritePaletteByTag","FreeSpriteTilesByTag"],
    lineCount: 3,
    bodyC: "FreeSpriteTilesByTag(ANIM_TAG_POKEBLOCK);\n    FreeSpritePaletteByTag(ANIM_TAG_POKEBLOCK);\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_GetBattlersFromArg": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask"],
    lineCount: 3,
    bodyC: "gBattleAnimAttacker = gBattleSpritesDataPtr->animationData->animArg;\n    gBattleAnimTarget = gBattleSpritesDataPtr->animationData->animArg >> 8;\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_GetTrappedMoveAnimId": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask"],
    lineCount: 11,
    bodyC: "if (gBattleSpritesDataPtr->animationData->animArg == MOVE_FIRE_SPIN)\n        gBattleAnimArgs[0] = TRAP_ANIM_FIRE_SPIN;\n    else if (gBattleSpritesDataPtr->animationData->animArg == MOVE_WHIRLPOOL)\n        gBattleAnimArgs[0] = TRAP_ANIM_WHIRLPOOL;\n    else if (gBattleSpritesDataPtr->animationData->animArg == MOVE_CLAMP)\n        gBattleAnimArgs[0] = TRAP_ANIM_CLAMP;\n    else if (gBattleSpritesDataPtr->animationData->animArg == MOVE_SAND_TOMB)\n        gBattleAnimArgs[0] = TRAP_ANIM_SAND_TOMB;\n    else\n        gBattleAnimArgs[0] = TRAP_ANIM_BIND;\n\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_IsAttackerBehindSubstitute": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask"],
    lineCount: 2,
    bodyC: "gBattleAnimArgs[ARG_RET_ID] = gBattleSpritesDataPtr->battlerData[gBattleAnimAttacker].behindSubstitute;\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_IsBallBlockedByTrainer": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask"],
    lineCount: 5,
    bodyC: "if (gBattleSpritesDataPtr->animationData->ballThrowCaseId == BALL_TRAINER_BLOCK)\n        gBattleAnimArgs[ARG_RET_ID] = -1;\n    else\n        gBattleAnimArgs[ARG_RET_ID] = 0;\n\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_LoadBallGfx": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask","ItemIdToBallId","LoadBallGfx"],
    lineCount: 3,
    bodyC: "u8 ballId = ItemIdToBallId(gLastUsedItem);\n    LoadBallGfx(ballId);\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_LoadHealthboxPalsForLevelUp": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask","LoadHealthboxPalsForLevelUp"],
    lineCount: 3,
    bodyC: "u8 paletteId1, paletteId2;\n    LoadHealthboxPalsForLevelUp(&paletteId1, &paletteId2, gBattleAnimAttacker);\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_LoadPokeblockGfx": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask","IndexOfSpritePaletteTag","LoadCompressedSpritePaletteUsingHeap","LoadCompressedSpriteSheetUsingHeap"],
    lineCount: 5,
    bodyC: "u8 UNUSED paletteIndex;\n\n    LoadCompressedSpriteSheetUsingHeap(&gBattleAnimPicTable[ANIM_TAG_POKEBLOCK - ANIM_SPRITES_START]);\n    LoadCompressedSpritePaletteUsingHeap(&gBattleAnimPaletteTable[ANIM_TAG_POKEBLOCK - ANIM_SPRITES_START]);\n    paletteIndex = IndexOfSpritePaletteTag(ANIM_TAG_POKEBLOCK);\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_SetAttackerTargetLeftPos": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask","GetBattlerAtPosition"],
    lineCount: 12,
    bodyC: "switch (gBattleAnimArgs[0])\n    {\n    case 0:\n        gBattleAnimAttacker = GetBattlerAtPosition(B_POSITION_PLAYER_LEFT);\n        gBattleAnimTarget = GetBattlerAtPosition(B_POSITION_OPPONENT_LEFT);\n        break;\n    case 1:\n        gBattleAnimAttacker = GetBattlerAtPosition(B_POSITION_OPPONENT_LEFT);\n        gBattleAnimTarget = GetBattlerAtPosition(B_POSITION_PLAYER_LEFT);\n        break;\n    }\n\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_SetTargetToEffectBattler": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask"],
    lineCount: 2,
    bodyC: "gBattleAnimTarget = gEffectBattler;\n    DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_SubstituteFadeToInvisible": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["BLDALPHA_BLEND","ClearBehindSubstituteBit","DestroyAnimVisualTask","GetBattlerSpriteBGPriorityRank","RequestDma3Fill","SetGpuReg"],
    lineCount: 28,
    bodyC: "u8 spriteId;\n\n    switch (gTasks[taskId].data[15])\n    {\n    case 0:\n        if (GetBattlerSpriteBGPriorityRank(gBattleAnimAttacker) == B_POSITION_OPPONENT_LEFT)\n            SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_TGT1_BG1 | BLDCNT_EFFECT_BLEND | BLDCNT_TGT2_ALL);\n        else\n            SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_TGT1_BG2 | BLDCNT_EFFECT_BLEND | BLDCNT_TGT2_ALL);\n\n        SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(16, 0));\n        gTasks[taskId].data[15]++;\n        break;\n    case 1:\n        if (gTasks[taskId].data[1]++ > 1)\n        {\n            gTasks[taskId].data[1] = 0;\n            gTasks[taskId].data[0]++;\n            SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(16 - gTasks[taskId].data[0], gTasks[taskId].data[0]));\n            if (gTasks[taskId].data[0] == 16)\n                gTasks[taskId].data[15]++;\n        }\n        break;\n    case 2:\n        spriteId = gBattlerSpriteIds[gBattleAnimAttacker];\n        RequestDma3Fill(0, (void *)OBJ_VRAM0 + gSprites[spriteId].oam.tileNum * TILE_SIZE_4BPP, MON_PIC_SIZE, 1);\n        ClearBehindSubstituteBit(gBattleAnimAttacker);\n        DestroyAnimVisualTask(taskId);\n        break;\n    }",
  },
  "AnimTask_SwapMonSpriteToFromSubstitute": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask","GetBattlerSide","LoadBattleMonGfxAndAnimate"],
    lineCount: 49,
    bodyC: "u8 spriteId;\n    u32 x;\n    u32 done = FALSE;\n\n    spriteId = gBattlerSpriteIds[gBattleAnimAttacker];\n    switch (gTasks[taskId].data[10])\n    {\n    case 0:\n        gTasks[taskId].data[11] = gBattleAnimArgs[0];\n        gTasks[taskId].data[0] += 0x500;\n        if (GetBattlerSide(gBattleAnimAttacker) != B_SIDE_PLAYER)\n            gSprites[spriteId].x2 += gTasks[taskId].data[0] >> 8;\n        else\n            gSprites[spriteId].x2 -= gTasks[taskId].data[0] >> 8;\n\n        gTasks[taskId].data[0] &= 0xFF;\n        x = gSprites[spriteId].x + gSprites[spriteId].x2 + 32;\n        if (x > DISPLAY_WIDTH + 64)\n            gTasks[taskId].data[10]++;\n        break;\n    case 1:\n        LoadBattleMonGfxAndAnimate(gBattleAnimAttacker, gTasks[taskId].data[11], spriteId);\n        gTasks[taskId].data[10]++;\n        break;\n    case 2:\n        gTasks[taskId].data[0] += 0x500;\n        if (GetBattlerSide(gBattleAnimAttacker) != B_SIDE_PLAYER)\n            gSprites[spriteId].x2 -= gTasks[taskId].data[0] >> 8;\n        else\n            gSprites[spriteId].x2 += gTasks[taskId].data[0] >> 8;\n\n        gTasks[taskId].data[0] &= 0xFF;\n        if (GetBattlerSide(gBattleAnimAttacker) != B_SIDE_PLAYER)\n        {\n            if (gSprites[spriteId].x2 <= 0)\n            {\n                gSprites[spriteId].x2 = 0;\n                done = TRUE;\n            }\n        }\n        else\n        {\n            if (gSprites[spriteId].x2 >= 0)\n            {\n                gSprites[spriteId].x2 = 0;\n                done = TRUE;\n            }\n        }\n\n        if (done)\n            DestroyAnimVisualTask(taskId);\n\n        break;\n    }",
  },
  "AnimTask_SwitchOutBallEffect": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["AnimateBallOpenParticles","DestroyAnimVisualTask","GetBattlePalettesMask","GetBattlerSide","GetBattlerSpriteCoord","GetMonData","ItemIdToBallId","LaunchBallFadeMonTask"],
    lineCount: 29,
    bodyC: "u8 spriteId;\n    u16 ball;\n    u8 ballId;\n    u8 x, y;\n    u8 priority, subpriority;\n    u32 selectedPalettes;\n\n    spriteId = gBattlerSpriteIds[gBattleAnimAttacker];\n    if (GetBattlerSide(gBattleAnimAttacker) == B_SIDE_PLAYER)\n        ball = GetMonData(&gPlayerParty[gBattlerPartyIndexes[gBattleAnimAttacker]], MON_DATA_POKEBALL);\n    else\n        ball = GetMonData(&gEnemyParty[gBattlerPartyIndexes[gBattleAnimAttacker]], MON_DATA_POKEBALL);\n\n    ballId = ItemIdToBallId(ball);\n    switch (gTasks[taskId].data[0])\n    {\n    case 0:\n        x = GetBattlerSpriteCoord(gBattleAnimAttacker, BATTLER_COORD_X);\n        y = GetBattlerSpriteCoord(gBattleAnimAttacker, BATTLER_COORD_Y);\n        priority = gSprites[spriteId].oam.priority;\n        subpriority = gSprites[spriteId].subpriority;\n        gTasks[taskId].data[10] = AnimateBallOpenParticles(x, y + 32, priority, subpriority, ballId);\n        selectedPalettes = GetBattlePalettesMask(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE);\n        gTasks[taskId].data[11] = LaunchBallFadeMonTask(FALSE, gBattleAnimAttacker, selectedPalettes, ballId);\n        gTasks[taskId].data[0]++;\n        break;\n    case 1:\n        if (!gTasks[gTasks[taskId].data[10]].isActive && !gTasks[gTasks[taskId].data[11]].isActive)\n            DestroyAnimVisualTask(taskId);\n        break;\n    }",
  },
  "AnimTask_SwitchOutShrinkMon": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask","PrepareBattlerSpriteForRotScale","ResetSpriteRotScale","SetBattlerSpriteYOffsetFromYScale","SetSpriteRotScale"],
    lineCount: 22,
    bodyC: "u8 spriteId;\n\n    spriteId = gBattlerSpriteIds[gBattleAnimAttacker];\n    switch (gTasks[taskId].data[0])\n    {\n    case 0:\n        PrepareBattlerSpriteForRotScale(spriteId, ST_OAM_OBJ_NORMAL);\n        gTasks[taskId].data[10] = 0x100;\n        gTasks[taskId].data[0]++;\n        break;\n    case 1:\n        gTasks[taskId].data[10] += 0x30;\n        SetSpriteRotScale(spriteId, gTasks[taskId].data[10], gTasks[taskId].data[10], 0);\n        SetBattlerSpriteYOffsetFromYScale(spriteId);\n        if (gTasks[taskId].data[10] >= 0x2D0)\n            gTasks[taskId].data[0]++;\n        break;\n    case 2:\n        ResetSpriteRotScale(spriteId);\n        gSprites[spriteId].invisible = TRUE;\n        DestroyAnimVisualTask(taskId);\n        break;\n    }",
  },
  "AnimTask_ThrowBall": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","GetBattlerSpriteCoord","ItemIdToBallId"],
    lineCount: 11,
    bodyC: "u8 ballId;\n    u8 spriteId;\n\n    ballId = ItemIdToBallId(gLastUsedItem);\n    spriteId = CreateSprite(&gBallSpriteTemplates[ballId], 32, 80, 29);\n    gSprites[spriteId].sDuration = 34;\n    gSprites[spriteId].sTargetX = GetBattlerSpriteCoord(gBattleAnimTarget, BATTLER_COORD_X);\n    gSprites[spriteId].sTargetY = GetBattlerSpriteCoord(gBattleAnimTarget, BATTLER_COORD_Y) - 16;\n    gSprites[spriteId].callback = SpriteCB_Ball_Throw;\n    gBattleSpritesDataPtr->animationData->wildMonInvisible = gSprites[gBattlerSpriteIds[gBattleAnimTarget]].invisible;\n    gTasks[taskId].tSpriteId = spriteId;\n    gTasks[taskId].func = AnimTask_ThrowBall_Step;",
  },
  "AnimTask_ThrowBall_StandingTrainer": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","GetBattlerAtPosition","GetBattlerSpriteCoord","GetBattlerSpriteSubpriority","ItemIdToBallId"],
    lineCount: 24,
    bodyC: "s16 x, y;\n    u8 ballId;\n    u8 subpriority;\n    u8 spriteId;\n\n    if (gBattleTypeFlags & BATTLE_TYPE_WALLY_TUTORIAL)\n    {\n        x = 32;\n        y = 11;\n    }\n    else\n    {\n        x = 23;\n        y = 5;\n    }\n\n    ballId = ItemIdToBallId(gLastUsedItem);\n    subpriority = GetBattlerSpriteSubpriority(GetBattlerAtPosition(B_POSITION_OPPONENT_LEFT)) + 1;\n    spriteId = CreateSprite(&gBallSpriteTemplates[ballId], x + 32, y | 80, subpriority);\n    gSprites[spriteId].sDuration = 34;\n    gSprites[spriteId].sTargetX = GetBattlerSpriteCoord(gBattleAnimTarget, BATTLER_COORD_X);\n    gSprites[spriteId].sTargetY = GetBattlerSpriteCoord(gBattleAnimTarget, BATTLER_COORD_Y) - 16;\n    gSprites[spriteId].callback = SpriteCallbackDummy;\n    gSprites[gBattlerSpriteIds[GetBattlerAtPosition(B_POSITION_PLAYER_LEFT)]].callback = SpriteCB_TrainerThrowObject;\n    gTasks[taskId].tSpriteId = spriteId;\n    gTasks[taskId].func = AnimTask_ThrowBall_StandingTrainer_Step;",
  },
  "AnimTask_ThrowBall_StandingTrainer_Step": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateTask","GetBattlerAtPosition","PlaySE12WithPanning"],
    lineCount: 7,
    bodyC: "if (gSprites[gBattlerSpriteIds[GetBattlerAtPosition(B_POSITION_PLAYER_LEFT)]].animCmdIndex == 1)\n    {\n        PlaySE12WithPanning(SE_BALL_THROW, 0);\n        gSprites[gTasks[taskId].tSpriteId].callback = SpriteCB_Ball_Throw;\n        CreateTask(Task_PlayerThrow_Wait, 10);\n        gTasks[taskId].func = AnimTask_ThrowBall_Step;\n    }",
  },
  "AnimTask_ThrowBall_Step": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyAnimVisualTask"],
    lineCount: 3,
    bodyC: "u8 spriteId = gTasks[taskId].tSpriteId;\n    if ((u16)gSprites[spriteId].sDuration == 0xFFFF)\n        DestroyAnimVisualTask(taskId);",
  },
  "AnimTask_UnusedLevelUpHealthBox": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["AnimLoadCompressedBgGfx","AnimLoadCompressedBgTilemap","BG_PLTT_ID","BLDALPHA_BLEND","CreateInvisibleSpriteWithCallback","GetBattleAnimBg1Data","LoadCompressedPalette","SetAnimBgAttribute","SetGpuReg","SetGpuRegBits"],
    lineCount: 40,
    bodyC: "struct BattleAnimBgData animBgData;\n    u8 healthBoxSpriteId;\n    u8 battler;\n    u8 spriteId1, spriteId2, spriteId3, spriteId4;\n\n    battler = gBattleAnimAttacker;\n    gBattle_WIN0H = 0;\n    gBattle_WIN0V = 0;\n    SetGpuReg(REG_OFFSET_WININ, WININ_WIN0_BG_ALL | WININ_WIN0_OBJ | WININ_WIN0_CLR | WININ_WIN1_BG_ALL | WININ_WIN1_OBJ | WININ_WIN1_CLR);\n    SetGpuReg(REG_OFFSET_WINOUT, WINOUT_WIN01_BG0 | WINOUT_WIN01_BG2 | WINOUT_WIN01_BG3 | WINOUT_WIN01_OBJ | WINOUT_WIN01_CLR | WINOUT_WINOBJ_BG_ALL | WINOUT_WINOBJ_OBJ | WINOUT_WINOBJ_CLR);\n    SetGpuRegBits(REG_OFFSET_DISPCNT, DISPCNT_OBJWIN_ON);\n    SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_TGT1_BG1 | BLDCNT_EFFECT_BLEND | BLDCNT_TGT2_ALL);\n    SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(0, 16));\n    SetAnimBgAttribute(1, BG_ANIM_PRIORITY, 0);\n    SetAnimBgAttribute(1, BG_ANIM_SCREEN_SIZE, 0);\n    SetAnimBgAttribute(1, BG_ANIM_AREA_OVERFLOW_MODE, 1);\n    SetAnimBgAttribute(1, BG_ANIM_CHAR_BASE_BLOCK, 1);\n\n    healthBoxSpriteId = gHealthboxSpriteIds[battler];\n    spriteId1 = gSprites[healthBoxSpriteId].oam.affineParam;\n    spriteId2 = gSprites[healthBoxSpriteId].data[5];\n    spriteId3 = CreateInvisibleSpriteWithCallback(SpriteCallbackDummy);\n    spriteId4 = CreateInvisibleSpriteWithCallback(SpriteCallbackDummy);\n    gSprites[healthBoxSpriteId].oam.priority = 1;\n    gSprites[spriteId1].oam.priority = 1;\n    gSprites[spriteId2].oam.priority = 1;\n    gSprites[spriteId3] = gSprites[healthBoxSpriteId];\n    gSprites[spriteId4] = gSprites[spriteId1];\n    gSprites[spriteId3].oam.objMode = ST_OAM_OBJ_WINDOW;\n    gSprites[spriteId4].oam.objMode = ST_OAM_OBJ_WINDOW;\n    gSprites[spriteId3].callback = SpriteCallbackDummy;\n    gSprites[spriteId4].callback = SpriteCallbackDummy;\n\n    GetBattleAnimBg1Data(&animBgData);\n    AnimLoadCompressedBgTilemap(animBgData.bgId, UnusedLevelupAnimationTilemap);\n    AnimLoadCompressedBgGfx(animBgData.bgId, UnusedLevelupAnimationGfx, animBgData.tilesOffset);\n    LoadCompressedPalette(gCureBubblesPal, BG_PLTT_ID(animBgData.paletteId), PLTT_SIZE_4BPP);\n\n    gBattle_BG1_X = -gSprites[spriteId3].x + 32;\n    gBattle_BG1_Y = -gSprites[spriteId3].y - 32;\n    gTasks[taskId].data[1] = 640;\n    gTasks[taskId].data[0] = spriteId3;\n    gTasks[taskId].data[2] = spriteId4;\n    gTasks[taskId].func = AnimTask_UnusedLevelUpHealthBox_Step;",
  },
  "AnimTask_UnusedLevelUpHealthBox_Step": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BLDALPHA_BLEND","DestroyAnimVisualTask","DestroySprite","GetGpuReg","IsContest","ResetBattleAnimBg","SetAnimBgAttribute","SetGpuReg"],
    lineCount: 53,
    bodyC: "u8 spriteId1, spriteId2;\n    u8 battler;\n\n    battler = gBattleAnimAttacker;\n    gTasks[taskId].data[13] += gTasks[taskId].data[1];\n    gBattle_BG1_Y += (u16)gTasks[taskId].data[13] >> 8;\n    gTasks[taskId].data[13] &= 0xFF;\n\n    switch (gTasks[taskId].data[15])\n    {\n    case 0:\n        if (gTasks[taskId].data[11]++ > 1)\n        {\n            gTasks[taskId].data[11] = 0;\n            gTasks[taskId].data[12]++;\n            SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(gTasks[taskId].data[12], 16 - gTasks[taskId].data[12]));\n            if (gTasks[taskId].data[12] == 8)\n                gTasks[taskId].data[15]++;\n        }\n        break;\n    case 1:\n        if (++gTasks[taskId].data[10] == 30)\n            gTasks[taskId].data[15]++;\n        break;\n    case 2:\n        if (gTasks[taskId].data[11]++ > 1)\n        {\n            gTasks[taskId].data[11] = 0;\n            gTasks[taskId].data[12]--;\n            SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(gTasks[taskId].data[12], 16 - gTasks[taskId].data[12]));\n            if (gTasks[taskId].data[12] == 0)\n            {\n                ResetBattleAnimBg(FALSE);\n                gBattle_WIN0H = 0;\n                gBattle_WIN0V = 0;\n                SetGpuReg(REG_OFFSET_WININ, WININ_WIN0_BG_ALL | WININ_WIN0_OBJ | WININ_WIN0_CLR | WININ_WIN1_BG_ALL | WININ_WIN1_OBJ | WININ_WIN1_CLR);\n                SetGpuReg(REG_OFFSET_WINOUT, WINOUT_WIN01_BG_ALL | WINOUT_WIN01_OBJ | WINOUT_WIN01_CLR | WINOUT_WINOBJ_BG_ALL | WINOUT_WINOBJ_OBJ | WINOUT_WINOBJ_CLR);\n                if (!IsContest())\n                    SetAnimBgAttribute(1, BG_ANIM_CHAR_BASE_BLOCK, 0);\n\n                SetGpuReg(REG_OFFSET_DISPCNT, GetGpuReg(REG_OFFSET_DISPCNT) ^ DISPCNT_OBJWIN_ON);\n                SetGpuReg(REG_OFFSET_BLDCNT, 0);\n                SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(0, 0));\n                DestroySprite(&gSprites[gTasks[taskId].data[0]]);\n                DestroySprite(&gSprites[gTasks[taskId].data[2]]);\n                SetAnimBgAttribute(1, BG_ANIM_AREA_OVERFLOW_MODE, 0);\n                spriteId1 = gSprites[gHealthboxSpriteIds[battler]].oam.affineParam;\n                spriteId2 = gSprites[gHealthboxSpriteIds[battler]].data[5];\n                gSprites[gHealthboxSpriteIds[battler]].oam.priority = 1;\n                gSprites[spriteId1].oam.priority = 1;\n                gSprites[spriteId2].oam.priority = 1;\n                DestroyAnimVisualTask(taskId);\n            }\n        }\n        break;\n    }",
  },
  "AnimateBallOpenParticles": {
    returnType: "u8",
    params: "u8 x, u8 y, u8 priority, u8 subpriority, u8 ballId",
    callsTo: ["CreateTask","LoadBallParticleGfx","PlaySE"],
    lineCount: 10,
    bodyC: "u8 taskId;\n\n    LoadBallParticleGfx(ballId);\n    taskId = CreateTask(sBallParticleAnimationFuncs[ballId], 5);\n    gTasks[taskId].data[1] = x;\n    gTasks[taskId].data[2] = y;\n    gTasks[taskId].data[3] = priority;\n    gTasks[taskId].data[4] = subpriority;\n    gTasks[taskId].data[15] = ballId;\n    PlaySE(SE_BALL_OPEN);\n\n    return taskId;",
  },
  "DestroyBallOpenAnimationParticle": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroySprite","DestroySpriteAndFreeResources","FreeSpritePaletteByTag","FreeSpriteTilesByTag","FuncIsActiveTask"],
    lineCount: 33,
    bodyC: "s32 i, j;\n\n    if (!gMain.inBattle)\n    {\n        if (sprite->data[7] == 1)\n            DestroySpriteAndFreeResources(sprite);\n        else\n            DestroySprite(sprite);\n    }\n    else\n    {\n        gBattleSpritesDataPtr->animationData->numBallParticles--;\n        if (gBattleSpritesDataPtr->animationData->numBallParticles == 0)\n        {\n            for (i = 0; i < POKEBALL_COUNT; i++)\n            {\n                if (FuncIsActiveTask(sBallParticleAnimationFuncs[i]) == TRUE)\n                    break;\n            }\n\n            if (i == POKEBALL_COUNT)\n            {\n                for (j = 0; j < POKEBALL_COUNT; j++)\n                {\n                    FreeSpriteTilesByTag(sBallParticleSpriteSheets[j].tag);\n                    FreeSpritePaletteByTag(sBallParticlePalettes[j].tag);\n                }\n            }\n\n            DestroySprite(sprite);\n        }\n        else\n        {\n            DestroySprite(sprite);\n        }\n    }",
  },
  "DestroySpriteAfterOneFrame": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroySprite","FreeSpriteOamMatrix"],
    lineCount: 9,
    bodyC: "if (sprite->sFrame == 0)\n    {\n        sprite->sFrame = -1;\n    }\n    else\n    {\n        FreeSpriteOamMatrix(sprite);\n        DestroySprite(sprite);\n    }",
  },
  "DiveBallOpenParticleAnimation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","DestroyTask","IncrBallParticleCount","StartSpriteAnim"],
    lineCount: 26,
    bodyC: "u8 i;\n    u8 x, y, priority, subpriority, ballId;\n    u8 spriteId;\n\n    ballId = gTasks[taskId].data[15];\n    x = gTasks[taskId].data[1];\n    y = gTasks[taskId].data[2];\n    priority = gTasks[taskId].data[3];\n    subpriority = gTasks[taskId].data[4];\n\n    for (i = 0; i < 8; i++)\n    {\n        spriteId = CreateSprite(&sBallParticleSpriteTemplates[ballId], x, y, subpriority);\n        if (spriteId != MAX_SPRITES)\n        {\n            IncrBallParticleCount();\n            StartSpriteAnim(&gSprites[spriteId], sBallParticleAnimNums[ballId]);\n            gSprites[spriteId].callback = FanOutBallOpenParticles_Step1;\n            gSprites[spriteId].oam.priority = priority;\n            gSprites[spriteId].data[0] = i * 32;\n            gSprites[spriteId].data[4] = 10;\n            gSprites[spriteId].data[5] = 1;\n            gSprites[spriteId].data[6] = 2;\n        }\n    }\n\n    if (!gMain.inBattle)\n        gSprites[spriteId].data[7] = 1;\n\n    DestroyTask(taskId);",
  },
  "FanOutBallOpenParticles_Step1": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["Cos","DestroyBallOpenAnimationParticle","Sin"],
    lineCount: 7,
    bodyC: "sprite->x2 = Sin(sprite->data[0], sprite->data[1]);\n    sprite->y2 = Cos(sprite->data[0], sprite->data[2]);\n    sprite->data[0] = (sprite->data[0] + sprite->data[4]) & 0xFF;\n    sprite->data[1] += sprite->data[5];\n    sprite->data[2] += sprite->data[6];\n    if (++sprite->data[3] == 51)\n        DestroyBallOpenAnimationParticle(sprite);",
  },
  "FreeHealthboxPalsForLevelUp": {
    returnType: "static void",
    params: "u8 battler",
    callsTo: ["FreeSpritePaletteByTag","IndexOfSpritePaletteTag"],
    lineCount: 13,
    bodyC: "u8 healthBoxSpriteId;\n    u8 spriteId1, spriteId2;\n    u8 paletteId1, paletteId2;\n\n    healthBoxSpriteId = gHealthboxSpriteIds[battler];\n    spriteId1 = gSprites[healthBoxSpriteId].oam.affineParam;\n    spriteId2 = gSprites[healthBoxSpriteId].data[5];\n\n    FreeSpritePaletteByTag(TAG_HEALTHBOX_PALS_1);\n    FreeSpritePaletteByTag(TAG_HEALTHBOX_PALS_2);\n    paletteId1 = IndexOfSpritePaletteTag(TAG_HEALTHBOX_PAL);\n    paletteId2 = IndexOfSpritePaletteTag(TAG_HEALTHBAR_PAL);\n    gSprites[healthBoxSpriteId].oam.paletteNum = paletteId1;\n    gSprites[spriteId1].oam.paletteNum = paletteId1;\n    gSprites[spriteId2].oam.paletteNum = paletteId2;",
  },
  "GreatBallOpenParticleAnimation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","DestroyTask","IncrBallParticleCount","StartSpriteAnim"],
    lineCount: 37,
    bodyC: "u8 i;\n    u8 x, y, priority, subpriority, ballId;\n    u8 spriteId;\n\n    if (gTasks[taskId].data[7])\n    {\n        gTasks[taskId].data[7]--;\n    }\n    else\n    {\n        ballId = gTasks[taskId].data[15];\n        x = gTasks[taskId].data[1];\n        y = gTasks[taskId].data[2];\n        priority = gTasks[taskId].data[3];\n        subpriority = gTasks[taskId].data[4];\n\n        for (i = 0; i < 8; i++)\n        {\n            spriteId = CreateSprite(&sBallParticleSpriteTemplates[ballId], x, y, subpriority);\n            if (spriteId != MAX_SPRITES)\n            {\n                IncrBallParticleCount();\n                StartSpriteAnim(&gSprites[spriteId], sBallParticleAnimNums[ballId]);\n                gSprites[spriteId].callback = FanOutBallOpenParticles_Step1;\n                gSprites[spriteId].oam.priority = priority;\n                gSprites[spriteId].data[0] = i * 32;\n                gSprites[spriteId].data[4] = 8;\n                gSprites[spriteId].data[5] = 2;\n                gSprites[spriteId].data[6] = 2;\n            }\n        }\n\n        gTasks[taskId].data[7] = 8;\n        if (++gTasks[taskId].data[0] == 2)\n        {\n            if (!gMain.inBattle)\n                gSprites[spriteId].data[7] = 1;\n\n            DestroyTask(taskId);\n        }\n    }",
  },
  "IncrBallParticleCount": {
    returnType: "static void",
    params: "void",
    lineCount: 2,
    bodyC: "if (gMain.inBattle)\n        gBattleSpritesDataPtr->animationData->numBallParticles++;",
  },
  "ItemIdToBallId": {
    returnType: "u8",
    params: "u16 ballItem",
    lineCount: 28,
    bodyC: "switch (ballItem)\n    {\n    case ITEM_MASTER_BALL:\n        return BALL_MASTER;\n    case ITEM_ULTRA_BALL:\n        return BALL_ULTRA;\n    case ITEM_GREAT_BALL:\n        return BALL_GREAT;\n    case ITEM_SAFARI_BALL:\n        return BALL_SAFARI;\n    case ITEM_NET_BALL:\n        return BALL_NET;\n    case ITEM_DIVE_BALL:\n        return BALL_DIVE;\n    case ITEM_NEST_BALL:\n        return BALL_NEST;\n    case ITEM_REPEAT_BALL:\n        return BALL_REPEAT;\n    case ITEM_TIMER_BALL:\n        return BALL_TIMER;\n    case ITEM_LUXURY_BALL:\n        return BALL_LUXURY;\n    case ITEM_PREMIER_BALL:\n        return BALL_PREMIER;\n    case ITEM_POKE_BALL:\n    default:\n        return BALL_POKE;\n    }",
  },
  "LaunchBallFadeMonTask": {
    returnType: "u8",
    params: "bool8 unfadeLater, u8 spritePalNum, u32 selectedPalettes, u8 ballId",
    callsTo: ["BeginNormalPaletteFade","BlendPalette","CreateTask","OBJ_PLTT_ID"],
    lineCount: 20,
    bodyC: "u8 taskId;\n\n    taskId = CreateTask(Task_FadeMon_ToBallColor, 5);\n    gTasks[taskId].tBallId = ballId;\n    gTasks[taskId].tPalOffset = spritePalNum;\n    gTasks[taskId].tPaletteLo = selectedPalettes;\n    gTasks[taskId].tPaletteHi = selectedPalettes >> 16;\n\n    if (!unfadeLater)\n    {\n        BlendPalette(OBJ_PLTT_ID(spritePalNum), 16, 0, gBallOpenFadeColors[ballId]);\n        gTasks[taskId].tdCoeff = 1;\n    }\n    else\n    {\n        BlendPalette(OBJ_PLTT_ID(spritePalNum), 16, 16, gBallOpenFadeColors[ballId]);\n        gTasks[taskId].tCoeff = 16;\n        gTasks[taskId].tdCoeff = -1;\n        gTasks[taskId].func = Task_FadeMon_ToNormal;\n    }\n\n    BeginNormalPaletteFade(selectedPalettes, 0, 0, 16, RGB_WHITE);\n    return taskId;",
  },
  "LoadBallParticleGfx": {
    returnType: "static void",
    params: "u8 ballId",
    callsTo: ["GetSpriteTileStartByTag","LoadCompressedSpritePaletteUsingHeap","LoadCompressedSpriteSheetUsingHeap"],
    lineCount: 5,
    bodyC: "if (GetSpriteTileStartByTag(sBallParticleSpriteSheets[ballId].tag) == 0xFFFF)\n    {\n        LoadCompressedSpriteSheetUsingHeap(&sBallParticleSpriteSheets[ballId]);\n        LoadCompressedSpritePaletteUsingHeap(&sBallParticlePalettes[ballId]);\n    }",
  },
  "LoadHealthboxPalsForLevelUp": {
    returnType: "static void",
    params: "u8 *paletteId1, u8 *paletteId2, u8 battler",
    callsTo: ["AllocSpritePalette","LoadPalette","OBJ_PLTT_ID"],
    lineCount: 15,
    bodyC: "u8 healthBoxSpriteId;\n    u8 spriteId1, spriteId2;\n    u16 offset1, offset2;\n\n    healthBoxSpriteId = gHealthboxSpriteIds[battler];\n    spriteId1 = gSprites[healthBoxSpriteId].oam.affineParam;\n    spriteId2 = gSprites[healthBoxSpriteId].data[5];\n    *paletteId1 = AllocSpritePalette(TAG_HEALTHBOX_PALS_1);\n    *paletteId2 = AllocSpritePalette(TAG_HEALTHBOX_PALS_2);\n\n    offset1 = OBJ_PLTT_ID(gSprites[healthBoxSpriteId].oam.paletteNum);\n    offset2 = OBJ_PLTT_ID(gSprites[spriteId2].oam.paletteNum);\n    LoadPalette(&gPlttBufferUnfaded[offset1], OBJ_PLTT_ID(*paletteId1), PLTT_SIZE_4BPP);\n    LoadPalette(&gPlttBufferUnfaded[offset2], OBJ_PLTT_ID(*paletteId2), PLTT_SIZE_4BPP);\n\n    gSprites[healthBoxSpriteId].oam.paletteNum = *paletteId1;\n    gSprites[spriteId1].oam.paletteNum = *paletteId1;\n    gSprites[spriteId2].oam.paletteNum = *paletteId2;",
  },
  "MakeCaptureStars": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["ARRAY_COUNT","CreateSprite","InitAnimArcTranslation","LoadBallParticleGfx","StartSpriteAnim"],
    lineCount: 26,
    bodyC: "u32 i;\n    u8 subpriority;\n\n    if (sprite->subpriority)\n    {\n        subpriority = sprite->subpriority - 1;\n    }\n    else\n    {\n        subpriority = 0;\n        sprite->subpriority = 1;\n    }\n\n    LoadBallParticleGfx(BALL_MASTER);\n    for (i = 0; i < ARRAY_COUNT(sCaptureStars); i++)\n    {\n        u8 spriteId = CreateSprite(&sBallParticleSpriteTemplates[BALL_MASTER], sprite->x, sprite->y, subpriority);\n        if (spriteId != MAX_SPRITES)\n        {\n            gSprites[spriteId].sDuration = 24;\n            gSprites[spriteId].sTargetX = sprite->x + sCaptureStars[i].xOffset;\n            gSprites[spriteId].sTargetY = sprite->y + sCaptureStars[i].yOffset;\n            gSprites[spriteId].sAmplitude = sCaptureStars[i].amplitude;\n            InitAnimArcTranslation(&gSprites[spriteId]);\n            gSprites[spriteId].callback = SpriteCB_CaptureStar_Flicker;\n            StartSpriteAnim(&gSprites[spriteId], sBallParticleAnimNums[BALL_MASTER]);\n        }\n    }",
  },
  "MasterBallOpenParticleAnimation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","DestroyTask","IncrBallParticleCount","StartSpriteAnim"],
    lineCount: 37,
    bodyC: "u8 i, j;\n    u8 x, y, priority, subpriority, ballId;\n    u8 spriteId;\n\n    ballId = gTasks[taskId].data[15];\n    x = gTasks[taskId].data[1];\n    y = gTasks[taskId].data[2];\n    priority = gTasks[taskId].data[3];\n    subpriority = gTasks[taskId].data[4];\n\n    for (j = 0; j < 2; j++)\n    {\n        for (i = 0; i < 8; i++)\n        {\n            spriteId = CreateSprite(&sBallParticleSpriteTemplates[ballId], x, y, subpriority);\n            if (spriteId != MAX_SPRITES)\n            {\n                IncrBallParticleCount();\n                StartSpriteAnim(&gSprites[spriteId], sBallParticleAnimNums[ballId]);\n                gSprites[spriteId].callback = FanOutBallOpenParticles_Step1;\n                gSprites[spriteId].oam.priority = priority;\n                gSprites[spriteId].data[0] = i * 32;\n                gSprites[spriteId].data[4] = 8;\n\n                if (j == 0)\n                {\n                    gSprites[spriteId].data[5] = 2;\n                    gSprites[spriteId].data[6] = 1;\n                }\n                else\n                {\n                    gSprites[spriteId].data[5] = 1;\n                    gSprites[spriteId].data[6] = 2;\n                }\n            }\n        }\n    }\n\n    if (!gMain.inBattle)\n        gSprites[spriteId].data[7] = 1;\n\n    DestroyTask(taskId);",
  },
  "PokeBallOpenParticleAnimation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","DestroyTask","IncrBallParticleCount","StartSpriteAnim"],
    lineCount: 33,
    bodyC: "u8 spriteId;\n    u8 x, y;\n    u8 priority, subpriority;\n    u8 ballId;\n    u8 var0;\n\n    ballId = gTasks[taskId].data[15];\n    if (gTasks[taskId].data[0] < 16)\n    {\n        x = gTasks[taskId].data[1];\n        y = gTasks[taskId].data[2];\n        priority = gTasks[taskId].data[3];\n        subpriority = gTasks[taskId].data[4];\n\n        spriteId = CreateSprite(&sBallParticleSpriteTemplates[ballId], x, y, subpriority);\n        if (spriteId != MAX_SPRITES)\n        {\n            IncrBallParticleCount();\n            StartSpriteAnim(&gSprites[spriteId], sBallParticleAnimNums[ballId]);\n            gSprites[spriteId].callback = PokeBallOpenParticleAnimation_Step1;\n            gSprites[spriteId].oam.priority = priority;\n\n            var0 = (u8)gTasks[taskId].data[0];\n            if (var0 >= 8)\n                var0 -= 8;\n\n            gSprites[spriteId].data[0] = var0 * 32;\n        }\n\n        if (gTasks[taskId].data[0] == 15)\n        {\n            if (!gMain.inBattle)\n                gSprites[spriteId].data[7] = 1;\n\n            DestroyTask(taskId);\n            return;\n        }\n    }\n\n    gTasks[taskId].data[0]++;",
  },
  "PokeBallOpenParticleAnimation_Step1": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    lineCount: 4,
    bodyC: "if (sprite->data[1] == 0)\n        sprite->callback = PokeBallOpenParticleAnimation_Step2;\n    else\n        sprite->data[1]--;",
  },
  "PokeBallOpenParticleAnimation_Step2": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["Cos","DestroyBallOpenAnimationParticle","Sin"],
    lineCount: 5,
    bodyC: "sprite->x2 = Sin(sprite->data[0], sprite->data[1]);\n    sprite->y2 = Cos(sprite->data[0], sprite->data[1]);\n    sprite->data[1] += 2;\n    if (sprite->data[1] == 50)\n        DestroyBallOpenAnimationParticle(sprite);",
  },
  "PremierBallOpenParticleAnimation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","DestroyTask","IncrBallParticleCount","StartSpriteAnim"],
    lineCount: 23,
    bodyC: "u8 i;\n    u8 x, y, priority, subpriority, ballId;\n    u8 spriteId;\n\n    ballId = gTasks[taskId].data[15];\n    x = gTasks[taskId].data[1];\n    y = gTasks[taskId].data[2];\n    priority = gTasks[taskId].data[3];\n    subpriority = gTasks[taskId].data[4];\n\n    for (i = 0; i < 8; i++)\n    {\n        spriteId = CreateSprite(&sBallParticleSpriteTemplates[ballId], x, y, subpriority);\n        if (spriteId != MAX_SPRITES)\n        {\n            IncrBallParticleCount();\n            StartSpriteAnim(&gSprites[spriteId], sBallParticleAnimNums[ballId]);\n            gSprites[spriteId].callback = PremierBallOpenParticleAnimation_Step1;\n            gSprites[spriteId].oam.priority = priority;\n            gSprites[spriteId].data[0] = i * 32;\n        }\n    }\n\n    if (!gMain.inBattle)\n        gSprites[spriteId].data[7] = 1;\n\n    DestroyTask(taskId);",
  },
  "PremierBallOpenParticleAnimation_Step1": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["Cos","DestroyBallOpenAnimationParticle","Sin"],
    lineCount: 7,
    bodyC: "sprite->x2 = Sin(sprite->data[0], sprite->data[1]);\n    sprite->y2 = Cos(sprite->data[0], Sin(sprite->data[0] & 0x3F, sprite->data[2]));\n    sprite->data[0] = (sprite->data[0] + 10) & 0xFF;\n    sprite->data[1]++;\n    sprite->data[2]++;\n    if (++sprite->data[3] == 51)\n        DestroyBallOpenAnimationParticle(sprite);",
  },
  "RepeatBallOpenParticleAnimation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","DestroyTask","IncrBallParticleCount","StartSpriteAnim"],
    lineCount: 23,
    bodyC: "u8 i;\n    u8 x, y, priority, subpriority, ballId;\n    u8 spriteId;\n\n    ballId = gTasks[taskId].data[15];\n    x = gTasks[taskId].data[1];\n    y = gTasks[taskId].data[2];\n    priority = gTasks[taskId].data[3];\n    subpriority = gTasks[taskId].data[4];\n\n    for (i = 0; i < POKEBALL_COUNT; i++)\n    {\n        spriteId = CreateSprite(&sBallParticleSpriteTemplates[ballId], x, y, subpriority);\n        if (spriteId != MAX_SPRITES)\n        {\n            IncrBallParticleCount();\n            StartSpriteAnim(&gSprites[spriteId], sBallParticleAnimNums[ballId]);\n            gSprites[spriteId].callback = RepeatBallOpenParticleAnimation_Step1;\n            gSprites[spriteId].oam.priority = priority;\n            gSprites[spriteId].data[0] = i * 21;\n        }\n    }\n\n    if (!gMain.inBattle)\n        gSprites[spriteId].data[7] = 1;\n\n    DestroyTask(taskId);",
  },
  "RepeatBallOpenParticleAnimation_Step1": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["Cos","DestroyBallOpenAnimationParticle","Sin"],
    lineCount: 7,
    bodyC: "sprite->x2 = Sin(sprite->data[0], sprite->data[1]);\n    sprite->y2 = Cos(sprite->data[0], Sin(sprite->data[0], sprite->data[2]));\n    sprite->data[0] = (sprite->data[0] + 6) & 0xFF;\n    sprite->data[1]++;\n    sprite->data[2]++;\n    if (++sprite->data[3] == 51)\n        DestroyBallOpenAnimationParticle(sprite);",
  },
  "SafariBallOpenParticleAnimation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","DestroyTask","IncrBallParticleCount","StartSpriteAnim"],
    lineCount: 26,
    bodyC: "u8 i;\n    u8 x, y, priority, subpriority, ballId;\n    u8 spriteId;\n\n    ballId = gTasks[taskId].data[15];\n    x = gTasks[taskId].data[1];\n    y = gTasks[taskId].data[2];\n    priority = gTasks[taskId].data[3];\n    subpriority = gTasks[taskId].data[4];\n\n    for (i = 0; i < 8; i++)\n    {\n        spriteId = CreateSprite(&sBallParticleSpriteTemplates[ballId], x, y, subpriority);\n        if (spriteId != MAX_SPRITES)\n        {\n            IncrBallParticleCount();\n            StartSpriteAnim(&gSprites[spriteId], sBallParticleAnimNums[ballId]);\n            gSprites[spriteId].callback = FanOutBallOpenParticles_Step1;\n            gSprites[spriteId].oam.priority = priority;\n            gSprites[spriteId].data[0] = i * 32;\n            gSprites[spriteId].data[4] = 4;\n            gSprites[spriteId].data[5] = 1;\n            gSprites[spriteId].data[6] = 1;\n        }\n    }\n\n    if (!gMain.inBattle)\n        gSprites[spriteId].data[7] = 1;\n\n    DestroyTask(taskId);",
  },
  "SpriteCB_Ball_Arc": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["AnimateBallOpenParticles","ItemIdToBallId","LaunchBallFadeMonTask","StartSpriteAnim","TranslateAnimHorizontalArc"],
    lineCount: 29,
    bodyC: "s32 i;\n    u8 ballId;\n\n    if (TranslateAnimHorizontalArc(sprite))\n    {\n        if (gBattleSpritesDataPtr->animationData->ballThrowCaseId == BALL_TRAINER_BLOCK)\n        {\n            sprite->callback = SpriteCB_Ball_Block;\n        }\n        else\n        {\n            StartSpriteAnim(sprite, 1);\n            sprite->x += sprite->x2;\n            sprite->y += sprite->y2;\n            sprite->x2 = 0;\n            sprite->y2 = 0;\n\n            for (i = 0; i < 8; i++)\n                sprite->data[i] = 0;\n\n            sprite->sTimer = 0;\n            sprite->callback = SpriteCB_Ball_MonShrink;\n\n            ballId = ItemIdToBallId(gLastUsedItem);\n            switch (ballId)\n            {\n            case 0 ... POKEBALL_COUNT - 1:\n                AnimateBallOpenParticles(sprite->x, sprite->y - 5, 1, 28, ballId);\n                LaunchBallFadeMonTask(FALSE, gBattleAnimTarget, 14, ballId);\n                break;\n            }\n        }\n    }",
  },
  "SpriteCB_Ball_Block": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    lineCount: 8,
    bodyC: "s32 i;\n\n    sprite->x += sprite->x2;\n    sprite->y += sprite->y2;\n    sprite->y2 = 0;\n    sprite->x2 = 0;\n    for (i = 0; i < 6; i++)\n        sprite->data[i] = 0;\n\n    sprite->callback = SpriteCB_Ball_Block_Step;",
  },
  "SpriteCB_Ball_Block_Step": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["UpdateOamPriorityInAllHealthboxes"],
    lineCount: 14,
    bodyC: "s16 dy = sprite->sDy + 0x800;\n    s16 dx = sprite->sDx + 0x680;\n    sprite->x2 -= dx >> 8;\n    sprite->y2 += dy >> 8;\n    sprite->sDy = (sprite->sDy + 0x800) & 0xFF;\n    sprite->sDx = (sprite->sDx + 0x680) & 0xFF;\n\n    if (sprite->y + sprite->y2 > DISPLAY_HEIGHT\n     || sprite->x + sprite->x2 < -8)\n    {\n        sprite->sFrame = 0;\n        sprite->callback = DestroySpriteAfterOneFrame;\n        gDoingBattleAnim = 0;\n        UpdateOamPriorityInAllHealthboxes(1);\n    }",
  },
  "SpriteCB_Ball_Bounce": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["Cos"],
    lineCount: 11,
    bodyC: "s16 phase;\n\n    if (sprite->animEnded)\n    {\n        sprite->sState = 0;\n        sprite->sAmplitude = 40;\n        sprite->sPhase = 0;\n        phase = 0;\n        sprite->y += Cos(phase, 40);\n        sprite->y2 = -Cos(phase, sprite->sAmplitude);\n        sprite->callback = SpriteCB_Ball_Bounce_Step;\n    }",
  },
  "SpriteCB_Ball_Bounce_Step": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["BOUNCES","Cos","DIRECTION","FALL","PHASE_DELTA","PlaySE","RISE_FASTER"],
    lineCount: 59,
    bodyC: "bool8 lastBounce;\n    s16 bounceCount;\n\n    lastBounce = FALSE;\n\n    switch (DIRECTION(sprite->sState))\n    {\n    case BALL_FALLING:\n        sprite->y2 = -Cos(sprite->sPhase, sprite->sAmplitude);\n        sprite->sPhase += PHASE_DELTA(sprite->sState) + 4;\n         \n        if (sprite->sPhase >= 64)\n        {\n            sprite->sAmplitude -= 10;\n            RISE_FASTER(sprite->sState);\n\n            bounceCount = BOUNCES(sprite->sState);\n            if (bounceCount == 4)\n                lastBounce = TRUE;\n\n            switch (bounceCount)\n            {\n            case 1:\n                PlaySE(SE_BALL_BOUNCE_1);\n                break;\n            case 2:\n                PlaySE(SE_BALL_BOUNCE_2);\n                break;\n            case 3:\n                PlaySE(SE_BALL_BOUNCE_3);\n                break;\n            default:\n                PlaySE(SE_BALL_BOUNCE_4);\n                break;\n            }\n        }\n        break;\n    case BALL_RISING:\n        sprite->y2 = -Cos(sprite->sPhase, sprite->sAmplitude);\n        sprite->sPhase -= PHASE_DELTA(sprite->sState) + 4;\n         \n        if (sprite->sPhase <= 0)\n        {\n             \n            sprite->sPhase = 0;\n            FALL(sprite->sState);\n        }\n        break;\n    }\n\n    if (lastBounce)\n    {\n        sprite->sState = 0;\n        sprite->y += Cos(64, 40);\n        sprite->y2 = 0;\n        if (gBattleSpritesDataPtr->animationData->ballThrowCaseId == BALL_NO_SHAKES)\n        {\n            sprite->sTimer = 0;\n            sprite->callback = SpriteCB_Ball_Release;\n        }\n        else\n        {\n            sprite->callback = SpriteCB_Ball_Wobble;\n            sprite->data[4] = 1;\n            sprite->data[5] = 0;\n        }\n    }",
  },
  "SpriteCB_Ball_Capture": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    lineCount: 5,
    bodyC: "sprite->animPaused = TRUE;\n    sprite->callback = SpriteCB_Ball_Capture_Step;\n    sprite->data[3] = 0;\n    sprite->sTimer = 0;\n    sprite->data[5] = 0;",
  },
  "SpriteCB_Ball_Capture_Step": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["BeginNormalPaletteFade","BlendPalettes","DestroySprite","FreeOamMatrix","MakeCaptureStars","PlaySE","UpdateOamPriorityInAllHealthboxes","m4aMPlayAllStop"],
    lineCount: 26,
    bodyC: "u8 *battler = &gBattleAnimTarget;\n\n    sprite->sTimer++;\n    if (sprite->sTimer == 40)\n    {\n        PlaySE(SE_RG_BALL_CLICK);\n        BlendPalettes(0x10000 << sprite->oam.paletteNum, 6, RGB_BLACK);\n        MakeCaptureStars(sprite);\n    }\n    else if (sprite->sTimer == 60)\n    {\n        BeginNormalPaletteFade(0x10000 << sprite->oam.paletteNum, 2, 6, 0, RGB_BLACK);\n    }\n    else if (sprite->sTimer == 95)\n    {\n        gDoingBattleAnim = FALSE;\n        UpdateOamPriorityInAllHealthboxes(1);\n        m4aMPlayAllStop();\n        PlaySE(MUS_RG_CAUGHT_INTRO);\n    }\n    else if (sprite->sTimer == 315)\n    {\n        FreeOamMatrix(gSprites[gBattlerSpriteIds[*battler]].oam.matrixNum);\n        DestroySprite(&gSprites[gBattlerSpriteIds[*battler]]);\n\n        sprite->sState = 0;\n        sprite->callback = SpriteCB_Ball_FadeOut;\n    }",
  },
  "SpriteCB_Ball_FadeOut": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["BLDALPHA_BLEND","BeginNormalPaletteFade","IndexOfSpritePaletteTag","SetGpuReg"],
    lineCount: 37,
    bodyC: "u8 paletteIndex;\n\n    switch (sprite->sState)\n    {\n    case 0:\n        sprite->data[1] = 0;\n        sprite->data[2] = 0;\n        sprite->oam.objMode = ST_OAM_OBJ_BLEND;\n        SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_EFFECT_BLEND | BLDCNT_TGT2_ALL);\n        SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(16, 0));\n        paletteIndex = IndexOfSpritePaletteTag(sprite->template->paletteTag);\n        BeginNormalPaletteFade(1 << (paletteIndex + 0x10), 0, 0, 16, RGB_WHITE);\n        sprite->sState++;\n        break;\n    case 1:\n        if (sprite->data[1]++ > 0)\n        {\n            sprite->data[1] = 0;\n            sprite->data[2]++;\n            SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(16 - sprite->data[2], sprite->data[2]));\n            if (sprite->data[2] == 16)\n                sprite->sState++;\n        }\n        break;\n    case 2:\n        sprite->invisible = TRUE;\n        sprite->sState++;\n        break;\n    default:\n        if (!gPaletteFade.active)\n        {\n            SetGpuReg(REG_OFFSET_BLDCNT, 0);\n            SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n\n            sprite->sFrame = 0;\n            sprite->callback = DestroySpriteAfterOneFrame;\n        }\n        break;\n    }",
  },
  "SpriteCB_Ball_MonShrink": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["CreateTask"],
    lineCount: 6,
    bodyC: "if (++sprite->sTimer == 10)\n    {\n        sprite->sTaskId = CreateTask(TaskDummy, 50);\n        sprite->callback = SpriteCB_Ball_MonShrink_Step;\n        gSprites[gBattlerSpriteIds[gBattleAnimTarget]].data[1] = 0;\n    }",
  },
  "SpriteCB_Ball_MonShrink_Step": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroyTask","PlaySE","PrepareBattlerSpriteForRotScale","ResetSpriteRotScale","SetSpriteRotScale","StartSpriteAnim"],
    lineCount: 41,
    bodyC: "u8 spriteId;\n    u8 taskId;\n\n    spriteId = gBattlerSpriteIds[gBattleAnimTarget];\n    taskId = sprite->sTaskId;\n\n    if (++gTasks[taskId].sTimer == 11)\n        PlaySE(SE_BALL_TRADE);\n\n    switch (gTasks[taskId].tState)\n    {\n    case MON_SHRINK:\n        PrepareBattlerSpriteForRotScale(spriteId, ST_OAM_OBJ_NORMAL);\n        gTasks[taskId].data[10] = 256;\n        gMonShrinkDuration = 28;\n        gMonShrinkDistance = (gSprites[spriteId].y + gSprites[spriteId].y2) - (sprite->y + sprite->y2);\n        gMonShrinkDelta = (u32)(gMonShrinkDistance * 256) / gMonShrinkDuration;\n        gTasks[taskId].data[2] = gMonShrinkDelta;\n        gTasks[taskId].tState++;  \n        break;\n    case MON_SHRINK_STEP:\n        gTasks[taskId].data[10] += 32;\n        SetSpriteRotScale(spriteId, gTasks[taskId].data[10], gTasks[taskId].data[10], 0);\n        gTasks[taskId].data[3] += gTasks[taskId].data[2];\n        gSprites[spriteId].y2 = -gTasks[taskId].data[3] >> 8;\n        if (gTasks[taskId].data[10] >= 1152)\n            gTasks[taskId].tState++;  \n        break;\n    case MON_SHRINK_INVISIBLE:\n        ResetSpriteRotScale(spriteId);\n        gSprites[spriteId].invisible = TRUE;\n        gTasks[taskId].tState++;  \n        break;\n    case MON_SHRINK_FREE:\n    default:\n        if (gTasks[taskId].data[1] > 10)\n        {\n            DestroyTask(taskId);\n            StartSpriteAnim(sprite, 2);\n            sprite->data[5] = 0;\n            sprite->callback = SpriteCB_Ball_Bounce;\n        }\n        break;\n    }",
  },
  "SpriteCB_Ball_Release": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    lineCount: 5,
    bodyC: "if (++sprite->sTimer == 31)\n    {\n        sprite->data[5] = 0;\n        sprite->callback = SpriteCB_Ball_Release_Step;\n    }",
  },
  "SpriteCB_Ball_Release_Step": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["AnimateBallOpenParticles","AnimateSprite","ItemIdToBallId","LaunchBallFadeMonTask","StartSpriteAffineAnim","StartSpriteAnim"],
    lineCount: 16,
    bodyC: "u8 ballId;\n\n    StartSpriteAnim(sprite, 1);\n    StartSpriteAffineAnim(sprite, 0);\n    sprite->callback = SpriteCB_Ball_Release_Wait;\n\n    ballId = ItemIdToBallId(gLastUsedItem);\n    switch (ballId)\n    {\n    case 0 ... POKEBALL_COUNT - 1:\n        AnimateBallOpenParticles(sprite->x, sprite->y - 5, 1, 28, ballId);\n        LaunchBallFadeMonTask(TRUE, gBattleAnimTarget, 14, ballId);\n        break;\n    }\n\n     \n    gSprites[gBattlerSpriteIds[gBattleAnimTarget]].invisible = FALSE;\n    StartSpriteAffineAnim(&gSprites[gBattlerSpriteIds[gBattleAnimTarget]], BATTLER_AFFINE_EMERGE);\n    AnimateSprite(&gSprites[gBattlerSpriteIds[gBattleAnimTarget]]);\n    gSprites[gBattlerSpriteIds[gBattleAnimTarget]].sOffsetY = 4096;",
  },
  "SpriteCB_Ball_Release_Wait": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["StartSpriteAffineAnim","UpdateOamPriorityInAllHealthboxes"],
    lineCount: 22,
    bodyC: "bool8 released = FALSE;\n\n    if (sprite->animEnded)\n        sprite->invisible = TRUE;\n\n    if (gSprites[gBattlerSpriteIds[gBattleAnimTarget]].affineAnimEnded)\n    {\n        StartSpriteAffineAnim(&gSprites[gBattlerSpriteIds[gBattleAnimTarget]], BATTLER_AFFINE_NORMAL);\n        released = TRUE;\n    }\n    else\n    {\n        gSprites[gBattlerSpriteIds[gBattleAnimTarget]].sOffsetY -= 288;\n        gSprites[gBattlerSpriteIds[gBattleAnimTarget]].y2 = gSprites[gBattlerSpriteIds[gBattleAnimTarget]].sOffsetY >> 8;\n    }\n\n    if (sprite->animEnded && released)\n    {\n        gSprites[gBattlerSpriteIds[gBattleAnimTarget]].y2 = 0;\n        gSprites[gBattlerSpriteIds[gBattleAnimTarget]].invisible = gBattleSpritesDataPtr->animationData->wildMonInvisible;\n        sprite->sFrame = 0;\n        sprite->callback = DestroySpriteAfterOneFrame;\n        gDoingBattleAnim = 0;\n        UpdateOamPriorityInAllHealthboxes(1);\n    }",
  },
  "SpriteCB_Ball_Throw": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["InitAnimArcTranslation"],
    lineCount: 9,
    bodyC: "u16 targetX = sprite->sTargetXArg;\n    u16 targetY = sprite->sTargetYArg;\n\n    sprite->sOffsetX = sprite->x;\n    sprite->sTargetX = targetX;\n    sprite->sOffsetY = sprite->y;\n    sprite->sTargetY = targetY;\n    sprite->sAmplitude = -40;\n    InitAnimArcTranslation(sprite);\n    sprite->callback = SpriteCB_Ball_Arc;",
  },
  "SpriteCB_Ball_Wobble": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["PlaySE","StartSpriteAffineAnim"],
    lineCount: 9,
    bodyC: "if (++sprite->sTimer == 31)\n    {\n        sprite->sState = 0;\n        sprite->affineAnimPaused = TRUE;\n        StartSpriteAffineAnim(sprite, BALL_ROTATE_RIGHT);\n        gBattleSpritesDataPtr->animationData->ballSubpx = 0;\n        sprite->callback = SpriteCB_Ball_Wobble_Step;\n        PlaySE(SE_BALL);\n    }",
  },
  "SpriteCB_Ball_Wobble_Step": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["ChangeSpriteAffineAnim","PlaySE","RESET_STATE","SHAKES","SHAKE_INC","STATE","StartSpriteAffineAnim"],
    lineCount: 133,
    bodyC: "s8 shakes;\n    u16 frame;\n\n    switch (STATE(sprite->sState))\n    {\n    case BALL_ROLL_1:\n         \n        if (gBattleSpritesDataPtr->animationData->ballSubpx > 255)\n        {\n            sprite->x2 += sprite->sDirection;\n            gBattleSpritesDataPtr->animationData->ballSubpx &= 0xFF;\n        }\n        else\n        {\n            gBattleSpritesDataPtr->animationData->ballSubpx += 176;\n        }\n\n        sprite->sTimer++;\n        sprite->affineAnimPaused = FALSE;\n        frame = sprite->sTimer + 7;\n        if (frame > 14)\n        {\n            gBattleSpritesDataPtr->animationData->ballSubpx = 0;\n            sprite->sState++;  \n            sprite->sTimer = 0;\n        }\n        break;\n    case BALL_PIVOT_1:\n        if (++sprite->sTimer == 1)\n        {\n            sprite->sTimer = 0;\n            sprite->sDirection = -sprite->sDirection;\n            sprite->sState++;  \n            sprite->affineAnimPaused = FALSE;\n            if (sprite->sDirection < 0)\n                ChangeSpriteAffineAnim(sprite, BALL_ROTATE_LEFT);\n            else\n                ChangeSpriteAffineAnim(sprite, BALL_ROTATE_RIGHT);\n        }\n        else\n        {\n            sprite->affineAnimPaused = TRUE;\n        }\n        break;\n    case BALL_ROLL_2:\n        if (gBattleSpritesDataPtr->animationData->ballSubpx > 255)\n        {\n            sprite->x2 += sprite->sDirection;\n            gBattleSpritesDataPtr->animationData->ballSubpx &= 0xFF;\n        }\n        else\n        {\n            gBattleSpritesDataPtr->animationData->ballSubpx += 176;\n        }\n\n        sprite->sTimer++;\n        sprite->affineAnimPaused = FALSE;\n        frame = sprite->sTimer + 12;\n        if (frame > 24)\n        {\n            gBattleSpritesDataPtr->animationData->ballSubpx = 0;\n            sprite->sState++;  \n            sprite->sTimer = 0;\n        }\n        break;\n    case BALL_PIVOT_2:\n        if (sprite->sTimer++ < 0)\n        {\n            sprite->affineAnimPaused = TRUE;\n            break;\n        }\n\n        sprite->sTimer = 0;\n        sprite->sDirection = -sprite->sDirection;\n        sprite->sState++;  \n        sprite->affineAnimPaused = FALSE;\n        if (sprite->sDirection < 0)\n            ChangeSpriteAffineAnim(sprite, BALL_ROTATE_LEFT);\n        else\n            ChangeSpriteAffineAnim(sprite, BALL_ROTATE_RIGHT);\n         \n    case BALL_ROLL_3:\n        if (gBattleSpritesDataPtr->animationData->ballSubpx > 0xFF)\n        {\n            sprite->x2 += sprite->sDirection;\n            gBattleSpritesDataPtr->animationData->ballSubpx &= 0xFF;\n        }\n        else\n        {\n            gBattleSpritesDataPtr->animationData->ballSubpx += 176;\n        }\n\n        sprite->sTimer++;\n        sprite->affineAnimPaused = FALSE;\n        frame = sprite->sTimer + 4;\n        if (frame > 8)\n        {\n            gBattleSpritesDataPtr->animationData->ballSubpx = 0;\n            sprite->sState++;  \n            sprite->sTimer = 0;\n            sprite->sDirection = -sprite->sDirection;\n        }\n        break;\n    case BALL_NEXT_MOVE:\n        SHAKE_INC(sprite->sState);\n        shakes = SHAKES(sprite->sState);\n        if (shakes == gBattleSpritesDataPtr->animationData->ballThrowCaseId)\n        {\n            sprite->affineAnimPaused = TRUE;\n            sprite->callback = SpriteCB_Ball_Release;\n        }\n        else\n        {\n            if (gBattleSpritesDataPtr->animationData->ballThrowCaseId == BALL_3_SHAKES_SUCCESS && shakes == 3)\n            {\n                sprite->callback = SpriteCB_Ball_Capture;\n                sprite->affineAnimPaused = TRUE;\n            }\n            else\n            {\n                sprite->sState++;  \n                sprite->affineAnimPaused = TRUE;\n            }\n        }\n        break;\n    case BALL_WAIT_NEXT_SHAKE:\n    default:\n        if (++sprite->sTimer == 31)\n        {\n            sprite->sTimer = 0;\n            RESET_STATE(sprite->sState);\n            StartSpriteAffineAnim(sprite, 3);\n            if (sprite->sDirection < 0)\n                StartSpriteAffineAnim(sprite, BALL_ROTATE_LEFT);\n            else\n                StartSpriteAffineAnim(sprite, BALL_ROTATE_RIGHT);\n\n            PlaySE(SE_BALL);\n        }\n        break;\n    }",
  },
  "SpriteCB_CaptureStar_Flicker": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroySprite","TranslateAnimHorizontalArc"],
    lineCount: 3,
    bodyC: "sprite->invisible = !sprite->invisible;\n    if (TranslateAnimHorizontalArc(sprite))\n        DestroySprite(sprite);",
  },
  "SpriteCB_PokeBlock_Arc": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["TranslateAnimHorizontalArc"],
    lineCount: 6,
    bodyC: "if (TranslateAnimHorizontalArc(sprite))\n    {\n        sprite->data[0] = 0;\n        sprite->invisible = TRUE;\n        sprite->callback = SpriteCB_ThrowPokeBlock_Free;\n    }",
  },
  "SpriteCB_PokeBlock_LiftArm": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    lineCount: 2,
    bodyC: "if (gSprites[gBattlerSpriteIds[gBattleAnimAttacker]].animCmdIndex == 1)\n        sprite->callback = SpriteCB_PokeBlock_Arc;",
  },
  "SpriteCB_PokeBlock_Throw": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["GetBattlerAtPosition","GetBattlerSpriteCoord","InitAnimArcTranslation","InitSpritePosToAnimAttacker"],
    lineCount: 8,
    bodyC: "InitSpritePosToAnimAttacker(sprite, FALSE);\n    sprite->sDuration = 30;\n    sprite->sTargetX = GetBattlerSpriteCoord(GetBattlerAtPosition(B_POSITION_OPPONENT_LEFT), BATTLER_COORD_X) + gBattleAnimArgs[2];\n    sprite->sTargetY = GetBattlerSpriteCoord(GetBattlerAtPosition(B_POSITION_OPPONENT_LEFT), BATTLER_COORD_Y) + gBattleAnimArgs[3];\n    sprite->sAmplitude = -32;\n    InitAnimArcTranslation(sprite);\n    gSprites[gBattlerSpriteIds[gBattleAnimAttacker]].callback = SpriteCB_TrainerThrowObject;\n    sprite->callback = SpriteCB_PokeBlock_LiftArm;",
  },
  "SpriteCB_ShinyStars_Diagonal": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroySprite","FreeSpriteOamMatrix"],
    lineCount: 16,
    bodyC: "if (sprite->sTimer < 4)\n    {\n        sprite->sTimer++;\n    }\n    else\n    {\n        sprite->invisible = FALSE;\n        sprite->x2 += 5;\n        sprite->y2 -= 5;\n        if (sprite->x2 > 32)\n        {\n            gTasks[sprite->sTaskId].tNumStars--;\n            FreeSpriteOamMatrix(sprite);\n            DestroySprite(sprite);\n        }\n    }",
  },
  "SpriteCB_ShinyStars_Encircle": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["Cos","DestroySprite","FreeSpriteOamMatrix","Sin"],
    lineCount: 9,
    bodyC: "sprite->x2 = Sin(sprite->sPhase, 24);\n    sprite->y2 = Cos(sprite->sPhase, 24);\n    sprite->sPhase += 12;\n    if (sprite->sPhase > 255)\n    {\n        gTasks[sprite->sTaskId].tNumStars--;\n        FreeSpriteOamMatrix(sprite);\n        DestroySprite(sprite);\n    }",
  },
  "SpriteCB_ThrowPokeBlock_Free": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroyAnimSprite","StartSpriteAnim"],
    lineCount: 8,
    bodyC: "if (gSprites[gBattlerSpriteIds[gBattleAnimAttacker]].animEnded)\n    {\n        if (++sprite->data[0] > 0)\n        {\n            StartSpriteAnim(&gSprites[gBattlerSpriteIds[gBattleAnimAttacker]], 0);\n            DestroyAnimSprite(sprite);\n        }\n    }",
  },
  "Task_FadeMon_ToBallColor": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BeginNormalPaletteFade","BlendPalette","DestroyTask","OBJ_PLTT_ID"],
    lineCount: 13,
    bodyC: "u8 ballId = gTasks[taskId].tBallId;\n\n    if (gTasks[taskId].tTimer <= 16)\n    {\n        BlendPalette(OBJ_PLTT_ID(gTasks[taskId].tPalOffset), 16, gTasks[taskId].tCoeff, gBallOpenFadeColors[ballId]);\n        gTasks[taskId].tCoeff += gTasks[taskId].tdCoeff;\n        gTasks[taskId].tTimer++;\n    }\n    else if (!gPaletteFade.active)\n    {\n        u32 selectedPalettes = (u16)gTasks[taskId].tPaletteLo | ((u16)gTasks[taskId].tPaletteHi << 16);\n        BeginNormalPaletteFade(selectedPalettes, 0, 16, 0, RGB_WHITE);\n        DestroyTask(taskId);\n    }",
  },
  "Task_FadeMon_ToNormal": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BeginNormalPaletteFade"],
    lineCount: 6,
    bodyC: "if (!gPaletteFade.active)\n    {\n        u32 selectedPalettes = (u16)gTasks[taskId].tPaletteLo | ((u16)gTasks[taskId].tPaletteHi << 16);\n        BeginNormalPaletteFade(selectedPalettes, 0, 16, 0, RGB_WHITE);\n        gTasks[taskId].func = Task_FadeMon_ToNormal_Step;\n    }",
  },
  "Task_FadeMon_ToNormal_Step": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BlendPalette","DestroyTask","OBJ_PLTT_ID"],
    lineCount: 11,
    bodyC: "u8 ballId = gTasks[taskId].tBallId;\n\n    if (gTasks[taskId].tTimer <= 16)\n    {\n        BlendPalette(OBJ_PLTT_ID(gTasks[taskId].tPalOffset), 16, gTasks[taskId].tCoeff, gBallOpenFadeColors[ballId]);\n        gTasks[taskId].tCoeff += gTasks[taskId].tdCoeff;\n        gTasks[taskId].tTimer++;\n    }\n    else\n    {\n        DestroyTask(taskId);\n    }",
  },
  "Task_PlayerThrow_Wait": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","GetBattlerAtPosition","StartSpriteAnim"],
    lineCount: 5,
    bodyC: "if (gSprites[gBattlerSpriteIds[GetBattlerAtPosition(B_POSITION_PLAYER_LEFT)]].animEnded)\n    {\n        StartSpriteAnim(&gSprites[gBattlerSpriteIds[GetBattlerAtPosition(B_POSITION_PLAYER_LEFT)]], 0);\n        DestroyTask(taskId);\n    }",
  },
  "Task_ShinyStars": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","GetBattlerSide","GetBattlerSpriteCoord","PlaySE12WithPanning"],
    lineCount: 59,
    bodyC: "u8 battler;\n    u8 x, y;\n    u8 spriteId;\n    u16 timer;\n    s16 starIdx;\n    u8 pan;\n\n    if (gTasks[taskId].tTimer < 60)\n    {\n        gTasks[taskId].tTimer++;\n        return;\n    }\n\n     \n    if (gBattleSpritesDataPtr->animationData->numBallParticles)\n        return;\n\n    timer = gTasks[taskId].tStarTimer++;\n    if (timer % 4)  \n        return;\n\n    battler = gTasks[taskId].tBattler;\n    x = GetBattlerSpriteCoord(battler, BATTLER_COORD_X);\n    y = GetBattlerSpriteCoord(battler, BATTLER_COORD_Y);\n\n    starIdx = gTasks[taskId].tStarIdx;\n    if (starIdx == 0)  \n    {\n        spriteId = CreateSprite(&gWishStarSpriteTemplate, x, y, 5);\n    }\n    else if (starIdx >= 0 && gTasks[taskId].tStarIdx < 4)  \n    {\n        spriteId = CreateSprite(&gMiniTwinklingStarSpriteTemplate, x, y, 5);\n        gSprites[spriteId].oam.tileNum += 4;\n    }\n    else  \n    {\n        spriteId = CreateSprite(&gMiniTwinklingStarSpriteTemplate, x, y, 5);\n        gSprites[spriteId].oam.tileNum += 5;\n    }\n\n    if (gTasks[taskId].tStarMove == SHINY_STAR_ENCIRCLE)\n    {\n        gSprites[spriteId].callback = SpriteCB_ShinyStars_Encircle;\n    }\n    else\n    {\n        gSprites[spriteId].callback = SpriteCB_ShinyStars_Diagonal;\n        gSprites[spriteId].x2 = -32;\n        gSprites[spriteId].y2 = 32;\n        gSprites[spriteId].invisible = TRUE;\n        if (gTasks[taskId].tStarIdx == 0)\n        {\n            if (GetBattlerSide(battler) == B_SIDE_PLAYER)\n                pan = -64;\n            else\n                pan = 63;\n\n            PlaySE12WithPanning(SE_SHINY, pan);\n        }\n    }\n\n    gSprites[spriteId].sTaskId = taskId;\n    gTasks[taskId].tStarIdx++;\n    if (spriteId != MAX_SPRITES)\n        gTasks[taskId].tNumStars++;\n\n    if (gTasks[taskId].tStarIdx == 5)\n        gTasks[taskId].func = Task_ShinyStars_Wait;",
  },
  "Task_ShinyStars_Wait": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask"],
    lineCount: 10,
    bodyC: "u8 battler;\n\n    if (gTasks[taskId].tNumStars == 0)\n    {\n        if (gTasks[taskId].tStarMove == SHINY_STAR_DIAGONAL)\n        {\n            battler = gTasks[taskId].tBattler;\n            gBattleSpritesDataPtr->healthBoxesData[battler].finishedShinyMonAnim = TRUE;\n        }\n\n        DestroyTask(taskId);\n    }",
  },
  "TimerBallOpenParticleAnimation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","DestroyTask","IncrBallParticleCount","StartSpriteAnim"],
    lineCount: 26,
    bodyC: "u8 i;\n    u8 x, y, priority, subpriority, ballId;\n    u8 spriteId;\n\n    ballId = gTasks[taskId].data[15];\n    x = gTasks[taskId].data[1];\n    y = gTasks[taskId].data[2];\n    priority = gTasks[taskId].data[3];\n    subpriority = gTasks[taskId].data[4];\n\n    for (i = 0; i < 8; i++)\n    {\n        spriteId = CreateSprite(&sBallParticleSpriteTemplates[ballId], x, y, subpriority);\n        if (spriteId != MAX_SPRITES)\n        {\n            IncrBallParticleCount();\n            StartSpriteAnim(&gSprites[spriteId], sBallParticleAnimNums[ballId]);\n            gSprites[spriteId].callback = FanOutBallOpenParticles_Step1;\n            gSprites[spriteId].oam.priority = priority;\n            gSprites[spriteId].data[0] = i * 32;\n            gSprites[spriteId].data[4] = 10;\n            gSprites[spriteId].data[5] = 2;\n            gSprites[spriteId].data[6] = 1;\n        }\n    }\n\n    if (!gMain.inBattle)\n        gSprites[spriteId].data[7] = 1;\n\n    DestroyTask(taskId);",
  },
  "TryShinyAnimation": {
    returnType: "void",
    params: "u8 battler, struct Pokemon *mon",
    callsTo: ["CreateTask","GET_SHINY_VALUE","GetMonData","GetSpriteTileStartByTag","IsBattlerSpriteVisible","LoadCompressedSpritePaletteUsingHeap","LoadCompressedSpriteSheetUsingHeap"],
    lineCount: 30,
    bodyC: "bool8 isShiny;\n    u32 otId, personality;\n    u32 shinyValue;\n    u8 taskCirc, taskDgnl;\n\n    isShiny = FALSE;\n    gBattleSpritesDataPtr->healthBoxesData[battler].triedShinyMonAnim = TRUE;\n    otId = GetMonData(mon, MON_DATA_OT_ID);\n    personality = GetMonData(mon, MON_DATA_PERSONALITY);\n\n    if (IsBattlerSpriteVisible(battler))\n    {\n        shinyValue = GET_SHINY_VALUE(otId, personality);\n        if (shinyValue < SHINY_ODDS)\n            isShiny = TRUE;\n\n        if (isShiny)\n        {\n            if (GetSpriteTileStartByTag(ANIM_TAG_GOLD_STARS) == 0xFFFF)\n            {\n                LoadCompressedSpriteSheetUsingHeap(&gBattleAnimPicTable[ANIM_TAG_GOLD_STARS - ANIM_SPRITES_START]);\n                LoadCompressedSpritePaletteUsingHeap(&gBattleAnimPaletteTable[ANIM_TAG_GOLD_STARS - ANIM_SPRITES_START]);\n            }\n\n            taskCirc = CreateTask(Task_ShinyStars, 10);\n            taskDgnl = CreateTask(Task_ShinyStars, 10);\n            gTasks[taskCirc].tBattler = battler;\n            gTasks[taskDgnl].tBattler = battler;\n            gTasks[taskCirc].tStarMove = SHINY_STAR_ENCIRCLE;\n            gTasks[taskDgnl].tStarMove = SHINY_STAR_DIAGONAL;\n            return;\n        }\n    }\n\n    gBattleSpritesDataPtr->healthBoxesData[battler].finishedShinyMonAnim = TRUE;",
  },
  "UltraBallOpenParticleAnimation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","DestroyTask","IncrBallParticleCount","StartSpriteAnim"],
    lineCount: 26,
    bodyC: "u8 i;\n    u8 x, y, priority, subpriority, ballId;\n    u8 spriteId;\n\n    ballId = gTasks[taskId].data[15];\n    x = gTasks[taskId].data[1];\n    y = gTasks[taskId].data[2];\n    priority = gTasks[taskId].data[3];\n    subpriority = gTasks[taskId].data[4];\n\n    for (i = 0; i < 10; i++)\n    {\n        spriteId = CreateSprite(&sBallParticleSpriteTemplates[ballId], x, y, subpriority);\n        if (spriteId != MAX_SPRITES)\n        {\n            IncrBallParticleCount();\n            StartSpriteAnim(&gSprites[spriteId], sBallParticleAnimNums[ballId]);\n            gSprites[spriteId].callback = FanOutBallOpenParticles_Step1;\n            gSprites[spriteId].oam.priority = priority;\n            gSprites[spriteId].data[0] = i * 25;\n            gSprites[spriteId].data[4] = 5;\n            gSprites[spriteId].data[5] = 1;\n            gSprites[spriteId].data[6] = 1;\n        }\n    }\n\n    if (!gMain.inBattle)\n        gSprites[spriteId].data[7] = 1;\n\n    DestroyTask(taskId);",
  },
} as const;
