// AUTO-GENERATED from src/cable_club.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 57

export const ENGINE_FUNCTIONS = {
  "AreBattleTowerLinkSpeciesSame": {
    returnType: "bool32",
    params: "u16 *speciesList1, u16 *speciesList2",
    callsTo: ["StringCopy"],
    lineCount: 28,
    bodyC: "int i;\n    int j;\n    bool32 haveSameSpecies = FALSE;\n    int numSameSpecies = 0;\n\n    gStringVar1[0] = EOS;\n    gStringVar2[0] = EOS;\n\n    for (i = 0; i < FRONTIER_MULTI_PARTY_SIZE; i++)\n    {\n        for (j = 0; j < FRONTIER_MULTI_PARTY_SIZE; j++)\n        {\n            if (speciesList1[i] == speciesList2[j])\n            {\n                if (numSameSpecies == 0)\n                {\n                    StringCopy(gStringVar1, gSpeciesNames[speciesList1[i]]);\n                    haveSameSpecies = TRUE;\n                }\n\n                if (numSameSpecies == 1)\n                {\n                    StringCopy(gStringVar2, gSpeciesNames[speciesList1[i]]);\n                    haveSameSpecies = TRUE;\n                }\n\n                numSameSpecies++;\n            }\n        }\n    }\n\n     \n    gSpecialVar_0x8005 = numSameSpecies;\n\n    return haveSameSpecies;",
  },
  "CB2_ReturnFromCableClubBattle": {
    returnType: "void",
    params: "void",
    callsTo: ["GetMultiplayerId","InUnionRoom","LoadPlayerParty","MysteryGift_TryIncrementStat","Overworld_ResetMapMusic","SavePlayerBag","SetMainCallback2","UpdatePlayerLinkBattleRecords","UpdateTrainerFansAfterLinkBattle"],
    lineCount: 26,
    bodyC: "gBattleTypeFlags &= ~BATTLE_TYPE_LINK_IN_BATTLE;\n    Overworld_ResetMapMusic();\n    LoadPlayerParty();\n    SavePlayerBag();\n    UpdateTrainerFansAfterLinkBattle();\n\n    if (gSpecialVar_0x8004 == USING_SINGLE_BATTLE || gSpecialVar_0x8004 == USING_DOUBLE_BATTLE)\n    {\n        UpdatePlayerLinkBattleRecords(gLocalLinkPlayerId ^ 1);\n        if (gWirelessCommType)\n        {\n            switch (gBattleOutcome)\n            {\n            case B_OUTCOME_WON:\n                MysteryGift_TryIncrementStat(CARD_STAT_BATTLES_WON, gLinkPlayers[GetMultiplayerId() ^ 1].trainerId);\n                break;\n            case B_OUTCOME_LOST:\n                MysteryGift_TryIncrementStat(CARD_STAT_BATTLES_LOST, gLinkPlayers[GetMultiplayerId() ^ 1].trainerId);\n                break;\n            }\n        }\n    }\n\n    if (InUnionRoom() == TRUE)\n        gMain.savedCallback = CB2_ReturnFromUnionRoomBattle;\n    else\n        gMain.savedCallback = CB2_ReturnToFieldFromMultiplayer;\n\n    SetMainCallback2(CB2_SetUpSaveAfterLinkBattle);",
  },
  "CB2_ReturnFromUnionRoomBattle": {
    returnType: "static void",
    params: "void",
    callsTo: ["GetLinkPlayerCount","RunTasks","SetCloseLinkCallback","SetMainCallback2"],
    lineCount: 38,
    bodyC: "u8 playerCount;\n    int i;\n    bool32 linkedWithFRLG;\n\n    switch (gMain.state)\n    {\n    case 0:\n        playerCount = GetLinkPlayerCount();\n        linkedWithFRLG = FALSE;\n        for (i = 0; i < playerCount; i++)\n        {\n            u32 version = (u8)gLinkPlayers[i].version;\n            if (version == VERSION_FIRE_RED || version == VERSION_LEAF_GREEN)\n            {\n                linkedWithFRLG = TRUE;\n                break;\n            }\n        }\n\n        if (linkedWithFRLG)\n        {\n            gMain.state = 2;\n        }\n        else\n        {\n            SetCloseLinkCallback();\n            gMain.state = 1;\n        }\n        break;\n    case 1:\n        if (!gReceivedRemoteLinkPlayers)\n        {\n            SetMainCallback2(CB2_ReturnToField);\n        }\n        break;\n    case 2:\n        SetMainCallback2(CB2_ReturnToField);\n        break;\n    }\n    RunTasks();",
  },
  "CableClubSaveGame": {
    returnType: "void",
    params: "void",
    callsTo: ["SaveGame"],
    lineCount: 1,
    bodyC: "SaveGame();",
  },
  "CheckLinkCanceled": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["IsLinkConnectionEstablished","JOY_NEW","SetSuppressLinkErrorMessage"],
    lineCount: 9,
    bodyC: "if (IsLinkConnectionEstablished())\n        SetSuppressLinkErrorMessage(TRUE);\n\n    if (JOY_NEW(B_BUTTON))\n    {\n        gLinkType = 0;\n        gTasks[taskId].func = Task_LinkupFailed;\n        return TRUE;\n    }\n    return FALSE;",
  },
  "CheckLinkCanceledBeforeConnection": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["IsLinkConnectionEstablished","JOY_NEW"],
    lineCount: 8,
    bodyC: "if ((JOY_NEW(B_BUTTON))\n     && IsLinkConnectionEstablished() == FALSE)\n    {\n        gLinkType = 0;\n        gTasks[taskId].func = Task_LinkupFailed;\n        return TRUE;\n    }\n    return FALSE;",
  },
  "CheckLinkErrored": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["HasLinkErrorOccurred"],
    lineCount: 6,
    bodyC: "if (HasLinkErrorOccurred() == TRUE)\n    {\n        gTasks[taskId].func = Task_LinkupConnectionError;\n        return TRUE;\n    }\n    return FALSE;",
  },
  "CheckSioErrored": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["GetSioMultiSI"],
    lineCount: 6,
    bodyC: "if (GetSioMultiSI() == TRUE)\n    {\n        gTasks[taskId].func = Task_LinkupConnectionError;\n        return TRUE;\n    }\n    return FALSE;",
  },
  "CleanupLinkRoomState": {
    returnType: "void",
    params: "void",
    callsTo: ["LoadPlayerParty","SavePlayerBag","SetWarpDestinationToDynamicWarp"],
    lineCount: 9,
    bodyC: "if (gSpecialVar_0x8004 == USING_SINGLE_BATTLE\n     || gSpecialVar_0x8004 == USING_DOUBLE_BATTLE\n     || gSpecialVar_0x8004 == USING_MULTI_BATTLE\n     || gSpecialVar_0x8004 == USING_BATTLE_TOWER)\n    {\n        LoadPlayerParty();\n        SavePlayerBag();\n    }\n    SetWarpDestinationToDynamicWarp(WARP_ID_DYNAMIC);",
  },
  "ClearLinkPlayerCountWindow": {
    returnType: "static void",
    params: "u16 windowId",
    callsTo: ["ClearStdWindowAndFrame","CopyWindowToVram"],
    lineCount: 2,
    bodyC: "ClearStdWindowAndFrame(windowId, FALSE);\n    CopyWindowToVram(windowId, COPYWIN_FULL);",
  },
  "ColosseumPlayerSpotTriggered": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateTask_EnterCableClubSeat"],
    lineCount: 5,
    bodyC: "gLinkType = LINKTYPE_BATTLE;\n\n    if (gWirelessCommType)\n        CreateTask_EnterCableClubSeat(Task_StartWirelessCableClubBattle);\n    else\n        CreateTask_EnterCableClubSeat(Task_StartWiredCableClubBattle);",
  },
  "CreateLinkupTask": {
    returnType: "static void",
    params: "u8 minPlayers, u8 maxPlayers",
    callsTo: ["CreateTask","FindTaskIdByFunc"],
    lineCount: 7,
    bodyC: "if (FindTaskIdByFunc(Task_LinkupStart) == TASK_NONE)\n    {\n        u8 taskId1;\n\n        taskId1 = CreateTask(Task_LinkupStart, 80);\n        gTasks[taskId1].tMinPlayers = minPlayers;\n        gTasks[taskId1].tMaxPlayers = maxPlayers;\n    }",
  },
  "CreateTask_EnterCableClubSeat": {
    returnType: "void",
    params: "TaskFunc followupFunc",
    callsTo: ["CreateTask","ScriptContext_Stop","SetTaskFuncWithFollowupFunc"],
    lineCount: 3,
    bodyC: "u8 taskId = CreateTask(Task_EnterCableClubSeat, 80);\n    SetTaskFuncWithFollowupFunc(taskId, Task_EnterCableClubSeat, followupFunc);\n    ScriptContext_Stop();",
  },
  "CreateTask_ReestablishCableClubLink": {
    returnType: "u8",
    params: "void",
    callsTo: ["CreateTask","FuncIsActiveTask"],
    lineCount: 27,
    bodyC: "if (FuncIsActiveTask(Task_ReestablishLink) != FALSE)\n        return TASK_NONE;\n\n    switch (gSpecialVar_0x8004)\n    {\n    case USING_SINGLE_BATTLE:\n        gLinkType = LINKTYPE_SINGLE_BATTLE;\n        break;\n    case USING_DOUBLE_BATTLE:\n        gLinkType = LINKTYPE_DOUBLE_BATTLE;\n        break;\n    case USING_MULTI_BATTLE:\n        gLinkType = LINKTYPE_MULTI_BATTLE;\n        break;\n    case USING_BATTLE_TOWER:\n        if (gSaveBlock2Ptr->frontier.lvlMode == FRONTIER_LVL_50)\n            gLinkType = LINKTYPE_BATTLE_TOWER_50;\n        else\n            gLinkType = LINKTYPE_BATTLE_TOWER_OPEN;\n        break;\n    case USING_TRADE_CENTER:\n        gLinkType = LINKTYPE_TRADE;\n        break;\n    case USING_RECORD_CORNER:\n        gLinkType = LINKTYPE_RECORD_MIX_AFTER;\n        break;\n    }\n\n    return CreateTask(Task_ReestablishLink, 80);",
  },
  "ExchangeDataAndGetLinkupStatus": {
    returnType: "static u32",
    params: "u8 minPlayers, u8 maxPlayers",
    callsTo: ["ConvertIntToDecimalStringN","GetLinkPlayerCount_2","GetLinkPlayerDataExchangeStatusTimed"],
    lineCount: 19,
    bodyC: "switch (GetLinkPlayerDataExchangeStatusTimed(minPlayers, maxPlayers))\n    {\n    case EXCHANGE_COMPLETE:\n        return LINKUP_SUCCESS;\n    case EXCHANGE_DIFF_SELECTIONS:\n        return LINKUP_DIFF_SELECTIONS;\n    case EXCHANGE_PLAYER_NOT_READY:\n        return LINKUP_PLAYER_NOT_READY;\n    case EXCHANGE_PARTNER_NOT_READY:\n        return LINKUP_PARTNER_NOT_READY;\n    case EXCHANGE_WRONG_NUM_PLAYERS:\n        ConvertIntToDecimalStringN(gStringVar1, GetLinkPlayerCount_2(), STR_CONV_MODE_LEFT_ALIGN, 1);\n        return LINKUP_WRONG_NUM_PLAYERS;\n    case EXCHANGE_STAT_7:\n        return LINKUP_FAILED_CONTEST_GMODE;\n    case EXCHANGE_TIMED_OUT:\n    default:\n        return LINKUP_ONGOING;\n    }",
  },
  "ExitLinkRoom": {
    returnType: "void",
    params: "void",
    callsTo: ["QueueExitLinkRoomKey"],
    lineCount: 1,
    bodyC: "QueueExitLinkRoomKey();",
  },
  "FinishLinkup": {
    returnType: "static void",
    params: "u16 *linkupStatus, u32 taskId",
    callsTo: ["AreBattleTowerLinkSpeciesSame","ClearLinkPlayerCountWindow","DestroyTask","ScriptContext_Enable","SetCloseLinkCallback"],
    lineCount: 30,
    bodyC: "struct TrainerCard *trainerCards = gTrainerCards;\n\n    if (*linkupStatus == LINKUP_SUCCESS)\n    {\n        if (gLinkType == LINKTYPE_BATTLE_TOWER_50 || gLinkType == LINKTYPE_BATTLE_TOWER_OPEN)\n        {\n            if (AreBattleTowerLinkSpeciesSame(trainerCards[0].monSpecies, trainerCards[1].monSpecies))\n            {\n                 \n                *linkupStatus = LINKUP_FAILED_BATTLE_TOWER;\n                SetCloseLinkCallback();\n                gTasks[taskId].func = Task_StopLinkup;\n            }\n            else\n            {\n                 \n                ClearLinkPlayerCountWindow(gTasks[taskId].tWindowId);\n                ScriptContext_Enable();\n                DestroyTask(taskId);\n            }\n        }\n        else\n        {\n             \n            ClearLinkPlayerCountWindow(gTasks[taskId].tWindowId);\n            ScriptContext_Enable();\n            DestroyTask(taskId);\n        }\n    }\n    else\n    {\n         \n        SetCloseLinkCallback();\n        gTasks[taskId].func = Task_StopLinkup;\n    }",
  },
  "GetLinkTrainerCardColor": {
    returnType: "bool32",
    params: "u8 linkPlayerIndex",
    callsTo: ["GetTrainerCardStars","StringCopy"],
    lineCount: 8,
    bodyC: "u32 numStars;\n\n    gSpecialVar_0x8006 = linkPlayerIndex;\n    StringCopy(gStringVar1, gLinkPlayers[linkPlayerIndex].name);\n\n    numStars = GetTrainerCardStars(linkPlayerIndex);\n    if (numStars == 0)\n        return FALSE;\n\n    StringCopy(gStringVar2, sTrainerCardColorNames[numStars - 1]);\n    return TRUE;",
  },
  "PlayerEnteredTradeSeat": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateTask_EnterCableClubSeat"],
    lineCount: 4,
    bodyC: "if (gWirelessCommType != 0)\n        CreateTask_EnterCableClubSeat(Task_StartWirelessTrade);\n    else\n        CreateTask_EnterCableClubSeat(Task_StartWiredTrade);",
  },
  "PrintNumPlayersInLink": {
    returnType: "static void",
    params: "u16 windowId, u32 numPlayers",
    callsTo: ["AddTextPrinterParameterized","ConvertIntToDecimalStringN","CopyWindowToVram","GetStringCenterAlignXOffset","SetStandardWindowBorderStyle","StringExpandPlaceholders"],
    lineCount: 7,
    bodyC: "u8 xPos;\n\n    ConvertIntToDecimalStringN(gStringVar1, numPlayers, STR_CONV_MODE_LEFT_ALIGN, 1);\n    SetStandardWindowBorderStyle(windowId, FALSE);\n    StringExpandPlaceholders(gStringVar4, gText_NumPlayerLink);\n    xPos = GetStringCenterAlignXOffset(FONT_NORMAL, gStringVar4, 88);\n    AddTextPrinterParameterized(windowId, FONT_NORMAL, gStringVar4, xPos, 1, TEXT_SKIP_DRAW, NULL);\n    CopyWindowToVram(windowId, COPYWIN_FULL);",
  },
  "Script_ShowLinkTrainerCard": {
    returnType: "void",
    params: "void",
    callsTo: ["ShowTrainerCardInLink"],
    lineCount: 1,
    bodyC: "ShowTrainerCardInLink(gSpecialVar_0x8006, CB2_ReturnToFieldContinueScriptPlayMapMusic);",
  },
  "SetLinkBattleTypeFlags": {
    returnType: "static void",
    params: "int linkService",
    callsTo: ["ReducePlayerPartyToSelectedMons"],
    lineCount: 16,
    bodyC: "switch (linkService)\n    {\n    case USING_SINGLE_BATTLE:\n        gBattleTypeFlags = BATTLE_TYPE_LINK | BATTLE_TYPE_TRAINER;\n        break;\n    case USING_DOUBLE_BATTLE:\n        gBattleTypeFlags = BATTLE_TYPE_DOUBLE | BATTLE_TYPE_LINK | BATTLE_TYPE_TRAINER;\n        break;\n    case USING_MULTI_BATTLE:\n        ReducePlayerPartyToSelectedMons();\n        gBattleTypeFlags = BATTLE_TYPE_DOUBLE | BATTLE_TYPE_LINK | BATTLE_TYPE_TRAINER | BATTLE_TYPE_MULTI;\n        break;\n    case USING_BATTLE_TOWER:\n        gBattleTypeFlags = BATTLE_TYPE_BATTLE_TOWER | BATTLE_TYPE_DOUBLE | BATTLE_TYPE_LINK | BATTLE_TYPE_TRAINER | BATTLE_TYPE_MULTI;\n        break;\n    }",
  },
  "Task_EnterCableClubSeat": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","EraseFieldMessageBox","GetCableClubPartnersReady","HideFieldMessageBox","IsFieldMessageBoxHidden","ScriptContext_Enable","SetInCableClubSeat","SetLinkWaitingForScript","SetLocalLinkPlayerId","SetStartedCableClubActivity","ShowFieldMessage","SwitchTaskToFollowupFunc"],
    lineCount: 38,
    bodyC: "struct Task *task = &gTasks[taskId];\n\n    switch (task->tState)\n    {\n    case 0:\n        ShowFieldMessage(gText_PleaseWaitForLink);\n        task->tState = 1;\n        break;\n    case 1:\n        if (IsFieldMessageBoxHidden())\n        {\n            SetInCableClubSeat();\n            SetLocalLinkPlayerId(gSpecialVar_0x8005);\n            task->tState = 2;\n        }\n        break;\n    case 2:\n        switch (GetCableClubPartnersReady())\n        {\n        case CABLE_SEAT_WAITING:\n            break;\n        case CABLE_SEAT_SUCCESS:\n             \n            HideFieldMessageBox();\n            task->tState = 0;\n            SetStartedCableClubActivity();\n            SwitchTaskToFollowupFunc(taskId);\n            break;\n        case CABLE_SEAT_FAILED:\n            task->tState = 3;\n            break;\n        }\n        break;\n    case 3:\n         \n        SetLinkWaitingForScript();\n        EraseFieldMessageBox(TRUE);\n        DestroyTask(taskId);\n        ScriptContext_Enable();\n        break;\n    }",
  },
  "Task_LinkupAwaitConfirmation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CheckLinkCanceledBeforeConnection","CheckLinkErrored","CheckSioErrored","ClearLinkPlayerCountWindow","ConvertIntToDecimalStringN","GetLinkPlayerCount_2","JOY_NEW","SaveLinkPlayers","ShowFieldAutoScrollMessage","UpdateLinkPlayerCountDisplay"],
    lineCount: 16,
    bodyC: "s16 *data = gTasks[taskId].data;\n    s32 linkPlayerCount = GetLinkPlayerCount_2();\n\n    if (CheckLinkCanceledBeforeConnection(taskId) == TRUE\n     || CheckSioErrored(taskId) == TRUE\n     || CheckLinkErrored(taskId) == TRUE)\n        return;\n\n    UpdateLinkPlayerCountDisplay(taskId, linkPlayerCount);\n\n    if (!(JOY_NEW(A_BUTTON)))\n        return;\n\n    if (linkPlayerCount < tMinPlayers)\n        return;\n\n    SaveLinkPlayers(linkPlayerCount);\n    ClearLinkPlayerCountWindow(tWindowId);\n    ConvertIntToDecimalStringN(gStringVar1, linkPlayerCount, STR_CONV_MODE_LEFT_ALIGN, 1);\n    ShowFieldAutoScrollMessage(gText_ConfirmStartLinkWithXPlayers);\n    gTasks[taskId].func = Task_LinkupTryConfirmation;",
  },
  "Task_LinkupAwaitConnection": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CheckLinkCanceled","CheckLinkCanceledBeforeConnection","GetLinkPlayerCount_2","IsLinkMaster","PlaySE","SetSuppressLinkErrorMessage","ShowFieldAutoScrollMessage"],
    lineCount: 19,
    bodyC: "u32 playerCount = GetLinkPlayerCount_2();\n\n    if (CheckLinkCanceledBeforeConnection(taskId) == TRUE\n     || CheckLinkCanceled(taskId) == TRUE\n     || playerCount < 2)\n        return;\n\n    SetSuppressLinkErrorMessage(TRUE);\n    gTasks[taskId].data[3] = 0;\n    if (IsLinkMaster() == TRUE)\n    {\n        PlaySE(SE_PIN);\n        ShowFieldAutoScrollMessage(gText_ConfirmLinkWhenPlayersReady);\n        gTasks[taskId].func = Task_LinkupConfirmWhenReady;\n    }\n    else\n    {\n        PlaySE(SE_BOO);\n        ShowFieldAutoScrollMessage(gText_AwaitingLinkup);\n        gTasks[taskId].func = Task_LinkupExchangeDataWithLeader;\n    }",
  },
  "Task_LinkupAwaitTrainerCardData": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CheckLinkErrored","CopyTrainerCardData","FinishLinkup","GetBlockReceivedStatus","GetLinkPlayerCount","GetSavedLinkPlayerCountAsBitFlags","ResetBlockReceivedFlags","SetSuppressLinkErrorMessage"],
    lineCount: 12,
    bodyC: "u8 index;\n\n    if (CheckLinkErrored(taskId) == TRUE)\n        return;\n\n    if (GetBlockReceivedStatus() != GetSavedLinkPlayerCountAsBitFlags())\n        return;\n\n    for (index = 0; index < GetLinkPlayerCount(); index++)\n    {\n        CopyTrainerCardData(&gTrainerCards[index], (struct TrainerCard *)gBlockRecvBuffer[index], gLinkPlayers[index].version);\n    }\n\n    SetSuppressLinkErrorMessage(FALSE);\n    ResetBlockReceivedFlags();\n    FinishLinkup(&gSpecialVar_Result, taskId);",
  },
  "Task_LinkupCheckStatusAfterConfirm": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CheckLinkErrored","CloseLink","GetLinkPlayerCount_2","GetMonData","GetMultiplayerId","HideFieldMessageBox","Link_AnyPartnersPlayingRubyOrSapphire","SaveLinkPlayers","SendBlockRequest","SetCloseLinkCallback","TrainerCard_GenerateCardForLinkPlayer"],
    lineCount: 43,
    bodyC: "struct TrainerCard *card;\n\n    if (CheckLinkErrored(taskId) == TRUE)\n        return;\n\n    if (gSpecialVar_Result == LINKUP_WRONG_NUM_PLAYERS)\n    {\n        if (!Link_AnyPartnersPlayingRubyOrSapphire())\n        {\n            SetCloseLinkCallback();\n            HideFieldMessageBox();\n            gTasks[taskId].func = Task_StopLinkup;\n        }\n        else\n        {\n            CloseLink();\n            HideFieldMessageBox();\n            gTasks[taskId].func = Task_StopLinkup;\n        }\n    }\n    else if (gSpecialVar_Result == LINKUP_DIFF_SELECTIONS)\n    {\n        SetCloseLinkCallback();\n        HideFieldMessageBox();\n        gTasks[taskId].func = Task_StopLinkup;\n    }\n    else if (gSpecialVar_Result == LINKUP_PLAYER_NOT_READY\n          || gSpecialVar_Result == LINKUP_PARTNER_NOT_READY)\n    {\n        CloseLink();\n        HideFieldMessageBox();\n        gTasks[taskId].func = Task_StopLinkup;\n    }\n    else\n    {\n        gFieldLinkPlayerCount = GetLinkPlayerCount_2();\n        gLocalLinkPlayerId = GetMultiplayerId();\n        SaveLinkPlayers(gFieldLinkPlayerCount);\n        card = (struct TrainerCard *)gBlockSendBuffer;\n        TrainerCard_GenerateCardForLinkPlayer(card);\n        card->monSpecies[0] = GetMonData(&gPlayerParty[gSelectedOrderFromParty[0] - 1], MON_DATA_SPECIES, NULL);\n        card->monSpecies[1] = GetMonData(&gPlayerParty[gSelectedOrderFromParty[1] - 1], MON_DATA_SPECIES, NULL);\n        gTasks[taskId].func = Task_LinkupAwaitTrainerCardData;\n        SendBlockRequest(BLOCK_REQ_SIZE_100);\n    }",
  },
  "Task_LinkupConfirm": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CheckLinkErrored","ExchangeDataAndGetLinkupStatus","GetLinkPlayerCount_2","GetSavedPlayerCount","TryLinkTimeout"],
    lineCount: 15,
    bodyC: "u8 minPlayers = gTasks[taskId].tMinPlayers;\n    u8 maxPlayers = gTasks[taskId].tMaxPlayers;\n\n    if (CheckLinkErrored(taskId) == TRUE\n     || TryLinkTimeout(taskId) == TRUE)\n        return;\n\n    if (GetLinkPlayerCount_2() != GetSavedPlayerCount())\n    {\n        gTasks[taskId].func = Task_LinkupConnectionError;\n    }\n    else\n    {\n        gSpecialVar_Result = ExchangeDataAndGetLinkupStatus(minPlayers, maxPlayers);\n        if (gSpecialVar_Result != LINKUP_ONGOING)\n            gTasks[taskId].func = Task_LinkupCheckStatusAfterConfirm;\n    }",
  },
  "Task_LinkupConfirmWhenReady": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CheckLinkCanceledBeforeConnection","CheckLinkErrored","CheckSioErrored","GetFieldMessageBoxMode"],
    lineCount: 9,
    bodyC: "if (CheckLinkCanceledBeforeConnection(taskId) == TRUE\n     || CheckSioErrored(taskId) == TRUE\n     || CheckLinkErrored(taskId) == TRUE)\n        return;\n\n    if (GetFieldMessageBoxMode() == FIELD_MESSAGE_BOX_HIDDEN)\n    {\n        gTasks[taskId].tNumPlayers = 0;\n        gTasks[taskId].func = Task_LinkupAwaitConfirmation;\n    }",
  },
  "Task_LinkupConnectionError": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["ClearLinkPlayerCountWindow","DestroyTask","HideFieldMessageBox","RemoveWindow","ScriptContext_Enable"],
    lineCount: 6,
    bodyC: "gSpecialVar_Result = LINKUP_CONNECTION_ERROR;\n    ClearLinkPlayerCountWindow(gTasks[taskId].tWindowId);\n    RemoveWindow(gTasks[taskId].tWindowId);\n    HideFieldMessageBox();\n    ScriptContext_Enable();\n    DestroyTask(taskId);",
  },
  "Task_LinkupExchangeDataWithLeader": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CheckLinkCanceledBeforeConnection","CheckLinkErrored","CloseLink","ExchangeDataAndGetLinkupStatus","GetLinkPlayerCount_2","GetMonData","GetMultiplayerId","HideFieldMessageBox","SaveLinkPlayers","SetCloseLinkCallback","TrainerCard_GenerateCardForLinkPlayer"],
    lineCount: 35,
    bodyC: "u8 minPlayers, maxPlayers;\n    struct TrainerCard *card;\n\n    minPlayers = gTasks[taskId].tMinPlayers;\n    maxPlayers = gTasks[taskId].tMaxPlayers;\n\n    if (CheckLinkCanceledBeforeConnection(taskId) == TRUE\n     || CheckLinkErrored(taskId) == TRUE)\n        return;\n\n    gSpecialVar_Result = ExchangeDataAndGetLinkupStatus(minPlayers, maxPlayers);\n    if (gSpecialVar_Result == LINKUP_ONGOING)\n        return;\n    if (gSpecialVar_Result == LINKUP_DIFF_SELECTIONS\n     || gSpecialVar_Result == LINKUP_WRONG_NUM_PLAYERS)\n    {\n        SetCloseLinkCallback();\n        HideFieldMessageBox();\n        gTasks[taskId].func = Task_StopLinkup;\n    }\n    else if (gSpecialVar_Result == LINKUP_PLAYER_NOT_READY\n          || gSpecialVar_Result == LINKUP_PARTNER_NOT_READY)\n    {\n        CloseLink();\n        HideFieldMessageBox();\n        gTasks[taskId].func = Task_StopLinkup;\n    }\n    else\n    {\n        gFieldLinkPlayerCount = GetLinkPlayerCount_2();\n        gLocalLinkPlayerId = GetMultiplayerId();\n        SaveLinkPlayers(gFieldLinkPlayerCount);\n        card = (struct TrainerCard *)gBlockSendBuffer;\n        TrainerCard_GenerateCardForLinkPlayer(card);\n        card->monSpecies[0] = GetMonData(&gPlayerParty[gSelectedOrderFromParty[0] - 1], MON_DATA_SPECIES, NULL);\n        card->monSpecies[1] = GetMonData(&gPlayerParty[gSelectedOrderFromParty[1] - 1], MON_DATA_SPECIES, NULL);\n        gTasks[taskId].func = Task_LinkupAwaitTrainerCardData;\n    }",
  },
  "Task_LinkupFailed": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["ClearLinkPlayerCountWindow","DestroyTask","RemoveWindow","ScriptContext_Enable","StopFieldMessage"],
    lineCount: 6,
    bodyC: "gSpecialVar_Result = LINKUP_FAILED;\n    ClearLinkPlayerCountWindow(gTasks[taskId].tWindowId);\n    StopFieldMessage();\n    RemoveWindow(gTasks[taskId].tWindowId);\n    ScriptContext_Enable();\n    DestroyTask(taskId);",
  },
  "Task_LinkupStart": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["AddWindow","OpenLinkTimed","ResetLinkPlayerCount","ResetLinkPlayers"],
    lineCount: 13,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n    if (data[0] == 0)\n    {\n        OpenLinkTimed();\n        ResetLinkPlayerCount();\n        ResetLinkPlayers();\n        tWindowId = AddWindow(&sWindowTemplate_LinkPlayerCount);\n    }\n    else if (data[0] > 9)\n    {\n        gTasks[taskId].func = Task_LinkupAwaitConnection;\n    }\n    data[0]++;",
  },
  "Task_LinkupTryConfirmation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CheckLinkCanceledBeforeConnection","CheckLinkErrored","CheckShouldAdvanceLinkState","CheckSioErrored","GetFieldMessageBoxMode","GetLinkPlayerCount_2","GetSavedPlayerCount","JOY_HELD","PlaySE","ShowFieldAutoScrollMessage"],
    lineCount: 23,
    bodyC: "if (CheckLinkCanceledBeforeConnection(taskId) == TRUE\n     || CheckSioErrored(taskId) == TRUE\n     || CheckLinkErrored(taskId) == TRUE)\n        return;\n\n    if (GetFieldMessageBoxMode() == FIELD_MESSAGE_BOX_HIDDEN)\n    {\n        if (GetSavedPlayerCount() != GetLinkPlayerCount_2())\n        {\n            ShowFieldAutoScrollMessage(gText_ConfirmLinkWhenPlayersReady);\n            gTasks[taskId].func = Task_LinkupConfirmWhenReady;\n        }\n        else if (JOY_HELD(B_BUTTON))\n        {\n            ShowFieldAutoScrollMessage(gText_ConfirmLinkWhenPlayersReady);\n            gTasks[taskId].func = Task_LinkupConfirmWhenReady;\n        }\n        else if (JOY_HELD(A_BUTTON))\n        {\n            PlaySE(SE_SELECT);\n            CheckShouldAdvanceLinkState();\n            gTasks[taskId].func = Task_LinkupConfirm;\n        }\n    }",
  },
  "Task_ReconnectWithLinkPlayers": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["CheckShouldAdvanceLinkState","CreateTask","DestroyTask","GetLinkPlayerCount_2","GetSavedPlayerCount","IsLinkMaster","IsLinkPlayerDataExchangeComplete","OpenLink"],
    lineCount: 46,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n    switch (tState)\n    {\n    case 0:\n        if (gWirelessCommType != 0)\n        {\n            DestroyTask(taskId);\n        }\n        else\n        {\n            OpenLink();\n            CreateTask(Task_WaitForLinkPlayerConnection, 1);\n            tState++;\n        }\n        break;\n    case 1:\n        if (++tTimer > 11)\n        {\n            tTimer = 0;\n            tState++;\n        }\n        break;\n    case 2:\n        if (GetLinkPlayerCount_2() >= GetSavedPlayerCount())\n        {\n            if (IsLinkMaster())\n            {\n                if (++tTimer > 30)\n                {\n                    CheckShouldAdvanceLinkState();\n                    tState++;\n                }\n            }\n            else\n            {\n                tState++;\n            }\n        }\n        break;\n    case 3:\n        if (gReceivedRemoteLinkPlayers == TRUE && IsLinkPlayerDataExchangeComplete() == TRUE)\n        {\n            DestroyTask(taskId);\n        }\n        break;\n    }",
  },
  "Task_ReestablishLink": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateTask","OpenLink","ResetLinkPlayers"],
    lineCount: 12,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n    if (data[0] == 0)\n    {\n        OpenLink();\n        ResetLinkPlayers();\n        CreateTask(Task_WaitForLinkPlayerConnection, 80);\n    }\n    else if (data[0] >= 10)\n    {\n        gTasks[taskId].func = Task_ReestablishLinkAwaitConnection;\n    }\n    data[0]++;",
  },
  "Task_ReestablishLinkAwaitConfirmation": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CheckLinkPlayersMatchSaved","DestroyTask","IsLinkPlayerDataExchangeComplete","StartSendingKeysToLink"],
    lineCount: 7,
    bodyC: "if (gReceivedRemoteLinkPlayers == TRUE\n     && IsLinkPlayerDataExchangeComplete() == TRUE)\n    {\n        CheckLinkPlayersMatchSaved();\n        StartSendingKeysToLink();\n        DestroyTask(taskId);\n    }",
  },
  "Task_ReestablishLinkAwaitConnection": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["GetLinkPlayerCount_2","IsLinkMaster"],
    lineCount: 7,
    bodyC: "if (GetLinkPlayerCount_2() >= 2)\n    {\n        if (IsLinkMaster() == TRUE)\n            gTasks[taskId].func = Task_ReestablishLinkLeader;\n        else\n            gTasks[taskId].func = Task_ReestablishLinkAwaitConfirmation;\n    }",
  },
  "Task_ReestablishLinkLeader": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CheckShouldAdvanceLinkState","GetLinkPlayerCount_2","GetSavedPlayerCount"],
    lineCount: 5,
    bodyC: "if (GetSavedPlayerCount() == GetLinkPlayerCount_2())\n    {\n        CheckShouldAdvanceLinkState();\n        gTasks[taskId].func = Task_ReestablishLinkAwaitConfirmation;\n    }",
  },
  "Task_StartWiredCableClubBattle": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CleanupOverworldWindowsAndTilemaps","ClearLinkCallback_2","DestroyTask","FadeScreen","PlayMapChosenOrBattleBGM","SetCloseLinkCallback","SetLinkBattleTypeFlags","SetMainCallback2"],
    lineCount: 39,
    bodyC: "struct Task *task = &gTasks[taskId];\n\n    switch (task->tState)\n    {\n    case 0:\n        FadeScreen(FADE_TO_BLACK, 0);\n        gLinkType = LINKTYPE_BATTLE;\n        ClearLinkCallback_2();\n        task->tState++;\n        break;\n    case 1:\n        if (!gPaletteFade.active)\n            task->tState++;\n        break;\n    case 2:\n        task->tTimer++;\n        if (task->tTimer > 20)\n            task->tState++;\n        break;\n    case 3:\n        SetCloseLinkCallback();\n        task->tState++;\n        break;\n    case 4:\n        if (!gReceivedRemoteLinkPlayers)\n            task->tState++;\n        break;\n    case 5:\n        if (gLinkPlayers[0].trainerId & 1)\n            PlayMapChosenOrBattleBGM(MUS_VS_GYM_LEADER);\n        else\n            PlayMapChosenOrBattleBGM(MUS_VS_TRAINER);\n\n        SetLinkBattleTypeFlags(gSpecialVar_0x8004);\n        CleanupOverworldWindowsAndTilemaps();\n        gTrainerBattleOpponent_A = TRAINER_LINK_OPPONENT;\n        SetMainCallback2(CB2_InitBattle);\n        gMain.savedCallback = CB2_ReturnFromCableClubBattle;\n        DestroyTask(taskId);\n        break;\n    }",
  },
  "Task_StartWiredTrade": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["ClearLinkCallback_2","DestroyTask","FadeScreen","LockPlayerFieldControls","SetCloseLinkCallback","SetMainCallback2","m4aMPlayAllStop"],
    lineCount: 28,
    bodyC: "struct Task *task = &gTasks[taskId];\n\n    switch (task->tState)\n    {\n    case 0:\n        LockPlayerFieldControls();\n        FadeScreen(FADE_TO_BLACK, 0);\n        ClearLinkCallback_2();\n        task->tState++;\n        break;\n    case 1:\n        if (!gPaletteFade.active)\n            task->tState++;\n        break;\n    case 2:\n        gSelectedTradeMonPositions[TRADE_PLAYER] = 0;\n        gSelectedTradeMonPositions[TRADE_PARTNER] = 0;\n        m4aMPlayAllStop();\n        SetCloseLinkCallback();\n        task->tState++;\n        break;\n    case 3:\n        if (!gReceivedRemoteLinkPlayers)\n        {\n            SetMainCallback2(CB2_StartCreateTradeMenu);\n            DestroyTask(taskId);\n        }\n        break;\n    }",
  },
  "Task_StartWirelessCableClubBattle": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CleanupOverworldWindowsAndTilemaps","ClearLinkCallback_2","ConvertLinkPlayerName","DestroyTask","FadeScreen","GetBlockReceivedStatus","GetLinkPlayerCount","GetLinkPlayerCountAsBitFlags","IsLinkTaskFinished","PlayMapChosenOrBattleBGM","ResetBlockReceivedFlag","SendBlock","SetLinkBattleTypeFlags","SetLinkStandbyCallback","SetMainCallback2"],
    lineCount: 60,
    bodyC: "int i;\n    s16 *data = gTasks[taskId].data;\n\n    switch (tState)\n    {\n    case 0:\n        FadeScreen(FADE_TO_BLACK, 0);\n        gLinkType = LINKTYPE_BATTLE;\n        ClearLinkCallback_2();\n        tState = 1;\n        break;\n    case 1:\n        if (!gPaletteFade.active)\n            tState = 2;\n        break;\n    case 2:\n        SendBlock(0, &gLocalLinkPlayer, sizeof(gLocalLinkPlayer));\n        tState = 3;\n        break;\n    case 3:\n        if (GetBlockReceivedStatus() == GetLinkPlayerCountAsBitFlags())\n        {\n            for (i = 0; i < GetLinkPlayerCount(); i++)\n            {\n                struct LinkPlayer *player = (struct LinkPlayer *)gBlockRecvBuffer[i];\n                gLinkPlayers[i] = *player;\n                ConvertLinkPlayerName(&gLinkPlayers[i]);\n                ResetBlockReceivedFlag(i);\n            }\n            tState = 4;\n        }\n        break;\n    case 4:\n        tTimer++;\n        if (tTimer > 20)\n            tState = 5;\n        break;\n    case 5:\n        SetLinkStandbyCallback();\n        tState = 6;\n        break;\n    case 6:\n        if (IsLinkTaskFinished())\n        {\n            tState = 7;\n        }\n        break;\n    case 7:\n        if (gLinkPlayers[0].trainerId & 1)\n            PlayMapChosenOrBattleBGM(MUS_VS_GYM_LEADER);\n        else\n            PlayMapChosenOrBattleBGM(MUS_VS_TRAINER);\n\n        gLinkPlayers[0].linkType = LINKTYPE_BATTLE;\n        SetLinkBattleTypeFlags(gSpecialVar_0x8004);\n        CleanupOverworldWindowsAndTilemaps();\n        gTrainerBattleOpponent_A = TRAINER_LINK_OPPONENT;\n        SetMainCallback2(CB2_InitBattle);\n        gMain.savedCallback = CB2_ReturnFromCableClubBattle;\n        DestroyTask(taskId);\n        break;\n    }",
  },
  "Task_StartWirelessTrade": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["ClearLinkRfuCallback","CreateTask_CreateTradeMenu","DestroyTask","FadeScreen","IsLinkTaskFinished","LockPlayerFieldControls","SetLinkStandbyCallback","m4aMPlayAllStop"],
    lineCount: 28,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n    switch (tState)\n    {\n    case 0:\n        LockPlayerFieldControls();\n        FadeScreen(FADE_TO_BLACK, 0);\n        ClearLinkRfuCallback();\n        tState++;\n        break;\n    case 1:\n        if (!gPaletteFade.active)\n            tState++;\n        break;\n    case 2:\n        gSelectedTradeMonPositions[TRADE_PLAYER] = 0;\n        gSelectedTradeMonPositions[TRADE_PARTNER] = 0;\n        m4aMPlayAllStop();\n        SetLinkStandbyCallback();\n        tState++;\n        break;\n    case 3:\n        if (IsLinkTaskFinished())\n        {\n            CreateTask_CreateTradeMenu();\n            DestroyTask(taskId);\n        }\n        break;\n    }",
  },
  "Task_StopLinkup": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["ClearLinkPlayerCountWindow","DestroyTask","RemoveWindow","ScriptContext_Enable"],
    lineCount: 7,
    bodyC: "if (!gReceivedRemoteLinkPlayers)\n    {\n        ClearLinkPlayerCountWindow(gTasks[taskId].tWindowId);\n        ScriptContext_Enable();\n        RemoveWindow(gTasks[taskId].tWindowId);\n        DestroyTask(taskId);\n    }",
  },
  "Task_ValidateMixingGameLanguage": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","GetLinkPlayerCount","ScriptContext_Enable","SetCloseLinkCallbackHandleJP"],
    lineCount: 58,
    bodyC: "int playerCount;\n    int i;\n\n    switch (gTasks[taskId].tState)\n    {\n    case 0:\n        if (gSpecialVar_Result == LINKUP_SUCCESS)\n        {\n            bool32 mixingForeignGames = FALSE;\n            bool32 isEnglishRSLinked = FALSE;\n            bool32 isJapaneseEmeraldLinked = FALSE;\n\n            playerCount = GetLinkPlayerCount();\n            for (i = 0; i < playerCount; i++)\n            {\n                u32 version = (u8)gLinkPlayers[i].version;\n                u32 language = gLinkPlayers[i].language;\n\n                if (version == VERSION_RUBY || version == VERSION_SAPPHIRE)\n                {\n                    if (language == LANGUAGE_JAPANESE)\n                    {\n                        mixingForeignGames = TRUE;\n                        break;\n                    }\n                    else\n                    {\n                        isEnglishRSLinked = TRUE;\n                    }\n                }\n                else if (version == VERSION_EMERALD)\n                {\n                    if (language == LANGUAGE_JAPANESE)\n                    {\n                        isJapaneseEmeraldLinked = TRUE;\n                    }\n                }\n            }\n\n            if (isEnglishRSLinked && isJapaneseEmeraldLinked)\n            {\n                mixingForeignGames = TRUE;\n            }\n\n            if (mixingForeignGames)\n            {\n                gSpecialVar_Result = LINKUP_FOREIGN_GAME;\n                SetCloseLinkCallbackHandleJP();\n                gTasks[taskId].tState = 1;\n                return;\n            }\n        }\n        ScriptContext_Enable();\n        DestroyTask(taskId);\n        break;\n    case 1:\n        if (!gReceivedRemoteLinkPlayers)\n        {\n            ScriptContext_Enable();\n            DestroyTask(taskId);\n        }\n        break;\n    }",
  },
  "Task_WaitExitToScript": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","ScriptContext_Enable"],
    lineCount: 5,
    bodyC: "if (!gReceivedRemoteLinkPlayers)\n    {\n        ScriptContext_Enable();\n        DestroyTask(taskId);\n    }",
  },
  "Task_WaitForLinkPlayerConnection": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["CloseLink","DestroyTask","DoesLinkPlayerCountMatchSaved","SetMainCallback2"],
    lineCount: 24,
    bodyC: "struct Task *task = &gTasks[taskId];\n\n    task->tTimer++;\n    if (task->tTimer > 480)  \n    {\n        CloseLink();\n        SetMainCallback2(CB2_LinkError);\n        DestroyTask(taskId);\n    }\n\n    if (gReceivedRemoteLinkPlayers)\n    {\n         \n        if (gWirelessCommType == 0)\n        {\n            if (!DoesLinkPlayerCountMatchSaved())\n            {\n                CloseLink();\n                SetMainCallback2(CB2_LinkError);\n            }\n            DestroyTask(taskId);\n        }\n        else\n        {\n            DestroyTask(taskId);\n        }\n    }",
  },
  "TryBattleLinkup": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateLinkupTask"],
    lineCount: 26,
    bodyC: "u8 minPlayers = 2;\n    u8 maxPlayers = 2;\n\n    switch (gSpecialVar_0x8004)\n    {\n    case USING_SINGLE_BATTLE:\n        minPlayers = 2;\n        gLinkType = LINKTYPE_SINGLE_BATTLE;\n        break;\n    case USING_DOUBLE_BATTLE:\n        minPlayers = 2;\n        gLinkType = LINKTYPE_DOUBLE_BATTLE;\n        break;\n    case USING_MULTI_BATTLE:\n        minPlayers = 4;\n        maxPlayers = 4;\n        gLinkType = LINKTYPE_MULTI_BATTLE;\n        break;\n    case USING_BATTLE_TOWER:\n        minPlayers = 2;\n        if (gSaveBlock2Ptr->frontier.lvlMode == FRONTIER_LVL_50)\n            gLinkType = LINKTYPE_BATTLE_TOWER_50;\n        else\n            gLinkType = LINKTYPE_BATTLE_TOWER_OPEN;\n\n        break;\n    }\n\n    CreateLinkupTask(minPlayers, maxPlayers);",
  },
  "TryBerryBlenderLinkup": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateLinkupTask"],
    lineCount: 3,
    bodyC: "gLinkType = LINKTYPE_BERRY_BLENDER_SETUP;\n    gBattleTypeFlags = 0;\n    CreateLinkupTask(2, 4);",
  },
  "TryContestEModeLinkup": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateLinkupTask"],
    lineCount: 3,
    bodyC: "gLinkType = LINKTYPE_CONTEST_EMODE;\n    gBattleTypeFlags = 0;\n    CreateLinkupTask(2, 4);",
  },
  "TryContestGModeLinkup": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateLinkupTask"],
    lineCount: 3,
    bodyC: "gLinkType = LINKTYPE_CONTEST_GMODE;\n    gBattleTypeFlags = 0;\n    CreateLinkupTask(4, 4);",
  },
  "TryLinkTimeout": {
    returnType: "static bool8",
    params: "u8 taskId",
    lineCount: 7,
    bodyC: "gTasks[taskId].tTimer++;\n    if (gTasks[taskId].tTimer > 600)\n    {\n        gTasks[taskId].func = Task_LinkupConnectionError;\n        return TRUE;\n    }\n\n    return FALSE;",
  },
  "TryRecordMixLinkup": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateLinkupTask"],
    lineCount: 4,
    bodyC: "gSpecialVar_Result = LINKUP_ONGOING;\n    gLinkType = LINKTYPE_RECORD_MIX_BEFORE;\n    gBattleTypeFlags = 0;\n    CreateLinkupTask(2, 4);",
  },
  "TrySetBattleTowerLinkType": {
    returnType: "void",
    params: "void",
    lineCount: 2,
    bodyC: "if (gWirelessCommType == 0)\n        gLinkType = LINKTYPE_BATTLE_TOWER;",
  },
  "TryTradeLinkup": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateLinkupTask"],
    lineCount: 3,
    bodyC: "gLinkType = LINKTYPE_TRADE_SETUP;\n    gBattleTypeFlags = 0;\n    CreateLinkupTask(2, 2);",
  },
  "UpdateLinkPlayerCountDisplay": {
    returnType: "static void",
    params: "u8 taskId, u8 numPlayers",
    callsTo: ["ClearLinkPlayerCountWindow","PrintNumPlayersInLink"],
    lineCount: 9,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n    if (numPlayers != tNumPlayers)\n    {\n        if (numPlayers <= 1)\n            ClearLinkPlayerCountWindow(tWindowId);\n        else\n            PrintNumPlayersInLink(tWindowId, numPlayers);\n        tNumPlayers = numPlayers;\n    }",
  },
  "ValidateMixingGameLanguage": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateTask","FindTaskIdByFunc"],
    lineCount: 6,
    bodyC: "u32 taskId = FindTaskIdByFunc(Task_ValidateMixingGameLanguage);\n\n    if (taskId == TASK_NONE)\n    {\n        taskId = CreateTask(Task_ValidateMixingGameLanguage, 80);\n        gTasks[taskId].tState = 0;\n    }",
  },
} as const;
