// AUTO-GENERATED from src/contest_util.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 111

export const ENGINE_FUNCTIONS = {
  "AddContestTextPrinter": {
    returnType: "static void",
    params: "int windowId, u8 *str, int x",
    callsTo: ["AddTextPrinter","PutWindowTilemap"],
    lineCount: 16,
    bodyC: "struct TextPrinterTemplate textPrinter;\n    textPrinter.currentChar = str;\n    textPrinter.windowId = windowId;\n    textPrinter.fontId = FONT_NARROW;\n    textPrinter.x = x;\n    textPrinter.y = 2;\n    textPrinter.currentX = x;\n    textPrinter.currentY = 2;\n    textPrinter.letterSpacing = 0;\n    textPrinter.lineSpacing = 0;\n    textPrinter.unk = 0;\n    textPrinter.fgColor = 1;\n    textPrinter.bgColor = 0;\n    textPrinter.shadowColor = 8;\n    AddTextPrinter(&textPrinter, 0, NULL);\n    PutWindowTilemap(windowId);",
  },
  "AllocContestResults": {
    returnType: "static void",
    params: "void",
    callsTo: ["AllocZeroed","AllocateMonSpritesGfx"],
    lineCount: 10,
    bodyC: "sContestResults = AllocZeroed(sizeof(*sContestResults));\n    sContestResults->data = AllocZeroed(sizeof(*sContestResults->data));\n    sContestResults->monResults = AllocZeroed(sizeof(*sContestResults->monResults));\n    sContestResults->unusedBg = AllocZeroed(BG_SCREEN_SIZE);\n    sContestResults->tilemapBuffers[0] = AllocZeroed(BG_SCREEN_SIZE);\n    sContestResults->tilemapBuffers[1] = AllocZeroed(BG_SCREEN_SIZE);\n    sContestResults->tilemapBuffers[2] = AllocZeroed(BG_SCREEN_SIZE);\n    sContestResults->tilemapBuffers[3] = AllocZeroed(BG_SCREEN_SIZE);\n    sContestResults->unused = AllocZeroed(0x1000);\n    AllocateMonSpritesGfx();",
  },
  "BounceMonIconInBox": {
    returnType: "static void",
    params: "u8 monIndex, u8 numFrames",
    callsTo: ["CreateTask"],
    lineCount: 4,
    bodyC: "u8 taskId = CreateTask(Task_BounceMonIconInBox, 8);\n    gTasks[taskId].tMonIndex = monIndex;\n    gTasks[taskId].tNumFrames = numFrames;\n    gTasks[taskId].tSpecies = gContestMons[monIndex].species;",
  },
  "BufferContestTrainerAndMonNames": {
    returnType: "void",
    params: "void",
    callsTo: ["BufferContestantMonNickname","BufferContestantMonSpecies","BufferContestantTrainerName"],
    lineCount: 3,
    bodyC: "BufferContestantTrainerName();\n    BufferContestantMonNickname();\n    BufferContestantMonSpecies();",
  },
  "BufferContestWinnerMonName": {
    returnType: "void",
    params: "void",
    callsTo: ["GET_CONTEST_WINNER_ID","StringCopy"],
    lineCount: 3,
    bodyC: "u8 i;\n    GET_CONTEST_WINNER_ID(i);\n    StringCopy(gStringVar1, gContestMons[i].nickname);",
  },
  "BufferContestWinnerTrainerName": {
    returnType: "void",
    params: "void",
    callsTo: ["ConvertInternationalContestantName","GET_CONTEST_WINNER_ID","StringCopy"],
    lineCount: 4,
    bodyC: "u8 i;\n    GET_CONTEST_WINNER_ID(i);\n    StringCopy(gStringVar3, gContestMons[i].trainerName);\n    ConvertInternationalContestantName(gStringVar3);",
  },
  "BufferContestantMonNickname": {
    returnType: "void",
    params: "void",
    callsTo: ["StringCopy"],
    lineCount: 1,
    bodyC: "StringCopy(gStringVar3, gContestMons[gSpecialVar_0x8006].nickname);",
  },
  "BufferContestantMonSpecies": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "gSpecialVar_0x8004 = gContestMons[gSpecialVar_0x8006].species;",
  },
  "BufferContestantTrainerName": {
    returnType: "void",
    params: "void",
    callsTo: ["ConvertInternationalContestantName","StringCopy"],
    lineCount: 2,
    bodyC: "StringCopy(gStringVar1, gContestMons[gSpecialVar_0x8006].trainerName);\n    ConvertInternationalContestantName(gStringVar1);",
  },
  "CB2_SetStartContestCallback": {
    returnType: "void",
    params: "void",
    callsTo: ["SetMainCallback2"],
    lineCount: 1,
    bodyC: "SetMainCallback2(CB2_StartContest);",
  },
  "CB2_ShowContestResults": {
    returnType: "static void",
    params: "void",
    callsTo: ["AnimateSprites","BuildOamBuffer","CopyBgTilemapBufferToVram","RunTasks","UpdatePaletteFade"],
    lineCount: 6,
    bodyC: "AnimateSprites();\n    BuildOamBuffer();\n    RunTasks();\n    UpdatePaletteFade();\n    CopyBgTilemapBufferToVram(1);\n    CopyBgTilemapBufferToVram(2);",
  },
  "CB2_StartShowContestResults": {
    returnType: "static void",
    params: "void",
    callsTo: ["AllocContestResults","BeginNormalPaletteFade","CalculateContestantsResultData","CreateResultsTextWindowSprites","CreateTask","FreeAllSpritePalettes","InitContestResultsDisplay","LoadAllContestMonIconPalettes","LoadAllContestMonIcons","LoadAllContestMonNames","LoadContestResultsBgGfx","PlayBGM","ResetPaletteFade","ResetSpriteData","ResetTasks","ScanlineEffect_Clear","SetMainCallback2","SetVBlankCallback","TryCreateWirelessSprites","WIN_RANGE","memset"],
    lineCount: 30,
    bodyC: "gPaletteFade.bufferTransferDisabled = TRUE;\n    SetVBlankCallback(NULL);\n    AllocContestResults();\n    InitContestResultsDisplay();\n    ScanlineEffect_Clear();\n    ResetPaletteFade();\n    ResetSpriteData();\n    ResetTasks();\n    FreeAllSpritePalettes();\n    LoadContestResultsBgGfx();\n    LoadAllContestMonIconPalettes();\n    LoadAllContestMonIcons(0, TRUE);\n    LoadAllContestMonNames();\n    memset(sContestResults->data, 0, sizeof(*sContestResults->data));\n    memset(sContestResults->monResults, 0, sizeof(*sContestResults->monResults));\n    CreateResultsTextWindowSprites();\n    TryCreateWirelessSprites();\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_BLACK);\n    gPaletteFade.bufferTransferDisabled = FALSE;\n    sContestResults->data->showResultsTaskId = CreateTask(Task_ShowContestResults, 5);\n    SetMainCallback2(CB2_ShowContestResults);\n    gBattle_WIN1H = WIN_RANGE(0, DISPLAY_WIDTH);\n    gBattle_WIN1V = WIN_RANGE(DISPLAY_HEIGHT - 32, DISPLAY_HEIGHT);\n    CreateTask(Task_SlideContestResultsBg, 20);\n    CalculateContestantsResultData();\n    if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS)\n        gPaletteFade.bufferTransferDisabled = TRUE;\n    else\n        PlayBGM(MUS_CONTEST_RESULTS);\n\n    SetVBlankCallback(VBlankCB_ShowContestResults);",
  },
  "CalculateContestantsResultData": {
    returnType: "static void",
    params: "void",
    callsTo: ["GetNumPreliminaryPoints","GetNumRound2Points","abs"],
    lineCount: 57,
    bodyC: "int i, relativePoints;\n    u32 barLength;\n    s16 highestPoints;\n    s8 round2Points;\n\n    highestPoints = gContestMonTotalPoints[0];\n    for (i = 1; i < CONTESTANT_COUNT; i++)\n    {\n        if (highestPoints < gContestMonTotalPoints[i])\n            highestPoints = gContestMonTotalPoints[i];\n    }\n\n    if (highestPoints < 0)\n    {\n        highestPoints = gContestMonTotalPoints[0];\n        for (i = 1; i < CONTESTANT_COUNT; i++)\n        {\n            if (highestPoints > gContestMonTotalPoints[i])\n                highestPoints = gContestMonTotalPoints[i];\n        }\n    }\n\n    for (i = 0; i < CONTESTANT_COUNT; i++)\n    {\n        relativePoints = (gContestMonRound1Points[i] * 1000) / abs(highestPoints);\n        if (relativePoints % 10 > 4)\n            relativePoints += 10;\n        (*sContestResults->monResults)[i].relativePreliminaryPoints = relativePoints / 10;\n\n        relativePoints = (abs(gContestMonRound2Points[i]) * 1000) / abs(highestPoints);\n        if (relativePoints % 10 > 4)\n            relativePoints += 10;\n        (*sContestResults->monResults)[i].relativeRound2Points = relativePoints / 10;\n\n        if (gContestMonRound2Points[i] < 0)\n            (*sContestResults->monResults)[i].lostPoints = TRUE;\n\n        barLength = ((*sContestResults->monResults)[i].relativePreliminaryPoints * 0x5800) / 100;\n        if ((barLength & 0xFF) > 0x7F)\n            barLength += 0x100;\n        (*sContestResults->monResults)[i].barLengthPreliminary = barLength >> 8;\n\n        barLength = ((*sContestResults->monResults)[i].relativeRound2Points * 0x5800) / 100;\n        if ((barLength & 0xFF) > 0x7F)\n            barLength += 0x100;\n        (*sContestResults->monResults)[i].barLengthRound2 = barLength >> 8;\n\n        (*sContestResults->monResults)[i].numStars = GetNumPreliminaryPoints(i, TRUE);\n        round2Points = GetNumRound2Points(i, TRUE);\n        (*sContestResults->monResults)[i].numHearts = abs(round2Points);\n\n        if (gContestFinalStandings[i])\n        {\n            s16 barLengthPreliminary = (*sContestResults->monResults)[i].barLengthPreliminary;\n            s16 barLengthRound2 = (*sContestResults->monResults)[i].barLengthRound2;\n\n            if ((*sContestResults->monResults)[i].lostPoints)\n                barLengthRound2 *= -1;\n\n            if (barLengthPreliminary + barLengthRound2 == MAX_BAR_LENGTH)\n            {\n                if (barLengthRound2 > 0)\n                    (*sContestResults->monResults)[i].barLengthRound2--;\n                else if (barLengthPreliminary > 0)\n                    (*sContestResults->monResults)[i].barLengthPreliminary--;\n            }\n        }\n    }",
  },
  "ClearLinkContestFlags": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "gLinkContestFlags = 0;",
  },
  "ContestLinkTransfer": {
    returnType: "void",
    params: "u8 category",
    callsTo: ["CreateTask","LockPlayerFieldControls","SetTaskFuncWithFollowupFunc"],
    lineCount: 5,
    bodyC: "u8 newTaskId;\n    LockPlayerFieldControls();\n    newTaskId = CreateTask(Task_LinkContest_Init, 0);\n    SetTaskFuncWithFollowupFunc(newTaskId, Task_LinkContest_Init, Task_StartCommunication);\n    gTasks[newTaskId].data[9] = category;",
  },
  "CountPlayerMuseumPaintings": {
    returnType: "u8",
    params: "void",
    lineCount: 8,
    bodyC: "int i;\n    u8 count = 0;\n\n    for (i = 0; i < NUM_CONTEST_WINNERS - MUSEUM_CONTEST_WINNERS_START; i++)\n    {\n        if (gSaveBlock1Ptr->contestWinners[MUSEUM_CONTEST_WINNERS_START + i].species)\n            count++;\n    }\n\n    return count;",
  },
  "CreateResultsTextWindowSprites": {
    returnType: "static void",
    params: "void",
    callsTo: ["ARRAY_COUNT","CreateSprite","HideLinkResultsTextBox","LoadSpritePalette","LoadSpriteSheet"],
    lineCount: 22,
    bodyC: "int i;\n    struct SpriteTemplate template;\n    u8 spriteIds[ARRAY_COUNT(sSpriteSheets_ResultsTextWindow)];\n\n    template = sSpriteTemplate_ResultsTextWindow;\n    for (i = 0; i < (int)ARRAY_COUNT(sSpriteSheets_ResultsTextWindow); i++)\n        LoadSpriteSheet(&sSpriteSheets_ResultsTextWindow[i]);\n\n    LoadSpritePalette(&sSpritePalette_ResultsTextWindow);\n\n     \n    for (i = 0; i < (int)ARRAY_COUNT(sSpriteSheets_ResultsTextWindow); i++)\n    {\n        spriteIds[i] = CreateSprite(&template, TEXT_BOX_X, TEXT_BOX_Y, 10);\n        template.tileTag++;\n    }\n\n     \n    gSprites[spriteIds[0]].data[0] = spriteIds[1];\n    gSprites[spriteIds[0]].data[1] = spriteIds[2];\n    gSprites[spriteIds[0]].data[2] = spriteIds[3];\n\n     \n    gSprites[spriteIds[4]].data[0] = spriteIds[5];\n    gSprites[spriteIds[4]].data[1] = spriteIds[6];\n    gSprites[spriteIds[4]].data[2] = spriteIds[7];\n\n    sContestResults->data->slidingTextBoxSpriteId = spriteIds[0];\n    sContestResults->data->slidingTextBoxState = SLIDING_TEXT_OFFSCREEN;\n    sContestResults->data->linkTextBoxSpriteId = spriteIds[4];\n    HideLinkResultsTextBox();",
  },
  "DoesContestCategoryHaveMuseumPainting": {
    returnType: "void",
    params: "void",
    lineCount: 24,
    bodyC: "int contestWinner;\n    switch (gSpecialVar_ContestCategory)\n    {\n    case CONTEST_CATEGORY_COOL:\n        contestWinner = CONTEST_WINNER_MUSEUM_COOL - 1;\n        break;\n    case CONTEST_CATEGORY_BEAUTY:\n        contestWinner = CONTEST_WINNER_MUSEUM_BEAUTY - 1;\n        break;\n    case CONTEST_CATEGORY_CUTE:\n        contestWinner = CONTEST_WINNER_MUSEUM_CUTE - 1;\n        break;\n    case CONTEST_CATEGORY_SMART:\n        contestWinner = CONTEST_WINNER_MUSEUM_SMART - 1;\n        break;\n    case CONTEST_CATEGORY_TOUGH:\n    default:\n        contestWinner = CONTEST_WINNER_MUSEUM_TOUGH - 1;\n        break;\n    }\n\n    if (gSaveBlock1Ptr->contestWinners[contestWinner].species == SPECIES_NONE)\n        gSpecialVar_0x8004 = FALSE;\n    else\n        gSpecialVar_0x8004 = TRUE;",
  },
  "DrawResultsTextWindow": {
    returnType: "static s32",
    params: "const u8 *text, u8 spriteId",
    callsTo: ["ARRAY_COUNT","AddTextPrinterParameterized3","AddWindow","CpuCopy32","CpuFill32","FillWindowPixelBuffer","GetStringWidth","GetWindowAttribute","PIXEL_FILL","RemoveWindow","memset"],
    lineCount: 50,
    bodyC: "u16 windowId;\n    int origWidth;\n    int strWidth;\n    u8 *spriteTilePtrs[4];\n    u8 *dst;\n\n    struct WindowTemplate windowTemplate;\n    memset(&windowTemplate, 0, sizeof(windowTemplate));\n    windowTemplate.width = DISPLAY_TILE_WIDTH;\n    windowTemplate.height = 2;\n    windowId = AddWindow(&windowTemplate);\n    FillWindowPixelBuffer(windowId, PIXEL_FILL(1));\n\n    origWidth = GetStringWidth(FONT_NORMAL, text, 0);\n    strWidth = (origWidth + 9) / 8;\n    if (strWidth > 30)\n     strWidth = 30;\n\n    AddTextPrinterParameterized3(windowId, FONT_NORMAL, (strWidth * 8 - origWidth) / 2, 1, sContestLinkTextColors, TEXT_SKIP_DRAW, text);\n    {\n        s32 i;\n        struct Sprite *sprite;\n        const u8 *src, *windowTilesPtr;\n        windowTilesPtr = (u8 *)GetWindowAttribute(windowId, WINDOW_TILE_DATA);\n        src = (u8 *)sResultsTextWindow_Gfx;\n\n        sprite = &gSprites[spriteId];\n        spriteTilePtrs[0] = (u8 *)(sprite->oam.tileNum * 32 + OBJ_VRAM0);\n\n        for (i = 1; i < (int)ARRAY_COUNT(spriteTilePtrs); i++)\n            spriteTilePtrs[i] = (void *)(gSprites[sprite->data[i - 1]].oam.tileNum * 32 + OBJ_VRAM0);\n\n        for (i = 0; i < (int)ARRAY_COUNT(spriteTilePtrs); i++)\n            CpuFill32(0, spriteTilePtrs[i], 0x400);\n\n        dst = spriteTilePtrs[0];\n        CpuCopy32(src, dst, 0x20);\n        CpuCopy32(src + 128, dst + 0x100, 0x20);\n        CpuCopy32(src + 128, dst + 0x200, 0x20);\n        CpuCopy32(src + 64,  dst + 0x300, 0x20);\n\n        for (i = 0; i < strWidth; i++)\n        {\n            dst = &spriteTilePtrs[(i + 1) / 8][((i + 1) % 8) * 32];\n            CpuCopy32(src + 192, dst, 0x20);\n            CpuCopy32(windowTilesPtr, dst + 0x100, 0x20);\n            CpuCopy32(windowTilesPtr + 960, dst + 0x200, 0x20);\n            CpuCopy32(src + 224, dst + 0x300, 0x20);\n            windowTilesPtr += 0x20;\n        }\n\n        dst = &spriteTilePtrs[(i + 1) / 8][((i + 1) % 8) * 32];\n        CpuCopy32(src + 32,  dst, 0x20);\n        CpuCopy32(src + 160, dst + 0x100, 0x20);\n        CpuCopy32(src + 160, dst + 0x200, 0x20);\n        CpuCopy32(src + 96,  dst + 0x300, 0x20);\n    }\n    RemoveWindow(windowId);\n\n    return (DISPLAY_WIDTH - (strWidth + 2) * 8) / 2;",
  },
  "EndTextBoxSlideOut": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    lineCount: 6,
    bodyC: "sprite->x = TEXT_BOX_X;\n    sprite->y = TEXT_BOX_Y;\n    sprite->y2 = 0;\n    sprite->x2 = 0;\n    sprite->callback = SpriteCallbackDummy;\n    sContestResults->data->slidingTextBoxState = SLIDING_TEXT_OFFSCREEN;",
  },
  "ExitContestPainting": {
    returnType: "static void",
    params: "void",
    callsTo: ["SetMainCallback2"],
    lineCount: 1,
    bodyC: "SetMainCallback2(CB2_ReturnToFieldContinueScriptPlayMapMusic);",
  },
  "FreeContestResults": {
    returnType: "static void",
    params: "void",
    callsTo: ["FREE_AND_SET_NULL","FreeMonSpritesGfx"],
    lineCount: 10,
    bodyC: "FREE_AND_SET_NULL(sContestResults->data);\n    FREE_AND_SET_NULL(sContestResults->monResults);\n    FREE_AND_SET_NULL(sContestResults->unusedBg);\n    FREE_AND_SET_NULL(sContestResults->tilemapBuffers[0]);\n    FREE_AND_SET_NULL(sContestResults->tilemapBuffers[1]);\n    FREE_AND_SET_NULL(sContestResults->tilemapBuffers[2]);\n    FREE_AND_SET_NULL(sContestResults->tilemapBuffers[3]);\n    FREE_AND_SET_NULL(sContestResults->unused);\n    FREE_AND_SET_NULL(sContestResults);\n    FreeMonSpritesGfx();",
  },
  "GenerateContestRand": {
    returnType: "void",
    params: "void",
    callsTo: ["ISO_RANDOMIZE1","Random"],
    lineCount: 14,
    bodyC: "u16 random;\n    u16 *result;\n\n    if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n    {\n        gContestRngValue = ISO_RANDOMIZE1(gContestRngValue);\n        random = gContestRngValue >> 16;\n        result = &gSpecialVar_Result;\n    }\n    else\n    {\n        result = &gSpecialVar_Result;\n        random = Random();\n    }\n    *result = random % *result;",
  },
  "GetContestMonCondition": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "gSpecialVar_0x8004 = gContestMonRound1Points[gSpecialVar_0x8006];",
  },
  "GetContestMonConditionRanking": {
    returnType: "void",
    params: "void",
    lineCount: 7,
    bodyC: "u8 i, rank;\n\n    for (i = 0, rank = 0; i < CONTESTANT_COUNT; i++)\n    {\n        if (gContestMonRound1Points[gSpecialVar_0x8006] < gContestMonRound1Points[i])\n            rank++;\n    }\n\n    gSpecialVar_0x8004 = rank;",
  },
  "GetContestMultiplayerId": {
    returnType: "void",
    params: "void",
    callsTo: ["GetMultiplayerId"],
    lineCount: 6,
    bodyC: "if ((gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n        && gNumLinkContestPlayers == CONTESTANT_COUNT\n        && !(gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS))\n        gSpecialVar_Result = GetMultiplayerId();\n    else\n        gSpecialVar_Result = MAX_LINK_PLAYERS;",
  },
  "GetContestPlayerId": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "gSpecialVar_0x8004 = gContestPlayerMonIndex;",
  },
  "GetContestRand": {
    returnType: "u16",
    params: "void",
    callsTo: ["ISO_RANDOMIZE1"],
    lineCount: 2,
    bodyC: "gContestRngValue = ISO_RANDOMIZE1(gContestRngValue);\n    return gContestRngValue >> 16;",
  },
  "GetContestWinnerId": {
    returnType: "void",
    params: "void",
    callsTo: ["GET_CONTEST_WINNER_ID"],
    lineCount: 3,
    bodyC: "u8 i;\n    GET_CONTEST_WINNER_ID(i);\n    gSpecialVar_0x8005 = i;",
  },
  "GetContestantNamesAtRank": {
    returnType: "void",
    params: "void",
    callsTo: ["ConvertInternationalContestantName","SWAP","StringCopy"],
    lineCount: 57,
    bodyC: "s16 conditions[CONTESTANT_COUNT];\n    int i, j;\n    s16 condition;\n    s8 numAtCondition;\n    u8 contestantOffset;\n    u8 tieRank;\n    u8 rank;\n\n     \n    for (i = 0; i < CONTESTANT_COUNT; i++)\n        conditions[i] = gContestMonRound1Points[i];\n\n     \n    for (i = 0; i < CONTESTANT_COUNT - 1; i++)\n    {\n        for (j = CONTESTANT_COUNT - 1; j > i; j--)\n        {\n            if (conditions[j - 1] < conditions[j])\n            {\n                int temp;\n                SWAP(conditions[j], conditions[j - 1], temp)\n            }\n        }\n    }\n\n     \n    condition = conditions[gSpecialVar_0x8006];\n\n     \n    numAtCondition = 0;\n    tieRank = 0;\n    for (i = 0; i < CONTESTANT_COUNT; i++)\n    {\n        if (conditions[i] == condition)\n        {\n            numAtCondition++;\n            if (i == gSpecialVar_0x8006)\n                tieRank = numAtCondition;\n        }\n    }\n\n     \n    for (i = 0; i < CONTESTANT_COUNT; i++)\n    {\n        if (conditions[i] == condition)\n            break;\n    }\n    rank = i;\n\n     \n    contestantOffset = tieRank;\n    for (i = 0; i < CONTESTANT_COUNT; i++)\n    {\n        if (condition == gContestMonRound1Points[i])\n        {\n            if (contestantOffset == 1)\n                break;\n            contestantOffset--;\n        }\n    }\n\n     \n    StringCopy(gStringVar1, gContestMons[i].nickname);\n    StringCopy(gStringVar2, gContestMons[i].trainerName);\n    ConvertInternationalContestantName(gStringVar2);\n\n     \n    if (numAtCondition == 1)\n        gSpecialVar_0x8006 = rank;\n    else if (tieRank == numAtCondition)\n        gSpecialVar_0x8006 = rank;\n    else\n        gSpecialVar_0x8006 = rank + CONTESTANT_COUNT;",
  },
  "GetNpcContestantLocalId": {
    returnType: "void",
    params: "void",
    lineCount: 18,
    bodyC: "u16 localId;\n    u8 contestant = gSpecialVar_0x8005;\n    switch (contestant)\n    {\n    case 0:\n        localId = LOCALID_CONTESTANT_1;\n        break;\n    case 1:\n        localId = LOCALID_CONTESTANT_2;\n        break;\n    case 2:\n        localId = LOCALID_CONTESTANT_3;\n        break;\n    default:  \n        localId = 100;\n        break;\n    }\n\n    gSpecialVar_0x8004 = localId;",
  },
  "GetNumPreliminaryPoints": {
    returnType: "static u8",
    params: "u8 monIndex, bool8 capPoints",
    lineCount: 10,
    bodyC: "u32 condition = gContestMonRound1Points[monIndex] << 16;\n    u32 numStars = condition / 0x3F;\n\n    if (numStars & 0xFFFF)\n        numStars += 0x10000;\n\n    numStars >>= 16;\n    if (numStars == 0 && condition)\n        numStars = 1;\n\n    if (capPoints && numStars > 10)\n        numStars = 10;\n\n    return numStars;",
  },
  "GetNumRound2Points": {
    returnType: "static s8",
    params: "u8 monIndex, bool8 capPoints",
    lineCount: 21,
    bodyC: "u32 r4, numHearts;\n    s16 results;\n    s8 points;\n\n    results = gContestMonRound2Points[monIndex];\n    if (results < 0)\n        r4 = -results << 16;\n    else\n        r4 = results << 16;\n\n    numHearts = r4 / 80;\n    if (numHearts & 0xFFFF)\n        numHearts += 0x10000;\n\n    numHearts >>= 16;\n    if (numHearts == 0 && r4 != 0)\n        numHearts = 1;\n\n    if (capPoints && numHearts > 10)\n        numHearts = 10;\n\n    if (gContestMonRound2Points[monIndex] < 0)\n        points = -numHearts;\n    else\n        points = numHearts;\n\n    return points;",
  },
  "GiveMonArtistRibbon": {
    returnType: "bool8",
    params: "void",
    callsTo: ["GetMonData","GetRibbonCount","SetMonData","TryPutSpotTheCutiesOnAir"],
    lineCount: 17,
    bodyC: "u8 hasArtistRibbon;\n\n    hasArtistRibbon = GetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_ARTIST_RIBBON);\n    if (!hasArtistRibbon\n        && gContestFinalStandings[gContestPlayerMonIndex] == 0\n        && gSpecialVar_ContestRank == CONTEST_RANK_MASTER\n        && gContestMonTotalPoints[gContestPlayerMonIndex] >= 800)\n    {\n        hasArtistRibbon = 1;\n        SetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_ARTIST_RIBBON, &hasArtistRibbon);\n        if (GetRibbonCount(&gPlayerParty[gContestMonPartyIndex]) > NUM_CUTIES_RIBBONS)\n            TryPutSpotTheCutiesOnAir(&gPlayerParty[gContestMonPartyIndex], MON_DATA_ARTIST_RIBBON);\n\n        return TRUE;\n    }\n    else\n    {\n        return FALSE;\n    }",
  },
  "GiveMonContestRibbon": {
    returnType: "void",
    params: "void",
    callsTo: ["GetMonData","GetRibbonCount","SetMonData","TryPutSpotTheCutiesOnAir"],
    lineCount: 56,
    bodyC: "u8 ribbonData;\n\n    if (gContestFinalStandings[gContestPlayerMonIndex] != 0)\n        return;\n\n    switch (gSpecialVar_ContestCategory)\n    {\n    case CONTEST_CATEGORY_COOL:\n        ribbonData = GetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_COOL_RIBBON);\n        if (ribbonData <= gSpecialVar_ContestRank && ribbonData <= CONTEST_RANK_MASTER)\n        {\n            ribbonData++;\n            SetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_COOL_RIBBON, &ribbonData);\n            if (GetRibbonCount(&gPlayerParty[gContestMonPartyIndex]) > NUM_CUTIES_RIBBONS)\n                TryPutSpotTheCutiesOnAir(&gPlayerParty[gContestMonPartyIndex], MON_DATA_COOL_RIBBON);\n        }\n        break;\n    case CONTEST_CATEGORY_BEAUTY:\n        ribbonData = GetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_BEAUTY_RIBBON);\n        if (ribbonData <= gSpecialVar_ContestRank && ribbonData <= CONTEST_RANK_MASTER)\n        {\n            ribbonData++;\n            SetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_BEAUTY_RIBBON, &ribbonData);\n            if (GetRibbonCount(&gPlayerParty[gContestMonPartyIndex]) > NUM_CUTIES_RIBBONS)\n                TryPutSpotTheCutiesOnAir(&gPlayerParty[gContestMonPartyIndex], MON_DATA_BEAUTY_RIBBON);\n        }\n        break;\n    case CONTEST_CATEGORY_CUTE:\n        ribbonData = GetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_CUTE_RIBBON);\n        if (ribbonData <= gSpecialVar_ContestRank && ribbonData <= CONTEST_RANK_MASTER)\n        {\n            ribbonData++;\n            SetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_CUTE_RIBBON, &ribbonData);\n            if (GetRibbonCount(&gPlayerParty[gContestMonPartyIndex]) > NUM_CUTIES_RIBBONS)\n                TryPutSpotTheCutiesOnAir(&gPlayerParty[gContestMonPartyIndex], MON_DATA_CUTE_RIBBON);\n        }\n        break;\n    case CONTEST_CATEGORY_SMART:\n        ribbonData = GetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_SMART_RIBBON);\n        if (ribbonData <= gSpecialVar_ContestRank && ribbonData <= CONTEST_RANK_MASTER)\n        {\n            ribbonData++;\n            SetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_SMART_RIBBON, &ribbonData);\n            if (GetRibbonCount(&gPlayerParty[gContestMonPartyIndex]) > NUM_CUTIES_RIBBONS)\n                TryPutSpotTheCutiesOnAir(&gPlayerParty[gContestMonPartyIndex], MON_DATA_SMART_RIBBON);\n        }\n        break;\n    case CONTEST_CATEGORY_TOUGH:\n        ribbonData = GetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_TOUGH_RIBBON);\n        if (ribbonData <= gSpecialVar_ContestRank && ribbonData <= CONTEST_RANK_MASTER)\n        {\n            ribbonData++;\n            SetMonData(&gPlayerParty[gContestMonPartyIndex], MON_DATA_TOUGH_RIBBON, &ribbonData);\n            if (GetRibbonCount(&gPlayerParty[gContestMonPartyIndex]) > NUM_CUTIES_RIBBONS)\n                TryPutSpotTheCutiesOnAir(&gPlayerParty[gContestMonPartyIndex], MON_DATA_TOUGH_RIBBON);\n        }\n        break;\n    }",
  },
  "HasMonWonThisContestBefore": {
    returnType: "u16",
    params: "void",
    callsTo: ["GetMonData"],
    lineCount: 26,
    bodyC: "u16 hasRankRibbon = FALSE;\n    struct Pokemon *mon = &gPlayerParty[gContestMonPartyIndex];\n    switch (gSpecialVar_ContestCategory)\n    {\n    case CONTEST_CATEGORY_COOL:\n        if (GetMonData(mon, MON_DATA_COOL_RIBBON) > gSpecialVar_ContestRank)\n            hasRankRibbon = TRUE;\n        break;\n    case CONTEST_CATEGORY_BEAUTY:\n        if (GetMonData(mon, MON_DATA_BEAUTY_RIBBON) > gSpecialVar_ContestRank)\n            hasRankRibbon = TRUE;\n        break;\n    case CONTEST_CATEGORY_CUTE:\n        if (GetMonData(mon, MON_DATA_CUTE_RIBBON) > gSpecialVar_ContestRank)\n            hasRankRibbon = TRUE;\n        break;\n    case CONTEST_CATEGORY_SMART:\n        if (GetMonData(mon, MON_DATA_SMART_RIBBON) > gSpecialVar_ContestRank)\n            hasRankRibbon = TRUE;\n        break;\n    case CONTEST_CATEGORY_TOUGH:\n        if (GetMonData(mon, MON_DATA_TOUGH_RIBBON) > gSpecialVar_ContestRank)\n            hasRankRibbon = TRUE;\n        break;\n    }\n\n    return hasRankRibbon;",
  },
  "HideContestEntryMonPic": {
    returnType: "void",
    params: "void",
    callsTo: ["FindTaskIdByFunc","FreeMonSpritesGfx"],
    lineCount: 6,
    bodyC: "u8 taskId = FindTaskIdByFunc(Task_ShowContestEntryMonPic);\n    if (taskId != TASK_NONE)\n    {\n        gTasks[taskId].data[0]++;\n        FreeMonSpritesGfx();\n    }",
  },
  "HideLinkResultsTextBox": {
    returnType: "static void",
    params: "void",
    callsTo: ["SetGpuReg"],
    lineCount: 12,
    bodyC: "int i;\n    struct Sprite *sprite;\n\n    sprite = &gSprites[sContestResults->data->linkTextBoxSpriteId];\n    sprite->invisible = TRUE;\n    for (i = 0; i < 3; i++)\n        gSprites[sprite->data[i]].invisible = TRUE;\n\n    gBattle_WIN0H = 0;\n    gBattle_WIN0V = 0;\n    SetGpuReg(REG_OFFSET_WIN0H, gBattle_WIN0H);\n    SetGpuReg(REG_OFFSET_WIN0V, gBattle_WIN0V);\n    SetGpuReg(REG_OFFSET_WININ, WININ_WIN0_BG_ALL | WININ_WIN0_OBJ | WININ_WIN0_CLR\n        | WININ_WIN1_BG_ALL | WININ_WIN1_OBJ | WININ_WIN1_CLR);",
  },
  "InitContestResultsDisplay": {
    returnType: "static void",
    params: "void",
    callsTo: ["ARRAY_COUNT","DeactivateAllTextPrinters","InitBgsFromTemplates","InitWindows","ResetBgsAndClearDma3BusyFlags","SetBgTilemapBuffer","SetGpuReg","SetGpuRegBits"],
    lineCount: 39,
    bodyC: "int i;\n\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_1D_MAP);\n    ResetBgsAndClearDma3BusyFlags(0);\n    InitBgsFromTemplates(0, sBgTemplates, ARRAY_COUNT(sBgTemplates));\n    for (i = 0; i < (int)ARRAY_COUNT(sContestResults->tilemapBuffers); i++)\n        SetBgTilemapBuffer(i, sContestResults->tilemapBuffers[i]);\n\n    InitWindows(sWindowTemplates);\n    DeactivateAllTextPrinters();\n    SetGpuReg(REG_OFFSET_MOSAIC, 0);\n    SetGpuReg(REG_OFFSET_WININ, WININ_WIN0_BG_ALL | WININ_WIN0_OBJ | WININ_WIN0_CLR | WININ_WIN1_BG_ALL | WININ_WIN1_OBJ | WININ_WIN1_CLR);\n    SetGpuReg(REG_OFFSET_WINOUT, WINOUT_WIN01_BG1 | WINOUT_WIN01_BG2 | WINOUT_WIN01_BG3 | WINOUT_WIN01_CLR | WINOUT_WINOBJ_BG_ALL | WINOUT_WINOBJ_OBJ | WINOUT_WINOBJ_CLR);\n    SetGpuReg(REG_OFFSET_WIN0H, 0);\n    SetGpuReg(REG_OFFSET_WIN0V, 0);\n    SetGpuReg(REG_OFFSET_WIN1H, 0);\n    SetGpuReg(REG_OFFSET_WIN1V, 0);\n    SetGpuReg(REG_OFFSET_BLDCNT, 0);\n    SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n    SetGpuReg(REG_OFFSET_BLDY, 0);\n    SetGpuReg(REG_OFFSET_BG0HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG0VOFS, 0);\n    SetGpuReg(REG_OFFSET_BG1HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG1VOFS, 0);\n    SetGpuReg(REG_OFFSET_BG2HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG2VOFS, 0);\n    SetGpuReg(REG_OFFSET_BG3HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG3VOFS, 0);\n    SetGpuRegBits(REG_OFFSET_DISPCNT, DISPCNT_BG_ALL_ON | DISPCNT_OBJ_ON | DISPCNT_WIN0_ON | DISPCNT_WIN1_ON | DISPCNT_OBJWIN_ON);\n    gBattle_BG0_X = 0;\n    gBattle_BG0_Y = 0;\n    gBattle_BG1_X = 0;\n    gBattle_BG1_Y = 0;\n    gBattle_BG2_X = 0;\n    gBattle_BG2_Y = 0;\n    gBattle_BG3_X = 0;\n    gBattle_BG3_Y = 0;\n    gBattle_WIN0H = 0;\n    gBattle_WIN0V = 0;\n    gBattle_WIN1H = 0;\n    gBattle_WIN1V = 0;",
  },
  "IsContestDebugActive": {
    returnType: "bool8",
    params: "void",
    lineCount: 1,
    bodyC: "return FALSE;",
  },
  "IsContestWithRSPlayer": {
    returnType: "bool8",
    params: "void",
    lineCount: 4,
    bodyC: "if (gLinkContestFlags & LINK_CONTEST_FLAG_HAS_RS_PLAYER)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "IsWirelessContest": {
    returnType: "bool8",
    params: "void",
    lineCount: 4,
    bodyC: "if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "LinkContestTryHideWirelessIndicator": {
    returnType: "void",
    params: "void",
    callsTo: ["DestroyWirelessStatusIndicatorSprite"],
    lineCount: 5,
    bodyC: "if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS)\n    {\n        if (gReceivedRemoteLinkPlayers)\n            DestroyWirelessStatusIndicatorSprite();\n    }",
  },
  "LinkContestTryShowWirelessIndicator": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateWirelessStatusIndicatorSprite","LoadWirelessStatusIndicatorSpriteGfx"],
    lineCount: 8,
    bodyC: "if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS)\n    {\n        if (gReceivedRemoteLinkPlayers)\n        {\n            LoadWirelessStatusIndicatorSpriteGfx();\n            CreateWirelessStatusIndicatorSprite(8, 8);\n        }\n    }",
  },
  "LinkContestWaitForConnection": {
    returnType: "bool8",
    params: "void",
    callsTo: ["CreateTask"],
    lineCount: 9,
    bodyC: "if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS)\n    {\n        CreateTask(Task_LinkContestWaitForConnection, 5);\n        return TRUE;\n    }\n    else\n    {\n        return FALSE;\n    }",
  },
  "LinkContest_GetLeaderIndex": {
    returnType: "u8",
    params: "u8 *ids",
    lineCount: 8,
    bodyC: "int i;\n    u8 leaderIdx = 0;\n\n    for (i = 1; i < gNumLinkContestPlayers; i++)\n    {\n        if (ids[leaderIdx] < ids[i])\n            leaderIdx = i;\n    }\n\n    return leaderIdx;",
  },
  "LoadAllContestMonIconPalettes": {
    returnType: "static void",
    params: "void",
    callsTo: ["BG_PLTT_ID","GetIconSpecies","LoadPalette"],
    lineCount: 6,
    bodyC: "int i, species;\n\n    for (i = 0; i < CONTESTANT_COUNT; i++)\n    {\n        species = gContestMons[i].species;\n        LoadPalette(gMonIconPalettes[gMonIconPaletteIndices[GetIconSpecies(species, 0)]], BG_PLTT_ID(10 + i), PLTT_SIZE_4BPP);\n    }",
  },
  "LoadAllContestMonIcons": {
    returnType: "static void",
    params: "u8 srcOffset, bool8 useDmaNow",
    callsTo: ["LoadContestMonIcon"],
    lineCount: 3,
    bodyC: "int i;\n\n    for (i = 0; i < CONTESTANT_COUNT; i++)\n        LoadContestMonIcon(gContestMons[i].species, i, srcOffset, useDmaNow, gContestMons[i].personality);",
  },
  "LoadAllContestMonNames": {
    returnType: "static void",
    params: "void",
    callsTo: ["CopyBgTilemapBufferToVram","LoadContestMonName"],
    lineCount: 4,
    bodyC: "int i;\n\n    for (i = 0; i < CONTESTANT_COUNT; i++)\n        LoadContestMonName(i);\n\n    CopyBgTilemapBufferToVram(1);",
  },
  "LoadContestMonIcon": {
    returnType: "static void",
    params: "u16 species, u8 monIndex, u8 srcOffset, u8 useDmaNow, u32 personality",
    callsTo: ["BG_CHAR_ADDR","GetMonIconPtr","RequestDma3Copy","WriteSequenceToBgTilemapBuffer"],
    lineCount: 19,
    bodyC: "const u8 *iconPtr;\n    u16 var0, var1, frameNum;\n\n    if (monIndex == gContestPlayerMonIndex)\n        frameNum = 1;\n    else\n        frameNum = 0;\n\n    iconPtr = GetMonIconPtr(species, personality, frameNum);\n    iconPtr += srcOffset * 0x200 + 0x80;\n    if (useDmaNow)\n    {\n        RequestDma3Copy(iconPtr, (void *)BG_CHAR_ADDR(1) + monIndex * 0x200, 0x180, 1);\n        var0 = ((monIndex + 10) << 12);\n        var1 = (monIndex * 0x10 + 0x200);\n        WriteSequenceToBgTilemapBuffer(1, var1 | var0, 3, monIndex * 3 + 4, 4, 3, 17, 1);\n    }\n    else\n    {\n        RequestDma3Copy(iconPtr, (void *)BG_CHAR_ADDR(1) + monIndex * 0x200, 0x180, 1);\n    }",
  },
  "LoadContestMonName": {
    returnType: "static void",
    params: "u8 monIndex",
    callsTo: ["AddContestTextPrinter","StringAppend","StringCopy"],
    lineCount: 9,
    bodyC: "struct ContestPokemon *mon = &gContestMons[monIndex];\n    u8 *str = gDisplayedStringBattle;\n    if (monIndex == gContestPlayerMonIndex)\n        str = StringCopy(gDisplayedStringBattle, gText_ColorDarkGray);\n\n    StringCopy(str, mon->nickname);\n    AddContestTextPrinter(monIndex, gDisplayedStringBattle, 0);\n    StringCopy(str, gText_Slash);\n    StringAppend(str, mon->trainerName);\n    AddContestTextPrinter(monIndex, gDisplayedStringBattle, 50);",
  },
  "LoadContestResultsBgGfx": {
    returnType: "static void",
    params: "void",
    callsTo: ["BG_CHAR_ADDR","BG_PLTT_ID","CopyBgTilemapBufferToVram","CopyToBgTilemapBuffer","FillBgTilemapBufferRect_Palette0","GetNumPreliminaryPoints","GetNumRound2Points","LZDecompressVram","LoadCompressedPalette","LoadContestResultsTitleBarTilemaps","LoadPalette","ShowBg","abs"],
    lineCount: 41,
    bodyC: "int i, j;\n    s8 numStars, round2Points;\n    u16 tile1, tile2;\n\n    LZDecompressVram(gContestResults_Gfx, (void *)BG_CHAR_ADDR(0));\n    CopyToBgTilemapBuffer(3, gContestResults_Bg_Tilemap, 0, 0);\n    CopyToBgTilemapBuffer(2, gContestResults_Interface_Tilemap, 0, 0);\n    CopyToBgTilemapBuffer(0, gContestResults_WinnerBanner_Tilemap, 0, 0);\n    LoadContestResultsTitleBarTilemaps();\n    LoadCompressedPalette(gContestResults_Pal, BG_PLTT_OFFSET, BG_PLTT_SIZE);\n    LoadPalette(sResultsTextWindow_Pal, BG_PLTT_ID(15), sizeof(sResultsTextWindow_Pal));\n\n    for (i = 0; i < CONTESTANT_COUNT; i++)\n    {\n        numStars = GetNumPreliminaryPoints(i, TRUE);\n        round2Points = GetNumRound2Points(i, TRUE);\n        for (j = 0; j < 10; j++)\n        {\n            tile1 = 0x60B2;\n            if (j < numStars)\n                tile1 += 2;\n\n             \n            if (j < abs(round2Points))\n            {\n                tile2 = 0x60A4;\n                if (round2Points < 0)\n                    tile2 += 2;\n            }\n            else\n            {\n                tile2 = 0x60A2;\n            }\n\n            FillBgTilemapBufferRect_Palette0(1, tile1, j + 19, i * 3 + 5, 1, 1);\n            FillBgTilemapBufferRect_Palette0(1, tile2, j + 19, i * 3 + 6, 1, 1);\n        }\n    }\n\n    CopyBgTilemapBufferToVram(0);\n    CopyBgTilemapBufferToVram(1);\n    CopyBgTilemapBufferToVram(2);\n    CopyBgTilemapBufferToVram(3);\n    ShowBg(0);\n    ShowBg(1);\n    ShowBg(2);\n    ShowBg(3);",
  },
  "LoadContestResultsTitleBarTilemaps": {
    returnType: "void",
    params: "void",
    callsTo: ["CopyToBgTilemapBufferRect","CopyToBgTilemapBufferRect_ChangePalette"],
    lineCount: 48,
    bodyC: "u8 palette;\n\n    if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n    {\n        CopyToBgTilemapBufferRect(2, gContestResultsTitle_Link_Tilemap, 17, 1, 6, 2);\n    }\n    else if (gSpecialVar_ContestRank == CONTEST_RANK_NORMAL)\n    {\n        CopyToBgTilemapBufferRect(2, gContestResultsTitle_Normal_Tilemap, 17, 1, 10, 2);\n    }\n    else if (gSpecialVar_ContestRank == CONTEST_RANK_SUPER)\n    {\n        CopyToBgTilemapBufferRect(2, gContestResultsTitle_Super_Tilemap, 17, 1, 10, 2);\n    }\n    else if (gSpecialVar_ContestRank == CONTEST_RANK_HYPER)\n    {\n        CopyToBgTilemapBufferRect(2, gContestResultsTitle_Hyper_Tilemap, 17, 1, 10, 2);\n    }\n    else  \n    {\n        CopyToBgTilemapBufferRect(2, gContestResultsTitle_Master_Tilemap, 17, 1, 10, 2);\n    }\n\n    if (gSpecialVar_ContestCategory == CONTEST_CATEGORY_COOL)\n    {\n        palette = 0;\n        CopyToBgTilemapBufferRect(2, gContestResultsTitle_Cool_Tilemap, 10, 1, 7, 2);\n    }\n    else if (gSpecialVar_ContestCategory == CONTEST_CATEGORY_BEAUTY)\n    {\n        palette = 1;\n        CopyToBgTilemapBufferRect(2, gContestResultsTitle_Beauty_Tilemap, 10, 1, 7, 2);\n    }\n    else if (gSpecialVar_ContestCategory == CONTEST_CATEGORY_CUTE)\n    {\n        palette = 2;\n        CopyToBgTilemapBufferRect(2, gContestResultsTitle_Cute_Tilemap, 10, 1, 7, 2);\n    }\n    else if (gSpecialVar_ContestCategory == CONTEST_CATEGORY_SMART)\n    {\n        palette = 3;\n        CopyToBgTilemapBufferRect(2, gContestResultsTitle_Smart_Tilemap, 10, 1, 7, 2);\n    }\n    else  \n    {\n        palette = 4;\n        CopyToBgTilemapBufferRect(2, gContestResultsTitle_Tough_Tilemap, 10, 1, 7, 2);\n    }\n\n    CopyToBgTilemapBufferRect(2, gContestResultsTitle_Tilemap, 5, 1, 5, 2);\n    CopyToBgTilemapBufferRect_ChangePalette(2, sContestResults->tilemapBuffers[2], 0, 0, 32, 4, palette);",
  },
  "LoadLinkContestPlayerPalettes": {
    returnType: "void",
    params: "void",
    callsTo: ["GetObjectEventIdByLocalIdAndMap","LoadPalette","OBJ_PLTT_ID"],
    lineCount: 35,
    bodyC: "int i;\n    u8 objectEventId;\n    int version;\n    struct Sprite *sprite;\n    static const u8 sContestantLocalIds[CONTESTANT_COUNT] = {\n        LOCALID_CONTESTANT_1,\n        LOCALID_CONTESTANT_2,\n        LOCALID_CONTESTANT_3,\n        LOCALID_CONTESTANT_4,\n    };\n\n    gReservedSpritePaletteCount = 12;\n    if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n    {\n        for (i = 0; i < gNumLinkContestPlayers; i++)\n        {\n            objectEventId = GetObjectEventIdByLocalIdAndMap(sContestantLocalIds[i], gSaveBlock1Ptr->location.mapNum, gSaveBlock1Ptr->location.mapGroup);\n            sprite = &gSprites[gObjectEvents[objectEventId].spriteId];\n            sprite->oam.paletteNum = 6 + i;\n            version = (u8)gLinkPlayers[i].version;\n            if (version == VERSION_RUBY || version == VERSION_SAPPHIRE)\n            {\n                if (gLinkPlayers[i].gender == MALE)\n                    LoadPalette(gObjectEventPal_RubySapphireBrendan, OBJ_PLTT_ID(6 + i), PLTT_SIZE_4BPP);\n                else\n                    LoadPalette(gObjectEventPal_RubySapphireMay, OBJ_PLTT_ID(6 + i), PLTT_SIZE_4BPP);\n            }\n            else\n            {\n                if (gLinkPlayers[i].gender == MALE)\n                    LoadPalette(gObjectEventPal_Brendan, OBJ_PLTT_ID(6 + i), PLTT_SIZE_4BPP);\n                else\n                    LoadPalette(gObjectEventPal_May, OBJ_PLTT_ID(6 + i), PLTT_SIZE_4BPP);\n            }\n        }\n    }",
  },
  "SaveMuseumContestPainting": {
    returnType: "void",
    params: "void",
    callsTo: ["SaveContestWinner"],
    lineCount: 1,
    bodyC: "SaveContestWinner(CONTEST_SAVE_FOR_MUSEUM);",
  },
  "SetContestTrainerGfxIds": {
    returnType: "void",
    params: "void",
    lineCount: 3,
    bodyC: "gSaveBlock1Ptr->vars[VAR_OBJ_GFX_ID_0 - VARS_START] = gContestMons[0].trainerGfxId;\n    gSaveBlock1Ptr->vars[VAR_OBJ_GFX_ID_1 - VARS_START] = gContestMons[1].trainerGfxId;\n    gSaveBlock1Ptr->vars[VAR_OBJ_GFX_ID_2 - VARS_START] = gContestMons[2].trainerGfxId;",
  },
  "SetLinkContestPlayerGfx": {
    returnType: "void",
    params: "void",
    callsTo: ["VarSet"],
    lineCount: 19,
    bodyC: "int i;\n\n    if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n    {\n        for (i = 0; i < gNumLinkContestPlayers; i++)\n        {\n            int version = (u8)gLinkPlayers[i].version;\n            if (version == VERSION_RUBY || version == VERSION_SAPPHIRE)\n            {\n                if (gLinkPlayers[i].gender == MALE)\n                    gContestMons[i].trainerGfxId = OBJ_EVENT_GFX_LINK_RS_BRENDAN;\n                else\n                    gContestMons[i].trainerGfxId = OBJ_EVENT_GFX_LINK_RS_MAY;\n            }\n        }\n\n        VarSet(VAR_OBJ_GFX_ID_0, gContestMons[0].trainerGfxId);\n        VarSet(VAR_OBJ_GFX_ID_1, gContestMons[1].trainerGfxId);\n        VarSet(VAR_OBJ_GFX_ID_2, gContestMons[2].trainerGfxId);\n        VarSet(VAR_OBJ_GFX_ID_3, gContestMons[3].trainerGfxId);\n    }",
  },
  "ShouldReadyContestArtist": {
    returnType: "void",
    params: "void",
    lineCount: 10,
    bodyC: "if (gContestFinalStandings[gContestPlayerMonIndex] == 0\n     && gSpecialVar_ContestRank == CONTEST_RANK_MASTER\n     && gContestMonTotalPoints[gContestPlayerMonIndex] >= 800)\n    {\n        gSpecialVar_0x8004 = TRUE;\n    }\n    else\n    {\n        gSpecialVar_0x8004 = FALSE;\n    }",
  },
  "ShowContestEntryMonPic": {
    returnType: "void",
    params: "void",
    callsTo: ["AllocateMonSpritesGfx","CreateSprite","CreateTask","DoMonFrontSpriteAnimation","FindTaskIdByFunc","GetMonSpritePalStructFromOtIdPersonality","HandleLoadSpecialPokePic_2","HandleLoadSpecialPokePic_DontHandleDeoxys","LoadCompressedSpritePalette","SetMultiuseSpriteTemplateToPokemon"],
    lineCount: 41,
    bodyC: "const struct CompressedSpritePalette *palette;\n    u32 personality, otId;\n    u16 species;\n    u8 spriteId;\n    u8 taskId;\n    u8 left, top;\n\n    if (FindTaskIdByFunc(Task_ShowContestEntryMonPic) == TASK_NONE)\n    {\n        AllocateMonSpritesGfx();\n        left = 10;\n        top = 3;\n        species = gContestMons[gSpecialVar_0x8006].species;\n        personality = gContestMons[gSpecialVar_0x8006].personality;\n        otId = gContestMons[gSpecialVar_0x8006].otId;\n        taskId = CreateTask(Task_ShowContestEntryMonPic, 0x50);\n        gTasks[taskId].data[0] = 0;\n        gTasks[taskId].data[1] = species;\n        if (gSpecialVar_0x8006 == gContestPlayerMonIndex)\n            HandleLoadSpecialPokePic_2(&gMonFrontPicTable[species], gMonSpritesGfxPtr->sprites.ptr[B_POSITION_OPPONENT_LEFT], species, personality);\n        else\n            HandleLoadSpecialPokePic_DontHandleDeoxys(&gMonFrontPicTable[species], gMonSpritesGfxPtr->sprites.ptr[B_POSITION_OPPONENT_LEFT], species, personality);\n\n        palette = GetMonSpritePalStructFromOtIdPersonality(species, otId, personality);\n        LoadCompressedSpritePalette(palette);\n        SetMultiuseSpriteTemplateToPokemon(species, B_POSITION_OPPONENT_LEFT);\n        gMultiuseSpriteTemplate.paletteTag = palette->tag;\n        spriteId = CreateSprite(&gMultiuseSpriteTemplate, (left + 1) * 8 + 32, (top * 8) + 40, 0);\n\n        if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n        {\n            if (!(gLinkContestFlags & LINK_CONTEST_FLAG_HAS_RS_PLAYER))\n                DoMonFrontSpriteAnimation(&gSprites[spriteId], species, FALSE, 0);\n        }\n        else\n        {\n            DoMonFrontSpriteAnimation(&gSprites[spriteId], species, FALSE, 0);\n        }\n\n        gTasks[taskId].data[2] = spriteId;\n        gTasks[taskId].data[3] = left;\n        gTasks[taskId].data[4] = top;\n        gSprites[spriteId].callback = SpriteCallbackDummy;\n        gSprites[spriteId].oam.priority = 0;\n    }",
  },
  "ShowContestPainting": {
    returnType: "void",
    params: "void",
    callsTo: ["SetMainCallback2"],
    lineCount: 2,
    bodyC: "SetMainCallback2(CB2_ContestPainting);\n    gMain.savedCallback = ExitContestPainting;",
  },
  "ShowContestResults": {
    returnType: "void",
    params: "void",
    callsTo: ["BeginNormalPaletteFade","CreateTask","LockPlayerFieldControls"],
    lineCount: 3,
    bodyC: "LockPlayerFieldControls();\n    CreateTask(Task_StartShowContestResults, 10);\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_BLACK);",
  },
  "ShowLinkResultsTextBox": {
    returnType: "static void",
    params: "const u8 *text",
    callsTo: ["DrawResultsTextWindow","SetGpuReg","WIN_RANGE"],
    lineCount: 18,
    bodyC: "int i;\n    u16 x;\n    struct Sprite *sprite;\n\n    x = DrawResultsTextWindow(text, sContestResults->data->linkTextBoxSpriteId);\n    sprite = &gSprites[sContestResults->data->linkTextBoxSpriteId];\n    sprite->x = x + 32;\n    sprite->y = 80;\n    sprite->invisible = FALSE;\n    for (i = 0; i < 3; i++)\n    {\n        gSprites[sprite->data[i]].x = sprite->x + sprite->x2 + (i + 1) * 64;\n        gSprites[sprite->data[i]].y = sprite->y;\n        gSprites[sprite->data[i]].invisible = FALSE;\n    }\n\n    gBattle_WIN0H = WIN_RANGE(0, DISPLAY_WIDTH);\n    gBattle_WIN0V = WIN_RANGE(sprite->y - 16, sprite->y + 16);\n    SetGpuReg(REG_OFFSET_WININ, WININ_WIN1_BG_ALL | WININ_WIN1_OBJ | WININ_WIN1_CLR\n        | WININ_WIN0_BG1 | WININ_WIN0_BG2 | WININ_WIN0_BG3 | WININ_WIN0_OBJ | WININ_WIN0_CLR);",
  },
  "SpriteCB_Confetti": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroySprite","Sin"],
    lineCount: 15,
    bodyC: "s16 delta;\n\n    sprite->data[3] += sprite->data[0];\n    sprite->x2 = Sin(sprite->data[3] >> 8, sprite->data[1]);\n    delta = sprite->data[4] + sprite->data[2];\n    sprite->x += delta >> 8;\n    sprite->data[4] += sprite->data[2];\n    sprite->data[4] &= 0xff;\n\n    sprite->y++;\n    if (sContestResults->data->destroyConfetti)\n        sprite->invisible = TRUE;\n\n    if (sprite->x > DISPLAY_WIDTH + 8 || sprite->y > 116)\n    {\n        DestroySprite(sprite);\n        sContestResults->data->confettiCount--;\n    }",
  },
  "SpriteCB_EndTextBoxSlideIn": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["StartTextBoxSlideOut"],
    lineCount: 6,
    bodyC: "sContestResults->data->slidingTextBoxState = SLIDING_TEXT_ARRIVED;\n    if ((u16)sprite->sSlideOutTimer != 0xFFFF)\n    {\n        if (--sprite->sSlideOutTimer == -1)\n            StartTextBoxSlideOut(sprite->sSlideIncrement);\n    }",
  },
  "SpriteCB_TextBoxSlideIn": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    lineCount: 14,
    bodyC: "int i;\n\n    s16 delta = sprite->sDistance + sprite->sSlideIncrement;\n    sprite->x -= delta >> 8;\n    sprite->sDistance += sprite->sSlideIncrement;\n    sprite->sDistance &= 0xFF;\n\n     \n    if (sprite->x < sprite->sTargetX)\n        sprite->x = sprite->sTargetX;\n\n    for (i = 0; i < 3; i++)\n    {\n        struct Sprite *sprite2 = &gSprites[sprite->data[i]];\n        sprite2->x = sprite->x + sprite->x2 + (i + 1) * 64;\n    }\n\n    if (sprite->x == sprite->sTargetX)\n        sprite->callback = SpriteCB_EndTextBoxSlideIn;",
  },
  "SpriteCB_TextBoxSlideOut": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["EndTextBoxSlideOut"],
    lineCount: 13,
    bodyC: "int i;\n    s16 delta;\n\n    delta = sprite->sDistance + sprite->sSlideIncrement;\n    sprite->x -= delta >> 8;\n    sprite->sDistance += sprite->sSlideIncrement;\n    sprite->sDistance &= 0xFF;\n    for (i = 0; i < 3; i++)\n    {\n        struct Sprite *sprite2 = &gSprites[sprite->data[i]];\n        sprite2->x = sprite->x + sprite->x2 + (i + 1) * 64;\n    }\n\n    if (sprite->x + sprite->x2 < -224)\n        EndTextBoxSlideOut(sprite);",
  },
  "SpriteCB_WinnerMonSlideIn": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["PlayCry_Normal"],
    lineCount: 23,
    bodyC: "if (sprite->data[0] < 10)\n    {\n        if (++sprite->data[0] == 10)\n        {\n            PlayCry_Normal(sprite->data[1], 0);\n            sprite->data[1] = 0;\n        }\n    }\n    else\n    {\n        s16 delta = sprite->data[1] + 0x600;\n        sprite->x -= delta >> 8;\n        sprite->data[1] += 0x600;\n        sprite->data[1] &= 0xFF;\n        if (sprite->x < DISPLAY_WIDTH / 2)\n            sprite->x = DISPLAY_WIDTH / 2;\n\n        if (sprite->x == DISPLAY_WIDTH / 2)\n        {\n            sprite->callback = SpriteCallbackDummy;\n            sprite->data[1] = 0;\n            sContestResults->data->winnerMonSlidingState = SLIDING_MON_ENTERED;\n        }\n    }",
  },
  "SpriteCB_WinnerMonSlideOut": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    lineCount: 10,
    bodyC: "s16 delta = sprite->data[1] + 0x600;\n    sprite->x -= delta >> 8;\n    sprite->data[1] += + 0x600;\n    sprite->data[1] &= 0xFF;\n    if (sprite->x < -32)\n    {\n        sprite->callback = SpriteCallbackDummy;\n        sprite->invisible = TRUE;\n        sContestResults->data->winnerMonSlidingState = SLIDING_MON_EXITED;\n    }",
  },
  "StartContest": {
    returnType: "void",
    params: "void",
    callsTo: ["BeginNormalPaletteFade","CreateTask","LockPlayerFieldControls"],
    lineCount: 3,
    bodyC: "LockPlayerFieldControls();\n    CreateTask(Task_StartContest, 10);\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_BLACK);",
  },
  "StartTextBoxSlideIn": {
    returnType: "static void",
    params: "s16 x, u16 y, u16 slideOutTimer, u16 slideIncrement",
    lineCount: 11,
    bodyC: "struct Sprite *sprite = &gSprites[sContestResults->data->slidingTextBoxSpriteId];\n    sprite->x = TEXT_BOX_X;\n    sprite->y = y;\n    sprite->x2 = 0;\n    sprite->y2 = 0;\n    sprite->sTargetX = x + 32;\n    sprite->sSlideOutTimer = slideOutTimer;\n    sprite->sSlideIncrement = slideIncrement;\n    sprite->sDistance = 0;\n    sprite->callback = SpriteCB_TextBoxSlideIn;\n    sContestResults->data->slidingTextBoxState = SLIDING_TEXT_ENTERING;",
  },
  "StartTextBoxSlideOut": {
    returnType: "static void",
    params: "u16 slideIncrement",
    lineCount: 9,
    bodyC: "struct Sprite *sprite = &gSprites[sContestResults->data->slidingTextBoxSpriteId];\n    sprite->x += sprite->x2;\n    sprite->y += sprite->y2;\n    sprite->y2 = 0;\n    sprite->x2 = 0;\n    sprite->sSlideIncrement = slideIncrement;\n    sprite->sDistance = 0;\n    sprite->callback = SpriteCB_TextBoxSlideOut;\n    sContestResults->data->slidingTextBoxState = SLIDING_TEXT_EXITING;",
  },
  "Task_AnnouncePreliminaryResults": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateTask","DrawResultsTextWindow","StartTextBoxSlideIn"],
    lineCount: 38,
    bodyC: "s16 x;\n\n    if (gTasks[taskId].tState == 0)\n    {\n        CreateTask(Task_FlashStarsAndHearts, 20);\n        x = DrawResultsTextWindow(gText_AnnouncingResults, sContestResults->data->slidingTextBoxSpriteId);\n        StartTextBoxSlideIn(x, TEXT_BOX_Y, 120, 1088);\n        gTasks[taskId].tState++;\n    }\n    else if (gTasks[taskId].tState == 1)\n    {\n         \n        if (sContestResults->data->slidingTextBoxState == SLIDING_TEXT_OFFSCREEN)\n        {\n            gTasks[taskId].tTimer = 0;\n            gTasks[taskId].tState++;\n        }\n    }\n    else if (gTasks[taskId].tState == 2)\n    {\n        if (++gTasks[taskId].tTimer == 21)\n        {\n            gTasks[taskId].tTimer = 0;\n            gTasks[taskId].tState++;\n        }\n    }\n    else if (gTasks[taskId].tState == 3)\n    {\n        x = DrawResultsTextWindow(gText_PreliminaryResults, sContestResults->data->slidingTextBoxSpriteId);\n        StartTextBoxSlideIn(x, TEXT_BOX_Y, -1, 1088);\n        gTasks[taskId].tState++;\n    }\n    else if (gTasks[taskId].tState == 4)\n    {\n        if (sContestResults->data->slidingTextBoxState == SLIDING_TEXT_ARRIVED)\n        {\n            gTasks[taskId].tState = 0;\n            gTasks[taskId].func = Task_ShowPreliminaryResults;\n        }\n    }",
  },
  "Task_AnnounceRound2Results": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DrawResultsTextWindow","StartTextBoxSlideIn"],
    lineCount: 14,
    bodyC: "s16 x;\n\n    if (sContestResults->data->slidingTextBoxState == SLIDING_TEXT_OFFSCREEN)\n    {\n        if (++gTasks[taskId].tTimer == 21)\n        {\n            gTasks[taskId].tTimer = 0;\n            x = DrawResultsTextWindow(gText_Round2Results, sContestResults->data->slidingTextBoxSpriteId);\n            StartTextBoxSlideIn(x, TEXT_BOX_Y, -1, 1088);\n        }\n    }\n    else if (sContestResults->data->slidingTextBoxState == SLIDING_TEXT_ARRIVED)\n    {\n        gTasks[taskId].func = Task_ShowRound2Results;\n    }",
  },
  "Task_AnnounceWinner": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BounceMonIconInBox","ConvertInternationalContestantName","CreateTask","DrawResultsTextWindow","GET_CONTEST_WINNER_ID","StartTextBoxSlideIn","StringCopy","StringExpandPlaceholders"],
    lineCount: 57,
    bodyC: "int i;\n    switch (gTasks[taskId].tState)\n    {\n    case 0:\n        if (sContestResults->data->slidingTextBoxState == SLIDING_TEXT_OFFSCREEN)\n            gTasks[taskId].tState++;\n        break;\n    case 1:\n        if (++gTasks[taskId].tTimer == 31)\n        {\n            gTasks[taskId].tTimer = 0;\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 2:\n        for (i = 0; i < CONTESTANT_COUNT; i++)\n        {\n            u8 newTaskId = CreateTask(Task_DrawFinalStandingNumber, 10);\n            gTasks[newTaskId].tFinalStanding = gContestFinalStandings[i];\n            gTasks[newTaskId].tMonIndex = i;\n        }\n        gTasks[taskId].tState++;\n        break;\n    case 3:\n        if (sContestResults->data->numStandingsPrinted == CONTESTANT_COUNT)\n        {\n            if (++gTasks[taskId].tTimer == 31)\n            {\n                gTasks[taskId].tTimer = 0;\n                CreateTask(Task_StartHighlightWinnersBox, 10);\n                gTasks[taskId].tState++;\n                GET_CONTEST_WINNER_ID(i);\n                BounceMonIconInBox(i, 14);\n            }\n        }\n        break;\n    case 4:\n        if (++gTasks[taskId].tTimer == 21)\n        {\n            u8 winnerTextBuffer[100];\n            s16 x;\n            gTasks[taskId].tTimer = 0;\n            GET_CONTEST_WINNER_ID(i);\n            StringCopy(gStringVar1, gContestMons[i].trainerName);\n            ConvertInternationalContestantName(gStringVar1);\n            StringCopy(gStringVar2, gContestMons[i].nickname);\n            StringExpandPlaceholders(winnerTextBuffer, gText_ContestantsMonWon);\n            x = DrawResultsTextWindow(winnerTextBuffer, sContestResults->data->slidingTextBoxSpriteId);\n            StartTextBoxSlideIn(x, TEXT_BOX_Y, -1, 1088);\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 5:\n        gTasks[taskId].tState = 0;\n        gTasks[taskId].func = Task_ShowWinnerMonBanner;\n        break;\n    }",
  },
  "Task_BounceMonIconInBox": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["LoadContestMonIcon"],
    lineCount: 7,
    bodyC: "u8 monIndex = gTasks[taskId].tMonIndex;\n    if (gTasks[taskId].tTimer++ == gTasks[taskId].tNumFrames)\n    {\n        gTasks[taskId].tTimer = 0;\n        LoadContestMonIcon(gTasks[taskId].tSpecies, monIndex, gTasks[taskId].tBounced, FALSE, gContestMons[monIndex].personality);\n        gTasks[taskId].tBounced ^= 1;\n    }",
  },
  "Task_CommunicateMonIdxsForResults": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["SetTaskFuncWithFollowupFunc"],
    lineCount: 1,
    bodyC: "SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateMonIdxs, Task_WaitForLinkPartnerMonIdxs);",
  },
  "Task_CreateConfetti": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","DestroyTask","Random"],
    lineCount: 15,
    bodyC: "if (++gTasks[taskId].data[0] == 5)\n    {\n        gTasks[taskId].data[0] = 0;\n        if (sContestResults->data->confettiCount < 40)\n        {\n            u8 spriteId = CreateSprite(&sSpriteTemplate_Confetti, (Random() % DISPLAY_WIDTH) - 20, 44, 5);\n            gSprites[spriteId].data[0] = Random() % 512;\n            gSprites[spriteId].data[1] = (Random() % 24) + 16;\n            gSprites[spriteId].data[2] = (Random() % 256) + 48;\n            gSprites[spriteId].oam.tileNum += Random() % 17;\n            sContestResults->data->confettiCount++;\n        }\n    }\n\n    if (sContestResults->data->destroyConfetti)\n        DestroyTask(taskId);",
  },
  "Task_DrawFinalStandingNumber": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","PlaySE","WriteSequenceToBgTilemapBuffer"],
    lineCount: 18,
    bodyC: "u16 firstTileNum;\n\n    if (gTasks[taskId].tState == 0)\n    {\n        gTasks[taskId].data[11] = (3 - gTasks[taskId].tFinalStanding) * 40;\n        gTasks[taskId].tState++;\n    }\n    else if (gTasks[taskId].tState == 1)\n    {\n        if (--gTasks[taskId].data[11] == -1)\n        {\n            firstTileNum = gTasks[taskId].tFinalStanding * 2 + 0x5043;\n            WriteSequenceToBgTilemapBuffer(2, firstTileNum, 1, gTasks[taskId].tMonIndex * 3 + 5, 2, 1, 17, 1);\n            WriteSequenceToBgTilemapBuffer(2, firstTileNum + 0x10, 1, gTasks[taskId].tMonIndex * 3 + 6, 2, 1, 17, 1);\n            sContestResults->data->numStandingsPrinted++;\n            DestroyTask(taskId);\n            PlaySE(SE_CONTEST_PLACE);\n        }\n    }",
  },
  "Task_EndShowContestResults": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BlendPalettes","DestroyTask","FreeAllWindowBuffers","FreeContestResults","SetGpuReg","SetMainCallback2"],
    lineCount: 23,
    bodyC: "if (!gPaletteFade.active)\n    {\n        if (gTasks[taskId].tTimer == 0)\n        {\n            DestroyTask(sContestResults->data->highlightWinnerTaskId);\n            BlendPalettes(PALETTES_BG, 16, RGB_BLACK);\n            gTasks[taskId].tTimer++;\n        }\n        else if (gTasks[taskId].tTimer == 1)\n        {\n            BlendPalettes(PALETTES_OBJECTS, 16, RGB_BLACK);\n            gTasks[taskId].tTimer++;\n        }\n        else\n        {\n            SetGpuReg(REG_OFFSET_BLDCNT, 0);\n            SetGpuReg(REG_OFFSET_BLDY, 0);\n            DestroyTask(taskId);\n            FreeAllWindowBuffers();\n            SetMainCallback2(CB2_ReturnToFieldContinueScriptPlayMapMusic);\n            FreeContestResults();\n        }\n    }",
  },
  "Task_FlashStarsAndHearts": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BG_PLTT_ID","BlendPalette","RGB"],
    lineCount: 19,
    bodyC: "if (++gTasks[taskId].tDelay == 2)\n    {\n        gTasks[taskId].tDelay = 0;\n        if (!gTasks[taskId].tDecreasing)\n            gTasks[taskId].tCoeff++;\n        else\n            gTasks[taskId].tCoeff--;\n\n        if (gTasks[taskId].tCoeff == 16)\n            gTasks[taskId].tDecreasing = TRUE;\n        else if (gTasks[taskId].tCoeff == 0)\n            gTasks[taskId].tDecreasing = FALSE;\n\n        BlendPalette(BG_PLTT_ID(6) + 11, 1, gTasks[taskId].tCoeff, RGB(30, 22, 11));\n        BlendPalette(BG_PLTT_ID(6) + 8, 1, gTasks[taskId].tCoeff, RGB_WHITE);\n        BlendPalette(BG_PLTT_ID(6) + 14, 1, gTasks[taskId].tCoeff, RGB(30, 29, 29));\n    }\n\n    if (gTasks[taskId].tCoeff == 0)\n        sContestResults->data->pointsFlashing = FALSE;\n    else\n        sContestResults->data->pointsFlashing = TRUE;",
  },
  "Task_HighlightWinnersBox": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BG_PLTT_ID","BlendPalette","RGB"],
    lineCount: 15,
    bodyC: "if (++gTasks[taskId].data[11] == 1)\n    {\n        gTasks[taskId].data[11] = 0;\n        BlendPalette(BG_PLTT_ID(9) + 1, 1, gTasks[taskId].data[12], RGB(13, 28, 27));\n        if (gTasks[taskId].data[13] == 0)\n        {\n            if (++gTasks[taskId].data[12] == 16)\n                gTasks[taskId].data[13] = 1;\n        }\n        else\n        {\n            if (--gTasks[taskId].data[12] == 0)\n                gTasks[taskId].data[13] = 0;\n        }\n    }",
  },
  "Task_LinkContestWaitForConnection": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","IsLinkTaskFinished","ScriptContext_Enable","SetLinkStandbyCallback"],
    lineCount: 20,
    bodyC: "switch (gTasks[taskId].data[0])\n    {\n    case 0:\n        if (IsLinkTaskFinished())\n        {\n            SetLinkStandbyCallback();\n            gTasks[taskId].data[0]++;\n        }\n        break;\n    case 1:\n        gTasks[taskId].data[0]++;\n        break;\n    default:\n        if (IsLinkTaskFinished() == 1)\n        {\n            ScriptContext_Enable();\n            DestroyTask(taskId);\n        }\n        break;\n    }",
  },
  "Task_LinkContest_CalculateTurnOrderRS": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["SetTaskFuncWithFollowupFunc","SortContestants"],
    lineCount: 2,
    bodyC: "SortContestants(FALSE);\n    SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateTurnOrder, Task_LinkContest_FinalizeConnection);",
  },
  "Task_LinkContest_Disconnect": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["SetCloseLinkCallback"],
    lineCount: 2,
    bodyC: "SetCloseLinkCallback();\n    gTasks[taskId].func = Task_LinkContest_WaitDisconnect;",
  },
  "Task_LinkContest_FinalizeConnection": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","IsLinkTaskFinished","ScriptContext_Enable","SetDynamicWarp","StringGet_Nickname","UnlockPlayerFieldControls"],
    lineCount: 15,
    bodyC: "int i;\n\n    if (gSpecialVar_0x8004 == TRUE)\n    {\n         \n        if (IsLinkTaskFinished())\n            gTasks[taskId].func = Task_LinkContest_Disconnect;\n    }\n    else\n    {\n         \n        for (i = 0; i < CONTESTANT_COUNT; i++)\n            StringGet_Nickname(gContestMons[i].nickname);\n\n        DestroyTask(taskId);\n        SetDynamicWarp(0, gSaveBlock1Ptr->location.mapGroup, gSaveBlock1Ptr->location.mapNum, WARP_ID_NONE);\n        UnlockPlayerFieldControls();\n        ScriptContext_Enable();\n    }",
  },
  "Task_LinkContest_SetUpContestRS": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CalculateRound1Points","LinkContest_GetLeaderIndex","SetTaskFuncWithFollowupFunc","memset"],
    lineCount: 18,
    bodyC: "u8 i;\n    u8 categories[CONTESTANT_COUNT];\n    u8 leaderIds[CONTESTANT_COUNT];\n\n    memset(categories, 0, sizeof(categories));\n    memset(leaderIds, 0, sizeof(leaderIds));\n\n    for (i = 0; i < gNumLinkContestPlayers; i++)\n        categories[i] = gTasks[taskId].data[i + 1];\n\n     \n    for (i = 0; i < gNumLinkContestPlayers && categories[0] == categories[i]; i++)\n        ;\n\n    if (i == gNumLinkContestPlayers)\n        gSpecialVar_0x8004 = FALSE;  \n    else\n        gSpecialVar_0x8004 = TRUE;  \n\n    for (i = 0; i < gNumLinkContestPlayers; i++)\n        leaderIds[i] = gTasks[taskId].data[i + 5];\n\n    gContestLinkLeaderIndex = LinkContest_GetLeaderIndex(leaderIds);\n    CalculateRound1Points(gSpecialVar_ContestCategory);\n    SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateRound1Points, Task_LinkContest_CalculateTurnOrderRS);",
  },
  "Task_LinkContest_WaitDisconnect": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","ScriptContext_Enable","UnlockPlayerFieldControls"],
    lineCount: 6,
    bodyC: "if (!gReceivedRemoteLinkPlayers)\n    {\n        DestroyTask(taskId);\n        UnlockPlayerFieldControls();\n        ScriptContext_Enable();\n    }",
  },
  "Task_SetSeenWinnerMon": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["GetSetPokedexFlag","JOY_NEW","SpeciesToNationalPokedexNum"],
    lineCount: 14,
    bodyC: "int i, nationalDexNum;\n\n    if (JOY_NEW(A_BUTTON))\n    {\n        if (!(gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK))\n        {\n            for (i = 0; i < CONTESTANT_COUNT; i++)\n            {\n                nationalDexNum = SpeciesToNationalPokedexNum(gContestMons[i].species);\n                GetSetPokedexFlag(nationalDexNum, FLAG_SET_SEEN);\n            }\n        }\n\n        gTasks[taskId].data[10] = 0;\n        gTasks[taskId].func = Task_TryDisconnectLinkPartners;\n    }",
  },
  "Task_ShowContestEntryMonPic": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["ClearToTransparentAndRemoveWindow","CreateWindowFromRect","DestroySprite","DestroyTask","FreeOamMatrix","FreeSpritePaletteByTag","GetSpritePaletteTagByPaletteNum","SetStandardWindowBorderStyle"],
    lineCount: 27,
    bodyC: "struct Task *task = &gTasks[taskId];\n    struct Sprite *sprite;\n\n    switch(task->data[0])\n    {\n    case 0:\n        task->data[0]++;\n        break;\n    case 1:\n        task->data[5] = CreateWindowFromRect(10, 3, 8, 8);\n        SetStandardWindowBorderStyle(task->data[5], TRUE);\n        task->data[0]++;\n        break;\n    case 2:\n        break;\n    case 3:\n        sprite = &gSprites[task->data[2]];\n        FreeSpritePaletteByTag(GetSpritePaletteTagByPaletteNum(sprite->oam.paletteNum));\n\n        if(sprite->oam.affineMode)\n            FreeOamMatrix(sprite->oam.matrixNum);\n\n        DestroySprite(sprite);\n        task->data[0]++;\n        break;\n    case 4:\n        ClearToTransparentAndRemoveWindow(gTasks[taskId].data[5]);\n        DestroyTask(taskId);\n        break;\n    }",
  },
  "Task_ShowContestResults": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["ClearContinueGameWarpStatus2","GetContestWinnerSaveIdx","IncrementGameStat","InterviewAfter","InterviewBefore","IsLinkTaskFinished","PlayBGM","SaveContestWinner","SaveLinkContestResults","SetContinueGameWarpStatusToDynamicWarp","SetLinkStandbyCallback","ShowLinkResultsTextBox","TryGainNewFanFromCounter","TrySavingData","VarGet","VarSet"],
    lineCount: 72,
    bodyC: "u16 var;\n\n    if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n    {\n        switch (gTasks[taskId].tState)\n        {\n        case 0:\n            SaveLinkContestResults();\n            if (gContestFinalStandings[gContestPlayerMonIndex] == 0)\n            {\n                IncrementGameStat(GAME_STAT_WON_LINK_CONTEST);\n                gSpecialVar_0x8005 = TVSHOW_CONTEST_LIVE_UPDATES;\n                InterviewBefore();\n                if (gSpecialVar_Result != TRUE)\n                    InterviewAfter();\n            }\n\n            TryGainNewFanFromCounter(FANCOUNTER_FINISHED_CONTEST);\n            SaveContestWinner(gSpecialVar_ContestRank);  \n            SaveContestWinner(CONTEST_SAVE_FOR_ARTIST);\n            gCurContestWinnerIsForArtist = TRUE;\n            gCurContestWinnerSaveIdx = GetContestWinnerSaveIdx(CONTEST_SAVE_FOR_ARTIST, FALSE);\n            var = VarGet(VAR_CONTEST_HALL_STATE);\n            VarSet(VAR_CONTEST_HALL_STATE, 0);\n            SetContinueGameWarpStatusToDynamicWarp();\n            TrySavingData(SAVE_LINK);\n            ClearContinueGameWarpStatus2();\n            VarSet(VAR_CONTEST_HALL_STATE, var);\n            gTasks[taskId].tState++;\n            break;\n        case 1:\n            gTasks[taskId].tState++;\n            if (!(gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS))\n                gTasks[taskId].tState = 100;\n            break;\n        case 2:\n            if (IsLinkTaskFinished())\n            {\n                SetLinkStandbyCallback();\n                gTasks[taskId].tState++;\n            }\n            return;\n        case 3:\n            if (IsLinkTaskFinished() == TRUE)\n            {\n                PlayBGM(MUS_CONTEST_RESULTS);\n                gPaletteFade.bufferTransferDisabled = FALSE;\n                gTasks[taskId].tState++;\n                break;\n            }\n            return;\n        }\n    }\n\n    if (!gPaletteFade.active)\n    {\n        gTasks[taskId].tState = 0;\n        if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n        {\n            ShowLinkResultsTextBox(gText_CommunicationStandby);\n            gTasks[taskId].func = Task_WaitForLinkPartnersBeforeResults;\n        }\n        else\n        {\n            IncrementGameStat(GAME_STAT_ENTERED_CONTEST);\n            if (gContestFinalStandings[gContestPlayerMonIndex] == 0)\n                IncrementGameStat(GAME_STAT_WON_CONTEST);\n\n            SaveContestWinner(gSpecialVar_ContestRank);  \n            SaveContestWinner(CONTEST_SAVE_FOR_ARTIST);\n            gCurContestWinnerIsForArtist = TRUE;\n            gCurContestWinnerSaveIdx = GetContestWinnerSaveIdx(CONTEST_SAVE_FOR_ARTIST, FALSE);\n            TryGainNewFanFromCounter(FANCOUNTER_FINISHED_CONTEST);\n            gTasks[taskId].func = Task_AnnouncePreliminaryResults;\n        }\n    }",
  },
  "Task_ShowPreliminaryResults": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["StartTextBoxSlideOut","UpdateContestResultBars"],
    lineCount: 23,
    bodyC: "switch (gTasks[taskId].tState)\n    {\n    case 0:\n        if (!sContestResults->data->pointsFlashing)\n        {\n            UpdateContestResultBars(FALSE, gTasks[taskId].tCounter++);\n            if (sContestResults->data->numBarsUpdating == 0)\n                gTasks[taskId].tState = 2;\n            else\n                gTasks[taskId].tState++;\n        }\n        break;\n    case 1:\n        if (sContestResults->data->numBarsUpdating == 0)\n            gTasks[taskId].tState = 0;\n        break;\n    case 2:\n        StartTextBoxSlideOut(1088);\n        gTasks[taskId].tState = 0;\n        gTasks[taskId].tCounter = 0;\n        gTasks[taskId].func = Task_AnnounceRound2Results;\n        break;\n    }",
  },
  "Task_ShowRound2Results": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["StartTextBoxSlideOut","UpdateContestResultBars"],
    lineCount: 22,
    bodyC: "switch (gTasks[taskId].tState)\n    {\n    case 0:\n        if (!sContestResults->data->pointsFlashing)\n        {\n            UpdateContestResultBars(TRUE, gTasks[taskId].tCounter++);\n            if (sContestResults->data->numBarsUpdating == 0)\n                gTasks[taskId].tState = 2;\n            else\n                gTasks[taskId].tState++;\n        }\n        break;\n    case 1:\n        if (sContestResults->data->numBarsUpdating == 0)\n            gTasks[taskId].tState = 0;\n        break;\n    case 2:\n        StartTextBoxSlideOut(1088);\n        gTasks[taskId].tState = 0;\n        gTasks[taskId].func = Task_AnnounceWinner;\n        break;\n    }",
  },
  "Task_ShowWinnerMonBanner": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateSprite","CreateTask","GET_CONTEST_WINNER_ID","GetMonSpritePalStructFromOtIdPersonality","HandleLoadSpecialPokePic_2","HandleLoadSpecialPokePic_DontHandleDeoxys","LoadCompressedSpritePalette","LoadCompressedSpriteSheet","SetMultiuseSpriteTemplateToPokemon","WIN_RANGE"],
    lineCount: 92,
    bodyC: "int i;\n    u8 spriteId;\n    u16 species;\n    u32 otId;\n    u32 personality;\n    const struct CompressedSpritePalette *pokePal;\n\n    switch (gTasks[taskId].tState)\n    {\n    case 0:\n        gBattle_WIN0H = WIN_RANGE(0, DISPLAY_WIDTH);\n        gBattle_WIN0V = WIN_RANGE(DISPLAY_HEIGHT / 2, DISPLAY_HEIGHT / 2);\n\n        GET_CONTEST_WINNER_ID(i);\n        species = gContestMons[i].species;\n        personality = gContestMons[i].personality;\n        otId = gContestMons[i].otId;\n        if (i == gContestPlayerMonIndex)\n        {\n            HandleLoadSpecialPokePic_2(\n                &gMonFrontPicTable[species],\n                gMonSpritesGfxPtr->sprites.ptr[B_POSITION_OPPONENT_LEFT],\n                species,\n                personality);\n        }\n        else\n        {\n            HandleLoadSpecialPokePic_DontHandleDeoxys(\n                &gMonFrontPicTable[species],\n                gMonSpritesGfxPtr->sprites.ptr[B_POSITION_OPPONENT_LEFT],\n                species,\n                personality);\n        }\n\n        pokePal = GetMonSpritePalStructFromOtIdPersonality(species, otId, personality);\n        LoadCompressedSpritePalette(pokePal);\n        SetMultiuseSpriteTemplateToPokemon(species, B_POSITION_OPPONENT_LEFT);\n        gMultiuseSpriteTemplate.paletteTag = pokePal->tag;\n        spriteId = CreateSprite(&gMultiuseSpriteTemplate, DISPLAY_WIDTH + 32, DISPLAY_HEIGHT / 2, 10);\n        gSprites[spriteId].data[1] = species;\n        gSprites[spriteId].oam.priority = 0;\n        gSprites[spriteId].callback = SpriteCB_WinnerMonSlideIn;\n        sContestResults->data->winnerMonSpriteId = spriteId;\n        LoadCompressedSpriteSheet(&sSpriteSheet_Confetti);\n        LoadCompressedSpritePalette(&sSpritePalette_Confetti);\n        CreateTask(Task_CreateConfetti, 10);\n        gTasks[taskId].tState++;\n        break;\n    case 1:\n        if (++gTasks[taskId].data[3] == 1)\n        {\n            u8 counter;\n            gTasks[taskId].data[3] = 0;\n            gTasks[taskId].tCounter += 2;\n            if (gTasks[taskId].tCounter > 32)\n                gTasks[taskId].tCounter = 32;\n\n            counter = gTasks[taskId].tCounter;\n            gBattle_WIN0V = WIN_RANGE(DISPLAY_HEIGHT / 2 - counter, DISPLAY_HEIGHT / 2 + counter);\n            if (counter == 32)\n                gTasks[taskId].tState++;\n        }\n        break;\n    case 2:\n        if (sContestResults->data->winnerMonSlidingState == SLIDING_MON_ENTERED)\n            gTasks[taskId].tState++;\n        break;\n    case 3:\n        if (++gTasks[taskId].tTimer == 121)\n        {\n            gTasks[taskId].tTimer = 0;\n            gSprites[sContestResults->data->winnerMonSpriteId].callback = SpriteCB_WinnerMonSlideOut;\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 4:\n        if (sContestResults->data->winnerMonSlidingState == SLIDING_MON_EXITED)\n        {\n            u8 top = (gBattle_WIN0V >> 8);\n            top += 2;\n            if (top > DISPLAY_HEIGHT / 2)\n                top = DISPLAY_HEIGHT / 2;\n\n            gBattle_WIN0V = WIN_RANGE(top, DISPLAY_HEIGHT - top);\n            if (top == DISPLAY_HEIGHT / 2)\n                gTasks[taskId].tState++;\n        }\n        break;\n    case 5:\n        if (sContestResults->data->winnerMonSlidingState == SLIDING_MON_EXITED)\n        {\n            sContestResults->data->destroyConfetti = TRUE;\n            gTasks[taskId].tState = 0;\n            gTasks[taskId].func = Task_SetSeenWinnerMon;\n        }\n        break;\n    }",
  },
  "Task_SlideContestResultsBg": {
    returnType: "static void",
    params: "u8 taskId",
    lineCount: 6,
    bodyC: "gBattle_BG3_X += 2;\n    gBattle_BG3_Y += 1;\n    if (gBattle_BG3_X > 255)\n        gBattle_BG3_X -= 255;\n    if (gBattle_BG3_Y > 255)\n        gBattle_BG3_Y -= 255;",
  },
  "Task_StartCommunicateCategoryRS": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["SetTaskFuncWithFollowupFunc"],
    lineCount: 1,
    bodyC: "SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateCategoryRS, Task_LinkContest_SetUpContestRS);",
  },
  "Task_StartCommunicateLeaderIdsRS": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["SetTaskFuncWithFollowupFunc"],
    lineCount: 1,
    bodyC: "SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateLeaderIdsRS, Task_StartCommunicateCategoryRS);",
  },
  "Task_StartCommunicateRngRS": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["SetTaskFuncWithFollowupFunc"],
    lineCount: 1,
    bodyC: "SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateRngRS, Task_StartCommunicateLeaderIdsRS);",
  },
  "Task_StartCommunication": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateContestMonFromParty","SetTaskFuncWithFollowupFunc"],
    lineCount: 10,
    bodyC: "if (gLinkContestFlags & LINK_CONTEST_FLAG_HAS_RS_PLAYER)\n    {\n        CreateContestMonFromParty(gContestMonPartyIndex);\n        SetTaskFuncWithFollowupFunc(taskId, Task_LinkContest_CommunicateMonsRS, Task_StartCommunicateRngRS);\n    }\n    else\n    {\n        CreateContestMonFromParty(gContestMonPartyIndex);\n        gTasks[taskId].func = Task_LinkContest_StartCommunicationEm;\n    }",
  },
  "Task_StartContest": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","SetMainCallback2"],
    lineCount: 5,
    bodyC: "if (!gPaletteFade.active)\n    {\n        DestroyTask(taskId);\n        SetMainCallback2(CB2_SetStartContestCallback);\n    }",
  },
  "Task_StartHighlightWinnersBox": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CopyToBgTilemapBufferRect_ChangePalette","GET_CONTEST_WINNER_ID"],
    lineCount: 7,
    bodyC: "int i;\n    GET_CONTEST_WINNER_ID(i);\n    CopyToBgTilemapBufferRect_ChangePalette(2, i * 0xC0 + 0x100 + sContestResults->tilemapBuffers[2], 0, i * 3 + 4, 32, 3, 9);\n    gTasks[taskId].data[10] = i;\n    gTasks[taskId].data[12] = 1;\n    gTasks[taskId].func = Task_HighlightWinnersBox;\n    sContestResults->data->highlightWinnerTaskId = taskId;",
  },
  "Task_StartShowContestResults": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","SetMainCallback2"],
    lineCount: 5,
    bodyC: "if (!gPaletteFade.active)\n    {\n        DestroyTask(taskId);\n        SetMainCallback2(CB2_StartShowContestResults);\n    }",
  },
  "Task_TryDisconnectLinkPartners": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["SetCloseLinkCallback","ShowLinkResultsTextBox"],
    lineCount: 13,
    bodyC: "if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK)\n    {\n        if (!gTasks[taskId].data[10])\n        {\n            ShowLinkResultsTextBox(gText_CommunicationStandby);\n            SetCloseLinkCallback();\n            gTasks[taskId].func = Task_WaitForLinkPartnersDisconnect;\n        }\n    }\n    else\n    {\n        gTasks[taskId].func = Task_TrySetContestInterviewData;\n    }",
  },
  "Task_TrySetContestInterviewData": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BeginHardwarePaletteFade","BravoTrainerPokemonProfile_BeforeInterview2"],
    lineCount: 4,
    bodyC: "if (!(gLinkContestFlags & LINK_CONTEST_FLAG_IS_LINK))\n        BravoTrainerPokemonProfile_BeforeInterview2(gContestFinalStandings[gContestPlayerMonIndex]);\n\n    BeginHardwarePaletteFade(0xFF, 0, 0, 16, 0);\n    gTasks[taskId].func = Task_EndShowContestResults;",
  },
  "Task_UpdateContestResultBar": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","FillBgTilemapBufferRect_Palette0"],
    lineCount: 51,
    bodyC: "int i;\n    bool32 minMaxReached = FALSE;\n    bool32 targetReached = FALSE;\n    u8 monId = gTasks[taskId].tMonId;\n    s16 target = gTasks[taskId].tTarget;\n    s16 decreasing = gTasks[taskId].tDecreasing;\n\n     \n    if (decreasing)\n    {\n        if (sContestResults->data->barLength[monId] <= 0)\n            minMaxReached = TRUE;\n    }\n    else\n    {\n        if (sContestResults->data->barLength[monId] >= MAX_BAR_LENGTH)\n            minMaxReached = TRUE;\n    }\n\n    if (sContestResults->data->barLength[monId] == target)\n        targetReached = TRUE;\n\n    if (!targetReached)\n    {\n         \n        if (minMaxReached)\n            sContestResults->data->barLength[monId] = target;\n        else if (decreasing)\n            sContestResults->data->barLength[monId]--;\n        else\n            sContestResults->data->barLength[monId]++;\n    }\n\n     \n    if (!minMaxReached && !targetReached)\n    {\n        u8 tileOffset;\n        u16 tileNum;\n        for (i = 0; i < NUM_BAR_SEGMENTS; i++)\n        {\n            if (sContestResults->data->barLength[monId] >= (i + 1) * BAR_SEGMENT_LENGTH)\n                tileOffset = 8;  \n            else if (sContestResults->data->barLength[monId] >= i * BAR_SEGMENT_LENGTH)\n                tileOffset = sContestResults->data->barLength[monId] % 8;  \n            else\n                tileOffset = 0;  \n\n             \n             \n            if (tileOffset < 4)\n                tileNum = 0x504C + tileOffset;\n            else\n                tileNum = 0x5057 + tileOffset;\n\n            FillBgTilemapBufferRect_Palette0(2, tileNum, i + 7, monId * 3 + 6, 1, 1);\n        }\n    }\n\n    if (targetReached)\n    {\n        sContestResults->data->numBarsUpdating--;\n        DestroyTask(taskId);\n    }",
  },
  "Task_WaitForLinkPartnerMonIdxs": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","HideLinkResultsTextBox","IsLinkTaskFinished"],
    lineCount: 6,
    bodyC: "if (IsLinkTaskFinished())\n    {\n        DestroyTask(taskId);\n        gTasks[sContestResults->data->showResultsTaskId].func = Task_AnnouncePreliminaryResults;\n        HideLinkResultsTextBox();\n    }",
  },
  "Task_WaitForLinkPartnersBeforeResults": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateTask"],
    lineCount: 5,
    bodyC: "if (gReceivedRemoteLinkPlayers)\n    {\n        CreateTask(Task_CommunicateMonIdxsForResults, 0);\n        gTasks[taskId].func = TaskDummy;\n    }",
  },
  "Task_WaitForLinkPartnersDisconnect": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyWirelessStatusIndicatorSprite","HideLinkResultsTextBox"],
    lineCount: 7,
    bodyC: "if (!gReceivedRemoteLinkPlayers)\n    {\n        if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS)\n            DestroyWirelessStatusIndicatorSprite();\n\n        HideLinkResultsTextBox();\n        gTasks[taskId].func = Task_TrySetContestInterviewData;\n    }",
  },
  "TryCreateWirelessSprites": {
    returnType: "static void",
    params: "void",
    callsTo: ["BG_CHAR_ADDR","CreateSprite","CreateWirelessStatusIndicatorSprite","LoadSpriteSheet","LoadWirelessStatusIndicatorSpriteGfx","RequestDma3Fill"],
    lineCount: 12,
    bodyC: "u16 sheet;\n    u8 spriteId;\n\n    if (gLinkContestFlags & LINK_CONTEST_FLAG_IS_WIRELESS)\n    {\n        LoadWirelessStatusIndicatorSpriteGfx();\n        CreateWirelessStatusIndicatorSprite(8, 8);\n        gSprites[gWirelessStatusIndicatorSpriteId].subpriority = 1;\n        sheet = LoadSpriteSheet(&sSpriteSheet_WirelessIndicatorWindow);\n        RequestDma3Fill(0xFFFFFFFF, (void *)BG_CHAR_ADDR(4) + sheet * 0x20, 0x80, 1);\n        spriteId = CreateSprite(&sSpriteTemplate_WirelessIndicatorWindow, 8, 8, 0);\n        gSprites[spriteId].oam.objMode = ST_OAM_OBJ_WINDOW;\n    }",
  },
  "TryEnterContestMon": {
    returnType: "void",
    params: "void",
    callsTo: ["CalculateRound1Points","GetContestEntryEligibility","SetContestants"],
    lineCount: 7,
    bodyC: "u8 eligibility = GetContestEntryEligibility(&gPlayerParty[gContestMonPartyIndex]);\n\n     \n    if (eligibility)\n    {\n        SetContestants(gSpecialVar_ContestCategory, gSpecialVar_ContestRank);\n        CalculateRound1Points(gSpecialVar_ContestCategory);\n    }\n\n    gSpecialVar_Result = eligibility;",
  },
  "UpdateContestResultBars": {
    returnType: "static void",
    params: "bool8 isRound2, u8 numUpdates",
    callsTo: ["CreateTask","FillBgTilemapBufferRect_Palette0","PlaySE"],
    lineCount: 57,
    bodyC: "int i, taskId;\n    u32 target;\n    u8 numIncreasing = 0, numDecreasing = 0;\n\n    if (!isRound2)\n    {\n        for (i = 0; i < CONTESTANT_COUNT; i++)\n        {\n            u8 numStars = (*sContestResults->monResults)[i].numStars;\n            if (numUpdates < numStars)\n            {\n                FillBgTilemapBufferRect_Palette0(1, 0x60B3, ((19 + numStars) - numUpdates) - 1, i * 3 + 5, 1, 1);\n                taskId = CreateTask(Task_UpdateContestResultBar, 10);\n\n                target = (((*sContestResults->monResults)[i].barLengthPreliminary << 16) / (*sContestResults->monResults)[i].numStars) * (numUpdates + 1);\n                if ((target & 0xFFFF) > 0x7FFF)\n                    target += 0x10000;\n\n                gTasks[taskId].tMonId = i;\n                gTasks[taskId].tTarget = target >> 16;\n                sContestResults->data->numBarsUpdating++;\n                numIncreasing++;\n            }\n        }\n    }\n    else\n    {\n        for (i = 0; i < CONTESTANT_COUNT; i++)\n        {\n            s8 numHearts = (*sContestResults->monResults)[i].numHearts;\n            u32 tile = (*sContestResults->monResults)[i].lostPoints ? 0x60A5 : 0x60A3;\n            if (numUpdates < numHearts)\n            {\n                FillBgTilemapBufferRect_Palette0(1, tile, ((19 + numHearts) - numUpdates) - 1, i * 3 + 6, 1, 1);\n                taskId = CreateTask(Task_UpdateContestResultBar, 10);\n\n                target = (((*sContestResults->monResults)[i].barLengthRound2 << 16) / (*sContestResults->monResults)[i].numHearts) * (numUpdates + 1);\n                if ((target & 0xFFFF) > 0x7FFF)\n                    target += 0x10000;\n\n                gTasks[taskId].tMonId = i;\n                if ((*sContestResults->monResults)[i].lostPoints)\n                {\n                    gTasks[taskId].tDecreasing = TRUE;\n                    numDecreasing++;\n                }\n                else\n                {\n                    numIncreasing++;\n                }\n\n                if ((*sContestResults->monResults)[i].lostPoints)\n                    gTasks[taskId].tTarget = -(target >> 16) + (*sContestResults->monResults)[i].barLengthPreliminary;\n                else\n                    gTasks[taskId].tTarget = (target >> 16) + (*sContestResults->monResults)[i].barLengthPreliminary;\n\n                sContestResults->data->numBarsUpdating++;\n            }\n        }\n    }\n\n    if (numDecreasing)\n        PlaySE(SE_BOO);\n    if (numIncreasing)\n        PlaySE(SE_PIN);",
  },
  "VBlankCB_ShowContestResults": {
    returnType: "static void",
    params: "void",
    callsTo: ["LoadOam","ProcessSpriteCopyRequests","ScanlineEffect_InitHBlankDmaTransfer","SetGpuReg","TransferPlttBuffer"],
    lineCount: 16,
    bodyC: "SetGpuReg(REG_OFFSET_BG0HOFS, gBattle_BG0_X);\n    SetGpuReg(REG_OFFSET_BG0VOFS, gBattle_BG0_Y);\n    SetGpuReg(REG_OFFSET_BG1HOFS, gBattle_BG1_X);\n    SetGpuReg(REG_OFFSET_BG1VOFS, gBattle_BG1_Y);\n    SetGpuReg(REG_OFFSET_BG2HOFS, gBattle_BG2_X);\n    SetGpuReg(REG_OFFSET_BG2VOFS, gBattle_BG2_Y);\n    SetGpuReg(REG_OFFSET_BG3HOFS, gBattle_BG3_X);\n    SetGpuReg(REG_OFFSET_BG3VOFS, gBattle_BG3_Y);\n    SetGpuReg(REG_OFFSET_WIN0H, gBattle_WIN0H);\n    SetGpuReg(REG_OFFSET_WIN0V, gBattle_WIN0V);\n    SetGpuReg(REG_OFFSET_WIN1H, gBattle_WIN1H);\n    SetGpuReg(REG_OFFSET_WIN1V, gBattle_WIN1V);\n    LoadOam();\n    ProcessSpriteCopyRequests();\n    TransferPlttBuffer();\n    ScanlineEffect_InitHBlankDmaTransfer();",
  },
} as const;
