// AUTO-GENERATED from src/credits.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 36

export const ENGINE_FUNCTIONS = {
  "CB2_Credits": {
    returnType: "static void",
    params: "void",
    callsTo: ["AnimateSprites","BuildOamBuffer","JOY_HELD","RunTasks","UpdatePaletteFade","VBlankCB_Credits"],
    lineCount: 13,
    bodyC: "RunTasks();\n    AnimateSprites();\n\n    if ((JOY_HELD(B_BUTTON))\n     && gHasHallOfFameRecords\n     && gTasks[sSavedTaskId].func == Task_CreditsMain)\n    {\n         \n        VBlankCB_Credits();\n        RunTasks();\n        AnimateSprites();\n        sUsedSpeedUp = TRUE;\n    }\n    BuildOamBuffer();\n    UpdatePaletteFade();",
  },
  "CB2_StartCreditsSequence": {
    returnType: "void",
    params: "void",
    callsTo: ["AllocZeroed","BeginNormalPaletteFade","CreateTask","DeterminePokemonToShow","EnableInterrupts","InitCreditsBgsAndWindows","InitHeap","LoadBikeScene","ResetGpuAndVram","ResetPaletteFade","ResetTasks","SetGpuReg","SetMainCallback2","SetVBlankCallback","m4aSongNumStart"],
    lineCount: 37,
    bodyC: "u8 taskId;\n    s16 bikeTaskId;\n    u8 pageTaskId;\n\n    ResetGpuAndVram();\n    SetVBlankCallback(NULL);\n    InitHeap(gHeap, HEAP_SIZE);\n    ResetPaletteFade();\n    ResetTasks();\n    InitCreditsBgsAndWindows();\n\n    taskId = CreateTask(Task_WaitPaletteFade, 0);\n\n    gTasks[taskId].tEndCredits = FALSE;\n    gTasks[taskId].tSceneNum = SCENE_OCEAN_MORNING;\n    gTasks[taskId].tNextMode = MODE_NONE;\n    gTasks[taskId].tCurrentMode = MODE_BIKE_SCENE;\n\n    while (TRUE)\n    {\n        if (LoadBikeScene(SCENE_OCEAN_MORNING, taskId))\n            break;\n    }\n\n    bikeTaskId = gTasks[taskId].tTaskId_BikeScene;\n    gTasks[bikeTaskId].tState = 40;\n\n    SetGpuReg(REG_OFFSET_BG0VOFS, 0xFFFC);\n\n    pageTaskId = CreateTask(Task_UpdatePage, 0);\n\n    gTasks[pageTaskId].tMainTaskId = taskId;\n    gTasks[taskId].tTaskId_UpdatePage = pageTaskId;\n\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_BLACK);\n    EnableInterrupts(INTR_FLAG_VBLANK);\n    SetVBlankCallback(VBlankCB_Credits);\n    m4aSongNumStart(MUS_CREDITS);\n    SetMainCallback2(CB2_Credits);\n    sUsedSpeedUp = FALSE;\n    sCreditsData = AllocZeroed(sizeof(struct CreditsData));\n\n    DeterminePokemonToShow();\n\n    sCreditsData->imgCounter = 0;\n    sCreditsData->nextImgPos = POS_LEFT;\n    sCreditsData->currShownMon = 0;\n\n    sSavedTaskId = taskId;",
  },
  "CheckChangeScene": {
    returnType: "static u8",
    params: "u8 page, u8 taskId",
    lineCount: 41,
    bodyC: "if (page == PAGE_INTERVAL * 1)\n    {\n         \n        gTasks[taskId].tNextMode = MODE_SHOW_MONS;\n    }\n\n    if (page == PAGE_INTERVAL * 2)\n    {\n         \n        gTasks[taskId].tSceneNum = SCENE_OCEAN_SUNSET;\n        gTasks[taskId].tNextMode = MODE_BIKE_SCENE;\n    }\n\n    if (page == PAGE_INTERVAL * 3)\n    {\n         \n        gTasks[taskId].tNextMode = MODE_SHOW_MONS;\n    }\n\n    if (page == PAGE_INTERVAL * 4)\n    {\n         \n        gTasks[taskId].tSceneNum = SCENE_FOREST_RIVAL_ARRIVE;\n        gTasks[taskId].tNextMode = MODE_BIKE_SCENE;\n    }\n\n    if (page == PAGE_INTERVAL * 5)\n    {\n         \n        gTasks[taskId].tNextMode = MODE_SHOW_MONS;\n    }\n\n    if (page == PAGE_INTERVAL * 6)\n    {\n         \n        gTasks[taskId].tSceneNum = SCENE_FOREST_CATCH_RIVAL;\n        gTasks[taskId].tNextMode = MODE_BIKE_SCENE;\n    }\n\n    if (page == PAGE_INTERVAL * 7)\n    {\n         \n        gTasks[taskId].tNextMode = MODE_SHOW_MONS;\n    }\n\n    if (page == PAGE_INTERVAL * 8)\n    {\n         \n        gTasks[taskId].tSceneNum = SCENE_CITY_NIGHT;\n        gTasks[taskId].tNextMode = MODE_BIKE_SCENE;\n    }\n\n    if (gTasks[taskId].tNextMode != MODE_NONE)\n    {\n         \n        return TRUE;\n    }\n\n    return FALSE;",
  },
  "CreateCreditsMonSprite": {
    returnType: "static u8",
    params: "u16 nationalDexNum, s16 x, s16 y, u16 position",
    callsTo: ["CreateMonSpriteFromNationalDexNumber","CreateSprite","StartSpriteAnimIfDifferent"],
    lineCount: 12,
    bodyC: "u8 monSpriteId;\n    u8 bgSpriteId;\n\n    monSpriteId = CreateMonSpriteFromNationalDexNumber(nationalDexNum, x, y, position);\n    gSprites[monSpriteId].oam.priority = 1;\n    gSprites[monSpriteId].sPosition = position + 1;\n    gSprites[monSpriteId].invisible = TRUE;\n    gSprites[monSpriteId].callback = SpriteCB_CreditsMon;\n    gSprites[monSpriteId].sSpriteId = monSpriteId;\n\n    bgSpriteId = CreateSprite(&sSpriteTemplate_CreditsMonBg, gSprites[monSpriteId].x, gSprites[monSpriteId].y, 1);\n    gSprites[bgSpriteId].sMonSpriteId = monSpriteId;\n\n    StartSpriteAnimIfDifferent(&gSprites[bgSpriteId], position);\n\n    return monSpriteId;",
  },
  "DeterminePokemonToShow": {
    returnType: "static void",
    params: "void",
    callsTo: ["GetSetPokedexFlag","GetStarterPokemon","Random","SpeciesToNationalPokedexNum","VarGet"],
    lineCount: 59,
    bodyC: "u16 starter = SpeciesToNationalPokedexNum(GetStarterPokemon(VarGet(VAR_STARTER_MON)));\n    u16 page;\n    u16 dexNum;\n    u16 j;\n\n     \n     \n    for (dexNum = 1, j = 0; dexNum < NATIONAL_DEX_COUNT; dexNum++)\n    {\n        if (GetSetPokedexFlag(dexNum, FLAG_GET_CAUGHT))\n        {\n            sCreditsData->caughtMonIds[j] = dexNum;\n            j++;\n        }\n    }\n\n     \n    for (dexNum = j; dexNum < NATIONAL_DEX_COUNT; dexNum++)\n        sCreditsData->caughtMonIds[dexNum] = NATIONAL_DEX_NONE;\n\n     \n    sCreditsData->numCaughtMon = j;\n    if (sCreditsData->numCaughtMon < NUM_MON_SLIDES)\n        sCreditsData->numMonToShow = j;\n    else\n        sCreditsData->numMonToShow = NUM_MON_SLIDES;\n\n     \n    j = 0;\n    do\n    {\n         \n        page = Random() % sCreditsData->numCaughtMon;\n        sCreditsData->monToShow[j] = sCreditsData->caughtMonIds[page];\n\n         \n        j++;\n        sCreditsData->caughtMonIds[page] = 0;\n        sCreditsData->numCaughtMon--;\n        if (page != sCreditsData->numCaughtMon)\n        {\n             \n            sCreditsData->caughtMonIds[page] = sCreditsData->caughtMonIds[sCreditsData->numCaughtMon];\n            sCreditsData->caughtMonIds[sCreditsData->numCaughtMon] = 0;\n        }\n    }\n    while (sCreditsData->numCaughtMon != 0 && j < NUM_MON_SLIDES);\n\n     \n    if (sCreditsData->numMonToShow < NUM_MON_SLIDES)\n    {\n        for (j = sCreditsData->numMonToShow, page = 0; j < NUM_MON_SLIDES; j++)\n        {\n            sCreditsData->monToShow[j] = sCreditsData->monToShow[page];\n\n            page++;\n            if (page == sCreditsData->numMonToShow)\n                page = 0;\n        }\n         \n        sCreditsData->monToShow[NUM_MON_SLIDES - 1] = starter;\n    }\n    else\n    {\n         \n        for (dexNum = 0; sCreditsData->monToShow[dexNum] != starter && dexNum < NUM_MON_SLIDES; dexNum++);\n\n         \n        if (dexNum < sCreditsData->numMonToShow - 1)\n        {\n            sCreditsData->monToShow[dexNum] = sCreditsData->monToShow[NUM_MON_SLIDES-1];\n            sCreditsData->monToShow[NUM_MON_SLIDES - 1] = starter;\n        }\n        else\n        {\n             \n            sCreditsData->monToShow[NUM_MON_SLIDES - 1] = starter;\n        }\n    }\n    sCreditsData->numMonToShow = NUM_MON_SLIDES;",
  },
  "DrawTheEnd": {
    returnType: "static void",
    params: "u16 offset, u16 palette",
    callsTo: ["LZ77UnCompVram"],
    lineCount: 1,
    bodyC: "LZ77UnCompVram(gCreditsCopyrightEnd_Tilemap, ((u16 *) (VRAM + offset)));",
  },
  "FreeCreditsBgsAndWindows": {
    returnType: "static void",
    params: "void",
    callsTo: ["Free","FreeAllWindowBuffers","GetBgTilemapBuffer"],
    lineCount: 5,
    bodyC: "void *ptr;\n    FreeAllWindowBuffers();\n    ptr = GetBgTilemapBuffer(0);\n    if (ptr)\n        Free(ptr);",
  },
  "InitCreditsBgsAndWindows": {
    returnType: "static void",
    params: "void",
    callsTo: ["ARRAY_COUNT","AllocZeroed","BG_PLTT_ID","CopyWindowToVram","DeactivateAllTextPrinters","InitBgsFromTemplates","InitWindows","LoadPalette","PutWindowTilemap","ResetBgsAndClearDma3BusyFlags","SetBgTilemapBuffer","ShowBg"],
    lineCount: 9,
    bodyC: "ResetBgsAndClearDma3BusyFlags(0);\n    InitBgsFromTemplates(0, sBackgroundTemplates, ARRAY_COUNT(sBackgroundTemplates));\n    SetBgTilemapBuffer(0, AllocZeroed(BG_SCREEN_SIZE));\n    LoadPalette(sCredits_Pal, BG_PLTT_ID(8), 2 * PLTT_SIZE_4BPP);\n    InitWindows(sWindowTemplates);\n    DeactivateAllTextPrinters();\n    PutWindowTilemap(0);\n    CopyWindowToVram(0, COPYWIN_FULL);\n    ShowBg(0);",
  },
  "LoadBikeScene": {
    returnType: "static bool8",
    params: "u8 scene, u8 taskId",
    callsTo: ["CreateIntroBrendanSprite","CreateIntroMaySprite","FreeAllSpritePalettes","LoadCompressedSpriteSheet","LoadCreditsSceneGraphics","LoadSpritePalettes","ResetSpriteData","SetBikeScene","SetCreditsSceneBgCnt","SetGpuReg"],
    lineCount: 64,
    bodyC: "u8 spriteId;\n\n    switch (gMain.state)\n    {\n    default:\n    case 0:\n        SetGpuReg(REG_OFFSET_DISPCNT, 0);\n        SetGpuReg(REG_OFFSET_BG3HOFS, 8);\n        SetGpuReg(REG_OFFSET_BG3VOFS, 0);\n        SetGpuReg(REG_OFFSET_BG2HOFS, 0);\n        SetGpuReg(REG_OFFSET_BG2VOFS, 0);\n        SetGpuReg(REG_OFFSET_BG1HOFS, 0);\n        SetGpuReg(REG_OFFSET_BG1VOFS, 0);\n        SetGpuReg(REG_OFFSET_BLDCNT, 0);\n        SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n        ResetSpriteData();\n        FreeAllSpritePalettes();\n        gMain.state = 1;\n        break;\n    case 1:\n        gIntroCredits_MovingSceneryVBase = 34;\n        gIntroCredits_MovingSceneryVOffset = 0;\n        LoadCreditsSceneGraphics(scene);\n        gMain.state++;\n        break;\n    case 2:\n        if (gSaveBlock2Ptr->playerGender == MALE)\n        {\n            LoadCompressedSpriteSheet(gSpriteSheet_CreditsBrendan);\n            LoadCompressedSpriteSheet(gSpriteSheet_CreditsRivalMay);\n            LoadCompressedSpriteSheet(gSpriteSheet_CreditsBicycle);\n            LoadSpritePalettes(gSpritePalettes_Credits);\n\n            spriteId = CreateIntroBrendanSprite(120, 46);\n            gTasks[taskId].tPlayerSpriteId = spriteId;\n            gSprites[spriteId].callback = SpriteCB_Player;\n            gSprites[spriteId].anims = sAnims_Player;\n\n            spriteId = CreateIntroMaySprite(DISPLAY_WIDTH + 32, 46);\n            gTasks[taskId].tRivalSpriteId = spriteId;\n            gSprites[spriteId].callback = SpriteCB_Rival;\n            gSprites[spriteId].anims = sAnims_Rival;\n        }\n        else\n        {\n            LoadCompressedSpriteSheet(gSpriteSheet_CreditsMay);\n            LoadCompressedSpriteSheet(gSpriteSheet_CreditsRivalBrendan);\n            LoadCompressedSpriteSheet(gSpriteSheet_CreditsBicycle);\n            LoadSpritePalettes(gSpritePalettes_Credits);\n\n            spriteId = CreateIntroMaySprite(120, 46);\n            gTasks[taskId].tPlayerSpriteId = spriteId;\n            gSprites[spriteId].callback = SpriteCB_Player;\n            gSprites[spriteId].anims = sAnims_Player;\n\n            spriteId = CreateIntroBrendanSprite(DISPLAY_WIDTH + 32, 46);\n            gTasks[taskId].tRivalSpriteId = spriteId;\n            gSprites[spriteId].callback = SpriteCB_Rival;\n            gSprites[spriteId].anims = sAnims_Rival;\n        };\n        gMain.state++;\n        break;\n    case 3:\n        SetBikeScene(scene, taskId);\n        SetCreditsSceneBgCnt(scene);\n        gMain.state = 0;\n        return TRUE;\n    }\n    return FALSE;",
  },
  "LoadTheEndScreen": {
    returnType: "static void",
    params: "u16 tileOffsetLoad, u16 tileOffsetWrite, u16 palOffset",
    callsTo: ["LZ77UnCompVram","LoadPalette"],
    lineCount: 7,
    bodyC: "u16 baseTile;\n    u16 i;\n\n    LZ77UnCompVram(gCreditsCopyrightEnd_Gfx, (void *)(VRAM + tileOffsetLoad));\n    LoadPalette(gIntroCopyright_Pal, palOffset, sizeof(gIntroCopyright_Pal));\n\n    baseTile = (palOffset / 16) << 12;\n\n    for (i = 0; i < 32 * 32; i++)\n        ((u16 *) (VRAM + tileOffsetWrite))[i] = baseTile;",
  },
  "PrintCreditsText": {
    returnType: "static void",
    params: "const u8 *string, u8 y, bool8 isTitle",
    callsTo: ["AddTextPrinterParameterized4","GetStringCenterAlignXOffsetWithLetterSpacing"],
    lineCount: 15,
    bodyC: "u8 x;\n    u8 color[3];\n\n    color[0] = TEXT_COLOR_TRANSPARENT;\n\n    if (isTitle == TRUE)\n    {\n        color[1] = TEXT_COLOR_LIGHT_GRAY;\n        color[2] = TEXT_COLOR_RED;\n    }\n    else\n    {\n        color[1] = TEXT_COLOR_WHITE;\n        color[2] = TEXT_COLOR_DARK_GRAY;\n    }\n\n    x = GetStringCenterAlignXOffsetWithLetterSpacing(FONT_NORMAL, string, DISPLAY_WIDTH, 1);\n    AddTextPrinterParameterized4(0, FONT_NORMAL, x, y, 1, 0, color, TEXT_SKIP_DRAW, string);",
  },
  "ResetCreditsTasks": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask"],
    lineCount: 21,
    bodyC: "if (gTasks[taskId].tTaskId_BgScenery != 0)\n    {\n        DestroyTask(gTasks[taskId].tTaskId_BgScenery);\n        gTasks[taskId].tTaskId_BgScenery = 0;\n    }\n\n     \n    if (gTasks[taskId].tTaskId_BikeScene != 0)\n    {\n        DestroyTask(gTasks[taskId].tTaskId_BikeScene);\n        gTasks[taskId].tTaskId_BikeScene = 0;\n    }\n\n     \n    if (gTasks[taskId].tTaskId_SceneryPal != 0)\n    {\n        DestroyTask(gTasks[taskId].tTaskId_SceneryPal);\n        gTasks[taskId].tTaskId_SceneryPal = 0;\n    }\n\n     \n    if (gTasks[taskId].tTaskId_ShowMons != 0)\n    {\n        DestroyTask(gTasks[taskId].tTaskId_ShowMons);\n        gTasks[taskId].tTaskId_ShowMons = 0;\n    }\n\n    gIntroCredits_MovingSceneryState = INTROCRED_SCENERY_DESTROY;",
  },
  "ResetGpuAndVram": {
    returnType: "static void",
    params: "void",
    callsTo: ["DmaFill16","DmaFill32","SetGpuReg"],
    lineCount: 15,
    bodyC: "SetGpuReg(REG_OFFSET_DISPCNT, 0);\n\n    SetGpuReg(REG_OFFSET_BG3HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG3VOFS, 0);\n    SetGpuReg(REG_OFFSET_BG2HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG2VOFS, 0);\n    SetGpuReg(REG_OFFSET_BG1HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG1VOFS, 0);\n    SetGpuReg(REG_OFFSET_BG0HOFS, 0);\n    SetGpuReg(REG_OFFSET_BG0VOFS, 0);\n\n    SetGpuReg(REG_OFFSET_BLDCNT, 0);\n    SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n    SetGpuReg(REG_OFFSET_BLDY, 0);\n\n    DmaFill16(3, 0, (void *)VRAM, VRAM_SIZE);\n    DmaFill32(3, 0, (void *)OAM, OAM_SIZE);\n    DmaFill16(3, 0, (void *)(PLTT + 2), PLTT_SIZE - 2);",
  },
  "SetBikeScene": {
    returnType: "static void",
    params: "u8 scene, u8 taskId",
    callsTo: ["CreateBicycleBgAnimationTask","CreateTask"],
    lineCount: 70,
    bodyC: "switch (scene)\n    {\n    case SCENE_OCEAN_MORNING:\n        gSprites[gTasks[taskId].tPlayerSpriteId].invisible = FALSE;\n        gSprites[gTasks[taskId].tRivalSpriteId].invisible = FALSE;\n        gSprites[gTasks[taskId].tPlayerSpriteId].x = DISPLAY_WIDTH + 32;\n        gSprites[gTasks[taskId].tRivalSpriteId].x = DISPLAY_WIDTH + 32;\n        gSprites[gTasks[taskId].tPlayerSpriteId].y = 46;\n        gSprites[gTasks[taskId].tRivalSpriteId].y = 46;\n        gSprites[gTasks[taskId].tPlayerSpriteId].data[0] = 0;\n        gSprites[gTasks[taskId].tRivalSpriteId].data[0] = 0;\n        gTasks[taskId].tTaskId_BgScenery = CreateBicycleBgAnimationTask(0, 0x2000, 0x20, 8);\n        break;\n    case SCENE_OCEAN_SUNSET:\n        gSprites[gTasks[taskId].tPlayerSpriteId].invisible = FALSE;\n        gSprites[gTasks[taskId].tRivalSpriteId].invisible = FALSE;\n        gSprites[gTasks[taskId].tPlayerSpriteId].x = 120;\n        gSprites[gTasks[taskId].tRivalSpriteId].x = DISPLAY_WIDTH + 32;\n        gSprites[gTasks[taskId].tPlayerSpriteId].y = 46;\n        gSprites[gTasks[taskId].tRivalSpriteId].y = 46;\n        gSprites[gTasks[taskId].tPlayerSpriteId].data[0] = 0;\n        gSprites[gTasks[taskId].tRivalSpriteId].data[0] = 0;\n        gTasks[taskId].tTaskId_BgScenery = CreateBicycleBgAnimationTask(0, 0x2000, 0x20, 8);\n        break;\n    case SCENE_FOREST_RIVAL_ARRIVE:\n        gSprites[gTasks[taskId].tPlayerSpriteId].invisible = FALSE;\n        gSprites[gTasks[taskId].tRivalSpriteId].invisible = FALSE;\n        gSprites[gTasks[taskId].tPlayerSpriteId].x = 120;\n        gSprites[gTasks[taskId].tRivalSpriteId].x = DISPLAY_WIDTH + 32;\n        gSprites[gTasks[taskId].tPlayerSpriteId].y = 46;\n        gSprites[gTasks[taskId].tRivalSpriteId].y = 46;\n        gSprites[gTasks[taskId].tPlayerSpriteId].data[0] = 0;\n        gSprites[gTasks[taskId].tRivalSpriteId].data[0] = 0;\n        gTasks[taskId].tTaskId_BgScenery = CreateBicycleBgAnimationTask(1, 0x2000, 0x200, 8);\n        break;\n    case SCENE_FOREST_CATCH_RIVAL:\n        gSprites[gTasks[taskId].tPlayerSpriteId].invisible = FALSE;\n        gSprites[gTasks[taskId].tRivalSpriteId].invisible = FALSE;\n        gSprites[gTasks[taskId].tPlayerSpriteId].x = 120;\n        gSprites[gTasks[taskId].tRivalSpriteId].x = -32;\n        gSprites[gTasks[taskId].tPlayerSpriteId].y = 46;\n        gSprites[gTasks[taskId].tRivalSpriteId].y = 46;\n        gSprites[gTasks[taskId].tPlayerSpriteId].data[0] = 0;\n        gSprites[gTasks[taskId].tRivalSpriteId].data[0] = 0;\n        gTasks[taskId].tTaskId_BgScenery = CreateBicycleBgAnimationTask(1, 0x2000, 0x200, 8);\n        break;\n    case SCENE_CITY_NIGHT:\n        gSprites[gTasks[taskId].tPlayerSpriteId].invisible = FALSE;\n        gSprites[gTasks[taskId].tRivalSpriteId].invisible = FALSE;\n        gSprites[gTasks[taskId].tPlayerSpriteId].x = 88;\n        gSprites[gTasks[taskId].tRivalSpriteId].x = 152;\n        gSprites[gTasks[taskId].tPlayerSpriteId].y = 46;\n        gSprites[gTasks[taskId].tRivalSpriteId].y = 46;\n        gSprites[gTasks[taskId].tPlayerSpriteId].data[0] = 0;\n        gSprites[gTasks[taskId].tRivalSpriteId].data[0] = 0;\n        gTasks[taskId].tTaskId_BgScenery = CreateBicycleBgAnimationTask(2, 0x2000, 0x200, 8);\n        break;\n    }\n\n    gTasks[taskId].tTaskId_SceneryPal = CreateTask(Task_CycleSceneryPalette, 0);\n    gTasks[gTasks[taskId].tTaskId_SceneryPal].tState = scene;\n    gTasks[gTasks[taskId].tTaskId_SceneryPal].tTimer = 0;\n    gTasks[gTasks[taskId].tTaskId_SceneryPal].tMainTaskId = taskId;\n\n    gTasks[taskId].tTaskId_BikeScene = CreateTask(Task_BikeScene, 0);\n    gTasks[gTasks[taskId].tTaskId_BikeScene].tState = 0;\n    gTasks[gTasks[taskId].tTaskId_BikeScene].data[1] = taskId;  \n    gTasks[gTasks[taskId].tTaskId_BikeScene].tPlayer = gTasks[taskId].tPlayerSpriteId;\n    gTasks[gTasks[taskId].tTaskId_BikeScene].tRival = gTasks[taskId].tRivalSpriteId;\n    gTasks[gTasks[taskId].tTaskId_BikeScene].tDelay = 0;\n\n    if (scene == SCENE_FOREST_RIVAL_ARRIVE)\n        gTasks[gTasks[taskId].tTaskId_BikeScene].tSinIdx = 69;",
  },
  "SpriteCB_CreditsMon": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["BLDALPHA_BLEND","FreeAndDestroyMonPicSprite","SetGpuReg","SetOamMatrix"],
    lineCount: 80,
    bodyC: "if (gIntroCredits_MovingSceneryState != INTROCRED_SCENERY_NORMAL)\n    {\n        FreeAndDestroyMonPicSprite(sprite->sSpriteId);\n        return;\n    }\n\n    sprite->data[7]++;\n    switch (sprite->sState)\n    {\n    case 0:\n    default:\n        sprite->oam.affineMode = ST_OAM_AFFINE_NORMAL;\n        sprite->oam.matrixNum = sprite->sPosition;\n        sprite->data[2] = 16;\n        SetOamMatrix(sprite->sPosition, 0x10000 / sprite->data[2], 0, 0, 0x10000 / sprite->data[2]);\n        sprite->invisible = FALSE;\n        sprite->sState = 1;\n        break;\n    case 1:\n        if (sprite->data[2] < 256)\n        {\n            sprite->data[2] += 8;\n            SetOamMatrix(sprite->sPosition, 0x10000 / sprite->data[2], 0, 0, 0x10000 / sprite->data[2]);\n        }\n        else\n        {\n            sprite->sState++;\n        }\n        switch (sprite->sPosition)\n        {\n        case POS_LEFT + 1:\n            if ((sprite->data[7] & 3) == 0)\n                sprite->y++;\n            sprite->x -= 2;\n            break;\n        case POS_CENTER + 1:\n            break;\n        case POS_RIGHT + 1:\n            if ((sprite->data[7] & 3) == 0)\n                sprite->y++;\n            sprite->x += 2;\n            break;\n        }\n        break;\n    case 2:\n        if (sprite->data[3] != 0)\n        {\n            sprite->data[3]--;\n        }\n        else\n        {\n            SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_EFFECT_BLEND | BLDCNT_TGT2_BG0 | BLDCNT_TGT2_BG1 | BLDCNT_TGT2_BG2 | BLDCNT_TGT2_BG3);\n            SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(16, 0));\n            sprite->oam.objMode = ST_OAM_OBJ_BLEND;\n            sprite->data[3] = 16;\n            sprite->sState++;\n        }\n        break;\n    case 3:\n        if (sprite->data[3] != 0)\n        {\n            int data3;\n\n            sprite->data[3]--;\n\n            data3 = 16 - sprite->data[3];\n            SetGpuReg(REG_OFFSET_BLDALPHA, (data3 << 8) + sprite->data[3]);\n        }\n        else\n        {\n            sprite->invisible = TRUE;\n            sprite->sState = 9;\n        }\n        break;\n    case 9:\n        sprite->sState++;\n        break;\n    case 10:\n        SetGpuReg(REG_OFFSET_BLDCNT, 0);\n        SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n        FreeAndDestroyMonPicSprite(sprite->data[6]);\n        break;\n    }",
  },
  "SpriteCB_CreditsMonBg": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroySprite"],
    lineCount: 12,
    bodyC: "if (gSprites[sprite->sMonSpriteId].data[0] == 10\n     || gIntroCredits_MovingSceneryState != INTROCRED_SCENERY_NORMAL)\n    {\n        DestroySprite(sprite);\n        return;\n    }\n\n     \n    sprite->invisible = gSprites[sprite->sMonSpriteId].invisible;\n    sprite->oam.objMode = gSprites[sprite->sMonSpriteId].oam.objMode;\n    sprite->oam.affineMode = gSprites[sprite->sMonSpriteId].oam.affineMode;\n    sprite->oam.matrixNum = gSprites[sprite->sMonSpriteId].oam.matrixNum;\n    sprite->x = gSprites[sprite->sMonSpriteId].x;\n    sprite->y = gSprites[sprite->sMonSpriteId].y;",
  },
  "SpriteCB_Player": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroySprite","StartSpriteAnimIfDifferent"],
    lineCount: 32,
    bodyC: "if (gIntroCredits_MovingSceneryState != INTROCRED_SCENERY_NORMAL)\n    {\n        DestroySprite(sprite);\n        return;\n    }\n\n    switch (sprite->sState)\n    {\n    case 0:\n        StartSpriteAnimIfDifferent(sprite, 0);\n        break;\n    case 1:\n        StartSpriteAnimIfDifferent(sprite, 1);\n        if (sprite->x > -32)\n            sprite->x--;\n        break;\n    case 2:\n        StartSpriteAnimIfDifferent(sprite, 2);\n        break;\n    case 3:\n        StartSpriteAnimIfDifferent(sprite, 3);\n        break;\n    case 4:\n        StartSpriteAnimIfDifferent(sprite, 0);\n        if (sprite->x > DISPLAY_WIDTH / 2)\n            sprite->x--;\n        break;\n    case 5:\n        StartSpriteAnimIfDifferent(sprite, 0);\n        if (sprite->x > -32)\n            sprite->x--;\n        break;\n    }",
  },
  "SpriteCB_Rival": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroySprite","StartSpriteAnimIfDifferent"],
    lineCount: 32,
    bodyC: "if (gIntroCredits_MovingSceneryState != INTROCRED_SCENERY_NORMAL)\n    {\n        DestroySprite(sprite);\n        return;\n    }\n\n    switch (sprite->sState)\n    {\n    case 0:\n        sprite->y2 = 0;\n        StartSpriteAnimIfDifferent(sprite, 0);\n        break;\n    case 1:\n        if (sprite->x > 200)\n            StartSpriteAnimIfDifferent(sprite, 1);\n        else\n            StartSpriteAnimIfDifferent(sprite, 2);\n        if (sprite->x > -32)\n            sprite->x -= 2;\n        sprite->y2 = -gIntroCredits_MovingSceneryVOffset;\n        break;\n    case 2:\n        sprite->data[7]++;\n        StartSpriteAnimIfDifferent(sprite, 0);\n        if ((sprite->data[7] & 3) == 0)\n            sprite->x++;\n        break;\n    case 3:\n        StartSpriteAnimIfDifferent(sprite, 0);\n        if (sprite->x > -32)\n            sprite->x--;\n        break;\n    }",
  },
  "Task_BikeScene": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["Sin"],
    lineCount: 79,
    bodyC: "switch (gTasks[taskId].tState)\n    {\n    case 0:\n        gIntroCredits_MovingSceneryVOffset = Sin((gTasks[taskId].tSinIdx >> 1) & 0x7F, 12);\n        gTasks[taskId].tSinIdx++;\n        break;\n    case 1:\n        if (gIntroCredits_MovingSceneryVOffset != 0)\n        {\n            gIntroCredits_MovingSceneryVOffset = Sin((gTasks[taskId].tSinIdx >> 1) & 0x7F, 12);\n            gTasks[taskId].tSinIdx++;\n        }\n        else\n        {\n            gSprites[gTasks[taskId].tPlayer].data[0] = 2;\n            gTasks[taskId].tSinIdx = 0;\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 2:\n        if (gTasks[taskId].tSinIdx < 64)\n        {\n            gTasks[taskId].tSinIdx++;\n            gIntroCredits_MovingSceneryVOffset = Sin(gTasks[taskId].tSinIdx & 0x7F, 20);\n        }\n        else\n        {\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 3:\n        gSprites[gTasks[taskId].tPlayer].data[0] = 3;\n        gSprites[gTasks[taskId].tRival].data[0] = 1;\n        gTasks[taskId].tDelay = 120;\n        gTasks[taskId].tState++;\n        break;\n    case 4:\n        if (gTasks[taskId].tDelay != 0)\n        {\n            gTasks[taskId].tDelay--;\n        }\n        else\n        {\n            gTasks[taskId].tSinIdx = 64;\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 5:\n        if (gTasks[taskId].tSinIdx > 0)\n        {\n            gTasks[taskId].tSinIdx--;\n            gIntroCredits_MovingSceneryVOffset = Sin(gTasks[taskId].tSinIdx & 0x7F, 20);\n        }\n        else\n        {\n            gSprites[gTasks[taskId].tPlayer].data[0] = 1;\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 6:\n        gTasks[taskId].tState = 50;\n        break;\n    case 10:\n        gSprites[gTasks[taskId].tRival].data[0] = 2;\n        gTasks[taskId].tState = 50;\n        break;\n    case 20:\n        gSprites[gTasks[taskId].tPlayer].data[0] = 4;\n        gTasks[taskId].tState = 50;\n        break;\n    case 30:\n        gSprites[gTasks[taskId].tPlayer].data[0] = 5;\n        gSprites[gTasks[taskId].tRival].data[0] = 3;\n        gTasks[taskId].tState = 50;\n        break;\n    case 50:\n        gTasks[taskId].tState = 0;\n        break;\n    }",
  },
  "Task_CreditsMain": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BeginNormalPaletteFade"],
    lineCount: 25,
    bodyC: "u16 mode;\n\n    if (gTasks[taskId].tEndCredits)\n    {\n        s16 bikeTaskId = gTasks[taskId].tTaskId_BikeScene;\n        gTasks[bikeTaskId].tState = 30;\n\n        gTasks[taskId].tTheEndDelay = 256;\n        gTasks[taskId].func = Task_CreditsTheEnd1;\n        return;\n    }\n\n    sUnkVar = 0;\n    mode = gTasks[taskId].tNextMode;\n\n    if (gTasks[taskId].tNextMode == MODE_BIKE_SCENE)\n    {\n         \n        gTasks[taskId].tCurrentMode = mode;\n        gTasks[taskId].tNextMode = MODE_NONE;\n        BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_BLACK);\n        gTasks[taskId].func = Task_ReadyBikeScene;\n    }\n    else if (gTasks[taskId].tNextMode == MODE_SHOW_MONS)\n    {\n         \n        gTasks[taskId].tCurrentMode = mode;\n        gTasks[taskId].tNextMode = MODE_NONE;\n        BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_BLACK);\n        gTasks[taskId].func = Task_ReadyShowMons;\n    }",
  },
  "Task_CreditsSoftReset": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["SoftReset"],
    lineCount: 2,
    bodyC: "if (!gPaletteFade.active)\n        SoftReset(RESET_ALL);",
  },
  "Task_CreditsTheEnd1": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BeginNormalPaletteFade"],
    lineCount: 7,
    bodyC: "if (gTasks[taskId].tTheEndDelay)\n    {\n        gTasks[taskId].tTheEndDelay--;\n        return;\n    }\n\n    BeginNormalPaletteFade(PALETTES_ALL, 12, 0, 16, RGB_BLACK);\n    gTasks[taskId].func = Task_CreditsTheEnd2;",
  },
  "Task_CreditsTheEnd2": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["ResetCreditsTasks"],
    lineCount: 5,
    bodyC: "if (!gPaletteFade.active)\n    {\n        ResetCreditsTasks(taskId);\n        gTasks[taskId].func = Task_CreditsTheEnd3;\n    }",
  },
  "Task_CreditsTheEnd3": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BGCNT_CHARBASE","BGCNT_PRIORITY","BGCNT_SCREENBASE","BG_PLTT_ID","BeginNormalPaletteFade","EnableInterrupts","FreeAllSpritePalettes","LoadTheEndScreen","ResetGpuAndVram","ResetPaletteFade","ResetSpriteData","SetGpuReg"],
    lineCount: 17,
    bodyC: "ResetGpuAndVram();\n    ResetPaletteFade();\n    LoadTheEndScreen(0, 0x3800, BG_PLTT_ID(0));\n    ResetSpriteData();\n    FreeAllSpritePalettes();\n    BeginNormalPaletteFade(PALETTES_ALL, 8, 16, 0, RGB_BLACK);\n\n    SetGpuReg(REG_OFFSET_BG0CNT, BGCNT_PRIORITY(0)\n                               | BGCNT_CHARBASE(0)\n                               | BGCNT_SCREENBASE(7)\n                               | BGCNT_16COLOR\n                               | BGCNT_TXT256x256);\n    EnableInterrupts(INTR_FLAG_VBLANK);\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_0\n                                | DISPCNT_OBJ_1D_MAP\n                                | DISPCNT_BG0_ON);\n\n    gTasks[taskId].tDelay = 235;  \n    gTasks[taskId].func = Task_CreditsTheEnd4;",
  },
  "Task_CreditsTheEnd4": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BeginNormalPaletteFade"],
    lineCount: 7,
    bodyC: "if (gTasks[taskId].tDelay)\n    {\n        gTasks[taskId].tDelay--;\n        return;\n    }\n\n    BeginNormalPaletteFade(PALETTES_ALL, 6, 0, 16, RGB_BLACK);\n    gTasks[taskId].func = Task_CreditsTheEnd5;",
  },
  "Task_CreditsTheEnd5": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BeginNormalPaletteFade","DrawTheEnd"],
    lineCount: 7,
    bodyC: "if (!gPaletteFade.active)\n    {\n        DrawTheEnd(0x3800, 0);\n\n        BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 0, RGB_BLACK);\n        gTasks[taskId].tDelay = 7200;\n        gTasks[taskId].func = Task_CreditsTheEnd6;\n    }",
  },
  "Task_CreditsTheEnd6": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BeginNormalPaletteFade","FadeOutBGM","m4aSongNumStart"],
    lineCount: 15,
    bodyC: "if (!gPaletteFade.active)\n    {\n        if (gTasks[taskId].tDelay == 0 || gMain.newKeys)\n        {\n            FadeOutBGM(4);\n            BeginNormalPaletteFade(PALETTES_ALL, 8, 0, 16, RGB_WHITEALPHA);\n            gTasks[taskId].func = Task_CreditsSoftReset;\n            return;\n        }\n\n        if (gTasks[taskId].tDelay == 7144)\n            FadeOutBGM(8);\n\n        if (gTasks[taskId].tDelay == 6840)\n            m4aSongNumStart(MUS_END);\n\n        gTasks[taskId].tDelay--;\n    }",
  },
  "Task_CycleSceneryPalette": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CycleSceneryPalette"],
    lineCount: 49,
    bodyC: "s16 bikeTaskId;\n\n    switch (gTasks[taskId].tState)\n    {\n    default:\n    case SCENE_OCEAN_MORNING:\n        if (gTasks[taskId].tTimer != TIMER_STOP)\n        {\n            if (gTasks[gTasks[gTasks[taskId].tMainTaskId].tTaskId_UpdatePage].tCurrentPage == 2)\n            {\n                gTasks[gTasks[gTasks[taskId].tMainTaskId].tTaskId_BikeScene].tState = 20;\n                gTasks[taskId].tTimer = TIMER_STOP;\n            }\n        }\n        CycleSceneryPalette(0);\n        break;\n    case SCENE_OCEAN_SUNSET:\n        CycleSceneryPalette(0);\n        break;\n    case SCENE_FOREST_RIVAL_ARRIVE:\n        if (gTasks[taskId].tTimer != TIMER_STOP)\n        {\n            bikeTaskId = gTasks[gTasks[taskId].tMainTaskId].tTaskId_BikeScene;\n\n             \n            if ((gTasks[bikeTaskId].tSinIdx & -128) == 640)\n            {\n                gTasks[bikeTaskId].tState = 1;\n                gTasks[taskId].tTimer = TIMER_STOP;\n            }\n        }\n        CycleSceneryPalette(1);\n        break;\n    case SCENE_FOREST_CATCH_RIVAL:\n        if (gTasks[taskId].tTimer != TIMER_STOP)\n        {\n\n            if (gTasks[taskId].tTimer == 620)  \n            {\n                gTasks[gTasks[gTasks[taskId].tMainTaskId].tTaskId_BikeScene].tState = 10;\n                gTasks[taskId].tTimer = TIMER_STOP;\n            }\n            else\n            {\n                gTasks[taskId].tTimer++;\n            }\n        }\n        CycleSceneryPalette(1);\n        break;\n    case SCENE_CITY_NIGHT:\n        CycleSceneryPalette(2);\n        break;\n    }",
  },
  "Task_LoadShowMons": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BGCNT_CHARBASE","BGCNT_PRIORITY","BGCNT_SCREENBASE","BG_PLTT_ID","BG_SCREEN_ADDR","BeginNormalPaletteFade","CreateTask","FreeAllSpritePalettes","LZ77UnCompVram","LoadPalette","LoadSpritePalette","LoadSpriteSheet","PLTT_SIZEOF","RGB","ResetAllPicSprites","ResetSpriteData","SetGpuReg"],
    lineCount: 53,
    bodyC: "switch (gMain.state)\n    {\n    default:\n    case 0:\n    {\n        u16 i;\n        u16 *temp;\n\n        ResetSpriteData();\n        ResetAllPicSprites();\n        FreeAllSpritePalettes();\n        gReservedSpritePaletteCount = 8;\n        LZ77UnCompVram(gBirchBagGrass_Gfx, (void *)VRAM);\n        LZ77UnCompVram(gBirchGrassTilemap, (void *)(BG_SCREEN_ADDR(7)));\n        LoadPalette(gBirchBagGrass_Pal + 1, BG_PLTT_ID(0) + 1, PLTT_SIZEOF(2 * 16 - 1));\n\n        for (i = 0; i < MON_PIC_SIZE; i++)\n            gDecompressionBuffer[i] = 0x11;\n        for (i = 0; i < MON_PIC_SIZE; i++)\n            (gDecompressionBuffer + MON_PIC_SIZE)[i] = 0x22;\n        for (i = 0; i < MON_PIC_SIZE; i++)\n            (gDecompressionBuffer + MON_PIC_SIZE * 2)[i] = 0x33;\n\n        temp = (u16 *)(&gDecompressionBuffer[MONBG_OFFSET]);\n        temp[0] = RGB_BLACK;\n        temp[1] = RGB(31, 31, 20);  \n        temp[2] = RGB(31, 20, 20);  \n        temp[3] = RGB(20, 20, 31);  \n\n        LoadSpriteSheet(sSpriteSheet_MonBg);\n        LoadSpritePalette(sSpritePalette_MonBg);\n\n        gMain.state++;\n        break;\n    }\n    case 1:\n        gTasks[taskId].tTaskId_ShowMons = CreateTask(Task_ShowMons, 0);\n        gTasks[gTasks[taskId].tTaskId_ShowMons].tState = 1;\n        gTasks[gTasks[taskId].tTaskId_ShowMons].tMainTaskId = taskId;\n        gTasks[gTasks[taskId].tTaskId_ShowMons].data[2] = gTasks[taskId].tSceneNum;  \n\n        BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_BLACK);\n        SetGpuReg(REG_OFFSET_BG3HOFS, 0);\n        SetGpuReg(REG_OFFSET_BG3VOFS, 32);\n        SetGpuReg(REG_OFFSET_BG3CNT, BGCNT_PRIORITY(3)\n                                   | BGCNT_CHARBASE(0)\n                                   | BGCNT_SCREENBASE(7)\n                                   | BGCNT_16COLOR\n                                   | BGCNT_TXT256x256);\n        SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_0\n                                    | DISPCNT_OBJ_1D_MAP\n                                    | DISPCNT_BG0_ON\n                                    | DISPCNT_BG3_ON\n                                    | DISPCNT_OBJ_ON);\n\n        gMain.state = 0;\n        gIntroCredits_MovingSceneryState = INTROCRED_SCENERY_NORMAL;\n        gTasks[taskId].func = Task_WaitPaletteFade;\n        break;\n    }",
  },
  "Task_ReadyBikeScene": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["ResetCreditsTasks","SetGpuReg"],
    lineCount: 6,
    bodyC: "if (!gPaletteFade.active)\n    {\n        SetGpuReg(REG_OFFSET_DISPCNT, 0);\n        ResetCreditsTasks(taskId);\n        gTasks[taskId].func = Task_SetBikeScene;\n    }",
  },
  "Task_ReadyShowMons": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["ResetCreditsTasks","SetGpuReg"],
    lineCount: 6,
    bodyC: "if (!gPaletteFade.active)\n    {\n        SetGpuReg(REG_OFFSET_DISPCNT, 0);\n        ResetCreditsTasks(taskId);\n        gTasks[taskId].func = Task_LoadShowMons;\n    }",
  },
  "Task_SetBikeScene": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BeginNormalPaletteFade","EnableInterrupts","LoadBikeScene","SetVBlankCallback"],
    lineCount: 8,
    bodyC: "SetVBlankCallback(NULL);\n\n    if (LoadBikeScene(gTasks[taskId].tSceneNum, taskId))\n    {\n        BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_BLACK);\n        EnableInterrupts(INTR_FLAG_VBLANK);\n        SetVBlankCallback(VBlankCB_Credits);\n        gTasks[taskId].func = Task_WaitPaletteFade;\n    }",
  },
  "Task_ShowMons": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateCreditsMonSprite"],
    lineCount: 42,
    bodyC: "u8 spriteId;\n\n    switch (gTasks[taskId].tState)\n    {\n    case 0:\n        break;\n    case 1:\n        if (sCreditsData->nextImgPos == POS_LEFT && gTasks[gTasks[taskId].tMainTaskId].tPrintedPage == FALSE)\n            break;\n        gTasks[taskId].tState++;\n        break;\n    case 2:\n        if (sCreditsData->imgCounter == NUM_MON_SLIDES || gTasks[gTasks[taskId].tMainTaskId].func != Task_CreditsMain)\n            break;\n        spriteId = CreateCreditsMonSprite(sCreditsData->monToShow[sCreditsData->currShownMon],\n                                    sMonSpritePos[sCreditsData->nextImgPos][0],\n                                    sMonSpritePos[sCreditsData->nextImgPos][1],\n                                    sCreditsData->nextImgPos);\n        if (sCreditsData->currShownMon < sCreditsData->numMonToShow - 1)\n        {\n            sCreditsData->currShownMon++;\n            gSprites[spriteId].data[3] = 52;  \n        }\n        else\n        {\n            sCreditsData->currShownMon = 0;\n            gSprites[spriteId].data[3] = 512;\n        }\n        sCreditsData->imgCounter++;\n\n        if (sCreditsData->nextImgPos == POS_RIGHT)\n            sCreditsData->nextImgPos = POS_LEFT;\n        else\n            sCreditsData->nextImgPos++;\n\n        gTasks[taskId].tDelay = 52;  \n        gTasks[taskId].tState++;\n        break;\n    case 3:\n        if (gTasks[taskId].tDelay != 0)\n            gTasks[taskId].tDelay--;\n        else\n            gTasks[taskId].tState = 1;\n        break;\n    }",
  },
  "Task_UpdatePage": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BeginNormalPaletteFade","CheckChangeScene","CopyWindowToVram","DestroyTask","FREE_AND_SET_NULL","FillWindowPixelBuffer","FreeCreditsBgsAndWindows","PIXEL_FILL","PrintCreditsText"],
    lineCount: 89,
    bodyC: "int i;\n\n    switch (gTasks[taskId].tState)\n    {\n    case 0:\n    case 6:\n    case 7:\n    case 8:\n    case 9:\n    default:\n        if (!gPaletteFade.active)\n        {\n            gTasks[taskId].tState = 1;\n            gTasks[taskId].tDelay = 72;\n            gTasks[gTasks[taskId].tMainTaskId].tPrintedPage = FALSE;\n            sUnkVar = 0;\n        }\n        return;\n    case 1:\n        if (gTasks[taskId].tDelay != 0)\n        {\n            gTasks[taskId].tDelay--;\n            return;\n        }\n        gTasks[taskId].tState++;\n        return;\n    case 2:\n        if (gTasks[gTasks[taskId].tMainTaskId].func == Task_CreditsMain)\n        {\n            if (gTasks[taskId].tCurrentPage < PAGE_COUNT)\n            {\n                 \n                for (i = 0; i < ENTRIES_PER_PAGE; i++)\n                    PrintCreditsText(\n                        sCreditsEntryPointerTable[gTasks[taskId].tCurrentPage][i]->text,\n                         5 + i * 16,\n                         sCreditsEntryPointerTable[gTasks[taskId].tCurrentPage][i]->isTitle);\n                CopyWindowToVram(0, COPYWIN_GFX);\n\n                gTasks[taskId].tCurrentPage++;\n                gTasks[taskId].tState++;\n\n                gTasks[gTasks[taskId].tMainTaskId].tPrintedPage = TRUE;\n\n                if (gTasks[gTasks[taskId].tMainTaskId].tCurrentMode == MODE_BIKE_SCENE)\n                    BeginNormalPaletteFade(0x300, 0, 16, 0, COLOR_LIGHT_GREEN);\n                else  \n                    BeginNormalPaletteFade(0x300, 0, 16, 0, COLOR_DARK_GREEN);\n                return;\n            }\n\n             \n            gTasks[taskId].tState = 10;\n            return;\n        }\n        gTasks[gTasks[taskId].tMainTaskId].tPrintedPage = FALSE;\n        return;\n    case 3:\n        if (!gPaletteFade.active)\n        {\n            gTasks[taskId].tDelay = 121;  \n            gTasks[taskId].tState++;\n        }\n        return;\n    case 4:\n        if (gTasks[taskId].tDelay != 0)\n        {\n            gTasks[taskId].tDelay--;\n            return;\n        }\n\n        if (CheckChangeScene((u8)gTasks[taskId].tCurrentPage, (u8)gTasks[taskId].tMainTaskId))\n        {\n            gTasks[taskId].tState++;\n            return;\n        }\n        gTasks[taskId].tState++;\n        if (gTasks[gTasks[taskId].tMainTaskId].tCurrentMode == MODE_BIKE_SCENE)\n            BeginNormalPaletteFade(0x300, 0, 0, 16, COLOR_LIGHT_GREEN);\n        else  \n            BeginNormalPaletteFade(0x300, 0, 0, 16, COLOR_DARK_GREEN);\n        return;\n    case 5:\n        if (!gPaletteFade.active)\n        {\n             \n            FillWindowPixelBuffer(0, PIXEL_FILL(0));\n            CopyWindowToVram(0, COPYWIN_GFX);\n            gTasks[taskId].tState = 2;\n        }\n        return;\n    case 10:\n        gTasks[gTasks[taskId].tMainTaskId].tEndCredits = TRUE;\n        DestroyTask(taskId);\n        FreeCreditsBgsAndWindows();\n        FREE_AND_SET_NULL(sCreditsData);\n        return;\n    }",
  },
  "Task_WaitPaletteFade": {
    returnType: "static void",
    params: "u8 taskId",
    lineCount: 2,
    bodyC: "if (!gPaletteFade.active)\n        gTasks[taskId].func = Task_CreditsMain;",
  },
  "VBlankCB_Credits": {
    returnType: "static void",
    params: "void",
    callsTo: ["LoadOam","ProcessSpriteCopyRequests","TransferPlttBuffer"],
    lineCount: 3,
    bodyC: "LoadOam();\n    ProcessSpriteCopyRequests();\n    TransferPlttBuffer();",
  },
} as const;
