// AUTO-GENERATED from src/decompress.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 20

export const ENGINE_FUNCTIONS = {
  "DecompressPicFromTable": {
    returnType: "void",
    params: "const struct CompressedSpriteSheet *src, void *buffer, s32 species",
    callsTo: ["DuplicateDeoxysTiles","LZ77UnCompWram"],
    lineCount: 5,
    bodyC: "if (species > NUM_SPECIES)\n        LZ77UnCompWram(gMonFrontPicTable[0].data, buffer);\n    else\n        LZ77UnCompWram(src->data, buffer);\n    DuplicateDeoxysTiles(buffer, species);",
  },
  "DecompressPicFromTable_2": {
    returnType: "void",
    params: "const struct CompressedSpriteSheet *src, void *buffer, s32 species",
    callsTo: ["DuplicateDeoxysTiles","LZ77UnCompWram"],
    lineCount: 5,
    bodyC: "if (species > NUM_SPECIES)\n        LZ77UnCompWram(gMonFrontPicTable[0].data, buffer);\n    else\n        LZ77UnCompWram(src->data, buffer);\n    DuplicateDeoxysTiles(buffer, species);",
  },
  "DecompressPicFromTable_DontHandleDeoxys": {
    returnType: "void",
    params: "const struct CompressedSpriteSheet *src, void *buffer, s32 species",
    callsTo: ["LZ77UnCompWram"],
    lineCount: 4,
    bodyC: "if (species > NUM_SPECIES)\n        LZ77UnCompWram(gMonFrontPicTable[0].data, buffer);\n    else\n        LZ77UnCompWram(src->data, buffer);",
  },
  "DuplicateDeoxysTiles": {
    returnType: "static void",
    params: "void *pointer, s32 species",
    callsTo: ["CpuCopy32"],
    lineCount: 2,
    bodyC: "if (species == SPECIES_DEOXYS)\n        CpuCopy32(pointer + MON_PIC_SIZE, pointer, MON_PIC_SIZE);",
  },
  "GetDecompressedDataSize": {
    returnType: "u32",
    params: "const u32 *ptr",
    lineCount: 2,
    bodyC: "const u8 *ptr8 = (const u8 *)ptr;\n    return (ptr8[3] << 16) | (ptr8[2] << 8) | (ptr8[1]);",
  },
  "HandleLoadSpecialPokePic": {
    returnType: "void",
    params: "const struct CompressedSpriteSheet *src, void *dest, s32 species, u32 personality",
    callsTo: ["LoadSpecialPokePic_2"],
    lineCount: 6,
    bodyC: "bool8 isFrontPic;\n\n    if (src == &gMonFrontPicTable[species])\n        isFrontPic = TRUE;  \n    else\n        isFrontPic = FALSE;  \n\n    LoadSpecialPokePic_2(src, dest, species, personality, isFrontPic);",
  },
  "HandleLoadSpecialPokePic_2": {
    returnType: "void",
    params: "const struct CompressedSpriteSheet *src, void *dest, s32 species, u32 personality",
    callsTo: ["LoadSpecialPokePic_2"],
    lineCount: 6,
    bodyC: "bool8 isFrontPic;\n\n    if (src == &gMonFrontPicTable[species])\n        isFrontPic = TRUE;  \n    else\n        isFrontPic = FALSE;  \n\n    LoadSpecialPokePic_2(src, dest, species, personality, isFrontPic);",
  },
  "HandleLoadSpecialPokePic_DontHandleDeoxys": {
    returnType: "void",
    params: "const struct CompressedSpriteSheet *src, void *dest, s32 species, u32 personality",
    callsTo: ["LoadSpecialPokePic_DontHandleDeoxys"],
    lineCount: 6,
    bodyC: "bool8 isFrontPic;\n\n    if (src == &gMonFrontPicTable[species])\n        isFrontPic = TRUE;  \n    else\n        isFrontPic = FALSE;  \n\n    LoadSpecialPokePic_DontHandleDeoxys(src, dest, species, personality, isFrontPic);",
  },
  "LZDecompressVram": {
    returnType: "void",
    params: "const u32 *src, void *dest",
    callsTo: ["LZ77UnCompVram"],
    lineCount: 1,
    bodyC: "LZ77UnCompVram(src, dest);",
  },
  "LZDecompressWram": {
    returnType: "void",
    params: "const u32 *src, void *dest",
    callsTo: ["LZ77UnCompWram"],
    lineCount: 1,
    bodyC: "LZ77UnCompWram(src, dest);",
  },
  "LoadCompressedSpritePalette": {
    returnType: "void",
    params: "const struct CompressedSpritePalette *src",
    callsTo: ["LZ77UnCompWram","LoadSpritePalette"],
    lineCount: 5,
    bodyC: "struct SpritePalette dest;\n\n    LZ77UnCompWram(src->data, gDecompressionBuffer);\n    dest.data = (void *) gDecompressionBuffer;\n    dest.tag = src->tag;\n    LoadSpritePalette(&dest);",
  },
  "LoadCompressedSpritePaletteOverrideBuffer": {
    returnType: "void",
    params: "const struct CompressedSpritePalette *src, void *buffer",
    callsTo: ["LZ77UnCompWram","LoadSpritePalette"],
    lineCount: 5,
    bodyC: "struct SpritePalette dest;\n\n    LZ77UnCompWram(src->data, buffer);\n    dest.data = buffer;\n    dest.tag = src->tag;\n    LoadSpritePalette(&dest);",
  },
  "LoadCompressedSpritePaletteUsingHeap": {
    returnType: "bool8",
    params: "const struct CompressedSpritePalette *src",
    callsTo: ["AllocZeroed","Free","LZ77UnCompWram","LoadSpritePalette"],
    lineCount: 9,
    bodyC: "struct SpritePalette dest;\n    void *buffer;\n\n    buffer = AllocZeroed(src->data[0] >> 8);\n    LZ77UnCompWram(src->data, buffer);\n    dest.data = buffer;\n    dest.tag = src->tag;\n\n    LoadSpritePalette(&dest);\n    Free(buffer);\n    return FALSE;",
  },
  "LoadCompressedSpriteSheet": {
    returnType: "u16",
    params: "const struct CompressedSpriteSheet *src",
    callsTo: ["LZ77UnCompWram","LoadSpriteSheet"],
    lineCount: 6,
    bodyC: "struct SpriteSheet dest;\n\n    LZ77UnCompWram(src->data, gDecompressionBuffer);\n    dest.data = gDecompressionBuffer;\n    dest.size = src->size;\n    dest.tag = src->tag;\n    return LoadSpriteSheet(&dest);",
  },
  "LoadCompressedSpriteSheetOverrideBuffer": {
    returnType: "void",
    params: "const struct CompressedSpriteSheet *src, void *buffer",
    callsTo: ["LZ77UnCompWram","LoadSpriteSheet"],
    lineCount: 6,
    bodyC: "struct SpriteSheet dest;\n\n    LZ77UnCompWram(src->data, buffer);\n    dest.data = buffer;\n    dest.size = src->size;\n    dest.tag = src->tag;\n    LoadSpriteSheet(&dest);",
  },
  "LoadCompressedSpriteSheetUsingHeap": {
    returnType: "bool8",
    params: "const struct CompressedSpriteSheet *src",
    callsTo: ["AllocZeroed","Free","LZ77UnCompWram","LoadSpriteSheet"],
    lineCount: 10,
    bodyC: "struct SpriteSheet dest;\n    void *buffer;\n\n    buffer = AllocZeroed(src->data[0] >> 8);\n    LZ77UnCompWram(src->data, buffer);\n\n    dest.data = buffer;\n    dest.size = src->size;\n    dest.tag = src->tag;\n\n    LoadSpriteSheet(&dest);\n    Free(buffer);\n    return FALSE;",
  },
  "LoadSpecialPokePic": {
    returnType: "void",
    params: "const struct CompressedSpriteSheet *src, void *dest, s32 species, u32 personality, bool8 isFrontPic",
    callsTo: ["DrawSpindaSpots","DuplicateDeoxysTiles","GET_UNOWN_LETTER","LZ77UnCompWram"],
    lineCount: 22,
    bodyC: "if (species == SPECIES_UNOWN)\n    {\n        u16 i = GET_UNOWN_LETTER(personality);\n\n         \n        if (i == 0)\n            i = SPECIES_UNOWN;\n        else\n            i += SPECIES_UNOWN_B - 1;\n\n        if (!isFrontPic)\n            LZ77UnCompWram(gMonBackPicTable[i].data, dest);\n        else\n            LZ77UnCompWram(gMonFrontPicTable[i].data, dest);\n    }\n    else if (species > NUM_SPECIES)  \n    {\n        LZ77UnCompWram(gMonFrontPicTable[0].data, dest);\n    }\n    else\n    {\n        LZ77UnCompWram(src->data, dest);\n    }\n\n    DuplicateDeoxysTiles(dest, species);\n    DrawSpindaSpots(species, personality, dest, isFrontPic);",
  },
  "LoadSpecialPokePic_2": {
    returnType: "void",
    params: "const struct CompressedSpriteSheet *src, void *dest, s32 species, u32 personality, bool8 isFrontPic",
    callsTo: ["DrawSpindaSpots","DuplicateDeoxysTiles","GET_UNOWN_LETTER","LZ77UnCompWram"],
    lineCount: 22,
    bodyC: "if (species == SPECIES_UNOWN)\n    {\n        u16 i = GET_UNOWN_LETTER(personality);\n\n         \n        if (i == 0)\n            i = SPECIES_UNOWN;\n        else\n            i += SPECIES_UNOWN_B - 1;\n\n        if (!isFrontPic)\n            LZ77UnCompWram(gMonBackPicTable[i].data, dest);\n        else\n            LZ77UnCompWram(gMonFrontPicTable[i].data, dest);\n    }\n    else if (species > NUM_SPECIES)  \n    {\n        LZ77UnCompWram(gMonFrontPicTable[0].data, dest);\n    }\n    else\n    {\n        LZ77UnCompWram(src->data, dest);\n    }\n\n    DuplicateDeoxysTiles(dest, species);\n    DrawSpindaSpots(species, personality, dest, isFrontPic);",
  },
  "LoadSpecialPokePic_DontHandleDeoxys": {
    returnType: "void",
    params: "const struct CompressedSpriteSheet *src, void *dest, s32 species, u32 personality, bool8 isFrontPic",
    callsTo: ["DrawSpindaSpots","GET_UNOWN_LETTER","LZ77UnCompWram"],
    lineCount: 21,
    bodyC: "if (species == SPECIES_UNOWN)\n    {\n        u16 i = GET_UNOWN_LETTER(personality);\n\n         \n        if (i == 0)\n            i = SPECIES_UNOWN;\n        else\n            i += SPECIES_UNOWN_B - 1;\n\n        if (!isFrontPic)\n            LZ77UnCompWram(gMonBackPicTable[i].data, dest);\n        else\n            LZ77UnCompWram(gMonFrontPicTable[i].data, dest);\n    }\n    else if (species > NUM_SPECIES)  \n    {\n        LZ77UnCompWram(gMonFrontPicTable[0].data, dest);\n    }\n    else\n    {\n        LZ77UnCompWram(src->data, dest);\n    }\n\n    DrawSpindaSpots(species, personality, dest, isFrontPic);",
  },
  "Unused_LZDecompressWramIndirect": {
    returnType: "void",
    params: "const void **src, void *dest",
    callsTo: ["LZ77UnCompWram"],
    lineCount: 1,
    bodyC: "LZ77UnCompWram(*src, dest);",
  },
} as const;
