// AUTO-GENERATED from src/field_player_avatar.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 166

export const ENGINE_FUNCTIONS = {
  "AlignFishingAnimationFrames": {
    returnType: "static void",
    params: "void",
    callsTo: ["AnimateSprite","GetPlayerFacingDirection","SetSurfBlob_PlayerOffset"],
    lineCount: 30,
    bodyC: "struct Sprite *playerSprite = &gSprites[gPlayerAvatar.spriteId];\n    u8 animCmdIndex;\n    u8 animType;\n\n    AnimateSprite(playerSprite);\n    playerSprite->x2 = 0;\n    playerSprite->y2 = 0;\n    animCmdIndex = playerSprite->animCmdIndex;\n    if (playerSprite->anims[playerSprite->animNum][animCmdIndex].type == -1)\n    {\n        animCmdIndex--;\n    }\n    else\n    {\n        playerSprite->animDelayCounter++;\n        if (playerSprite->anims[playerSprite->animNum][animCmdIndex].type == -1)\n            animCmdIndex--;\n    }\n    animType = playerSprite->anims[playerSprite->animNum][animCmdIndex].type;\n    if (animType == 1 || animType == 2 || animType == 3)\n    {\n        playerSprite->x2 = 8;\n        if (GetPlayerFacingDirection() == 3)\n            playerSprite->x2 = -8;\n    }\n    if (animType == 5)\n        playerSprite->y2 = -8;\n    if (animType == 10 || animType == 11)\n        playerSprite->y2 = 8;\n    if (gPlayerAvatar.flags & PLAYER_AVATAR_FLAG_SURFING)\n        SetSurfBlob_PlayerOffset(gObjectEvents[gPlayerAvatar.objectEventId].fieldEffectSpriteId, TRUE, playerSprite->y2);",
  },
  "CanStopSurfing": {
    returnType: "static bool8",
    params: "s16 x, s16 y, u8 direction",
    callsTo: ["CreateStopSurfingTask","GetObjectEventIdByPosition","MapGridGetElevationAt"],
    lineCount: 11,
    bodyC: "if ((gPlayerAvatar.flags & PLAYER_AVATAR_FLAG_SURFING)\n     && MapGridGetElevationAt(x, y) == ELEVATION_DEFAULT\n     && GetObjectEventIdByPosition(x, y, ELEVATION_DEFAULT) == OBJECT_EVENTS_COUNT)\n    {\n        CreateStopSurfingTask(direction);\n        return TRUE;\n    }\n    else\n    {\n        return FALSE;\n    }",
  },
  "CancelPlayerForcedMovement": {
    returnType: "void",
    params: "void",
    callsTo: ["ForcedMovement_None"],
    lineCount: 1,
    bodyC: "ForcedMovement_None();",
  },
  "CheckAcroBikeCollision": {
    returnType: "static void",
    params: "s16 x, s16 y, u8 metatileBehavior, u8 *collision",
    lineCount: 9,
    bodyC: "u8 i;\n\n    for (i = 0; i < NUM_ACRO_BIKE_COLLISIONS; i++)\n    {\n        if (sAcroBikeTrickMetatiles[i](metatileBehavior))\n        {\n            *collision = sAcroBikeTrickCollisionTypes[i];\n            return;\n        }\n    }",
  },
  "CheckForObjectEventCollision": {
    returnType: "u8",
    params: "struct ObjectEvent *objectEvent, s16 x, s16 y, u8 direction, u8 metatileBehavior",
    callsTo: ["CanStopSurfing","CheckAcroBikeCollision","CheckForRotatingGatePuzzleCollision","GetCollisionAtCoords","IncrementGameStat","ShouldJumpLedge","TryPushBoulder"],
    lineCount: 17,
    bodyC: "u8 collision = GetCollisionAtCoords(objectEvent, x, y, direction);\n    if (collision == COLLISION_ELEVATION_MISMATCH && CanStopSurfing(x, y, direction))\n        return COLLISION_STOP_SURFING;\n\n    if (ShouldJumpLedge(x, y, direction))\n    {\n        IncrementGameStat(GAME_STAT_JUMPED_DOWN_LEDGES);\n        return COLLISION_LEDGE_JUMP;\n    }\n    if (collision == COLLISION_OBJECT_EVENT && TryPushBoulder(x, y, direction))\n        return COLLISION_PUSHED_BOULDER;\n\n    if (collision == COLLISION_NONE)\n    {\n        if (CheckForRotatingGatePuzzleCollision(direction, x, y))\n            return COLLISION_ROTATING_GATE;\n        CheckAcroBikeCollision(x, y, metatileBehavior, &collision);\n    }\n    return collision;",
  },
  "CheckForObjectEventStaticCollision": {
    returnType: "static u8",
    params: "struct ObjectEvent *objectEvent, s16 x, s16 y, u8 direction, u8 metatileBehavior",
    callsTo: ["CheckAcroBikeCollision","CheckForRotatingGatePuzzleCollisionWithoutAnimation","GetCollisionAtCoords"],
    lineCount: 8,
    bodyC: "u8 collision = GetCollisionAtCoords(objectEvent, x, y, direction);\n\n    if (collision == COLLISION_NONE)\n    {\n        if (CheckForRotatingGatePuzzleCollisionWithoutAnimation(direction, x, y))\n            return COLLISION_ROTATING_GATE;\n        CheckAcroBikeCollision(x, y, metatileBehavior, &collision);\n    }\n    return collision;",
  },
  "CheckForPlayerAvatarCollision": {
    returnType: "static u8",
    params: "u8 direction",
    callsTo: ["CheckForObjectEventCollision","MapGridGetMetatileBehaviorAt","MoveCoords"],
    lineCount: 6,
    bodyC: "s16 x, y;\n    struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n    x = playerObjEvent->currentCoords.x;\n    y = playerObjEvent->currentCoords.y;\n    MoveCoords(direction, &x, &y);\n    return CheckForObjectEventCollision(playerObjEvent, x, y, direction, MapGridGetMetatileBehaviorAt(x, y));",
  },
  "CheckForPlayerAvatarStaticCollision": {
    returnType: "static u8",
    params: "u8 direction",
    callsTo: ["CheckForObjectEventStaticCollision","MapGridGetMetatileBehaviorAt","MoveCoords"],
    lineCount: 6,
    bodyC: "s16 x, y;\n    struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n    x = playerObjEvent->currentCoords.x;\n    y = playerObjEvent->currentCoords.y;\n    MoveCoords(direction, &x, &y);\n    return CheckForObjectEventStaticCollision(playerObjEvent, x, y, direction, MapGridGetMetatileBehaviorAt(x, y));",
  },
  "CheckMovementInputNotOnBike": {
    returnType: "static u8",
    params: "u8 direction",
    callsTo: ["GetPlayerMovementDirection"],
    lineCount: 6,
    bodyC: "if (direction == DIR_NONE)\n        return gPlayerAvatar.runningState = NOT_MOVING;\n    else if (direction != GetPlayerMovementDirection() && gPlayerAvatar.runningState != MOVING)\n        return gPlayerAvatar.runningState = TURN_DIRECTION;\n    else\n        return gPlayerAvatar.runningState = MOVING;",
  },
  "ClearPlayerAvatarInfo": {
    returnType: "void",
    params: "void",
    callsTo: ["memset"],
    lineCount: 1,
    bodyC: "memset(&gPlayerAvatar, 0, sizeof(struct PlayerAvatar));",
  },
  "CreateStopSurfingTask": {
    returnType: "static void",
    params: "u8 direction",
    callsTo: ["CreateTask","LockPlayerFieldControls","Overworld_ChangeMusicToDefault","Overworld_ClearSavedMusic","Task_StopSurfingInit"],
    lineCount: 10,
    bodyC: "u8 taskId;\n\n    LockPlayerFieldControls();\n    Overworld_ClearSavedMusic();\n    Overworld_ChangeMusicToDefault();\n    gPlayerAvatar.flags &= ~PLAYER_AVATAR_FLAG_SURFING;\n    gPlayerAvatar.flags |= PLAYER_AVATAR_FLAG_ON_FOOT;\n    gPlayerAvatar.preventStep = TRUE;\n    taskId = CreateTask(Task_StopSurfingInit, 0xFF);\n    gTasks[taskId].data[0] = direction;\n    Task_StopSurfingInit(taskId);",
  },
  "DoForcedMovement": {
    returnType: "static bool8",
    params: "u8 direction, void (*moveFunc)(u8)",
    callsTo: ["CheckForPlayerAvatarCollision","ForcedMovement_None","PlayerJumpLedge","moveFunc"],
    lineCount: 25,
    bodyC: "struct PlayerAvatar *playerAvatar = &gPlayerAvatar;\n    u8 collision = CheckForPlayerAvatarCollision(direction);\n\n    playerAvatar->flags |= PLAYER_AVATAR_FLAG_FORCED_MOVE;\n    if (collision)\n    {\n        ForcedMovement_None();\n        if (collision < COLLISION_STOP_SURFING)\n        {\n            return FALSE;\n        }\n        else\n        {\n            if (collision == COLLISION_LEDGE_JUMP)\n                PlayerJumpLedge(direction);\n            playerAvatar->flags |= PLAYER_AVATAR_FLAG_FORCED_MOVE;\n            playerAvatar->runningState = MOVING;\n            return TRUE;\n        }\n    }\n    else\n    {\n        playerAvatar->runningState = MOVING;\n        moveFunc(direction);\n        return TRUE;\n    }",
  },
  "DoForcedMovementInCurrentDirection": {
    returnType: "static bool8",
    params: "void (*moveFunc)(u8)",
    callsTo: ["DoForcedMovement"],
    lineCount: 3,
    bodyC: "struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n    playerObjEvent->disableAnim = TRUE;\n    return DoForcedMovement(playerObjEvent->movementDirection, moveFunc);",
  },
  "DoPlayerAvatarSecretBaseMatJump": {
    returnType: "static void",
    params: "u8 taskId",
    lineCount: 2,
    bodyC: "while (sPlayerAvatarSecretBaseMatJump[gTasks[taskId].data[0]](&gTasks[taskId], &gObjectEvents[gPlayerAvatar.objectEventId]))\n        ;",
  },
  "DoPlayerAvatarTransition": {
    returnType: "static void",
    params: "void",
    callsTo: ["ARRAY_COUNT"],
    lineCount: 11,
    bodyC: "u8 i;\n    u8 flags = gPlayerAvatar.transitionFlags;\n\n    if (flags != 0)\n    {\n        for (i = 0; i < ARRAY_COUNT(sPlayerAvatarTransitionFuncs); i++, flags >>= 1)\n        {\n            if (flags & 1)\n                sPlayerAvatarTransitionFuncs[i](&gObjectEvents[gPlayerAvatar.objectEventId]);\n        }\n        gPlayerAvatar.transitionFlags = 0;\n    }",
  },
  "DoPlayerMatJump": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateTask","DoPlayerAvatarSecretBaseMatJump"],
    lineCount: 1,
    bodyC: "DoPlayerAvatarSecretBaseMatJump(CreateTask(DoPlayerAvatarSecretBaseMatJump, 0xFF));",
  },
  "DoPlayerMatSpin": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateTask","PlayerAvatar_DoSecretBaseMatSpin"],
    lineCount: 2,
    bodyC: "u8 taskId = CreateTask(PlayerAvatar_DoSecretBaseMatSpin, 0xFF);\n\n    PlayerAvatar_DoSecretBaseMatSpin(taskId);",
  },
  "DoPlayerSpinEntrance": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateTask","Task_DoPlayerSpinEntrance"],
    lineCount: 1,
    bodyC: "Task_DoPlayerSpinEntrance(CreateTask(Task_DoPlayerSpinEntrance, 0));",
  },
  "DoPlayerSpinExit": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateTask","Task_DoPlayerSpinExit"],
    lineCount: 1,
    bodyC: "Task_DoPlayerSpinExit(CreateTask(Task_DoPlayerSpinExit, 0));",
  },
  "Fishing_CheckForBite": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AlignFishingAnimationFrames","DoesCurrentMapHaveFishingMons","GetFishingBiteDirectionAnimNum","GetMonAbility","GetMonData","GetPlayerFacingDirection","Random","StartSpriteAnim"],
    lineCount: 30,
    bodyC: "bool8 bite;\n\n    AlignFishingAnimationFrames();\n    task->tStep++;\n    bite = FALSE;\n\n    if (!DoesCurrentMapHaveFishingMons())\n    {\n        task->tStep = FISHING_NO_BITE;\n    }\n    else\n    {\n        if (!GetMonData(&gPlayerParty[0], MON_DATA_SANITY_IS_EGG))\n        {\n            u8 ability = GetMonAbility(&gPlayerParty[0]);\n            if (ability == ABILITY_SUCTION_CUPS || ability  == ABILITY_STICKY_HOLD)\n            {\n                if (Random() % 100 > 14)\n                    bite = TRUE;\n            }\n        }\n\n        if (!bite)\n        {\n            if (Random() & 1)\n                task->tStep = FISHING_NO_BITE;\n            else\n                bite = TRUE;\n        }\n\n        if (bite == TRUE)\n            StartSpriteAnim(&gSprites[gPlayerAvatar.spriteId], GetFishingBiteDirectionAnimNum(GetPlayerFacingDirection()));\n    }\n    return TRUE;",
  },
  "Fishing_CheckMoreDots": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AlignFishingAnimationFrames","Random"],
    lineCount: 19,
    bodyC: "const s16 moreDotsChance[][2] =\n    {\n        [OLD_ROD]   = {0, 0},\n        [GOOD_ROD]  = {40, 10},\n        [SUPER_ROD] = {70, 30}\n    };\n\n    AlignFishingAnimationFrames();\n    task->tStep++;\n    if (task->tRoundsPlayed < task->tMinRoundsRequired)\n    {\n        task->tStep = FISHING_START_ROUND;\n    }\n    else if (task->tRoundsPlayed < 2)\n    {\n         \n        s16 probability = Random() % 100;\n\n        if (moreDotsChance[task->tFishingRod][task->tRoundsPlayed] > probability)\n            task->tStep = FISHING_START_ROUND;\n    }\n    return FALSE;",
  },
  "Fishing_EndNoMon": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["ClearDialogWindowAndFrame","DestroyTask","FindTaskIdByFunc","IsTextPrinterActive","RecordFishingAttemptForTV","RunTextPrinters","UnfreezeObjectEvents","UnlockPlayerFieldControls"],
    lineCount: 11,
    bodyC: "RunTextPrinters();\n    if (!IsTextPrinterActive(0))\n    {\n        gPlayerAvatar.preventStep = FALSE;\n        UnlockPlayerFieldControls();\n        UnfreezeObjectEvents();\n        ClearDialogWindowAndFrame(0, TRUE);\n        RecordFishingAttemptForTV(FALSE);\n        DestroyTask(FindTaskIdByFunc(Task_Fishing));\n    }\n    return FALSE;",
  },
  "Fishing_GetRodOut": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["ObjectEventClearHeldMovementIfActive","Random","SetPlayerAvatarFishing"],
    lineCount: 20,
    bodyC: "struct ObjectEvent *playerObjEvent;\n    const s16 minRounds1[] = {\n        [OLD_ROD]   = 1,\n        [GOOD_ROD]  = 1,\n        [SUPER_ROD] = 1\n    };\n    const s16 minRounds2[] = {\n        [OLD_ROD]   = 1,\n        [GOOD_ROD]  = 3,\n        [SUPER_ROD] = 6\n    };\n\n    task->tRoundsPlayed = 0;\n    task->tMinRoundsRequired = minRounds1[task->tFishingRod] + (Random() % minRounds2[task->tFishingRod]);\n    task->tPlayerGfxId = gObjectEvents[gPlayerAvatar.objectEventId].graphicsId;\n    playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n    ObjectEventClearHeldMovementIfActive(playerObjEvent);\n    playerObjEvent->enableAnim = TRUE;\n    SetPlayerAvatarFishing(playerObjEvent->facingDirection);\n    task->tStep++;\n    return FALSE;",
  },
  "Fishing_GotAway": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AddTextPrinterParameterized2","AlignFishingAnimationFrames","FillWindowPixelBuffer","GetFishingNoCatchDirectionAnimNum","GetPlayerFacingDirection","PIXEL_FILL","StartSpriteAnim"],
    lineCount: 6,
    bodyC: "AlignFishingAnimationFrames();\n    StartSpriteAnim(&gSprites[gPlayerAvatar.spriteId], GetFishingNoCatchDirectionAnimNum(GetPlayerFacingDirection()));\n    FillWindowPixelBuffer(0, PIXEL_FILL(1));\n    AddTextPrinterParameterized2(0, FONT_NORMAL, gText_ItGotAway, 1, 0, TEXT_COLOR_DARK_GRAY, TEXT_COLOR_WHITE, TEXT_COLOR_LIGHT_GRAY);\n    task->tStep++;\n    return TRUE;",
  },
  "Fishing_GotBite": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AddTextPrinterParameterized","AlignFishingAnimationFrames"],
    lineCount: 5,
    bodyC: "AlignFishingAnimationFrames();\n    AddTextPrinterParameterized(0, FONT_NORMAL, gText_OhABite, 0, 17, 0, NULL);\n    task->tStep++;\n    task->tFrameCounter = 0;\n    return FALSE;",
  },
  "Fishing_Init": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["LockPlayerFieldControls"],
    lineCount: 4,
    bodyC: "LockPlayerFieldControls();\n    gPlayerAvatar.preventStep = TRUE;\n    task->tStep++;\n    return FALSE;",
  },
  "Fishing_InitDots": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["LoadMessageBoxAndFrameGfx","Random"],
    lineCount: 13,
    bodyC: "u32 randVal;\n\n    LoadMessageBoxAndFrameGfx(0, TRUE);\n    task->tStep++;\n    task->tFrameCounter = 0;\n    task->tNumDots = 0;\n    randVal = Random();\n    randVal %= 10;\n    task->tDotsRequired = randVal + 1;\n    if (task->tRoundsPlayed == 0)\n        task->tDotsRequired = randVal + 4;\n    if (task->tDotsRequired >= 10)\n        task->tDotsRequired = 10;\n    return TRUE;",
  },
  "Fishing_MonOnHook": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AddTextPrinterParameterized2","AlignFishingAnimationFrames","FillWindowPixelBuffer","PIXEL_FILL"],
    lineCount: 6,
    bodyC: "AlignFishingAnimationFrames();\n    FillWindowPixelBuffer(0, PIXEL_FILL(1));\n    AddTextPrinterParameterized2(0, FONT_NORMAL, gText_PokemonOnHook, 1, 0, TEXT_COLOR_DARK_GRAY, TEXT_COLOR_WHITE, TEXT_COLOR_LIGHT_GRAY);\n    task->tStep++;\n    task->tFrameCounter = 0;\n    return FALSE;",
  },
  "Fishing_NoMon": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AlignFishingAnimationFrames"],
    lineCount: 3,
    bodyC: "AlignFishingAnimationFrames();\n    task->tStep++;\n    return FALSE;",
  },
  "Fishing_NotEvenNibble": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AddTextPrinterParameterized2","AlignFishingAnimationFrames","FillWindowPixelBuffer","GetFishingNoCatchDirectionAnimNum","GetPlayerFacingDirection","PIXEL_FILL","StartSpriteAnim"],
    lineCount: 6,
    bodyC: "AlignFishingAnimationFrames();\n    StartSpriteAnim(&gSprites[gPlayerAvatar.spriteId], GetFishingNoCatchDirectionAnimNum(GetPlayerFacingDirection()));\n    FillWindowPixelBuffer(0, PIXEL_FILL(1));\n    AddTextPrinterParameterized2(0, FONT_NORMAL, gText_NotEvenANibble, 1, 0, TEXT_COLOR_DARK_GRAY, TEXT_COLOR_WHITE, TEXT_COLOR_LIGHT_GRAY);\n    task->tStep = FISHING_SHOW_RESULT;\n    return TRUE;",
  },
  "Fishing_PutRodAway": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AlignFishingAnimationFrames","ObjectEventSetGraphicsId","ObjectEventTurn","SetSurfBlob_PlayerOffset"],
    lineCount: 13,
    bodyC: "AlignFishingAnimationFrames();\n    if (gSprites[gPlayerAvatar.spriteId].animEnded)\n    {\n        struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n        ObjectEventSetGraphicsId(playerObjEvent, task->tPlayerGfxId);\n        ObjectEventTurn(playerObjEvent, playerObjEvent->movementDirection);\n        if (gPlayerAvatar.flags & PLAYER_AVATAR_FLAG_SURFING)\n            SetSurfBlob_PlayerOffset(gObjectEvents[gPlayerAvatar.objectEventId].fieldEffectSpriteId, FALSE, 0);\n        gSprites[gPlayerAvatar.spriteId].x2 = 0;\n        gSprites[gPlayerAvatar.spriteId].y2 = 0;\n        task->tStep++;\n    }\n    return FALSE;",
  },
  "Fishing_ShowDots": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AddTextPrinterParameterized","AlignFishingAnimationFrames","JOY_NEW","_"],
    lineCount: 30,
    bodyC: "const u8 dot[] = _(\"·\");\n\n    AlignFishingAnimationFrames();\n    task->tFrameCounter++;\n    if (JOY_NEW(A_BUTTON))\n    {\n        task->tStep = FISHING_NO_BITE;\n        if (task->tRoundsPlayed != 0)\n            task->tStep = FISHING_GOT_AWAY;\n        return TRUE;\n    }\n    else\n    {\n        if (task->tFrameCounter >= 20)\n        {\n            task->tFrameCounter = 0;\n            if (task->tNumDots >= task->tDotsRequired)\n            {\n                task->tStep++;\n                if (task->tRoundsPlayed != 0)\n                    task->tStep++;\n                task->tRoundsPlayed++;\n            }\n            else\n            {\n                AddTextPrinterParameterized(0, FONT_NORMAL, dot, task->tNumDots * 8, 1, 0, NULL);\n                task->tNumDots++;\n            }\n        }\n        return FALSE;\n    }",
  },
  "Fishing_StartEncounter": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AlignFishingAnimationFrames","ClearDialogWindowAndFrame","DestroyTask","FindTaskIdByFunc","FishingWildEncounter","IsTextPrinterActive","ObjectEventSetGraphicsId","ObjectEventTurn","RecordFishingAttemptForTV","RunTextPrinters","SetSurfBlob_PlayerOffset","UnlockPlayerFieldControls"],
    lineCount: 28,
    bodyC: "if (task->tFrameCounter == 0)\n        AlignFishingAnimationFrames();\n\n    RunTextPrinters();\n\n    if (task->tFrameCounter == 0)\n    {\n        if (!IsTextPrinterActive(0))\n        {\n            struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n            ObjectEventSetGraphicsId(playerObjEvent, task->tPlayerGfxId);\n            ObjectEventTurn(playerObjEvent, playerObjEvent->movementDirection);\n            if (gPlayerAvatar.flags & PLAYER_AVATAR_FLAG_SURFING)\n                SetSurfBlob_PlayerOffset(gObjectEvents[gPlayerAvatar.objectEventId].fieldEffectSpriteId, FALSE, 0);\n            gSprites[gPlayerAvatar.spriteId].x2 = 0;\n            gSprites[gPlayerAvatar.spriteId].y2 = 0;\n            ClearDialogWindowAndFrame(0, TRUE);\n            task->tFrameCounter++;\n            return FALSE;\n        }\n    }\n\n    if (task->tFrameCounter != 0)\n    {\n        gPlayerAvatar.preventStep = FALSE;\n        UnlockPlayerFieldControls();\n        FishingWildEncounter(task->tFishingRod);\n        RecordFishingAttemptForTV(TRUE);\n        DestroyTask(FindTaskIdByFunc(Task_Fishing));\n    }\n    return FALSE;",
  },
  "Fishing_WaitBeforeDots": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AlignFishingAnimationFrames"],
    lineCount: 5,
    bodyC: "AlignFishingAnimationFrames();\n\n     \n    task->tFrameCounter++;\n    if (task->tFrameCounter >= 60)\n        task->tStep++;\n    return FALSE;",
  },
  "Fishing_WaitForA": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["AlignFishingAnimationFrames","JOY_NEW"],
    lineCount: 12,
    bodyC: "const s16 reelTimeouts[3] = {\n        [OLD_ROD]   = 36,\n        [GOOD_ROD]  = 33,\n        [SUPER_ROD] = 30\n    };\n\n    AlignFishingAnimationFrames();\n    task->tFrameCounter++;\n    if (task->tFrameCounter >= reelTimeouts[task->tFishingRod])\n        task->tStep = FISHING_GOT_AWAY;\n    else if (JOY_NEW(A_BUTTON))\n        task->tStep++;\n    return FALSE;",
  },
  "ForcedMovement_MatJump": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DoPlayerMatJump"],
    lineCount: 2,
    bodyC: "DoPlayerMatJump();\n    return TRUE;",
  },
  "ForcedMovement_MatSpin": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DoPlayerMatSpin"],
    lineCount: 2,
    bodyC: "DoPlayerMatSpin();\n    return TRUE;",
  },
  "ForcedMovement_MuddySlope": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["Bike_UpdateBikeCounterSpeed","DoForcedMovement","GetPlayerSpeed"],
    lineCount: 11,
    bodyC: "struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n    if (playerObjEvent->movementDirection != DIR_NORTH || GetPlayerSpeed() < PLAYER_SPEED_FASTEST)\n    {\n        Bike_UpdateBikeCounterSpeed(0);\n        playerObjEvent->facingDirectionLocked = TRUE;\n        return DoForcedMovement(DIR_SOUTH, PlayerWalkFast);\n    }\n    else\n    {\n        return FALSE;\n    }",
  },
  "ForcedMovement_None": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["SetObjectEventDirection"],
    lineCount: 9,
    bodyC: "if (gPlayerAvatar.flags & PLAYER_AVATAR_FLAG_FORCED_MOVE)\n    {\n        struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n        playerObjEvent->facingDirectionLocked = FALSE;\n        playerObjEvent->enableAnim = TRUE;\n        SetObjectEventDirection(playerObjEvent, playerObjEvent->facingDirection);\n        gPlayerAvatar.flags &= ~PLAYER_AVATAR_FLAG_FORCED_MOVE;\n    }\n    return FALSE;",
  },
  "ForcedMovement_PushedEastByCurrent": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DoForcedMovement"],
    lineCount: 1,
    bodyC: "return DoForcedMovement(DIR_EAST, PlayerRideWaterCurrent);",
  },
  "ForcedMovement_PushedNorthByCurrent": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DoForcedMovement"],
    lineCount: 1,
    bodyC: "return DoForcedMovement(DIR_NORTH, PlayerRideWaterCurrent);",
  },
  "ForcedMovement_PushedSouthByCurrent": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DoForcedMovement"],
    lineCount: 1,
    bodyC: "return DoForcedMovement(DIR_SOUTH, PlayerRideWaterCurrent);",
  },
  "ForcedMovement_PushedWestByCurrent": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DoForcedMovement"],
    lineCount: 1,
    bodyC: "return DoForcedMovement(DIR_WEST, PlayerRideWaterCurrent);",
  },
  "ForcedMovement_Slide": {
    returnType: "static bool8",
    params: "u8 direction, void (*moveFunc)(u8)",
    callsTo: ["DoForcedMovement"],
    lineCount: 4,
    bodyC: "struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n    playerObjEvent->disableAnim = TRUE;\n    playerObjEvent->facingDirectionLocked = TRUE;\n    return DoForcedMovement(direction, moveFunc);",
  },
  "ForcedMovement_SlideEast": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["ForcedMovement_Slide"],
    lineCount: 1,
    bodyC: "return ForcedMovement_Slide(DIR_EAST, PlayerWalkFast);",
  },
  "ForcedMovement_SlideNorth": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["ForcedMovement_Slide"],
    lineCount: 1,
    bodyC: "return ForcedMovement_Slide(DIR_NORTH, PlayerWalkFast);",
  },
  "ForcedMovement_SlideSouth": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["ForcedMovement_Slide"],
    lineCount: 1,
    bodyC: "return ForcedMovement_Slide(DIR_SOUTH, PlayerWalkFast);",
  },
  "ForcedMovement_SlideWest": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["ForcedMovement_Slide"],
    lineCount: 1,
    bodyC: "return ForcedMovement_Slide(DIR_WEST, PlayerWalkFast);",
  },
  "ForcedMovement_Slip": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DoForcedMovementInCurrentDirection"],
    lineCount: 1,
    bodyC: "return DoForcedMovementInCurrentDirection(PlayerWalkFast);",
  },
  "ForcedMovement_WalkEast": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DoForcedMovement"],
    lineCount: 1,
    bodyC: "return DoForcedMovement(DIR_EAST, PlayerWalkNormal);",
  },
  "ForcedMovement_WalkNorth": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DoForcedMovement"],
    lineCount: 1,
    bodyC: "return DoForcedMovement(DIR_NORTH, PlayerWalkNormal);",
  },
  "ForcedMovement_WalkSouth": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DoForcedMovement"],
    lineCount: 1,
    bodyC: "return DoForcedMovement(DIR_SOUTH, PlayerWalkNormal);",
  },
  "ForcedMovement_WalkWest": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DoForcedMovement"],
    lineCount: 1,
    bodyC: "return DoForcedMovement(DIR_WEST, PlayerWalkNormal);",
  },
  "GetFRLGAvatarGraphicsIdByGender": {
    returnType: "u8",
    params: "u8 gender",
    lineCount: 1,
    bodyC: "return sFRLGAvatarGfxIds[gender];",
  },
  "GetForcedMovementByMetatileBehavior": {
    returnType: "static u8",
    params: "void",
    lineCount: 11,
    bodyC: "u8 i;\n\n    if (!(gPlayerAvatar.flags & PLAYER_AVATAR_FLAG_CONTROLLABLE))\n    {\n        u8 metatileBehavior = gObjectEvents[gPlayerAvatar.objectEventId].currentMetatileBehavior;\n\n        for (i = 0; i < NUM_FORCED_MOVEMENTS; i++)\n        {\n            if (sForcedMovementTestFuncs[i](metatileBehavior))\n                return i + 1;\n        }\n    }\n    return 0;",
  },
  "GetPlayerAvatarFlags": {
    returnType: "u8",
    params: "void",
    lineCount: 1,
    bodyC: "return gPlayerAvatar.flags;",
  },
  "GetPlayerAvatarGenderByGraphicsId": {
    returnType: "u8",
    params: "u8 gfxId",
    lineCount: 14,
    bodyC: "switch (gfxId)\n    {\n    case OBJ_EVENT_GFX_MAY_NORMAL:\n    case OBJ_EVENT_GFX_MAY_MACH_BIKE:\n    case OBJ_EVENT_GFX_MAY_ACRO_BIKE:\n    case OBJ_EVENT_GFX_MAY_SURFING:\n    case OBJ_EVENT_GFX_MAY_FIELD_MOVE:\n    case OBJ_EVENT_GFX_MAY_UNDERWATER:\n    case OBJ_EVENT_GFX_MAY_FISHING:\n    case OBJ_EVENT_GFX_MAY_WATERING:\n        return FEMALE;\n    default:\n        return MALE;\n    }",
  },
  "GetPlayerAvatarGraphicsIdByCurrentState": {
    returnType: "u8",
    params: "void",
    callsTo: ["ARRAY_COUNT"],
    lineCount: 8,
    bodyC: "u8 i;\n    u8 flags = gPlayerAvatar.flags;\n\n    for (i = 0; i < ARRAY_COUNT(sPlayerAvatarGfxToStateFlag[0]); i++)\n    {\n        if (sPlayerAvatarGfxToStateFlag[gPlayerAvatar.gender][i].playerFlag & flags)\n            return sPlayerAvatarGfxToStateFlag[gPlayerAvatar.gender][i].graphicsId;\n    }\n    return 0;",
  },
  "GetPlayerAvatarGraphicsIdByStateId": {
    returnType: "u8",
    params: "u8 state",
    callsTo: ["GetPlayerAvatarGraphicsIdByStateIdAndGender"],
    lineCount: 1,
    bodyC: "return GetPlayerAvatarGraphicsIdByStateIdAndGender(state, gPlayerAvatar.gender);",
  },
  "GetPlayerAvatarGraphicsIdByStateIdAndGender": {
    returnType: "u8",
    params: "u8 state, u8 gender",
    lineCount: 1,
    bodyC: "return sPlayerAvatarGfxIds[state][gender];",
  },
  "GetPlayerAvatarSpriteId": {
    returnType: "u8",
    params: "void",
    lineCount: 1,
    bodyC: "return gPlayerAvatar.spriteId;",
  },
  "GetPlayerAvatarStateTransitionByGraphicsId": {
    returnType: "static u8",
    params: "u8 graphicsId, u8 gender",
    callsTo: ["ARRAY_COUNT"],
    lineCount: 7,
    bodyC: "u8 i;\n\n    for (i = 0; i < ARRAY_COUNT(sPlayerAvatarGfxToStateFlag[0]); i++)\n    {\n        if (sPlayerAvatarGfxToStateFlag[gender][i].graphicsId == graphicsId)\n            return sPlayerAvatarGfxToStateFlag[gender][i].playerFlag;\n    }\n    return PLAYER_AVATAR_FLAG_ON_FOOT;",
  },
  "GetPlayerFacingDirection": {
    returnType: "u8",
    params: "void",
    lineCount: 1,
    bodyC: "return gObjectEvents[gPlayerAvatar.objectEventId].facingDirection;",
  },
  "GetPlayerMovementDirection": {
    returnType: "u8",
    params: "void",
    lineCount: 1,
    bodyC: "return gObjectEvents[gPlayerAvatar.objectEventId].movementDirection;",
  },
  "GetRSAvatarGraphicsIdByGender": {
    returnType: "u8",
    params: "u8 gender",
    lineCount: 1,
    bodyC: "return sRSAvatarGfxIds[gender];",
  },
  "GetRivalAvatarGraphicsIdByStateIdAndGender": {
    returnType: "u8",
    params: "u8 state, u8 gender",
    lineCount: 1,
    bodyC: "return sRivalAvatarGfxIds[state][gender];",
  },
  "GetSpinStartFacingDir": {
    returnType: "static u8",
    params: "void",
    lineCount: 3,
    bodyC: "if (sSpinStartFacingDir == DIR_NONE)\n        return DIR_SOUTH;\n\n    return sSpinStartFacingDir;",
  },
  "GetXYCoordsOneStepInFrontOfPlayer": {
    returnType: "void",
    params: "s16 *x, s16 *y",
    callsTo: ["GetPlayerFacingDirection","MoveCoords"],
    lineCount: 3,
    bodyC: "*x = gObjectEvents[gPlayerAvatar.objectEventId].currentCoords.x;\n    *y = gObjectEvents[gPlayerAvatar.objectEventId].currentCoords.y;\n    MoveCoords(GetPlayerFacingDirection(), x, y);",
  },
  "HideShowWarpArrow": {
    returnType: "static void",
    params: "struct ObjectEvent *objectEvent",
    callsTo: ["MoveCoords","SetSpriteInvisible","ShowWarpArrowSprite"],
    lineCount: 16,
    bodyC: "s16 x;\n    s16 y;\n    u8 direction;\n    u8 metatileBehavior = objectEvent->currentMetatileBehavior;\n\n    for (x = 0, direction = DIR_SOUTH; x < 4; x++, direction++)\n    {\n        if (sArrowWarpMetatileBehaviorChecks2[x](metatileBehavior) && direction == objectEvent->movementDirection)\n        {\n             \n            x = objectEvent->currentCoords.x;\n            y = objectEvent->currentCoords.y;\n            MoveCoords(direction, &x, &y);\n            ShowWarpArrowSprite(objectEvent->warpArrowSpriteId, direction, x, y);\n            return;\n        }\n    }\n    SetSpriteInvisible(objectEvent->warpArrowSpriteId);",
  },
  "InitPlayerAvatar": {
    returnType: "void",
    params: "s16 x, s16 y, u8 direction, u8 gender",
    callsTo: ["ClearPlayerAvatarInfo","CreateWarpArrowSprite","GetPlayerAvatarGraphicsIdByStateIdAndGender","ObjectEventTurn","SetPlayerAvatarStateMask","SpawnSpecialObjectEvent"],
    lineCount: 27,
    bodyC: "struct ObjectEventTemplate playerObjEventTemplate;\n    u8 objectEventId;\n    struct ObjectEvent *objectEvent;\n\n    playerObjEventTemplate.localId = LOCALID_PLAYER;\n    playerObjEventTemplate.graphicsId = GetPlayerAvatarGraphicsIdByStateIdAndGender(PLAYER_AVATAR_STATE_NORMAL, gender);\n    playerObjEventTemplate.x = x - MAP_OFFSET;\n    playerObjEventTemplate.y = y - MAP_OFFSET;\n    playerObjEventTemplate.elevation = ELEVATION_TRANSITION;\n    playerObjEventTemplate.movementType = MOVEMENT_TYPE_PLAYER;\n    playerObjEventTemplate.movementRangeX = 0;\n    playerObjEventTemplate.movementRangeY = 0;\n    playerObjEventTemplate.trainerType = TRAINER_TYPE_NONE;\n    playerObjEventTemplate.trainerRange_berryTreeId = 0;\n    playerObjEventTemplate.script = NULL;\n    playerObjEventTemplate.flagId = 0;\n    objectEventId = SpawnSpecialObjectEvent(&playerObjEventTemplate);\n    objectEvent = &gObjectEvents[objectEventId];\n    objectEvent->isPlayer = TRUE;\n    objectEvent->warpArrowSpriteId = CreateWarpArrowSprite();\n    ObjectEventTurn(objectEvent, direction);\n    ClearPlayerAvatarInfo();\n    gPlayerAvatar.runningState = NOT_MOVING;\n    gPlayerAvatar.tileTransitionState = T_NOT_MOVING;\n    gPlayerAvatar.objectEventId = objectEventId;\n    gPlayerAvatar.spriteId = objectEvent->spriteId;\n    gPlayerAvatar.gender = gender;\n    SetPlayerAvatarStateMask(PLAYER_AVATAR_FLAG_CONTROLLABLE | PLAYER_AVATAR_FLAG_ON_FOOT);",
  },
  "IsPlayerCollidingWithFarawayIslandMew": {
    returnType: "bool8",
    params: "u8 direction",
    callsTo: ["GetObjectEventIdByLocalIdAndMap","MAP_GROUP","MAP_NUM","MoveCoords"],
    lineCount: 26,
    bodyC: "u8 mewObjectId;\n    struct ObjectEvent *object;\n    s16 playerX;\n    s16 playerY;\n    s16 mewPrevX;\n\n    object = &gObjectEvents[gPlayerAvatar.objectEventId];\n    playerX = object->currentCoords.x;\n    playerY = object->currentCoords.y;\n\n    MoveCoords(direction, &playerX, &playerY);\n    mewObjectId = GetObjectEventIdByLocalIdAndMap(LOCALID_FARAWAY_ISLAND_MEW, MAP_NUM(MAP_FARAWAY_ISLAND_INTERIOR), MAP_GROUP(MAP_FARAWAY_ISLAND_INTERIOR));\n    if (mewObjectId == OBJECT_EVENTS_COUNT)\n        return FALSE;\n\n    object = &gObjectEvents[mewObjectId];\n    mewPrevX = object->previousCoords.x;\n\n    if (mewPrevX == playerX)\n    {\n        if (object->previousCoords.y != playerY\n            || object->currentCoords.x != mewPrevX\n            || object->currentCoords.y != object->previousCoords.y)\n        {\n            if (object->previousCoords.x == playerX &&\n                object->previousCoords.y == playerY)\n                return TRUE;\n        }\n    }\n    return FALSE;",
  },
  "IsPlayerFacingSurfableFishableWater": {
    returnType: "bool8",
    params: "void",
    callsTo: ["GetCollisionAtCoords","MapGridGetMetatileBehaviorAt","MetatileBehavior_IsSurfableFishableWater","MoveCoords","PlayerGetElevation"],
    lineCount: 10,
    bodyC: "struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n    s16 x = playerObjEvent->currentCoords.x;\n    s16 y = playerObjEvent->currentCoords.y;\n\n    MoveCoords(playerObjEvent->facingDirection, &x, &y);\n    if (GetCollisionAtCoords(playerObjEvent, x, y, playerObjEvent->facingDirection) == COLLISION_ELEVATION_MISMATCH\n     && PlayerGetElevation() == ELEVATION_DEFAULT\n     && MetatileBehavior_IsSurfableFishableWater(MapGridGetMetatileBehaviorAt(x, y)))\n        return TRUE;\n    else\n        return FALSE;",
  },
  "IsPlayerSpinEntranceActive": {
    returnType: "bool32",
    params: "void",
    callsTo: ["FuncIsActiveTask"],
    lineCount: 1,
    bodyC: "return FuncIsActiveTask(Task_DoPlayerSpinEntrance);",
  },
  "IsPlayerSpinExitActive": {
    returnType: "bool32",
    params: "void",
    callsTo: ["FuncIsActiveTask"],
    lineCount: 1,
    bodyC: "return FuncIsActiveTask(Task_DoPlayerSpinExit);",
  },
  "IsPlayerSurfingNorth": {
    returnType: "bool8",
    params: "void",
    callsTo: ["GetPlayerMovementDirection","TestPlayerAvatarFlags"],
    lineCount: 4,
    bodyC: "if (GetPlayerMovementDirection() == DIR_NORTH && TestPlayerAvatarFlags(PLAYER_AVATAR_FLAG_SURFING))\n        return TRUE;\n    else\n        return FALSE;",
  },
  "MovePlayerAvatarUsingKeypadInput": {
    returnType: "static void",
    params: "u8 direction, u16 newKeys, u16 heldKeys",
    callsTo: ["MovePlayerNotOnBike","MovePlayerOnBike"],
    lineCount: 4,
    bodyC: "if (gPlayerAvatar.flags & (PLAYER_AVATAR_FLAG_MACH_BIKE | PLAYER_AVATAR_FLAG_ACRO_BIKE))\n        MovePlayerOnBike(direction, newKeys, heldKeys);\n    else\n        MovePlayerNotOnBike(direction, heldKeys);",
  },
  "MovePlayerNotOnBike": {
    returnType: "static void",
    params: "u8 direction, u16 heldKeys",
    callsTo: ["CheckMovementInputNotOnBike"],
    lineCount: 1,
    bodyC: "sPlayerNotOnBikeFuncs[CheckMovementInputNotOnBike(direction)](direction, heldKeys);",
  },
  "MovePlayerToMapCoords": {
    returnType: "void",
    params: "s16 x, s16 y",
    callsTo: ["MoveObjectEventToMapCoords"],
    lineCount: 1,
    bodyC: "MoveObjectEventToMapCoords(&gObjectEvents[gPlayerAvatar.objectEventId], x, y);",
  },
  "MovementType_Player": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["UpdateObjectEventCurrentMovement","bool8"],
    lineCount: 1,
    bodyC: "UpdateObjectEventCurrentMovement(&gObjectEvents[sprite->data[0]], sprite, (bool8 (*)(struct ObjectEvent *, struct Sprite *))ObjectEventCB2_NoMovement2);",
  },
  "ObjectEventCB2_NoMovement2": {
    returnType: "static u8",
    params: "void",
    lineCount: 1,
    bodyC: "return 0;",
  },
  "PartyHasMonWithSurf": {
    returnType: "bool8",
    params: "void",
    callsTo: ["GetMonData","MonKnowsMove","TestPlayerAvatarFlags"],
    lineCount: 12,
    bodyC: "u8 i;\n\n    if (!TestPlayerAvatarFlags(PLAYER_AVATAR_FLAG_SURFING))\n    {\n        for (i = 0; i < PARTY_SIZE; i++)\n        {\n            if (GetMonData(&gPlayerParty[i], MON_DATA_SPECIES) == SPECIES_NONE)\n                break;\n            if (MonKnowsMove(&gPlayerParty[i], MOVE_SURF))\n                return TRUE;\n        }\n    }\n    return FALSE;",
  },
  "PlayCollisionSoundIfNotFacingWarp": {
    returnType: "static void",
    params: "u8 direction",
    callsTo: ["MapGridGetMetatileBehaviorAt","MetatileBehavior_IsWarpDoor","MoveCoords","PlaySE","PlayerGetDestCoords"],
    lineCount: 13,
    bodyC: "s16 x, y;\n    u8 metatileBehavior = gObjectEvents[gPlayerAvatar.objectEventId].currentMetatileBehavior;\n\n    if (!sArrowWarpMetatileBehaviorChecks[direction - 1](metatileBehavior))\n    {\n         \n        if (direction == DIR_NORTH)\n        {\n            PlayerGetDestCoords(&x, &y);\n            MoveCoords(direction, &x, &y);\n            if (MetatileBehavior_IsWarpDoor(MapGridGetMetatileBehaviorAt(x, y)))\n                return;\n        }\n        PlaySE(SE_WALL_HIT);\n    }",
  },
  "PlayerAcroTurnJump": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetJumpInPlaceTurnAroundMovementAction","PlaySE","PlayerSetAnimId"],
    lineCount: 2,
    bodyC: "PlaySE(SE_BIKE_HOP);\n    PlayerSetAnimId(GetJumpInPlaceTurnAroundMovementAction(direction), COPY_MOVE_FACE);",
  },
  "PlayerAllowForcedMovementIfMovingSameDirection": {
    returnType: "static void",
    params: "void",
    lineCount: 2,
    bodyC: "if (gPlayerAvatar.runningState == MOVING)\n        gPlayerAvatar.flags &= ~PLAYER_AVATAR_FLAG_CONTROLLABLE;",
  },
  "PlayerAnimIsMultiFrameStationary": {
    returnType: "static bool8",
    params: "void",
    lineCount: 9,
    bodyC: "u8 movementActionId = gObjectEvents[gPlayerAvatar.objectEventId].movementActionId;\n\n    if (movementActionId <= MOVEMENT_ACTION_FACE_RIGHT\n     || (movementActionId >= MOVEMENT_ACTION_DELAY_1 && movementActionId <= MOVEMENT_ACTION_DELAY_16)\n     || (movementActionId >= MOVEMENT_ACTION_WALK_IN_PLACE_SLOW_DOWN && movementActionId <= MOVEMENT_ACTION_WALK_IN_PLACE_FASTER_RIGHT)\n     || (movementActionId >= MOVEMENT_ACTION_ACRO_WHEELIE_FACE_DOWN && movementActionId <= MOVEMENT_ACTION_ACRO_END_WHEELIE_FACE_RIGHT)\n     || (movementActionId >= MOVEMENT_ACTION_ACRO_WHEELIE_IN_PLACE_DOWN && movementActionId <= MOVEMENT_ACTION_ACRO_WHEELIE_IN_PLACE_RIGHT))\n        return TRUE;\n    else\n        return FALSE;",
  },
  "PlayerAnimIsMultiFrameStationaryAndStateNotTurning": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["PlayerAnimIsMultiFrameStationary"],
    lineCount: 4,
    bodyC: "if (PlayerAnimIsMultiFrameStationary() && gPlayerAvatar.runningState != TURN_DIRECTION)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "PlayerAvatarTransition_AcroBike": {
    returnType: "static void",
    params: "struct ObjectEvent *objEvent",
    callsTo: ["BikeClearState","Bike_HandleBumpySlopeJump","GetPlayerAvatarGraphicsIdByStateId","ObjectEventSetGraphicsId","ObjectEventTurn","SetPlayerAvatarStateMask"],
    lineCount: 5,
    bodyC: "ObjectEventSetGraphicsId(objEvent, GetPlayerAvatarGraphicsIdByStateId(PLAYER_AVATAR_STATE_ACRO_BIKE));\n    ObjectEventTurn(objEvent, objEvent->movementDirection);\n    SetPlayerAvatarStateMask(PLAYER_AVATAR_FLAG_ACRO_BIKE);\n    BikeClearState(0, 0);\n    Bike_HandleBumpySlopeJump();",
  },
  "PlayerAvatarTransition_Dummy": {
    returnType: "static void",
    params: "struct ObjectEvent *objEvent",
    lineCount: 0,
    bodyC: "",
  },
  "PlayerAvatarTransition_MachBike": {
    returnType: "static void",
    params: "struct ObjectEvent *objEvent",
    callsTo: ["BikeClearState","GetPlayerAvatarGraphicsIdByStateId","ObjectEventSetGraphicsId","ObjectEventTurn","SetPlayerAvatarStateMask"],
    lineCount: 4,
    bodyC: "ObjectEventSetGraphicsId(objEvent, GetPlayerAvatarGraphicsIdByStateId(PLAYER_AVATAR_STATE_MACH_BIKE));\n    ObjectEventTurn(objEvent, objEvent->movementDirection);\n    SetPlayerAvatarStateMask(PLAYER_AVATAR_FLAG_MACH_BIKE);\n    BikeClearState(0, 0);",
  },
  "PlayerAvatarTransition_Normal": {
    returnType: "static void",
    params: "struct ObjectEvent *objEvent",
    callsTo: ["GetPlayerAvatarGraphicsIdByStateId","ObjectEventSetGraphicsId","ObjectEventTurn","SetPlayerAvatarStateMask"],
    lineCount: 3,
    bodyC: "ObjectEventSetGraphicsId(objEvent, GetPlayerAvatarGraphicsIdByStateId(PLAYER_AVATAR_STATE_NORMAL));\n    ObjectEventTurn(objEvent, objEvent->movementDirection);\n    SetPlayerAvatarStateMask(PLAYER_AVATAR_FLAG_ON_FOOT);",
  },
  "PlayerAvatarTransition_ReturnToField": {
    returnType: "static void",
    params: "struct ObjectEvent *objEvent",
    lineCount: 1,
    bodyC: "gPlayerAvatar.flags |= PLAYER_AVATAR_FLAG_CONTROLLABLE;",
  },
  "PlayerAvatarTransition_Surfing": {
    returnType: "static void",
    params: "struct ObjectEvent *objEvent",
    callsTo: ["FieldEffectStart","GetPlayerAvatarGraphicsIdByStateId","ObjectEventSetGraphicsId","ObjectEventTurn","SetPlayerAvatarStateMask","SetSurfBlob_BobState"],
    lineCount: 10,
    bodyC: "u8 spriteId;\n\n    ObjectEventSetGraphicsId(objEvent, GetPlayerAvatarGraphicsIdByStateId(PLAYER_AVATAR_STATE_SURFING));\n    ObjectEventTurn(objEvent, objEvent->movementDirection);\n    SetPlayerAvatarStateMask(PLAYER_AVATAR_FLAG_SURFING);\n    gFieldEffectArguments[0] = objEvent->currentCoords.x;\n    gFieldEffectArguments[1] = objEvent->currentCoords.y;\n    gFieldEffectArguments[2] = gPlayerAvatar.objectEventId;\n    spriteId = FieldEffectStart(FLDEFF_SURF_BLOB);\n    objEvent->fieldEffectSpriteId = spriteId;\n    SetSurfBlob_BobState(spriteId, BOB_PLAYER_AND_MON);",
  },
  "PlayerAvatarTransition_Underwater": {
    returnType: "static void",
    params: "struct ObjectEvent *objEvent",
    callsTo: ["GetPlayerAvatarGraphicsIdByStateId","ObjectEventSetGraphicsId","ObjectEventTurn","SetPlayerAvatarStateMask","StartUnderwaterSurfBlobBobbing"],
    lineCount: 4,
    bodyC: "ObjectEventSetGraphicsId(objEvent, GetPlayerAvatarGraphicsIdByStateId(PLAYER_AVATAR_STATE_UNDERWATER));\n    ObjectEventTurn(objEvent, objEvent->movementDirection);\n    SetPlayerAvatarStateMask(PLAYER_AVATAR_FLAG_UNDERWATER);\n    objEvent->fieldEffectSpriteId = StartUnderwaterSurfBlobBobbing(objEvent->spriteId);",
  },
  "PlayerAvatar_DoSecretBaseMatJump": {
    returnType: "static u8",
    params: "struct Task *task, struct ObjectEvent *objectEvent",
    callsTo: ["DestroyTask","FindTaskIdByFunc","GetJumpInPlaceMovementAction","ObjectEventClearHeldMovementIfFinished","ObjectEventSetHeldMovement","PlaySE"],
    lineCount: 14,
    bodyC: "gPlayerAvatar.preventStep = TRUE;\n    if (ObjectEventClearHeldMovementIfFinished(objectEvent))\n    {\n        PlaySE(SE_LEDGE);\n        ObjectEventSetHeldMovement(objectEvent, GetJumpInPlaceMovementAction(objectEvent->facingDirection));\n        task->data[1]++;\n        if (task->data[1] > 1)\n        {\n            gPlayerAvatar.preventStep = FALSE;\n            gPlayerAvatar.transitionFlags |= PLAYER_AVATAR_FLAG_CONTROLLABLE;\n            DestroyTask(FindTaskIdByFunc(DoPlayerAvatarSecretBaseMatJump));\n        }\n    }\n    return FALSE;",
  },
  "PlayerAvatar_DoSecretBaseMatSpin": {
    returnType: "static void",
    params: "u8 taskId",
    lineCount: 2,
    bodyC: "while (sPlayerAvatarSecretBaseMatSpin[gTasks[taskId].data[0]](&gTasks[taskId], &gObjectEvents[gPlayerAvatar.objectEventId]))\n        ;",
  },
  "PlayerAvatar_SecretBaseMatSpinStep0": {
    returnType: "static bool8",
    params: "struct Task *task, struct ObjectEvent *objectEvent",
    callsTo: ["LockPlayerFieldControls","PlaySE"],
    lineCount: 6,
    bodyC: "task->data[0]++;\n    task->data[1] = objectEvent->movementDirection;\n    gPlayerAvatar.preventStep = TRUE;\n    LockPlayerFieldControls();\n    PlaySE(SE_WARP_IN);\n    return TRUE;",
  },
  "PlayerAvatar_SecretBaseMatSpinStep1": {
    returnType: "static bool8",
    params: "struct Task *task, struct ObjectEvent *objectEvent",
    callsTo: ["GetFaceDirectionMovementAction","GetOppositeDirection","ObjectEventClearHeldMovementIfFinished","ObjectEventSetHeldMovement"],
    lineCount: 12,
    bodyC: "u8 directions[] = {DIR_WEST, DIR_EAST, DIR_NORTH, DIR_SOUTH};\n\n    if (ObjectEventClearHeldMovementIfFinished(objectEvent))\n    {\n        u8 direction;\n\n        ObjectEventSetHeldMovement(objectEvent, GetFaceDirectionMovementAction(direction = directions[objectEvent->movementDirection - 1]));\n        if (direction == (u8)task->data[1])\n            task->data[2]++;\n        task->data[0]++;\n        if (task->data[2] > 3 && direction == GetOppositeDirection(task->data[1]))\n            task->data[0]++;\n    }\n    return FALSE;",
  },
  "PlayerAvatar_SecretBaseMatSpinStep2": {
    returnType: "static bool8",
    params: "struct Task *task, struct ObjectEvent *objectEvent",
    callsTo: ["ObjectEventClearHeldMovementIfFinished","ObjectEventSetHeldMovement"],
    lineCount: 13,
    bodyC: "const u8 actions[] = {\n        MOVEMENT_ACTION_DELAY_1,\n        MOVEMENT_ACTION_DELAY_1,\n        MOVEMENT_ACTION_DELAY_2,\n        MOVEMENT_ACTION_DELAY_4,\n        MOVEMENT_ACTION_DELAY_8,\n    };\n\n    if (ObjectEventClearHeldMovementIfFinished(objectEvent))\n    {\n        ObjectEventSetHeldMovement(objectEvent, actions[task->data[2]]);\n        task->data[0] = 1;\n    }\n    return FALSE;",
  },
  "PlayerAvatar_SecretBaseMatSpinStep3": {
    returnType: "static bool8",
    params: "struct Task *task, struct ObjectEvent *objectEvent",
    callsTo: ["DestroyTask","FindTaskIdByFunc","GetOppositeDirection","GetWalkSlowMovementAction","ObjectEventClearHeldMovementIfFinished","ObjectEventSetHeldMovement","UnlockPlayerFieldControls"],
    lineCount: 8,
    bodyC: "if (ObjectEventClearHeldMovementIfFinished(objectEvent))\n    {\n        ObjectEventSetHeldMovement(objectEvent, GetWalkSlowMovementAction(GetOppositeDirection(task->data[1])));\n        UnlockPlayerFieldControls();\n        gPlayerAvatar.preventStep = FALSE;\n        DestroyTask(FindTaskIdByFunc(PlayerAvatar_DoSecretBaseMatSpin));\n    }\n    return FALSE;",
  },
  "PlayerCheckIfAnimFinishedOrInactive": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["ObjectEventCheckHeldMovementStatus"],
    lineCount: 1,
    bodyC: "return ObjectEventCheckHeldMovementStatus(&gObjectEvents[gPlayerAvatar.objectEventId]);",
  },
  "PlayerEndWheelie": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetAcroEndWheelieFaceDirectionMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetAcroEndWheelieFaceDirectionMovementAction(direction), COPY_MOVE_FACE);",
  },
  "PlayerEndWheelieWhileMoving": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetAcroEndWheelieMoveDirectionMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetAcroEndWheelieMoveDirectionMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerFaceDirection": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetFaceDirectionMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetFaceDirectionMovementAction(direction), COPY_MOVE_FACE);",
  },
  "PlayerForceSetHeldMovement": {
    returnType: "static void",
    params: "u8 movementActionId",
    callsTo: ["ObjectEventForceSetHeldMovement"],
    lineCount: 1,
    bodyC: "ObjectEventForceSetHeldMovement(&gObjectEvents[gPlayerAvatar.objectEventId], movementActionId);",
  },
  "PlayerFreeze": {
    returnType: "void",
    params: "void",
    callsTo: ["GetFaceDirectionMovementAction","IsPlayerNotUsingAcroBikeOnBumpySlope","PlayerForceSetHeldMovement"],
    lineCount: 5,
    bodyC: "if (gPlayerAvatar.tileTransitionState == T_TILE_CENTER || gPlayerAvatar.tileTransitionState == T_NOT_MOVING)\n    {\n        if (IsPlayerNotUsingAcroBikeOnBumpySlope())\n            PlayerForceSetHeldMovement(GetFaceDirectionMovementAction(gObjectEvents[gPlayerAvatar.objectEventId].facingDirection));\n    }",
  },
  "PlayerGetCopyableMovement": {
    returnType: "u8",
    params: "void",
    lineCount: 1,
    bodyC: "return gObjectEvents[gPlayerAvatar.objectEventId].playerCopyableMovement;",
  },
  "PlayerGetDestCoords": {
    returnType: "void",
    params: "s16 *x, s16 *y",
    lineCount: 2,
    bodyC: "*x = gObjectEvents[gPlayerAvatar.objectEventId].currentCoords.x;\n    *y = gObjectEvents[gPlayerAvatar.objectEventId].currentCoords.y;",
  },
  "PlayerGetElevation": {
    returnType: "u8",
    params: "void",
    lineCount: 1,
    bodyC: "return gObjectEvents[gPlayerAvatar.objectEventId].previousElevation;",
  },
  "PlayerIdleWheelie": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetAcroWheelieFaceDirectionMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetAcroWheelieFaceDirectionMovementAction(direction), COPY_MOVE_FACE);",
  },
  "PlayerIsAnimActive": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["ObjectEventIsMovementOverridden"],
    lineCount: 1,
    bodyC: "return ObjectEventIsMovementOverridden(&gObjectEvents[gPlayerAvatar.objectEventId]);",
  },
  "PlayerJumpLedge": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetJump2MovementAction","PlaySE","PlayerSetAnimId"],
    lineCount: 2,
    bodyC: "PlaySE(SE_LEDGE);\n    PlayerSetAnimId(GetJump2MovementAction(direction), COPY_MOVE_JUMP2);",
  },
  "PlayerLedgeHoppingWheelie": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetAcroWheelieJumpDirectionMovementAction","PlaySE","PlayerSetAnimId"],
    lineCount: 2,
    bodyC: "PlaySE(SE_BIKE_HOP);\n    PlayerSetAnimId(GetAcroWheelieJumpDirectionMovementAction(direction), COPY_MOVE_JUMP2);",
  },
  "PlayerMovingHoppingWheelie": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetAcroWheelieHopDirectionMovementAction","PlaySE","PlayerSetAnimId"],
    lineCount: 2,
    bodyC: "PlaySE(SE_BIKE_HOP);\n    PlayerSetAnimId(GetAcroWheelieHopDirectionMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerNotOnBikeCollide": {
    returnType: "static void",
    params: "u8 direction",
    callsTo: ["GetWalkInPlaceSlowMovementAction","PlayCollisionSoundIfNotFacingWarp","PlayerSetAnimId"],
    lineCount: 2,
    bodyC: "PlayCollisionSoundIfNotFacingWarp(direction);\n    PlayerSetAnimId(GetWalkInPlaceSlowMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerNotOnBikeCollideWithFarawayIslandMew": {
    returnType: "static void",
    params: "u8 direction",
    callsTo: ["GetWalkInPlaceSlowMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetWalkInPlaceSlowMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerNotOnBikeMoving": {
    returnType: "static void",
    params: "u8 direction, u16 heldKeys",
    callsTo: ["CheckForPlayerAvatarCollision","FlagGet","IsPlayerCollidingWithFarawayIslandMew","IsRunningDisallowed","PlayerJumpLedge","PlayerNotOnBikeCollide","PlayerNotOnBikeCollideWithFarawayIslandMew","PlayerRun","PlayerWalkFast","PlayerWalkNormal"],
    lineCount: 37,
    bodyC: "u8 collision = CheckForPlayerAvatarCollision(direction);\n\n    if (collision)\n    {\n        if (collision == COLLISION_LEDGE_JUMP)\n        {\n            PlayerJumpLedge(direction);\n            return;\n        }\n        else if (collision == COLLISION_OBJECT_EVENT && IsPlayerCollidingWithFarawayIslandMew(direction))\n        {\n            PlayerNotOnBikeCollideWithFarawayIslandMew(direction);\n            return;\n        }\n        else\n        {\n             \n            u8 adjustedCollision = collision - COLLISION_STOP_SURFING;\n            if (adjustedCollision > 3)\n                PlayerNotOnBikeCollide(direction);\n            return;\n        }\n    }\n\n    if (gPlayerAvatar.flags & PLAYER_AVATAR_FLAG_SURFING)\n    {\n         \n        PlayerWalkFast(direction);\n        return;\n    }\n\n    if (!(gPlayerAvatar.flags & PLAYER_AVATAR_FLAG_UNDERWATER) && (heldKeys & B_BUTTON) && FlagGet(FLAG_SYS_B_DASH)\n     && IsRunningDisallowed(gObjectEvents[gPlayerAvatar.objectEventId].currentMetatileBehavior) == 0)\n    {\n        PlayerRun(direction);\n        gPlayerAvatar.flags |= PLAYER_AVATAR_FLAG_DASH;\n        return;\n    }\n    else\n    {\n        PlayerWalkNormal(direction);\n    }",
  },
  "PlayerNotOnBikeNotMoving": {
    returnType: "static void",
    params: "u8 direction, u16 heldKeys",
    callsTo: ["GetPlayerFacingDirection","PlayerFaceDirection"],
    lineCount: 1,
    bodyC: "PlayerFaceDirection(GetPlayerFacingDirection());",
  },
  "PlayerNotOnBikeTurningInPlace": {
    returnType: "static void",
    params: "u8 direction, u16 heldKeys",
    callsTo: ["PlayerTurnInPlace"],
    lineCount: 1,
    bodyC: "PlayerTurnInPlace(direction);",
  },
  "PlayerOnBikeCollide": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetWalkInPlaceNormalMovementAction","PlayCollisionSoundIfNotFacingWarp","PlayerSetAnimId"],
    lineCount: 2,
    bodyC: "PlayCollisionSoundIfNotFacingWarp(direction);\n    PlayerSetAnimId(GetWalkInPlaceNormalMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerOnBikeCollideWithFarawayIslandMew": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetWalkInPlaceNormalMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetWalkInPlaceNormalMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerPopWheelieWhileMoving": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetAcroPopWheelieMoveDirectionMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetAcroPopWheelieMoveDirectionMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerRideWaterCurrent": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetRideWaterCurrentMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetRideWaterCurrentMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerRun": {
    returnType: "static void",
    params: "u8 direction",
    callsTo: ["GetPlayerRunMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetPlayerRunMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerSetAnimId": {
    returnType: "void",
    params: "u8 movementActionId, u8 copyableMovement",
    callsTo: ["ObjectEventSetHeldMovement","PlayerIsAnimActive","PlayerSetCopyableMovement"],
    lineCount: 5,
    bodyC: "if (!PlayerIsAnimActive())\n    {\n        PlayerSetCopyableMovement(copyableMovement);\n        ObjectEventSetHeldMovement(&gObjectEvents[gPlayerAvatar.objectEventId], movementActionId);\n    }",
  },
  "PlayerSetCopyableMovement": {
    returnType: "static void",
    params: "u8 movement",
    lineCount: 1,
    bodyC: "gObjectEvents[gPlayerAvatar.objectEventId].playerCopyableMovement = movement;",
  },
  "PlayerStandingHoppingWheelie": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetAcroWheelieHopFaceDirectionMovementAction","PlaySE","PlayerSetAnimId"],
    lineCount: 2,
    bodyC: "PlaySE(SE_BIKE_HOP);\n    PlayerSetAnimId(GetAcroWheelieHopFaceDirectionMovementAction(direction), COPY_MOVE_FACE);",
  },
  "PlayerStartWheelie": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetAcroPopWheelieFaceDirectionMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetAcroPopWheelieFaceDirectionMovementAction(direction), COPY_MOVE_FACE);",
  },
  "PlayerStep": {
    returnType: "void",
    params: "u8 direction, u16 newKeys, u16 heldKeys",
    callsTo: ["Bike_TryAcroBikeHistoryUpdate","DoPlayerAvatarTransition","HideShowWarpArrow","MovePlayerAvatarUsingKeypadInput","PlayerAllowForcedMovementIfMovingSameDirection","TryDoMetatileBehaviorForcedMovement","TryInterruptObjectEventSpecialAnim","npc_clear_strange_bits"],
    lineCount: 16,
    bodyC: "struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n    HideShowWarpArrow(playerObjEvent);\n    if (gPlayerAvatar.preventStep == FALSE)\n    {\n        Bike_TryAcroBikeHistoryUpdate(newKeys, heldKeys);\n        if (TryInterruptObjectEventSpecialAnim(playerObjEvent, direction) == 0)\n        {\n            npc_clear_strange_bits(playerObjEvent);\n            DoPlayerAvatarTransition();\n            if (TryDoMetatileBehaviorForcedMovement() == 0)\n            {\n                MovePlayerAvatarUsingKeypadInput(direction, newKeys, heldKeys);\n                PlayerAllowForcedMovementIfMovingSameDirection();\n            }\n        }\n    }",
  },
  "PlayerTurnInPlace": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetWalkInPlaceFastMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetWalkInPlaceFastMovementAction(direction), COPY_MOVE_FACE);",
  },
  "PlayerUseAcroBikeOnBumpySlope": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetAcroWheelieDirectionAnimNum","GetPlayerAvatarGraphicsIdByStateId","ObjectEventSetGraphicsId","SeekSpriteAnim","StartSpriteAnim"],
    lineCount: 3,
    bodyC: "ObjectEventSetGraphicsId(&gObjectEvents[gPlayerAvatar.objectEventId], GetPlayerAvatarGraphicsIdByStateId(PLAYER_AVATAR_STATE_ACRO_BIKE));\n    StartSpriteAnim(&gSprites[gPlayerAvatar.spriteId], GetAcroWheelieDirectionAnimNum(direction));\n    SeekSpriteAnim(&gSprites[gPlayerAvatar.spriteId], 1);",
  },
  "PlayerWalkFast": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetWalkFastMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetWalkFastMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerWalkFaster": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetWalkFasterMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetWalkFasterMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerWalkNormal": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetWalkNormalMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetWalkNormalMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerWheelieInPlace": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetAcroWheelieInPlaceDirectionMovementAction","PlaySE","PlayerSetAnimId"],
    lineCount: 2,
    bodyC: "PlaySE(SE_WALL_HIT);\n    PlayerSetAnimId(GetAcroWheelieInPlaceDirectionMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PlayerWheelieMove": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetAcroWheelieMoveDirectionMovementAction","PlayerSetAnimId"],
    lineCount: 1,
    bodyC: "PlayerSetAnimId(GetAcroWheelieMoveDirectionMovementAction(direction), COPY_MOVE_WALK);",
  },
  "PushBoulder_End": {
    returnType: "static bool8",
    params: "struct Task *task, struct ObjectEvent *player, struct ObjectEvent *boulder",
    callsTo: ["DestroyTask","FindTaskIdByFunc","ObjectEventCheckHeldMovementStatus","ObjectEventClearHeldMovementIfFinished","UnlockPlayerFieldControls"],
    lineCount: 10,
    bodyC: "if (ObjectEventCheckHeldMovementStatus(player)\n     && ObjectEventCheckHeldMovementStatus(boulder))\n    {\n        ObjectEventClearHeldMovementIfFinished(player);\n        ObjectEventClearHeldMovementIfFinished(boulder);\n        gPlayerAvatar.preventStep = FALSE;\n        UnlockPlayerFieldControls();\n        DestroyTask(FindTaskIdByFunc(Task_PushBoulder));\n    }\n    return FALSE;",
  },
  "PushBoulder_Move": {
    returnType: "static bool8",
    params: "struct Task *task, struct ObjectEvent *player, struct ObjectEvent *boulder",
    callsTo: ["FieldEffectStart","GetWalkInPlaceNormalMovementAction","GetWalkSlowMovementAction","ObjectEventClearHeldMovementIfFinished","ObjectEventIsHeldMovementActive","ObjectEventIsMovementOverridden","ObjectEventSetHeldMovement","PlaySE"],
    lineCount: 20,
    bodyC: "if (ObjectEventIsHeldMovementActive(player))\n        ObjectEventClearHeldMovementIfFinished(player);\n\n    if (ObjectEventIsHeldMovementActive(boulder))\n        ObjectEventClearHeldMovementIfFinished(boulder);\n\n    if (!ObjectEventIsMovementOverridden(player)\n     && !ObjectEventIsMovementOverridden(boulder))\n    {\n        ObjectEventClearHeldMovementIfFinished(player);\n        ObjectEventClearHeldMovementIfFinished(boulder);\n        ObjectEventSetHeldMovement(player, GetWalkInPlaceNormalMovementAction((u8)task->tDirection));\n        ObjectEventSetHeldMovement(boulder, GetWalkSlowMovementAction((u8)task->tDirection));\n        gFieldEffectArguments[0] = boulder->currentCoords.x;\n        gFieldEffectArguments[1] = boulder->currentCoords.y;\n        gFieldEffectArguments[2] = boulder->previousElevation;\n        gFieldEffectArguments[3] = gSprites[boulder->spriteId].oam.priority;\n        FieldEffectStart(FLDEFF_DUST);\n        PlaySE(SE_M_STRENGTH);\n        task->tState++;\n    }\n    return FALSE;",
  },
  "PushBoulder_Start": {
    returnType: "static bool8",
    params: "struct Task *task, struct ObjectEvent *player, struct ObjectEvent *boulder",
    callsTo: ["LockPlayerFieldControls"],
    lineCount: 4,
    bodyC: "LockPlayerFieldControls();\n    gPlayerAvatar.preventStep = TRUE;\n    task->tState++;\n    return FALSE;",
  },
  "SetPlayerAvatarExtraStateTransition": {
    returnType: "void",
    params: "u8 graphicsId, u8 transitionFlag",
    callsTo: ["DoPlayerAvatarTransition","GetPlayerAvatarStateTransitionByGraphicsId"],
    lineCount: 3,
    bodyC: "u8 stateFlag = GetPlayerAvatarStateTransitionByGraphicsId(graphicsId, gPlayerAvatar.gender);\n\n    gPlayerAvatar.transitionFlags |= stateFlag | transitionFlag;\n    DoPlayerAvatarTransition();",
  },
  "SetPlayerAvatarFieldMove": {
    returnType: "void",
    params: "void",
    callsTo: ["GetPlayerAvatarGraphicsIdByStateId","ObjectEventSetGraphicsId","StartSpriteAnim"],
    lineCount: 2,
    bodyC: "ObjectEventSetGraphicsId(&gObjectEvents[gPlayerAvatar.objectEventId], GetPlayerAvatarGraphicsIdByStateId(PLAYER_AVATAR_STATE_FIELD_MOVE));\n    StartSpriteAnim(&gSprites[gPlayerAvatar.spriteId], ANIM_FIELD_MOVE);",
  },
  "SetPlayerAvatarFishing": {
    returnType: "static void",
    params: "u8 direction",
    callsTo: ["GetFishingDirectionAnimNum","GetPlayerAvatarGraphicsIdByStateId","ObjectEventSetGraphicsId","StartSpriteAnim"],
    lineCount: 2,
    bodyC: "ObjectEventSetGraphicsId(&gObjectEvents[gPlayerAvatar.objectEventId], GetPlayerAvatarGraphicsIdByStateId(PLAYER_AVATAR_STATE_FISHING));\n    StartSpriteAnim(&gSprites[gPlayerAvatar.spriteId], GetFishingDirectionAnimNum(direction));",
  },
  "SetPlayerAvatarStateMask": {
    returnType: "void",
    params: "u8 flags",
    lineCount: 2,
    bodyC: "gPlayerAvatar.flags &= (PLAYER_AVATAR_FLAG_DASH | PLAYER_AVATAR_FLAG_FORCED_MOVE | PLAYER_AVATAR_FLAG_CONTROLLABLE);\n    gPlayerAvatar.flags |= flags;",
  },
  "SetPlayerAvatarTransitionFlags": {
    returnType: "void",
    params: "u16 transitionFlags",
    callsTo: ["DoPlayerAvatarTransition"],
    lineCount: 2,
    bodyC: "gPlayerAvatar.transitionFlags |= transitionFlags;\n    DoPlayerAvatarTransition();",
  },
  "SetPlayerAvatarWatering": {
    returnType: "void",
    params: "u8 direction",
    callsTo: ["GetFaceDirectionAnimNum","GetPlayerAvatarGraphicsIdByStateId","ObjectEventSetGraphicsId","StartSpriteAnim"],
    lineCount: 2,
    bodyC: "ObjectEventSetGraphicsId(&gObjectEvents[gPlayerAvatar.objectEventId], GetPlayerAvatarGraphicsIdByStateId(PLAYER_AVATAR_STATE_WATERING));\n    StartSpriteAnim(&gSprites[gPlayerAvatar.spriteId], GetFaceDirectionAnimNum(direction));",
  },
  "SetPlayerInvisibility": {
    returnType: "void",
    params: "bool8 invisible",
    callsTo: ["TestPlayerAvatarFlags"],
    lineCount: 3,
    bodyC: "gObjectEvents[gPlayerAvatar.objectEventId].invisible = invisible;\n    if (TestPlayerAvatarFlags(PLAYER_AVATAR_FLAG_SURFING))\n        gSprites[gObjectEvents[gPlayerAvatar.objectEventId].fieldEffectSpriteId].invisible = invisible;",
  },
  "SetSpinStartFacingDir": {
    returnType: "void",
    params: "u8 direction",
    lineCount: 1,
    bodyC: "sSpinStartFacingDir = direction;",
  },
  "ShouldJumpLedge": {
    returnType: "static bool8",
    params: "s16 x, s16 y, u8 direction",
    callsTo: ["GetLedgeJumpDirection"],
    lineCount: 4,
    bodyC: "if (GetLedgeJumpDirection(x, y, direction) != DIR_NONE)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "StartFishing": {
    returnType: "void",
    params: "u8 rod",
    callsTo: ["CreateTask","Task_Fishing"],
    lineCount: 3,
    bodyC: "u8 taskId = CreateTask(Task_Fishing, 0xFF);\n\n    gTasks[taskId].tFishingRod = rod;\n    Task_Fishing(taskId);",
  },
  "StartStrengthAnim": {
    returnType: "static void",
    params: "u8 objectEventId, u8 direction",
    callsTo: ["CreateTask","Task_PushBoulder"],
    lineCount: 4,
    bodyC: "u8 taskId = CreateTask(Task_PushBoulder, 0xFF);\n\n    gTasks[taskId].tBoulderObjId = objectEventId;\n    gTasks[taskId].tDirection = direction;\n    Task_PushBoulder(taskId);",
  },
  "StopPlayerAvatar": {
    returnType: "void",
    params: "void",
    callsTo: ["Bike_HandleBumpySlopeJump","Bike_UpdateBikeCounterSpeed","SetObjectEventDirection","TestPlayerAvatarFlags","npc_clear_strange_bits"],
    lineCount: 8,
    bodyC: "struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n    npc_clear_strange_bits(playerObjEvent);\n    SetObjectEventDirection(playerObjEvent, playerObjEvent->facingDirection);\n    if (TestPlayerAvatarFlags(PLAYER_AVATAR_FLAG_MACH_BIKE | PLAYER_AVATAR_FLAG_ACRO_BIKE))\n    {\n        Bike_HandleBumpySlopeJump();\n        Bike_UpdateBikeCounterSpeed(0);\n    }",
  },
  "Task_DoPlayerSpinEntrance": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CameraObjectFreeze","CameraObjectReset","DestroyTask","GetFaceDirectionMovementAction","GetSpinStartFacingDir","ObjectEventForceSetHeldMovement","TrySpinPlayerForWarp"],
    lineCount: 51,
    bodyC: "struct ObjectEvent *object = &gObjectEvents[gPlayerAvatar.objectEventId];\n    struct Sprite *sprite = &gSprites[object->spriteId];\n    s16 *data = gTasks[taskId].data;\n\n    switch (tState)\n    {\n        case 0:\n             \n             \n             \n            tStartDir = GetSpinStartFacingDir();\n            ObjectEventForceSetHeldMovement(object, GetFaceDirectionMovementAction(sSpinDirections[tStartDir]));\n            tSpinDelayTimer = 0;\n            tSpeed = 116;\n            tDestY = sprite->y;\n            tPriority = sprite->oam.priority;\n            tSubpriority = sprite->subpriority;\n            tCurY = -((u16)sprite->y2 + 32) * 16;\n            sprite->y2 = 0;\n            CameraObjectFreeze();\n            object->fixedPriority = TRUE;\n            sprite->oam.priority = 1;\n            sprite->subpriority = 0;\n            sprite->subspriteMode = SUBSPRITES_OFF;\n            tState++;\n        case 1:  \n            TrySpinPlayerForWarp(object, &tSpinDelayTimer);\n\n             \n            tCurY += tSpeed;\n            tSpeed -= 3;\n            if (tSpeed < 4)\n                tSpeed = 4;\n            sprite->y = tCurY >> 4;\n\n             \n            if (sprite->y >= tDestY)\n            {\n                sprite->y = tDestY;\n                tGroundTimer = 0;\n                tState++;\n            }\n            break;\n        case 2:  \n            TrySpinPlayerForWarp(object, &tSpinDelayTimer);\n            if (++tGroundTimer > 8)\n                tState++;\n            break;\n        case 3:  \n            if (tStartDir == TrySpinPlayerForWarp(object, &tSpinDelayTimer))\n            {\n                object->fixedPriority = 0;\n                sprite->oam.priority = tPriority;\n                sprite->subpriority = tSubpriority;\n                CameraObjectReset();\n                DestroyTask(taskId);\n            }\n            break;\n    }",
  },
  "Task_DoPlayerSpinExit": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CameraObjectFreeze","DestroyTask","ObjectEventClearHeldMovementIfFinished","SetSpinStartFacingDir","TrySpinPlayerForWarp"],
    lineCount: 31,
    bodyC: "struct ObjectEvent *object = &gObjectEvents[gPlayerAvatar.objectEventId];\n    struct Sprite *sprite = &gSprites[object->spriteId];\n    s16 *data = gTasks[taskId].data;\n\n    switch (tState)\n    {\n        case 0:  \n            if (!ObjectEventClearHeldMovementIfFinished(object))\n                return;\n\n            SetSpinStartFacingDir(object->facingDirection);\n            tSpinDelayTimer = 0;\n            tSpeed = 1;\n            tCurY = (u16)(sprite->y + sprite->y2) << 4;\n            sprite->y2 = 0;\n            CameraObjectFreeze();\n            object->fixedPriority = TRUE;\n            sprite->oam.priority = 0;\n            sprite->subpriority = 0;\n            sprite->subspriteMode = SUBSPRITES_OFF;\n            tState++;\n        case 1:  \n            TrySpinPlayerForWarp(object, &tSpinDelayTimer);\n\n             \n            tCurY -= tSpeed;\n            tSpeed += 3;\n            sprite->y = tCurY >> 4;\n\n             \n            if (sprite->y + (s16)gTotalCameraPixelOffsetY < -32)\n                tState++;\n            break;\n        case 2:\n            DestroyTask(taskId);\n            break;\n    }",
  },
  "Task_Fishing": {
    returnType: "static void",
    params: "u8 taskId",
    lineCount: 2,
    bodyC: "while (sFishingStateFuncs[gTasks[taskId].tStep](&gTasks[taskId]))\n        ;",
  },
  "Task_PushBoulder": {
    returnType: "static void",
    params: "u8 taskId",
    lineCount: 4,
    bodyC: "while (sPushBoulderFuncs[gTasks[taskId].tState](&gTasks[taskId],\n                                                     &gObjectEvents[gPlayerAvatar.objectEventId],\n                                                     &gObjectEvents[gTasks[taskId].tBoulderObjId]))\n        ;",
  },
  "Task_StopSurfingInit": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["GetJumpSpecialMovementAction","ObjectEventClearHeldMovementIfFinished","ObjectEventIsMovementOverridden","ObjectEventSetHeldMovement","SetSurfBlob_BobState"],
    lineCount: 9,
    bodyC: "struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n    if (ObjectEventIsMovementOverridden(playerObjEvent))\n    {\n        if (!ObjectEventClearHeldMovementIfFinished(playerObjEvent))\n            return;\n    }\n    SetSurfBlob_BobState(playerObjEvent->fieldEffectSpriteId, BOB_JUST_MON);\n    ObjectEventSetHeldMovement(playerObjEvent, GetJumpSpecialMovementAction((u8)gTasks[taskId].data[0]));\n    gTasks[taskId].func = Task_WaitStopSurfing;",
  },
  "Task_WaitStopSurfing": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroySprite","DestroyTask","GetFaceDirectionMovementAction","GetPlayerAvatarGraphicsIdByStateId","ObjectEventClearHeldMovementIfFinished","ObjectEventSetGraphicsId","ObjectEventSetHeldMovement","UnlockPlayerFieldControls"],
    lineCount: 13,
    bodyC: "struct ObjectEvent *playerObjEvent = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n    if (ObjectEventClearHeldMovementIfFinished(playerObjEvent))\n    {\n        ObjectEventSetGraphicsId(playerObjEvent, GetPlayerAvatarGraphicsIdByStateId(PLAYER_AVATAR_STATE_NORMAL));\n        ObjectEventSetHeldMovement(playerObjEvent, GetFaceDirectionMovementAction(playerObjEvent->facingDirection));\n        gPlayerAvatar.preventStep = FALSE;\n        UnlockPlayerFieldControls();\n        DestroySprite(&gSprites[playerObjEvent->fieldEffectSpriteId]);\n#ifdef BUGFIX\n         \n        playerObjEvent->triggerGroundEffectsOnMove = TRUE;\n#endif\n        DestroyTask(taskId);\n    }",
  },
  "TestPlayerAvatarFlags": {
    returnType: "u8",
    params: "u8 flag",
    lineCount: 1,
    bodyC: "return gPlayerAvatar.flags & flag;",
  },
  "TryDoMetatileBehaviorForcedMovement": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["GetForcedMovementByMetatileBehavior"],
    lineCount: 1,
    bodyC: "return sForcedMovementFuncs[GetForcedMovementByMetatileBehavior()]();",
  },
  "TryInterruptObjectEventSpecialAnim": {
    returnType: "static bool8",
    params: "struct ObjectEvent *playerObjEvent, u8 direction",
    callsTo: ["CheckForPlayerAvatarStaticCollision","ObjectEventClearHeldMovement","ObjectEventClearHeldMovementIfFinished","ObjectEventGetHeldMovementActionId","ObjectEventIsMovementOverridden"],
    lineCount: 24,
    bodyC: "if (ObjectEventIsMovementOverridden(playerObjEvent)\n     && !ObjectEventClearHeldMovementIfFinished(playerObjEvent))\n    {\n        u8 heldMovementActionId = ObjectEventGetHeldMovementActionId(playerObjEvent);\n        if (heldMovementActionId > MOVEMENT_ACTION_WALK_FAST_RIGHT && heldMovementActionId < MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_DOWN)\n        {\n            if (direction == DIR_NONE)\n            {\n                return TRUE;\n            }\n\n            if (playerObjEvent->movementDirection != direction)\n            {\n                ObjectEventClearHeldMovement(playerObjEvent);\n                return FALSE;\n            }\n\n            if (CheckForPlayerAvatarStaticCollision(direction) == COLLISION_NONE)\n            {\n                ObjectEventClearHeldMovement(playerObjEvent);\n                return FALSE;\n            }\n        }\n\n        return TRUE;\n    }\n\n    return FALSE;",
  },
  "TryPushBoulder": {
    returnType: "static bool8",
    params: "s16 x, s16 y, u8 direction",
    callsTo: ["FlagGet","GetCollisionAtCoords","GetObjectEventIdByXY","MapGridGetMetatileBehaviorAt","MetatileBehavior_IsNonAnimDoor","MoveCoords","StartStrengthAnim"],
    lineCount: 17,
    bodyC: "if (FlagGet(FLAG_SYS_USE_STRENGTH))\n    {\n        u8 objectEventId = GetObjectEventIdByXY(x, y);\n\n        if (objectEventId != OBJECT_EVENTS_COUNT && gObjectEvents[objectEventId].graphicsId == OBJ_EVENT_GFX_PUSHABLE_BOULDER)\n        {\n            x = gObjectEvents[objectEventId].currentCoords.x;\n            y = gObjectEvents[objectEventId].currentCoords.y;\n            MoveCoords(direction, &x, &y);\n            if (GetCollisionAtCoords(&gObjectEvents[objectEventId], x, y, direction) == COLLISION_NONE\n             && MetatileBehavior_IsNonAnimDoor(MapGridGetMetatileBehaviorAt(x, y)) == FALSE)\n            {\n                StartStrengthAnim(objectEventId, direction);\n                return TRUE;\n            }\n        }\n    }\n    return FALSE;",
  },
  "TrySpinPlayerForWarp": {
    returnType: "static u8",
    params: "struct ObjectEvent *object, s16 *delayTimer",
    callsTo: ["GetFaceDirectionMovementAction","ObjectEventCheckHeldMovementStatus","ObjectEventForceSetHeldMovement"],
    lineCount: 7,
    bodyC: "if (*delayTimer < 8 && ++(*delayTimer) < 8)\n        return object->facingDirection;\n\n    if (!ObjectEventCheckHeldMovementStatus(object))\n        return object->facingDirection;\n\n    ObjectEventForceSetHeldMovement(object, GetFaceDirectionMovementAction(sSpinDirections[object->facingDirection]));\n    *delayTimer = 0;\n    return sSpinDirections[object->facingDirection];",
  },
  "UpdatePlayerAvatarTransitionState": {
    returnType: "void",
    params: "void",
    callsTo: ["PlayerAnimIsMultiFrameStationary","PlayerAnimIsMultiFrameStationaryAndStateNotTurning","PlayerCheckIfAnimFinishedOrInactive","PlayerIsAnimActive"],
    lineCount: 14,
    bodyC: "gPlayerAvatar.tileTransitionState = T_NOT_MOVING;\n    if (PlayerIsAnimActive())\n    {\n        if (!PlayerCheckIfAnimFinishedOrInactive())\n        {\n            if (!PlayerAnimIsMultiFrameStationary())\n                gPlayerAvatar.tileTransitionState = T_TILE_TRANSITION;\n        }\n        else\n        {\n            if (!PlayerAnimIsMultiFrameStationaryAndStateNotTurning())\n                gPlayerAvatar.tileTransitionState = T_TILE_CENTER;\n        }\n    }",
  },
  "_": {
    returnType: "static const struct __attribute_",
    params: "(packed)",
    lineCount: 2,
    bodyC: "u8 graphicsId;\n    u8 playerFlag;",
  },
  "npc_clear_strange_bits": {
    returnType: "static void",
    params: "struct ObjectEvent *objEvent",
    lineCount: 4,
    bodyC: "objEvent->inanimate = FALSE;\n    objEvent->disableAnim = FALSE;\n    objEvent->facingDirectionLocked = FALSE;\n    gPlayerAvatar.flags &= ~PLAYER_AVATAR_FLAG_DASH;",
  },
  "player_get_pos_including_state_based_drift": {
    returnType: "u8",
    params: "s16 *x, s16 *y",
    lineCount: 28,
    bodyC: "struct ObjectEvent *object = &gObjectEvents[gPlayerAvatar.objectEventId];\n\n    if (object->heldMovementActive && !object->heldMovementFinished && !gSprites[object->spriteId].data[2])\n    {\n        *x = object->currentCoords.x;\n        *y = object->currentCoords.y;\n\n        switch (object->movementActionId)\n        {\n        case MOVEMENT_ACTION_WALK_NORMAL_DOWN:\n        case MOVEMENT_ACTION_PLAYER_RUN_DOWN:\n            (*y)++;\n            return TRUE;\n        case MOVEMENT_ACTION_WALK_NORMAL_UP:\n        case MOVEMENT_ACTION_PLAYER_RUN_UP:\n            (*y)--;\n            return TRUE;\n        case MOVEMENT_ACTION_WALK_NORMAL_LEFT:\n        case MOVEMENT_ACTION_PLAYER_RUN_LEFT:\n            (*x)--;\n            return TRUE;\n        case MOVEMENT_ACTION_WALK_NORMAL_RIGHT:\n        case MOVEMENT_ACTION_PLAYER_RUN_RIGHT:\n            (*x)++;\n            return TRUE;\n        }\n    }\n\n    *x = -1;\n    *y = -1;\n    return FALSE;",
  },
  "unref_GetRivalAvatarGenderByGraphicsId": {
    returnType: "u8",
    params: "u8 gfxId",
    lineCount: 14,
    bodyC: "switch (gfxId)\n    {\n    case OBJ_EVENT_GFX_RIVAL_MAY_NORMAL:\n    case OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE:\n    case OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE:\n    case OBJ_EVENT_GFX_RIVAL_MAY_SURFING:\n    case OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE:\n    case OBJ_EVENT_GFX_MAY_UNDERWATER:\n    case OBJ_EVENT_GFX_MAY_FISHING:\n    case OBJ_EVENT_GFX_MAY_WATERING:\n        return FEMALE;\n    default:\n        return MALE;\n    }",
  },
} as const;
