// AUTO-GENERATED from src/link_rfu_2.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 145

export const ENGINE_FUNCTIONS = {
  "AreAllPlayersFinishedReceiving": {
    returnType: "static bool8",
    params: "void",
    lineCount: 7,
    bodyC: "s32 i;\n\n    for (i = 0; i < gRfu.playerCount; i++)\n    {\n        if (gRfu.recvBlock[i].receiving != RECV_STATE_FINISHED || gRfu.blockReceived[i] != TRUE)\n            return FALSE;\n    }\n    return TRUE;",
  },
  "AreAllPlayersReadyToReceive": {
    returnType: "static bool8",
    params: "void",
    lineCount: 7,
    bodyC: "s32 i;\n\n    for (i = 0; i < MAX_RFU_PLAYERS; i++)\n    {\n        if (gRfu.recvBlock[i].receiving != RECV_STATE_READY)\n            return FALSE;\n    }\n    return TRUE;",
  },
  "CB2_RfuIdle": {
    returnType: "static void",
    params: "void",
    callsTo: ["AnimateSprites","BuildOamBuffer","RunTasks","UpdatePaletteFade"],
    lineCount: 4,
    bodyC: "RunTasks();\n    AnimateSprites();\n    BuildOamBuffer();\n    UpdatePaletteFade();",
  },
  "CallRfuFunc": {
    returnType: "static void",
    params: "void",
    callsTo: ["callback"],
    lineCount: 2,
    bodyC: "if (gRfu.callback)\n        gRfu.callback();",
  },
  "CanTryReconnectParent": {
    returnType: "static bool8",
    params: "void",
    lineCount: 3,
    bodyC: "if (gRfu.state == RFUSTATE_CHILD_CONNECT_END && gRfu.parentId)\n        return TRUE;\n    return FALSE;",
  },
  "CheckForLeavingGroupMembers": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["rfu_NI_setSendData","rfu_clearSlot"],
    lineCount: 26,
    bodyC: "s32 i;\n    bool8 memberLeft = FALSE;\n    for (i = 0; i < RFU_CHILD_MAX; i++)\n    {\n        if (gRfu.partnerSendStatuses[i] < RFU_STATUS_JOIN_GROUP_OK\n         || gRfu.partnerSendStatuses[i] > RFU_STATUS_JOIN_GROUP_NO)\n        {\n            if (gRfuSlotStatusNI[i]->recv.state == SLOT_STATE_RECV_SUCCESS\n             || gRfuSlotStatusNI[i]->recv.state == SLOT_STATE_RECV_SUCCESS_AND_SENDSIDE_UNKNOWN)\n            {\n                if (gRfu.partnerRecvStatuses[i] == RFU_STATUS_LEAVE_GROUP_NOTICE)\n                {\n                    gRfu.partnerSendStatuses[i] = RFU_STATUS_LEAVE_GROUP;\n                    gRfu.partnerRecvStatuses[i] = RFU_STATUS_CHILD_LEAVE_READY;\n                    rfu_clearSlot(TYPE_NI_RECV, i);\n                    rfu_NI_setSendData(1 << i, 8, &gRfu.partnerSendStatuses[i], 1);\n                    memberLeft = TRUE;\n                }\n\n            }\n            else if (gRfuSlotStatusNI[gRfu.childSlot]->recv.state == SLOT_STATE_RECV_FAILED)\n            {\n                rfu_clearSlot(TYPE_NI_RECV, i);\n            }\n        }\n    }\n    return memberLeft;",
  },
  "ChildBuildSendCmd": {
    returnType: "static void",
    params: "u16 *sendCmd, u8 *dst",
    lineCount: 16,
    bodyC: "s32 i;\n\n    if (sendCmd[0])\n    {\n        sendCmd[0] |= (gRfu.childSendCmdId << 5);\n        gRfu.childSendCmdId = (gRfu.childSendCmdId + 1) & 7;\n        for (i = 0; i < CMD_LENGTH - 1; i++)\n        {\n            dst[2 * i + 1] = sendCmd[i] >> 8;\n            dst[2 * i + 0] = sendCmd[i];\n        }\n    }\n    else\n    {\n        for (i = 0; i < COMM_SLOT_LENGTH; i++)\n            dst[i] = 0;\n    }",
  },
  "ClearLinkRfuCallback": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "gRfu.callback = NULL;",
  },
  "ClearRecvCommands": {
    returnType: "void",
    params: "void",
    callsTo: ["CpuFill32"],
    lineCount: 1,
    bodyC: "CpuFill32(0, gRecvCmds, sizeof(gRecvCmds));",
  },
  "ClearSelectedLinkPlayerIds": {
    returnType: "static void",
    params: "u16 selected",
    lineCount: 6,
    bodyC: "s32 i;\n\n    for (i = 0; i < RFU_CHILD_MAX; i++)\n    {\n        if ((selected >> i) & 1)\n            gRfu.linkPlayerIdx[i] = 0;\n    }",
  },
  "CreateTask_ChildSearchForParent": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateTask"],
    lineCount: 1,
    bodyC: "gRfu.searchTaskId = CreateTask(Task_ChildSearchForParent, 1);",
  },
  "CreateTask_ParentSearchForChildren": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateTask"],
    lineCount: 1,
    bodyC: "gRfu.searchTaskId = CreateTask(Task_ParentSearchForChildren, 1);",
  },
  "CreateTask_RfuIdle": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateTask","FuncIsActiveTask"],
    lineCount: 2,
    bodyC: "if (!FuncIsActiveTask(Task_Idle))\n        gRfu.idleTaskId = CreateTask(Task_Idle, 0);",
  },
  "CreateTask_RfuReconnectWithParent": {
    returnType: "void",
    params: "const u8 *name, u16 trainerId",
    callsTo: ["CreateTask","StringCopy"],
    lineCount: 7,
    bodyC: "u8 taskId;\n    s16 *data;\n\n    gRfu.status = RFU_STATUS_OK;\n    taskId = CreateTask(Task_RfuReconnectWithParent, 3);\n    data = gTasks[taskId].data;\n    StringCopy((u8 *)(data), name);\n    data[8] = trainerId;",
  },
  "Debug_PrintEmpty": {
    returnType: "static void",
    params: "void",
    callsTo: ["Debug_PrintString"],
    lineCount: 3,
    bodyC: "s32 i;\n    for (i = 0; i < 20; i++)\n        Debug_PrintString(sASCII_30Spaces, 0, i);",
  },
  "Debug_PrintNum": {
    returnType: "static void",
    params: "u16 num, u8 x, u8 y, u8 numDigits",
    lineCount: 0,
    bodyC: "",
  },
  "Debug_PrintString": {
    returnType: "static void",
    params: "const void *str, u8 x, u8 y",
    lineCount: 0,
    bodyC: "",
  },
  "DestroyTask_RfuIdle": {
    returnType: "void",
    params: "void",
    callsTo: ["DestroyTask","FuncIsActiveTask"],
    lineCount: 2,
    bodyC: "if (FuncIsActiveTask(Task_Idle) == TRUE)\n        DestroyTask(gRfu.idleTaskId);",
  },
  "DisconnectNewChild": {
    returnType: "static void",
    params: "void",
    callsTo: ["SendDisconnectCommand"],
    lineCount: 2,
    bodyC: "SendDisconnectCommand(lman.acceptSlot_flag, RFU_DISCONNECT_ERROR);\n    gRfu.callback = NULL;",
  },
  "DisconnectRfu": {
    returnType: "static void",
    params: "void",
    callsTo: ["RfuShutdownAfterDisconnect","rfu_REQ_disconnect","rfu_waitREQComplete"],
    lineCount: 3,
    bodyC: "rfu_REQ_disconnect(gRfuLinkStatus->connSlotFlag | gRfuLinkStatus->linkLossSlotFlag);\n    rfu_waitREQComplete();\n    RfuShutdownAfterDisconnect();",
  },
  "GetHostRfuGameData": {
    returnType: "struct RfuGameData *",
    params: "void",
    lineCount: 1,
    bodyC: "return &gHostRfuGameData;",
  },
  "GetJoinGroupStatus": {
    returnType: "static s32",
    params: "void",
    callsTo: ["RfuSetStatus","rfu_clearSlot"],
    lineCount: 20,
    bodyC: "s32 status = RFU_STATUS_OK;\n    if (gRfu.leaveGroupStatus == RFU_STATUS_LEAVE_GROUP_NOTICE)\n    {\n        if (gRfuSlotStatusNI[gRfu.childSlot]->send.state == SLOT_STATE_SEND_SUCCESS\n         || gRfuSlotStatusNI[gRfu.childSlot]->send.state == SLOT_STATE_SEND_FAILED)\n            rfu_clearSlot(TYPE_NI_SEND, gRfu.childSlot);\n    }\n    if (gRfuSlotStatusNI[gRfu.childSlot]->recv.state == SLOT_STATE_RECV_SUCCESS\n     || gRfuSlotStatusNI[gRfu.childSlot]->recv.state == SLOT_STATE_RECV_SUCCESS_AND_SENDSIDE_UNKNOWN)\n    {\n        rfu_clearSlot(TYPE_NI_RECV, gRfu.childSlot);\n        RfuSetStatus(gRfu.childRecvStatus, 0);\n        status = gRfu.childRecvStatus;\n    }\n    else if (gRfuSlotStatusNI[gRfu.childSlot]->recv.state == SLOT_STATE_RECV_FAILED)\n    {\n        rfu_clearSlot(TYPE_NI_RECV, gRfu.childSlot);\n        status = RFU_STATUS_JOIN_GROUP_NO;\n    }\n    return status;",
  },
  "GetLinkPlayerInfoFlags": {
    returnType: "u8",
    params: "s32 playerId",
    lineCount: 4,
    bodyC: "u8 retval = PINFO_ACTIVE_FLAG;\n    retval |= (gLinkPlayers[playerId].gender << PINFO_GENDER_SHIFT);\n    retval |= (gLinkPlayers[playerId].trainerId & PINFO_TID_MASK);\n    return retval;",
  },
  "GetNewChildrenInUnionRoomChat": {
    returnType: "static u8",
    params: "s32 emptySlotMask",
    lineCount: 12,
    bodyC: "u8 ret = 0;\n    u8 i;\n\n    for (i = 0; i < RFU_CHILD_MAX; i++)\n    {\n        if ((emptySlotMask >> i) & 1)\n        {\n            struct RfuGameData *data = (void *)gRfuLinkStatus->partner[i].gname;\n            if (data->activity == (ACTIVITY_CHAT | IN_UNION_ROOM))\n                ret |= (1 << i);\n        }\n    }\n\n    return ret;",
  },
  "GetOtherPlayersInfoFlags": {
    returnType: "void",
    params: "void",
    callsTo: ["GetLinkPlayerCount","GetLinkPlayerInfoFlags"],
    lineCount: 4,
    bodyC: "struct RfuGameData *data = &gHostRfuGameData;\n    s32 i;\n\n    for (i = 1; i < GetLinkPlayerCount(); i++)\n        data->partnerInfo[i - 1] = GetLinkPlayerInfoFlags(i);",
  },
  "GetPartnerIndexByNameAndTrainerID": {
    returnType: "static u8",
    params: "const u8 *name, u16 id",
    callsTo: ["IsRfuSerialNumberValid","ReadU16","StringCompare"],
    lineCount: 15,
    bodyC: "u8 i;\n    u8 idx = 0xFF;\n\n    for (i = 0; i < RFU_CHILD_MAX; i++)\n    {\n        u16 trainerId = ReadU16(((struct RfuGameData *)gRfuLinkStatus->partner[i].gname)->compatibility.playerTrainerId);\n        if (IsRfuSerialNumberValid(gRfuLinkStatus->partner[i].serialNo)\n            && !StringCompare(name, gRfuLinkStatus->partner[i].uname)\n            && id == trainerId)\n        {\n            idx = i;\n            if (gRfuLinkStatus->partner[i].slot != 0xFF)\n                break;\n        }\n    }\n\n    return idx;",
  },
  "GetRfuRecvQueueLength": {
    returnType: "u32",
    params: "void",
    lineCount: 1,
    bodyC: "return gRfu.recvQueue.count;",
  },
  "HandleBlockSend": {
    returnType: "static void",
    params: "void",
    callsTo: ["GetMultiplayerId","RfuPrepareSendBuffer"],
    lineCount: 14,
    bodyC: "if (gSendCmd[0] == 0)\n    {\n        RfuPrepareSendBuffer(RFUCMD_SEND_BLOCK_INIT);\n        if (gRfu.parentChild == MODE_PARENT)\n        {\n            if (++gRfu.blockSendAttempts > 2)\n                gRfu.callback = SendNextBlock;\n        }\n        else\n        {\n            if ((gRecvCmds[GetMultiplayerId()][0] & RFUCMD_MASK) == RFUCMD_SEND_BLOCK_INIT)\n                gRfu.callback = SendNextBlock;\n        }\n    }",
  },
  "HandleSendFailure": {
    returnType: "static void",
    params: "u8 unused, u32 flags",
    callsTo: ["RfuSendQueue_Enqueue"],
    lineCount: 24,
    bodyC: "s32 i, j, temp;\n\n    const u8 *payload = gRfu.sendBlock.payload;\n    for (i = 0; i < gRfu.sendBlock.count; i++)\n    {\n        if (!(flags & 1))\n        {\n            sResendBlock16[0] = RFUCMD_SEND_BLOCK | i;\n            for (j = 0; j < CMD_LENGTH - 1; j++)\n            {\n                temp = j * 2;\n                sResendBlock16[j + 1] = (payload[(COMM_SLOT_LENGTH - 2) * i + temp + 1] << 8)\n                                       | payload[(COMM_SLOT_LENGTH - 2) * i + temp + 0];\n            }\n            for (j = 0; j < CMD_LENGTH - 1; j++)\n            {\n                temp = j * 2;\n                sResendBlock8[temp + 1] = sResendBlock16[j] >> 8;\n                sResendBlock8[temp + 0] = sResendBlock16[j];\n            }\n            RfuSendQueue_Enqueue(&gRfu.sendQueue, sResendBlock8);\n            gRfu.sendBlock.failedFlags |= (1 << i);\n        }\n        flags >>= 1;\n    }",
  },
  "HasTrainerLeftPartnersList": {
    returnType: "bool32",
    params: "u16 trainerId, const u8 *name",
    callsTo: ["GetPartnerIndexByNameAndTrainerID"],
    lineCount: 6,
    bodyC: "u8 idx = GetPartnerIndexByNameAndTrainerID(name, trainerId);\n    if (idx == 0xFF)\n        return TRUE;\n    if (gRfu.partnerSendStatuses[idx] == RFU_STATUS_LEAVE_GROUP)\n        return TRUE;\n    return FALSE;",
  },
  "InitChildRecvBuffers": {
    returnType: "static void",
    params: "void",
    callsTo: ["rfu_clearSlot","rfu_setRecvBuffer"],
    lineCount: 11,
    bodyC: "u8 i;\n    u8 acceptSlot = lman.acceptSlot_flag;\n    for (i = 0; i < RFU_CHILD_MAX; i++)\n    {\n        if (acceptSlot & 1)\n        {\n            rfu_setRecvBuffer(TYPE_UNI, i, gRfu.childRecvBuffer[i], sizeof(gRfu.childRecvBuffer[0]));\n            rfu_clearSlot(TYPE_UNI_SEND | TYPE_UNI_RECV, i);\n        }\n        acceptSlot >>= 1;\n    }",
  },
  "InitParentSendData": {
    returnType: "static void",
    params: "void",
    callsTo: ["Rfu_GetIndexOfNewestChild","SetLinkPlayerIdsFromSlots","rfu_UNI_setSendData"],
    lineCount: 6,
    bodyC: "u8 acceptSlot = lman.acceptSlot_flag;\n    rfu_UNI_setSendData(acceptSlot, gRfu.recvCmds, sizeof(gRfu.recvCmds));\n    gRfu.parentSendSlot = Rfu_GetIndexOfNewestChild(acceptSlot);\n    gRfu.parentSlots = acceptSlot;\n    SetLinkPlayerIdsFromSlots(acceptSlot, -1);\n    gRfu.parentChild = MODE_PARENT;",
  },
  "InitRFU": {
    returnType: "void",
    params: "void",
    callsTo: ["InitRFUAPI","rfu_REQ_stopMode","rfu_waitREQComplete"],
    lineCount: 9,
    bodyC: "IntrFunc serialIntr = gIntrTable[1];\n    IntrFunc timerIntr = gIntrTable[2];\n    InitRFUAPI();\n    rfu_REQ_stopMode();\n    rfu_waitREQComplete();\n    REG_IME = 0;\n    gIntrTable[1] = serialIntr;\n    gIntrTable[2] = timerIntr;\n    REG_IME = INTR_FLAG_VBLANK;",
  },
  "InitRFUAPI": {
    returnType: "void",
    params: "void",
    callsTo: ["ClearSavedLinkPlayers","ResetLinkRfuGFLayer","RfuSetIgnoreError","rfu_initializeAPI","rfu_setTimerInterrupt"],
    lineCount: 8,
    bodyC: "if (!rfu_initializeAPI((void *)gRfuAPIBuffer, sizeof(gRfuAPIBuffer), &gIntrTable[1], TRUE))\n    {\n        gLinkType = 0;\n        ClearSavedLinkPlayers();\n        RfuSetIgnoreError(FALSE);\n        ResetLinkRfuGFLayer();\n        rfu_setTimerInterrupt(3, &gIntrTable[2]);\n    }",
  },
  "InitializeRfuLinkManager_EnterUnionRoom": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateTask","SetHostRfuUsername","rfu_LMAN_initializeManager"],
    lineCount: 7,
    bodyC: "gRfu.parentChild = MODE_P_C_SWITCH;\n    SetHostRfuUsername();\n    rfu_LMAN_initializeManager(LinkManagerCB_UnionRoom, NULL);\n    sRfuReqConfig = sRfuReqConfigTemplate;\n    sRfuReqConfig.linkRecovery_enable = 0;\n    sRfuReqConfig.linkRecovery_period = 600;\n    gRfu.searchTaskId = CreateTask(Task_UnionRoomListen, 1);",
  },
  "InitializeRfuLinkManager_JoinGroup": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateTask_ChildSearchForParent","SetHostRfuUsername","rfu_LMAN_initializeManager"],
    lineCount: 4,
    bodyC: "gRfu.parentChild = MODE_CHILD;\n    SetHostRfuUsername();\n    rfu_LMAN_initializeManager(LinkManagerCB_Child, MSCCallback_Child);\n    CreateTask_ChildSearchForParent();",
  },
  "InitializeRfuLinkManager_LinkLeader": {
    returnType: "void",
    params: "u32 groupMax",
    callsTo: ["CreateTask_ParentSearchForChildren","SetHostRfuUsername","rfu_LMAN_initializeManager"],
    lineCount: 6,
    bodyC: "gRfu.parentChild = MODE_PARENT;\n    SetHostRfuUsername();\n    rfu_LMAN_initializeManager(LinkManagerCB_Parent, NULL);\n    sRfuReqConfig = sRfuReqConfigTemplate;\n    sRfuReqConfig.availSlot_flag = sAvailSlots[groupMax - 1];\n    CreateTask_ParentSearchForChildren();",
  },
  "IsLinkRfuTaskFinished": {
    returnType: "bool8",
    params: "void",
    lineCount: 3,
    bodyC: "if (gRfu.status == RFU_STATUS_CONNECTION_ERROR)\n        return FALSE;\n    return gRfu.callback ? FALSE : TRUE;",
  },
  "IsPartnerActivityIncompatible": {
    returnType: "static bool32",
    params: "s16 activity, struct RfuGameData *partner",
    callsTo: ["GetHostRfuGameData"],
    lineCount: 27,
    bodyC: "if (GetHostRfuGameData()->activity == (ACTIVITY_CHAT | IN_UNION_ROOM))\n    {\n         \n        if (partner->activity != (ACTIVITY_CHAT | IN_UNION_ROOM))\n            return TRUE;\n    }\n    else if (partner->activity != IN_UNION_ROOM)\n    {\n         \n        return TRUE;\n    }\n    else if (activity == (ACTIVITY_TRADE | IN_UNION_ROOM))\n    {\n         \n        struct RfuGameData *original = &gRfu.parent;\n        if (original->tradeSpecies == SPECIES_EGG)\n        {\n            if (partner->tradeSpecies == original->tradeSpecies)\n                return FALSE;\n            else\n                return TRUE;\n        }\n        else if (partner->tradeSpecies != original->tradeSpecies\n                 || partner->tradeLevel != original->tradeLevel\n                 || partner->tradeType != original->tradeType)\n        {\n            return TRUE;\n        }\n    }\n\n    return FALSE;",
  },
  "IsRfuCommunicatingWithAllChildren": {
    returnType: "bool32",
    params: "void",
    lineCount: 7,
    bodyC: "s32 i;\n    for (i = 0; i < RFU_CHILD_MAX; i++)\n    {\n         \n         \n         \n        if ((lman.acceptSlot_flag >> i) & 1 && gRfu.partnerSendStatuses[i] == RFU_STATUS_OK)\n            return FALSE;\n    }\n\n    return TRUE;",
  },
  "IsRfuRecoveringFromLinkLoss": {
    returnType: "bool8",
    params: "void",
    lineCount: 4,
    bodyC: "if (gRfu.linkLossRecoveryState == 1)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "IsRfuRecvQueueEmpty": {
    returnType: "bool32",
    params: "void",
    lineCount: 9,
    bodyC: "s32 i;\n    s32 j;\n\n    if (!gRfuLinkStatus->sendSlotUNIFlag)\n        return FALSE;\n\n    for (i = 0; i < MAX_RFU_PLAYERS; i++)\n        for (j = 0; j < CMD_LENGTH - 1; j++)\n            if (gRecvCmds[i][j] != 0)\n                return FALSE;\n\n    return TRUE;",
  },
  "IsRfuSerialNumberValid": {
    returnType: "bool32",
    params: "u32 serialNo",
    lineCount: 7,
    bodyC: "s32 i;\n    for (i = 0; sAcceptedSerialNos[i] != serialNo; i++)\n    {\n        if (sAcceptedSerialNos[i] == RFU_SERIAL_END)\n            return FALSE;\n    }\n    return TRUE;",
  },
  "IsSendingKeysToRfu": {
    returnType: "bool32",
    params: "void",
    lineCount: 1,
    bodyC: "return gRfu.callback == SendKeysToRfu;",
  },
  "IsUnionRoomListenTaskActive": {
    returnType: "bool32",
    params: "void",
    callsTo: ["FuncIsActiveTask"],
    lineCount: 1,
    bodyC: "return FuncIsActiveTask(Task_UnionRoomListen);",
  },
  "LinkLeaderReadyToExitStandby": {
    returnType: "static void",
    params: "void",
    callsTo: ["RfuPrepareSendBuffer"],
    lineCount: 5,
    bodyC: "if (gRfu.recvQueue.count == 0 && gSendCmd[0] == 0)\n    {\n        RfuPrepareSendBuffer(RFUCMD_READY_EXIT_STANDBY);\n        gRfu.callback = SendReadyExitStandbyUntilAllReady;\n    }",
  },
  "LinkManagerCB_Child": {
    returnType: "static void",
    params: "u8 msg, u8 unused1",
    callsTo: ["Debug_PrintString","RfuSetErrorParams","RfuSetStatus","rfu_setRecvBuffer"],
    lineCount: 67,
    bodyC: "switch (msg)\n    {\n    case LMAN_MSG_INITIALIZE_COMPLETED:\n        gRfu.state = RFUSTATE_CHILD_CONNECT;\n        break;\n    case LMAN_MSG_PARENT_FOUND:\n        gRfu.parentId = lman.param[0];\n        break;\n    case LMAN_MSG_SEARCH_PARENT_PERIOD_EXPIRED:\n        break;\n    case LMAN_MSG_CONNECT_PARENT_SUCCESSED:\n        gRfu.childSlot = lman.param[0];\n        break;\n    case LMAN_MSG_CONNECT_PARENT_FAILED:\n        RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, msg);\n        break;\n    case LMAN_MSG_CHILD_NAME_SEND_COMPLETED:\n        gRfu.state = RFUSTATE_CHILD_TRY_JOIN;\n        gRfu.leaveGroupStatus = RFU_STATUS_OK;\n        gRfu.childRecvStatus = RFU_STATUS_OK;\n        rfu_setRecvBuffer(TYPE_NI, gRfu.childSlot, &gRfu.childRecvStatus, sizeof(gRfu.childRecvStatus));\n        rfu_setRecvBuffer(TYPE_UNI, gRfu.childSlot, gRfu.childRecvQueue, sizeof(gRfu.childRecvQueue));\n        break;\n    case LMAN_MSG_CHILD_NAME_SEND_FAILED_AND_DISCONNECTED:\n        RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, msg);\n        break;\n    case LMAN_MSG_LINK_LOSS_DETECTED_AND_DISCONNECTED:\n        gRfu.linkLossRecoveryState = 2;\n        if (gRfu.childRecvStatus == RFU_STATUS_JOIN_GROUP_NO)\n            break;\n    case LMAN_MSG_LINK_RECOVERY_FAILED_AND_DISCONNECTED:\n        if (gRfu.linkLossRecoveryState != 2)\n            gRfu.linkLossRecoveryState = 4;\n        if (gRfu.childRecvStatus != RFU_STATUS_LEAVE_GROUP)\n            RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, msg);\n        Debug_PrintString(sASCII_LinkLossDisconnect, 5, 5);\n        if (gReceivedRemoteLinkPlayers == 1)\n            RfuSetErrorParams(msg);\n        break;\n    case LMAN_MSG_LINK_LOSS_DETECTED_AND_START_RECOVERY:\n        gRfu.linkLossRecoveryState = 1;\n        Debug_PrintString(sASCII_LinkLossRecoveryNow, 5, 5);\n        break;\n    case LMAN_MSG_LINK_RECOVERY_SUCCESSED:\n        gRfu.linkLossRecoveryState = 3;\n        gRfu.linkRecovered = TRUE;\n        break;\n    case 0x34:  \n        break;\n    case LMAN_MSG_RFU_POWER_DOWN:\n    case LMAN_MSG_MANAGER_STOPPED:\n    case LMAN_MSG_MANAGER_FORCED_STOPPED_AND_RFU_RESET:\n        break;\n    case LMAN_MSG_LMAN_API_ERROR_RETURN:\n        RfuSetStatus(RFU_STATUS_FATAL_ERROR, msg);\n        RfuSetErrorParams(msg);\n        gRfu.isShuttingDown = TRUE;\n        break;\n    case LMAN_MSG_REQ_API_ERROR:\n    case LMAN_MSG_WATCH_DOG_TIMER_ERROR:\n    case LMAN_MSG_CLOCK_SLAVE_MS_CHANGE_ERROR_BY_DMA:\n    case LMAN_MSG_RFU_FATAL_ERROR:\n        RfuSetStatus(RFU_STATUS_FATAL_ERROR, msg);\n        RfuSetErrorParams(msg);\n        gRfu.parentFinished = TRUE;\n        break;\n    }",
  },
  "LinkManagerCB_Parent": {
    returnType: "static void",
    params: "u8 msg, u8 paramCount",
    callsTo: ["GetHostRfuGameData","ParentResetChildRecvMetadata","RfuSetErrorParams","RfuSetStatus","StartDisconnectNewChild","rfu_REQ_disconnect","rfu_setRecvBuffer","rfu_waitREQComplete"],
    lineCount: 84,
    bodyC: "u8 i;\n    u8 disconnectFlag = 0;\n    switch (msg)\n    {\n    case LMAN_MSG_INITIALIZE_COMPLETED:\n        gRfu.state = RFUSTATE_PARENT_CONNECT;\n        break;\n    case LMAN_MSG_NEW_CHILD_CONNECT_DETECTED:\n        break;\n    case LMAN_MSG_NEW_CHILD_CONNECT_ACCEPTED:\n        ParentResetChildRecvMetadata(lman.param[0]);\n        for (i = 0; i < RFU_CHILD_MAX; i++)\n        {\n            if ((lman.param[0] >> i) & 1)\n            {\n                struct RfuGameData *data = (void *)gRfuLinkStatus->partner[i].gname;\n                if (data->activity == GetHostRfuGameData()->activity)\n                {\n                    gRfu.partnerSendStatuses[i] = RFU_STATUS_OK;\n                    gRfu.partnerRecvStatuses[i] = RFU_STATUS_OK;\n                    rfu_setRecvBuffer(TYPE_NI, i, &gRfu.partnerRecvStatuses[i], sizeof(gRfu.partnerRecvStatuses[0]));\n                }\n                else\n                {\n                    disconnectFlag |= (1 << i);\n                }\n            }\n        }\n        if (disconnectFlag)\n        {\n            rfu_REQ_disconnect(disconnectFlag);\n            rfu_waitREQComplete();\n        }\n        break;\n    case LMAN_MSG_NEW_CHILD_CONNECT_REJECTED:\n        break;\n    case LMAN_MSG_SEARCH_CHILD_PERIOD_EXPIRED:\n        break;\n    case LMAN_MSG_END_WAIT_CHILD_NAME:\n        if (gRfu.acceptSlot_flag != lman.acceptSlot_flag)\n        {\n            rfu_REQ_disconnect(gRfu.acceptSlot_flag ^ lman.acceptSlot_flag);\n            rfu_waitREQComplete();\n        }\n        gRfu.state = RFUSTATE_PARENT_FINALIZE_START;\n        break;\n    case LMAN_MSG_LINK_LOSS_DETECTED_AND_START_RECOVERY:\n        gRfu.linkLossRecoveryState = 1;\n        break;\n    case LMAN_MSG_LINK_RECOVERY_SUCCESSED:\n        gRfu.linkLossRecoveryState = 3;\n        break;\n    case LMAN_MSG_LINK_LOSS_DETECTED_AND_DISCONNECTED:\n    case LMAN_MSG_LINK_RECOVERY_FAILED_AND_DISCONNECTED:\n        gRfu.linkLossRecoveryState = 4;\n        gRfu.parentSlots &= ~lman.param[0];\n        if (gReceivedRemoteLinkPlayers == 1)\n        {\n            if (gRfu.parentSlots == 0)\n                RfuSetErrorParams(msg);\n            else\n                StartDisconnectNewChild();\n        }\n        RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, msg);\n        break;\n    case 0x34:  \n    case LMAN_MSG_RFU_POWER_DOWN:\n    case LMAN_MSG_MANAGER_STOPPED:\n    case LMAN_MSG_MANAGER_FORCED_STOPPED_AND_RFU_RESET:\n        break;\n    case LMAN_MSG_LMAN_API_ERROR_RETURN:\n        RfuSetStatus(RFU_STATUS_FATAL_ERROR, msg);\n        RfuSetErrorParams(msg);\n        gRfu.isShuttingDown = TRUE;\n        break;\n    case LMAN_MSG_REQ_API_ERROR:\n    case LMAN_MSG_WATCH_DOG_TIMER_ERROR:\n    case LMAN_MSG_CLOCK_SLAVE_MS_CHANGE_ERROR_BY_DMA:\n    case LMAN_MSG_RFU_FATAL_ERROR:\n        RfuSetErrorParams(msg);\n        RfuSetStatus(RFU_STATUS_FATAL_ERROR, msg);\n        gRfu.parentFinished = TRUE;\n        break;\n    }",
  },
  "LinkManagerCB_UnionRoom": {
    returnType: "static void",
    params: "u8 msg, u8 paramCount",
    callsTo: ["CreateTask","FuncIsActiveTask","GetHostRfuGameData","GetNewChildrenInUnionRoomChat","ParentResetChildRecvMetadata","RfuSetErrorParams","RfuSetStatus","Rfu_GetIndexOfNewestChild","StartDisconnectNewChild","rfu_LMAN_stopManager","rfu_REQ_disconnect","rfu_setRecvBuffer","rfu_waitREQComplete"],
    lineCount: 140,
    bodyC: "u8 acceptSlot;\n\n    switch (msg)\n    {\n    case LMAN_MSG_INITIALIZE_COMPLETED:\n        gRfu.state = RFUSTATE_UR_CONNECT;\n        break;\n    case LMAN_MSG_NEW_CHILD_CONNECT_DETECTED:\n        RfuSetStatus(RFU_STATUS_NEW_CHILD_DETECTED, 0);\n        break;\n    case LMAN_MSG_NEW_CHILD_CONNECT_ACCEPTED:\n        if (GetHostRfuGameData()->activity == (ACTIVITY_CHAT | IN_UNION_ROOM) && !gRfu.stopNewConnections)\n        {\n            u8 newChildren = GetNewChildrenInUnionRoomChat(lman.param[0]);\n            if (newChildren != 0)\n            {\n                acceptSlot = 1 << Rfu_GetIndexOfNewestChild(newChildren);\n                if (gRfu.newChildQueue == 0 && !gRfu.playerExchangeActive)\n                {\n                    gRfu.nextChildBits = acceptSlot;\n                    gRfu.newChildQueue |= (acceptSlot ^ newChildren);\n                    gRfu.playerExchangeActive = TRUE;\n                }\n                else\n                {\n                    gRfu.newChildQueue |= newChildren;\n                }\n            }\n            if (newChildren != lman.param[0])\n            {\n                gRfu.disconnectSlots |= (newChildren ^ lman.param[0]);\n                gRfu.disconnectMode = RFU_DISCONNECT_NORMAL;\n            }\n        }\n        else if (GetHostRfuGameData()->activity == (ACTIVITY_PLYRTALK | IN_UNION_ROOM))\n        {\n            rfu_REQ_disconnect(lman.acceptSlot_flag);\n            rfu_waitREQComplete();\n        }\n        ParentResetChildRecvMetadata(lman.param[0]);\n        break;\n    case LMAN_MSG_NEW_CHILD_CONNECT_REJECTED:\n        break;\n    case LMAN_MSG_SEARCH_CHILD_PERIOD_EXPIRED:\n        break;\n    case LMAN_MSG_END_WAIT_CHILD_NAME:\n        if (GetHostRfuGameData()->activity != (ACTIVITY_CHAT | IN_UNION_ROOM) && lman.acceptCount > 1)\n        {\n            acceptSlot = 1 << Rfu_GetIndexOfNewestChild(lman.param[0]);\n            rfu_REQ_disconnect(lman.acceptSlot_flag ^ acceptSlot);\n            rfu_waitREQComplete();\n        }\n        if (gRfu.state == RFUSTATE_UR_STOP_MANAGER_END)\n            gRfu.state = RFUSTATE_UR_FINALIZE;\n        break;\n        break;\n    case LMAN_MSG_PARENT_FOUND:\n        gRfu.parentId = lman.param[0];\n        break;\n    case LMAN_MSG_SEARCH_PARENT_PERIOD_EXPIRED:\n        break;\n    case LMAN_MSG_CONNECT_PARENT_SUCCESSED:\n        gRfu.childSlot = lman.param[0];\n        break;\n    case LMAN_MSG_CONNECT_PARENT_FAILED:\n        gRfu.state = RFUSTATE_UR_CONNECT_END;\n        if (gRfu.connectParentFailures < 2)\n        {\n            gRfu.connectParentFailures++;\n            CreateTask(Task_TryConnectToUnionRoomParent, 2);\n        }\n        else\n        {\n            RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, msg);\n        }\n        break;\n    case LMAN_MSG_CHILD_NAME_SEND_COMPLETED:\n        gRfu.state = RFUSTATE_UR_PLAYER_EXCHANGE;\n        RfuSetStatus(RFU_STATUS_CHILD_SEND_COMPLETE, 0);\n        rfu_setRecvBuffer(TYPE_UNI, gRfu.childSlot, gRfu.childRecvQueue, sizeof(gRfu.childRecvQueue));\n        break;\n    case LMAN_MSG_CHILD_NAME_SEND_FAILED_AND_DISCONNECTED:\n        RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, msg);\n        break;\n    case LMAN_MSG_LINK_LOSS_DETECTED_AND_START_RECOVERY:\n        if (lman.acceptSlot_flag & lman.param[0])\n            gRfu.linkLossRecoveryState = 1;\n        break;\n    case LMAN_MSG_LINK_RECOVERY_SUCCESSED:\n        gRfu.linkLossRecoveryState = 3;\n        if (gRfuLinkStatus->parentChild == MODE_CHILD)\n            gRfu.linkRecovered = TRUE;\n        break;\n    case LMAN_MSG_LINK_LOSS_DETECTED_AND_DISCONNECTED:\n        gRfu.linkLossRecoveryState = 2;\n    case LMAN_MSG_LINK_RECOVERY_FAILED_AND_DISCONNECTED:\n        if (gRfu.linkLossRecoveryState != 2)\n            gRfu.linkLossRecoveryState = 4;\n        if (gRfu.parentChild == MODE_PARENT)\n        {\n            if (gReceivedRemoteLinkPlayers == 1)\n            {\n                gRfu.parentSlots &= ~(lman.param[0]);\n                if (gRfu.parentSlots == 0)\n                    RfuSetErrorParams(msg);\n                else\n                    StartDisconnectNewChild();\n            }\n        }\n        else if (gRfu.disconnectMode != RFU_DISCONNECT_NORMAL && gReceivedRemoteLinkPlayers == 1)\n        {\n            RfuSetErrorParams(msg);\n            rfu_LMAN_stopManager(FALSE);\n        }\n\n        if (gRfuLinkStatus->parentChild == MODE_NEUTRAL\n            && !lman.pcswitch_flag\n            && FuncIsActiveTask(Task_UnionRoomListen) == TRUE)\n            gRfu.state = RFUSTATE_UR_CONNECT;\n\n        RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, msg);\n        break;\n    case LMAN_MSG_LINK_DISCONNECTED_BY_USER:\n        gRfu.disconnectSlots = 0;\n        break;\n    case LMAN_MSG_RFU_POWER_DOWN:\n    case LMAN_MSG_MANAGER_STOPPED:\n    case LMAN_MSG_MANAGER_FORCED_STOPPED_AND_RFU_RESET:\n        break;\n    case LMAN_MSG_LMAN_API_ERROR_RETURN:\n        RfuSetStatus(RFU_STATUS_FATAL_ERROR, msg);\n        RfuSetErrorParams(msg);\n        gRfu.isShuttingDown = TRUE;\n        break;\n    case LMAN_MSG_REQ_API_ERROR:\n    case LMAN_MSG_WATCH_DOG_TIMER_ERROR:\n    case LMAN_MSG_CLOCK_SLAVE_MS_CHANGE_ERROR_BY_DMA:\n    case LMAN_MSG_RFU_FATAL_ERROR:\n        RfuSetErrorParams(msg);\n        RfuSetStatus(RFU_STATUS_FATAL_ERROR, msg);\n        gRfu.parentFinished = FALSE;\n        break;\n    }",
  },
  "LinkRfu_CreateConnectionAsParent": {
    returnType: "void",
    params: "void",
    callsTo: ["rfu_LMAN_establishConnection"],
    lineCount: 1,
    bodyC: "rfu_LMAN_establishConnection(MODE_PARENT, 0, 240, (u16 *)sAcceptedSerialNos);",
  },
  "LinkRfu_FatalError": {
    returnType: "void",
    params: "void",
    callsTo: ["rfu_LMAN_requestChangeAgbClockMaster"],
    lineCount: 3,
    bodyC: "rfu_LMAN_requestChangeAgbClockMaster();\n    gRfu.disconnectMode = RFU_DISCONNECT_ERROR;\n    gRfu.disconnectSlots = gRfuLinkStatus->connSlotFlag | gRfuLinkStatus->linkLossSlotFlag;",
  },
  "LinkRfu_Shutdown": {
    returnType: "void",
    params: "void",
    callsTo: ["ARRAY_COUNT","DestroyTask","FindTaskIdByFunc","FuncIsActiveTask","ResetLinkRfuGFLayer","rfu_LMAN_powerDownRFU"],
    lineCount: 31,
    bodyC: "u8 i;\n\n    rfu_LMAN_powerDownRFU();\n    if (gRfu.parentChild == MODE_PARENT)\n    {\n         \n        if (FuncIsActiveTask(Task_ParentSearchForChildren) == TRUE)\n        {\n            DestroyTask(gRfu.searchTaskId);\n            ResetLinkRfuGFLayer();\n        }\n    }\n    else if (gRfu.parentChild == MODE_CHILD)\n    {\n         \n        if (FuncIsActiveTask(Task_ChildSearchForParent) == TRUE)\n        {\n            DestroyTask(gRfu.searchTaskId);\n            ResetLinkRfuGFLayer();\n        }\n    }\n    else if (gRfu.parentChild == MODE_P_C_SWITCH)\n    {\n         \n        if (FuncIsActiveTask(Task_UnionRoomListen) == TRUE)\n        {\n            DestroyTask(gRfu.searchTaskId);\n            ResetLinkRfuGFLayer();\n        }\n    }\n\n     \n    for (i = 0; i < ARRAY_COUNT(sShutdownTasks); i++)\n    {\n        if (FuncIsActiveTask(sShutdownTasks[i]) == TRUE)\n            DestroyTask(FindTaskIdByFunc(sShutdownTasks[i]));\n    }",
  },
  "LinkRfu_StopManagerAndFinalizeSlots": {
    returnType: "void",
    params: "void",
    lineCount: 2,
    bodyC: "gRfu.state = RFUSTATE_STOP_MANAGER;\n    gRfu.acceptSlot_flag = lman.acceptSlot_flag;",
  },
  "LinkRfu_StopManagerBeforeEnteringChat": {
    returnType: "void",
    params: "void",
    callsTo: ["rfu_LMAN_stopManager"],
    lineCount: 1,
    bodyC: "rfu_LMAN_stopManager(FALSE);",
  },
  "LmanAcceptSlotFlagIsNotZero": {
    returnType: "bool8",
    params: "void",
    lineCount: 3,
    bodyC: "if (lman.acceptSlot_flag)\n        return TRUE;\n    return FALSE;",
  },
  "LoadLinkPlayerIds": {
    returnType: "static u8",
    params: "const u8 *ids",
    lineCount: 6,
    bodyC: "u8 i;\n    if (gRfu.parentChild == MODE_PARENT)\n        return FALSE;\n    for (i = 0; i < RFU_CHILD_MAX; i++)\n        gRfu.linkPlayerIdx[i] = ids[i];\n\n    return ids[gRfu.childSlot];",
  },
  "MSCCallback_Child": {
    returnType: "static void",
    params: "u16 REQ_commandID",
    callsTo: ["RfuRecvQueue_Enqueue","UpdateBackupQueue","rfu_LMAN_REQ_sendData","rfu_REQ_recvData","rfu_UNI_clearRecvNewDataFlag","rfu_UNI_readySendData","rfu_waitREQComplete"],
    lineCount: 15,
    bodyC: "s32 i;\n\n    for (i = 0; i < COMM_SLOT_LENGTH; i++)\n        gRfu.childSendBuffer[i] = 0;\n\n    rfu_REQ_recvData();\n    rfu_waitREQComplete();\n    if (gRfuSlotStatusUNI[gRfu.childSlot]->recv.newDataFlag)\n    {\n        gRfu.childSendCount++;\n        RfuRecvQueue_Enqueue(&gRfu.recvQueue, gRfu.childRecvQueue);\n        sRfuDebug.recvCount++;\n        UpdateBackupQueue();\n        rfu_UNI_readySendData(gRfu.childSlot);\n        rfu_UNI_clearRecvNewDataFlag(gRfu.childSlot);\n    }\n    rfu_LMAN_REQ_sendData(TRUE);",
  },
  "MSCCallback_Parent": {
    returnType: "static void",
    params: "u16 REQ_commandID",
    lineCount: 1,
    bodyC: "gRfu.parentFinished = TRUE;",
  },
  "MoveSendCmdToRecv": {
    returnType: "static void",
    params: "void",
    lineCount: 5,
    bodyC: "s32 i;\n    for (i = 0; i < CMD_LENGTH - 1; i++)\n        gRecvCmds[0][i] = gSendCmd[i];\n\n    for (i = 0; i < CMD_LENGTH - 1; i++)\n        gSendCmd[i] = 0;",
  },
  "ParentResetChildRecvMetadata": {
    returnType: "static void",
    params: "s32 slot",
    lineCount: 9,
    bodyC: "s32 i;\n\n    for (i = 0; i < RFU_CHILD_MAX; i++)\n    {\n        if ((slot >> i) & 1)\n        {\n            gRfu.numChildRecvErrors[i] = 0;\n            gRfu.childRecvIds[i] = 0xFF;\n        }\n    }",
  },
  "ReadAllPlayerRecvCmds": {
    returnType: "static void",
    params: "void",
    callsTo: ["CpuFill16"],
    lineCount: 11,
    bodyC: "s32 i, j;\n\n    for (i = 0; i < MAX_RFU_PLAYERS; i++)\n    {\n        struct RfuManager *rfu = &gRfu;\n        for (j = 0; j < CMD_LENGTH - 1; j++)\n        {\n            rfu->recvCmds[i][j][1] = gRecvCmds[i][j] >> 8;\n            rfu->recvCmds[i][j][0] = gRecvCmds[i][j];\n        }\n    }\n    CpuFill16(0, gRecvCmds, sizeof gRecvCmds);",
  },
  "ReadU16": {
    returnType: "static u16",
    params: "const void *ptr",
    lineCount: 2,
    bodyC: "const u8 *ptr_ = ptr;\n    return (ptr_[1] << 8) | (ptr_[0]);",
  },
  "ReceiveRfuLinkPlayers": {
    returnType: "static void",
    params: "const struct SioInfo *sioInfo",
    callsTo: ["ConvertLinkPlayerName"],
    lineCount: 9,
    bodyC: "s32 i;\n    gRfu.playerCount = sioInfo->playerCount;\n    for (i = 0; i < RFU_CHILD_MAX; i++)\n        gRfu.linkPlayerIdx[i] = sioInfo->linkPlayerIdx[i];\n    for (i = 0; i < MAX_RFU_PLAYERS; i++)\n    {\n        gLinkPlayers[i] = sioInfo->linkPlayers[i];\n        ConvertLinkPlayerName(gLinkPlayers + i);\n    }",
  },
  "RequestDisconnectSlotByTrainerNameAndId": {
    returnType: "void",
    params: "const u8 *name, u16 id",
    callsTo: ["GetPartnerIndexByNameAndTrainerID","RfuReqDisconnectSlot"],
    lineCount: 3,
    bodyC: "u8 index = GetPartnerIndexByNameAndTrainerID(name, id);\n    if (index != 0xFF)\n        RfuReqDisconnectSlot(1 << index);",
  },
  "ResetHostRfuGameData": {
    returnType: "void",
    params: "void",
    callsTo: ["InitHostRfuGameData","memset"],
    lineCount: 2,
    bodyC: "memset(&gHostRfuGameData, 0, RFU_GAME_NAME_LENGTH);\n    InitHostRfuGameData(&gHostRfuGameData, ACTIVITY_NONE, FALSE, 0);",
  },
  "ResetLinkRfuGFLayer": {
    returnType: "void",
    params: "void",
    callsTo: ["CpuFill16","ResetSendDataManager","RfuRecvQueue_Reset","RfuSendQueue_Reset"],
    lineCount: 15,
    bodyC: "s32 i;\n    u8 errorState = gRfu.errorState;\n    CpuFill16(0, &gRfu, sizeof(gRfu));\n    gRfu.errorState = errorState;\n    gRfu.parentChild = 0xFF;\n    if (gRfu.errorState != RFU_ERROR_STATE_IGNORE)\n        gRfu.errorState = RFU_ERROR_STATE_NONE;\n    for (i = 0; i < MAX_RFU_PLAYERS; i++)\n        ResetSendDataManager(&gRfu.recvBlock[i]);\n    ResetSendDataManager(&gRfu.sendBlock);\n    RfuRecvQueue_Reset(&gRfu.recvQueue);\n    RfuSendQueue_Reset(&gRfu.sendQueue);\n    CpuFill16(0, gSendCmd, sizeof gSendCmd);\n    CpuFill16(0, gRecvCmds, sizeof gRecvCmds);\n    CpuFill16(0, gLinkPlayers, sizeof gLinkPlayers);",
  },
  "ResetSendDataManager": {
    returnType: "static void",
    params: "struct RfuBlockSend *data",
    lineCount: 7,
    bodyC: "data->next = 0;\n    data->count = 0;\n    data->payload = NULL;\n    data->receivedFlags = 0;\n    data->sending = FALSE;\n    data->owner = 0;\n    data->receiving = RECV_STATE_READY;",
  },
  "RfuCheckErrorStatus": {
    returnType: "static void",
    params: "void",
    callsTo: ["CloseLink","RfuGetStatus","RfuSetErrorParams","RfuSetStatus","SetLinkErrorBuffer","SetMainCallback2","rfu_LMAN_requestChangeAgbClockMaster"],
    lineCount: 17,
    bodyC: "if (gRfu.errorState == RFU_ERROR_STATE_OCCURRED && lman.childClockSlave_flag == 0)\n    {\n        if (gMain.callback2 == CB2_MysteryGiftEReader || lman.init_param->mboot_flag)\n            gWirelessCommType = 2;\n        SetMainCallback2(CB2_LinkError);\n        gMain.savedCallback = CB2_LinkError;\n        SetLinkErrorBuffer((gRfu.errorInfo << 16) | (gRfu.errorParam0 << 8) | gRfu.errorParam1, gRfu.recvQueue.count, gRfu.sendQueue.count, RfuGetStatus() == RFU_STATUS_CONNECTION_ERROR);\n        gRfu.errorState = RFU_ERROR_STATE_PROCESSED;\n        CloseLink();\n    }\n    else if (gRfu.sendQueue.full == TRUE || gRfu.recvQueue.full == TRUE)\n    {\n        if (lman.childClockSlave_flag)\n            rfu_LMAN_requestChangeAgbClockMaster();\n        RfuSetStatus(RFU_STATUS_FATAL_ERROR, F_RFU_ERROR_5 | F_RFU_ERROR_6 | F_RFU_ERROR_7);\n        RfuSetErrorParams(F_RFU_ERROR_5 | F_RFU_ERROR_6 | F_RFU_ERROR_7);\n    }",
  },
  "RfuGetStatus": {
    returnType: "u8",
    params: "void",
    lineCount: 1,
    bodyC: "return gRfu.status;",
  },
  "RfuHandleReceiveCommand": {
    returnType: "static void",
    params: "u8 unused",
    callsTo: ["ClearSelectedLinkPlayerIds","GetHostRfuGameData","LoadLinkPlayerIds","RfuPrepareSendBuffer","Rfu_InitBlockSend","Rfu_SetBlockReceivedFlag","ValidateAndReceivePokemonSioInfo","rfu_LMAN_requestChangeAgbClockMaster"],
    lineCount: 102,
    bodyC: "u16 i;\n    u16 j;\n\n    for (i = 0; i < MAX_RFU_PLAYERS; i++)\n    {\n        switch (gRecvCmds[i][0] & RFUCMD_MASK)\n        {\n        case RFUCMD_SEND_PLAYER_IDS_NEW:\n            if (gRfu.parentChild == MODE_CHILD && gReceivedRemoteLinkPlayers)\n                return;\n             \n        case RFUCMD_SEND_PLAYER_IDS:\n            if (gRfuLinkStatus->parentChild == MODE_CHILD)\n            {\n                gRfu.playerCount = gRecvCmds[i][1];\n                gRfu.multiplayerId = LoadLinkPlayerIds((u8 *)(gRecvCmds[i] + 2));\n            }\n            break;\n        case RFUCMD_SEND_BLOCK_INIT:\n            if (gRfu.recvBlock[i].receiving == RECV_STATE_READY)\n            {\n                gRfu.recvBlock[i].next = 0;\n                gRfu.recvBlock[i].count = gRecvCmds[i][1];\n                gRfu.recvBlock[i].owner = gRecvCmds[i][2];\n                gRfu.recvBlock[i].receivedFlags = 0;\n                gRfu.recvBlock[i].receiving = RECV_STATE_RECEIVING;\n                gRfu.blockReceived[i] = FALSE;\n            }\n            break;\n        case RFUCMD_SEND_BLOCK:\n            if (gRfu.recvBlock[i].receiving == RECV_STATE_RECEIVING)\n            {\n                gRfu.recvBlock[i].next = gRecvCmds[i][0] & 0xff;\n                gRfu.recvBlock[i].receivedFlags |= (1 << gRfu.recvBlock[i].next);\n                for (j = 0; j < 6; j++)\n                    gBlockRecvBuffer[i][gRfu.recvBlock[i].next * 6 + j] = gRecvCmds[i][j + 1];\n                if (gRfu.recvBlock[i].receivedFlags == sAllBlocksReceived[gRfu.recvBlock[i].count])\n                {\n                    gRfu.recvBlock[i].receiving = RECV_STATE_FINISHED;\n                    Rfu_SetBlockReceivedFlag(i);\n                    if (GetHostRfuGameData()->activity == (ACTIVITY_CHAT | IN_UNION_ROOM) && gReceivedRemoteLinkPlayers && gRfu.parentChild == MODE_CHILD)\n                        ValidateAndReceivePokemonSioInfo(gBlockRecvBuffer);\n                }\n            }\n            break;\n        case RFUCMD_SEND_BLOCK_REQ:\n            Rfu_InitBlockSend(sBlockRequests[gRecvCmds[i][1]].address, (u16)sBlockRequests[gRecvCmds[i][1]].size);\n            break;\n        case RFUCMD_READY_CLOSE_LINK:\n            gRfu.readyCloseLink[i] = TRUE;\n            break;\n        case RFUCMD_READY_EXIT_STANDBY:\n            if (gRfu.allReadyNum == gRecvCmds[i][1])\n                gRfu.readyExitStandby[i] = TRUE;\n            break;\n        case RFUCMD_DISCONNECT:\n            if (gRfu.parentChild == MODE_CHILD)\n            {\n                 \n                if (gReceivedRemoteLinkPlayers)\n                {\n                    if (gRecvCmds[i][1] & gRfuLinkStatus->connSlotFlag)\n                    {\n                        gReceivedRemoteLinkPlayers = 0;\n                        rfu_LMAN_requestChangeAgbClockMaster();\n                        gRfu.disconnectMode = gRecvCmds[i][2];\n                    }\n                    gRfu.playerCount = gRecvCmds[i][3];\n                    ClearSelectedLinkPlayerIds(gRecvCmds[i][1]);\n                }\n            }\n            else\n            {\n                 \n                RfuPrepareSendBuffer(RFUCMD_DISCONNECT_PARENT);\n                gSendCmd[1] = gRecvCmds[i][1];\n                gSendCmd[2] = gRecvCmds[i][2];\n                gSendCmd[3] = gRecvCmds[i][3];\n            }\n            break;\n        case RFUCMD_DISCONNECT_PARENT:\n            if (gRfu.parentChild == MODE_PARENT)\n            {\n                gRfu.disconnectSlots |= gRecvCmds[i][1];\n                gRfu.disconnectMode = gRecvCmds[i][2];\n                ClearSelectedLinkPlayerIds(gRecvCmds[i][1]);\n            }\n            break;\n        case RFUCMD_BLENDER_SEND_KEYS:\n        case RFUCMD_SEND_HELD_KEYS:\n            gLinkPartnersHeldKeys[i] = gRecvCmds[i][1];\n            break;\n        }\n        if (gRfu.parentChild == MODE_PARENT && gRfu.numBlocksReceived[i])\n        {\n            if (gRfu.numBlocksReceived[i] == 4)\n            {\n                gRfu.blockReceived[i] = TRUE;\n                gRfu.numBlocksReceived[i] = 0;\n            }\n            else\n            {\n                gRfu.numBlocksReceived[i]++;\n            }\n        }\n    }",
  },
  "RfuHasErrored": {
    returnType: "bool32",
    params: "void",
    callsTo: ["RfuGetStatus"],
    lineCount: 5,
    bodyC: "u32 status = RfuGetStatus() - 1;\n    if (status < RFU_STATUS_CONNECTION_ERROR)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "RfuMain1": {
    returnType: "bool32",
    params: "void",
    callsTo: ["Random2","RfuMain1_Child","RfuMain1_Parent","RfuMain1_UnionRoom","rfu_LMAN_manager_entity"],
    lineCount: 19,
    bodyC: "bool32 retval = FALSE;\n    gRfu.parentId = 0;\n    rfu_LMAN_manager_entity(Random2());\n    if (!gRfu.isShuttingDown)\n    {\n        switch (gRfu.parentChild)\n        {\n        case MODE_PARENT:\n            RfuMain1_Parent();\n            break;\n        case MODE_CHILD:\n            retval = RfuMain1_Child();\n            break;\n        case MODE_P_C_SWITCH:\n            RfuMain1_UnionRoom();\n            break;\n        }\n    }\n    return retval;",
  },
  "RfuMain1_Child": {
    returnType: "static bool32",
    params: "void",
    callsTo: ["CallRfuFunc","ChildBuildSendCmd","IsRfuRecvQueueEmpty","RfuGetStatus","RfuHandleReceiveCommand","RfuRecvQueue_Dequeue","RfuSendQueue_Enqueue","RfuSetErrorParams","RfuSetStatus","rfu_REQ_disconnect","rfu_clearAllSlot","rfu_waitREQComplete"],
    lineCount: 41,
    bodyC: "u8 i;\n    u8 j;\n    u8 recv[MAX_RFU_PLAYERS * (2 * (CMD_LENGTH - 1))];\n    u8 send[2 * (CMD_LENGTH - 1)];\n    u8 status;\n\n    RfuRecvQueue_Dequeue(&gRfu.recvQueue, recv);\n    for (i = 0; i < MAX_RFU_PLAYERS; i++)\n    {\n        for (j = 0; j < CMD_LENGTH - 1; j++)\n            gRecvCmds[i][j] = (recv[i * COMM_SLOT_LENGTH + (j * 2) + 1] << 8)\n                             | recv[i * COMM_SLOT_LENGTH + (j * 2) + 0];\n    }\n    RfuHandleReceiveCommand(0);\n    if (lman.childClockSlave_flag == 0 && gRfu.disconnectMode != RFU_DISCONNECT_NONE)\n    {\n        rfu_REQ_disconnect(gRfuLinkStatus->connSlotFlag | gRfuLinkStatus->linkLossSlotFlag);\n        rfu_waitREQComplete();\n        status = RfuGetStatus();\n        if (status != RFU_STATUS_FATAL_ERROR && status != RFU_STATUS_JOIN_GROUP_NO && status != RFU_STATUS_LEAVE_GROUP)\n            RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, F_RFU_ERROR_5 | F_RFU_ERROR_8);\n        rfu_clearAllSlot();\n        gReceivedRemoteLinkPlayers = FALSE;\n        gRfu.callback = NULL;\n        if (gRfu.disconnectMode == RFU_DISCONNECT_ERROR)\n        {\n            RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, F_RFU_ERROR_5 | F_RFU_ERROR_8);\n            RfuSetErrorParams(F_RFU_ERROR_5 | F_RFU_ERROR_8);\n        }\n        lman.state = lman.next_state = 0;\n        gRfu.disconnectMode = RFU_DISCONNECT_NONE;\n    }\n    if (gRfu.childSendCount)\n    {\n        gRfu.childSendCount--;\n        CallRfuFunc();\n        ChildBuildSendCmd(gSendCmd, send);\n        RfuSendQueue_Enqueue(&gRfu.sendQueue, send);\n        for (i = 0; i < CMD_LENGTH - 1; i++)\n            gSendCmd[i] = 0;\n    }\n    return IsRfuRecvQueueEmpty();",
  },
  "RfuMain1_Parent": {
    returnType: "static bool32",
    params: "void",
    callsTo: ["LinkRfu_Shutdown","ReadAllPlayerRecvCmds","RfuReqDisconnectSlot","RfuSetErrorParams","RfuSetStatus","rfu_LMAN_REQ_sendData","rfu_REQ_PARENT_resumeRetransmitAndChange","rfu_REQ_recvData","rfu_UNI_readySendData","rfu_waitREQComplete"],
    lineCount: 42,
    bodyC: "if (gRfu.state < RFUSTATE_FINALIZED)\n    {\n        rfu_REQ_recvData();\n        rfu_waitREQComplete();\n        rfu_LMAN_REQ_sendData(FALSE);\n    }\n    else\n    {\n        gRfu.parentFinished = FALSE;\n        if ((gRfu.parentSlots & gRfuLinkStatus->connSlotFlag) == gRfu.parentSlots && (gRfu.parentSlots & gRfuLinkStatus->connSlotFlag))\n        {\n            if (!gRfu.parentMain2Failed)\n            {\n                if (gRfu.disconnectSlots)\n                {\n                    RfuReqDisconnectSlot(gRfu.disconnectSlots);\n                    gRfu.disconnectSlots = 0;\n                    if (gRfu.disconnectMode == RFU_DISCONNECT_ERROR)\n                    {\n                        RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, F_RFU_ERROR_8);\n                        RfuSetErrorParams(F_RFU_ERROR_8);\n                        return FALSE;\n                    }\n                    if (!lman.acceptSlot_flag)\n                    {\n                        LinkRfu_Shutdown();\n                        gReceivedRemoteLinkPlayers = 0;\n                        return FALSE;\n                    }\n                }\n                ReadAllPlayerRecvCmds();\n                rfu_UNI_readySendData(gRfu.parentSendSlot);\n                rfu_LMAN_REQ_sendData(TRUE);\n            }\n            else\n            {\n                rfu_REQ_PARENT_resumeRetransmitAndChange();\n            }\n            gRfu.runParentMain2 = TRUE;\n        }\n    }\n    return FALSE;",
  },
  "RfuMain1_UnionRoom": {
    returnType: "static void",
    params: "void",
    callsTo: ["rfu_LMAN_REQ_sendData","rfu_REQ_recvData","rfu_waitREQComplete"],
    lineCount: 6,
    bodyC: "if (lman.parent_child == MODE_PARENT)\n    {\n        rfu_REQ_recvData();\n        rfu_waitREQComplete();\n        rfu_LMAN_REQ_sendData(FALSE);\n    }",
  },
  "RfuMain2": {
    returnType: "bool32",
    params: "void",
    callsTo: ["RfuCheckErrorStatus","RfuMain2_Parent"],
    lineCount: 8,
    bodyC: "bool32 retval = FALSE;\n    if (!gRfu.isShuttingDown)\n    {\n        if (gRfu.parentChild == MODE_PARENT)\n            retval = RfuMain2_Parent();\n        RfuCheckErrorStatus();\n    }\n    return retval;",
  },
  "RfuMain2_Parent": {
    returnType: "static bool32",
    params: "void",
    callsTo: ["CallRfuFunc","CreateTask","MoveSendCmdToRecv","RfuHandleReceiveCommand","RfuSetErrorParams","Rfu_GetIndexOfNewestChild","SetLinkPlayerIdsFromSlots","rfu_REQ_recvData","rfu_UNI_clearRecvNewDataFlag","rfu_UNI_setSendData","rfu_clearSlot","rfu_setRecvBuffer","rfu_waitREQComplete"],
    lineCount: 79,
    bodyC: "u16 i;\n    u16 flags;\n    u8 r0;\n    u16 j;\n    bool8 failed;\n\n    if (gRfu.state >= RFUSTATE_FINALIZED && gRfu.runParentMain2 == TRUE)\n    {\n        rfu_waitREQComplete();\n        while (gRfu.parentFinished == FALSE)\n        {\n            if (gRfu.errorState != RFU_ERROR_STATE_NONE)\n                return FALSE;\n        }\n        rfu_REQ_recvData();\n        rfu_waitREQComplete();\n        if ((lman.parentAck_flag & gRfu.parentSlots) == gRfu.parentSlots)\n        {\n            gRfu.parentMain2Failed = FALSE;\n            sRfuDebug.recvCount++;\n            flags = lman.acceptSlot_flag;\n            for (i = 0; i < RFU_CHILD_MAX; i++)\n            {\n                if (flags & 1)\n                {\n                    if (gRfu.childRecvBuffer[i][1])\n                    {\n                        if (gRfu.childRecvIds[i] != 0xFF && (gRfu.childRecvBuffer[i][0] >> 5) != ((gRfu.childRecvIds[i] + 1) & 7))\n                        {\n                            if (++gRfu.numChildRecvErrors[i] > 4)\n                                RfuSetErrorParams(F_RFU_ERROR_8 | F_RFU_ERROR_1);\n                        }\n                        else\n                        {\n                            gRfu.childRecvIds[i] = gRfu.childRecvBuffer[i][0] / 32;\n                            gRfu.numChildRecvErrors[i] = 0;\n                            gRfu.childRecvBuffer[i][0] &= 0x1f;\n                            r0 = gRfu.linkPlayerIdx[i];\n                            for (j = 0; j < CMD_LENGTH - 1; j++)\n                            {\n                                gRecvCmds[r0][j] = (gRfu.childRecvBuffer[i][(j << 1) + 1] << 8) | gRfu.childRecvBuffer[i][(j << 1) + 0];\n                                gRfu.childRecvBuffer[i][(j << 1) + 1] = 0;\n                                gRfu.childRecvBuffer[i][(j << 1) + 0] = 0;\n                            }\n                        }\n                    }\n                    rfu_UNI_clearRecvNewDataFlag(i);\n                }\n                flags >>= 1;\n            }\n            MoveSendCmdToRecv();\n            RfuHandleReceiveCommand(0);\n            CallRfuFunc();\n            if (gRfu.nextChildBits && !gRfu.stopNewConnections)\n            {\n                sRfuDebug.unkFlag = FALSE;\n                rfu_clearSlot(TYPE_UNI_SEND | TYPE_UNI_RECV, gRfu.parentSendSlot);\n                for (i = 0; i < RFU_CHILD_MAX; i++)\n                {\n                    if ((gRfu.nextChildBits >> i) & 1)\n                        rfu_setRecvBuffer(TYPE_UNI, i, gRfu.childRecvBuffer[i], sizeof(gRfu.childRecvBuffer[0]));\n                }\n                SetLinkPlayerIdsFromSlots(gRfu.parentSlots, gRfu.parentSlots | gRfu.nextChildBits);\n                gRfu.incomingChild = gRfu.nextChildBits;\n                gRfu.parentSlots |= gRfu.nextChildBits;\n                gRfu.nextChildBits = 0;\n                rfu_UNI_setSendData(gRfu.parentSlots, gRfu.recvCmds, sizeof(gRfu.recvCmds));\n                gRfu.parentSendSlot = Rfu_GetIndexOfNewestChild(gRfu.parentSlots);\n                CreateTask(Task_PlayerExchangeUpdate, 0);\n            }\n        }\n        else\n        {\n            gRfu.parentMain2Failed = TRUE;\n            gRfu.runParentMain2 = FALSE;\n        }\n        gRfu.runParentMain2 = FALSE;\n    }\n    failed = gRfu.parentMain2Failed;\n    return gRfuLinkStatus->sendSlotUNIFlag ? failed & 1 : FALSE;",
  },
  "RfuPrepareSendBuffer": {
    returnType: "static void",
    params: "u16 command",
    callsTo: ["AreAllPlayersReadyToReceive"],
    lineCount: 42,
    bodyC: "u8 i;\n    u8 *buff;\n    u8 tmp;\n\n    gSendCmd[0] = command;\n    switch (command)\n    {\n    case RFUCMD_SEND_BLOCK_INIT:\n        gSendCmd[1] = gRfu.sendBlock.count;\n        gSendCmd[2] = gRfu.sendBlock.owner + 0x80;\n        break;\n    case RFUCMD_SEND_BLOCK_REQ:\n        if (AreAllPlayersReadyToReceive())\n            gSendCmd[1] = gRfu.blockRequestType;\n        break;\n    case RFUCMD_SEND_PLAYER_IDS:\n    case RFUCMD_SEND_PLAYER_IDS_NEW:\n        tmp = gRfu.parentSlots ^ gRfu.disconnectSlots;\n        gRfu.playerCount = sPlayerBitsToCount[tmp] + 1;\n        gSendCmd[1] = gRfu.playerCount;\n        buff = (u8 *)&gSendCmd[2];\n        for (i = 0; i < RFU_CHILD_MAX; i++)\n            buff[i] = gRfu.linkPlayerIdx[i];\n        break;\n    case RFUCMD_READY_EXIT_STANDBY:\n    case RFUCMD_READY_CLOSE_LINK:\n        gSendCmd[1] = gRfu.allReadyNum;\n        break;\n    case RFUCMD_BLENDER_SEND_KEYS:\n        gSendCmd[0] = command;\n        gSendCmd[1] = gMain.heldKeys;\n        break;\n    case RFUCMD_SEND_PACKET:\n        for (i = 0; i < RFU_PACKET_SIZE; i++)\n            gSendCmd[1 + i] = gRfu.packet[i];\n        break;\n    case RFUCMD_SEND_HELD_KEYS:\n        gSendCmd[1] = gHeldKeyCodeToSend;\n        break;\n    case RFUCMD_DISCONNECT_PARENT:\n    case RFUCMD_DISCONNECT:\n        break;\n    }",
  },
  "RfuReqDisconnectSlot": {
    returnType: "static void",
    params: "u32 slot",
    callsTo: ["Rfu_GetIndexOfNewestChild","rfu_REQ_disconnect","rfu_UNI_setSendData","rfu_clearSlot","rfu_waitREQComplete"],
    lineCount: 6,
    bodyC: "rfu_REQ_disconnect(slot);\n    rfu_waitREQComplete();\n    gRfu.parentSlots &= ~slot;\n    rfu_clearSlot(1, gRfu.parentSendSlot);\n    rfu_UNI_setSendData(gRfu.parentSlots, gRfu.recvCmds, sizeof(gRfu.recvCmds));\n    gRfu.parentSendSlot = Rfu_GetIndexOfNewestChild(gRfu.parentSlots);",
  },
  "RfuSetErrorParams": {
    returnType: "void",
    params: "u32 errorInfo",
    lineCount: 7,
    bodyC: "if (gRfu.errorState == RFU_ERROR_STATE_NONE)\n    {\n        gRfu.errorParam0 = lman.param[0];\n        gRfu.errorParam1 = lman.param[1];\n        gRfu.errorInfo = errorInfo;\n        gRfu.errorState = RFU_ERROR_STATE_OCCURRED;\n    }",
  },
  "RfuSetIgnoreError": {
    returnType: "void",
    params: "bool32 enable",
    lineCount: 4,
    bodyC: "if (!enable)\n        gRfu.errorState = RFU_ERROR_STATE_NONE;\n    else\n        gRfu.errorState = RFU_ERROR_STATE_IGNORE;",
  },
  "RfuSetNormalDisconnectMode": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "gRfu.disconnectMode = RFU_DISCONNECT_NORMAL;",
  },
  "RfuSetStatus": {
    returnType: "void",
    params: "u8 status, u16 errorInfo",
    lineCount: 2,
    bodyC: "gRfu.status = status;\n    gRfu.errorInfo = errorInfo;",
  },
  "RfuShutdownAfterDisconnect": {
    returnType: "static void",
    params: "void",
    callsTo: ["rfu_LMAN_powerDownRFU","rfu_clearAllSlot"],
    lineCount: 5,
    bodyC: "rfu_clearAllSlot();\n    rfu_LMAN_powerDownRFU();\n    gReceivedRemoteLinkPlayers = 0;\n    gRfu.isShuttingDown = TRUE;\n    gRfu.callback = NULL;",
  },
  "RfuTryDisconnectLeavingChildren": {
    returnType: "bool32",
    params: "void",
    callsTo: ["rfu_REQ_disconnect","rfu_waitREQComplete"],
    lineCount: 22,
    bodyC: "u8 childrenLeaving = 0;\n    s32 i;\n\n     \n    for (i = 0; i < RFU_CHILD_MAX; i++)\n    {\n        if (gRfu.partnerRecvStatuses[i] == RFU_STATUS_CHILD_LEAVE)\n        {\n            childrenLeaving |= (1 << i);\n            gRfu.partnerRecvStatuses[i] = RFU_STATUS_OK;\n        }\n    }\n\n     \n    if (childrenLeaving)\n    {\n        rfu_REQ_disconnect(childrenLeaving);\n        rfu_waitREQComplete();\n    }\n\n     \n    for (i = 0; i < RFU_CHILD_MAX; i++)\n    {\n        if (gRfu.partnerRecvStatuses[i] == RFU_STATUS_CHILD_LEAVE_READY\n         || gRfu.partnerRecvStatuses[i] == RFU_STATUS_CHILD_LEAVE)\n            return TRUE;\n    }\n    return FALSE;",
  },
  "RfuVSync": {
    returnType: "void",
    params: "void",
    callsTo: ["rfu_LMAN_syncVBlank"],
    lineCount: 1,
    bodyC: "rfu_LMAN_syncVBlank();",
  },
  "Rfu_BerryBlenderSendHeldKeys": {
    returnType: "static void",
    params: "void",
    callsTo: ["GetBlenderArrowPosition","GetMultiplayerId","RfuPrepareSendBuffer"],
    lineCount: 4,
    bodyC: "RfuPrepareSendBuffer(RFUCMD_BLENDER_SEND_KEYS);\n    if (GetMultiplayerId() == 0)\n        gSendCmd[BLENDER_COMM_ARROW_POS] = GetBlenderArrowPosition();\n    gBerryBlenderKeySendAttempts++;",
  },
  "Rfu_DisconnectPlayerById": {
    returnType: "void",
    params: "u32 playerIdx",
    callsTo: ["SendDisconnectCommand"],
    lineCount: 12,
    bodyC: "if (playerIdx != 0)\n    {\n        s32 i;\n        u8 toDisconnect = 0;\n\n        for (i = 0; i < RFU_CHILD_MAX; i++)\n        {\n            if (gRfu.linkPlayerIdx[i] == playerIdx && (gRfu.parentSlots >> i) & 1)\n                toDisconnect |= 1 << i;\n        }\n        if (toDisconnect)\n            SendDisconnectCommand(toDisconnect, RFU_DISCONNECT_NORMAL);\n    }",
  },
  "Rfu_GetBlockReceivedStatus": {
    returnType: "u8",
    params: "void",
    lineCount: 8,
    bodyC: "u8 flags = 0;\n    s32 i;\n\n    for (i = 0; i < MAX_RFU_PLAYERS; i++)\n    {\n        if (gRfu.recvBlock[i].receiving == RECV_STATE_FINISHED && gRfu.blockReceived[i] == TRUE)\n            flags |= (1 << i);\n    }\n    return flags;",
  },
  "Rfu_GetIndexOfNewestChild": {
    returnType: "s32",
    params: "u8 bits",
    lineCount: 1,
    bodyC: "return sPlayerBitsToNewChildIdx[bits];",
  },
  "Rfu_GetLinkPlayerCount": {
    returnType: "u8",
    params: "void",
    lineCount: 1,
    bodyC: "return gRfu.playerCount;",
  },
  "Rfu_GetMultiplayerId": {
    returnType: "u8",
    params: "void",
    lineCount: 3,
    bodyC: "if (gRfu.parentChild == MODE_PARENT)\n        return 0;\n    return gRfu.multiplayerId;",
  },
  "Rfu_InitBlockSend": {
    returnType: "bool32",
    params: "const u8 *src, size_t size",
    callsTo: ["GetMultiplayerId","RfuPrepareSendBuffer","memcpy"],
    lineCount: 29,
    bodyC: "bool8 r4;\n    if (gRfu.callback != NULL)\n        return FALSE;\n    if (gSendCmd[0] != 0)\n        return FALSE;\n    if (gRfu.sendBlock.sending)\n    {\n        sRfuDebug.blockSendTime++;\n        return FALSE;\n    }\n    r4 = (size % 12) != 0;\n    gRfu.sendBlock.owner = GetMultiplayerId();\n    gRfu.sendBlock.sending = TRUE;\n    gRfu.sendBlock.count = (size / 12) + r4;\n    gRfu.sendBlock.next = 0;\n    if (size > BLOCK_BUFFER_SIZE)\n    {\n        gRfu.sendBlock.payload = src;\n    }\n    else\n    {\n        if (src != gBlockSendBuffer)\n            memcpy(gBlockSendBuffer, src, size);\n        gRfu.sendBlock.payload = gBlockSendBuffer;\n    }\n    RfuPrepareSendBuffer(RFUCMD_SEND_BLOCK_INIT);\n    gRfu.callback = HandleBlockSend;\n    gRfu.blockSendAttempts = 0;\n    return TRUE;",
  },
  "Rfu_IsMaster": {
    returnType: "bool8",
    params: "void",
    lineCount: 1,
    bodyC: "return gRfu.parentChild;",
  },
  "Rfu_IsPlayerExchangeActive": {
    returnType: "bool32",
    params: "void",
    lineCount: 1,
    bodyC: "return gRfu.playerExchangeActive;",
  },
  "Rfu_LinkStandby": {
    returnType: "static void",
    params: "void",
    callsTo: ["GetLinkPlayerCount","GetMultiplayerId","RfuPrepareSendBuffer"],
    lineCount: 27,
    bodyC: "u8 i;\n    u8 playerCount;\n\n    if (GetMultiplayerId() != 0)\n    {\n         \n        if (gRfu.recvQueue.count == 0 && gSendCmd[0] == 0)\n        {\n            RfuPrepareSendBuffer(RFUCMD_READY_EXIT_STANDBY);\n            gRfu.callback = SendReadyExitStandbyUntilAllReady;\n        }\n    }\n    else\n    {\n         \n        playerCount = GetLinkPlayerCount();\n        for (i = 1; i < playerCount; i++)\n        {\n            if (!gRfu.readyExitStandby[i])\n                break;\n        }\n        if (i == playerCount)\n        {\n            if (gRfu.recvQueue.count == 0 && gSendCmd[0] == 0)\n            {\n                RfuPrepareSendBuffer(RFUCMD_READY_EXIT_STANDBY);\n                gRfu.callback = LinkLeaderReadyToExitStandby;\n            }\n        }\n    }",
  },
  "Rfu_ResetBlockReceivedFlag": {
    returnType: "void",
    params: "u8 linkPlayerId",
    lineCount: 2,
    bodyC: "gRfu.blockReceived[linkPlayerId] = FALSE;\n    gRfu.recvBlock[linkPlayerId].receiving = RECV_STATE_READY;",
  },
  "Rfu_SendBlockRequest": {
    returnType: "bool8",
    params: "u8 type",
    callsTo: ["RfuPrepareSendBuffer"],
    lineCount: 3,
    bodyC: "gRfu.blockRequestType = type;\n    RfuPrepareSendBuffer(RFUCMD_SEND_BLOCK_REQ);\n    return TRUE;",
  },
  "Rfu_SendPacket": {
    returnType: "void",
    params: "void *data",
    callsTo: ["RfuHasErrored","RfuPrepareSendBuffer","memcpy"],
    lineCount: 5,
    bodyC: "if (gSendCmd[0] == 0 && !RfuHasErrored())\n    {\n        memcpy(gRfu.packet, data, sizeof(gRfu.packet));\n        RfuPrepareSendBuffer(RFUCMD_SEND_PACKET);\n    }",
  },
  "Rfu_SetBerryBlenderLinkCallback": {
    returnType: "void",
    params: "void",
    lineCount: 2,
    bodyC: "if (gRfu.callback == NULL)\n        gRfu.callback = Rfu_BerryBlenderSendHeldKeys;",
  },
  "Rfu_SetBlockReceivedFlag": {
    returnType: "void",
    params: "u8 linkPlayerId",
    lineCount: 4,
    bodyC: "if (gRfu.parentChild == MODE_PARENT && linkPlayerId)\n        gRfu.numBlocksReceived[linkPlayerId] = 1;\n    else\n        gRfu.blockReceived[linkPlayerId] = TRUE;",
  },
  "Rfu_SetCloseLinkCallback": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateTask","FuncIsActiveTask"],
    lineCount: 2,
    bodyC: "if (!FuncIsActiveTask(Task_TryReadyCloseLink))\n        CreateTask(Task_TryReadyCloseLink, 5);",
  },
  "Rfu_SetLinkRecovery": {
    returnType: "u8",
    params: "bool32 enable",
    callsTo: ["rfu_LMAN_setLinkRecovery"],
    lineCount: 4,
    bodyC: "if (enable == FALSE)\n        return rfu_LMAN_setLinkRecovery(0, 0);\n    rfu_LMAN_setLinkRecovery(1, 600);\n    return 0;",
  },
  "Rfu_SetLinkStandbyCallback": {
    returnType: "void",
    params: "void",
    lineCount: 5,
    bodyC: "if (gRfu.callback == NULL)\n    {\n        gRfu.callback = Rfu_LinkStandby;\n        gRfu.resendExitStandbyTimer = 0;\n    }",
  },
  "Rfu_StopPartnerSearch": {
    returnType: "void",
    params: "void",
    callsTo: ["rfu_LMAN_stopManager"],
    lineCount: 2,
    bodyC: "gRfu.stopNewConnections = TRUE;\n    rfu_LMAN_stopManager(FALSE);",
  },
  "SendDisconnectCommand": {
    returnType: "static void",
    params: "u32 playersToDisconnect, u32 disconnectMode",
    callsTo: ["CreateTask","FindTaskIdByFunc"],
    lineCount: 11,
    bodyC: "u8 taskId = FindTaskIdByFunc(Task_SendDisconnectCommand);\n    if (taskId == TASK_NONE)\n    {\n        taskId = CreateTask(Task_SendDisconnectCommand, 5);\n        gTasks[taskId].tDisconnectPlayers = playersToDisconnect;\n    }\n    else\n    {\n         \n        gTasks[taskId].tDisconnectPlayers |= playersToDisconnect;\n    }\n\n    gTasks[taskId].tDisconnectMode = disconnectMode;",
  },
  "SendKeysToRfu": {
    returnType: "static void",
    params: "void",
    callsTo: ["RfuPrepareSendBuffer"],
    lineCount: 8,
    bodyC: "if (gReceivedRemoteLinkPlayers\n        && gHeldKeyCodeToSend != LINK_KEY_CODE_NULL\n        && gLinkTransferringData != TRUE)\n    {\n        sHeldKeyCount++;\n        gHeldKeyCodeToSend |= (sHeldKeyCount << 8);\n        RfuPrepareSendBuffer(RFUCMD_SEND_HELD_KEYS);\n    }",
  },
  "SendLastBlock": {
    returnType: "static void",
    params: "void",
    callsTo: ["GetMultiplayerId","HandleSendFailure"],
    lineCount: 25,
    bodyC: "const u8 *src = gRfu.sendBlock.payload;\n    u8 mpId = GetMultiplayerId();\n    s32 i;\n    if (gRfu.parentChild == MODE_CHILD)\n    {\n        gSendCmd[0] = RFUCMD_SEND_BLOCK | (gRfu.sendBlock.count - 1);\n        for (i = 0; i < CMD_LENGTH - 1; i++)\n            gSendCmd[i + 1] = (src[(i << 1) + (gRfu.sendBlock.count - 1) * 12 + 1] << 8) | src[(i << 1) + (gRfu.sendBlock.count - 1) * 12 + 0];\n        if ((u8)gRecvCmds[mpId][0] == gRfu.sendBlock.count - 1)\n        {\n            if (gRfu.recvBlock[mpId].receivedFlags != sAllBlocksReceived[gRfu.recvBlock[mpId].count])\n            {\n                HandleSendFailure(mpId, gRfu.recvBlock[mpId].receivedFlags);\n                sRfuDebug.blockSendFailures++;\n            }\n            else\n            {\n                gRfu.callback = NULL;\n            }\n        }\n    }\n    else\n    {\n        gRfu.callback = NULL;\n    }",
  },
  "SendLeaveGroupNotice": {
    returnType: "void",
    params: "void",
    callsTo: ["rfu_NI_setSendData","rfu_clearSlot"],
    lineCount: 3,
    bodyC: "gRfu.leaveGroupStatus = RFU_STATUS_LEAVE_GROUP_NOTICE;\n    rfu_clearSlot(TYPE_NI_SEND, gRfu.childSlot);\n    rfu_NI_setSendData(1 << gRfu.childSlot, 8, &gRfu.leaveGroupStatus, 1);",
  },
  "SendNextBlock": {
    returnType: "static void",
    params: "void",
    lineCount: 11,
    bodyC: "s32 i;\n    const u8 *src = gRfu.sendBlock.payload;\n    gSendCmd[0] = RFUCMD_SEND_BLOCK | gRfu.sendBlock.next;\n    for (i = 0; i < CMD_LENGTH - 1; i++)\n        gSendCmd[i + 1] = (src[(i << 1) + gRfu.sendBlock.next * 12 + 1] << 8) | src[(i << 1) + gRfu.sendBlock.next * 12 + 0];\n    gRfu.sendBlock.next++;\n    if (gRfu.sendBlock.count <= gRfu.sendBlock.next)\n    {\n        gRfu.sendBlock.sending = FALSE;\n        gRfu.callback = SendLastBlock;\n    }",
  },
  "SendReadyCloseLink": {
    returnType: "static void",
    params: "void",
    callsTo: ["RfuPrepareSendBuffer"],
    lineCount: 5,
    bodyC: "if (gSendCmd[0] == 0 && !gRfu.playerExchangeActive)\n    {\n        RfuPrepareSendBuffer(RFUCMD_READY_CLOSE_LINK);\n        gRfu.callback = WaitAllReadyToCloseLink;\n    }",
  },
  "SendReadyExitStandbyUntilAllReady": {
    returnType: "static void",
    params: "void",
    callsTo: ["GetLinkPlayerCount","GetMultiplayerId","RfuPrepareSendBuffer"],
    lineCount: 24,
    bodyC: "u8 playerCount;\n    u8 i;\n\n    if (GetMultiplayerId() != 0)\n    {\n        if (gRfu.recvQueue.count == 0 && gRfu.resendExitStandbyTimer > 60)\n        {\n            RfuPrepareSendBuffer(RFUCMD_READY_EXIT_STANDBY);\n            gRfu.resendExitStandbyTimer = 0;\n        }\n    }\n    playerCount = GetLinkPlayerCount();\n    for (i = 0; i < playerCount; i++)\n    {\n        if (!gRfu.readyExitStandby[i])\n            break;\n    }\n    if (i == playerCount)\n    {\n        for (i = 0; i < MAX_RFU_PLAYERS; i++)\n            gRfu.readyExitStandby[i] = FALSE;\n        gRfu.allReadyNum++;\n        gRfu.callback = NULL;\n    }\n    gRfu.resendExitStandbyTimer++;",
  },
  "SendRfuStatusToPartner": {
    returnType: "void",
    params: "u8 status, u16 trainerId, const u8 *name",
    callsTo: ["GetPartnerIndexByNameAndTrainerID","rfu_NI_setSendData","rfu_clearSlot"],
    lineCount: 4,
    bodyC: "u8 idx = GetPartnerIndexByNameAndTrainerID(name, trainerId);\n    gRfu.partnerSendStatuses[idx] = status;\n    rfu_clearSlot(TYPE_NI_SEND, idx);\n    rfu_NI_setSendData(1 << idx, 8, &gRfu.partnerSendStatuses[idx], 1);",
  },
  "SetHostRfuGameData": {
    returnType: "void",
    params: "u8 activity, u32 partnerInfo, bool32 startedActivity",
    callsTo: ["InitHostRfuGameData"],
    lineCount: 1,
    bodyC: "InitHostRfuGameData(&gHostRfuGameData, activity, startedActivity, partnerInfo);",
  },
  "SetHostRfuUsername": {
    returnType: "static void",
    params: "void",
    callsTo: ["StringCopy"],
    lineCount: 1,
    bodyC: "StringCopy(gHostRfuUsername, gSaveBlock2Ptr->playerName);",
  },
  "SetHostRfuWonderFlags": {
    returnType: "void",
    params: "bool32 hasNews, bool32 hasCard",
    lineCount: 2,
    bodyC: "gHostRfuGameData.compatibility.hasNews = hasNews;\n    gHostRfuGameData.compatibility.hasCard = hasCard;",
  },
  "SetLinkPlayerIdsFromSlots": {
    returnType: "static void",
    params: "s32 baseSlots, s32 addSlots",
    lineCount: 35,
    bodyC: "u8 i;\n    u8 baseId = 1;\n    s32 baseSlotsCopy = baseSlots;\n    s32 newId = 0;\n    if (addSlots == -1)\n    {\n         \n        for (i = 0; i < RFU_CHILD_MAX; baseSlots >>= 1, i++)\n        {\n            if (baseSlots & 1)\n            {\n                gRfu.linkPlayerIdx[i] = baseId;\n                baseId++;\n            }\n        }\n    }\n    else\n    {\n         \n        for (i = 0; i < RFU_CHILD_MAX; baseSlotsCopy >>= 1, i++)\n        {\n            if (!(baseSlotsCopy & 1))\n                gRfu.linkPlayerIdx[i] = 0;\n        }\n\n         \n        for (baseId = RFU_CHILD_MAX; baseId != 0; baseId--)\n        {\n            for (i = 0; i < RFU_CHILD_MAX && gRfu.linkPlayerIdx[i] != baseId; i++)\n                ;\n            if (i == RFU_CHILD_MAX)\n                newId = baseId;\n        }\n\n         \n        for (addSlots &= ~baseSlots, i = 0; i < RFU_CHILD_MAX; addSlots >>= 1, i++)\n        {\n            if (addSlots & 1)\n                gRfu.linkPlayerIdx[i] = newId++;\n        }\n    }",
  },
  "SetTradeBoardRegisteredMonInfo": {
    returnType: "void",
    params: "u32 type, u32 species, u32 level",
    lineCount: 3,
    bodyC: "gHostRfuGameData.tradeType = type;\n    gHostRfuGameData.tradeSpecies = species;\n    gHostRfuGameData.tradeLevel = level;",
  },
  "SetUnionRoomChatPlayerData": {
    returnType: "void",
    params: "u32 numPlayers",
    callsTo: ["GetHostRfuGameData","UpdateGameData_SetActivity"],
    lineCount: 23,
    bodyC: "s32 i;\n    u32 numConnectedChildren;\n    u32 partnerInfo;\n    s32 slots;\n\n    if (GetHostRfuGameData()->activity == (ACTIVITY_CHAT | IN_UNION_ROOM))\n    {\n        numConnectedChildren = 0;\n        partnerInfo = 0;\n        slots = gRfu.parentSlots ^ gRfu.disconnectSlots;\n        for (i = 0; i < RFU_CHILD_MAX; i++)\n        {\n            if ((slots >> i) & 1)\n            {\n                 \n                 \n                partnerInfo |= ((PINFO_ACTIVE_FLAG\n                             | ((gLinkPlayers[gRfu.linkPlayerIdx[i]].gender & 1) << PINFO_GENDER_SHIFT)\n                             | (gLinkPlayers[gRfu.linkPlayerIdx[i]].trainerId & PINFO_TID_MASK)) << (numConnectedChildren * 8));\n                numConnectedChildren++;\n                if (numConnectedChildren == numPlayers - 1)\n                    break;\n            }\n        }\n        UpdateGameData_SetActivity(ACTIVITY_CHAT | IN_UNION_ROOM, partnerInfo, FALSE);\n    }",
  },
  "StartDisconnectNewChild": {
    returnType: "static void",
    params: "void",
    lineCount: 1,
    bodyC: "gRfu.callback = DisconnectNewChild;",
  },
  "StartSendingKeysToRfu": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "gRfu.callback = SendKeysToRfu;",
  },
  "StopUnionRoomLinkManager": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "gRfu.state = RFUSTATE_UR_STOP_MANAGER;",
  },
  "Task_ChildSearchForParent": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateTask","Debug_PrintEmpty","DestroyTask","GetJoinGroupStatus","rfu_LMAN_establishConnection","rfu_LMAN_initializeRFU","rfu_LMAN_requestChangeAgbClockMaster","rfu_UNI_setSendData","rfu_clearSlot","rfu_setRecvBuffer"],
    lineCount: 50,
    bodyC: "switch (gRfu.state)\n    {\n    case RFUSTATE_INIT:\n        rfu_LMAN_initializeRFU((INIT_PARAM *)&sRfuReqConfigTemplate);\n        gRfu.state = RFUSTATE_INIT_END;\n        gTasks[taskId].data[1] = 1;\n        break;\n    case RFUSTATE_INIT_END:\n        break;\n    case RFUSTATE_CHILD_CONNECT:\n        rfu_LMAN_establishConnection(gRfu.parentChild, 0, 240, (u16 *)sAcceptedSerialNos);\n        gRfu.state = RFUSTATE_CHILD_CONNECT_END;\n        gTasks[taskId].data[1] = 7;\n        break;\n    case RFUSTATE_CHILD_CONNECT_END:\n        break;\n    case RFUSTATE_RECONNECTED:\n        gTasks[taskId].data[1] = 10;\n        break;\n    case RFUSTATE_CHILD_TRY_JOIN:\n        switch (GetJoinGroupStatus())\n        {\n        case RFU_STATUS_JOIN_GROUP_OK:\n            gRfu.state = RFUSTATE_CHILD_JOINED;\n            break;\n        case RFU_STATUS_JOIN_GROUP_NO:\n        case RFU_STATUS_LEAVE_GROUP:\n            rfu_LMAN_requestChangeAgbClockMaster();\n            gRfu.disconnectMode = RFU_DISCONNECT_NORMAL;\n            DestroyTask(taskId);\n            break;\n        }\n        break;\n    case RFUSTATE_CHILD_JOINED:\n    {\n        u8 bmChildSlot = 1 << gRfu.childSlot;\n        rfu_clearSlot(TYPE_NI_SEND | TYPE_NI_RECV, gRfu.childSlot);\n        rfu_setRecvBuffer(TYPE_UNI, gRfu.childSlot, gRfu.childRecvQueue, sizeof(gRfu.childRecvQueue));\n        rfu_UNI_setSendData(bmChildSlot, gRfu.childSendBuffer,  sizeof(gRfu.childSendBuffer));\n        gTasks[taskId].data[1] = 8;\n        DestroyTask(taskId);\n        if (sRfuDebug.childJoinCount == 0)\n        {\n            Debug_PrintEmpty();\n            sRfuDebug.childJoinCount++;\n        }\n        CreateTask(Task_PlayerExchange, 5);\n        break;\n    }\n    }",
  },
  "Task_Idle": {
    returnType: "static void",
    params: "u8 taskId",
    lineCount: 0,
    bodyC: "",
  },
  "Task_ParentSearchForChildren": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateTask","DestroyTask","InitChildRecvBuffers","InitParentSendData","UpdateChildStatuses","rfu_LMAN_establishConnection","rfu_LMAN_initializeRFU","rfu_LMAN_setMSCCallback","rfu_LMAN_stopManager"],
    lineCount: 34,
    bodyC: "UpdateChildStatuses();\n    switch (gRfu.state)\n    {\n    case RFUSTATE_INIT:\n        rfu_LMAN_initializeRFU(&sRfuReqConfig);\n        gRfu.state = RFUSTATE_INIT_END;\n        gTasks[taskId].data[1] = 1;\n        break;\n    case RFUSTATE_INIT_END:\n        break;\n    case RFUSTATE_PARENT_CONNECT:\n        rfu_LMAN_establishConnection(gRfu.parentChild, 0, 240, (u16 *)sAcceptedSerialNos);\n        gRfu.state = RFUSTATE_PARENT_CONNECT_END;\n        gTasks[taskId].data[1] = 6;\n        break;\n    case RFUSTATE_PARENT_CONNECT_END:\n        break;\n    case RFUSTATE_STOP_MANAGER:\n        rfu_LMAN_stopManager(FALSE);\n        gRfu.state = RFUSTATE_STOP_MANAGER_END;\n        break;\n    case RFUSTATE_STOP_MANAGER_END:\n        break;\n    case RFUSTATE_PARENT_FINALIZE:\n        gRfu.parentFinished = FALSE;\n        rfu_LMAN_setMSCCallback(MSCCallback_Parent);\n        InitChildRecvBuffers();\n        InitParentSendData();\n        gRfu.state = RFUSTATE_FINALIZED;\n        gTasks[taskId].data[1] = 8;\n        CreateTask(Task_PlayerExchange, 5);\n        DestroyTask(taskId);\n        break;\n    }",
  },
  "Task_PlayerExchange": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["AreAllPlayersFinishedReceiving","AreAllPlayersReadyToReceive","DestroyTask","LinkPlayerFromBlock","LocalLinkPlayerToBlock","ResetBlockReceivedFlags","RfuPrepareSendBuffer","Rfu_ResetBlockReceivedFlag","rfu_LMAN_setLinkRecovery"],
    lineCount: 83,
    bodyC: "s32 i;\n\n    if (gRfu.status == RFU_STATUS_FATAL_ERROR || gRfu.status == RFU_STATUS_CONNECTION_ERROR)\n    {\n        gRfu.playerExchangeActive = FALSE;\n        DestroyTask(taskId);\n    }\n    switch (gTasks[taskId].tState)\n    {\n    case 0:\n        if (AreAllPlayersReadyToReceive())\n        {\n            ResetBlockReceivedFlags();\n            LocalLinkPlayerToBlock();\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 1:\n        if (gRfu.parentChild == MODE_PARENT)\n        {\n            if (gReceivedRemoteLinkPlayers)\n                RfuPrepareSendBuffer(RFUCMD_SEND_PLAYER_IDS_NEW);\n            else\n                RfuPrepareSendBuffer(RFUCMD_SEND_PLAYER_IDS);\n            gTasks[taskId].tState = 101;\n        }\n        else\n        {\n            gTasks[taskId].tState = 2;\n        }\n        break;\n    case 101:\n        if (gSendCmd[0] == 0)\n            gTasks[taskId].tState = 2;\n        break;\n    case 2:\n        if (gRfu.playerCount)\n            gTasks[taskId].tState++;\n        break;\n    case 3:\n        if (gRfu.parentChild == MODE_PARENT)\n        {\n            if (AreAllPlayersReadyToReceive())\n            {\n                gRfu.blockRequestType = BLOCK_REQ_SIZE_NONE;\n                RfuPrepareSendBuffer(RFUCMD_SEND_BLOCK_REQ);\n                gTasks[taskId].tState++;\n            }\n        }\n        else\n        {\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 4:\n        if (AreAllPlayersFinishedReceiving())\n            gTasks[taskId].tState++;\n        break;\n    case 5:\n        for (i = 0; i < gRfu.playerCount; i++)\n        {\n            LinkPlayerFromBlock(i);\n            Rfu_ResetBlockReceivedFlag(i);\n        }\n        gTasks[taskId].tState++;\n        break;\n    case 6:\n        DestroyTask(taskId);\n        gReceivedRemoteLinkPlayers = TRUE;\n        gRfu.playerExchangeActive = FALSE;\n        rfu_LMAN_setLinkRecovery(1, 600);\n        if (gRfu.newChildQueue)\n        {\n            for (i = 0; i < RFU_CHILD_MAX; i++)\n            {\n                if ((gRfu.newChildQueue >> i) & 1)\n                {\n                    gRfu.nextChildBits = 1 << i;\n                    gRfu.newChildQueue ^= (1 << i);\n                }\n            }\n        }\n        break;\n    }",
  },
  "Task_PlayerExchangeChat": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","GetBlockReceivedStatus","IsLinkTaskFinished","LocalLinkPlayerToBlock","ReceiveRfuLinkPlayers","ResetBlockReceivedFlag","SendBlock"],
    lineCount: 26,
    bodyC: "if (gRfu.status == RFU_STATUS_FATAL_ERROR || gRfu.status == RFU_STATUS_CONNECTION_ERROR)\n        DestroyTask(taskId);\n    switch (gTasks[taskId].tState)\n    {\n    case 0:\n        if (gRfu.playerCount)\n        {\n            LocalLinkPlayerToBlock();\n            SendBlock(0, gBlockSendBuffer, sizeof(struct LinkPlayerBlock));\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 1:\n        if (IsLinkTaskFinished())\n            gTasks[taskId].tState++;\n        break;\n    case 2:\n        if (GetBlockReceivedStatus() & 1)\n        {\n            ReceiveRfuLinkPlayers((const struct SioInfo *)gBlockRecvBuffer);\n            ResetBlockReceivedFlag(0);\n            gReceivedRemoteLinkPlayers = 1;\n            DestroyTask(taskId);\n        }\n        break;\n    }",
  },
  "Task_PlayerExchangeUpdate": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["ConvertLinkPlayerName","CpuFill16","DestroyTask","GetBlockReceivedStatus","IsLinkTaskFinished","ResetBlockReceivedFlag","RfuPrepareSendBuffer","SendBlock","memcpy","offsetof"],
    lineCount: 73,
    bodyC: "s32 i;\n    struct LinkPlayerBlock *playerBlock;\n    struct SioInfo *sio;\n    u8 playerId = gRfu.linkPlayerIdx[sSlotToLinkPlayerTableId[gRfu.incomingChild]];\n    if (gRfu.status == RFU_STATUS_FATAL_ERROR || gRfu.status == RFU_STATUS_CONNECTION_ERROR)\n    {\n        gRfu.playerExchangeActive = FALSE;\n        DestroyTask(taskId);\n    }\n    switch (gTasks[taskId].tState)\n    {\n    case 0:\n        if (gSendCmd[0] == 0)\n        {\n            ResetBlockReceivedFlag(playerId);\n            RfuPrepareSendBuffer(RFUCMD_SEND_PLAYER_IDS_NEW);\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 1:\n        if (gSendCmd[0] == 0)\n            gTasks[taskId].tState++;\n        break;\n    case 2:\n        if ((GetBlockReceivedStatus() >> playerId) & 1)\n        {\n            ResetBlockReceivedFlag(playerId);\n            playerBlock = (struct LinkPlayerBlock *)gBlockRecvBuffer[playerId];\n            gLinkPlayers[playerId] = playerBlock->linkPlayer;\n            ConvertLinkPlayerName(&gLinkPlayers[playerId]);\n            gTasks[taskId].tState++;\n        }\n        break;\n    case 3:\n        sio = (struct SioInfo *)gBlockSendBuffer;\n        memcpy(sio->magic, sASCII_PokemonSioInfo, sizeof sASCII_PokemonSioInfo);\n        sio->playerCount = gRfu.playerCount;\n        for (i = 0; i < RFU_CHILD_MAX; i++)\n            sio->linkPlayerIdx[i] = gRfu.linkPlayerIdx[i];\n        memcpy(sio->linkPlayers, gLinkPlayers, sizeof gLinkPlayers);\n        gTasks[taskId].tState++;\n         \n    case 4:\n        sio = (struct SioInfo *)gBlockSendBuffer;\n        sio->playerCount = gRfu.playerCount;\n        for (i = 0; i < RFU_CHILD_MAX; i++)\n            sio->linkPlayerIdx[i] = gRfu.linkPlayerIdx[i];\n        memcpy(sio->linkPlayers, gLinkPlayers, sizeof(gLinkPlayers));\n         \n        if (SendBlock(0, gBlockSendBuffer, offsetof(struct SioInfo, filler)))\n            gTasks[taskId].tState++;\n        break;\n    case 5:\n        if (IsLinkTaskFinished() && GetBlockReceivedStatus() & 1)\n        {\n            CpuFill16(0, gBlockRecvBuffer, sizeof(struct SioInfo));\n            ResetBlockReceivedFlag(0);\n            gRfu.playerExchangeActive = FALSE;\n            if (gRfu.newChildQueue)\n            {\n                for (i = 0; i < RFU_CHILD_MAX; i++)\n                {\n                    if ((gRfu.newChildQueue >> i) & 1)\n                    {\n                        gRfu.nextChildBits = 1 << i;\n                        gRfu.newChildQueue ^= (1 << i);\n                        gRfu.playerExchangeActive = TRUE;\n                        break;\n                    }\n                }\n            }\n            DestroyTask(taskId);\n        }\n        break;\n    }",
  },
  "Task_RfuReconnectWithParent": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CanTryReconnectParent","DestroyTask","GetHostRfuGameData","GetPartnerIndexByNameAndTrainerID","ReadU16","RfuSetStatus","TryReconnectParent"],
    lineCount: 38,
    bodyC: "s16 *data = gTasks[taskId].data;\n\n    if (CanTryReconnectParent())\n    {\n        u8 id = GetPartnerIndexByNameAndTrainerID((u8 *)data, ReadU16(&data[8]));\n        if (id != 0xFF)\n        {\n            if (gRfuLinkStatus->partner[id].slot != 0xFF)\n            {\n                gRfu.reconnectParentId = id;\n                if (TryReconnectParent())\n                    DestroyTask(taskId);\n            }\n            else if (GetHostRfuGameData()->activity == ACTIVITY_WONDER_CARD\n                  || GetHostRfuGameData()->activity == ACTIVITY_WONDER_NEWS)\n            {\n                tTime++;\n            }\n            else\n            {\n                 \n                RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, F_RFU_ERROR_5 | F_RFU_ERROR_6 | F_RFU_ERROR_7);\n                DestroyTask(taskId);\n            }\n        }\n        else\n        {\n            tTime++;\n            gRfu.reconnectParentId = id;\n        }\n    }\n    else\n    {\n        tTime++;\n    }\n\n    if (tTime > 240)\n    {\n         \n        RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, F_RFU_ERROR_5 | F_RFU_ERROR_6 | F_RFU_ERROR_7);\n        DestroyTask(taskId);\n    }",
  },
  "Task_SendDisconnectCommand": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","RfuPrepareSendBuffer"],
    lineCount: 9,
    bodyC: "if (gSendCmd[0] == 0 && !gRfu.playerExchangeActive)\n    {\n        RfuPrepareSendBuffer(RFUCMD_DISCONNECT);\n        gSendCmd[1] = gTasks[taskId].tDisconnectPlayers;\n        gSendCmd[2] = gTasks[taskId].tDisconnectMode;\n        gRfu.playerCount -= sPlayerBitsToCount[gTasks[taskId].tDisconnectPlayers];\n        gSendCmd[3] = gRfu.playerCount;\n        DestroyTask(taskId);\n    }",
  },
  "Task_TryConnectToUnionRoomParent": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","GetPartnerIndexByNameAndTrainerID","IsPartnerActivityIncompatible","ReadU16","RfuSetStatus","rfu_LMAN_CHILD_connectParent"],
    lineCount: 28,
    bodyC: "if (gRfu.status == RFU_STATUS_NEW_CHILD_DETECTED)\n        DestroyTask(taskId);\n\n    if (++gTasks[taskId].tTime > 300)\n    {\n         \n        RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, F_RFU_ERROR_5 | F_RFU_ERROR_6 | F_RFU_ERROR_7);\n        DestroyTask(taskId);\n    }\n\n     \n    if (gRfu.parentId != 0 && lman.parent_child == MODE_CHILD)\n    {\n         \n        u16 trainerId = ReadU16(gRfu.parent.compatibility.playerTrainerId);\n        u8 id = GetPartnerIndexByNameAndTrainerID(gRfu.parentName, trainerId);\n        if (id != 0xFF)\n        {\n             \n            if (!IsPartnerActivityIncompatible(gTasks[taskId].tActivity, (void *)gRfuLinkStatus->partner[id].gname))\n            {\n                if (gRfuLinkStatus->partner[id].slot != 0xFF && !rfu_LMAN_CHILD_connectParent(gRfuLinkStatus->partner[id].id, 90))\n                {\n                     \n                    gRfu.state = RFUSTATE_CONNECTED;\n                    DestroyTask(taskId);\n                }\n            }\n            else\n            {\n                 \n                RfuSetStatus(RFU_STATUS_CONNECTION_ERROR, F_RFU_ERROR_5 | F_RFU_ERROR_6 | F_RFU_ERROR_7);\n                DestroyTask(taskId);\n            }\n        }\n    }",
  },
  "Task_TryReadyCloseLink": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask"],
    lineCount: 6,
    bodyC: "if (gRfu.callback == NULL)\n    {\n        gRfu.stopNewConnections = TRUE;\n        gRfu.callback = SendReadyCloseLink;\n        DestroyTask(taskId);\n    }",
  },
  "Task_UnionRoomListen": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CreateTask","DestroyTask","GetHostRfuGameData","InitChildRecvBuffers","InitParentSendData","RfuGetStatus","RfuSetStatus","UpdateGameData_GroupLockedIn","rfu_LMAN_establishConnection","rfu_LMAN_initializeRFU","rfu_LMAN_setMSCCallback","rfu_LMAN_stopManager","rfu_REQ_disconnect","rfu_UNI_setSendData","rfu_waitREQComplete"],
    lineCount: 53,
    bodyC: "if (GetHostRfuGameData()->activity == (ACTIVITY_PLYRTALK | IN_UNION_ROOM) && RfuGetStatus() == RFU_STATUS_NEW_CHILD_DETECTED)\n    {\n        rfu_REQ_disconnect(lman.acceptSlot_flag);\n        rfu_waitREQComplete();\n        RfuSetStatus(RFU_STATUS_OK, 0);\n    }\n    switch (gRfu.state)\n    {\n    case RFUSTATE_INIT:\n        rfu_LMAN_initializeRFU(&sRfuReqConfig);\n        gRfu.state = RFUSTATE_INIT_END;\n        gTasks[taskId].data[1] = 1;\n        break;\n    case RFUSTATE_INIT_END:\n        break;\n    case RFUSTATE_UR_CONNECT:\n        rfu_LMAN_establishConnection(MODE_P_C_SWITCH, 0, 240, (u16 *)sAcceptedSerialNos);\n        rfu_LMAN_setMSCCallback(MSCCallback_Child);\n        gRfu.state = RFUSTATE_UR_CONNECT_END;\n        break;\n    case RFUSTATE_UR_CONNECT_END:\n        break;\n    case RFUSTATE_UR_PLAYER_EXCHANGE:\n        if (rfu_UNI_setSendData(1 << gRfu.childSlot, gRfu.childSendBuffer, sizeof(gRfu.childSendBuffer)) == 0)\n        {\n            gRfu.parentChild = MODE_CHILD;\n            DestroyTask(taskId);\n            if (gTasks[taskId].tConnectingForChat)\n                CreateTask(Task_PlayerExchangeChat, 1);\n            else\n                CreateTask(Task_PlayerExchange, 5);\n        }\n        break;\n    case RFUSTATE_UR_STOP_MANAGER:\n        rfu_LMAN_stopManager(FALSE);\n        gRfu.state = RFUSTATE_UR_STOP_MANAGER_END;\n        break;\n    case RFUSTATE_UR_STOP_MANAGER_END:\n        break;\n    case RFUSTATE_UR_FINALIZE:\n        gRfu.parentFinished = FALSE;\n        rfu_LMAN_setMSCCallback(MSCCallback_Parent);\n        UpdateGameData_GroupLockedIn(TRUE);\n        InitChildRecvBuffers();\n        InitParentSendData();\n        gRfu.state = RFUSTATE_FINALIZED;\n        gTasks[taskId].data[1] = 8;\n        gRfu.parentChild = MODE_PARENT;\n        CreateTask(Task_PlayerExchange, 5);\n        gRfu.playerExchangeActive = TRUE;\n        DestroyTask(taskId);\n        break;\n    }",
  },
  "TryConnectToUnionRoomParent": {
    returnType: "void",
    params: "const u8 *name, struct RfuGameData *parent, u8 activity",
    callsTo: ["CreateTask","FindTaskIdByFunc","StringCopy","memcpy","rfu_LMAN_forceChangeSP"],
    lineCount: 19,
    bodyC: "u8 taskId, listenTaskId;\n\n    gRfu.connectParentFailures = 0;\n    gRfu.status = RFU_STATUS_OK;\n    StringCopy(gRfu.parentName, name);\n    memcpy(&gRfu.parent, parent, RFU_GAME_NAME_LENGTH);\n    rfu_LMAN_forceChangeSP();\n    taskId = CreateTask(Task_TryConnectToUnionRoomParent, 2);\n    gTasks[taskId].tActivity = activity;\n    listenTaskId = FindTaskIdByFunc(Task_UnionRoomListen);\n    if (activity == (ACTIVITY_CHAT | IN_UNION_ROOM))\n    {\n        if (listenTaskId != TASK_NONE)\n            gTasks[listenTaskId].tConnectingForChat = TRUE;\n    }\n    else\n    {\n        if (listenTaskId != TASK_NONE)\n            gTasks[listenTaskId].tConnectingForChat = FALSE;\n    }",
  },
  "TryDisconnectRfu": {
    returnType: "static void",
    params: "void",
    callsTo: ["rfu_LMAN_requestChangeAgbClockMaster"],
    lineCount: 9,
    bodyC: "if (gRfu.parentChild == MODE_CHILD)\n    {\n        rfu_LMAN_requestChangeAgbClockMaster();\n        gRfu.disconnectMode = RFU_DISCONNECT_NORMAL;\n    }\n    else\n    {\n        gRfu.callback = DisconnectRfu;\n    }",
  },
  "TryReconnectParent": {
    returnType: "static bool32",
    params: "void",
    callsTo: ["rfu_LMAN_CHILD_connectParent"],
    lineCount: 6,
    bodyC: "if (gRfu.state == RFUSTATE_CHILD_CONNECT_END && !rfu_LMAN_CHILD_connectParent(gRfuLinkStatus->partner[gRfu.reconnectParentId].id, 240))\n    {\n        gRfu.state = RFUSTATE_RECONNECTED;\n        return TRUE;\n    }\n    return FALSE;",
  },
  "UpdateBackupQueue": {
    returnType: "static void",
    params: "void",
    callsTo: ["RfuBackupQueue_Dequeue","RfuBackupQueue_Enqueue","RfuSendQueue_Dequeue"],
    lineCount: 13,
    bodyC: "if (gRfu.linkRecovered)\n    {\n        bool8 backupEmpty = RfuBackupQueue_Dequeue(&gRfu.backupQueue, gRfu.childSendBuffer);\n\n        if (gRfu.backupQueue.count == 0)\n            gRfu.linkRecovered = FALSE;\n\n        if (backupEmpty)\n            return;\n    }\n    if (!gRfu.linkRecovered)\n    {\n        RfuSendQueue_Dequeue(&gRfu.sendQueue, gRfu.childSendBuffer);\n        RfuBackupQueue_Enqueue(&gRfu.backupQueue, gRfu.childSendBuffer);\n    }",
  },
  "UpdateChildStatuses": {
    returnType: "static void",
    params: "void",
    callsTo: ["CheckForLeavingGroupMembers","rfu_clearSlot"],
    lineCount: 12,
    bodyC: "s32 i;\n\n    CheckForLeavingGroupMembers();\n    for (i = 0; i < RFU_CHILD_MAX; i++)\n    {\n        if (gRfuSlotStatusNI[i]->send.state == SLOT_STATE_SEND_SUCCESS\n         || gRfuSlotStatusNI[i]->send.state == SLOT_STATE_SEND_FAILED)\n        {\n            if (gRfu.partnerRecvStatuses[i] == RFU_STATUS_CHILD_LEAVE_READY)\n                gRfu.partnerRecvStatuses[i] = RFU_STATUS_CHILD_LEAVE;\n            rfu_clearSlot(TYPE_NI_SEND, i);\n        }\n    }",
  },
  "UpdateGameData_GroupLockedIn": {
    returnType: "void",
    params: "bool8 startedActivity",
    callsTo: ["rfu_REQ_configGameData"],
    lineCount: 2,
    bodyC: "gHostRfuGameData.startedActivity = startedActivity;\n    rfu_REQ_configGameData(0, RFU_SERIAL_GAME, (void *)&gHostRfuGameData, gHostRfuUsername);",
  },
  "UpdateGameData_SetActivity": {
    returnType: "void",
    params: "u8 activity, u32 partnerInfo, bool32 startedActivity",
    callsTo: ["SetHostRfuGameData","rfu_REQ_configGameData"],
    lineCount: 3,
    bodyC: "if (activity != ACTIVITY_NONE)\n        SetHostRfuGameData(activity, partnerInfo, startedActivity);\n    rfu_REQ_configGameData(0, RFU_SERIAL_GAME, (void *)&gHostRfuGameData, gHostRfuUsername);",
  },
  "VBlank_RfuIdle": {
    returnType: "static void",
    params: "void",
    callsTo: ["LoadOam","ProcessSpriteCopyRequests","TransferPlttBuffer"],
    lineCount: 3,
    bodyC: "LoadOam();\n    ProcessSpriteCopyRequests();\n    TransferPlttBuffer();",
  },
  "ValidateAndReceivePokemonSioInfo": {
    returnType: "static void",
    params: "void *recvBuffer",
    callsTo: ["CpuFill16","ReceiveRfuLinkPlayers","ResetBlockReceivedFlag","strcmp"],
    lineCount: 6,
    bodyC: "if (strcmp(sASCII_PokemonSioInfo, recvBuffer) == 0)\n    {\n        ReceiveRfuLinkPlayers(recvBuffer);\n        CpuFill16(0, recvBuffer, sizeof(struct SioInfo));\n        ResetBlockReceivedFlag(0);\n    }",
  },
  "WaitAllReadyToCloseLink": {
    returnType: "static void",
    params: "void",
    callsTo: ["TryDisconnectRfu"],
    lineCount: 21,
    bodyC: "s32 i;\n    u8 playerCount = gRfu.playerCount;\n    s32 count = 0;\n\n     \n    for (i = 0; i < MAX_RFU_PLAYERS; i++)\n    {\n        if (gRfu.readyCloseLink[i])\n            count++;\n    }\n    if (count == playerCount)\n    {\n         \n        gBattleTypeFlags &= ~BATTLE_TYPE_LINK_IN_BATTLE;\n        if (gRfu.parentChild == MODE_CHILD)\n        {\n            gRfu.errorState = RFU_ERROR_STATE_DISCONNECTING;\n            TryDisconnectRfu();\n        }\n        else\n        {\n            gRfu.callback = TryDisconnectRfu;\n        }\n    }",
  },
  "WaitRfuState": {
    returnType: "bool32",
    params: "bool32 force",
    lineCount: 6,
    bodyC: "if (gRfu.state == RFUSTATE_PARENT_FINALIZE_START || force)\n    {\n        gRfu.state = RFUSTATE_PARENT_FINALIZE;\n        return TRUE;\n    }\n    return FALSE;",
  },
  "WaitSendRfuStatusToPartner": {
    returnType: "u32",
    params: "u16 trainerId, const u8 *name",
    callsTo: ["GetPartnerIndexByNameAndTrainerID"],
    lineCount: 6,
    bodyC: "u8 idx = GetPartnerIndexByNameAndTrainerID(name, trainerId);\n    if (idx == 0xFF)\n        return 2;\n    if (gRfuSlotStatusNI[idx]->send.state == 0)\n        return 1;\n    return 0;",
  },
} as const;
