// AUTO-GENERATED from src/main.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 29

export const ENGINE_FUNCTIONS = {
  "AgbMain": {
    returnType: "void",
    params: "void",
    callsTo: ["CheckForFlashMemory","ClearDma3Requests","ClearSpriteCopyRequests","DoSoftReset","EnableVCountIntrAtLine150","InitGpuRegManager","InitHeap","InitIntrHandlers","InitKeys","InitMainCallbacks","InitMapMusic","InitRFU","JOY_HELD_RAW","MapMusicMain","Overworld_RecvKeysFromLinkIsRunning","Overworld_SendKeysToLinkIsRunning","PlayTimeCounter_Update","ReadKeys","RegisterRamReset","ResetBgs","RtcInit","SeedRngWithRtc","SetDefaultFontsPointer","SetMainCallback2","UpdateLinkAndCallCallbacks","WaitForVBlank","m4aSoundInit","rfu_REQ_stopMode","rfu_waitREQComplete"],
    lineCount: 61,
    bodyC: "#if !MODERN\n    RegisterRamReset(RESET_ALL);\n#endif  \n    *(vu16 *)BG_PLTT = RGB_WHITE;  \n    InitGpuRegManager();\n    REG_WAITCNT = WAITCNT_PREFETCH_ENABLE | WAITCNT_WS0_S_1 | WAITCNT_WS0_N_3;\n    InitKeys();\n    InitIntrHandlers();\n    m4aSoundInit();\n    EnableVCountIntrAtLine150();\n    InitRFU();\n    RtcInit();\n    CheckForFlashMemory();\n    InitMainCallbacks();\n    InitMapMusic();\n#ifdef BUGFIX\n    SeedRngWithRtc();  \n#endif\n    ClearDma3Requests();\n    ResetBgs();\n    SetDefaultFontsPointer();\n    InitHeap(gHeap, HEAP_SIZE);\n\n    gSoftResetDisabled = FALSE;\n\n    if (gFlashMemoryPresent != TRUE)\n        SetMainCallback2(NULL);\n\n    gLinkTransferringData = FALSE;\n    sUnusedVar = 0xFC0;\n\n    for (;;)\n    {\n        ReadKeys();\n\n        if (gSoftResetDisabled == FALSE\n         && JOY_HELD_RAW(A_BUTTON)\n         && JOY_HELD_RAW(B_START_SELECT) == B_START_SELECT)\n        {\n            rfu_REQ_stopMode();\n            rfu_waitREQComplete();\n            DoSoftReset();\n        }\n\n        if (Overworld_SendKeysToLinkIsRunning() == TRUE)\n        {\n            gLinkTransferringData = TRUE;\n            UpdateLinkAndCallCallbacks();\n            gLinkTransferringData = FALSE;\n        }\n        else\n        {\n            gLinkTransferringData = FALSE;\n            UpdateLinkAndCallCallbacks();\n\n            if (Overworld_RecvKeysFromLinkIsRunning() == TRUE)\n            {\n                gMain.newKeys = 0;\n                ClearSpriteCopyRequests();\n                gLinkTransferringData = TRUE;\n                UpdateLinkAndCallCallbacks();\n                gLinkTransferringData = FALSE;\n            }\n        }\n\n        PlayTimeCounter_Update();\n        MapMusicMain();\n        WaitForVBlank();\n    }",
  },
  "CallCallbacks": {
    returnType: "static void",
    params: "void",
    callsTo: ["callback1","callback2"],
    lineCount: 4,
    bodyC: "if (gMain.callback1)\n        gMain.callback1();\n\n    if (gMain.callback2)\n        gMain.callback2();",
  },
  "ClearPokemonCrySongs": {
    returnType: "void",
    params: "void",
    callsTo: ["CpuFill16"],
    lineCount: 1,
    bodyC: "CpuFill16(0, gPokemonCrySongs, MAX_POKEMON_CRIES * sizeof(struct PokemonCrySong));",
  },
  "ClearTrainerHillVBlankCounter": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "gTrainerHillVBlankCounter = NULL;",
  },
  "DoSoftReset": {
    returnType: "void",
    params: "void",
    callsTo: ["DmaStop","ScanlineEffect_Stop","SiiRtcProtect","SoftReset","m4aSoundVSyncOff"],
    lineCount: 8,
    bodyC: "REG_IME = 0;\n    m4aSoundVSyncOff();\n    ScanlineEffect_Stop();\n    DmaStop(1);\n    DmaStop(2);\n    DmaStop(3);\n    SiiRtcProtect();\n    SoftReset(RESET_ALL);",
  },
  "EnableVCountIntrAtLine150": {
    returnType: "void",
    params: "void",
    callsTo: ["EnableInterrupts","GetGpuReg","SetGpuReg"],
    lineCount: 3,
    bodyC: "u16 gpuReg = (GetGpuReg(REG_OFFSET_DISPSTAT) & 0xFF) | (150 << 8);\n    SetGpuReg(REG_OFFSET_DISPSTAT, gpuReg | DISPSTAT_VCOUNT_INTR);\n    EnableInterrupts(INTR_FLAG_VCOUNT);",
  },
  "GetGeneratedTrainerIdLower": {
    returnType: "u16",
    params: "void",
    lineCount: 1,
    bodyC: "return sTrainerId;",
  },
  "HBlankIntr": {
    returnType: "static void",
    params: "void",
    callsTo: ["hblankCallback"],
    lineCount: 4,
    bodyC: "if (gMain.hblankCallback)\n        gMain.hblankCallback();\n\n    INTR_CHECK |= INTR_FLAG_HBLANK;\n    gMain.intrCheck |= INTR_FLAG_HBLANK;",
  },
  "InitFlashTimer": {
    returnType: "void",
    params: "void",
    callsTo: ["SetFlashTimerIntr"],
    lineCount: 1,
    bodyC: "SetFlashTimerIntr(2, gIntrTable + 0x7);",
  },
  "InitIntrHandlers": {
    returnType: "void",
    params: "void",
    callsTo: ["DmaCopy32","EnableInterrupts","SetHBlankCallback","SetSerialCallback","SetVBlankCallback"],
    lineCount: 10,
    bodyC: "int i;\n\n    for (i = 0; i < INTR_COUNT; i++)\n        gIntrTable[i] = gIntrTableTemplate[i];\n\n    DmaCopy32(3, IntrMain, IntrMain_Buffer, sizeof(IntrMain_Buffer));\n\n    INTR_VECTOR = IntrMain_Buffer;\n\n    SetVBlankCallback(NULL);\n    SetHBlankCallback(NULL);\n    SetSerialCallback(NULL);\n\n    REG_IME = 1;\n\n    EnableInterrupts(INTR_FLAG_VBLANK);",
  },
  "InitKeys": {
    returnType: "void",
    params: "void",
    lineCount: 7,
    bodyC: "gKeyRepeatContinueDelay = 5;\n    gKeyRepeatStartDelay = 40;\n\n    gMain.heldKeys = 0;\n    gMain.newKeys = 0;\n    gMain.newAndRepeatedKeys = 0;\n    gMain.heldKeysRaw = 0;\n    gMain.newKeysRaw = 0;",
  },
  "InitMainCallbacks": {
    returnType: "static void",
    params: "void",
    callsTo: ["SetMainCallback2"],
    lineCount: 7,
    bodyC: "gMain.vblankCounter1 = 0;\n    gTrainerHillVBlankCounter = NULL;\n    gMain.vblankCounter2 = 0;\n    gMain.callback1 = NULL;\n    SetMainCallback2(CB2_InitCopyrightScreenAfterBootup);\n    gSaveBlock2Ptr = &gSaveblock2.block;\n    gPokemonStoragePtr = &gPokemonStorage.block;",
  },
  "IntrDummy": {
    returnType: "static void",
    params: "void",
    lineCount: 0,
    bodyC: "",
  },
  "ReadKeys": {
    returnType: "static void",
    params: "void",
    callsTo: ["JOY_HELD","JOY_NEW"],
    lineCount: 28,
    bodyC: "u16 keyInput = REG_KEYINPUT ^ KEYS_MASK;\n    gMain.newKeysRaw = keyInput & ~gMain.heldKeysRaw;\n    gMain.newKeys = gMain.newKeysRaw;\n    gMain.newAndRepeatedKeys = gMain.newKeysRaw;\n\n     \n     \n     \n\n    if (keyInput != 0 && gMain.heldKeys == keyInput)\n    {\n        gMain.keyRepeatCounter--;\n\n        if (gMain.keyRepeatCounter == 0)\n        {\n            gMain.newAndRepeatedKeys = keyInput;\n            gMain.keyRepeatCounter = gKeyRepeatContinueDelay;\n        }\n    }\n    else\n    {\n         \n        gMain.keyRepeatCounter = gKeyRepeatStartDelay;\n    }\n\n    gMain.heldKeysRaw = keyInput;\n    gMain.heldKeys = gMain.heldKeysRaw;\n\n     \n    if (gSaveBlock2Ptr->optionsButtonMode == OPTIONS_BUTTON_MODE_L_EQUALS_A)\n    {\n        if (JOY_NEW(L_BUTTON))\n            gMain.newKeys |= A_BUTTON;\n\n        if (JOY_HELD(L_BUTTON))\n            gMain.heldKeys |= A_BUTTON;\n    }\n\n    if (JOY_NEW(gMain.watchedKeysMask))\n        gMain.watchedKeysPressed = TRUE;",
  },
  "RestoreSerialTimer3IntrHandlers": {
    returnType: "void",
    params: "void",
    lineCount: 2,
    bodyC: "gIntrTable[1] = SerialIntr;\n    gIntrTable[2] = Timer3Intr;",
  },
  "SeedRngAndSetTrainerId": {
    returnType: "void",
    params: "void",
    callsTo: ["SeedRng"],
    lineCount: 4,
    bodyC: "u16 val = REG_TM1CNT_L;\n    SeedRng(val);\n    REG_TM1CNT_H = 0;\n    sTrainerId = val;",
  },
  "SeedRngWithRtc": {
    returnType: "static void",
    params: "void",
    callsTo: ["RtcGetMinuteCount","SeedRng"],
    lineCount: 3,
    bodyC: "u32 seed = RtcGetMinuteCount();\n    seed = (seed >> 16) ^ (seed & 0xFFFF);\n    SeedRng(seed);",
  },
  "SerialIntr": {
    returnType: "static void",
    params: "void",
    callsTo: ["serialCallback"],
    lineCount: 4,
    bodyC: "if (gMain.serialCallback)\n        gMain.serialCallback();\n\n    INTR_CHECK |= INTR_FLAG_SERIAL;\n    gMain.intrCheck |= INTR_FLAG_SERIAL;",
  },
  "SetHBlankCallback": {
    returnType: "void",
    params: "IntrCallback callback",
    lineCount: 1,
    bodyC: "gMain.hblankCallback = callback;",
  },
  "SetMainCallback2": {
    returnType: "void",
    params: "MainCallback callback",
    lineCount: 2,
    bodyC: "gMain.callback2 = callback;\n    gMain.state = 0;",
  },
  "SetSerialCallback": {
    returnType: "void",
    params: "IntrCallback callback",
    lineCount: 1,
    bodyC: "gMain.serialCallback = callback;",
  },
  "SetTrainerHillVBlankCounter": {
    returnType: "void",
    params: "u32 *counter",
    lineCount: 1,
    bodyC: "gTrainerHillVBlankCounter = counter;",
  },
  "SetVBlankCallback": {
    returnType: "void",
    params: "IntrCallback callback",
    lineCount: 1,
    bodyC: "gMain.vblankCallback = callback;",
  },
  "SetVCountCallback": {
    returnType: "void",
    params: "IntrCallback callback",
    lineCount: 1,
    bodyC: "gMain.vcountCallback = callback;",
  },
  "StartTimer1": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "REG_TM1CNT_H = 0x80;",
  },
  "UpdateLinkAndCallCallbacks": {
    returnType: "static void",
    params: "void",
    callsTo: ["CallCallbacks","HandleLinkConnection"],
    lineCount: 2,
    bodyC: "if (!HandleLinkConnection())\n        CallCallbacks();",
  },
  "VBlankIntr": {
    returnType: "static void",
    params: "void",
    callsTo: ["CopyBufferedValuesToGpuRegs","LinkVSync","ProcessDma3Requests","Random","RfuVSync","TryReceiveLinkBattleData","UpdateWirelessStatusIndicatorSprite","m4aSoundMain","vblankCallback"],
    lineCount: 20,
    bodyC: "if (gWirelessCommType != 0)\n        RfuVSync();\n    else if (gLinkVSyncDisabled == FALSE)\n        LinkVSync();\n\n    gMain.vblankCounter1++;\n\n    if (gTrainerHillVBlankCounter && *gTrainerHillVBlankCounter < 0xFFFFFFFF)\n        (*gTrainerHillVBlankCounter)++;\n\n    if (gMain.vblankCallback)\n        gMain.vblankCallback();\n\n    gMain.vblankCounter2++;\n\n    CopyBufferedValuesToGpuRegs();\n    ProcessDma3Requests();\n\n    gPcmDmaCounter = gSoundInfo.pcmDmaCounter;\n\n    m4aSoundMain();\n    TryReceiveLinkBattleData();\n\n    if (!gMain.inBattle || !(gBattleTypeFlags & (BATTLE_TYPE_LINK | BATTLE_TYPE_FRONTIER | BATTLE_TYPE_RECORDED)))\n        Random();\n\n    UpdateWirelessStatusIndicatorSprite();\n\n    INTR_CHECK |= INTR_FLAG_VBLANK;\n    gMain.intrCheck |= INTR_FLAG_VBLANK;",
  },
  "VCountIntr": {
    returnType: "static void",
    params: "void",
    callsTo: ["m4aSoundVSync","vcountCallback"],
    lineCount: 5,
    bodyC: "if (gMain.vcountCallback)\n        gMain.vcountCallback();\n\n    m4aSoundVSync();\n    INTR_CHECK |= INTR_FLAG_VCOUNT;\n    gMain.intrCheck |= INTR_FLAG_VCOUNT;",
  },
  "WaitForVBlank": {
    returnType: "static void",
    params: "void",
    lineCount: 3,
    bodyC: "gMain.intrCheck &= ~INTR_FLAG_VBLANK;\n\n    while (!(gMain.intrCheck & INTR_FLAG_VBLANK))\n        ;",
  },
} as const;
