// AUTO-GENERATED from src/match_call.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 54

export const ENGINE_FUNCTIONS = {
  "BufferPokedexRatingForMatchCall": {
    returnType: "void",
    params: "u8 *destStr",
    callsTo: ["Alloc","ConvertIntToDecimalStringN","Free","GetHoennPokedexCount","GetNationalPokedexCount","GetPokedexRatingLevel","IsNationalPokedexEnabled","StringCopy","StringExpandPlaceholders"],
    lineCount: 30,
    bodyC: "int numSeen, numCaught;\n    u8 *str;\n    u8 dexRatingLevel;\n\n    u8 *buffer = Alloc(sizeof(gStringVar4));\n    if (!buffer)\n    {\n        destStr[0] = EOS;\n        return;\n    }\n\n    numSeen = GetHoennPokedexCount(FLAG_GET_SEEN);\n    numCaught = GetHoennPokedexCount(FLAG_GET_CAUGHT);\n    ConvertIntToDecimalStringN(gStringVar1, numSeen, STR_CONV_MODE_LEFT_ALIGN, 3);\n    ConvertIntToDecimalStringN(gStringVar2, numCaught, STR_CONV_MODE_LEFT_ALIGN, 3);\n    dexRatingLevel = GetPokedexRatingLevel(numCaught);\n    str = StringCopy(buffer, gBirchDexRatingText_AreYouCurious);\n    *(str++) = CHAR_PROMPT_CLEAR;\n    str = StringCopy(str, gBirchDexRatingText_SoYouveSeenAndCaught);\n    *(str++) = CHAR_PROMPT_CLEAR;\n    StringCopy(str, sBirchDexRatingTexts[dexRatingLevel]);\n    str = StringExpandPlaceholders(destStr, buffer);\n\n    if (IsNationalPokedexEnabled())\n    {\n        *(str++) = CHAR_PROMPT_CLEAR;\n        numSeen = GetNationalPokedexCount(FLAG_GET_SEEN);\n        numCaught = GetNationalPokedexCount(FLAG_GET_CAUGHT);\n        ConvertIntToDecimalStringN(gStringVar1, numSeen, STR_CONV_MODE_LEFT_ALIGN, 3);\n        ConvertIntToDecimalStringN(gStringVar2, numCaught, STR_CONV_MODE_LEFT_ALIGN, 3);\n        StringExpandPlaceholders(str, gBirchDexRatingText_OnANationwideBasis);\n    }\n\n    Free(buffer);",
  },
  "BuildMatchCallString": {
    returnType: "static void",
    params: "int matchCallId, const struct MatchCallText *matchCallText, u8 *str",
    callsTo: ["PopulateMatchCallStringVars","StringExpandPlaceholders"],
    lineCount: 2,
    bodyC: "PopulateMatchCallStringVars(matchCallId, matchCallText->stringVarFuncIds);\n    StringExpandPlaceholders(str, matchCallText->text);",
  },
  "CheckMatchCallChance": {
    returnType: "static bool32",
    params: "void",
    callsTo: ["GetMonAbility","GetMonData","Random"],
    lineCount: 7,
    bodyC: "int callChance = 1;\n    if (!GetMonData(&gPlayerParty[0], MON_DATA_SANITY_IS_EGG) && GetMonAbility(&gPlayerParty[0]) == ABILITY_LIGHTNING_ROD)\n        callChance = 2;\n\n    if (Random() % 10 < callChance * 3)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "DrawMatchCallTextBoxBorder": {
    returnType: "void",
    params: "u32 windowId, u32 tileOffset, u32 paletteId",
    callsTo: ["DrawMatchCallTextBoxBorder_Internal"],
    lineCount: 1,
    bodyC: "DrawMatchCallTextBoxBorder_Internal(windowId, tileOffset, paletteId);",
  },
  "DrawMatchCallTextBoxBorder_Internal": {
    returnType: "static void",
    params: "u32 windowId, u32 tileOffset, u32 paletteId",
    callsTo: ["FillBgTilemapBufferRect_Palette0","GetBgAttribute","GetWindowAttribute"],
    lineCount: 16,
    bodyC: "int bg, x, y, width, height;\n    int tileNum;\n\n    bg = GetWindowAttribute(windowId, WINDOW_BG);\n    x = GetWindowAttribute(windowId, WINDOW_TILEMAP_LEFT);\n    y = GetWindowAttribute(windowId, WINDOW_TILEMAP_TOP);\n    width = GetWindowAttribute(windowId, WINDOW_WIDTH);\n    height = GetWindowAttribute(windowId, WINDOW_HEIGHT);\n    tileNum = tileOffset + GetBgAttribute(bg, BG_ATTR_BASETILE);\n\n    FillBgTilemapBufferRect_Palette0(bg, ((paletteId << 12) & 0xF000) | (tileNum + 0), x - 1, y - 1, 1, 1);\n    FillBgTilemapBufferRect_Palette0(bg, ((paletteId << 12) & 0xF000) | (tileNum + 1), x, y - 1, width, 1);\n    FillBgTilemapBufferRect_Palette0(bg, ((paletteId << 12) & 0xF000) | (tileNum + 2), x + width, y - 1, 1, 1);\n    FillBgTilemapBufferRect_Palette0(bg, ((paletteId << 12) & 0xF000) | (tileNum + 3), x - 1, y, 1, height);\n    FillBgTilemapBufferRect_Palette0(bg, ((paletteId << 12) & 0xF000) | (tileNum + 4), x + width, y, 1, height);\n    FillBgTilemapBufferRect_Palette0(bg, ((paletteId << 12) & 0xF000) | (tileNum + 5), x - 1, y + height, 1, 1);\n    FillBgTilemapBufferRect_Palette0(bg, ((paletteId << 12) & 0xF000) | (tileNum + 6), x, y + height, width, 1);\n    FillBgTilemapBufferRect_Palette0(bg, ((paletteId << 12) & 0xF000) | (tileNum + 7), x + width, y + height, 1, 1);",
  },
  "ExecuteMatchCall": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask"],
    lineCount: 8,
    bodyC: "s16 *data = gTasks[taskId].data;\n    if (sMatchCallTaskFuncs[tState](taskId))\n    {\n        tState++;\n        data[1] = 0;  \n        if ((u16)tState > 7)\n            DestroyTask(taskId);\n    }",
  },
  "GetActiveMatchCallTrainerId": {
    returnType: "static u32",
    params: "u32 activeMatchCallId",
    callsTo: ["FlagGet"],
    lineCount: 11,
    bodyC: "u32 i;\n    for (i = 0; i < REMATCH_SPECIAL_TRAINER_START; i++)\n    {\n        if (FlagGet(TRAINER_REGISTERED_FLAGS_START + i))\n        {\n            if (!activeMatchCallId)\n                return gRematchTable[i].trainerIds[0];\n\n            activeMatchCallId--;\n        }\n    }\n\n    return REMATCH_TABLE_ENTRIES;",
  },
  "GetBattleMatchCallText": {
    returnType: "static const struct MatchCallText *",
    params: "int matchCallId, u8 *str",
    callsTo: ["Random","SpriteCallbackDummy"],
    lineCount: 10,
    bodyC: "int mask;\n    u32 textId, topic, id;\n\n    topic = Random() % 3;\n    textId = sMatchCallTrainers[matchCallId].battleTopicTextIds[topic];\n    if (!textId)\n        SpriteCallbackDummy(NULL);  \n\n    mask = 0xFF;\n    topic = (textId >> 8) - 1;\n    id = (textId & mask) - 1;\n    return &sMatchCallBattleTopics[topic][id];",
  },
  "GetCurrentTotalMinutes": {
    returnType: "static u32",
    params: "struct Time *time",
    lineCount: 1,
    bodyC: "return time->days * 24 * 60 + time->hours * 60 + time->minutes;",
  },
  "GetDifferentRouteMatchCallText": {
    returnType: "static const struct MatchCallText *",
    params: "int matchCallId, u8 *str",
    lineCount: 5,
    bodyC: "u16 textId = sMatchCallTrainers[matchCallId].differentRouteMatchCallTextId;\n    int mask = 0xFF;\n    u32 topic = (textId >> 8) - 1;\n    u32 id = (textId & mask) - 1;\n    return &sMatchCallBattleRequestTopics[topic][id];",
  },
  "GetFrontierStreakInfo": {
    returnType: "static u16",
    params: "u16 facilityId, u32 *topicTextId",
    callsTo: ["ARRAY_COUNT"],
    lineCount: 75,
    bodyC: "int i;\n    int j;\n    u16 streak = 0;\n\n    switch (facilityId)\n    {\n    case FRONTIER_FACILITY_DOME:\n        for (i = 0; i < (int)ARRAY_COUNT(gSaveBlock2Ptr->frontier.domeRecordWinStreaks); i++)\n        {\n            for (j = 0; j < FRONTIER_LVL_MODE_COUNT; j++)\n            {\n                if (streak < gSaveBlock2Ptr->frontier.domeRecordWinStreaks[i][j])\n                    streak = gSaveBlock2Ptr->frontier.domeRecordWinStreaks[i][j];\n            }\n        }\n        *topicTextId = GEN_TOPIC_B_DOME - 1;\n        break;\n    case MATCH_CALL_PIKE:\n        for (i = 0; i < FRONTIER_LVL_MODE_COUNT; i++)\n        {\n            if (streak < gSaveBlock2Ptr->frontier.pikeRecordStreaks[i])\n                streak = gSaveBlock2Ptr->frontier.pikeRecordStreaks[i];\n        }\n        *topicTextId = GEN_TOPIC_B_PIKE - 1;\n        break;\n    case FRONTIER_FACILITY_TOWER:\n        for (i = 0; i < (int)ARRAY_COUNT(gSaveBlock2Ptr->frontier.towerRecordWinStreaks); i++)\n        {\n            for (j = 0; j < FRONTIER_LVL_MODE_COUNT; j++)\n            {\n                if (streak < gSaveBlock2Ptr->frontier.towerRecordWinStreaks[i][j])\n                    streak = gSaveBlock2Ptr->frontier.towerRecordWinStreaks[i][j];\n            }\n        }\n        *topicTextId = GEN_TOPIC_STREAK_RECORD - 1;\n        break;\n    case FRONTIER_FACILITY_PALACE:\n        for (i = 0; i < (int)ARRAY_COUNT(gSaveBlock2Ptr->frontier.palaceRecordWinStreaks); i++)\n        {\n            for (j = 0; j < FRONTIER_LVL_MODE_COUNT; j++)\n            {\n                if (streak < gSaveBlock2Ptr->frontier.palaceRecordWinStreaks[i][j])\n                    streak = gSaveBlock2Ptr->frontier.palaceRecordWinStreaks[i][j];\n            }\n        }\n        *topicTextId = GEN_TOPIC_STREAK_RECORD - 1;\n        break;\n    case MATCH_CALL_FACTORY:\n        for (i = 0; i < (int)ARRAY_COUNT(gSaveBlock2Ptr->frontier.factoryRecordWinStreaks); i++)\n        {\n            for (j = 0; j < FRONTIER_LVL_MODE_COUNT; j++)\n            {\n                if (streak < gSaveBlock2Ptr->frontier.factoryRecordWinStreaks[i][j])\n                    streak = gSaveBlock2Ptr->frontier.factoryRecordWinStreaks[i][j];\n            }\n        }\n        *topicTextId = GEN_TOPIC_STREAK_RECORD - 1;\n        break;\n    case FRONTIER_FACILITY_ARENA:\n        for (i = 0; i < FRONTIER_LVL_MODE_COUNT; i++)\n        {\n            if (streak < gSaveBlock2Ptr->frontier.arenaRecordStreaks[i])\n                streak = gSaveBlock2Ptr->frontier.arenaRecordStreaks[i];\n        }\n        *topicTextId = GEN_TOPIC_STREAK_RECORD - 1;\n        break;\n    case FRONTIER_FACILITY_PYRAMID:\n        for (i = 0; i < FRONTIER_LVL_MODE_COUNT; i++)\n        {\n            if (streak < gSaveBlock2Ptr->frontier.pyramidRecordStreaks[i])\n                streak = gSaveBlock2Ptr->frontier.pyramidRecordStreaks[i];\n        }\n        *topicTextId = GEN_TOPIC_B_PYRAMID - 1;\n        break;\n    }\n\n    return streak;",
  },
  "GetGeneralMatchCallText": {
    returnType: "static const struct MatchCallText *",
    params: "int matchCallId, u8 *str",
    callsTo: ["GetFrontierStreakInfo","Random"],
    lineCount: 32,
    bodyC: "int i;\n    int count;\n    u32 topic, id;\n    u16 rand;\n\n    rand = Random();\n    if (!(rand & 1))\n    {\n         \n        for (count = 0, i = 0; i < NUM_FRONTIER_FACILITIES; i++)\n        {\n            if (GetFrontierStreakInfo(i, &topic) > 1)\n                count++;\n        }\n\n        if (count)\n        {\n             \n             \n            count = Random() % count;\n            for (i = 0; i < NUM_FRONTIER_FACILITIES; i++)\n            {\n                sBattleFrontierStreakInfo.streak = GetFrontierStreakInfo(i, &topic);\n                if (sBattleFrontierStreakInfo.streak < 2)\n                    continue;\n\n                if (!count)\n                    break;\n\n                count--;\n            }\n\n            sBattleFrontierStreakInfo.facilityId = i;\n            id = sMatchCallTrainers[matchCallId].battleFrontierRecordStreakTextIndex - 1;\n            return &sMatchCallGeneralTopics[topic][id];\n        }\n    }\n\n    topic = (sMatchCallTrainers[matchCallId].generalTextId >> 8) - 1;\n    id = (sMatchCallTrainers[matchCallId].generalTextId & 0xFF) - 1;\n    return &sMatchCallGeneralTopics[topic][id];",
  },
  "GetLandEncounterSlot": {
    returnType: "static u8",
    params: "void",
    callsTo: ["Random"],
    lineCount: 25,
    bodyC: "int rand = Random() % 100;\n    if (rand < 20)\n        return 0;\n    else if (rand >= 20 && rand < 40)\n        return 1;\n    else if (rand >= 40 && rand < 50)\n        return 2;\n    else if (rand >= 50 && rand < 60)\n        return 3;\n    else if (rand >= 60 && rand < 70)\n        return 4;\n    else if (rand >= 70 && rand < 80)\n        return 5;\n    else if (rand >= 80 && rand < 85)\n        return 6;\n    else if (rand >= 85 && rand < 90)\n        return 7;\n    else if (rand >= 90 && rand < 94)\n        return 8;\n    else if (rand >= 94 && rand < 98)\n        return 9;\n    else if (rand >= 98 && rand < 99)\n        return 10;\n    else\n        return 11;",
  },
  "GetNthRematchTrainerFought": {
    returnType: "static u32",
    params: "int n",
    callsTo: ["HasTrainerBeenFought"],
    lineCount: 11,
    bodyC: "u32 i, count;\n\n    for (i = 0, count = 0; i < REMATCH_TABLE_ENTRIES; i++)\n    {\n        if (HasTrainerBeenFought(gRematchTable[i].trainerIds[0]))\n        {\n            if (count == n)\n                return i;\n\n            count++;\n        }\n    }\n\n    return REMATCH_TABLE_ENTRIES;",
  },
  "GetNumOwnedBadges": {
    returnType: "static int",
    params: "void",
    callsTo: ["FlagGet"],
    lineCount: 7,
    bodyC: "u32 i;\n\n    for (i = 0; i < NUM_BADGES; i++)\n    {\n        if (!FlagGet(sBadgeFlags[i]))\n            break;\n    }\n\n    return i;",
  },
  "GetNumRegisteredTrainers": {
    returnType: "static u32",
    params: "void",
    callsTo: ["FlagGet"],
    lineCount: 7,
    bodyC: "u32 i, count;\n    for (i = 0, count = 0; i < REMATCH_SPECIAL_TRAINER_START; i++)\n    {\n        if (FlagGet(TRAINER_REGISTERED_FLAGS_START + i))\n            count++;\n    }\n\n    return count;",
  },
  "GetNumRematchTrainersFought": {
    returnType: "static u32",
    params: "void",
    callsTo: ["HasTrainerBeenFought"],
    lineCount: 7,
    bodyC: "u32 i, count;\n    for (i = 0, count = 0; i < REMATCH_SPECIAL_TRAINER_START; i++)\n    {\n        if (HasTrainerBeenFought(gRematchTable[i].trainerIds[0]))\n            count++;\n    }\n\n    return count;",
  },
  "GetPokedexRatingLevel": {
    returnType: "static u8",
    params: "u16 numSeen",
    callsTo: ["GetSetPokedexFlag","SpeciesToNationalPokedexNum"],
    lineCount: 48,
    bodyC: "if (numSeen < 10)\n        return 0;\n    if (numSeen < 20)\n        return 1;\n    if (numSeen < 30)\n        return 2;\n    if (numSeen < 40)\n        return 3;\n    if (numSeen < 50)\n        return 4;\n    if (numSeen < 60)\n        return 5;\n    if (numSeen < 70)\n        return 6;\n    if (numSeen < 80)\n        return 7;\n    if (numSeen < 90)\n        return 8;\n    if (numSeen < 100)\n        return 9;\n    if (numSeen < 110)\n        return 10;\n    if (numSeen < 120)\n        return 11;\n    if (numSeen < 130)\n        return 12;\n    if (numSeen < 140)\n        return 13;\n    if (numSeen < 150)\n        return 14;\n    if (numSeen < 160)\n        return 15;\n    if (numSeen < 170)\n        return 16;\n    if (numSeen < 180)\n        return 17;\n    if (numSeen < 190)\n        return 18;\n    if (numSeen < 200)\n        return 19;\n\n    if (GetSetPokedexFlag(SpeciesToNationalPokedexNum(SPECIES_DEOXYS), FLAG_GET_CAUGHT))\n        numSeen--;\n    if (GetSetPokedexFlag(SpeciesToNationalPokedexNum(SPECIES_JIRACHI), FLAG_GET_CAUGHT))\n        numSeen--;\n\n    if (numSeen < 200)\n        return 19;\n    else\n        return 20;",
  },
  "GetRematchTrainerLocation": {
    returnType: "static mapsec_u16_t",
    params: "int matchCallId",
    callsTo: ["Overworld_GetMapHeaderByGroupAndId"],
    lineCount: 2,
    bodyC: "const struct MapHeader *mapHeader = Overworld_GetMapHeaderByGroupAndId(gRematchTable[matchCallId].mapGroup, gRematchTable[matchCallId].mapNum);\n    return mapHeader->regionMapSectionId;",
  },
  "GetSameRouteMatchCallText": {
    returnType: "static const struct MatchCallText *",
    params: "int matchCallId, u8 *str",
    lineCount: 5,
    bodyC: "u16 textId = sMatchCallTrainers[matchCallId].sameRouteMatchCallTextId;\n    int mask = 0xFF;\n    u32 topic = (textId >> 8) - 1;\n    u32 id = (textId & mask) - 1;\n    return &sMatchCallBattleRequestTopics[topic][id];",
  },
  "GetTrainerMatchCallId": {
    returnType: "static int",
    params: "int trainerId",
    lineCount: 8,
    bodyC: "int i = 0;\n    while (1)\n    {\n        if (sMatchCallTrainers[i].trainerId == trainerId)\n            return i;\n        else\n            i++;\n    }",
  },
  "GetWaterEncounterSlot": {
    returnType: "static u8",
    params: "void",
    callsTo: ["Random"],
    lineCount: 11,
    bodyC: "int rand = Random() % 100;\n    if (rand < 60)\n        return 0;\n    else if (rand >= 60 && rand < 90)\n        return 1;\n    else if (rand >= 90 && rand < 95)\n        return 2;\n    else if (rand >= 95 && rand < 99)\n        return 3;\n    else\n        return 4;",
  },
  "InitMatchCallCounters": {
    returnType: "void",
    params: "void",
    callsTo: ["GetCurrentTotalMinutes","RtcCalcLocalTime"],
    lineCount: 3,
    bodyC: "RtcCalcLocalTime();\n    sMatchCallState.minutes = GetCurrentTotalMinutes(&gLocalTime) + 10;\n    sMatchCallState.stepCounter = 0;",
  },
  "InitMatchCallTextPrinter": {
    returnType: "static void",
    params: "int windowId, const u8 *str",
    callsTo: ["AddTextPrinter","GetPlayerTextSpeedDelay"],
    lineCount: 16,
    bodyC: "struct TextPrinterTemplate printerTemplate;\n    printerTemplate.currentChar = str;\n    printerTemplate.windowId = windowId;\n    printerTemplate.fontId = FONT_NORMAL;\n    printerTemplate.x = 32;\n    printerTemplate.y = 1;\n    printerTemplate.currentX = 32;\n    printerTemplate.currentY = 1;\n    printerTemplate.letterSpacing = 0;\n    printerTemplate.lineSpacing = 0;\n    printerTemplate.unk = 0;\n    printerTemplate.fgColor = TEXT_DYNAMIC_COLOR_1;\n    printerTemplate.bgColor = TEXT_COLOR_BLUE;\n    printerTemplate.shadowColor = TEXT_DYNAMIC_COLOR_5;\n    gTextFlags.useAlternateDownArrow = FALSE;\n\n    AddTextPrinter(&printerTemplate, GetPlayerTextSpeedDelay(), NULL);",
  },
  "IsMatchCallTaskActive": {
    returnType: "bool32",
    params: "void",
    callsTo: ["FuncIsActiveTask"],
    lineCount: 1,
    bodyC: "return FuncIsActiveTask(ExecuteMatchCall);",
  },
  "LoadMatchCallWindowGfx": {
    returnType: "void",
    params: "u32 windowId, u32 destOffset, u32 paletteId",
    callsTo: ["BG_PLTT_ID","GetWindowAttribute","LoadBgTiles","LoadPalette"],
    lineCount: 3,
    bodyC: "u8 bg = GetWindowAttribute(windowId, WINDOW_BG);\n    LoadBgTiles(bg, sMatchCallWindow_Gfx, 0x100, destOffset);\n    LoadPalette(sMatchCallWindow_Pal, BG_PLTT_ID(paletteId), sizeof(sMatchCallWindow_Pal));",
  },
  "MapAllowsMatchCall": {
    returnType: "static bool32",
    params: "void",
    callsTo: ["FlagGet","Overworld_MapTypeAllowsTeleportAndFly"],
    lineCount: 11,
    bodyC: "if (!Overworld_MapTypeAllowsTeleportAndFly(gMapHeader.mapType) || gMapHeader.regionMapSectionId == MAPSEC_SAFARI_ZONE)\n        return FALSE;\n\n    if (gMapHeader.regionMapSectionId == MAPSEC_SOOTOPOLIS_CITY\n     && FlagGet(FLAG_HIDE_SOOTOPOLIS_CITY_RAYQUAZA) == TRUE\n     && FlagGet(FLAG_NEVER_SET_0x0DC) == FALSE)\n        return FALSE;\n\n    if (gMapHeader.regionMapSectionId == MAPSEC_MT_CHIMNEY\n     && FlagGet(FLAG_MET_ARCHIE_METEOR_FALLS) == TRUE\n     && FlagGet(FLAG_DEFEATED_EVIL_TEAM_MT_CHIMNEY) == FALSE)\n        return FALSE;\n\n    return TRUE;",
  },
  "MatchCall_DrawWindow": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["CopyBgTilemapBufferToVram","CopyWindowToVram","CreateTask","DrawMatchCallTextBoxBorder_Internal","FreeTempTileDataBuffersIfPossible","PutWindowTilemap","WriteSequenceToBgTilemapBuffer"],
    lineCount: 10,
    bodyC: "s16 *data = gTasks[taskId].data;\n    if (FreeTempTileDataBuffersIfPossible())\n        return FALSE;\n\n    PutWindowTilemap(tWindowId);\n    DrawMatchCallTextBoxBorder_Internal(tWindowId, TILE_MC_WINDOW, 14);\n    WriteSequenceToBgTilemapBuffer(0, (0xF << 12) | TILE_POKENAV_ICON, 1, 15, 4, 4, 17, 1);\n    tIconTaskId = CreateTask(Task_SpinPokenavIcon, 10);\n    CopyWindowToVram(tWindowId, COPYWIN_GFX);\n    CopyBgTilemapBufferToVram(0);\n    return TRUE;",
  },
  "MatchCall_EndCall": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["ChangeBgY","GetObjectEventIdByLocalIdAndMap","IsDma3ManagerBusyWithBgCopy","IsSEPlaying","LoadMessageBoxAndBorderGfx","ObjectEventClearHeldMovementIfFinished","ScriptMovement_UnfreezeObjectEvents","UnfreezeObjectEvents","UnlockPlayerFieldControls"],
    lineCount: 16,
    bodyC: "u8 playerObjectId;\n    if (!IsDma3ManagerBusyWithBgCopy() && !IsSEPlaying())\n    {\n        ChangeBgY(0, 0, BG_COORD_SET);\n        if (!sMatchCallState.triggeredFromScript)\n        {\n            LoadMessageBoxAndBorderGfx();\n            playerObjectId = GetObjectEventIdByLocalIdAndMap(LOCALID_PLAYER, 0, 0);\n            ObjectEventClearHeldMovementIfFinished(&gObjectEvents[playerObjectId]);\n            ScriptMovement_UnfreezeObjectEvents();\n            UnfreezeObjectEvents();\n            UnlockPlayerFieldControls();\n        }\n\n        return TRUE;\n    }\n\n    return FALSE;",
  },
  "MatchCall_LoadGfx": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["AddWindow","BG_PLTT_ID","ChangeBgY","DecompressAndCopyTileDataToVram","DestroyTask","FillWindowPixelBuffer","LoadBgTiles","LoadPalette","PIXEL_FILL","RemoveWindow"],
    lineCount: 24,
    bodyC: "s16 *data = gTasks[taskId].data;\n    tWindowId = AddWindow(&sMatchCallTextWindow);\n    if (tWindowId == WINDOW_NONE)\n    {\n        DestroyTask(taskId);\n        return FALSE;\n    }\n\n    if (LoadBgTiles(0, sMatchCallWindow_Gfx, sizeof(sMatchCallWindow_Gfx), TILE_MC_WINDOW) == 0xFFFF)\n    {\n        RemoveWindow(tWindowId);\n        DestroyTask(taskId);\n        return FALSE;\n    }\n\n    if (!DecompressAndCopyTileDataToVram(0, sPokenavIcon_Gfx, 0, TILE_POKENAV_ICON, 0))\n    {\n        RemoveWindow(tWindowId);\n        DestroyTask(taskId);\n        return FALSE;\n    }\n\n    FillWindowPixelBuffer(tWindowId, PIXEL_FILL(8));\n    LoadPalette(sMatchCallWindow_Pal, BG_PLTT_ID(14), sizeof(sMatchCallWindow_Pal));\n    LoadPalette(sPokenavIcon_Pal, BG_PLTT_ID(15), sizeof(sPokenavIcon_Pal));\n    ChangeBgY(0, -0x2000, BG_COORD_SET);\n    return TRUE;",
  },
  "MatchCall_PrintIntro": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["FillWindowPixelBuffer","InitMatchCallTextPrinter","PIXEL_FILL","RunMatchCallTextPrinter","SelectMatchCallMessage"],
    lineCount: 10,
    bodyC: "s16 *data = gTasks[taskId].data;\n    if (!RunMatchCallTextPrinter(tWindowId))\n    {\n        FillWindowPixelBuffer(tWindowId, PIXEL_FILL(8));\n\n         \n        if (!sMatchCallState.triggeredFromScript)\n            SelectMatchCallMessage(sMatchCallState.trainerId, gStringVar4);\n        InitMatchCallTextPrinter(tWindowId, gStringVar4);\n        return TRUE;\n    }\n\n    return FALSE;",
  },
  "MatchCall_PrintMessage": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["CopyWindowToVram","FillWindowPixelBuffer","IsSEPlaying","JOY_NEW","PIXEL_FILL","PlaySE","RunMatchCallTextPrinter"],
    lineCount: 9,
    bodyC: "s16 *data = gTasks[taskId].data;\n    if (!RunMatchCallTextPrinter(tWindowId) && !IsSEPlaying() && JOY_NEW(A_BUTTON | B_BUTTON))\n    {\n        FillWindowPixelBuffer(tWindowId, PIXEL_FILL(8));\n        CopyWindowToVram(tWindowId, COPYWIN_GFX);\n        PlaySE(SE_POKENAV_HANG_UP);\n        return TRUE;\n    }\n\n    return FALSE;",
  },
  "MatchCall_ReadyIntro": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["InitMatchCallTextPrinter","IsDma3ManagerBusyWithBgCopy"],
    lineCount: 7,
    bodyC: "s16 *data = gTasks[taskId].data;\n    if (!IsDma3ManagerBusyWithBgCopy())\n    {\n         \n        InitMatchCallTextPrinter(tWindowId, sText_PokenavCallEllipsis);\n        return TRUE;\n    }\n\n    return FALSE;",
  },
  "MatchCall_SlideWindowIn": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["ChangeBgY"],
    lineCount: 6,
    bodyC: "if (ChangeBgY(0, 0x600, BG_COORD_ADD) >= 0)\n    {\n        ChangeBgY(0, 0, BG_COORD_SET);\n        return TRUE;\n    }\n\n    return FALSE;",
  },
  "MatchCall_SlideWindowOut": {
    returnType: "static bool32",
    params: "u8 taskId",
    callsTo: ["ChangeBgY","CopyBgTilemapBufferToVram","DestroyTask","FillBgTilemapBufferRect_Palette0","RemoveWindow"],
    lineCount: 10,
    bodyC: "s16 *data = gTasks[taskId].data;\n    if (ChangeBgY(0, 0x600, BG_COORD_SUB) <= -0x2000)\n    {\n        FillBgTilemapBufferRect_Palette0(0, 0, 0, 14, 30, 6);\n        DestroyTask(tIconTaskId);\n        RemoveWindow(tWindowId);\n        CopyBgTilemapBufferToVram(0);\n        return TRUE;\n    }\n\n    return FALSE;",
  },
  "PopulateBattleFrontierFacilityName": {
    returnType: "static void",
    params: "int matchCallId, u8 *destStr",
    callsTo: ["StringCopy"],
    lineCount: 1,
    bodyC: "StringCopy(destStr, sBattleFrontierFacilityNames[sBattleFrontierStreakInfo.facilityId]);",
  },
  "PopulateBattleFrontierStreak": {
    returnType: "static void",
    params: "int matchCallId, u8 *destStr",
    callsTo: ["ConvertIntToDecimalStringN"],
    lineCount: 8,
    bodyC: "int i = 0;\n    int streak = sBattleFrontierStreakInfo.streak;\n    while (streak != 0)\n    {\n        streak /= 10;\n        i++;\n    }\n\n    ConvertIntToDecimalStringN(destStr, sBattleFrontierStreakInfo.streak, STR_CONV_MODE_LEFT_ALIGN, i);",
  },
  "PopulateMapName": {
    returnType: "static void",
    params: "int matchCallId, u8 *destStr",
    callsTo: ["GetMapName","GetRematchTrainerLocation"],
    lineCount: 1,
    bodyC: "GetMapName(destStr, GetRematchTrainerLocation(matchCallId), 0);",
  },
  "PopulateMatchCallStringVar": {
    returnType: "static void",
    params: "int matchCallId, int funcId, u8 *destStr",
    lineCount: 1,
    bodyC: "sPopulateMatchCallStringVarFuncs[funcId](matchCallId, destStr);",
  },
  "PopulateMatchCallStringVars": {
    returnType: "static void",
    params: "int matchCallId, const s8 *stringVarFuncIds",
    callsTo: ["PopulateMatchCallStringVar"],
    lineCount: 6,
    bodyC: "int i;\n    for (i = 0; i < NUM_STRVARS_IN_MSG; i++)\n    {\n        if (stringVarFuncIds[i] >= 0)\n            PopulateMatchCallStringVar(matchCallId, stringVarFuncIds[i], sMatchCallTextStringVars[i]);\n    }",
  },
  "PopulateSpeciesFromTrainerLocation": {
    returnType: "static void",
    params: "int matchCallId, u8 *destStr",
    callsTo: ["GetLandEncounterSlot","GetWaterEncounterSlot","MAP_GROUP","Random","StringCopy"],
    lineCount: 36,
    bodyC: "u16 species[2];\n    int numSpecies;\n    u8 slot;\n    int i = 0;\n\n    if (gWildMonHeaders[i].mapGroup != MAP_GROUP(MAP_UNDEFINED))  \n    {\n        while (gWildMonHeaders[i].mapGroup != MAP_GROUP(MAP_UNDEFINED))\n        {\n            if (gWildMonHeaders[i].mapGroup == gRematchTable[matchCallId].mapGroup\n             && gWildMonHeaders[i].mapNum == gRematchTable[matchCallId].mapNum)\n                break;\n\n            i++;\n        }\n\n        if (gWildMonHeaders[i].mapGroup != MAP_GROUP(MAP_UNDEFINED))\n        {\n            numSpecies = 0;\n            if (gWildMonHeaders[i].landMonsInfo)\n            {\n                slot = GetLandEncounterSlot();\n                species[numSpecies] = gWildMonHeaders[i].landMonsInfo->wildPokemon[slot].species;\n                numSpecies++;\n            }\n\n            if (gWildMonHeaders[i].waterMonsInfo)\n            {\n                slot = GetWaterEncounterSlot();\n                species[numSpecies] = gWildMonHeaders[i].waterMonsInfo->wildPokemon[slot].species;\n                numSpecies++;\n            }\n\n            if (numSpecies)\n            {\n                StringCopy(destStr, gSpeciesNames[species[Random() % numSpecies]]);\n                return;\n            }\n        }\n    }\n\n    destStr[0] = EOS;",
  },
  "PopulateSpeciesFromTrainerParty": {
    returnType: "static void",
    params: "int matchCallId, u8 *destStr",
    callsTo: ["GetLastBeatenRematchTrainerId","Random","StringCopy"],
    lineCount: 24,
    bodyC: "u16 trainerId;\n    union TrainerMonPtr party;\n    u8 monId;\n    const u8 *speciesName;\n\n    trainerId = GetLastBeatenRematchTrainerId(sMatchCallTrainers[matchCallId].trainerId);\n    party = gTrainers[trainerId].party;\n    monId = Random() % gTrainers[trainerId].partySize;\n\n    switch (gTrainers[trainerId].partyFlags)\n    {\n    case 0:\n    default:\n        speciesName = gSpeciesNames[party.NoItemDefaultMoves[monId].species];\n        break;\n    case F_TRAINER_PARTY_CUSTOM_MOVESET:\n        speciesName = gSpeciesNames[party.NoItemCustomMoves[monId].species];\n        break;\n    case F_TRAINER_PARTY_HELD_ITEM:\n        speciesName = gSpeciesNames[party.ItemDefaultMoves[monId].species];\n        break;\n    case F_TRAINER_PARTY_CUSTOM_MOVESET | F_TRAINER_PARTY_HELD_ITEM:\n        speciesName = gSpeciesNames[party.ItemCustomMoves[monId].species];\n        break;\n    }\n\n    StringCopy(destStr, speciesName);",
  },
  "PopulateTrainerName": {
    returnType: "static void",
    params: "int matchCallId, u8 *destStr",
    callsTo: ["ARRAY_COUNT","StringCopy"],
    lineCount: 11,
    bodyC: "u32 i;\n    u16 trainerId = sMatchCallTrainers[matchCallId].trainerId;\n    for (i = 0; i < ARRAY_COUNT(sMultiTrainerMatchCallTexts); i++)\n    {\n        if (sMultiTrainerMatchCallTexts[i].trainerId == trainerId)\n        {\n            StringCopy(destStr, sMultiTrainerMatchCallTexts[i].text);\n            return;\n        }\n    }\n\n    StringCopy(destStr, gTrainers[trainerId].trainerName);",
  },
  "RunMatchCallTextPrinter": {
    returnType: "static bool32",
    params: "int windowId",
    callsTo: ["IsTextPrinterActive","JOY_HELD","RunTextPrinters"],
    lineCount: 6,
    bodyC: "if (JOY_HELD(A_BUTTON))\n        gTextFlags.canABSpeedUpPrint = TRUE;\n    else\n        gTextFlags.canABSpeedUpPrint = FALSE;\n\n    RunTextPrinters();\n    return IsTextPrinterActive(windowId);",
  },
  "SelectMatchCallMessage": {
    returnType: "bool32",
    params: "int trainerId, u8 *str",
    callsTo: ["BuildMatchCallString","GetBattleMatchCallText","GetDifferentRouteMatchCallText","GetGeneralMatchCallText","GetRematchTrainerLocation","GetSameRouteMatchCallText","GetTrainerMatchCallId","Random","ShouldTrainerRequestBattle","TrainerIsEligibleForRematch","UpdateRematchIfDefeated"],
    lineCount: 26,
    bodyC: "u32 matchCallId;\n    const struct MatchCallText *matchCallText;\n    bool32 newRematchRequest = FALSE;\n\n    matchCallId = GetTrainerMatchCallId(trainerId);\n    sBattleFrontierStreakInfo.facilityId = 0;\n\n     \n     \n    if (TrainerIsEligibleForRematch(matchCallId)\n     && GetRematchTrainerLocation(matchCallId) == gMapHeader.regionMapSectionId)\n    {\n        matchCallText = GetSameRouteMatchCallText(matchCallId, str);\n    }\n     \n     \n     \n    else if (ShouldTrainerRequestBattle(matchCallId))\n    {\n        matchCallText = GetDifferentRouteMatchCallText(matchCallId, str);\n        newRematchRequest = TRUE;\n        UpdateRematchIfDefeated(matchCallId);\n    }\n    else if (Random() % 3)\n    {\n         \n        matchCallText = GetBattleMatchCallText(matchCallId, str);\n    }\n    else\n    {\n         \n        matchCallText = GetGeneralMatchCallText(matchCallId, str);\n    }\n\n    BuildMatchCallString(matchCallId, matchCallText, str);\n    return newRematchRequest;",
  },
  "SelectMatchCallTrainer": {
    returnType: "static bool32",
    params: "void",
    callsTo: ["GetActiveMatchCallTrainerId","GetNumRegisteredTrainers","GetRematchTrainerLocation","GetTrainerMatchCallId","Random","TrainerIsEligibleForRematch"],
    lineCount: 12,
    bodyC: "u32 matchCallId;\n    u32 numRegistered = GetNumRegisteredTrainers();\n    if (numRegistered == 0)\n        return FALSE;\n\n    sMatchCallState.trainerId = GetActiveMatchCallTrainerId(Random() % numRegistered);\n    sMatchCallState.triggeredFromScript = FALSE;\n    if (sMatchCallState.trainerId == REMATCH_TABLE_ENTRIES)\n        return FALSE;\n\n    matchCallId = GetTrainerMatchCallId(sMatchCallState.trainerId);\n    if (GetRematchTrainerLocation(matchCallId) == gMapHeader.regionMapSectionId && !TrainerIsEligibleForRematch(matchCallId))\n        return FALSE;\n\n    return TRUE;",
  },
  "ShouldTrainerRequestBattle": {
    returnType: "static bool32",
    params: "int matchCallId",
    callsTo: ["GetGameStat","GetNthRematchTrainerFought","GetNumOwnedBadges","GetNumRematchTrainersFought","GetTrainerId","RtcGetLocalDayCount"],
    lineCount: 20,
    bodyC: "int dayCount;\n    int otId;\n    u16 dewfordRand;\n    int numRematchTrainersFought;\n    int max, rand, n;\n\n    if (GetNumOwnedBadges() < 5)\n        return FALSE;\n\n    dayCount = RtcGetLocalDayCount();\n    otId = GetTrainerId(gSaveBlock2Ptr->playerTrainerId) & 0xFFFF;\n\n    dewfordRand = gSaveBlock1Ptr->dewfordTrends[0].rand;\n    numRematchTrainersFought = GetNumRematchTrainersFought();\n    max = (numRematchTrainersFought * 13) / 10;\n    rand = ((dayCount ^ dewfordRand) + (dewfordRand ^ GetGameStat(GAME_STAT_TRAINER_BATTLES))) ^ otId;\n    n = rand % max;\n    if (n < numRematchTrainersFought)\n    {\n        if (GetNthRematchTrainerFought(n) == matchCallId)\n            return TRUE;\n    }\n\n    return FALSE;",
  },
  "StartMatchCall": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateTask","FreezeObjectEvents","LockPlayerFieldControls","PlaySE","PlayerFreeze","StopPlayerAvatar"],
    lineCount: 9,
    bodyC: "if (!sMatchCallState.triggeredFromScript)\n    {\n        LockPlayerFieldControls();\n        FreezeObjectEvents();\n        PlayerFreeze();\n        StopPlayerAvatar();\n    }\n\n    PlaySE(SE_POKENAV_CALL);\n    CreateTask(ExecuteMatchCall, 1);",
  },
  "StartMatchCallFromScript": {
    returnType: "void",
    params: "const u8 *message",
    callsTo: ["StartMatchCall"],
    lineCount: 2,
    bodyC: "sMatchCallState.triggeredFromScript = TRUE;\n    StartMatchCall();",
  },
  "Task_SpinPokenavIcon": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["CopyBgTilemapBufferToVram","WriteSequenceToBgTilemapBuffer"],
    lineCount: 10,
    bodyC: "s16 *data = gTasks[taskId].data;\n    if (++tTimer > 8)\n    {\n        tTimer = 0;\n        if (++tSpinStage > 7)\n            tSpinStage = 0;\n\n        tTileNum = (tSpinStage * 16) + TILE_POKENAV_ICON;\n        WriteSequenceToBgTilemapBuffer(0, tTileNum | ~0xFFF, 1, 15, 4, 4, 17, 1);\n        CopyBgTilemapBufferToVram(0);\n    }",
  },
  "TrainerIsEligibleForRematch": {
    returnType: "static bool32",
    params: "int matchCallId",
    lineCount: 1,
    bodyC: "return gSaveBlock1Ptr->trainerRematches[matchCallId] > 0;",
  },
  "TryStartMatchCall": {
    returnType: "bool32",
    params: "void",
    callsTo: ["CheckMatchCallChance","FlagGet","MapAllowsMatchCall","SelectMatchCallTrainer","StartMatchCall","UpdateMatchCallMinutesCounter","UpdateMatchCallStepCounter"],
    lineCount: 11,
    bodyC: "if (FlagGet(FLAG_HAS_MATCH_CALL)\n        && UpdateMatchCallStepCounter()\n        && UpdateMatchCallMinutesCounter()\n        && CheckMatchCallChance()\n        && MapAllowsMatchCall()\n        && SelectMatchCallTrainer())\n    {\n        StartMatchCall();\n        return TRUE;\n    }\n\n    return FALSE;",
  },
  "UpdateMatchCallMinutesCounter": {
    returnType: "static bool32",
    params: "void",
    callsTo: ["GetCurrentTotalMinutes","RtcCalcLocalTime"],
    lineCount: 9,
    bodyC: "int curMinutes;\n    RtcCalcLocalTime();\n    curMinutes = GetCurrentTotalMinutes(&gLocalTime);\n    if (sMatchCallState.minutes > curMinutes || curMinutes - sMatchCallState.minutes > 9)\n    {\n        sMatchCallState.minutes = curMinutes;\n        return TRUE;\n    }\n\n    return FALSE;",
  },
  "UpdateMatchCallStepCounter": {
    returnType: "static bool32",
    params: "void",
    lineCount: 9,
    bodyC: "if (++sMatchCallState.stepCounter >= 10)\n    {\n        sMatchCallState.stepCounter = 0;\n        return TRUE;\n    }\n    else\n    {\n        return FALSE;\n    }",
  },
} as const;
