// AUTO-GENERATED from src/menu.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 101

export const ENGINE_FUNCTIONS = {
  "AddMapNamePopUpWindow": {
    returnType: "u8",
    params: "void",
    callsTo: ["AddWindowParameterized"],
    lineCount: 3,
    bodyC: "if (sMapNamePopupWindowId == WINDOW_NONE)\n        sMapNamePopupWindowId = AddWindowParameterized(0, 1, 1, 10, 3, 14, 0x107);\n    return sMapNamePopupWindowId;",
  },
  "AddStartMenuWindow": {
    returnType: "u8",
    params: "u8 numActions",
    callsTo: ["AddWindowParameterized"],
    lineCount: 3,
    bodyC: "if (sStartMenuWindowId == WINDOW_NONE)\n        sStartMenuWindowId = AddWindowParameterized(0, 22, 1, 7, (numActions * 2) + 2, 15, 0x139);\n    return sStartMenuWindowId;",
  },
  "AddTextPrinterForMessage": {
    returnType: "void",
    params: "bool8 allowSkippingDelayWithButtonPress",
    callsTo: ["AddTextPrinterParameterized2","GetPlayerTextSpeedDelay"],
    lineCount: 3,
    bodyC: "void (*callback)(struct TextPrinterTemplate *, u16) = NULL;\n    gTextFlags.canABSpeedUpPrint = allowSkippingDelayWithButtonPress;\n    AddTextPrinterParameterized2(0, FONT_NORMAL, gStringVar4, GetPlayerTextSpeedDelay(), callback, TEXT_COLOR_DARK_GRAY, TEXT_COLOR_WHITE, TEXT_COLOR_LIGHT_GRAY);",
  },
  "AddTextPrinterForMessage_2": {
    returnType: "void",
    params: "bool8 allowSkippingDelayWithButtonPress",
    callsTo: ["AddTextPrinterParameterized2","GetPlayerTextSpeedDelay"],
    lineCount: 2,
    bodyC: "gTextFlags.canABSpeedUpPrint = allowSkippingDelayWithButtonPress;\n    AddTextPrinterParameterized2(0, FONT_NORMAL, gStringVar4, GetPlayerTextSpeedDelay(), NULL, TEXT_COLOR_DARK_GRAY, TEXT_COLOR_WHITE, TEXT_COLOR_LIGHT_GRAY);",
  },
  "AddTextPrinterParameterized2": {
    returnType: "u16",
    params: "u8 windowId, u8 fontId, const u8 *str, u8 speed, void (*callback)(struct TextPrinterTemplate *, u16), u8 fgColor, u8 bgColor, u8 shadowColor",
    callsTo: ["AddTextPrinter"],
    lineCount: 16,
    bodyC: "struct TextPrinterTemplate printer;\n\n    printer.currentChar = str;\n    printer.windowId = windowId;\n    printer.fontId = fontId;\n    printer.x = 0;\n    printer.y = 1;\n    printer.currentX = 0;\n    printer.currentY = 1;\n    printer.letterSpacing = 0;\n    printer.lineSpacing = 0;\n    printer.unk = 0;\n    printer.fgColor = fgColor;\n    printer.bgColor = bgColor;\n    printer.shadowColor = shadowColor;\n\n    gTextFlags.useAlternateDownArrow = 0;\n    return AddTextPrinter(&printer, speed, callback);",
  },
  "AddTextPrinterParameterized3": {
    returnType: "void",
    params: "u8 windowId, u8 fontId, u8 left, u8 top, const u8 *color, s8 speed, const u8 *str",
    callsTo: ["AddTextPrinter","GetFontAttribute"],
    lineCount: 15,
    bodyC: "struct TextPrinterTemplate printer;\n\n    printer.currentChar = str;\n    printer.windowId = windowId;\n    printer.fontId = fontId;\n    printer.x = left;\n    printer.y = top;\n    printer.currentX = printer.x;\n    printer.currentY = printer.y;\n    printer.letterSpacing = GetFontAttribute(fontId, FONTATTR_LETTER_SPACING);\n    printer.lineSpacing = GetFontAttribute(fontId, FONTATTR_LINE_SPACING);\n    printer.unk = 0;\n    printer.fgColor = color[1];\n    printer.bgColor = color[0];\n    printer.shadowColor = color[2];\n\n    AddTextPrinter(&printer, speed, NULL);",
  },
  "AddTextPrinterParameterized4": {
    returnType: "void",
    params: "u8 windowId, u8 fontId, u8 left, u8 top, u8 letterSpacing, u8 lineSpacing, const u8 *color, s8 speed, const u8 *str",
    callsTo: ["AddTextPrinter"],
    lineCount: 15,
    bodyC: "struct TextPrinterTemplate printer;\n\n    printer.currentChar = str;\n    printer.windowId = windowId;\n    printer.fontId = fontId;\n    printer.x = left;\n    printer.y = top;\n    printer.currentX = printer.x;\n    printer.currentY = printer.y;\n    printer.letterSpacing = letterSpacing;\n    printer.lineSpacing = lineSpacing;\n    printer.unk = 0;\n    printer.fgColor = color[1];\n    printer.bgColor = color[0];\n    printer.shadowColor = color[2];\n\n    AddTextPrinter(&printer, speed, NULL);",
  },
  "AddTextPrinterParameterized5": {
    returnType: "void",
    params: "u8 windowId, u8 fontId, const u8 *str, u8 left, u8 top, u8 speed, void (*callback)(struct TextPrinterTemplate *, u16), u8 letterSpacing, u8 lineSpacing",
    callsTo: ["AddTextPrinter","GetFontAttribute"],
    lineCount: 15,
    bodyC: "struct TextPrinterTemplate printer;\n\n    printer.currentChar = str;\n    printer.windowId = windowId;\n    printer.fontId = fontId;\n    printer.x = left;\n    printer.y = top;\n    printer.currentX = left;\n    printer.currentY = top;\n    printer.letterSpacing = letterSpacing;\n    printer.lineSpacing = lineSpacing;\n    printer.unk = 0;\n\n    printer.fgColor = GetFontAttribute(fontId, FONTATTR_COLOR_FOREGROUND);\n    printer.bgColor = GetFontAttribute(fontId, FONTATTR_COLOR_BACKGROUND);\n    printer.shadowColor = GetFontAttribute(fontId, FONTATTR_COLOR_SHADOW);\n\n    AddTextPrinter(&printer, speed, callback);",
  },
  "AddTextPrinterWithCallbackForMessage": {
    returnType: "void",
    params: "bool8 canSpeedUp, void (*callback)(struct TextPrinterTemplate *, u16)",
    callsTo: ["AddTextPrinterParameterized2","GetPlayerTextSpeedDelay"],
    lineCount: 2,
    bodyC: "gTextFlags.canABSpeedUpPrint = canSpeedUp;\n    AddTextPrinterParameterized2(0, FONT_NORMAL, gStringVar4, GetPlayerTextSpeedDelay(), callback, TEXT_COLOR_DARK_GRAY, TEXT_COLOR_WHITE, TEXT_COLOR_LIGHT_GRAY);",
  },
  "AddTextPrinterWithCustomSpeedForMessage": {
    returnType: "void",
    params: "bool8 allowSkippingDelayWithButtonPress, u8 speed",
    callsTo: ["AddTextPrinterParameterized2"],
    lineCount: 2,
    bodyC: "gTextFlags.canABSpeedUpPrint = allowSkippingDelayWithButtonPress;\n    AddTextPrinterParameterized2(0, FONT_NORMAL, gStringVar4, speed, NULL, TEXT_COLOR_DARK_GRAY, TEXT_COLOR_WHITE, TEXT_COLOR_LIGHT_GRAY);",
  },
  "AddValToTilemapBuffer": {
    returnType: "void",
    params: "void *ptr, int delta, int width, int height, bool32 isAffine",
    lineCount: 14,
    bodyC: "int i;\n    int area = width * height;\n    if (isAffine == TRUE)\n    {\n        u8 *as8BPP = ptr;\n        for (i = 0; i < area; i++)\n            as8BPP[i] += delta;\n    }\n    else\n    {\n         \n        u16 *as4BPP = ptr;\n        for (i = 0; i < area; i++)\n            as4BPP[i] = (as4BPP[i] & 0xFC00) | ((as4BPP[i] + delta) & 0x3FF);\n    }",
  },
  "AddWindowParameterized": {
    returnType: "u16",
    params: "u8 bg, u8 left, u8 top, u8 width, u8 height, u8 paletteNum, u16 baseBlock",
    callsTo: ["AddWindow","SetWindowTemplateFields"],
    lineCount: 3,
    bodyC: "struct WindowTemplate template;\n    SetWindowTemplateFields(&template, bg, left, top, width, height, paletteNum, baseBlock);\n    return AddWindow(&template);",
  },
  "BgDmaFill": {
    returnType: "void",
    params: "u32 bg, u8 value, int offset, int size",
    callsTo: ["GetBgAttribute","RequestDma3Fill"],
    lineCount: 3,
    bodyC: "int temp = (!GetBgAttribute(bg, BG_ATTR_PALETTEMODE)) ? 32 : 64;\n    void *addr = (void *)((GetBgAttribute(bg, BG_ATTR_CHARBASEINDEX) * 0x4000) + (GetBgAttribute(bg, BG_ATTR_BASETILE) + offset) * temp);\n    RequestDma3Fill(value << 24 | value << 16 | value << 8 | value, VRAM + addr, size * temp, 1);",
  },
  "BlitMenuInfoIcon": {
    returnType: "void",
    params: "u8 windowId, u8 iconId, u16 x, u16 y",
    callsTo: ["BlitBitmapRectToWindow"],
    lineCount: 1,
    bodyC: "BlitBitmapRectToWindow(windowId, &gMenuInfoElements_Gfx[sMenuInfoIcons[iconId].offset * 32], 0, 0, 128, 128, x, y, sMenuInfoIcons[iconId].width, sMenuInfoIcons[iconId].height);",
  },
  "BufferSaveMenuText": {
    returnType: "void",
    params: "u8 textId, u8 *dest, u8 color",
    callsTo: ["ConvertIntToDecimalStringN","FlagGet","GetHoennPokedexCount","GetMapNameGeneric","GetNationalPokedexCount","IsNationalPokedexEnabled","StringCopy"],
    lineCount: 40,
    bodyC: "s32 curFlag;\n    s32 flagCount;\n    u8 *endOfString;\n    u8 *string = dest;\n\n    *(string++) = EXT_CTRL_CODE_BEGIN;\n    *(string++) = EXT_CTRL_CODE_COLOR;\n    *(string++) = color;\n    *(string++) = EXT_CTRL_CODE_BEGIN;\n    *(string++) = EXT_CTRL_CODE_SHADOW;\n    *(string++) = color + 1;\n\n    switch (textId)\n    {\n        case SAVE_MENU_NAME:\n            StringCopy(string, gSaveBlock2Ptr->playerName);\n            break;\n        case SAVE_MENU_CAUGHT:\n            if (IsNationalPokedexEnabled())\n                string = ConvertIntToDecimalStringN(string, GetNationalPokedexCount(FLAG_GET_CAUGHT), STR_CONV_MODE_LEFT_ALIGN, 3);\n            else\n                string = ConvertIntToDecimalStringN(string, GetHoennPokedexCount(FLAG_GET_CAUGHT), STR_CONV_MODE_LEFT_ALIGN, 3);\n            *string = EOS;\n            break;\n        case SAVE_MENU_PLAY_TIME:\n            string = ConvertIntToDecimalStringN(string, gSaveBlock2Ptr->playTimeHours, STR_CONV_MODE_LEFT_ALIGN, 3);\n            *(string++) = CHAR_COLON;\n            ConvertIntToDecimalStringN(string, gSaveBlock2Ptr->playTimeMinutes, STR_CONV_MODE_LEADING_ZEROS, 2);\n            break;\n        case SAVE_MENU_LOCATION:\n            GetMapNameGeneric(string, gMapHeader.regionMapSectionId);\n            break;\n        case SAVE_MENU_BADGES:\n            for (curFlag = FLAG_BADGE01_GET, flagCount = 0, endOfString = string + 1; curFlag < FLAG_BADGE01_GET + NUM_BADGES; curFlag++)\n            {\n                if (FlagGet(curFlag))\n                    flagCount++;\n            }\n            *string = flagCount + CHAR_0;\n            *endOfString = EOS;\n            break;\n    }",
  },
  "ChangeGridMenuCursorPosition": {
    returnType: "u8",
    params: "s8 deltaX, s8 deltaY",
    callsTo: ["MoveMenuGridCursor"],
    lineCount: 27,
    bodyC: "u8 oldPos = sMenu.cursorPos;\n\n    if (deltaX != 0)\n    {\n        if (((sMenu.cursorPos % sMenu.columns) + deltaX >= 0) &&\n        ((sMenu.cursorPos % sMenu.columns) + deltaX < sMenu.columns))\n        {\n            sMenu.cursorPos += deltaX;\n        }\n    }\n\n    if (deltaY != 0)\n    {\n        if (((sMenu.cursorPos / sMenu.columns) + deltaY >= 0) &&\n        ((sMenu.cursorPos / sMenu.columns) + deltaY < sMenu.rows))\n        {\n            sMenu.cursorPos += (sMenu.columns * deltaY);\n        }\n    }\n\n    if (sMenu.cursorPos > sMenu.maxCursorPos)\n    {\n        sMenu.cursorPos = oldPos;\n        return sMenu.cursorPos;\n    }\n    else\n    {\n        MoveMenuGridCursor(oldPos, sMenu.cursorPos);\n        return sMenu.cursorPos;\n    }",
  },
  "ChangeMenuGridCursorPosition": {
    returnType: "u8",
    params: "s8 deltaX, s8 deltaY",
    callsTo: ["MoveMenuGridCursor"],
    lineCount: 29,
    bodyC: "u8 oldPos = sMenu.cursorPos;\n\n    if (deltaX != 0)\n    {\n        if ((sMenu.cursorPos % sMenu.columns) + deltaX < 0)\n            sMenu.cursorPos += sMenu.columns - 1;\n        else if ((sMenu.cursorPos % sMenu.columns) + deltaX >= sMenu.columns)\n            sMenu.cursorPos = (sMenu.cursorPos / sMenu.columns) * sMenu.columns;\n        else\n            sMenu.cursorPos += deltaX;\n    }\n\n    if (deltaY != 0)\n    {\n        if ((sMenu.cursorPos / sMenu.columns) + deltaY < 0)\n            sMenu.cursorPos += sMenu.columns * (sMenu.rows - 1);\n        else if ((sMenu.cursorPos / sMenu.columns) + deltaY >= sMenu.rows)\n            sMenu.cursorPos -= sMenu.columns * (sMenu.rows - 1);\n        else\n            sMenu.cursorPos += (sMenu.columns * deltaY);\n    }\n\n    if (sMenu.cursorPos > sMenu.maxCursorPos)\n    {\n        sMenu.cursorPos = oldPos;\n        return sMenu.cursorPos;\n    }\n    else\n    {\n        MoveMenuGridCursor(oldPos, sMenu.cursorPos);\n        return sMenu.cursorPos;\n    }",
  },
  "ClearDialogWindowAndFrame": {
    returnType: "void",
    params: "u8 windowId, bool8 copyToVram",
    callsTo: ["CallWindowFunction","ClearWindowTilemap","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL"],
    lineCount: 5,
    bodyC: "CallWindowFunction(windowId, WindowFunc_ClearDialogWindowAndFrame);\n    FillWindowPixelBuffer(windowId, PIXEL_FILL(1));\n    ClearWindowTilemap(windowId);\n    if (copyToVram == TRUE)\n        CopyWindowToVram(windowId, COPYWIN_FULL);",
  },
  "ClearDialogWindowAndFrameToTransparent": {
    returnType: "void",
    params: "u8 windowId, bool8 copyToVram",
    callsTo: ["CallWindowFunction","ClearWindowTilemap","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL"],
    lineCount: 5,
    bodyC: "CallWindowFunction(windowId, WindowFunc_ClearDialogWindowAndFrameNullPalette);\n    FillWindowPixelBuffer(windowId, PIXEL_FILL(0));\n    ClearWindowTilemap(windowId);\n    if (copyToVram == TRUE)\n        CopyWindowToVram(windowId, COPYWIN_FULL);",
  },
  "ClearScheduledBgCopiesToVram": {
    returnType: "void",
    params: "void",
    callsTo: ["memset"],
    lineCount: 1,
    bodyC: "memset(sScheduledBgCopiesToVram, 0, sizeof(sScheduledBgCopiesToVram));",
  },
  "ClearStdWindowAndFrame": {
    returnType: "void",
    params: "u8 windowId, bool8 copyToVram",
    callsTo: ["CallWindowFunction","ClearWindowTilemap","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL"],
    lineCount: 5,
    bodyC: "CallWindowFunction(windowId, WindowFunc_ClearStdWindowAndFrame);\n    FillWindowPixelBuffer(windowId, PIXEL_FILL(1));\n    ClearWindowTilemap(windowId);\n    if (copyToVram == TRUE)\n        CopyWindowToVram(windowId, COPYWIN_FULL);",
  },
  "ClearStdWindowAndFrameToTransparent": {
    returnType: "void",
    params: "u8 windowId, bool8 copyToVram",
    callsTo: ["CallWindowFunction","ClearWindowTilemap","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL"],
    lineCount: 5,
    bodyC: "CallWindowFunction(windowId, WindowFunc_ClearStdWindowAndFrameToTransparent);\n    FillWindowPixelBuffer(windowId, PIXEL_FILL(0));\n    ClearWindowTilemap(windowId);\n    if (copyToVram == TRUE)\n        CopyWindowToVram(windowId, COPYWIN_FULL);",
  },
  "CopyToBufferFromBgTilemap": {
    returnType: "void",
    params: "u8 bgId, u16 *dest, u8 left, u8 top, u8 width, u8 height",
    callsTo: ["GetBgTilemapBuffer"],
    lineCount: 8,
    bodyC: "u8 i;\n    u8 j;\n    const u16 *src = GetBgTilemapBuffer(bgId);\n\n    for (i = 0; i < height; i++)\n    {\n        for (j = 0; j < width; j++)\n            dest[(i * width) + j] = src[(i + top) * 32 + j + left];\n    }",
  },
  "CreateWindowTemplate": {
    returnType: "struct WindowTemplate",
    params: "u8 bg, u8 left, u8 top, u8 width, u8 height, u8 paletteNum, u16 baseBlock",
    callsTo: ["SetWindowTemplateFields"],
    lineCount: 3,
    bodyC: "struct WindowTemplate template;\n    SetWindowTemplateFields(&template, bg, left, top, width, height, paletteNum, baseBlock);\n    return template;",
  },
  "CreateYesNoMenu": {
    returnType: "void",
    params: "const struct WindowTemplate *window, u16 baseTileNum, u8 paletteNum, u8 initialCursorPos",
    callsTo: ["AddTextPrinter","AddWindow","DrawStdFrameWithCustomTileAndPalette","GetFontAttribute","InitMenuInUpperLeftCornerNormal"],
    lineCount: 18,
    bodyC: "struct TextPrinterTemplate printer;\n\n    sYesNoWindowId = AddWindow(window);\n    DrawStdFrameWithCustomTileAndPalette(sYesNoWindowId, TRUE, baseTileNum, paletteNum);\n\n    printer.currentChar = gText_YesNo;\n    printer.windowId = sYesNoWindowId;\n    printer.fontId = FONT_NORMAL;\n    printer.x = 8;\n    printer.y = 1;\n    printer.currentX = printer.x;\n    printer.currentY = printer.y;\n    printer.fgColor = GetFontAttribute(FONT_NORMAL, FONTATTR_COLOR_FOREGROUND);\n    printer.bgColor = GetFontAttribute(FONT_NORMAL, FONTATTR_COLOR_BACKGROUND);\n    printer.shadowColor = GetFontAttribute(FONT_NORMAL, FONTATTR_COLOR_SHADOW);\n    printer.unk = GetFontAttribute(FONT_NORMAL, FONTATTR_UNKNOWN);\n    printer.letterSpacing = 0;\n    printer.lineSpacing = 0;\n\n    AddTextPrinter(&printer, TEXT_SKIP_DRAW, NULL);\n    InitMenuInUpperLeftCornerNormal(sYesNoWindowId, 2, initialCursorPos);",
  },
  "CreateYesNoMenuAtPos": {
    returnType: "static void",
    params: "const struct WindowTemplate *window, u8 fontId, u8 left, u8 top, u16 baseTileNum, u8 paletteNum, u8 initialCursorPos",
    callsTo: ["AddTextPrinter","AddWindow","DrawStdFrameWithCustomTileAndPalette","GetFontAttribute","InitMenuNormal"],
    lineCount: 18,
    bodyC: "struct TextPrinterTemplate printer;\n\n    sYesNoWindowId = AddWindow(window);\n    DrawStdFrameWithCustomTileAndPalette(sYesNoWindowId, TRUE, baseTileNum, paletteNum);\n\n    printer.currentChar = gText_YesNo;\n    printer.windowId = sYesNoWindowId;\n    printer.fontId = fontId;\n    printer.x = GetFontAttribute(fontId, FONTATTR_MAX_LETTER_WIDTH) + left;\n    printer.y = top;\n    printer.currentX = printer.x;\n    printer.currentY = printer.y;\n    printer.fgColor = GetFontAttribute(fontId, FONTATTR_COLOR_FOREGROUND);\n    printer.bgColor = GetFontAttribute(fontId, FONTATTR_COLOR_BACKGROUND);\n    printer.shadowColor = GetFontAttribute(fontId, FONTATTR_COLOR_SHADOW);\n    printer.unk = GetFontAttribute(fontId, FONTATTR_UNKNOWN);\n    printer.letterSpacing = GetFontAttribute(fontId, FONTATTR_LETTER_SPACING);\n    printer.lineSpacing = GetFontAttribute(fontId, FONTATTR_LINE_SPACING);\n\n    AddTextPrinter(&printer, TEXT_SKIP_DRAW, NULL);\n\n    InitMenuNormal(sYesNoWindowId, fontId, left, top, GetFontAttribute(fontId, FONTATTR_MAX_LETTER_HEIGHT), 2, initialCursorPos);",
  },
  "DecompressAndCopyTileDataToVram": {
    returnType: "void *",
    params: "u8 bgId, const void *src, u32 size, u16 offset, u8 mode",
    callsTo: ["ARRAY_COUNT","copy_decompressed_tile_data_to_vram","malloc_and_decompress"],
    lineCount: 14,
    bodyC: "u32 sizeOut;\n    if (sTempTileDataBufferIdx < ARRAY_COUNT(sTempTileDataBuffer))\n    {\n        void *ptr = malloc_and_decompress(src, &sizeOut);\n        if (!size)\n            size = sizeOut;\n        if (ptr)\n        {\n            copy_decompressed_tile_data_to_vram(bgId, ptr, size, offset, mode);\n            sTempTileDataBuffer[sTempTileDataBufferIdx++] = ptr;\n        }\n        return ptr;\n    }\n    return NULL;",
  },
  "DecompressAndLoadBgGfxUsingHeap": {
    returnType: "void",
    params: "u8 bgId, const void *src, u32 size, u16 offset, u8 mode",
    callsTo: ["CreateTask","SetWordTaskArg","copy_decompressed_tile_data_to_vram","malloc_and_decompress"],
    lineCount: 10,
    bodyC: "u32 sizeOut;\n    void *ptr = malloc_and_decompress(src, &sizeOut);\n    if (!size)\n        size = sizeOut;\n    if (ptr)\n    {\n        u8 taskId = CreateTask(task_free_buf_after_copying_tile_data_to_vram, 0);\n        gTasks[taskId].data[0] = copy_decompressed_tile_data_to_vram(bgId, ptr, size, offset, mode);\n        SetWordTaskArg(taskId, 1, (u32)ptr);\n    }",
  },
  "DisplayItemMessageOnField": {
    returnType: "void",
    params: "u8 taskId, const u8 *string, TaskFunc callback",
    callsTo: ["CopyWindowToVram","DisplayMessageAndContinueTask","GetPlayerTextSpeedDelay","LoadMessageBoxAndBorderGfx"],
    lineCount: 3,
    bodyC: "LoadMessageBoxAndBorderGfx();\n    DisplayMessageAndContinueTask(taskId, 0, DLG_WINDOW_BASE_TILE_NUM, DLG_WINDOW_PALETTE_NUM, FONT_NORMAL, GetPlayerTextSpeedDelay(), string, callback);\n    CopyWindowToVram(0, COPYWIN_FULL);",
  },
  "DisplayYesNoMenuDefaultYes": {
    returnType: "void",
    params: "void",
    callsTo: ["CreateYesNoMenu"],
    lineCount: 1,
    bodyC: "CreateYesNoMenu(&sYesNo_WindowTemplates, STD_WINDOW_BASE_TILE_NUM, STD_WINDOW_PALETTE_NUM, 0);",
  },
  "DisplayYesNoMenuWithDefault": {
    returnType: "void",
    params: "u8 initialCursorPos",
    callsTo: ["CreateYesNoMenu"],
    lineCount: 1,
    bodyC: "CreateYesNoMenu(&sYesNo_WindowTemplates, STD_WINDOW_BASE_TILE_NUM, STD_WINDOW_PALETTE_NUM, initialCursorPos);",
  },
  "DoScheduledBgTilemapCopiesToVram": {
    returnType: "void",
    params: "void",
    callsTo: ["CopyBgTilemapBufferToVram"],
    lineCount: 20,
    bodyC: "if (sScheduledBgCopiesToVram[0] == TRUE)\n    {\n        CopyBgTilemapBufferToVram(0);\n        sScheduledBgCopiesToVram[0] = FALSE;\n    }\n    if (sScheduledBgCopiesToVram[1] == TRUE)\n    {\n        CopyBgTilemapBufferToVram(1);\n        sScheduledBgCopiesToVram[1] = FALSE;\n    }\n    if (sScheduledBgCopiesToVram[2] == TRUE)\n    {\n        CopyBgTilemapBufferToVram(2);\n        sScheduledBgCopiesToVram[2] = FALSE;\n    }\n    if (sScheduledBgCopiesToVram[3] == TRUE)\n    {\n        CopyBgTilemapBufferToVram(3);\n        sScheduledBgCopiesToVram[3] = FALSE;\n    }",
  },
  "DrawDialogFrameWithCustomTileAndPalette": {
    returnType: "void",
    params: "u8 windowId, bool8 copyToVram, u16 tileNum, u8 paletteNum",
    callsTo: ["CallWindowFunction","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL","PutWindowTilemap"],
    lineCount: 7,
    bodyC: "sTileNum = tileNum;\n    sPaletteNum = paletteNum;\n    CallWindowFunction(windowId, WindowFunc_DrawDialogFrameWithCustomTileAndPalette);\n    FillWindowPixelBuffer(windowId, PIXEL_FILL(1));\n    PutWindowTilemap(windowId);\n    if (copyToVram == TRUE)\n        CopyWindowToVram(windowId, COPYWIN_FULL);",
  },
  "DrawDialogueFrame": {
    returnType: "void",
    params: "u8 windowId, bool8 copyToVram",
    callsTo: ["CallWindowFunction","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL","PutWindowTilemap"],
    lineCount: 5,
    bodyC: "CallWindowFunction(windowId, WindowFunc_DrawDialogueFrame);\n    FillWindowPixelBuffer(windowId, PIXEL_FILL(1));\n    PutWindowTilemap(windowId);\n    if (copyToVram == TRUE)\n        CopyWindowToVram(windowId, COPYWIN_FULL);",
  },
  "DrawStdFrameWithCustomTile": {
    returnType: "void",
    params: "u8 windowId, bool8 copyToVram, u16 baseTileNum",
    callsTo: ["CallWindowFunction","CopyWindowToVram","FillWindowPixelBuffer","GetWindowAttribute","PIXEL_FILL","PutWindowTilemap"],
    lineCount: 7,
    bodyC: "sTileNum = baseTileNum;\n    sPaletteNum = GetWindowAttribute(windowId, WINDOW_PALETTE_NUM);\n    CallWindowFunction(windowId, WindowFunc_DrawStdFrameWithCustomTileAndPalette);\n    FillWindowPixelBuffer(windowId, PIXEL_FILL(1));\n    PutWindowTilemap(windowId);\n    if (copyToVram == TRUE)\n        CopyWindowToVram(windowId, COPYWIN_FULL);",
  },
  "DrawStdFrameWithCustomTileAndPalette": {
    returnType: "void",
    params: "u8 windowId, bool8 copyToVram, u16 baseTileNum, u8 paletteNum",
    callsTo: ["CallWindowFunction","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL","PutWindowTilemap"],
    lineCount: 7,
    bodyC: "sTileNum = baseTileNum;\n    sPaletteNum = paletteNum;\n    CallWindowFunction(windowId, WindowFunc_DrawStdFrameWithCustomTileAndPalette);\n    FillWindowPixelBuffer(windowId, PIXEL_FILL(1));\n    PutWindowTilemap(windowId);\n    if (copyToVram == TRUE)\n        CopyWindowToVram(windowId, COPYWIN_FULL);",
  },
  "DrawStdWindowFrame": {
    returnType: "void",
    params: "u8 windowId, bool8 copyToVram",
    callsTo: ["CallWindowFunction","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL","PutWindowTilemap"],
    lineCount: 5,
    bodyC: "CallWindowFunction(windowId, WindowFunc_DrawStandardFrame);\n    FillWindowPixelBuffer(windowId, PIXEL_FILL(1));\n    PutWindowTilemap(windowId);\n    if (copyToVram == TRUE)\n        CopyWindowToVram(windowId, COPYWIN_FULL);",
  },
  "EraseFieldMessageBox": {
    returnType: "void",
    params: "bool8 copyToVram",
    callsTo: ["CopyBgTilemapBufferToVram","FillBgTilemapBufferRect"],
    lineCount: 3,
    bodyC: "FillBgTilemapBufferRect(0, 0, 0, 0, 32, 32, 17);\n    if (copyToVram == TRUE)\n        CopyBgTilemapBufferToVram(0);",
  },
  "EraseYesNoWindow": {
    returnType: "void",
    params: "void",
    callsTo: ["ClearStdWindowAndFrameToTransparent","RemoveWindow"],
    lineCount: 2,
    bodyC: "ClearStdWindowAndFrameToTransparent(sYesNoWindowId, TRUE);\n    RemoveWindow(sYesNoWindowId);",
  },
  "FreeAllOverworldWindowBuffers": {
    returnType: "void",
    params: "void",
    callsTo: ["FreeAllWindowBuffers"],
    lineCount: 1,
    bodyC: "FreeAllWindowBuffers();",
  },
  "FreeTempTileDataBuffersIfPossible": {
    returnType: "bool8",
    params: "void",
    callsTo: ["FREE_AND_SET_NULL","IsDma3ManagerBusyWithBgCopy"],
    lineCount: 15,
    bodyC: "int i;\n\n    if (!IsDma3ManagerBusyWithBgCopy())\n    {\n        if (sTempTileDataBufferIdx)\n        {\n            for (i = 0; i < sTempTileDataBufferIdx; i++)\n                FREE_AND_SET_NULL(sTempTileDataBuffer[i]);\n            sTempTileDataBufferIdx = 0;\n        }\n        return FALSE;\n    }\n    else\n    {\n        return TRUE;\n    }",
  },
  "GetMapNamePopUpWindowId": {
    returnType: "u8",
    params: "void",
    lineCount: 1,
    bodyC: "return sMapNamePopupWindowId;",
  },
  "GetPlayerTextSpeed": {
    returnType: "u32",
    params: "void",
    lineCount: 3,
    bodyC: "if (gTextFlags.forceMidTextSpeed)\n        return OPTIONS_TEXT_SPEED_MID;\n    return gSaveBlock2Ptr->optionsTextSpeed;",
  },
  "GetPlayerTextSpeedDelay": {
    returnType: "u8",
    params: "void",
    callsTo: ["GetPlayerTextSpeed"],
    lineCount: 5,
    bodyC: "u32 speed;\n    if (gSaveBlock2Ptr->optionsTextSpeed > OPTIONS_TEXT_SPEED_FAST)\n        gSaveBlock2Ptr->optionsTextSpeed = OPTIONS_TEXT_SPEED_MID;\n    speed = GetPlayerTextSpeed();\n    return sTextSpeedFrameDelays[speed];",
  },
  "GetStartMenuWindowId": {
    returnType: "u8",
    params: "void",
    lineCount: 1,
    bodyC: "return sStartMenuWindowId;",
  },
  "HofPCTopBar_AddWindow": {
    returnType: "u8",
    params: "u8 bg, u8 xPos, u8 yPos, u8 palette, u16 baseTile",
    callsTo: ["AddWindow","BG_PLTT_ID","LoadPalette","memset"],
    lineCount: 19,
    bodyC: "struct WindowTemplate window;\n    memset(&window, 0, sizeof(window));\n\n    if (bg > 3)\n        window.bg = 0;\n    else\n        window.bg = bg;\n\n    window.tilemapTop = yPos;\n    window.height = 2;\n    window.tilemapLeft = 30 - xPos;\n    window.width = xPos;\n    window.paletteNum = palette;\n    window.baseBlock = baseTile;\n\n    sHofPCTopBarWindowId = AddWindow(&window);\n\n    if (palette > 15)\n        palette = BG_PLTT_ID(15);\n    else\n        palette = BG_PLTT_ID(palette);\n\n    LoadPalette(sHofPC_TopBar_Pal, palette, sizeof(sHofPC_TopBar_Pal));\n    return sHofPCTopBarWindowId;",
  },
  "HofPCTopBar_Print": {
    returnType: "void",
    params: "const u8 *string, u8 left, bool8 copyToVram",
    callsTo: ["AddTextPrinterParameterized3","CopyWindowToVram","FillWindowPixelBuffer","GetStringWidth","GetWindowAttribute","PIXEL_FILL","PutWindowTilemap"],
    lineCount: 16,
    bodyC: "u16 width = 0;\n\n    if (sHofPCTopBarWindowId != WINDOW_NONE)\n    {\n        PutWindowTilemap(sHofPCTopBarWindowId);\n        FillWindowPixelBuffer(sHofPCTopBarWindowId, PIXEL_FILL(15));\n        width = GetStringWidth(FONT_SMALL, string, 0);\n        AddTextPrinterParameterized3(sHofPCTopBarWindowId,\n                  FONT_SMALL,\n                  236 - (GetWindowAttribute(sHofPCTopBarWindowId, WINDOW_TILEMAP_LEFT) * 8) - left - width,\n                  1,\n                  sTextColors,\n                  0,\n                  string);\n        if (copyToVram)\n            CopyWindowToVram(sHofPCTopBarWindowId, COPYWIN_FULL);\n    }",
  },
  "HofPCTopBar_PrintPair": {
    returnType: "void",
    params: "const u8 *string, const u8 *string2, bool8 noBg, u8 left, bool8 copyToVram",
    callsTo: ["AddTextPrinterParameterized3","AddTextPrinterParameterized4","CopyWindowToVram","FillWindowPixelBuffer","GetStringWidth","GetWindowAttribute","PIXEL_FILL","PutWindowTilemap"],
    lineCount: 33,
    bodyC: "u8 color[3];\n    u16 width = 0;\n\n    if (sHofPCTopBarWindowId != WINDOW_NONE)\n    {\n        if (noBg)\n        {\n            color[0] = TEXT_COLOR_TRANSPARENT;\n            color[1] = TEXT_COLOR_WHITE;\n            color[2] = TEXT_COLOR_DARK_GRAY;\n        }\n        else\n        {\n            color[0] = TEXT_DYNAMIC_COLOR_6;\n            color[1] = TEXT_COLOR_WHITE;\n            color[2] = TEXT_COLOR_DARK_GRAY;\n        }\n        PutWindowTilemap(sHofPCTopBarWindowId);\n        FillWindowPixelBuffer(sHofPCTopBarWindowId, PIXEL_FILL(15));\n        if (string2 != NULL)\n        {\n            width = GetStringWidth(FONT_SMALL, string2, 0);\n            AddTextPrinterParameterized3(sHofPCTopBarWindowId,\n                      FONT_SMALL,\n                      236 - (GetWindowAttribute(sHofPCTopBarWindowId, WINDOW_TILEMAP_LEFT) * 8) - left - width,\n                      1,\n                      color,\n                      0,\n                      string2);\n        }\n        AddTextPrinterParameterized4(sHofPCTopBarWindowId, FONT_NORMAL, 4, 1, 0, 0, color, 0, string);\n        if (copyToVram)\n            CopyWindowToVram(sHofPCTopBarWindowId, COPYWIN_FULL);\n    }",
  },
  "HofPCTopBar_RemoveWindow": {
    returnType: "void",
    params: "void",
    callsTo: ["ClearWindowTilemap","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL","RemoveWindow"],
    lineCount: 8,
    bodyC: "if (sHofPCTopBarWindowId != WINDOW_NONE)\n    {\n        FillWindowPixelBuffer(sHofPCTopBarWindowId, PIXEL_FILL(0));\n        ClearWindowTilemap(sHofPCTopBarWindowId);\n        CopyWindowToVram(sHofPCTopBarWindowId, COPYWIN_FULL);\n        RemoveWindow(sHofPCTopBarWindowId);\n        sHofPCTopBarWindowId = WINDOW_NONE;\n    }",
  },
  "InitMenu": {
    returnType: "static u8",
    params: "u8 windowId, u8 fontId, u8 left, u8 top, u8 cursorHeight, u8 numChoices, u8 initialCursorPos, bool8 muteAPress",
    callsTo: ["Menu_MoveCursor"],
    lineCount: 16,
    bodyC: "s32 pos;\n\n    sMenu.left = left;\n    sMenu.top = top;\n    sMenu.minCursorPos = 0;\n    sMenu.maxCursorPos = numChoices - 1;\n    sMenu.windowId = windowId;\n    sMenu.fontId = fontId;\n    sMenu.optionHeight = cursorHeight;\n    sMenu.APressMuted = muteAPress;\n\n    pos = initialCursorPos;\n\n    if (pos < 0 || pos > sMenu.maxCursorPos)\n        sMenu.cursorPos = 0;\n    else\n        sMenu.cursorPos = pos;\n\n    Menu_MoveCursor(0);\n    return sMenu.cursorPos;",
  },
  "InitMenuActionGrid": {
    returnType: "u8",
    params: "u8 windowId, u8 optionWidth, u8 columns, u8 rows, u8 initialCursorPos",
    callsTo: ["ChangeMenuGridCursorPosition"],
    lineCount: 18,
    bodyC: "s32 pos;\n\n    sMenu.left = 0;\n    sMenu.top = 1;\n    sMenu.minCursorPos = 0;\n    sMenu.maxCursorPos = (columns * rows) - 1;\n    sMenu.windowId = windowId;\n    sMenu.fontId = FONT_NORMAL;\n    sMenu.optionWidth = optionWidth;\n    sMenu.optionHeight = 16;\n    sMenu.columns = columns;\n    sMenu.rows = rows;\n\n    pos = initialCursorPos;\n\n    if (pos < 0 || pos > sMenu.maxCursorPos)\n        sMenu.cursorPos = 0;\n    else\n        sMenu.cursorPos = pos;\n\n     \n    ChangeMenuGridCursorPosition(MENU_CURSOR_DELTA_NONE, MENU_CURSOR_DELTA_NONE);\n    return sMenu.cursorPos;",
  },
  "InitMenuGrid": {
    returnType: "static u8",
    params: "u8 windowId, u8 fontId, u8 left, u8 top, u8 optionWidth, u8 optionHeight, u8 columns, u8 rows, u8 numChoices, u8 cursorPos",
    callsTo: ["ChangeMenuGridCursorPosition"],
    lineCount: 18,
    bodyC: "s32 pos;\n\n    sMenu.left = left;\n    sMenu.top = top;\n    sMenu.minCursorPos = 0;\n    sMenu.maxCursorPos = numChoices - 1;\n    sMenu.windowId = windowId;\n    sMenu.fontId = fontId;\n    sMenu.optionWidth = optionWidth;\n    sMenu.optionHeight = optionHeight;\n    sMenu.columns = columns;\n    sMenu.rows = rows;\n\n    pos = cursorPos;\n\n    if (pos < 0 || pos > sMenu.maxCursorPos)\n        sMenu.cursorPos = 0;\n    else\n        sMenu.cursorPos = pos;\n\n     \n    ChangeMenuGridCursorPosition(MENU_CURSOR_DELTA_NONE, MENU_CURSOR_DELTA_NONE);\n    return sMenu.cursorPos;",
  },
  "InitMenuInUpperLeftCorner": {
    returnType: "u8",
    params: "u8 windowId, u8 itemCount, u8 initialCursorPos, bool8 APressMuted",
    callsTo: ["Menu_MoveCursor"],
    lineCount: 15,
    bodyC: "s32 pos;\n\n    sMenu.left = 0;\n    sMenu.top = 1;\n    sMenu.minCursorPos = 0;\n    sMenu.maxCursorPos = itemCount - 1;\n    sMenu.windowId = windowId;\n    sMenu.fontId = FONT_NORMAL;\n    sMenu.optionHeight = 16;\n    sMenu.APressMuted = APressMuted;\n\n    pos = initialCursorPos;\n\n    if (pos < 0 || pos > sMenu.maxCursorPos)\n        sMenu.cursorPos = 0;\n    else\n        sMenu.cursorPos = pos;\n\n    return Menu_MoveCursor(0);",
  },
  "InitMenuInUpperLeftCornerNormal": {
    returnType: "u8",
    params: "u8 windowId, u8 itemCount, u8 initialCursorPos",
    callsTo: ["InitMenuInUpperLeftCorner"],
    lineCount: 1,
    bodyC: "return InitMenuInUpperLeftCorner(windowId, itemCount, initialCursorPos, FALSE);",
  },
  "InitMenuNormal": {
    returnType: "u8",
    params: "u8 windowId, u8 fontId, u8 left, u8 top, u8 cursorHeight, u8 numChoices, u8 initialCursorPos",
    callsTo: ["InitMenu"],
    lineCount: 1,
    bodyC: "return InitMenu(windowId, fontId, left, top, cursorHeight, numChoices, initialCursorPos, FALSE);",
  },
  "InitStandardTextBoxWindows": {
    returnType: "void",
    params: "void",
    callsTo: ["InitWindows"],
    lineCount: 3,
    bodyC: "InitWindows(sStandardTextBox_WindowTemplates);\n    sStartMenuWindowId = WINDOW_NONE;\n    sMapNamePopupWindowId = WINDOW_NONE;",
  },
  "InitTextBoxGfxAndPrinters": {
    returnType: "void",
    params: "void",
    callsTo: ["ChangeBgX","ChangeBgY","DeactivateAllTextPrinters","LoadMessageBoxAndBorderGfx"],
    lineCount: 4,
    bodyC: "ChangeBgX(0, 0, BG_COORD_SET);\n    ChangeBgY(0, 0, BG_COORD_SET);\n    DeactivateAllTextPrinters();\n    LoadMessageBoxAndBorderGfx();",
  },
  "ListMenuLoadStdPalAt": {
    returnType: "void",
    params: "u8 palOffset, u8 palId",
    callsTo: ["LoadPalette"],
    lineCount: 15,
    bodyC: "const u16 *palette;\n\n    switch (palId)\n    {\n        case 0:\n        default:\n            palette = gMenuInfoElements1_Pal;\n            break;\n        case 1:\n            palette = gMenuInfoElements2_Pal;\n            break;\n        case 2:\n            palette = gMenuInfoElements3_Pal;\n            break;\n    }\n\n    LoadPalette(palette, palOffset, PLTT_SIZE_4BPP);",
  },
  "LoadMessageBoxAndBorderGfx": {
    returnType: "void",
    params: "void",
    callsTo: ["BG_PLTT_ID","LoadMessageBoxGfx","LoadUserWindowBorderGfx"],
    lineCount: 2,
    bodyC: "LoadMessageBoxGfx(0, DLG_WINDOW_BASE_TILE_NUM, BG_PLTT_ID(DLG_WINDOW_PALETTE_NUM));\n    LoadUserWindowBorderGfx(0, STD_WINDOW_BASE_TILE_NUM, BG_PLTT_ID(STD_WINDOW_PALETTE_NUM));",
  },
  "LoadMessageBoxAndFrameGfx": {
    returnType: "void",
    params: "u8 windowId, bool8 copyToVram",
    callsTo: ["BG_PLTT_ID","DrawDialogFrameWithCustomTileAndPalette","LoadMessageBoxGfx"],
    lineCount: 2,
    bodyC: "LoadMessageBoxGfx(windowId, DLG_WINDOW_BASE_TILE_NUM, BG_PLTT_ID(DLG_WINDOW_PALETTE_NUM));\n    DrawDialogFrameWithCustomTileAndPalette(windowId, copyToVram, DLG_WINDOW_BASE_TILE_NUM, DLG_WINDOW_PALETTE_NUM);",
  },
  "Menu_GetCursorPos": {
    returnType: "u8",
    params: "void",
    lineCount: 1,
    bodyC: "return sMenu.cursorPos;",
  },
  "Menu_LoadStdPal": {
    returnType: "void",
    params: "void",
    callsTo: ["BG_PLTT_ID","LoadPalette"],
    lineCount: 1,
    bodyC: "LoadPalette(gStandardMenuPalette, BG_PLTT_ID(STD_WINDOW_PALETTE_NUM), STD_WINDOW_PALETTE_SIZE);",
  },
  "Menu_LoadStdPalAt": {
    returnType: "void",
    params: "u16 offset",
    callsTo: ["LoadPalette"],
    lineCount: 1,
    bodyC: "LoadPalette(gStandardMenuPalette, offset, STD_WINDOW_PALETTE_SIZE);",
  },
  "Menu_MoveCursor": {
    returnType: "u8",
    params: "s8 cursorDelta",
    callsTo: ["RedrawMenuCursor"],
    lineCount: 10,
    bodyC: "u8 oldPos = sMenu.cursorPos;\n    int newPos = sMenu.cursorPos + cursorDelta;\n\n    if (newPos < sMenu.minCursorPos)\n        sMenu.cursorPos = sMenu.maxCursorPos;\n    else if (newPos > sMenu.maxCursorPos)\n        sMenu.cursorPos = sMenu.minCursorPos;\n    else\n        sMenu.cursorPos += cursorDelta;\n\n    RedrawMenuCursor(oldPos, sMenu.cursorPos);\n    return sMenu.cursorPos;",
  },
  "Menu_MoveCursorNoWrapAround": {
    returnType: "u8",
    params: "s8 cursorDelta",
    callsTo: ["RedrawMenuCursor"],
    lineCount: 10,
    bodyC: "u8 oldPos = sMenu.cursorPos;\n    int newPos = sMenu.cursorPos + cursorDelta;\n\n    if (newPos < sMenu.minCursorPos)\n        sMenu.cursorPos = sMenu.minCursorPos;\n    else if (newPos > sMenu.maxCursorPos)\n        sMenu.cursorPos = sMenu.maxCursorPos;\n    else\n        sMenu.cursorPos += cursorDelta;\n\n    RedrawMenuCursor(oldPos, sMenu.cursorPos);\n    return sMenu.cursorPos;",
  },
  "Menu_ProcessGridInput": {
    returnType: "s8",
    params: "void",
    callsTo: ["ChangeGridMenuCursorPosition","GetLRKeysPressed","JOY_NEW","PlaySE"],
    lineCount: 35,
    bodyC: "u8 oldPos = sMenu.cursorPos;\n\n    if (JOY_NEW(A_BUTTON))\n    {\n        PlaySE(SE_SELECT);\n        return sMenu.cursorPos;\n    }\n    else if (JOY_NEW(B_BUTTON))\n    {\n        return MENU_B_PRESSED;\n    }\n    else if (JOY_NEW(DPAD_UP))\n    {\n        if (oldPos != ChangeGridMenuCursorPosition(0, -1))\n            PlaySE(SE_SELECT);\n        return MENU_NOTHING_CHOSEN;\n    }\n    else if (JOY_NEW(DPAD_DOWN))\n    {\n        if (oldPos != ChangeGridMenuCursorPosition(0, 1))\n            PlaySE(SE_SELECT);\n        return MENU_NOTHING_CHOSEN;\n    }\n    else if (JOY_NEW(DPAD_LEFT) || GetLRKeysPressed() == MENU_L_PRESSED)\n    {\n        if (oldPos != ChangeGridMenuCursorPosition(-1, 0))\n            PlaySE(SE_SELECT);\n        return MENU_NOTHING_CHOSEN;\n    }\n    else if (JOY_NEW(DPAD_RIGHT) || GetLRKeysPressed() == MENU_R_PRESSED)\n    {\n        if (oldPos != ChangeGridMenuCursorPosition(1, 0))\n            PlaySE(SE_SELECT);\n        return MENU_NOTHING_CHOSEN;\n    }\n\n    return MENU_NOTHING_CHOSEN;",
  },
  "Menu_ProcessInput": {
    returnType: "s8",
    params: "void",
    callsTo: ["JOY_NEW","Menu_MoveCursor","PlaySE"],
    lineCount: 23,
    bodyC: "if (JOY_NEW(A_BUTTON))\n    {\n        if (!sMenu.APressMuted)\n            PlaySE(SE_SELECT);\n        return sMenu.cursorPos;\n    }\n    else if (JOY_NEW(B_BUTTON))\n    {\n        return MENU_B_PRESSED;\n    }\n    else if (JOY_NEW(DPAD_UP))\n    {\n        PlaySE(SE_SELECT);\n        Menu_MoveCursor(-1);\n        return MENU_NOTHING_CHOSEN;\n    }\n    else if (JOY_NEW(DPAD_DOWN))\n    {\n        PlaySE(SE_SELECT);\n        Menu_MoveCursor(1);\n        return MENU_NOTHING_CHOSEN;\n    }\n\n    return MENU_NOTHING_CHOSEN;",
  },
  "Menu_ProcessInputNoWrap": {
    returnType: "s8",
    params: "void",
    callsTo: ["JOY_NEW","Menu_MoveCursorNoWrapAround","PlaySE"],
    lineCount: 24,
    bodyC: "u8 oldPos = sMenu.cursorPos;\n\n    if (JOY_NEW(A_BUTTON))\n    {\n        if (!sMenu.APressMuted)\n            PlaySE(SE_SELECT);\n        return sMenu.cursorPos;\n    }\n    else if (JOY_NEW(B_BUTTON))\n    {\n        return MENU_B_PRESSED;\n    }\n    else if (JOY_NEW(DPAD_UP))\n    {\n        if (oldPos != Menu_MoveCursorNoWrapAround(-1))\n            PlaySE(SE_SELECT);\n        return MENU_NOTHING_CHOSEN;\n    }\n    else if (JOY_NEW(DPAD_DOWN))\n    {\n        if (oldPos != Menu_MoveCursorNoWrapAround(1))\n            PlaySE(SE_SELECT);\n        return MENU_NOTHING_CHOSEN;\n    }\n\n    return MENU_NOTHING_CHOSEN;",
  },
  "Menu_ProcessInputNoWrapAround_other": {
    returnType: "s8",
    params: "void",
    callsTo: ["JOY_NEW","JOY_REPEAT","Menu_MoveCursorNoWrapAround","PlaySE"],
    lineCount: 24,
    bodyC: "u8 oldPos = sMenu.cursorPos;\n\n    if (JOY_NEW(A_BUTTON))\n    {\n        if (!sMenu.APressMuted)\n            PlaySE(SE_SELECT);\n        return sMenu.cursorPos;\n    }\n    else if (JOY_NEW(B_BUTTON))\n    {\n        return MENU_B_PRESSED;\n    }\n    else if (JOY_REPEAT(DPAD_ANY) == DPAD_UP)\n    {\n        if (oldPos != Menu_MoveCursorNoWrapAround(-1))\n            PlaySE(SE_SELECT);\n        return MENU_NOTHING_CHOSEN;\n    }\n    else if (JOY_REPEAT(DPAD_ANY) == DPAD_DOWN)\n    {\n        if (oldPos != Menu_MoveCursorNoWrapAround(1))\n            PlaySE(SE_SELECT);\n        return MENU_NOTHING_CHOSEN;\n    }\n\n    return MENU_NOTHING_CHOSEN;",
  },
  "Menu_ProcessInputNoWrapClearOnChoose": {
    returnType: "s8",
    params: "void",
    callsTo: ["EraseYesNoWindow","Menu_ProcessInputNoWrap"],
    lineCount: 4,
    bodyC: "s8 result = Menu_ProcessInputNoWrap();\n    if (result != MENU_NOTHING_CHOSEN)\n        EraseYesNoWindow();\n    return result;",
  },
  "MoveMenuGridCursor": {
    returnType: "static void",
    params: "u8 oldCursorPos, u8 newCursorPos",
    callsTo: ["AddTextPrinterParameterized","FillWindowPixelRect","GetMenuCursorDimensionByFont","PIXEL_FILL"],
    lineCount: 8,
    bodyC: "u8 cursorWidth = GetMenuCursorDimensionByFont(sMenu.fontId, 0);\n    u8 cursorHeight = GetMenuCursorDimensionByFont(sMenu.fontId, 1);\n\n    u8 xPos = (oldCursorPos % sMenu.columns) * sMenu.optionWidth + sMenu.left;\n    u8 yPos = (oldCursorPos / sMenu.columns) * sMenu.optionHeight + sMenu.top;\n    FillWindowPixelRect(sMenu.windowId, PIXEL_FILL(1), xPos, yPos, cursorWidth, cursorHeight);\n\n    xPos = (newCursorPos % sMenu.columns) * sMenu.optionWidth + sMenu.left;\n    yPos = (newCursorPos / sMenu.columns) * sMenu.optionHeight + sMenu.top;\n    AddTextPrinterParameterized(sMenu.windowId, sMenu.fontId, gText_SelectorArrow3, xPos, yPos, 0, 0);",
  },
  "PrintMenuActionGrid": {
    returnType: "void",
    params: "u8 windowId, u8 fontId, u8 left, u8 top, u8 optionWidth, u8 horizontalCount, u8 verticalCount, const struct MenuAction *menuActions, const u8 *actionIds",
    callsTo: ["AddTextPrinter","CopyWindowToVram","GetFontAttribute"],
    lineCount: 24,
    bodyC: "u8 i;\n    u8 j;\n    struct TextPrinterTemplate printer;\n\n    printer.windowId = windowId;\n    printer.fontId = fontId;\n    printer.fgColor = GetFontAttribute(fontId, FONTATTR_COLOR_FOREGROUND);\n    printer.bgColor = GetFontAttribute(fontId, FONTATTR_COLOR_BACKGROUND);\n    printer.shadowColor = GetFontAttribute(fontId, FONTATTR_COLOR_SHADOW);\n    printer.unk = GetFontAttribute(fontId, FONTATTR_UNKNOWN);\n    printer.letterSpacing = GetFontAttribute(fontId, FONTATTR_LETTER_SPACING);\n    printer.lineSpacing = GetFontAttribute(fontId, FONTATTR_LINE_SPACING);\n\n    for (i = 0; i < verticalCount; i++)\n    {\n        for (j = 0; j < horizontalCount; j++)\n        {\n            printer.currentChar = menuActions[actionIds[(horizontalCount * i) + j]].text;\n            printer.x = (optionWidth * j) + left;\n            printer.y = (GetFontAttribute(fontId, FONTATTR_MAX_LETTER_HEIGHT) * i) + top;\n            printer.currentX = printer.x;\n            printer.currentY = printer.y;\n            AddTextPrinter(&printer, TEXT_SKIP_DRAW, NULL);\n        }\n    }\n\n    CopyWindowToVram(windowId, COPYWIN_GFX);",
  },
  "PrintMenuActionGridText": {
    returnType: "static void",
    params: "u8 windowId, u8 fontId, u8 left, u8 top, u8 width, u8 height, u8 columns, u8 rows, const struct MenuAction *menuActions",
    callsTo: ["AddTextPrinterParameterized","CopyWindowToVram"],
    lineCount: 8,
    bodyC: "u8 i;\n    u8 j;\n    for (i = 0; i < rows; i++)\n    {\n        for (j = 0; j < columns; j++)\n            AddTextPrinterParameterized(windowId, fontId, menuActions[(i * columns) + j].text, (width * j) + left, (height * i) + top, TEXT_SKIP_DRAW, NULL);\n    }\n    CopyWindowToVram(windowId, COPYWIN_GFX);",
  },
  "PrintMenuActionTexts": {
    returnType: "void",
    params: "u8 windowId, u8 fontId, u8 left, u8 top, u8 letterSpacing, u8 lineHeight, u8 itemCount, const struct MenuAction *menuActions, const u8 *actionIds",
    callsTo: ["AddTextPrinter","CopyWindowToVram","GetFontAttribute"],
    lineCount: 20,
    bodyC: "u8 i;\n    struct TextPrinterTemplate printer;\n\n    printer.windowId = windowId;\n    printer.fontId = fontId;\n    printer.fgColor = GetFontAttribute(fontId, FONTATTR_COLOR_FOREGROUND);\n    printer.bgColor = GetFontAttribute(fontId, FONTATTR_COLOR_BACKGROUND);\n    printer.shadowColor = GetFontAttribute(fontId, FONTATTR_COLOR_SHADOW);\n    printer.unk = GetFontAttribute(fontId, FONTATTR_UNKNOWN);\n    printer.letterSpacing = letterSpacing;\n    printer.lineSpacing = GetFontAttribute(fontId, FONTATTR_LINE_SPACING);\n    printer.x = left;\n    printer.currentX = left;\n\n    for (i = 0; i < itemCount; i++)\n    {\n        printer.currentChar = menuActions[actionIds[i]].text;\n        printer.y = (lineHeight * i) + top;\n        printer.currentY = printer.y;\n        AddTextPrinter(&printer, TEXT_SKIP_DRAW, NULL);\n    }\n\n    CopyWindowToVram(windowId, COPYWIN_GFX);",
  },
  "PrintMenuActionTextsAtPos": {
    returnType: "void",
    params: "u8 windowId, u8 fontId, u8 left, u8 top, u8 lineHeight, u8 itemCount, const struct MenuAction *menuActions",
    callsTo: ["AddTextPrinterParameterized","CopyWindowToVram"],
    lineCount: 4,
    bodyC: "u8 i;\n    for (i = 0; i < itemCount; i++)\n        AddTextPrinterParameterized(windowId, fontId, menuActions[i].text, left, (lineHeight * i) + top, TEXT_SKIP_DRAW, NULL);\n    CopyWindowToVram(windowId, COPYWIN_GFX);",
  },
  "PrintMenuActionTextsInUpperLeftCorner": {
    returnType: "void",
    params: "u8 windowId, u8 itemCount, const struct MenuAction *menuActions, const u8 *actionIds",
    callsTo: ["AddTextPrinter","CopyWindowToVram","GetFontAttribute"],
    lineCount: 20,
    bodyC: "u8 i;\n    struct TextPrinterTemplate printer;\n\n    printer.windowId = windowId;\n    printer.fontId = FONT_NORMAL;\n    printer.fgColor = GetFontAttribute(FONT_NORMAL, FONTATTR_COLOR_FOREGROUND);\n    printer.bgColor = GetFontAttribute(FONT_NORMAL, FONTATTR_COLOR_BACKGROUND);\n    printer.shadowColor = GetFontAttribute(FONT_NORMAL, FONTATTR_COLOR_SHADOW);\n    printer.unk = GetFontAttribute(FONT_NORMAL, FONTATTR_UNKNOWN);\n    printer.letterSpacing = 0;\n    printer.lineSpacing = 0;\n    printer.x = 8;\n    printer.currentX = 8;\n\n    for (i = 0; i < itemCount; i++)\n    {\n        printer.currentChar = menuActions[actionIds[i]].text;\n        printer.y = (i * 16) + 1;\n        printer.currentY = (i * 16) + 1;\n        AddTextPrinter(&printer, TEXT_SKIP_DRAW, NULL);\n    }\n\n    CopyWindowToVram(windowId, COPYWIN_GFX);",
  },
  "PrintMenuGridTable": {
    returnType: "void",
    params: "u8 windowId, u8 optionWidth, u8 columns, u8 rows, const struct MenuAction *menuActions",
    callsTo: ["AddTextPrinterParameterized","CopyWindowToVram"],
    lineCount: 7,
    bodyC: "u32 i, j;\n\n    for (i = 0; i < rows; i++)\n    {\n        for (j = 0; j < columns; j++)\n            AddTextPrinterParameterized(windowId, 1, menuActions[(i * columns) + j].text, (optionWidth * j) + 8, (i * 16) + 1, TEXT_SKIP_DRAW, NULL);\n    }\n    CopyWindowToVram(windowId, COPYWIN_GFX);",
  },
  "PrintMenuTable": {
    returnType: "void",
    params: "u8 windowId, u8 itemCount, const struct MenuAction *menuActions",
    callsTo: ["AddTextPrinterParameterized","CopyWindowToVram"],
    lineCount: 4,
    bodyC: "u32 i;\n\n    for (i = 0; i < itemCount; i++)\n        AddTextPrinterParameterized(windowId, 1, menuActions[i].text, 8, (i * 16) + 1, TEXT_SKIP_DRAW, NULL);\n\n    CopyWindowToVram(windowId, COPYWIN_GFX);",
  },
  "PrintPlayerNameOnWindow": {
    returnType: "void",
    params: "u8 windowId, const u8 *src, u16 x, u16 y",
    callsTo: ["AddTextPrinterParameterized","StringExpandPlaceholders"],
    lineCount: 5,
    bodyC: "int count = 0;\n    while (gSaveBlock2Ptr->playerName[count] != EOS)\n        count++;\n\n    StringExpandPlaceholders(gStringVar4, src);\n\n    AddTextPrinterParameterized(windowId, 1, gStringVar4, x, y, TEXT_SKIP_DRAW, 0);",
  },
  "ProcessMenuInput_other": {
    returnType: "s8",
    params: "void",
    callsTo: ["JOY_NEW","JOY_REPEAT","Menu_MoveCursor","PlaySE"],
    lineCount: 23,
    bodyC: "if (JOY_NEW(A_BUTTON))\n    {\n        if (!sMenu.APressMuted)\n            PlaySE(SE_SELECT);\n        return sMenu.cursorPos;\n    }\n    else if (JOY_NEW(B_BUTTON))\n    {\n        return MENU_B_PRESSED;\n    }\n    else if ((JOY_REPEAT(DPAD_ANY)) == DPAD_UP)\n    {\n        PlaySE(SE_SELECT);\n        Menu_MoveCursor(-1);\n        return MENU_NOTHING_CHOSEN;\n    }\n    else if ((JOY_REPEAT(DPAD_ANY)) == DPAD_DOWN)\n    {\n        PlaySE(SE_SELECT);\n        Menu_MoveCursor(1);\n        return MENU_NOTHING_CHOSEN;\n    }\n\n    return MENU_NOTHING_CHOSEN;",
  },
  "RedrawMenuCursor": {
    returnType: "void",
    params: "u8 oldPos, u8 newPos",
    callsTo: ["AddTextPrinterParameterized","FillWindowPixelRect","GetMenuCursorDimensionByFont","PIXEL_FILL"],
    lineCount: 5,
    bodyC: "u8 width, height;\n\n    width = GetMenuCursorDimensionByFont(sMenu.fontId, 0);\n    height = GetMenuCursorDimensionByFont(sMenu.fontId, 1);\n    FillWindowPixelRect(sMenu.windowId, PIXEL_FILL(1), sMenu.left, sMenu.optionHeight * oldPos + sMenu.top, width, height);\n    AddTextPrinterParameterized(sMenu.windowId, sMenu.fontId, gText_SelectorArrow3, sMenu.left, sMenu.optionHeight * newPos + sMenu.top, 0, 0);",
  },
  "RemoveMapNamePopUpWindow": {
    returnType: "void",
    params: "void",
    callsTo: ["RemoveWindow"],
    lineCount: 5,
    bodyC: "if (sMapNamePopupWindowId != WINDOW_NONE)\n    {\n        RemoveWindow(sMapNamePopupWindowId);\n        sMapNamePopupWindowId = WINDOW_NONE;\n    }",
  },
  "RemoveStartMenuWindow": {
    returnType: "void",
    params: "void",
    callsTo: ["RemoveWindow"],
    lineCount: 5,
    bodyC: "if (sStartMenuWindowId != WINDOW_NONE)\n    {\n        RemoveWindow(sStartMenuWindowId);\n        sStartMenuWindowId = WINDOW_NONE;\n    }",
  },
  "ResetBgPositions": {
    returnType: "void",
    params: "void",
    callsTo: ["ChangeBgX","ChangeBgY"],
    lineCount: 8,
    bodyC: "ChangeBgX(0, 0, BG_COORD_SET);\n    ChangeBgX(1, 0, BG_COORD_SET);\n    ChangeBgX(2, 0, BG_COORD_SET);\n    ChangeBgX(3, 0, BG_COORD_SET);\n    ChangeBgY(0, 0, BG_COORD_SET);\n    ChangeBgY(1, 0, BG_COORD_SET);\n    ChangeBgY(2, 0, BG_COORD_SET);\n    ChangeBgY(3, 0, BG_COORD_SET);",
  },
  "ResetTempTileDataBuffers": {
    returnType: "void",
    params: "void",
    callsTo: ["ARRAY_COUNT"],
    lineCount: 4,
    bodyC: "int i;\n    for (i = 0; i < (int)ARRAY_COUNT(sTempTileDataBuffer); i++)\n        sTempTileDataBuffer[i] = NULL;\n    sTempTileDataBufferIdx = 0;",
  },
  "RunTextPrintersAndIsPrinter0Active": {
    returnType: "u16",
    params: "void",
    callsTo: ["IsTextPrinterActive","RunTextPrinters"],
    lineCount: 2,
    bodyC: "RunTextPrinters();\n    return IsTextPrinterActive(0);",
  },
  "ScheduleBgCopyTilemapToVram": {
    returnType: "void",
    params: "u8 bgId",
    lineCount: 1,
    bodyC: "sScheduledBgCopiesToVram[bgId] = TRUE;",
  },
  "SetBgTilemapPalette": {
    returnType: "void",
    params: "u8 bgId, u8 left, u8 top, u8 width, u8 height, u8 palette",
    callsTo: ["GetBgTilemapBuffer"],
    lineCount: 10,
    bodyC: "u8 i;\n    u8 j;\n    u16 *ptr = GetBgTilemapBuffer(bgId);\n\n    for (i = top; i < top + height; i++)\n    {\n        for (j = left; j < left + width; j++)\n        {\n            ptr[(i * 32) + j] = (ptr[(i * 32) + j] & 0xFFF) | (palette << 12);\n        }\n    }",
  },
  "SetStandardWindowBorderStyle": {
    returnType: "void",
    params: "u8 windowId, bool8 copyToVram",
    callsTo: ["DrawStdFrameWithCustomTileAndPalette"],
    lineCount: 1,
    bodyC: "DrawStdFrameWithCustomTileAndPalette(windowId, copyToVram, STD_WINDOW_BASE_TILE_NUM, STD_WINDOW_PALETTE_NUM);",
  },
  "SetWindowTemplateFields": {
    returnType: "void",
    params: "struct WindowTemplate *template, u8 bg, u8 left, u8 top, u8 width, u8 height, u8 paletteNum, u16 baseBlock",
    lineCount: 7,
    bodyC: "template->bg = bg;\n    template->tilemapLeft = left;\n    template->tilemapTop = top;\n    template->width = width;\n    template->height = height;\n    template->paletteNum = paletteNum;\n    template->baseBlock = baseBlock;",
  },
  "WindowFunc_ClearDialogWindowAndFrame": {
    returnType: "static void",
    params: "u8 bg, u8 tilemapLeft, u8 tilemapTop, u8 width, u8 height, u8 paletteNum",
    callsTo: ["FillBgTilemapBufferRect"],
    lineCount: 1,
    bodyC: "FillBgTilemapBufferRect(bg, 0, tilemapLeft - 3, tilemapTop - 1, width + 6, height + 2, STD_WINDOW_PALETTE_NUM);",
  },
  "WindowFunc_ClearDialogWindowAndFrameNullPalette": {
    returnType: "static void",
    params: "u8 bg, u8 tilemapLeft, u8 tilemapTop, u8 width, u8 height, u8 paletteNum",
    callsTo: ["FillBgTilemapBufferRect"],
    lineCount: 1,
    bodyC: "FillBgTilemapBufferRect(bg, 0, tilemapLeft - 3, tilemapTop - 1, width + 6, height + 2, 0);",
  },
  "WindowFunc_ClearStdWindowAndFrame": {
    returnType: "static void",
    params: "u8 bg, u8 tilemapLeft, u8 tilemapTop, u8 width, u8 height, u8 paletteNum",
    callsTo: ["FillBgTilemapBufferRect"],
    lineCount: 1,
    bodyC: "FillBgTilemapBufferRect(bg, 0, tilemapLeft - 1, tilemapTop - 1, width + 2, height + 2, STD_WINDOW_PALETTE_NUM);",
  },
  "WindowFunc_ClearStdWindowAndFrameToTransparent": {
    returnType: "static void",
    params: "u8 bg, u8 tilemapLeft, u8 tilemapTop, u8 width, u8 height, u8 paletteNum",
    callsTo: ["FillBgTilemapBufferRect"],
    lineCount: 1,
    bodyC: "FillBgTilemapBufferRect(bg, 0, tilemapLeft - 1, tilemapTop - 1, width + 2, height + 2, 0);",
  },
  "WindowFunc_DrawDialogFrameWithCustomTileAndPalette": {
    returnType: "static void",
    params: "u8 bg, u8 tilemapLeft, u8 tilemapTop, u8 width, u8 height, u8 paletteNum",
    callsTo: ["BG_TILE_V_FLIP","FillBgTilemapBufferRect"],
    lineCount: 91,
    bodyC: "FillBgTilemapBufferRect(bg,\n                            sTileNum + 1,\n                            tilemapLeft - 2,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 3,\n                            tilemapLeft - 1,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 4,\n                            tilemapLeft,\n                            tilemapTop - 1,\n                            width - 1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 5,\n                            tilemapLeft + width - 1,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 6,\n                            tilemapLeft + width,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 7,\n                            tilemapLeft - 2,\n                            tilemapTop,\n                            1,\n                            5,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 9,\n                            tilemapLeft - 1,\n                            tilemapTop,\n                            width + 1,\n                            5,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 10,\n                            tilemapLeft + width,\n                            tilemapTop,\n                            1,\n                            5,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            BG_TILE_V_FLIP(sTileNum + 1),\n                            tilemapLeft - 2,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            BG_TILE_V_FLIP(sTileNum + 3),\n                            tilemapLeft - 1,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            BG_TILE_V_FLIP(sTileNum + 4),\n                            tilemapLeft,\n                            tilemapTop + height,\n                            width - 1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            BG_TILE_V_FLIP(sTileNum + 5),\n                            tilemapLeft + width - 1,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            BG_TILE_V_FLIP(sTileNum + 6),\n                            tilemapLeft + width,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            sPaletteNum);",
  },
  "WindowFunc_DrawDialogueFrame": {
    returnType: "static void",
    params: "u8 bg, u8 tilemapLeft, u8 tilemapTop, u8 width, u8 height, u8 paletteNum",
    callsTo: ["BG_TILE_V_FLIP","FillBgTilemapBufferRect"],
    lineCount: 91,
    bodyC: "FillBgTilemapBufferRect(bg,\n                            DLG_WINDOW_BASE_TILE_NUM + 1,\n                            tilemapLeft - 2,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            DLG_WINDOW_BASE_TILE_NUM + 3,\n                            tilemapLeft - 1,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            DLG_WINDOW_BASE_TILE_NUM + 4,\n                            tilemapLeft,\n                            tilemapTop - 1,\n                            width - 1,\n                            1,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            DLG_WINDOW_BASE_TILE_NUM + 5,\n                            tilemapLeft + width - 1,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            DLG_WINDOW_BASE_TILE_NUM + 6,\n                            tilemapLeft + width,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            DLG_WINDOW_BASE_TILE_NUM + 7,\n                            tilemapLeft - 2,\n                            tilemapTop,\n                            1,\n                            5,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            DLG_WINDOW_BASE_TILE_NUM + 9,\n                            tilemapLeft - 1,\n                            tilemapTop,\n                            width + 1,\n                            5,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            DLG_WINDOW_BASE_TILE_NUM + 10,\n                            tilemapLeft + width,\n                            tilemapTop,\n                            1,\n                            5,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            BG_TILE_V_FLIP(DLG_WINDOW_BASE_TILE_NUM + 1),\n                            tilemapLeft - 2,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            BG_TILE_V_FLIP(DLG_WINDOW_BASE_TILE_NUM + 3),\n                            tilemapLeft - 1,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            BG_TILE_V_FLIP(DLG_WINDOW_BASE_TILE_NUM + 4),\n                            tilemapLeft,\n                            tilemapTop + height,\n                            width - 1,\n                            1,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            BG_TILE_V_FLIP(DLG_WINDOW_BASE_TILE_NUM + 5),\n                            tilemapLeft + width - 1,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            DLG_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            BG_TILE_V_FLIP(DLG_WINDOW_BASE_TILE_NUM + 6),\n                            tilemapLeft + width,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            DLG_WINDOW_PALETTE_NUM);",
  },
  "WindowFunc_DrawStandardFrame": {
    returnType: "static void",
    params: "u8 bg, u8 tilemapLeft, u8 tilemapTop, u8 width, u8 height, u8 paletteNum",
    callsTo: ["FillBgTilemapBufferRect"],
    lineCount: 60,
    bodyC: "int i;\n\n    FillBgTilemapBufferRect(bg,\n                            STD_WINDOW_BASE_TILE_NUM + 0,\n                            tilemapLeft - 1,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            STD_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            STD_WINDOW_BASE_TILE_NUM + 1,\n                            tilemapLeft,\n                            tilemapTop - 1,\n                            width,\n                            1,\n                            STD_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            STD_WINDOW_BASE_TILE_NUM + 2,\n                            tilemapLeft + width,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            STD_WINDOW_PALETTE_NUM);\n\n    for (i = tilemapTop; i < tilemapTop + height; i++)\n    {\n        FillBgTilemapBufferRect(bg,\n                                STD_WINDOW_BASE_TILE_NUM + 3,\n                                tilemapLeft - 1,\n                                i,\n                                1,\n                                1,\n                                STD_WINDOW_PALETTE_NUM);\n        FillBgTilemapBufferRect(bg,\n                                STD_WINDOW_BASE_TILE_NUM + 5,\n                                tilemapLeft + width,\n                                i,\n                                1,\n                                1,\n                                STD_WINDOW_PALETTE_NUM);\n    }\n\n    FillBgTilemapBufferRect(bg,\n                            STD_WINDOW_BASE_TILE_NUM + 6,\n                            tilemapLeft - 1,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            STD_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            STD_WINDOW_BASE_TILE_NUM + 7,\n                            tilemapLeft,\n                            tilemapTop + height,\n                            width,\n                            1,\n                            STD_WINDOW_PALETTE_NUM);\n    FillBgTilemapBufferRect(bg,\n                            STD_WINDOW_BASE_TILE_NUM + 8,\n                            tilemapLeft + width,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            STD_WINDOW_PALETTE_NUM);",
  },
  "WindowFunc_DrawStdFrameWithCustomTileAndPalette": {
    returnType: "static void",
    params: "u8 bg, u8 tilemapLeft, u8 tilemapTop, u8 width, u8 height, u8 paletteNum",
    callsTo: ["FillBgTilemapBufferRect"],
    lineCount: 56,
    bodyC: "FillBgTilemapBufferRect(bg,\n                            sTileNum + 0,\n                            tilemapLeft - 1,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 1,\n                            tilemapLeft,\n                            tilemapTop - 1,\n                            width,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 2,\n                            tilemapLeft + width,\n                            tilemapTop - 1,\n                            1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 3,\n                            tilemapLeft - 1,\n                            tilemapTop,\n                            1,\n                            height,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 5,\n                            tilemapLeft + width,\n                            tilemapTop,\n                            1,\n                            height,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 6,\n                            tilemapLeft - 1,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 7,\n                            tilemapLeft,\n                            tilemapTop + height,\n                            width,\n                            1,\n                            sPaletteNum);\n    FillBgTilemapBufferRect(bg,\n                            sTileNum + 8,\n                            tilemapLeft + width,\n                            tilemapTop + height,\n                            1,\n                            1,\n                            sPaletteNum);",
  },
  "copy_decompressed_tile_data_to_vram": {
    returnType: "u16",
    params: "u8 bgId, const void *src, u16 size, u16 offset, u8 mode",
    callsTo: ["LoadBgTilemap","LoadBgTiles"],
    lineCount: 9,
    bodyC: "switch (mode)\n    {\n        case 0:\n            return LoadBgTiles(bgId, src, size, offset);\n        case 1:\n            return LoadBgTilemap(bgId, src, size, offset);\n        default:\n            return -1;\n    }",
  },
  "malloc_and_decompress": {
    returnType: "void *",
    params: "const void *src, u32 *size",
    callsTo: ["Alloc","LZ77UnCompWram"],
    lineCount: 11,
    bodyC: "void *ptr;\n    u8 *sizeAsBytes = (u8 *)size;\n    u8 *srcAsBytes = (u8 *)src;\n\n    sizeAsBytes[0] = srcAsBytes[1];\n    sizeAsBytes[1] = srcAsBytes[2];\n    sizeAsBytes[2] = srcAsBytes[3];\n    sizeAsBytes[3] = 0;\n\n    ptr = Alloc(*size);\n    if (ptr)\n        LZ77UnCompWram(src, ptr);\n    return ptr;",
  },
  "task_free_buf_after_copying_tile_data_to_vram": {
    returnType: "void",
    params: "u8 taskId",
    callsTo: ["CheckForSpaceForDma3Request","DestroyTask","Free","GetWordTaskArg"],
    lineCount: 5,
    bodyC: "if (!CheckForSpaceForDma3Request(gTasks[taskId].data[0]))\n    {\n        Free((void *)GetWordTaskArg(taskId, 1));\n        DestroyTask(taskId);\n    }",
  },
} as const;
