// AUTO-GENERATED from src/mystery_event_script.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 30

export const ENGINE_FUNCTIONS = {
  "CalcRecordMixingGiftChecksum": {
    returnType: "static int",
    params: "void",
    lineCount: 6,
    bodyC: "unsigned int i;\n    int sum = 0;\n    u8 *data = (u8 *)(&gSaveBlock1Ptr->recordMixingGift.data);\n\n    for (i = 0; i < sizeof(gSaveBlock1Ptr->recordMixingGift.data); i++)\n        sum += data[i];\n\n    return sum;",
  },
  "CheckCompatibility": {
    returnType: "static bool32",
    params: "u16 unk0, u32 unk1, u16 unk2, u32 version",
    lineCount: 9,
    bodyC: "if (!(unk0 & 0x1))\n        return FALSE;\n\n     \n    if (!(unk1 & 0x1))\n        return FALSE;\n\n     \n    if (!(unk2 & 0x4))\n        return FALSE;\n\n    if (!(version & VERSION_MASK))\n        return FALSE;\n\n    return TRUE;",
  },
  "ClearRecordMixingGift": {
    returnType: "static void",
    params: "void",
    callsTo: ["CpuFill16"],
    lineCount: 1,
    bodyC: "CpuFill16(0, &gSaveBlock1Ptr->recordMixingGift, sizeof(gSaveBlock1Ptr->recordMixingGift));",
  },
  "GetRecordMixingGift": {
    returnType: "u16",
    params: "void",
    callsTo: ["CalcRecordMixingGiftChecksum","ClearRecordMixingGift","IsRecordMixingGiftValid"],
    lineCount: 16,
    bodyC: "struct RecordMixingGiftData *data = &gSaveBlock1Ptr->recordMixingGift.data;\n\n    if (!IsRecordMixingGiftValid())\n    {\n        ClearRecordMixingGift();\n        return 0;\n    }\n    else\n    {\n        u16 itemId = data->itemId;\n        data->quantity--;\n        if (data->quantity == 0)\n            ClearRecordMixingGift();\n        else\n            gSaveBlock1Ptr->recordMixingGift.checksum = CalcRecordMixingGiftChecksum();\n\n        return itemId;\n    }",
  },
  "InitMysteryEventScript": {
    returnType: "static void",
    params: "struct ScriptContext *ctx, u8 *script",
    callsTo: ["InitScriptContext","SetupBytecodeScript"],
    lineCount: 6,
    bodyC: "InitScriptContext(ctx, gMysteryEventScriptCmdTable, gMysteryEventScriptCmdTableEnd);\n    SetupBytecodeScript(ctx, script);\n    ctx->mScriptBase = (u32)script;\n    ctx->mOffset = 0;\n    ctx->mStatus = MEVENT_STATUS_LOAD_OK;\n    ctx->mValid = FALSE;",
  },
  "InitMysteryEventScriptContext": {
    returnType: "void",
    params: "u8 *script",
    callsTo: ["InitMysteryEventScript"],
    lineCount: 1,
    bodyC: "InitMysteryEventScript(&sMysteryEventScriptContext, script);",
  },
  "IsRecordMixingGiftValid": {
    returnType: "static bool32",
    params: "void",
    callsTo: ["CalcRecordMixingGiftChecksum"],
    lineCount: 10,
    bodyC: "struct RecordMixingGiftData *data = &gSaveBlock1Ptr->recordMixingGift.data;\n    int checksum = CalcRecordMixingGiftChecksum();\n\n    if (data->unk0 == 0\n        || data->quantity == 0\n        || data->itemId == 0\n        || checksum == 0\n        || checksum != gSaveBlock1Ptr->recordMixingGift.checksum)\n        return FALSE;\n    else\n        return TRUE;",
  },
  "MEScrCmd_addrareword": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","StringExpandPlaceholders","UnlockTrendySaying"],
    lineCount: 4,
    bodyC: "UnlockTrendySaying(ScriptReadByte(ctx));\n    StringExpandPlaceholders(gStringVar4, gText_MysteryEventRareWord);\n    ctx->mStatus = MEVENT_STATUS_SUCCESS;\n    return FALSE;",
  },
  "MEScrCmd_addtrainer": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadWord","StringExpandPlaceholders","ValidateEReaderTrainer","memcpy"],
    lineCount: 6,
    bodyC: "u32 data = ScriptReadWord(ctx) - ctx->mOffset + ctx->mScriptBase;\n    memcpy(&gSaveBlock2Ptr->frontier.ereaderTrainer, (void *)data, sizeof(gSaveBlock2Ptr->frontier.ereaderTrainer));\n    ValidateEReaderTrainer();\n    StringExpandPlaceholders(gStringVar4, gText_MysteryEventNewTrainer);\n    ctx->mStatus = MEVENT_STATUS_SUCCESS;\n    return FALSE;",
  },
  "MEScrCmd_checkcompat": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CheckCompatibility","ScriptReadHalfword","ScriptReadWord","SetIncompatible"],
    lineCount: 14,
    bodyC: "u16 unk0;\n    u32 unk1;\n    u16 unk2;\n    u32 version;\n\n    ctx->mOffset = ScriptReadWord(ctx);\n    unk0 = ScriptReadHalfword(ctx);\n    unk1 = ScriptReadWord(ctx);\n    unk2 = ScriptReadHalfword(ctx);\n    version = ScriptReadWord(ctx);\n\n    if (CheckCompatibility(unk0, unk1, unk2, version) == TRUE)\n        ctx->mValid = TRUE;\n    else\n        SetIncompatible();\n\n    return TRUE;",
  },
  "MEScrCmd_checksum": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CalcByteArraySum","ScriptReadWord"],
    lineCount: 9,
    bodyC: "int checksum = ScriptReadWord(ctx);\n    u8 *data = (u8 *)(ScriptReadWord(ctx) - ctx->mOffset + ctx->mScriptBase);\n    u8 *dataEnd = (u8 *)(ScriptReadWord(ctx) - ctx->mOffset + ctx->mScriptBase);\n    if (checksum != CalcByteArraySum(data, dataEnd - data))\n    {\n        ctx->mValid = FALSE;\n        ctx->mStatus = MEVENT_STATUS_LOAD_ERROR;\n    }\n    return TRUE;",
  },
  "MEScrCmd_crc": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CalcCRC16","ScriptReadWord"],
    lineCount: 9,
    bodyC: "int crc = ScriptReadWord(ctx);\n    u8 *data = (u8 *)(ScriptReadWord(ctx) - ctx->mOffset + ctx->mScriptBase);\n    u8 *dataEnd = (u8 *)(ScriptReadWord(ctx) - ctx->mOffset + ctx->mScriptBase);\n    if (crc != CalcCRC16(data, dataEnd - data))\n    {\n        ctx->mValid = FALSE;\n        ctx->mStatus = MEVENT_STATUS_LOAD_ERROR;\n    }\n    return TRUE;",
  },
  "MEScrCmd_enableresetrtc": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["EnableResetRTC","StringExpandPlaceholders"],
    lineCount: 4,
    bodyC: "EnableResetRTC();\n    StringExpandPlaceholders(gStringVar4, gText_InGameClockUsable);\n    ctx->mStatus = MEVENT_STATUS_SUCCESS;\n    return FALSE;",
  },
  "MEScrCmd_end": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["StopScript"],
    lineCount: 2,
    bodyC: "StopScript(ctx);\n    return TRUE;",
  },
  "MEScrCmd_givenationaldex": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["EnableNationalPokedex","StringExpandPlaceholders"],
    lineCount: 4,
    bodyC: "EnableNationalPokedex();\n    StringExpandPlaceholders(gStringVar4, gText_MysteryEventNationalDex);\n    ctx->mStatus = MEVENT_STATUS_SUCCESS;\n    return FALSE;",
  },
  "MEScrCmd_givepokemon": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CalculatePlayerPartyCount","CompactPartySlots","GetMonData","GetSetPokedexFlag","GiveMailToMon","ItemIsMail","ScriptReadWord","SpeciesToNationalPokedexNum","StringCopyN","StringExpandPlaceholders","memcpy"],
    lineCount: 37,
    bodyC: "struct Mail mail;\n    struct Pokemon pokemon;\n    u16 species;\n    u16 heldItem;\n    u32 data = ScriptReadWord(ctx) - ctx->mOffset + ctx->mScriptBase;\n    void *pokemonPtr = (void *)data;\n    void *mailPtr = (void *)(data + sizeof(struct Pokemon));\n\n    pokemon = *(struct Pokemon *)pokemonPtr;\n    species = GetMonData(&pokemon, MON_DATA_SPECIES_OR_EGG);\n\n    if (species == SPECIES_EGG)\n        StringCopyN(gStringVar1, gText_EggNickname, POKEMON_NAME_LENGTH + 1);\n    else\n        StringCopyN(gStringVar1, gText_Pokemon, POKEMON_NAME_LENGTH + 1);\n\n    if (gPlayerPartyCount == PARTY_SIZE)\n    {\n        StringExpandPlaceholders(gStringVar4, gText_MysteryEventFullParty);\n        ctx->mStatus = MEVENT_STATUS_FAILURE;\n    }\n    else\n    {\n        memcpy(&gPlayerParty[PARTY_SIZE - 1], pokemonPtr, sizeof(struct Pokemon));\n        memcpy(&mail, mailPtr, sizeof(struct Mail));\n\n        if (species != SPECIES_EGG)\n        {\n            u16 pokedexNum = SpeciesToNationalPokedexNum(species);\n            GetSetPokedexFlag(pokedexNum, FLAG_SET_SEEN);\n            GetSetPokedexFlag(pokedexNum, FLAG_SET_CAUGHT);\n        }\n\n        heldItem = GetMonData(&gPlayerParty[PARTY_SIZE - 1], MON_DATA_HELD_ITEM);\n        if (ItemIsMail(heldItem))\n            GiveMailToMon(&gPlayerParty[PARTY_SIZE - 1], &mail);\n        CompactPartySlots();\n        CalculatePlayerPartyCount();\n        StringExpandPlaceholders(gStringVar4, gText_MysteryEventSentOver);\n        ctx->mStatus = MEVENT_STATUS_SUCCESS;\n    }\n\n    return FALSE;",
  },
  "MEScrCmd_giveribbon": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GiveGiftRibbonToParty","ScriptReadByte","StringExpandPlaceholders"],
    lineCount: 6,
    bodyC: "u8 index = ScriptReadByte(ctx);\n    u8 ribbonId = ScriptReadByte(ctx);\n    GiveGiftRibbonToParty(index, ribbonId);\n    StringExpandPlaceholders(gStringVar4, gText_MysteryEventSpecialRibbon);\n    ctx->mStatus = MEVENT_STATUS_SUCCESS;\n    return FALSE;",
  },
  "MEScrCmd_initramscript": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["InitRamScript","ScriptReadByte","ScriptReadWord"],
    lineCount: 7,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 objectId = ScriptReadByte(ctx);\n    u8 *script = (u8 *)(ScriptReadWord(ctx) - ctx->mOffset + ctx->mScriptBase);\n    u8 *scriptEnd = (u8 *)(ScriptReadWord(ctx) - ctx->mOffset + ctx->mScriptBase);\n    InitRamScript(script, scriptEnd - script, mapGroup, mapNum, objectId);\n    return FALSE;",
  },
  "MEScrCmd_nop": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    lineCount: 1,
    bodyC: "return FALSE;",
  },
  "MEScrCmd_runscript": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["RunScriptImmediately","ScriptReadWord"],
    lineCount: 3,
    bodyC: "u8 *script = (u8 *)(ScriptReadWord(ctx) - ctx->mOffset + ctx->mScriptBase);\n    RunScriptImmediately(script);\n    return FALSE;",
  },
  "MEScrCmd_setenigmaberry": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["IsEnigmaBerryValid","ScriptReadWord","SetEnigmaBerry","StringCompare","StringCopyN","StringExpandPlaceholders","VarSet"],
    lineCount: 29,
    bodyC: "u8 *str;\n    const u8 *message;\n    bool32 haveBerry = IsEnigmaBerryValid();\n    u8 *berry = (u8 *)(ScriptReadWord(ctx) - ctx->mOffset + ctx->mScriptBase);\n    StringCopyN(gStringVar1, gSaveBlock1Ptr->enigmaBerry.berry.name, BERRY_NAME_LENGTH + 1);\n    SetEnigmaBerry(berry);\n    StringCopyN(gStringVar2, gSaveBlock1Ptr->enigmaBerry.berry.name, BERRY_NAME_LENGTH + 1);\n\n    if (!haveBerry)\n    {\n        str = gStringVar4;\n        message = gText_MysteryEventBerry;\n    }\n    else if (StringCompare(gStringVar1, gStringVar2))\n    {\n        str = gStringVar4;\n        message = gText_MysteryEventBerryTransform;\n    }\n    else\n    {\n        str = gStringVar4;\n        message = gText_MysteryEventBerryObtained;\n    }\n\n    StringExpandPlaceholders(str, message);\n\n    ctx->mStatus = MEVENT_STATUS_SUCCESS;\n\n    if (IsEnigmaBerryValid() == TRUE)\n        VarSet(VAR_ENIGMA_BERRY_AVAILABLE, 1);\n    else\n        ctx->mStatus = MEVENT_STATUS_LOAD_ERROR;\n\n    return FALSE;",
  },
  "MEScrCmd_setmsg": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadWord","StringExpandPlaceholders"],
    lineCount: 5,
    bodyC: "u8 status = ScriptReadByte(ctx);\n    u8 *str = (u8 *)(ScriptReadWord(ctx) - ctx->mOffset + ctx->mScriptBase);\n    if (status == MEVENT_STATUS_FF || status == ctx->mStatus)\n        StringExpandPlaceholders(gStringVar4, str);\n    return FALSE;",
  },
  "MEScrCmd_setrecordmixinggift": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetRecordMixingGift"],
    lineCount: 5,
    bodyC: "u8 unk = ScriptReadByte(ctx);\n    u8 quantity = ScriptReadByte(ctx);\n    u16 itemId = ScriptReadHalfword(ctx);\n    SetRecordMixingGift(unk, quantity, itemId);\n    return FALSE;",
  },
  "MEScrCmd_setstatus": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte"],
    lineCount: 3,
    bodyC: "u8 status = ScriptReadByte(ctx);\n    ctx->mStatus = status;\n    return FALSE;",
  },
  "RunMysteryEventScript": {
    returnType: "u32",
    params: "u8 *script",
    callsTo: ["InitMysteryEventScript","RunMysteryEventScriptCommand"],
    lineCount: 4,
    bodyC: "struct ScriptContext *ctx = &sMysteryEventScriptContext;\n    InitMysteryEventScript(ctx, script);\n    while (RunMysteryEventScriptCommand(ctx));\n\n    return ctx->mStatus;",
  },
  "RunMysteryEventScriptCommand": {
    returnType: "static bool32",
    params: "struct ScriptContext *ctx",
    callsTo: ["RunScriptCommand"],
    lineCount: 4,
    bodyC: "if (RunScriptCommand(ctx) && ctx->mValid)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "RunMysteryEventScriptContextCommand": {
    returnType: "bool32",
    params: "u32 *status",
    callsTo: ["RunMysteryEventScriptCommand"],
    lineCount: 3,
    bodyC: "bool32 ret = RunMysteryEventScriptCommand(&sMysteryEventScriptContext);\n    *status = sMysteryEventScriptContext.mStatus;\n\n    return ret;",
  },
  "SetIncompatible": {
    returnType: "static void",
    params: "void",
    callsTo: ["SetMysteryEventScriptStatus","StringExpandPlaceholders"],
    lineCount: 2,
    bodyC: "StringExpandPlaceholders(gStringVar4, gText_MysteryEventCantBeUsed);\n    SetMysteryEventScriptStatus(MEVENT_STATUS_FAILURE);",
  },
  "SetMysteryEventScriptStatus": {
    returnType: "void",
    params: "u32 status",
    lineCount: 1,
    bodyC: "sMysteryEventScriptContext.mStatus = status;",
  },
  "SetRecordMixingGift": {
    returnType: "static void",
    params: "u8 unk, u8 quantity, u16 itemId",
    callsTo: ["CalcRecordMixingGiftChecksum","ClearRecordMixingGift"],
    lineCount: 11,
    bodyC: "if (!unk || !quantity || !itemId)\n    {\n        ClearRecordMixingGift();\n    }\n    else\n    {\n        gSaveBlock1Ptr->recordMixingGift.data.unk0 = unk;\n        gSaveBlock1Ptr->recordMixingGift.data.quantity = quantity;\n        gSaveBlock1Ptr->recordMixingGift.data.itemId = itemId;\n        gSaveBlock1Ptr->recordMixingGift.checksum = CalcRecordMixingGiftChecksum();\n    }",
  },
} as const;
