// AUTO-GENERATED from src/mystery_gift.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 45

export const ENGINE_FUNCTIONS = {
  "ClearMysteryGift": {
    returnType: "void",
    params: "void",
    callsTo: ["ClearSavedWonderNewsMetadata","CpuFill32","InitQuestionnaireWords"],
    lineCount: 3,
    bodyC: "CpuFill32(0, &gSaveBlock1Ptr->mysteryGift, sizeof(gSaveBlock1Ptr->mysteryGift));\n    ClearSavedWonderNewsMetadata();  \n    InitQuestionnaireWords();",
  },
  "ClearSavedTrainerIds": {
    returnType: "static void",
    params: "void",
    callsTo: ["CpuFill32"],
    lineCount: 1,
    bodyC: "CpuFill32(0, gSaveBlock1Ptr->mysteryGift.trainerIds, sizeof(gSaveBlock1Ptr->mysteryGift.trainerIds));",
  },
  "ClearSavedWonderCard": {
    returnType: "static void",
    params: "void",
    callsTo: ["CpuFill32"],
    lineCount: 2,
    bodyC: "CpuFill32(0, &gSaveBlock1Ptr->mysteryGift.card, sizeof(gSaveBlock1Ptr->mysteryGift.card));\n    gSaveBlock1Ptr->mysteryGift.cardCrc = 0;",
  },
  "ClearSavedWonderCardAndRelated": {
    returnType: "void",
    params: "void",
    callsTo: ["ClearEReaderTrainer","ClearMysteryGiftFlags","ClearMysteryGiftVars","ClearRamScript","ClearSavedTrainerIds","ClearSavedWonderCard","ClearSavedWonderCardMetadata"],
    lineCount: 7,
    bodyC: "ClearSavedWonderCard();\n    ClearSavedWonderCardMetadata();\n    ClearSavedTrainerIds();\n    ClearRamScript();\n    ClearMysteryGiftFlags();\n    ClearMysteryGiftVars();\n    ClearEReaderTrainer(&gSaveBlock2Ptr->frontier.ereaderTrainer);",
  },
  "ClearSavedWonderCardMetadata": {
    returnType: "static void",
    params: "void",
    callsTo: ["CpuFill32","GetSavedWonderCardMetadata"],
    lineCount: 2,
    bodyC: "CpuFill32(0, GetSavedWonderCardMetadata(), sizeof(gSaveBlock1Ptr->mysteryGift.cardMetadata));\n    gSaveBlock1Ptr->mysteryGift.cardMetadataCrc = 0;",
  },
  "ClearSavedWonderNews": {
    returnType: "static void",
    params: "void",
    callsTo: ["CpuFill32","GetSavedWonderNews"],
    lineCount: 2,
    bodyC: "CpuFill32(0, GetSavedWonderNews(), sizeof(gSaveBlock1Ptr->mysteryGift.news));\n    gSaveBlock1Ptr->mysteryGift.newsCrc = 0;",
  },
  "ClearSavedWonderNewsAndRelated": {
    returnType: "void",
    params: "void",
    callsTo: ["ClearSavedWonderNews"],
    lineCount: 1,
    bodyC: "ClearSavedWonderNews();",
  },
  "ClearSavedWonderNewsMetadata": {
    returnType: "static void",
    params: "void",
    callsTo: ["CpuFill32","GetSavedWonderNewsMetadata","WonderNews_Reset"],
    lineCount: 2,
    bodyC: "CpuFill32(0, GetSavedWonderNewsMetadata(), sizeof(gSaveBlock1Ptr->mysteryGift.newsMetadata));\n    WonderNews_Reset();",
  },
  "DisableWonderCardSending": {
    returnType: "void",
    params: "struct WonderCard *card",
    lineCount: 2,
    bodyC: "if (card->sendType == SEND_TYPE_ALLOWED)\n        card->sendType = SEND_TYPE_DISALLOWED;",
  },
  "GetNumStampsInLinkData": {
    returnType: "static int",
    params: "const struct MysteryGiftLinkGameData *data",
    callsTo: ["GetNumStampsInMetadata"],
    lineCount: 1,
    bodyC: "return GetNumStampsInMetadata(&data->cardMetadata, data->maxStamps);",
  },
  "GetNumStampsInMetadata": {
    returnType: "static int",
    params: "const struct WonderCardMetadata *data, int size",
    lineCount: 8,
    bodyC: "int numStamps = 0;\n    int i;\n    for (i = 0; i < size; i++)\n    {\n        if (data->stampData[STAMP_ID][i] && data->stampData[STAMP_SPECIES][i] != SPECIES_NONE)\n            numStamps++;\n    }\n\n    return numStamps;",
  },
  "GetNumStampsInSavedCard": {
    returnType: "static int",
    params: "void",
    callsTo: ["GetNumStampsInMetadata","ValidateSavedWonderCard"],
    lineCount: 7,
    bodyC: "struct WonderCard *card;\n    if (!ValidateSavedWonderCard())\n        return 0;\n\n    card = &gSaveBlock1Ptr->mysteryGift.card;\n    if (card->type != CARD_TYPE_STAMP)\n        return 0;\n\n    return GetNumStampsInMetadata(&gSaveBlock1Ptr->mysteryGift.cardMetadata, card->maxStamps);",
  },
  "GetQuestionnaireWordsPtr": {
    returnType: "u16 *",
    params: "void",
    lineCount: 1,
    bodyC: "return gSaveBlock1Ptr->mysteryGift.questionnaireWords;",
  },
  "GetSavedWonderCard": {
    returnType: "struct WonderCard *",
    params: "void",
    lineCount: 1,
    bodyC: "return &gSaveBlock1Ptr->mysteryGift.card;",
  },
  "GetSavedWonderCardMetadata": {
    returnType: "struct WonderCardMetadata *",
    params: "void",
    lineCount: 1,
    bodyC: "return &gSaveBlock1Ptr->mysteryGift.cardMetadata;",
  },
  "GetSavedWonderNews": {
    returnType: "struct WonderNews *",
    params: "void",
    lineCount: 1,
    bodyC: "return &gSaveBlock1Ptr->mysteryGift.news;",
  },
  "GetSavedWonderNewsMetadata": {
    returnType: "struct WonderNewsMetadata *",
    params: "void",
    lineCount: 1,
    bodyC: "return &gSaveBlock1Ptr->mysteryGift.newsMetadata;",
  },
  "GetWonderCardFlagID": {
    returnType: "u16",
    params: "void",
    callsTo: ["ValidateSavedWonderCard"],
    lineCount: 3,
    bodyC: "if (ValidateSavedWonderCard())\n        return gSaveBlock1Ptr->mysteryGift.card.flagId;\n\n    return 0;",
  },
  "IncrementCardStat": {
    returnType: "static void",
    params: "u32 statType",
    callsTo: ["AGB_ASSERT"],
    lineCount: 28,
    bodyC: "struct WonderCard *card = &gSaveBlock1Ptr->mysteryGift.card;\n    if (card->type == CARD_TYPE_LINK_STAT)\n    {\n        u16 *stat = NULL;\n        switch (statType)\n        {\n        case CARD_STAT_BATTLES_WON:\n            stat = &gSaveBlock1Ptr->mysteryGift.cardMetadata.battlesWon;\n            break;\n        case CARD_STAT_BATTLES_LOST:\n            stat = &gSaveBlock1Ptr->mysteryGift.cardMetadata.battlesLost;\n            break;\n        case CARD_STAT_NUM_TRADES:\n            stat = &gSaveBlock1Ptr->mysteryGift.cardMetadata.numTrades;\n            break;\n        case CARD_STAT_NUM_STAMPS:  \n        case CARD_STAT_MAX_STAMPS:  \n            break;\n        }\n\n        if (stat == NULL)\n        {\n            AGB_ASSERT(0);\n        }\n        else if (++(*stat) > MAX_WONDER_CARD_STAT)\n        {\n            *stat = MAX_WONDER_CARD_STAT;\n        }\n    }",
  },
  "IncrementCardStatForNewTrainer": {
    returnType: "static void",
    params: "u32 stat, u32 trainerId, u32 *trainerIds, int size",
    callsTo: ["IncrementCardStat","RecordTrainerId"],
    lineCount: 2,
    bodyC: "if (RecordTrainerId(trainerId, trainerIds, size))\n        IncrementCardStat(stat);",
  },
  "IsSavedWonderCardGiftNotReceived": {
    returnType: "bool32",
    params: "void",
    callsTo: ["FlagGet","GetWonderCardFlagID","IsWonderCardFlagIDInValidRange"],
    lineCount: 6,
    bodyC: "u16 value = GetWonderCardFlagID();\n    if (!IsWonderCardFlagIDInValidRange(value))\n        return FALSE;\n\n     \n    if (FlagGet(sReceivedGiftFlags[value - WONDER_CARD_FLAG_OFFSET]) == TRUE)\n        return FALSE;\n\n    return TRUE;",
  },
  "IsSendingSavedWonderCardAllowed": {
    returnType: "bool32",
    params: "void",
    lineCount: 4,
    bodyC: "const struct WonderCard *card = &gSaveBlock1Ptr->mysteryGift.card;\n    if (card->sendType == SEND_TYPE_DISALLOWED)\n        return FALSE;\n\n    return TRUE;",
  },
  "IsSendingSavedWonderNewsAllowed": {
    returnType: "bool32",
    params: "void",
    lineCount: 4,
    bodyC: "const struct WonderNews *news = &gSaveBlock1Ptr->mysteryGift.news;\n    if (news->sendType == SEND_TYPE_DISALLOWED)\n        return FALSE;\n\n    return TRUE;",
  },
  "IsStampInMetadata": {
    returnType: "static bool32",
    params: "const struct WonderCardMetadata *metadata, const u16 *stamp, int maxStamps",
    lineCount: 9,
    bodyC: "int i;\n    for (i = 0; i < maxStamps; i++)\n    {\n        if (metadata->stampData[STAMP_ID][i] == stamp[STAMP_ID])\n            return TRUE;\n        if (metadata->stampData[STAMP_SPECIES][i] == stamp[STAMP_SPECIES])\n            return TRUE;\n    }\n\n    return FALSE;",
  },
  "IsWonderCardFlagIDInValidRange": {
    returnType: "static bool32",
    params: "u16 flagId",
    lineCount: 3,
    bodyC: "if (flagId >= WONDER_CARD_FLAG_OFFSET && flagId < WONDER_CARD_FLAG_OFFSET + NUM_WONDER_CARD_FLAGS)\n        return TRUE;\n\n    return FALSE;",
  },
  "IsWonderNewsSameAsSaved": {
    returnType: "bool32",
    params: "const u8 *news",
    callsTo: ["ValidateSavedWonderNews"],
    lineCount: 10,
    bodyC: "const u8 *savedNews = (const u8 *)&gSaveBlock1Ptr->mysteryGift.news;\n    u32 i;\n    if (!ValidateSavedWonderNews())\n        return FALSE;\n\n    for (i = 0; i < sizeof(gSaveBlock1Ptr->mysteryGift.news); i++)\n    {\n        if (savedNews[i] != news[i])\n            return FALSE;\n    }\n\n    return TRUE;",
  },
  "MysteryGift_CheckStamps": {
    returnType: "u32",
    params: "const u16 *stamp, const struct MysteryGiftLinkGameData *data, const void *unused",
    callsTo: ["GetNumStampsInMetadata","IsStampInMetadata"],
    lineCount: 8,
    bodyC: "int stampsMissing = data->maxStamps - GetNumStampsInMetadata(&data->cardMetadata, data->maxStamps);\n\n     \n    if (stampsMissing == 0)\n        return 1;\n\n     \n    if (IsStampInMetadata(&data->cardMetadata, stamp, data->maxStamps))\n        return 3;\n\n     \n    if (stampsMissing == 1)\n        return 4;\n\n     \n    return 2;",
  },
  "MysteryGift_CompareCardFlags": {
    returnType: "u32",
    params: "const u16 *flagId, const struct MysteryGiftLinkGameData *data, const void *unused",
    lineCount: 5,
    bodyC: "if (data->flagId == 0)\n        return HAS_NO_CARD;\n\n     \n    if (*flagId == data->flagId)\n        return HAS_SAME_CARD;\n\n     \n    return HAS_DIFF_CARD;",
  },
  "MysteryGift_DisableStats": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "sStatsEnabled = FALSE;",
  },
  "MysteryGift_DoesQuestionnaireMatch": {
    returnType: "bool32",
    params: "const struct MysteryGiftLinkGameData *data, const u16 *words",
    lineCount: 7,
    bodyC: "int i;\n    for (i = 0; i < NUM_QUESTIONNAIRE_WORDS; i++)\n    {\n        if (data->questionnaireWords[i] != words[i])\n            return FALSE;\n    }\n\n    return TRUE;",
  },
  "MysteryGift_GetCardStat": {
    returnType: "u16",
    params: "u32 stat",
    callsTo: ["AGB_ASSERT","GetNumStampsInSavedCard"],
    lineCount: 49,
    bodyC: "switch (stat)\n    {\n    case CARD_STAT_BATTLES_WON:\n    {\n        struct WonderCard *card = &gSaveBlock1Ptr->mysteryGift.card;\n        if (card->type == CARD_TYPE_LINK_STAT)\n        {\n            struct WonderCardMetadata *metadata = &gSaveBlock1Ptr->mysteryGift.cardMetadata;\n            return metadata->battlesWon;\n        }\n        break;\n    }\n    case CARD_STAT_BATTLES_LOST:\n    {\n        struct WonderCard *card = &gSaveBlock1Ptr->mysteryGift.card;\n        if (card->type == CARD_TYPE_LINK_STAT)\n        {\n            struct WonderCardMetadata *metadata = &gSaveBlock1Ptr->mysteryGift.cardMetadata;\n            return metadata->battlesLost;\n        }\n        break;\n    }\n    case CARD_STAT_NUM_TRADES:\n    {\n        struct WonderCard *card = &gSaveBlock1Ptr->mysteryGift.card;\n        if (card->type == CARD_TYPE_LINK_STAT)\n        {\n            struct WonderCardMetadata *metadata = &gSaveBlock1Ptr->mysteryGift.cardMetadata;\n            return metadata->numTrades;\n        }\n        break;\n    }\n    case CARD_STAT_NUM_STAMPS:\n    {\n        struct WonderCard *card = &gSaveBlock1Ptr->mysteryGift.card;\n        if (card->type == CARD_TYPE_STAMP)\n            return GetNumStampsInSavedCard();\n        break;\n    }\n    case CARD_STAT_MAX_STAMPS:\n    {\n        struct WonderCard *card = &gSaveBlock1Ptr->mysteryGift.card;\n        if (card->type == CARD_TYPE_STAMP)\n            return card->maxStamps;\n        break;\n    }\n    }\n\n    AGB_ASSERT(0);\n    return 0;",
  },
  "MysteryGift_GetCardStatFromLinkData": {
    returnType: "u16",
    params: "const struct MysteryGiftLinkGameData *data, u32 stat",
    callsTo: ["AGB_ASSERT","GetNumStampsInLinkData"],
    lineCount: 16,
    bodyC: "switch (stat)\n    {\n    case CARD_STAT_BATTLES_WON:\n        return data->cardMetadata.battlesWon;\n    case CARD_STAT_BATTLES_LOST:\n        return data->cardMetadata.battlesLost;\n    case CARD_STAT_NUM_TRADES:\n        return data->cardMetadata.numTrades;\n    case CARD_STAT_NUM_STAMPS:\n        return GetNumStampsInLinkData(data);\n    case CARD_STAT_MAX_STAMPS:\n        return data->maxStamps;\n    default:\n        AGB_ASSERT(0);\n        return 0;\n    }",
  },
  "MysteryGift_LoadLinkGameData": {
    returnType: "void",
    params: "struct MysteryGiftLinkGameData *data, bool32 isWonderNews",
    callsTo: ["CopyTrainerId","CpuFill32","GetSavedWonderCard","GetSavedWonderCardMetadata","StringCopy","ValidateSavedWonderCard","memcpy"],
    lineCount: 33,
    bodyC: "int i;\n    CpuFill32(0, data, sizeof(*data));\n    data->validationVar = GAME_DATA_VALID_VAR;\n    data->validationFlag1 = 1;\n    data->validationFlag2 = 1;\n\n    if (isWonderNews)\n    {\n         \n         \n        data->validationGiftType1 = GAME_DATA_VALID_GIFT_TYPE_1 | 1;\n        data->validationGiftType2 = GAME_DATA_VALID_GIFT_TYPE_2 | 1;\n    }\n    else  \n    {\n        data->validationGiftType1 = GAME_DATA_VALID_GIFT_TYPE_1;\n        data->validationGiftType2 = GAME_DATA_VALID_GIFT_TYPE_2;\n    }\n\n    if (ValidateSavedWonderCard())\n    {\n        data->flagId = GetSavedWonderCard()->flagId;\n        data->cardMetadata = *GetSavedWonderCardMetadata();\n        data->maxStamps = GetSavedWonderCard()->maxStamps;\n    }\n    else\n    {\n        data->flagId = 0;\n    }\n\n    for (i = 0; i < NUM_QUESTIONNAIRE_WORDS; i++)\n        data->questionnaireWords[i] = gSaveBlock1Ptr->mysteryGift.questionnaireWords[i];\n\n    CopyTrainerId(data->playerTrainerId, gSaveBlock2Ptr->playerTrainerId);\n    StringCopy(data->playerName, gSaveBlock2Ptr->playerName);\n    for (i = 0; i < EASY_CHAT_BATTLE_WORDS_COUNT; i++)\n        data->easyChatProfile[i] = gSaveBlock1Ptr->easyChatProfile[i];\n\n    memcpy(data->romHeaderGameCode, RomHeaderGameCode, GAME_CODE_LENGTH);\n    data->romHeaderSoftwareVersion = RomHeaderSoftwareVersion;",
  },
  "MysteryGift_TryEnableStatsByFlagId": {
    returnType: "bool32",
    params: "u16 flagId",
    callsTo: ["ValidateSavedWonderCard"],
    lineCount: 9,
    bodyC: "sStatsEnabled = FALSE;\n    if (flagId == 0)\n        return FALSE;\n\n    if (!ValidateSavedWonderCard())\n        return FALSE;\n\n    if (gSaveBlock1Ptr->mysteryGift.card.flagId != flagId)\n        return FALSE;\n\n    sStatsEnabled = TRUE;\n    return TRUE;",
  },
  "MysteryGift_TryIncrementStat": {
    returnType: "void",
    params: "u32 stat, u32 trainerId",
    callsTo: ["AGB_ASSERT","ARRAY_COUNT","IncrementCardStatForNewTrainer"],
    lineCount: 27,
    bodyC: "if (sStatsEnabled)\n    {\n        switch (stat)\n        {\n        case CARD_STAT_NUM_TRADES:\n            IncrementCardStatForNewTrainer(CARD_STAT_NUM_TRADES,\n                                            trainerId,\n                                            gSaveBlock1Ptr->mysteryGift.trainerIds[1],\n                                            ARRAY_COUNT(gSaveBlock1Ptr->mysteryGift.trainerIds[1]));\n            break;\n        case CARD_STAT_BATTLES_WON:\n            IncrementCardStatForNewTrainer(CARD_STAT_BATTLES_WON,\n                                            trainerId,\n                                            gSaveBlock1Ptr->mysteryGift.trainerIds[0],\n                                            ARRAY_COUNT(gSaveBlock1Ptr->mysteryGift.trainerIds[0]));\n            break;\n        case CARD_STAT_BATTLES_LOST:\n            IncrementCardStatForNewTrainer(CARD_STAT_BATTLES_LOST,\n                                            trainerId,\n                                            gSaveBlock1Ptr->mysteryGift.trainerIds[0],\n                                            ARRAY_COUNT(gSaveBlock1Ptr->mysteryGift.trainerIds[0]));\n            break;\n        default:\n            AGB_ASSERT(0);\n            break;\n        }\n    }",
  },
  "MysteryGift_TrySaveStamp": {
    returnType: "bool32",
    params: "const u16 *stamp",
    callsTo: ["IsStampInMetadata","ValidateStamp"],
    lineCount: 18,
    bodyC: "struct WonderCard *card = &gSaveBlock1Ptr->mysteryGift.card;\n    int maxStamps = card->maxStamps;\n    int i;\n    if (!ValidateStamp(stamp))\n        return FALSE;\n\n    if (IsStampInMetadata(&gSaveBlock1Ptr->mysteryGift.cardMetadata, stamp, maxStamps))\n        return FALSE;\n\n    for (i = 0; i < maxStamps; i++)\n    {\n        if (gSaveBlock1Ptr->mysteryGift.cardMetadata.stampData[STAMP_ID][i] == 0\n         && gSaveBlock1Ptr->mysteryGift.cardMetadata.stampData[STAMP_SPECIES][i] == SPECIES_NONE)\n        {\n            gSaveBlock1Ptr->mysteryGift.cardMetadata.stampData[STAMP_ID][i] = stamp[STAMP_ID];\n            gSaveBlock1Ptr->mysteryGift.cardMetadata.stampData[STAMP_SPECIES][i] = stamp[STAMP_SPECIES];\n            return TRUE;\n        }\n    }\n\n    return FALSE;",
  },
  "MysteryGift_ValidateLinkGameData": {
    returnType: "bool32",
    params: "const struct MysteryGiftLinkGameData *data, bool32 isWonderNews",
    lineCount: 14,
    bodyC: "if (data->validationVar != GAME_DATA_VALID_VAR)\n        return FALSE;\n\n    if (!(data->validationFlag1 & 1))\n        return FALSE;\n\n    if (!(data->validationFlag2 & 1))\n        return FALSE;\n\n    if (!isWonderNews)\n    {\n        if (!(data->validationGiftType1 & GAME_DATA_VALID_GIFT_TYPE_1))\n            return FALSE;\n\n        if (!(data->validationGiftType2 & (GAME_DATA_VALID_GIFT_TYPE_2 | 0x180)))\n            return FALSE;\n    }\n\n    return TRUE;",
  },
  "RecordTrainerId": {
    returnType: "static bool32",
    params: "u32 trainerId, u32 *trainerIds, int size",
    lineCount: 20,
    bodyC: "int i, j;\n\n    for (i = 0; i < size; i++)\n    {\n        if (trainerIds[i] == trainerId)\n            break;\n    }\n\n    if (i == size)\n    {\n         \n        for (j = size - 1; j > 0; j--)\n            trainerIds[j] = trainerIds[j - 1];\n\n        trainerIds[0] = trainerId;\n        return TRUE;\n    }\n    else\n    {\n         \n        for (j = i; j > 0; j--)\n            trainerIds[j] = trainerIds[j - 1];\n\n        trainerIds[0] = trainerId;\n        return FALSE;\n    }",
  },
  "SaveWonderCard": {
    returnType: "bool32",
    params: "const struct WonderCard *card",
    callsTo: ["CALC_CRC","ClearSavedWonderCardAndRelated","ValidateWonderCard","memcpy"],
    lineCount: 9,
    bodyC: "struct WonderCardMetadata *metadata;\n    if (!ValidateWonderCard(card))\n        return FALSE;\n\n    ClearSavedWonderCardAndRelated();\n    memcpy(&gSaveBlock1Ptr->mysteryGift.card, card, sizeof(struct WonderCard));\n    gSaveBlock1Ptr->mysteryGift.cardCrc = CALC_CRC(gSaveBlock1Ptr->mysteryGift.card);\n    metadata = &gSaveBlock1Ptr->mysteryGift.cardMetadata;\n    metadata->iconSpecies = (&gSaveBlock1Ptr->mysteryGift.card)->iconSpecies;\n    return TRUE;",
  },
  "SaveWonderNews": {
    returnType: "bool32",
    params: "const struct WonderNews *news",
    callsTo: ["CALC_CRC","ClearSavedWonderNews","ValidateWonderNews"],
    lineCount: 6,
    bodyC: "if (!ValidateWonderNews(news))\n        return FALSE;\n\n    ClearSavedWonderNews();\n    gSaveBlock1Ptr->mysteryGift.news = *news;\n    gSaveBlock1Ptr->mysteryGift.newsCrc = CALC_CRC(gSaveBlock1Ptr->mysteryGift.news);\n    return TRUE;",
  },
  "ValidateSavedWonderCard": {
    returnType: "bool32",
    params: "void",
    callsTo: ["CALC_CRC","ValidateSavedRamScript","ValidateWonderCard"],
    lineCount: 7,
    bodyC: "if (gSaveBlock1Ptr->mysteryGift.cardCrc != CALC_CRC(gSaveBlock1Ptr->mysteryGift.card))\n        return FALSE;\n    if (!ValidateWonderCard(&gSaveBlock1Ptr->mysteryGift.card))\n        return FALSE;\n    if (!ValidateSavedRamScript())\n        return FALSE;\n\n    return TRUE;",
  },
  "ValidateSavedWonderNews": {
    returnType: "bool32",
    params: "void",
    callsTo: ["CALC_CRC","ValidateWonderNews"],
    lineCount: 5,
    bodyC: "if (CALC_CRC(gSaveBlock1Ptr->mysteryGift.news) != gSaveBlock1Ptr->mysteryGift.newsCrc)\n        return FALSE;\n    if (!ValidateWonderNews(&gSaveBlock1Ptr->mysteryGift.news))\n        return FALSE;\n\n    return TRUE;",
  },
  "ValidateStamp": {
    returnType: "static bool32",
    params: "const u16 *stamp",
    lineCount: 7,
    bodyC: "if (stamp[STAMP_ID] == 0)\n        return FALSE;\n    if (stamp[STAMP_SPECIES] == SPECIES_NONE)\n        return FALSE;\n    if (stamp[STAMP_SPECIES] >= NUM_SPECIES)\n        return FALSE;\n    return TRUE;",
  },
  "ValidateWonderCard": {
    returnType: "static bool32",
    params: "const struct WonderCard *card",
    lineCount: 13,
    bodyC: "if (card->flagId == 0)\n        return FALSE;\n    if (card->type >= CARD_TYPE_COUNT)\n        return FALSE;\n    if (!(card->sendType == SEND_TYPE_DISALLOWED\n       || card->sendType == SEND_TYPE_ALLOWED\n       || card->sendType == SEND_TYPE_ALLOWED_ALWAYS))\n        return FALSE;\n    if (card->bgType >= NUM_WONDER_BGS)\n        return FALSE;\n    if (card->maxStamps > MAX_STAMP_CARD_STAMPS)\n        return FALSE;\n\n    return TRUE;",
  },
  "ValidateWonderNews": {
    returnType: "static bool32",
    params: "const struct WonderNews *news",
    lineCount: 3,
    bodyC: "if (news->id == 0)\n        return FALSE;\n\n    return TRUE;",
  },
} as const;
