// AUTO-GENERATED from src/naming_screen.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 106

export const ENGINE_FUNCTIONS = {
  "AddTextCharacter": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["BufferCharacter","CopyBgTilemapBufferToVram","DrawTextEntry","GetCharAtKeyboardPos","GetCursorPos","GetPreviousTextCaretPosition","PlaySE"],
    lineCount: 11,
    bodyC: "s16 x;\n    s16 y;\n\n    GetCursorPos(&x, &y);\n    BufferCharacter(GetCharAtKeyboardPos(x, y));\n    DrawTextEntry();\n    CopyBgTilemapBufferToVram(3);\n    PlaySE(SE_SELECT);\n\n    if (GetPreviousTextCaretPosition() != sNamingScreen->template->maxChars - 1)\n        return FALSE;\n    else\n        return TRUE;",
  },
  "BufferCharacter": {
    returnType: "static void",
    params: "u8 ch",
    callsTo: ["GetTextEntryPosition"],
    lineCount: 2,
    bodyC: "u8 index = GetTextEntryPosition();\n    sNamingScreen->textBuffer[index] = ch;",
  },
  "CB2_LoadNamingScreen": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateHelperTasks","CreateNamingScreenTask","CreateSprites","FreeAllSpritePalettes","LoadGfx","LoadPalettes","NamingScreen_Init","NamingScreen_InitBGs","NamingScreen_ShowBgs","ResetPaletteFade","ResetSpriteData","ResetTasks","ResetVHBlank","UpdatePaletteFade"],
    lineCount: 43,
    bodyC: "switch (gMain.state)\n    {\n    case 0:\n        ResetVHBlank();\n        NamingScreen_Init();\n        gMain.state++;\n        break;\n    case 1:\n        NamingScreen_InitBGs();\n        gMain.state++;\n        break;\n    case 2:\n        ResetPaletteFade();\n        gMain.state++;\n        break;\n    case 3:\n        ResetSpriteData();\n        FreeAllSpritePalettes();\n        gMain.state++;\n        break;\n    case 4:\n        ResetTasks();\n        gMain.state++;\n        break;\n    case 5:\n        LoadPalettes();\n        gMain.state++;\n        break;\n    case 6:\n        LoadGfx();\n        gMain.state++;\n        break;\n    case 7:\n        CreateSprites();\n        UpdatePaletteFade();\n        NamingScreen_ShowBgs();\n        gMain.state++;\n        break;\n    default:\n        CreateHelperTasks();\n        CreateNamingScreenTask();\n        break;\n    }",
  },
  "CB2_NamingScreen": {
    returnType: "static void",
    params: "void",
    callsTo: ["AnimateSprites","BuildOamBuffer","RunTasks","UpdatePaletteFade"],
    lineCount: 4,
    bodyC: "RunTasks();\n    AnimateSprites();\n    BuildOamBuffer();\n    UpdatePaletteFade();",
  },
  "CreateBackOkSprites": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateSprite","SetSubspriteTables"],
    lineCount: 7,
    bodyC: "u8 spriteId;\n\n    spriteId = CreateSprite(&sSpriteTemplate_BackButton, 204, 116, 0);\n    SetSubspriteTables(&gSprites[spriteId], sSubspriteTable_Button);\n    gSprites[spriteId].invisible = TRUE;\n\n    spriteId = CreateSprite(&sSpriteTemplate_OkButton, 204, 140, 0);\n    SetSubspriteTables(&gSprites[spriteId], sSubspriteTable_Button);\n    gSprites[spriteId].invisible = TRUE;",
  },
  "CreateButtonFlashTask": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateTask"],
    lineCount: 3,
    bodyC: "u8 taskId;\n\n    taskId = CreateTask(Task_UpdateButtonFlash, 3);\n    gTasks[taskId].tButtonId = BUTTON_COUNT;",
  },
  "CreateCursorSprite": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateSprite","SetCursorInvisibility","SetCursorPos"],
    lineCount: 7,
    bodyC: "sNamingScreen->cursorSpriteId = CreateSprite(&sSpriteTemplate_Cursor, 38, 88, 1);\n    SetCursorInvisibility(TRUE);\n    gSprites[sNamingScreen->cursorSpriteId].oam.priority = 1;\n    gSprites[sNamingScreen->cursorSpriteId].oam.objMode = ST_OAM_OBJ_BLEND;\n    gSprites[sNamingScreen->cursorSpriteId].sColorIncr = 1;  \n    gSprites[sNamingScreen->cursorSpriteId].sColorIncr = 2;\n    SetCursorPos(0, 0);",
  },
  "CreateHelperTasks": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateButtonFlashTask","CreateInputHandlerTask"],
    lineCount: 2,
    bodyC: "CreateInputHandlerTask();\n    CreateButtonFlashTask();",
  },
  "CreateInputHandlerTask": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateTask"],
    lineCount: 1,
    bodyC: "CreateTask(Task_HandleInput, 1);",
  },
  "CreateInputTargetIcon": {
    returnType: "static void",
    params: "void",
    lineCount: 1,
    bodyC: "sIconFunctions[sNamingScreen->template->iconFunction]();",
  },
  "CreateNamingScreenTask": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateTask","SetMainCallback2"],
    lineCount: 2,
    bodyC: "CreateTask(Task_NamingScreen, 2);\n    SetMainCallback2(CB2_NamingScreen);",
  },
  "CreatePageSwapButtonSprites": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateSprite","SetSubspriteTables"],
    lineCount: 15,
    bodyC: "u8 frameSpriteId;\n    u8 textSpriteId;\n    u8 buttonSpriteId;\n\n    frameSpriteId = CreateSprite(&sSpriteTemplate_PageSwapFrame, 204, 88, 0);\n    sNamingScreen->swapBtnFrameSpriteId = frameSpriteId;\n    SetSubspriteTables(&gSprites[frameSpriteId], sSubspriteTable_PageSwapFrame);\n    gSprites[frameSpriteId].invisible = TRUE;\n\n    textSpriteId = CreateSprite(&sSpriteTemplate_PageSwapText, 204, 84, 1);\n    gSprites[frameSpriteId].sTextSpriteId = textSpriteId;\n    SetSubspriteTables(&gSprites[textSpriteId], sSubspriteTable_PageSwapText);\n    gSprites[textSpriteId].invisible = TRUE;\n\n    buttonSpriteId = CreateSprite(&sSpriteTemplate_PageSwapButton, 204, 83, 2);\n    gSprites[buttonSpriteId].oam.priority = 1;\n    gSprites[frameSpriteId].sButtonSpriteId = buttonSpriteId;\n    gSprites[buttonSpriteId].invisible = TRUE;",
  },
  "CreateSprites": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateBackOkSprites","CreateCursorSprite","CreateInputTargetIcon","CreatePageSwapButtonSprites","CreateTextEntrySprites"],
    lineCount: 5,
    bodyC: "CreateCursorSprite();\n    CreatePageSwapButtonSprites();\n    CreateBackOkSprites();\n    CreateTextEntrySprites();\n    CreateInputTargetIcon();",
  },
  "CreateTextEntrySprites": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateSprite"],
    lineCount: 15,
    bodyC: "u8 spriteId;\n    s16 xPos;\n    u8 i;\n\n    xPos = sNamingScreen->inputCharBaseXPos - 5;\n    spriteId = CreateSprite(&sSpriteTemplate_InputArrow, xPos, 56, 0);\n    gSprites[spriteId].oam.priority = 3;\n    gSprites[spriteId].invisible = TRUE;\n    xPos = sNamingScreen->inputCharBaseXPos;\n    for (i = 0; i < sNamingScreen->template->maxChars; i++, xPos += 8)\n    {\n        spriteId = CreateSprite(&sSpriteTemplate_Underscore, xPos + 3, 60, 0);\n        gSprites[spriteId].oam.priority = 3;\n        gSprites[spriteId].data[0] = i;\n        gSprites[spriteId].invisible = TRUE;\n    }",
  },
  "CurrentPageToKeyboardId": {
    returnType: "static u8",
    params: "void",
    lineCount: 1,
    bodyC: "return sPageToKeyboardId[sNamingScreen->currentPage];",
  },
  "CurrentPageToNextKeyboardId": {
    returnType: "static u8",
    params: "void",
    lineCount: 1,
    bodyC: "return sPageToNextKeyboardId[sNamingScreen->currentPage];",
  },
  "DeleteTextCharacter": {
    returnType: "static void",
    params: "void",
    callsTo: ["CopyBgTilemapBufferToVram","DrawTextEntry","GetKeyRoleAtCursorPos","GetPreviousTextCaretPosition","PlaySE","TryStartButtonFlash"],
    lineCount: 11,
    bodyC: "u8 index;\n    u8 keyRole;\n\n    index = GetPreviousTextCaretPosition();\n    sNamingScreen->textBuffer[index] = 0;\n    DrawTextEntry();\n    CopyBgTilemapBufferToVram(3);\n    sNamingScreen->textBuffer[index] = EOS;\n    keyRole = GetKeyRoleAtCursorPos();\n\n     \n     \n    if (keyRole == KEY_ROLE_CHAR || keyRole == KEY_ROLE_BACKSPACE)\n        TryStartButtonFlash(BUTTON_BACK, FALSE, TRUE);\n    PlaySE(SE_BALL);",
  },
  "DisplaySentToPCMessage": {
    returnType: "static void",
    params: "void",
    callsTo: ["AddTextPrinterParameterized2","CopyWindowToVram","DrawDialogueFrame","FlagGet","GetBoxNamePtr","GetPCBoxToSendMon","GetPlayerTextSpeedDelay","IsDestinationBoxFull","StringCopy","StringExpandPlaceholders","VarGet"],
    lineCount: 20,
    bodyC: "u8 stringToDisplay = 0;\n\n    if (!IsDestinationBoxFull())\n    {\n        StringCopy(gStringVar1, GetBoxNamePtr(VarGet(VAR_PC_BOX_TO_SEND_MON)));\n        StringCopy(gStringVar2, sNamingScreen->destBuffer);\n    }\n    else\n    {\n        StringCopy(gStringVar1, GetBoxNamePtr(VarGet(VAR_PC_BOX_TO_SEND_MON)));\n        StringCopy(gStringVar2, sNamingScreen->destBuffer);\n        StringCopy(gStringVar3, GetBoxNamePtr(GetPCBoxToSendMon()));\n        stringToDisplay = 2;\n    }\n\n    if (FlagGet(FLAG_SYS_PC_LANETTE))\n        stringToDisplay++;\n\n    StringExpandPlaceholders(gStringVar4, sTransferredToPCMessages[stringToDisplay]);\n    DrawDialogueFrame(0, FALSE);\n    gTextFlags.canABSpeedUpPrint = TRUE;\n    AddTextPrinterParameterized2(0, FONT_NORMAL, gStringVar4, GetPlayerTextSpeedDelay(), 0, TEXT_COLOR_DARK_GRAY, TEXT_COLOR_WHITE, TEXT_COLOR_LIGHT_GRAY);\n    CopyWindowToVram(0, COPYWIN_FULL);",
  },
  "DoNamingScreen": {
    returnType: "void",
    params: "u8 templateNum, u8 *destBuffer, u16 monSpecies, u16 monGender, u32 monPersonality, MainCallback returnCallback",
    callsTo: ["Alloc","SetMainCallback2","StartTimer1"],
    lineCount: 17,
    bodyC: "sNamingScreen = Alloc(sizeof(struct NamingScreenData));\n    if (!sNamingScreen)\n    {\n        SetMainCallback2(returnCallback);\n    }\n    else\n    {\n        sNamingScreen->templateNum = templateNum;\n        sNamingScreen->monSpecies = monSpecies;\n        sNamingScreen->monGender = monGender;\n        sNamingScreen->monPersonality = monPersonality;\n        sNamingScreen->destBuffer = destBuffer;\n        sNamingScreen->returnCallback = returnCallback;\n\n        if (templateNum == NAMING_SCREEN_PLAYER)\n            StartTimer1();\n\n        SetMainCallback2(CB2_LoadNamingScreen);\n    }",
  },
  "DrawBgTilemap": {
    returnType: "static void",
    params: "u8 bg, const void *src",
    callsTo: ["CopyToBgTilemapBuffer"],
    lineCount: 1,
    bodyC: "CopyToBgTilemapBuffer(bg, src, 0, 0);",
  },
  "DrawGenderIcon": {
    returnType: "static void",
    params: "void",
    callsTo: ["AddTextPrinterParameterized3","StringCopy"],
    lineCount: 12,
    bodyC: "u8 text[2];\n    bool8 isFemale = FALSE;\n\n    StringCopy(text, gText_MaleSymbol);\n    if (sNamingScreen->monGender != MON_GENDERLESS)\n    {\n        if (sNamingScreen->monGender == MON_FEMALE)\n        {\n            StringCopy(text, gText_FemaleSymbol);\n            isFemale = TRUE;\n        }\n        AddTextPrinterParameterized3(sNamingScreen->windows[WIN_TEXT_ENTRY], FONT_NORMAL, (POKEMON_NAME_LENGTH * 4) + 64, 1, sGenderColors[isFemale], TEXT_SKIP_DRAW, text);\n    }",
  },
  "DrawKeyboardPageOnDeck": {
    returnType: "static void",
    params: "void",
    callsTo: ["CopyBgTilemapBufferToVram","CurrentPageToNextKeyboardId","DrawBgTilemap","GetGpuReg","NamingScreen_Dummy","PrintKeyboardKeys"],
    lineCount: 21,
    bodyC: "u8 bg;\n    u8 bg_;\n    u8 windowId;\n    u8 bg1Priority = GetGpuReg(REG_OFFSET_BG1CNT) & 3;\n    u8 bg2Priority = GetGpuReg(REG_OFFSET_BG2CNT) & 3;\n\n    if (bg1Priority > bg2Priority)\n    {\n        bg = 1;\n        bg_ = 1;\n        windowId = sNamingScreen->windows[WIN_KB_PAGE_1];\n    }\n    else\n    {\n        bg = 2;\n        bg_ = 2;\n        windowId = sNamingScreen->windows[WIN_KB_PAGE_2];\n    }\n\n    DrawBgTilemap(bg, sNextKeyboardPageTilemaps[sNamingScreen->currentPage]);\n    PrintKeyboardKeys(windowId, CurrentPageToNextKeyboardId());\n    NamingScreen_Dummy(bg, CurrentPageToNextKeyboardId());\n    CopyBgTilemapBufferToVram(bg_);",
  },
  "DrawMonTextEntryBox": {
    returnType: "static void",
    params: "void",
    callsTo: ["AddTextPrinterParameterized","FillWindowPixelBuffer","PIXEL_FILL","PutWindowTilemap","StringCopy","StringExpandPlaceholders"],
    lineCount: 6,
    bodyC: "u8 buffer[48];\n\n    StringCopy(gStringVar1, gSpeciesNames[sNamingScreen->monSpecies]);\n    StringExpandPlaceholders(buffer, sNamingScreen->template->title);\n    FillWindowPixelBuffer(sNamingScreen->windows[WIN_TEXT_ENTRY_BOX], PIXEL_FILL(1));\n    AddTextPrinterParameterized(sNamingScreen->windows[WIN_TEXT_ENTRY_BOX], FONT_NORMAL, buffer, 8, 1, 0, 0);\n    PutWindowTilemap(sNamingScreen->windows[WIN_TEXT_ENTRY_BOX]);",
  },
  "DrawNormalTextEntryBox": {
    returnType: "static void",
    params: "void",
    callsTo: ["AddTextPrinterParameterized","FillWindowPixelBuffer","PIXEL_FILL","PutWindowTilemap"],
    lineCount: 3,
    bodyC: "FillWindowPixelBuffer(sNamingScreen->windows[WIN_TEXT_ENTRY_BOX], PIXEL_FILL(1));\n    AddTextPrinterParameterized(sNamingScreen->windows[WIN_TEXT_ENTRY_BOX], FONT_NORMAL, sNamingScreen->template->title, 8, 1, 0, 0);\n    PutWindowTilemap(sNamingScreen->windows[WIN_TEXT_ENTRY_BOX]);",
  },
  "DrawTextEntry": {
    returnType: "static void",
    params: "void",
    callsTo: ["AddTextPrinterParameterized","CopyWindowToVram","FillWindowPixelBuffer","IsWideLetter","PIXEL_FILL","PutWindowTilemap","TryDrawGenderIcon"],
    lineCount: 16,
    bodyC: "u8 i;\n    u8 temp[2];\n    u16 extraWidth;\n    u8 maxChars = sNamingScreen->template->maxChars;\n    u16 x = sNamingScreen->inputCharBaseXPos - 0x40;\n\n    FillWindowPixelBuffer(sNamingScreen->windows[WIN_TEXT_ENTRY], PIXEL_FILL(1));\n\n    for (i = 0; i < maxChars; i++)\n    {\n        temp[0] = sNamingScreen->textBuffer[i];\n        temp[1] = gText_ExpandedPlaceholder_Empty[0];\n        extraWidth = (IsWideLetter(temp[0]) == TRUE) ? 2 : 0;\n\n        AddTextPrinterParameterized(sNamingScreen->windows[WIN_TEXT_ENTRY], FONT_NORMAL, temp, i * 8 + x + extraWidth, 1, TEXT_SKIP_DRAW, NULL);\n    }\n\n    TryDrawGenderIcon();\n    CopyWindowToVram(sNamingScreen->windows[WIN_TEXT_ENTRY], COPYWIN_GFX);\n    PutWindowTilemap(sNamingScreen->windows[WIN_TEXT_ENTRY]);",
  },
  "DrawTextEntryBox": {
    returnType: "static void",
    params: "void",
    lineCount: 1,
    bodyC: "sDrawTextEntryBoxFuncs[sNamingScreen->templateNum]();",
  },
  "DummyGenderIcon": {
    returnType: "static void",
    params: "void",
    lineCount: 0,
    bodyC: "",
  },
  "GetButtonPalOffset": {
    returnType: "static u16",
    params: "u8 button",
    callsTo: ["IndexOfSpritePaletteTag","OBJ_PLTT_ID"],
    lineCount: 8,
    bodyC: "const u16 palOffsets[BUTTON_COUNT + 1] =\n    {\n        [BUTTON_PAGE]  = OBJ_PLTT_ID(IndexOfSpritePaletteTag(PALTAG_PAGE_SWAP)) + 14,\n        [BUTTON_BACK]  = OBJ_PLTT_ID(IndexOfSpritePaletteTag(PALTAG_BACK_BUTTON)) + 14,\n        [BUTTON_OK]    = OBJ_PLTT_ID(IndexOfSpritePaletteTag(PALTAG_OK_BUTTON)) + 14,\n        [BUTTON_COUNT] = OBJ_PLTT_ID(IndexOfSpritePaletteTag(PALTAG_OK_BUTTON)) + 1,\n    };\n\n    return palOffsets[button];",
  },
  "GetCharAtKeyboardPos": {
    returnType: "static u8",
    params: "s16 x, s16 y",
    callsTo: ["CurrentPageToKeyboardId"],
    lineCount: 1,
    bodyC: "return sKeyboardChars[CurrentPageToKeyboardId()][y][x];",
  },
  "GetCurrentPageColumnCount": {
    returnType: "static u8",
    params: "void",
    callsTo: ["CurrentPageToKeyboardId"],
    lineCount: 1,
    bodyC: "return sPageColumnCounts[CurrentPageToKeyboardId()];",
  },
  "GetCursorPos": {
    returnType: "static void",
    params: "s16 *x, s16 *y",
    lineCount: 3,
    bodyC: "struct Sprite *cursorSprite = &gSprites[sNamingScreen->cursorSpriteId];\n\n    *x = cursorSprite->sX;\n    *y = cursorSprite->sY;",
  },
  "GetInputEvent": {
    returnType: "static u8",
    params: "void",
    callsTo: ["FindTaskIdByFunc"],
    lineCount: 2,
    bodyC: "u8 taskId = FindTaskIdByFunc(Task_HandleInput);\n\n    return gTasks[taskId].tKeyboardEvent;",
  },
  "GetKeyRoleAtCursorPos": {
    returnType: "static u8",
    params: "void",
    callsTo: ["GetCurrentPageColumnCount","GetCursorPos"],
    lineCount: 7,
    bodyC: "s16 cursorX;\n    s16 cursorY;\n\n    GetCursorPos(&cursorX, &cursorY);\n    if (cursorX < GetCurrentPageColumnCount())\n        return KEY_ROLE_CHAR;\n    else\n        return sButtonKeyRoles[cursorY];",
  },
  "GetPreviousTextCaretPosition": {
    returnType: "static u8",
    params: "void",
    lineCount: 7,
    bodyC: "s8 i;\n\n    for (i = sNamingScreen->template->maxChars - 1; i > 0; i--)\n    {\n        if (sNamingScreen->textBuffer[i] != EOS)\n            return i;\n    }\n    return 0;",
  },
  "GetTextEntryPosition": {
    returnType: "static u8",
    params: "void",
    lineCount: 7,
    bodyC: "u8 i;\n\n    for (i = 0; i < sNamingScreen->template->maxChars; i++)\n    {\n        if (sNamingScreen->textBuffer[i] == EOS)\n            return i;\n    }\n    return sNamingScreen->template->maxChars - 1;",
  },
  "HandleDpadMovement": {
    returnType: "static void",
    params: "struct Task *task",
    callsTo: ["GetCurrentPageColumnCount","GetCursorPos","JOY_REPEAT","SetCursorPos"],
    lineCount: 73,
    bodyC: "const s16 sDpadDeltaX[] =\n    {\n        [INPUT_NONE]       = 0,\n        [INPUT_DPAD_UP]    = 0,\n        [INPUT_DPAD_DOWN]  = 0,\n        [INPUT_DPAD_LEFT]  = -1,\n        [INPUT_DPAD_RIGHT] = 1\n    };\n\n    const s16 sDpadDeltaY[] =\n    {\n        [INPUT_NONE]       = 0,\n        [INPUT_DPAD_UP]    = -1,\n        [INPUT_DPAD_DOWN]  = 1,\n        [INPUT_DPAD_LEFT]  = 0,\n        [INPUT_DPAD_RIGHT] = 0\n    };\n\n    const s16 sKeyRowToButtonRow[KBROW_COUNT] = {0, 1, 1, 2};\n    const s16 sButtonRowToKeyRow[BUTTON_COUNT] = {0, 0, 3};\n\n    s16 cursorX;\n    s16 cursorY;\n    u16 input;\n    s16 prevCursorX;\n\n    GetCursorPos(&cursorX, &cursorY);\n    input = INPUT_NONE;\n    if (JOY_REPEAT(DPAD_UP))\n        input = INPUT_DPAD_UP;\n    if (JOY_REPEAT(DPAD_DOWN))\n        input = INPUT_DPAD_DOWN;\n    if (JOY_REPEAT(DPAD_LEFT))\n        input = INPUT_DPAD_LEFT;\n    if (JOY_REPEAT(DPAD_RIGHT))\n        input = INPUT_DPAD_RIGHT;\n\n     \n    prevCursorX = cursorX;\n    cursorX += sDpadDeltaX[input];\n    cursorY += sDpadDeltaY[input];\n\n     \n    if (cursorX < 0)\n        cursorX = GetCurrentPageColumnCount();\n    if (cursorX > GetCurrentPageColumnCount())\n        cursorX = 0;\n\n\n     \n    if (sDpadDeltaX[input] != 0)\n    {\n        if (cursorX == GetCurrentPageColumnCount())\n        {\n             \n             \n            task->tButtonId = cursorY;\n            cursorY = sKeyRowToButtonRow[cursorY];\n        }\n        else if (prevCursorX == GetCurrentPageColumnCount())\n        {\n             \n             \n             \n            if (cursorY == BUTTON_COUNT / 2)\n                cursorY = task->tButtonId;\n            else\n                cursorY = sButtonRowToKeyRow[cursorY];\n        }\n    }\n\n     \n    if (cursorX == GetCurrentPageColumnCount())\n    {\n         \n         \n        if (cursorY < 0)\n            cursorY = BUTTON_COUNT - 1;\n        if (cursorY >= BUTTON_COUNT)\n            cursorY = 0;\n\n        if (cursorY == 0)\n            task->tButtonId = BUTTON_BACK;\n        else if (cursorY == BUTTON_COUNT - 1)\n            task->tButtonId = BUTTON_OK;\n    }\n    else\n    {\n        if (cursorY < 0)\n            cursorY = KBROW_COUNT - 1;\n        if (cursorY > KBROW_COUNT - 1)\n            cursorY = 0;\n    }\n    SetCursorPos(cursorX, cursorY);",
  },
  "HandleKeyboardEvent": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DeleteTextCharacter","GetInputEvent","GetKeyRoleAtCursorPos","MoveCursorToOKButton","SwapKeyboardPage"],
    lineCount: 20,
    bodyC: "u8 input = GetInputEvent();\n    u8 keyRole = GetKeyRoleAtCursorPos();\n\n    if (input == INPUT_SELECT)\n    {\n        return SwapKeyboardPage();\n    }\n    else if (input == INPUT_B_BUTTON)\n    {\n        DeleteTextCharacter();\n        return FALSE;\n    }\n    else if (input == INPUT_START)\n    {\n        MoveCursorToOKButton();\n        return FALSE;\n    }\n    else\n    {\n        return sKeyboardKeyHandlers[keyRole](input);\n    }",
  },
  "Input_Disabled": {
    returnType: "static void",
    params: "struct Task *task",
    lineCount: 1,
    bodyC: "task->tKeyboardEvent = INPUT_NONE;",
  },
  "Input_Enabled": {
    returnType: "static void",
    params: "struct Task *task",
    callsTo: ["HandleDpadMovement","JOY_NEW"],
    lineCount: 11,
    bodyC: "task->tKeyboardEvent = INPUT_NONE;\n\n    if (JOY_NEW(A_BUTTON))\n        task->tKeyboardEvent = INPUT_A_BUTTON;\n    else if (JOY_NEW(B_BUTTON))\n        task->tKeyboardEvent = INPUT_B_BUTTON;\n    else if (JOY_NEW(SELECT_BUTTON))\n        task->tKeyboardEvent = INPUT_SELECT;\n    else if (JOY_NEW(START_BUTTON))\n        task->tKeyboardEvent = INPUT_START;\n    else\n        HandleDpadMovement(task);",
  },
  "Input_Override": {
    returnType: "static void",
    params: "struct Task *task",
    lineCount: 1,
    bodyC: "task->tKeyboardEvent = INPUT_NONE;",
  },
  "IsCursorAnimFinished": {
    returnType: "static bool8",
    params: "void",
    lineCount: 1,
    bodyC: "return gSprites[sNamingScreen->cursorSpriteId].animEnded;",
  },
  "IsPageSwapAnimNotInProgress": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["FindTaskIdByFunc"],
    lineCount: 4,
    bodyC: "if (FindTaskIdByFunc(Task_HandlePageSwapAnim) == TASK_NONE)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "IsWideLetter": {
    returnType: "static bool8",
    params: "u8 character",
    lineCount: 7,
    bodyC: "u8 i;\n\n    for (i = 0; sText_AlphabetUpperLower[i] != EOS; i++)\n    {\n        if (character == sText_AlphabetUpperLower[i])\n            return FALSE;\n    }\n    return FALSE;",
  },
  "KeyboardKeyHandler_Backspace": {
    returnType: "static bool8",
    params: "u8 input",
    callsTo: ["DeleteTextCharacter","TryStartButtonFlash"],
    lineCount: 4,
    bodyC: "TryStartButtonFlash(BUTTON_BACK, TRUE, FALSE);\n    if (input == INPUT_A_BUTTON)\n        DeleteTextCharacter();\n    return FALSE;",
  },
  "KeyboardKeyHandler_Character": {
    returnType: "static bool8",
    params: "u8 input",
    callsTo: ["AddTextCharacter","SetInputState","SquishCursor","TryStartButtonFlash"],
    lineCount: 12,
    bodyC: "TryStartButtonFlash(BUTTON_COUNT, FALSE, FALSE);\n    if (input == INPUT_A_BUTTON)\n    {\n        bool8 textFull = AddTextCharacter();\n\n        SquishCursor();\n        if (textFull)\n        {\n            SetInputState(INPUT_STATE_OVERRIDE);\n            sNamingScreen->state = STATE_MOVE_TO_OK_BUTTON;\n        }\n    }\n    return FALSE;",
  },
  "KeyboardKeyHandler_OK": {
    returnType: "static bool8",
    params: "u8 input",
    callsTo: ["PlaySE","TryStartButtonFlash"],
    lineCount: 9,
    bodyC: "TryStartButtonFlash(BUTTON_OK, TRUE, FALSE);\n    if (input == INPUT_A_BUTTON)\n    {\n        PlaySE(SE_SELECT);\n        sNamingScreen->state = STATE_PRESSED_OK;\n        return TRUE;\n    }\n    else\n        return FALSE;",
  },
  "KeyboardKeyHandler_Page": {
    returnType: "static bool8",
    params: "u8 input",
    callsTo: ["SwapKeyboardPage","TryStartButtonFlash"],
    lineCount: 5,
    bodyC: "TryStartButtonFlash(BUTTON_PAGE, TRUE, FALSE);\n    if (input == INPUT_A_BUTTON)\n        return SwapKeyboardPage();\n    else\n        return FALSE;",
  },
  "LoadGfx": {
    returnType: "static void",
    params: "void",
    callsTo: ["LZ77UnCompWram","LoadBgTiles","LoadSpritePalettes","LoadSpriteSheets"],
    lineCount: 6,
    bodyC: "LZ77UnCompWram(gNamingScreenMenu_Gfx, sNamingScreen->tileBuffer);\n    LoadBgTiles(1, sNamingScreen->tileBuffer, sizeof(sNamingScreen->tileBuffer), 0);\n    LoadBgTiles(2, sNamingScreen->tileBuffer, sizeof(sNamingScreen->tileBuffer), 0);\n    LoadBgTiles(3, sNamingScreen->tileBuffer, sizeof(sNamingScreen->tileBuffer), 0);\n    LoadSpriteSheets(sSpriteSheets);\n    LoadSpritePalettes(sSpritePalettes);",
  },
  "LoadPalettes": {
    returnType: "static void",
    params: "void",
    callsTo: ["BG_PLTT_ID","GetTextWindowPalette","LoadPalette"],
    lineCount: 3,
    bodyC: "LoadPalette(gNamingScreenMenu_Pal, BG_PLTT_ID(0), sizeof(gNamingScreenMenu_Pal));\n    LoadPalette(sKeyboard_Pal, BG_PLTT_ID(10), sizeof(sKeyboard_Pal));\n    LoadPalette(GetTextWindowPalette(2), BG_PLTT_ID(11), PLTT_SIZE_4BPP);",
  },
  "MainState_Exit": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DestroyTask","FREE_AND_SET_NULL","FindTaskIdByFunc","FreeAllWindowBuffers","SeedRngAndSetTrainerId","SetMainCallback2"],
    lineCount: 10,
    bodyC: "if (!gPaletteFade.active)\n    {\n        if (sNamingScreen->templateNum == NAMING_SCREEN_PLAYER)\n            SeedRngAndSetTrainerId();\n        SetMainCallback2(sNamingScreen->returnCallback);\n        DestroyTask(FindTaskIdByFunc(Task_NamingScreen));\n        FreeAllWindowBuffers();\n        FREE_AND_SET_NULL(sNamingScreen);\n    }\n    return FALSE;",
  },
  "MainState_FadeIn": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["BeginNormalPaletteFade","BlendPalettes","CopyBgTilemapBufferToVram","DrawBgTilemap","DrawTextEntry","DrawTextEntryBox","NamingScreen_Dummy","PrintControls","PrintKeyboardKeys"],
    lineCount: 18,
    bodyC: "DrawBgTilemap(3, gNamingScreenBackground_Tilemap);\n    sNamingScreen->currentPage = KBPAGE_LETTERS_UPPER;\n    DrawBgTilemap(2, gNamingScreenKeyboardLower_Tilemap);\n    DrawBgTilemap(1, gNamingScreenKeyboardUpper_Tilemap);\n    PrintKeyboardKeys(sNamingScreen->windows[WIN_KB_PAGE_2], KEYBOARD_LETTERS_LOWER);\n    PrintKeyboardKeys(sNamingScreen->windows[WIN_KB_PAGE_1], KEYBOARD_LETTERS_UPPER);\n    NamingScreen_Dummy(2, KEYBOARD_LETTERS_LOWER);\n    NamingScreen_Dummy(1, KEYBOARD_LETTERS_UPPER);\n    DrawTextEntry();\n    DrawTextEntryBox();\n    PrintControls();\n    CopyBgTilemapBufferToVram(1);\n    CopyBgTilemapBufferToVram(2);\n    CopyBgTilemapBufferToVram(3);\n    BlendPalettes(PALETTES_ALL, 16, 0);\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_BLACK);\n    sNamingScreen->state++;\n    return FALSE;",
  },
  "MainState_FadeOut": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["BeginNormalPaletteFade"],
    lineCount: 3,
    bodyC: "BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_BLACK);\n    sNamingScreen->state++;\n    return FALSE;",
  },
  "MainState_HandleInput": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["HandleKeyboardEvent"],
    lineCount: 1,
    bodyC: "return HandleKeyboardEvent();",
  },
  "MainState_MoveToOKButton": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["IsCursorAnimFinished","MoveCursorToOKButton","SetInputState"],
    lineCount: 7,
    bodyC: "if (IsCursorAnimFinished())\n    {\n        SetInputState(INPUT_STATE_ENABLED);\n        MoveCursorToOKButton();\n        sNamingScreen->state = STATE_HANDLE_INPUT;\n    }\n    return FALSE;",
  },
  "MainState_PressedOKButton": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["CalculatePlayerPartyCount","DisplaySentToPCMessage","SaveInputText","SetCursorFlashing","SetInputState","TryStartButtonFlash"],
    lineCount: 16,
    bodyC: "SaveInputText();\n    SetInputState(INPUT_STATE_DISABLED);\n    SetCursorFlashing(FALSE);\n    TryStartButtonFlash(BUTTON_COUNT, FALSE, TRUE);\n    if (sNamingScreen->templateNum == NAMING_SCREEN_CAUGHT_MON\n        && CalculatePlayerPartyCount() >= PARTY_SIZE)\n    {\n        DisplaySentToPCMessage();\n        sNamingScreen->state = STATE_WAIT_SENT_TO_PC_MESSAGE;\n        return FALSE;\n    }\n    else\n    {\n        sNamingScreen->state = STATE_FADE_OUT;\n        return TRUE;\n    }",
  },
  "MainState_StartPageSwap": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["PlaySE","SetCursorInvisibility","SetInputState","StartPageSwapAnim","StartPageSwapButtonAnim","TryStartButtonFlash"],
    lineCount: 8,
    bodyC: "SetInputState(INPUT_STATE_DISABLED);\n    StartPageSwapButtonAnim();\n    StartPageSwapAnim();\n    SetCursorInvisibility(TRUE);\n    TryStartButtonFlash(BUTTON_PAGE, FALSE, TRUE);\n    PlaySE(SE_WIN_OPEN);\n    sNamingScreen->state = STATE_WAIT_PAGE_SWAP;\n    return FALSE;",
  },
  "MainState_WaitFadeIn": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["SetCursorFlashing","SetInputState"],
    lineCount: 7,
    bodyC: "if (!gPaletteFade.active)\n    {\n        SetInputState(INPUT_STATE_ENABLED);\n        SetCursorFlashing(TRUE);\n        sNamingScreen->state++;\n    }\n    return FALSE;",
  },
  "MainState_WaitPageSwap": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["DrawKeyboardPageOnDeck","GetCurrentPageColumnCount","GetCursorPos","IsPageSwapAnimNotInProgress","SetCursorInvisibility","SetCursorPos","SetInputState"],
    lineCount: 25,
    bodyC: "s16 cursorX;\n    s16 cursorY;\n    bool32 onLastColumn;\n\n    if (IsPageSwapAnimNotInProgress())\n    {\n\n        GetCursorPos(&cursorX, &cursorY);\n        onLastColumn = (cursorX == GetCurrentPageColumnCount());\n\n        sNamingScreen->state = STATE_HANDLE_INPUT;\n        sNamingScreen->currentPage++;\n        sNamingScreen->currentPage %= KBPAGE_COUNT;\n\n        if (onLastColumn)\n        {\n            cursorX = GetCurrentPageColumnCount();\n        }\n        else\n        {\n            if (cursorX >= GetCurrentPageColumnCount())\n                cursorX = GetCurrentPageColumnCount() - 1;\n        }\n\n        SetCursorPos(cursorX, cursorY);\n        DrawKeyboardPageOnDeck();\n        SetInputState(INPUT_STATE_ENABLED);\n        SetCursorInvisibility(FALSE);\n    }\n    return FALSE;",
  },
  "MainState_WaitSentToPCMessage": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["IsTextPrinterActive","JOY_NEW","RunTextPrinters"],
    lineCount: 4,
    bodyC: "RunTextPrinters();\n    if (!IsTextPrinterActive(0) && JOY_NEW(A_BUTTON))\n        sNamingScreen->state = STATE_FADE_OUT;\n\n    return FALSE;",
  },
  "MoveCursorToOKButton": {
    returnType: "static void",
    params: "void",
    callsTo: ["GetCurrentPageColumnCount","SetCursorPos"],
    lineCount: 1,
    bodyC: "SetCursorPos(GetCurrentPageColumnCount(), 2);",
  },
  "NamingScreen_CreateMonIcon": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateMonIcon","LoadMonIconPalettes"],
    lineCount: 4,
    bodyC: "u8 spriteId;\n\n    LoadMonIconPalettes();\n    spriteId = CreateMonIcon(sNamingScreen->monSpecies, SpriteCallbackDummy, 56, 40, 0, sNamingScreen->monPersonality, 1);\n    gSprites[spriteId].oam.priority = 3;",
  },
  "NamingScreen_CreatePCIcon": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateSprite","SetSubspriteTables"],
    lineCount: 4,
    bodyC: "u8 spriteId;\n\n    spriteId = CreateSprite(&sSpriteTemplate_PCIcon, 56, 41, 0);\n    SetSubspriteTables(&gSprites[spriteId], sSubspriteTable_PCIcon);\n    gSprites[spriteId].oam.priority = 3;",
  },
  "NamingScreen_CreatePlayerIcon": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateObjectGraphicsSprite","GetRivalAvatarGraphicsIdByStateIdAndGender","StartSpriteAnim"],
    lineCount: 6,
    bodyC: "u8 rivalGfxId;\n    u8 spriteId;\n\n    rivalGfxId = GetRivalAvatarGraphicsIdByStateIdAndGender(PLAYER_AVATAR_STATE_NORMAL, sNamingScreen->monSpecies);\n    spriteId = CreateObjectGraphicsSprite(rivalGfxId, SpriteCallbackDummy, 56, 37, 0);\n    gSprites[spriteId].oam.priority = 3;\n    StartSpriteAnim(&gSprites[spriteId], ANIM_STD_GO_SOUTH);",
  },
  "NamingScreen_CreateWaldaDadIcon": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateObjectGraphicsSprite","StartSpriteAnim"],
    lineCount: 4,
    bodyC: "u8 spriteId;\n\n    spriteId = CreateObjectGraphicsSprite(OBJ_EVENT_GFX_MAN_1, SpriteCallbackDummy, 56, 37, 0);\n    gSprites[spriteId].oam.priority = 3;\n    StartSpriteAnim(&gSprites[spriteId], ANIM_STD_GO_SOUTH);",
  },
  "NamingScreen_Dummy": {
    returnType: "static void",
    params: "u8 bg, u8 page",
    lineCount: 0,
    bodyC: "",
  },
  "NamingScreen_Init": {
    returnType: "static void",
    params: "void",
    callsTo: ["BGCNT_PRIORITY","StringCopy","memset"],
    lineCount: 17,
    bodyC: "sNamingScreen->state = STATE_FADE_IN;\n    sNamingScreen->bg1vOffset = 0;\n    sNamingScreen->bg2vOffset = 0;\n    sNamingScreen->bg1Priority = BGCNT_PRIORITY(1);\n    sNamingScreen->bg2Priority = BGCNT_PRIORITY(2);\n    sNamingScreen->bgToReveal = 0;\n    sNamingScreen->bgToHide = 1;\n    sNamingScreen->template = sNamingScreenTemplates[sNamingScreen->templateNum];\n    sNamingScreen->currentPage = sNamingScreen->template->initialPage;\n    sNamingScreen->inputCharBaseXPos = (DISPLAY_WIDTH - sNamingScreen->template->maxChars * 8) / 2 + 6;\n    if (sNamingScreen->templateNum == NAMING_SCREEN_WALDA)\n        sNamingScreen->inputCharBaseXPos += 11;\n    sNamingScreen->keyRepeatStartDelayCopy = gKeyRepeatStartDelay;\n    memset(sNamingScreen->textBuffer, EOS, sizeof(sNamingScreen->textBuffer));\n    if (sNamingScreen->template->copyExistingString)\n        StringCopy(sNamingScreen->textBuffer, sNamingScreen->destBuffer);\n    gKeyRepeatStartDelay = 16;",
  },
  "NamingScreen_InitBGs": {
    returnType: "static void",
    params: "void",
    callsTo: ["ARRAY_COUNT","AddWindow","BLDALPHA_BLEND","ChangeBgX","ChangeBgY","DmaClear16","DmaClear32","DmaClearLarge16","FillBgTilemapBufferRect_Palette0","InitBgsFromTemplates","InitStandardTextBoxWindows","InitTextBoxGfxAndPrinters","ResetBgsAndClearDma3BusyFlags","SetBgTilemapBuffer","SetGpuReg"],
    lineCount: 28,
    bodyC: "u8 i;\n\n    DmaClearLarge16(3, (void *)VRAM, VRAM_SIZE, 0x1000);\n    DmaClear32(3, (void *)OAM, OAM_SIZE);\n    DmaClear16(3, (void *)PLTT, PLTT_SIZE);\n\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_0);\n    ResetBgsAndClearDma3BusyFlags(0);\n    InitBgsFromTemplates(0, sBgTemplates, ARRAY_COUNT(sBgTemplates));\n\n    ChangeBgX(0, 0, BG_COORD_SET);\n    ChangeBgY(0, 0, BG_COORD_SET);\n    ChangeBgX(1, 0, BG_COORD_SET);\n    ChangeBgY(1, 0, BG_COORD_SET);\n    ChangeBgX(2, 0, BG_COORD_SET);\n    ChangeBgY(2, 0, BG_COORD_SET);\n    ChangeBgX(3, 0, BG_COORD_SET);\n    ChangeBgY(3, 0, BG_COORD_SET);\n\n    InitStandardTextBoxWindows();\n    InitTextBoxGfxAndPrinters();\n\n    for (i = 0; i < WIN_COUNT; i++)\n        sNamingScreen->windows[i] = AddWindow(&sWindowTemplates[i]);\n\n    SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_1D_MAP | DISPCNT_OBJ_ON);\n    SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_EFFECT_BLEND | BLDCNT_TGT2_BG1 | BLDCNT_TGT2_BG2);\n    SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(12, 8));\n\n    SetBgTilemapBuffer(1, sNamingScreen->tilemapBuffer1);\n    SetBgTilemapBuffer(2, sNamingScreen->tilemapBuffer2);\n    SetBgTilemapBuffer(3, sNamingScreen->tilemapBuffer3);\n\n    FillBgTilemapBufferRect_Palette0(1, 0, 0, 0, 0x20, 0x20);\n    FillBgTilemapBufferRect_Palette0(2, 0, 0, 0, 0x20, 0x20);\n    FillBgTilemapBufferRect_Palette0(3, 0, 0, 0, 0x20, 0x20);",
  },
  "NamingScreen_NoIcon": {
    returnType: "static void",
    params: "void",
    lineCount: 0,
    bodyC: "",
  },
  "NamingScreen_ShowBgs": {
    returnType: "static void",
    params: "void",
    callsTo: ["ShowBg"],
    lineCount: 4,
    bodyC: "ShowBg(0);\n    ShowBg(1);\n    ShowBg(2);\n    ShowBg(3);",
  },
  "PageSwapAnimState_1": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["Sin"],
    lineCount: 16,
    bodyC: "u16 *const vOffsets[] =\n    {\n        &sNamingScreen->bg2vOffset,\n        &sNamingScreen->bg1vOffset\n    };\n\n    task->tFrameCount += 4;\n    *vOffsets[sNamingScreen->bgToReveal] = Sin(task->tFrameCount, 40);\n    *vOffsets[sNamingScreen->bgToHide] = Sin((task->tFrameCount + 128) & 0xFF, 40);\n    if (task->tFrameCount >= 64)\n    {\n        u8 temp = sNamingScreen->bg1Priority;   \n\n        sNamingScreen->bg1Priority = sNamingScreen->bg2Priority;\n        sNamingScreen->bg2Priority = temp;\n        task->tState++;\n    }\n    return 0;",
  },
  "PageSwapAnimState_2": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["Sin"],
    lineCount: 16,
    bodyC: "u16 *const vOffsets[] =\n    {\n        &sNamingScreen->bg2vOffset,\n        &sNamingScreen->bg1vOffset\n    };\n\n    task->tFrameCount += 4;\n    *vOffsets[sNamingScreen->bgToReveal] = Sin(task->tFrameCount, 40);\n    *vOffsets[sNamingScreen->bgToHide] = Sin((task->tFrameCount + 128) & 0xFF, 40);\n    if (task->tFrameCount >= 128)\n    {\n        u8 temp = sNamingScreen->bgToReveal;\n\n        sNamingScreen->bgToReveal = sNamingScreen->bgToHide;\n        sNamingScreen->bgToHide = temp;\n        task->tState++;\n    }\n    return 0;",
  },
  "PageSwapAnimState_Done": {
    returnType: "static bool8",
    params: "struct Task *task",
    callsTo: ["DestroyTask","FindTaskIdByFunc"],
    lineCount: 2,
    bodyC: "DestroyTask(FindTaskIdByFunc(Task_HandlePageSwapAnim));\n    return 0;",
  },
  "PageSwapAnimState_Init": {
    returnType: "static bool8",
    params: "struct Task *task",
    lineCount: 4,
    bodyC: "sNamingScreen->bg1vOffset = 0;\n    sNamingScreen->bg2vOffset = 0;\n    task->tState++;\n    return 0;",
  },
  "PageSwapSprite_Idle": {
    returnType: "static bool8",
    params: "struct Sprite *sprite",
    lineCount: 1,
    bodyC: "return FALSE;",
  },
  "PageSwapSprite_Init": {
    returnType: "static bool8",
    params: "struct Sprite *sprite",
    callsTo: ["PageToNextGfxId","SetPageSwapButtonGfx"],
    lineCount: 5,
    bodyC: "struct Sprite *text = &gSprites[sprite->sTextSpriteId];\n    struct Sprite *button = &gSprites[sprite->sButtonSpriteId];\n\n    SetPageSwapButtonGfx(PageToNextGfxId(sNamingScreen->currentPage), text, button);\n    sprite->sState++;\n    return FALSE;",
  },
  "PageSwapSprite_SlideOff": {
    returnType: "static bool8",
    params: "struct Sprite *sprite",
    callsTo: ["PageToNextGfxId","SetPageSwapButtonGfx"],
    lineCount: 11,
    bodyC: "struct Sprite *text = &gSprites[sprite->sTextSpriteId];\n    struct Sprite *button = &gSprites[sprite->sButtonSpriteId];\n\n    text->y2++;\n    if (text->y2 > 7)\n    {\n        sprite->sState++;\n        text->y2 = -4;\n        text->invisible = TRUE;\n        SetPageSwapButtonGfx(PageToNextGfxId(((u8)sprite->sPage + 1) % KBPAGE_COUNT), text, button);\n    }\n    return FALSE;",
  },
  "PageSwapSprite_SlideOn": {
    returnType: "static bool8",
    params: "struct Sprite *sprite",
    lineCount: 9,
    bodyC: "struct Sprite *text = &gSprites[sprite->sTextSpriteId];\n\n    text->invisible = FALSE;\n    text->y2++;\n    if (text->y2 >= 0)\n    {\n        text->y2 = 0;\n        sprite->sState = 1;  \n    }\n    return FALSE;",
  },
  "PageToNextGfxId": {
    returnType: "static u8",
    params: "u8 page",
    lineCount: 1,
    bodyC: "return sPageToNextGfxId[page];",
  },
  "PrintControls": {
    returnType: "static void",
    params: "void",
    callsTo: ["AddTextPrinterParameterized3","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL","PutWindowTilemap"],
    lineCount: 5,
    bodyC: "const u8 color[3] = { TEXT_DYNAMIC_COLOR_6, TEXT_COLOR_WHITE, TEXT_COLOR_DARK_GRAY };\n\n    FillWindowPixelBuffer(sNamingScreen->windows[WIN_BANNER], PIXEL_FILL(15));\n    AddTextPrinterParameterized3(sNamingScreen->windows[WIN_BANNER], FONT_SMALL, 2, 1, color, 0, gText_MoveOkBack);\n    PutWindowTilemap(sNamingScreen->windows[WIN_BANNER]);\n    CopyWindowToVram(sNamingScreen->windows[WIN_BANNER], COPYWIN_FULL);",
  },
  "PrintKeyboardKeys": {
    returnType: "static void",
    params: "u8 window, u8 page",
    callsTo: ["AddTextPrinterParameterized3","FillWindowPixelBuffer","PutWindowTilemap"],
    lineCount: 5,
    bodyC: "u8 i;\n\n    FillWindowPixelBuffer(window, sFillValues[page]);\n\n    for (i = 0; i < KBROW_COUNT; i++)\n        AddTextPrinterParameterized3(window, FONT_NORMAL, 0, i * 16 + 1, sKeyboardTextColors[page], 0, sNamingScreenKeyboardText[page][i]);\n\n    PutWindowTilemap(window);",
  },
  "ResetVHBlank": {
    returnType: "static void",
    params: "void",
    callsTo: ["SetHBlankCallback","SetVBlankCallback"],
    lineCount: 2,
    bodyC: "SetVBlankCallback(NULL);\n    SetHBlankCallback(NULL);",
  },
  "RestoreButtonColor": {
    returnType: "static void",
    params: "u8 button",
    callsTo: ["GetButtonPalOffset"],
    lineCount: 2,
    bodyC: "u16 index = GetButtonPalOffset(button);\n    gPlttBufferFaded[index] = gPlttBufferUnfaded[index];",
  },
  "SaveInputText": {
    returnType: "static void",
    params: "void",
    callsTo: ["StringCopyN"],
    lineCount: 9,
    bodyC: "u8 i;\n\n    for (i = 0; i < sNamingScreen->template->maxChars; i++)\n    {\n        if (sNamingScreen->textBuffer[i] != CHAR_SPACE && sNamingScreen->textBuffer[i] != EOS)\n        {\n            StringCopyN(sNamingScreen->destBuffer, sNamingScreen->textBuffer, sNamingScreen->template->maxChars + 1);\n            break;\n        }\n    }",
  },
  "SetCursorFlashing": {
    returnType: "static void",
    params: "bool8 flashing",
    lineCount: 2,
    bodyC: "gSprites[sNamingScreen->cursorSpriteId].data[4] &= 0xFF;\n    gSprites[sNamingScreen->cursorSpriteId].data[4] |= flashing << 8;",
  },
  "SetCursorInvisibility": {
    returnType: "static void",
    params: "bool8 invisible",
    callsTo: ["StartSpriteAnim"],
    lineCount: 3,
    bodyC: "gSprites[sNamingScreen->cursorSpriteId].data[4] &= 0xFF00;\n    gSprites[sNamingScreen->cursorSpriteId].data[4] |= invisible;  \n    StartSpriteAnim(&gSprites[sNamingScreen->cursorSpriteId], 0);",
  },
  "SetCursorPos": {
    returnType: "static void",
    params: "s16 x, s16 y",
    callsTo: ["CurrentPageToKeyboardId"],
    lineCount: 10,
    bodyC: "struct Sprite *cursorSprite = &gSprites[sNamingScreen->cursorSpriteId];\n\n    if (x < sPageColumnCounts[CurrentPageToKeyboardId()])\n        cursorSprite->x = sPageColumnXPos[CurrentPageToKeyboardId()][x] + 38;\n    else\n        cursorSprite->x = 0;\n\n    cursorSprite->y = y * 16 + 88;\n    cursorSprite->sPrevX = cursorSprite->sX;\n    cursorSprite->sPrevY = cursorSprite->sY;\n    cursorSprite->sX = x;\n    cursorSprite->sY = y;",
  },
  "SetInputState": {
    returnType: "static void",
    params: "u8 state",
    callsTo: ["FindTaskIdByFunc"],
    lineCount: 2,
    bodyC: "u8 taskId = FindTaskIdByFunc(Task_HandleInput);\n\n    gTasks[taskId].tState = state;",
  },
  "SetPageSwapButtonGfx": {
    returnType: "static void",
    params: "u8 page, struct Sprite *text, struct Sprite *button",
    callsTo: ["GetSpriteTileStartByTag","IndexOfSpritePaletteTag"],
    lineCount: 3,
    bodyC: "button->oam.paletteNum = IndexOfSpritePaletteTag(sPageSwapPalTags[page]);\n    text->sheetTileStart = GetSpriteTileStartByTag(sPageSwapGfxTags[page]);\n    text->subspriteTableNum = page;",
  },
  "SetSpritesVisible": {
    returnType: "static void",
    params: "void",
    callsTo: ["SetCursorInvisibility"],
    lineCount: 7,
    bodyC: "u8 i;\n    for (i = 0; i < MAX_SPRITES; i++)\n    {\n        if (gSprites[i].inUse)\n            gSprites[i].invisible = FALSE;\n    }\n    SetCursorInvisibility(FALSE);",
  },
  "SetVBlank": {
    returnType: "static void",
    params: "void",
    callsTo: ["SetVBlankCallback"],
    lineCount: 1,
    bodyC: "SetVBlankCallback(VBlankCB_NamingScreen);",
  },
  "SpriteCB_Cursor": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["GetCurrentPageColumnCount","IndexOfSpritePaletteTag","MultiplyInvertedPaletteRGBComponents","OBJ_PLTT_ID","StartSpriteAnim"],
    lineCount: 29,
    bodyC: "if (sprite->animEnded)\n        StartSpriteAnim(sprite, 0);\n\n     \n    sprite->invisible = sprite->sInvisible;\n    if (sprite->sX == GetCurrentPageColumnCount())\n        sprite->invisible = TRUE;\n\n    if (sprite->invisible\n       || !(sprite->sFlashing)\n       || sprite->sX != sprite->sPrevX\n       || sprite->sY != sprite->sPrevY)\n    {\n        sprite->sColor = 0;\n        sprite->sColorIncr = 2;\n        sprite->sColorDelay = 2;\n    }\n\n    sprite->sColorDelay--;\n    if (sprite->sColorDelay == 0)\n    {\n        sprite->sColor += sprite->sColorIncr;\n        if (sprite->sColor == 16 || sprite->sColor == 0)\n            sprite->sColorIncr = -sprite->sColorIncr;\n        sprite->sColorDelay = 2;\n    }\n\n    if (sprite->sFlashing)\n    {\n        s8 gb = sprite->sColor;\n        s8 r = sprite->sColor >> 1;\n        u16 index = OBJ_PLTT_ID(IndexOfSpritePaletteTag(PALTAG_CURSOR)) + 1;\n\n        MultiplyInvertedPaletteRGBComponents(index, r, gb, gb);\n    }",
  },
  "SpriteCB_InputArrow": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["ARRAY_COUNT","MOD"],
    lineCount: 7,
    bodyC: "const s16 x[] = {0, -4, -2, -1};\n\n    if (sprite->sDelay == 0 || --sprite->sDelay == 0)\n    {\n        sprite->sDelay = 8;\n        sprite->sXPosId = MOD(sprite->sXPosId + 1, ARRAY_COUNT(x));\n    }\n    sprite->x2 = x[sprite->sXPosId];",
  },
  "SpriteCB_PageSwap": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    lineCount: 1,
    bodyC: "while (sPageSwapSpriteFuncs[sprite->sState](sprite));",
  },
  "SpriteCB_Underscore": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["ARRAY_COUNT","GetTextEntryPosition","MOD"],
    lineCount: 19,
    bodyC: "const s16 y[] = {2, 3, 2, 1};\n    u8 pos;\n\n    pos = GetTextEntryPosition();\n    if (pos != (u8)sprite->sId)\n    {\n        sprite->y2 = 0;\n        sprite->sYPosId = 0;\n        sprite->sDelay = 0;\n    }\n    else\n    {\n        sprite->y2 = y[sprite->sYPosId];\n        sprite->sDelay++;\n        if (sprite->sDelay > 8)\n        {\n            sprite->sYPosId = MOD(sprite->sYPosId + 1, ARRAY_COUNT(y));\n            sprite->sDelay = 0;\n        }\n    }",
  },
  "SquishCursor": {
    returnType: "static void",
    params: "void",
    callsTo: ["StartSpriteAnim"],
    lineCount: 1,
    bodyC: "StartSpriteAnim(&gSprites[sNamingScreen->cursorSpriteId], 1);",
  },
  "StartButtonFlash": {
    returnType: "static void",
    params: "struct Task *task, u8 button, bool8 keepFlashing",
    lineCount: 7,
    bodyC: "task->tButtonId = button;\n    task->tKeepFlashing = keepFlashing;\n    task->tAllowFlash = TRUE;\n    task->tColor = 4;\n    task->tColorIncr = 2;\n    task->tColorDelay = 0;\n    task->tColorDelta = 4;",
  },
  "StartPageSwapAnim": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateTask","Task_HandlePageSwapAnim"],
    lineCount: 3,
    bodyC: "u8 taskId;\n\n    taskId = CreateTask(Task_HandlePageSwapAnim, 0);\n    Task_HandlePageSwapAnim(taskId);",
  },
  "StartPageSwapButtonAnim": {
    returnType: "static void",
    params: "void",
    lineCount: 3,
    bodyC: "struct Sprite *sprite = &gSprites[sNamingScreen->swapBtnFrameSpriteId];\n\n    sprite->sState = 2;  \n    sprite->sPage = sNamingScreen->currentPage;",
  },
  "SwapKeyboardPage": {
    returnType: "static bool8",
    params: "void",
    lineCount: 2,
    bodyC: "sNamingScreen->state = STATE_START_PAGE_SWAP;\n    return TRUE;",
  },
  "Task_HandleInput": {
    returnType: "static void",
    params: "u8 taskId",
    lineCount: 1,
    bodyC: "sInputFuncs[gTasks[taskId].tState](&gTasks[taskId]);",
  },
  "Task_HandlePageSwapAnim": {
    returnType: "static void",
    params: "u8 taskId",
    lineCount: 1,
    bodyC: "while (sPageSwapAnimStateFuncs[gTasks[taskId].tState](&gTasks[taskId]) != 0);",
  },
  "Task_NamingScreen": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["MainState_Exit","MainState_FadeIn","MainState_FadeOut","MainState_HandleInput","MainState_MoveToOKButton","MainState_PressedOKButton","MainState_StartPageSwap","MainState_WaitFadeIn","MainState_WaitPageSwap","MainState_WaitSentToPCMessage","SetSpritesVisible","SetVBlank"],
    lineCount: 36,
    bodyC: "switch (sNamingScreen->state)\n    {\n    case STATE_FADE_IN:\n        MainState_FadeIn();\n        SetSpritesVisible();\n        SetVBlank();\n        break;\n    case STATE_WAIT_FADE_IN:\n        MainState_WaitFadeIn();\n        break;\n    case STATE_HANDLE_INPUT:\n        MainState_HandleInput();\n        break;\n    case STATE_MOVE_TO_OK_BUTTON:\n        MainState_MoveToOKButton();\n        MainState_HandleInput();\n        break;\n    case STATE_START_PAGE_SWAP:\n        MainState_StartPageSwap();\n        break;\n    case STATE_WAIT_PAGE_SWAP:\n        MainState_WaitPageSwap();\n        break;\n    case STATE_PRESSED_OK:\n        MainState_PressedOKButton();\n        break;\n    case STATE_WAIT_SENT_TO_PC_MESSAGE:\n        MainState_WaitSentToPCMessage();\n        break;\n    case STATE_FADE_OUT:\n        MainState_FadeOut();\n        break;\n    case STATE_EXIT:\n        MainState_Exit();\n        break;\n    }",
  },
  "Task_UpdateButtonFlash": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["GetButtonPalOffset","MultiplyInvertedPaletteRGBComponents"],
    lineCount: 35,
    bodyC: "struct Task *task = &gTasks[taskId];\n\n    if (task->tButtonId == BUTTON_COUNT || !task->tAllowFlash)\n        return;\n\n    MultiplyInvertedPaletteRGBComponents(GetButtonPalOffset(task->tButtonId), task->tColor, task->tColor, task->tColor);\n\n    if (task->tColorDelay && --task->tColorDelay)\n        return;\n\n    task->tColorDelay = 2;\n    if (task->tColorIncr >= 0)\n    {\n        if (task->tColor < 14)\n        {\n            task->tColor += task->tColorIncr;\n            task->tColorDelta += task->tColorIncr;\n        }\n        else\n        {\n            task->tColor = 16;\n            task->tColorDelta++;\n        }\n    }\n    else\n    {\n        task->tColor += task->tColorIncr;\n        task->tColorDelta += task->tColorIncr;\n    }\n\n    if (task->tColor == 16 && task->tColorDelta == 22)\n    {\n        task->tColorIncr = -4;\n    }\n    else if (task->tColor == 0)\n    {\n        task->tAllowFlash = task->tKeepFlashing;\n        task->tColorIncr = 2;\n        task->tColorDelta = 0;\n    }",
  },
  "TryDrawGenderIcon": {
    returnType: "static void",
    params: "void",
    lineCount: 1,
    bodyC: "sDrawGenderIconFuncs[sNamingScreen->template->addGenderIcon]();",
  },
  "TryStartButtonFlash": {
    returnType: "static void",
    params: "u8 button, bool8 keepFlashing, bool8 interruptCurFlash",
    callsTo: ["FindTaskIdByFunc","RestoreButtonColor","StartButtonFlash"],
    lineCount: 12,
    bodyC: "struct Task *task = &gTasks[FindTaskIdByFunc(Task_UpdateButtonFlash)];\n\n    if (button == task->tButtonId && !interruptCurFlash)\n    {\n        task->tKeepFlashing = keepFlashing;\n        task->tAllowFlash = TRUE;\n        return;\n    }\n    if (button == BUTTON_COUNT && !task->tKeepFlashing && !interruptCurFlash)\n        return;\n\n    if (task->tButtonId != BUTTON_COUNT)\n        RestoreButtonColor(task->tButtonId);\n\n    StartButtonFlash(task, button, keepFlashing);",
  },
  "VBlankCB_NamingScreen": {
    returnType: "static void",
    params: "void",
    callsTo: ["GetGpuReg","LoadOam","ProcessSpriteCopyRequests","SetGpuReg","SetGpuRegBits","TransferPlttBuffer"],
    lineCount: 9,
    bodyC: "LoadOam();\n    ProcessSpriteCopyRequests();\n    TransferPlttBuffer();\n    SetGpuReg(REG_OFFSET_BG1VOFS, sNamingScreen->bg1vOffset);\n    SetGpuReg(REG_OFFSET_BG2VOFS, sNamingScreen->bg2vOffset);\n    SetGpuReg(REG_OFFSET_BG1CNT, GetGpuReg(REG_OFFSET_BG1CNT) & 0xFFFC);\n    SetGpuRegBits(REG_OFFSET_BG1CNT, sNamingScreen->bg1Priority);\n    SetGpuReg(REG_OFFSET_BG2CNT, GetGpuReg(REG_OFFSET_BG2CNT) & 0xFFFC);\n    SetGpuRegBits(REG_OFFSET_BG2CNT, sNamingScreen->bg2Priority);",
  },
} as const;
