// AUTO-GENERATED from src/option_menu.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 24

export const ENGINE_FUNCTIONS = {
  "BattleScene_DrawChoices": {
    returnType: "static void",
    params: "u8 selection",
    callsTo: ["DrawOptionMenuChoice","GetStringRightAlignXOffset"],
    lineCount: 6,
    bodyC: "u8 styles[2];\n\n    styles[0] = 0;\n    styles[1] = 0;\n    styles[selection] = 1;\n\n    DrawOptionMenuChoice(gText_BattleSceneOn, 104, YPOS_BATTLESCENE, styles[0]);\n    DrawOptionMenuChoice(gText_BattleSceneOff, GetStringRightAlignXOffset(FONT_NORMAL, gText_BattleSceneOff, 198), YPOS_BATTLESCENE, styles[1]);",
  },
  "BattleScene_ProcessInput": {
    returnType: "static u8",
    params: "u8 selection",
    callsTo: ["JOY_NEW"],
    lineCount: 6,
    bodyC: "if (JOY_NEW(DPAD_LEFT | DPAD_RIGHT))\n    {\n        selection ^= 1;\n        sArrowPressed = TRUE;\n    }\n\n    return selection;",
  },
  "BattleStyle_DrawChoices": {
    returnType: "static void",
    params: "u8 selection",
    callsTo: ["DrawOptionMenuChoice","GetStringRightAlignXOffset"],
    lineCount: 6,
    bodyC: "u8 styles[2];\n\n    styles[0] = 0;\n    styles[1] = 0;\n    styles[selection] = 1;\n\n    DrawOptionMenuChoice(gText_BattleStyleShift, 104, YPOS_BATTLESTYLE, styles[0]);\n    DrawOptionMenuChoice(gText_BattleStyleSet, GetStringRightAlignXOffset(FONT_NORMAL, gText_BattleStyleSet, 198), YPOS_BATTLESTYLE, styles[1]);",
  },
  "BattleStyle_ProcessInput": {
    returnType: "static u8",
    params: "u8 selection",
    callsTo: ["JOY_NEW"],
    lineCount: 6,
    bodyC: "if (JOY_NEW(DPAD_LEFT | DPAD_RIGHT))\n    {\n        selection ^= 1;\n        sArrowPressed = TRUE;\n    }\n\n    return selection;",
  },
  "ButtonMode_DrawChoices": {
    returnType: "static void",
    params: "u8 selection",
    callsTo: ["DrawOptionMenuChoice","GetStringRightAlignXOffset","GetStringWidth"],
    lineCount: 14,
    bodyC: "s32 widthNormal, widthLR, widthLA, xLR;\n    u8 styles[3];\n\n    styles[0] = 0;\n    styles[1] = 0;\n    styles[2] = 0;\n    styles[selection] = 1;\n\n    DrawOptionMenuChoice(gText_ButtonTypeNormal, 104, YPOS_BUTTONMODE, styles[0]);\n\n    widthNormal = GetStringWidth(FONT_NORMAL, gText_ButtonTypeNormal, 0);\n    widthLR = GetStringWidth(FONT_NORMAL, gText_ButtonTypeLR, 0);\n    widthLA = GetStringWidth(FONT_NORMAL, gText_ButtonTypeLEqualsA, 0);\n\n    widthLR -= 94;\n    xLR = (widthNormal - widthLR - widthLA) / 2 + 104;\n    DrawOptionMenuChoice(gText_ButtonTypeLR, xLR, YPOS_BUTTONMODE, styles[1]);\n\n    DrawOptionMenuChoice(gText_ButtonTypeLEqualsA, GetStringRightAlignXOffset(FONT_NORMAL, gText_ButtonTypeLEqualsA, 198), YPOS_BUTTONMODE, styles[2]);",
  },
  "ButtonMode_ProcessInput": {
    returnType: "static u8",
    params: "u8 selection",
    callsTo: ["JOY_NEW"],
    lineCount: 17,
    bodyC: "if (JOY_NEW(DPAD_RIGHT))\n    {\n        if (selection <= 1)\n            selection++;\n        else\n            selection = 0;\n\n        sArrowPressed = TRUE;\n    }\n    if (JOY_NEW(DPAD_LEFT))\n    {\n        if (selection != 0)\n            selection--;\n        else\n            selection = 2;\n\n        sArrowPressed = TRUE;\n    }\n    return selection;",
  },
  "CB2_InitOptionMenu": {
    returnType: "void",
    params: "void",
    callsTo: ["ARRAY_COUNT","BG_PLTT_ID","BattleScene_DrawChoices","BattleStyle_DrawChoices","BeginNormalPaletteFade","ButtonMode_DrawChoices","ChangeBgX","ChangeBgY","CopyWindowToVram","CreateTask","DeactivateAllTextPrinters","DmaClear16","DmaClear32","DmaClearLarge16","DrawBgWindowFrames","DrawHeaderText","DrawOptionMenuTexts","FrameType_DrawChoices","GetWindowFrameTilesPal","HighlightOptionMenuItem","InitBgsFromTemplates","InitWindows","LoadBgTiles","LoadPalette","PutWindowTilemap","ResetBgsAndClearDma3BusyFlags","ResetPaletteFade","ResetSpriteData","ResetTasks","ScanlineEffect_Stop","SetGpuReg","SetMainCallback2","SetVBlankCallback","ShowBg","Sound_DrawChoices","TextSpeed_DrawChoices"],
    lineCount: 99,
    bodyC: "switch (gMain.state)\n    {\n    default:\n    case 0:\n        SetVBlankCallback(NULL);\n        gMain.state++;\n        break;\n    case 1:\n        DmaClearLarge16(3, (void *)(VRAM), VRAM_SIZE, 0x1000);\n        DmaClear32(3, OAM, OAM_SIZE);\n        DmaClear16(3, PLTT, PLTT_SIZE);\n        SetGpuReg(REG_OFFSET_DISPCNT, 0);\n        ResetBgsAndClearDma3BusyFlags(0);\n        InitBgsFromTemplates(0, sOptionMenuBgTemplates, ARRAY_COUNT(sOptionMenuBgTemplates));\n        ChangeBgX(0, 0, BG_COORD_SET);\n        ChangeBgY(0, 0, BG_COORD_SET);\n        ChangeBgX(1, 0, BG_COORD_SET);\n        ChangeBgY(1, 0, BG_COORD_SET);\n        ChangeBgX(2, 0, BG_COORD_SET);\n        ChangeBgY(2, 0, BG_COORD_SET);\n        ChangeBgX(3, 0, BG_COORD_SET);\n        ChangeBgY(3, 0, BG_COORD_SET);\n        InitWindows(sOptionMenuWinTemplates);\n        DeactivateAllTextPrinters();\n        SetGpuReg(REG_OFFSET_WIN0H, 0);\n        SetGpuReg(REG_OFFSET_WIN0V, 0);\n        SetGpuReg(REG_OFFSET_WININ, WININ_WIN0_BG0);\n        SetGpuReg(REG_OFFSET_WINOUT, WINOUT_WIN01_BG0 | WINOUT_WIN01_BG1 | WINOUT_WIN01_CLR);\n        SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_TGT1_BG0 | BLDCNT_EFFECT_DARKEN);\n        SetGpuReg(REG_OFFSET_BLDALPHA, 0);\n        SetGpuReg(REG_OFFSET_BLDY, 4);\n        SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_WIN0_ON | DISPCNT_OBJ_ON | DISPCNT_OBJ_1D_MAP);\n        ShowBg(0);\n        ShowBg(1);\n        gMain.state++;\n        break;\n    case 2:\n        ResetPaletteFade();\n        ScanlineEffect_Stop();\n        ResetTasks();\n        ResetSpriteData();\n        gMain.state++;\n        break;\n    case 3:\n        LoadBgTiles(1, GetWindowFrameTilesPal(gSaveBlock2Ptr->optionsWindowFrameType)->tiles, 0x120, 0x1A2);\n        gMain.state++;\n        break;\n    case 4:\n        LoadPalette(sOptionMenuBg_Pal, BG_PLTT_ID(0), sizeof(sOptionMenuBg_Pal));\n        LoadPalette(GetWindowFrameTilesPal(gSaveBlock2Ptr->optionsWindowFrameType)->pal, BG_PLTT_ID(7), PLTT_SIZE_4BPP);\n        gMain.state++;\n        break;\n    case 5:\n        LoadPalette(sOptionMenuText_Pal, BG_PLTT_ID(1), sizeof(sOptionMenuText_Pal));\n        gMain.state++;\n        break;\n    case 6:\n        PutWindowTilemap(WIN_HEADER);\n        DrawHeaderText();\n        gMain.state++;\n        break;\n    case 7:\n        gMain.state++;\n        break;\n    case 8:\n        PutWindowTilemap(WIN_OPTIONS);\n        DrawOptionMenuTexts();\n        gMain.state++;\n    case 9:\n        DrawBgWindowFrames();\n        gMain.state++;\n        break;\n    case 10:\n    {\n        u8 taskId = CreateTask(Task_OptionMenuFadeIn, 0);\n\n        gTasks[taskId].tMenuSelection = 0;\n        gTasks[taskId].tTextSpeed = gSaveBlock2Ptr->optionsTextSpeed;\n        gTasks[taskId].tBattleSceneOff = gSaveBlock2Ptr->optionsBattleSceneOff;\n        gTasks[taskId].tBattleStyle = gSaveBlock2Ptr->optionsBattleStyle;\n        gTasks[taskId].tSound = gSaveBlock2Ptr->optionsSound;\n        gTasks[taskId].tButtonMode = gSaveBlock2Ptr->optionsButtonMode;\n        gTasks[taskId].tWindowFrameType = gSaveBlock2Ptr->optionsWindowFrameType;\n\n        TextSpeed_DrawChoices(gTasks[taskId].tTextSpeed);\n        BattleScene_DrawChoices(gTasks[taskId].tBattleSceneOff);\n        BattleStyle_DrawChoices(gTasks[taskId].tBattleStyle);\n        Sound_DrawChoices(gTasks[taskId].tSound);\n        ButtonMode_DrawChoices(gTasks[taskId].tButtonMode);\n        FrameType_DrawChoices(gTasks[taskId].tWindowFrameType);\n        HighlightOptionMenuItem(gTasks[taskId].tMenuSelection);\n\n        CopyWindowToVram(WIN_OPTIONS, COPYWIN_FULL);\n        gMain.state++;\n        break;\n    }\n    case 11:\n        BeginNormalPaletteFade(PALETTES_ALL, 0, 16, 0, RGB_BLACK);\n        SetVBlankCallback(VBlankCB);\n        SetMainCallback2(MainCB2);\n        return;\n    }",
  },
  "DrawBgWindowFrames": {
    returnType: "static void",
    params: "void",
    callsTo: ["CopyBgTilemapBufferToVram","FillBgTilemapBufferRect"],
    lineCount: 17,
    bodyC: "FillBgTilemapBufferRect(1, TILE_TOP_CORNER_L,  1,  0,  1,  1,  7);\n    FillBgTilemapBufferRect(1, TILE_TOP_EDGE,      2,  0, 27,  1,  7);\n    FillBgTilemapBufferRect(1, TILE_TOP_CORNER_R, 28,  0,  1,  1,  7);\n    FillBgTilemapBufferRect(1, TILE_LEFT_EDGE,     1,  1,  1,  2,  7);\n    FillBgTilemapBufferRect(1, TILE_RIGHT_EDGE,   28,  1,  1,  2,  7);\n    FillBgTilemapBufferRect(1, TILE_BOT_CORNER_L,  1,  3,  1,  1,  7);\n    FillBgTilemapBufferRect(1, TILE_BOT_EDGE,      2,  3, 27,  1,  7);\n    FillBgTilemapBufferRect(1, TILE_BOT_CORNER_R, 28,  3,  1,  1,  7);\n\n     \n    FillBgTilemapBufferRect(1, TILE_TOP_CORNER_L,  1,  4,  1,  1,  7);\n    FillBgTilemapBufferRect(1, TILE_TOP_EDGE,      2,  4, 26,  1,  7);\n    FillBgTilemapBufferRect(1, TILE_TOP_CORNER_R, 28,  4,  1,  1,  7);\n    FillBgTilemapBufferRect(1, TILE_LEFT_EDGE,     1,  5,  1, 18,  7);\n    FillBgTilemapBufferRect(1, TILE_RIGHT_EDGE,   28,  5,  1, 18,  7);\n    FillBgTilemapBufferRect(1, TILE_BOT_CORNER_L,  1, 19,  1,  1,  7);\n    FillBgTilemapBufferRect(1, TILE_BOT_EDGE,      2, 19, 26,  1,  7);\n    FillBgTilemapBufferRect(1, TILE_BOT_CORNER_R, 28, 19,  1,  1,  7);\n\n    CopyBgTilemapBufferToVram(1);",
  },
  "DrawHeaderText": {
    returnType: "static void",
    params: "void",
    callsTo: ["AddTextPrinterParameterized","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL"],
    lineCount: 3,
    bodyC: "FillWindowPixelBuffer(WIN_HEADER, PIXEL_FILL(1));\n    AddTextPrinterParameterized(WIN_HEADER, FONT_NORMAL, gText_Option, 8, 1, TEXT_SKIP_DRAW, NULL);\n    CopyWindowToVram(WIN_HEADER, COPYWIN_FULL);",
  },
  "DrawOptionMenuChoice": {
    returnType: "static void",
    params: "const u8 *text, u8 x, u8 y, u8 style",
    callsTo: ["ARRAY_COUNT","AddTextPrinterParameterized"],
    lineCount: 11,
    bodyC: "u8 dst[16];\n    u16 i;\n\n    for (i = 0; *text != EOS && i < ARRAY_COUNT(dst) - 1; i++)\n        dst[i] = *(text++);\n\n    if (style != 0)\n    {\n        dst[2] = TEXT_COLOR_RED;\n        dst[5] = TEXT_COLOR_LIGHT_RED;\n    }\n\n    dst[i] = EOS;\n    AddTextPrinterParameterized(WIN_OPTIONS, FONT_NORMAL, dst, x, y + 1, TEXT_SKIP_DRAW, NULL);",
  },
  "DrawOptionMenuTexts": {
    returnType: "static void",
    params: "void",
    callsTo: ["AddTextPrinterParameterized","CopyWindowToVram","FillWindowPixelBuffer","PIXEL_FILL"],
    lineCount: 5,
    bodyC: "u8 i;\n\n    FillWindowPixelBuffer(WIN_OPTIONS, PIXEL_FILL(1));\n    for (i = 0; i < MENUITEM_COUNT; i++)\n        AddTextPrinterParameterized(WIN_OPTIONS, FONT_NORMAL, sOptionMenuItemsNames[i], 8, (i * 16) + 1, TEXT_SKIP_DRAW, NULL);\n    CopyWindowToVram(WIN_OPTIONS, COPYWIN_FULL);",
  },
  "FrameType_DrawChoices": {
    returnType: "static void",
    params: "u8 selection",
    callsTo: ["DrawOptionMenuChoice","GetStringWidth"],
    lineCount: 24,
    bodyC: "u8 text[16];\n    u8 n = selection + 1;\n    u16 i;\n    u32 width;  \n\n    for (i = 0; gText_FrameTypeNumber[i] != EOS && i <= 5; i++)\n        text[i] = gText_FrameTypeNumber[i];\n\n     \n    if (n / 10 != 0)\n    {\n        text[i] = n / 10 + CHAR_0;\n        i++;\n        text[i] = n % 10 + CHAR_0;\n        i++;\n    }\n    else\n    {\n        text[i] = n % 10 + CHAR_0;\n        i++;\n        text[i] = CHAR_SPACER;\n        i++;\n    }\n\n    text[i] = EOS;\n\n     \n    width = GetStringWidth(1, gText_FrameType, 0);\n    DrawOptionMenuChoice(gText_FrameType, 104, YPOS_FRAMETYPE, 0);\n    DrawOptionMenuChoice(text, width + 107, YPOS_FRAMETYPE, 1);",
  },
  "FrameType_ProcessInput": {
    returnType: "static u8",
    params: "u8 selection",
    callsTo: ["BG_PLTT_ID","GetWindowFrameTilesPal","JOY_NEW","LoadBgTiles","LoadPalette"],
    lineCount: 21,
    bodyC: "if (JOY_NEW(DPAD_RIGHT))\n    {\n        if (selection < WINDOW_FRAMES_COUNT - 1)\n            selection++;\n        else\n            selection = 0;\n\n        LoadBgTiles(1, GetWindowFrameTilesPal(selection)->tiles, 0x120, 0x1A2);\n        LoadPalette(GetWindowFrameTilesPal(selection)->pal, BG_PLTT_ID(7), PLTT_SIZE_4BPP);\n        sArrowPressed = TRUE;\n    }\n    if (JOY_NEW(DPAD_LEFT))\n    {\n        if (selection != 0)\n            selection--;\n        else\n            selection = WINDOW_FRAMES_COUNT - 1;\n\n        LoadBgTiles(1, GetWindowFrameTilesPal(selection)->tiles, 0x120, 0x1A2);\n        LoadPalette(GetWindowFrameTilesPal(selection)->pal, BG_PLTT_ID(7), PLTT_SIZE_4BPP);\n        sArrowPressed = TRUE;\n    }\n    return selection;",
  },
  "HighlightOptionMenuItem": {
    returnType: "static void",
    params: "u8 index",
    callsTo: ["SetGpuReg","WIN_RANGE"],
    lineCount: 2,
    bodyC: "SetGpuReg(REG_OFFSET_WIN0H, WIN_RANGE(16, DISPLAY_WIDTH - 16));\n    SetGpuReg(REG_OFFSET_WIN0V, WIN_RANGE(index * 16 + 40, index * 16 + 56));",
  },
  "MainCB2": {
    returnType: "static void",
    params: "void",
    callsTo: ["AnimateSprites","BuildOamBuffer","RunTasks","UpdatePaletteFade"],
    lineCount: 4,
    bodyC: "RunTasks();\n    AnimateSprites();\n    BuildOamBuffer();\n    UpdatePaletteFade();",
  },
  "Sound_DrawChoices": {
    returnType: "static void",
    params: "u8 selection",
    callsTo: ["DrawOptionMenuChoice","GetStringRightAlignXOffset"],
    lineCount: 6,
    bodyC: "u8 styles[2];\n\n    styles[0] = 0;\n    styles[1] = 0;\n    styles[selection] = 1;\n\n    DrawOptionMenuChoice(gText_SoundMono, 104, YPOS_SOUND, styles[0]);\n    DrawOptionMenuChoice(gText_SoundStereo, GetStringRightAlignXOffset(FONT_NORMAL, gText_SoundStereo, 198), YPOS_SOUND, styles[1]);",
  },
  "Sound_ProcessInput": {
    returnType: "static u8",
    params: "u8 selection",
    callsTo: ["JOY_NEW","SetPokemonCryStereo"],
    lineCount: 7,
    bodyC: "if (JOY_NEW(DPAD_LEFT | DPAD_RIGHT))\n    {\n        selection ^= 1;\n        SetPokemonCryStereo(selection);\n        sArrowPressed = TRUE;\n    }\n\n    return selection;",
  },
  "Task_OptionMenuFadeIn": {
    returnType: "static void",
    params: "u8 taskId",
    lineCount: 2,
    bodyC: "if (!gPaletteFade.active)\n        gTasks[taskId].func = Task_OptionMenuProcessInput;",
  },
  "Task_OptionMenuFadeOut": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","FreeAllWindowBuffers","SetMainCallback2"],
    lineCount: 6,
    bodyC: "if (!gPaletteFade.active)\n    {\n        DestroyTask(taskId);\n        FreeAllWindowBuffers();\n        SetMainCallback2(gMain.savedCallback);\n    }",
  },
  "Task_OptionMenuProcessInput": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BattleScene_DrawChoices","BattleScene_ProcessInput","BattleStyle_DrawChoices","BattleStyle_ProcessInput","ButtonMode_DrawChoices","ButtonMode_ProcessInput","CopyWindowToVram","FrameType_DrawChoices","FrameType_ProcessInput","HighlightOptionMenuItem","JOY_NEW","Sound_DrawChoices","Sound_ProcessInput","TextSpeed_DrawChoices","TextSpeed_ProcessInput"],
    lineCount: 75,
    bodyC: "if (JOY_NEW(A_BUTTON))\n    {\n        if (gTasks[taskId].tMenuSelection == MENUITEM_CANCEL)\n            gTasks[taskId].func = Task_OptionMenuSave;\n    }\n    else if (JOY_NEW(B_BUTTON))\n    {\n        gTasks[taskId].func = Task_OptionMenuSave;\n    }\n    else if (JOY_NEW(DPAD_UP))\n    {\n        if (gTasks[taskId].tMenuSelection > 0)\n            gTasks[taskId].tMenuSelection--;\n        else\n            gTasks[taskId].tMenuSelection = MENUITEM_CANCEL;\n        HighlightOptionMenuItem(gTasks[taskId].tMenuSelection);\n    }\n    else if (JOY_NEW(DPAD_DOWN))\n    {\n        if (gTasks[taskId].tMenuSelection < MENUITEM_CANCEL)\n            gTasks[taskId].tMenuSelection++;\n        else\n            gTasks[taskId].tMenuSelection = 0;\n        HighlightOptionMenuItem(gTasks[taskId].tMenuSelection);\n    }\n    else\n    {\n        u8 previousOption;\n\n        switch (gTasks[taskId].tMenuSelection)\n        {\n        case MENUITEM_TEXTSPEED:\n            previousOption = gTasks[taskId].tTextSpeed;\n            gTasks[taskId].tTextSpeed = TextSpeed_ProcessInput(gTasks[taskId].tTextSpeed);\n\n            if (previousOption != gTasks[taskId].tTextSpeed)\n                TextSpeed_DrawChoices(gTasks[taskId].tTextSpeed);\n            break;\n        case MENUITEM_BATTLESCENE:\n            previousOption = gTasks[taskId].tBattleSceneOff;\n            gTasks[taskId].tBattleSceneOff = BattleScene_ProcessInput(gTasks[taskId].tBattleSceneOff);\n\n            if (previousOption != gTasks[taskId].tBattleSceneOff)\n                BattleScene_DrawChoices(gTasks[taskId].tBattleSceneOff);\n            break;\n        case MENUITEM_BATTLESTYLE:\n            previousOption = gTasks[taskId].tBattleStyle;\n            gTasks[taskId].tBattleStyle = BattleStyle_ProcessInput(gTasks[taskId].tBattleStyle);\n\n            if (previousOption != gTasks[taskId].tBattleStyle)\n                BattleStyle_DrawChoices(gTasks[taskId].tBattleStyle);\n            break;\n        case MENUITEM_SOUND:\n            previousOption = gTasks[taskId].tSound;\n            gTasks[taskId].tSound = Sound_ProcessInput(gTasks[taskId].tSound);\n\n            if (previousOption != gTasks[taskId].tSound)\n                Sound_DrawChoices(gTasks[taskId].tSound);\n            break;\n        case MENUITEM_BUTTONMODE:\n            previousOption = gTasks[taskId].tButtonMode;\n            gTasks[taskId].tButtonMode = ButtonMode_ProcessInput(gTasks[taskId].tButtonMode);\n\n            if (previousOption != gTasks[taskId].tButtonMode)\n                ButtonMode_DrawChoices(gTasks[taskId].tButtonMode);\n            break;\n        case MENUITEM_FRAMETYPE:\n            previousOption = gTasks[taskId].tWindowFrameType;\n            gTasks[taskId].tWindowFrameType = FrameType_ProcessInput(gTasks[taskId].tWindowFrameType);\n\n            if (previousOption != gTasks[taskId].tWindowFrameType)\n                FrameType_DrawChoices(gTasks[taskId].tWindowFrameType);\n            break;\n        default:\n            return;\n        }\n\n        if (sArrowPressed)\n        {\n            sArrowPressed = FALSE;\n            CopyWindowToVram(WIN_OPTIONS, COPYWIN_GFX);\n        }\n    }",
  },
  "Task_OptionMenuSave": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["BeginNormalPaletteFade"],
    lineCount: 8,
    bodyC: "gSaveBlock2Ptr->optionsTextSpeed = gTasks[taskId].tTextSpeed;\n    gSaveBlock2Ptr->optionsBattleSceneOff = gTasks[taskId].tBattleSceneOff;\n    gSaveBlock2Ptr->optionsBattleStyle = gTasks[taskId].tBattleStyle;\n    gSaveBlock2Ptr->optionsSound = gTasks[taskId].tSound;\n    gSaveBlock2Ptr->optionsButtonMode = gTasks[taskId].tButtonMode;\n    gSaveBlock2Ptr->optionsWindowFrameType = gTasks[taskId].tWindowFrameType;\n\n    BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, RGB_BLACK);\n    gTasks[taskId].func = Task_OptionMenuFadeOut;",
  },
  "TextSpeed_DrawChoices": {
    returnType: "static void",
    params: "u8 selection",
    callsTo: ["DrawOptionMenuChoice","GetStringRightAlignXOffset","GetStringWidth"],
    lineCount: 14,
    bodyC: "u8 styles[3];\n    s32 widthSlow, widthMid, widthFast, xMid;\n\n    styles[0] = 0;\n    styles[1] = 0;\n    styles[2] = 0;\n    styles[selection] = 1;\n\n    DrawOptionMenuChoice(gText_TextSpeedSlow, 104, YPOS_TEXTSPEED, styles[0]);\n\n    widthSlow = GetStringWidth(FONT_NORMAL, gText_TextSpeedSlow, 0);\n    widthMid = GetStringWidth(FONT_NORMAL, gText_TextSpeedMid, 0);\n    widthFast = GetStringWidth(FONT_NORMAL, gText_TextSpeedFast, 0);\n\n    widthMid -= 94;\n    xMid = (widthSlow - widthMid - widthFast) / 2 + 104;\n    DrawOptionMenuChoice(gText_TextSpeedMid, xMid, YPOS_TEXTSPEED, styles[1]);\n\n    DrawOptionMenuChoice(gText_TextSpeedFast, GetStringRightAlignXOffset(FONT_NORMAL, gText_TextSpeedFast, 198), YPOS_TEXTSPEED, styles[2]);",
  },
  "TextSpeed_ProcessInput": {
    returnType: "static u8",
    params: "u8 selection",
    callsTo: ["JOY_NEW"],
    lineCount: 17,
    bodyC: "if (JOY_NEW(DPAD_RIGHT))\n    {\n        if (selection <= 1)\n            selection++;\n        else\n            selection = 0;\n\n        sArrowPressed = TRUE;\n    }\n    if (JOY_NEW(DPAD_LEFT))\n    {\n        if (selection != 0)\n            selection--;\n        else\n            selection = 2;\n\n        sArrowPressed = TRUE;\n    }\n    return selection;",
  },
  "VBlankCB": {
    returnType: "static void",
    params: "void",
    callsTo: ["LoadOam","ProcessSpriteCopyRequests","TransferPlttBuffer"],
    lineCount: 3,
    bodyC: "LoadOam();\n    ProcessSpriteCopyRequests();\n    TransferPlttBuffer();",
  },
} as const;
