// AUTO-GENERATED from src/pokemon_icon.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 23

export const ENGINE_FUNCTIONS = {
  "CreateMonIcon": {
    returnType: "u8",
    params: "u16 species, void (*callback)(struct Sprite *), s16 x, s16 y, u8 subpriority, u32 personality, bool32 handleDeoxys",
    callsTo: ["CreateMonIconSprite","GetMonIconPtr","UpdateMonIconFrame"],
    lineCount: 15,
    bodyC: "u8 spriteId;\n    struct MonIconSpriteTemplate iconTemplate =\n    {\n        .oam = &sMonIconOamData,\n        .image = GetMonIconPtr(species, personality, handleDeoxys),\n        .anims = sMonIconAnims,\n        .affineAnims = sMonIconAffineAnims,\n        .callback = callback,\n        .paletteTag = POKE_ICON_BASE_PAL_TAG + gMonIconPaletteIndices[species],\n    };\n\n    if (species > NUM_SPECIES)\n        iconTemplate.paletteTag = POKE_ICON_BASE_PAL_TAG;\n\n    spriteId = CreateMonIconSprite(&iconTemplate, x, y, subpriority);\n\n    UpdateMonIconFrame(&gSprites[spriteId]);\n\n    return spriteId;",
  },
  "CreateMonIconNoPersonality": {
    returnType: "u8",
    params: "u16 species, void (*callback)(struct Sprite *), s16 x, s16 y, u8 subpriority, bool32 handleDeoxys",
    callsTo: ["CreateMonIconSprite","GetMonIconTiles","UpdateMonIconFrame"],
    lineCount: 14,
    bodyC: "u8 spriteId;\n    struct MonIconSpriteTemplate iconTemplate =\n    {\n        .oam = &sMonIconOamData,\n        .image = NULL,\n        .anims = sMonIconAnims,\n        .affineAnims = sMonIconAffineAnims,\n        .callback = callback,\n        .paletteTag = POKE_ICON_BASE_PAL_TAG + gMonIconPaletteIndices[species],\n    };\n\n    iconTemplate.image = GetMonIconTiles(species, handleDeoxys);\n    spriteId = CreateMonIconSprite(&iconTemplate, x, y, subpriority);\n\n    UpdateMonIconFrame(&gSprites[spriteId]);\n\n    return spriteId;",
  },
  "CreateMonIconSprite": {
    returnType: "static u8",
    params: "struct MonIconSpriteTemplate *iconTemplate, s16 x, s16 y, u8 subpriority",
    callsTo: ["CreateSprite"],
    lineCount: 17,
    bodyC: "u8 spriteId;\n\n    struct SpriteFrameImage image = { NULL, sSpriteImageSizes[iconTemplate->oam->shape][iconTemplate->oam->size] };\n\n    struct SpriteTemplate spriteTemplate =\n    {\n        .tileTag = TAG_NONE,\n        .paletteTag = iconTemplate->paletteTag,\n        .oam = iconTemplate->oam,\n        .anims = iconTemplate->anims,\n        .images = &image,\n        .affineAnims = iconTemplate->affineAnims,\n        .callback = iconTemplate->callback,\n    };\n\n    spriteId = CreateSprite(&spriteTemplate, x, y, subpriority);\n    gSprites[spriteId].animPaused = TRUE;\n    gSprites[spriteId].animBeginning = FALSE;\n    gSprites[spriteId].images = (const struct SpriteFrameImage *)iconTemplate->image;\n    return spriteId;",
  },
  "FreeAndDestroyMonIconSprite": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["FreeAndDestroyMonIconSprite_"],
    lineCount: 1,
    bodyC: "FreeAndDestroyMonIconSprite_(sprite);",
  },
  "FreeAndDestroyMonIconSprite_": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroySprite"],
    lineCount: 3,
    bodyC: "struct SpriteFrameImage image = { NULL, sSpriteImageSizes[sprite->oam.shape][sprite->oam.size] };\n    sprite->images = &image;\n    DestroySprite(sprite);",
  },
  "FreeMonIconPalette": {
    returnType: "void",
    params: "u16 species",
    callsTo: ["FreeSpritePaletteByTag"],
    lineCount: 3,
    bodyC: "u8 palIndex;\n    palIndex = gMonIconPaletteIndices[species];\n    FreeSpritePaletteByTag(gMonIconPaletteTable[palIndex].tag);",
  },
  "FreeMonIconPalettes": {
    returnType: "void",
    params: "void",
    callsTo: ["ARRAY_COUNT","FreeSpritePaletteByTag"],
    lineCount: 3,
    bodyC: "u8 i;\n    for (i = 0; i < ARRAY_COUNT(gMonIconPaletteTable); i++)\n        FreeSpritePaletteByTag(gMonIconPaletteTable[i].tag);",
  },
  "GetIconSpecies": {
    returnType: "u16",
    params: "u16 species, u32 personality",
    callsTo: ["GetUnownLetterByPersonality"],
    lineCount: 18,
    bodyC: "u16 result;\n\n    if (species == SPECIES_UNOWN)\n    {\n        u16 letter = GetUnownLetterByPersonality(personality);\n        if (letter == 0)\n            letter = SPECIES_UNOWN;\n        else\n            letter += (SPECIES_UNOWN_B - 1);\n        result = letter;\n    }\n    else\n    {\n        if (species > NUM_SPECIES)\n            result = INVALID_ICON_SPECIES;\n        else\n            result = species;\n    }\n\n    return result;",
  },
  "GetIconSpeciesNoPersonality": {
    returnType: "u16",
    params: "u16 species",
    callsTo: ["GetIconSpecies","MailSpeciesToSpecies"],
    lineCount: 15,
    bodyC: "u16 value;\n\n    if (MailSpeciesToSpecies(species, &value) == SPECIES_UNOWN)\n    {\n        if (value == 0)\n            value += SPECIES_UNOWN;\n        else\n            value += (SPECIES_UNOWN_B - 1);\n        return value;\n    }\n    else\n    {\n        if (species > NUM_SPECIES)\n            species = INVALID_ICON_SPECIES;\n        return GetIconSpecies(species, 0);\n    }",
  },
  "GetMonIconPaletteIndexFromSpecies": {
    returnType: "u8",
    params: "u16 species",
    lineCount: 1,
    bodyC: "return gMonIconPaletteIndices[species];",
  },
  "GetMonIconPtr": {
    returnType: "const u8 *",
    params: "u16 species, u32 personality, bool32 handleDeoxys",
    callsTo: ["GetIconSpecies","GetMonIconTiles"],
    lineCount: 1,
    bodyC: "return GetMonIconTiles(GetIconSpecies(species, personality), handleDeoxys);",
  },
  "GetMonIconTiles": {
    returnType: "const u8 *",
    params: "u16 species, bool32 handleDeoxys",
    lineCount: 6,
    bodyC: "const u8 *iconSprite = gMonIconTable[species];\n    if (species == SPECIES_DEOXYS && handleDeoxys == TRUE)\n    {\n        iconSprite = (const u8 *)(0x400 + (u32)iconSprite);  \n    }\n    return iconSprite;",
  },
  "GetUnownLetterByPersonality": {
    returnType: "u16",
    params: "u32 personality",
    callsTo: ["GET_UNOWN_LETTER"],
    lineCount: 4,
    bodyC: "if (!personality)\n        return 0;\n    else\n        return GET_UNOWN_LETTER(personality);",
  },
  "GetValidMonIconPalIndex": {
    returnType: "u8",
    params: "u16 species",
    lineCount: 3,
    bodyC: "if (species > NUM_SPECIES)\n        species = INVALID_ICON_SPECIES;\n    return gMonIconPaletteIndices[species];",
  },
  "GetValidMonIconPalettePtr": {
    returnType: "const u16 *",
    params: "u16 species",
    lineCount: 3,
    bodyC: "if (species > NUM_SPECIES)\n        species = INVALID_ICON_SPECIES;\n    return gMonIconPaletteTable[gMonIconPaletteIndices[species]].data;",
  },
  "LoadMonIconPalette": {
    returnType: "void",
    params: "u16 species",
    callsTo: ["IndexOfSpritePaletteTag","LoadSpritePalette"],
    lineCount: 3,
    bodyC: "u8 palIndex = gMonIconPaletteIndices[species];\n    if (IndexOfSpritePaletteTag(gMonIconPaletteTable[palIndex].tag) == 0xFF)\n        LoadSpritePalette(&gMonIconPaletteTable[palIndex]);",
  },
  "LoadMonIconPalettes": {
    returnType: "void",
    params: "void",
    callsTo: ["ARRAY_COUNT","LoadSpritePalette"],
    lineCount: 3,
    bodyC: "u8 i;\n    for (i = 0; i < ARRAY_COUNT(gMonIconPaletteTable); i++)\n        LoadSpritePalette(&gMonIconPaletteTable[i]);",
  },
  "SafeFreeMonIconPalette": {
    returnType: "void",
    params: "u16 species",
    callsTo: ["FreeSpritePaletteByTag"],
    lineCount: 5,
    bodyC: "u8 palIndex;\n    if (species > NUM_SPECIES)\n        species = INVALID_ICON_SPECIES;\n    palIndex = gMonIconPaletteIndices[species];\n    FreeSpritePaletteByTag(gMonIconPaletteTable[palIndex].tag);",
  },
  "SafeLoadMonIconPalette": {
    returnType: "void",
    params: "u16 species",
    callsTo: ["IndexOfSpritePaletteTag","LoadSpritePalette"],
    lineCount: 6,
    bodyC: "u8 palIndex;\n    if (species > NUM_SPECIES)\n        species = INVALID_ICON_SPECIES;\n    palIndex = gMonIconPaletteIndices[species];\n    if (IndexOfSpritePaletteTag(gMonIconPaletteTable[palIndex].tag) == 0xFF)\n        LoadSpritePalette(&gMonIconPaletteTable[palIndex]);",
  },
  "SetPartyHPBarSprite": {
    returnType: "void",
    params: "struct Sprite *sprite, u8 animNum",
    lineCount: 3,
    bodyC: "sprite->animNum = animNum;\n    sprite->animDelayCounter = 0;\n    sprite->animCmdIndex = 0;",
  },
  "SpriteCB_MonIcon": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["UpdateMonIconFrame"],
    lineCount: 1,
    bodyC: "UpdateMonIconFrame(sprite);",
  },
  "TryLoadAllMonIconPalettesAtOffset": {
    returnType: "void",
    params: "u16 offset",
    callsTo: ["ARRAY_COUNT","BG_PLTT_ID","LoadPalette"],
    lineCount: 12,
    bodyC: "s32 i;\n     \n    const struct SpritePalette* monIconPalettePtr;\n\n    if (offset <= BG_PLTT_ID(16 - ARRAY_COUNT(gMonIconPaletteTable)))\n    {\n        monIconPalettePtr = gMonIconPaletteTable;\n        for(i = ARRAY_COUNT(gMonIconPaletteTable) - 1; i >= 0; i--)\n        {\n            LoadPalette(monIconPalettePtr->data, offset, 0x20);\n            offset += 0x10;\n            monIconPalettePtr++;\n        }\n    }",
  },
  "UpdateMonIconFrame": {
    returnType: "u8",
    params: "struct Sprite *sprite",
    callsTo: ["RequestSpriteCopy"],
    lineCount: 27,
    bodyC: "u8 result = 0;\n\n    if (sprite->animDelayCounter == 0)\n    {\n        s16 frame = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.imageValue;\n\n        switch (frame)\n        {\n        case -1:\n            break;\n        case -2:\n            sprite->animCmdIndex = 0;\n            break;\n        default:\n            RequestSpriteCopy(\n                 \n                 \n                 \n                (u8 *)sprite->images + (sSpriteImageSizes[sprite->oam.shape][sprite->oam.size] * frame),\n                (u8 *)(OBJ_VRAM0 + sprite->oam.tileNum * TILE_SIZE_4BPP),\n                sSpriteImageSizes[sprite->oam.shape][sprite->oam.size]);\n            sprite->animDelayCounter = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.duration & 0xFF;\n            sprite->animCmdIndex++;\n            result = sprite->animCmdIndex;\n            break;\n        }\n    }\n    else\n    {\n        sprite->animDelayCounter--;\n    }\n    return result;",
  },
} as const;
