// AUTO-GENERATED from src/scrcmd.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 231

export const ENGINE_FUNCTIONS = {
  "CloseBrailleWindow": {
    returnType: "static void",
    params: "void",
    callsTo: ["ClearStdWindowAndFrame","RemoveWindow"],
    lineCount: 2,
    bodyC: "ClearStdWindowAndFrame(sBrailleWindowId, TRUE);\n    RemoveWindow(sBrailleWindowId);",
  },
  "Compare": {
    returnType: "u8",
    params: "u16 a, u16 b",
    lineCount: 5,
    bodyC: "if (a < b)\n        return 0;\n    if (a == b)\n        return 1;\n    return 2;",
  },
  "IsDoorAnimationStopped": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["FieldIsDoorAnimationRunning"],
    lineCount: 4,
    bodyC: "if (!FieldIsDoorAnimationRunning())\n        return TRUE;\n    else\n        return FALSE;",
  },
  "IsPaletteNotActive": {
    returnType: "static bool8",
    params: "void",
    lineCount: 4,
    bodyC: "if (!gPaletteFade.active)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "RunPauseTimer": {
    returnType: "static bool8",
    params: "void",
    lineCount: 4,
    bodyC: "if (--sPauseCounter == 0)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "ScrCmd_addcoins": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["AddCoins","ScriptReadHalfword","VarGet"],
    lineCount: 6,
    bodyC: "u16 coins = VarGet(ScriptReadHalfword(ctx));\n\n    if (AddCoins(coins) == TRUE)\n        gSpecialVar_Result = FALSE;\n    else\n        gSpecialVar_Result = TRUE;\n    return FALSE;",
  },
  "ScrCmd_adddecoration": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DecorationAdd","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u32 decorId = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = DecorationAdd(decorId);\n    return FALSE;",
  },
  "ScrCmd_addelevmenuitem": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","VarGet"],
    lineCount: 5,
    bodyC: "u8 v3 = ScriptReadByte(ctx);\n    u16 v5 = VarGet(ScriptReadHalfword(ctx));\n    u16 v7 = VarGet(ScriptReadHalfword(ctx));\n    u16 v9 = VarGet(ScriptReadHalfword(ctx));\n\n     \n    return FALSE;",
  },
  "ScrCmd_additem": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["AddBagItem","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u16 itemId = VarGet(ScriptReadHalfword(ctx));\n    u32 quantity = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = AddBagItem(itemId, (u8)quantity);\n    return FALSE;",
  },
  "ScrCmd_addmoney": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["AddMoney","ScriptReadByte","ScriptReadWord"],
    lineCount: 5,
    bodyC: "u32 amount = ScriptReadWord(ctx);\n    u8 ignore = ScriptReadByte(ctx);\n\n    if (!ignore)\n        AddMoney(&gSaveBlock1Ptr->money, amount);\n    return FALSE;",
  },
  "ScrCmd_addobject": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","TrySpawnObjectEvent","VarGet"],
    lineCount: 3,
    bodyC: "u16 objectId = VarGet(ScriptReadHalfword(ctx));\n\n    TrySpawnObjectEvent(objectId, gSaveBlock1Ptr->location.mapNum, gSaveBlock1Ptr->location.mapGroup);\n    return FALSE;",
  },
  "ScrCmd_addobjectat": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","TrySpawnObjectEvent","VarGet"],
    lineCount: 5,
    bodyC: "u16 objectId = VarGet(ScriptReadHalfword(ctx));\n    u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n\n    TrySpawnObjectEvent(objectId, mapNum, mapGroup);\n    return FALSE;",
  },
  "ScrCmd_addpcitem": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["AddPCItem","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u16 itemId = VarGet(ScriptReadHalfword(ctx));\n    u16 quantity = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = AddPCItem(itemId, quantity);\n    return FALSE;",
  },
  "ScrCmd_addvar": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetVarPointer","ScriptReadHalfword"],
    lineCount: 3,
    bodyC: "u16 *ptr = GetVarPointer(ScriptReadHalfword(ctx));\n    *ptr += ScriptReadHalfword(ctx);\n    return FALSE;",
  },
  "ScrCmd_animateflash": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["AnimateFlash","ScriptContext_Stop","ScriptReadByte"],
    lineCount: 3,
    bodyC: "AnimateFlash(ScriptReadByte(ctx));\n    ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_applymovement": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptMovement_StartObjectMovementScript","ScriptReadHalfword","ScriptReadWord","VarGet"],
    lineCount: 5,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n    const void *movementScript = (const void *)ScriptReadWord(ctx);\n\n    ScriptMovement_StartObjectMovementScript(localId, gSaveBlock1Ptr->location.mapNum, gSaveBlock1Ptr->location.mapGroup, movementScript);\n    sMovingNpcId = localId;\n    return FALSE;",
  },
  "ScrCmd_applymovementat": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptMovement_StartObjectMovementScript","ScriptReadByte","ScriptReadHalfword","ScriptReadWord","VarGet"],
    lineCount: 7,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n    const void *movementScript = (const void *)ScriptReadWord(ctx);\n    u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n\n    ScriptMovement_StartObjectMovementScript(localId, mapNum, mapGroup, movementScript);\n    sMovingNpcId = localId;\n    return FALSE;",
  },
  "ScrCmd_braillemessage": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["AddTextPrinterParameterized","AddWindow","BG_PLTT_ID","CopyWindowToVram","CreateWindowTemplate","DrawStdWindowFrame","FillWindowPixelBuffer","GetStringWidth","LoadUserWindowBorderGfx","PIXEL_FILL","PutWindowTilemap","ScriptReadWord","StringExpandPlaceholders"],
    lineCount: 36,
    bodyC: "u8 *ptr = (u8 *)ScriptReadWord(ctx);\n    struct WindowTemplate winTemplate;\n    s32 i;\n    u8 width, height;\n    u8 xWindow, yWindow, xText, yText;\n    u8 temp;\n\n     \n     \n     \n    StringExpandPlaceholders(gStringVar4, ptr + 6);\n\n    width = GetStringWidth(FONT_BRAILLE, gStringVar4, -1) / 8u;\n\n    if (width > 28)\n        width = 28;\n\n    for (i = 0, height = 4; gStringVar4[i] != EOS;)\n    {\n        if (gStringVar4[i++] == CHAR_NEWLINE)\n            height += 3;\n    }\n\n    if (height > 18)\n        height = 18;\n\n    temp = width + 2;\n    xWindow = (30 - temp) / 2;\n\n    temp = height + 2;\n    yText = (20 - temp) / 2;\n\n    xText = xWindow;\n    xWindow += 1;\n\n    yWindow = yText;\n    yText += 2;\n\n    xText = (xWindow - xText - 1) * 8 + 3;\n    yText = (yText - yWindow - 1) * 8;\n\n    winTemplate = CreateWindowTemplate(0, xWindow, yWindow + 1, width, height, 0xF, 0x1);\n    sBrailleWindowId = AddWindow(&winTemplate);\n    LoadUserWindowBorderGfx(sBrailleWindowId, 0x214, BG_PLTT_ID(14));\n    DrawStdWindowFrame(sBrailleWindowId, FALSE);\n    PutWindowTilemap(sBrailleWindowId);\n    FillWindowPixelBuffer(sBrailleWindowId, PIXEL_FILL(1));\n    AddTextPrinterParameterized(sBrailleWindowId, FONT_BRAILLE, gStringVar4, xText, yText, TEXT_SKIP_DRAW, NULL);\n    CopyWindowToVram(sBrailleWindowId, COPYWIN_FULL);\n    return FALSE;",
  },
  "ScrCmd_bufferboxname": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetBoxNamePtr","ScriptReadByte","ScriptReadHalfword","StringCopy","VarGet"],
    lineCount: 4,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 boxId = VarGet(ScriptReadHalfword(ctx));\n\n    StringCopy(sScriptStringVars[stringVarIndex], GetBoxNamePtr(boxId));\n    return FALSE;",
  },
  "ScrCmd_buffercontestname": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["BufferContestName","ScriptReadByte","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 category = VarGet(ScriptReadHalfword(ctx));\n\n    BufferContestName(sScriptStringVars[stringVarIndex], category);\n    return FALSE;",
  },
  "ScrCmd_bufferdecorationname": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","StringCopy","VarGet"],
    lineCount: 4,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 decorId = VarGet(ScriptReadHalfword(ctx));\n\n    StringCopy(sScriptStringVars[stringVarIndex], gDecorations[decorId].name);\n    return FALSE;",
  },
  "ScrCmd_bufferitemname": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CopyItemName","ScriptReadByte","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 itemId = VarGet(ScriptReadHalfword(ctx));\n\n    CopyItemName(itemId, sScriptStringVars[stringVarIndex]);\n    return FALSE;",
  },
  "ScrCmd_bufferitemnameplural": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CopyItemNameHandlePlural","ScriptReadByte","ScriptReadHalfword","VarGet"],
    lineCount: 5,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 itemId = VarGet(ScriptReadHalfword(ctx));\n    u16 quantity = VarGet(ScriptReadHalfword(ctx));\n\n    CopyItemNameHandlePlural(itemId, sScriptStringVars[stringVarIndex], quantity);\n    return FALSE;",
  },
  "ScrCmd_bufferleadmonspeciesname": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetLeadMonIndex","GetMonData","ScriptReadByte","StringCopy"],
    lineCount: 6,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n\n    u8 *dest = sScriptStringVars[stringVarIndex];\n    u8 partyIndex = GetLeadMonIndex();\n    u32 species = GetMonData(&gPlayerParty[partyIndex], MON_DATA_SPECIES, NULL);\n    StringCopy(dest, gSpeciesNames[species]);\n    return FALSE;",
  },
  "ScrCmd_buffermovename": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","StringCopy","VarGet"],
    lineCount: 4,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 move = VarGet(ScriptReadHalfword(ctx));\n\n    StringCopy(sScriptStringVars[stringVarIndex], gMoveNames[move]);\n    return FALSE;",
  },
  "ScrCmd_buffernumberstring": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ConvertIntToDecimalStringN","CountDigits","ScriptReadByte","ScriptReadHalfword","VarGet"],
    lineCount: 5,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 num = VarGet(ScriptReadHalfword(ctx));\n    u8 numDigits = CountDigits(num);\n\n    ConvertIntToDecimalStringN(sScriptStringVars[stringVarIndex], num, STR_CONV_MODE_LEFT_ALIGN, numDigits);\n    return FALSE;",
  },
  "ScrCmd_bufferpartymonnick": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetMonData","ScriptReadByte","ScriptReadHalfword","StringGet_Nickname","VarGet"],
    lineCount: 5,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 partyIndex = VarGet(ScriptReadHalfword(ctx));\n\n    GetMonData(&gPlayerParty[partyIndex], MON_DATA_NICKNAME, sScriptStringVars[stringVarIndex]);\n    StringGet_Nickname(sScriptStringVars[stringVarIndex]);\n    return FALSE;",
  },
  "ScrCmd_bufferspeciesname": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","StringCopy","VarGet"],
    lineCount: 4,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 species = VarGet(ScriptReadHalfword(ctx));\n\n    StringCopy(sScriptStringVars[stringVarIndex], gSpeciesNames[species]);\n    return FALSE;",
  },
  "ScrCmd_bufferstdstring": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","StringCopy","VarGet"],
    lineCount: 4,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 index = VarGet(ScriptReadHalfword(ctx));\n\n    StringCopy(sScriptStringVars[stringVarIndex], gStdStrings[index]);\n    return FALSE;",
  },
  "ScrCmd_bufferstring": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadWord","StringCopy"],
    lineCount: 4,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    const u8 *text = (u8 *)ScriptReadWord(ctx);\n\n    StringCopy(sScriptStringVars[stringVarIndex], text);\n    return FALSE;",
  },
  "ScrCmd_buffertrainerclassname": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetTrainerClassNameFromId","ScriptReadByte","ScriptReadHalfword","StringCopy","VarGet"],
    lineCount: 4,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 trainerClassId = VarGet(ScriptReadHalfword(ctx));\n\n    StringCopy(sScriptStringVars[stringVarIndex], GetTrainerClassNameFromId(trainerClassId));\n    return FALSE;",
  },
  "ScrCmd_buffertrainername": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetTrainerNameFromId","ScriptReadByte","ScriptReadHalfword","StringCopy","VarGet"],
    lineCount: 4,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u16 trainerClassId = VarGet(ScriptReadHalfword(ctx));\n\n    StringCopy(sScriptStringVars[stringVarIndex], GetTrainerNameFromId(trainerClassId));\n    return FALSE;",
  },
  "ScrCmd_call": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptCall","ScriptReadWord"],
    lineCount: 3,
    bodyC: "const u8 *ptr = (const u8 *)ScriptReadWord(ctx);\n\n    ScriptCall(ctx, ptr);\n    return FALSE;",
  },
  "ScrCmd_call_if": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptCall","ScriptReadByte","ScriptReadWord"],
    lineCount: 5,
    bodyC: "u8 condition = ScriptReadByte(ctx);\n    const u8 *ptr = (const u8 *)ScriptReadWord(ctx);\n\n    if (sScriptConditionTable[condition][ctx->comparisonResult] == 1)\n        ScriptCall(ctx, ptr);\n    return FALSE;",
  },
  "ScrCmd_callnative": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadWord","func"],
    lineCount: 3,
    bodyC: "NativeFunc func = (NativeFunc)ScriptReadWord(ctx);\n\n    func();\n    return FALSE;",
  },
  "ScrCmd_callstd": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptCall","ScriptReadByte"],
    lineCount: 5,
    bodyC: "u8 index = ScriptReadByte(ctx);\n    const u8 **ptr = &gStdScripts[index];\n\n    if (ptr < gStdScripts_End)\n        ScriptCall(ctx, *ptr);\n    return FALSE;",
  },
  "ScrCmd_callstd_if": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptCall","ScriptReadByte"],
    lineCount: 9,
    bodyC: "u8 condition = ScriptReadByte(ctx);\n    u8 index = ScriptReadByte(ctx);\n\n    if (sScriptConditionTable[condition][ctx->comparisonResult] == 1)\n    {\n        const u8 **ptr = &gStdScripts[index];\n        if (ptr < gStdScripts_End)\n            ScriptCall(ctx, *ptr);\n    }\n    return FALSE;",
  },
  "ScrCmd_checkcoins": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetCoins","GetVarPointer","ScriptReadHalfword"],
    lineCount: 3,
    bodyC: "u16 *ptr = GetVarPointer(ScriptReadHalfword(ctx));\n    *ptr = GetCoins();\n    return FALSE;",
  },
  "ScrCmd_checkdecor": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CheckHasDecoration","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u32 decorId = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = CheckHasDecoration(decorId);\n    return FALSE;",
  },
  "ScrCmd_checkdecorspace": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DecorationCheckSpace","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u32 decorId = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = DecorationCheckSpace(decorId);\n    return FALSE;",
  },
  "ScrCmd_checkflag": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FlagGet","ScriptReadHalfword"],
    lineCount: 2,
    bodyC: "ctx->comparisonResult = FlagGet(ScriptReadHalfword(ctx));\n    return FALSE;",
  },
  "ScrCmd_checkitem": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CheckBagHasItem","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u16 itemId = VarGet(ScriptReadHalfword(ctx));\n    u32 quantity = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = CheckBagHasItem(itemId, (u8)quantity);\n    return FALSE;",
  },
  "ScrCmd_checkitemspace": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CheckBagHasSpace","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u16 itemId = VarGet(ScriptReadHalfword(ctx));\n    u32 quantity = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = CheckBagHasSpace(itemId, (u8)quantity);\n    return FALSE;",
  },
  "ScrCmd_checkitemtype": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetPocketByItemId","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 itemId = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = GetPocketByItemId(itemId);\n    return FALSE;",
  },
  "ScrCmd_checkmodernfatefulencounter": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetMonData","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 partyIndex = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = GetMonData(&gPlayerParty[partyIndex], MON_DATA_MODERN_FATEFUL_ENCOUNTER, NULL);\n    return FALSE;",
  },
  "ScrCmd_checkmoney": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["IsEnoughMoney","ScriptReadByte","ScriptReadWord"],
    lineCount: 5,
    bodyC: "u32 amount = ScriptReadWord(ctx);\n    u8 ignore = ScriptReadByte(ctx);\n\n    if (!ignore)\n        gSpecialVar_Result = IsEnoughMoney(&gSaveBlock1Ptr->money, amount);\n    return FALSE;",
  },
  "ScrCmd_checkpartymove": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetMonData","MonKnowsMove","ScriptReadHalfword"],
    lineCount: 16,
    bodyC: "u8 i;\n    u16 move = ScriptReadHalfword(ctx);\n\n    gSpecialVar_Result = PARTY_SIZE;\n    for (i = 0; i < PARTY_SIZE; i++)\n    {\n        u16 species = GetMonData(&gPlayerParty[i], MON_DATA_SPECIES, NULL);\n        if (!species)\n            break;\n        if (!GetMonData(&gPlayerParty[i], MON_DATA_IS_EGG) && MonKnowsMove(&gPlayerParty[i], move) == TRUE)\n        {\n            gSpecialVar_Result = i;\n            gSpecialVar_0x8004 = species;\n            break;\n        }\n    }\n    return FALSE;",
  },
  "ScrCmd_checkpcitem": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CheckPCHasItem","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u16 itemId = VarGet(ScriptReadHalfword(ctx));\n    u16 quantity = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = CheckPCHasItem(itemId, quantity);\n    return FALSE;",
  },
  "ScrCmd_checkplayergender": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    lineCount: 2,
    bodyC: "gSpecialVar_Result = gSaveBlock2Ptr->playerGender;\n    return FALSE;",
  },
  "ScrCmd_checktrainerflag": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["HasTrainerBeenFought","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 index = VarGet(ScriptReadHalfword(ctx));\n\n    ctx->comparisonResult = HasTrainerBeenFought(index);\n    return FALSE;",
  },
  "ScrCmd_choosecontestmon": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ChooseContestMon","ScriptContext_Stop"],
    lineCount: 3,
    bodyC: "ChooseContestMon();\n    ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_clearflag": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FlagClear","ScriptReadHalfword"],
    lineCount: 2,
    bodyC: "FlagClear(ScriptReadHalfword(ctx));\n    return FALSE;",
  },
  "ScrCmd_cleartrainerflag": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ClearTrainerFlag","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 index = VarGet(ScriptReadHalfword(ctx));\n\n    ClearTrainerFlag(index);\n    return FALSE;",
  },
  "ScrCmd_closebraillemessage": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CloseBrailleWindow"],
    lineCount: 2,
    bodyC: "CloseBrailleWindow();\n    return FALSE;",
  },
  "ScrCmd_closedoor": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FieldAnimateDoorClose","ScriptReadHalfword","VarGet"],
    lineCount: 6,
    bodyC: "u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    x += MAP_OFFSET;\n    y += MAP_OFFSET;\n    FieldAnimateDoorClose(x, y);\n    return FALSE;",
  },
  "ScrCmd_closemessage": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["HideFieldMessageBox"],
    lineCount: 2,
    bodyC: "HideFieldMessageBox();\n    return FALSE;",
  },
  "ScrCmd_compare_local_to_local": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Compare","ScriptReadByte"],
    lineCount: 4,
    bodyC: "const u8 value1 = ctx->data[ScriptReadByte(ctx)];\n    const u8 value2 = ctx->data[ScriptReadByte(ctx)];\n\n    ctx->comparisonResult = Compare(value1, value2);\n    return FALSE;",
  },
  "ScrCmd_compare_local_to_ptr": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Compare","ScriptReadByte","ScriptReadWord"],
    lineCount: 4,
    bodyC: "const u8 value1 = ctx->data[ScriptReadByte(ctx)];\n    const u8 value2 = *(const u8 *)ScriptReadWord(ctx);\n\n    ctx->comparisonResult = Compare(value1, value2);\n    return FALSE;",
  },
  "ScrCmd_compare_local_to_value": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Compare","ScriptReadByte"],
    lineCount: 4,
    bodyC: "const u8 value1 = ctx->data[ScriptReadByte(ctx)];\n    const u8 value2 = ScriptReadByte(ctx);\n\n    ctx->comparisonResult = Compare(value1, value2);\n    return FALSE;",
  },
  "ScrCmd_compare_ptr_to_local": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Compare","ScriptReadByte","ScriptReadWord"],
    lineCount: 4,
    bodyC: "const u8 value1 = *(const u8 *)ScriptReadWord(ctx);\n    const u8 value2 = ctx->data[ScriptReadByte(ctx)];\n\n    ctx->comparisonResult = Compare(value1, value2);\n    return FALSE;",
  },
  "ScrCmd_compare_ptr_to_ptr": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Compare","ScriptReadWord"],
    lineCount: 4,
    bodyC: "const u8 value1 = *(const u8 *)ScriptReadWord(ctx);\n    const u8 value2 = *(const u8 *)ScriptReadWord(ctx);\n\n    ctx->comparisonResult = Compare(value1, value2);\n    return FALSE;",
  },
  "ScrCmd_compare_ptr_to_value": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Compare","ScriptReadByte","ScriptReadWord"],
    lineCount: 4,
    bodyC: "const u8 value1 = *(const u8 *)ScriptReadWord(ctx);\n    const u8 value2 = ScriptReadByte(ctx);\n\n    ctx->comparisonResult = Compare(value1, value2);\n    return FALSE;",
  },
  "ScrCmd_compare_var_to_value": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Compare","GetVarPointer","ScriptReadHalfword"],
    lineCount: 4,
    bodyC: "const u16 value1 = *GetVarPointer(ScriptReadHalfword(ctx));\n    const u16 value2 = ScriptReadHalfword(ctx);\n\n    ctx->comparisonResult = Compare(value1, value2);\n    return FALSE;",
  },
  "ScrCmd_compare_var_to_var": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Compare","GetVarPointer","ScriptReadHalfword"],
    lineCount: 4,
    bodyC: "const u16 *ptr1 = GetVarPointer(ScriptReadHalfword(ctx));\n    const u16 *ptr2 = GetVarPointer(ScriptReadHalfword(ctx));\n\n    ctx->comparisonResult = Compare(*ptr1, *ptr2);\n    return FALSE;",
  },
  "ScrCmd_contestlinktransfer": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ContestLinkTransfer","ScriptContext_Stop"],
    lineCount: 3,
    bodyC: "ContestLinkTransfer(gSpecialVar_ContestCategory);\n    ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_copybyte": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadWord"],
    lineCount: 3,
    bodyC: "u8 *ptr = (u8 *)ScriptReadWord(ctx);\n    *ptr = *(const u8 *)ScriptReadWord(ctx);\n    return FALSE;",
  },
  "ScrCmd_copylocal": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte"],
    lineCount: 4,
    bodyC: "u8 destIndex = ScriptReadByte(ctx);\n    u8 srcIndex = ScriptReadByte(ctx);\n\n    ctx->data[destIndex] = ctx->data[srcIndex];\n    return FALSE;",
  },
  "ScrCmd_copyobjectxytoperm": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","TryOverrideObjectEventTemplateCoords","VarGet"],
    lineCount: 3,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n\n    TryOverrideObjectEventTemplateCoords(localId, gSaveBlock1Ptr->location.mapNum, gSaveBlock1Ptr->location.mapGroup);\n    return FALSE;",
  },
  "ScrCmd_copyvar": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetVarPointer","ScriptReadHalfword"],
    lineCount: 3,
    bodyC: "u16 *ptr = GetVarPointer(ScriptReadHalfword(ctx));\n    *ptr = *GetVarPointer(ScriptReadHalfword(ctx));\n    return FALSE;",
  },
  "ScrCmd_createvobject": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CreateVirtualObject","ScriptReadByte","ScriptReadHalfword","VarGet"],
    lineCount: 8,
    bodyC: "u8 graphicsId = ScriptReadByte(ctx);\n    u8 virtualObjId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u32 y = VarGet(ScriptReadHalfword(ctx));\n    u8 elevation = ScriptReadByte(ctx);\n    u8 direction = ScriptReadByte(ctx);\n\n    CreateVirtualObject(graphicsId, virtualObjId, x, y, elevation, direction);\n    return FALSE;",
  },
  "ScrCmd_delay": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","SetupNativeScript"],
    lineCount: 3,
    bodyC: "sPauseCounter = ScriptReadHalfword(ctx);\n    SetupNativeScript(ctx, RunPauseTimer);\n    return TRUE;",
  },
  "ScrCmd_dofieldeffect": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FieldEffectStart","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u16 effectId = VarGet(ScriptReadHalfword(ctx));\n\n    sFieldEffectScriptId = effectId;\n    FieldEffectStart(sFieldEffectScriptId);\n    return FALSE;",
  },
  "ScrCmd_dotimebasedevents": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DoTimeBasedEvents"],
    lineCount: 2,
    bodyC: "DoTimeBasedEvents();\n    return FALSE;",
  },
  "ScrCmd_dotrainerbattle": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["BattleSetup_StartTrainerBattle"],
    lineCount: 2,
    bodyC: "BattleSetup_StartTrainerBattle();\n    return TRUE;",
  },
  "ScrCmd_doweather": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DoCurrentWeather"],
    lineCount: 2,
    bodyC: "DoCurrentWeather();\n    return FALSE;",
  },
  "ScrCmd_dowildbattle": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["BattleSetup_StartScriptedWildBattle","ScriptContext_Stop"],
    lineCount: 3,
    bodyC: "BattleSetup_StartScriptedWildBattle();\n    ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_drawbox": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    lineCount: 1,
    bodyC: "return FALSE;",
  },
  "ScrCmd_drawboxtext": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte"],
    lineCount: 5,
    bodyC: "u8 left = ScriptReadByte(ctx);\n    u8 top = ScriptReadByte(ctx);\n    u8 multichoiceId = ScriptReadByte(ctx);\n    bool8 ignoreBPress = ScriptReadByte(ctx);\n\n     \n    return FALSE;",
  },
  "ScrCmd_end": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["StopScript"],
    lineCount: 2,
    bodyC: "StopScript(ctx);\n    return FALSE;",
  },
  "ScrCmd_endram": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ClearRamScript","StopScript"],
    lineCount: 3,
    bodyC: "ClearRamScript();\n    StopScript(ctx);\n    return TRUE;",
  },
  "ScrCmd_erasebox": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte"],
    lineCount: 5,
    bodyC: "u8 left = ScriptReadByte(ctx);\n    u8 top = ScriptReadByte(ctx);\n    u8 right = ScriptReadByte(ctx);\n    u8 bottom = ScriptReadByte(ctx);\n\n     \n    return FALSE;",
  },
  "ScrCmd_faceplayer": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetPlayerFacingDirection","ObjectEventFaceOppositeDirection"],
    lineCount: 3,
    bodyC: "if (gObjectEvents[gSelectedObjectEvent].active)\n        ObjectEventFaceOppositeDirection(&gObjectEvents[gSelectedObjectEvent], GetPlayerFacingDirection());\n    return FALSE;",
  },
  "ScrCmd_fadedefaultbgm": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Overworld_ChangeMusicToDefault"],
    lineCount: 2,
    bodyC: "Overworld_ChangeMusicToDefault();\n    return FALSE;",
  },
  "ScrCmd_fadeinbgm": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FadeInBGM","ScriptReadByte"],
    lineCount: 6,
    bodyC: "u8 speed = ScriptReadByte(ctx);\n\n    if (speed != 0)\n        FadeInBGM(4 * speed);\n    else\n        FadeInBGM(4);\n    return FALSE;",
  },
  "ScrCmd_fadenewbgm": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Overworld_ChangeMusicTo","ScriptReadHalfword"],
    lineCount: 2,
    bodyC: "Overworld_ChangeMusicTo(ScriptReadHalfword(ctx));\n    return FALSE;",
  },
  "ScrCmd_fadeoutbgm": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FadeOutBGMTemporarily","ScriptReadByte","SetupNativeScript"],
    lineCount: 7,
    bodyC: "u8 speed = ScriptReadByte(ctx);\n\n    if (speed != 0)\n        FadeOutBGMTemporarily(4 * speed);\n    else\n        FadeOutBGMTemporarily(4);\n    SetupNativeScript(ctx, IsBGMPausedOrStopped);\n    return TRUE;",
  },
  "ScrCmd_fadescreen": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FadeScreen","ScriptReadByte","SetupNativeScript"],
    lineCount: 3,
    bodyC: "FadeScreen(ScriptReadByte(ctx), 0);\n    SetupNativeScript(ctx, IsPaletteNotActive);\n    return TRUE;",
  },
  "ScrCmd_fadescreenspeed": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FadeScreen","ScriptReadByte","SetupNativeScript"],
    lineCount: 5,
    bodyC: "u8 mode = ScriptReadByte(ctx);\n    u8 speed = ScriptReadByte(ctx);\n\n    FadeScreen(mode, speed);\n    SetupNativeScript(ctx, IsPaletteNotActive);\n    return TRUE;",
  },
  "ScrCmd_fadescreenswapbuffers": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CpuCopy32","FadeScreen","ScriptReadByte","SetupNativeScript"],
    lineCount: 17,
    bodyC: "u8 mode = ScriptReadByte(ctx);\n\n    switch (mode)\n    {\n    case FADE_TO_BLACK:\n    case FADE_TO_WHITE:\n    default:\n        CpuCopy32(gPlttBufferUnfaded, gPaletteDecompressionBuffer, PLTT_SIZE);\n        FadeScreen(mode, 0);\n        break;\n    case FADE_FROM_BLACK:\n    case FADE_FROM_WHITE:\n        CpuCopy32(gPaletteDecompressionBuffer, gPlttBufferUnfaded, PLTT_SIZE);\n        FadeScreen(mode, 0);\n        break;\n    }\n\n    SetupNativeScript(ctx, IsPaletteNotActive);\n    return TRUE;",
  },
  "ScrCmd_freerotatingtilepuzzle": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FreeRotatingTilePuzzle"],
    lineCount: 2,
    bodyC: "FreeRotatingTilePuzzle();\n    return FALSE;",
  },
  "ScrCmd_getpartysize": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CalculatePlayerPartyCount"],
    lineCount: 2,
    bodyC: "gSpecialVar_Result = CalculatePlayerPartyCount();\n    return FALSE;",
  },
  "ScrCmd_getplayerxy": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetVarPointer","ScriptReadHalfword"],
    lineCount: 5,
    bodyC: "u16 *pX = GetVarPointer(ScriptReadHalfword(ctx));\n    u16 *pY = GetVarPointer(ScriptReadHalfword(ctx));\n\n    *pX = gSaveBlock1Ptr->pos.x;\n    *pY = gSaveBlock1Ptr->pos.y;\n    return FALSE;",
  },
  "ScrCmd_getpokenewsactive": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["IsPokeNewsActive","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 newsKind = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = IsPokeNewsActive(newsKind);\n    return FALSE;",
  },
  "ScrCmd_gettime": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["RtcCalcLocalTime"],
    lineCount: 5,
    bodyC: "RtcCalcLocalTime();\n    gSpecialVar_0x8000 = gLocalTime.hours;\n    gSpecialVar_0x8001 = gLocalTime.minutes;\n    gSpecialVar_0x8002 = gLocalTime.seconds;\n    return FALSE;",
  },
  "ScrCmd_giveegg": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptGiveEgg","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 species = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = ScriptGiveEgg(species);\n    return FALSE;",
  },
  "ScrCmd_givemon": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptGiveMon","ScriptReadByte","ScriptReadHalfword","ScriptReadWord","VarGet"],
    lineCount: 8,
    bodyC: "u16 species = VarGet(ScriptReadHalfword(ctx));\n    u8 level = ScriptReadByte(ctx);\n    u16 item = VarGet(ScriptReadHalfword(ctx));\n    u32 unkParam1 = ScriptReadWord(ctx);\n    u32 unkParam2 = ScriptReadWord(ctx);\n    u8 unkParam3 = ScriptReadByte(ctx);\n\n    gSpecialVar_Result = ScriptGiveMon(species, level, item, unkParam1, unkParam2, unkParam3);\n    return FALSE;",
  },
  "ScrCmd_goto": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptJump","ScriptReadWord"],
    lineCount: 3,
    bodyC: "const u8 *ptr = (const u8 *)ScriptReadWord(ctx);\n\n    ScriptJump(ctx, ptr);\n    return FALSE;",
  },
  "ScrCmd_goto_if": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptJump","ScriptReadByte","ScriptReadWord"],
    lineCount: 5,
    bodyC: "u8 condition = ScriptReadByte(ctx);\n    const u8 *ptr = (const u8 *)ScriptReadWord(ctx);\n\n    if (sScriptConditionTable[condition][ctx->comparisonResult] == 1)\n        ScriptJump(ctx, ptr);\n    return FALSE;",
  },
  "ScrCmd_gotobeatenscript": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["BattleSetup_GetTrainerPostBattleScript"],
    lineCount: 2,
    bodyC: "ctx->scriptPtr = BattleSetup_GetTrainerPostBattleScript();\n    return FALSE;",
  },
  "ScrCmd_gotonative": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadWord","SetupNativeScript","bool8"],
    lineCount: 3,
    bodyC: "bool8 (*addr)(void) = (bool8 (*)(void))ScriptReadWord(ctx);\n\n    SetupNativeScript(ctx, addr);\n    return TRUE;",
  },
  "ScrCmd_gotopostbattlescript": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["BattleSetup_GetScriptAddrAfterBattle"],
    lineCount: 2,
    bodyC: "ctx->scriptPtr = BattleSetup_GetScriptAddrAfterBattle();\n    return FALSE;",
  },
  "ScrCmd_gotostd": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptJump","ScriptReadByte"],
    lineCount: 5,
    bodyC: "u8 index = ScriptReadByte(ctx);\n    const u8 **ptr = &gStdScripts[index];\n\n    if (ptr < gStdScripts_End)\n        ScriptJump(ctx, *ptr);\n    return FALSE;",
  },
  "ScrCmd_gotostd_if": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptJump","ScriptReadByte"],
    lineCount: 9,
    bodyC: "u8 condition = ScriptReadByte(ctx);\n    u8 index = ScriptReadByte(ctx);\n\n    if (sScriptConditionTable[condition][ctx->comparisonResult] == 1)\n    {\n        const u8 **ptr = &gStdScripts[index];\n        if (ptr < gStdScripts_End)\n            ScriptJump(ctx, *ptr);\n    }\n    return FALSE;",
  },
  "ScrCmd_hidecoinsbox": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["HideCoinsWindow","ScriptReadByte"],
    lineCount: 4,
    bodyC: "u8 x = ScriptReadByte(ctx);\n    u8 y = ScriptReadByte(ctx);\n\n    HideCoinsWindow();\n    return FALSE;",
  },
  "ScrCmd_hidemoneybox": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["HideMoneyBox"],
    lineCount: 2,
    bodyC: "HideMoneyBox();\n    return FALSE;",
  },
  "ScrCmd_hidemonpic": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptMenu_HidePokemonPic","SetupNativeScript","bool8"],
    lineCount: 5,
    bodyC: "bool8 (*func)(void) = ScriptMenu_HidePokemonPic();\n\n    if (func == NULL)\n        return FALSE;\n    SetupNativeScript(ctx, func);\n    return TRUE;",
  },
  "ScrCmd_hideobjectat": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetObjectInvisibility","VarGet"],
    lineCount: 5,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n    u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n\n    SetObjectInvisibility(localId, mapNum, mapGroup, TRUE);\n    return FALSE;",
  },
  "ScrCmd_incrementgamestat": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["IncrementGameStat","ScriptReadByte"],
    lineCount: 2,
    bodyC: "IncrementGameStat(ScriptReadByte(ctx));\n    return FALSE;",
  },
  "ScrCmd_initclock": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["RtcInitLocalTimeOffset","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u8 hour = VarGet(ScriptReadHalfword(ctx));\n    u8 minute = VarGet(ScriptReadHalfword(ctx));\n\n    RtcInitLocalTimeOffset(hour, minute);\n    return FALSE;",
  },
  "ScrCmd_initrotatingtilepuzzle": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["InitRotatingTilePuzzle","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 isTrickHouse = VarGet(ScriptReadHalfword(ctx));\n\n    InitRotatingTilePuzzle(isTrickHouse);\n    return FALSE;",
  },
  "ScrCmd_loadbyte": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte"],
    lineCount: 3,
    bodyC: "u8 index = ScriptReadByte(ctx);\n\n    ctx->data[index] = ScriptReadByte(ctx);\n    return FALSE;",
  },
  "ScrCmd_loadbytefromptr": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadWord"],
    lineCount: 3,
    bodyC: "u8 index = ScriptReadByte(ctx);\n\n    ctx->data[index] = *(const u8 *)ScriptReadWord(ctx);\n    return FALSE;",
  },
  "ScrCmd_loadword": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadWord"],
    lineCount: 3,
    bodyC: "u8 index = ScriptReadByte(ctx);\n\n    ctx->data[index] = ScriptReadWord(ctx);\n    return FALSE;",
  },
  "ScrCmd_lock": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FreezeObjects_WaitForPlayer","FreezeObjects_WaitForPlayerAndSelected","IsOverworldLinkActive","SetupNativeScript"],
    lineCount: 18,
    bodyC: "if (IsOverworldLinkActive())\n    {\n        return FALSE;\n    }\n    else\n    {\n        if (gObjectEvents[gSelectedObjectEvent].active)\n        {\n            FreezeObjects_WaitForPlayerAndSelected();\n            SetupNativeScript(ctx, IsFreezeSelectedObjectAndPlayerFinished);\n        }\n        else\n        {\n            FreezeObjects_WaitForPlayer();\n            SetupNativeScript(ctx, IsFreezePlayerFinished);\n        }\n        return TRUE;\n    }",
  },
  "ScrCmd_lockall": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FreezeObjects_WaitForPlayer","IsOverworldLinkActive","SetupNativeScript"],
    lineCount: 10,
    bodyC: "if (IsOverworldLinkActive())\n    {\n        return FALSE;\n    }\n    else\n    {\n        FreezeObjects_WaitForPlayer();\n        SetupNativeScript(ctx, IsFreezePlayerFinished);\n        return TRUE;\n    }",
  },
  "ScrCmd_lockfortrainer": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FreezeForApproachingTrainers","IsOverworldLinkActive","SetupNativeScript"],
    lineCount: 13,
    bodyC: "if (IsOverworldLinkActive())\n    {\n        return FALSE;\n    }\n    else\n    {\n        if (gObjectEvents[gSelectedObjectEvent].active)\n        {\n            FreezeForApproachingTrainers();\n            SetupNativeScript(ctx, IsFreezeObjectAndPlayerFinished);\n        }\n        return TRUE;\n    }",
  },
  "ScrCmd_message": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadWord","ShowFieldMessage"],
    lineCount: 5,
    bodyC: "const u8 *msg = (const u8 *)ScriptReadWord(ctx);\n\n    if (msg == NULL)\n        msg = (const u8 *)ctx->data[0];\n    ShowFieldMessage(msg);\n    return FALSE;",
  },
  "ScrCmd_messageautoscroll": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadWord","ShowFieldAutoScrollMessage"],
    lineCount: 7,
    bodyC: "const u8 *msg = (const u8 *)ScriptReadWord(ctx);\n\n    if (msg == NULL)\n        msg = (const u8 *)ctx->data[0];\n    gTextFlags.autoScroll = TRUE;\n    gTextFlags.forceMidTextSpeed = TRUE;\n    ShowFieldAutoScrollMessage(msg);\n    return FALSE;",
  },
  "ScrCmd_messageinstant": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["AddTextPrinterParameterized","DrawDialogueFrame","LoadMessageBoxAndBorderGfx","ScriptReadWord"],
    lineCount: 7,
    bodyC: "const u8 *msg = (const u8 *)ScriptReadWord(ctx);\n\n    if (msg == NULL)\n        msg = (const u8 *)ctx->data[0];\n    LoadMessageBoxAndBorderGfx();\n    DrawDialogueFrame(0, TRUE);\n    AddTextPrinterParameterized(0, FONT_NORMAL, msg, 0, 1, 0, NULL);\n    return FALSE;",
  },
  "ScrCmd_moverotatingtileobjects": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["MoveRotatingTileObjects","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 puzzleNumber = VarGet(ScriptReadHalfword(ctx));\n\n    sMovingNpcId = MoveRotatingTileObjects(puzzleNumber);\n    return FALSE;",
  },
  "ScrCmd_multichoice": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptContext_Stop","ScriptMenu_Multichoice","ScriptReadByte"],
    lineCount: 13,
    bodyC: "u8 left = ScriptReadByte(ctx);\n    u8 top = ScriptReadByte(ctx);\n    u8 multichoiceId = ScriptReadByte(ctx);\n    bool8 ignoreBPress = ScriptReadByte(ctx);\n\n    if (ScriptMenu_Multichoice(left, top, multichoiceId, ignoreBPress) == TRUE)\n    {\n        ScriptContext_Stop();\n        return TRUE;\n    }\n    else\n    {\n        return FALSE;\n    }",
  },
  "ScrCmd_multichoicedefault": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptContext_Stop","ScriptMenu_MultichoiceWithDefault","ScriptReadByte"],
    lineCount: 14,
    bodyC: "u8 left = ScriptReadByte(ctx);\n    u8 top = ScriptReadByte(ctx);\n    u8 multichoiceId = ScriptReadByte(ctx);\n    u8 defaultChoice = ScriptReadByte(ctx);\n    bool8 ignoreBPress = ScriptReadByte(ctx);\n\n    if (ScriptMenu_MultichoiceWithDefault(left, top, multichoiceId, ignoreBPress, defaultChoice) == TRUE)\n    {\n        ScriptContext_Stop();\n        return TRUE;\n    }\n    else\n    {\n        return FALSE;\n    }",
  },
  "ScrCmd_multichoicegrid": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptContext_Stop","ScriptMenu_MultichoiceGrid","ScriptReadByte"],
    lineCount: 14,
    bodyC: "u8 left = ScriptReadByte(ctx);\n    u8 top = ScriptReadByte(ctx);\n    u8 multichoiceId = ScriptReadByte(ctx);\n    u8 numColumns = ScriptReadByte(ctx);\n    bool8 ignoreBPress = ScriptReadByte(ctx);\n\n    if (ScriptMenu_MultichoiceGrid(left, top, multichoiceId, ignoreBPress, numColumns) == TRUE)\n    {\n        ScriptContext_Stop();\n        return TRUE;\n    }\n    else\n    {\n        return FALSE;\n    }",
  },
  "ScrCmd_nop": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    lineCount: 1,
    bodyC: "return FALSE;",
  },
  "ScrCmd_nop1": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    lineCount: 1,
    bodyC: "return FALSE;",
  },
  "ScrCmd_opendoor": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FieldAnimateDoorOpen","GetDoorSoundEffect","PlaySE","ScriptReadHalfword","VarGet"],
    lineCount: 7,
    bodyC: "u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    x += MAP_OFFSET;\n    y += MAP_OFFSET;\n    PlaySE(GetDoorSoundEffect(x, y));\n    FieldAnimateDoorOpen(x, y);\n    return FALSE;",
  },
  "ScrCmd_playbgm": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Overworld_SetSavedMusic","PlayNewMapMusic","ScriptReadByte","ScriptReadHalfword"],
    lineCount: 6,
    bodyC: "u16 songId = ScriptReadHalfword(ctx);\n    bool8 save = ScriptReadByte(ctx);\n\n    if (save == TRUE)\n        Overworld_SetSavedMusic(songId);\n    PlayNewMapMusic(songId);\n    return FALSE;",
  },
  "ScrCmd_playfanfare": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["PlayFanfare","ScriptReadHalfword"],
    lineCount: 2,
    bodyC: "PlayFanfare(ScriptReadHalfword(ctx));\n    return FALSE;",
  },
  "ScrCmd_playmoncry": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["PlayCry_Script","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u16 species = VarGet(ScriptReadHalfword(ctx));\n    u16 mode = VarGet(ScriptReadHalfword(ctx));\n\n    PlayCry_Script(species, mode);\n    return FALSE;",
  },
  "ScrCmd_playse": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["PlaySE","ScriptReadHalfword"],
    lineCount: 2,
    bodyC: "PlaySE(ScriptReadHalfword(ctx));\n    return FALSE;",
  },
  "ScrCmd_playslotmachine": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["PlaySlotMachine","ScriptContext_Stop","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u8 machineId = VarGet(ScriptReadHalfword(ctx));\n\n    PlaySlotMachine(machineId, CB2_ReturnToFieldContinueScriptPlayMapMusic);\n    ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_pokemart": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CreatePokemartMenu","ScriptContext_Stop","ScriptReadWord"],
    lineCount: 4,
    bodyC: "const void *ptr = (void *)ScriptReadWord(ctx);\n\n    CreatePokemartMenu(ptr);\n    ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_pokemartdecoration": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CreateDecorationShop1Menu","ScriptContext_Stop","ScriptReadWord"],
    lineCount: 4,
    bodyC: "const void *ptr = (void *)ScriptReadWord(ctx);\n\n    CreateDecorationShop1Menu(ptr);\n    ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_pokemartdecoration2": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CreateDecorationShop2Menu","ScriptContext_Stop","ScriptReadWord"],
    lineCount: 4,
    bodyC: "const void *ptr = (void *)ScriptReadWord(ctx);\n\n    CreateDecorationShop2Menu(ptr);\n    ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_pokenavcall": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadWord","ShowPokenavFieldMessage"],
    lineCount: 5,
    bodyC: "const u8 *msg = (const u8 *)ScriptReadWord(ctx);\n\n    if (msg == NULL)\n        msg = (const u8 *)ctx->data[0];\n    ShowPokenavFieldMessage(msg);\n    return FALSE;",
  },
  "ScrCmd_random": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Random","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 max = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = Random() % max;\n    return FALSE;",
  },
  "ScrCmd_release": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetObjectEventIdByLocalIdAndMap","HideFieldMessageBox","ObjectEventClearHeldMovementIfFinished","ScriptMovement_UnfreezeObjectEvents","UnfreezeObjectEvents"],
    lineCount: 9,
    bodyC: "u8 playerObjectId;\n\n    HideFieldMessageBox();\n    if (gObjectEvents[gSelectedObjectEvent].active)\n        ObjectEventClearHeldMovementIfFinished(&gObjectEvents[gSelectedObjectEvent]);\n    playerObjectId = GetObjectEventIdByLocalIdAndMap(LOCALID_PLAYER, 0, 0);\n    ObjectEventClearHeldMovementIfFinished(&gObjectEvents[playerObjectId]);\n    ScriptMovement_UnfreezeObjectEvents();\n    UnfreezeObjectEvents();\n    return FALSE;",
  },
  "ScrCmd_releaseall": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetObjectEventIdByLocalIdAndMap","HideFieldMessageBox","ObjectEventClearHeldMovementIfFinished","ScriptMovement_UnfreezeObjectEvents","UnfreezeObjectEvents"],
    lineCount: 7,
    bodyC: "u8 playerObjectId;\n\n    HideFieldMessageBox();\n    playerObjectId = GetObjectEventIdByLocalIdAndMap(LOCALID_PLAYER, 0, 0);\n    ObjectEventClearHeldMovementIfFinished(&gObjectEvents[playerObjectId]);\n    ScriptMovement_UnfreezeObjectEvents();\n    UnfreezeObjectEvents();\n    return FALSE;",
  },
  "ScrCmd_removecoins": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["RemoveCoins","ScriptReadHalfword","VarGet"],
    lineCount: 6,
    bodyC: "u16 coins = VarGet(ScriptReadHalfword(ctx));\n\n    if (RemoveCoins(coins) == TRUE)\n        gSpecialVar_Result = FALSE;\n    else\n        gSpecialVar_Result = TRUE;\n    return FALSE;",
  },
  "ScrCmd_removedecoration": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DecorationRemove","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u32 decorId = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = DecorationRemove(decorId);\n    return FALSE;",
  },
  "ScrCmd_removeitem": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["RemoveBagItem","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u16 itemId = VarGet(ScriptReadHalfword(ctx));\n    u32 quantity = VarGet(ScriptReadHalfword(ctx));\n\n    gSpecialVar_Result = RemoveBagItem(itemId, (u8)quantity);\n    return FALSE;",
  },
  "ScrCmd_removemoney": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["RemoveMoney","ScriptReadByte","ScriptReadWord"],
    lineCount: 5,
    bodyC: "u32 amount = ScriptReadWord(ctx);\n    u8 ignore = ScriptReadByte(ctx);\n\n    if (!ignore)\n        RemoveMoney(&gSaveBlock1Ptr->money, amount);\n    return FALSE;",
  },
  "ScrCmd_removeobject": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["RemoveObjectEventByLocalIdAndMap","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n\n    RemoveObjectEventByLocalIdAndMap(localId, gSaveBlock1Ptr->location.mapNum, gSaveBlock1Ptr->location.mapGroup);\n    return FALSE;",
  },
  "ScrCmd_removeobjectat": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["RemoveObjectEventByLocalIdAndMap","ScriptReadByte","ScriptReadHalfword","VarGet"],
    lineCount: 5,
    bodyC: "u16 objectId = VarGet(ScriptReadHalfword(ctx));\n    u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n\n    RemoveObjectEventByLocalIdAndMap(objectId, mapNum, mapGroup);\n    return FALSE;",
  },
  "ScrCmd_resetobjectsubpriority": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ResetObjectSubpriority","ScriptReadByte","ScriptReadHalfword","VarGet"],
    lineCount: 5,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n    u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n\n    ResetObjectSubpriority(localId, mapNum, mapGroup);\n    return FALSE;",
  },
  "ScrCmd_resetweather": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["SetSavedWeatherFromCurrMapHeader"],
    lineCount: 2,
    bodyC: "SetSavedWeatherFromCurrMapHeader();\n    return FALSE;",
  },
  "ScrCmd_return": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReturn"],
    lineCount: 2,
    bodyC: "ScriptReturn(ctx);\n    return FALSE;",
  },
  "ScrCmd_returnram": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptJump"],
    lineCount: 2,
    bodyC: "ScriptJump(ctx, gRamScriptRetAddr);\n    return FALSE;",
  },
  "ScrCmd_savebgm": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["Overworld_SetSavedMusic","ScriptReadHalfword"],
    lineCount: 2,
    bodyC: "Overworld_SetSavedMusic(ScriptReadHalfword(ctx));\n    return FALSE;",
  },
  "ScrCmd_selectapproachingtrainer": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetCurrentApproachingTrainerObjectEventId"],
    lineCount: 2,
    bodyC: "gSelectedObjectEvent = GetCurrentApproachingTrainerObjectEventId();\n    return FALSE;",
  },
  "ScrCmd_setberrytree": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["PlantBerryTree","ScriptReadByte"],
    lineCount: 8,
    bodyC: "u8 treeId = ScriptReadByte(ctx);\n    u8 berry = ScriptReadByte(ctx);\n    u8 growthStage = ScriptReadByte(ctx);\n\n    if (berry == 0)\n        PlantBerryTree(treeId, berry, growthStage, FALSE);\n    else\n        PlantBerryTree(treeId, berry, growthStage, FALSE);\n    return FALSE;",
  },
  "ScrCmd_setdivewarp": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetFixedDiveWarp","VarGet"],
    lineCount: 7,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetFixedDiveWarp(mapGroup, mapNum, warpId, x, y);\n    return FALSE;",
  },
  "ScrCmd_setdoorclosed": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FieldSetDoorClosed","ScriptReadHalfword","VarGet"],
    lineCount: 6,
    bodyC: "u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    x += MAP_OFFSET;\n    y += MAP_OFFSET;\n    FieldSetDoorClosed(x, y);\n    return FALSE;",
  },
  "ScrCmd_setdooropen": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FieldSetDoorOpened","ScriptReadHalfword","VarGet"],
    lineCount: 6,
    bodyC: "u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    x += MAP_OFFSET;\n    y += MAP_OFFSET;\n    FieldSetDoorOpened(x, y);\n    return FALSE;",
  },
  "ScrCmd_setdynamicwarp": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetDynamicWarpWithCoords","VarGet"],
    lineCount: 7,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetDynamicWarpWithCoords(0, mapGroup, mapNum, warpId, x, y);\n    return FALSE;",
  },
  "ScrCmd_setescapewarp": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetEscapeWarp","VarGet"],
    lineCount: 7,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetEscapeWarp(mapGroup, mapNum, warpId, x, y);\n    return FALSE;",
  },
  "ScrCmd_setfieldeffectargument": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u8 argNum = ScriptReadByte(ctx);\n\n    gFieldEffectArguments[argNum] = (s16)VarGet(ScriptReadHalfword(ctx));\n    return FALSE;",
  },
  "ScrCmd_setflag": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["FlagSet","ScriptReadHalfword"],
    lineCount: 2,
    bodyC: "FlagSet(ScriptReadHalfword(ctx));\n    return FALSE;",
  },
  "ScrCmd_setflashlevel": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","SetFlashLevel","VarGet"],
    lineCount: 2,
    bodyC: "SetFlashLevel(VarGet(ScriptReadHalfword(ctx)));\n    return FALSE;",
  },
  "ScrCmd_setholewarp": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetFixedHoleWarp","VarGet"],
    lineCount: 7,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetFixedHoleWarp(mapGroup, mapNum, warpId, x, y);\n    return FALSE;",
  },
  "ScrCmd_setmaplayoutindex": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","SetCurrentMapLayout","VarGet"],
    lineCount: 3,
    bodyC: "u16 value = VarGet(ScriptReadHalfword(ctx));\n\n    SetCurrentMapLayout(value);\n    return FALSE;",
  },
  "ScrCmd_setmetatile": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["MapGridSetMetatileIdAt","ScriptReadHalfword","VarGet"],
    lineCount: 11,
    bodyC: "u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n    u16 metatileId = VarGet(ScriptReadHalfword(ctx));\n    bool16 isImpassable = VarGet(ScriptReadHalfword(ctx));\n\n    x += MAP_OFFSET;\n    y += MAP_OFFSET;\n    if (!isImpassable)\n        MapGridSetMetatileIdAt(x, y, metatileId);\n    else\n        MapGridSetMetatileIdAt(x, y, metatileId | MAPGRID_IMPASSABLE);\n    return FALSE;",
  },
  "ScrCmd_setmodernfatefulencounter": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","SetMonData","VarGet"],
    lineCount: 4,
    bodyC: "bool8 isModernFatefulEncounter = TRUE;\n    u16 partyIndex = VarGet(ScriptReadHalfword(ctx));\n\n    SetMonData(&gPlayerParty[partyIndex], MON_DATA_MODERN_FATEFUL_ENCOUNTER, &isModernFatefulEncounter);\n    return FALSE;",
  },
  "ScrCmd_setmonmetlocation": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetMonData","VarGet"],
    lineCount: 5,
    bodyC: "u16 partyIndex = VarGet(ScriptReadHalfword(ctx));\n    u8 location = ScriptReadByte(ctx);\n\n    if (partyIndex < PARTY_SIZE)\n        SetMonData(&gPlayerParty[partyIndex], MON_DATA_MET_LOCATION, &location);\n    return FALSE;",
  },
  "ScrCmd_setmonmove": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","ScriptSetMonMoveSlot"],
    lineCount: 5,
    bodyC: "u8 partyIndex = ScriptReadByte(ctx);\n    u8 slot = ScriptReadByte(ctx);\n    u16 move = ScriptReadHalfword(ctx);\n\n    ScriptSetMonMoveSlot(partyIndex, move, slot);\n    return FALSE;",
  },
  "ScrCmd_setmysteryeventstatus": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","SetMysteryEventScriptStatus"],
    lineCount: 3,
    bodyC: "u8 status = ScriptReadByte(ctx);\n\n    SetMysteryEventScriptStatus(status);\n    return FALSE;",
  },
  "ScrCmd_setobjectmovementtype": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetObjEventTemplateMovementType","VarGet"],
    lineCount: 4,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n    u8 movementType = ScriptReadByte(ctx);\n\n    SetObjEventTemplateMovementType(localId, movementType);\n    return FALSE;",
  },
  "ScrCmd_setobjectsubpriority": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetObjectSubpriority","VarGet"],
    lineCount: 6,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n    u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 priority = ScriptReadByte(ctx);\n\n    SetObjectSubpriority(localId, mapNum, mapGroup, priority + 83);\n    return FALSE;",
  },
  "ScrCmd_setobjectxy": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","TryMoveObjectEventToMapCoords","VarGet"],
    lineCount: 5,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    TryMoveObjectEventToMapCoords(localId, gSaveBlock1Ptr->location.mapNum, gSaveBlock1Ptr->location.mapGroup, x, y);\n    return FALSE;",
  },
  "ScrCmd_setobjectxyperm": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","SetObjEventTemplateCoords","VarGet"],
    lineCount: 5,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetObjEventTemplateCoords(localId, x, y);\n    return FALSE;",
  },
  "ScrCmd_setorcopyvar": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetVarPointer","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 *ptr = GetVarPointer(ScriptReadHalfword(ctx));\n    *ptr = VarGet(ScriptReadHalfword(ctx));\n    return FALSE;",
  },
  "ScrCmd_setptr": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadWord"],
    lineCount: 3,
    bodyC: "u8 value = ScriptReadByte(ctx);\n\n    *(u8 *)ScriptReadWord(ctx) = value;\n    return FALSE;",
  },
  "ScrCmd_setptrbyte": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadWord"],
    lineCount: 3,
    bodyC: "u8 index = ScriptReadByte(ctx);\n\n    *(u8 *)ScriptReadWord(ctx) = ctx->data[index];\n    return FALSE;",
  },
  "ScrCmd_setrespawn": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","SetLastHealLocationWarp","VarGet"],
    lineCount: 3,
    bodyC: "u16 healLocationId = VarGet(ScriptReadHalfword(ctx));\n\n    SetLastHealLocationWarp(healLocationId);\n    return FALSE;",
  },
  "ScrCmd_setstepcallback": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ActivatePerStepCallback","ScriptReadByte"],
    lineCount: 2,
    bodyC: "ActivatePerStepCallback(ScriptReadByte(ctx));\n    return FALSE;",
  },
  "ScrCmd_settrainerflag": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","SetTrainerFlag","VarGet"],
    lineCount: 3,
    bodyC: "u16 index = VarGet(ScriptReadHalfword(ctx));\n\n    SetTrainerFlag(index);\n    return FALSE;",
  },
  "ScrCmd_setvaddress": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadWord"],
    lineCount: 4,
    bodyC: "u32 addr1 = (u32)ctx->scriptPtr - 1;\n    u32 addr2 = ScriptReadWord(ctx);\n\n    sAddressOffset = addr2 - addr1;\n    return FALSE;",
  },
  "ScrCmd_setvar": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetVarPointer","ScriptReadHalfword"],
    lineCount: 3,
    bodyC: "u16 *ptr = GetVarPointer(ScriptReadHalfword(ctx));\n    *ptr = ScriptReadHalfword(ctx);\n    return FALSE;",
  },
  "ScrCmd_setwarp": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetWarpDestination","VarGet"],
    lineCount: 7,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetWarpDestination(mapGroup, mapNum, warpId, x, y);\n    return FALSE;",
  },
  "ScrCmd_setweather": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","SetSavedWeather","VarGet"],
    lineCount: 3,
    bodyC: "u16 weather = VarGet(ScriptReadHalfword(ctx));\n\n    SetSavedWeather(weather);\n    return FALSE;",
  },
  "ScrCmd_setwildbattle": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["CreateScriptedWildMon","ScriptReadByte","ScriptReadHalfword"],
    lineCount: 5,
    bodyC: "u16 species = ScriptReadHalfword(ctx);\n    u8 level = ScriptReadByte(ctx);\n    u16 item = ScriptReadHalfword(ctx);\n\n    CreateScriptedWildMon(species, level, item);\n    return FALSE;",
  },
  "ScrCmd_showcoinsbox": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetCoins","ScriptReadByte","ShowCoinsWindow"],
    lineCount: 4,
    bodyC: "u8 x = ScriptReadByte(ctx);\n    u8 y = ScriptReadByte(ctx);\n\n    ShowCoinsWindow(GetCoins(), x, y);\n    return FALSE;",
  },
  "ScrCmd_showcontestpainting": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptContext_Stop","ScriptReadByte","SetContestWinnerForPainting","ShowContestPainting"],
    lineCount: 6,
    bodyC: "u8 contestWinnerId = ScriptReadByte(ctx);\n\n     \n    if (contestWinnerId != CONTEST_WINNER_ARTIST)\n        SetContestWinnerForPainting(contestWinnerId);\n\n    ShowContestPainting();\n    ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_showcontestresults": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptContext_Stop","ShowContestResults"],
    lineCount: 3,
    bodyC: "ShowContestResults();\n    ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_showelevmenu": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    lineCount: 1,
    bodyC: "return FALSE;",
  },
  "ScrCmd_showmoneybox": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DrawMoneyBox","GetMoney","ScriptReadByte"],
    lineCount: 6,
    bodyC: "u8 x = ScriptReadByte(ctx);\n    u8 y = ScriptReadByte(ctx);\n    u8 ignore = ScriptReadByte(ctx);\n\n    if (!ignore)\n        DrawMoneyBox(GetMoney(&gSaveBlock1Ptr->money), x, y);\n    return FALSE;",
  },
  "ScrCmd_showmonpic": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptMenu_ShowPokemonPic","ScriptReadByte","ScriptReadHalfword","VarGet"],
    lineCount: 5,
    bodyC: "u16 species = VarGet(ScriptReadHalfword(ctx));\n    u8 x = ScriptReadByte(ctx);\n    u8 y = ScriptReadByte(ctx);\n\n    ScriptMenu_ShowPokemonPic(species, x, y);\n    return FALSE;",
  },
  "ScrCmd_showobjectat": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetObjectInvisibility","VarGet"],
    lineCount: 5,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n    u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n\n    SetObjectInvisibility(localId, mapNum, mapGroup, FALSE);\n    return FALSE;",
  },
  "ScrCmd_special": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword"],
    lineCount: 3,
    bodyC: "u16 index = ScriptReadHalfword(ctx);\n\n    gSpecials[index]();\n    return FALSE;",
  },
  "ScrCmd_specialvar": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetVarPointer","ScriptReadHalfword"],
    lineCount: 3,
    bodyC: "u16 *var = GetVarPointer(ScriptReadHalfword(ctx));\n\n    *var = gSpecials[ScriptReadHalfword(ctx)]();\n    return FALSE;",
  },
  "ScrCmd_startcontest": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptContext_Stop","StartContest"],
    lineCount: 3,
    bodyC: "StartContest();\n    ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_subvar": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetVarPointer","ScriptReadHalfword","VarGet"],
    lineCount: 3,
    bodyC: "u16 *ptr = GetVarPointer(ScriptReadHalfword(ctx));\n    *ptr -= VarGet(ScriptReadHalfword(ctx));\n    return FALSE;",
  },
  "ScrCmd_trainerbattle": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["BattleSetup_ConfigureTrainerBattle"],
    lineCount: 2,
    bodyC: "ctx->scriptPtr = BattleSetup_ConfigureTrainerBattle(ctx->scriptPtr);\n    return FALSE;",
  },
  "ScrCmd_trywondercardscript": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetSavedRamScriptIfValid","ScriptJump"],
    lineCount: 7,
    bodyC: "const u8 *script = GetSavedRamScriptIfValid();\n\n    if (script)\n    {\n        gRamScriptRetAddr = ctx->scriptPtr;\n        ScriptJump(ctx, script);\n    }\n    return FALSE;",
  },
  "ScrCmd_turnobject": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ObjectEventTurnByLocalIdAndMap","ScriptReadByte","ScriptReadHalfword","VarGet"],
    lineCount: 4,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n    u8 direction = ScriptReadByte(ctx);\n\n    ObjectEventTurnByLocalIdAndMap(localId, gSaveBlock1Ptr->location.mapNum, gSaveBlock1Ptr->location.mapGroup, direction);\n    return FALSE;",
  },
  "ScrCmd_turnrotatingtileobjects": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["TurnRotatingTileObjects"],
    lineCount: 2,
    bodyC: "TurnRotatingTileObjects();\n    return FALSE;",
  },
  "ScrCmd_turnvobject": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","TurnVirtualObject"],
    lineCount: 4,
    bodyC: "u8 virtualObjId = ScriptReadByte(ctx);\n    u8 direction = ScriptReadByte(ctx);\n\n    TurnVirtualObject(virtualObjId, direction);\n    return FALSE;",
  },
  "ScrCmd_updatecoinsbox": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["GetCoins","PrintCoinsString","ScriptReadByte"],
    lineCount: 4,
    bodyC: "u8 x = ScriptReadByte(ctx);\n    u8 y = ScriptReadByte(ctx);\n\n    PrintCoinsString(GetCoins());\n    return FALSE;",
  },
  "ScrCmd_updatemoneybox": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ChangeAmountInMoneyBox","GetMoney","ScriptReadByte"],
    lineCount: 6,
    bodyC: "u8 x = ScriptReadByte(ctx);\n    u8 y = ScriptReadByte(ctx);\n    u8 ignore = ScriptReadByte(ctx);\n\n    if (!ignore)\n        ChangeAmountInMoneyBox(GetMoney(&gSaveBlock1Ptr->money));\n    return FALSE;",
  },
  "ScrCmd_vbuffermessage": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadWord","StringExpandPlaceholders"],
    lineCount: 3,
    bodyC: "const u8 *ptr = (u8 *)(ScriptReadWord(ctx) - sAddressOffset);\n\n    StringExpandPlaceholders(gStringVar4, ptr);\n    return FALSE;",
  },
  "ScrCmd_vbufferstring": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadWord","StringCopy"],
    lineCount: 6,
    bodyC: "u8 stringVarIndex = ScriptReadByte(ctx);\n    u32 addr = ScriptReadWord(ctx);\n\n    const u8 *src = (u8 *)(addr - sAddressOffset);\n    u8 *dest = sScriptStringVars[stringVarIndex];\n    StringCopy(dest, src);\n    return FALSE;",
  },
  "ScrCmd_vcall": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptCall","ScriptReadWord"],
    lineCount: 3,
    bodyC: "u32 addr = ScriptReadWord(ctx);\n\n    ScriptCall(ctx, (u8 *)(addr - sAddressOffset));\n    return FALSE;",
  },
  "ScrCmd_vcall_if": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptCall","ScriptReadByte","ScriptReadWord"],
    lineCount: 5,
    bodyC: "u8 condition = ScriptReadByte(ctx);\n    const u8 *ptr = (const u8 *)(ScriptReadWord(ctx) - sAddressOffset);\n\n    if (sScriptConditionTable[condition][ctx->comparisonResult] == 1)\n        ScriptCall(ctx, ptr);\n    return FALSE;",
  },
  "ScrCmd_vgoto": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptJump","ScriptReadWord"],
    lineCount: 3,
    bodyC: "u32 addr = ScriptReadWord(ctx);\n\n    ScriptJump(ctx, (u8 *)(addr - sAddressOffset));\n    return FALSE;",
  },
  "ScrCmd_vgoto_if": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptJump","ScriptReadByte","ScriptReadWord"],
    lineCount: 5,
    bodyC: "u8 condition = ScriptReadByte(ctx);\n    const u8 *ptr = (const u8 *)(ScriptReadWord(ctx) - sAddressOffset);\n\n    if (sScriptConditionTable[condition][ctx->comparisonResult] == 1)\n        ScriptJump(ctx, ptr);\n    return FALSE;",
  },
  "ScrCmd_vmessage": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadWord","ShowFieldMessage"],
    lineCount: 3,
    bodyC: "u32 msg = ScriptReadWord(ctx);\n\n    ShowFieldMessage((u8 *)(msg - sAddressOffset));\n    return FALSE;",
  },
  "ScrCmd_waitbuttonpress": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["SetupNativeScript"],
    lineCount: 2,
    bodyC: "SetupNativeScript(ctx, WaitForAorBPress);\n    return TRUE;",
  },
  "ScrCmd_waitdooranim": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["SetupNativeScript"],
    lineCount: 2,
    bodyC: "SetupNativeScript(ctx, IsDoorAnimationStopped);\n    return TRUE;",
  },
  "ScrCmd_waitfanfare": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["SetupNativeScript"],
    lineCount: 2,
    bodyC: "SetupNativeScript(ctx, WaitForFanfareFinish);\n    return TRUE;",
  },
  "ScrCmd_waitfieldeffect": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","SetupNativeScript","VarGet"],
    lineCount: 3,
    bodyC: "sFieldEffectScriptId = VarGet(ScriptReadHalfword(ctx));\n    SetupNativeScript(ctx, WaitForFieldEffectFinish);\n    return TRUE;",
  },
  "ScrCmd_waitmessage": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["SetupNativeScript"],
    lineCount: 2,
    bodyC: "SetupNativeScript(ctx, IsFieldMessageBoxHidden);\n    return TRUE;",
  },
  "ScrCmd_waitmoncry": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["SetupNativeScript"],
    lineCount: 2,
    bodyC: "SetupNativeScript(ctx, IsCryFinished);\n    return TRUE;",
  },
  "ScrCmd_waitmovement": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadHalfword","SetupNativeScript","VarGet"],
    lineCount: 7,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n\n    if (localId != LOCALID_NONE)\n        sMovingNpcId = localId;\n    sMovingNpcMapGroup = gSaveBlock1Ptr->location.mapGroup;\n    sMovingNpcMapNum = gSaveBlock1Ptr->location.mapNum;\n    SetupNativeScript(ctx, WaitForMovementFinish);\n    return TRUE;",
  },
  "ScrCmd_waitmovementat": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptReadByte","ScriptReadHalfword","SetupNativeScript","VarGet"],
    lineCount: 11,
    bodyC: "u16 localId = VarGet(ScriptReadHalfword(ctx));\n    u8 mapGroup;\n    u8 mapNum;\n\n    if (localId != LOCALID_NONE)\n        sMovingNpcId = localId;\n    mapGroup = ScriptReadByte(ctx);\n    mapNum = ScriptReadByte(ctx);\n    sMovingNpcMapGroup = mapGroup;\n    sMovingNpcMapNum = mapNum;\n    SetupNativeScript(ctx, WaitForMovementFinish);\n    return TRUE;",
  },
  "ScrCmd_waitse": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["SetupNativeScript"],
    lineCount: 2,
    bodyC: "SetupNativeScript(ctx, WaitForSoundEffectFinish);\n    return TRUE;",
  },
  "ScrCmd_waitstate": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptContext_Stop"],
    lineCount: 2,
    bodyC: "ScriptContext_Stop();\n    return TRUE;",
  },
  "ScrCmd_warp": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DoWarp","ResetInitialPlayerAvatarState","ScriptReadByte","ScriptReadHalfword","SetWarpDestination","VarGet"],
    lineCount: 9,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetWarpDestination(mapGroup, mapNum, warpId, x, y);\n    DoWarp();\n    ResetInitialPlayerAvatarState();\n    return TRUE;",
  },
  "ScrCmd_warpdoor": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DoDoorWarp","ResetInitialPlayerAvatarState","ScriptReadByte","ScriptReadHalfword","SetWarpDestination","VarGet"],
    lineCount: 9,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetWarpDestination(mapGroup, mapNum, warpId, x, y);\n    DoDoorWarp();\n    ResetInitialPlayerAvatarState();\n    return TRUE;",
  },
  "ScrCmd_warphole": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DoFallWarp","MAP_GROUP","MAP_NUM","PlayerGetDestCoords","ResetInitialPlayerAvatarState","ScriptReadByte","SetWarpDestination","SetWarpDestinationToFixedHoleWarp"],
    lineCount: 12,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u16 x;\n    u16 y;\n\n    PlayerGetDestCoords(&x, &y);\n    if (mapGroup == MAP_GROUP(MAP_UNDEFINED) && mapNum == MAP_NUM(MAP_UNDEFINED))\n        SetWarpDestinationToFixedHoleWarp(x - MAP_OFFSET, y - MAP_OFFSET);\n    else\n        SetWarpDestination(mapGroup, mapNum, WARP_ID_NONE, x - MAP_OFFSET, y - MAP_OFFSET);\n    DoFallWarp();\n    ResetInitialPlayerAvatarState();\n    return TRUE;",
  },
  "ScrCmd_warpmossdeepgym": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DoMossdeepGymWarp","ResetInitialPlayerAvatarState","ScriptReadByte","ScriptReadHalfword","SetWarpDestination","VarGet"],
    lineCount: 9,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetWarpDestination(mapGroup, mapNum, warpId, x, y);\n    DoMossdeepGymWarp();\n    ResetInitialPlayerAvatarState();\n    return TRUE;",
  },
  "ScrCmd_warpsilent": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DoDiveWarp","ResetInitialPlayerAvatarState","ScriptReadByte","ScriptReadHalfword","SetWarpDestination","VarGet"],
    lineCount: 9,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetWarpDestination(mapGroup, mapNum, warpId, x, y);\n    DoDiveWarp();\n    ResetInitialPlayerAvatarState();\n    return TRUE;",
  },
  "ScrCmd_warpspinenter": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DoSpinEnterWarp","GetPlayerFacingDirection","ResetInitialPlayerAvatarState","ScriptReadByte","ScriptReadHalfword","SetSpinStartFacingDir","SetWarpDestination","VarGet"],
    lineCount: 10,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetWarpDestination(mapGroup, mapNum, warpId, x, y);\n    SetSpinStartFacingDir(GetPlayerFacingDirection());\n    DoSpinEnterWarp();\n    ResetInitialPlayerAvatarState();\n    return TRUE;",
  },
  "ScrCmd_warpteleport": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DoTeleportTileWarp","ResetInitialPlayerAvatarState","ScriptReadByte","ScriptReadHalfword","SetWarpDestination","VarGet"],
    lineCount: 9,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetWarpDestination(mapGroup, mapNum, warpId, x, y);\n    DoTeleportTileWarp();\n    ResetInitialPlayerAvatarState();\n    return TRUE;",
  },
  "ScrCmd_warpwhitefade": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["DoWhiteFadeWarp","ResetInitialPlayerAvatarState","ScriptReadByte","ScriptReadHalfword","SetWarpDestination","VarGet"],
    lineCount: 9,
    bodyC: "u8 mapGroup = ScriptReadByte(ctx);\n    u8 mapNum = ScriptReadByte(ctx);\n    u8 warpId = ScriptReadByte(ctx);\n    u16 x = VarGet(ScriptReadHalfword(ctx));\n    u16 y = VarGet(ScriptReadHalfword(ctx));\n\n    SetWarpDestination(mapGroup, mapNum, warpId, x, y);\n    DoWhiteFadeWarp();\n    ResetInitialPlayerAvatarState();\n    return TRUE;",
  },
  "ScrCmd_yesnobox": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptContext_Stop","ScriptMenu_YesNo","ScriptReadByte"],
    lineCount: 11,
    bodyC: "u8 left = ScriptReadByte(ctx);\n    u8 top = ScriptReadByte(ctx);\n\n    if (ScriptMenu_YesNo(left, top) == TRUE)\n    {\n        ScriptContext_Stop();\n        return TRUE;\n    }\n    else\n    {\n        return FALSE;\n    }",
  },
  "SetMovingNpcId": {
    returnType: "void",
    params: "u16 npcId",
    lineCount: 1,
    bodyC: "sMovingNpcId = npcId;",
  },
  "WaitForAorBPress": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["JOY_NEW"],
    lineCount: 5,
    bodyC: "if (JOY_NEW(A_BUTTON))\n        return TRUE;\n    if (JOY_NEW(B_BUTTON))\n        return TRUE;\n    return FALSE;",
  },
  "WaitForFanfareFinish": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["IsFanfareTaskInactive"],
    lineCount: 1,
    bodyC: "return IsFanfareTaskInactive();",
  },
  "WaitForFieldEffectFinish": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["FieldEffectActiveListContains"],
    lineCount: 4,
    bodyC: "if (!FieldEffectActiveListContains(sFieldEffectScriptId))\n        return TRUE;\n    else\n        return FALSE;",
  },
  "WaitForMovementFinish": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["ScriptMovement_IsObjectMovementFinished"],
    lineCount: 1,
    bodyC: "return ScriptMovement_IsObjectMovementFinished(sMovingNpcId, sMovingNpcMapNum, sMovingNpcMapGroup);",
  },
  "WaitForSoundEffectFinish": {
    returnType: "static bool8",
    params: "void",
    callsTo: ["IsSEPlaying"],
    lineCount: 4,
    bodyC: "if (!IsSEPlaying())\n        return TRUE;\n    else\n        return FALSE;",
  },
} as const;
