// AUTO-GENERATED from src/script.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 39

export const ENGINE_FUNCTIONS = {
  "ArePlayerFieldControlsLocked": {
    returnType: "bool8",
    params: "void",
    lineCount: 1,
    bodyC: "return sLockFieldControls;",
  },
  "CalculateRamScriptChecksum": {
    returnType: "u32",
    params: "void",
    callsTo: ["CalcCRC16WithTable"],
    lineCount: 1,
    bodyC: "return CalcCRC16WithTable((u8 *)(&gSaveBlock1Ptr->ramScript.data), sizeof(gSaveBlock1Ptr->ramScript.data));",
  },
  "ClearRamScript": {
    returnType: "void",
    params: "void",
    callsTo: ["CpuFill32"],
    lineCount: 1,
    bodyC: "CpuFill32(0, &gSaveBlock1Ptr->ramScript, sizeof(struct RamScript));",
  },
  "GetRamScript": {
    returnType: "const u8 *",
    params: "u8 localId, const u8 *script",
    callsTo: ["CalculateRamScriptChecksum","ClearRamScript"],
    lineCount: 20,
    bodyC: "struct RamScriptData *scriptData = &gSaveBlock1Ptr->ramScript.data;\n    gRamScriptRetAddr = NULL;\n    if (scriptData->magic != RAM_SCRIPT_MAGIC)\n        return script;\n    if (scriptData->mapGroup != gSaveBlock1Ptr->location.mapGroup)\n        return script;\n    if (scriptData->mapNum != gSaveBlock1Ptr->location.mapNum)\n        return script;\n    if (scriptData->localId != localId)\n        return script;\n    if (CalculateRamScriptChecksum() != gSaveBlock1Ptr->ramScript.checksum)\n    {\n        ClearRamScript();\n        return script;\n    }\n    else\n    {\n        gRamScriptRetAddr = script;\n        return scriptData->script;\n    }",
  },
  "GetSavedRamScriptIfValid": {
    returnType: "u8 *",
    params: "void",
    callsTo: ["CalculateRamScriptChecksum","ClearRamScript","MAP_GROUP","MAP_NUM","ValidateSavedWonderCard"],
    lineCount: 20,
    bodyC: "struct RamScriptData *scriptData = &gSaveBlock1Ptr->ramScript.data;\n    if (!ValidateSavedWonderCard())\n        return NULL;\n    if (scriptData->magic != RAM_SCRIPT_MAGIC)\n        return NULL;\n    if (scriptData->mapGroup != MAP_GROUP(MAP_UNDEFINED))\n        return NULL;\n    if (scriptData->mapNum != MAP_NUM(MAP_UNDEFINED))\n        return NULL;\n    if (scriptData->localId != NO_OBJECT)\n        return NULL;\n    if (CalculateRamScriptChecksum() != gSaveBlock1Ptr->ramScript.checksum)\n    {\n        ClearRamScript();\n        return NULL;\n    }\n    else\n    {\n        return scriptData->script;\n    }",
  },
  "InitRamScript": {
    returnType: "bool8",
    params: "const u8 *script, u16 scriptSize, u8 mapGroup, u8 mapNum, u8 localId",
    callsTo: ["CalculateRamScriptChecksum","ClearRamScript","memcpy"],
    lineCount: 11,
    bodyC: "struct RamScriptData *scriptData = &gSaveBlock1Ptr->ramScript.data;\n\n    ClearRamScript();\n\n    if (scriptSize > sizeof(scriptData->script))\n        return FALSE;\n\n    scriptData->magic = RAM_SCRIPT_MAGIC;\n    scriptData->mapGroup = mapGroup;\n    scriptData->mapNum = mapNum;\n    scriptData->localId = localId;\n    memcpy(scriptData->script, script, scriptSize);\n    gSaveBlock1Ptr->ramScript.checksum = CalculateRamScriptChecksum();\n    return TRUE;",
  },
  "InitRamScript_NoObjectEvent": {
    returnType: "void",
    params: "u8 *script, u16 scriptSize",
    callsTo: ["InitRamScript","MAP_GROUP","MAP_NUM"],
    lineCount: 3,
    bodyC: "if (scriptSize > sizeof(gSaveBlock1Ptr->ramScript.data.script))\n        scriptSize = sizeof(gSaveBlock1Ptr->ramScript.data.script);\n    InitRamScript(script, scriptSize, MAP_GROUP(MAP_UNDEFINED), MAP_NUM(MAP_UNDEFINED), NO_OBJECT);",
  },
  "InitScriptContext": {
    returnType: "void",
    params: "struct ScriptContext *ctx, void *cmdTable, void *cmdTableEnd",
    callsTo: ["ARRAY_COUNT"],
    lineCount: 11,
    bodyC: "s32 i;\n\n    ctx->mode = SCRIPT_MODE_STOPPED;\n    ctx->scriptPtr = NULL;\n    ctx->stackDepth = 0;\n    ctx->nativePtr = NULL;\n    ctx->cmdTable = cmdTable;\n    ctx->cmdTableEnd = cmdTableEnd;\n\n    for (i = 0; i < (int)ARRAY_COUNT(ctx->data); i++)\n        ctx->data[i] = 0;\n\n    for (i = 0; i < (int)ARRAY_COUNT(ctx->stack); i++)\n        ctx->stack[i] = NULL;",
  },
  "LockPlayerFieldControls": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "sLockFieldControls = TRUE;",
  },
  "MapHeaderCheckScriptTable": {
    returnType: "u8 *",
    params: "u8 tag",
    callsTo: ["MapHeaderGetScriptTable","T1_READ_16","T2_READ_PTR","VarGet"],
    lineCount: 17,
    bodyC: "u8 *ptr = MapHeaderGetScriptTable(tag);\n\n    if (!ptr)\n        return NULL;\n\n    while (1)\n    {\n        u16 varIndex1;\n        u16 varIndex2;\n\n         \n        varIndex1 = T1_READ_16(ptr);\n        if (!varIndex1)\n            return NULL;  \n        ptr += 2;\n\n         \n        varIndex2 = T1_READ_16(ptr);\n        ptr += 2;\n\n         \n        if (VarGet(varIndex1) == VarGet(varIndex2))\n            return T2_READ_PTR(ptr);\n        ptr += 4;\n    }",
  },
  "MapHeaderGetScriptTable": {
    returnType: "u8 *",
    params: "u8 tag",
    callsTo: ["T2_READ_PTR"],
    lineCount: 14,
    bodyC: "const u8 *mapScripts = gMapHeader.mapScripts;\n\n    if (!mapScripts)\n        return NULL;\n\n    while (1)\n    {\n        if (!*mapScripts)\n            return NULL;\n        if (*mapScripts == tag)\n        {\n            mapScripts++;\n            return T2_READ_PTR(mapScripts);\n        }\n        mapScripts += 5;\n    }",
  },
  "MapHeaderRunScriptType": {
    returnType: "void",
    params: "u8 tag",
    callsTo: ["MapHeaderGetScriptTable","RunScriptImmediately"],
    lineCount: 3,
    bodyC: "u8 *ptr = MapHeaderGetScriptTable(tag);\n    if (ptr)\n        RunScriptImmediately(ptr);",
  },
  "RunOnDiveWarpMapScript": {
    returnType: "void",
    params: "void",
    callsTo: ["MapHeaderRunScriptType"],
    lineCount: 1,
    bodyC: "MapHeaderRunScriptType(MAP_SCRIPT_ON_DIVE_WARP);",
  },
  "RunOnLoadMapScript": {
    returnType: "void",
    params: "void",
    callsTo: ["MapHeaderRunScriptType"],
    lineCount: 1,
    bodyC: "MapHeaderRunScriptType(MAP_SCRIPT_ON_LOAD);",
  },
  "RunOnResumeMapScript": {
    returnType: "void",
    params: "void",
    callsTo: ["MapHeaderRunScriptType"],
    lineCount: 1,
    bodyC: "MapHeaderRunScriptType(MAP_SCRIPT_ON_RESUME);",
  },
  "RunOnReturnToFieldMapScript": {
    returnType: "void",
    params: "void",
    callsTo: ["MapHeaderRunScriptType"],
    lineCount: 1,
    bodyC: "MapHeaderRunScriptType(MAP_SCRIPT_ON_RETURN_TO_FIELD);",
  },
  "RunOnTransitionMapScript": {
    returnType: "void",
    params: "void",
    callsTo: ["MapHeaderRunScriptType"],
    lineCount: 1,
    bodyC: "MapHeaderRunScriptType(MAP_SCRIPT_ON_TRANSITION);",
  },
  "RunScriptCommand": {
    returnType: "bool8",
    params: "struct ScriptContext *ctx",
    callsTo: ["asm","nativePtr"],
    lineCount: 42,
    bodyC: "if (ctx->mode == SCRIPT_MODE_STOPPED)\n        return FALSE;\n\n    switch (ctx->mode)\n    {\n    case SCRIPT_MODE_STOPPED:\n        return FALSE;\n    case SCRIPT_MODE_NATIVE:\n         \n         \n        if (ctx->nativePtr)\n        {\n            if (ctx->nativePtr() == TRUE)\n                ctx->mode = SCRIPT_MODE_BYTECODE;\n            return TRUE;\n        }\n        ctx->mode = SCRIPT_MODE_BYTECODE;\n         \n    case SCRIPT_MODE_BYTECODE:\n        while (1)\n        {\n            u8 cmdCode;\n            ScrCmdFunc *func;\n\n            if (!ctx->scriptPtr)\n            {\n                ctx->mode = SCRIPT_MODE_STOPPED;\n                return FALSE;\n            }\n\n            if (ctx->scriptPtr == gNullScriptPtr)\n            {\n                while (1)\n                    asm(\"svc 2\");  \n            }\n\n            cmdCode = *(ctx->scriptPtr);\n            ctx->scriptPtr++;\n            func = &ctx->cmdTable[cmdCode];\n\n            if (func >= ctx->cmdTableEnd)\n            {\n                ctx->mode = SCRIPT_MODE_STOPPED;\n                return FALSE;\n            }\n\n            if ((*func)(ctx) == TRUE)\n                return TRUE;\n        }\n    }\n\n    return TRUE;",
  },
  "RunScriptImmediately": {
    returnType: "void",
    params: "const u8 *ptr",
    callsTo: ["InitScriptContext","RunScriptCommand","SetupBytecodeScript"],
    lineCount: 3,
    bodyC: "InitScriptContext(&sImmediateScriptContext, gScriptCmdTable, gScriptCmdTableEnd);\n    SetupBytecodeScript(&sImmediateScriptContext, ptr);\n    while (RunScriptCommand(&sImmediateScriptContext) == TRUE);",
  },
  "ScriptCall": {
    returnType: "void",
    params: "struct ScriptContext *ctx, const u8 *ptr",
    callsTo: ["ScriptPush"],
    lineCount: 2,
    bodyC: "ScriptPush(ctx, ctx->scriptPtr);\n    ctx->scriptPtr = ptr;",
  },
  "ScriptContext_Enable": {
    returnType: "void",
    params: "void",
    callsTo: ["LockPlayerFieldControls"],
    lineCount: 2,
    bodyC: "sGlobalScriptContextStatus = CONTEXT_RUNNING;\n    LockPlayerFieldControls();",
  },
  "ScriptContext_Init": {
    returnType: "void",
    params: "void",
    callsTo: ["InitScriptContext"],
    lineCount: 2,
    bodyC: "InitScriptContext(&sGlobalScriptContext, gScriptCmdTable, gScriptCmdTableEnd);\n    sGlobalScriptContextStatus = CONTEXT_SHUTDOWN;",
  },
  "ScriptContext_IsEnabled": {
    returnType: "bool8",
    params: "void",
    lineCount: 4,
    bodyC: "if (sGlobalScriptContextStatus == CONTEXT_RUNNING)\n        return TRUE;\n    else\n        return FALSE;",
  },
  "ScriptContext_RunScript": {
    returnType: "bool8",
    params: "void",
    callsTo: ["LockPlayerFieldControls","RunScriptCommand","UnlockPlayerFieldControls"],
    lineCount: 12,
    bodyC: "if (sGlobalScriptContextStatus == CONTEXT_SHUTDOWN)\n        return FALSE;\n\n    if (sGlobalScriptContextStatus == CONTEXT_WAITING)\n        return FALSE;\n\n    LockPlayerFieldControls();\n\n    if (!RunScriptCommand(&sGlobalScriptContext))\n    {\n        sGlobalScriptContextStatus = CONTEXT_SHUTDOWN;\n        UnlockPlayerFieldControls();\n        return FALSE;\n    }\n\n    return TRUE;",
  },
  "ScriptContext_SetupScript": {
    returnType: "void",
    params: "const u8 *ptr",
    callsTo: ["InitScriptContext","LockPlayerFieldControls","SetupBytecodeScript"],
    lineCount: 4,
    bodyC: "InitScriptContext(&sGlobalScriptContext, gScriptCmdTable, gScriptCmdTableEnd);\n    SetupBytecodeScript(&sGlobalScriptContext, ptr);\n    LockPlayerFieldControls();\n    sGlobalScriptContextStatus = CONTEXT_RUNNING;",
  },
  "ScriptContext_Stop": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "sGlobalScriptContextStatus = CONTEXT_WAITING;",
  },
  "ScriptJump": {
    returnType: "void",
    params: "struct ScriptContext *ctx, const u8 *ptr",
    lineCount: 1,
    bodyC: "ctx->scriptPtr = ptr;",
  },
  "ScriptPop": {
    returnType: "static const u8 *",
    params: "struct ScriptContext *ctx",
    lineCount: 4,
    bodyC: "if (ctx->stackDepth == 0)\n        return NULL;\n\n    ctx->stackDepth--;\n    return ctx->stack[ctx->stackDepth];",
  },
  "ScriptPush": {
    returnType: "static bool8",
    params: "struct ScriptContext *ctx, const u8 *ptr",
    callsTo: ["ARRAY_COUNT"],
    lineCount: 10,
    bodyC: "if (ctx->stackDepth + 1 >= (int)ARRAY_COUNT(ctx->stack))\n    {\n        return TRUE;\n    }\n    else\n    {\n        ctx->stack[ctx->stackDepth] = ptr;\n        ctx->stackDepth++;\n        return FALSE;\n    }",
  },
  "ScriptReadHalfword": {
    returnType: "u16",
    params: "struct ScriptContext *ctx",
    lineCount: 3,
    bodyC: "u16 value = *(ctx->scriptPtr++);\n    value |= *(ctx->scriptPtr++) << 8;\n    return value;",
  },
  "ScriptReadWord": {
    returnType: "u32",
    params: "struct ScriptContext *ctx",
    lineCount: 5,
    bodyC: "u32 value0 = *(ctx->scriptPtr++);\n    u32 value1 = *(ctx->scriptPtr++);\n    u32 value2 = *(ctx->scriptPtr++);\n    u32 value3 = *(ctx->scriptPtr++);\n    return (((((value3 << 8) + value2) << 8) + value1) << 8) + value0;",
  },
  "ScriptReturn": {
    returnType: "void",
    params: "struct ScriptContext *ctx",
    callsTo: ["ScriptPop"],
    lineCount: 1,
    bodyC: "ctx->scriptPtr = ScriptPop(ctx);",
  },
  "SetupBytecodeScript": {
    returnType: "u8",
    params: "struct ScriptContext *ctx, const u8 *ptr",
    lineCount: 3,
    bodyC: "ctx->scriptPtr = ptr;\n    ctx->mode = SCRIPT_MODE_BYTECODE;\n    return 1;",
  },
  "SetupNativeScript": {
    returnType: "void",
    params: "struct ScriptContext *ctx, bool8 (*ptr)(void)",
    lineCount: 2,
    bodyC: "ctx->mode = SCRIPT_MODE_NATIVE;\n    ctx->nativePtr = ptr;",
  },
  "StopScript": {
    returnType: "void",
    params: "struct ScriptContext *ctx",
    lineCount: 2,
    bodyC: "ctx->mode = SCRIPT_MODE_STOPPED;\n    ctx->scriptPtr = NULL;",
  },
  "TryRunOnFrameMapScript": {
    returnType: "bool8",
    params: "void",
    callsTo: ["MapHeaderCheckScriptTable","ScriptContext_SetupScript"],
    lineCount: 5,
    bodyC: "u8 *ptr = MapHeaderCheckScriptTable(MAP_SCRIPT_ON_FRAME_TABLE);\n\n    if (!ptr)\n        return FALSE;\n\n    ScriptContext_SetupScript(ptr);\n    return TRUE;",
  },
  "TryRunOnWarpIntoMapScript": {
    returnType: "void",
    params: "void",
    callsTo: ["MapHeaderCheckScriptTable","RunScriptImmediately"],
    lineCount: 3,
    bodyC: "u8 *ptr = MapHeaderCheckScriptTable(MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE);\n    if (ptr)\n        RunScriptImmediately(ptr);",
  },
  "UnlockPlayerFieldControls": {
    returnType: "void",
    params: "void",
    lineCount: 1,
    bodyC: "sLockFieldControls = FALSE;",
  },
  "ValidateSavedRamScript": {
    returnType: "bool32",
    params: "void",
    callsTo: ["CalculateRamScriptChecksum","MAP_GROUP","MAP_NUM"],
    lineCount: 12,
    bodyC: "struct RamScriptData *scriptData = &gSaveBlock1Ptr->ramScript.data;\n    if (scriptData->magic != RAM_SCRIPT_MAGIC)\n        return FALSE;\n    if (scriptData->mapGroup != MAP_GROUP(MAP_UNDEFINED))\n        return FALSE;\n    if (scriptData->mapNum != MAP_NUM(MAP_UNDEFINED))\n        return FALSE;\n    if (scriptData->localId != NO_OBJECT)\n        return FALSE;\n    if (CalculateRamScriptChecksum() != gSaveBlock1Ptr->ramScript.checksum)\n        return FALSE;\n    return TRUE;",
  },
} as const;
