// AUTO-GENERATED from src/sound.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 46

export const ENGINE_FUNCTIONS = {
  "CreateFanfareTask": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateTask","FuncIsActiveTask"],
    lineCount: 2,
    bodyC: "if (FuncIsActiveTask(Task_Fanfare) != TRUE)\n        CreateTask(Task_Fanfare, 80);",
  },
  "FadeInBGM": {
    returnType: "void",
    params: "u8 speed",
    callsTo: ["m4aMPlayFadeIn"],
    lineCount: 1,
    bodyC: "m4aMPlayFadeIn(&gMPlayInfo_BGM, speed);",
  },
  "FadeInNewBGM": {
    returnType: "void",
    params: "u16 songNum, u8 speed",
    callsTo: ["m4aMPlayFadeIn","m4aMPlayImmInit","m4aMPlayVolumeControl","m4aSongNumStart","m4aSongNumStop"],
    lineCount: 9,
    bodyC: "if (gDisableMusic)\n        songNum = 0;\n    if (songNum == MUS_NONE)\n        songNum = 0;\n    m4aSongNumStart(songNum);\n    m4aMPlayImmInit(&gMPlayInfo_BGM);\n    m4aMPlayVolumeControl(&gMPlayInfo_BGM, TRACKS_ALL, 0);\n    m4aSongNumStop(songNum);\n    m4aMPlayFadeIn(&gMPlayInfo_BGM, speed);",
  },
  "FadeOutAndFadeInNewMapMusic": {
    returnType: "void",
    params: "u16 songNum, u8 fadeOutSpeed, u8 fadeInSpeed",
    callsTo: ["FadeOutMapMusic"],
    lineCount: 5,
    bodyC: "FadeOutMapMusic(fadeOutSpeed);\n    sCurrentMapMusic = 0;\n    sNextMapMusic = songNum;\n    sMapMusicState = 7;\n    sMapMusicFadeInSpeed = fadeInSpeed;",
  },
  "FadeOutAndPlayNewMapMusic": {
    returnType: "void",
    params: "u16 songNum, u8 speed",
    callsTo: ["FadeOutMapMusic"],
    lineCount: 4,
    bodyC: "FadeOutMapMusic(speed);\n    sCurrentMapMusic = 0;\n    sNextMapMusic = songNum;\n    sMapMusicState = 6;",
  },
  "FadeOutBGM": {
    returnType: "void",
    params: "u8 speed",
    callsTo: ["m4aMPlayFadeOut"],
    lineCount: 1,
    bodyC: "m4aMPlayFadeOut(&gMPlayInfo_BGM, speed);",
  },
  "FadeOutBGMTemporarily": {
    returnType: "void",
    params: "u8 speed",
    callsTo: ["m4aMPlayFadeOutTemporarily"],
    lineCount: 1,
    bodyC: "m4aMPlayFadeOutTemporarily(&gMPlayInfo_BGM, speed);",
  },
  "FadeOutMapMusic": {
    returnType: "void",
    params: "u8 speed",
    callsTo: ["FadeOutBGM","IsNotWaitingForBGMStop"],
    lineCount: 5,
    bodyC: "if (IsNotWaitingForBGMStop())\n        FadeOutBGM(speed);\n    sCurrentMapMusic = 0;\n    sNextMapMusic = 0;\n    sMapMusicState = 5;",
  },
  "GetCurrentMapMusic": {
    returnType: "u16",
    params: "void",
    lineCount: 1,
    bodyC: "return sCurrentMapMusic;",
  },
  "InitMapMusic": {
    returnType: "void",
    params: "void",
    callsTo: ["ResetMapMusic"],
    lineCount: 2,
    bodyC: "gDisableMusic = FALSE;\n    ResetMapMusic();",
  },
  "IsBGMPausedOrStopped": {
    returnType: "bool8",
    params: "void",
    lineCount: 5,
    bodyC: "if (gMPlayInfo_BGM.status & MUSICPLAYER_STATUS_PAUSE)\n        return TRUE;\n    if (!(gMPlayInfo_BGM.status & MUSICPLAYER_STATUS_TRACK))\n        return TRUE;\n    return FALSE;",
  },
  "IsBGMPlaying": {
    returnType: "bool8",
    params: "void",
    lineCount: 5,
    bodyC: "if (gMPlayInfo_BGM.status & MUSICPLAYER_STATUS_PAUSE)\n        return FALSE;\n    if (!(gMPlayInfo_BGM.status & MUSICPLAYER_STATUS_TRACK))\n        return FALSE;\n    return TRUE;",
  },
  "IsBGMStopped": {
    returnType: "bool8",
    params: "void",
    lineCount: 3,
    bodyC: "if (!(gMPlayInfo_BGM.status & MUSICPLAYER_STATUS_TRACK))\n        return TRUE;\n    return FALSE;",
  },
  "IsCryFinished": {
    returnType: "bool8",
    params: "void",
    callsTo: ["ClearPokemonCrySongs","FuncIsActiveTask"],
    lineCount: 9,
    bodyC: "if (FuncIsActiveTask(Task_DuckBGMForPokemonCry) == TRUE)\n    {\n        return FALSE;\n    }\n    else\n    {\n        ClearPokemonCrySongs();\n        return TRUE;\n    }",
  },
  "IsCryPlaying": {
    returnType: "bool8",
    params: "void",
    callsTo: ["IsPokemonCryPlaying"],
    lineCount: 4,
    bodyC: "if (IsPokemonCryPlaying(gMPlay_PokemonCry))\n        return TRUE;\n    else\n        return FALSE;",
  },
  "IsCryPlayingOrClearCrySongs": {
    returnType: "bool8",
    params: "void",
    callsTo: ["ClearPokemonCrySongs","IsPokemonCryPlaying"],
    lineCount: 9,
    bodyC: "if (IsPokemonCryPlaying(gMPlay_PokemonCry))\n    {\n        return TRUE;\n    }\n    else\n    {\n        ClearPokemonCrySongs();\n        return FALSE;\n    }",
  },
  "IsFanfareTaskInactive": {
    returnType: "bool8",
    params: "void",
    callsTo: ["FuncIsActiveTask"],
    lineCount: 3,
    bodyC: "if (FuncIsActiveTask(Task_Fanfare) == TRUE)\n        return FALSE;\n    return TRUE;",
  },
  "IsNotWaitingForBGMStop": {
    returnType: "bool8",
    params: "void",
    lineCount: 7,
    bodyC: "if (sMapMusicState == 6)\n        return FALSE;\n    if (sMapMusicState == 5)\n        return FALSE;\n    if (sMapMusicState == 7)\n        return FALSE;\n    return TRUE;",
  },
  "IsSEPlaying": {
    returnType: "bool8",
    params: "void",
    lineCount: 5,
    bodyC: "if ((gMPlayInfo_SE1.status & MUSICPLAYER_STATUS_PAUSE) && (gMPlayInfo_SE2.status & MUSICPLAYER_STATUS_PAUSE))\n        return FALSE;\n    if (!(gMPlayInfo_SE1.status & MUSICPLAYER_STATUS_TRACK) && !(gMPlayInfo_SE2.status & MUSICPLAYER_STATUS_TRACK))\n        return FALSE;\n    return TRUE;",
  },
  "IsSpecialSEPlaying": {
    returnType: "bool8",
    params: "void",
    lineCount: 5,
    bodyC: "if (gMPlayInfo_SE3.status & MUSICPLAYER_STATUS_PAUSE)\n        return FALSE;\n    if (!(gMPlayInfo_SE3.status & MUSICPLAYER_STATUS_TRACK))\n        return FALSE;\n    return TRUE;",
  },
  "MapMusicMain": {
    returnType: "void",
    params: "void",
    callsTo: ["FadeInNewBGM","IsBGMStopped","IsFanfareTaskInactive","PlayBGM"],
    lineCount: 39,
    bodyC: "switch (sMapMusicState)\n    {\n    case 0:\n        break;\n    case 1:\n        sMapMusicState = 2;\n        PlayBGM(sCurrentMapMusic);\n        break;\n    case 2:\n    case 3:\n    case 4:\n        break;\n    case 5:\n        if (IsBGMStopped())\n        {\n            sNextMapMusic = 0;\n            sMapMusicState = 0;\n        }\n        break;\n    case 6:\n        if (IsBGMStopped() && IsFanfareTaskInactive())\n        {\n            sCurrentMapMusic = sNextMapMusic;\n            sNextMapMusic = 0;\n            sMapMusicState = 2;\n            PlayBGM(sCurrentMapMusic);\n        }\n        break;\n    case 7:\n        if (IsBGMStopped() && IsFanfareTaskInactive())\n        {\n            FadeInNewBGM(sNextMapMusic, sMapMusicFadeInSpeed);\n            sCurrentMapMusic = sNextMapMusic;\n            sNextMapMusic = 0;\n            sMapMusicState = 2;\n            sMapMusicFadeInSpeed = 0;\n        }\n        break;\n    }",
  },
  "PlayBGM": {
    returnType: "void",
    params: "u16 songNum",
    callsTo: ["m4aSongNumStart"],
    lineCount: 5,
    bodyC: "if (gDisableMusic)\n        songNum = 0;\n    if (songNum == MUS_NONE)\n        songNum = 0;\n    m4aSongNumStart(songNum);",
  },
  "PlayCryInternal": {
    returnType: "void",
    params: "u16 species, s8 pan, s8 volume, u8 priority, u8 mode",
    callsTo: ["GET_CRY","SetPokemonCryChorus","SetPokemonCryLength","SetPokemonCryPanpot","SetPokemonCryPitch","SetPokemonCryPriority","SetPokemonCryProgress","SetPokemonCryRelease","SetPokemonCryTone","SetPokemonCryVolume","SpeciesToCryId"],
    lineCount: 109,
    bodyC: "bool32 reverse;\n    u32 release;\n    u32 length;\n    u32 pitch;\n    u32 chorus;\n    u32 index;\n    u8 table;\n\n    species--;\n\n     \n     \n    length = 140;\n    reverse = FALSE;\n    release = 0;\n    pitch = 15360;\n    chorus = 0;\n\n    switch (mode)\n    {\n    case CRY_MODE_NORMAL:\n        break;\n    case CRY_MODE_DOUBLES:\n        length = 20;\n        release = 225;\n        break;\n    case CRY_MODE_ENCOUNTER:\n        release = 225;\n        pitch = 15600;\n        chorus = 20;\n        volume = 90;\n        break;\n    case CRY_MODE_HIGH_PITCH:\n        length = 50;\n        release = 200;\n        pitch = 15800;\n        chorus = 20;\n        volume = 90;\n        break;\n    case CRY_MODE_ECHO_START:\n        length = 25;\n        reverse = TRUE;\n        release = 100;\n        pitch = 15600;\n        chorus = 192;\n        volume = 90;\n        break;\n    case CRY_MODE_FAINT:\n        release = 200;\n        pitch = 14440;\n        break;\n    case CRY_MODE_ECHO_END:\n        release = 220;\n        pitch = 15555;\n        chorus = 192;\n        volume = 70;\n        break;\n    case CRY_MODE_ROAR_1:\n        length = 10;\n        release = 100;\n        pitch = 14848;\n        break;\n    case CRY_MODE_ROAR_2:\n        length = 60;\n        release = 225;\n        pitch = 15616;\n        break;\n    case CRY_MODE_GROWL_1:\n        length = 15;\n        reverse = TRUE;\n        release = 125;\n        pitch = 15200;\n        break;\n    case CRY_MODE_GROWL_2:\n        length = 100;\n        release = 225;\n        pitch = 15200;\n        break;\n    case CRY_MODE_WEAK_DOUBLES:\n        length = 20;\n        release = 225;\n         \n    case CRY_MODE_WEAK:\n        pitch = 15000;\n        break;\n    }\n\n    SetPokemonCryVolume(volume);\n    SetPokemonCryPanpot(pan);\n    SetPokemonCryPitch(pitch);\n    SetPokemonCryLength(length);\n    SetPokemonCryProgress(0);\n    SetPokemonCryRelease(release);\n    SetPokemonCryChorus(chorus);\n    SetPokemonCryPriority(priority);\n\n     \n     \n     \n     \n    species = SpeciesToCryId(species);\n    index = species % 128;\n    table = species / 128;\n\n    #define GET_CRY(speciesIndex, tableId, reversed) \\\n        ((reversed) ? &gCryTable_Reverse[(128 * (tableId)) + (speciesIndex)] : &gCryTable[(128 * (tableId)) + (speciesIndex)])\n\n    switch (table)\n    {\n    case 0:\n        gMPlay_PokemonCry = SetPokemonCryTone(GET_CRY(index, 0, reverse));\n        break;\n    case 1:\n        gMPlay_PokemonCry = SetPokemonCryTone(GET_CRY(index, 1, reverse));\n        break;\n    case 2:\n        gMPlay_PokemonCry = SetPokemonCryTone(GET_CRY(index, 2, reverse));\n        break;\n    case 3:\n        gMPlay_PokemonCry = SetPokemonCryTone(GET_CRY(index, 3, reverse));\n        break;\n    }\n\n    #undef GET_CRY",
  },
  "PlayCry_ByMode": {
    returnType: "void",
    params: "u16 species, s8 pan, u8 mode",
    callsTo: ["PlayCryInternal","RestoreBGMVolumeAfterPokemonCry","m4aMPlayVolumeControl"],
    lineCount: 11,
    bodyC: "if (mode == CRY_MODE_DOUBLES)\n    {\n        PlayCryInternal(species, pan, CRY_VOLUME, CRY_PRIORITY_NORMAL, mode);\n    }\n    else\n    {\n        m4aMPlayVolumeControl(&gMPlayInfo_BGM, TRACKS_ALL, 85);\n        PlayCryInternal(species, pan, CRY_VOLUME, CRY_PRIORITY_NORMAL, mode);\n        gPokemonCryBGMDuckingCounter = 2;\n        RestoreBGMVolumeAfterPokemonCry();\n    }",
  },
  "PlayCry_DuckNoRestore": {
    returnType: "void",
    params: "u16 species, s8 pan, u8 mode",
    callsTo: ["PlayCryInternal","m4aMPlayVolumeControl"],
    lineCount: 10,
    bodyC: "if (mode == CRY_MODE_DOUBLES)\n    {\n        PlayCryInternal(species, pan, CRY_VOLUME, CRY_PRIORITY_NORMAL, mode);\n    }\n    else\n    {\n        m4aMPlayVolumeControl(&gMPlayInfo_BGM, TRACKS_ALL, 85);\n        PlayCryInternal(species, pan, CRY_VOLUME, CRY_PRIORITY_NORMAL, mode);\n        gPokemonCryBGMDuckingCounter = 2;\n    }",
  },
  "PlayCry_Normal": {
    returnType: "void",
    params: "u16 species, s8 pan",
    callsTo: ["PlayCryInternal","RestoreBGMVolumeAfterPokemonCry","m4aMPlayVolumeControl"],
    lineCount: 4,
    bodyC: "m4aMPlayVolumeControl(&gMPlayInfo_BGM, TRACKS_ALL, 85);\n    PlayCryInternal(species, pan, CRY_VOLUME, CRY_PRIORITY_NORMAL, CRY_MODE_NORMAL);\n    gPokemonCryBGMDuckingCounter = 2;\n    RestoreBGMVolumeAfterPokemonCry();",
  },
  "PlayCry_NormalNoDucking": {
    returnType: "void",
    params: "u16 species, s8 pan, s8 volume, u8 priority",
    callsTo: ["PlayCryInternal"],
    lineCount: 1,
    bodyC: "PlayCryInternal(species, pan, volume, priority, CRY_MODE_NORMAL);",
  },
  "PlayCry_ReleaseDouble": {
    returnType: "void",
    params: "u16 species, s8 pan, u8 mode",
    callsTo: ["PlayCryInternal","m4aMPlayVolumeControl"],
    lineCount: 10,
    bodyC: "if (mode == CRY_MODE_DOUBLES)\n    {\n        PlayCryInternal(species, pan, CRY_VOLUME, CRY_PRIORITY_NORMAL, mode);\n    }\n    else\n    {\n        if (!(gBattleTypeFlags & BATTLE_TYPE_MULTI))\n            m4aMPlayVolumeControl(&gMPlayInfo_BGM, TRACKS_ALL, 85);\n        PlayCryInternal(species, pan, CRY_VOLUME, CRY_PRIORITY_NORMAL, mode);\n    }",
  },
  "PlayCry_Script": {
    returnType: "void",
    params: "u16 species, u8 mode",
    callsTo: ["PlayCryInternal","RestoreBGMVolumeAfterPokemonCry","m4aMPlayVolumeControl"],
    lineCount: 4,
    bodyC: "m4aMPlayVolumeControl(&gMPlayInfo_BGM, TRACKS_ALL, 85);\n    PlayCryInternal(species, 0, CRY_VOLUME, CRY_PRIORITY_NORMAL, mode);\n    gPokemonCryBGMDuckingCounter = 2;\n    RestoreBGMVolumeAfterPokemonCry();",
  },
  "PlayFanfare": {
    returnType: "void",
    params: "u16 songNum",
    callsTo: ["ARRAY_COUNT","CreateFanfareTask","PlayFanfareByFanfareNum"],
    lineCount: 12,
    bodyC: "s32 i;\n    for (i = 0; (u32)i < ARRAY_COUNT(sFanfares); i++)\n    {\n        if (sFanfares[i].songNum == songNum)\n        {\n            PlayFanfareByFanfareNum(i);\n            CreateFanfareTask();\n            return;\n        }\n    }\n\n     \n     \n    PlayFanfareByFanfareNum(0);\n    CreateFanfareTask();",
  },
  "PlayFanfareByFanfareNum": {
    returnType: "void",
    params: "u8 fanfareNum",
    callsTo: ["m4aMPlayStop","m4aSongNumStart"],
    lineCount: 5,
    bodyC: "u16 songNum;\n    m4aMPlayStop(&gMPlayInfo_BGM);\n    songNum = sFanfares[fanfareNum].songNum;\n    sFanfareCounter = sFanfares[fanfareNum].duration;\n    m4aSongNumStart(songNum);",
  },
  "PlayNewMapMusic": {
    returnType: "void",
    params: "u16 songNum",
    lineCount: 3,
    bodyC: "sCurrentMapMusic = songNum;\n    sNextMapMusic = 0;\n    sMapMusicState = 1;",
  },
  "PlaySE": {
    returnType: "void",
    params: "u16 songNum",
    callsTo: ["m4aSongNumStart"],
    lineCount: 1,
    bodyC: "m4aSongNumStart(songNum);",
  },
  "PlaySE12WithPanning": {
    returnType: "void",
    params: "u16 songNum, s8 pan",
    callsTo: ["m4aMPlayImmInit","m4aMPlayPanpotControl","m4aSongNumStart"],
    lineCount: 5,
    bodyC: "m4aSongNumStart(songNum);\n    m4aMPlayImmInit(&gMPlayInfo_SE1);\n    m4aMPlayImmInit(&gMPlayInfo_SE2);\n    m4aMPlayPanpotControl(&gMPlayInfo_SE1, TRACKS_ALL, pan);\n    m4aMPlayPanpotControl(&gMPlayInfo_SE2, TRACKS_ALL, pan);",
  },
  "PlaySE1WithPanning": {
    returnType: "void",
    params: "u16 songNum, s8 pan",
    callsTo: ["m4aMPlayImmInit","m4aMPlayPanpotControl","m4aSongNumStart"],
    lineCount: 3,
    bodyC: "m4aSongNumStart(songNum);\n    m4aMPlayImmInit(&gMPlayInfo_SE1);\n    m4aMPlayPanpotControl(&gMPlayInfo_SE1, TRACKS_ALL, pan);",
  },
  "PlaySE2WithPanning": {
    returnType: "void",
    params: "u16 songNum, s8 pan",
    callsTo: ["m4aMPlayImmInit","m4aMPlayPanpotControl","m4aSongNumStart"],
    lineCount: 3,
    bodyC: "m4aSongNumStart(songNum);\n    m4aMPlayImmInit(&gMPlayInfo_SE2);\n    m4aMPlayPanpotControl(&gMPlayInfo_SE2, TRACKS_ALL, pan);",
  },
  "ResetMapMusic": {
    returnType: "void",
    params: "void",
    lineCount: 4,
    bodyC: "sCurrentMapMusic = 0;\n    sNextMapMusic = 0;\n    sMapMusicState = 0;\n    sMapMusicFadeInSpeed = 0;",
  },
  "RestoreBGMVolumeAfterPokemonCry": {
    returnType: "static void",
    params: "void",
    callsTo: ["CreateTask","FuncIsActiveTask"],
    lineCount: 2,
    bodyC: "if (FuncIsActiveTask(Task_DuckBGMForPokemonCry) != TRUE)\n        CreateTask(Task_DuckBGMForPokemonCry, 80);",
  },
  "SE12PanpotControl": {
    returnType: "void",
    params: "s8 pan",
    callsTo: ["m4aMPlayPanpotControl"],
    lineCount: 2,
    bodyC: "m4aMPlayPanpotControl(&gMPlayInfo_SE1, TRACKS_ALL, pan);\n    m4aMPlayPanpotControl(&gMPlayInfo_SE2, TRACKS_ALL, pan);",
  },
  "StopCry": {
    returnType: "void",
    params: "void",
    callsTo: ["m4aMPlayStop"],
    lineCount: 1,
    bodyC: "m4aMPlayStop(gMPlay_PokemonCry);",
  },
  "StopCryAndClearCrySongs": {
    returnType: "void",
    params: "void",
    callsTo: ["ClearPokemonCrySongs","m4aMPlayStop"],
    lineCount: 2,
    bodyC: "m4aMPlayStop(gMPlay_PokemonCry);\n    ClearPokemonCrySongs();",
  },
  "StopFanfareByFanfareNum": {
    returnType: "void",
    params: "u8 fanfareNum",
    callsTo: ["m4aSongNumStop"],
    lineCount: 1,
    bodyC: "m4aSongNumStop(sFanfares[fanfareNum].songNum);",
  },
  "StopMapMusic": {
    returnType: "void",
    params: "void",
    lineCount: 3,
    bodyC: "sCurrentMapMusic = 0;\n    sNextMapMusic = 0;\n    sMapMusicState = 1;",
  },
  "Task_DuckBGMForPokemonCry": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","IsPokemonCryPlaying","m4aMPlayVolumeControl"],
    lineCount: 10,
    bodyC: "if (gPokemonCryBGMDuckingCounter)\n    {\n        gPokemonCryBGMDuckingCounter--;\n        return;\n    }\n\n    if (!IsPokemonCryPlaying(gMPlay_PokemonCry))\n    {\n        m4aMPlayVolumeControl(&gMPlayInfo_BGM, TRACKS_ALL, 256);\n        DestroyTask(taskId);\n    }",
  },
  "Task_Fanfare": {
    returnType: "static void",
    params: "u8 taskId",
    callsTo: ["DestroyTask","m4aMPlayContinue"],
    lineCount: 9,
    bodyC: "if (sFanfareCounter)\n    {\n        sFanfareCounter--;\n    }\n    else\n    {\n        m4aMPlayContinue(&gMPlayInfo_BGM);\n        DestroyTask(taskId);\n    }",
  },
  "WaitFanfare": {
    returnType: "bool8",
    params: "bool8 stop",
    callsTo: ["m4aMPlayContinue","m4aSongNumStart"],
    lineCount: 13,
    bodyC: "if (sFanfareCounter)\n    {\n        sFanfareCounter--;\n        return FALSE;\n    }\n    else\n    {\n        if (!stop)\n            m4aMPlayContinue(&gMPlayInfo_BGM);\n        else\n            m4aSongNumStart(MUS_DUMMY);\n\n        return TRUE;\n    }",
  },
} as const;
