// AUTO-GENERATED from src/sprite.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 102

export const ENGINE_FUNCTIONS = {
  "AddSpriteToOamBuffer": {
    returnType: "bool8",
    params: "struct Sprite *sprite, u8 *oamIndex",
    callsTo: ["AddSubspritesToOamBuffer"],
    lineCount: 12,
    bodyC: "if (*oamIndex >= gOamLimit)\n        return 1;\n\n    if (!sprite->subspriteTables || sprite->subspriteMode == SUBSPRITES_OFF)\n    {\n        gMain.oamBuffer[*oamIndex] = sprite->oam;\n        (*oamIndex)++;\n        return 0;\n    }\n    else\n    {\n        return AddSubspritesToOamBuffer(sprite, &gMain.oamBuffer[*oamIndex], oamIndex);\n    }",
  },
  "AddSpritesToOamBuffer": {
    returnType: "void",
    params: "void",
    callsTo: ["AddSpriteToOamBuffer"],
    lineCount: 14,
    bodyC: "u8 i = 0;\n    u8 oamIndex = 0;\n\n    while (i < MAX_SPRITES)\n    {\n        struct Sprite *sprite = &gSprites[sSpriteOrder[i]];\n        if (sprite->inUse && !sprite->invisible && AddSpriteToOamBuffer(sprite, &oamIndex))\n            return;\n        i++;\n    }\n\n    while (oamIndex < gOamLimit)\n    {\n        gMain.oamBuffer[oamIndex] = gDummyOamData;\n        oamIndex++;\n    }",
  },
  "AddSubspritesToOamBuffer": {
    returnType: "bool8",
    params: "struct Sprite *sprite, struct OamData *destOam, u8 *oamIndex",
    lineCount: 62,
    bodyC: "const struct SubspriteTable *subspriteTable;\n    struct OamData *oam;\n\n    if (*oamIndex >= gOamLimit)\n        return 1;\n\n    subspriteTable = &sprite->subspriteTables[sprite->subspriteTableNum];\n    oam = &sprite->oam;\n\n    if (!subspriteTable || !subspriteTable->subsprites)\n    {\n        *destOam = *oam;\n        (*oamIndex)++;\n        return 0;\n    }\n    else\n    {\n        u16 tileNum;\n        u16 baseX;\n        u16 baseY;\n        u8 subspriteCount;\n        u8 hFlip;\n        u8 vFlip;\n        u8 i;\n\n        tileNum = oam->tileNum;\n        subspriteCount = subspriteTable->subspriteCount;\n        hFlip = ((s32)oam->matrixNum >> 3) & 1;\n        vFlip = ((s32)oam->matrixNum >> 4) & 1;\n        baseX = oam->x - sprite->centerToCornerVecX;\n        baseY = oam->y - sprite->centerToCornerVecY;\n\n        for (i = 0; i < subspriteCount; i++, (*oamIndex)++)\n        {\n            u16 x;\n            u16 y;\n\n            if (*oamIndex >= gOamLimit)\n                return 1;\n\n            x = subspriteTable->subsprites[i].x;\n            y = subspriteTable->subsprites[i].y;\n\n            if (hFlip)\n            {\n                s8 width = sOamDimensions[subspriteTable->subsprites[i].shape][subspriteTable->subsprites[i].size].width;\n                s16 right = x;\n                right += width;\n                x = right;\n                x = ~x + 1;\n            }\n\n            if (vFlip)\n            {\n                s8 height = sOamDimensions[subspriteTable->subsprites[i].shape][subspriteTable->subsprites[i].size].height;\n                s16 bottom = y;\n                bottom += height;\n                y = bottom;\n                y = ~y + 1;\n            }\n\n            destOam[i] = *oam;\n            destOam[i].shape = subspriteTable->subsprites[i].shape;\n            destOam[i].size = subspriteTable->subsprites[i].size;\n            destOam[i].x = (s16)baseX + (s16)x;\n            destOam[i].y = baseY + y;\n            destOam[i].tileNum = tileNum + subspriteTable->subsprites[i].tileOffset;\n\n            if (sprite->subspriteMode != SUBSPRITES_IGNORE_PRIORITY)\n                destOam[i].priority = subspriteTable->subsprites[i].priority;\n        }\n    }\n\n    return 0;",
  },
  "AffineAnimCmd_end": {
    returnType: "void",
    params: "u8 matrixNum, struct Sprite *sprite",
    callsTo: ["ApplyAffineAnimFrameRelativeAndUpdateMatrix"],
    lineCount: 4,
    bodyC: "struct AffineAnimFrameCmd dummyFrameCmd = {0};\n    sprite->affineAnimEnded = TRUE;\n    sAffineAnimStates[matrixNum].animCmdIndex--;\n    ApplyAffineAnimFrameRelativeAndUpdateMatrix(matrixNum, &dummyFrameCmd);",
  },
  "AffineAnimCmd_frame": {
    returnType: "void",
    params: "u8 matrixNum, struct Sprite *sprite",
    callsTo: ["ApplyAffineAnimFrame","GetAffineAnimFrame"],
    lineCount: 4,
    bodyC: "struct AffineAnimFrameCmd frameCmd;\n    GetAffineAnimFrame(matrixNum, sprite, &frameCmd);\n    ApplyAffineAnimFrame(matrixNum, &frameCmd);\n    sAffineAnimStates[matrixNum].delayCounter = frameCmd.duration;",
  },
  "AffineAnimCmd_jump": {
    returnType: "void",
    params: "u8 matrixNum, struct Sprite *sprite",
    callsTo: ["ApplyAffineAnimFrame","GetAffineAnimFrame"],
    lineCount: 5,
    bodyC: "struct AffineAnimFrameCmd frameCmd;\n    sAffineAnimStates[matrixNum].animCmdIndex = sprite->affineAnims[sAffineAnimStates[matrixNum].animNum][sAffineAnimStates[matrixNum].animCmdIndex].jump.target;\n    GetAffineAnimFrame(matrixNum, sprite, &frameCmd);\n    ApplyAffineAnimFrame(matrixNum, &frameCmd);\n    sAffineAnimStates[matrixNum].delayCounter = frameCmd.duration;",
  },
  "AffineAnimCmd_loop": {
    returnType: "void",
    params: "u8 matrixNum, struct Sprite *sprite",
    callsTo: ["BeginAffineAnimLoop","ContinueAffineAnimLoop"],
    lineCount: 4,
    bodyC: "if (sAffineAnimStates[matrixNum].loopCounter)\n        ContinueAffineAnimLoop(matrixNum, sprite);\n    else\n        BeginAffineAnimLoop(matrixNum, sprite);",
  },
  "AffineAnimDelay": {
    returnType: "void",
    params: "u8 matrixNum, struct Sprite *sprite",
    callsTo: ["ApplyAffineAnimFrameRelativeAndUpdateMatrix","DecrementAffineAnimDelayCounter","GetAffineAnimFrame"],
    lineCount: 6,
    bodyC: "if (!DecrementAffineAnimDelayCounter(sprite, matrixNum))\n    {\n        struct AffineAnimFrameCmd frameCmd;\n        GetAffineAnimFrame(matrixNum, sprite, &frameCmd);\n        ApplyAffineAnimFrameRelativeAndUpdateMatrix(matrixNum, &frameCmd);\n    }",
  },
  "AffineAnimStateReset": {
    returnType: "void",
    params: "u8 matrixNum",
    lineCount: 7,
    bodyC: "sAffineAnimStates[matrixNum].animNum = 0;\n    sAffineAnimStates[matrixNum].animCmdIndex = 0;\n    sAffineAnimStates[matrixNum].delayCounter = 0;\n    sAffineAnimStates[matrixNum].loopCounter = 0;\n    sAffineAnimStates[matrixNum].xScale = 0x0100;\n    sAffineAnimStates[matrixNum].yScale = 0x0100;\n    sAffineAnimStates[matrixNum].rotation = 0;",
  },
  "AffineAnimStateRestartAnim": {
    returnType: "void",
    params: "u8 matrixNum",
    lineCount: 3,
    bodyC: "sAffineAnimStates[matrixNum].animCmdIndex = 0;\n    sAffineAnimStates[matrixNum].delayCounter = 0;\n    sAffineAnimStates[matrixNum].loopCounter = 0;",
  },
  "AffineAnimStateStartAnim": {
    returnType: "void",
    params: "u8 matrixNum, u8 animNum",
    lineCount: 7,
    bodyC: "sAffineAnimStates[matrixNum].animNum = animNum;\n    sAffineAnimStates[matrixNum].animCmdIndex = 0;\n    sAffineAnimStates[matrixNum].delayCounter = 0;\n    sAffineAnimStates[matrixNum].loopCounter = 0;\n    sAffineAnimStates[matrixNum].xScale = 0x0100;\n    sAffineAnimStates[matrixNum].yScale = 0x0100;\n    sAffineAnimStates[matrixNum].rotation = 0;",
  },
  "AllocOamMatrix": {
    returnType: "u8",
    params: "void",
    lineCount: 14,
    bodyC: "u8 i = 0;\n    u32 bit = 1;\n    u32 bitmap = gOamMatrixAllocBitmap;\n\n    while (i < OAM_MATRIX_COUNT)\n    {\n        if (!(bitmap & bit))\n        {\n            gOamMatrixAllocBitmap |= bit;\n            return i;\n        }\n\n        i++;\n        bit <<= 1;\n    }\n\n    return 0xFF;",
  },
  "AllocSpritePalette": {
    returnType: "u8",
    params: "u16 tag",
    callsTo: ["IndexOfSpritePaletteTag"],
    lineCount: 10,
    bodyC: "u8 index = IndexOfSpritePaletteTag(TAG_NONE);\n    if (index == 0xFF)\n    {\n        return 0xFF;\n    }\n    else\n    {\n        sSpritePaletteTags[index] = tag;\n        return index;\n    }",
  },
  "AllocSpriteTileRange": {
    returnType: "void",
    params: "u16 tag, u16 start, u16 count",
    callsTo: ["IndexOfSpriteTileTag","SET_SPRITE_TILE_RANGE"],
    lineCount: 3,
    bodyC: "u8 freeIndex = IndexOfSpriteTileTag(TAG_NONE);\n    sSpriteTileRangeTags[freeIndex] = tag;\n    SET_SPRITE_TILE_RANGE(freeIndex, start, count);",
  },
  "AllocSpriteTiles": {
    returnType: "s16",
    params: "u16 tileCount",
    callsTo: ["ALLOC_SPRITE_TILE","FREE_SPRITE_TILE","SPRITE_TILE_IS_ALLOCATED"],
    lineCount: 36,
    bodyC: "u16 i;\n    s16 start;\n    u16 numTilesFound;\n\n    if (tileCount == 0)\n    {\n         \n        for (i = gReservedSpriteTileCount; i < TOTAL_OBJ_TILE_COUNT; i++)\n            FREE_SPRITE_TILE(i);\n\n        return 0;\n    }\n\n    i = gReservedSpriteTileCount;\n\n    for (;;)\n    {\n        while (SPRITE_TILE_IS_ALLOCATED(i))\n        {\n            i++;\n\n            if (i == TOTAL_OBJ_TILE_COUNT)\n                return -1;\n        }\n\n        start = i;\n        numTilesFound = 1;\n\n        while (numTilesFound != tileCount)\n        {\n            i++;\n\n            if (i == TOTAL_OBJ_TILE_COUNT)\n                return -1;\n\n            if (!SPRITE_TILE_IS_ALLOCATED(i))\n                numTilesFound++;\n            else\n                break;\n        }\n\n        if (numTilesFound == tileCount)\n            break;\n    }\n\n    for (i = start; i < tileCount + start; i++)\n        ALLOC_SPRITE_TILE(i);\n\n    return start;",
  },
  "AnimCmd_end": {
    returnType: "void",
    params: "struct Sprite *sprite",
    lineCount: 2,
    bodyC: "sprite->animCmdIndex--;\n    sprite->animEnded = TRUE;",
  },
  "AnimCmd_frame": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["RequestSpriteFrameImageCopy","SetSpriteOamFlipBits"],
    lineCount: 17,
    bodyC: "s16 imageValue;\n    u8 duration;\n    u8 hFlip;\n    u8 vFlip;\n\n    imageValue = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.imageValue;\n    duration = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.duration;\n    hFlip = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.hFlip;\n    vFlip = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.vFlip;\n\n    if (duration)\n        duration--;\n\n    sprite->animDelayCounter = duration;\n\n    if (!(sprite->oam.affineMode & ST_OAM_AFFINE_ON_MASK))\n        SetSpriteOamFlipBits(sprite, hFlip, vFlip);\n\n    if (sprite->usingSheet)\n        sprite->oam.tileNum = sprite->sheetTileStart + imageValue;\n    else\n        RequestSpriteFrameImageCopy(imageValue, sprite->oam.tileNum, sprite->images);",
  },
  "AnimCmd_jump": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["RequestSpriteFrameImageCopy","SetSpriteOamFlipBits"],
    lineCount: 18,
    bodyC: "s16 imageValue;\n    u8 duration;\n    u8 hFlip;\n    u8 vFlip;\n\n    sprite->animCmdIndex = sprite->anims[sprite->animNum][sprite->animCmdIndex].jump.target;\n\n    imageValue = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.imageValue;\n    duration = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.duration;\n    hFlip = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.hFlip;\n    vFlip = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.vFlip;\n\n    if (duration)\n        duration--;\n\n    sprite->animDelayCounter = duration;\n\n    if (!(sprite->oam.affineMode & ST_OAM_AFFINE_ON_MASK))\n        SetSpriteOamFlipBits(sprite, hFlip, vFlip);\n\n    if (sprite->usingSheet)\n        sprite->oam.tileNum = sprite->sheetTileStart + imageValue;\n    else\n        RequestSpriteFrameImageCopy(imageValue, sprite->oam.tileNum, sprite->images);",
  },
  "AnimCmd_loop": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["BeginAnimLoop","ContinueAnimLoop"],
    lineCount: 4,
    bodyC: "if (sprite->animLoopCounter)\n        ContinueAnimLoop(sprite);\n    else\n        BeginAnimLoop(sprite);",
  },
  "AnimateSprite": {
    returnType: "void",
    params: "struct Sprite *sprite",
    lineCount: 3,
    bodyC: "sAnimFuncs[sprite->animBeginning](sprite);\n\n    if (!gAffineAnimsDisabled)\n        sAffineAnimFuncs[sprite->affineAnimBeginning](sprite);",
  },
  "AnimateSprites": {
    returnType: "void",
    params: "void",
    callsTo: ["AnimateSprite","callback"],
    lineCount: 11,
    bodyC: "u8 i;\n    for (i = 0; i < MAX_SPRITES; i++)\n    {\n        struct Sprite *sprite = &gSprites[i];\n\n        if (sprite->inUse)\n        {\n            sprite->callback(sprite);\n\n            if (sprite->inUse)\n                AnimateSprite(sprite);\n        }\n    }",
  },
  "ApplyAffineAnimFrame": {
    returnType: "void",
    params: "u8 matrixNum, struct AffineAnimFrameCmd *frameCmd",
    callsTo: ["ApplyAffineAnimFrameAbsolute","ApplyAffineAnimFrameRelativeAndUpdateMatrix"],
    lineCount: 11,
    bodyC: "struct AffineAnimFrameCmd dummyFrameCmd = {0};\n\n    if (frameCmd->duration)\n    {\n        frameCmd->duration--;\n        ApplyAffineAnimFrameRelativeAndUpdateMatrix(matrixNum, frameCmd);\n    }\n    else\n    {\n        ApplyAffineAnimFrameAbsolute(matrixNum, frameCmd);\n        ApplyAffineAnimFrameRelativeAndUpdateMatrix(matrixNum, &dummyFrameCmd);\n    }",
  },
  "ApplyAffineAnimFrameAbsolute": {
    returnType: "void",
    params: "u8 matrixNum, struct AffineAnimFrameCmd *frameCmd",
    lineCount: 3,
    bodyC: "sAffineAnimStates[matrixNum].xScale = frameCmd->xScale;\n    sAffineAnimStates[matrixNum].yScale = frameCmd->yScale;\n    sAffineAnimStates[matrixNum].rotation = frameCmd->rotation << 8;",
  },
  "ApplyAffineAnimFrameRelativeAndUpdateMatrix": {
    returnType: "void",
    params: "u8 matrixNum, struct AffineAnimFrameCmd *frameCmd",
    callsTo: ["ConvertScaleParam","CopyOamMatrix","ObjAffineSet"],
    lineCount: 10,
    bodyC: "struct ObjAffineSrcData srcData;\n    struct OamMatrix matrix;\n    sAffineAnimStates[matrixNum].xScale += frameCmd->xScale;\n    sAffineAnimStates[matrixNum].yScale += frameCmd->yScale;\n    sAffineAnimStates[matrixNum].rotation = (sAffineAnimStates[matrixNum].rotation + (frameCmd->rotation << 8)) & ~0xFF;\n    srcData.xScale = ConvertScaleParam(sAffineAnimStates[matrixNum].xScale);\n    srcData.yScale = ConvertScaleParam(sAffineAnimStates[matrixNum].yScale);\n    srcData.rotation = sAffineAnimStates[matrixNum].rotation;\n    ObjAffineSet(&srcData, &matrix, 1, 2);\n    CopyOamMatrix(matrixNum, &matrix);",
  },
  "BeginAffineAnim": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["AffineAnimStateRestartAnim","ApplyAffineAnimFrame","GetAffineAnimFrame","GetSpriteMatrixNum","UpdateSpriteMatrixAnchorPos"],
    lineCount: 13,
    bodyC: "if ((sprite->oam.affineMode & ST_OAM_AFFINE_ON_MASK) && sprite->affineAnims[0][0].type != 32767)\n    {\n        struct AffineAnimFrameCmd frameCmd;\n        u8 matrixNum = GetSpriteMatrixNum(sprite);\n        AffineAnimStateRestartAnim(matrixNum);\n        GetAffineAnimFrame(matrixNum, sprite, &frameCmd);\n        sprite->affineAnimBeginning = FALSE;\n        sprite->affineAnimEnded = FALSE;\n        ApplyAffineAnimFrame(matrixNum, &frameCmd);\n        sAffineAnimStates[matrixNum].delayCounter = frameCmd.duration;\n        if (sprite->anchored)\n            UpdateSpriteMatrixAnchorPos(sprite, sprite->sAnchorX, sprite->sAnchorY);\n    }",
  },
  "BeginAffineAnimLoop": {
    returnType: "void",
    params: "u8 matrixNum, struct Sprite *sprite",
    callsTo: ["ContinueAffineAnim","JumpToTopOfAffineAnimLoop"],
    lineCount: 3,
    bodyC: "sAffineAnimStates[matrixNum].loopCounter = sprite->affineAnims[sAffineAnimStates[matrixNum].animNum][sAffineAnimStates[matrixNum].animCmdIndex].loop.count;\n    JumpToTopOfAffineAnimLoop(matrixNum, sprite);\n    ContinueAffineAnim(sprite);",
  },
  "BeginAnim": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["RequestSpriteFrameImageCopy","SetSpriteOamFlipBits"],
    lineCount: 24,
    bodyC: "s16 imageValue;\n    u8 duration;\n    u8 hFlip;\n    u8 vFlip;\n\n    sprite->animCmdIndex = 0;\n    sprite->animEnded = FALSE;\n    sprite->animLoopCounter = 0;\n    imageValue = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.imageValue;\n\n    if (imageValue != -1)\n    {\n        sprite->animBeginning = FALSE;\n        duration = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.duration;\n        hFlip = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.hFlip;\n        vFlip = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.vFlip;\n\n        if (duration)\n            duration--;\n\n        sprite->animDelayCounter = duration;\n\n        if (!(sprite->oam.affineMode & ST_OAM_AFFINE_ON_MASK))\n            SetSpriteOamFlipBits(sprite, hFlip, vFlip);\n\n        if (sprite->usingSheet)\n            sprite->oam.tileNum = sprite->sheetTileStart + imageValue;\n        else\n            RequestSpriteFrameImageCopy(imageValue, sprite->oam.tileNum, sprite->images);\n    }",
  },
  "BeginAnimLoop": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["ContinueAnim","JumpToTopOfAnimLoop"],
    lineCount: 3,
    bodyC: "sprite->animLoopCounter = sprite->anims[sprite->animNum][sprite->animCmdIndex].loop.count;\n    JumpToTopOfAnimLoop(sprite);\n    ContinueAnim(sprite);",
  },
  "BuildOamBuffer": {
    returnType: "void",
    params: "void",
    callsTo: ["AddSpritesToOamBuffer","BuildSpritePriorities","CopyMatricesToOamBuffer","SortSprites","UpdateOamCoords"],
    lineCount: 10,
    bodyC: "u8 temp;\n    UpdateOamCoords();\n    BuildSpritePriorities();\n    SortSprites();\n    temp = gMain.oamLoadDisabled;\n    gMain.oamLoadDisabled = TRUE;\n    AddSpritesToOamBuffer();\n    CopyMatricesToOamBuffer();\n    gMain.oamLoadDisabled = temp;\n    sShouldProcessSpriteCopyRequests = TRUE;",
  },
  "BuildSpritePriorities": {
    returnType: "void",
    params: "void",
    lineCount: 7,
    bodyC: "u16 i;\n    for (i = 0; i < MAX_SPRITES; i++)\n    {\n        struct Sprite *sprite = &gSprites[i];\n        u16 priority = sprite->subpriority | (sprite->oam.priority << 8);\n        sSpritePriorities[i] = priority;\n    }",
  },
  "CalcCenterToCornerVec": {
    returnType: "void",
    params: "struct Sprite *sprite, u8 shape, u8 size, u8 affineMode",
    lineCount: 9,
    bodyC: "u8 x = sCenterToCornerVecTable[shape][size][0];\n    u8 y = sCenterToCornerVecTable[shape][size][1];\n\n    if (affineMode & ST_OAM_AFFINE_DOUBLE_MASK)\n    {\n        x *= 2;\n        y *= 2;\n    }\n\n    sprite->centerToCornerVecX = x;\n    sprite->centerToCornerVecY = y;",
  },
  "ChangeSpriteAffineAnim": {
    returnType: "void",
    params: "struct Sprite *sprite, u8 animNum",
    callsTo: ["GetSpriteMatrixNum"],
    lineCount: 4,
    bodyC: "u8 matrixNum = GetSpriteMatrixNum(sprite);\n    sAffineAnimStates[matrixNum].animNum = animNum;\n    sprite->affineAnimBeginning = TRUE;\n    sprite->affineAnimEnded = FALSE;",
  },
  "ChangeSpriteAffineAnimIfDifferent": {
    returnType: "void",
    params: "struct Sprite *sprite, u8 animNum",
    callsTo: ["ChangeSpriteAffineAnim","GetSpriteMatrixNum"],
    lineCount: 3,
    bodyC: "u8 matrixNum = GetSpriteMatrixNum(sprite);\n    if (sAffineAnimStates[matrixNum].animNum != animNum)\n        ChangeSpriteAffineAnim(sprite, animNum);",
  },
  "ClearSpriteCopyRequests": {
    returnType: "void",
    params: "void",
    lineCount: 9,
    bodyC: "u8 i;\n\n    sShouldProcessSpriteCopyRequests = FALSE;\n    sSpriteCopyRequestCount = 0;\n\n    for (i = 0; i < MAX_SPRITE_COPY_REQUESTS; i++)\n    {\n        sSpriteCopyRequests[i].src = 0;\n        sSpriteCopyRequests[i].dest = 0;\n        sSpriteCopyRequests[i].size = 0;\n    }",
  },
  "ContinueAffineAnim": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["AffineAnimDelay","GetSpriteMatrixNum","UpdateSpriteMatrixAnchorPos"],
    lineCount: 25,
    bodyC: "if (sprite->oam.affineMode & ST_OAM_AFFINE_ON_MASK)\n    {\n        u8 matrixNum = GetSpriteMatrixNum(sprite);\n\n        if (sAffineAnimStates[matrixNum].delayCounter)\n        {\n            AffineAnimDelay(matrixNum, sprite);\n        }\n        else if (sprite->affineAnimPaused)\n        {\n            return;\n        }\n        else\n        {\n            s16 type;\n            s16 funcIndex;\n            sAffineAnimStates[matrixNum].animCmdIndex++;\n            type = sprite->affineAnims[sAffineAnimStates[matrixNum].animNum][sAffineAnimStates[matrixNum].animCmdIndex].type;\n            funcIndex = 3;\n            if (type >= 32765)\n                funcIndex = type - 32765;\n            sAffineAnimCmdFuncs[funcIndex](matrixNum, sprite);\n        }\n        if (sprite->anchored)\n            UpdateSpriteMatrixAnchorPos(sprite, sprite->sAnchorX, sprite->sAnchorY);\n    }",
  },
  "ContinueAffineAnimLoop": {
    returnType: "void",
    params: "u8 matrixNum, struct Sprite *sprite",
    callsTo: ["ContinueAffineAnim","JumpToTopOfAffineAnimLoop"],
    lineCount: 3,
    bodyC: "sAffineAnimStates[matrixNum].loopCounter--;\n    JumpToTopOfAffineAnimLoop(matrixNum, sprite);\n    ContinueAffineAnim(sprite);",
  },
  "ContinueAnim": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["DecrementAnimDelayCounter","SetSpriteOamFlipBits"],
    lineCount: 21,
    bodyC: "if (sprite->animDelayCounter)\n    {\n        u8 hFlip;\n        u8 vFlip;\n        DecrementAnimDelayCounter(sprite);\n        hFlip = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.hFlip;\n        vFlip = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.vFlip;\n        if (!(sprite->oam.affineMode & ST_OAM_AFFINE_ON_MASK))\n            SetSpriteOamFlipBits(sprite, hFlip, vFlip);\n    }\n    else if (!sprite->animPaused)\n    {\n        s16 type;\n        s16 funcIndex;\n        sprite->animCmdIndex++;\n        type = sprite->anims[sprite->animNum][sprite->animCmdIndex].type;\n        funcIndex = 3;\n        if (type < 0)\n            funcIndex = type + 3;\n        sAnimCmdFuncs[funcIndex](sprite);\n    }",
  },
  "ContinueAnimLoop": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["ContinueAnim","JumpToTopOfAnimLoop"],
    lineCount: 3,
    bodyC: "sprite->animLoopCounter--;\n    JumpToTopOfAnimLoop(sprite);\n    ContinueAnim(sprite);",
  },
  "ConvertScaleParam": {
    returnType: "s16",
    params: "s16 scale",
    callsTo: ["SAFE_DIV"],
    lineCount: 2,
    bodyC: "s32 val = 0x10000;\n    return SAFE_DIV(val, scale);",
  },
  "CopyFromSprites": {
    returnType: "void",
    params: "u8 *dest",
    lineCount: 8,
    bodyC: "u32 i;\n    u8 *src = (u8 *)gSprites;\n    for (i = 0; i < sizeof(struct Sprite) * MAX_SPRITES; i++)\n    {\n        *dest = *src;\n        dest++;\n        src++;\n    }",
  },
  "CopyMatricesToOamBuffer": {
    returnType: "void",
    params: "void",
    lineCount: 9,
    bodyC: "u8 i;\n    for (i = 0; i < OAM_MATRIX_COUNT; i++)\n    {\n        u32 base = 4 * i;\n        gMain.oamBuffer[base + 0].affineParam = gOamMatrices[i].a;\n        gMain.oamBuffer[base + 1].affineParam = gOamMatrices[i].b;\n        gMain.oamBuffer[base + 2].affineParam = gOamMatrices[i].c;\n        gMain.oamBuffer[base + 3].affineParam = gOamMatrices[i].d;\n    }",
  },
  "CopyOamMatrix": {
    returnType: "void",
    params: "u8 destMatrixIndex, struct OamMatrix *srcMatrix",
    lineCount: 4,
    bodyC: "gOamMatrices[destMatrixIndex].a = srcMatrix->a;\n    gOamMatrices[destMatrixIndex].b = srcMatrix->b;\n    gOamMatrices[destMatrixIndex].c = srcMatrix->c;\n    gOamMatrices[destMatrixIndex].d = srcMatrix->d;",
  },
  "CopyToSprites": {
    returnType: "void",
    params: "u8 *src",
    lineCount: 8,
    bodyC: "u32 i;\n    u8 *dest = (u8 *)gSprites;\n    for (i = 0; i < sizeof(struct Sprite) * MAX_SPRITES; i++)\n    {\n        *dest = *src;\n        src++;\n        dest++;\n    }",
  },
  "CreateInvisibleSprite": {
    returnType: "u8",
    params: "void (*callback)(struct Sprite *)",
    callsTo: ["CreateSprite"],
    lineCount: 11,
    bodyC: "u8 index = CreateSprite(&gDummySpriteTemplate, 0, 0, 31);\n\n    if (index == MAX_SPRITES)\n    {\n        return MAX_SPRITES;\n    }\n    else\n    {\n        gSprites[index].invisible = TRUE;\n        gSprites[index].callback = callback;\n        return index;\n    }",
  },
  "CreateSprite": {
    returnType: "u8",
    params: "const struct SpriteTemplate *template, s16 x, s16 y, u8 subpriority",
    callsTo: ["CreateSpriteAt"],
    lineCount: 5,
    bodyC: "u8 i;\n\n    for (i = 0; i < MAX_SPRITES; i++)\n        if (!gSprites[i].inUse)\n            return CreateSpriteAt(i, template, x, y, subpriority);\n\n    return MAX_SPRITES;",
  },
  "CreateSpriteAndAnimate": {
    returnType: "u8",
    params: "const struct SpriteTemplate *template, s16 x, s16 y, u8 subpriority",
    callsTo: ["AnimateSprite","CreateSpriteAt","callback"],
    lineCount: 16,
    bodyC: "u8 i;\n\n    for (i = 0; i < MAX_SPRITES; i++)\n    {\n        struct Sprite *sprite = &gSprites[i];\n\n        if (!gSprites[i].inUse)\n        {\n            u8 index = CreateSpriteAt(i, template, x, y, subpriority);\n\n            if (index == MAX_SPRITES)\n                return MAX_SPRITES;\n\n            gSprites[i].callback(sprite);\n\n            if (gSprites[i].inUse)\n                AnimateSprite(sprite);\n\n            return index;\n        }\n    }\n\n    return MAX_SPRITES;",
  },
  "CreateSpriteAt": {
    returnType: "u8",
    params: "u8 index, const struct SpriteTemplate *template, s16 x, s16 y, u8 subpriority",
    callsTo: ["AllocSpriteTiles","CalcCenterToCornerVec","GetSpriteTileStartByTag","IndexOfSpritePaletteTag","InitSpriteAffineAnim","ResetSprite","SetSpriteSheetFrameTileNum"],
    lineCount: 39,
    bodyC: "struct Sprite *sprite = &gSprites[index];\n\n    ResetSprite(sprite);\n\n    sprite->inUse = TRUE;\n    sprite->animBeginning = TRUE;\n    sprite->affineAnimBeginning = TRUE;\n    sprite->usingSheet = TRUE;\n\n    sprite->subpriority = subpriority;\n    sprite->oam = *template->oam;\n    sprite->anims = template->anims;\n    sprite->affineAnims = template->affineAnims;\n    sprite->template = template;\n    sprite->callback = template->callback;\n    sprite->x = x;\n    sprite->y = y;\n\n    CalcCenterToCornerVec(sprite, sprite->oam.shape, sprite->oam.size, sprite->oam.affineMode);\n\n    if (template->tileTag == TAG_NONE)\n    {\n        s16 tileNum;\n        sprite->images = template->images;\n        tileNum = AllocSpriteTiles((u8)(sprite->images->size / TILE_SIZE_4BPP));\n        if (tileNum == -1)\n        {\n            ResetSprite(sprite);\n            return MAX_SPRITES;\n        }\n        sprite->oam.tileNum = tileNum;\n        sprite->usingSheet = FALSE;\n        sprite->sheetTileStart = 0;\n    }\n    else\n    {\n        sprite->sheetTileStart = GetSpriteTileStartByTag(template->tileTag);\n        SetSpriteSheetFrameTileNum(sprite);\n    }\n\n    if (sprite->oam.affineMode & ST_OAM_AFFINE_ON_MASK)\n        InitSpriteAffineAnim(sprite);\n\n    if (template->paletteTag != TAG_NONE)\n        sprite->oam.paletteNum = IndexOfSpritePaletteTag(template->paletteTag);\n\n    return index;",
  },
  "CreateSpriteAtEnd": {
    returnType: "u8",
    params: "const struct SpriteTemplate *template, s16 x, s16 y, u8 subpriority",
    callsTo: ["CreateSpriteAt"],
    lineCount: 5,
    bodyC: "s16 i;\n\n    for (i = MAX_SPRITES - 1; i > -1; i--)\n        if (!gSprites[i].inUse)\n            return CreateSpriteAt(i, template, x, y, subpriority);\n\n    return MAX_SPRITES;",
  },
  "DecrementAffineAnimDelayCounter": {
    returnType: "bool8",
    params: "struct Sprite *sprite, u8 matrixNum",
    lineCount: 3,
    bodyC: "if (!sprite->affineAnimPaused)\n        --sAffineAnimStates[matrixNum].delayCounter;\n    return sprite->affineAnimPaused;",
  },
  "DecrementAnimDelayCounter": {
    returnType: "void",
    params: "struct Sprite *sprite",
    lineCount: 2,
    bodyC: "if (!sprite->animPaused)\n        sprite->animDelayCounter--;",
  },
  "DestroySprite": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["FREE_SPRITE_TILE","ResetSprite"],
    lineCount: 11,
    bodyC: "if (sprite->inUse)\n    {\n        if (!sprite->usingSheet)\n        {\n            u16 i;\n            u16 tileEnd = (sprite->images->size / TILE_SIZE_4BPP) + sprite->oam.tileNum;\n            for (i = sprite->oam.tileNum; i < tileEnd; i++)\n                FREE_SPRITE_TILE(i);\n        }\n        ResetSprite(sprite);\n    }",
  },
  "DestroySpriteAndFreeResources": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["DestroySprite","FreeSpriteOamMatrix","FreeSpritePalette","FreeSpriteTiles"],
    lineCount: 4,
    bodyC: "FreeSpriteTiles(sprite);\n    FreeSpritePalette(sprite);\n    FreeSpriteOamMatrix(sprite);\n    DestroySprite(sprite);",
  },
  "DoLoadSpritePalette": {
    returnType: "void",
    params: "const u16 *src, u16 paletteOffset",
    callsTo: ["LoadPalette"],
    lineCount: 1,
    bodyC: "LoadPalette(src, OBJ_PLTT_OFFSET + paletteOffset, PLTT_SIZE_4BPP);",
  },
  "FreeAllSpritePalettes": {
    returnType: "void",
    params: "void",
    lineCount: 4,
    bodyC: "u8 i;\n    gReservedSpritePaletteCount = 0;\n    for (i = 0; i < 16; i++)\n        sSpritePaletteTags[i] = TAG_NONE;",
  },
  "FreeOamMatrix": {
    returnType: "void",
    params: "u8 matrixNum",
    callsTo: ["SetOamMatrix"],
    lineCount: 9,
    bodyC: "u8 i = 0;\n    u32 bit = 1;\n\n    while (i < matrixNum)\n    {\n        i++;\n        bit <<= 1;\n    }\n\n    gOamMatrixAllocBitmap &= ~bit;\n    SetOamMatrix(matrixNum, 0x100, 0, 0, 0x100);",
  },
  "FreeSpriteOamMatrix": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["FreeOamMatrix"],
    lineCount: 5,
    bodyC: "if (sprite->oam.affineMode & ST_OAM_AFFINE_ON_MASK)\n    {\n        FreeOamMatrix(sprite->oam.matrixNum);\n        sprite->oam.affineMode = ST_OAM_AFFINE_OFF;\n    }",
  },
  "FreeSpritePalette": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["FreeSpritePaletteByTag"],
    lineCount: 5,
    bodyC: "#ifdef UBFIX\n    if (!sprite || !sprite->template)\n        return;\n#endif\n\n    FreeSpritePaletteByTag(sprite->template->paletteTag);",
  },
  "FreeSpritePaletteByTag": {
    returnType: "void",
    params: "u16 tag",
    callsTo: ["IndexOfSpritePaletteTag"],
    lineCount: 3,
    bodyC: "u8 index = IndexOfSpritePaletteTag(tag);\n    if (index != 0xFF)\n        sSpritePaletteTags[index] = TAG_NONE;",
  },
  "FreeSpriteTileRanges": {
    returnType: "void",
    params: "void",
    callsTo: ["SET_SPRITE_TILE_RANGE"],
    lineCount: 6,
    bodyC: "u8 i;\n\n    for (i = 0; i < MAX_SPRITES; i++)\n    {\n        sSpriteTileRangeTags[i] = TAG_NONE;\n        SET_SPRITE_TILE_RANGE(i, 0, 0);\n    }",
  },
  "FreeSpriteTiles": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["FreeSpriteTilesByTag"],
    lineCount: 6,
    bodyC: "#ifdef UBFIX\n    if (!sprite || !sprite->template)\n        return;\n#endif\n\n    if (sprite->template->tileTag != TAG_NONE)\n        FreeSpriteTilesByTag(sprite->template->tileTag);",
  },
  "FreeSpriteTilesByTag": {
    returnType: "void",
    params: "u16 tag",
    callsTo: ["FREE_SPRITE_TILE","IndexOfSpriteTileTag"],
    lineCount: 16,
    bodyC: "u8 index = IndexOfSpriteTileTag(tag);\n    if (index != 0xFF)\n    {\n        u16 i;\n        u16 *rangeStarts;\n        u16 *rangeCounts;\n        u16 start;\n        u16 count;\n        rangeStarts = sSpriteTileRanges;\n        start = rangeStarts[index * 2];\n        rangeCounts = sSpriteTileRanges + 1;\n        count = rangeCounts[index * 2];\n\n        for (i = start; i < start + count; i++)\n            FREE_SPRITE_TILE(i);\n\n        sSpriteTileRangeTags[index] = TAG_NONE;\n    }",
  },
  "GetAffineAnimFrame": {
    returnType: "void",
    params: "u8 matrixNum, struct Sprite *sprite, struct AffineAnimFrameCmd *frameCmd",
    lineCount: 4,
    bodyC: "frameCmd->xScale = sprite->affineAnims[sAffineAnimStates[matrixNum].animNum][sAffineAnimStates[matrixNum].animCmdIndex].frame.xScale;\n    frameCmd->yScale = sprite->affineAnims[sAffineAnimStates[matrixNum].animNum][sAffineAnimStates[matrixNum].animCmdIndex].frame.yScale;\n    frameCmd->rotation = sprite->affineAnims[sAffineAnimStates[matrixNum].animNum][sAffineAnimStates[matrixNum].animCmdIndex].frame.rotation;\n    frameCmd->duration = sprite->affineAnims[sAffineAnimStates[matrixNum].animNum][sAffineAnimStates[matrixNum].animCmdIndex].frame.duration;",
  },
  "GetAnchorCoord": {
    returnType: "static s32",
    params: "s32 a0, s32 a1, s32 coord",
    lineCount: 7,
    bodyC: "s32 subResult, var1;\n\n    subResult = a1 - a0;\n    if (subResult < 0)\n        var1 = -(subResult) >> 9;\n    else\n        var1 = -(subResult >> 9);\n    return coord - ((u32)(coord * a1) / (u32)(a0) + var1);",
  },
  "GetSpriteMatrixNum": {
    returnType: "u8",
    params: "struct Sprite *sprite",
    lineCount: 4,
    bodyC: "u8 matrixNum = 0;\n    if (sprite->oam.affineMode & ST_OAM_AFFINE_ON_MASK)\n        matrixNum = sprite->oam.matrixNum;\n    return matrixNum;",
  },
  "GetSpritePaletteTagByPaletteNum": {
    returnType: "u16",
    params: "u8 paletteNum",
    lineCount: 1,
    bodyC: "return sSpritePaletteTags[paletteNum];",
  },
  "GetSpriteTileStartByTag": {
    returnType: "u16",
    params: "u16 tag",
    callsTo: ["IndexOfSpriteTileTag"],
    lineCount: 4,
    bodyC: "u8 index = IndexOfSpriteTileTag(tag);\n    if (index == 0xFF)\n        return 0xFFFF;\n    return sSpriteTileRanges[index * 2];",
  },
  "GetSpriteTileTagByTileStart": {
    returnType: "u16",
    params: "u16 start",
    lineCount: 7,
    bodyC: "u8 i;\n\n    for (i = 0; i < MAX_SPRITES; i++)\n    {\n        if (sSpriteTileRangeTags[i] != TAG_NONE && sSpriteTileRanges[i * 2] == start)\n            return sSpriteTileRangeTags[i];\n    }\n\n    return TAG_NONE;",
  },
  "IndexOfSpritePaletteTag": {
    returnType: "u8",
    params: "u16 tag",
    lineCount: 5,
    bodyC: "u8 i;\n    for (i = gReservedSpritePaletteCount; i < 16; i++)\n        if (sSpritePaletteTags[i] == tag)\n            return i;\n\n    return 0xFF;",
  },
  "IndexOfSpriteTileTag": {
    returnType: "u8",
    params: "u16 tag",
    lineCount: 5,
    bodyC: "u8 i;\n\n    for (i = 0; i < MAX_SPRITES; i++)\n        if (sSpriteTileRangeTags[i] == tag)\n            return i;\n\n    return 0xFF;",
  },
  "InitSpriteAffineAnim": {
    returnType: "void",
    params: "struct Sprite *sprite",
    callsTo: ["AffineAnimStateReset","AllocOamMatrix","CalcCenterToCornerVec"],
    lineCount: 8,
    bodyC: "u8 matrixNum = AllocOamMatrix();\n    if (matrixNum != 0xFF)\n    {\n        CalcCenterToCornerVec(sprite, sprite->oam.shape, sprite->oam.size, sprite->oam.affineMode);\n        sprite->oam.matrixNum = matrixNum;\n        sprite->affineAnimBeginning = TRUE;\n        AffineAnimStateReset(matrixNum);\n    }",
  },
  "JumpToTopOfAffineAnimLoop": {
    returnType: "void",
    params: "u8 matrixNum, struct Sprite *sprite",
    lineCount: 11,
    bodyC: "if (sAffineAnimStates[matrixNum].loopCounter)\n    {\n        sAffineAnimStates[matrixNum].animCmdIndex--;\n\n        while (sprite->affineAnims[sAffineAnimStates[matrixNum].animNum][sAffineAnimStates[matrixNum].animCmdIndex - 1].type != 32765)\n        {\n            if (sAffineAnimStates[matrixNum].animCmdIndex == 0)\n                break;\n            sAffineAnimStates[matrixNum].animCmdIndex--;\n        }\n\n        sAffineAnimStates[matrixNum].animCmdIndex--;\n    }",
  },
  "JumpToTopOfAnimLoop": {
    returnType: "void",
    params: "struct Sprite *sprite",
    lineCount: 11,
    bodyC: "if (sprite->animLoopCounter)\n    {\n        sprite->animCmdIndex--;\n\n        while (sprite->anims[sprite->animNum][sprite->animCmdIndex - 1].type != -3)\n        {\n            if (sprite->animCmdIndex == 0)\n                break;\n            sprite->animCmdIndex--;\n        }\n\n        sprite->animCmdIndex--;\n    }",
  },
  "LoadOam": {
    returnType: "void",
    params: "void",
    callsTo: ["CpuCopy32"],
    lineCount: 2,
    bodyC: "if (!gMain.oamLoadDisabled)\n        CpuCopy32(gMain.oamBuffer, (void *)OAM, sizeof(gMain.oamBuffer));",
  },
  "LoadSpritePalette": {
    returnType: "u8",
    params: "const struct SpritePalette *palette",
    callsTo: ["DoLoadSpritePalette","IndexOfSpritePaletteTag","PLTT_ID"],
    lineCount: 14,
    bodyC: "u8 index = IndexOfSpritePaletteTag(palette->tag);\n\n    if (index != 0xFF)\n        return index;\n\n    index = IndexOfSpritePaletteTag(TAG_NONE);\n\n    if (index == 0xFF)\n    {\n        return 0xFF;\n    }\n    else\n    {\n        sSpritePaletteTags[index] = palette->tag;\n        DoLoadSpritePalette(palette->data, PLTT_ID(index));\n        return index;\n    }",
  },
  "LoadSpritePalettes": {
    returnType: "void",
    params: "const struct SpritePalette *palettes",
    callsTo: ["LoadSpritePalette"],
    lineCount: 4,
    bodyC: "u8 i;\n    for (i = 0; palettes[i].data != NULL; i++)\n        if (LoadSpritePalette(&palettes[i]) == 0xFF)\n            break;",
  },
  "LoadSpriteSheet": {
    returnType: "u16",
    params: "const struct SpriteSheet *sheet",
    callsTo: ["AllocSpriteTileRange","AllocSpriteTiles","CpuCopy16"],
    lineCount: 11,
    bodyC: "s16 tileStart = AllocSpriteTiles(sheet->size / TILE_SIZE_4BPP);\n\n    if (tileStart < 0)\n    {\n        return 0;\n    }\n    else\n    {\n        AllocSpriteTileRange(sheet->tag, (u16)tileStart, sheet->size / TILE_SIZE_4BPP);\n        CpuCopy16(sheet->data, (u8 *)OBJ_VRAM0 + TILE_SIZE_4BPP * tileStart, sheet->size);\n        return (u16)tileStart;\n    }",
  },
  "LoadSpriteSheets": {
    returnType: "void",
    params: "const struct SpriteSheet *sheets",
    callsTo: ["LoadSpriteSheet"],
    lineCount: 3,
    bodyC: "u8 i;\n    for (i = 0; sheets[i].data != NULL; i++)\n        LoadSpriteSheet(&sheets[i]);",
  },
  "ProcessSpriteCopyRequests": {
    returnType: "void",
    params: "void",
    callsTo: ["CpuCopy16"],
    lineCount: 11,
    bodyC: "if (sShouldProcessSpriteCopyRequests)\n    {\n        u8 i = 0;\n\n        while (sSpriteCopyRequestCount > 0)\n        {\n            CpuCopy16(sSpriteCopyRequests[i].src, sSpriteCopyRequests[i].dest, sSpriteCopyRequests[i].size);\n            sSpriteCopyRequestCount--;\n            i++;\n        }\n\n        sShouldProcessSpriteCopyRequests = FALSE;\n    }",
  },
  "RequestSpriteCopy": {
    returnType: "void",
    params: "const u8 *src, u8 *dest, u16 size",
    lineCount: 7,
    bodyC: "if (sSpriteCopyRequestCount < MAX_SPRITE_COPY_REQUESTS)\n    {\n        sSpriteCopyRequests[sSpriteCopyRequestCount].src = src;\n        sSpriteCopyRequests[sSpriteCopyRequestCount].dest = dest;\n        sSpriteCopyRequests[sSpriteCopyRequestCount].size = size;\n        sSpriteCopyRequestCount++;\n    }",
  },
  "RequestSpriteFrameImageCopy": {
    returnType: "void",
    params: "u16 index, u16 tileNum, const struct SpriteFrameImage *images",
    lineCount: 7,
    bodyC: "if (sSpriteCopyRequestCount < MAX_SPRITE_COPY_REQUESTS)\n    {\n        sSpriteCopyRequests[sSpriteCopyRequestCount].src = images[index].data;\n        sSpriteCopyRequests[sSpriteCopyRequestCount].dest = (u8 *)OBJ_VRAM0 + TILE_SIZE_4BPP * tileNum;\n        sSpriteCopyRequests[sSpriteCopyRequestCount].size = images[index].size;\n        sSpriteCopyRequestCount++;\n    }",
  },
  "ResetAffineAnimData": {
    returnType: "void",
    params: "void",
    callsTo: ["AffineAnimStateReset","ResetOamMatrices"],
    lineCount: 6,
    bodyC: "u8 i;\n\n    gAffineAnimsDisabled = FALSE;\n    gOamMatrixAllocBitmap = 0;\n\n    ResetOamMatrices();\n\n    for (i = 0; i < OAM_MATRIX_COUNT; i++)\n        AffineAnimStateReset(i);",
  },
  "ResetAllSprites": {
    returnType: "void",
    params: "void",
    callsTo: ["ResetSprite"],
    lineCount: 7,
    bodyC: "u8 i;\n\n    for (i = 0; i < MAX_SPRITES; i++)\n    {\n        ResetSprite(&gSprites[i]);\n        sSpriteOrder[i] = i;\n    }\n\n    ResetSprite(&gSprites[i]);",
  },
  "ResetOamMatrices": {
    returnType: "void",
    params: "void",
    lineCount: 8,
    bodyC: "u8 i;\n    for (i = 0; i < OAM_MATRIX_COUNT; i++)\n    {\n         \n        gOamMatrices[i].a = 0x0100;\n        gOamMatrices[i].b = 0x0000;\n        gOamMatrices[i].c = 0x0000;\n        gOamMatrices[i].d = 0x0100;\n    }",
  },
  "ResetOamRange": {
    returnType: "void",
    params: "u8 start, u8 end",
    lineCount: 3,
    bodyC: "u8 i;\n    for (i = start; i < end; i++)\n        gMain.oamBuffer[i] = *(struct OamData *)&gDummyOamData;",
  },
  "ResetSprite": {
    returnType: "void",
    params: "struct Sprite *sprite",
    lineCount: 1,
    bodyC: "*sprite = sDummySprite;",
  },
  "ResetSpriteData": {
    returnType: "void",
    params: "void",
    callsTo: ["AllocSpriteTiles","ClearSpriteCopyRequests","FreeSpriteTileRanges","ResetAffineAnimData","ResetAllSprites","ResetOamRange"],
    lineCount: 10,
    bodyC: "ResetOamRange(0, 128);\n    ResetAllSprites();\n    ClearSpriteCopyRequests();\n    ResetAffineAnimData();\n    FreeSpriteTileRanges();\n    gOamLimit = 64;\n    gReservedSpriteTileCount = 0;\n    AllocSpriteTiles(0);\n    gSpriteCoordOffsetX = 0;\n    gSpriteCoordOffsetY = 0;",
  },
  "SeekSpriteAnim": {
    returnType: "void",
    params: "struct Sprite *sprite, u8 animCmdIndex",
    callsTo: ["ContinueAnim"],
    lineCount: 10,
    bodyC: "u8 temp = sprite->animPaused;\n    sprite->animCmdIndex = animCmdIndex - 1;\n    sprite->animDelayCounter = 0;\n    sprite->animBeginning = FALSE;\n    sprite->animEnded = FALSE;\n    sprite->animPaused = FALSE;\n    ContinueAnim(sprite);\n    if (sprite->animDelayCounter)\n        sprite->animDelayCounter++;\n    sprite->animPaused = temp;",
  },
  "SetOamMatrix": {
    returnType: "void",
    params: "u8 matrixNum, u16 a, u16 b, u16 c, u16 d",
    lineCount: 4,
    bodyC: "gOamMatrices[matrixNum].a = a;\n    gOamMatrices[matrixNum].b = b;\n    gOamMatrices[matrixNum].c = c;\n    gOamMatrices[matrixNum].d = d;",
  },
  "SetOamMatrixRotationScaling": {
    returnType: "void",
    params: "u8 matrixNum, s16 xScale, s16 yScale, u16 rotation",
    callsTo: ["ConvertScaleParam","CopyOamMatrix","ObjAffineSet"],
    lineCount: 7,
    bodyC: "struct ObjAffineSrcData srcData;\n    struct OamMatrix matrix;\n    srcData.xScale = ConvertScaleParam(xScale);\n    srcData.yScale = ConvertScaleParam(yScale);\n    srcData.rotation = rotation;\n    ObjAffineSet(&srcData, &matrix, 1, 2);\n    CopyOamMatrix(matrixNum, &matrix);",
  },
  "SetSpriteMatrixAnchor": {
    returnType: "void",
    params: "struct Sprite *sprite, s16 x, s16 y",
    lineCount: 3,
    bodyC: "sprite->sAnchorX = x;\n    sprite->sAnchorY = y;\n    sprite->anchored = TRUE;",
  },
  "SetSpriteOamFlipBits": {
    returnType: "void",
    params: "struct Sprite *sprite, u8 hFlip, u8 vFlip",
    lineCount: 3,
    bodyC: "sprite->oam.matrixNum &= 0x7;\n    sprite->oam.matrixNum |= (((hFlip ^ sprite->hFlip) & 1) << 3);\n    sprite->oam.matrixNum |= (((vFlip ^ sprite->vFlip) & 1) << 4);",
  },
  "SetSpriteSheetFrameTileNum": {
    returnType: "void",
    params: "struct Sprite *sprite",
    lineCount: 7,
    bodyC: "if (sprite->usingSheet)\n    {\n        s16 tileOffset = sprite->anims[sprite->animNum][sprite->animCmdIndex].frame.imageValue;\n        if (tileOffset < 0)\n            tileOffset = 0;\n        sprite->oam.tileNum = sprite->sheetTileStart + tileOffset;\n    }",
  },
  "SetSubspriteTables": {
    returnType: "void",
    params: "struct Sprite *sprite, const struct SubspriteTable *subspriteTables",
    lineCount: 3,
    bodyC: "sprite->subspriteTables = subspriteTables;\n    sprite->subspriteTableNum = 0;\n    sprite->subspriteMode = SUBSPRITES_ON;",
  },
  "SortSprites": {
    returnType: "void",
    params: "void",
    lineCount: 78,
    bodyC: "u8 i;\n    for (i = 1; i < MAX_SPRITES; i++)\n    {\n        u8 j = i;\n        struct Sprite *sprite1 = &gSprites[sSpriteOrder[i - 1]];\n        struct Sprite *sprite2 = &gSprites[sSpriteOrder[i]];\n        u16 sprite1Priority = sSpritePriorities[sSpriteOrder[i - 1]];\n        u16 sprite2Priority = sSpritePriorities[sSpriteOrder[i]];\n        s16 sprite1Y = sprite1->oam.y;\n        s16 sprite2Y = sprite2->oam.y;\n\n        if (sprite1Y >= DISPLAY_HEIGHT)\n            sprite1Y = sprite1Y - 256;\n\n        if (sprite2Y >= DISPLAY_HEIGHT)\n            sprite2Y = sprite2Y - 256;\n\n        if (sprite1->oam.affineMode == ST_OAM_AFFINE_DOUBLE\n         && sprite1->oam.size == ST_OAM_SIZE_3)\n        {\n            u32 shape = sprite1->oam.shape;\n            if (shape == ST_OAM_SQUARE || shape == ST_OAM_V_RECTANGLE)\n            {\n                if (sprite1Y > 128)\n                    sprite1Y = sprite1Y - 256;\n            }\n        }\n\n        if (sprite2->oam.affineMode == ST_OAM_AFFINE_DOUBLE\n         && sprite2->oam.size == ST_OAM_SIZE_3)\n        {\n            u32 shape = sprite2->oam.shape;\n            if (shape == ST_OAM_SQUARE || shape == ST_OAM_V_RECTANGLE)\n            {\n                if (sprite2Y > 128)\n                    sprite2Y = sprite2Y - 256;\n            }\n        }\n\n        while (j > 0\n            && ((sprite1Priority > sprite2Priority)\n             || (sprite1Priority == sprite2Priority && sprite1Y < sprite2Y)))\n        {\n            u8 temp = sSpriteOrder[j];\n            sSpriteOrder[j] = sSpriteOrder[j - 1];\n            sSpriteOrder[j - 1] = temp;\n\n             \n             \n             \n             \n            j--;\n#ifdef UBFIX\n            if (j == 0)\n                break;\n#endif\n\n            sprite1 = &gSprites[sSpriteOrder[j - 1]];\n            sprite2 = &gSprites[sSpriteOrder[j]];\n            sprite1Priority = sSpritePriorities[sSpriteOrder[j - 1]];\n            sprite2Priority = sSpritePriorities[sSpriteOrder[j]];\n            sprite1Y = sprite1->oam.y;\n            sprite2Y = sprite2->oam.y;\n\n            if (sprite1Y >= DISPLAY_HEIGHT)\n                sprite1Y = sprite1Y - 256;\n\n            if (sprite2Y >= DISPLAY_HEIGHT)\n                sprite2Y = sprite2Y - 256;\n\n            if (sprite1->oam.affineMode == ST_OAM_AFFINE_DOUBLE\n             && sprite1->oam.size == ST_OAM_SIZE_3)\n            {\n                u32 shape = sprite1->oam.shape;\n                if (shape == ST_OAM_SQUARE || shape == ST_OAM_V_RECTANGLE)\n                {\n                    if (sprite1Y > 128)\n                        sprite1Y = sprite1Y - 256;\n                }\n            }\n\n            if (sprite2->oam.affineMode == ST_OAM_AFFINE_DOUBLE\n             && sprite2->oam.size == ST_OAM_SIZE_3)\n            {\n                u32 shape = sprite2->oam.shape;\n                if (shape == ST_OAM_SQUARE || shape == ST_OAM_V_RECTANGLE)\n                {\n                    if (sprite2Y > 128)\n                        sprite2Y = sprite2Y - 256;\n                }\n            }\n        }\n    }",
  },
  "SpriteCallbackDummy": {
    returnType: "void",
    params: "struct Sprite *sprite",
    lineCount: 0,
    bodyC: "",
  },
  "SpriteTileAllocBitmapOp": {
    returnType: "u8",
    params: "u16 bit, u8 op",
    lineCount: 20,
    bodyC: "u8 index = bit / 8;\n    u8 shift = bit % 8;\n    u8 val = bit % 8;\n    u8 retVal = 0;\n\n    if (op == 0)\n    {\n        val = ~(1 << val);\n        sSpriteTileAllocBitmap[index] &= val;\n    }\n    else if (op == 1)\n    {\n        val = (1 << val);\n        sSpriteTileAllocBitmap[index] |= val;\n    }\n    else\n    {\n        retVal = 1 << shift;\n        retVal &= sSpriteTileAllocBitmap[index];\n    }\n\n    return retVal;",
  },
  "StartSpriteAffineAnim": {
    returnType: "void",
    params: "struct Sprite *sprite, u8 animNum",
    callsTo: ["AffineAnimStateStartAnim","GetSpriteMatrixNum"],
    lineCount: 4,
    bodyC: "u8 matrixNum = GetSpriteMatrixNum(sprite);\n    AffineAnimStateStartAnim(matrixNum, animNum);\n    sprite->affineAnimBeginning = TRUE;\n    sprite->affineAnimEnded = FALSE;",
  },
  "StartSpriteAffineAnimIfDifferent": {
    returnType: "void",
    params: "struct Sprite *sprite, u8 animNum",
    callsTo: ["GetSpriteMatrixNum","StartSpriteAffineAnim"],
    lineCount: 3,
    bodyC: "u8 matrixNum = GetSpriteMatrixNum(sprite);\n    if (sAffineAnimStates[matrixNum].animNum != animNum)\n        StartSpriteAffineAnim(sprite, animNum);",
  },
  "StartSpriteAnim": {
    returnType: "void",
    params: "struct Sprite *sprite, u8 animNum",
    lineCount: 3,
    bodyC: "sprite->animNum = animNum;\n    sprite->animBeginning = TRUE;\n    sprite->animEnded = FALSE;",
  },
  "StartSpriteAnimIfDifferent": {
    returnType: "void",
    params: "struct Sprite *sprite, u8 animNum",
    callsTo: ["StartSpriteAnim"],
    lineCount: 2,
    bodyC: "if (sprite->animNum != animNum)\n        StartSpriteAnim(sprite, animNum);",
  },
  "UpdateOamCoords": {
    returnType: "void",
    params: "void",
    lineCount: 18,
    bodyC: "u8 i;\n    for (i = 0; i < MAX_SPRITES; i++)\n    {\n        struct Sprite *sprite = &gSprites[i];\n        if (sprite->inUse && !sprite->invisible)\n        {\n            if (sprite->coordOffsetEnabled)\n            {\n                sprite->oam.x = sprite->x + sprite->x2 + sprite->centerToCornerVecX + gSpriteCoordOffsetX;\n                sprite->oam.y = sprite->y + sprite->y2 + sprite->centerToCornerVecY + gSpriteCoordOffsetY;\n            }\n            else\n            {\n                sprite->oam.x = sprite->x + sprite->x2 + sprite->centerToCornerVecX;\n                sprite->oam.y = sprite->y + sprite->y2 + sprite->centerToCornerVecY;\n            }\n        }\n    }",
  },
  "UpdateSpriteMatrixAnchorPos": {
    returnType: "static void",
    params: "struct Sprite *sprite, s32 x, s32 y",
    callsTo: ["GetAnchorCoord"],
    lineCount: 16,
    bodyC: "s32 dimension, var1, var2;\n\n    u32 matrixNum = sprite->oam.matrixNum;\n    if (x != NO_ANCHOR)\n    {\n        dimension = sOamDimensions32[sprite->oam.shape][sprite->oam.size].width;\n        var1 = dimension << 8;\n        var2 = (dimension << 16) / gOamMatrices[matrixNum].a;\n        sprite->x2 = GetAnchorCoord(var1, var2, x);\n    }\n    if (y != NO_ANCHOR)\n    {\n        dimension = sOamDimensions32[sprite->oam.shape][sprite->oam.size].height;\n        var1 = dimension << 8;\n        var2 = (dimension << 16) / gOamMatrices[matrixNum].d;\n        sprite->y2 = GetAnchorCoord(var1, var2, y);\n    }",
  },
} as const;
