// AUTO-GENERATED from src/trainer_pokemon_sprites.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 21

export const ENGINE_FUNCTIONS = {
  "AssignSpriteAnimsTable": {
    returnType: "static void",
    params: "bool8 isTrainer",
    lineCount: 4,
    bodyC: "if (!isTrainer)\n        sCreatingSpriteTemplate.anims = gAnims_MonPic;\n    else\n        sCreatingSpriteTemplate.anims = gTrainerFrontAnimsPtrTable[0];",
  },
  "CreateMonPicSprite": {
    returnType: "static u16",
    params: "u16 species, u32 otId, u32 personality, bool8 isFrontPic, s16 x, s16 y, u8 paletteSlot, u16 paletteTag, bool8 ignoreDeoxys",
    callsTo: ["CreatePicSprite"],
    lineCount: 1,
    bodyC: "return CreatePicSprite(species, otId, personality, isFrontPic, x, y, paletteSlot, paletteTag, FALSE, ignoreDeoxys);",
  },
  "CreateMonPicSprite_Affine": {
    returnType: "u16",
    params: "u16 species, u32 otId, u32 personality, u8 flags, s16 x, s16 y, u8 paletteSlot, u16 paletteTag",
    callsTo: ["Alloc","CreateSprite","DecompressPic","Free","LoadPicPaletteByTagOrSlot"],
    lineCount: 69,
    bodyC: "u8 *framePics;\n    struct SpriteFrameImage *images;\n    int j;\n    u8 i;\n    u8 spriteId;\n    u8 type;\n\n    for (i = 0; i < PICS_COUNT; i++)\n    {\n        if (!sSpritePics[i].active)\n            break;\n    }\n    if (i == PICS_COUNT)\n        return 0xFFFF;\n\n    framePics = Alloc(MON_PIC_SIZE * MAX_MON_PIC_FRAMES);\n    if (!framePics)\n        return 0xFFFF;\n\n    if (flags & F_MON_PIC_NO_AFFINE)\n    {\n        flags &= ~F_MON_PIC_NO_AFFINE;\n        type = MON_PIC_AFFINE_NONE;\n    }\n    else\n    {\n        type = flags;\n    }\n    images = Alloc(sizeof(struct SpriteFrameImage) * MAX_MON_PIC_FRAMES);\n    if (!images)\n    {\n        Free(framePics);\n        return 0xFFFF;\n    }\n    if (DecompressPic(species, personality, flags, framePics, FALSE, FALSE))\n    {\n         \n        return 0xFFFF;\n    }\n    for (j = 0; j < MAX_MON_PIC_FRAMES; j ++)\n    {\n        images[j].data = framePics + MON_PIC_SIZE * j;\n        images[j].size = MON_PIC_SIZE;\n    }\n    sCreatingSpriteTemplate.tileTag = TAG_NONE;\n    sCreatingSpriteTemplate.anims = gMonFrontAnimsPtrTable[species];\n    sCreatingSpriteTemplate.images = images;\n    if (type == MON_PIC_AFFINE_FRONT)\n    {\n        sCreatingSpriteTemplate.affineAnims = gAffineAnims_BattleSpriteOpponentSide;\n        sCreatingSpriteTemplate.oam = &sOamData_Affine;\n    }\n    else if (type == MON_PIC_AFFINE_BACK)\n    {\n        sCreatingSpriteTemplate.affineAnims = gAffineAnims_BattleSpritePlayerSide;\n        sCreatingSpriteTemplate.oam = &sOamData_Affine;\n    }\n    else  \n    {\n        sCreatingSpriteTemplate.oam = &sOamData_Normal;\n        sCreatingSpriteTemplate.affineAnims = gDummySpriteAffineAnimTable;\n    }\n    sCreatingSpriteTemplate.callback = DummyPicSpriteCallback;\n    LoadPicPaletteByTagOrSlot(species, otId, personality, paletteSlot, paletteTag, FALSE);\n    spriteId = CreateSprite(&sCreatingSpriteTemplate, x, y, 0);\n    if (paletteTag == TAG_NONE)\n        gSprites[spriteId].oam.paletteNum = paletteSlot;\n    sSpritePics[i].frames = framePics;\n    sSpritePics[i].images = images;\n    sSpritePics[i].paletteTag = paletteTag;\n    sSpritePics[i].spriteId = spriteId;\n    sSpritePics[i].active = TRUE;\n    return spriteId;",
  },
  "CreateMonPicSprite_HandleDeoxys": {
    returnType: "u16",
    params: "u16 species, u32 otId, u32 personality, bool8 isFrontPic, s16 x, s16 y, u8 paletteSlot, u16 paletteTag",
    callsTo: ["CreateMonPicSprite"],
    lineCount: 1,
    bodyC: "return CreateMonPicSprite(species, otId, personality, isFrontPic, x, y, paletteSlot, paletteTag, FALSE);",
  },
  "CreatePicSprite": {
    returnType: "static u16",
    params: "u16 species, u32 otId, u32 personality, bool8 isFrontPic, s16 x, s16 y, u8 paletteSlot, u16 paletteTag, bool8 isTrainer, bool8 ignoreDeoxys",
    callsTo: ["Alloc","AssignSpriteAnimsTable","CreateSprite","DecompressPic","Free","LoadPicPaletteByTagOrSlot"],
    lineCount: 46,
    bodyC: "u8 i;\n    u8 *framePics;\n    struct SpriteFrameImage *images;\n    int j;\n    u8 spriteId;\n\n    for (i = 0; i < PICS_COUNT; i ++)\n    {\n        if (!sSpritePics[i].active)\n            break;\n    }\n    if (i == PICS_COUNT)\n        return 0xFFFF;\n\n    framePics = Alloc(PIC_SPRITE_SIZE * MAX_PIC_FRAMES);\n    if (!framePics)\n        return 0xFFFF;\n\n    images = Alloc(sizeof(struct SpriteFrameImage) * MAX_PIC_FRAMES);\n    if (!images)\n    {\n        Free(framePics);\n        return 0xFFFF;\n    }\n    if (DecompressPic(species, personality, isFrontPic, framePics, isTrainer, ignoreDeoxys))\n    {\n         \n        return 0xFFFF;\n    }\n    for (j = 0; j < MAX_PIC_FRAMES; j ++)\n    {\n        images[j].data = framePics + PIC_SPRITE_SIZE * j;\n        images[j].size = PIC_SPRITE_SIZE;\n    }\n    sCreatingSpriteTemplate.tileTag = TAG_NONE;\n    sCreatingSpriteTemplate.oam = &sOamData_Normal;\n    AssignSpriteAnimsTable(isTrainer);\n    sCreatingSpriteTemplate.images = images;\n    sCreatingSpriteTemplate.affineAnims = gDummySpriteAffineAnimTable;\n    sCreatingSpriteTemplate.callback = DummyPicSpriteCallback;\n    LoadPicPaletteByTagOrSlot(species, otId, personality, paletteSlot, paletteTag, isTrainer);\n    spriteId = CreateSprite(&sCreatingSpriteTemplate, x, y, 0);\n    if (paletteTag == TAG_NONE)\n        gSprites[spriteId].oam.paletteNum = paletteSlot;\n    sSpritePics[i].frames = framePics;\n    sSpritePics[i].images = images;\n    sSpritePics[i].paletteTag = paletteTag;\n    sSpritePics[i].spriteId = spriteId;\n    sSpritePics[i].active = TRUE;\n    return spriteId;",
  },
  "CreatePicSprite_HandleDeoxys": {
    returnType: "static u16",
    params: "u16 species, u32 otId, u32 personality, bool8 isFrontPic, s16 x, s16 y, u8 paletteSlot, u16 paletteTag, bool8 isTrainer",
    callsTo: ["CreatePicSprite"],
    lineCount: 1,
    bodyC: "return CreatePicSprite(species, otId, personality, isFrontPic, x, y, paletteSlot, paletteTag, isTrainer, FALSE);",
  },
  "CreateTrainerCardMonIconSprite": {
    returnType: "u16",
    params: "u16 species, u32 otId, u32 personality, bool8 isFrontPic, u16 destX, u16 destY, u8 paletteSlot, u8 windowId",
    callsTo: ["CreateTrainerCardSprite"],
    lineCount: 1,
    bodyC: "return CreateTrainerCardSprite(species, otId, personality, isFrontPic, destX, destY, paletteSlot, windowId, FALSE);",
  },
  "CreateTrainerCardSprite": {
    returnType: "static u16",
    params: "u16 species, u32 otId, u32 personality, bool8 isFrontPic, u16 destX, u16 destY, u8 paletteSlot, u8 windowId, bool8 isTrainer",
    callsTo: ["Alloc","BlitBitmapRectToWindow","DecompressPic_HandleDeoxys","Free","LoadPicPaletteBySlot"],
    lineCount: 10,
    bodyC: "u8 *framePics;\n\n    framePics = Alloc(TRAINER_PIC_SIZE * MAX_TRAINER_PIC_FRAMES);\n    if (framePics && !DecompressPic_HandleDeoxys(species, personality, isFrontPic, framePics, isTrainer))\n    {\n        BlitBitmapRectToWindow(windowId, framePics, 0, 0, TRAINER_PIC_WIDTH, TRAINER_PIC_HEIGHT, destX, destY, TRAINER_PIC_WIDTH, TRAINER_PIC_HEIGHT);\n        LoadPicPaletteBySlot(species, otId, personality, paletteSlot, isTrainer);\n        Free(framePics);\n        return 0;\n    }\n    return 0xFFFF;",
  },
  "CreateTrainerCardTrainerPicSprite": {
    returnType: "u16",
    params: "u16 species, bool8 isFrontPic, u16 destX, u16 destY, u8 paletteSlot, u8 windowId",
    callsTo: ["CreateTrainerCardSprite"],
    lineCount: 1,
    bodyC: "return CreateTrainerCardSprite(species, 0, 0, isFrontPic, destX, destY, paletteSlot, windowId, TRUE);",
  },
  "CreateTrainerPicSprite": {
    returnType: "u16",
    params: "u16 species, bool8 isFrontPic, s16 x, s16 y, u8 paletteSlot, u16 paletteTag",
    callsTo: ["CreatePicSprite_HandleDeoxys"],
    lineCount: 1,
    bodyC: "return CreatePicSprite_HandleDeoxys(species, 0, 0, isFrontPic, x, y, paletteSlot, paletteTag, TRUE);",
  },
  "DecompressPic": {
    returnType: "static bool16",
    params: "u16 picId, u32 personality, bool8 isFrontPic, u8 *dest, bool8 isTrainer, bool8 ignoreDeoxys",
    callsTo: ["CpuCopy32","DecompressPicFromTable","LoadSpecialPokePic","LoadSpecialPokePic_DontHandleDeoxys"],
    lineCount: 35,
    bodyC: "if (!isTrainer)\n    {\n        u16 species = picId;\n        if (isFrontPic)\n        {\n            if (!ignoreDeoxys)\n                LoadSpecialPokePic(&gMonFrontPicTable[species], dest, species, personality, isFrontPic);\n            else\n                LoadSpecialPokePic_DontHandleDeoxys(&gMonFrontPicTable[species], dest, species, personality, isFrontPic);\n        }\n        else\n        {\n            if (!ignoreDeoxys)\n                LoadSpecialPokePic(&gMonBackPicTable[species], dest, species, personality, isFrontPic);\n            else\n                LoadSpecialPokePic_DontHandleDeoxys(&gMonBackPicTable[species], dest, species, personality, isFrontPic);\n        }\n    }\n    else\n    {\n        u16 trainerPicId = picId;\n        if (isFrontPic)\n        {\n            DecompressPicFromTable(&gTrainerFrontPicTable[trainerPicId], dest, trainerPicId);\n        }\n        else\n        {\n#ifdef BUGFIX\n            CpuCopy32(gTrainerBackPicTable[trainerPicId].data, dest, gTrainerBackPicTable[trainerPicId].size);\n#else\n             \n             \n             \n             \n            DecompressPicFromTable(&gTrainerBackPicTable[trainerPicId], dest, trainerPicId);\n#endif\n        }\n    }\n    return FALSE;",
  },
  "DecompressPic_HandleDeoxys": {
    returnType: "static bool16",
    params: "u16 species, u32 personality, bool8 isFrontPic, u8 *dest, bool8 isTrainer",
    callsTo: ["DecompressPic"],
    lineCount: 1,
    bodyC: "return DecompressPic(species, personality, isFrontPic, dest, isTrainer, FALSE);",
  },
  "DummyPicSpriteCallback": {
    returnType: "static void",
    params: "struct Sprite *sprite",
    lineCount: 0,
    bodyC: "",
  },
  "FreeAndDestroyMonPicSprite": {
    returnType: "u16",
    params: "u16 spriteId",
    callsTo: ["FreeAndDestroyPicSpriteInternal"],
    lineCount: 1,
    bodyC: "return FreeAndDestroyPicSpriteInternal(spriteId);",
  },
  "FreeAndDestroyPicSpriteInternal": {
    returnType: "static u16",
    params: "u16 spriteId",
    callsTo: ["DestroySprite","Free","FreeSpritePaletteByTag","GetSpritePaletteTagByPaletteNum"],
    lineCount: 19,
    bodyC: "u8 i;\n    u8 *framePics;\n    struct SpriteFrameImage *images;\n\n    for (i = 0; i < PICS_COUNT; i ++)\n    {\n        if (sSpritePics[i].spriteId == spriteId)\n            break;\n    }\n    if (i == PICS_COUNT)\n        return 0xFFFF;\n\n    framePics = sSpritePics[i].frames;\n    images = sSpritePics[i].images;\n    if (sSpritePics[i].paletteTag != TAG_NONE)\n        FreeSpritePaletteByTag(GetSpritePaletteTagByPaletteNum(gSprites[spriteId].oam.paletteNum));\n    DestroySprite(&gSprites[spriteId]);\n    Free(framePics);\n    Free(images);\n    sSpritePics[i] = sDummyPicData;\n    return 0;",
  },
  "FreeAndDestroyTrainerPicSprite": {
    returnType: "u16",
    params: "u16 spriteId",
    callsTo: ["FreeAndDestroyPicSpriteInternal"],
    lineCount: 1,
    bodyC: "return FreeAndDestroyPicSpriteInternal(spriteId);",
  },
  "LoadPicPaletteBySlot": {
    returnType: "static void",
    params: "u16 species, u32 otId, u32 personality, u8 paletteSlot, bool8 isTrainer",
    callsTo: ["GetMonSpritePalFromSpeciesAndPersonality","LoadCompressedPalette","PLTT_ID"],
    lineCount: 4,
    bodyC: "if (!isTrainer)\n        LoadCompressedPalette(GetMonSpritePalFromSpeciesAndPersonality(species, otId, personality), PLTT_ID(paletteSlot), PLTT_SIZE_4BPP);\n    else\n        LoadCompressedPalette(gTrainerFrontPicPaletteTable[species].data, PLTT_ID(paletteSlot), PLTT_SIZE_4BPP);",
  },
  "LoadPicPaletteByTagOrSlot": {
    returnType: "static void",
    params: "u16 species, u32 otId, u32 personality, u8 paletteSlot, u16 paletteTag, bool8 isTrainer",
    callsTo: ["GetMonSpritePalFromSpeciesAndPersonality","GetMonSpritePalStructFromOtIdPersonality","LoadCompressedPalette","LoadCompressedSpritePalette","OBJ_PLTT_ID"],
    lineCount: 26,
    bodyC: "if (!isTrainer)\n    {\n        if (paletteTag == TAG_NONE)\n        {\n            sCreatingSpriteTemplate.paletteTag = TAG_NONE;\n            LoadCompressedPalette(GetMonSpritePalFromSpeciesAndPersonality(species, otId, personality), OBJ_PLTT_ID(paletteSlot), PLTT_SIZE_4BPP);\n        }\n        else\n        {\n            sCreatingSpriteTemplate.paletteTag = paletteTag;\n            LoadCompressedSpritePalette(GetMonSpritePalStructFromOtIdPersonality(species, otId, personality));\n        }\n    }\n    else\n    {\n        if (paletteTag == TAG_NONE)\n        {\n            sCreatingSpriteTemplate.paletteTag = TAG_NONE;\n            LoadCompressedPalette(gTrainerFrontPicPaletteTable[species].data, OBJ_PLTT_ID(paletteSlot), PLTT_SIZE_4BPP);\n        }\n        else\n        {\n            sCreatingSpriteTemplate.paletteTag = paletteTag;\n            LoadCompressedSpritePalette(&gTrainerFrontPicPaletteTable[species]);\n        }\n    }",
  },
  "LoadPicSpriteInWindow": {
    returnType: "static u16",
    params: "u16 species, u32 otId, u32 personality, bool8 isFrontPic, u8 paletteSlot, u8 windowId, bool8 isTrainer",
    callsTo: ["DecompressPic_HandleDeoxys","GetWindowAttribute","LoadPicPaletteBySlot"],
    lineCount: 4,
    bodyC: "if (DecompressPic_HandleDeoxys(species, personality, isFrontPic, (u8 *)GetWindowAttribute(windowId, WINDOW_TILE_DATA), FALSE))\n        return 0xFFFF;\n\n    LoadPicPaletteBySlot(species, otId, personality, paletteSlot, isTrainer);\n    return 0;",
  },
  "PlayerGenderToFrontTrainerPicId_Debug": {
    returnType: "u16",
    params: "u8 gender, bool8 getClass",
    lineCount: 8,
    bodyC: "if (getClass == TRUE)\n    {\n        if (gender != MALE)\n            return gFacilityClassToPicIndex[FACILITY_CLASS_MAY];\n        else\n            return gFacilityClassToPicIndex[FACILITY_CLASS_BRENDAN];\n    }\n    return gender;",
  },
  "ResetAllPicSprites": {
    returnType: "bool16",
    params: "void",
    lineCount: 4,
    bodyC: "int i;\n\n    for (i = 0; i < PICS_COUNT; i ++)\n        sSpritePics[i] = sDummyPicData;\n\n    return FALSE;",
  },
} as const;
