// AUTO-GENERATED from src/window.c by extract-engine-helpers.mjs
// Do not edit — re-run `node scripts/extract-engine-helpers.mjs` to refresh.
//
// Generated: 2026-04-27
// Functions: 29

export const ENGINE_FUNCTIONS = {
  "AddWindow": {
    returnType: "u16",
    params: "const struct WindowTemplate *template",
    callsTo: ["AllocZeroed","BgTileAllocOp","Free","GetBgAttribute","GetNumActiveWindowsOnBg","SetBgTilemapBuffer"],
    lineCount: 53,
    bodyC: "u16 win;\n    u8 bgLayer;\n    int allocatedBaseBlock;\n    u16 attrib;\n    u8 *allocatedTilemapBuffer;\n    int i;\n\n    for (win = 0; win < WINDOWS_MAX; ++win)\n    {\n        if ((bgLayer = gWindows[win].window.bg) == 0xFF)\n            break;\n    }\n\n    if (win == WINDOWS_MAX)\n        return WINDOW_NONE;\n\n    bgLayer = template->bg;\n    allocatedBaseBlock = 0;\n\n    if (gWindowTileAutoAllocEnabled == TRUE)\n    {\n        allocatedBaseBlock = BgTileAllocOp(bgLayer, 0, template->width * template->height, 0);\n\n        if (allocatedBaseBlock == -1)\n            return WINDOW_NONE;\n    }\n\n    if (gWindowBgTilemapBuffers[bgLayer] == NULL)\n    {\n        attrib = GetBgAttribute(bgLayer, BG_ATTR_METRIC);\n\n        if (attrib != 0xFFFF)\n        {\n            allocatedTilemapBuffer = AllocZeroed(attrib);\n\n            if (allocatedTilemapBuffer == NULL)\n                return WINDOW_NONE;\n\n            for (i = 0; i < attrib; ++i)\n                allocatedTilemapBuffer[i] = 0;\n\n            gWindowBgTilemapBuffers[bgLayer] = allocatedTilemapBuffer;\n            SetBgTilemapBuffer(bgLayer, allocatedTilemapBuffer);\n        }\n    }\n\n    allocatedTilemapBuffer = AllocZeroed((u16)(32 * (template->width * template->height)));\n\n    if (allocatedTilemapBuffer == NULL)\n    {\n        if ((GetNumActiveWindowsOnBg(bgLayer) == 0) && (gWindowBgTilemapBuffers[bgLayer] != DummyWindowBgTilemap))\n        {\n            Free(gWindowBgTilemapBuffers[bgLayer]);\n            gWindowBgTilemapBuffers[bgLayer] = allocatedTilemapBuffer;\n        }\n        return WINDOW_NONE;\n    }\n\n    gWindows[win].tileData = allocatedTilemapBuffer;\n    gWindows[win].window = *template;\n\n    if (gWindowTileAutoAllocEnabled == TRUE)\n    {\n        gWindows[win].window.baseBlock = allocatedBaseBlock;\n        BgTileAllocOp(bgLayer, allocatedBaseBlock, gWindows[win].window.width * gWindows[win].window.height, 1);\n    }\n\n    return win;",
  },
  "AddWindow8Bit": {
    returnType: "u16",
    params: "const struct WindowTemplate *template",
    callsTo: ["Alloc","Free","GetBgAttribute","GetNumActiveWindowsOnBg8Bit","SetBgTilemapBuffer"],
    lineCount: 42,
    bodyC: "u16 windowId;\n    u8 *memAddress;\n    u8 bgLayer;\n\n    for (windowId = 0; windowId < WINDOWS_MAX; windowId++)\n    {\n        if (gWindows[windowId].window.bg == 0xFF)\n            break;\n    }\n    if (windowId == WINDOWS_MAX)\n        return WINDOW_NONE;\n    bgLayer = template->bg;\n    if (gWindowBgTilemapBuffers[bgLayer] == NULL)\n    {\n        u16 attribute = GetBgAttribute(bgLayer, BG_ATTR_METRIC);\n        if (attribute != 0xFFFF)\n        {\n            s32 i;\n            memAddress = Alloc(attribute);\n            if (memAddress == NULL)\n                return WINDOW_NONE;\n            for (i = 0; i < attribute; i++)  \n                memAddress[i] = 0;\n            gWindowBgTilemapBuffers[bgLayer] = memAddress;\n            SetBgTilemapBuffer(bgLayer, memAddress);\n        }\n    }\n    memAddress = Alloc((u16)(64 * (template->width * template->height)));\n    if (memAddress == NULL)\n    {\n        if (GetNumActiveWindowsOnBg8Bit(bgLayer) == 0 && gWindowBgTilemapBuffers[bgLayer] != DummyWindowBgTilemap8Bit)\n        {\n            Free(gWindowBgTilemapBuffers[bgLayer]);\n            gWindowBgTilemapBuffers[bgLayer] = NULL;\n        }\n        return WINDOW_NONE;\n    }\n    else\n    {\n        gWindows[windowId].tileData = memAddress;\n        gWindows[windowId].window = *template;\n        return windowId;\n    }",
  },
  "AddWindowWithoutTileMap": {
    returnType: "int",
    params: "const struct WindowTemplate *template",
    callsTo: ["BgTileAllocOp"],
    lineCount: 25,
    bodyC: "u16 win;\n    u8 bgLayer;\n    int allocatedBaseBlock;\n\n    for (win = 0; win < WINDOWS_MAX; ++win)\n    {\n        if (gWindows[win].window.bg == 0xFF)\n            break;\n    }\n\n    if (win == WINDOWS_MAX)\n        return WINDOW_NONE;\n\n    bgLayer = template->bg;\n    allocatedBaseBlock = 0;\n\n    if (gWindowTileAutoAllocEnabled == TRUE)\n    {\n        allocatedBaseBlock = BgTileAllocOp(bgLayer, 0, template->width * template->height, 0);\n\n        if (allocatedBaseBlock == -1)\n            return WINDOW_NONE;\n    }\n\n    gWindows[win].window = *template;\n\n    if (gWindowTileAutoAllocEnabled == TRUE)\n    {\n        gWindows[win].window.baseBlock = allocatedBaseBlock;\n        BgTileAllocOp(bgLayer, allocatedBaseBlock, gWindows[win].window.width * gWindows[win].window.height, 1);\n    }\n\n    return win;",
  },
  "BlitBitmapRectToWindow": {
    returnType: "void",
    params: "u8 windowId, const u8 *pixels, u16 srcX, u16 srcY, u16 srcWidth, int srcHeight, u16 destX, u16 destY, u16 rectWidth, u16 rectHeight",
    callsTo: ["BlitBitmapRect4Bit"],
    lineCount: 9,
    bodyC: "struct Bitmap sourceRect;\n    struct Bitmap destRect;\n\n    sourceRect.pixels = (u8 *)pixels;\n    sourceRect.width = srcWidth;\n    sourceRect.height = srcHeight;\n\n    destRect.pixels = gWindows[windowId].tileData;\n    destRect.width = 8 * gWindows[windowId].window.width;\n    destRect.height = 8 * gWindows[windowId].window.height;\n\n    BlitBitmapRect4Bit(&sourceRect, &destRect, srcX, srcY, destX, destY, rectWidth, rectHeight, 0);",
  },
  "BlitBitmapRectToWindow4BitTo8Bit": {
    returnType: "void",
    params: "u8 windowId, const u8 *pixels, u16 srcX, u16 srcY, u16 srcWidth, int srcHeight, u16 destX, u16 destY, u16 rectWidth, u16 rectHeight, u8 paletteNum",
    callsTo: ["BlitBitmapRect4BitTo8Bit"],
    lineCount: 9,
    bodyC: "struct Bitmap sourceRect;\n    struct Bitmap destRect;\n\n    sourceRect.pixels = (u8 *) pixels;\n    sourceRect.width = srcWidth;\n    sourceRect.height = srcHeight;\n\n    destRect.pixels = gWindows[windowId].tileData;\n    destRect.width = 8 * gWindows[windowId].window.width;\n    destRect.height = 8 * gWindows[windowId].window.height;\n\n    BlitBitmapRect4BitTo8Bit(&sourceRect, &destRect, srcX, srcY, destX, destY, rectWidth, rectHeight, 0, paletteNum);",
  },
  "BlitBitmapToWindow": {
    returnType: "void",
    params: "u8 windowId, const u8 *pixels, u16 x, u16 y, u16 width, u16 height",
    callsTo: ["BlitBitmapRectToWindow"],
    lineCount: 1,
    bodyC: "BlitBitmapRectToWindow(windowId, pixels, 0, 0, width, height, x, y, width, height);",
  },
  "CallWindowFunction": {
    returnType: "void",
    params: "u8 windowId, void ( *func)(u8, u8, u8, u8, u8, u8)",
    callsTo: ["func"],
    lineCount: 2,
    bodyC: "struct WindowTemplate window = gWindows[windowId].window;\n    func(window.bg, window.tilemapLeft, window.tilemapTop, window.width, window.height, window.paletteNum);",
  },
  "ClearWindowTilemap": {
    returnType: "void",
    params: "u8 windowId",
    callsTo: ["FillBgTilemapBufferRect"],
    lineCount: 9,
    bodyC: "struct Window windowLocal = gWindows[windowId];\n\n    FillBgTilemapBufferRect(\n        windowLocal.window.bg,\n        gTransparentTileNumber,\n        windowLocal.window.tilemapLeft,\n        windowLocal.window.tilemapTop,\n        windowLocal.window.width,\n        windowLocal.window.height,\n        windowLocal.window.paletteNum);",
  },
  "CopyToWindowPixelBuffer": {
    returnType: "void",
    params: "u8 windowId, const void *src, u16 size, u16 tileOffset",
    callsTo: ["CpuCopy16","LZ77UnCompWram"],
    lineCount: 4,
    bodyC: "if (size != 0)\n        CpuCopy16(src, gWindows[windowId].tileData + (32 * tileOffset), size);\n    else\n        LZ77UnCompWram(src, gWindows[windowId].tileData + (32 * tileOffset));",
  },
  "CopyWindowRectToVram": {
    returnType: "void",
    params: "u32 windowId, u32 mode, u32 x, u32 y, u32 w, u32 h",
    callsTo: ["CopyBgTilemapBufferToVram","LoadBgTiles"],
    lineCount: 25,
    bodyC: "struct Window windowLocal;\n    int rectSize;\n    int rectPos;\n\n    if (w != 0 && h != 0)\n    {\n        windowLocal = gWindows[windowId];\n\n        rectSize = ((h - 1) * windowLocal.window.width);\n        rectSize += (windowLocal.window.width - x);\n        rectSize -= (windowLocal.window.width - (x + w));\n        rectSize *= 32;\n\n        rectPos = (y * windowLocal.window.width) + x;\n\n        switch (mode)\n        {\n        case COPYWIN_MAP:\n            CopyBgTilemapBufferToVram(windowLocal.window.bg);\n            break;\n        case COPYWIN_GFX:\n            LoadBgTiles(windowLocal.window.bg, windowLocal.tileData + (rectPos * 32), rectSize, windowLocal.window.baseBlock + rectPos);\n            break;\n        case COPYWIN_FULL:\n            LoadBgTiles(windowLocal.window.bg, windowLocal.tileData + (rectPos * 32), rectSize, windowLocal.window.baseBlock + rectPos);\n            CopyBgTilemapBufferToVram(windowLocal.window.bg);\n            break;\n        }\n    }",
  },
  "CopyWindowToVram": {
    returnType: "void",
    params: "u8 windowId, u8 mode",
    callsTo: ["CopyBgTilemapBufferToVram","LoadBgTiles"],
    lineCount: 15,
    bodyC: "struct Window windowLocal = gWindows[windowId];\n    u16 windowSize = 32 * (windowLocal.window.width * windowLocal.window.height);\n\n    switch (mode)\n    {\n    case COPYWIN_MAP:\n        CopyBgTilemapBufferToVram(windowLocal.window.bg);\n        break;\n    case COPYWIN_GFX:\n        LoadBgTiles(windowLocal.window.bg, windowLocal.tileData, windowSize, windowLocal.window.baseBlock);\n        break;\n    case COPYWIN_FULL:\n        LoadBgTiles(windowLocal.window.bg, windowLocal.tileData, windowSize, windowLocal.window.baseBlock);\n        CopyBgTilemapBufferToVram(windowLocal.window.bg);\n        break;\n    }",
  },
  "CopyWindowToVram8Bit": {
    returnType: "void",
    params: "u8 windowId, u8 mode",
    callsTo: ["CopyBgTilemapBufferToVram","LoadBgTiles"],
    lineCount: 15,
    bodyC: "sWindowPtr = &gWindows[windowId];\n    sWindowSize = 64 * (sWindowPtr->window.width * sWindowPtr->window.height);\n\n    switch (mode)\n    {\n    case COPYWIN_MAP:\n        CopyBgTilemapBufferToVram(sWindowPtr->window.bg);\n        break;\n    case COPYWIN_GFX:\n        LoadBgTiles(sWindowPtr->window.bg, sWindowPtr->tileData, sWindowSize, sWindowPtr->window.baseBlock);\n        break;\n    case COPYWIN_FULL:\n        LoadBgTiles(sWindowPtr->window.bg, sWindowPtr->tileData, sWindowSize, sWindowPtr->window.baseBlock);\n        CopyBgTilemapBufferToVram(sWindowPtr->window.bg);\n        break;\n    }",
  },
  "DummyWindowBgTilemap": {
    returnType: "static void",
    params: "void",
    lineCount: 0,
    bodyC: "",
  },
  "DummyWindowBgTilemap8Bit": {
    returnType: "static void",
    params: "void",
    lineCount: 0,
    bodyC: "",
  },
  "FillWindowPixelBuffer": {
    returnType: "void",
    params: "u8 windowId, u8 fillValue",
    callsTo: ["CpuFastFill8"],
    lineCount: 2,
    bodyC: "int fillSize = gWindows[windowId].window.width * gWindows[windowId].window.height;\n    CpuFastFill8(fillValue, gWindows[windowId].tileData, 32 * fillSize);",
  },
  "FillWindowPixelBuffer8Bit": {
    returnType: "void",
    params: "u8 windowId, u8 fillValue",
    lineCount: 5,
    bodyC: "s32 i;\n    s32 size;\n\n    size = (u16)(64 * (gWindows[windowId].window.width * gWindows[windowId].window.height));\n    for (i = 0; i < size; i++)\n        gWindows[windowId].tileData[i] = fillValue;",
  },
  "FillWindowPixelRect": {
    returnType: "void",
    params: "u8 windowId, u8 fillValue, u16 x, u16 y, u16 width, u16 height",
    callsTo: ["FillBitmapRect4Bit"],
    lineCount: 5,
    bodyC: "struct Bitmap pixelRect;\n\n    pixelRect.pixels = gWindows[windowId].tileData;\n    pixelRect.width = 8 * gWindows[windowId].window.width;\n    pixelRect.height = 8 * gWindows[windowId].window.height;\n\n    FillBitmapRect4Bit(&pixelRect, x, y, width, height, fillValue);",
  },
  "FillWindowPixelRect8Bit": {
    returnType: "void",
    params: "u8 windowId, u8 fillValue, u16 x, u16 y, u16 width, u16 height",
    callsTo: ["FillBitmapRect8Bit"],
    lineCount: 5,
    bodyC: "struct Bitmap pixelRect;\n\n    pixelRect.pixels = gWindows[windowId].tileData;\n    pixelRect.width = 8 * gWindows[windowId].window.width;\n    pixelRect.height = 8 * gWindows[windowId].window.height;\n\n    FillBitmapRect8Bit(&pixelRect, x, y, width, height, fillValue);",
  },
  "FreeAllWindowBuffers": {
    returnType: "void",
    params: "void",
    callsTo: ["Free"],
    lineCount: 17,
    bodyC: "int i;\n\n    for (i = 0; i < NUM_BACKGROUNDS; ++i)\n    {\n        if (gWindowBgTilemapBuffers[i] != NULL && gWindowBgTilemapBuffers[i] != DummyWindowBgTilemap)\n        {\n            Free(gWindowBgTilemapBuffers[i]);\n            gWindowBgTilemapBuffers[i] = NULL;\n        }\n    }\n\n    for (i = 0; i < WINDOWS_MAX; ++i)\n    {\n        if (gWindows[i].tileData != NULL)\n        {\n            Free(gWindows[i].tileData);\n            gWindows[i].tileData = NULL;\n        }\n    }",
  },
  "GetNumActiveWindowsOnBg": {
    returnType: "static u8",
    params: "u8 bgId",
    lineCount: 8,
    bodyC: "u8 windowsNum = 0;\n    s32 i;\n    for (i = 0; i < WINDOWS_MAX; i++)\n    {\n        if (gWindows[i].window.bg == bgId)\n            windowsNum++;\n    }\n    return windowsNum;",
  },
  "GetNumActiveWindowsOnBg8Bit": {
    returnType: "static u8",
    params: "u8 bgId",
    lineCount: 8,
    bodyC: "u8 windowsNum = 0;\n    s32 i;\n    for (i = 0; i < WINDOWS_MAX; i++)\n    {\n        if (gWindows[i].window.bg == bgId)\n            windowsNum++;\n    }\n    return windowsNum;",
  },
  "GetWindowAttribute": {
    returnType: "u32",
    params: "u8 windowId, u8 attributeId",
    lineCount: 21,
    bodyC: "switch (attributeId)\n    {\n    case WINDOW_BG:\n        return gWindows[windowId].window.bg;\n    case WINDOW_TILEMAP_LEFT:\n        return gWindows[windowId].window.tilemapLeft;\n    case WINDOW_TILEMAP_TOP:\n        return gWindows[windowId].window.tilemapTop;\n    case WINDOW_WIDTH:\n        return gWindows[windowId].window.width;\n    case WINDOW_HEIGHT:\n        return gWindows[windowId].window.height;\n    case WINDOW_PALETTE_NUM:\n        return gWindows[windowId].window.paletteNum;\n    case WINDOW_BASE_BLOCK:\n        return gWindows[windowId].window.baseBlock;\n    case WINDOW_TILE_DATA:\n        return (u32)(gWindows[windowId].tileData);\n    default:\n        return 0;\n    }",
  },
  "InitWindows": {
    returnType: "bool16",
    params: "const struct WindowTemplate *templates",
    callsTo: ["AllocZeroed","BgTileAllocOp","Free","FreeAllWindowBuffers","GetBgAttribute","GetBgTilemapBuffer","GetNumActiveWindowsOnBg","SetBgTilemapBuffer"],
    lineCount: 65,
    bodyC: "int i;\n    void *bgTilemapBuffer;\n    int j;\n    u8 bgLayer;\n    u16 attrib;\n    u8 *allocatedTilemapBuffer;\n    int allocatedBaseBlock;\n\n    for (i = 0; i < NUM_BACKGROUNDS; ++i)\n    {\n        bgTilemapBuffer = GetBgTilemapBuffer(i);\n        if (bgTilemapBuffer != NULL)\n            gWindowBgTilemapBuffers[i] = DummyWindowBgTilemap;\n        else\n            gWindowBgTilemapBuffers[i] = bgTilemapBuffer;\n    }\n\n    for (i = 0; i < WINDOWS_MAX; ++i)\n    {\n        gWindows[i].window = sDummyWindowTemplate;\n        gWindows[i].tileData = NULL;\n    }\n\n    for (i = 0, allocatedBaseBlock = 0, bgLayer = templates[i].bg; bgLayer != 0xFF && i < WINDOWS_MAX; ++i, bgLayer = templates[i].bg)\n    {\n        if (gWindowTileAutoAllocEnabled == TRUE)\n        {\n            allocatedBaseBlock = BgTileAllocOp(bgLayer, 0, templates[i].width * templates[i].height, 0);\n            if (allocatedBaseBlock == -1)\n                return FALSE;\n        }\n\n        if (gWindowBgTilemapBuffers[bgLayer] == NULL)\n        {\n            attrib = GetBgAttribute(bgLayer, BG_ATTR_METRIC);\n\n            if (attrib != 0xFFFF)\n            {\n                allocatedTilemapBuffer = AllocZeroed(attrib);\n\n                if (allocatedTilemapBuffer == NULL)\n                {\n                    FreeAllWindowBuffers();\n                    return FALSE;\n                }\n\n                for (j = 0; j < attrib; ++j)\n                    allocatedTilemapBuffer[j] = 0;\n\n                gWindowBgTilemapBuffers[bgLayer] = allocatedTilemapBuffer;\n                SetBgTilemapBuffer(bgLayer, allocatedTilemapBuffer);\n            }\n        }\n\n        allocatedTilemapBuffer = AllocZeroed((u16)(32 * (templates[i].width * templates[i].height)));\n\n        if (allocatedTilemapBuffer == NULL)\n        {\n            if ((GetNumActiveWindowsOnBg(bgLayer) == 0) && (gWindowBgTilemapBuffers[bgLayer] != DummyWindowBgTilemap))\n            {\n                Free(gWindowBgTilemapBuffers[bgLayer]);\n                gWindowBgTilemapBuffers[bgLayer] = allocatedTilemapBuffer;\n            }\n\n            return FALSE;\n        }\n\n        gWindows[i].tileData = allocatedTilemapBuffer;\n        gWindows[i].window = templates[i];\n\n        if (gWindowTileAutoAllocEnabled == TRUE)\n        {\n            gWindows[i].window.baseBlock = allocatedBaseBlock;\n            BgTileAllocOp(bgLayer, allocatedBaseBlock, templates[i].width * templates[i].height, 1);\n        }\n    }\n\n    gTransparentTileNumber = 0;\n    return TRUE;",
  },
  "PutWindowRectTilemap": {
    returnType: "void",
    params: "u8 windowId, u8 x, u8 y, u8 width, u8 height",
    callsTo: ["GetBgAttribute","WriteSequenceToBgTilemapBuffer"],
    lineCount: 16,
    bodyC: "struct Window windowLocal = gWindows[windowId];\n    u16 currentRow = windowLocal.window.baseBlock + (y * windowLocal.window.width) + x + GetBgAttribute(windowLocal.window.bg, BG_ATTR_BASETILE);\n    int i;\n\n    for (i = 0; i < height; ++i)\n    {\n        WriteSequenceToBgTilemapBuffer(\n            windowLocal.window.bg,\n            currentRow,\n            windowLocal.window.tilemapLeft + x,\n            windowLocal.window.tilemapTop + y + i,\n            width,\n            1,\n            windowLocal.window.paletteNum,\n            1);\n\n        currentRow += windowLocal.window.width;\n    }",
  },
  "PutWindowRectTilemapOverridePalette": {
    returnType: "void",
    params: "u8 windowId, u8 x, u8 y, u8 width, u8 height, u8 palette",
    callsTo: ["GetBgAttribute","WriteSequenceToBgTilemapBuffer"],
    lineCount: 16,
    bodyC: "struct Window windowLocal = gWindows[windowId];\n    u16 currentRow = windowLocal.window.baseBlock + (y * windowLocal.window.width) + x + GetBgAttribute(windowLocal.window.bg, BG_ATTR_BASETILE);\n    int i;\n\n    for (i = 0; i < height; ++i)\n    {\n        WriteSequenceToBgTilemapBuffer(\n            windowLocal.window.bg,\n            currentRow,\n            windowLocal.window.tilemapLeft + x,\n            windowLocal.window.tilemapTop + y + i,\n            width,\n            1,\n            palette,\n            1);\n\n        currentRow += windowLocal.window.width;\n    }",
  },
  "PutWindowTilemap": {
    returnType: "void",
    params: "u8 windowId",
    callsTo: ["GetBgAttribute","WriteSequenceToBgTilemapBuffer"],
    lineCount: 10,
    bodyC: "struct Window windowLocal = gWindows[windowId];\n\n    WriteSequenceToBgTilemapBuffer(\n        windowLocal.window.bg,\n        GetBgAttribute(windowLocal.window.bg, BG_ATTR_BASETILE) + windowLocal.window.baseBlock,\n        windowLocal.window.tilemapLeft,\n        windowLocal.window.tilemapTop,\n        windowLocal.window.width,\n        windowLocal.window.height,\n        windowLocal.window.paletteNum,\n        1);",
  },
  "RemoveWindow": {
    returnType: "void",
    params: "u8 windowId",
    callsTo: ["BgTileAllocOp","Free","GetNumActiveWindowsOnBg"],
    lineCount: 17,
    bodyC: "u8 bgLayer = gWindows[windowId].window.bg;\n\n    if (gWindowTileAutoAllocEnabled == TRUE)\n        BgTileAllocOp(bgLayer, gWindows[windowId].window.baseBlock, gWindows[windowId].window.width * gWindows[windowId].window.height, 2);\n\n    gWindows[windowId].window = sDummyWindowTemplate;\n\n    if (GetNumActiveWindowsOnBg(bgLayer) == 0)\n    {\n        if (gWindowBgTilemapBuffers[bgLayer] != DummyWindowBgTilemap)\n        {\n            Free(gWindowBgTilemapBuffers[bgLayer]);\n            gWindowBgTilemapBuffers[bgLayer] = NULL;\n        }\n    }\n\n    if (gWindows[windowId].tileData != NULL)\n    {\n        Free(gWindows[windowId].tileData);\n        gWindows[windowId].tileData = NULL;\n    }",
  },
  "ScrollWindow": {
    returnType: "void",
    params: "u8 windowId, u8 direction, u8 distance, u8 fillValue",
    callsTo: ["MOVE_TILES_DOWN","MOVE_TILES_UP"],
    lineCount: 42,
    bodyC: "struct WindowTemplate window = gWindows[windowId].window;\n    u8 *tileData = gWindows[windowId].tileData;\n    u32 fillValue32 = (fillValue << 24) | (fillValue << 16) | (fillValue << 8) | fillValue;\n    s32 size = window.height * window.width * 32;\n    u32 width = window.width;\n    s32 i;\n    s32 srcOffset, destOffset;\n    u32 distanceLoop;\n\n    switch (direction)\n    {\n    case 0:\n        for (i = 0; i < size; i += 32)\n        {\n            distanceLoop = distance;\n            MOVE_TILES_DOWN(0)\n            MOVE_TILES_DOWN(4)\n            MOVE_TILES_DOWN(8)\n            MOVE_TILES_DOWN(12)\n            MOVE_TILES_DOWN(16)\n            MOVE_TILES_DOWN(20)\n            MOVE_TILES_DOWN(24)\n            MOVE_TILES_DOWN(28)\n        }\n        break;\n    case 1:\n        tileData += size - 4;\n        for (i = 0; i < size; i += 32)\n        {\n            distanceLoop = distance;\n            MOVE_TILES_UP(0)\n            MOVE_TILES_UP(4)\n            MOVE_TILES_UP(8)\n            MOVE_TILES_UP(12)\n            MOVE_TILES_UP(16)\n            MOVE_TILES_UP(20)\n            MOVE_TILES_UP(24)\n            MOVE_TILES_UP(28)\n        }\n        break;\n    case 2:\n        break;\n    }",
  },
  "SetWindowAttribute": {
    returnType: "bool8",
    params: "u8 windowId, u8 attributeId, u32 value",
    lineCount: 23,
    bodyC: "switch (attributeId)\n    {\n    case WINDOW_TILEMAP_LEFT:\n        gWindows[windowId].window.tilemapLeft = value;\n        return FALSE;\n    case WINDOW_TILEMAP_TOP:\n        gWindows[windowId].window.tilemapTop = value;\n        return FALSE;\n    case WINDOW_PALETTE_NUM:\n        gWindows[windowId].window.paletteNum = value;\n        return FALSE;\n    case WINDOW_BASE_BLOCK:\n        gWindows[windowId].window.baseBlock = value;\n        return FALSE;\n    case WINDOW_TILE_DATA:\n        gWindows[windowId].tileData = (u8 *)(value);\n        return TRUE;\n    case WINDOW_BG:\n    case WINDOW_WIDTH:\n    case WINDOW_HEIGHT:\n    default:\n        return TRUE;\n    }",
  },
} as const;
