// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/battle_anim_normal.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 36 functions extracted from src/battle_anim_normal.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck

/** static void AnimConfusionDuck(struct Sprite *sprite) */
export function AnimConfusionDuck(sprite: any): any {
  CMD_ARGS(x, y, waveOffset, wavePeriod, duration);

      sprite.x += cmd.x;
      sprite.y += cmd.y;
      sprite.data[0] = cmd.waveOffset;
      if (GetBattlerSide(gBattleAnimAttacker) != B_SIDE_PLAYER)
      {
          sprite.data[1] = -cmd.wavePeriod;
          sprite.data[4] = 1;
      }
      else
      {
          sprite.data[1] = cmd.wavePeriod;
          sprite.data[4] = 0;
          StartSpriteAnim(sprite, 1);
      }

      sprite.data[3] = cmd.duration;
      sprite.callback = AnimConfusionDuck_Step;
      sprite.callback(sprite);
}

/** static void AnimConfusionDuck_Step(struct Sprite *sprite) */
export function AnimConfusionDuck_Step(sprite: any): any {
  sprite.x2 = Cos(sprite.data[0], 30);
      sprite.y2 = Sin(sprite.data[0], 10);

      if (sprite.data[0] < 128)
          sprite.oam.priority = 1;
      else
          sprite.oam.priority = 3;

      sprite.data[0] = (sprite.data[0] + sprite.data[1]) & 0xFF;
      if (++sprite.data[2] == sprite.data[3])
          DestroyAnimSprite(sprite);
}

/** static void AnimSimplePaletteBlend(struct Sprite *sprite) */
export function AnimSimplePaletteBlend(sprite: any): any {
  CMD_ARGS(selector, delay, initialBlendY, targetBlendY, color);

      let selectedPalettes: any = UnpackSelectedBattlePalettes(cmd.selector);
      BeginNormalPaletteFade(selectedPalettes, cmd.delay, cmd.initialBlendY, cmd.targetBlendY, cmd.color);
      sprite.invisible = TRUE;
      sprite.callback = AnimSimplePaletteBlend_Step;
}

/** u32 UnpackSelectedBattlePalettes(s16 selector) */
export function UnpackSelectedBattlePalettes(selector: any): any {
  let battleBackground: any = selector & 1;
      let attacker: any = (selector >> 1) & 1;
      let target: any = (selector >> 2) & 1;
      let attackerPartner: any = (selector >> 3) & 1;
      let targetPartner: any = (selector >> 4) & 1;
      let anim1: any = (selector >> 5) & 1;
      let anim2: any = (selector >> 6) & 1;
      return GetBattlePalettesMask(battleBackground, attacker, target, attackerPartner, targetPartner, anim1, anim2);
}

/** static void AnimSimplePaletteBlend_Step(struct Sprite *sprite) */
export function AnimSimplePaletteBlend_Step(sprite: any): any {
  if (!gPaletteFade.active)
          DestroyAnimSprite(sprite);
}

/** static void AnimComplexPaletteBlend(struct Sprite *sprite) */
export function AnimComplexPaletteBlend(sprite: any): any {
  CMD_ARGS(selector, delay, numBlends, color1, blendY1, color2, blendY2);

      let selectedPalettes: any = null;

      sprite.sTimer = cmd.delay;
      sprite.sDelay = cmd.delay;
      sprite.sNumBlends = cmd.numBlends;
      sprite.sColor1 = cmd.color1;
      sprite.sBlendY1 = cmd.blendY1;
      sprite.sColor2 = cmd.color2;
      sprite.sBlendY2 = cmd.blendY2;
      sprite.sPaletteSelector = cmd.selector;

      selectedPalettes = UnpackSelectedBattlePalettes(sprite.sPaletteSelector);
      BlendPalettes(selectedPalettes, cmd.blendY1, cmd.color1);
      sprite.invisible = TRUE;
      sprite.callback = AnimComplexPaletteBlend_Step1;
}

/** static void AnimComplexPaletteBlend_Step1(struct Sprite *sprite) */
export function AnimComplexPaletteBlend_Step1(sprite: any): any {
  let selectedPalettes: any = null;

      if (sprite.sTimer > 0)
      {
          sprite.sTimer--;
          return;
      }

      if (gPaletteFade.active)
          return;

      if (sprite.sNumBlends == 0)
      {
          sprite.callback = AnimComplexPaletteBlend_Step2;
          return;
      }

      selectedPalettes = UnpackSelectedBattlePalettes(sprite.sPaletteSelector);
      if (sprite.sDelay & 0x100)
          BlendPalettes(selectedPalettes, sprite.sBlendY1, sprite.sColor1);
      else
          BlendPalettes(selectedPalettes, sprite.sBlendY2, sprite.sColor2);

      sprite.sDelay ^= 0x100;
      sprite.sTimer = sprite.sDelay & 0xFF;
      sprite.sNumBlends--;
}

/** static void AnimComplexPaletteBlend_Step2(struct Sprite *sprite) */
export function AnimComplexPaletteBlend_Step2(sprite: any): any {
  let selectedPalettes: any = null;

      if (!gPaletteFade.active)
      {
          selectedPalettes = UnpackSelectedBattlePalettes(sprite.sPaletteSelector);
          BlendPalettes(selectedPalettes, 0, 0);
          DestroyAnimSprite(sprite);
      }
}

/** static void AnimCirclingSparkle(struct Sprite *sprite) */
export function AnimCirclingSparkle(sprite: any): any {
  CMD_ARGS(x, y);

      sprite.x += cmd.x;
      sprite.y += cmd.y;
      sprite.data[0] = 0;
      sprite.data[1] = 10;
      sprite.data[2] = 8;
      sprite.data[3] = 40;
      sprite.data[4] = 112;
      sprite.data[5] = 0;
      StoreSpriteCallbackInData6(sprite, DestroySpriteAndMatrix);
      sprite.callback = TranslateSpriteInGrowingCircle;
      sprite.callback(sprite);
}

/** void AnimTask_BlendColorCycle(u8 taskId) */
export function AnimTask_BlendColorCycle(taskId: any): any {
  CMD_ARGS(selector, delay, numBlends, initialBlendY, targetBlendY, color);

      gTasks[taskId].tPalSelector = cmd.selector;
      gTasks[taskId].tDelay = cmd.delay;
      gTasks[taskId].tNumBlends = cmd.numBlends;
      gTasks[taskId].tInitialBlendY = cmd.initialBlendY;
      gTasks[taskId].tTargetBlendY = cmd.targetBlendY;
      gTasks[taskId].tBlendColor = cmd.color;
      gTasks[taskId].tRestoreBlend = FALSE;
      BlendColorCycle(taskId, 0, gTasks[taskId].tTargetBlendY);
      gTasks[taskId].func = AnimTask_BlendColorCycleLoop;
}

/** static void BlendColorCycle(u8 taskId, u8 startBlendAmount, u8 targetBlendAmount) */
export function BlendColorCycle(taskId: any, startBlendAmount: any, targetBlendAmount: any): any {
  let selectedPalettes: any = UnpackSelectedBattlePalettes(gTasks[taskId].tPalSelector);
      BeginNormalPaletteFade(
          selectedPalettes,
          gTasks[taskId].tDelay,
          startBlendAmount,
          targetBlendAmount,
          gTasks[taskId].tBlendColor);

      gTasks[taskId].tNumBlends--;
      gTasks[taskId].tRestoreBlend ^= 1;
}

/** static void AnimTask_BlendColorCycleLoop(u8 taskId) */
export function AnimTask_BlendColorCycleLoop(taskId: any): any {
  let startBlendAmount, targetBlendAmount;
      if (!gPaletteFade.active)
      {
          if (gTasks[taskId].tNumBlends > 0)
          {
              if (!gTasks[taskId].tRestoreBlend)
              {
                   
                  startBlendAmount = gTasks[taskId].tInitialBlendY;
                  targetBlendAmount = gTasks[taskId].tTargetBlendY;
              }
              else
              {
                   
                  startBlendAmount = gTasks[taskId].tTargetBlendY;
                  targetBlendAmount = gTasks[taskId].tInitialBlendY;
              }

              if (gTasks[taskId].tNumBlends == 1)
                  targetBlendAmount = 0;

              BlendColorCycle(taskId, startBlendAmount, targetBlendAmount);
          }
          else
          {
              DestroyAnimVisualTask(taskId);
          }
      }
}

/** void AnimTask_BlendColorCycleExclude(u8 taskId) */
export function AnimTask_BlendColorCycleExclude(taskId: any): any {
  CMD_ARGS(unk0, delay, numBlends, initialBlendY, targetBlendY, color);

      let battler: any = null;
      let selectedPalettes: any = 0;

      gTasks[taskId].data[0] = cmd.unk0;
      gTasks[taskId].tDelay = cmd.delay;
      gTasks[taskId].tNumBlends = cmd.numBlends;
      gTasks[taskId].tInitialBlendY = cmd.initialBlendY;
      gTasks[taskId].tTargetBlendY = cmd.targetBlendY;
      gTasks[taskId].tBlendColor = cmd.color;
      gTasks[taskId].tRestoreBlend = 0;

      for (battler = 0; battler < gBattlersCount; battler++)
      {
          if (battler != gBattleAnimAttacker && battler != gBattleAnimTarget)
              selectedPalettes |= 1 << (battler + 16);
      }

      if (cmd.unk0 == 1)
          selectedPalettes |= 0xE;

      gTasks[taskId].tPalSelectorHi = selectedPalettes >> 16;
      gTasks[taskId].tPalSelectorLo = selectedPalettes & 0xFF;
      BlendColorCycleExclude(taskId, 0, gTasks[taskId].tTargetBlendY);
      gTasks[taskId].func = AnimTask_BlendColorCycleExcludeLoop;
}

/** static void BlendColorCycleExclude(u8 taskId, u8 startBlendAmount, u8 targetBlendAmount) */
export function BlendColorCycleExclude(taskId: any, startBlendAmount: any, targetBlendAmount: any): any {
  let selectedPalettes: any = (gTasks[taskId].tPalSelectorHi << 16) | gTasks[taskId].tPalSelectorLo;
      BeginNormalPaletteFade(
          selectedPalettes,
          gTasks[taskId].tDelay,
          startBlendAmount,
          targetBlendAmount,
          gTasks[taskId].tBlendColor);

      gTasks[taskId].tNumBlends--;
      gTasks[taskId].tRestoreBlend ^= 1;
}

/** static void AnimTask_BlendColorCycleExcludeLoop(u8 taskId) */
export function AnimTask_BlendColorCycleExcludeLoop(taskId: any): any {
  let startBlendAmount, targetBlendAmount;
      if (!gPaletteFade.active)
      {
          if (gTasks[taskId].tNumBlends > 0)
          {
              if (!gTasks[taskId].tRestoreBlend)
              {
                   
                  startBlendAmount = gTasks[taskId].tInitialBlendY;
                  targetBlendAmount = gTasks[taskId].tTargetBlendY;
              }
              else
              {
                   
                  startBlendAmount = gTasks[taskId].tTargetBlendY;
                  targetBlendAmount = gTasks[taskId].tInitialBlendY;
              }

              if (gTasks[taskId].tNumBlends == 1)
                  targetBlendAmount = 0;

              BlendColorCycleExclude(taskId, startBlendAmount, targetBlendAmount);
          }
          else
          {
              DestroyAnimVisualTask(taskId);
          }
      }
}

/** void AnimTask_BlendColorCycleByTag(u8 taskId) */
export function AnimTask_BlendColorCycleByTag(taskId: any): any {
  CMD_ARGS(tag, delay, numBlends, initialBlendY, targetBlendY, color);

      gTasks[taskId].tPalTag = cmd.tag;
      gTasks[taskId].tDelay = cmd.delay;
      gTasks[taskId].tNumBlends = cmd.numBlends;
      gTasks[taskId].tInitialBlendY = cmd.initialBlendY;
      gTasks[taskId].tTargetBlendY = cmd.targetBlendY;
      gTasks[taskId].tBlendColor = cmd.color;
      gTasks[taskId].tRestoreBlend = FALSE;

      BlendColorCycleByTag(taskId, 0, gTasks[taskId].tTargetBlendY);
      gTasks[taskId].func = AnimTask_BlendColorCycleByTagLoop;
}

/** static void BlendColorCycleByTag(u8 taskId, u8 startBlendAmount, u8 targetBlendAmount) */
export function BlendColorCycleByTag(taskId: any, startBlendAmount: any, targetBlendAmount: any): any {
  let paletteIndex: any = IndexOfSpritePaletteTag(gTasks[taskId].tPalTag);
      BeginNormalPaletteFade(
          1 << (paletteIndex + 16),
          gTasks[taskId].tDelay,
          startBlendAmount,
          targetBlendAmount,
          gTasks[taskId].tBlendColor);

      gTasks[taskId].tNumBlends--;
      gTasks[taskId].tRestoreBlend ^= 1;
}

/** static void AnimTask_BlendColorCycleByTagLoop(u8 taskId) */
export function AnimTask_BlendColorCycleByTagLoop(taskId: any): any {
  let startBlendAmount, targetBlendAmount;
      if (!gPaletteFade.active)
      {
          if (gTasks[taskId].tNumBlends > 0)
          {
              if (!gTasks[taskId].tRestoreBlend)
              {
                   
                  startBlendAmount = gTasks[taskId].tInitialBlendY;
                  targetBlendAmount = gTasks[taskId].tTargetBlendY;
              }
              else
              {
                   
                  startBlendAmount = gTasks[taskId].tTargetBlendY;
                  targetBlendAmount = gTasks[taskId].tInitialBlendY;
              }

              if (gTasks[taskId].tNumBlends == 1)
                  targetBlendAmount = 0;

              BlendColorCycleByTag(taskId, startBlendAmount, targetBlendAmount);
          }
          else
          {
              DestroyAnimVisualTask(taskId);
          }
      }
}

/** void AnimTask_FlashAnimTagWithColor(u8 taskId) */
export function AnimTask_FlashAnimTagWithColor(taskId: any): any {
  CMD_ARGS(tag, delay, numBlends, color1, blendY1, color2, blendY2);

      let paletteIndex: any = null;

      gTasks[taskId].tTimer = cmd.delay;
      gTasks[taskId].tDelay = cmd.delay;
      gTasks[taskId].tNumBlends = cmd.numBlends;
      gTasks[taskId].tColor1 = cmd.color1;
      gTasks[taskId].tBlendY1 = cmd.blendY1;
      gTasks[taskId].tColor2 = cmd.color2;
      gTasks[taskId].tBlendY2 = cmd.blendY2;
      gTasks[taskId].tAnimTag = cmd.tag;

      paletteIndex = IndexOfSpritePaletteTag(cmd.tag);
      BeginNormalPaletteFade(
          1 << (paletteIndex + 16),
          0,
          cmd.blendY1,
          cmd.blendY1,
          cmd.color1);

      gTasks[taskId].func = AnimTask_FlashAnimTagWithColor_Step1;
}

/** static void AnimTask_FlashAnimTagWithColor_Step1(u8 taskId) */
export function AnimTask_FlashAnimTagWithColor_Step1(taskId: any): any {
  let selectedPalettes: any = null;

      if (gTasks[taskId].tTimer > 0)
      {
          gTasks[taskId].tTimer--;
          return;
      }

      if (gPaletteFade.active)
          return;

      if (gTasks[taskId].tNumBlends == 0)
      {
          gTasks[taskId].func = AnimTask_FlashAnimTagWithColor_Step2;
          return;
      }

      selectedPalettes = 1 << (IndexOfSpritePaletteTag(gTasks[taskId].tAnimTag) + 16);
      if (gTasks[taskId].tDelay & 0x100)
      {
          BeginNormalPaletteFade(
              selectedPalettes,
              0,
              gTasks[taskId].tBlendY1,
              gTasks[taskId].tBlendY1,
              gTasks[taskId].tColor1);
      }
      else
      {
          BeginNormalPaletteFade(
              selectedPalettes,
              0,
              gTasks[taskId].tBlendY2,
              gTasks[taskId].tBlendY2,
              gTasks[taskId].tColor2);
      }

      gTasks[taskId].tDelay ^= 0x100;
      gTasks[taskId].tTimer = gTasks[taskId].tDelay & 0xFF;
      gTasks[taskId].tNumBlends--;
}

/** static void AnimTask_FlashAnimTagWithColor_Step2(u8 taskId) */
export function AnimTask_FlashAnimTagWithColor_Step2(taskId: any): any {
  let selectedPalettes: any = null;

      if (!gPaletteFade.active)
      {
          selectedPalettes = 1 << (IndexOfSpritePaletteTag(gTasks[taskId].tAnimTag) + 16);
          BeginNormalPaletteFade(selectedPalettes, 0, 0, 0, RGB_BLACK);
          DestroyAnimVisualTask(taskId);
      }
}

/** void AnimTask_InvertScreenColor(u8 taskId) */
export function AnimTask_InvertScreenColor(taskId: any): any {
  CMD_ARGS(flagsScenery, flagsAttacker, flagsTarget);

      let selectedPalettes: any = 0;
      let attackerBattler: any = gBattleAnimAttacker;
      let targetBattler: any = gBattleAnimTarget;

      if (cmd.flagsScenery & (1 << 8))
          selectedPalettes = GetBattlePalettesMask(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE);

      if (cmd.flagsAttacker & (1 << 8))
          selectedPalettes |= (0x10000 << attackerBattler);

      if (cmd.flagsTarget & (1 << 8))
          selectedPalettes |= (0x10000 << targetBattler);

      InvertPlttBuffer(selectedPalettes);
      DestroyAnimVisualTask(taskId);
}

/** void AnimTask_TintPalettes(u8 taskId) */
export function AnimTask_TintPalettes(taskId: any): any {
  CMD_ARGS(flagsScenery, flagsAttacker, flagsTarget, duration, r, g, b);

      let attackerBattler: any = null;
      let targetBattler: any = null;
      let paletteIndex: any = null;
      let selectedPalettes: any = 0;

      if (gTasks[taskId].tTimer == 0)
      {
          gTasks[taskId].tFlagsScenery = cmd.flagsScenery;
          gTasks[taskId].tFlagsAttacker = cmd.flagsAttacker;
          gTasks[taskId].tFlagsTarget = cmd.flagsTarget;
          gTasks[taskId].tLength = cmd.duration;
          gTasks[taskId].tColorR = cmd.r;
          gTasks[taskId].tColorG = cmd.g;
          gTasks[taskId].tColorB = cmd.b;
      }

      gTasks[taskId].tTimer++;
      attackerBattler = gBattleAnimAttacker;
      targetBattler = gBattleAnimTarget;

      if (gTasks[taskId].tFlagsScenery & (1 << 8))
          selectedPalettes = PALETTES_BG;

      if (gTasks[taskId].tFlagsScenery & 1)
      {
          paletteIndex = IndexOfSpritePaletteTag(gSprites[gHealthboxSpriteIds[attackerBattler]].template.paletteTag);
          selectedPalettes |= (1 << paletteIndex) << 16;
      }

      if (gTasks[taskId].tFlagsAttacker & (1 << 8))
          selectedPalettes |= (1 << attackerBattler) << 16;

      if (gTasks[taskId].tFlagsTarget & (1 << 8))
          selectedPalettes |= (1 << targetBattler) << 16;

      TintPlttBuffer(selectedPalettes, gTasks[taskId].tColorR, gTasks[taskId].tColorG, gTasks[taskId].tColorB);
      if (gTasks[taskId].tTimer == gTasks[taskId].tLength)
      {
          UnfadePlttBuffer(selectedPalettes);
          DestroyAnimVisualTask(taskId);
      }
}

/** static void AnimShakeMonOrBattlePlatforms(struct Sprite *sprite) */
export function AnimShakeMonOrBattlePlatforms(sprite: any): any {
  CMD_ARGS(velocity, shakeTimer, shakeDuration, type, battlerSelector);

      sprite.invisible = TRUE;
      sprite.sShakeVelocity = -cmd.velocity;
      sprite.sShakeTimer = cmd.shakeTimer;
      sprite.sShakeDuration = cmd.shakeTimer;
      sprite.sTimer = cmd.shakeDuration;

      switch (cmd.type)
      {
      case SHAKE_BG_X:
          StoreSpriteCallbackInData6(sprite,gBattle_BG3_X);
          break;
      case SHAKE_BG_Y:
          StoreSpriteCallbackInData6(sprite,gBattle_BG3_Y);
          break;
      case SHAKE_MON_X:
          StoreSpriteCallbackInData6(sprite,gSpriteCoordOffsetX);
          break;
      default:
          StoreSpriteCallbackInData6(sprite,gSpriteCoordOffsetY);
          break;
      }

      sprite.sOriginalValue = (sprite.sShakePtrLo | (sprite.sShakePtrHi << 16));
      sprite.sType = cmd.type;
      if (sprite.sType == SHAKE_MON_X || sprite.sType == SHAKE_MON_Y)
          AnimShakeMonOrBattlePlatforms_UpdateCoordOffsetEnabled();

      sprite.callback = AnimShakeMonOrBattlePlatforms_Step;
}

/** static void AnimShakeMonOrBattlePlatforms_Step(struct Sprite *sprite) */
export function AnimShakeMonOrBattlePlatforms_Step(sprite: any): any {
  let i: any = null;

      if (sprite.sTimer > 0)
      {
          sprite.sTimer--;
          if (sprite.sShakeTimer > 0)
          {
              sprite.sShakeTimer--;
          }
          else
          {
              sprite.sShakeTimer = sprite.sShakeDuration;
              /* transpiler bug LHS : (sprite.sShakePtrLo | (sprite.sShakePtrHi << 16)) += sprite.sShakeVelocity; */ ;
              sprite.sShakeVelocity = -sprite.sShakeVelocity;
          }
      }
      else
      {
          /* transpiler bug LHS : (sprite.sShakePtrLo | (sprite.sShakePtrHi << 16)) = sprite.sOriginalValue; */ ;
          if (sprite.sType == SHAKE_MON_X || sprite.sType == SHAKE_MON_Y)
          {
              for (i = 0; i < gBattlersCount; i++)
                  gSprites[gBattlerSpriteIds[i]].coordOffsetEnabled = FALSE;
          }

          DestroyAnimSprite(sprite);
      }
}

/** static void AnimShakeMonOrBattlePlatforms_UpdateCoordOffsetEnabled(void) */
export function AnimShakeMonOrBattlePlatforms_UpdateCoordOffsetEnabled(): any {
  CMD_ARGS(velocity, shakeDuration, duration, type, battlerSelector);

      gSprites[gBattlerSpriteIds[gBattleAnimAttacker]].coordOffsetEnabled = FALSE;
      gSprites[gBattlerSpriteIds[gBattleAnimTarget]].coordOffsetEnabled = FALSE;

      if (cmd.battlerSelector == 2)
      {
          gSprites[gBattlerSpriteIds[gBattleAnimAttacker]].coordOffsetEnabled = TRUE;
          gSprites[gBattlerSpriteIds[gBattleAnimTarget]].coordOffsetEnabled = TRUE;
      }
      else
      {
          if (cmd.battlerSelector == 0)
              gSprites[gBattlerSpriteIds[gBattleAnimAttacker]].coordOffsetEnabled = TRUE;
          else
              gSprites[gBattlerSpriteIds[gBattleAnimTarget]].coordOffsetEnabled = TRUE;
      }
}

/** void AnimTask_ShakeBattlePlatforms(u8 taskId) */
export function AnimTask_ShakeBattlePlatforms(taskId: any): any {
  CMD_ARGS(xOffset, yOffset, shakes, delay);

      gTasks[taskId].tXOffset = cmd.xOffset;
      gTasks[taskId].tYOffset = cmd.yOffset;
      gTasks[taskId].tNumShakes = cmd.shakes;
      gTasks[taskId].tTimer = cmd.delay;
      gTasks[taskId].tShakeDelay = cmd.delay;
      gBattle_BG3_X = cmd.xOffset;
      gBattle_BG3_Y = cmd.yOffset;
      gTasks[taskId].func = AnimTask_ShakeBattlePlatforms_Step;
      gTasks[taskId].func(taskId);
}

/** static void AnimTask_ShakeBattlePlatforms_Step(u8 taskId) */
export function AnimTask_ShakeBattlePlatforms_Step(taskId: any): any {
  if (gTasks[taskId].tTimer == 0)
      {
          if (gBattle_BG3_X == gTasks[taskId].tXOffset)
              gBattle_BG3_X = -gTasks[taskId].tXOffset;
          else
              gBattle_BG3_X = gTasks[taskId].tXOffset;

          if (gBattle_BG3_Y == -gTasks[taskId].tYOffset)
              gBattle_BG3_Y = 0;
          else
              gBattle_BG3_Y = -gTasks[taskId].tYOffset;

          gTasks[taskId].tTimer = gTasks[taskId].tShakeDelay;
          if (--gTasks[taskId].tNumShakes == 0)
          {
              gBattle_BG3_X = 0;
              gBattle_BG3_Y = 0;
              DestroyAnimVisualTask(taskId);
          }
      }
      else
      {
          gTasks[taskId].tTimer--;
      }
}

/** static void AnimHitSplatBasic(struct Sprite *sprite) */
export function AnimHitSplatBasic(sprite: any): any {
  CMD_ARGS(x, y, relativeTo, animation);

      StartSpriteAffineAnim(sprite, cmd.animation);
      if (cmd.relativeTo == ANIM_ATTACKER)
          InitSpritePosToAnimAttacker(sprite, TRUE);
      else
          InitSpritePosToAnimTarget(sprite, TRUE);

      sprite.callback = RunStoredCallbackWhenAffineAnimEnds;
      StoreSpriteCallbackInData6(sprite, DestroyAnimSprite);
}

/** static void AnimHitSplatPersistent(struct Sprite *sprite) */
export function AnimHitSplatPersistent(sprite: any): any {
  CMD_ARGS(x, y, relativeTo, animation, duration);

      StartSpriteAffineAnim(sprite, cmd.animation);
      if (cmd.relativeTo == ANIM_ATTACKER)
          InitSpritePosToAnimAttacker(sprite, TRUE);
      else
          InitSpritePosToAnimTarget(sprite, TRUE);

      sprite.data[0] = cmd.duration;
      sprite.callback = RunStoredCallbackWhenAffineAnimEnds;
      StoreSpriteCallbackInData6(sprite, DestroyAnimSpriteAfterTimer);
}

/** static void AnimHitSplatHandleInvert(struct Sprite *sprite) */
export function AnimHitSplatHandleInvert(sprite: any): any {
  CMD_ARGS(x, y, relativeTo, animation);

      if (GetBattlerSide(gBattleAnimAttacker) != B_SIDE_PLAYER && !IsContest())
          cmd.y = -cmd.y;

      AnimHitSplatBasic(sprite);
}

/** static void AnimHitSplatRandom(struct Sprite *sprite) */
export function AnimHitSplatRandom(sprite: any): any {
  CMD_ARGS(relativeTo, animation);

      if (cmd.animation == -1)
          cmd.animation = Random2() & 3;

      StartSpriteAffineAnim(sprite, cmd.animation);
      if (cmd.relativeTo == ANIM_ATTACKER)
          InitSpritePosToAnimAttacker(sprite, FALSE);
      else
          InitSpritePosToAnimTarget(sprite, FALSE);

      sprite.x2 += (Random2() % 48) - 24;
      sprite.y2 += (Random2() % 24) - 12;

      StoreSpriteCallbackInData6(sprite, DestroySpriteAndMatrix);
      sprite.callback = RunStoredCallbackWhenAffineAnimEnds;
}

/** static void AnimHitSplatOnMonEdge(struct Sprite *sprite) */
export function AnimHitSplatOnMonEdge(sprite: any): any {
  CMD_ARGS(relativeTo, x, y, animation);

      sprite.data[0] = GetAnimBattlerSpriteId(cmd.relativeTo);
      sprite.x = gSprites[sprite.data[0]].x + gSprites[sprite.data[0]].x2;
      sprite.y = gSprites[sprite.data[0]].y + gSprites[sprite.data[0]].y2;
      sprite.x2 = cmd.x;
      sprite.y2 = cmd.y;
      StartSpriteAffineAnim(sprite, cmd.animation);
      StoreSpriteCallbackInData6(sprite, DestroySpriteAndMatrix);
      sprite.callback = RunStoredCallbackWhenAffineAnimEnds;
}

/** static void AnimCrossImpact(struct Sprite *sprite) */
export function AnimCrossImpact(sprite: any): any {
  CMD_ARGS(x, y, relativeTo, duration);

      if (cmd.relativeTo == ANIM_ATTACKER)
          InitSpritePosToAnimAttacker(sprite, TRUE);
      else
          InitSpritePosToAnimTarget(sprite, TRUE);

      sprite.data[0] = cmd.duration;
      StoreSpriteCallbackInData6(sprite, DestroyAnimSprite);
      sprite.callback = WaitAnimForDuration;
}

/** static void AnimFlashingHitSplat(struct Sprite *sprite) */
export function AnimFlashingHitSplat(sprite: any): any {
  CMD_ARGS(x, y, relativeTo, animation);

      StartSpriteAffineAnim(sprite, cmd.animation);
      if (cmd.relativeTo == ANIM_ATTACKER)
          InitSpritePosToAnimAttacker(sprite, TRUE);
      else
          InitSpritePosToAnimTarget(sprite, TRUE);

      sprite.callback = AnimFlashingHitSplat_Step;
}

/** static void AnimFlashingHitSplat_Step(struct Sprite *sprite) */
export function AnimFlashingHitSplat_Step(sprite: any): any {
  sprite.invisible ^= 1;
      if (sprite.data[0]++ > 12)
          DestroyAnimSprite(sprite);
}

// ─── callsTo manifest (= 27 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["AnimHitSplatBasic","AnimShakeMonOrBattlePlatforms_UpdateCoordOffsetEnabled","BeginNormalPaletteFade","BlendColorCycle","BlendColorCycleByTag","BlendColorCycleExclude","BlendPalettes","CMD_ARGS","Cos","DestroyAnimSprite","DestroyAnimVisualTask","GetAnimBattlerSpriteId","GetBattlePalettesMask","GetBattlerSide","IndexOfSpritePaletteTag","InitSpritePosToAnimAttacker","InitSpritePosToAnimTarget","InvertPlttBuffer","IsContest","Random2","Sin","StartSpriteAffineAnim","StartSpriteAnim","StoreSpriteCallbackInData6","TintPlttBuffer","UnfadePlttBuffer","UnpackSelectedBattlePalettes"];
