// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/clear_save_data_screen.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 9 functions extracted from src/clear_save_data_screen.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck


// ─── AUTO-INJECTED file-scope vars (= EWRAM/IWRAM static C decls) ──
let sClearSaveBgTemplates: any = null;
let sClearSaveTextWindow: any = null;
let sClearSaveYesNo: any = null;
/** void CB2_InitClearSaveDataScreen(void) */
export function CB2_InitClearSaveDataScreen(): any {
  if (SetupClearSaveDataScreen())
          CreateTask(Task_DoClearSaveDataScreenYesNo, 0);
}

/** static void Task_DoClearSaveDataScreenYesNo(u8 taskId) */
export function Task_DoClearSaveDataScreenYesNo(taskId: any): any {
  DrawStdFrameWithCustomTileAndPalette(0, FALSE, 2, 14);
      AddTextPrinterParameterized(0, FONT_NORMAL, gText_ClearAllSaveData, 0, 1, 0, 0);
      CreateYesNoMenu(sClearSaveYesNo, 2, 14, 1);
      gTasks[taskId].func = Task_ClearSaveDataScreenYesNoChoice;
}

/** static void Task_ClearSaveDataScreenYesNoChoice(u8 taskId) */
export function Task_ClearSaveDataScreenYesNoChoice(taskId: any): any {
  switch (Menu_ProcessInputNoWrapClearOnChoose())
      {
      case 0:
          FillWindowPixelBuffer(0, PIXEL_FILL(1));
          AddTextPrinterParameterized(0, FONT_NORMAL, gText_ClearingData, 0, 1, 0, 0);
          gTasks[taskId].func = Task_ClearSaveData;
          break;
      case 1:
      case MENU_B_PRESSED:
          PlaySE(SE_SELECT);
          DestroyTask(taskId);
          SetMainCallback2(CB2_FadeAndDoReset);
      }
}

/** static void Task_ClearSaveData(u8 taskId) */
export function Task_ClearSaveData(taskId: any): any {
  ClearSaveData();
      DestroyTask(taskId);
      SetMainCallback2(CB2_FadeAndDoReset);
}

/** static void MainCB(void) */
export function MainCB(): any {
  RunTasks();
      UpdatePaletteFade();
}

/** static void VBlankCB(void) */
export function VBlankCB(): any {
  TransferPlttBuffer();
}

/** static bool8 SetupClearSaveDataScreen(void) */
export function SetupClearSaveDataScreen(): any {
  let i: any = null;

      switch(gMain.state)
      {
      case 0:
      default:
          SetVBlankCallback(NULL);
          SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_0);
          SetGpuReg(REG_OFFSET_BG0HOFS, 0);
          SetGpuReg(REG_OFFSET_BG0VOFS, 0);
          SetGpuReg(REG_OFFSET_BG3HOFS, 0);
          SetGpuReg(REG_OFFSET_BG3VOFS, 0);
          SetGpuReg(REG_OFFSET_WIN0H, 0);
          SetGpuReg(REG_OFFSET_WIN0V, 0);
          SetGpuReg(REG_OFFSET_WININ, 0);
          SetGpuReg(REG_OFFSET_WINOUT, 0);
          SetGpuReg(REG_OFFSET_BLDCNT, 0);
          SetGpuReg(REG_OFFSET_BLDALPHA, 0);
          SetGpuReg(REG_OFFSET_BLDY, 0);
          DmaFill16(3, 0, VRAM, VRAM_SIZE);
          DmaFill32(3, 0, OAM, OAM_SIZE);
          DmaFill16(3, 0, (PLTT + 2), PLTT_SIZE - 2);
          ResetPaletteFade();
          gPlttBufferUnfaded[0] = RGB_WHITE;
          gPlttBufferFaded[0] = RGB_WHITE;
          gPlttBufferUnfaded[1] = RGB(5, 10, 14);
          gPlttBufferFaded[1] = RGB(5, 10, 14);
          for (i = 0; i < 0x10; i++)
              ((VRAM + 0x20))[i] = 0x1111;

          for (i = 0; i < 0x400; i++)
              ((BG_SCREEN_ADDR(30)))[i] = 0x0001;
          ResetTasks();
          ResetSpriteData();
          ResetBgsAndClearDma3BusyFlags(0);
          InitBgsFromTemplates(0, sClearSaveBgTemplates, ARRAY_COUNT(sClearSaveBgTemplates));
          SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_ON | DISPCNT_OBJ_1D_MAP);
          ShowBg(0);
          ShowBg(3);
          SetGpuReg(REG_OFFSET_BLDCNT, 0);
          InitClearSaveDataScreenWindows();
          BeginNormalPaletteFade(PALETTES_BG, 0, 0x10, 0, RGB_WHITEALPHA);
          EnableInterrupts(INTR_FLAG_VBLANK);
          SetVBlankCallback(VBlankCB);
          gMain.state = 1;
          break;
      case 1:
          UpdatePaletteFade();
          if(!gPaletteFade.active)
          {
              SetMainCallback2(MainCB);
              return TRUE;
          }
      }
      return FALSE;
}

/** static void CB2_FadeAndDoReset(void) */
export function CB2_FadeAndDoReset(): any {
  switch(gMain.state)
      {
      case 0:
      default:
          BeginNormalPaletteFade(PALETTES_BG, 0, 0, 0x10, RGB_WHITEALPHA);
          gMain.state = 1;
          break;
      case 1:
          UpdatePaletteFade();
          if(!gPaletteFade.active)
          {
              FreeAllWindowBuffers();
              DoSoftReset();
          }
          break;
      }
}

/** static void InitClearSaveDataScreenWindows(void) */
export function InitClearSaveDataScreenWindows(): any {
  InitWindows(sClearSaveTextWindow);
      DeactivateAllTextPrinters();
      FillWindowPixelBuffer(0, PIXEL_FILL(0));
      LoadWindowGfx(0, 0, 2, BG_PLTT_ID(14));
      LoadPalette(gStandardMenuPalette, BG_PLTT_ID(15), PLTT_SIZE_4BPP);
}

// ─── callsTo manifest (= 37 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["ARRAY_COUNT","AddTextPrinterParameterized","BG_PLTT_ID","BG_SCREEN_ADDR","BeginNormalPaletteFade","ClearSaveData","CreateTask","CreateYesNoMenu","DeactivateAllTextPrinters","DestroyTask","DmaFill16","DmaFill32","DoSoftReset","DrawStdFrameWithCustomTileAndPalette","EnableInterrupts","FillWindowPixelBuffer","FreeAllWindowBuffers","InitBgsFromTemplates","InitClearSaveDataScreenWindows","InitWindows","LoadPalette","LoadWindowGfx","Menu_ProcessInputNoWrapClearOnChoose","PIXEL_FILL","PlaySE","ResetBgsAndClearDma3BusyFlags","ResetPaletteFade","ResetSpriteData","ResetTasks","RunTasks","SetGpuReg","SetMainCallback2","SetVBlankCallback","SetupClearSaveDataScreen","ShowBg","TransferPlttBuffer","UpdatePaletteFade"];
