// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/contest_link.c
// Generated : 2026-05-08
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 17 functions extracted from src/contest_link.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck

/** bool32 LinkContest_SendBlock(void *src, u16 size) */
export function LinkContest_SendBlock(...args: any[]): any {
  memcpy(gDecompressionBuffer, src, size);
      if (SendBlock(BitmaskAllOtherLinkPlayers(), gDecompressionBuffer, size))
          return TRUE;
      else
          return FALSE;
}

/** bool8 LinkContest_GetBlockReceived(u8 flag) */
export function LinkContest_GetBlockReceived(...args: any[]): any {
  let mask = (1 << flag);
      if (!(GetBlockReceivedStatus() & mask))
      {
          return FALSE;
      }
      else
      {
          ResetBlockReceivedFlag(flag);
          return TRUE;
      }
}

/** bool8 LinkContest_GetBlockReceivedFromAllPlayers(void) */
export function LinkContest_GetBlockReceivedFromAllPlayers(): any {
  if (GetBlockReceivedStatus() == GetLinkPlayerCountAsBitFlags())
      {
          ResetBlockReceivedFlags();
          return TRUE;
      }
      else
      {
          return FALSE;
      }
}

/** void Task_LinkContest_Init(u8 taskId) */
export function Task_LinkContest_Init(...args: any[]): any {
  let i: any = null;

      for (i = 0; i < CONTESTANT_COUNT; i++)
          gBlockRecvBuffer[i][0] = 0xFF;

      gTasks[taskId].tState = 0;
      gTasks[taskId].func = Task_LinkContest_StartInitFlags;
}

/** static void Task_LinkContest_StartInitFlags(u8 taskId) */
export function Task_LinkContest_StartInitFlags(...args: any[]): any {
  gTasks[taskId].func = Task_LinkContest_InitFlags;
}

/** static void Task_LinkContest_InitFlags(u8 taskId) */
export function Task_LinkContest_InitFlags(...args: any[]): any {
  let i: any = null;

      if (!gReceivedRemoteLinkPlayers)
          return;

      gContestPlayerMonIndex = GetMultiplayerId();
      gNumLinkContestPlayers = GetLinkPlayerCount();
      gLinkContestFlags = LINK_CONTEST_FLAG_IS_LINK;
      if (gWirelessCommType == 1)
          gLinkContestFlags = LINK_CONTEST_FLAG_IS_LINK | LINK_CONTEST_FLAG_IS_WIRELESS;

       
      for (i = 0; i < gNumLinkContestPlayers && (u32)(gLinkPlayers[i].version & 0xFF) - 1 > VERSION_RUBY - 1; i++)
          ;

      if (i < gNumLinkContestPlayers)
          gLinkContestFlags |= LINK_CONTEST_FLAG_HAS_RS_PLAYER;

      SwitchTaskToFollowupFunc(taskId);
}

/** bool32 LinkContest_TryLinkStandby(s16 *state) */
export function LinkContest_TryLinkStandby(...args: any[]): any {
  if (gLinkContestFlags & LINK_CONTEST_FLAG_HAS_RS_PLAYER)
          return TRUE;

      switch (*state)
      {
      case 0:
          if (IsLinkTaskFinished())
          {
              SetLinkStandbyCallback();
              (*state)++;
          }
          return FALSE;
      case 1:
          (*state)++;
          return FALSE;
      default:
          if (IsLinkTaskFinished() != TRUE)
              return FALSE;
          else
              return TRUE;
      }
}

/** void Task_LinkContest_CommunicateMonsRS(u8 taskId) */
export function Task_LinkContest_CommunicateMonsRS(...args: any[]): any {
  let i: any = null;

      if (!LinkContest_TryLinkStandby(gTasks[taskId].tStandbyState))
          return;

      switch (gTasks[taskId].tState)
      {
      case 0:
           
          if (GetMultiplayerId() == 0)
          {
              if (IsLinkTaskFinished())
              {
                  memcpy(gBlockSendBuffer, gContestMons[gContestPlayerMonIndex], sizeof(struct ContestPokemon));
                  gTasks[taskId].tState = 10;
              }
          }
          else
          {
              memcpy(gBlockSendBuffer, gContestMons[gContestPlayerMonIndex], sizeof(struct ContestPokemon));
              gTasks[taskId].tState = 1;
          }
          break;
      case 1:
           
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              for (i = 0; i < gNumLinkContestPlayers; i++)
              {
                  memcpy(gContestMons[i], gBlockRecvBuffer[i], sizeof(struct ContestPokemon));
                  StripPlayerAndMonNamesForLinkContest(gContestMons[i], gLinkPlayers[i].language);
              }

              gTasks[taskId].tState++;
          }
          break;
      case 10:
           
          if (++gTasks[taskId].tTimer > 300)
          {
              SendBlockRequest(BLOCK_REQ_SIZE_100);
              gTasks[taskId].tState = 1;
          }
          break;
      default:
          gTasks[taskId].tState = 0;
          gTasks[taskId].tTimer = 0;
          gTasks[taskId].tStandbyState = 0;
          SwitchTaskToFollowupFunc(taskId);
          break;
      }
}

/** void Task_LinkContest_CommunicateRngRS(u8 taskId) */
export function Task_LinkContest_CommunicateRngRS(...args: any[]): any {
  switch (gTasks[taskId].tState)
      {
      case 0:
          if (GetMultiplayerId() == 0)
          {
              if (IsLinkTaskFinished() && LinkContest_SendBlock(gRngValue, sizeof(gRngValue)) == TRUE)
                  gTasks[taskId].tState++;
          }
          else
          {
              gTasks[taskId].tState++;
          }
          break;
      case 1:
          if (LinkContest_GetBlockReceived(0))
          {
              memcpy(gRngValue, gBlockRecvBuffer[0], sizeof(gRngValue));
              memcpy(gContestRngValue, gBlockRecvBuffer[0], sizeof(gContestRngValue));
              gTasks[taskId].tState++;
          }
          break;
      default:
          gTasks[taskId].tState = 0;
          SwitchTaskToFollowupFunc(taskId);
          break;
      }
}

/** void Task_LinkContest_CommunicateCategoryRS(u8 taskId) */
export function Task_LinkContest_CommunicateCategoryRS(...args: any[]): any {
  let i: any = null;

      if (!LinkContest_TryLinkStandby(gTasks[taskId].tStandbyState))
          return;

      switch (gTasks[taskId].tState)
      {
      case 0:
          gBlockSendBuffer[0] = gTasks[taskId].tCategory;
          if (GetMultiplayerId() == 0)
          {
              if (IsLinkTaskFinished())
                  gTasks[taskId].tState = 10;
          }
          else
          {
              gTasks[taskId].tState++;
          }
          break;
      case 1:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              for (i = 0; i < gNumLinkContestPlayers; i++)
                  gTasks[taskId].tCategories(i) = gBlockRecvBuffer[i][0];

              gTasks[taskId].tState++;
          }
          break;
      case 10:
          if (++gTasks[taskId].tTimer > 10)
          {
              SendBlockRequest(BLOCK_REQ_SIZE_100);
              gTasks[taskId].tState = 1;
          }
          break;
      default:
          gTasks[taskId].tState = 0;
          gTasks[taskId].tTimer = 0;
          gTasks[taskId].tStandbyState = 0;
          SwitchTaskToFollowupFunc(taskId);
          break;
      }
}

/** void Task_LinkContest_CommunicateMonIdxs(u8 taskId) */
export function Task_LinkContest_CommunicateMonIdxs(...args: any[]): any {
  switch (gTasks[taskId].tState)
      {
      case 0:
          if (IsLinkTaskFinished())
          {
              if (LinkContest_SendBlock(gContestPlayerMonIndex, sizeof(gContestPlayerMonIndex)) == TRUE)
                  gTasks[taskId].tState++;
          }
          break;
      case 1:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
              gTasks[taskId].tState++;
          break;
      default:
          gTasks[taskId].tState = 0;
          SwitchTaskToFollowupFunc(taskId);
          break;
      }
}

/** void Task_LinkContest_CommunicateMoveSelections(u8 taskId) */
export function Task_LinkContest_CommunicateMoveSelections(...args: any[]): any {
  let i: any = null;

      switch (gTasks[taskId].tState)
      {
      case 0:
          if (IsLinkTaskFinished())
          {
               
              if (LinkContest_SendBlock(eContestantStatus[gContestPlayerMonIndex].currMove, sizeof(eContestantStatus[gContestPlayerMonIndex].currMove)) == TRUE)
                  gTasks[taskId].tState++;
          }
          break;
      case 1:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
               
              for (i = 0; i < gNumLinkContestPlayers; i++)
                  eContestantStatus[i].currMove = gBlockRecvBuffer[i][0];

              gTasks[taskId].tState++;
          }
          break;
      default:
          gTasks[taskId].tState = 0;
          SwitchTaskToFollowupFunc(taskId);
          break;
      }
}

/** void Task_LinkContest_CommunicateFinalStandings(u8 taskId) */
export function Task_LinkContest_CommunicateFinalStandings(...args: any[]): any {
  switch (gTasks[taskId].tState)
      {
      case 0:
          if (IsLinkTaskFinished())
          {
              if (LinkContest_SendBlock(gContestMonTotalPoints, sizeof(gContestMonTotalPoints)) == 1)
                  gTasks[taskId].tState++;
          }
          break;
      case 1:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              memcpy(gContestMonTotalPoints, gBlockRecvBuffer[gContestLinkLeaderIndex], sizeof(gContestMonTotalPoints));
              gTasks[taskId].tState++;
          }
          break;
      case 2:
      case 5:
      case 8:
      case 11:
          if (gTasks[taskId].tDelayTimer++ > 10)
          {
              gTasks[taskId].tDelayTimer = 0;
              gTasks[taskId].tState++;
          }
          break;
      case 3:
          if (IsLinkTaskFinished())
          {
              if (LinkContest_SendBlock(gContestMonAppealPointTotals, sizeof(gContestMonAppealPointTotals)) == 1)
                  gTasks[taskId].tState++;
          }
          break;
      case 4:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              memcpy(gContestMonAppealPointTotals, gBlockRecvBuffer[gContestLinkLeaderIndex], sizeof(gContestMonAppealPointTotals));
              gTasks[taskId].tState++;
          }
          break;
      case 6:
          if (IsLinkTaskFinished())
          {
              if (LinkContest_SendBlock(gContestMonRound2Points, sizeof(gContestMonRound2Points)) == 1)
                  gTasks[taskId].tState++;
          }
          break;
      case 7:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              memcpy(gContestMonRound2Points, gBlockRecvBuffer[gContestLinkLeaderIndex], sizeof(gContestMonRound2Points));
              gTasks[taskId].tState++;
          }
          break;
      case 9:
          if (IsLinkTaskFinished())
          {
              if (LinkContest_SendBlock(gContestFinalStandings, sizeof(gContestFinalStandings)) == 1)
                  gTasks[taskId].tState++;
          }
          break;
      case 10:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              memcpy(gContestFinalStandings, gBlockRecvBuffer[gContestLinkLeaderIndex], sizeof(gContestFinalStandings));
              gTasks[taskId].tState++;
          }
          break;
      default:
          gTasks[taskId].tState = 0;
          SwitchTaskToFollowupFunc(taskId);
          break;
      }
}

/** void Task_LinkContest_CommunicateAppealsState(u8 taskId) */
export function Task_LinkContest_CommunicateAppealsState(...args: any[]): any {
  switch (gTasks[taskId].tState)
      {
      case 0:
          if (IsLinkTaskFinished())
          {
              if (LinkContest_SendBlock(eContestantStatus, CONTESTANT_COUNT * sizeof(struct ContestantStatus)) == 1)
                  gTasks[taskId].tState++;
          }
          break;
      case 1:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              memcpy(eContestantStatus, gBlockRecvBuffer[gContestLinkLeaderIndex], CONTESTANT_COUNT * sizeof(struct ContestantStatus));
              gTasks[taskId].tState++;
          }
          break;
      case 2:
      case 5:
      case 8:
      case 11:
          if (gTasks[taskId].tDelayTimer++ > 10)
          {
              gTasks[taskId].tDelayTimer = 0;
              gTasks[taskId].tState++;
          }
          break;
      case 3:
          if (IsLinkTaskFinished())
          {
              if (LinkContest_SendBlock(gContestResources.appealResults, sizeof(struct ContestAppealMoveResults)) == 1)
                  gTasks[taskId].tState++;
          }
          break;
      case 4:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              memcpy(gContestResources.appealResults, gBlockRecvBuffer[gContestLinkLeaderIndex], sizeof(struct ContestAppealMoveResults));
              gTasks[taskId].tState++;
          }
          break;
      case 6:
          if (IsLinkTaskFinished())
          {
              if (LinkContest_SendBlock(gContestResources.excitement, sizeof(struct ContestExcitement)) == 1)
                  gTasks[taskId].tState++;
          }
          break;
      case 7:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              memcpy(gContestResources.excitement, gBlockRecvBuffer[gContestLinkLeaderIndex], sizeof(struct ContestExcitement));
              gTasks[taskId].tState++;
          }
          break;
      case 9:
          if (IsLinkTaskFinished())
          {
              if (LinkContest_SendBlock(gContestantTurnOrder, sizeof(gContestantTurnOrder)) == 1)
                  gTasks[taskId].tState++;
          }
          break;
      case 10:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              memcpy(gContestantTurnOrder, gBlockRecvBuffer[gContestLinkLeaderIndex], sizeof(gContestantTurnOrder));
              gTasks[taskId].tState++;
          }
          break;
      default:
          gTasks[taskId].tState = 0;
          SwitchTaskToFollowupFunc(taskId);
          break;
      }
}

/** void Task_LinkContest_CommunicateLeaderIdsRS(u8 taskId) */
export function Task_LinkContest_CommunicateLeaderIdsRS(...args: any[]): any {
  let i: any = null;

      if (!LinkContest_TryLinkStandby(gTasks[taskId].tStandbyState))
          return;

      switch (gTasks[taskId].tState)
      {
      case 0:
          gBlockSendBuffer[0] = 0x6E;
          if (GetMultiplayerId() == 0)
          {
              if (IsLinkTaskFinished())
                  gTasks[taskId].tState = 10;
          }
          else
          {
              gTasks[taskId].tState++;
          }
          break;
      case 1:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              for (i = 0; i < CONTESTANT_COUNT; i++)
                  gTasks[taskId].tLeaderIds(i) = gBlockRecvBuffer[i][0];

              gTasks[taskId].tState++;
          }
          break;
      case 10:
          if (++gTasks[taskId].tTimer > 10)
          {
              SendBlockRequest(BLOCK_REQ_SIZE_100);
              gTasks[taskId].tState = 1;
          }
          break;
      default:
          gTasks[taskId].tState = 0;
          gTasks[taskId].tTimer = 0;
          gTasks[taskId].tStandbyState = 0;
          SwitchTaskToFollowupFunc(taskId);
          break;
      }
}

/** void Task_LinkContest_CommunicateRound1Points(u8 taskId) */
export function Task_LinkContest_CommunicateRound1Points(...args: any[]): any {
  if (!LinkContest_TryLinkStandby(gTasks[taskId].tStandbyState))
          return;

      switch (gTasks[taskId].tState)
      {
      case 0:
          if (IsLinkTaskFinished())
          {
              if (LinkContest_SendBlock(gContestMonRound1Points, sizeof(gContestMonRound1Points)) == 1)
                  gTasks[taskId].tState++;
          }
          break;
      case 1:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              memcpy(gContestMonRound1Points, gBlockRecvBuffer[gContestLinkLeaderIndex], sizeof(gContestMonRound1Points));
              gTasks[taskId].tState++;
          }
          break;
      default:
          gTasks[taskId].tState = 0;
          gTasks[taskId].tStandbyState = 0;
          SwitchTaskToFollowupFunc(taskId);
          break;
      }
}

/** void Task_LinkContest_CommunicateTurnOrder(u8 taskId) */
export function Task_LinkContest_CommunicateTurnOrder(...args: any[]): any {
  if (!LinkContest_TryLinkStandby(gTasks[taskId].tStandbyState))
          return;

      switch (gTasks[taskId].tState)
      {
      case 0:
          if (IsLinkTaskFinished())
          {
              if (LinkContest_SendBlock(gContestantTurnOrder, sizeof(gContestantTurnOrder)) == 1)
                  gTasks[taskId].tState++;
          }
          break;
      case 1:
          if (LinkContest_GetBlockReceivedFromAllPlayers())
          {
              memcpy(gContestantTurnOrder, gBlockRecvBuffer[gContestLinkLeaderIndex], sizeof(gContestantTurnOrder));
              gTasks[taskId].tState++;
          }
          break;
      default:
          gTasks[taskId].tState = 0;
          gTasks[taskId].tStandbyState = 0;
          SwitchTaskToFollowupFunc(taskId);
          break;
      }
}

// ─── callsTo manifest (= 17 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["BitmaskAllOtherLinkPlayers","GetBlockReceivedStatus","GetLinkPlayerCount","GetLinkPlayerCountAsBitFlags","GetMultiplayerId","IsLinkTaskFinished","LinkContest_GetBlockReceived","LinkContest_GetBlockReceivedFromAllPlayers","LinkContest_SendBlock","LinkContest_TryLinkStandby","ResetBlockReceivedFlag","ResetBlockReceivedFlags","SendBlock","SendBlockRequest","SetLinkStandbyCallback","StripPlayerAndMonNamesForLinkContest","SwitchTaskToFollowupFunc"];
