// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/decoration_inventory.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 11 functions extracted from src/decoration_inventory.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck

// ─── BRIDGE IMPORT (auto-injected by inject-bridge-imports.mjs) ───
// Pull tous les callees ce module fait depuis le bridge unifié.
// Si un helper est bridgé : binding actif. Sinon : undefined → throw au call.
// Names already defined in this file via 'export function' are EXCLUDED
// to avoid "already declared" esbuild errors.
import * as _bridge from '../../../decomp-bridge';
const {
  InitDecorationContextItems, SET_DECOR_INV,  // 4-per-line for readability
} = _bridge;
// ─── END BRIDGE IMPORT ───
/** void SetDecorationInventoriesPointers(void) */
export function SetDecorationInventoriesPointers(): any {
  SET_DECOR_INV(DECORCAT_DESK, gSaveBlock1Ptr.decorationDesks);
      SET_DECOR_INV(DECORCAT_CHAIR, gSaveBlock1Ptr.decorationChairs);
      SET_DECOR_INV(DECORCAT_PLANT, gSaveBlock1Ptr.decorationPlants);
      SET_DECOR_INV(DECORCAT_ORNAMENT, gSaveBlock1Ptr.decorationOrnaments);
      SET_DECOR_INV(DECORCAT_MAT, gSaveBlock1Ptr.decorationMats);
      SET_DECOR_INV(DECORCAT_POSTER, gSaveBlock1Ptr.decorationPosters);
      SET_DECOR_INV(DECORCAT_DOLL, gSaveBlock1Ptr.decorationDolls);
      SET_DECOR_INV(DECORCAT_CUSHION, gSaveBlock1Ptr.decorationCushions);
      InitDecorationContextItems();
}

/** static void ClearDecorationInventory(u8 category) */
export function ClearDecorationInventory(category: any): any {
  let i: any = null;
      for (i = 0; i < gDecorationInventories[category].size; i ++)
          gDecorationInventories[category].items[i] = DECOR_NONE;
}

/** void ClearDecorationInventories(void) */
export function ClearDecorationInventories(): any {
  let category: any = null;
      for (category = 0; category < DECORCAT_COUNT; category++)
          ClearDecorationInventory(category);
}

/** s8 GetFirstEmptyDecorSlot(u8 category) */
export function GetFirstEmptyDecorSlot(category: any): any {
  let i: any = null;
      for (i = 0; i < gDecorationInventories[category].size; i++)
      {
          if (gDecorationInventories[category].items[i] == DECOR_NONE)
              return i;
      }

      return -1;
}

/** bool8 CheckHasDecoration(u8 decor) */
export function CheckHasDecoration(decor: any): any {
  let i: any = null;
      let category: any = null;

      category = gDecorations[decor].category;
      for (i = 0; i < gDecorationInventories[category].size; i ++)
      {
          if (gDecorationInventories[category].items[i] == decor)
              return TRUE;
      }

      return FALSE;
}

/** bool8 DecorationAdd(u8 decor) */
export function DecorationAdd(decor: any): any {
  let category: any = null;
      let idx: any = null;

      if (decor == DECOR_NONE)
          return FALSE;
      category = gDecorations[decor].category;
      idx = GetFirstEmptyDecorSlot(category);
      if (idx == -1)
          return FALSE;
      gDecorationInventories[category].items[idx] = decor;
      return TRUE;
}

/** bool8 DecorationCheckSpace(u8 decor) */
export function DecorationCheckSpace(decor: any): any {
  if (decor == DECOR_NONE)
          return FALSE;
      if (GetFirstEmptyDecorSlot(gDecorations[decor].category) == -1)
          return FALSE;
      return TRUE;
}

/** s8 DecorationRemove(u8 decor) */
export function DecorationRemove(decor: any): any {
  let i: any = null;
      let category: any = null;

      i = 0;
      if (decor == DECOR_NONE)
          return 0;

      for (i = 0; i < gDecorationInventories[gDecorations[decor].category].size; i ++)
      {
          category = gDecorations[decor].category;
          if (gDecorationInventories[category].items[i] == decor)
          {
              gDecorationInventories[category].items[i] = DECOR_NONE;
              CondenseDecorationsInCategory(category);
              return 1;
          }
      }

      return 0;
}

/** void CondenseDecorationsInCategory(u8 category) */
export function CondenseDecorationsInCategory(category: any): any {
  let i: any = null;
      let j: any = null;
      let tmp: any = null;

      for (i = 0; i < gDecorationInventories[category].size; i ++)
      {
          for (j = i + 1; j < gDecorationInventories[category].size; j ++)
          {
              if (gDecorationInventories[category].items[j] != DECOR_NONE && (gDecorationInventories[category].items[i] == DECOR_NONE || gDecorationInventories[category].items[i] > gDecorationInventories[category].items[j]))
              {
                  tmp = gDecorationInventories[category].items[i];
                  gDecorationInventories[category].items[i] = gDecorationInventories[category].items[j];
                  gDecorationInventories[category].items[j] = tmp;
              }
          }
      }
}

/** u8 GetNumOwnedDecorationsInCategory(u8 category) */
export function GetNumOwnedDecorationsInCategory(category: any): any {
  let i: any = null;
      let ct: any = null;

      ct = 0;
      for (i = 0; i < gDecorationInventories[category].size; i++)
      {
          if (gDecorationInventories[category].items[i] != DECOR_NONE)
              ct++;
      }

      return ct;
}

/** u8 GetNumOwnedDecorations(void) */
export function GetNumOwnedDecorations(): any {
  let category: any = null;
      let count: any = null;

      count = 0;
      for (category = 0; category < DECORCAT_COUNT; category++)
          count += GetNumOwnedDecorationsInCategory(category);

      return count;
}

// ─── callsTo manifest (= 6 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["ClearDecorationInventory","CondenseDecorationsInCategory","GetFirstEmptyDecorSlot","GetNumOwnedDecorationsInCategory","InitDecorationContextItems","SET_DECOR_INV"];
