// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/dynamic_placeholder_text_util.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 2 functions extracted from src/dynamic_placeholder_text_util.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck

// ─── BRIDGE IMPORT (auto-injected by inject-bridge-imports.mjs) ───
// Pull tous les callees ce module fait depuis le bridge unifié.
// Si un helper est bridgé : binding actif. Sinon : undefined → throw au call.
// Names already defined in this file via 'export function' are EXCLUDED
// to avoid "already declared" esbuild errors.
import * as _bridge from '../../../decomp-bridge';
const {
  ARRAY_COUNT, NULL,  // 4-per-line for readability
} = _bridge;
// ─── END BRIDGE IMPORT ───
/** void DynamicPlaceholderTextUtil_Reset(void) */
export function DynamicPlaceholderTextUtil_Reset(): any {
  let i: any = null;
      for (i = 0; i < ARRAY_COUNT(sStringPointers); i++)
          sStringPointers[i] = NULL;
}

/** void DynamicPlaceholderTextUtil_SetPlaceholderPtr(u8 idx, const u8 *ptr) */
export function DynamicPlaceholderTextUtil_SetPlaceholderPtr(idx: any, ptr: any): any {
  if (idx < ARRAY_COUNT(sStringPointers))
      {
          sStringPointers[idx] = ptr;
      }
}

// ─── callsTo manifest (= 1 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["ARRAY_COUNT"];
