// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/field_door.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 20 functions extracted from src/field_door.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck


// ─── AUTO-INJECTED file-scope vars (= EWRAM/IWRAM static C decls) ──
let tCounter: any = null;
let tFramesHi: any = null;
let tFramesLo: any = null;
let tGfxHi: any = null;
let tGfxLo: any = null;
let tX: any = null;
let tY: any = null;
/** static void CopyDoorTilesToVram(const struct DoorGraphics *gfx, const struct DoorAnimFrame *frame) */
export function CopyDoorTilesToVram(gfx: any, frame: any): any {
  if (gfx.size == 2)
          CpuFastCopy(gfx.tiles + frame.offset, (VRAM + TILE_OFFSET_4BPP((((1024) - 16)))), 16 * TILE_SIZE_4BPP);
      else
          CpuFastCopy(gfx.tiles + frame.offset, (VRAM + TILE_OFFSET_4BPP((((1024) - 8)))), 8 * TILE_SIZE_4BPP);
}

/** static void BuildDoorTiles(u16 *tiles, u16 tileNum, const u8 *paletteNums) */
export function BuildDoorTiles(tiles: any, tileNum: any, paletteNums: any): any {
  let i: any = null;
      let tile: any = null;

       
      for (i = 0; i < 4; i++)
      {
          tile = (paletteNums++) << 12;
          tiles[i] = tile | (tileNum + i);
      }

       
      for (; i < 8; i++)
      {
          tile = (paletteNums++) << 12;
          tiles[i] = tile;
      }
}

/** static void DrawCurrentDoorAnimFrame(const struct DoorGraphics *gfx, u32 x, u32 y, const u8 *paletteNums) */
export function DrawCurrentDoorAnimFrame(gfx: any, x: any, y: any, paletteNums: any): any {
  let tiles: any = [];

      if (gfx.size == 2)
      {
           
          BuildDoorTiles(tiles[8], (((1024) - 16)) + 0,paletteNums[0]);
          DrawDoorMetatileAt(x, y - 1,tiles[8]);

           
          BuildDoorTiles(tiles[8], (((1024) - 16)) + 4,paletteNums[4]);
          DrawDoorMetatileAt(x, y,tiles[8]);

           
          BuildDoorTiles(tiles[8], (((1024) - 16)) + 8,paletteNums[0]);
          DrawDoorMetatileAt(x + 1, y - 1,tiles[8]);

           
          BuildDoorTiles(tiles[8], (((1024) - 16)) + 12,paletteNums[4]);
          DrawDoorMetatileAt(x + 1, y,tiles[8]);
      }
      else
      {
           
          BuildDoorTiles(tiles[0], (((1024) - 8)) + 0,paletteNums[0]);
          DrawDoorMetatileAt(x, y - 1,tiles[0]);

           
          BuildDoorTiles(tiles[0], (((1024) - 8)) + 4,paletteNums[4]);
          DrawDoorMetatileAt(x, y,tiles[0]);
      }
}

/** static void DrawClosedDoorTiles(const struct DoorGraphics *gfx, u32 x, u32 y) */
export function DrawClosedDoorTiles(gfx: any, x: any, y: any): any {
  CurrentMapDrawMetatileAt(x, y - 1);
      CurrentMapDrawMetatileAt(x, y);

      if (gfx.size == 2)
      {
          CurrentMapDrawMetatileAt(x + 1, y - 1);
          CurrentMapDrawMetatileAt(x + 1, y);
      }
}

/** static void DrawDoor(const struct DoorGraphics *gfx, const struct DoorAnimFrame *frame, u32 x, u32 y) */
export function DrawDoor(gfx: any, frame: any, x: any, y: any): any {
  if (frame.offset == 0xFFFF)
      {
          DrawClosedDoorTiles(gfx, x, y);
          if (ShouldUseMultiCorridorDoor())
              DrawClosedDoorTiles(gfx, gSpecialVar_0x8004 + (7), gSpecialVar_0x8005 + (7));
      }
      else
      {
          CopyDoorTilesToVram(gfx, frame);
          DrawCurrentDoorAnimFrame(gfx, x, y, gfx.palettes);
          if (ShouldUseMultiCorridorDoor())
              DrawCurrentDoorAnimFrame(gfx, gSpecialVar_0x8004 + (7), gSpecialVar_0x8005 + (7), gfx.palettes);
      }
}

/** static bool32 AnimateDoorFrame(struct DoorGraphics *gfx, struct DoorAnimFrame *frames, s16 *data) */
export function AnimateDoorFrame(gfx: any, frames: any, data: any): any {
  if (tCounter == 0)
          DrawDoor(gfx,frames[tFrameId], tX, tY);

      if (tCounter == frames[tFrameId].time)
      {
          tCounter = 0;
          tFrameId++;
          if (frames[tFrameId].time == 0)
              return FALSE;
          else
              return TRUE;
      }
      tCounter++;
      return TRUE;
}

/** static void Task_AnimateDoor(u8 taskId) */
export function Task_AnimateDoor(taskId: any): any {
  let data: any = gTasks[taskId].data;
      let frames: any = (tFramesHi << 16 | tFramesLo);
      let gfx: any = (tGfxHi << 16 | tGfxLo);

      if (AnimateDoorFrame(gfx, frames, data) == FALSE)
          DestroyTask(taskId);
}

/** static s8 StartDoorAnimationTask(const struct DoorGraphics *gfx, const struct DoorAnimFrame *frames, u32 x, u32 y) */
export function StartDoorAnimationTask(gfx: any, frames: any, x: any, y: any): any {
  if (FuncIsActiveTask(Task_AnimateDoor) == TRUE)
      {
          return -1;
      }
      else
      {
          let taskId: any = CreateTask(Task_AnimateDoor, 0x50);
          let data: any = gTasks[taskId].data;

          tX = x;
          tY = y;

          tFramesLo = frames;
          tFramesHi = frames >> 16;

          tGfxLo = gfx;
          tGfxHi = gfx >> 16;

          return taskId;
      }
}

/** static void DrawClosedDoor(const struct DoorGraphics *gfx, u32 x, u32 y) */
export function DrawClosedDoor(gfx: any, x: any, y: any): any {
  DrawClosedDoorTiles(gfx, x, y);
}

/** static void DrawOpenedDoor(const struct DoorGraphics *gfx, u32 x, u32 y) */
export function DrawOpenedDoor(gfx: any, x: any, y: any): any {
  gfx = GetDoorGraphics(gfx, MapGridGetMetatileIdAt(x, y));
      if (gfx != NULL)
          DrawDoor(gfx, GetLastDoorFrame(sDoorOpenAnimFrames, sDoorOpenAnimFrames), x, y);
}

/** static s8 StartDoorOpenAnimation(const struct DoorGraphics *gfx, u32 x, u32 y) */
export function StartDoorOpenAnimation(gfx: any, x: any, y: any): any {
  gfx = GetDoorGraphics(gfx, MapGridGetMetatileIdAt(x, y));
      if (gfx == NULL)
      {
          return -1;
      }
      else
      {
          if (gfx.size == 2)
              return StartDoorAnimationTask(gfx, sBigDoorOpenAnimFrames, x, y);
          else
              return StartDoorAnimationTask(gfx, sDoorOpenAnimFrames, x, y);
      }
}

/** static s8 StartDoorCloseAnimation(const struct DoorGraphics *gfx, u32 x, u32 y) */
export function StartDoorCloseAnimation(gfx: any, x: any, y: any): any {
  gfx = GetDoorGraphics(gfx, MapGridGetMetatileIdAt(x, y));
      if (gfx == NULL)
          return -1;
      else
          return StartDoorAnimationTask(gfx, sDoorCloseAnimFrames, x, y);
}

/** static s8 GetDoorSoundType(const struct DoorGraphics *gfx, u32 x, u32 y) */
export function GetDoorSoundType(gfx: any, x: any, y: any): any {
  gfx = GetDoorGraphics(gfx, MapGridGetMetatileIdAt(x, y));
      if (gfx == NULL)
          return -1;
      else
          return gfx.sound;
}

/** void FieldSetDoorOpened(u32 x, u32 y) */
export function FieldSetDoorOpened(x: any, y: any): any {
  if (MetatileBehavior_IsDoor(MapGridGetMetatileBehaviorAt(x, y)))
          DrawOpenedDoor(sDoorAnimGraphicsTable, x, y);
}

/** void FieldSetDoorClosed(u32 x, u32 y) */
export function FieldSetDoorClosed(x: any, y: any): any {
  if (MetatileBehavior_IsDoor(MapGridGetMetatileBehaviorAt(x, y)))
          DrawClosedDoor(sDoorAnimGraphicsTable, x, y);
}

/** s8 FieldAnimateDoorClose(u32 x, u32 y) */
export function FieldAnimateDoorClose(x: any, y: any): any {
  if (!MetatileBehavior_IsDoor(MapGridGetMetatileBehaviorAt(x, y)))
          return -1;
      else
          return StartDoorCloseAnimation(sDoorAnimGraphicsTable, x, y);
}

/** s8 FieldAnimateDoorOpen(u32 x, u32 y) */
export function FieldAnimateDoorOpen(x: any, y: any): any {
  if (!MetatileBehavior_IsDoor(MapGridGetMetatileBehaviorAt(x, y)))
          return -1;
      else
          return StartDoorOpenAnimation(sDoorAnimGraphicsTable, x, y);
}

/** bool8 FieldIsDoorAnimationRunning(void) */
export function FieldIsDoorAnimationRunning(): any {
  return FuncIsActiveTask(Task_AnimateDoor);
}

/** u32 GetDoorSoundEffect(u32 x, u32 y) */
export function GetDoorSoundEffect(x: any, y: any): any {
  let sound: any = GetDoorSoundType(sDoorAnimGraphicsTable, x, y);

      if (sound == (0))
          return (8);
      else if (sound == (1))
          return (18);
      else if (sound == (2))
          return (47);
      else
          return (8);
}

/** static bool8 ShouldUseMultiCorridorDoor(void) */
export function ShouldUseMultiCorridorDoor(): any {
  if (FlagGet((((0x4000) + 0x2))))
      {
          if (gSaveBlock1Ptr.location.mapGroup == MAP_GROUP(MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR)
              && gSaveBlock1Ptr.location.mapNum == MAP_NUM(MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR))
          {
              return TRUE;
          }
      }
      return FALSE;
}

// ─── callsTo manifest (= 28 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["AnimateDoorFrame","BuildDoorTiles","CopyDoorTilesToVram","CpuFastCopy","CreateTask","CurrentMapDrawMetatileAt","DestroyTask","DrawClosedDoor","DrawClosedDoorTiles","DrawCurrentDoorAnimFrame","DrawDoor","DrawDoorMetatileAt","DrawOpenedDoor","FlagGet","FuncIsActiveTask","GetDoorGraphics","GetDoorSoundType","GetLastDoorFrame","MAP_GROUP","MAP_NUM","MapGridGetMetatileBehaviorAt","MapGridGetMetatileIdAt","MetatileBehavior_IsDoor","ShouldUseMultiCorridorDoor","StartDoorAnimationTask","StartDoorCloseAnimation","StartDoorOpenAnimation","TILE_OFFSET_4BPP"];
