// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/fldeff_softboiled.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 8 functions extracted from src/fldeff_softboiled.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck

/** bool8 SetUpFieldMove_SoftBoiled(void) */
export function SetUpFieldMove_SoftBoiled(): any {
  let maxHp: any = null;
      let hp: any = null;
      let minHp: any = null;

      maxHp = GetMonData(gPlayerParty[GetCursorSelectionMonId()], MON_DATA_MAX_HP);
      hp = GetMonData(gPlayerParty[GetCursorSelectionMonId()], MON_DATA_HP);

      minHp = (maxHp / 5);
      if (hp > minHp)
          return TRUE;
      return FALSE;
}

/** void ChooseMonForSoftboiled(u8 taskId) */
export function ChooseMonForSoftboiled(taskId: any): any {
  gPartyMenu.action = (10);
      gPartyMenu.slotId2 =  gPartyMenu.slotId;
      AnimatePartySlot(GetCursorSelectionMonId(), 1);
      DisplayPartyMenuStdMessage((5));
      gTasks[taskId].func = Task_HandleChooseMonInput;
}

/** void Task_TryUseSoftboiledOnPartyMon(u8 taskId) */
export function Task_TryUseSoftboiledOnPartyMon(taskId: any): any {
  let hp: any = null;

      let userPartyId: any = gPartyMenu.slotId;
      let recipientPartyId: any = gPartyMenu.slotId2;
      if(recipientPartyId > (6))
      {
          gPartyMenu.action = 0;
          DisplayPartyMenuStdMessage((0));
          gTasks[taskId].func = Task_HandleChooseMonInput;
          return;
      }

      hp = GetMonData(gPlayerParty[recipientPartyId], MON_DATA_HP);
      if(hp == 0 || userPartyId == recipientPartyId || GetMonData(gPlayerParty[recipientPartyId], MON_DATA_MAX_HP) == hp)
      {
          CantUseSoftboiledOnMon(taskId);
          return;
      }

       
      PlaySE((1));
      PartyMenuModifyHP(taskId, userPartyId, -1, GetMonData(gPlayerParty[userPartyId], MON_DATA_MAX_HP)/5, Task_SoftboiledRestoreHealth);
}

/** static void Task_SoftboiledRestoreHealth(u8 taskId) */
export function Task_SoftboiledRestoreHealth(taskId: any): any {
  PlaySE((1));
      PartyMenuModifyHP(taskId, gPartyMenu.slotId2, 1, GetMonData(gPlayerParty[gPartyMenu.slotId], MON_DATA_MAX_HP)/5, Task_DisplayHPRestoredMessage);
}

/** static void Task_DisplayHPRestoredMessage(u8 taskId) */
export function Task_DisplayHPRestoredMessage(taskId: any): any {
  GetMonNickname(gPlayerParty[gPartyMenu.slotId2], gStringVar1);
      StringExpandPlaceholders(gStringVar4, gText_PkmnHPRestoredByVar2);
      DisplayPartyMenuMessage(gStringVar4, FALSE);
      ScheduleBgCopyTilemapToVram(2);
      gTasks[taskId].func = Task_FinishSoftboiled;
}

/** static void Task_FinishSoftboiled(u8 taskId) */
export function Task_FinishSoftboiled(taskId: any): any {
  if(IsPartyMenuTextPrinterActive() == TRUE)
          return;
      gPartyMenu.action = 0;
      AnimatePartySlot(gPartyMenu.slotId, 0);
      gPartyMenu.slotId = gPartyMenu.slotId2;
      AnimatePartySlot(gPartyMenu.slotId2, 1);
      ClearStdWindowAndFrameToTransparent(6, FALSE);
      ClearWindowTilemap(6);
      DisplayPartyMenuStdMessage((0));
      gTasks[taskId].func = Task_HandleChooseMonInput;
}

/** static void Task_ChooseNewMonForSoftboiled(u8 taskId) */
export function Task_ChooseNewMonForSoftboiled(taskId: any): any {
  if(IsPartyMenuTextPrinterActive() == TRUE)
          return;
      DisplayPartyMenuStdMessage((5));
      gTasks[taskId].func = Task_HandleChooseMonInput;
}

/** static void CantUseSoftboiledOnMon(u8 taskId) */
export function CantUseSoftboiledOnMon(taskId: any): any {
  PlaySE((5));
      DisplayPartyMenuMessage(gText_CantBeUsedOnPkmn, FALSE);
      ScheduleBgCopyTilemapToVram(2);
      gTasks[taskId].func = Task_ChooseNewMonForSoftboiled;
}

// ─── callsTo manifest (= 14 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["AnimatePartySlot","CantUseSoftboiledOnMon","ClearStdWindowAndFrameToTransparent","ClearWindowTilemap","DisplayPartyMenuMessage","DisplayPartyMenuStdMessage","GetCursorSelectionMonId","GetMonData","GetMonNickname","IsPartyMenuTextPrinterActive","PartyMenuModifyHP","PlaySE","ScheduleBgCopyTilemapToVram","StringExpandPlaceholders"];
