// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/fldeff_strength.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 4 functions extracted from src/fldeff_strength.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck


// ─── AUTO-INJECTED file-scope vars (= EWRAM/IWRAM static C decls) ──
let gPostMenuFieldCallback: any = null;
/** bool8 SetUpFieldMove_Strength(void) */
export function SetUpFieldMove_Strength(): any {
  if (CheckObjectGraphicsInFrontOfPlayer((87)) == TRUE)
      {
          gSpecialVar_Result = GetCursorSelectionMonId();
          gFieldCallback2 = FieldCallback_PrepareFadeInFromMenu;
          gPostMenuFieldCallback = FieldCallback_Strength;
          return TRUE;
      }
      return FALSE;
}

/** static void FieldCallback_Strength(void) */
export function FieldCallback_Strength(): any {
  gFieldEffectArguments[0] = GetCursorSelectionMonId();
      ScriptContext_SetupScript(EventScript_UseStrength);
}

/** bool8 FldEff_UseStrength(void) */
export function FldEff_UseStrength(): any {
  let taskId: any = CreateFieldMoveTask();
      gTasks[taskId].data[8] = StartStrengthFieldEffect >> 16;
      gTasks[taskId].data[9] = StartStrengthFieldEffect;
      GetMonNickname(gPlayerParty[gFieldEffectArguments[0]], gStringVar1);
      return FALSE;
}

/** static void StartStrengthFieldEffect(void) */
export function StartStrengthFieldEffect(): any {
  FieldEffectActiveListRemove((40));
      ScriptContext_Enable();
}

// ─── callsTo manifest (= 7 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["CheckObjectGraphicsInFrontOfPlayer","CreateFieldMoveTask","FieldEffectActiveListRemove","GetCursorSelectionMonId","GetMonNickname","ScriptContext_Enable","ScriptContext_SetupScript"];
