// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/gym_leader_rematch.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 3 functions extracted from src/gym_leader_rematch.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck

/** void UpdateGymLeaderRematch(void) */
export function UpdateGymLeaderRematch(): any {
  if (FlagGet(FLAG_SYS_GAME_CLEAR) && (Random() % 100) <= 30)
      {
          if (FlagGet(FLAG_WATTSON_REMATCH_AVAILABLE))
              UpdateGymLeaderRematchFromArray(GymLeaderRematches_AfterNewMauville, ARRAY_COUNT(GymLeaderRematches_AfterNewMauville), 5);
          else
              UpdateGymLeaderRematchFromArray(GymLeaderRematches_BeforeNewMauville, ARRAY_COUNT(GymLeaderRematches_BeforeNewMauville), 1);
      }
}

/** static void UpdateGymLeaderRematchFromArray(const u16 *data, size_t size, u32 maxRematch) */
export function UpdateGymLeaderRematchFromArray(data: any, size: any, maxRematch: any): any {
  let whichLeader: any = 0;
      let lowestRematchIndex: any = 5;
      let i: any = null;
      let rematchIndex: any = null;
      for (i = 0; i < size; i++)
      {
          if (!gSaveBlock1Ptr.trainerRematches[data[i]])
          {
              rematchIndex = GetRematchIndex(data[i]);
              if (lowestRematchIndex > rematchIndex)
                  lowestRematchIndex = rematchIndex;
              whichLeader++;
          }
      }
      if (whichLeader != 0 && lowestRematchIndex <= maxRematch)
      {
          whichLeader = 0;
          for (i = 0; i < size; i++)
          {
              if (!gSaveBlock1Ptr.trainerRematches[data[i]])
              {
                  rematchIndex = GetRematchIndex(data[i]);
                  if (rematchIndex == lowestRematchIndex)
                      whichLeader++;
              }
          }
          if (whichLeader != 0)
          {
              whichLeader = Random() % whichLeader;
              for (i = 0; i < size; i++)
              {
                  if (!gSaveBlock1Ptr.trainerRematches[data[i]])
                  {
                      rematchIndex = GetRematchIndex(data[i]);
                      if (rematchIndex == lowestRematchIndex)
                      {
                          if (whichLeader == 0)
                          {
                              gSaveBlock1Ptr.trainerRematches[data[i]] = lowestRematchIndex;
                              break;
                          }
                          whichLeader--;
                      }
                  }
              }
          }
      }
}

/** static s32 GetRematchIndex(u32 trainerIdx) */
export function GetRematchIndex(trainerIdx: any): any {
  let i: any = null;
      for (i = 0; i < 5; i++)
      {
          if (!HasTrainerBeenFought(gRematchTable[trainerIdx].trainerIds[i]))
          {
              return i;
          }
      }
      return 5;
}

// ─── callsTo manifest (= 6 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["ARRAY_COUNT","FlagGet","GetRematchIndex","HasTrainerBeenFought","Random","UpdateGymLeaderRematchFromArray"];
