// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/hof_pc.c
// Generated : 2026-05-08
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 4 functions extracted from src/hof_pc.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck

/** void AccessHallOfFamePC(void) */
export function AccessHallOfFamePC(): any {
  SetMainCallback2(CB2_DoHallOfFamePC);
      LockPlayerFieldControls();
}

/** void ReturnFromHallOfFamePC(void) */
export function ReturnFromHallOfFamePC(): any {
  SetMainCallback2(CB2_ReturnToField);
      gFieldCallback = ReshowPCMenuAfterHallOfFamePC;
}

/** static void ReshowPCMenuAfterHallOfFamePC(void) */
export function ReshowPCMenuAfterHallOfFamePC(): any {
  LockPlayerFieldControls();
      Overworld_PlaySpecialMapMusic();
      ScriptMenu_CreatePCMultichoice();
      ScriptMenu_DisplayPCStartupPrompt();
      BeginNormalPaletteFade(PALETTES_ALL, 0, 0x10, 0, RGB_BLACK);
      CreateTask(Task_WaitForPaletteFade, 10);
}

/** static void Task_WaitForPaletteFade(u8 taskId) */
export function Task_WaitForPaletteFade(...args: any[]): any {
  if (!gPaletteFade.active)
          DestroyTask(taskId);
}

// ─── callsTo manifest (= 8 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["BeginNormalPaletteFade","CreateTask","DestroyTask","LockPlayerFieldControls","Overworld_PlaySpecialMapMusic","ScriptMenu_CreatePCMultichoice","ScriptMenu_DisplayPCStartupPrompt","SetMainCallback2"];
