// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/pokemon_icon.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 20 functions extracted from src/pokemon_icon.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck

/** u8 CreateMonIcon(u16 species, void (*callback)(struct Sprite *), s16 x, s16 y, u8 subpriority, u32 personality, bool32 handleDeoxys) */
export function CreateMonIcon(species: any, callback: any, x: any, y: any, subpriority: any, personality: any, handleDeoxys: any): any {
  let spriteId: any = null;
      let iconTemplate: any =
      [ sMonIconOamData, GetMonIconPtr(species, personality, handleDeoxys), sMonIconAnims, sMonIconAffineAnims, callback, POKE_ICON_BASE_PAL_TAG + gMonIconPaletteIndices[species],
      ];

      if (species > NUM_SPECIES)
          iconTemplate.paletteTag = POKE_ICON_BASE_PAL_TAG;

      spriteId = CreateMonIconSprite(iconTemplate, x, y, subpriority);

      UpdateMonIconFrame(gSprites[spriteId]);

      return spriteId;
}

/** u8 CreateMonIconNoPersonality(u16 species, void (*callback)(struct Sprite *), s16 x, s16 y, u8 subpriority, bool32 handleDeoxys) */
export function CreateMonIconNoPersonality(species: any, callback: any, x: any, y: any, subpriority: any, handleDeoxys: any): any {
  let spriteId: any = null;
      let iconTemplate: any =
      [ sMonIconOamData, NULL, sMonIconAnims, sMonIconAffineAnims, callback, POKE_ICON_BASE_PAL_TAG + gMonIconPaletteIndices[species],
      ];

      iconTemplate.image = GetMonIconTiles(species, handleDeoxys);
      spriteId = CreateMonIconSprite(iconTemplate, x, y, subpriority);

      UpdateMonIconFrame(gSprites[spriteId]);

      return spriteId;
}

/** u16 GetIconSpecies(u16 species, u32 personality) */
export function GetIconSpecies(species: any, personality: any): any {
  let result: any = null;

      if (species == SPECIES_UNOWN)
      {
          let letter: any = GetUnownLetterByPersonality(personality);
          if (letter == 0)
              letter = SPECIES_UNOWN;
          else
              letter += (SPECIES_UNOWN_B - 1);
          result = letter;
      }
      else
      {
          if (species > NUM_SPECIES)
              result = INVALID_ICON_SPECIES;
          else
              result = species;
      }

      return result;
}

/** u16 GetUnownLetterByPersonality(u32 personality) */
export function GetUnownLetterByPersonality(personality: any): any {
  if (!personality)
          return 0;
      else
          return GET_UNOWN_LETTER(personality);
}

/** u16 GetIconSpeciesNoPersonality(u16 species) */
export function GetIconSpeciesNoPersonality(species: any): any {
  let value: any = null;

      if (MailSpeciesToSpecies(species,value) == SPECIES_UNOWN)
      {
          if (value == 0)
              value += SPECIES_UNOWN;
          else
              value += (SPECIES_UNOWN_B - 1);
          return value;
      }
      else
      {
          if (species > NUM_SPECIES)
              species = INVALID_ICON_SPECIES;
          return GetIconSpecies(species, 0);
      }
}

/** void FreeAndDestroyMonIconSprite(struct Sprite *sprite) */
export function FreeAndDestroyMonIconSprite(sprite: any): any {
  FreeAndDestroyMonIconSprite_(sprite);
}

/** void LoadMonIconPalettes(void) */
export function LoadMonIconPalettes(): any {
  let i: any = null;
      for (i = 0; i < ARRAY_COUNT(gMonIconPaletteTable); i++)
          LoadSpritePalette(gMonIconPaletteTable[i]);
}

/** void SafeLoadMonIconPalette(u16 species) */
export function SafeLoadMonIconPalette(species: any): any {
  let palIndex: any = null;
      if (species > NUM_SPECIES)
          species = INVALID_ICON_SPECIES;
      palIndex = gMonIconPaletteIndices[species];
      if (IndexOfSpritePaletteTag(gMonIconPaletteTable[palIndex].tag) == 0xFF)
          LoadSpritePalette(gMonIconPaletteTable[palIndex]);
}

/** void LoadMonIconPalette(u16 species) */
export function LoadMonIconPalette(species: any): any {
  let palIndex: any = gMonIconPaletteIndices[species];
      if (IndexOfSpritePaletteTag(gMonIconPaletteTable[palIndex].tag) == 0xFF)
          LoadSpritePalette(gMonIconPaletteTable[palIndex]);
}

/** void FreeMonIconPalettes(void) */
export function FreeMonIconPalettes(): any {
  let i: any = null;
      for (i = 0; i < ARRAY_COUNT(gMonIconPaletteTable); i++)
          FreeSpritePaletteByTag(gMonIconPaletteTable[i].tag);
}

/** void SafeFreeMonIconPalette(u16 species) */
export function SafeFreeMonIconPalette(species: any): any {
  let palIndex: any = null;
      if (species > NUM_SPECIES)
          species = INVALID_ICON_SPECIES;
      palIndex = gMonIconPaletteIndices[species];
      FreeSpritePaletteByTag(gMonIconPaletteTable[palIndex].tag);
}

/** void FreeMonIconPalette(u16 species) */
export function FreeMonIconPalette(species: any): any {
  let palIndex: any = null;
      palIndex = gMonIconPaletteIndices[species];
      FreeSpritePaletteByTag(gMonIconPaletteTable[palIndex].tag);
}

/** void SpriteCB_MonIcon(struct Sprite *sprite) */
export function SpriteCB_MonIcon(sprite: any): any {
  UpdateMonIconFrame(sprite);
}

/** void TryLoadAllMonIconPalettesAtOffset(u16 offset) */
export function TryLoadAllMonIconPalettesAtOffset(offset: any): any {
  let i: any = null;
       
      let monIconPalettePtr: any = null;

      if (offset <= BG_PLTT_ID(16 - ARRAY_COUNT(gMonIconPaletteTable)))
      {
          monIconPalettePtr = gMonIconPaletteTable;
          for(i = ARRAY_COUNT(gMonIconPaletteTable) - 1; i >= 0; i--)
          {
              LoadPalette(monIconPalettePtr.data, offset, 0x20);
              offset += 0x10;
              monIconPalettePtr++;
          }
      }
}

/** u8 GetValidMonIconPalIndex(u16 species) */
export function GetValidMonIconPalIndex(species: any): any {
  if (species > NUM_SPECIES)
          species = INVALID_ICON_SPECIES;
      return gMonIconPaletteIndices[species];
}

/** u8 GetMonIconPaletteIndexFromSpecies(u16 species) */
export function GetMonIconPaletteIndexFromSpecies(species: any): any {
  return gMonIconPaletteIndices[species];
}

/** u8 UpdateMonIconFrame(struct Sprite *sprite) */
export function UpdateMonIconFrame(sprite: any): any {
  let result: any = 0;

      if (sprite.animDelayCounter == 0)
      {
          let frame: any = sprite.anims[sprite.animNum][sprite.animCmdIndex].frame.imageValue;

          switch (frame)
          {
          case -1:
              break;
          case -2:
              sprite.animCmdIndex = 0;
              break;
          default:
              RequestSpriteCopy(
                   
                   
                   
                  sprite.images + (sSpriteImageSizes[sprite.oam.shape][sprite.oam.size] * frame),
                  (OBJ_VRAM0 + sprite.oam.tileNum * TILE_SIZE_4BPP),
                  sSpriteImageSizes[sprite.oam.shape][sprite.oam.size]);
              sprite.animDelayCounter = sprite.anims[sprite.animNum][sprite.animCmdIndex].frame.duration & 0xFF;
              sprite.animCmdIndex++;
              result = sprite.animCmdIndex;
              break;
          }
      }
      else
      {
          sprite.animDelayCounter--;
      }
      return result;
}

/** static u8 CreateMonIconSprite(struct MonIconSpriteTemplate *iconTemplate, s16 x, s16 y, u8 subpriority) */
export function CreateMonIconSprite(iconTemplate: any, x: any, y: any, subpriority: any): any {
  let spriteId: any = null;

      let image: any = [ NULL, sSpriteImageSizes[iconTemplate.oam.shape][iconTemplate.oam.size] ];

      let spriteTemplate: any =
      [ TAG_NONE, iconTemplate.paletteTag, iconTemplate.oam, iconTemplate.anims, image, iconTemplate.affineAnims, iconTemplate.callback,
      ];

      spriteId = CreateSprite(spriteTemplate, x, y, subpriority);
      gSprites[spriteId].animPaused = TRUE;
      gSprites[spriteId].animBeginning = FALSE;
      gSprites[spriteId].images = iconTemplate.image;
      return spriteId;
}

/** static void FreeAndDestroyMonIconSprite_(struct Sprite *sprite) */
export function FreeAndDestroyMonIconSprite_(sprite: any): any {
  let image: any = [ NULL, sSpriteImageSizes[sprite.oam.shape][sprite.oam.size] ];
      sprite.images =image;
      DestroySprite(sprite);
}

/** void SetPartyHPBarSprite(struct Sprite *sprite, u8 animNum) */
export function SetPartyHPBarSprite(sprite: any, animNum: any): any {
  sprite.animNum = animNum;
      sprite.animDelayCounter = 0;
      sprite.animCmdIndex = 0;
}

// ─── callsTo manifest (= 18 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["ARRAY_COUNT","BG_PLTT_ID","CreateMonIconSprite","CreateSprite","DestroySprite","FreeAndDestroyMonIconSprite_","FreeSpritePaletteByTag","GET_UNOWN_LETTER","GetIconSpecies","GetMonIconPtr","GetMonIconTiles","GetUnownLetterByPersonality","IndexOfSpritePaletteTag","LoadPalette","LoadSpritePalette","MailSpeciesToSpecies","RequestSpriteCopy","UpdateMonIconFrame"];
