// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/pokenav.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 26 functions extracted from src/pokenav.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck

// ─── BRIDGE IMPORT (auto-injected by inject-bridge-imports.mjs) ───
// Pull tous les callees ce module fait depuis le bridge unifié.
// Si un helper est bridgé : binding actif. Sinon : undefined → throw au call.
import * as _bridge from '../../../decomp-bridge';
const {
  Alloc, AnimateSprites, AnyMonHasRibbon, BuildOamBuffer,
  CheckBoxMonSanityAt, CreateTask, DestroyTask, FREE_AND_SET_NULL,
  FadeScreen, FreeAllSpritePalettes, FreeMenuHandlerSubstruct1, FreePokenavResources,
  FreePokenavSubstruct, GetBoxMonDataAt, GetCurrentMenuCB, GetMonData,
  GetWordTaskArg, InitKeys, InitKeys_, InitPokenavMainMenu,
  InitPokenavResources, IsActiveMenuLoopTaskActive, IsActiveMenuLoopTaskActive_, IsOverworldLinkActive,
  LOOPED_TASK_DECODE_STATE, LOOPED_TASK_ID, LOOPED_TASK_PRIMARY_ID, LOOPED_TASK_SECONDARY_ID,
  LoadOam, Overworld_IsRecvQueueAtMax, PokenavMainMenuLoopedTaskIsActive, ProcessSpriteCopyRequests,
  ResetSpriteData, ResetTasks, RunMainMenuLoopedTask, RunTasks,
  SetActiveMenuLoopTasks, SetActivePokenavMenu, SetMainCallback2, SetVBlankCallback,
  SetWordTaskArg, ShutdownPokenav, TRY_FREE_AND_SET_NULL, TransferPlttBuffer,
  UpdatePaletteFade, WaitForPokenavShutdownFade,  // 4-per-line for readability
} = _bridge;
// ─── END BRIDGE IMPORT ───
/** u32 CreateLoopedTask(LoopedTask loopedTask, u32 priority) */
export function CreateLoopedTask(loopedTask: any, priority: any): any {
  let taskId: any = null;

      if (!IsOverworldLinkActive())
          taskId = CreateTask(Task_RunLoopedTask, priority);
      else
          taskId = CreateTask(Task_RunLoopedTask_LinkMode, priority);

      SetWordTaskArg(taskId, 1, loopedTask);

      gTasks[taskId].data[3] = gNextLoopedTaskId;
      return LOOPED_TASK_ID(taskId, gNextLoopedTaskId++);
}

/** bool32 IsLoopedTaskActive(u32 taskId) */
export function IsLoopedTaskActive(taskId: any): any {
  let primaryId: any = LOOPED_TASK_PRIMARY_ID(taskId);
      let secondaryId: any = LOOPED_TASK_SECONDARY_ID(taskId);

      if (gTasks[primaryId].isActive
          && (gTasks[primaryId].func == Task_RunLoopedTask || gTasks[primaryId].func == Task_RunLoopedTask_LinkMode)
          && gTasks[primaryId].data[3] == secondaryId)
          return TRUE;
      else
          return FALSE;
}

/** bool32 FuncIsActiveLoopedTask(LoopedTask func) */
export function FuncIsActiveLoopedTask(func: any): any {
  let i: any = null;
      for (i = 0; i < NUM_TASKS; i++)
      {
          if (gTasks[i].isActive
              && (gTasks[i].func == Task_RunLoopedTask || gTasks[i].func == Task_RunLoopedTask_LinkMode)
              && GetWordTaskArg(i, 1) == func)
              return TRUE;
      }
      return FALSE;
}

/** static void Task_RunLoopedTask(u8 taskId) */
export function Task_RunLoopedTask(taskId: any): any {
  let loopedTask: any = GetWordTaskArg(taskId, 1);
      let state: any =gTasks[taskId].data[0];
      let exitLoop: any = FALSE;

      while (!exitLoop)
      {
          let action: any = loopedTask(state);
          switch (action)
          {
          case LT_INC_AND_CONTINUE:
              state++;
              break;
          case LT_INC_AND_PAUSE:
              state++;
              return;
          case LT_FINISH:
              DestroyTask(taskId);
              return;
           
          default:
              state = LOOPED_TASK_DECODE_STATE(action);
              break;
          case LT_CONTINUE:
              break;
          case LT_PAUSE:
              return;
          }
      }
}

/** static void Task_RunLoopedTask_LinkMode(u8 taskId) */
export function Task_RunLoopedTask_LinkMode(taskId: any): any {
  let task: any = null;
      let state: any = null;
      let action: any = null;

      if (Overworld_IsRecvQueueAtMax())
          return;

      task = GetWordTaskArg(taskId, 1);
      state =gTasks[taskId].data[0];
      action = task(state);
      switch (action)
      {
      case LT_INC_AND_PAUSE:
      case LT_INC_AND_CONTINUE:
          state++;
          break;
      case LT_FINISH:
          DestroyTask(taskId);
          break;
       
      default:
          state = LOOPED_TASK_DECODE_STATE(action);
          break;
      case LT_PAUSE:
      case LT_CONTINUE:
          break;
      }
}

/** void CB2_InitPokeNav(void) */
export function CB2_InitPokeNav(): any {
  gPokenavResources = Alloc(0);
      if (gPokenavResources == NULL)
      {
          SetMainCallback2(CB2_ReturnToFieldWithOpenMenu);
      }
      else
      {
          InitPokenavResources(gPokenavResources);
          ResetTasks();
          SetVBlankCallback(NULL);
          CreateTask(Task_Pokenav, 0);
          SetMainCallback2(CB2_Pokenav);
          SetVBlankCallback(VBlankCB_Pokenav);
      }
}

/** void OpenPokenavForTutorial(void) */
export function OpenPokenavForTutorial(): any {
  SetMainCallback2(CB2_InitPokenavForTutorial);
      FadeScreen(FADE_TO_BLACK, 0);
}

/** static void CB2_InitPokenavForTutorial(void) */
export function CB2_InitPokenavForTutorial(): any {
  UpdatePaletteFade();
      if (gPaletteFade.active)
          return;

      gPokenavResources = Alloc(0);
      if (gPokenavResources == NULL)
      {
          SetMainCallback2(CB2_ReturnToFieldContinueScriptPlayMapMusic);
      }
      else
      {
          InitPokenavResources(gPokenavResources);
          gPokenavResources.mode = POKENAV_MODE_FORCE_CALL_READY;
          ResetTasks();
          ResetSpriteData();
          FreeAllSpritePalettes();
          SetVBlankCallback(NULL);
          CreateTask(Task_Pokenav, 0);
          SetMainCallback2(CB2_Pokenav);
          SetVBlankCallback(VBlankCB_Pokenav);
      }
}

/** static void FreePokenavResources(void) */
export function FreePokenavResources(): any {
  let i: any = null;

      for (i = 0; i < POKENAV_SUBSTRUCT_COUNT; i++)
          FreePokenavSubstruct(i);

      FREE_AND_SET_NULL(gPokenavResources);
      InitKeys();
}

/** static void InitPokenavResources(struct PokenavResources *resources) */
export function InitPokenavResources(resources: any): any {
  let i: any = null;

      for (i = 0; i < POKENAV_SUBSTRUCT_COUNT; i++)
          resources.substructPtrs[i] = NULL;

      resources.mode = POKENAV_MODE_NORMAL;
      resources.currentMenuIndex = 0;
      resources.hasAnyRibbons = AnyMonHasRibbon();
      resources.currentMenuCb1 = NULL;
}

/** static bool32 AnyMonHasRibbon(void) */
export function AnyMonHasRibbon(): any {
  let i, j;

      for (i = 0; i < PARTY_SIZE; i++)
      {
          if (GetMonData(gPlayerParty[i],  MON_DATA_SANITY_HAS_SPECIES)
              && !GetMonData(gPlayerParty[i], MON_DATA_SANITY_IS_EGG)
              && GetMonData(gPlayerParty[i], MON_DATA_RIBBON_COUNT) != 0)
          {
              return TRUE;
          }
      }

      for (j = 0; j < TOTAL_BOXES_COUNT; j++)
      {
          for (i = 0; i < IN_BOX_COUNT; i++)
          {
              if (CheckBoxMonSanityAt(j, i)
                  && GetBoxMonDataAt(j, i, MON_DATA_RIBBON_COUNT) != 0)
              {
                  return TRUE;
              }
          }
      }

      return FALSE;
}

/** static void CB2_Pokenav(void) */
export function CB2_Pokenav(): any {
  RunTasks();
      AnimateSprites();
      BuildOamBuffer();
      UpdatePaletteFade();
}

/** static void VBlankCB_Pokenav(void) */
export function VBlankCB_Pokenav(): any {
  TransferPlttBuffer();
      LoadOam();
      ProcessSpriteCopyRequests();
}

/** static void Task_Pokenav(u8 taskId) */
export function Task_Pokenav(taskId: any): any {
  let menuId: any = null;
      let data: any = gTasks[taskId].data;

      switch (tState)
      {
      case 0:
          InitPokenavMainMenu();
          tState = 1;
          break;
      case 1:
           
          if (PokenavMainMenuLoopedTaskIsActive())
              break;
          SetActivePokenavMenu(POKENAV_MAIN_MENU);
          tState = 4;
          break;
      case 2:
          if (IsActiveMenuLoopTaskActive())
              break;
          tState = 3;
      case 3:
          menuId = GetCurrentMenuCB();
          if (menuId == POKENAV_MENU_FUNC_EXIT)
          {
              ShutdownPokenav();
              tState = 5;
          }
          else if (menuId >= POKENAV_MENU_IDS_START)
          {
              PokenavMenuCallbacks[gPokenavResources.currentMenuIndex].free2();
              PokenavMenuCallbacks[gPokenavResources.currentMenuIndex].free1();
              if (SetActivePokenavMenu(menuId))
              {
                  tState = 4;
              }
              else
              {
                  ShutdownPokenav();
                  tState = 5;
              }
          }
          else if (menuId != 0)
          {
              RunMainMenuLoopedTask(menuId);
              if (IsActiveMenuLoopTaskActive())
                  tState = 2;
          }
          break;
      case 4:
          if (!IsActiveMenuLoopTaskActive_())
              tState = 3;
          break;
      case 5:
          if (!WaitForPokenavShutdownFade())
          {
              let calledFromScript: any = (gPokenavResources.mode != POKENAV_MODE_NORMAL);

              FreeMenuHandlerSubstruct1();
              FreePokenavResources();
              if (calledFromScript)
                  SetMainCallback2(CB2_ReturnToFieldContinueScriptPlayMapMusic);
              else
                  SetMainCallback2(CB2_ReturnToFieldWithOpenMenu);
          }
          break;
      }
}

/** static bool32 SetActivePokenavMenu(u32 menuId) */
export function SetActivePokenavMenu(menuId: any): any {
  let index: any = menuId - POKENAV_MENU_IDS_START;

      InitKeys_();
      if (!PokenavMenuCallbacks[index].init())
          return FALSE;
      if (!PokenavMenuCallbacks[index].open())
          return FALSE;

      SetActiveMenuLoopTasks(PokenavMenuCallbacks[index].createLoopTask, PokenavMenuCallbacks[index].isLoopTaskActive);
      gPokenavResources.currentMenuCb1 = PokenavMenuCallbacks[index].callback;
      gPokenavResources.currentMenuIndex = index;
      return TRUE;
}

/** static u32 IsActiveMenuLoopTaskActive_(void) */
export function IsActiveMenuLoopTaskActive_(): any {
  return IsActiveMenuLoopTaskActive();
}

/** static u32 GetCurrentMenuCB(void) */
export function GetCurrentMenuCB(): any {
  return gPokenavResources.currentMenuCb1();
}

/** static void InitKeys_(void) */
export function InitKeys_(): any {
  InitKeys();
}

/** void SetVBlankCallback_(IntrCallback callback) */
export function SetVBlankCallback_(callback: any): any {
  SetVBlankCallback(callback);
}

/** void SetPokenavVBlankCallback(void) */
export function SetPokenavVBlankCallback(): any {
  SetVBlankCallback(VBlankCB_Pokenav);
}

/** void FreePokenavSubstruct(u32 index) */
export function FreePokenavSubstruct(index: any): any {
  TRY_FREE_AND_SET_NULL(gPokenavResources.substructPtrs[index]);
}

/** u32 GetPokenavMode(void) */
export function GetPokenavMode(): any {
  return gPokenavResources.mode;
}

/** void SetPokenavMode(u16 mode) */
export function SetPokenavMode(mode: any): any {
  gPokenavResources.mode = mode;
}

/** void SetSelectedConditionSearch(u32 cursorPos) */
export function SetSelectedConditionSearch(cursorPos: any): any {
  let searchId: any = cursorPos;

      if (searchId > POKENAV_MENUITEM_CONDITION_SEARCH_TOUGH - POKENAV_MENUITEM_CONDITION_SEARCH_COOL)
          searchId = 0;
      gPokenavResources.conditionSearchId = searchId;
}

/** u32 GetSelectedConditionSearch(void) */
export function GetSelectedConditionSearch(): any {
  return gPokenavResources.conditionSearchId;
}

/** bool32 CanViewRibbonsMenu(void) */
export function CanViewRibbonsMenu(): any {
  return gPokenavResources.hasAnyRibbons;
}

// ─── callsTo manifest (= 46 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["Alloc","AnimateSprites","AnyMonHasRibbon","BuildOamBuffer","CheckBoxMonSanityAt","CreateTask","DestroyTask","FREE_AND_SET_NULL","FadeScreen","FreeAllSpritePalettes","FreeMenuHandlerSubstruct1","FreePokenavResources","FreePokenavSubstruct","GetBoxMonDataAt","GetCurrentMenuCB","GetMonData","GetWordTaskArg","InitKeys","InitKeys_","InitPokenavMainMenu","InitPokenavResources","IsActiveMenuLoopTaskActive","IsActiveMenuLoopTaskActive_","IsOverworldLinkActive","LOOPED_TASK_DECODE_STATE","LOOPED_TASK_ID","LOOPED_TASK_PRIMARY_ID","LOOPED_TASK_SECONDARY_ID","LoadOam","Overworld_IsRecvQueueAtMax","PokenavMainMenuLoopedTaskIsActive","ProcessSpriteCopyRequests","ResetSpriteData","ResetTasks","RunMainMenuLoopedTask","RunTasks","SetActiveMenuLoopTasks","SetActivePokenavMenu","SetMainCallback2","SetVBlankCallback","SetWordTaskArg","ShutdownPokenav","TRY_FREE_AND_SET_NULL","TransferPlttBuffer","UpdatePaletteFade","WaitForPokenavShutdownFade"];
