// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/recorded_battle.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 40 functions extracted from src/recorded_battle.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck


// ─── AUTO-INJECTED file-scope vars (= EWRAM/IWRAM static C decls) ──
let gBattleOutcome: any = null;
let gPartnerTrainerId: any = null;
let gRecordedBattleMultiplayerId: any = null;
let gRecordedBattleRngSeed: any = null;
let gTrainerBattleOpponent_A: any = null;
let gTrainerBattleOpponent_B: any = null;
let sAI_Scripts: any = null;
let sApprenticeId: any = null;
let sApprenticeLanguage: any = null;
let sBattleFlags: any = null;
let sBattleOutcome: any = null;
let sBattleScene: any = null;
let sCallback2_AfterRecordedBattle: any = null;
let sFrontierBrainSymbol: any = null;
let sFrontierFacility: any = null;
let sFrontierPassFlag: any = null;
let sIsPlaybackFinished: any = null;
let sLvlMode: any = null;
let sRecordMixFriendClass: any = null;
let sRecordMixFriendLanguage: any = null;
let sRecordMode: any = null;
let sTextSpeed: any = null;
let savSection: any = null;
/** void RecordedBattle_Init(u8 mode) */
export function RecordedBattle_Init(mode: any): any {
  let i, j;

      sRecordMode = mode;
      sIsPlaybackFinished = FALSE;

      for (i = 0; i < MAX_BATTLERS_COUNT; i++)
      {
          sBattlerRecordSizes[i] = 0;
          sBattlerPrevRecordSizes[i] = 0;
          sBattlerSavedRecordSizes[i] = 0;

          if (mode == (1))
          {
              for (j = 0; j < (664); j++)
                  sBattleRecords[i][j] = 0xFF;
              sBattleFlags = gBattleTypeFlags;
              sAI_Scripts = gBattleResources.ai.aiFlags;
          }
      }
}

/** void RecordedBattle_SetTrainerInfo(void) */
export function RecordedBattle_SetTrainerInfo(): any {
  let i, j;

      if (sRecordMode == (1))
      {
          gRecordedBattleRngSeed = gRngValue;
          sFrontierFacility = VarGet((0x40CF));
          sFrontierBrainSymbol = GetFronterBrainSymbol();
      }
      else if (sRecordMode == (2))
      {
          gRngValue = gRecordedBattleRngSeed;
      }

      if (gBattleTypeFlags & ((1 << 1)))
      {
           
          let linkPlayersCount: any = null;
          let text: any = [];

          gRecordedBattleMultiplayerId = GetMultiplayerId();
          linkPlayersCount = GetLinkPlayerCount();

          for (i = 0; i < (4); i++)
          {
              sPlayers[i].trainerId = gLinkPlayers[i].trainerId;
              sPlayers[i].gender = gLinkPlayers[i].gender;
              sPlayers[i].battler = gLinkPlayers[i].id;
              sPlayers[i].language = gLinkPlayers[i].language;

               
              if (i < linkPlayersCount)
              {
                  StringCopy(text, gLinkPlayers[i].name);
                  StripExtCtrlCodes(text);
                  StringCopy(sPlayers[i].name, text);
              }
              else
              {
                  for (j = 0; j < (7) + 1; j++)
                      sPlayers[i].name[j] = gLinkPlayers[i].name[j];
              }
          }
      }
      else
      {
           
          sPlayers[0].trainerId = (gSaveBlock2Ptr.playerTrainerId[0])
                                | (gSaveBlock2Ptr.playerTrainerId[1] << 8)
                                | (gSaveBlock2Ptr.playerTrainerId[2] << 16)
                                | (gSaveBlock2Ptr.playerTrainerId[3] << 24);

          sPlayers[0].gender = gSaveBlock2Ptr.playerGender;
          sPlayers[0].battler = 0;
          sPlayers[0].language = gGameLanguage;

          for (i = 0; i < (7) + 1; i++)
              sPlayers[0].name[i] = gSaveBlock2Ptr.playerName[i];
      }
}

/** void RecordedBattle_SetBattlerAction(u8 battler, u8 action) */
export function RecordedBattle_SetBattlerAction(battler: any, action: any): any {
  if (sBattlerRecordSizes[battler] < (664) && sRecordMode != (2))
          sBattleRecords[battler][sBattlerRecordSizes[battler]++] = action;
}

/** void RecordedBattle_ClearBattlerAction(u8 battler, u8 bytesToClear) */
export function RecordedBattle_ClearBattlerAction(battler: any, bytesToClear: any): any {
  let i: any = null;

      for (i = 0; i < bytesToClear; i++)
      {
          sBattlerRecordSizes[battler]--;
          sBattleRecords[battler][sBattlerRecordSizes[battler]] = 0xFF;
          if (sBattlerRecordSizes[battler] == 0)
              break;
      }
}

/** u8 RecordedBattle_GetBattlerAction(u8 battler) */
export function RecordedBattle_GetBattlerAction(battler: any): any {
  if (sBattlerRecordSizes[battler] >= (664) || sBattleRecords[battler][sBattlerRecordSizes[battler]] == 0xFF)
      {
          gSpecialVar_Result = gBattleOutcome = (5);  
          ResetPaletteFadeControl();
          BeginNormalPaletteFade((((0x0000FFFF) | (0xFFFF0000))), 0, 0, 16, (RGB(0, 0, 0)));
          SetMainCallback2(CB2_QuitRecordedBattle);
          return (0xFF);
      }
      else
      {
          return sBattleRecords[battler][sBattlerRecordSizes[battler]++];
      }
}

/** u8 RecordedBattle_BufferNewBattlerData(u8 *dst) */
export function RecordedBattle_BufferNewBattlerData(dst: any): any {
  let i, j;
      let idx: any = 0;

      for (i = 0; i < MAX_BATTLERS_COUNT; i++)
      {
          if (sBattlerRecordSizes[i] != sBattlerPrevRecordSizes[i])
          {
              dst[idx++] = i;
              dst[idx++] = sBattlerRecordSizes[i] - sBattlerPrevRecordSizes[i];

              for (j = 0; j < sBattlerRecordSizes[i] - sBattlerPrevRecordSizes[i]; j++)
                  dst[idx++] = sBattleRecords[i][sBattlerPrevRecordSizes[i] + j];

              sBattlerPrevRecordSizes[i] = sBattlerRecordSizes[i];
          }
      }

      return idx;
}

/** void RecordedBattle_RecordAllBattlerData(u8 *src) */
export function RecordedBattle_RecordAllBattlerData(src: any): any {
  let i: any = null;
      let idx: any = 2;
      let size: any = null;

      if (!(gBattleTypeFlags & ((1 << 1))))
          return;

      for (i = 0; i < GetLinkPlayerCount(); i++)
      {
          if ((gLinkPlayers[i].version & 0xFF) != (3))
              return;
      }

      if (!(gBattleTypeFlags & ((1 << 2))))
      {
          for (size = src; size != 0;)
          {
              let battler: any = GetNextRecordedDataByte(src,idx,size);
              let numActions: any = GetNextRecordedDataByte(src,idx,size);

              for (i = 0; i < numActions; i++)
                  sBattleRecords[battler][sBattlerSavedRecordSizes[battler]++] = GetNextRecordedDataByte(src,idx,size);
          }
      }
}

/** static u8 GetNextRecordedDataByte(u8 *data, u8 *idx, u8 *size) */
export function GetNextRecordedDataByte(data: any, idx: any, size: any): any {
  size--;
      return data[idx++];
}

/** bool32 CanCopyRecordedBattleSaveData(void) */
export function CanCopyRecordedBattleSaveData(): any {
  let dst: any = AllocZeroed(0);
      let ret: any = CopyRecordedBattleFromSave(dst);
      Free(dst);
      return ret;
}

/** static bool32 IsRecordedBattleSaveValid(struct RecordedBattleSave *save) */
export function IsRecordedBattleSaveValid(save: any): any {
  if (save.battleFlags == 0)
          return FALSE;
      if (save.battleFlags & BATTLE_TYPE_RECORDED_INVALID)
          return FALSE;
      if (CalcByteArraySum((save), 0 - 4) != save.checksum)
          return FALSE;

      return TRUE;
}

/** static bool32 RecordedBattleToSave(struct RecordedBattleSave *battleSave, struct RecordedBattleSave *saveSector) */
export function RecordedBattleToSave(battleSave: any, saveSector: any): any {
  memset(saveSector, 0, (((3968) + (128))));
      memcpy(saveSector, battleSave, 0);

      saveSector.checksum = CalcByteArraySum((saveSector), 0 - 4);

      if (TryWriteSpecialSaveSector((31), (saveSector)) != (1))
          return FALSE;
      else
          return TRUE;
}

/** bool32 MoveRecordedBattleToSaveData(void) */
export function MoveRecordedBattleToSaveData(): any {
  let i, j;
      let ret: any = null;
      let battleSave, savSection;
      let saveAttempts: any = null;

      saveAttempts = 0;
      battleSave = AllocZeroed(0);
      savSection = AllocZeroed((((3968) + (128))));

      for (i = 0; i < (6); i++)
      {
          battleSave.playerParty[i] = sSavedPlayerParty[i];
          battleSave.opponentParty[i] = sSavedOpponentParty[i];
      }

      for (i = 0; i < (4); i++)
      {
          for (j = 0; j < (7) + 1; j++)
              battleSave.playersName[i][j] = sPlayers[i].name[j];
          battleSave.playersGender[i] = sPlayers[i].gender;
          battleSave.playersLanguage[i] = sPlayers[i].language;
          battleSave.playersBattlers[i] = sPlayers[i].battler;
          battleSave.playersTrainerId[i] = sPlayers[i].trainerId;
      }

      battleSave.rngSeed = gRecordedBattleRngSeed;

      if (sBattleFlags & ((1 << 1)))
      {
          battleSave.battleFlags = (sBattleFlags & ~(((1 << 1)) | ((1 << 5)))) | ((1 << 25));

           
           
           
          if (sBattleFlags & ((1 << 2)))
          {
              battleSave.battleFlags |= ((1 << 31));
          }
          else if (sBattleFlags & ((1 << 6)))
          {
              switch (sPlayers[0].battler)
              {
              case 0:
              case 2:
                  if (!(sPlayers[gRecordedBattleMultiplayerId].battler & 1))
                      battleSave.battleFlags |= ((1 << 31));
                  break;
              case 1:
              case 3:
                  if ((sPlayers[gRecordedBattleMultiplayerId].battler & 1))
                      battleSave.battleFlags |= ((1 << 31));
                  break;
              }
          }
      }
      else
      {
          battleSave.battleFlags = sBattleFlags;
      }

      battleSave.opponentA = gTrainerBattleOpponent_A;
      battleSave.opponentB = gTrainerBattleOpponent_B;
      battleSave.partnerId = gPartnerTrainerId;
      battleSave.multiplayerId = gRecordedBattleMultiplayerId;
      battleSave.lvlMode = gSaveBlock2Ptr.frontier.lvlMode;
      battleSave.frontierFacility = sFrontierFacility;
      battleSave.frontierBrainSymbol = sFrontierBrainSymbol;
      battleSave.battleScene = gSaveBlock2Ptr.optionsBattleSceneOff;
      battleSave.textSpeed = gSaveBlock2Ptr.optionsTextSpeed;
      battleSave.AI_scripts = sAI_Scripts;

      if (gTrainerBattleOpponent_A >= ((300)) && gTrainerBattleOpponent_A < (400))
      {
          for (i = 0; i < (7) + 1; i++)
              battleSave.recordMixFriendName[i] = gSaveBlock2Ptr.frontier.towerRecords[gTrainerBattleOpponent_A - ((300))].name[i];
          battleSave.recordMixFriendClass = gSaveBlock2Ptr.frontier.towerRecords[gTrainerBattleOpponent_A - ((300))].facilityClass;

          if (sBattleOutcome == (1))
          {
              for (i = 0; i < (6); i++)
                  battleSave.easyChatSpeech[i] = gSaveBlock2Ptr.frontier.towerRecords[gTrainerBattleOpponent_A - ((300))].speechLost[i];
          }
          else
          {
              for (i = 0; i < (6); i++)
                  battleSave.easyChatSpeech[i] = gSaveBlock2Ptr.frontier.towerRecords[gTrainerBattleOpponent_A - ((300))].speechWon[i];
          }
          battleSave.recordMixFriendLanguage = gSaveBlock2Ptr.frontier.towerRecords[gTrainerBattleOpponent_A - ((300))].language;
      }
      else if (gTrainerBattleOpponent_B >= ((300)) && gTrainerBattleOpponent_B < (400))
      {
          for (i = 0; i < (7) + 1; i++)
              battleSave.recordMixFriendName[i] = gSaveBlock2Ptr.frontier.towerRecords[gTrainerBattleOpponent_B - ((300))].name[i];
          battleSave.recordMixFriendClass = gSaveBlock2Ptr.frontier.towerRecords[gTrainerBattleOpponent_B - ((300))].facilityClass;

          if (sBattleOutcome == (1))
          {
              for (i = 0; i < (6); i++)
                  battleSave.easyChatSpeech[i] = gSaveBlock2Ptr.frontier.towerRecords[gTrainerBattleOpponent_B - ((300))].speechLost[i];
          }
          else
          {
              for (i = 0; i < (6); i++)
                  battleSave.easyChatSpeech[i] = gSaveBlock2Ptr.frontier.towerRecords[gTrainerBattleOpponent_B - ((300))].speechWon[i];
          }
          battleSave.recordMixFriendLanguage = gSaveBlock2Ptr.frontier.towerRecords[gTrainerBattleOpponent_B - ((300))].language;
      }
      else if (gPartnerTrainerId >= ((300)) && gPartnerTrainerId < (400))
      {
          for (i = 0; i < (7) + 1; i++)
              battleSave.recordMixFriendName[i] = gSaveBlock2Ptr.frontier.towerRecords[gPartnerTrainerId - ((300))].name[i];
          battleSave.recordMixFriendClass = gSaveBlock2Ptr.frontier.towerRecords[gPartnerTrainerId - ((300))].facilityClass;

          battleSave.recordMixFriendLanguage = gSaveBlock2Ptr.frontier.towerRecords[gPartnerTrainerId - ((300))].language;
      }

      if (gTrainerBattleOpponent_A >= (400))
      {
          battleSave.apprenticeId = gSaveBlock2Ptr.apprentices[gTrainerBattleOpponent_A - (400)].id;
          for (i = 0; i < (6); i++)
              battleSave.easyChatSpeech[i] = gSaveBlock2Ptr.apprentices[gTrainerBattleOpponent_A - (400)].speechWon[i];
          battleSave.apprenticeLanguage = gSaveBlock2Ptr.apprentices[gTrainerBattleOpponent_A - (400)].language;
      }
      else if (gTrainerBattleOpponent_B >= (400))
      {
          battleSave.apprenticeId = gSaveBlock2Ptr.apprentices[gTrainerBattleOpponent_B - (400)].id;
          for (i = 0; i < (6); i++)
              battleSave.easyChatSpeech[i] = gSaveBlock2Ptr.apprentices[gTrainerBattleOpponent_B - (400)].speechWon[i];
          battleSave.apprenticeLanguage = gSaveBlock2Ptr.apprentices[gTrainerBattleOpponent_B - (400)].language;
      }
      else if (gPartnerTrainerId >= (400))
      {
          battleSave.apprenticeId = gSaveBlock2Ptr.apprentices[gPartnerTrainerId - (400)].id;

          battleSave.apprenticeLanguage = gSaveBlock2Ptr.apprentices[gPartnerTrainerId - (400)].language;
      }

      for (i = 0; i < MAX_BATTLERS_COUNT; i++)
          for (j = 0; j < (664); j++)
              battleSave.battleRecord[i][j] = sBattleRecords[i][j];

      while (1)
      {
          ret = RecordedBattleToSave(battleSave, savSection);
          if (ret == TRUE)
              break;
          saveAttempts++;
          if (saveAttempts >= 3)
              break;
      }

      Free(battleSave);
      Free(savSection);
      return ret;
}

/** static bool32 TryCopyRecordedBattleSaveData(struct RecordedBattleSave *dst, struct SaveSector *saveBuffer) */
export function TryCopyRecordedBattleSaveData(dst: any, saveBuffer: any): any {
  if (TryReadSpecialSaveSector((31), (saveBuffer)) != (1))
          return FALSE;

      memcpy(dst, saveBuffer, 0);

      if (!IsRecordedBattleSaveValid(dst))
          return FALSE;

      return TRUE;
}

/** static bool32 CopyRecordedBattleFromSave(struct RecordedBattleSave *dst) */
export function CopyRecordedBattleFromSave(dst: any): any {
  let savBuffer: any = AllocZeroed((((3968) + (128))));
      let ret: any = TryCopyRecordedBattleSaveData(dst, savBuffer);
      Free(savBuffer);

      return ret;
}

/** static void CB2_RecordedBattleEnd(void) */
export function CB2_RecordedBattleEnd(): any {
  gSaveBlock2Ptr.frontier.lvlMode = sLvlMode;
      gBattleOutcome = 0;
      gBattleTypeFlags = 0;
      gTrainerBattleOpponent_A = 0;
      gTrainerBattleOpponent_B = 0;
      gPartnerTrainerId = 0;

      RecordedBattle_RestoreSavedParties();
      SetMainCallback2(sCallback2_AfterRecordedBattle);
}

/** static void Task_StartAfterCountdown(u8 taskId) */
export function Task_StartAfterCountdown(taskId: any): any {
  if (--gTasks[taskId].tFramesToWait == 0)
      {
          gMain.savedCallback = CB2_RecordedBattleEnd;
          SetMainCallback2(CB2_InitBattle);
          DestroyTask(taskId);
      }
}

/** static void SetVariablesForRecordedBattle(struct RecordedBattleSave *src) */
export function SetVariablesForRecordedBattle(src: any): any {
  let _var: any = null;
      let i, j;

      ZeroPlayerPartyMons();
      ZeroEnemyPartyMons();

      for (i = 0; i < (6); i++)
      {
          gPlayerParty[i] = src.playerParty[i];
          gEnemyParty[i] = src.opponentParty[i];
      }

      for (i = 0; i < (4); i++)
      {
          for (_var = FALSE, j = 0; j < (7) + 1; j++)
          {
              gLinkPlayers[i].name[j] = src.playersName[i][j];
              if (src.playersName[i][j] == (0xFF))
                  _var = TRUE;
          }
          gLinkPlayers[i].gender = src.playersGender[i];
          gLinkPlayers[i].language = src.playersLanguage[i];
          gLinkPlayers[i].id = src.playersBattlers[i];
          gLinkPlayers[i].trainerId = src.playersTrainerId[i];

          if (_var)
              ConvertInternationalString(gLinkPlayers[i].name, gLinkPlayers[i].language);
      }

      gRecordedBattleRngSeed = src.rngSeed;
      gBattleTypeFlags = src.battleFlags | ((1 << 24));
      gTrainerBattleOpponent_A = src.opponentA;
      gTrainerBattleOpponent_B = src.opponentB;
      gPartnerTrainerId = src.partnerId;
      gRecordedBattleMultiplayerId = src.multiplayerId;
      sLvlMode = gSaveBlock2Ptr.frontier.lvlMode;
      sFrontierFacility = src.frontierFacility;
      sFrontierBrainSymbol = src.frontierBrainSymbol;
      sBattleScene = src.battleScene;
      sTextSpeed = src.textSpeed;
      sAI_Scripts = src.AI_scripts;

      for (i = 0; i < (7) + 1; i++)
          sRecordMixFriendName[i] = src.recordMixFriendName[i];

      sRecordMixFriendClass = src.recordMixFriendClass;
      sApprenticeId = src.apprenticeId;
      sRecordMixFriendLanguage = src.recordMixFriendLanguage;
      sApprenticeLanguage = src.apprenticeLanguage;

      for (i = 0; i < (6); i++)
          sEasyChatSpeech[i] = src.easyChatSpeech[i];

      gSaveBlock2Ptr.frontier.lvlMode = src.lvlMode;

      for (i = 0; i < MAX_BATTLERS_COUNT; i++)
          for (j = 0; j < (664); j++)
              sBattleRecords[i][j] = src.battleRecord[i][j];
}

/** void PlayRecordedBattle(void (*CB2_After)(void)) */
export function PlayRecordedBattle(CB2_After: any): any {
  let battleSave: any = AllocZeroed(0);
      if (CopyRecordedBattleFromSave(battleSave) == TRUE)
      {
          let taskId: any = null;

          RecordedBattle_SaveParties();
          SetVariablesForRecordedBattle(battleSave);

          taskId = CreateTask(Task_StartAfterCountdown, 1);
          gTasks[taskId].tFramesToWait = 128;

          sCallback2_AfterRecordedBattle = CB2_After;
          PlayMapChosenOrBattleBGM(FALSE);
          SetMainCallback2(CB2_RecordedBattle);
      }
      Free(battleSave);
}

/** static void CB2_RecordedBattle(void) */
export function CB2_RecordedBattle(): any {
  AnimateSprites();
      BuildOamBuffer();
      RunTasks();
}

/** u8 GetRecordedBattleFrontierFacility(void) */
export function GetRecordedBattleFrontierFacility(): any {
  return sFrontierFacility;
}

/** u8 GetRecordedBattleFronterBrainSymbol(void) */
export function GetRecordedBattleFronterBrainSymbol(): any {
  return sFrontierBrainSymbol;
}

/** void RecordedBattle_SaveParties(void) */
export function RecordedBattle_SaveParties(): any {
  let i: any = null;

      for (i = 0; i < (6); i++)
      {
          sSavedPlayerParty[i] = gPlayerParty[i];
          sSavedOpponentParty[i] = gEnemyParty[i];
      }
}

/** static void RecordedBattle_RestoreSavedParties(void) */
export function RecordedBattle_RestoreSavedParties(): any {
  let i: any = null;

      for (i = 0; i < (6); i++)
      {
          gPlayerParty[i] = sSavedPlayerParty[i];
          gEnemyParty[i] = sSavedOpponentParty[i];
      }
}

/** u8 GetActiveBattlerLinkPlayerGender(void) */
export function GetActiveBattlerLinkPlayerGender(): any {
  let i: any = null;

      for (i = 0; i < (4); i++)
      {
          if (gLinkPlayers[i].id == gActiveBattler)
              break;
      }

      if (i != (4))
          return gLinkPlayers[i].gender;

      return 0;
}

/** void RecordedBattle_ClearFrontierPassFlag(void) */
export function RecordedBattle_ClearFrontierPassFlag(): any {
  sFrontierPassFlag = 0;
}

/** void RecordedBattle_SetFrontierPassFlagFromHword(u16 flags) */
export function RecordedBattle_SetFrontierPassFlagFromHword(flags: any): any {
  sFrontierPassFlag |= (flags & (1 << 15)) >> 15;
}

/** u8 RecordedBattle_GetFrontierPassFlag(void) */
export function RecordedBattle_GetFrontierPassFlag(): any {
  return sFrontierPassFlag;
}

/** u8 GetBattleSceneInRecordedBattle(void) */
export function GetBattleSceneInRecordedBattle(): any {
  return sBattleScene;
}

/** u8 GetTextSpeedInRecordedBattle(void) */
export function GetTextSpeedInRecordedBattle(): any {
  return sTextSpeed;
}

/** void RecordedBattle_CopyBattlerMoves(void) */
export function RecordedBattle_CopyBattlerMoves(): any {
  let i: any = null;

      if (GetBattlerSide(gActiveBattler) == (1))
          return;
      if (gBattleTypeFlags & (((1 << 1)) | ((1 << 25))))
          return;
      if (sRecordMode == (2))
          return;

      for (i = 0; i < (4); i++)
          sPlayerMonMoves[gActiveBattler / 2][i] = gBattleMons[gActiveBattler].moves[i];
}

/** void RecordedBattle_CheckMovesetChanges(u8 mode) */
export function RecordedBattle_CheckMovesetChanges(mode: any): any {
  let battler, j, k;

      if (gBattleTypeFlags & (((1 << 1)) | ((1 << 25))))
          return;

      for (battler = 0; battler < gBattlersCount; battler++)
      {
           
          if (GetBattlerSide(battler) != (1))
          {
              if (mode == (1))
              {
                   
                  for (j = 0; j < (4); j++)
                  {
                      if (gBattleMons[battler].moves[j] != sPlayerMonMoves[battler / 2][j])
                          break;
                  }
                  if (j != (4))
                  {
                       
                      RecordedBattle_SetBattlerAction(battler, (6));
                      for (j = 0; j < (4); j++)
                      {
                          for (k = 0; k < (4); k++)
                          {
                              if (gBattleMons[battler].moves[j] == sPlayerMonMoves[battler / 2][k])
                              {
                                  RecordedBattle_SetBattlerAction(battler, k);
                                  break;
                              }
                          }
                      }
                  }
              }
              else  
              {
                  if (sBattleRecords[battler][sBattlerRecordSizes[battler]] == (6))
                  {
                      let ppBonuses: any = [];
                      let moveSlots: any = [];
                      let mimickedMoveSlots: any = [];
                      let movePp: any = null;
                      let ppBonusSet: any = null;

                       
                       
                      RecordedBattle_GetBattlerAction(battler);

                      for (j = 0; j < (4); j++)
                          ppBonuses[j] = ((gBattleMons[battler].ppBonuses & (3 << (j << 1))) >> (j << 1));

                      for (j = 0; j < (4); j++)
                      {
                          moveSlots[j] = RecordedBattle_GetBattlerAction(battler);
                          movePp.moves[j] = gBattleMons[battler].moves[moveSlots[j]];
                          movePp.currentPp[j] = gBattleMons[battler].pp[moveSlots[j]];
                          movePp.maxPp[j] = ppBonuses[moveSlots[j]];
                          mimickedMoveSlots[j] = (gDisableStructs[battler].mimickedMoves & gBitTable[j]) >> j;
                      }
                      for (j = 0; j < (4); j++)
                      {
                          gBattleMons[battler].moves[j] = movePp.moves[j];
                          gBattleMons[battler].pp[j] = movePp.currentPp[j];
                      }
                      gBattleMons[battler].ppBonuses = 0;
                      gDisableStructs[battler].mimickedMoves = 0;
                      for (j = 0; j < (4); j++)
                      {
                          gBattleMons[battler].ppBonuses |= movePp.maxPp[j] << (j << 1);
                          gDisableStructs[battler].mimickedMoves |= mimickedMoveSlots[j] << j;
                      }

                      if (!(gBattleMons[battler].status2 & ((1 << 21))))
                      {
                          for (j = 0; j < (4); j++)
                              ppBonuses[j] = (GetMonData(gPlayerParty[gBattlerPartyIndexes[battler]], MON_DATA_PP_BONUSES, NULL) & ((3 << (j << 1)))) >> (j << 1);

                          for (j = 0; j < (4); j++)
                          {
                              movePp.moves[j] = GetMonData(gPlayerParty[gBattlerPartyIndexes[battler]], MON_DATA_MOVE1 + moveSlots[j], NULL);
                              movePp.currentPp[j] = GetMonData(gPlayerParty[gBattlerPartyIndexes[battler]], MON_DATA_PP1 + moveSlots[j], NULL);
                              movePp.maxPp[j] = ppBonuses[moveSlots[j]];
                          }
                          for (j = 0; j < (4); j++)
                          {
                              SetMonData(gPlayerParty[gBattlerPartyIndexes[battler]], MON_DATA_MOVE1 + j,movePp.moves[j]);
                              SetMonData(gPlayerParty[gBattlerPartyIndexes[battler]], MON_DATA_PP1 + j,movePp.currentPp[j]);
                          }
                          ppBonusSet = 0;
                          for (j = 0; j < (4); j++)
                              ppBonusSet |= movePp.maxPp[j] << (j << 1);

                          SetMonData(gPlayerParty[gBattlerPartyIndexes[battler]], MON_DATA_PP_BONUSES,ppBonusSet);
                      }
                      gChosenMoveByBattler[battler] = gBattleMons[battler].moves[(gBattleStruct.chosenMovePositions + battler)];
                  }
              }
          }
      }
}

/** u32 GetAiScriptsInRecordedBattle(void) */
export function GetAiScriptsInRecordedBattle(): any {
  return sAI_Scripts;
}

/** void RecordedBattle_SetPlaybackFinished(void) */
export function RecordedBattle_SetPlaybackFinished(): any {
  sIsPlaybackFinished = TRUE;
}

/** bool8 RecordedBattle_CanStopPlayback(void) */
export function RecordedBattle_CanStopPlayback(): any {
  return (sIsPlaybackFinished == FALSE);
}

/** void GetRecordedBattleRecordMixFriendName(u8 *dst) */
export function GetRecordedBattleRecordMixFriendName(dst: any): any {
  let i: any = null;

      for (i = 0; i < (7) + 1; i++)
          dst[i] = sRecordMixFriendName[i];
      dst[(7)] = (0xFF);
      ConvertInternationalString(dst, sRecordMixFriendLanguage);
}

/** u8 GetRecordedBattleRecordMixFriendClass(void) */
export function GetRecordedBattleRecordMixFriendClass(): any {
  return sRecordMixFriendClass;
}

/** u8 GetRecordedBattleApprenticeId(void) */
export function GetRecordedBattleApprenticeId(): any {
  return sApprenticeId;
}

/** u8 GetRecordedBattleRecordMixFriendLanguage(void) */
export function GetRecordedBattleRecordMixFriendLanguage(): any {
  return sRecordMixFriendLanguage;
}

/** u8 GetRecordedBattleApprenticeLanguage(void) */
export function GetRecordedBattleApprenticeLanguage(): any {
  return sApprenticeLanguage;
}

/** void RecordedBattle_SaveBattleOutcome(void) */
export function RecordedBattle_SaveBattleOutcome(): any {
  sBattleOutcome = gBattleOutcome;
}

// ─── callsTo manifest (= 36 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["AllocZeroed","AnimateSprites","BeginNormalPaletteFade","BuildOamBuffer","CalcByteArraySum","ConvertInternationalString","CopyRecordedBattleFromSave","CreateTask","DestroyTask","Free","GetBattlerSide","GetFronterBrainSymbol","GetLinkPlayerCount","GetMonData","GetMultiplayerId","GetNextRecordedDataByte","IsRecordedBattleSaveValid","PlayMapChosenOrBattleBGM","RecordedBattleToSave","RecordedBattle_GetBattlerAction","RecordedBattle_RestoreSavedParties","RecordedBattle_SaveParties","RecordedBattle_SetBattlerAction","ResetPaletteFadeControl","RunTasks","SetMainCallback2","SetMonData","SetVariablesForRecordedBattle","StringCopy","StripExtCtrlCodes","TryCopyRecordedBattleSaveData","TryReadSpecialSaveSector","TryWriteSpecialSaveSector","VarGet","ZeroEnemyPartyMons","ZeroPlayerPartyMons"];
