// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/tileset_anims.c
// Generated : 2026-05-09
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 84 functions extracted from src/tileset_anims.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck

// ─── BRIDGE IMPORT (auto-injected by inject-bridge-imports.mjs) ───
// Pull tous les callees ce module fait depuis le bridge unifié.
// Si un helper est bridgé : binding actif. Sinon : undefined → throw au call.
// Names already defined in this file via 'export function' are EXCLUDED
// to avoid "already declared" esbuild errors.
import * as _bridge from '../../../decomp-bridge';
const {
  ARRAY_COUNT, BG_PLTT_ID, BlendPalette, CpuCopy16,
  CpuFill32, DmaCopy16, FindTaskIdByFunc, NULL,
  PLTT_SIZE_4BPP, TASK_NONE, TILE_OFFSET_4BPP, TILE_SIZE_4BPP,  // 4-per-line for readability
} = _bridge;
// ─── END BRIDGE IMPORT ───
/** static void ResetTilesetAnimBuffer(void) */
export function ResetTilesetAnimBuffer(): any {
  sTilesetDMA3TransferBufferSize = 0;
      CpuFill32(0, sTilesetDMA3TransferBuffer, 0);
}

/** static void AppendTilesetAnimToBuffer(const u16 *src, u16 *dest, u16 size) */
export function AppendTilesetAnimToBuffer(src: any, dest: any, size: any): any {
  if (sTilesetDMA3TransferBufferSize < 20)
      {
          sTilesetDMA3TransferBuffer[sTilesetDMA3TransferBufferSize].src = src;
          sTilesetDMA3TransferBuffer[sTilesetDMA3TransferBufferSize].dest = dest;
          sTilesetDMA3TransferBuffer[sTilesetDMA3TransferBufferSize].size = size;
          sTilesetDMA3TransferBufferSize ++;
      }
}

/** void TransferTilesetAnimsBuffer(void) */
export function TransferTilesetAnimsBuffer(): any {
  let i: any = null;

      for (i = 0; i < sTilesetDMA3TransferBufferSize; i ++)
          DmaCopy16(3, sTilesetDMA3TransferBuffer[i].src, sTilesetDMA3TransferBuffer[i].dest, sTilesetDMA3TransferBuffer[i].size);

      sTilesetDMA3TransferBufferSize = 0;
}

/** void InitTilesetAnimations(void) */
export function InitTilesetAnimations(): any {
  ResetTilesetAnimBuffer();
      _InitPrimaryTilesetAnimation();
      _InitSecondaryTilesetAnimation();
}

/** void InitSecondaryTilesetAnimation(void) */
export function InitSecondaryTilesetAnimation(): any {
  _InitSecondaryTilesetAnimation();
}

/** void UpdateTilesetAnimations(void) */
export function UpdateTilesetAnimations(): any {
  ResetTilesetAnimBuffer();
      if (++sPrimaryTilesetAnimCounter >= sPrimaryTilesetAnimCounterMax)
          sPrimaryTilesetAnimCounter = 0;
      if (++sSecondaryTilesetAnimCounter >= sSecondaryTilesetAnimCounterMax)
          sSecondaryTilesetAnimCounter = 0;

      if (sPrimaryTilesetAnimCallback)
          sPrimaryTilesetAnimCallback(sPrimaryTilesetAnimCounter);
      if (sSecondaryTilesetAnimCallback)
          sSecondaryTilesetAnimCallback(sSecondaryTilesetAnimCounter);
}

/** static void _InitPrimaryTilesetAnimation(void) */
export function _InitPrimaryTilesetAnimation(): any {
  sPrimaryTilesetAnimCounter = 0;
      sPrimaryTilesetAnimCounterMax = 0;
      sPrimaryTilesetAnimCallback = NULL;
      if (gMapHeader.mapLayout.primaryTileset && gMapHeader.mapLayout.primaryTileset.callback)
          gMapHeader.mapLayout.primaryTileset.callback();
}

/** static void _InitSecondaryTilesetAnimation(void) */
export function _InitSecondaryTilesetAnimation(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = 0;
      sSecondaryTilesetAnimCallback = NULL;
      if (gMapHeader.mapLayout.secondaryTileset && gMapHeader.mapLayout.secondaryTileset.callback)
          gMapHeader.mapLayout.secondaryTileset.callback();
}

/** void InitTilesetAnim_General(void) */
export function InitTilesetAnim_General(): any {
  sPrimaryTilesetAnimCounter = 0;
      sPrimaryTilesetAnimCounterMax = 256;
      sPrimaryTilesetAnimCallback = TilesetAnim_General;
}

/** void InitTilesetAnim_Building(void) */
export function InitTilesetAnim_Building(): any {
  sPrimaryTilesetAnimCounter = 0;
      sPrimaryTilesetAnimCounterMax = 256;
      sPrimaryTilesetAnimCallback = TilesetAnim_Building;
}

/** static void TilesetAnim_General(u16 timer) */
export function TilesetAnim_General(timer: any): any {
  if (timer % 16 == 0)
          QueueAnimTiles_General_Flower(timer / 16);
      if (timer % 16 == 1)
          QueueAnimTiles_General_Water(timer / 16);
      if (timer % 16 == 2)
          QueueAnimTiles_General_SandWaterEdge(timer / 16);
      if (timer % 16 == 3)
          QueueAnimTiles_General_Waterfall(timer / 16);
      if (timer % 16 == 4)
          QueueAnimTiles_General_LandWaterEdge(timer / 16);
}

/** static void TilesetAnim_Building(u16 timer) */
export function TilesetAnim_Building(timer: any): any {
  if (timer % 8 == 0)
          QueueAnimTiles_Building_TVTurnedOn(timer / 8);
}

/** static void QueueAnimTiles_General_Flower(u16 timer) */
export function QueueAnimTiles_General_Flower(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_General_Flower);
      AppendTilesetAnimToBuffer(gTilesetAnims_General_Flower[i], (BG_VRAM + TILE_OFFSET_4BPP(508)), 4 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_General_Water(u16 timer) */
export function QueueAnimTiles_General_Water(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_General_Water);
      AppendTilesetAnimToBuffer(gTilesetAnims_General_Water[i], (BG_VRAM + TILE_OFFSET_4BPP(432)), 30 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_General_SandWaterEdge(u16 timer) */
export function QueueAnimTiles_General_SandWaterEdge(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_General_SandWaterEdge);
      AppendTilesetAnimToBuffer(gTilesetAnims_General_SandWaterEdge[i], (BG_VRAM + TILE_OFFSET_4BPP(464)), 10 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_General_Waterfall(u16 timer) */
export function QueueAnimTiles_General_Waterfall(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_General_Waterfall);
      AppendTilesetAnimToBuffer(gTilesetAnims_General_Waterfall[i], (BG_VRAM + TILE_OFFSET_4BPP(496)), 6 * TILE_SIZE_4BPP);
}

/** void InitTilesetAnim_Petalburg(void) */
export function InitTilesetAnim_Petalburg(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = NULL;
}

/** void InitTilesetAnim_Rustboro(void) */
export function InitTilesetAnim_Rustboro(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_Rustboro;
}

/** void InitTilesetAnim_Dewford(void) */
export function InitTilesetAnim_Dewford(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_Dewford;
}

/** void InitTilesetAnim_Slateport(void) */
export function InitTilesetAnim_Slateport(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_Slateport;
}

/** void InitTilesetAnim_Mauville(void) */
export function InitTilesetAnim_Mauville(): any {
  sSecondaryTilesetAnimCounter = sPrimaryTilesetAnimCounter;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_Mauville;
}

/** void InitTilesetAnim_Lavaridge(void) */
export function InitTilesetAnim_Lavaridge(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_Lavaridge;
}

/** void InitTilesetAnim_Fallarbor(void) */
export function InitTilesetAnim_Fallarbor(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = NULL;
}

/** void InitTilesetAnim_Fortree(void) */
export function InitTilesetAnim_Fortree(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = NULL;
}

/** void InitTilesetAnim_Lilycove(void) */
export function InitTilesetAnim_Lilycove(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = NULL;
}

/** void InitTilesetAnim_Mossdeep(void) */
export function InitTilesetAnim_Mossdeep(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = NULL;
}

/** void InitTilesetAnim_EverGrande(void) */
export function InitTilesetAnim_EverGrande(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_EverGrande;
}

/** void InitTilesetAnim_Pacifidlog(void) */
export function InitTilesetAnim_Pacifidlog(): any {
  sSecondaryTilesetAnimCounter = sPrimaryTilesetAnimCounter;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_Pacifidlog;
}

/** void InitTilesetAnim_Sootopolis(void) */
export function InitTilesetAnim_Sootopolis(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_Sootopolis;
}

/** void InitTilesetAnim_BattleFrontierOutsideWest(void) */
export function InitTilesetAnim_BattleFrontierOutsideWest(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_BattleFrontierOutsideWest;
}

/** void InitTilesetAnim_BattleFrontierOutsideEast(void) */
export function InitTilesetAnim_BattleFrontierOutsideEast(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_BattleFrontierOutsideEast;
}

/** void InitTilesetAnim_Underwater(void) */
export function InitTilesetAnim_Underwater(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = 128;
      sSecondaryTilesetAnimCallback = TilesetAnim_Underwater;
}

/** void InitTilesetAnim_SootopolisGym(void) */
export function InitTilesetAnim_SootopolisGym(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = 240;
      sSecondaryTilesetAnimCallback = TilesetAnim_SootopolisGym;
}

/** void InitTilesetAnim_Cave(void) */
export function InitTilesetAnim_Cave(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_Cave;
}

/** void InitTilesetAnim_EliteFour(void) */
export function InitTilesetAnim_EliteFour(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = 128;
      sSecondaryTilesetAnimCallback = TilesetAnim_EliteFour;
}

/** void InitTilesetAnim_MauvilleGym(void) */
export function InitTilesetAnim_MauvilleGym(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_MauvilleGym;
}

/** void InitTilesetAnim_BikeShop(void) */
export function InitTilesetAnim_BikeShop(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_BikeShop;
}

/** void InitTilesetAnim_BattlePyramid(void) */
export function InitTilesetAnim_BattlePyramid(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_BattlePyramid;
}

/** void InitTilesetAnim_BattleDome(void) */
export function InitTilesetAnim_BattleDome(): any {
  sSecondaryTilesetAnimCounter = 0;
      sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
      sSecondaryTilesetAnimCallback = TilesetAnim_BattleDome;
}

/** static void TilesetAnim_Rustboro(u16 timer) */
export function TilesetAnim_Rustboro(timer: any): any {
  if (timer % 8 == 0)
      {
          QueueAnimTiles_Rustboro_WindyWater(timer / 8, 0);
          QueueAnimTiles_Rustboro_Fountain(timer / 8);
      }
      if (timer % 8 == 1)
          QueueAnimTiles_Rustboro_WindyWater(timer / 8, 1);
      if (timer % 8 == 2)
          QueueAnimTiles_Rustboro_WindyWater(timer / 8, 2);
      if (timer % 8 == 3)
          QueueAnimTiles_Rustboro_WindyWater(timer / 8, 3);
      if (timer % 8 == 4)
          QueueAnimTiles_Rustboro_WindyWater(timer / 8, 4);
      if (timer % 8 == 5)
          QueueAnimTiles_Rustboro_WindyWater(timer / 8, 5);
      if (timer % 8 == 6)
          QueueAnimTiles_Rustboro_WindyWater(timer / 8, 6);
      if (timer % 8 == 7)
          QueueAnimTiles_Rustboro_WindyWater(timer / 8, 7);
}

/** static void TilesetAnim_Dewford(u16 timer) */
export function TilesetAnim_Dewford(timer: any): any {
  if (timer % 8 == 0)
          QueueAnimTiles_Dewford_Flag(timer / 8);
}

/** static void TilesetAnim_Slateport(u16 timer) */
export function TilesetAnim_Slateport(timer: any): any {
  if (timer % 16 == 0)
          QueueAnimTiles_Slateport_Balloons(timer / 16);
}

/** static void TilesetAnim_Mauville(u16 timer) */
export function TilesetAnim_Mauville(timer: any): any {
  if (timer % 8 == 0)
          QueueAnimTiles_Mauville_Flowers(timer / 8, 0);
      if (timer % 8 == 1)
          QueueAnimTiles_Mauville_Flowers(timer / 8, 1);
      if (timer % 8 == 2)
          QueueAnimTiles_Mauville_Flowers(timer / 8, 2);
      if (timer % 8 == 3)
          QueueAnimTiles_Mauville_Flowers(timer / 8, 3);
      if (timer % 8 == 4)
          QueueAnimTiles_Mauville_Flowers(timer / 8, 4);
      if (timer % 8 == 5)
          QueueAnimTiles_Mauville_Flowers(timer / 8, 5);
      if (timer % 8 == 6)
          QueueAnimTiles_Mauville_Flowers(timer / 8, 6);
      if (timer % 8 == 7)
          QueueAnimTiles_Mauville_Flowers(timer / 8, 7);
}

/** static void TilesetAnim_Lavaridge(u16 timer) */
export function TilesetAnim_Lavaridge(timer: any): any {
  if (timer % 16 == 0)
          QueueAnimTiles_Lavaridge_Steam(timer / 16);
      if (timer % 16 == 1)
          QueueAnimTiles_Lavaridge_Lava(timer / 16);
}

/** static void TilesetAnim_EverGrande(u16 timer) */
export function TilesetAnim_EverGrande(timer: any): any {
  if (timer % 8 == 0)
          QueueAnimTiles_EverGrande_Flowers(timer / 8, 0);
      if (timer % 8 == 1)
          QueueAnimTiles_EverGrande_Flowers(timer / 8, 1);
      if (timer % 8 == 2)
          QueueAnimTiles_EverGrande_Flowers(timer / 8, 2);
      if (timer % 8 == 3)
          QueueAnimTiles_EverGrande_Flowers(timer / 8, 3);
      if (timer % 8 == 4)
          QueueAnimTiles_EverGrande_Flowers(timer / 8, 4);
      if (timer % 8 == 5)
          QueueAnimTiles_EverGrande_Flowers(timer / 8, 5);
      if (timer % 8 == 6)
          QueueAnimTiles_EverGrande_Flowers(timer / 8, 6);
      if (timer % 8 == 7)
          QueueAnimTiles_EverGrande_Flowers(timer / 8, 7);
}

/** static void TilesetAnim_Pacifidlog(u16 timer) */
export function TilesetAnim_Pacifidlog(timer: any): any {
  if (timer % 16 == 0)
          QueueAnimTiles_Pacifidlog_LogBridges(timer / 16);
      if (timer % 16 == 1)
          QueueAnimTiles_Pacifidlog_WaterCurrents(timer / 16);
}

/** static void TilesetAnim_Sootopolis(u16 timer) */
export function TilesetAnim_Sootopolis(timer: any): any {
  if (timer % 16 == 0)
          QueueAnimTiles_Sootopolis_StormyWater(timer / 16);
}

/** static void TilesetAnim_Underwater(u16 timer) */
export function TilesetAnim_Underwater(timer: any): any {
  if (timer % 16 == 0)
          QueueAnimTiles_Underwater_Seaweed(timer / 16);
}

/** static void TilesetAnim_Cave(u16 timer) */
export function TilesetAnim_Cave(timer: any): any {
  if (timer % 16 == 1)
          QueueAnimTiles_Cave_Lava(timer / 16);
}

/** static void TilesetAnim_BattleFrontierOutsideWest(u16 timer) */
export function TilesetAnim_BattleFrontierOutsideWest(timer: any): any {
  if (timer % 8 == 0)
          QueueAnimTiles_BattleFrontierOutsideWest_Flag(timer / 8);
}

/** static void TilesetAnim_BattleFrontierOutsideEast(u16 timer) */
export function TilesetAnim_BattleFrontierOutsideEast(timer: any): any {
  if (timer % 8 == 0)
          QueueAnimTiles_BattleFrontierOutsideEast_Flag(timer / 8);
}

/** static void QueueAnimTiles_General_LandWaterEdge(u16 timer) */
export function QueueAnimTiles_General_LandWaterEdge(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_General_LandWaterEdge);
      AppendTilesetAnimToBuffer(gTilesetAnims_General_LandWaterEdge[i], (BG_VRAM + TILE_OFFSET_4BPP(480)), 10 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_Lavaridge_Steam(u8 timer) */
export function QueueAnimTiles_Lavaridge_Steam(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_Lavaridge_Steam);
      AppendTilesetAnimToBuffer(gTilesetAnims_Lavaridge_Steam[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 288)), 4 * TILE_SIZE_4BPP);

      i = (timer + 2) % ARRAY_COUNT(gTilesetAnims_Lavaridge_Steam);
      AppendTilesetAnimToBuffer(gTilesetAnims_Lavaridge_Steam[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 292)), 4 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_Pacifidlog_LogBridges(u8 timer) */
export function QueueAnimTiles_Pacifidlog_LogBridges(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_Pacifidlog_LogBridges);
      AppendTilesetAnimToBuffer(gTilesetAnims_Pacifidlog_LogBridges[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 464)), 30 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_Underwater_Seaweed(u8 timer) */
export function QueueAnimTiles_Underwater_Seaweed(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_Underwater_Seaweed);
      AppendTilesetAnimToBuffer(gTilesetAnims_Underwater_Seaweed[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 496)), 4 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_Pacifidlog_WaterCurrents(u8 timer) */
export function QueueAnimTiles_Pacifidlog_WaterCurrents(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_Pacifidlog_WaterCurrents);
      AppendTilesetAnimToBuffer(gTilesetAnims_Pacifidlog_WaterCurrents[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 496)), 8 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_Mauville_Flowers(u16 timer_div, u8 timer_mod) */
export function QueueAnimTiles_Mauville_Flowers(timer_div: any, timer_mod: any): any {
  timer_div -= timer_mod;
      if (timer_div < min(ARRAY_COUNT(gTilesetAnims_Mauville_Flower1), ARRAY_COUNT(gTilesetAnims_Mauville_Flower2)))
      {
          timer_div %= min(ARRAY_COUNT(gTilesetAnims_Mauville_Flower1), ARRAY_COUNT(gTilesetAnims_Mauville_Flower2));
          AppendTilesetAnimToBuffer(gTilesetAnims_Mauville_Flower1[timer_div], gTilesetAnims_Mauville_Flower1_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
          AppendTilesetAnimToBuffer(gTilesetAnims_Mauville_Flower2[timer_div], gTilesetAnims_Mauville_Flower2_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
      }
      else
      {
          timer_div %= min(ARRAY_COUNT(gTilesetAnims_Mauville_Flower1_B), ARRAY_COUNT(gTilesetAnims_Mauville_Flower2_B));
          AppendTilesetAnimToBuffer(gTilesetAnims_Mauville_Flower1_B[timer_div], gTilesetAnims_Mauville_Flower1_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
          AppendTilesetAnimToBuffer(gTilesetAnims_Mauville_Flower2_B[timer_div], gTilesetAnims_Mauville_Flower2_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
      }
}

/** static void QueueAnimTiles_Rustboro_WindyWater(u16 timer_div, u8 timer_mod) */
export function QueueAnimTiles_Rustboro_WindyWater(timer_div: any, timer_mod: any): any {
  timer_div -= timer_mod;
      timer_div %= ARRAY_COUNT(gTilesetAnims_Rustboro_WindyWater);
      if (gTilesetAnims_Rustboro_WindyWater[timer_div])
          AppendTilesetAnimToBuffer(gTilesetAnims_Rustboro_WindyWater[timer_div], gTilesetAnims_Rustboro_WindyWater_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_Rustboro_Fountain(u16 timer) */
export function QueueAnimTiles_Rustboro_Fountain(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_Rustboro_Fountain);
      AppendTilesetAnimToBuffer(gTilesetAnims_Rustboro_Fountain[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 448)), 4 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_Lavaridge_Lava(u16 timer) */
export function QueueAnimTiles_Lavaridge_Lava(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_Lavaridge_Cave_Lava);
      AppendTilesetAnimToBuffer(gTilesetAnims_Lavaridge_Cave_Lava[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 160)), 4 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_EverGrande_Flowers(u16 timer_div, u8 timer_mod) */
export function QueueAnimTiles_EverGrande_Flowers(timer_div: any, timer_mod: any): any {
  timer_div -= timer_mod;
      timer_div %= ARRAY_COUNT(gTilesetAnims_EverGrande_Flowers);

      AppendTilesetAnimToBuffer(gTilesetAnims_EverGrande_Flowers[timer_div], gTilesetAnims_EverGrande_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_Cave_Lava(u16 timer) */
export function QueueAnimTiles_Cave_Lava(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_Lavaridge_Cave_Lava);
      AppendTilesetAnimToBuffer(gTilesetAnims_Lavaridge_Cave_Lava[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 416)), 4 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_Dewford_Flag(u16 timer) */
export function QueueAnimTiles_Dewford_Flag(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_Dewford_Flag);
      AppendTilesetAnimToBuffer(gTilesetAnims_Dewford_Flag[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 170)), 6 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_BattleFrontierOutsideWest_Flag(u16 timer) */
export function QueueAnimTiles_BattleFrontierOutsideWest_Flag(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_BattleFrontierOutsideWest_Flag);
      AppendTilesetAnimToBuffer(gTilesetAnims_BattleFrontierOutsideWest_Flag[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 218)), 6 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_BattleFrontierOutsideEast_Flag(u16 timer) */
export function QueueAnimTiles_BattleFrontierOutsideEast_Flag(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_BattleFrontierOutsideEast_Flag);
      AppendTilesetAnimToBuffer(gTilesetAnims_BattleFrontierOutsideEast_Flag[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 218)), 6 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_Slateport_Balloons(u16 timer) */
export function QueueAnimTiles_Slateport_Balloons(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_Slateport_Balloons);
      AppendTilesetAnimToBuffer(gTilesetAnims_Slateport_Balloons[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 224)), 4 * TILE_SIZE_4BPP);
}

/** static void TilesetAnim_MauvilleGym(u16 timer) */
export function TilesetAnim_MauvilleGym(timer: any): any {
  if (timer % 2 == 0)
          QueueAnimTiles_MauvilleGym_ElectricGates(timer / 2);
}

/** static void TilesetAnim_SootopolisGym(u16 timer) */
export function TilesetAnim_SootopolisGym(timer: any): any {
  if (timer % 8 == 0)
          QueueAnimTiles_SootopolisGym_Waterfalls(timer / 8);
}

/** static void TilesetAnim_EliteFour(u16 timer) */
export function TilesetAnim_EliteFour(timer: any): any {
  if (timer % 64 == 1)
          QueueAnimTiles_EliteFour_GroundLights(timer / 64);
      if (timer % 8 == 1)
          QueueAnimTiles_EliteFour_WallLights(timer / 8);
}

/** static void TilesetAnim_BikeShop(u16 timer) */
export function TilesetAnim_BikeShop(timer: any): any {
  if (timer % 4 == 0)
          QueueAnimTiles_BikeShop_BlinkingLights(timer / 4);
}

/** static void TilesetAnim_BattlePyramid(u16 timer) */
export function TilesetAnim_BattlePyramid(timer: any): any {
  if (timer % 8 == 0)
      {
          QueueAnimTiles_BattlePyramid_Torch(timer / 8);
          QueueAnimTiles_BattlePyramid_StatueShadow(timer / 8);
      }
}

/** static void TilesetAnim_BattleDome(u16 timer) */
export function TilesetAnim_BattleDome(timer: any): any {
  if (timer % 4 == 0)
          BlendAnimPalette_BattleDome_FloorLights(timer / 4);
}

/** static void TilesetAnim_BattleDome2(u16 timer) */
export function TilesetAnim_BattleDome2(timer: any): any {
  if (timer % 4 == 0)
          BlendAnimPalette_BattleDome_FloorLightsNoBlend(timer / 4);
}

/** static void QueueAnimTiles_Building_TVTurnedOn(u16 timer) */
export function QueueAnimTiles_Building_TVTurnedOn(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_Building_TvTurnedOn);
      AppendTilesetAnimToBuffer(gTilesetAnims_Building_TvTurnedOn[i], (BG_VRAM + TILE_OFFSET_4BPP(496)), 4 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_SootopolisGym_Waterfalls(u16 timer) */
export function QueueAnimTiles_SootopolisGym_Waterfalls(timer: any): any {
  let i: any = timer % min(ARRAY_COUNT(gTilesetAnims_SootopolisGym_SideWaterfall), ARRAY_COUNT(gTilesetAnims_SootopolisGym_FrontWaterfall));
      AppendTilesetAnimToBuffer(gTilesetAnims_SootopolisGym_SideWaterfall[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 496)), 12 * TILE_SIZE_4BPP);
      AppendTilesetAnimToBuffer(gTilesetAnims_SootopolisGym_FrontWaterfall[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 464)), 20 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_EliteFour_WallLights(u16 timer) */
export function QueueAnimTiles_EliteFour_WallLights(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_EliteFour_WallLights);
      AppendTilesetAnimToBuffer(gTilesetAnims_EliteFour_WallLights[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 504)), 1 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_EliteFour_GroundLights(u16 timer) */
export function QueueAnimTiles_EliteFour_GroundLights(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_EliteFour_FloorLight);
      AppendTilesetAnimToBuffer(gTilesetAnims_EliteFour_FloorLight[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 480)), 4 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_MauvilleGym_ElectricGates(u16 timer) */
export function QueueAnimTiles_MauvilleGym_ElectricGates(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_MauvilleGym_ElectricGates);
      AppendTilesetAnimToBuffer(gTilesetAnims_MauvilleGym_ElectricGates[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 144)), 16 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_BikeShop_BlinkingLights(u16 timer) */
export function QueueAnimTiles_BikeShop_BlinkingLights(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_BikeShop_BlinkingLights);
      AppendTilesetAnimToBuffer(gTilesetAnims_BikeShop_BlinkingLights[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 496)), 9 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_Sootopolis_StormyWater(u16 timer) */
export function QueueAnimTiles_Sootopolis_StormyWater(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_Sootopolis_StormyWater);
      AppendTilesetAnimToBuffer(gTilesetAnims_Sootopolis_StormyWater[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 240)), 96 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_BattlePyramid_Torch(u16 timer) */
export function QueueAnimTiles_BattlePyramid_Torch(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_BattlePyramid_Torch);
      AppendTilesetAnimToBuffer(gTilesetAnims_BattlePyramid_Torch[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 151)), 8 * TILE_SIZE_4BPP);
}

/** static void QueueAnimTiles_BattlePyramid_StatueShadow(u16 timer) */
export function QueueAnimTiles_BattlePyramid_StatueShadow(timer: any): any {
  let i: any = timer % ARRAY_COUNT(gTilesetAnims_BattlePyramid_StatueShadow);
      AppendTilesetAnimToBuffer(gTilesetAnims_BattlePyramid_StatueShadow[i], (BG_VRAM + TILE_OFFSET_4BPP(NUM_TILES_IN_PRIMARY + 135)), 8 * TILE_SIZE_4BPP);
}

/** static void BlendAnimPalette_BattleDome_FloorLights(u16 timer) */
export function BlendAnimPalette_BattleDome_FloorLights(timer: any): any {
  CpuCopy16(sTilesetAnims_BattleDomeFloorLightPals[timer % ARRAY_COUNT(sTilesetAnims_BattleDomeFloorLightPals)],gPlttBufferUnfaded[BG_PLTT_ID(8)], PLTT_SIZE_4BPP);
      BlendPalette(BG_PLTT_ID(8), 16, gPaletteFade.y, gPaletteFade.blendColor & 0x7FFF);
      if (FindTaskIdByFunc(Task_BattleTransition_Intro) != TASK_NONE)
      {
          sSecondaryTilesetAnimCallback = TilesetAnim_BattleDome2;
          sSecondaryTilesetAnimCounterMax = 32;
      }
}

/** static void BlendAnimPalette_BattleDome_FloorLightsNoBlend(u16 timer) */
export function BlendAnimPalette_BattleDome_FloorLightsNoBlend(timer: any): any {
  CpuCopy16(sTilesetAnims_BattleDomeFloorLightPals[timer % ARRAY_COUNT(sTilesetAnims_BattleDomeFloorLightPals)],gPlttBufferUnfaded[BG_PLTT_ID(8)], PLTT_SIZE_4BPP);
      if (FindTaskIdByFunc(Task_BattleTransition_Intro) == TASK_NONE)
      {
          BlendPalette(BG_PLTT_ID(8), 16, gPaletteFade.y, gPaletteFade.blendColor & 0x7FFF);
          if (!--sSecondaryTilesetAnimCounterMax)
              sSecondaryTilesetAnimCallback = NULL;
      }
}

// ─── callsTo manifest (= 42 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["ARRAY_COUNT","AppendTilesetAnimToBuffer","BG_PLTT_ID","BlendAnimPalette_BattleDome_FloorLights","BlendAnimPalette_BattleDome_FloorLightsNoBlend","BlendPalette","CpuCopy16","CpuFill32","DmaCopy16","FindTaskIdByFunc","QueueAnimTiles_BattleFrontierOutsideEast_Flag","QueueAnimTiles_BattleFrontierOutsideWest_Flag","QueueAnimTiles_BattlePyramid_StatueShadow","QueueAnimTiles_BattlePyramid_Torch","QueueAnimTiles_BikeShop_BlinkingLights","QueueAnimTiles_Building_TVTurnedOn","QueueAnimTiles_Cave_Lava","QueueAnimTiles_Dewford_Flag","QueueAnimTiles_EliteFour_GroundLights","QueueAnimTiles_EliteFour_WallLights","QueueAnimTiles_EverGrande_Flowers","QueueAnimTiles_General_Flower","QueueAnimTiles_General_LandWaterEdge","QueueAnimTiles_General_SandWaterEdge","QueueAnimTiles_General_Water","QueueAnimTiles_General_Waterfall","QueueAnimTiles_Lavaridge_Lava","QueueAnimTiles_Lavaridge_Steam","QueueAnimTiles_MauvilleGym_ElectricGates","QueueAnimTiles_Mauville_Flowers","QueueAnimTiles_Pacifidlog_LogBridges","QueueAnimTiles_Pacifidlog_WaterCurrents","QueueAnimTiles_Rustboro_Fountain","QueueAnimTiles_Rustboro_WindyWater","QueueAnimTiles_Slateport_Balloons","QueueAnimTiles_SootopolisGym_Waterfalls","QueueAnimTiles_Sootopolis_StormyWater","QueueAnimTiles_Underwater_Seaweed","ResetTilesetAnimBuffer","TILE_OFFSET_4BPP","_InitPrimaryTilesetAnimation","_InitSecondaryTilesetAnimation"];
