// AUTO-GENERATED by scripts/transpile-decomp-all.mjs
// Source : src/union_room_player_avatar.c
// Generated : 2026-05-08
// DO NOT EDIT — re-run `node scripts/transpile-decomp-all.mjs` to refresh.
//
// Total : 38 functions extracted from src/union_room_player_avatar.c.
//
// IMPORTANT :
//   - Tous les imports manquants : marqués @ts-nocheck (= pas de typecheck).
//   - Les bodies référencent des helpers (= FaceDirection, InitMovementNormal, etc.)
//     qui doivent être bridged vers nos TS impls. Cf. memory/audit pour la liste.
//   - Pour activer une fonction, la importer depuis runtime engine + bridge
//     ses callsTo manquants.

/* eslint-disable */
// @ts-nocheck

/** static bool32 IsPlayerStandingStill(void) */
export function IsPlayerStandingStill(): any {
  if (gPlayerAvatar.tileTransitionState == T_TILE_CENTER || gPlayerAvatar.tileTransitionState == T_NOT_MOVING)
          return TRUE;
      else
          return FALSE;
}

/** static u8 GetUnionRoomPlayerGraphicsId(u32 gender, u32 id) */
export function GetUnionRoomPlayerGraphicsId(...args: any[]): any {
  return sUnionRoomObjGfxIds[gender][id % NUM_UNION_ROOM_CLASSES];
}

/** static void GetUnionRoomPlayerCoords(u32 leaderId, u32 memberId, s32 *x, s32 *y) */
export function GetUnionRoomPlayerCoords(...args: any[]): any {
  *x = sUnionRoomPlayerCoords[leaderId][0] + sUnionRoomGroupOffsets[memberId][0] + MAP_OFFSET;
      *y = sUnionRoomPlayerCoords[leaderId][1] + sUnionRoomGroupOffsets[memberId][1] + MAP_OFFSET;
}

/** static bool32 IsUnionRoomPlayerAt(u32 leaderId, u32 memberId, s32 x, s32 y) */
export function IsUnionRoomPlayerAt(...args: any[]): any {
  if ((sUnionRoomPlayerCoords[leaderId][0] + sUnionRoomGroupOffsets[memberId][0] + MAP_OFFSET == x)
      &&  (sUnionRoomPlayerCoords[leaderId][1] + sUnionRoomGroupOffsets[memberId][1] + MAP_OFFSET == y))
          return TRUE;
      else
          return FALSE;
}

/** static bool32 IsUnionRoomPlayerHidden(u32 player_idx) */
export function IsUnionRoomPlayerHidden(...args: any[]): any {
  return FlagGet(FLAG_HIDE_UNION_ROOM_PLAYER_1 + player_idx);
}

/** static void HideUnionRoomPlayer(u32 player_idx) */
export function HideUnionRoomPlayer(...args: any[]): any {
  FlagSet(FLAG_HIDE_UNION_ROOM_PLAYER_1 + player_idx);
}

/** static void ShowUnionRoomPlayer(u32 player_idx) */
export function ShowUnionRoomPlayer(...args: any[]): any {
  FlagClear(FLAG_HIDE_UNION_ROOM_PLAYER_1 + player_idx);
}

/** static void SetUnionRoomPlayerGfx(u32 leaderId, u32 gfxId) */
export function SetUnionRoomPlayerGfx(...args: any[]): any {
  VarSet(VAR_OBJ_GFX_ID_0 + leaderId, gfxId);
}

/** static void CreateUnionRoomPlayerObjectEvent(u32 leaderId) */
export function CreateUnionRoomPlayerObjectEvent(...args: any[]): any {
  TrySpawnObjectEvent(sUnionRoomLocalIds[leaderId], gSaveBlock1Ptr.location.mapNum, gSaveBlock1Ptr.location.mapGroup);
}

/** static void RemoveUnionRoomPlayerObjectEvent(u32 leaderId) */
export function RemoveUnionRoomPlayerObjectEvent(...args: any[]): any {
  RemoveObjectEventByLocalIdAndMap(sUnionRoomLocalIds[leaderId], gSaveBlock1Ptr.location.mapNum, gSaveBlock1Ptr.location.mapGroup);
}

/** static bool32 SetUnionRoomPlayerEnterExitMovement(u32 leaderId, const u8 *movement) */
export function SetUnionRoomPlayerEnterExitMovement(...args: any[]): any {
  let objectId: any = null;
      let object: any = null;
      if (TryGetObjectEventIdByLocalIdAndMap(sUnionRoomLocalIds[leaderId], gSaveBlock1Ptr.location.mapNum, gSaveBlock1Ptr.location.mapGroup, objectId))
          return FALSE;
      object = gObjectEvents[objectId];
      if (ObjectEventIsMovementOverridden(object))
          return FALSE;
      if (ObjectEventSetHeldMovement(object, *movement))
          return FALSE;
      return TRUE;
}

/** static bool32 TryReleaseUnionRoomPlayerObjectEvent(u32 leaderId) */
export function TryReleaseUnionRoomPlayerObjectEvent(...args: any[]): any {
  let objectId: any = null;
      let object: any = null;
      if (TryGetObjectEventIdByLocalIdAndMap(sUnionRoomLocalIds[leaderId], gSaveBlock1Ptr.location.mapNum, gSaveBlock1Ptr.location.mapGroup, objectId))
          return TRUE;

      object = gObjectEvents[objectId];
      if (!ObjectEventClearHeldMovementIfFinished(object))
          return FALSE;

      if (!ArePlayerFieldControlsLocked())
          UnfreezeObjectEvent(object);
      else
          FreezeObjectEvent(object);
      return TRUE;
}

/** u8 InitUnionRoomPlayerObjects(struct UnionRoomObject *players) */
export function InitUnionRoomPlayerObjects(...args: any[]): any {
  let i: any = null;

      sUnionObjRefreshTimer = 0;
      sUnionObjWork = players;
      for (i = 0; i < MAX_UNION_ROOM_LEADERS; i++)
      {
          players[i].state = 0;
          players[i].gfxId = 0;
          players[i].animState = 0;
          players[i].schedAnim = UNION_ROOM_SPAWN_NONE;
      }
      return CreateTask_AnimateUnionRoomPlayers();
}

/** static bool32 AnimateUnionRoomPlayerDespawn(s8 *state, u32 leaderId, struct UnionRoomObject *object) */
export function AnimateUnionRoomPlayerDespawn(...args: any[]): any {
  switch (*state)
      {
      case 0:
          if (SetUnionRoomPlayerEnterExitMovement(leaderId, sMovement_UnionPlayerExit) == TRUE)
          {
              HideUnionRoomPlayer(leaderId);
              (*state)++;
          }
          break;
      case 1:
          if (TryReleaseUnionRoomPlayerObjectEvent(leaderId))
          {
              RemoveUnionRoomPlayerObjectEvent(leaderId);
              HideUnionRoomPlayer(leaderId);
              *state = 0;
              return TRUE;
          }
          break;
      }
      return FALSE;
}

/** static bool32 AnimateUnionRoomPlayerSpawn(s8 *state, u32 leaderId, struct UnionRoomObject *object) */
export function AnimateUnionRoomPlayerSpawn(...args: any[]): any {
  let x, y;

      switch (*state)
      {
      case 0:
          if (!IsPlayerStandingStill())
              break;
          PlayerGetDestCoords(x, y);
          if (IsUnionRoomPlayerAt(leaderId, 0, x, y) == TRUE)
              break;
          player_get_pos_including_state_based_drift(x, y);
          if (IsUnionRoomPlayerAt(leaderId, 0, x, y) == TRUE)
              break;
          SetUnionRoomPlayerGfx(leaderId, object.gfxId);
          CreateUnionRoomPlayerObjectEvent(leaderId);
          ShowUnionRoomPlayer(leaderId);
          (*state)++;
           
      case 3:  
          if (SetUnionRoomPlayerEnterExitMovement(leaderId, sMovement_UnionPlayerEnter) == TRUE)
              (*state)++;
          break;
      case 2:
          if (TryReleaseUnionRoomPlayerObjectEvent(leaderId))
          {
              *state = 0;
              return TRUE;
          }
          break;
      }
      return FALSE;
}

/** static bool32 SpawnGroupLeader(u32 leaderId, u32 gender, u32 id) */
export function SpawnGroupLeader(...args: any[]): any {
  let object: any = sUnionObjWork[leaderId];
      object.schedAnim = UNION_ROOM_SPAWN_IN;
      object.gfxId = GetUnionRoomPlayerGraphicsId(gender, id);

      if (object.state == 0)
          return TRUE;
      else
          return FALSE;
}

/** static bool32 DespawnGroupLeader(u32 leaderId) */
export function DespawnGroupLeader(...args: any[]): any {
  let object: any = sUnionObjWork[leaderId];
      object.schedAnim = UNION_ROOM_SPAWN_OUT;

      if (object.state == 1)
          return TRUE;
      else
          return FALSE;
}

/** static void AnimateUnionRoomPlayer(u32 leaderId, struct UnionRoomObject *object) */
export function AnimateUnionRoomPlayer(...args: any[]): any {
  switch (object.state)
      {
      case 0:
          if (object.schedAnim == UNION_ROOM_SPAWN_IN)
          {
              object.state = 2;
              object.animState = 0;
          }
          else
          {
              break;
          }
           
      case 2:
          if (!IsUnionRoomPlayerInvisible(leaderId, 0) && object.schedAnim == UNION_ROOM_SPAWN_OUT)
          {
              object.state = 0;
              object.animState = 0;
              RemoveUnionRoomPlayerObjectEvent(leaderId);
              HideUnionRoomPlayer(leaderId);
          }
          else if (AnimateUnionRoomPlayerSpawn(object.animState, leaderId, object) == TRUE)
          {
              object.state = 1;
          }
          break;
      case 1:
           
          if (object.schedAnim == UNION_ROOM_SPAWN_OUT)
          {
              object.state = 3;
              object.animState = 0;
          }
          else
          {
              break;
          }
           
      case 3:
          if (AnimateUnionRoomPlayerDespawn(object.animState, leaderId, object) == 1)
              object.state = 0;
          break;
      }
      object.schedAnim = UNION_ROOM_SPAWN_NONE;
}

/** static void Task_AnimateUnionRoomPlayers(u8 taskId) */
export function Task_AnimateUnionRoomPlayers(...args: any[]): any {
  let i: any = null;
      for (i = 0; i < MAX_UNION_ROOM_LEADERS; i++)
          AnimateUnionRoomPlayer(i, sUnionObjWork[i]);
}

/** static u8 CreateTask_AnimateUnionRoomPlayers(void) */
export function CreateTask_AnimateUnionRoomPlayers(): any {
  if (FuncIsActiveTask(Task_AnimateUnionRoomPlayers) == TRUE)
          return NUM_TASKS;
      else
          return CreateTask(Task_AnimateUnionRoomPlayers, 5);
}

/** static void DestroyTask_AnimateUnionRoomPlayers(void) */
export function DestroyTask_AnimateUnionRoomPlayers(): any {
  let taskId = FindTaskIdByFunc(Task_AnimateUnionRoomPlayers);
      if (taskId < NUM_TASKS)
          DestroyTask(taskId);
}

/** void DestroyUnionRoomPlayerObjects(void) */
export function DestroyUnionRoomPlayerObjects(): any {
  let i: any = null;
      for (i = 0; i < MAX_UNION_ROOM_LEADERS; i++)
      {
          if (!IsUnionRoomPlayerHidden(i))
          {
              RemoveUnionRoomPlayerObjectEvent(i);
              HideUnionRoomPlayer(i);
          }
      }
      sUnionObjWork = NULL;
      DestroyTask_AnimateUnionRoomPlayers();
}

/** void CreateUnionRoomPlayerSprites(u8 *spriteIds, s32 leaderId) */
export function CreateUnionRoomPlayerSprites(...args: any[]): any {
  let memberId: any = null;
      for (memberId = 0; memberId < MAX_RFU_PLAYERS; memberId++)
      {
          let id = UR_PLAYER_SPRITE_ID(leaderId, memberId);
          spriteIds[id] = CreateVirtualObject(OBJ_EVENT_GFX_MAN_4,
                                             id - UR_SPRITE_START_ID,
                                             sUnionRoomPlayerCoords[leaderId][0] + sUnionRoomGroupOffsets[memberId][0],
                                             sUnionRoomPlayerCoords[leaderId][1] + sUnionRoomGroupOffsets[memberId][1],
                                             3, 1);
          SetVirtualObjectInvisibility(id - UR_SPRITE_START_ID, TRUE);
      }
}

/** void DestroyUnionRoomPlayerSprites(u8 *spriteIds) */
export function DestroyUnionRoomPlayerSprites(...args: any[]): any {
  let i: any = null;
      for (i = 0; i < NUM_UNION_ROOM_SPRITES; i++)
          DestroySprite(gSprites[spriteIds[i]]);
}

/** void SetTilesAroundUnionRoomPlayersPassable(void) */
export function SetTilesAroundUnionRoomPlayersPassable(): any {
  let i, memberId, x, y;
      for (i = 0; i < MAX_UNION_ROOM_LEADERS; i++)
      {
          for (memberId = 0; memberId < MAX_RFU_PLAYERS; memberId++)
          {
              GetUnionRoomPlayerCoords(i, memberId, x, y);
              MapGridSetMetatileImpassabilityAt(x, y, FALSE);
          }
      }
}

/** static u8 GetNewFacingDirectionForUnionRoomPlayer(u32 memberId, u32 leaderId, struct RfuGameData *gameData) */
export function GetNewFacingDirectionForUnionRoomPlayer(...args: any[]): any {
  if (memberId)  
          return sMemberFacingDirections[memberId];
      else if (gameData.activity == (ACTIVITY_CHAT | IN_UNION_ROOM))
          return DIR_SOUTH;
      else
          return DIR_EAST;
}

/** static bool32 IsUnionRoomPlayerInvisible(u32 leaderId, u32 memberId) */
export function IsUnionRoomPlayerInvisible(...args: any[]): any {
  return IsVirtualObjectInvisible(UR_PLAYER_SPRITE_ID(leaderId, memberId) - UR_SPRITE_START_ID);
}

/** static void SpawnGroupMember(u32 leaderId, u32 memberId, u8 graphicsId, struct RfuGameData *gameData) */
export function SpawnGroupMember(...args: any[]): any {
  let x, y;
      let id = UR_PLAYER_SPRITE_ID(leaderId, memberId);
      if (IsUnionRoomPlayerInvisible(leaderId, memberId) == TRUE)
      {
          SetVirtualObjectInvisibility(id - UR_SPRITE_START_ID, FALSE);
          SetVirtualObjectSpriteAnim(id - UR_SPRITE_START_ID, UNION_ROOM_SPAWN_IN);
      }
      SetVirtualObjectGraphics(id - UR_SPRITE_START_ID, graphicsId);
      SetUnionRoomObjectFacingDirection(memberId, leaderId, GetNewFacingDirectionForUnionRoomPlayer(memberId, leaderId, gameData));
      GetUnionRoomPlayerCoords(leaderId, memberId, x, y);
      MapGridSetMetatileImpassabilityAt(x, y, TRUE);
}

/** static void DespawnGroupMember(u32 leaderId, u32 memberId) */
export function DespawnGroupMember(...args: any[]): any {
  let x, y;
      SetVirtualObjectSpriteAnim(UR_PLAYER_SPRITE_ID(leaderId, memberId) - UR_SPRITE_START_ID, UNION_ROOM_SPAWN_OUT);
      GetUnionRoomPlayerCoords(leaderId, memberId, x, y);
      MapGridSetMetatileImpassabilityAt(x, y, FALSE);
}

/** static void AssembleGroup(u32 leaderId, struct RfuGameData *gameData) */
export function AssembleGroup(...args: any[]): any {
  let x, y, x2, y2;
      let i: any = null;

      PlayerGetDestCoords(x, y);
      player_get_pos_including_state_based_drift(x2, y2);
      if (IsVirtualObjectInvisible(UR_PLAYER_SPRITE_ID(leaderId, 0) - UR_SPRITE_START_ID) == TRUE)
      {
          if (IsUnionRoomPlayerAt(leaderId, 0, x, y) == TRUE || IsUnionRoomPlayerAt(leaderId, 0, x2, y2) == TRUE)
              return;
          SpawnGroupMember(leaderId, 0, GetUnionRoomPlayerGraphicsId(gameData.playerGender, gameData.compatibility.playerTrainerId[0]), gameData);
      }
      for (i = 1; i < MAX_RFU_PLAYERS; i++)
      {
          if (gameData.partnerInfo[i - 1] == 0)
          {
              DespawnGroupMember(leaderId, i);
          }
          else if (IsUnionRoomPlayerAt(leaderId, i, x, y) == FALSE && IsUnionRoomPlayerAt(leaderId, i, x2, y2) == FALSE)
          {
              SpawnGroupMember(leaderId, i, GetUnionRoomPlayerGraphicsId((gameData.partnerInfo[i - 1] >> PINFO_GENDER_SHIFT) & 1,
                                                                          gameData.partnerInfo[i - 1] & PINFO_TID_MASK),
                                                                          gameData);
          }
      }
}

/** static void SpawnGroupLeaderAndMembers(u32 leaderId, struct RfuGameData *gameData) */
export function SpawnGroupLeaderAndMembers(...args: any[]): any {
  let i: any = null;
      switch (gameData.activity)
      {
      case ACTIVITY_NONE | IN_UNION_ROOM:
      case ACTIVITY_PLYRTALK | IN_UNION_ROOM:
          SpawnGroupLeader(leaderId, gameData.playerGender, gameData.compatibility.playerTrainerId[0]);
          for (i = 0; i < MAX_RFU_PLAYERS; i++)
              DespawnGroupMember(leaderId, i);
          break;
      case ACTIVITY_BATTLE_SINGLE | IN_UNION_ROOM:
      case ACTIVITY_TRADE | IN_UNION_ROOM:
      case ACTIVITY_CHAT | IN_UNION_ROOM:
      case ACTIVITY_CARD | IN_UNION_ROOM:
      case ACTIVITY_ACCEPT | IN_UNION_ROOM:
      case ACTIVITY_DECLINE | IN_UNION_ROOM:
      case ACTIVITY_NPCTALK | IN_UNION_ROOM:
          DespawnGroupLeader(leaderId);
          AssembleGroup(leaderId, gameData);
          break;
      }
}

/** static void DespawnGroupLeaderAndMembers(u32 leaderId, struct RfuGameData *gameData) */
export function DespawnGroupLeaderAndMembers(...args: any[]): any {
  let i: any = null;
      DespawnGroupLeader(leaderId);
      for (i = 0; i < MAX_RFU_PLAYERS; i++)
          DespawnGroupMember(leaderId, i);
}

/** static void UpdateUnionRoomPlayerSprites(struct WirelessLink_URoom *uroom) */
export function UpdateUnionRoomPlayerSprites(...args: any[]): any {
  let i: any = null;
      let leaders: any = null;
      sUnionObjRefreshTimer = 0;
      for (i = 0, leaders = uroom.playerList.players; i < MAX_UNION_ROOM_LEADERS; i++)
      {
          if (leaders[i].groupScheduledAnim == UNION_ROOM_SPAWN_IN)
              SpawnGroupLeaderAndMembers(i, leaders[i].rfu.data);
          else if (leaders[i].groupScheduledAnim == UNION_ROOM_SPAWN_OUT)
              DespawnGroupLeaderAndMembers(i, leaders[i].rfu.data);
      }
}

/** void ScheduleUnionRoomPlayerRefresh(struct WirelessLink_URoom *uroom) */
export function ScheduleUnionRoomPlayerRefresh(...args: any[]): any {
  sUnionObjRefreshTimer = 300;
}

/** void HandleUnionRoomPlayerRefresh(struct WirelessLink_URoom *uroom) */
export function HandleUnionRoomPlayerRefresh(...args: any[]): any {
  if (++sUnionObjRefreshTimer > 300)
          UpdateUnionRoomPlayerSprites(uroom);
}

/** bool32 TryInteractWithUnionRoomMember(struct RfuPlayerList *list, s16 *memberIdPtr, s16 *leaderIdPtr, u8 *spriteIds) */
export function TryInteractWithUnionRoomMember(...args: any[]): any {
  let x, y;
      let i, memberId;
      let leaders: any = null;
      if (!IsPlayerStandingStill())
          return FALSE;

      GetXYCoordsOneStepInFrontOfPlayer(x, y);
      for (i = 0, leaders = list.players; i < MAX_UNION_ROOM_LEADERS; i++)
      {
          for (memberId = 0; memberId < MAX_RFU_PLAYERS; memberId++)
          {
              let id = UR_PLAYER_SPRITE_ID(i, memberId);

               
              if (x != sUnionRoomPlayerCoords[i][0] + sUnionRoomGroupOffsets[memberId][0] + 7)
                  continue;
              if (y != sUnionRoomPlayerCoords[i][1] + sUnionRoomGroupOffsets[memberId][1] + 7)
                  continue;

               
              if (IsVirtualObjectInvisible(id - UR_SPRITE_START_ID))
                  continue;
              if (IsVirtualObjectAnimating(id - UR_SPRITE_START_ID))
                  continue;
              if (leaders[i].groupScheduledAnim != UNION_ROOM_SPAWN_IN)
                  continue;

               
              SetUnionRoomObjectFacingDirection(memberId, i, sOppositeFacingDirection[GetPlayerFacingDirection()]);
              *memberIdPtr = memberId;
              *leaderIdPtr = i;
              return TRUE;
          }
      }
      return FALSE;
}

/** static void SetUnionRoomObjectFacingDirection(s32 memberId, s32 leaderId, u8 newDirection) */
export function SetUnionRoomObjectFacingDirection(...args: any[]): any {
  TurnVirtualObject(MAX_RFU_PLAYERS * leaderId - UR_SPRITE_START_ID + memberId, newDirection);
}

/** void UpdateUnionRoomMemberFacing(u32 memberId, u32 leaderId, struct RfuPlayerList *list) */
export function UpdateUnionRoomMemberFacing(...args: any[]): any {
  return SetUnionRoomObjectFacingDirection(memberId, leaderId, GetNewFacingDirectionForUnionRoomPlayer(memberId, leaderId, list.players[leaderId].rfu.data));
}

// ─── callsTo manifest (= 58 unique callees) ───────────────────────
// (Sorted alphabetically. Used for helper bridge detection.)
export const __callsTo__: ReadonlyArray<string> = ["AnimateUnionRoomPlayer","AnimateUnionRoomPlayerDespawn","AnimateUnionRoomPlayerSpawn","ArePlayerFieldControlsLocked","AssembleGroup","CreateTask","CreateTask_AnimateUnionRoomPlayers","CreateUnionRoomPlayerObjectEvent","CreateVirtualObject","DespawnGroupLeader","DespawnGroupLeaderAndMembers","DespawnGroupMember","DestroySprite","DestroyTask","DestroyTask_AnimateUnionRoomPlayers","FindTaskIdByFunc","FlagClear","FlagGet","FlagSet","FreezeObjectEvent","FuncIsActiveTask","GetNewFacingDirectionForUnionRoomPlayer","GetPlayerFacingDirection","GetUnionRoomPlayerCoords","GetUnionRoomPlayerGraphicsId","GetXYCoordsOneStepInFrontOfPlayer","HideUnionRoomPlayer","IsPlayerStandingStill","IsUnionRoomPlayerAt","IsUnionRoomPlayerHidden","IsUnionRoomPlayerInvisible","IsVirtualObjectAnimating","IsVirtualObjectInvisible","MapGridSetMetatileImpassabilityAt","ObjectEventClearHeldMovementIfFinished","ObjectEventIsMovementOverridden","ObjectEventSetHeldMovement","PlayerGetDestCoords","RemoveObjectEventByLocalIdAndMap","RemoveUnionRoomPlayerObjectEvent","SetUnionRoomObjectFacingDirection","SetUnionRoomPlayerEnterExitMovement","SetUnionRoomPlayerGfx","SetVirtualObjectGraphics","SetVirtualObjectInvisibility","SetVirtualObjectSpriteAnim","ShowUnionRoomPlayer","SpawnGroupLeader","SpawnGroupLeaderAndMembers","SpawnGroupMember","TryGetObjectEventIdByLocalIdAndMap","TryReleaseUnionRoomPlayerObjectEvent","TrySpawnObjectEvent","TurnVirtualObject","UR_PLAYER_SPRITE_ID","UnfreezeObjectEvent","UpdateUnionRoomPlayerSprites","VarSet"];
