// AUTO-GENERATED from src/battle_controller_link_partner.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/battle_controller_link_partner.c
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
/** Raw expr: `data[0]` */
export const sSpeedX_EXPR = "data[0]";
/** Raw expr: `data[2]` */
export const sSpeedY_EXPR = "data[2]";

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'LinkPartnerHandleGetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleGetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleSetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleSetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleLoadMonSprite', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleSwitchInAnim', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleReturnMonToBall', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleDrawTrainerPic', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleTrainerSlide', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleTrainerSlideBack', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleFaintAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandlePaletteFade', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleSuccessBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandlePause', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleMoveAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandlePrintString', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandlePrintSelectionString', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleChooseAction', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleYesNoBox', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleChooseMove', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleChooseItem', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleChoosePokemon', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleCmd23', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleHealthBarUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleExpUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleStatusIconUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleStatusAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleStatusXor', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleDataTransfer', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleDMA3Transfer', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandlePlayBGM', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleCmd32', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleTwoReturnValues', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleChosenMonReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleOneReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleOneReturnValue_Duplicate', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleClearUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleSetUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleClearUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleToggleUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleHitAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleCantSwitch', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandlePlaySE', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandlePlayFanfareOrBGM', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleFaintingCry', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleIntroSlide', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleIntroTrainerBallThrow', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleDrawPartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleHidePartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleEndBounceEffect', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleSpriteInvisibility', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleBattleAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleLinkStandbyMsg', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleResetActionMoveSelection', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerHandleEndLinkBattle', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerCmdEnd', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerBufferRunCommand', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerBufferExecCompleted', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_WaitAndEnd', ret: "void", arity: 0, params: "void" },
  { name: 'CopyLinkPartnerMonData', ret: "u32", arity: 2, params: "u8 monId, u8 *dst" },
  { name: 'SetLinkPartnerMonData', ret: "void", arity: 1, params: "u8 monId" },
  { name: 'StartSendOutAnim', ret: "void", arity: 2, params: "u8 battler, bool8 dontClearSubstituteBit" },
  { name: 'DoSwitchOutAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPartnerDoMoveAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'Task_StartSendOutAnim', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'EndDrawPartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'SpriteCB_Null2', ret: "void", arity: 0, params: "void" },
  { name: 'SetControllerToLinkPartner', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnBattlerSpriteCallbackDummy', ret: "void", arity: 0, params: "void" },
  { name: 'FreeTrainerSpriteAfterSlide', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_DelayAndEnd', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_WaitForHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_ShowHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'WaitForMonAnimAfterLoad', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnHealthbarDone', ret: "void", arity: 0, params: "void" },
  { name: 'FreeMonSpriteAfterFaintAnim', ret: "void", arity: 0, params: "void" },
  { name: 'FreeMonSpriteAfterSwitchOutAnim', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnInactiveTextPrinter', ret: "void", arity: 0, params: "void" },
  { name: 'DoHitAnimBlinkSpriteEffect', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_ShowSubstitute', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_ShowHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_TryShinyAnim', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedStatusAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedBattleAnimation', ret: "void", arity: 0, params: "void" },
] as const;

// ─── Task_* (state machine entry points) ────────────────────────────────────
export const TASK_NAMES = [
  'Task_StartSendOutAnim',
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'battle.h',
  'battle_ai_script_commands.h',
  'battle_anim.h',
  'battle_controllers.h',
  'battle_interface.h',
  'battle_message.h',
  'battle_setup.h',
  'battle_tower.h',
  'battle_tv.h',
  'bg.h',
  'data.h',
  'link.h',
  'main.h',
  'm4a.h',
  'palette.h',
  'pokeball.h',
  'pokemon.h',
  'recorded_battle.h',
  'reshow_battle_screen.h',
  'sound.h',
  'string_util.h',
  'task.h',
  'text.h',
  'util.h',
  'window.h',
  'constants/battle_anim.h',
  'constants/songs.h',
  'constants/trainers.h',
  'recorded_battle.h',
] as const;
