// AUTO-GENERATED from src/battle_controller_wally.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/battle_controller_wally.c
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
/** Raw expr: `data[0]` */
export const sSpeedX_EXPR = "data[0]";

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'WallyHandleGetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleGetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleSetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleSetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleLoadMonSprite', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleSwitchInAnim', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleReturnMonToBall', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleDrawTrainerPic', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleTrainerSlide', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleTrainerSlideBack', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleFaintAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandlePaletteFade', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleSuccessBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandlePause', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleMoveAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandlePrintString', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandlePrintSelectionString', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleChooseAction', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleYesNoBox', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleChooseMove', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleChooseItem', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleChoosePokemon', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleCmd23', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleHealthBarUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleExpUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleStatusIconUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleStatusAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleStatusXor', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleDataTransfer', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleDMA3Transfer', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandlePlayBGM', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleCmd32', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleTwoReturnValues', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleChosenMonReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleOneReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleOneReturnValue_Duplicate', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleClearUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleSetUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleClearUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleToggleUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleHitAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleCantSwitch', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandlePlaySE', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandlePlayFanfareOrBGM', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleFaintingCry', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleIntroSlide', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleIntroTrainerBallThrow', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleDrawPartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleHidePartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleEndBounceEffect', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleSpriteInvisibility', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleBattleAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleLinkStandbyMsg', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleResetActionMoveSelection', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleEndLinkBattle', ret: "void", arity: 0, params: "void" },
  { name: 'WallyCmdEnd', ret: "void", arity: 0, params: "void" },
  { name: 'WallyBufferRunCommand', ret: "void", arity: 0, params: "void" },
  { name: 'WallyBufferExecCompleted', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnChosenItem', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_WaitForShinyAnimAndHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'CopyWallyMonData', ret: "u32", arity: 2, params: "u8 monId, u8 *dst" },
  { name: 'SetWallyMonData', ret: "void", arity: 1, params: "u8 monId" },
  { name: 'WallyDoMoveAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'Task_StartSendOutAnim', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'SpriteCB_Null7', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'SetControllerToWally', ret: "void", arity: 0, params: "void" },
  { name: 'WallyHandleActions', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnBattlerSpriteCallbackDummy', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnInactiveTextPrinter', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'OpenBagAfterPaletteFade', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_TryShinyAnimShowHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnHealthbarDone', ret: "void", arity: 0, params: "void" },
  { name: 'DoHitAnimBlinkSpriteEffect', ret: "void", arity: 0, params: "void" },
  { name: 'DoSwitchOutAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnBankSpriteCallbackDummy2', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedBattleAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedStatusAnimation', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'HandleChooseActionAfterDma3', ret: "void", arity: 0, params: "void" },
  { name: 'StartSendOutAnim', ret: "void", arity: 1, params: "u8 battler" },
] as const;

// ─── Task_* (state machine entry points) ────────────────────────────────────
export const TASK_NAMES = [
  'Task_StartSendOutAnim',
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'battle.h',
  'battle_anim.h',
  'battle_controllers.h',
  'battle_interface.h',
  'battle_message.h',
  'battle_setup.h',
  'battle_tv.h',
  'bg.h',
  'data.h',
  'item.h',
  'item_menu.h',
  'link.h',
  'main.h',
  'm4a.h',
  'palette.h',
  'party_menu.h',
  'pokeball.h',
  'pokemon.h',
  'random.h',
  'reshow_battle_screen.h',
  'sound.h',
  'string_util.h',
  'task.h',
  'text.h',
  'util.h',
  'window.h',
  'constants/battle_anim.h',
  'constants/items.h',
  'constants/moves.h',
  'constants/songs.h',
  'constants/trainers.h',
  'constants/rgb.h',
] as const;
