// AUTO-GENERATED by scripts/transpile-callbacks.mjs
// Source : src/intro_credits_graphics.c (via SPRITE_CALLBACKS / TASKS / SPRITE_CBS / CB2S)
// Generated : 2026-04-29
// DO NOT EDIT — re-run `node scripts/transpile-callbacks.mjs` to refresh.
//
// Symbol substitution rules in script header.
// Manual fixes may be needed for /* TODO */ markers and undefined constants below.

/* eslint-disable */
// @ts-nocheck

import type { DecompRuntime, DecompSprite, DecompTask } from '../../../../harness/runtime/decomp-runtime';
import { DestroySprite } from '../../../sprite';
import {
  Sin, Cos, Q_8_8_TO_INT, SetOamMatrix, CalcCenterToCornerVec,
  ST_OAM_AFFINE_OFF, ST_OAM_AFFINE_NORMAL, ST_OAM_AFFINE_DOUBLE, ST_OAM_AFFINE_ERASE,
  ST_OAM_OBJ_NORMAL, ST_OAM_OBJ_BLEND, ST_OAM_OBJ_WINDOW,
  ST_OAM_4BPP, ST_OAM_8BPP,
  RGB, RGB_BLACK, RGB_WHITE, RGB_WHITEALPHA,
  PLTT_SIZEOF, PLTT_SIZE_4BPP, PLTT_SIZE_8BPP,
  OBJ_PLTT_ID_FADED, BG_PLTT_ID_FADED,
  BLDALPHA_BLEND, WIN_RANGE, GET_TRUE_SPRITE_INDEX, ANIM_SPRITES_START,
  gSineTable, PaletteBuffer, FreeAllSpritePalettes,
} from '../../../../harness/runtime/decomp-helpers';
import {
  gIntroCredits_MovingSceneryState,
  gIntroCredits_MovingSceneryVBase,
  gIntroCredits_MovingSceneryVOffset,
} from '../../../../harness/runtime/decomp-globals';
// Constants resolved from decomp #defines / enums / TS data modules :
const INTROCRED_SCENERY_FROZEN = 2;
const INTROCRED_SCENERY_NORMAL = 0;

export type SpriteCallback = (sprite: DecompSprite, rt: DecompRuntime) => void;
export type TaskCallback = (task: DecompTask, rt: DecompRuntime) => void;
export type CB2Callback = (rt: DecompRuntime) => void;

const _emptySprite: any = { data: new Array(16).fill(0), invisible: false, x: 0, y: 0, x2: 0, y2: 0, oamIndex: 0, spriteId: -1 };
const _emptyTask: any = { data: new Array(16).fill(0), func: null, taskId: -1 };
function _gs(rt: DecompRuntime, id: number): DecompSprite { return (rt.gSprites[id] as DecompSprite) ?? _emptySprite; }
function _gt(rt: DecompRuntime, id: number): DecompTask { return (rt.gTasks.get(id) as DecompTask) ?? _emptyTask; }
function _palView(buf: PaletteBuffer, base: number): ArrayLike<number> {
  return new Proxy({ length: 512 }, { get(t, k) { if (k === 'length') return 512; const i = Number(k); return Number.isFinite(i) ? buf.get(base + i) : undefined; } }) as ArrayLike<number>;
}

/** Source: intro_credits_graphics.c → SpriteCB_MovingScenery */
export const SpriteCB_MovingScenery: SpriteCallback = (sprite, rt) => {
  let x = 0;
      let state = gIntroCredits_MovingSceneryState;

      if (state != INTROCRED_SCENERY_FROZEN)
      {
          switch (state)
          {
          default:  
              DestroySprite(sprite.spriteId);
              break;
          case INTROCRED_SCENERY_NORMAL:
              x = ((sprite.x << 16) | sprite.data[2]) + sprite.data[1];
              sprite.x = x >> 16;
              sprite.data[2] = x;
              if (sprite.x > 255)
                  sprite.x = -32;
              if (sprite.data[0])
                  sprite.y2 = -(gIntroCredits_MovingSceneryVBase + gIntroCredits_MovingSceneryVOffset);
              else
                  sprite.y2 = -gIntroCredits_MovingSceneryVBase;
              break;
          }
      }
};

/** Source: intro_credits_graphics.c → SpriteCB_Bicycle */
export const SpriteCB_Bicycle: SpriteCallback = (sprite, rt) => {
  sprite.invisible = _gs(rt, sprite.data[0]).invisible;
      sprite.x = _gs(rt, sprite.data[0]).x;
      sprite.y = _gs(rt, sprite.data[0]).y + 8;
      sprite.x2 = _gs(rt, sprite.data[0]).x2;
      sprite.y2 = _gs(rt, sprite.data[0]).y2;
};

/** Source: intro_credits_graphics.c → SpriteCB_FlygonRightHalf */
export const SpriteCB_FlygonRightHalf: SpriteCallback = (sprite, rt) => {
  sprite.invisible = _gs(rt, sprite.data[0]).invisible;
      sprite.y = _gs(rt, sprite.data[0]).y;
      sprite.x2 = _gs(rt, sprite.data[0]).x2;
      sprite.y2 = _gs(rt, sprite.data[0]).y2;
};

/** Source: intro_credits_graphics.c (failed: empty bodyC) */
export const SpriteCB_Player: SpriteCallback = (_sprite, _rt) => { /* TODO empty bodyC */ };

/** Source: intro_credits_graphics.c (failed: empty bodyC) */
export const SpriteCB_FlygonLeftHalf: SpriteCallback = (_sprite, _rt) => { /* TODO empty bodyC */ };

/** Source: intro_credits_graphics.c → Task_BicycleBgAnimation */
export const Task_BicycleBgAnimation: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let bg1Speed = 0;
      let bg2Speed = 0;
      let bg3Speed = 0;
      let offset = 0;

       
      bg1Speed = task.data[1];
      if (bg1Speed != 0)
      {
          offset = (task.data[2] << 16) + (task.data[3] & 0xFFFF);
          offset -= bg1Speed << 4;
          task.data[2] = offset >> 16;
          task.data[3] = offset;
          rt.SetGpuReg(REG_OFFSET_BG1HOFS, task.data[2]);
          rt.SetGpuReg(REG_OFFSET_BG1VOFS, gIntroCredits_MovingSceneryVBase + gIntroCredits_MovingSceneryVOffset);
      }

       
      bg2Speed = task.data[4];
      if (bg2Speed != 0)
      {
          offset = (task.data[5] << 16) + (task.data[6] & 0xFFFF);
          offset -= bg2Speed << 4;
          task.data[5] = offset >> 16;
          task.data[6] = offset;
          rt.SetGpuReg(REG_OFFSET_BG2HOFS, task.data[5]);
          if (task.data[0] != 0)
              rt.SetGpuReg(REG_OFFSET_BG2VOFS, gIntroCredits_MovingSceneryVBase + gIntroCredits_MovingSceneryVOffset);
          else
              rt.SetGpuReg(REG_OFFSET_BG2VOFS, gIntroCredits_MovingSceneryVBase);
      }

       
      bg3Speed = task.data[7];
      if (bg3Speed != 0)
      {
          offset = (task.data[8] << 16) + (task.data[9] & 0xFFFF);
          offset -= bg3Speed << 4;
          task.data[8] = offset >> 16;
          task.data[9] = offset;
          rt.SetGpuReg(REG_OFFSET_BG3HOFS, task.data[8]);
          rt.SetGpuReg(REG_OFFSET_BG3VOFS, gIntroCredits_MovingSceneryVBase);
      }
};

/** Source: intro_credits_graphics.c → CreateBicycleBgAnimationTask (helper) */
export function CreateBicycleBgAnimationTask(rt: DecompRuntime, mode: number, bg1Speed: number, bg2Speed: number, bg3Speed: number): number {
  let sprite: any = _emptySprite;
  let task: any = _emptyTask;
  let taskId = rt.CreateTask((t) => Task_BicycleBgAnimation(t, rt), 0);

      task.data[0] = mode;
      task.data[1] = bg1Speed;
      task.data[2] = 0;
      task.data[3] = 0;
      task.data[4] = bg2Speed;
      task.data[5] = 0;
      task.data[6] = 0;
      task.data[7] = bg3Speed;
      task.data[8] = 8;
      task.data[9] = 0;
      Task_BicycleBgAnimation(taskId);
      return taskId;
  return -1;
}

/** Source: intro_credits_graphics.c → CreateMovingScenerySprites (helper) */
export function CreateMovingScenerySprites(rt: DecompRuntime, hasVerticalMove: number, metadata: any, anims: any, numSprites: number): number {
  let sprite: any = _emptySprite;
  let task: any = _emptyTask;
  let i = 0;

      for(i = 0; i < numSprites; i++)
      {
          let sprite = rt.CreateSpriteFromTemplate('sSpriteTemplate_MovingScenery',  metadata[i].x, metadata[i].y, metadata[i].subpriority);
          (() => { const _ctcv = CalcCenterToCornerVec(0, 0, 0); _gs(rt, sprite).centerToCornerVecX = _ctcv.centerToCornerVecX; _gs(rt, sprite).centerToCornerVecY = _ctcv.centerToCornerVecY; })();
          rt.gba.oam[_gs(rt, sprite).oamIndex].priority = 3;
          rt.gba.oam[_gs(rt, sprite).oamIndex].shape = metadata[i].shape;
          rt.gba.oam[_gs(rt, sprite).oamIndex].size = metadata[i].size;
          rt.gba.oam[_gs(rt, sprite).oamIndex].paletteBank = 0;
          _gs(rt, sprite).anims = anims;
          rt.rt.StartSpriteAnim(sprite.spriteId, metadata[i].animNum);
          _gs(rt, sprite).data[0] = hasVerticalMove;
          _gs(rt, sprite).data[1] = metadata[i].xOff;
          _gs(rt, sprite).data[2] = 0;
      }
  return -1;
}

/** Source: intro_credits_graphics.c → CreateCloudSprites (helper) */
export function CreateCloudSprites(rt: DecompRuntime): number {
  let sprite: any = _emptySprite;
  let task: any = _emptyTask;
  CreateMovingScenerySprites(rt, false, sSpriteMetadata_Clouds, sAnims_Clouds, 9);
  return -1;
}

/** Source: intro_credits_graphics.c → CreateTreeSprites (helper) */
export function CreateTreeSprites(rt: DecompRuntime): number {
  let sprite: any = _emptySprite;
  let task: any = _emptyTask;
  CreateMovingScenerySprites(rt, true, sSpriteMetadata_Trees, sAnims_Trees, 12);
  return -1;
}

/** Source: intro_credits_graphics.c → CreateHouseSprites (helper) */
export function CreateHouseSprites(rt: DecompRuntime): number {
  let sprite: any = _emptySprite;
  let task: any = _emptyTask;
  CreateMovingScenerySprites(rt, true, sSpriteMetadata_HouseSilhouette, sAnims_HouseSilhouette, 6);
  return -1;
}

/** Source: intro_credits_graphics.c → CreateIntroBrendanSprite (helper) */
export function CreateIntroBrendanSprite(rt: DecompRuntime, x: number, y: number): number {
  let sprite: any = _emptySprite;
  let task: any = _emptyTask;
  let playerSpriteId = rt.CreateSpriteFromTemplate('sSpriteTemplate_Brendan',  x, y, 2);
      let bicycleSpriteId = rt.CreateSpriteFromTemplate('sSpriteTemplate_BrendanBicycle',  x, y + 8, 3);
      _gs(rt, bicycleSpriteId).data[0] = playerSpriteId;
      return playerSpriteId;
  return -1;
}

/** Source: intro_credits_graphics.c → CreateIntroMaySprite (helper) */
export function CreateIntroMaySprite(rt: DecompRuntime, x: number, y: number): number {
  let sprite: any = _emptySprite;
  let task: any = _emptyTask;
  let playerSpriteId = rt.CreateSpriteFromTemplate('sSpriteTemplate_May',  x, y, 2);
      let bicycleSpriteId = rt.CreateSpriteFromTemplate('sSpriteTemplate_MayBicycle',  x, y + 8, 3);
      _gs(rt, bicycleSpriteId).data[0] = playerSpriteId;
      return playerSpriteId;
  return -1;
}

/** Source: intro_credits_graphics.c → CreateIntroFlygonSprite (helper) */
export function CreateIntroFlygonSprite(rt: DecompRuntime, x: number, y: number): number {
  let sprite: any = _emptySprite;
  let task: any = _emptyTask;
  let leftSpriteId = rt.CreateSpriteFromTemplate('sSpriteTemplate_FlygonLatias',  x - 32, y, 5);
      let rightSpriteId = rt.CreateSpriteFromTemplate('sSpriteTemplate_FlygonLatias',  x + 32, y, 6);
      _gs(rt, rightSpriteId).data[0] = leftSpriteId;
      rt.StartSpriteAnim(rightSpriteId, 1);
      _gs(rt, rightSpriteId).callback = SpriteCB_FlygonRightHalf;
      return leftSpriteId;
  return -1;
}
