// AUTO-GENERATED from src/lilycove_lady.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/lilycove_lady.c
// Generated: 2026-04-26

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'InitLilycoveQuizLady', ret: "void", arity: 0, params: "void" },
  { name: 'InitLilycoveFavorLady', ret: "void", arity: 0, params: "void" },
  { name: 'InitLilycoveContestLady', ret: "void", arity: 0, params: "void" },
  { name: 'ResetQuizLadyForRecordMix', ret: "void", arity: 0, params: "void" },
  { name: 'ResetFavorLadyForRecordMix', ret: "void", arity: 0, params: "void" },
  { name: 'ResetContestLadyForRecordMix', ret: "void", arity: 0, params: "void" },
  { name: 'BufferQuizAuthorName', ret: "u8", arity: 0, params: "void" },
  { name: 'IsQuizTrainerIdNotPlayer', ret: "bool8", arity: 0, params: "void" },
  { name: 'GetPlayerNameLength', ret: "u8", arity: 1, params: "const u8 *" },
  { name: 'GetLilycoveLadyId', ret: "u8", arity: 0, params: "void" },
  { name: 'SetLilycoveLadyGfx', ret: "void", arity: 0, params: "void" },
  { name: 'InitLilycoveLady', ret: "void", arity: 0, params: "void" },
  { name: 'ResetLilycoveLadyForRecordMix', ret: "void", arity: 0, params: "void" },
  { name: 'InitLilycoveLadyRandomly', ret: "void", arity: 0, params: "void" },
  { name: 'Script_GetLilycoveLadyId', ret: "void", arity: 0, params: "void" },
  { name: 'GetNumAcceptedItems', ret: "u8", arity: 1, params: "const u16 *itemsArray" },
  { name: 'FavorLadyPickFavorAndBestItem', ret: "void", arity: 0, params: "void" },
  { name: 'GetFavorLadyState', ret: "u8", arity: 0, params: "void" },
  { name: 'BufferFavorLadyRequest', ret: "void", arity: 0, params: "void" },
  { name: 'HasAnotherPlayerGivenFavorLadyItem', ret: "bool8", arity: 0, params: "void" },
  { name: 'BufferItemName', ret: "void", arity: 2, params: "u8 *dest, u16 itemId" },
  { name: 'BufferFavorLadyItemName', ret: "void", arity: 0, params: "void" },
  { name: 'SetFavorLadyPlayerName', ret: "void", arity: 2, params: "const u8 *src, u8 *dest" },
  { name: 'BufferFavorLadyPlayerName', ret: "void", arity: 0, params: "void" },
  { name: 'DidFavorLadyLikeItem', ret: "bool8", arity: 0, params: "void" },
  { name: 'Script_FavorLadyOpenBagMenu', ret: "void", arity: 0, params: "void" },
  { name: 'DoesFavorLadyLikeItem', ret: "bool8", arity: 1, params: "u16 itemId" },
  { name: 'Script_DoesFavorLadyLikeItem', ret: "bool8", arity: 0, params: "void" },
  { name: 'IsFavorLadyThresholdMet', ret: "bool8", arity: 0, params: "void" },
  { name: 'FavorLadyBufferPrizeName', ret: "void", arity: 1, params: "u16 prize" },
  { name: 'FavorLadyGetPrize', ret: "u16", arity: 0, params: "void" },
  { name: 'SetFavorLadyState_Complete', ret: "void", arity: 0, params: "void" },
  { name: 'FieldCallback_FavorLadyEnableScriptContexts', ret: "void", arity: 0, params: "void" },
  { name: 'QuizLadyPickQuestion', ret: "void", arity: 0, params: "void" },
  { name: 'GetQuizLadyState', ret: "u8", arity: 0, params: "void" },
  { name: 'GetQuizAuthor', ret: "u8", arity: 0, params: "void" },
  { name: 'BufferQuizPrizeName', ret: "void", arity: 0, params: "void" },
  { name: 'BufferQuizAuthorNameAndCheckIfLady', ret: "bool8", arity: 0, params: "void" },
  { name: 'IsQuizLadyWaitingForChallenger', ret: "bool8", arity: 0, params: "void" },
  { name: 'QuizLadyGetPlayerAnswer', ret: "void", arity: 0, params: "void" },
  { name: 'IsQuizAnswerCorrect', ret: "bool8", arity: 0, params: "void" },
  { name: 'BufferQuizPrizeItem', ret: "void", arity: 0, params: "void" },
  { name: 'SetQuizLadyState_Complete', ret: "void", arity: 0, params: "void" },
  { name: 'SetQuizLadyState_GivePrize', ret: "void", arity: 0, params: "void" },
  { name: 'ClearQuizLadyPlayerAnswer', ret: "void", arity: 0, params: "void" },
  { name: 'Script_QuizLadyOpenBagMenu', ret: "void", arity: 0, params: "void" },
  { name: 'QuizLadyPickNewQuestion', ret: "void", arity: 0, params: "void" },
  { name: 'ClearQuizLadyQuestionAndAnswer', ret: "void", arity: 0, params: "void" },
  { name: 'QuizLadySetCustomQuestion', ret: "void", arity: 0, params: "void" },
  { name: 'QuizLadyTakePrizeForCustomQuiz', ret: "void", arity: 0, params: "void" },
  { name: 'QuizLadyRecordCustomQuizData', ret: "void", arity: 0, params: "void" },
  { name: 'QuizLadySetWaitingForChallenger', ret: "void", arity: 0, params: "void" },
  { name: 'BufferQuizCorrectAnswer', ret: "void", arity: 0, params: "void" },
  { name: 'FieldCallback_QuizLadyEnableScriptContexts', ret: "void", arity: 0, params: "void" },
  { name: 'QuizLadyClearQuestionForRecordMix', ret: "void", arity: 1, params: "const LilycoveLady *lilycoveLady" },
  { name: 'ResetContestLadyContestData', ret: "void", arity: 0, params: "void" },
  { name: 'ContestLadySavePlayerNameIfHighSheen', ret: "void", arity: 1, params: "u8 sheen" },
  { name: 'GivePokeblockToContestLady', ret: "bool8", arity: 1, params: "struct Pokeblock *pokeblock" },
  { name: 'BufferContestLadyCategoryAndMonName', ret: "void", arity: 2, params: "u8 *category, u8 *nickname" },
  { name: 'BufferContestLadyMonName', ret: "void", arity: 2, params: "u8 *category, u8 *nickname" },
  { name: 'BufferContestLadyPlayerName', ret: "void", arity: 1, params: "u8 *dest" },
  { name: 'BufferContestLadyLanguage', ret: "void", arity: 1, params: "u8 *dest" },
  { name: 'BufferContestName', ret: "void", arity: 2, params: "u8 *dest, u8 category" },
  { name: 'GetContestLadyPokeblockState', ret: "u8", arity: 0, params: "void" },
  { name: 'HasPlayerGivenContestLadyPokeblock', ret: "bool8", arity: 0, params: "void" },
  { name: 'ShouldContestLadyShowGoOnAir', ret: "bool8", arity: 0, params: "void" },
  { name: 'Script_BufferContestLadyCategoryAndMonName', ret: "void", arity: 0, params: "void" },
  { name: 'OpenPokeblockCaseForContestLady', ret: "void", arity: 0, params: "void" },
  { name: 'SetContestLadyGivenPokeblock', ret: "void", arity: 0, params: "void" },
  { name: 'GetContestLadyMonSpecies', ret: "void", arity: 0, params: "void" },
  { name: 'GetContestLadyCategory', ret: "u8", arity: 0, params: "void" },
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'main.h',
  'overworld.h',
  'fldeff.h',
  'field_specials.h',
  'pokeblock.h',
  'event_data.h',
  'script.h',
  'random.h',
  'string_util.h',
  'item.h',
  'constants/items.h',
  'item_menu.h',
  'text.h',
  'easy_chat.h',
  'lilycove_lady.h',
  'contest.h',
  'strings.h',
  'constants/lilycove_lady.h',
  'data/lilycove_lady.h',
] as const;
