// AUTO-GENERATED from src/link.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/link.c
// Generated: 2026-04-26

// ─── Enums ───────────────────────────────────────────────────────────────────
export const ENUM_WIN_0 = {
  WIN_LINK_ERROR_TOP: 0,
  WIN_LINK_ERROR_MID: 1,
  WIN_LINK_ERROR_BOTTOM: 2,
} as const;

// ─── WindowTemplate ─────────────────────────────────────────────────────────────
export const sLinkErrorWindowTemplates = [
  { bg: 0, tilemapLeft: 0, tilemapTop: 0, width: "DISPLAY_TILE_WIDTH", height: 5, paletteNum: 15, baseBlock: 2 },
  { bg: 0, tilemapLeft: 0, tilemapTop: 6, width: "DISPLAY_TILE_WIDTH", height: 7, paletteNum: 15, baseBlock: 152 },
  { bg: 0, tilemapLeft: 0, tilemapTop: 13, width: "DISPLAY_TILE_WIDTH", height: 7, paletteNum: 15, baseBlock: 362 },
] as const;

// ─── BgTemplate ─────────────────────────────────────────────────────────────
export const sLinkErrorBgTemplates = [
  { bg: 0, charBaseIndex: 2, mapBaseIndex: 31, priority: 0 },
  { bg: 1, charBaseIndex: 0, mapBaseIndex: 8, priority: 1 },
] as const;

// ─── GFX/PAL paths (INCGFX) ─────────────────────────────────────────────────
export const GFX_SOURCES: Record<string, { path: string; ext: string; type: string }> = {
  'sWirelessLinkDisplayPal': { path: 'graphics/link/wireless_display.png', ext: '.gbapal', type: 'u16' },
  'sWirelessLinkDisplayGfx': { path: 'graphics/link/wireless_display.png', ext: '.4bpp.lz', type: 'u32' },
  'sWirelessLinkDisplayTilemap': { path: 'graphics/link/wireless_display.bin', ext: '.lz', type: 'u32' },
  'sLinkTestDigitsPal': { path: 'graphics/link/test_digits.png', ext: '.gbapal', type: 'u16' },
  'sLinkTestDigitsGfx': { path: 'graphics/link/test_digits.png', ext: '.4bpp', type: 'u16' },
  'sCommErrorBg_Gfx': { path: 'graphics/link/comm_error_bg.png', ext: '.4bpp', type: 'u16' },
};

// ─── Numeric arrays (raw data tables) ───────────────────────────────────────
export const sUnusedData: readonly number[] = [0,255,254,255,0] as const;

// ─── EWRAM/IWRAM/COMMON_DATA globals (initial values) ──────────────────────
export const SEGMENT_VARS = [
  { segment: 'COMMON_DATA', type: "u16", name: 'gLinkPartnersHeldKeys', isArray: true, init: "{0}" },
  { segment: 'COMMON_DATA', type: "u32", name: 'gLinkDebugSeed', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "struct LinkPlayerBlock", name: 'gLocalLinkPlayerBlock', isArray: false, init: "{0}" },
  { segment: 'COMMON_DATA', type: "bool8", name: 'gLinkErrorOccurred', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u32", name: 'gLinkDebugFlags', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u32", name: 'gLinkFiller1', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "bool8", name: 'gRemoteLinkPlayersNotReceived', isArray: true, init: "{0}" },
  { segment: 'COMMON_DATA', type: "u8", name: 'gBlockReceivedStatus', isArray: true, init: "{0}" },
  { segment: 'COMMON_DATA', type: "u32", name: 'gLinkFiller2', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u16", name: 'gLinkHeldKeys', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u32", name: 'gLinkStatus', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "bool8", name: 'gLinkDummy1', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "bool8", name: 'gLinkDummy2', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "bool8", name: 'gReadyToExitStandby', isArray: true, init: "{0}" },
  { segment: 'COMMON_DATA', type: "bool8", name: 'gReadyToCloseLink', isArray: true, init: "{0}" },
  { segment: 'COMMON_DATA', type: "u16", name: 'gReadyCloseLinkType', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u8", name: 'gSuppressLinkErrorMessage', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "bool8", name: 'gWirelessCommType', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "bool8", name: 'gSavedLinkPlayerCount', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u16", name: 'gSendCmd', isArray: true, init: "{0}" },
  { segment: 'COMMON_DATA', type: "u8", name: 'gSavedMultiplayerId', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "bool8", name: 'gReceivedRemoteLinkPlayers', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "struct LinkTestBGInfo", name: 'gLinkTestBGInfo', isArray: false, init: "{0}" },
  { segment: 'COMMON_DATA', type: "u8", name: 'gShouldAdvanceLinkState', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u16", name: 'gLinkTestBlockChecksums', isArray: true, init: "{0}" },
  { segment: 'COMMON_DATA', type: "u8", name: 'gBlockRequestType', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u32", name: 'gLinkFiller3', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u32", name: 'gLinkFiller4', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u32", name: 'gLinkFiller5', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u8", name: 'gLastSendQueueCount', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "struct Link", name: 'gLink', isArray: false, init: "{0}" },
  { segment: 'COMMON_DATA', type: "u8", name: 'gLastRecvQueueCount', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u16", name: 'gLinkSavedIme', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'sLinkTestDebugValuesEnabled', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'sDummyFlag', isArray: false, init: "FALSE" },
  { segment: 'EWRAM_DATA', type: "u32", name: 'gBerryBlenderKeySendAttempts', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'gBlockSendBuffer', isArray: true, init: "{}" },
  { segment: 'EWRAM_DATA', type: "bool8", name: 'sLinkOpen', isArray: false, init: "FALSE" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'gLinkType', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sTimeOutCounter', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "struct LinkPlayer", name: 'gLocalLinkPlayer', isArray: false, init: "{}" },
  { segment: 'EWRAM_DATA', type: "struct LinkPlayer", name: 'gLinkPlayers', isArray: true, init: "{}" },
  { segment: 'EWRAM_DATA', type: "struct LinkPlayer", name: 'sSavedLinkPlayers', isArray: true, init: "{}" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sReadyCloseLinkAttempts', isArray: false, init: "0" },
] as const;

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'InitLocalLinkPlayer', ret: "void", arity: 0, params: "void" },
  { name: 'VBlankCB_LinkError', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_LinkTest', ret: "void", arity: 0, params: "void" },
  { name: 'ProcessRecvCmds', ret: "void", arity: 1, params: "u8" },
  { name: 'LinkCB_SendHeldKeys', ret: "void", arity: 0, params: "void" },
  { name: 'ResetBlockSend', ret: "void", arity: 0, params: "void" },
  { name: 'InitBlockSend', ret: "bool32", arity: 2, params: "const void *, size_t" },
  { name: 'LinkCB_BlockSendBegin', ret: "void", arity: 0, params: "void" },
  { name: 'LinkCB_BlockSend', ret: "void", arity: 0, params: "void" },
  { name: 'LinkCB_BlockSendEnd', ret: "void", arity: 0, params: "void" },
  { name: 'SetBlockReceivedFlag', ret: "void", arity: 1, params: "u8" },
  { name: 'LinkTestCalcBlockChecksum', ret: "u16", arity: 2, params: "const u16 *, u16" },
  { name: 'LinkTest_PrintHex', ret: "void", arity: 4, params: "u32, u8, u8, u8" },
  { name: 'LinkCB_RequestPlayerDataExchange', ret: "void", arity: 0, params: "void" },
  { name: 'Task_PrintTestData', ret: "void", arity: 1, params: "u8" },
  { name: 'LinkCB_ReadyCloseLink', ret: "void", arity: 0, params: "void" },
  { name: 'LinkCB_WaitCloseLink', ret: "void", arity: 0, params: "void" },
  { name: 'LinkCB_ReadyCloseLinkWithJP', ret: "void", arity: 0, params: "void" },
  { name: 'LinkCB_WaitCloseLinkWithJP', ret: "void", arity: 0, params: "void" },
  { name: 'LinkCB_Standby', ret: "void", arity: 0, params: "void" },
  { name: 'LinkCB_StandbyForAll', ret: "void", arity: 0, params: "void" },
  { name: 'TrySetLinkErrorBuffer', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_PrintErrorMessage', ret: "void", arity: 0, params: "void" },
  { name: 'IsSioMultiMaster', ret: "bool8", arity: 0, params: "void" },
  { name: 'SetWirelessCommType0_Internal', ret: "void", arity: 0, params: "void" },
  { name: 'DisableSerial', ret: "void", arity: 0, params: "void" },
  { name: 'EnableSerial', ret: "void", arity: 0, params: "void" },
  { name: 'CheckMasterOrSlave', ret: "void", arity: 0, params: "void" },
  { name: 'InitTimer', ret: "void", arity: 0, params: "void" },
  { name: 'EnqueueSendCmd', ret: "void", arity: 1, params: "u16 *sendCmd" },
  { name: 'StartTransfer', ret: "void", arity: 0, params: "void" },
  { name: 'DoHandshake', ret: "bool8", arity: 0, params: "void" },
  { name: 'DoRecv', ret: "void", arity: 0, params: "void" },
  { name: 'DoSend', ret: "void", arity: 0, params: "void" },
  { name: 'StopTimer', ret: "void", arity: 0, params: "void" },
  { name: 'SendRecvDone', ret: "void", arity: 0, params: "void" },
  { name: 'IsWirelessAdapterConnected', ret: "bool8", arity: 0, params: "void" },
  { name: 'Task_DestroySelf', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'InitLinkTestBG', ret: "void", arity: 5, params: "u8 paletteNum, u8 bgNum, u8 screenBaseBlock, u8 charBaseBlock, u16 baseChar" },
  { name: 'LoadLinkTestBgGfx', ret: "UNUSED", arity: 4, params: "u8 paletteNum, u8 bgNum, u8 screenBaseBlock, u8 charBaseBlock" },
  { name: 'LinkTestScreen', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'SetLocalLinkPlayerId', ret: "void", arity: 1, params: "u8 playerId" },
  { name: 'InitLink', ret: "void", arity: 0, params: "void" },
  { name: 'Task_TriggerHandshake', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'OpenLink', ret: "void", arity: 0, params: "void" },
  { name: 'CloseLink', ret: "void", arity: 0, params: "void" },
  { name: 'TestBlockTransfer', ret: "void", arity: 3, params: "u8 nothing, u8 is, u8 used" },
  { name: 'LinkTestProcessKeyInput', ret: "void", arity: 0, params: "void" },
  { name: 'LinkMain2', ret: "u16", arity: 1, params: "const u16 *heldKeys" },
  { name: 'HandleReceiveRemoteLinkPlayer', ret: "void", arity: 1, params: "u8 who" },
  { name: 'BuildSendCmd', ret: "void", arity: 1, params: "u16 command" },
  { name: 'StartSendingKeysToLink', ret: "void", arity: 0, params: "void" },
  { name: 'IsSendingKeysToLink', ret: "bool32", arity: 0, params: "void" },
  { name: 'ClearLinkCallback', ret: "void", arity: 0, params: "void" },
  { name: 'ClearLinkCallback_2', ret: "void", arity: 0, params: "void" },
  { name: 'GetLinkPlayerCount', ret: "u8", arity: 0, params: "void" },
  { name: 'AreAnyLinkPlayersUsingVersions', ret: "int", arity: 2, params: "u32 version1, u32 version2" },
  { name: 'LinkDummy_Return2', ret: "u32", arity: 0, params: "void" },
  { name: 'IsFullLinkGroupWithNoRS', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'Link_AnyPartnersPlayingRubyOrSapphire', ret: "bool32", arity: 0, params: "void" },
  { name: 'Link_AnyPartnersPlayingFRLG_JP', ret: "bool32", arity: 0, params: "void" },
  { name: 'OpenLinkTimed', ret: "void", arity: 0, params: "void" },
  { name: 'GetLinkPlayerDataExchangeStatusTimed', ret: "u8", arity: 2, params: "int minPlayers, int maxPlayers" },
  { name: 'IsLinkPlayerDataExchangeComplete', ret: "bool8", arity: 0, params: "void" },
  { name: 'GetLinkPlayerTrainerId', ret: "u32", arity: 1, params: "u8 who" },
  { name: 'ResetLinkPlayers', ret: "void", arity: 0, params: "void" },
  { name: 'LinkCB_BerryBlenderSendHeldKeys', ret: "void", arity: 0, params: "void" },
  { name: 'SetBerryBlenderLinkCallback', ret: "void", arity: 0, params: "void" },
  { name: 'GetBerryBlenderKeySendAttempts', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'SendBerryBlenderNoSpaceForPokeblocks', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'GetMultiplayerId', ret: "u8", arity: 0, params: "void" },
  { name: 'BitmaskAllOtherLinkPlayers', ret: "u8", arity: 0, params: "void" },
  { name: 'SendBlock', ret: "bool8", arity: 3, params: "u8 unused, const void *src, u16 size" },
  { name: 'SendBlockRequest', ret: "bool8", arity: 1, params: "u8 blockReqType" },
  { name: 'IsLinkTaskFinished', ret: "bool8", arity: 0, params: "void" },
  { name: 'GetBlockReceivedStatus', ret: "u8", arity: 0, params: "void" },
  { name: 'ResetBlockReceivedFlags', ret: "void", arity: 0, params: "void" },
  { name: 'ResetBlockReceivedFlag', ret: "void", arity: 1, params: "u8 who" },
  { name: 'CheckShouldAdvanceLinkState', ret: "void", arity: 0, params: "void" },
  { name: 'LinkTest_PrintNumChar', ret: "void", arity: 3, params: "char val, u8 x, u8 y" },
  { name: 'LinkTest_PrintChar', ret: "void", arity: 3, params: "char val, u8 x, u8 y" },
  { name: 'LinkTest_PrintInt', ret: "UNUSED", arity: 4, params: "int num, u8 x, u8 y, u8 length" },
  { name: 'LinkTest_PrintString', ret: "void", arity: 3, params: "const char *str, u8 x, u8 y" },
  { name: 'SetLinkDebugValues', ret: "void", arity: 2, params: "u32 seed, u32 flags" },
  { name: 'GetSavedLinkPlayerCountAsBitFlags', ret: "u8", arity: 0, params: "void" },
  { name: 'GetLinkPlayerCountAsBitFlags', ret: "u8", arity: 0, params: "void" },
  { name: 'SaveLinkPlayers', ret: "void", arity: 1, params: "u8 playerCount" },
  { name: 'GetSavedPlayerCount', ret: "u8", arity: 0, params: "void" },
  { name: 'GetSavedMultiplayerId', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'DoesLinkPlayerCountMatchSaved', ret: "bool8", arity: 0, params: "void" },
  { name: 'ClearSavedLinkPlayers', ret: "void", arity: 0, params: "void" },
  { name: 'CheckLinkPlayersMatchSaved', ret: "void", arity: 0, params: "void" },
  { name: 'ResetLinkPlayerCount', ret: "void", arity: 0, params: "void" },
  { name: 'GetLinkPlayerCount_2', ret: "u8", arity: 0, params: "void" },
  { name: 'IsLinkMaster', ret: "bool8", arity: 0, params: "void" },
  { name: 'GetDummy2', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'SetCloseLinkCallbackAndType', ret: "void", arity: 1, params: "u16 type" },
  { name: 'SetCloseLinkCallback', ret: "void", arity: 0, params: "void" },
  { name: 'SetCloseLinkCallbackHandleJP', ret: "void", arity: 0, params: "void" },
  { name: 'SetLinkStandbyCallback', ret: "void", arity: 0, params: "void" },
  { name: 'SetLinkErrorBuffer', ret: "void", arity: 4, params: "u32 status, u8 lastSendQueueCount, u8 lastRecvQueueCount, bool8 disconnected" },
  { name: 'CB2_LinkError', ret: "void", arity: 0, params: "void" },
  { name: 'ErrorMsg_MoveCloserToPartner', ret: "void", arity: 0, params: "void" },
  { name: 'ErrorMsg_CheckConnections', ret: "void", arity: 0, params: "void" },
  { name: 'GetSioMultiSI', ret: "bool8", arity: 0, params: "void" },
  { name: 'IsLinkConnectionEstablished', ret: "bool8", arity: 0, params: "void" },
  { name: 'SetSuppressLinkErrorMessage', ret: "void", arity: 1, params: "bool8 flag" },
  { name: 'HasLinkErrorOccurred', ret: "bool8", arity: 0, params: "void" },
  { name: 'LocalLinkPlayerToBlock', ret: "void", arity: 0, params: "void" },
  { name: 'LinkPlayerFromBlock', ret: "void", arity: 1, params: "u32 who" },
  { name: 'HandleLinkConnection', ret: "bool8", arity: 0, params: "void" },
  { name: 'SetWirelessCommType1', ret: "void", arity: 0, params: "void" },
  { name: 'SetWirelessCommType0', ret: "void", arity: 0, params: "void" },
  { name: 'GetLinkRecvQueueLength', ret: "u32", arity: 0, params: "void" },
  { name: 'IsLinkRecvQueueAtOverworldMax', ret: "bool32", arity: 0, params: "void" },
  { name: 'GetWirelessCommType', ret: "u8", arity: 0, params: "void" },
  { name: 'ConvertLinkPlayerName', ret: "void", arity: 1, params: "struct LinkPlayer *player" },
  { name: 'ResetSerial', ret: "void", arity: 0, params: "void" },
  { name: 'LinkVSync', ret: "void", arity: 0, params: "void" },
  { name: 'Timer3Intr', ret: "void", arity: 0, params: "void" },
  { name: 'SerialCB', ret: "void", arity: 0, params: "void" },
  { name: 'ResetSendBuffer', ret: "void", arity: 0, params: "void" },
  { name: 'ResetRecvBuffer', ret: "void", arity: 0, params: "void" },
] as const;

// ─── Task_* (state machine entry points) ────────────────────────────────────
export const TASK_NAMES = [
  'Task_DestroySelf',
  'Task_PrintTestData',
  'Task_TriggerHandshake',
] as const;

// ─── CB2_* (callback / scene entry points) ──────────────────────────────────
export const CB2_NAMES = [
  'CB2_LinkError',
  'CB2_LinkTest',
  'CB2_PrintErrorMessage',
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'm4a.h',
  'malloc.h',
  'reload_save.h',
  'save.h',
  'bg.h',
  'window.h',
  'librfu.h',
  'random.h',
  'decompress.h',
  'string_util.h',
  'event_data.h',
  'item_menu.h',
  'overworld.h',
  'gpu_regs.h',
  'palette.h',
  'task.h',
  'scanline_effect.h',
  'menu.h',
  'text.h',
  'strings.h',
  'constants/songs.h',
  'sound.h',
  'trade.h',
  'battle.h',
  'link.h',
  'link_rfu.h',
  'constants/rgb.h',
  'constants/trade.h',
] as const;
