// AUTO-GENERATED from src/party_menu.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/party_menu.c
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
export const TAG_HELD_ITEM = 55120;
/** Raw expr: `(1 << 0)` */
export const PARTY_PAL_SELECTED_EXPR = "(1 << 0)";
/** Raw expr: `(1 << 1)` */
export const PARTY_PAL_FAINTED_EXPR = "(1 << 1)";
/** Raw expr: `(1 << 2)` */
export const PARTY_PAL_TO_SWITCH_EXPR = "(1 << 2)";
/** Raw expr: `(1 << 3)` */
export const PARTY_PAL_MULTI_ALT_EXPR = "(1 << 3)";
/** Raw expr: `(1 << 4)` */
export const PARTY_PAL_SWITCHING_EXPR = "(1 << 4)";
/** Raw expr: `(1 << 5)` */
export const PARTY_PAL_TO_SOFTBOIL_EXPR = "(1 << 5)";
/** Raw expr: `(1 << 6)` */
export const PARTY_PAL_NO_MON_EXPR = "(1 << 6)";
/** Raw expr: `(1 << 7)` */
export const PARTY_PAL_UNUSED_EXPR = "(1 << 7)";
export const MENU_DIR_DOWN = 1;
export const MENU_DIR_UP = -1;
export const MENU_DIR_RIGHT = 2;
export const MENU_DIR_LEFT = -2;
/** Raw expr: `data[0]` */
export const tKeepOpen_EXPR = "data[0]";
/** Raw expr: `data[0]` */
export const tHP_EXPR = "data[0]";
/** Raw expr: `data[1]` */
export const tMaxHP_EXPR = "data[1]";
/** Raw expr: `data[2]` */
export const tHPIncrement_EXPR = "data[2]";
/** Raw expr: `data[3]` */
export const tHPToAdd_EXPR = "data[3]";
/** Raw expr: `data[4]` */
export const tPartyId_EXPR = "data[4]";
/** Raw expr: `data[5]` */
export const tStartHP_EXPR = "data[5]";
/** Raw expr: `data[0]` */
export const tSlot1Left_EXPR = "data[0]";
/** Raw expr: `data[1]` */
export const tSlot1Top_EXPR = "data[1]";
/** Raw expr: `data[2]` */
export const tSlot1Width_EXPR = "data[2]";
/** Raw expr: `data[3]` */
export const tSlot1Height_EXPR = "data[3]";
/** Raw expr: `data[4]` */
export const tSlot2Left_EXPR = "data[4]";
/** Raw expr: `data[5]` */
export const tSlot2Top_EXPR = "data[5]";
/** Raw expr: `data[6]` */
export const tSlot2Width_EXPR = "data[6]";
/** Raw expr: `data[7]` */
export const tSlot2Height_EXPR = "data[7]";
/** Raw expr: `data[8]` */
export const tSlot1Offset_EXPR = "data[8]";
/** Raw expr: `data[9]` */
export const tSlot2Offset_EXPR = "data[9]";
/** Raw expr: `data[10]` */
export const tSlot1SlideDir_EXPR = "data[10]";
/** Raw expr: `data[11]` */
export const tSlot2SlideDir_EXPR = "data[11]";
/** Raw expr: `data[0]` */
export const tUsedOnSlot_EXPR = "data[0]";
/** Raw expr: `data[1]` */
export const tHadEffect_EXPR = "data[1]";
/** Raw expr: `data[2]` */
export const tLastSlotUsed_EXPR = "data[2]";
/** Raw expr: `data[0]` */
export const tXPos_EXPR = "data[0]";

// ─── Enums ───────────────────────────────────────────────────────────────────
export const ENUM_MENU_0 = {
  MENU_SUMMARY: 0,
  MENU_SWITCH: 1,
  MENU_CANCEL1: 2,
  MENU_ITEM: 3,
  MENU_GIVE: 4,
  MENU_TAKE_ITEM: 5,
  MENU_MAIL: 6,
  MENU_TAKE_MAIL: 7,
  MENU_READ: 8,
  MENU_CANCEL2: 9,
  MENU_SHIFT: 10,
  MENU_SEND_OUT: 11,
  MENU_ENTER: 12,
  MENU_NO_ENTRY: 13,
  MENU_STORE: 14,
  MENU_REGISTER: 15,
  MENU_TRADE1: 16,
  MENU_TRADE2: 17,
  MENU_TOSS: 18,
  MENU_FIELD_MOVES: 19,
} as const;
export const ENUM_ACTIONS_1 = {
  ACTIONS_NONE: 0,
  ACTIONS_SWITCH: 1,
  ACTIONS_SHIFT: 2,
  ACTIONS_SEND_OUT: 3,
  ACTIONS_ENTER: 4,
  ACTIONS_NO_ENTRY: 5,
  ACTIONS_STORE: 6,
  ACTIONS_SUMMARY_ONLY: 7,
  ACTIONS_ITEM: 8,
  ACTIONS_MAIL: 9,
  ACTIONS_REGISTER: 10,
  ACTIONS_TRADE: 11,
  ACTIONS_SPIN_TRADE: 12,
  ACTIONS_TAKEITEM_TOSS: 13,
} as const;
export const ENUM_FIELD_2 = {
  FIELD_MOVE_CUT: 0,
  FIELD_MOVE_FLASH: 1,
  FIELD_MOVE_ROCK_SMASH: 2,
  FIELD_MOVE_STRENGTH: 3,
  FIELD_MOVE_SURF: 4,
  FIELD_MOVE_FLY: 5,
  FIELD_MOVE_DIVE: 6,
  FIELD_MOVE_WATERFALL: 7,
  FIELD_MOVE_TELEPORT: 8,
  FIELD_MOVE_DIG: 9,
  FIELD_MOVE_SECRET_POWER: 10,
  FIELD_MOVE_MILK_DRINK: 11,
  FIELD_MOVE_SOFT_BOILED: 12,
  FIELD_MOVE_SWEET_SCENT: 13,
  FIELD_MOVES_COUNT: 14,
} as const;
export const ENUM_PARTY_3 = {
  PARTY_BOX_LEFT_COLUMN: 0,
  PARTY_BOX_RIGHT_COLUMN: 1,
} as const;
export const ENUM_TAG_4 = {
  TAG_POKEBALL: 1200,
  TAG_POKEBALL_SMALL: 1201,
  TAG_STATUS_ICONS: 1202,
} as const;
export const ENUM_CAN_5 = {
  CAN_LEARN_MOVE: 0,
  CANNOT_LEARN_MOVE: 1,
  ALREADY_KNOWS_MOVE: 2,
  CANNOT_LEARN_MOVE_IS_EGG: 3,
} as const;
export const ENUM_WIN_6 = {
  WIN_MSG: 0,
} as const;

// ─── EWRAM/IWRAM/COMMON_DATA globals (initial values) ──────────────────────
export const SEGMENT_VARS = [
  { segment: 'EWRAM_DATA', type: "struct PartyMenu", name: 'gPartyMenu', isArray: false, init: "{0}" },
  { segment: 'EWRAM_DATA', type: "bool8", name: 'gPartyMenuUseExitCallback', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'gSelectedMonPartyId', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "MainCallback", name: 'gPostMenuFieldCallback', isArray: false, init: "NULL" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'gSelectedOrderFromParty', isArray: true, init: "{0}" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sPartyMenuItemId', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sUnused', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'gBattlePartyCurrentOrder', isArray: true, init: "{0}" },
] as const;

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'ResetPartyMenu', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_InitPartyMenu', ret: "void", arity: 0, params: "void" },
  { name: 'ShowPartyMenu', ret: "bool8", arity: 0, params: "void" },
  { name: 'SetPartyMonsAllowedInMinigame', ret: "void", arity: 0, params: "void" },
  { name: 'ExitPartyMenu', ret: "void", arity: 0, params: "void" },
  { name: 'AllocPartyMenuBg', ret: "bool8", arity: 0, params: "void" },
  { name: 'AllocPartyMenuBgGfx', ret: "bool8", arity: 0, params: "void" },
  { name: 'InitPartyMenuWindows', ret: "void", arity: 1, params: "u8" },
  { name: 'InitPartyMenuBoxes', ret: "void", arity: 1, params: "u8" },
  { name: 'LoadPartyMenuPokeballGfx', ret: "void", arity: 0, params: "void" },
  { name: 'LoadPartyMenuAilmentGfx', ret: "void", arity: 0, params: "void" },
  { name: 'CreatePartyMonSpritesLoop', ret: "bool8", arity: 0, params: "void" },
  { name: 'RenderPartyMenuBoxes', ret: "bool8", arity: 0, params: "void" },
  { name: 'CreateCancelConfirmPokeballSprites', ret: "void", arity: 0, params: "void" },
  { name: 'CreateCancelConfirmWindows', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_ExitPartyMenu', ret: "void", arity: 1, params: "u8" },
  { name: 'FreePartyPointers', ret: "void", arity: 0, params: "void" },
  { name: 'PartyPaletteBufferCopy', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayPartyPokemonDataForMultiBattle', ret: "void", arity: 1, params: "u8" },
  { name: 'LoadPartyBoxPalette', ret: "void", arity: 2, params: "struct PartyMenuBox *, u8" },
  { name: 'DrawEmptySlot', ret: "void", arity: 1, params: "u8 windowId" },
  { name: 'DisplayPartyPokemonDataForRelearner', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayPartyPokemonDataForContest', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayPartyPokemonDataForChooseHalf', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayPartyPokemonDataForWirelessMinigame', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayPartyPokemonDataForBattlePyramidHeldItem', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayPartyPokemonDataForMoveTutorOrEvolutionItem', ret: "bool8", arity: 1, params: "u8" },
  { name: 'DisplayPartyPokemonData', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayPartyPokemonNickname', ret: "void", arity: 3, params: "struct Pokemon *, struct PartyMenuBox *, u8" },
  { name: 'DisplayPartyPokemonLevelCheck', ret: "void", arity: 3, params: "struct Pokemon *, struct PartyMenuBox *, u8" },
  { name: 'DisplayPartyPokemonGenderNidoranCheck', ret: "void", arity: 3, params: "struct Pokemon *, struct PartyMenuBox *, u8" },
  { name: 'DisplayPartyPokemonHPCheck', ret: "void", arity: 3, params: "struct Pokemon *, struct PartyMenuBox *, u8" },
  { name: 'DisplayPartyPokemonMaxHPCheck', ret: "void", arity: 3, params: "struct Pokemon *, struct PartyMenuBox *, u8" },
  { name: 'DisplayPartyPokemonHPBarCheck', ret: "void", arity: 2, params: "struct Pokemon *, struct PartyMenuBox *" },
  { name: 'DisplayPartyPokemonDescriptionText', ret: "void", arity: 3, params: "u8, struct PartyMenuBox *, u8" },
  { name: 'IsMonAllowedInMinigame', ret: "bool8", arity: 1, params: "u8" },
  { name: 'DisplayPartyPokemonDataToTeachMove', ret: "void", arity: 3, params: "u8, u16, u8" },
  { name: 'CanMonLearnTMTutor', ret: "u8", arity: 3, params: "struct Pokemon *, u16, u8" },
  { name: 'DisplayPartyPokemonBarDetail', ret: "void", arity: 4, params: "u8, const u8 *, u8, const u8 *" },
  { name: 'DisplayPartyPokemonLevel', ret: "void", arity: 2, params: "u8, struct PartyMenuBox *" },
  { name: 'DisplayPartyPokemonGender', ret: "void", arity: 4, params: "u8, u16, u8 *, struct PartyMenuBox *" },
  { name: 'DisplayPartyPokemonHP', ret: "void", arity: 2, params: "u16, struct PartyMenuBox *" },
  { name: 'DisplayPartyPokemonMaxHP', ret: "void", arity: 2, params: "u16, struct PartyMenuBox *" },
  { name: 'DisplayPartyPokemonHPBar', ret: "void", arity: 3, params: "u16, u16, struct PartyMenuBox *" },
  { name: 'CreatePartyMonIconSpriteParameterized', ret: "void", arity: 5, params: "u16, u32, struct PartyMenuBox *, u8, u32" },
  { name: 'CreatePartyMonHeldItemSpriteParameterized', ret: "void", arity: 3, params: "u16, u16, struct PartyMenuBox *" },
  { name: 'CreatePartyMonPokeballSpriteParameterized', ret: "void", arity: 2, params: "u16, struct PartyMenuBox *" },
  { name: 'CreatePartyMonStatusSpriteParameterized', ret: "void", arity: 3, params: "u16, u8, struct PartyMenuBox *" },
  { name: 'CreatePartyMonHeldItemSprite', ret: "void", arity: 2, params: "struct Pokemon *, struct PartyMenuBox *" },
  { name: 'CreatePartyMonPokeballSprite', ret: "void", arity: 2, params: "struct Pokemon *, struct PartyMenuBox *" },
  { name: 'CreatePartyMonIconSprite', ret: "void", arity: 3, params: "struct Pokemon *, struct PartyMenuBox *, u32" },
  { name: 'CreatePartyMonStatusSprite', ret: "void", arity: 2, params: "struct Pokemon *, struct PartyMenuBox *" },
  { name: 'CreateSmallPokeballButtonSprite', ret: "u8", arity: 2, params: "u8, u8" },
  { name: 'DrawCancelConfirmButtons', ret: "void", arity: 0, params: "void" },
  { name: 'CreatePokeballButtonSprite', ret: "u8", arity: 2, params: "u8, u8" },
  { name: 'AnimateSelectedPartyIcon', ret: "void", arity: 2, params: "u8, u8" },
  { name: 'PartyMenuStartSpriteAnim', ret: "void", arity: 2, params: "u8, u8" },
  { name: 'GetPartyBoxPaletteFlags', ret: "u8", arity: 2, params: "u8, u8" },
  { name: 'PartyBoxPal_ParnterOrDisqualifiedInArena', ret: "bool8", arity: 1, params: "u8" },
  { name: 'GetPartyIdFromBattleSlot', ret: "u8", arity: 1, params: "u8" },
  { name: 'Task_ClosePartyMenuAndSetCB2', ret: "void", arity: 1, params: "u8" },
  { name: 'UpdatePartyToFieldOrder', ret: "void", arity: 0, params: "void" },
  { name: 'MoveCursorToConfirm', ret: "void", arity: 0, params: "void" },
  { name: 'HandleChooseMonCancel', ret: "void", arity: 2, params: "u8, s8 *" },
  { name: 'HandleChooseMonSelection', ret: "void", arity: 2, params: "u8, s8 *" },
  { name: 'PartyMenuButtonHandler', ret: "u16", arity: 1, params: "s8 *" },
  { name: 'IsSelectedMonNotEgg', ret: "bool8", arity: 1, params: "u8 *" },
  { name: 'PartyMenuRemoveWindow', ret: "void", arity: 1, params: "u8 *" },
  { name: 'CB2_SetUpExitToBattleScreen', ret: "void", arity: 0, params: "void" },
  { name: 'Task_ClosePartyMenuAfterText', ret: "void", arity: 1, params: "u8" },
  { name: 'TryTutorSelectedMon', ret: "void", arity: 1, params: "u8" },
  { name: 'TryGiveMailToSelectedMon', ret: "void", arity: 1, params: "u8" },
  { name: 'TryGiveItemOrMailToSelectedMon', ret: "void", arity: 1, params: "u8" },
  { name: 'SwitchSelectedMons', ret: "void", arity: 1, params: "u8" },
  { name: 'TryEnterMonForMinigame', ret: "void", arity: 2, params: "u8, u8" },
  { name: 'Task_TryCreateSelectionWindow', ret: "void", arity: 1, params: "u8" },
  { name: 'FinishTwoMonAction', ret: "void", arity: 1, params: "u8" },
  { name: 'CancelParticipationPrompt', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayCancelChooseMonYesNo', ret: "bool8", arity: 1, params: "u8" },
  { name: 'Task_CancelChooseMonYesNo', ret: "void", arity: 1, params: "u8" },
  { name: 'PartyMenuDisplayYesNoMenu', ret: "void", arity: 0, params: "void" },
  { name: 'Task_HandleCancelChooseMonYesNoInput', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_ReturnToChooseMonAfterText', ret: "void", arity: 1, params: "u8" },
  { name: 'UpdateCurrentPartySelection', ret: "void", arity: 2, params: "s8 *, s8" },
  { name: 'UpdatePartySelectionSingleLayout', ret: "void", arity: 2, params: "s8 *, s8" },
  { name: 'UpdatePartySelectionDoubleLayout', ret: "void", arity: 2, params: "s8 *, s8" },
  { name: 'GetNewSlotDoubleLayout', ret: "s8", arity: 2, params: "s8, s8" },
  { name: 'PrintMessage', ret: "void", arity: 1, params: "const u8 *" },
  { name: 'Task_PrintAndWaitForText', ret: "void", arity: 1, params: "u8" },
  { name: 'IsMonAllowedInPokemonJump', ret: "bool16", arity: 1, params: "struct Pokemon *" },
  { name: 'IsMonAllowedInDodrioBerryPicking', ret: "bool16", arity: 1, params: "struct Pokemon *" },
  { name: 'Task_CancelParticipationYesNo', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_HandleCancelParticipationYesNoInput', ret: "void", arity: 1, params: "u8" },
  { name: 'CanLearnTutorMove', ret: "bool8", arity: 2, params: "u16, u8" },
  { name: 'GetTutorMove', ret: "u16", arity: 1, params: "u8" },
  { name: 'ShouldUseChooseMonText', ret: "bool8", arity: 0, params: "void" },
  { name: 'SetPartyMonFieldSelectionActions', ret: "void", arity: 2, params: "struct Pokemon *, u8" },
  { name: 'GetPartyMenuActionsTypeInBattle', ret: "u8", arity: 1, params: "struct Pokemon *" },
  { name: 'GetPartySlotEntryStatus', ret: "u8", arity: 1, params: "s8" },
  { name: 'Task_UpdateHeldItemSprite', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_HandleSelectionMenuInput', ret: "void", arity: 1, params: "u8" },
  { name: 'CB2_ShowPokemonSummaryScreen', ret: "void", arity: 0, params: "void" },
  { name: 'UpdatePartyToBattleOrder', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToPartyMenuFromSummaryScreen', ret: "void", arity: 0, params: "void" },
  { name: 'SlidePartyMenuBoxOneStep', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_SlideSelectedSlotsOffscreen', ret: "void", arity: 1, params: "u8" },
  { name: 'SwitchPartyMon', ret: "void", arity: 0, params: "void" },
  { name: 'Task_SlideSelectedSlotsOnscreen', ret: "void", arity: 1, params: "u8" },
  { name: 'CB2_SelectBagItemToGive', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_GiveHoldItem', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_WriteMailToGiveMon', ret: "void", arity: 0, params: "void" },
  { name: 'Task_SwitchHoldItemsPrompt', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_GiveHoldItem', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_SwitchItemsYesNo', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_HandleSwitchItemsYesNoInput', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_WriteMailToGiveMonAfterText', ret: "void", arity: 1, params: "u8" },
  { name: 'CB2_ReturnToPartyMenuFromWritingMail', ret: "void", arity: 0, params: "void" },
  { name: 'Task_DisplayGaveMailFromPartyMessage', ret: "void", arity: 1, params: "u8" },
  { name: 'UpdatePartyMonHeldItemSprite', ret: "void", arity: 2, params: "struct Pokemon *, struct PartyMenuBox *" },
  { name: 'Task_TossHeldItemYesNo', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'Task_HandleTossHeldItemYesNoInput', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_TossHeldItem', ret: "void", arity: 1, params: "u8" },
  { name: 'CB2_ReadHeldMail', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToPartyMenuFromReadingMail', ret: "void", arity: 0, params: "void" },
  { name: 'Task_SendMailToPCYesNo', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_HandleSendMailToPCYesNoInput', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_LoseMailMessageYesNo', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_HandleLoseMailMessageYesNoInput', ret: "void", arity: 1, params: "u8" },
  { name: 'TrySwitchInPokemon', ret: "bool8", arity: 0, params: "void" },
  { name: 'Task_SpinTradeYesNo', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_HandleSpinTradeYesNoInput', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_CancelAfterAorBPress', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayFieldMoveExitAreaMessage', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayCantUseFlashMessage', ret: "void", arity: 0, params: "void" },
  { name: 'DisplayCantUseSurfMessage', ret: "void", arity: 0, params: "void" },
  { name: 'Task_FieldMoveExitAreaYesNo', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_HandleFieldMoveExitAreaYesNoInput', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_FieldMoveWaitForFade', ret: "void", arity: 1, params: "u8" },
  { name: 'GetFieldMoveMonSpecies', ret: "u16", arity: 0, params: "void" },
  { name: 'UpdatePartyMonHPBar', ret: "void", arity: 2, params: "u8, struct Pokemon *" },
  { name: 'SpriteCB_UpdatePartyMonIcon', ret: "void", arity: 1, params: "struct Sprite *" },
  { name: 'SpriteCB_BouncePartyMonIcon', ret: "void", arity: 1, params: "struct Sprite *" },
  { name: 'ShowOrHideHeldItemSprite', ret: "void", arity: 2, params: "u16, struct PartyMenuBox *" },
  { name: 'CreateHeldItemSpriteForTrade', ret: "void", arity: 2, params: "u8, bool8" },
  { name: 'SpriteCB_HeldItem', ret: "void", arity: 1, params: "struct Sprite *" },
  { name: 'SetPartyMonAilmentGfx', ret: "void", arity: 2, params: "struct Pokemon *, struct PartyMenuBox *" },
  { name: 'UpdatePartyMonAilmentGfx', ret: "void", arity: 2, params: "u8, struct PartyMenuBox *" },
  { name: 'GetPartyLayoutFromBattleType', ret: "u8", arity: 0, params: "void" },
  { name: 'Task_SetSacredAshCB', ret: "void", arity: 1, params: "u8" },
  { name: 'CB2_ReturnToBagMenu', ret: "void", arity: 0, params: "void" },
  { name: 'Task_DisplayHPRestoredMessage', ret: "void", arity: 1, params: "u8" },
  { name: 'ItemEffectToMonEv', ret: "u16", arity: 2, params: "struct Pokemon *, u8" },
  { name: 'ItemEffectToStatString', ret: "void", arity: 2, params: "u8, u8 *" },
  { name: 'ReturnToUseOnWhichMon', ret: "void", arity: 1, params: "u8" },
  { name: 'SetSelectedMoveForPPItem', ret: "void", arity: 1, params: "u8" },
  { name: 'TryUsePPItem', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_LearnedMove', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_ReplaceMoveYesNo', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_DoLearnedMoveFanfareAfterText', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_LearnNextMoveOrClosePartyMenu', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_TryLearningNextMove', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_HandleReplaceMoveYesNoInput', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_ShowSummaryScreenToForgetMove', ret: "void", arity: 1, params: "u8" },
  { name: 'StopLearningMovePrompt', ret: "void", arity: 1, params: "u8" },
  { name: 'CB2_ShowSummaryScreenToForgetMove', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToPartyMenuWhileLearningMove', ret: "void", arity: 0, params: "void" },
  { name: 'Task_ReturnToPartyMenuWhileLearningMove', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayPartyMenuForgotMoveMessage', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_PartyMenuReplaceMove', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_StopLearningMoveYesNo', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_HandleStopLearningMoveYesNoInput', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_TryLearningNextMoveAfterText', ret: "void", arity: 1, params: "u8" },
  { name: 'BufferMonStatsToTaskData', ret: "void", arity: 2, params: "struct Pokemon *, s16 *" },
  { name: 'UpdateMonDisplayInfoAfterRareCandy', ret: "void", arity: 2, params: "u8, struct Pokemon *" },
  { name: 'Task_DisplayLevelUpStatsPg1', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayLevelUpStatsPg1', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_DisplayLevelUpStatsPg2', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayLevelUpStatsPg2', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_TryLearnNewMoves', ret: "void", arity: 1, params: "u8" },
  { name: 'PartyMenuTryEvolution', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayMonNeedsToReplaceMove', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayMonLearnedMove', ret: "void", arity: 2, params: "u8, u16" },
  { name: 'UseSacredAsh', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_SacredAshLoop', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_SacredAshDisplayHPRestored', ret: "void", arity: 1, params: "u8" },
  { name: 'GiveItemOrMailToSelectedMon', ret: "void", arity: 1, params: "u8" },
  { name: 'DisplayItemMustBeRemovedFirstMessage', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_SwitchItemsFromBagYesNo', ret: "void", arity: 1, params: "u8" },
  { name: 'RemoveItemToGiveFromBag', ret: "void", arity: 1, params: "u16" },
  { name: 'CB2_WriteMailToGiveMonFromBag', ret: "void", arity: 0, params: "void" },
  { name: 'GiveItemToSelectedMon', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_UpdateHeldItemSpriteAndClosePartyMenu', ret: "void", arity: 1, params: "u8" },
  { name: 'CB2_ReturnToPartyOrBagMenuFromWritingMail', ret: "void", arity: 0, params: "void" },
  { name: 'ReturnGiveItemToBagOrPC', ret: "bool8", arity: 1, params: "u16" },
  { name: 'Task_DisplayGaveMailFromBagMessage', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_HandleSwitchItemsFromBagYesNoInput', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_ValidateChosenHalfParty', ret: "void", arity: 1, params: "u8" },
  { name: 'GetBattleEntryEligibility', ret: "bool8", arity: 1, params: "struct Pokemon *" },
  { name: 'HasPartySlotAlreadyBeenSelected', ret: "bool8", arity: 1, params: "u8" },
  { name: 'GetBattleEntryLevelCap', ret: "u8", arity: 0, params: "void" },
  { name: 'GetMaxBattleEntries', ret: "u8", arity: 0, params: "void" },
  { name: 'GetMinBattleEntries', ret: "u8", arity: 0, params: "void" },
  { name: 'Task_ContinueChoosingHalfParty', ret: "void", arity: 1, params: "u8" },
  { name: 'BufferBattlePartyOrder', ret: "void", arity: 2, params: "u8 *, bool8" },
  { name: 'BufferBattlePartyOrderBySide', ret: "void", arity: 3, params: "u8 *, u8, u8" },
  { name: 'Task_InitMultiPartnerPartySlideIn', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_MultiPartnerPartySlideIn', ret: "void", arity: 1, params: "u8" },
  { name: 'SlideMultiPartyMenuBoxSpritesOneStep', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_WaitAfterMultiPartnerPartySlideIn', ret: "void", arity: 1, params: "u8" },
  { name: 'BufferMonSelection', ret: "void", arity: 0, params: "void" },
  { name: 'Task_PartyMenuWaitForFade', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'Task_ChooseContestMon', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'CB2_ChooseContestMon', ret: "void", arity: 0, params: "void" },
  { name: 'Task_ChoosePartyMon', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'Task_ChooseMonForMoveRelearner', ret: "void", arity: 1, params: "u8" },
  { name: 'CB2_ChooseMonForMoveRelearner', ret: "void", arity: 0, params: "void" },
  { name: 'Task_BattlePyramidChooseMonHeldItems', ret: "void", arity: 1, params: "u8" },
  { name: 'ShiftMoveSlot', ret: "void", arity: 3, params: "struct Pokemon *, u8, u8" },
  { name: 'BlitBitmapToPartyWindow_LeftColumn', ret: "void", arity: 6, params: "u8, u8, u8, u8, u8, bool8" },
  { name: 'BlitBitmapToPartyWindow_RightColumn', ret: "void", arity: 6, params: "u8, u8, u8, u8, u8, bool8" },
  { name: 'CursorCb_Summary', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Switch', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Cancel1', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Item', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Give', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_TakeItem', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Mail', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Read', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_TakeMail', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Cancel2', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_SendMon', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Enter', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_NoEntry', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Store', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Register', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Trade1', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Trade2', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_Toss', ret: "void", arity: 1, params: "u8" },
  { name: 'CursorCb_FieldMove', ret: "void", arity: 1, params: "u8" },
  { name: 'SetUpFieldMove_Surf', ret: "bool8", arity: 0, params: "void" },
  { name: 'SetUpFieldMove_Fly', ret: "bool8", arity: 0, params: "void" },
  { name: 'SetUpFieldMove_Waterfall', ret: "bool8", arity: 0, params: "void" },
  { name: 'SetUpFieldMove_Dive', ret: "bool8", arity: 0, params: "void" },
  { name: 'InitPartyMenu', ret: "void", arity: 7, params: "u8 menuType, u8 layout, u8 partyAction, bool8 keepCursorPos, u8 messageId, TaskFunc task, MainCallback callback" },
  { name: 'CB2_UpdatePartyMenu', ret: "void", arity: 0, params: "void" },
  { name: 'VBlankCB_PartyMenu', ret: "void", arity: 0, params: "void" },
  { name: 'RenderPartyMenuBox', ret: "void", arity: 1, params: "u8 slot" },
  { name: 'AnimatePartySlot', ret: "else", arity: 2, params: "slot, 0" },
  { name: 'DisplayPartyPokemonDescriptionData', ret: "void", arity: 2, params: "u8 slot, u8 stringID" },
  { name: 'CreatePartyMonSprites', ret: "void", arity: 1, params: "u8 slot" },
  { name: 'SetBgTilemapPalette', ret: "else", arity: 6, params: "1, 23, 16, 7, 2, 2" },
  { name: 'IsMultiBattle', ret: "bool8", arity: 0, params: "void" },
  { name: 'SwapPartyPokemon', ret: "void", arity: 2, params: "struct Pokemon *mon1, struct Pokemon *mon2" },
  { name: 'Task_ClosePartyMenu', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'SetMainCallback2', ret: "else", arity: 1, params: "gPartyMenu.exitCallback" },
  { name: 'GetCursorSelectionMonId', ret: "u8", arity: 0, params: "void" },
  { name: 'GetPartyMenuType', ret: "u8", arity: 0, params: "void" },
  { name: 'Task_HandleChooseMonInput', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'DisplayPartyMenuMessage', ret: "u8", arity: 2, params: "const u8 *str, bool8 keepOpen" },
  { name: 'IsPartyMenuTextPrinterActive', ret: "bool8", arity: 0, params: "void" },
  { name: 'Task_WaitForLinkAndReturnToChooseMon', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'DisplayGaveHeldItemMessage', ret: "void", arity: 4, params: "struct Pokemon *mon, u16 item, bool8 keepOpen, u8 unused" },
  { name: 'DisplayTookHeldItemMessage', ret: "void", arity: 3, params: "struct Pokemon *mon, u16 item, bool8 keepOpen" },
  { name: 'DisplayAlreadyHoldingItemSwitchMessage', ret: "void", arity: 3, params: "struct Pokemon *mon, u16 item, bool8 keepOpen" },
  { name: 'DisplaySwitchedHeldItemMessage', ret: "void", arity: 3, params: "u16 item, u16 item2, bool8 keepOpen" },
  { name: 'GiveItemToMon', ret: "void", arity: 2, params: "struct Pokemon *mon, u16 item" },
  { name: 'TryTakeMonItem', ret: "u8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'BufferBagFullCantTakeItemMessage', ret: "void", arity: 1, params: "u16 itemUnused" },
  { name: 'Task_PartyMenuModifyHP', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'PartyMenuModifyHP', ret: "void", arity: 5, params: "u8 taskId, u8 slot, s8 hpIncrement, s16 hpDifference, TaskFunc task" },
  { name: 'ResetHPTaskData', ret: "void", arity: 3, params: "u8 taskId, u8 caseId, u32 hp" },
  { name: 'GetAilmentFromStatus', ret: "u8", arity: 1, params: "u32 status" },
  { name: 'GetMonAilment', ret: "u8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'BlitBitmapToPartyWindow', ret: "void", arity: 7, params: "u8 windowId, const u8 *b, u8 c, u8 x, u8 y, u8 width, u8 height" },
  { name: 'DisplayPartyMenuStdMessage', ret: "void", arity: 1, params: "u32 stringId" },
  { name: 'DisplaySelectionWindow', ret: "u8", arity: 1, params: "u8 windowType" },
  { name: 'CreateLevelUpStatsWindow', ret: "u8", arity: 0, params: "void" },
  { name: 'RemoveLevelUpStatsWindow', ret: "void", arity: 0, params: "void" },
  { name: 'SetPartyMonSelectionActions', ret: "void", arity: 3, params: "struct Pokemon *mons, u8 slotId, u8 action" },
  { name: 'AppendToList', ret: "else", arity: 3, params: "sPartyMenuInternal->actions, &sPartyMenuInternal->numActions, MENU_ITEM" },
  { name: 'GetPartyMenuActionsType', ret: "u8", arity: 1, params: "struct Pokemon *mon" },
  { name: 'CreateSelectionWindow', ret: "bool8", arity: 1, params: "u8 taskId" },
  { name: 'TryMovePartySlot', ret: "bool8", arity: 5, params: "s16 x, s16 width, u8 *leftMove, u8 *newX, u8 *newWidth" },
  { name: 'MoveAndBufferPartySlot', ret: "void", arity: 6, params: "const void *rectSrc, s16 x, s16 y, s16 width, s16 height, s16 dir" },
  { name: 'MovePartyMenuBoxSprites', ret: "void", arity: 2, params: "struct PartyMenuBox *menuBox, s16 offset" },
  { name: 'SlidePartyMenuBoxSpritesOneStep', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'SwitchMenuBoxSprites', ret: "void", arity: 2, params: "u8 *spriteIdPtr1, u8 *spriteIdPtr2" },
  { name: 'GoToBattlePyramidBagMenu', ret: "else", arity: 2, params: "PYRAMIDBAG_LOC_PARTY, CB2_GiveHoldItem" },
  { name: 'FieldCallback_PrepareFadeInFromMenu', ret: "bool8", arity: 0, params: "void" },
  { name: 'FieldCallback_Surf', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToPartyMenuFromFlyMap', ret: "void", arity: 0, params: "void" },
  { name: 'FieldCallback_Waterfall', ret: "void", arity: 0, params: "void" },
  { name: 'FieldCallback_Dive', ret: "void", arity: 0, params: "void" },
  { name: 'UpdateHPBar', ret: "void", arity: 3, params: "u8 spriteId, u16 hp, u16 maxhp" },
  { name: 'StartSpriteAnim', ret: "else", arity: 2, params: "&gSprites[menuBox->itemSpriteId], 0" },
  { name: 'LoadHeldItemIcons', ret: "void", arity: 0, params: "void" },
  { name: 'DrawHeldItemIconsForTrade', ret: "void", arity: 3, params: "u8 *partyCounts, u8 *partySpriteIds, u8 whichParty" },
  { name: 'SpriteCB_BounceConfirmCancelButton', ret: "UNUSED", arity: 3, params: "u8 spriteId, u8 spriteId2, u8 animNum" },
  { name: 'CB2_ShowPartyMenuForItemUse', ret: "void", arity: 0, params: "void" },
  { name: 'IsHPRecoveryItem', ret: "bool8", arity: 1, params: "u16 item" },
  { name: 'GetMedicineItemEffectMessage', ret: "void", arity: 1, params: "u16 item" },
  { name: 'NotUsingHPEVItemOnShedinja', ret: "bool8", arity: 2, params: "struct Pokemon *mon, u16 item" },
  { name: 'IsItemFlute', ret: "bool8", arity: 1, params: "u16 item" },
  { name: 'ExecuteTableBasedItemEffect_', ret: "bool8", arity: 3, params: "u8 partyMonIndex, u16 item, u8 monMoveIndex" },
  { name: 'ItemUseCB_Medicine', ret: "void", arity: 2, params: "u8 taskId, TaskFunc task" },
  { name: 'ItemUseCB_ReduceEV', ret: "void", arity: 2, params: "u8 taskId, TaskFunc task" },
  { name: 'StringExpandPlaceholders', ret: "else", arity: 2, params: "gStringVar4, gText_PkmnFriendlyBaseVar2CantFall" },
  { name: 'ShowMoveSelectWindow', ret: "void", arity: 1, params: "u8 slot" },
  { name: 'Task_HandleWhichMoveInput', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'ItemUseCB_PPRecovery', ret: "void", arity: 2, params: "u8 taskId, TaskFunc task" },
  { name: 'ItemUseCB_PPUp', ret: "void", arity: 2, params: "u8 taskId, TaskFunc task" },
  { name: 'ItemIdToBattleMoveId', ret: "u16", arity: 1, params: "u16 item" },
  { name: 'IsMoveHm', ret: "bool8", arity: 1, params: "u16 move" },
  { name: 'MonKnowsMove', ret: "bool8", arity: 2, params: "struct Pokemon *mon, u16 move" },
  { name: 'DisplayLearnMoveMessage', ret: "void", arity: 1, params: "const u8 *str" },
  { name: 'DisplayLearnMoveMessageAndClose', ret: "void", arity: 2, params: "u8 taskId, const u8 *str" },
  { name: 'ItemUseCB_TMHM', ret: "void", arity: 2, params: "u8 taskId, TaskFunc task" },
  { name: 'ItemUseCB_RareCandy', ret: "void", arity: 2, params: "u8 taskId, TaskFunc task" },
  { name: 'ItemUseCB_SacredAsh', ret: "void", arity: 2, params: "u8 taskId, TaskFunc task" },
  { name: 'ItemUseCB_EvolutionStone', ret: "void", arity: 2, params: "u8 taskId, TaskFunc task" },
  { name: 'GetItemEffectType', ret: "u8", arity: 1, params: "u16 item" },
  { name: 'CB2_PartyMenuFromStartMenu', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ChooseMonToGiveItem', ret: "void", arity: 0, params: "void" },
  { name: 'RemoveBagItem', ret: "else", arity: 2, params: "item, 1" },
  { name: 'ChooseMonToGiveMailFromMailbox', ret: "void", arity: 0, params: "void" },
  { name: 'InitChooseHalfPartyForBattle', ret: "void", arity: 1, params: "u8 unused" },
  { name: 'ClearSelectedPartyOrder', ret: "void", arity: 0, params: "void" },
  { name: 'CheckBattleEntriesAndGetMessage', ret: "u8", arity: 0, params: "void" },
  { name: 'ChooseMonForTradingBoard', ret: "void", arity: 2, params: "u8 menuType, MainCallback callback" },
  { name: 'ChooseMonForMoveTutor', ret: "void", arity: 0, params: "void" },
  { name: 'ChooseMonForWirelessMinigame', ret: "void", arity: 0, params: "void" },
  { name: 'OpenPartyMenuInBattle', ret: "void", arity: 1, params: "u8 partyAction" },
  { name: 'ChooseMonForInBattleItem', ret: "void", arity: 0, params: "void" },
  { name: 'BufferBattlePartyCurrentOrder', ret: "void", arity: 0, params: "void" },
  { name: 'BufferBattlePartyCurrentOrderBySide', ret: "void", arity: 2, params: "u8 battler, u8 flankId" },
  { name: 'SwitchPartyOrderLinkMulti', ret: "void", arity: 3, params: "u8 battler, u8 slot, u8 slot2" },
  { name: 'SetPartyIdAtBattleSlot', ret: "void", arity: 2, params: "u8 slot, u8 setVal" },
  { name: 'SwitchPartyMonSlots', ret: "void", arity: 2, params: "u8 slot, u8 slot2" },
  { name: 'GetPartyIdFromBattlePartyId', ret: "u8", arity: 1, params: "u8 battlePartyId" },
  { name: 'SwitchAliveMonIntoLeadSlot', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'ShowPartyMenuToShowcaseMultiBattleParty', ret: "void", arity: 0, params: "void" },
  { name: 'MoveMultiPartyMenuBoxSprite', ret: "void", arity: 2, params: "u8 spriteId, s16 x" },
  { name: 'ChooseMonForDaycare', ret: "void", arity: 0, params: "void" },
  { name: 'ChoosePartyMonByMenuType', ret: "UNUSED", arity: 1, params: "u8 menuType" },
  { name: 'CB2_FadeFromPartyMenu', ret: "bool8", arity: 0, params: "void" },
  { name: 'ChooseContestMon', ret: "void", arity: 0, params: "void" },
  { name: 'ChoosePartyMon', ret: "void", arity: 0, params: "void" },
  { name: 'ChooseMonForMoveRelearner', ret: "void", arity: 0, params: "void" },
  { name: 'DoBattlePyramidMonsHaveHeldItem', ret: "void", arity: 0, params: "void" },
  { name: 'BattlePyramidChooseMonHeldItems', ret: "void", arity: 0, params: "void" },
  { name: 'MoveDeleterChooseMoveToForget', ret: "void", arity: 0, params: "void" },
  { name: 'GetNumMovesSelectedMonHas', ret: "void", arity: 0, params: "void" },
  { name: 'BufferMoveDeleterNicknameAndMove', ret: "void", arity: 0, params: "void" },
  { name: 'MoveDeleterForgetMove', ret: "void", arity: 0, params: "void" },
  { name: 'IsSelectedMonEgg', ret: "void", arity: 0, params: "void" },
  { name: 'IsLastMonThatKnowsSurf', ret: "void", arity: 0, params: "void" },
] as const;

// ─── Task_* (state machine entry points) ────────────────────────────────────
export const TASK_NAMES = [
  'Task_BattlePyramidChooseMonHeldItems',
  'Task_CancelAfterAorBPress',
  'Task_CancelChooseMonYesNo',
  'Task_CancelParticipationYesNo',
  'Task_ChooseContestMon',
  'Task_ChooseMonForMoveRelearner',
  'Task_ChoosePartyMon',
  'Task_ClosePartyMenu',
  'Task_ClosePartyMenuAfterText',
  'Task_ClosePartyMenuAndSetCB2',
  'Task_ContinueChoosingHalfParty',
  'Task_DisplayGaveMailFromBagMessage',
  'Task_DisplayGaveMailFromPartyMessage',
  'Task_DisplayHPRestoredMessage',
  'Task_DisplayLevelUpStatsPg1',
  'Task_DisplayLevelUpStatsPg2',
  'Task_DoLearnedMoveFanfareAfterText',
  'Task_ExitPartyMenu',
  'Task_FieldMoveExitAreaYesNo',
  'Task_FieldMoveWaitForFade',
  'Task_GiveHoldItem',
  'Task_HandleCancelChooseMonYesNoInput',
  'Task_HandleCancelParticipationYesNoInput',
  'Task_HandleChooseMonInput',
  'Task_HandleFieldMoveExitAreaYesNoInput',
  'Task_HandleLoseMailMessageYesNoInput',
  'Task_HandleReplaceMoveYesNoInput',
  'Task_HandleSelectionMenuInput',
  'Task_HandleSendMailToPCYesNoInput',
  'Task_HandleSpinTradeYesNoInput',
  'Task_HandleStopLearningMoveYesNoInput',
  'Task_HandleSwitchItemsFromBagYesNoInput',
  'Task_HandleSwitchItemsYesNoInput',
  'Task_HandleTossHeldItemYesNoInput',
  'Task_HandleWhichMoveInput',
  'Task_InitMultiPartnerPartySlideIn',
  'Task_LearnNextMoveOrClosePartyMenu',
  'Task_LearnedMove',
  'Task_LoseMailMessageYesNo',
  'Task_MultiPartnerPartySlideIn',
  'Task_PartyMenuModifyHP',
  'Task_PartyMenuReplaceMove',
  'Task_PartyMenuWaitForFade',
  'Task_PrintAndWaitForText',
  'Task_ReplaceMoveYesNo',
  'Task_ReturnToChooseMonAfterText',
  'Task_ReturnToPartyMenuWhileLearningMove',
  'Task_SacredAshDisplayHPRestored',
  'Task_SacredAshLoop',
  'Task_SendMailToPCYesNo',
  'Task_SetSacredAshCB',
  'Task_ShowSummaryScreenToForgetMove',
  'Task_SlideSelectedSlotsOffscreen',
  'Task_SlideSelectedSlotsOnscreen',
  'Task_SpinTradeYesNo',
  'Task_StopLearningMoveYesNo',
  'Task_SwitchHoldItemsPrompt',
  'Task_SwitchItemsFromBagYesNo',
  'Task_SwitchItemsYesNo',
  'Task_TossHeldItem',
  'Task_TossHeldItemYesNo',
  'Task_TryCreateSelectionWindow',
  'Task_TryLearnNewMoves',
  'Task_TryLearningNextMove',
  'Task_TryLearningNextMoveAfterText',
  'Task_UpdateHeldItemSprite',
  'Task_UpdateHeldItemSpriteAndClosePartyMenu',
  'Task_ValidateChosenHalfParty',
  'Task_WaitAfterMultiPartnerPartySlideIn',
  'Task_WaitForLinkAndReturnToChooseMon',
  'Task_WriteMailToGiveMonAfterText',
] as const;

// ─── CB2_* (callback / scene entry points) ──────────────────────────────────
export const CB2_NAMES = [
  'CB2_ChooseContestMon',
  'CB2_ChooseMonForMoveRelearner',
  'CB2_ChooseMonToGiveItem',
  'CB2_GiveHoldItem',
  'CB2_InitPartyMenu',
  'CB2_PartyMenuFromStartMenu',
  'CB2_ReadHeldMail',
  'CB2_ReturnToBagMenu',
  'CB2_ReturnToPartyMenuFromFlyMap',
  'CB2_ReturnToPartyMenuFromReadingMail',
  'CB2_ReturnToPartyMenuFromSummaryScreen',
  'CB2_ReturnToPartyMenuFromWritingMail',
  'CB2_ReturnToPartyMenuWhileLearningMove',
  'CB2_ReturnToPartyOrBagMenuFromWritingMail',
  'CB2_SelectBagItemToGive',
  'CB2_SetUpExitToBattleScreen',
  'CB2_ShowPartyMenuForItemUse',
  'CB2_ShowPokemonSummaryScreen',
  'CB2_ShowSummaryScreenToForgetMove',
  'CB2_UpdatePartyMenu',
  'CB2_WriteMailToGiveMon',
  'CB2_WriteMailToGiveMonFromBag',
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'malloc.h',
  'battle.h',
  'battle_anim.h',
  'battle_controllers.h',
  'battle_gfx_sfx_util.h',
  'battle_interface.h',
  'battle_pike.h',
  'battle_pyramid.h',
  'battle_pyramid_bag.h',
  'bg.h',
  'contest.h',
  'data.h',
  'decompress.h',
  'easy_chat.h',
  'event_data.h',
  'evolution_scene.h',
  'field_control_avatar.h',
  'field_effect.h',
  'field_player_avatar.h',
  'field_screen_effect.h',
  'field_specials.h',
  'field_weather.h',
  'fieldmap.h',
  'fldeff.h',
  'fldeff_misc.h',
  'frontier_util.h',
  'gpu_regs.h',
  'graphics.h',
  'international_string_util.h',
  'item.h',
  'item_menu.h',
  'item_use.h',
  'link.h',
  'link_rfu.h',
  'mail.h',
  'main.h',
  'menu.h',
  'menu_helpers.h',
  'menu_specialized.h',
  'metatile_behavior.h',
  'overworld.h',
  'palette.h',
  'party_menu.h',
  'player_pc.h',
  'pokemon.h',
  'pokemon_icon.h',
  'pokemon_jump.h',
  'pokemon_storage_system.h',
  'pokemon_summary_screen.h',
  'region_map.h',
  'reshow_battle_screen.h',
  'scanline_effect.h',
  'script.h',
  'sound.h',
  'sprite.h',
  'start_menu.h',
  'string_util.h',
  'strings.h',
  'task.h',
  'text.h',
  'text_window.h',
  'trade.h',
  'union_room.h',
  'window.h',
  'constants/battle.h',
  'constants/battle_frontier.h',
  'constants/field_effects.h',
  'constants/item_effects.h',
  'constants/items.h',
  'constants/moves.h',
  'constants/party_menu.h',
  'constants/rgb.h',
  'constants/songs.h',
  'data/pokemon/tutor_learnsets.h',
  'data/party_menu.h',
] as const;
