// AUTO-GENERATED from src/tv.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/tv.c
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
/** Raw expr: `(TV_SHOWS_COUNT - 1)` */
export const LAST_TVSHOW_IDX_EXPR = "(TV_SHOWS_COUNT - 1)";

// ─── Enums ───────────────────────────────────────────────────────────────────
export const ENUM_TVGROUP_0 = {
  TVGROUP_NONE: 0,
  TVGROUP_UNUSED: 1,
  TVGROUP_NORMAL: 2,
  TVGROUP_RECORD_MIX: 3,
  TVGROUP_OUTBREAK: 4,
} as const;
export const ENUM_SLOT_1 = {
  SLOT_MACHINE: 0,
  ROULETTE: 1,
} as const;

// ─── EWRAM/IWRAM/COMMON_DATA globals (initial values) ──────────────────────
export const SEGMENT_VARS = [
  { segment: 'COMMON_DATA', type: "s8", name: 'sCurTVShowSlot', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u16", name: 'sTV_SecretBaseVisitMovesTemp', isArray: true, init: "{0}" },
  { segment: 'COMMON_DATA', type: "u8", name: 'sTV_DecorationsBuffer', isArray: true, init: "{0}" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sPokemonAnglerSpecies', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sPokemonAnglerAttemptCounters', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sFindThatGamerCoinsSpent', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'sFindThatGamerWhichGame', isArray: false, init: "SLOT_MACHINE" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'sTVSecretBaseSecretsRandomValues', isArray: true, init: "{}" },
] as const;

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'ClearPokeNews', ret: "void", arity: 0, params: "void" },
  { name: 'GetTVGroupByShowId', ret: "u8", arity: 1, params: "u8" },
  { name: 'FindFirstActiveTVShowThatIsNotAMassOutbreak', ret: "u8", arity: 0, params: "void" },
  { name: 'SetTVMetatilesOnMap', ret: "void", arity: 3, params: "int, int, u16" },
  { name: 'FindAnyPokeNewsOnTheAir', ret: "u8", arity: 0, params: "void" },
  { name: 'TakeGabbyAndTyOffTheAir', ret: "void", arity: 0, params: "void" },
  { name: 'BernoulliTrial', ret: "bool8", arity: 1, params: "u16 ratio" },
  { name: 'FindFirstEmptyRecordMixTVShowSlot', ret: "s8", arity: 1, params: "TVShow *" },
  { name: 'IsRecordMixShowAlreadySpawned', ret: "bool8", arity: 2, params: "u8, bool8" },
  { name: 'StorePlayerIdInRecordMixShow', ret: "void", arity: 1, params: "TVShow *" },
  { name: 'DeleteTVShowInArrayByIdx', ret: "void", arity: 2, params: "TVShow *, u8" },
  { name: 'FindFirstEmptyNormalTVShowSlot', ret: "s8", arity: 1, params: "TVShow *" },
  { name: 'TryReplaceOldTVShowOfKind', ret: "void", arity: 1, params: "u8" },
  { name: 'InterviewBefore_BravoTrainerPkmnProfile', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewBefore_NameRater', ret: "void", arity: 0, params: "void" },
  { name: 'GetRandomDifferentSpeciesSeenByPlayer', ret: "u16", arity: 1, params: "u16" },
  { name: 'Script_FindFirstEmptyNormalTVShowSlot', ret: "void", arity: 0, params: "void" },
  { name: 'CompactTVShowArray', ret: "void", arity: 1, params: "TVShow *" },
  { name: 'GetFirstEmptyPokeNewsSlot', ret: "s8", arity: 1, params: "PokeNews *" },
  { name: 'IsAddingPokeNewsDisallowed', ret: "bool8", arity: 1, params: "u8" },
  { name: 'ClearPokeNewsBySlot', ret: "void", arity: 1, params: "u8" },
  { name: 'TranslateRubyShows', ret: "void", arity: 1, params: "TVShow *" },
  { name: 'TranslateJapaneseEmeraldShows', ret: "void", arity: 1, params: "TVShow *" },
  { name: 'SetMixedTVShows', ret: "void", arity: 4, params: "TVShow *, TVShow *, TVShow *, TVShow *" },
  { name: 'DeleteExcessMixedShows', ret: "void", arity: 0, params: "void" },
  { name: 'DeactivateShowsWithUnseenSpecies', ret: "void", arity: 0, params: "void" },
  { name: 'DeactivateGameCompleteShowsIfNotUnlocked', ret: "void", arity: 0, params: "void" },
  { name: 'FindInactiveShowInArray', ret: "s8", arity: 1, params: "TVShow *" },
  { name: 'TryMixTVShow', ret: "bool8", arity: 3, params: "TVShow *[], TVShow *[], u8" },
  { name: 'TryMixNormalTVShow', ret: "bool8", arity: 3, params: "TVShow *, TVShow *, u8" },
  { name: 'TryMixRecordMixTVShow', ret: "bool8", arity: 3, params: "TVShow *, TVShow *, u8" },
  { name: 'TryMixOutbreakTVShow', ret: "bool8", arity: 3, params: "TVShow *, TVShow *, u8" },
  { name: 'DeactivateShow', ret: "void", arity: 1, params: "u8 showIdx" },
  { name: 'DeactivateShowIfNotSeenSpecies', ret: "void", arity: 2, params: "u16, u8" },
  { name: 'SetMixedPokeNews', ret: "void", arity: 4, params: "PokeNews *, PokeNews *, PokeNews *, PokeNews *" },
  { name: 'ClearInvalidPokeNews', ret: "void", arity: 0, params: "void" },
  { name: 'ClearPokeNewsIfGameNotComplete', ret: "void", arity: 0, params: "void" },
  { name: 'GetPokeNewsSlotIfActive', ret: "s8", arity: 2, params: "PokeNews *, u8" },
  { name: 'InitTryMixPokeNewsShow', ret: "void", arity: 2, params: "PokeNews *[], PokeNews *[]" },
  { name: 'TryMixPokeNewsShow', ret: "bool8", arity: 3, params: "PokeNews *, PokeNews *, s8" },
  { name: 'TVShowDone', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewAfter_FanClubLetter', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewAfter_RecentHappenings', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewAfter_PkmnFanClubOpinions', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewAfter_Dummy', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewAfter_BravoTrainerPokemonProfile', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewAfter_BravoTrainerBattleTowerProfile', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewAfter_ContestLiveUpdates', ret: "void", arity: 0, params: "void" },
  { name: 'InitWorldOfMastersShowAttempt', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutPokemonTodayFailedOnTheAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryStartRandomMassOutbreak', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutRandomPokeNewsOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'SortPurchasesByQuantity', ret: "void", arity: 0, params: "void" },
  { name: 'UpdateMassOutbreakTimeLeft', ret: "void", arity: 1, params: "u16" },
  { name: 'TryEndMassOutbreak', ret: "void", arity: 1, params: "u16" },
  { name: 'UpdatePokeNewsCountdown', ret: "void", arity: 1, params: "u16" },
  { name: 'ResolveWorldOfMastersShow', ret: "void", arity: 1, params: "u16" },
  { name: 'ResolveNumberOneShow', ret: "void", arity: 1, params: "u16" },
  { name: 'TryPutFishingAdviceOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'MonDataIdxToRibbon', ret: "u8", arity: 1, params: "u8" },
  { name: 'TryPutNumberOneOnAir', ret: "void", arity: 1, params: "u8" },
  { name: 'ShouldApplyPokeNewsEffect', ret: "bool8", arity: 1, params: "u8" },
  { name: 'TryPutWorldOfMastersOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewBefore_FanClubLetter', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewBefore_RecentHappenings', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewBefore_PkmnFanClubOpinions', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewBefore_Dummy', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewBefore_BravoTrainerBTProfile', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewBefore_ContestLiveUpdates', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewBefore_3CheersForPokeblocks', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewBefore_FanClubSpecial', ret: "void", arity: 0, params: "void" },
  { name: 'ChangeBoxPokemonNickname_CB', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowPokemonFanClubLetter', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowRecentHappenings', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowPokemonFanClubOpinions', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowDummiedOut', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowPokemonNewsMassOutbreak', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowBravoTrainerPokemonProfile', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowBravoTrainerBattleTower', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowPokemonTodaySuccessfulCapture', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowTodaysSmartShopper', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowTheNameRaterShow', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowPokemonContestLiveUpdates', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowPokemonBattleUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShow3CheersForPokeblocks', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowPokemonTodayFailedCapture', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowPokemonAngler', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowTheWorldOfMasters', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowTodaysRivalTrainer', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowDewfordTrendWatcherNetwork', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowHoennTreasureInvestigators', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowFindThatGamer', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowBreakingNewsTV', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowSecretBaseVisit', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowPokemonLotteryWinnerFlashReport', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowThePokemonBattleSeminar', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowTrainerFanClubSpecial', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowTrainerFanClub', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowSpotTheCuties', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowPokemonNewsBattleFrontier', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowWhatsNo1InHoennToday', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowSecretBaseSecrets', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowSafariFanClub', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowLilycoveContestLady', ret: "void", arity: 0, params: "void" },
  { name: 'ClearTVShowData', ret: "void", arity: 0, params: "void" },
  { name: 'GetRandomActiveShowIdx', ret: "u8", arity: 0, params: "void" },
  { name: 'FindAnyTVShowOnTheAir', ret: "u8", arity: 0, params: "void" },
  { name: 'UpdateTVScreensOnMap', ret: "void", arity: 2, params: "int width, int height" },
  { name: 'TurnOffTVScreen', ret: "void", arity: 0, params: "void" },
  { name: 'TurnOnTVScreen', ret: "void", arity: 0, params: "void" },
  { name: 'GetSelectedTVShow', ret: "u8", arity: 0, params: "void" },
  { name: 'GetNextActiveShowIfMassOutbreak', ret: "u8", arity: 0, params: "void" },
  { name: 'ResetGabbyAndTy', ret: "void", arity: 0, params: "void" },
  { name: 'GabbyAndTyBeforeInterview', ret: "void", arity: 0, params: "void" },
  { name: 'GabbyAndTyAfterInterview', ret: "void", arity: 0, params: "void" },
  { name: 'GabbyAndTyGetBattleNum', ret: "u8", arity: 0, params: "void" },
  { name: 'IsGabbyAndTyShowOnTheAir', ret: "bool8", arity: 0, params: "void" },
  { name: 'GabbyAndTyGetLastQuote', ret: "bool8", arity: 0, params: "void" },
  { name: 'GabbyAndTyGetLastBattleTrivia', ret: "u8", arity: 0, params: "void" },
  { name: 'GetGabbyAndTyLocalIds', ret: "void", arity: 0, params: "void" },
  { name: 'InterviewAfter', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutPokemonTodayOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'StorePlayerIdInNormalShow', ret: "void", arity: 1, params: "TVShow *show" },
  { name: 'PutBattleUpdateOnTheAir', ret: "void", arity: 4, params: "u8 opponentLinkPlayerId, u16 move, u16 speciesPlayer, u16 speciesOpponent" },
  { name: 'Put3CheersForPokeblocksOnTheAir', ret: "bool8", arity: 5, params: "const u8 *partnersName, u8 flavor, u8 color, u8 sheen, u8 language" },
  { name: 'PutFanClubSpecialOnTheAir', ret: "void", arity: 0, params: "void" },
  { name: 'ContestLiveUpdates_Init', ret: "void", arity: 1, params: "u8 round1Placing" },
  { name: 'ContestLiveUpdates_SetRound2Placing', ret: "void", arity: 1, params: "u8 round2Placing" },
  { name: 'ContestLiveUpdates_SetWinnerAppealFlag', ret: "void", arity: 1, params: "u8 flag" },
  { name: 'ContestLiveUpdates_SetWinnerMoveUsed', ret: "void", arity: 1, params: "u16 move" },
  { name: 'ContestLiveUpdates_SetLoserData', ret: "void", arity: 2, params: "u8 flag, u8 loser" },
  { name: 'BravoTrainerPokemonProfile_BeforeInterview1', ret: "void", arity: 1, params: "u16 move" },
  { name: 'BravoTrainerPokemonProfile_BeforeInterview2', ret: "void", arity: 1, params: "u8 contestStandingPlace" },
  { name: 'TryPutSmartShopperOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'PutNameRaterShowOnTheAir', ret: "void", arity: 0, params: "void" },
  { name: 'StartMassOutbreak', ret: "void", arity: 0, params: "void" },
  { name: 'PutLilycoveContestLadyShowOnTheAir', ret: "void", arity: 0, params: "void" },
  { name: 'EndMassOutbreak', ret: "void", arity: 0, params: "void" },
  { name: 'UpdateTVShowsPerDay', ret: "void", arity: 1, params: "u16 days" },
  { name: 'RecordFishingAttemptForTV', ret: "void", arity: 1, params: "bool8 caughtFish" },
  { name: 'SetPokemonAnglerSpecies', ret: "void", arity: 1, params: "u16 species" },
  { name: 'TryPutTodaysRivalTrainerOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutTrendWatcherOnAir', ret: "void", arity: 1, params: "const u16 *words" },
  { name: 'TryPutTreasureInvestigatorsOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutFindThatGamerOnAir', ret: "void", arity: 1, params: "u16 nCoinsPaidOut" },
  { name: 'AlertTVThatPlayerPlayedSlotMachine', ret: "void", arity: 1, params: "u16 nCoinsSpent" },
  { name: 'AlertTVThatPlayerPlayedRoulette', ret: "void", arity: 1, params: "u16 nCoinsSpent" },
  { name: 'SecretBaseVisit_CalculateDecorationData', ret: "void", arity: 1, params: "TVShow *show" },
  { name: 'SecretBaseVisit_CalculatePartyData', ret: "void", arity: 1, params: "TVShow *show" },
  { name: 'TryPutSecretBaseVisitOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutBreakingNewsOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutLotteryWinnerReportOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'TryPutBattleSeminarOnAir', ret: "void", arity: 5, params: "u16 foeSpecies, u16 species, u8 moveIndex, const u16 *movePtr, u16 betterMove" },
  { name: 'TryPutSafariFanClubOnAir', ret: "void", arity: 2, params: "u8 monsCaught, u8 pokeblocksUsed" },
  { name: 'TryPutSpotTheCutiesOnAir', ret: "void", arity: 2, params: "struct Pokemon *pokemon, u8 ribbonMonDataIdx" },
  { name: 'GetRibbonCount', ret: "u8", arity: 1, params: "struct Pokemon *pokemon" },
  { name: 'TryPutTrainerFanClubOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'ShouldHideFanClubInterviewer', ret: "bool8", arity: 0, params: "void" },
  { name: 'ShouldAirFrontierTVShow', ret: "bool8", arity: 0, params: "void" },
  { name: 'TryPutFrontierTVShowOnAir', ret: "void", arity: 2, params: "u16 winStreak, u8 facilityAndMode" },
  { name: 'TryPutSecretBaseSecretsOnAir', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailySlotsUses', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyRouletteUses', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyWildBattles', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyBerryBlender', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyPlantedBerries', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyPickedBerries', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementDailyBattlePoints', ret: "void", arity: 1, params: "u16 delta" },
  { name: 'CompactPokeNews', ret: "void", arity: 0, params: "void" },
  { name: 'DoPokeNews', ret: "void", arity: 0, params: "void" },
  { name: 'ShowFieldMessage', ret: "else", arity: 1, params: "sPokeNewsTextGroup_Ending[gSaveBlock1Ptr->pokeNews[i].kind]" },
  { name: 'IsPokeNewsActive', ret: "bool8", arity: 1, params: "u8 newsKind" },
  { name: 'CopyContestRankToStringVar', ret: "void", arity: 2, params: "u8 varIdx, u8 rank" },
  { name: 'CopyContestCategoryToStringVar', ret: "void", arity: 2, params: "u8 varIdx, u8 category" },
  { name: 'SetContestCategoryStringVarForInterview', ret: "void", arity: 0, params: "void" },
  { name: 'ConvertIntToDecimalString', ret: "void", arity: 2, params: "u8 varIdx, int value" },
  { name: 'CountDigits', ret: "size_t", arity: 1, params: "int value" },
  { name: 'SmartShopper_BufferPurchaseTotal', ret: "void", arity: 2, params: "u8 varIdx, TVShow *show" },
  { name: 'InterviewBefore', ret: "void", arity: 0, params: "void" },
  { name: 'IsPartyMonNicknamedOrNotEnglish', ret: "bool8", arity: 1, params: "u8 monIdx" },
  { name: 'IsLeadMonNicknamedOrNotEnglish', ret: "bool8", arity: 0, params: "void" },
  { name: 'GetRandomDifferentSpeciesAndNameSeenByPlayer', ret: "u16", arity: 2, params: "u8 varIdx, u16 excludedSpecies" },
  { name: 'GetRandomWordFromShow', ret: "void", arity: 1, params: "TVShow *show" },
  { name: 'GetRandomNameRaterStateFromName', ret: "u8", arity: 1, params: "TVShow *show" },
  { name: 'GetNicknameSubstring', ret: "void", arity: 6, params: "u8 varIdx, u8 whichPosition, u8 charParam, u16 whichString, u16 species, TVShow *show" },
  { name: 'IsTVShowAlreadyInQueue', ret: "bool8", arity: 0, params: "void" },
  { name: 'TryPutNameRaterShowOnTheAir', ret: "bool8", arity: 0, params: "void" },
  { name: 'ChangePokemonNickname', ret: "void", arity: 0, params: "void" },
  { name: 'ChangePokemonNickname_CB', ret: "void", arity: 0, params: "void" },
  { name: 'ChangeBoxPokemonNickname', ret: "void", arity: 0, params: "void" },
  { name: 'BufferMonNickname', ret: "void", arity: 0, params: "void" },
  { name: 'IsMonOTIDNotPlayers', ret: "void", arity: 0, params: "void" },
  { name: 'GetPlayerIDAsU32', ret: "u32", arity: 0, params: "void" },
  { name: 'CheckForPlayersHouseNews', ret: "u8", arity: 0, params: "void" },
  { name: 'GetMomOrDadStringForTVMessage', ret: "void", arity: 0, params: "void" },
  { name: 'StringCopy', ret: "else", arity: 2, params: "gStringVar1, gText_Dad" },
  { name: 'HideBattleTowerReporter', ret: "void", arity: 0, params: "void" },
  { name: 'ReceiveTvShowsData', ret: "void", arity: 3, params: "void *src, u32 size, u8 playersLinkId" },
  { name: 'DeactivateAllNormalTVShows', ret: "void", arity: 0, params: "void" },
  { name: 'ReceivePokeNewsData', ret: "void", arity: 3, params: "void *src, u32 size, u8 playersLinkId" },
  { name: 'TranslateShowNames', ret: "UNUSED", arity: 2, params: "TVShow *show, u32 language" },
  { name: 'SanitizeTVShowsForRuby', ret: "void", arity: 1, params: "TVShow *shows" },
  { name: 'GetStringLanguage', ret: "u8", arity: 1, params: "u8 *str" },
  { name: 'SanitizeTVShowLocationsForRuby', ret: "void", arity: 1, params: "TVShow *shows" },
  { name: 'DoTVShow', ret: "void", arity: 0, params: "void" },
  { name: 'DoTVShowInSearchOfTrainers', ret: "void", arity: 0, params: "void" },
  { name: 'SecretBaseSecrets_GetNumActionsTaken', ret: "u8", arity: 1, params: "TVShow *show" },
  { name: 'SecretBaseSecrets_GetStateByFlagNumber', ret: "u8", arity: 2, params: "TVShow *show, u8 flagId" },
  { name: 'ResetTVShowState', ret: "void", arity: 0, params: "void" },
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'rtc.h',
  'overworld.h',
  'random.h',
  'event_data.h',
  'fieldmap.h',
  'field_camera.h',
  'field_specials.h',
  'fldeff.h',
  'strings.h',
  'string_util.h',
  'international_string_util.h',
  'pokemon_storage_system.h',
  'field_message_box.h',
  'easy_chat.h',
  'battle.h',
  'battle_tower.h',
  'contest.h',
  'item.h',
  'link.h',
  'main.h',
  'event_scripts.h',
  'shop.h',
  'lilycove_lady.h',
  'pokedex.h',
  'event_object_movement.h',
  'text.h',
  'script_menu.h',
  'naming_screen.h',
  'malloc.h',
  'region_map.h',
  'decoration.h',
  'secret_base.h',
  'tv.h',
  'pokeball.h',
  'data.h',
  'constants/battle_frontier.h',
  'constants/contest.h',
  'constants/decorations.h',
  'constants/event_objects.h',
  'constants/items.h',
  'constants/layouts.h',
  'constants/lilycove_lady.h',
  'constants/metatile_behaviors.h',
  'constants/metatile_labels.h',
  'constants/moves.h',
  'constants/region_map_sections.h',
] as const;
