// AUTO-GENERATED from src/union_room.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/union_room.c
// Generated: 2026-04-26

// ─── Enums ───────────────────────────────────────────────────────────────────
export const ENUM_UR_0 = {
  UR_STATE_INIT: 0,
  UR_STATE_INIT_OBJECTS: 1,
  UR_STATE_INIT_LINK: 2,
  UR_STATE_CHECK_SELECTING_MON: 3,
  UR_STATE_MAIN: 4,
  UR_STATE_DO_SOMETHING_PROMPT: 5,
  UR_STATE_HANDLE_DO_SOMETHING_PROMPT_INPUT: 6,
  UR_STATE_DO_SOMETHING_PROMPT_2: 7,
  UR_STATE_PRINT_MSG: 8,
  UR_STATE_HANDLE_ACTIVITY_REQUEST: 9,
  UR_STATE_DECLINE_ACTIVITY_REQUEST: 10,
  UR_STATE_PLAYER_CONTACTED_YOU: 11,
  UR_STATE_RECV_CONTACT_DATA: 12,
  UR_STATE_PRINT_START_ACTIVITY_MSG: 13,
  UR_STATE_START_ACTIVITY_LINK: 14,
  UR_STATE_START_ACTIVITY_WAIT_FOR_LINK: 15,
  UR_STATE_START_ACTIVITY_FREE_UROOM: 16,
  UR_STATE_START_ACTIVITY_FADE: 17,
  UR_STATE_START_ACTIVITY: 18,
  UR_STATE_RECV_JOIN_CHAT_REQUEST: 19,
  UR_STATE_TRY_ACCEPT_CHAT_REQUEST_DELAY: 20,
  UR_STATE_TRY_ACCEPT_CHAT_REQUEST: 21,
  UR_STATE_ACCEPT_CHAT_REQUEST: 22,
  UR_STATE_WAIT_FOR_START_MENU: 23,
  UR_STATE_INTERACT_WITH_PLAYER: 24,
  UR_STATE_TRY_COMMUNICATING: 25,
  UR_STATE_PRINT_AND_EXIT: 26,
  UR_STATE_SEND_ACTIVITY_REQUEST: 27,
  UR_STATE_TRAINER_APPEARS_BUSY: 28,
  UR_STATE_WAIT_FOR_RESPONSE_TO_REQUEST: 29,
  UR_STATE_CANCEL_ACTIVITY_LINK_ERROR: 30,
  UR_STATE_SEND_TRADE_REQUST: 31,
  UR_STATE_REQUEST_DECLINED: 32,
  UR_STATE_PRINT_CONTACT_MSG: 33,
  UR_STATE_HANDLE_CONTACT_DATA: 34,
  UR_STATE_RECV_ACTIVITY_REQUEST: 35,
  UR_STATE_CANCEL_REQUEST_PRINT_MSG: 36,
  UR_STATE_CANCEL_REQUEST_RESTART_LINK: 37,
  UR_STATE_COMMUNICATING_WAIT_FOR_DATA: 38,
  UR_STATE_WAIT_FOR_CONTACT_DATA: 39,
  UR_STATE_PRINT_CARD_INFO: 40,
  UR_STATE_WAIT_FINISH_READING_CARD: 41,
  UR_STATE_INTERACT_WITH_ATTENDANT: 42,
  UR_STATE_REGISTER_PROMPT: 43,
  UR_STATE_CANCEL_REGISTRATION_PROMPT: 44,
  UR_STATE_CHECK_TRADING_BOARD: 45,
  UR_STATE_TRADING_BOARD_LOAD: 46,
  UR_STATE_REGISTER_PROMPT_HANDLE_INPUT: 47,
  UR_STATE_TRADING_BOARD_HANDLE_INPUT: 48,
  UR_STATE_TRADE_PROMPT: 49,
  UR_STATE_TRADE_SELECT_MON: 50,
  UR_STATE_TRADE_OFFER_MON: 51,
  UR_STATE_REGISTER_REQUEST_TYPE: 52,
  UR_STATE_REGISTER_SELECT_MON_FADE: 53,
  UR_STATE_REGISTER_SELECT_MON: 54,
  UR_STATE_REGISTER_COMPLETE: 55,
  UR_STATE_CANCEL_REGISTRATION: 56,
} as const;
export const ENUM_URTRADE_1 = {
  URTRADE_STATE_NONE: 0,
  URTRADE_STATE_REGISTERING: 1,
  URTRADE_STATE_OFFERING: 2,
} as const;
export const ENUM_LL_2 = {
  LL_STATE_INIT: 0,
  LL_STATE_INIT2: 3,
  LL_STATE_GET_AWAITING_PLAYERS_TEXT: 4,
  LL_STATE_PRINT_AWAITING_PLAYERS: 5,
  LL_STATE_AWAIT_PLAYERS: 6,
  LL_STATE_ACCEPT_NEW_MEMBER_PROMPT: 7,
  LL_STATE_WAIT_DISCONNECT_CHILD: 9,
  LL_STATE_MEMBER_LEFT: 10,
  LL_STATE_ACCEPT_NEW_MEMBER_PROMPT_HANDLE_INPUT: 11,
  LL_STATE_UPDATE_AFTER_JOIN_REQUEST: 12,
  LL_STATE_ACCEPTED_FINAL_MEMBER: 13,
  LL_STATE_WAIT_AND_CONFIRM_MEMBERS: 14,
  LL_STATE_MEMBERS_OK_PROMPT: 15,
  LL_STATE_MEMBERS_OK_PROMPT_HANDLE_INPUT: 16,
  LL_STATE_CONFIRMED_MEMBERS: 17,
  LL_STATE_FINAL_MEMBER_CHECK: 18,
  LL_STATE_CANCEL_PROMPT: 19,
  LL_STATE_CANCEL_PROMPT_HANDLE_INPUT: 20,
  LL_STATE_SHUTDOWN_AND_RETRY: 21,
  LL_STATE_RETRY: 22,
  LL_STATE_SHUTDOWN_AND_FAIL: 23,
  LL_STATE_FAILED: 24,
  LL_STATE_TRY_START_ACTIVITY: 26,
  LL_STATE_MEMBER_DISCONNECTED: 29,
  LL_STATE_CANCEL_WITH_MSG: 30,
} as const;
export const ENUM_LG_3 = {
  LG_STATE_INIT: 0,
  LG_STATE_CHOOSE_LEADER_MSG: 1,
  LG_STATE_INIT_WINDOWS: 2,
  LG_STATE_CHOOSE_LEADER_HANDLE_INPUT: 3,
  LG_STATE_ASK_JOIN_GROUP: 5,
  LG_STATE_MAIN: 6,
  LG_STATE_ASK_LEAVE_GROUP: 7,
  LG_STATE_ASK_LEAVE_GROUP_HANDLE_INPUT: 8,
  LG_STATE_WAIT_LEAVE_GROUP: 9,
  LG_STATE_CANCEL_CHOOSE_LEADER: 10,
  LG_STATE_CANCELED: 11,
  LG_STATE_RFU_ERROR: 12,
  LG_STATE_RFU_ERROR_SHUTDOWN: 13,
  LG_STATE_DISCONNECTED: 14,
  LG_STATE_RETRY_CONNECTION: 15,
  LG_STATE_TRADE_NOT_READY: 18,
  LG_STATE_TRADE_NOT_READY_RETRY: 19,
  LG_STATE_READY_START_ACTIVITY: 20,
  LG_STATE_START_ACTIVITY: 21,
  LG_STATE_SHUTDOWN: 23,
} as const;
export const ENUM_UR_4 = {
  UR_COLOR_DEFAULT: 0,
  UR_COLOR_RED: 1,
  UR_COLOR_GREEN: 2,
  UR_COLOR_WHITE: 3,
  UR_COLOR_CANCEL: 4,
  UR_COLOR_TRADE_BOARD_SELF: 5,
  UR_COLOR_TRADE_BOARD_OTHER: 6,
} as const;
export const ENUM_PLIST_5 = {
  PLIST_NONE: 0,
  PLIST_NEW_PLAYER: 1,
  PLIST_RECENT_UPDATE: 2,
  PLIST_UNUSED: 3,
  PLIST_CONTACTED: 4,
} as const;

// ─── EWRAM/IWRAM/COMMON_DATA globals (initial values) ──────────────────────
export const SEGMENT_VARS = [
  { segment: 'EWRAM_DATA', type: "u8", name: 'sUnionRoomPlayerName', isArray: true, init: "{}" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'gPlayerCurrActivity', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'sPlayerActivityGroupSize', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u32", name: 'sUnused', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "struct RfuGameCompatibilityData", name: 'gRfuPartnerCompatibilityData', isArray: false, init: "{}" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'gUnionRoomOfferedSpecies', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'gUnionRoomRequestedMonType', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "struct UnionRoomTrade", name: 'sUnionRoomTrade', isArray: false, init: "{}" },
] as const;

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'PrintUnionRoomText', ret: "void", arity: 6, params: "u8, u8, const u8 *, u8, u8, u8" },
  { name: 'ReadAsU16', ret: "u16", arity: 1, params: "const u8 *" },
  { name: 'Task_TryBecomeLinkLeader', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_TryJoinLinkGroup', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_ListenToWireless', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_SendMysteryGift', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_CardOrNewsWithFriend', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_CardOrNewsOverWireless', ret: "void", arity: 1, params: "u8" },
  { name: 'Task_RunUnionRoom', ret: "void", arity: 1, params: "u8" },
  { name: 'ClearIncomingPlayerList', ret: "void", arity: 2, params: "struct RfuIncomingPlayerList *, u8" },
  { name: 'ClearRfuPlayerList', ret: "void", arity: 2, params: "struct RfuPlayer *, u8" },
  { name: 'CreateTask_ListenForCompatiblePartners', ret: "u8", arity: 2, params: "struct RfuIncomingPlayerList *, u32" },
  { name: 'CreateTask_ListenForWonderDistributor', ret: "u8", arity: 2, params: "struct RfuIncomingPlayerList *, u32" },
  { name: 'PrintOnTextbox', ret: "bool8", arity: 2, params: "u8 *, const u8 *" },
  { name: 'Leader_SetStateIfMemberListChanged', ret: "bool8", arity: 3, params: "struct WirelessLink_Leader *, u32, u32" },
  { name: 'LeaderPrunePlayerList', ret: "u8", arity: 1, params: "struct RfuPlayerList *" },
  { name: 'UnionRoomHandleYesNo', ret: "s8", arity: 2, params: "u8 *, bool32" },
  { name: 'CopyAndTranslatePlayerName', ret: "void", arity: 2, params: "u8 *, struct RfuPlayer *" },
  { name: 'Leader_DestroyResources', ret: "void", arity: 1, params: "struct WirelessLink_Leader *" },
  { name: 'CreateTask_RunScriptAndFadeToActivity', ret: "void", arity: 0, params: "void" },
  { name: 'LeaderUpdateGroupMembership', ret: "u8", arity: 1, params: "struct RfuPlayerList *" },
  { name: 'PrintGroupCandidateOnWindow', ret: "void", arity: 6, params: "u8, u8, u8, struct RfuPlayer *, u8, u8" },
  { name: 'GetNewIncomingPlayerId', ret: "u32", arity: 2, params: "struct RfuPlayer *, struct RfuIncomingPlayer *" },
  { name: 'TryAddIncomingPlayerToList', ret: "u8", arity: 3, params: "struct RfuPlayer *, struct RfuIncomingPlayer *, u8" },
  { name: 'GetNewLeaderCandidate', ret: "u8", arity: 0, params: "void" },
  { name: 'IsTryingToTradeAcrossVersionTooSoon', ret: "u32", arity: 2, params: "struct WirelessLink_Group *, s32" },
  { name: 'AskToJoinRfuGroup', ret: "void", arity: 2, params: "struct WirelessLink_Group *, s32" },
  { name: 'JoinGroup_EnableScriptContexts', ret: "void", arity: 0, params: "void" },
  { name: 'PrintGroupMemberOnWindow', ret: "void", arity: 6, params: "u8, u8, u8, struct RfuPlayer *, u8, u8" },
  { name: 'ArePlayerDataDifferent', ret: "bool32", arity: 2, params: "struct RfuPlayerData *, struct RfuPlayerData *" },
  { name: 'GetPartyPositionOfRegisteredMon', ret: "u32", arity: 2, params: "struct UnionRoomTrade *, u8" },
  { name: 'ResetUnionRoomTrade', ret: "void", arity: 1, params: "struct UnionRoomTrade *" },
  { name: 'CreateTask_StartActivity', ret: "void", arity: 0, params: "void" },
  { name: 'HasWonderCardOrNewsByLinkGroup', ret: "bool32", arity: 2, params: "struct RfuGameData *, s16" },
  { name: 'CreateTask_SearchForChildOrParent', ret: "u8", arity: 3, params: "struct RfuIncomingPlayerList *, struct RfuIncomingPlayerList *, u32" },
  { name: 'RegisterTradeMonAndGetIsEgg', ret: "bool32", arity: 2, params: "u32, struct UnionRoomTrade *" },
  { name: 'RegisterTradeMon', ret: "void", arity: 2, params: "u32, struct UnionRoomTrade *" },
  { name: 'StartScriptInteraction', ret: "void", arity: 0, params: "void" },
  { name: 'IsPlayerFacingTradingBoard', ret: "bool32", arity: 0, params: "void" },
  { name: 'HandlePlayerListUpdate', ret: "u8", arity: 0, params: "void" },
  { name: 'PollPartnerYesNoResponse', ret: "bool32", arity: 1, params: "struct WirelessLink_URoom *" },
  { name: 'ReceiveUnionRoomActivityPacket', ret: "void", arity: 1, params: "struct WirelessLink_URoom *" },
  { name: 'GetActivePartnersInfo', ret: "u8", arity: 1, params: "struct WirelessLink_URoom *" },
  { name: 'HandleContactFromOtherPlayer', ret: "bool32", arity: 1, params: "struct WirelessLink_URoom *" },
  { name: 'UR_RunTextPrinters', ret: "bool32", arity: 0, params: "void" },
  { name: 'GetUnionRoomPlayerGender', ret: "s32", arity: 2, params: "s32, struct RfuPlayerList *" },
  { name: 'UnionRoomGetPlayerInteractionResponse', ret: "s32", arity: 4, params: "struct RfuPlayerList *, u8, u8, u32" },
  { name: 'HandleCancelActivity', ret: "void", arity: 1, params: "bool32" },
  { name: 'ListMenuHandler_AllItemsAvailable', ret: "s32", arity: 5, params: "u8 *, u8 *, u8 *, const struct WindowTemplate *, const struct ListMenuTemplate *" },
  { name: 'TradeBoardMenuHandler', ret: "s32", arity: 7, params: "u8 *, u8 *, u8 *, u8 *, const struct WindowTemplate *, const struct ListMenuTemplate *, struct RfuPlayerList *" },
  { name: 'GetIndexOfNthTradeBoardOffer', ret: "s32", arity: 2, params: "struct RfuPlayer *, s32" },
  { name: 'HasAtLeastTwoMonsOfLevel30OrLower', ret: "bool32", arity: 0, params: "void" },
  { name: 'GetResponseIdx_InviteToURoomActivity', ret: "u32", arity: 1, params: "s32" },
  { name: 'ViewURoomPartnerTrainerCard', ret: "void", arity: 3, params: "u8 *, struct WirelessLink_URoom *, bool8" },
  { name: 'GetURoomActivityRejectMsg', ret: "void", arity: 3, params: "u8 *, s32, u32" },
  { name: 'ConvPartnerUnameAndGetWhetherMetAlready', ret: "u32", arity: 1, params: "struct RfuPlayer *" },
  { name: 'GetURoomActivityStartMsg', ret: "void", arity: 2, params: "u8 *, u8" },
  { name: 'UR_ClearBg0', ret: "void", arity: 0, params: "void" },
  { name: 'IsRequestedTradeInPlayerParty', ret: "s32", arity: 2, params: "u32, u32" },
  { name: 'UR_PrintFieldMessage', ret: "bool32", arity: 1, params: "const u8 *" },
  { name: 'GetChatLeaderActionRequestMessage', ret: "s32", arity: 4, params: "u8 *, u32, u16 *, struct WirelessLink_URoom *" },
  { name: 'Task_InitUnionRoom', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'ArePlayersDifferent', ret: "bool8", arity: 2, params: "struct RfuPlayerData *, const struct RfuPlayerData *" },
  { name: 'ItemPrintFunc_PossibleGroupMembers', ret: "void", arity: 3, params: "u8, u32, u8" },
  { name: 'ListMenuItemPrintFunc_UnionRoomGroups', ret: "void", arity: 3, params: "u8, u32, u8" },
  { name: 'TradeBoardListMenuItemPrintFunc', ret: "void", arity: 3, params: "u8, u32, u8" },
  { name: 'ItemPrintFunc_EmptyList', ret: "void", arity: 3, params: "u8, u32, u8" },
  { name: 'PrintNumPlayersWaitingForMsg', ret: "void", arity: 3, params: "u8 windowId, u8 capacityCode, u8 stringId" },
  { name: 'PrintPlayerNameAndIdOnWindow', ret: "void", arity: 1, params: "u8 windowId" },
  { name: 'GetAwaitingCommunicationText', ret: "void", arity: 2, params: "u8 *dst, u8 activity" },
  { name: 'IsActivityWithVariableGroupSize', ret: "bool32", arity: 1, params: "u32 activity" },
  { name: 'TryBecomeLinkLeader', ret: "void", arity: 0, params: "void" },
  { name: 'StringExpandPlaceholders', ret: "else", arity: 2, params: "gStringVar4, sText_AwaitingCommunication" },
  { name: 'Leader_GetAcceptNewMemberPrompt', ret: "void", arity: 2, params: "u8 *dst, u8 activity" },
  { name: 'GetYouDeclinedTheOfferMessage', ret: "void", arity: 2, params: "u8 *dst, u8 activity" },
  { name: 'GetYouAskedToJoinGroupPleaseWaitMessage', ret: "void", arity: 2, params: "u8 *dst, u8 activity" },
  { name: 'GetGroupLeaderSentAnOKMessage', ret: "void", arity: 2, params: "u8 *dst, u8 activity" },
  { name: 'TryJoinLinkGroup', ret: "void", arity: 0, params: "void" },
  { name: 'CreateTask_ListenToWireless', ret: "u8", arity: 0, params: "void" },
  { name: 'IsPartnerActivityAcceptable', ret: "bool32", arity: 2, params: "u32 activity, u32 linkGroup" },
  { name: 'GetGroupListTextColor', ret: "u8", arity: 2, params: "struct WirelessLink_Group *data, u32 id" },
  { name: 'Task_CreateTradeMenu', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'CreateTask_CreateTradeMenu', ret: "u8", arity: 0, params: "void" },
  { name: 'Task_StartUnionRoomTrade', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'Task_ExchangeCards', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'CB2_ShowCard', ret: "void", arity: 0, params: "void" },
  { name: 'StartUnionRoomBattle', ret: "void", arity: 1, params: "u16 battleFlags" },
  { name: 'WarpForWirelessMinigame', ret: "void", arity: 3, params: "u16 linkService, u16 x, u16 y" },
  { name: 'WarpForCableClubActivity', ret: "void", arity: 5, params: "s8 mapGroup, s8 mapNum, s32 x, s32 y, u16 linkService" },
  { name: 'CB2_TransitionToCableClub', ret: "void", arity: 0, params: "void" },
  { name: 'CreateTrainerCardInBuffer', ret: "void", arity: 2, params: "void *dest, bool32 setWonderCard" },
  { name: 'Task_StartActivity', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'Task_RunScriptAndFadeToActivity', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'CreateTask_SendMysteryGift', ret: "void", arity: 1, params: "u32 activity" },
  { name: 'CreateTask_LinkMysteryGiftWithFriend', ret: "void", arity: 1, params: "u32 activity" },
  { name: 'CreateTask_LinkMysteryGiftOverWireless', ret: "void", arity: 1, params: "u32 activity" },
  { name: 'RunUnionRoom', ret: "void", arity: 0, params: "void" },
  { name: 'ScheduleFieldMessageWithFollowupState', ret: "void", arity: 2, params: "u32 nextState, const u8 *src" },
  { name: 'ScheduleFieldMessageAndExit', ret: "void", arity: 1, params: "const u8 *src" },
  { name: 'CopyPlayerListToBuffer', ret: "void", arity: 1, params: "struct WirelessLink_URoom *uroom" },
  { name: 'CopyPlayerListFromBuffer', ret: "void", arity: 1, params: "struct WirelessLink_URoom *uroom" },
  { name: 'SetUsingUnionRoomStartMenu', ret: "void", arity: 0, params: "void" },
  { name: 'InitUnionRoom', ret: "void", arity: 0, params: "void" },
  { name: 'BufferUnionRoomPlayerName', ret: "bool16", arity: 0, params: "void" },
  { name: 'Task_SearchForChildOrParent', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'Task_ListenForCompatiblePartners', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'Task_ListenForWonderDistributor', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'CreateTradeBoardWindow', ret: "u8", arity: 1, params: "const struct WindowTemplate *template" },
  { name: 'DeleteTradeBoardWindow', ret: "void", arity: 1, params: "u8 windowId" },
  { name: 'TradeBoardPrintItemInfo', ret: "void", arity: 5, params: "u8 windowId, u8 y, struct RfuGameData *data, const u8 *playerName, u8 colorIdx" },
  { name: 'InUnionRoom', ret: "bool32", arity: 0, params: "void" },
  { name: 'Script_ResetUnionRoomTrade', ret: "void", arity: 0, params: "void" },
] as const;

// ─── Task_* (state machine entry points) ────────────────────────────────────
export const TASK_NAMES = [
  'Task_CardOrNewsOverWireless',
  'Task_CardOrNewsWithFriend',
  'Task_CreateTradeMenu',
  'Task_ExchangeCards',
  'Task_InitUnionRoom',
  'Task_ListenForCompatiblePartners',
  'Task_ListenForWonderDistributor',
  'Task_ListenToWireless',
  'Task_RunScriptAndFadeToActivity',
  'Task_RunUnionRoom',
  'Task_SearchForChildOrParent',
  'Task_SendMysteryGift',
  'Task_StartActivity',
  'Task_StartUnionRoomTrade',
  'Task_TryBecomeLinkLeader',
  'Task_TryJoinLinkGroup',
] as const;

// ─── CB2_* (callback / scene entry points) ──────────────────────────────────
export const CB2_NAMES = [
  'CB2_ShowCard',
  'CB2_TransitionToCableClub',
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'malloc.h',
  'battle.h',
  'berry_crush.h',
  'bg.h',
  'cable_club.h',
  'data.h',
  'decompress.h',
  'dodrio_berry_picking.h',
  'dynamic_placeholder_text_util.h',
  'easy_chat.h',
  'event_data.h',
  'event_object_lock.h',
  'fieldmap.h',
  'field_control_avatar.h',
  'field_player_avatar.h',
  'field_screen_effect.h',
  'field_weather.h',
  'international_string_util.h',
  'librfu.h',
  'link.h',
  'link_rfu.h',
  'list_menu.h',
  'load_save.h',
  'menu.h',
  'menu_helpers.h',
  'mystery_gift.h',
  'mystery_gift_menu.h',
  'overworld.h',
  'palette.h',
  'party_menu.h',
  'pokemon_jump.h',
  'random.h',
  'save_location.h',
  'script.h',
  'script_pokemon_util.h',
  'sound.h',
  'start_menu.h',
  'string_util.h',
  'strings.h',
  'task.h',
  'trade.h',
  'trainer_card.h',
  'union_room.h',
  'union_room_battle.h',
  'union_room_chat.h',
  'union_room_player_avatar.h',
  'window.h',
  'constants/battle_frontier.h',
  'constants/cable_club.h',
  'constants/game_stat.h',
  'constants/party_menu.h',
  'constants/rgb.h',
  'constants/songs.h',
  'data/union_room.h',
] as const;
