// AUTO-GENERATED from src/battle_controller_recorded_opponent.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/battle_controller_recorded_opponent.c
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
/** Raw expr: `data[0]` */
export const sSpeedX_EXPR = "data[0]";

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'RecordedOpponentHandleGetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleGetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleSetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleSetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleLoadMonSprite', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleSwitchInAnim', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleReturnMonToBall', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleDrawTrainerPic', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleTrainerSlide', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleTrainerSlideBack', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleFaintAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandlePaletteFade', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleSuccessBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandlePause', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleMoveAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandlePrintString', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandlePrintSelectionString', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleChooseAction', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleYesNoBox', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleChooseMove', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleChooseItem', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleChoosePokemon', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleCmd23', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleHealthBarUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleExpUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleStatusIconUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleStatusAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleStatusXor', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleDataTransfer', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleDMA3Transfer', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandlePlayBGM', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleCmd32', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleTwoReturnValues', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleChosenMonReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleOneReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleOneReturnValue_Duplicate', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleClearUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleSetUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleClearUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleToggleUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleHitAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleCantSwitch', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandlePlaySE', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandlePlayFanfareOrBGM', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleFaintingCry', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleIntroSlide', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleIntroTrainerBallThrow', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleDrawPartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleHidePartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleEndBounceEffect', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleSpriteInvisibility', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleBattleAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleLinkStandbyMsg', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleResetActionMoveSelection', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentHandleEndLinkBattle', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentCmdEnd', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentBufferRunCommand', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentBufferExecCompleted', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_HandleSoundAndEnd', ret: "void", arity: 0, params: "void" },
  { name: 'CopyRecordedOpponentMonData', ret: "u32", arity: 2, params: "u8 monId, u8 *dst" },
  { name: 'SetRecordedOpponentMonData', ret: "void", arity: 1, params: "u8 monId" },
  { name: 'StartSendOutAnim', ret: "void", arity: 2, params: "u8 battler, bool8 dontClearSubstituteBit" },
  { name: 'DoSwitchOutAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentDoMoveAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'Task_StartSendOutAnim', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'SpriteCB_FreeOpponentSprite', ret: "void", arity: 1, params: "struct Sprite *sprite" },
  { name: 'EndDrawPartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedOpponentDummy', ret: "void", arity: 0, params: "void" },
  { name: 'SetControllerToRecordedOpponent', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnBattlerSpriteCallbackDummy', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnBankSpriteCallbackDummy2', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'FreeTrainerSpriteAfterSlide', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_DelayAndEnd', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_WaitForShinyAnimAndHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_TryShinyAnimShowHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'TryShinyAnimAfterMonAnim', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnHealthbarDone', ret: "void", arity: 0, params: "void" },
  { name: 'HideHealthboxAfterMonFaint', ret: "void", arity: 0, params: "void" },
  { name: 'FreeMonSpriteAfterSwitchOutAnim', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnInactiveTextPrinter', ret: "void", arity: 0, params: "void" },
  { name: 'DoHitAnimBlinkSpriteEffect', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_ShowSubstitute', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_ShowHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_TryShinyAnim', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedStatusAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedBattleAnimation', ret: "void", arity: 0, params: "void" },
] as const;

// ─── Task_* (state machine entry points) ────────────────────────────────────
export const TASK_NAMES = [
  'Task_StartSendOutAnim',
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'battle.h',
  'battle_ai_script_commands.h',
  'battle_anim.h',
  'battle_controllers.h',
  'battle_interface.h',
  'battle_message.h',
  'battle_setup.h',
  'battle_tower.h',
  'battle_tv.h',
  'bg.h',
  'data.h',
  'item_use.h',
  'link.h',
  'main.h',
  'm4a.h',
  'palette.h',
  'pokeball.h',
  'pokemon.h',
  'recorded_battle.h',
  'reshow_battle_screen.h',
  'sound.h',
  'string_util.h',
  'task.h',
  'text.h',
  'util.h',
  'window.h',
  'constants/battle_anim.h',
  'constants/songs.h',
  'constants/trainers.h',
] as const;
