// AUTO-GENERATED from src/battle_controller_recorded_player.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/battle_controller_recorded_player.c
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
/** Raw expr: `data[0]` */
export const sSpeedX_EXPR = "data[0]";
/** Raw expr: `data[2]` */
export const sSpeedY_EXPR = "data[2]";

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'RecordedPlayerHandleGetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleGetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleSetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleSetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleLoadMonSprite', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleSwitchInAnim', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleReturnMonToBall', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleDrawTrainerPic', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleTrainerSlide', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleTrainerSlideBack', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleFaintAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandlePaletteFade', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleSuccessBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandlePause', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleMoveAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandlePrintString', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandlePrintSelectionString', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleChooseAction', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleYesNoBox', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleChooseMove', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleChooseItem', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleChoosePokemon', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleCmd23', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleHealthBarUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleExpUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleStatusIconUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleStatusAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleStatusXor', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleDataTransfer', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleDMA3Transfer', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandlePlayBGM', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleCmd32', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleTwoReturnValues', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleChosenMonReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleOneReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleOneReturnValue_Duplicate', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleClearUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleSetUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleClearUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleToggleUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleHitAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleCantSwitch', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandlePlaySE', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandlePlayFanfareOrBGM', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleFaintingCry', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleIntroSlide', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleIntroTrainerBallThrow', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleDrawPartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleHidePartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleEndBounceEffect', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleSpriteInvisibility', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleBattleAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleLinkStandbyMsg', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleResetActionMoveSelection', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerHandleEndLinkBattle', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerCmdEnd', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerBufferRunCommand', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerBufferExecCompleted', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_WaitAndEnd', ret: "void", arity: 0, params: "void" },
  { name: 'CopyRecordedPlayerMonData', ret: "u32", arity: 2, params: "u8 monId, u8 *dst" },
  { name: 'SetRecordedPlayerMonData', ret: "void", arity: 1, params: "u8 monId" },
  { name: 'StartSendOutAnim', ret: "void", arity: 2, params: "u8 battler, bool8 dontClearSubstituteBit" },
  { name: 'DoSwitchOutAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerDoMoveAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'Task_StartSendOutAnim', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'EndDrawPartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'RecordedPlayerDummy', ret: "void", arity: 0, params: "void" },
  { name: 'SetControllerToRecordedPlayer', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnBattlerSpriteCallbackDummy', ret: "void", arity: 0, params: "void" },
  { name: 'FreeTrainerSpriteAfterSlide', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_DelayAndEnd', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_WaitForShinyAnimAndHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_TryShinyAnimShowHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'WaitForMonAnimAfterLoad', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnHealthbarDone', ret: "void", arity: 0, params: "void" },
  { name: 'FreeMonSpriteAfterFaintAnim', ret: "void", arity: 0, params: "void" },
  { name: 'FreeMonSpriteAfterSwitchOutAnim', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnInactiveTextPrinter', ret: "void", arity: 0, params: "void" },
  { name: 'DoHitAnimBlinkSpriteEffect', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_ShowSubstitute', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_ShowHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_TryShinyAnim', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedStatusAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedBattleAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'ChooseActionInBattlePalace', ret: "void", arity: 0, params: "void" },
] as const;

// ─── Task_* (state machine entry points) ────────────────────────────────────
export const TASK_NAMES = [
  'Task_StartSendOutAnim',
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'battle.h',
  'battle_ai_script_commands.h',
  'battle_anim.h',
  'battle_controllers.h',
  'battle_message.h',
  'battle_interface.h',
  'bg.h',
  'data.h',
  'item_use.h',
  'link.h',
  'main.h',
  'm4a.h',
  'palette.h',
  'pokeball.h',
  'pokemon.h',
  'recorded_battle.h',
  'reshow_battle_screen.h',
  'sound.h',
  'string_util.h',
  'task.h',
  'text.h',
  'util.h',
  'window.h',
  'constants/battle_anim.h',
  'constants/songs.h',
] as const;
