// AUTO-GENERATED by scripts/transpile-callbacks.mjs
// Source : src/battle_anim.c (via SPRITE_CALLBACKS / TASKS / SPRITE_CBS / CB2S)
// Generated : 2026-04-27
// DO NOT EDIT — re-run `node scripts/transpile-callbacks.mjs` to refresh.
//
// Symbol substitution rules in script header.
// Manual fixes may be needed for /* TODO */ markers and undefined constants below.

/* eslint-disable */
// @ts-nocheck

import type { DecompRuntime, DecompSprite, DecompTask } from '../../../decomp-runtime';
import {
  Sin, Cos, Q_8_8_TO_INT, SetOamMatrix, CalcCenterToCornerVec,
  ST_OAM_AFFINE_OFF, ST_OAM_AFFINE_NORMAL, ST_OAM_AFFINE_DOUBLE, ST_OAM_AFFINE_ERASE,
  ST_OAM_OBJ_NORMAL, ST_OAM_OBJ_BLEND, ST_OAM_OBJ_WINDOW,
  ST_OAM_4BPP, ST_OAM_8BPP,
  RGB, RGB_BLACK, RGB_WHITE, RGB_WHITEALPHA,
  PLTT_SIZEOF, PLTT_SIZE_4BPP, PLTT_SIZE_8BPP,
  OBJ_PLTT_ID_FADED, BG_PLTT_ID_FADED,
  BLDALPHA_BLEND, WIN_RANGE, GET_TRUE_SPRITE_INDEX, ANIM_SPRITES_START,
  gSineTable, PaletteBuffer,
} from '../../../decomp-helpers';
// Constants resolved from decomp #defines / enums / TS data modules :
const B_POSITION_OPPONENT_LEFT = 1;
const B_POSITION_PLAYER_RIGHT = 2;
const TASK_NONE = 255;
// Unresolved constants (auto-stub at 0; replace with real values when needed) :
const _UNDEFINED = 0;
const BATTLE_PARTNER: any = _UNDEFINED; // TODO : not found in decomp /include or auto/src — possibly dynamic

export type SpriteCallback = (sprite: DecompSprite, rt: DecompRuntime) => void;
export type TaskCallback = (task: DecompTask, rt: DecompRuntime) => void;
export type CB2Callback = (rt: DecompRuntime) => void;

const _emptySprite: any = { data: new Array(16).fill(0), invisible: false, x: 0, y: 0, x2: 0, y2: 0, oamIndex: 0, spriteId: -1 };
const _emptyTask: any = { data: new Array(16).fill(0), func: null, taskId: -1 };
function _gs(rt: DecompRuntime, id: number): DecompSprite { return (rt.gSprites.get(id) as DecompSprite) ?? _emptySprite; }
function _gt(rt: DecompRuntime, id: number): DecompTask { return (rt.gTasks.get(id) as DecompTask) ?? _emptyTask; }
function _palView(buf: PaletteBuffer, base: number): ArrayLike<number> {
  return new Proxy({ length: 512 }, { get(t, k) { if (k === 'length') return 512; const i = Number(k); return Number.isFinite(i) ? buf.get(base + i) : undefined; } }) as ArrayLike<number>;
}

/** Source: battle_anim.c → Task_InitUpdateMonBg */
export const Task_InitUpdateMonBg: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let updateTaskId = 0;

      const data = task.data;
      let battlerSpriteId = gBattlerSpriteIds[data[0]];
      _gs(rt, battlerSpriteId).invisible = true;

      if (!data[2])
      {
          DestroyAnimVisualTask(taskId);
          return;
      }

      updateTaskId = rt.CreateTask((t) => Task_UpdateMonBg(t, rt), 10);
      _gt(rt, updateTaskId).t2_SpriteId = battlerSpriteId;
      _gt(rt, updateTaskId).t2_SpriteX = _gs(rt, battlerSpriteId).x + _gs(rt, battlerSpriteId).x2;
      _gt(rt, updateTaskId).t2_SpriteY = _gs(rt, battlerSpriteId).y + _gs(rt, battlerSpriteId).y2;

      if (!data[1])
      {
          _gt(rt, updateTaskId).t2_BgX = gBattle_BG1_X;
          _gt(rt, updateTaskId).t2_BgY = gBattle_BG1_Y;
      }
      else
      {
          _gt(rt, updateTaskId).t2_BgX = gBattle_BG2_X;
          _gt(rt, updateTaskId).t2_BgY = gBattle_BG2_Y;
      }

      _gt(rt, updateTaskId).t2_InBg2 = data[1];
      _gt(rt, updateTaskId).t2_BattlerId = data[0];
      sMonAnimTaskIdArray[data[3]] = updateTaskId;
      DestroyAnimVisualTask(taskId);
};

/** Source: battle_anim.c → Task_UpdateMonBg */
export const Task_UpdateMonBg: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let spriteId, battler;
      let x, y;
      let animBg: any = null;

      spriteId = task.t2_SpriteId;
      battler = task.t2_BattlerId;
      GetBattleAnimBg1Data(animBg);
      x = task.t2_SpriteX - (_gs(rt, spriteId).x + _gs(rt, spriteId).x2);
      y = task.t2_SpriteY - (_gs(rt, spriteId).y + _gs(rt, spriteId).y2);

      if (!task.t2_InBg2)
      {
          gBattle_BG1_X = x + task.t2_BgX;
          gBattle_BG1_Y = y + task.t2_BgY;
          rt.CpuCopy16(_palView(rt.gPlttBufferFaded, (256 + (battler) * 16)), 0, ((animBg.paletteId) * 16), Math.floor((PLTT_SIZE_4BPP) / 2));
      }
      else
      {
          gBattle_BG2_X = x + task.t2_BgX;
          gBattle_BG2_Y = y + task.t2_BgY;
          rt.CpuCopy16(_palView(rt.gPlttBufferFaded, (256 + (battler) * 16)), 0, ((9) * 16), Math.floor((PLTT_SIZE_4BPP) / 2));
      }
};

/** Source: battle_anim.c → Task_ClearMonBg */
export const Task_ClearMonBg: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  task.data[1]++;
      if (task.data[1] != 1)
      {
          let to_BG2 = 0;
          let position = GetBattlerPosition(task.data[2]);
          if (position == B_POSITION_OPPONENT_LEFT || position == B_POSITION_PLAYER_RIGHT || IsContest())
              to_BG2 = false;
          else
              to_BG2 = true;

          if (sMonAnimTaskIdArray[0] != TASK_NONE)
          {
              ResetBattleAnimBg(to_BG2);
              rt.DestroyTask(sMonAnimTaskIdArray[0]);
              sMonAnimTaskIdArray[0] = TASK_NONE;
          }
          if (task.data[0] > 1)
          {
              ResetBattleAnimBg(to_BG2 ^ 1);
              rt.DestroyTask(sMonAnimTaskIdArray[1]);
              sMonAnimTaskIdArray[1] = TASK_NONE;
          }
          rt.DestroyTask(taskId);
      }
};

/** Source: battle_anim.c → Task_ClearMonBgStatic */
export const Task_ClearMonBgStatic: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  task.data[1]++;
      if (task.data[1] != 1)
      {
          let toBG_2 = 0;
          let battler = task.data[2];
          let position = GetBattlerPosition(battler);
          if (position == B_POSITION_OPPONENT_LEFT || position == B_POSITION_PLAYER_RIGHT || IsContest())
              toBG_2 = false;
          else
              toBG_2 = true;

          if (IsBattlerSpriteVisible(battler))
              ResetBattleAnimBg(toBG_2);
          if (task.data[0] > 1 && IsBattlerSpriteVisible(BATTLE_PARTNER(battler)))
              ResetBattleAnimBg(toBG_2 ^ 1);

          rt.DestroyTask(taskId);
      }
};

/** Source: battle_anim.c → Task_FadeToBg */
export const Task_FadeToBg: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (task.data[10] == 0)
      {
          BeginHardwarePaletteFade(0xE8, 0, 0, 16, 0);
          task.data[10]++;
          return;
      }
      if (rt.gPaletteFade.active)
          return;
      if (task.data[10] == 1)
      {
          task.data[10]++;
          sAnimBackgroundFadeState = 2;
      }
      else if (task.data[10] == 2)
      {
          let bgId = task.data[0];

          if (bgId == -1)
              LoadDefaultBg();
          else
              LoadMoveBg(bgId);

          BeginHardwarePaletteFade(0xE8, 0, 16, 0, 1);
          task.data[10]++;
          return;
      }
      if (rt.gPaletteFade.active)
          return;
      if (task.data[10] == 3)
      {
          rt.DestroyTask(taskId);
          sAnimBackgroundFadeState = 0;
      }
};

/** Source: battle_anim.c → Task_PanFromInitialToTarget */
export const Task_PanFromInitialToTarget: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let destroyTask = false;
      if (task.data[8]++ >= task.data[2])
      {
          let pan = 0;
          let initialPanning, targetPanning, currentPan, incrementPan;

          task.data[8] = 0;
          initialPanning = task.data[0];
          targetPanning = task.data[1];
          currentPan = task.data[4];
          incrementPan = task.data[2];
          pan = currentPan + incrementPan;
          task.data[4] = pan;

          if (incrementPan == 0)  
          {
              destroyTask = true;
          }
          else if (initialPanning < targetPanning)  
          {
              if (pan >= targetPanning)  
                  destroyTask = true;
          }
          else  
          {
              if (pan <= targetPanning)  
                  destroyTask = true;
          }

          if (destroyTask)
          {
              pan = targetPanning;
              rt.DestroyTask(taskId);
              gAnimSoundTaskCount--;
          }

          SE12PanpotControl(pan);
      }
};

/** Source: battle_anim.c → Task_LoopAndPlaySE */
export const Task_LoopAndPlaySE: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (task.data[8]++ >= task.data[2])
      {
          let songId = 0;
          let panning = 0;
          let numberOfPlays = 0;

          task.data[8] = 0;
          songId = task.data[0];
          panning = task.data[1];
          numberOfPlays = --task.data[3];
          PlaySE12WithPanning(songId, panning);
          if (numberOfPlays == 0)
          {
              rt.DestroyTask(taskId);
              gAnimSoundTaskCount--;
          }
      }
};

/** Source: battle_anim.c → Task_WaitAndPlaySE */
export const Task_WaitAndPlaySE: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (task.data[2]-- <= 0)
      {
          PlaySE12WithPanning(task.data[0], task.data[1]);
          rt.DestroyTask(taskId);
          gAnimSoundTaskCount--;
      }
};
