// AUTO-GENERATED from src/battle_controller_safari.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/battle_controller_safari.c
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
/** Raw expr: `data[0]` */
export const sSpeedX_EXPR = "data[0]";

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'SafariHandleGetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleGetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleSetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleSetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleLoadMonSprite', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleSwitchInAnim', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleReturnMonToBall', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleDrawTrainerPic', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleTrainerSlide', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleTrainerSlideBack', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleFaintAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandlePaletteFade', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleSuccessBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandlePause', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleMoveAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandlePrintString', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandlePrintSelectionString', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleChooseAction', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleYesNoBox', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleChooseMove', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleChooseItem', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleChoosePokemon', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleCmd23', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleHealthBarUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleExpUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleStatusIconUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleStatusAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleStatusXor', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleDataTransfer', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleDMA3Transfer', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandlePlayBGM', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleCmd32', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleTwoReturnValues', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleChosenMonReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleOneReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleOneReturnValue_Duplicate', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleClearUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleSetUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleClearUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleToggleUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleHitAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleCantSwitch', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandlePlaySE', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandlePlayFanfareOrBGM', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleFaintingCry', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleIntroSlide', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleIntroTrainerBallThrow', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleDrawPartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleHidePartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleEndBounceEffect', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleSpriteInvisibility', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleBattleAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleLinkStandbyMsg', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleResetActionMoveSelection', ret: "void", arity: 0, params: "void" },
  { name: 'SafariHandleEndLinkBattle', ret: "void", arity: 0, params: "void" },
  { name: 'SafariCmdEnd', ret: "void", arity: 0, params: "void" },
  { name: 'SafariBufferRunCommand', ret: "void", arity: 0, params: "void" },
  { name: 'SafariBufferExecCompleted', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteWhenChosePokeblock', ret: "void", arity: 0, params: "void" },
  { name: 'SpriteCB_Null4', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'SetControllerToSafari', ret: "void", arity: 0, params: "void" },
  { name: 'HandleInputChooseAction', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnBattlerSpriteCallbackDummy', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnInactiveTextPrinter', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnHealthboxSpriteCallbackDummy', ret: "void", arity: 0, params: "void" },
  { name: 'SafariSetBattleEndCallbacks', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnSpecialAnimDone', ret: "void", arity: 0, params: "void" },
  { name: 'SafariOpenPokeblockCase', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedBattleAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedStatusAnimation', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'HandleChooseActionAfterDma3', ret: "void", arity: 0, params: "void" },
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'battle.h',
  'battle_anim.h',
  'battle_controllers.h',
  'battle_interface.h',
  'battle_message.h',
  'bg.h',
  'data.h',
  'item_menu.h',
  'link.h',
  'main.h',
  'm4a.h',
  'palette.h',
  'pokeball.h',
  'pokeblock.h',
  'pokemon.h',
  'reshow_battle_screen.h',
  'sound.h',
  'task.h',
  'text.h',
  'util.h',
  'window.h',
  'constants/battle_anim.h',
  'constants/songs.h',
  'constants/rgb.h',
] as const;
