// AUTO-GENERATED from src/battle_script_commands.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/battle_script_commands.c
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
/** Raw expr: `((gProtectStructs[gBattlerTarget].protected) && (gBattleMoves[gCurrentMove].flags & FLAG_PROTECT_AFFECTED))` */
export const DEFENDER_IS_PROTECTED_EXPR = "((gProtectStructs[gBattlerTarget].protected) && (gBattleMoves[gCurrentMove].flags & FLAG_PROTECT_AFFECTED))";
export const LEVEL_UP_BANNER_START = 416;
export const LEVEL_UP_BANNER_END = 512;
export const TAG_LVLUP_BANNER_MON_ICON = 55130;
export const MIMIC_FORBIDDEN_END = 65534;
export const METRONOME_FORBIDDEN_END = 65535;
export const ASSIST_FORBIDDEN_END = 65535;
/** Raw expr: `\` */
export const INCREMENT_RESET_RETURN_EXPR = "\\";
/** Raw expr: `\` */
export const RESET_RETURN_EXPR = "\\";
/** Raw expr: `data[0]` */
export const sDestroy_EXPR = "data[0]";
/** Raw expr: `data[1]` */
export const sXOffset_EXPR = "data[1]";
export const STAT_CHANGE_WORKED = 0;
export const STAT_CHANGE_DIDNT_WORK = 1;

// ─── WindowTemplate ─────────────────────────────────────────────────────────────
export const sUnusedWinTemplate = { bg: 0, tilemapLeft: 1, tilemapTop: 3, width: 7, height: 15, paletteNum: 31, baseBlock: 63 } as const;

// ─── OamData ─────────────────────────────────────────────────────────────
export const sOamData_MonIconOnLvlUpBanner = { y: 0, affineMode: "ST_OAM_AFFINE_OFF", objMode: "ST_OAM_OBJ_NORMAL", mosaic: 0, bpp: "ST_OAM_4BPP", shape: "SPRITE_SHAPE(32x32)", x: 0, matrixNum: 0, size: "SPRITE_SIZE(32x32)", tileNum: 0, priority: 0, paletteNum: 0, affineParam: 0 } as const;

// ─── SpriteTemplate ─────────────────────────────────────────────────────────────
export const sSpriteTemplate_MonIconOnLvlUpBanner = { tileTag: "TAG_LVLUP_BANNER_MON_ICON", paletteTag: "TAG_LVLUP_BANNER_MON_ICON", oam: "&sOamData_MonIconOnLvlUpBanner", anims: "gDummySpriteAnimTable", images: 0, affineAnims: "gDummySpriteAffineAnimTable", callback: "SpriteCB_MonIconOnLvlUpBanner" } as const;

// ─── GFX/PAL paths (INCGFX) ─────────────────────────────────────────────────
export const GFX_SOURCES: Record<string, { path: string; ext: string; type: string }> = {
  'sLevelUpBanner_Pal': { path: 'graphics/battle_interface/level_up_banner.png', ext: '.gbapal', type: 'u16' },
  'sLevelUpBanner_Gfx': { path: 'graphics/battle_interface/level_up_banner.png', ext: '.4bpp.lz', type: 'u32' },
};

// ─── Numeric arrays (raw data tables) ───────────────────────────────────────
export const sCriticalHitChance: readonly number[] = [16,8,4,3,2] as const;
export const sFlailHpScaleToPowerTable: readonly number[] = [1,200,4,150,9,100,16,80,32,40,48,20] as const;
export const sWeightToDamageTable: readonly number[] = [100,20,250,40,500,60,1000,80,2000,100,65535,65535] as const;
export const sPickupProbabilities: readonly number[] = [30,40,50,60,70,80,90,94,98] as const;

// ─── Function pointer tables (opcode dispatch) ──────────────────────────────
export const gBattleScriptingCommandsTable = ['Cmd_attackcanceler', 'Cmd_accuracycheck', 'Cmd_attackstring', 'Cmd_ppreduce', 'Cmd_critcalc', 'Cmd_damagecalc', 'Cmd_typecalc', 'Cmd_adjustnormaldamage', 'Cmd_adjustnormaldamage2', 'Cmd_attackanimation', 'Cmd_waitanimation', 'Cmd_healthbarupdate', 'Cmd_datahpupdate', 'Cmd_critmessage', 'Cmd_effectivenesssound', 'Cmd_resultmessage', 'Cmd_printstring', 'Cmd_printselectionstring', 'Cmd_waitmessage', 'Cmd_printfromtable', 'Cmd_printselectionstringfromtable', 'Cmd_seteffectwithchance', 'Cmd_seteffectprimary', 'Cmd_seteffectsecondary', 'Cmd_clearstatusfromeffect', 'Cmd_tryfaintmon', 'Cmd_dofaintanimation', 'Cmd_cleareffectsonfaint', 'Cmd_jumpifstatus', 'Cmd_jumpifstatus2', 'Cmd_jumpifability', 'Cmd_jumpifsideaffecting', 'Cmd_jumpifstat', 'Cmd_jumpifstatus3condition', 'Cmd_jumpiftype', 'Cmd_getexp', 'Cmd_checkteamslost', 'Cmd_movevaluescleanup', 'Cmd_setmultihit', 'Cmd_decrementmultihit', 'Cmd_goto', 'Cmd_jumpifbyte', 'Cmd_jumpifhalfword', 'Cmd_jumpifword', 'Cmd_jumpifarrayequal', 'Cmd_jumpifarraynotequal', 'Cmd_setbyte', 'Cmd_addbyte', 'Cmd_subbyte', 'Cmd_copyarray', 'Cmd_copyarraywithindex', 'Cmd_orbyte', 'Cmd_orhalfword', 'Cmd_orword', 'Cmd_bicbyte', 'Cmd_bichalfword', 'Cmd_bicword', 'Cmd_pause', 'Cmd_waitstate', 'Cmd_healthbar_update', 'Cmd_return', 'Cmd_end', 'Cmd_end2', 'Cmd_end3', 'Cmd_jumpifaffectedbyprotect', 'Cmd_call', 'Cmd_jumpiftype2', 'Cmd_jumpifabilitypresent', 'Cmd_endselectionscript', 'Cmd_playanimation', 'Cmd_playanimation_var', 'Cmd_setgraphicalstatchangevalues', 'Cmd_playstatchangeanimation', 'Cmd_moveend', 'Cmd_typecalc2', 'Cmd_returnatktoball', 'Cmd_getswitchedmondata', 'Cmd_switchindataupdate', 'Cmd_switchinanim', 'Cmd_jumpifcantswitch', 'Cmd_openpartyscreen', 'Cmd_switchhandleorder', 'Cmd_switchineffects', 'Cmd_trainerslidein', 'Cmd_playse', 'Cmd_fanfare', 'Cmd_playfaintcry', 'Cmd_endlinkbattle', 'Cmd_returntoball', 'Cmd_handlelearnnewmove', 'Cmd_yesnoboxlearnmove', 'Cmd_yesnoboxstoplearningmove', 'Cmd_hitanimation', 'Cmd_getmoneyreward', 'Cmd_updatebattlermoves', 'Cmd_swapattackerwithtarget', 'Cmd_incrementgamestat', 'Cmd_drawpartystatussummary', 'Cmd_hidepartystatussummary', 'Cmd_jumptocalledmove', 'Cmd_statusanimation', 'Cmd_status2animation', 'Cmd_chosenstatusanimation', 'Cmd_yesnobox', 'Cmd_cancelallactions', 'Cmd_adjustsetdamage', 'Cmd_removeitem', 'Cmd_atknameinbuff1', 'Cmd_drawlvlupbox', 'Cmd_resetsentmonsvalue', 'Cmd_setatktoplayer0', 'Cmd_makevisible', 'Cmd_recordlastability', 'Cmd_buffermovetolearn', 'Cmd_jumpifplayerran', 'Cmd_hpthresholds', 'Cmd_hpthresholds2', 'Cmd_useitemonopponent', 'Cmd_various', 'Cmd_setprotectlike', 'Cmd_tryexplosion', 'Cmd_setatkhptozero', 'Cmd_jumpifnexttargetvalid', 'Cmd_tryhealhalfhealth', 'Cmd_trymirrormove', 'Cmd_setrain', 'Cmd_setreflect', 'Cmd_setseeded', 'Cmd_manipulatedamage', 'Cmd_trysetrest', 'Cmd_jumpifnotfirstturn', 'Cmd_nop', 'Cmd_jumpifcantmakeasleep', 'Cmd_stockpile', 'Cmd_stockpiletobasedamage', 'Cmd_stockpiletohpheal', 'Cmd_negativedamage', 'Cmd_statbuffchange', 'Cmd_normalisebuffs', 'Cmd_setbide', 'Cmd_confuseifrepeatingattackends', 'Cmd_setmultihitcounter', 'Cmd_initmultihitstring', 'Cmd_forcerandomswitch', 'Cmd_tryconversiontypechange', 'Cmd_givepaydaymoney', 'Cmd_setlightscreen', 'Cmd_tryKO', 'Cmd_damagetohalftargethp', 'Cmd_setsandstorm', 'Cmd_weatherdamage', 'Cmd_tryinfatuating', 'Cmd_updatestatusicon', 'Cmd_setmist', 'Cmd_setfocusenergy', 'Cmd_transformdataexecution', 'Cmd_setsubstitute', 'Cmd_mimicattackcopy', 'Cmd_metronome', 'Cmd_dmgtolevel', 'Cmd_psywavedamageeffect', 'Cmd_counterdamagecalculator', 'Cmd_mirrorcoatdamagecalculator', 'Cmd_disablelastusedattack', 'Cmd_trysetencore', 'Cmd_painsplitdmgcalc', 'Cmd_settypetorandomresistance', 'Cmd_setalwayshitflag', 'Cmd_copymovepermanently', 'Cmd_trychoosesleeptalkmove', 'Cmd_setdestinybond', 'Cmd_trysetdestinybondtohappen', 'Cmd_remaininghptopower', 'Cmd_tryspiteppreduce', 'Cmd_healpartystatus', 'Cmd_cursetarget', 'Cmd_trysetspikes', 'Cmd_setforesight', 'Cmd_trysetperishsong', 'Cmd_rolloutdamagecalculation', 'Cmd_jumpifconfusedandstatmaxed', 'Cmd_furycuttercalc', 'Cmd_friendshiptodamagecalculation', 'Cmd_presentdamagecalculation', 'Cmd_setsafeguard', 'Cmd_magnitudedamagecalculation', 'Cmd_jumpifnopursuitswitchdmg', 'Cmd_setsunny', 'Cmd_maxattackhalvehp', 'Cmd_copyfoestats', 'Cmd_rapidspinfree', 'Cmd_setdefensecurlbit', 'Cmd_recoverbasedonsunlight', 'Cmd_hiddenpowercalc', 'Cmd_selectfirstvalidtarget', 'Cmd_trysetfutureattack', 'Cmd_trydobeatup', 'Cmd_setsemiinvulnerablebit', 'Cmd_clearsemiinvulnerablebit', 'Cmd_setminimize', 'Cmd_sethail', 'Cmd_trymemento', 'Cmd_setforcedtarget', 'Cmd_setcharge', 'Cmd_callenvironmentattack', 'Cmd_cureifburnedparalyzedorpoisoned', 'Cmd_settorment', 'Cmd_jumpifnodamage', 'Cmd_settaunt', 'Cmd_trysethelpinghand', 'Cmd_tryswapitems', 'Cmd_trycopyability', 'Cmd_trywish', 'Cmd_trysetroots', 'Cmd_doubledamagedealtifdamaged', 'Cmd_setyawn', 'Cmd_setdamagetohealthdifference', 'Cmd_scaledamagebyhealthratio', 'Cmd_tryswapabilities', 'Cmd_tryimprison', 'Cmd_trysetgrudge', 'Cmd_weightdamagecalculation', 'Cmd_assistattackselect', 'Cmd_trysetmagiccoat', 'Cmd_trysetsnatch', 'Cmd_trygetintimidatetarget', 'Cmd_switchoutabilities', 'Cmd_jumpifhasnohp', 'Cmd_getsecretpowereffect', 'Cmd_pickup', 'Cmd_docastformchangeanimation', 'Cmd_trycastformdatachange', 'Cmd_settypebasedhalvers', 'Cmd_setweatherballtype', 'Cmd_tryrecycleitem', 'Cmd_settypetoenvironment', 'Cmd_pursuitdoubles', 'Cmd_snatchsetbattlers', 'Cmd_removelightscreenreflect', 'Cmd_handleballthrow', 'Cmd_givecaughtmon', 'Cmd_trysetcaughtmondexflags', 'Cmd_displaydexinfo', 'Cmd_trygivecaughtmonnick', 'Cmd_subattackerhpbydmg', 'Cmd_removeattackerstatus1', 'Cmd_finishaction', 'Cmd_finishturn', 'Cmd_trainerslideout'] as const;

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'IsTwoTurnsMove', ret: "bool8", arity: 1, params: "u16 move" },
  { name: 'TrySetDestinyBondToHappen', ret: "void", arity: 0, params: "void" },
  { name: 'AttacksThisTurn', ret: "u8", arity: 2, params: "u8 battler, u16 move" },
  { name: 'CheckWonderGuardAndLevitate', ret: "void", arity: 0, params: "void" },
  { name: 'ChangeStatBuffs', ret: "u8", arity: 4, params: "s8 statValue, u8 statId, u8, const u8 *BS_ptr" },
  { name: 'IsMonGettingExpSentOut', ret: "bool32", arity: 0, params: "void" },
  { name: 'InitLevelUpBanner', ret: "void", arity: 0, params: "void" },
  { name: 'SlideInLevelUpBanner', ret: "bool8", arity: 0, params: "void" },
  { name: 'SlideOutLevelUpBanner', ret: "bool8", arity: 0, params: "void" },
  { name: 'DrawLevelUpWindow1', ret: "void", arity: 0, params: "void" },
  { name: 'DrawLevelUpWindow2', ret: "void", arity: 0, params: "void" },
  { name: 'PutMonIconOnLvlUpBanner', ret: "void", arity: 0, params: "void" },
  { name: 'DrawLevelUpBannerText', ret: "void", arity: 0, params: "void" },
  { name: 'SpriteCB_MonIconOnLvlUpBanner', ret: "void", arity: 1, params: "struct Sprite *sprite" },
  { name: 'Cmd_attackcanceler', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_accuracycheck', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_attackstring', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_ppreduce', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_critcalc', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_damagecalc', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_typecalc', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_adjustnormaldamage', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_adjustnormaldamage2', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_attackanimation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_waitanimation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_healthbarupdate', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_datahpupdate', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_critmessage', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_effectivenesssound', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_resultmessage', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_printstring', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_printselectionstring', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_waitmessage', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_printfromtable', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_printselectionstringfromtable', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_seteffectwithchance', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_seteffectprimary', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_seteffectsecondary', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_clearstatusfromeffect', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_tryfaintmon', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_dofaintanimation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_cleareffectsonfaint', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifstatus', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifstatus2', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifability', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifsideaffecting', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifstat', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifstatus3condition', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpiftype', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_getexp', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_checkteamslost', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_movevaluescleanup', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setmultihit', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_decrementmultihit', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_goto', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifbyte', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifhalfword', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifword', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifarrayequal', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifarraynotequal', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setbyte', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_addbyte', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_subbyte', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_copyarray', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_copyarraywithindex', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_orbyte', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_orhalfword', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_orword', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_bicbyte', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_bichalfword', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_bicword', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_pause', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_waitstate', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_healthbar_update', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_return', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_end', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_end2', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_end3', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifaffectedbyprotect', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_call', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpiftype2', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifabilitypresent', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_endselectionscript', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_playanimation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_playanimation_var', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setgraphicalstatchangevalues', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_playstatchangeanimation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_moveend', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_typecalc2', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_returnatktoball', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_getswitchedmondata', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_switchindataupdate', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_switchinanim', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifcantswitch', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_openpartyscreen', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_switchhandleorder', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_switchineffects', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trainerslidein', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_playse', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_fanfare', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_playfaintcry', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_endlinkbattle', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_returntoball', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_handlelearnnewmove', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_yesnoboxlearnmove', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_yesnoboxstoplearningmove', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_hitanimation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_getmoneyreward', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_updatebattlermoves', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_swapattackerwithtarget', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_incrementgamestat', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_drawpartystatussummary', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_hidepartystatussummary', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumptocalledmove', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_statusanimation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_status2animation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_chosenstatusanimation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_yesnobox', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_cancelallactions', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_adjustsetdamage', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_removeitem', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_atknameinbuff1', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_drawlvlupbox', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_resetsentmonsvalue', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setatktoplayer0', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_makevisible', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_recordlastability', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_buffermovetolearn', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifplayerran', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_hpthresholds', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_hpthresholds2', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_useitemonopponent', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_various', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setprotectlike', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_tryexplosion', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setatkhptozero', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifnexttargetvalid', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_tryhealhalfhealth', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trymirrormove', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setrain', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setreflect', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setseeded', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_manipulatedamage', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysetrest', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifnotfirstturn', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_nop', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifcantmakeasleep', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_stockpile', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_stockpiletobasedamage', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_stockpiletohpheal', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_negativedamage', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_statbuffchange', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_normalisebuffs', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setbide', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_confuseifrepeatingattackends', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setmultihitcounter', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_initmultihitstring', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_forcerandomswitch', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_tryconversiontypechange', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_givepaydaymoney', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setlightscreen', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_tryKO', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_damagetohalftargethp', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setsandstorm', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_weatherdamage', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_tryinfatuating', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_updatestatusicon', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setmist', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setfocusenergy', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_transformdataexecution', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setsubstitute', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_mimicattackcopy', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_metronome', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_dmgtolevel', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_psywavedamageeffect', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_counterdamagecalculator', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_mirrorcoatdamagecalculator', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_disablelastusedattack', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysetencore', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_painsplitdmgcalc', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_settypetorandomresistance', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setalwayshitflag', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_copymovepermanently', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trychoosesleeptalkmove', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setdestinybond', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysetdestinybondtohappen', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_remaininghptopower', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_tryspiteppreduce', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_healpartystatus', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_cursetarget', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysetspikes', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setforesight', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysetperishsong', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_rolloutdamagecalculation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifconfusedandstatmaxed', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_furycuttercalc', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_friendshiptodamagecalculation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_presentdamagecalculation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setsafeguard', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_magnitudedamagecalculation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifnopursuitswitchdmg', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setsunny', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_maxattackhalvehp', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_copyfoestats', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_rapidspinfree', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setdefensecurlbit', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_recoverbasedonsunlight', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_hiddenpowercalc', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_selectfirstvalidtarget', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysetfutureattack', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trydobeatup', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setsemiinvulnerablebit', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_clearsemiinvulnerablebit', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setminimize', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_sethail', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trymemento', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setforcedtarget', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setcharge', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_callenvironmentattack', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_cureifburnedparalyzedorpoisoned', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_settorment', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifnodamage', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_settaunt', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysethelpinghand', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_tryswapitems', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trycopyability', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trywish', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysetroots', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_doubledamagedealtifdamaged', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setyawn', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setdamagetohealthdifference', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_scaledamagebyhealthratio', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_tryswapabilities', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_tryimprison', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysetgrudge', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_weightdamagecalculation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_assistattackselect', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysetmagiccoat', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysetsnatch', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trygetintimidatetarget', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_switchoutabilities', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_jumpifhasnohp', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_getsecretpowereffect', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_pickup', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_docastformchangeanimation', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trycastformdatachange', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_settypebasedhalvers', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_setweatherballtype', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_tryrecycleitem', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_settypetoenvironment', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_pursuitdoubles', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_snatchsetbattlers', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_removelightscreenreflect', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_handleballthrow', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_givecaughtmon', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trysetcaughtmondexflags', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_displaydexinfo', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trygivecaughtmonnick', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_subattackerhpbydmg', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_removeattackerstatus1', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_finishaction', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_finishturn', ret: "void", arity: 0, params: "void" },
  { name: 'Cmd_trainerslideout', ret: "void", arity: 0, params: "void" },
  { name: 'PALACE_STYLE', ret: "define", arity: 4, params: "atk, def, atkLow, defLow" },
  { name: 'JumpIfMoveFailed', ret: "void", arity: 2, params: "u8 adder, u16 move" },
  { name: 'JumpIfMoveAffectedByProtect', ret: "bool8", arity: 1, params: "u16 move" },
  { name: 'AccuracyCalcHelper', ret: "bool8", arity: 1, params: "u16 move" },
  { name: 'AI_CalcDmg', ret: "void", arity: 2, params: "u8 attacker, u8 defender" },
  { name: 'ModulateDmgByType', ret: "void", arity: 1, params: "u8 multiplier" },
  { name: 'ModulateDmgByType2', ret: "void", arity: 3, params: "u8 multiplier, u16 move, u8 *flags" },
  { name: 'TypeCalc', ret: "u8", arity: 3, params: "u16 move, u8 attacker, u8 defender" },
  { name: 'AI_TypeCalc', ret: "u8", arity: 3, params: "u16 move, u16 targetSpecies, u8 targetAbility" },
  { name: 'ApplyRandomDmgMultiplier', ret: "void", arity: 0, params: "void" },
  { name: 'Unused_ApplyRandomDmgMultiplier', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'GetBattlerTurnOrderNum', ret: "u8", arity: 1, params: "u8 battler" },
  { name: 'SetMoveEffect', ret: "void", arity: 2, params: "bool8 primary, u8 certain" },
  { name: 'MoveValuesCleanUp', ret: "void", arity: 0, params: "void" },
  { name: 'ChooseMonToSendOut', ret: "void", arity: 1, params: "u8 slotId" },
  { name: 'GetTrainerMoneyToGive', ret: "u32", arity: 1, params: "u16 trainerId" },
  { name: 'BufferMoveToLearnIntoBattleTextBuff2', ret: "void", arity: 0, params: "void" },
  { name: 'UproarWakeUpCheck', ret: "bool8", arity: 1, params: "u8 battler" },
  { name: 'TryDoForceSwitchOut', ret: "bool8", arity: 0, params: "void" },
  { name: 'IsMoveUncopyableByMimic', ret: "bool8", arity: 1, params: "u16 move" },
  { name: 'IsInvalidForSleepTalkOrAssist', ret: "bool8", arity: 1, params: "u16 move" },
  { name: 'HandleBattleWindow', ret: "void", arity: 5, params: "u8 xStart, u8 yStart, u8 xEnd, u8 yEnd, u8 flags" },
  { name: 'CopyToBgTilemapBufferRect_ChangePalette', ret: "else", arity: 7, params: "0, &var, destX, destY, 1, 1, 0x11" },
  { name: 'BattleCreateYesNoCursorAt', ret: "void", arity: 1, params: "u8 cursorPosition" },
  { name: 'BattleDestroyYesNoCursorAt', ret: "void", arity: 1, params: "u8 cursorPosition" },
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'battle.h',
  'battle_message.h',
  'battle_anim.h',
  'battle_ai_script_commands.h',
  'battle_scripts.h',
  'item.h',
  'util.h',
  'pokemon.h',
  'random.h',
  'battle_controllers.h',
  'battle_interface.h',
  'text.h',
  'sound.h',
  'pokedex.h',
  'recorded_battle.h',
  'window.h',
  'reshow_battle_screen.h',
  'main.h',
  'palette.h',
  'money.h',
  'bg.h',
  'string_util.h',
  'pokemon_icon.h',
  'm4a.h',
  'mail.h',
  'event_data.h',
  'pokemon_storage_system.h',
  'task.h',
  'naming_screen.h',
  'battle_setup.h',
  'overworld.h',
  'party_menu.h',
  'battle_arena.h',
  'battle_pike.h',
  'battle_pyramid.h',
  'field_specials.h',
  'pokemon_summary_screen.h',
  'pokenav.h',
  'menu_specialized.h',
  'data.h',
  'constants/abilities.h',
  'constants/battle_anim.h',
  'constants/battle_move_effects.h',
  'constants/battle_string_ids.h',
  'constants/hold_effects.h',
  'constants/items.h',
  'constants/map_types.h',
  'constants/moves.h',
  'constants/party_menu.h',
  'constants/rgb.h',
  'constants/songs.h',
  'constants/trainers.h',
] as const;
