// AUTO-GENERATED from src/battle_controller_link_opponent.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/battle_controller_link_opponent.c
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
/** Raw expr: `data[0]` */
export const sSpeedX_EXPR = "data[0]";

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'LinkOpponentHandleGetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleGetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleSetMonData', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleSetRawMonData', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleLoadMonSprite', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleSwitchInAnim', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleReturnMonToBall', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleDrawTrainerPic', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleTrainerSlide', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleTrainerSlideBack', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleFaintAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandlePaletteFade', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleSuccessBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleBallThrowAnim', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandlePause', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleMoveAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandlePrintString', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandlePrintSelectionString', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleChooseAction', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleYesNoBox', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleChooseMove', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleChooseItem', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleChoosePokemon', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleCmd23', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleHealthBarUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleExpUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleStatusIconUpdate', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleStatusAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleStatusXor', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleDataTransfer', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleDMA3Transfer', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandlePlayBGM', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleCmd32', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleTwoReturnValues', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleChosenMonReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleOneReturnValue', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleOneReturnValue_Duplicate', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleClearUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleSetUnkVar', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleClearUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleToggleUnkFlag', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleHitAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleCantSwitch', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandlePlaySE', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandlePlayFanfareOrBGM', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleFaintingCry', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleIntroSlide', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleIntroTrainerBallThrow', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleDrawPartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleHidePartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleEndBounceEffect', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleSpriteInvisibility', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleBattleAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleLinkStandbyMsg', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleResetActionMoveSelection', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentHandleEndLinkBattle', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentCmdEnd', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentBufferRunCommand', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentBufferExecCompleted', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_HandleSoundAndEnd', ret: "void", arity: 0, params: "void" },
  { name: 'CopyLinkOpponentMonData', ret: "u32", arity: 2, params: "u8 monId, u8 *dst" },
  { name: 'SetLinkOpponentMonData', ret: "void", arity: 1, params: "u8 monId" },
  { name: 'StartSendOutAnim', ret: "void", arity: 2, params: "u8 battler, bool8 dontClearSubstituteBit" },
  { name: 'DoSwitchOutAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentDoMoveAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'Task_StartSendOutAnim', ret: "void", arity: 1, params: "u8 taskId" },
  { name: 'SpriteCB_FreeOpponentSprite', ret: "void", arity: 1, params: "struct Sprite *sprite" },
  { name: 'EndDrawPartyStatusSummary', ret: "void", arity: 0, params: "void" },
  { name: 'LinkOpponentDummy', ret: "void", arity: 0, params: "void" },
  { name: 'SetControllerToLinkOpponent', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnBattlerSpriteCallbackDummy', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnBankSpriteCallbackDummy2', ret: "void", arity: 0, params: "void" },
  { name: 'FreeTrainerSpriteAfterSlide', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_DelayAndEnd', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_WaitForShinyAnimAndHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'Intro_TryShinyAnimShowHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'TryShinyAnimAfterMonAnim', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnHealthbarDone', ret: "void", arity: 0, params: "void" },
  { name: 'HideHealthboxAfterMonFaint', ret: "void", arity: 0, params: "void" },
  { name: 'FreeMonSpriteAfterSwitchOutAnim', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnInactiveTextPrinter', ret: "void", arity: 0, params: "void" },
  { name: 'DoHitAnimBlinkSpriteEffect', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_ShowSubstitute', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_ShowHealthbox', ret: "void", arity: 0, params: "void" },
  { name: 'SwitchIn_TryShinyAnim', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedStatusAnimation', ret: "void", arity: 0, params: "void" },
  { name: 'CompleteOnFinishedBattleAnimation', ret: "void", arity: 0, params: "void" },
] as const;

// ─── Task_* (state machine entry points) ────────────────────────────────────
export const TASK_NAMES = [
  'Task_StartSendOutAnim',
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'battle.h',
  'battle_ai_script_commands.h',
  'battle_anim.h',
  'battle_controllers.h',
  'battle_interface.h',
  'battle_message.h',
  'battle_setup.h',
  'battle_tower.h',
  'battle_tv.h',
  'bg.h',
  'data.h',
  'link.h',
  'main.h',
  'm4a.h',
  'palette.h',
  'pokeball.h',
  'pokemon.h',
  'recorded_battle.h',
  'reshow_battle_screen.h',
  'sound.h',
  'string_util.h',
  'task.h',
  'text.h',
  'util.h',
  'window.h',
  'constants/battle_anim.h',
  'constants/songs.h',
  'constants/trainers.h',
  'recorded_battle.h',
] as const;
