// AUTO-GENERATED from src/battle_util.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/battle_util.c
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
export const SOUND_MOVES_END = 65535;
export const FAINTED_ACTIONS_MAX_CASE = 7;

// ─── Enums ───────────────────────────────────────────────────────────────────
export const ENUM_ENDTURN_0 = {
  ENDTURN_ORDER: 0,
  ENDTURN_REFLECT: 1,
  ENDTURN_LIGHT_SCREEN: 2,
  ENDTURN_MIST: 3,
  ENDTURN_SAFEGUARD: 4,
  ENDTURN_WISH: 5,
  ENDTURN_RAIN: 6,
  ENDTURN_SANDSTORM: 7,
  ENDTURN_SUN: 8,
  ENDTURN_HAIL: 9,
  ENDTURN_FIELD_COUNT: 10,
} as const;
export const ENUM_ENDTURN_1 = {
  ENDTURN_INGRAIN: 0,
  ENDTURN_ABILITIES: 1,
  ENDTURN_ITEMS1: 2,
  ENDTURN_LEECH_SEED: 3,
  ENDTURN_POISON: 4,
  ENDTURN_BAD_POISON: 5,
  ENDTURN_BURN: 6,
  ENDTURN_NIGHTMARES: 7,
  ENDTURN_CURSE: 8,
  ENDTURN_WRAP: 9,
  ENDTURN_UPROAR: 10,
  ENDTURN_THRASH: 11,
  ENDTURN_DISABLE: 12,
  ENDTURN_ENCORE: 13,
  ENDTURN_LOCK_ON: 14,
  ENDTURN_CHARGE: 15,
  ENDTURN_TAUNT: 16,
  ENDTURN_YAWN: 17,
  ENDTURN_ITEMS2: 18,
  ENDTURN_BATTLER_COUNT: 19,
} as const;
export const ENUM_CANCELER_2 = {
  CANCELER_FLAGS: 0,
  CANCELER_ASLEEP: 1,
  CANCELER_FROZEN: 2,
  CANCELER_TRUANT: 3,
  CANCELER_RECHARGE: 4,
  CANCELER_FLINCH: 5,
  CANCELER_DISABLED: 6,
  CANCELER_TAUNTED: 7,
  CANCELER_IMPRISONED: 8,
  CANCELER_CONFUSED: 9,
  CANCELER_PARALYZED: 10,
  CANCELER_IN_LOVE: 11,
  CANCELER_BIDE: 12,
  CANCELER_THAW: 13,
  CANCELER_END: 14,
} as const;
export const ENUM_ITEM_3 = {
  ITEM_NO_EFFECT: 0,
  ITEM_STATUS_CHANGE: 1,
  ITEM_EFFECT_OTHER: 2,
  ITEM_PP_CHANGE: 3,
  ITEM_HP_CHANGE: 4,
  ITEM_STATS_CHANGE: 5,
} as const;

// ─── Numeric arrays (raw data tables) ───────────────────────────────────────
export const sGoNearCounterToCatchFactor: readonly number[] = [4,3,2,1] as const;
export const sGoNearCounterToEscapeFactor: readonly number[] = [4,4,4,4] as const;

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'HandleAction_UseMove', ret: "void", arity: 0, params: "void" },
  { name: 'HandleAction_Switch', ret: "void", arity: 0, params: "void" },
  { name: 'HandleAction_UseItem', ret: "void", arity: 0, params: "void" },
  { name: 'TryRunFromBattle', ret: "bool8", arity: 1, params: "u8 battler" },
  { name: 'HandleAction_Run', ret: "void", arity: 0, params: "void" },
  { name: 'HandleAction_WatchesCarefully', ret: "void", arity: 0, params: "void" },
  { name: 'HandleAction_SafariZoneBallThrow', ret: "void", arity: 0, params: "void" },
  { name: 'HandleAction_ThrowPokeblock', ret: "void", arity: 0, params: "void" },
  { name: 'HandleAction_GoNear', ret: "void", arity: 0, params: "void" },
  { name: 'HandleAction_SafariZoneRun', ret: "void", arity: 0, params: "void" },
  { name: 'HandleAction_WallyBallThrow', ret: "void", arity: 0, params: "void" },
  { name: 'HandleAction_TryFinish', ret: "void", arity: 0, params: "void" },
  { name: 'HandleAction_NothingIsFainted', ret: "void", arity: 0, params: "void" },
  { name: 'HandleAction_ActionFinished', ret: "void", arity: 0, params: "void" },
  { name: 'GetBattlerForBattleScript', ret: "u8", arity: 1, params: "u8 caseId" },
  { name: 'PressurePPLose', ret: "void", arity: 3, params: "u8 target, u8 attacker, u16 move" },
  { name: 'PressurePPLoseOnUsingImprison', ret: "void", arity: 1, params: "u8 attacker" },
  { name: 'PressurePPLoseOnUsingPerishSong', ret: "void", arity: 1, params: "u8 attacker" },
  { name: 'MarkAllBattlersForControllerExec', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'MarkBattlerForControllerExec', ret: "void", arity: 1, params: "u8 battlerId" },
  { name: 'MarkBattlerReceivedLinkData', ret: "void", arity: 1, params: "u8 battlerId" },
  { name: 'CancelMultiTurnMoves', ret: "void", arity: 1, params: "u8 battler" },
  { name: 'WasUnableToUseMove', ret: "bool8", arity: 1, params: "u8 battler" },
  { name: 'PrepareStringBattle', ret: "void", arity: 2, params: "u16 stringId, u8 battler" },
  { name: 'ResetSentPokesToOpponentValue', ret: "void", arity: 0, params: "void" },
  { name: 'OpponentSwitchInResetSentPokesToOpponentValue', ret: "void", arity: 1, params: "u8 battler" },
  { name: 'UpdateSentPokesToOpponentValue', ret: "void", arity: 1, params: "u8 battler" },
  { name: 'BattleScriptPush', ret: "void", arity: 1, params: "const u8 *bsPtr" },
  { name: 'BattleScriptPushCursor', ret: "void", arity: 0, params: "void" },
  { name: 'BattleScriptPop', ret: "void", arity: 0, params: "void" },
  { name: 'TrySetCantSelectMoveBattleScript', ret: "u8", arity: 0, params: "void" },
  { name: 'CheckMoveLimitations', ret: "u8", arity: 3, params: "u8 battlerId, u8 unusableMoves, u8 check" },
  { name: 'AreAllMovesUnusable', ret: "bool8", arity: 0, params: "void" },
  { name: 'GetImprisonedMovesCount', ret: "u8", arity: 2, params: "u8 battlerId, u16 move" },
  { name: 'DoFieldEndTurnEffects', ret: "u8", arity: 0, params: "void" },
  { name: 'DoBattlerEndTurnEffects', ret: "u8", arity: 0, params: "void" },
  { name: 'HandleWishPerishSongOnTurnEnd', ret: "bool8", arity: 0, params: "void" },
  { name: 'HandleFaintedMonActions', ret: "bool8", arity: 0, params: "void" },
  { name: 'TryClearRageStatuses', ret: "void", arity: 0, params: "void" },
  { name: 'AtkCanceler_UnableToUseMove', ret: "u8", arity: 0, params: "void" },
  { name: 'HasNoMonsToSwitch', ret: "bool8", arity: 3, params: "u8 battler, u8 partyIdBattlerOn1, u8 partyIdBattlerOn2" },
  { name: 'CastformDataTypeChange', ret: "u8", arity: 1, params: "u8 battler" },
  { name: 'AbilityBattleEffects', ret: "u8", arity: 5, params: "u8 caseID, u8 battler, u8 ability, u8 special, u16 moveArg" },
  { name: 'BattleScriptExecute', ret: "void", arity: 1, params: "const u8 *BS_ptr" },
  { name: 'BattleScriptPushCursorAndCallback', ret: "void", arity: 1, params: "const u8 *BS_ptr" },
  { name: 'ItemBattleEffects', ret: "u8", arity: 3, params: "u8 caseID, u8 battlerId, bool8 moveTurn" },
  { name: 'ClearFuryCutterDestinyBondGrudge', ret: "void", arity: 1, params: "u8 battlerId" },
  { name: 'HandleAction_RunBattleScript', ret: "void", arity: 0, params: "void" },
  { name: 'GetMoveTarget', ret: "u8", arity: 2, params: "u16 move, u8 setTarget" },
  { name: 'IsBattlerModernFatefulEncounter', ret: "bool32", arity: 1, params: "u8 battlerId" },
  { name: 'IsMonDisobedient', ret: "u8", arity: 0, params: "void" },
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'battle.h',
  'battle_anim.h',
  'battle_arena.h',
  'battle_pyramid.h',
  'battle_util.h',
  'pokemon.h',
  'international_string_util.h',
  'item.h',
  'util.h',
  'battle_scripts.h',
  'random.h',
  'text.h',
  'safari_zone.h',
  'sound.h',
  'sprite.h',
  'string_util.h',
  'task.h',
  'trig.h',
  'window.h',
  'battle_message.h',
  'battle_ai_script_commands.h',
  'battle_controllers.h',
  'event_data.h',
  'link.h',
  'field_weather.h',
  'constants/abilities.h',
  'constants/battle_anim.h',
  'constants/battle_move_effects.h',
  'constants/battle_script_commands.h',
  'constants/battle_string_ids.h',
  'constants/hold_effects.h',
  'constants/items.h',
  'constants/moves.h',
  'constants/songs.h',
  'constants/species.h',
  'constants/weather.h',
] as const;
