// AUTO-GENERATED from src/contest_effect.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/contest_effect.c
// Generated: 2026-04-26

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'ContestEffect_HighlyAppealing', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_UserMoreEasilyStartled', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_GreatAppealButNoMoreMoves', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_RepetitionNotBoring', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_AvoidStartleOnce', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_AvoidStartle', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_AvoidStartleSlightly', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_UserLessEasilyStartled', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_StartleFrontMon', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_StartlePrevMons', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_StartlePrevMon2', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_StartlePrevMons2', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_ShiftJudgeAttention', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_StartleMonWithJudgesAttention', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_JamsOthersButMissOneTurn', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_StartleMonsSameTypeAppeal', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_StartleMonsCoolAppeal', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_StartleMonsBeautyAppeal', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_StartleMonsCuteAppeal', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_StartleMonsSmartAppeal', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_StartleMonsToughAppeal', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_MakeFollowingMonNervous', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_MakeFollowingMonsNervous', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_WorsenConditionOfPrevMons', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_BadlyStartlesMonsInGoodCondition', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_BetterIfFirst', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_BetterIfLast', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_AppealAsGoodAsPrevOnes', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_AppealAsGoodAsPrevOne', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_BetterWhenLater', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_QualityDependsOnTiming', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_BetterIfSameType', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_BetterIfDiffType', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_AffectedByPrevAppeal', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_ImproveConditionPreventNervousness', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_BetterWithGoodCondition', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_NextAppealEarlier', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_NextAppealLater', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_MakeScramblingTurnOrderEasier', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_ScrambleNextTurnOrder', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_ExciteAudienceInAnyContest', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_BadlyStartleMonsWithGoodAppeals', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_BetterWhenAudienceExcited', ret: "void", arity: 0, params: "void" },
  { name: 'ContestEffect_DontExciteAudience', ret: "void", arity: 0, params: "void" },
  { name: 'JamByMoveCategory', ret: "void", arity: 1, params: "u8" },
  { name: 'CanUnnerveContestant', ret: "bool8", arity: 1, params: "u8" },
  { name: 'WasAtLeastOneOpponentJammed', ret: "u8", arity: 0, params: "void" },
  { name: 'JamContestant', ret: "void", arity: 2, params: "u8, u8" },
  { name: 'RoundTowardsZero', ret: "s16", arity: 1, params: "s16" },
  { name: 'RoundUp', ret: "s16", arity: 1, params: "s16" },
  { name: 'AreMovesContestCombo', ret: "bool8", arity: 2, params: "u16 lastMove, u16 nextMove" },
  { name: 'SetContestantEffectStringID', ret: "else", arity: 2, params: "eContestAppealResults.contestant, CONTEST_STRING_APPEAL_EXCELLENTLY" },
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'random.h',
  'constants/moves.h',
  'contest.h',
  'contest_effect.h',
  'data/contest_moves.h',
] as const;
