// AUTO-GENERATED from src/librfu_rfu.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/librfu_rfu.c
// Generated: 2026-04-26

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'rfu_CB_defaultCallback', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_reset', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_configGameData', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_stopMode', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_startSearchChild', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_pollAndEndSearchChild', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_startSearchParent', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_pollSearchParent', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_pollConnectParent', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_disconnect', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_CHILD_pollConnectRecovery', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_sendData', ret: "void", arity: 2, params: "UNUSED u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_sendData2', ret: "void", arity: 2, params: "UNUSED u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_sendData3', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_CB_recvData', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_enableREQCallback', ret: "void", arity: 1, params: "bool8 enable" },
  { name: 'rfu_STC_clearAPIVariables', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_STC_readChildList', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_STC_readParentCandidateList', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_STC_REQ_callback', ret: "void", arity: 2, params: "u8 reqCommand, u16 reqResult" },
  { name: 'rfu_STC_removeLinkData', ret: "void", arity: 2, params: "u8, u8" },
  { name: 'rfu_STC_fastCopy', ret: "void", arity: 3, params: "const u8 **, u8 **, s32" },
  { name: 'rfu_STC_clearLinkStatus', ret: "void", arity: 1, params: "u8" },
  { name: 'rfu_NI_checkCommFailCounter', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_STC_setSendData_org', ret: "u16", arity: 5, params: "u8, u8, u8, const void *, u32" },
  { name: 'rfu_constructSendLLFrame', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_STC_NI_constructLLSF', ret: "u16", arity: 3, params: "u8, u8 **, struct NIComm *" },
  { name: 'rfu_STC_UNI_constructLLSF', ret: "u16", arity: 2, params: "u8, u8 **" },
  { name: 'rfu_STC_PARENT_analyzeRecvPacket', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_STC_CHILD_analyzeRecvPacket', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_STC_analyzeLLSF', ret: "u16", arity: 3, params: "u8, const u8 *, u16" },
  { name: 'rfu_STC_UNI_receive', ret: "void", arity: 3, params: "u8, const struct RfuLocalStruct *, const u8 *" },
  { name: 'rfu_STC_NI_receive_Receiver', ret: "void", arity: 3, params: "u8, const struct RfuLocalStruct *, const u8 *" },
  { name: 'rfu_STC_NI_receive_Sender', ret: "void", arity: 4, params: "u8, u8, const struct RfuLocalStruct *, UNUSED const u8 *" },
  { name: 'rfu_STC_NI_initSlot_asRecvDataEntity', ret: "void", arity: 2, params: "u8, struct NIComm *" },
  { name: 'rfu_STC_NI_initSlot_asRecvControllData', ret: "void", arity: 2, params: "u8, struct NIComm *" },
  { name: 'rfu_initializeAPI', ret: "u16", arity: 4, params: "u32 *APIBuffer, u16 buffByteSize, IntrFunc *sioIntrTable_p, bool8 copyInterruptToRam" },
  { name: 'rfu_REQ_PARENT_resumeRetransmitAndChange', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_UNI_PARENT_getDRAC_ACK', ret: "u16", arity: 1, params: "u8 *ackFlag" },
  { name: 'rfu_setTimerInterrupt', ret: "void", arity: 2, params: "u8 timerNo, IntrFunc *timerIntrTable_p" },
  { name: 'rfu_waitREQComplete', ret: "u16", arity: 0, params: "void" },
  { name: 'rfu_REQ_RFUStatus', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_getRFUStatus', ret: "u16", arity: 1, params: "u8 *rfuState" },
  { name: 'rfu_MBOOT_CHILD_inheritanceLinkStatus', ret: "u16", arity: 0, params: "void" },
  { name: 'rfu_REQ_stopMode', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_REQBN_softReset_and_checkID', ret: "u32", arity: 0, params: "void" },
  { name: 'rfu_REQ_reset', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_REQ_configSystem', ret: "void", arity: 3, params: "u16 availSlotFlag, u8 maxMFrame, u8 mcTimer" },
  { name: 'rfu_REQ_configGameData', ret: "void", arity: 4, params: "u8 mbootFlag, u16 serialNo, const u8 *gname, const u8 *uname" },
  { name: 'rfu_REQ_startSearchChild', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_REQ_pollSearchChild', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_REQ_endSearchChild', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_REQ_startSearchParent', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_REQ_pollSearchParent', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_REQ_endSearchParent', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_REQ_startConnectParent', ret: "void", arity: 1, params: "u16 pid" },
  { name: 'rfu_REQ_pollConnectParent', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_getConnectParentStatus', ret: "u16", arity: 2, params: "u8 *status, u8 *connectSlotNo" },
  { name: 'rfu_REQ_endConnectParent', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_syncVBlank', ret: "u16", arity: 0, params: "void" },
  { name: 'rfu_REQBN_watchLink', ret: "u16", arity: 4, params: "u16 reqCommandId, u8 *bmLinkLossSlot, u8 *linkLossReason, u8 *parentBmLinkRecoverySlot" },
  { name: 'rfu_REQ_disconnect', ret: "void", arity: 1, params: "u8 bmDisconnectSlot" },
  { name: 'rfu_REQ_CHILD_startConnectRecovery', ret: "void", arity: 1, params: "u8 bmRecoverySlot" },
  { name: 'rfu_REQ_CHILD_pollConnectRecovery', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_CHILD_getConnectRecoveryStatus', ret: "u16", arity: 1, params: "u8 *status" },
  { name: 'rfu_REQ_CHILD_endConnectRecovery', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_REQ_changeMasterSlave', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_getMasterSlave', ret: "bool8", arity: 0, params: "void" },
  { name: 'rfu_clearAllSlot', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_STC_releaseFrame', ret: "void", arity: 3, params: "u8 bm_slot_id, u8 send_recv, struct NIComm *NI_comm" },
  { name: 'rfu_clearSlot', ret: "u16", arity: 2, params: "u8 connTypeFlag, u8 slotStatusIndex" },
  { name: 'rfu_setRecvBuffer', ret: "u16", arity: 4, params: "u8 connType, u8 slotNo, void *buffer, u32 buffSize" },
  { name: 'rfu_NI_setSendData', ret: "u16", arity: 4, params: "u8 bmSendSlot, u8 subFrameSize, const void *src, u32 size" },
  { name: 'rfu_UNI_setSendData', ret: "u16", arity: 3, params: "u8 bmSendSlot, const void *src, u8 size" },
  { name: 'rfu_NI_CHILD_setSendGameName', ret: "u16", arity: 2, params: "u8 slotNo, u8 subFrameSize" },
  { name: 'rfu_changeSendTarget', ret: "u16", arity: 3, params: "u8 connType, u8 slotStatusIndex, u8 bmNewTgtSlot" },
  { name: 'rfu_NI_stopReceivingData', ret: "u16", arity: 1, params: "u8 slotStatusIndex" },
  { name: 'rfu_UNI_changeAndReadySendData', ret: "u16", arity: 3, params: "u8 slotStatusIndex, const void *src, u8 size" },
  { name: 'rfu_UNI_readySendData', ret: "void", arity: 1, params: "u8 slotStatusIndex" },
  { name: 'rfu_UNI_clearRecvNewDataFlag', ret: "void", arity: 1, params: "u8 slotStatusIndex" },
  { name: 'rfu_REQ_sendData', ret: "void", arity: 1, params: "bool8 clockChangeFlag" },
  { name: 'STWI_send_DataTxAndChangeREQ', ret: "else", arity: 2, params: "gRfuFixed->LLFBuffer, 1" },
  { name: 'rfu_REQ_recvData', ret: "void", arity: 0, params: "void" },
  { name: 'rfu_REQ_noise', ret: "void", arity: 0, params: "void" },
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'limits.h',
  'librfu.h',
] as const;
