// AUTO-GENERATED from src/overworld.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/overworld.c
// Generated: 2026-04-26

// ─── #define constants ──────────────────────────────────────────────────────
export const PLAYER_LINK_STATE_IDLE = 128;
export const PLAYER_LINK_STATE_BUSY = 129;
export const PLAYER_LINK_STATE_READY = 130;
export const PLAYER_LINK_STATE_EXITING_ROOM = 131;
export const FACING_NONE = 0;
export const FACING_UP = 1;
export const FACING_DOWN = 2;
export const FACING_LEFT = 3;
export const FACING_RIGHT = 4;
export const FACING_FORCED_UP = 7;
export const FACING_FORCED_DOWN = 8;
export const FACING_FORCED_LEFT = 9;
export const FACING_FORCED_RIGHT = 10;
/** Raw expr: `sLinkPlayerMovementModes[linkPlayerObjEvent->movementMode](linkPlayerObjEvent, objEvent, facing)` */
export const TEMP_EXPR = "sLinkPlayerMovementModes[linkPlayerObjEvent->movementMode](linkPlayerObjEvent, objEvent, facing)";

// ─── Enums ───────────────────────────────────────────────────────────────────
export const ENUM_AMB_0 = {
  AMB_CRY_INIT: 0,
  AMB_CRY_FIRST: 1,
  AMB_CRY_RESET: 2,
  AMB_CRY_WAIT: 3,
  AMB_CRY_IDLE: 4,
} as const;

// ─── BgTemplate ─────────────────────────────────────────────────────────────
export const sOverworldBgTemplates = [
  { bg: 0, charBaseIndex: 2, mapBaseIndex: 31, screenSize: 0, paletteMode: 0, priority: 0, baseTile: 0 },
  { bg: 1, charBaseIndex: 0, mapBaseIndex: 29, screenSize: 0, paletteMode: 0, priority: 1, baseTile: 0 },
  { bg: 2, charBaseIndex: 0, mapBaseIndex: 28, screenSize: 0, paletteMode: 0, priority: 2, baseTile: 0 },
  { bg: 3, charBaseIndex: 0, mapBaseIndex: 30, screenSize: 0, paletteMode: 0, priority: 3, baseTile: 0 },
] as const;

// ─── Numeric arrays (raw data tables) ───────────────────────────────────────
export const sUnusedData: readonly number[] = [1200,3600,1200,2400,50,80,-44,44] as const;

// ─── Function pointer tables (opcode dispatch) ──────────────────────────────
export const sLinkPlayerMovementModes = ['MovementEventModeCB_Normal', 'MovementEventModeCB_Ignored', 'MovementEventModeCB_Scripted'] as const;
export const sLinkPlayerFacingHandlers = ['FacingHandler_DoNothing', 'FacingHandler_DpadMovement', 'FacingHandler_DpadMovement', 'FacingHandler_DpadMovement', 'FacingHandler_DpadMovement', 'FacingHandler_DoNothing', 'FacingHandler_DoNothing', 'FacingHandler_ForcedFacingChange', 'FacingHandler_ForcedFacingChange', 'FacingHandler_ForcedFacingChange', 'FacingHandler_ForcedFacingChange'] as const;
export const sMovementStatusHandler = ['MovementStatusHandler_EnterFreeMode', 'MovementStatusHandler_TryAdvanceScript'] as const;

// ─── EWRAM/IWRAM/COMMON_DATA globals (initial values) ──────────────────────
export const SEGMENT_VARS = [
  { segment: 'COMMON_DATA', type: "u16", name: 'gHeldKeyCodeToSend', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u8", name: 'gLocalLinkPlayerId', isArray: false, init: "0" },
  { segment: 'COMMON_DATA', type: "u8", name: 'gFieldLinkPlayerCount', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u8", name: 'sObjectEventLoadFlag', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "struct WarpData", name: 'gLastUsedWarp', isArray: false, init: "{0}" },
  { segment: 'EWRAM_DATA', type: "struct WarpData", name: 'sWarpDestination', isArray: false, init: "{0}" },
  { segment: 'EWRAM_DATA', type: "struct WarpData", name: 'sFixedDiveWarp', isArray: false, init: "{0}" },
  { segment: 'EWRAM_DATA', type: "struct WarpData", name: 'sFixedHoleWarp', isArray: false, init: "{0}" },
  { segment: 'EWRAM_DATA', type: "mapsec_u16_t", name: 'sLastMapSectionId', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "struct InitialPlayerAvatarState", name: 'sInitialPlayerAvatarState', isArray: false, init: "{0}" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sAmbientCrySpecies', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "bool8", name: 'sIsAmbientCryWaterMon', isArray: false, init: "FALSE" },
  { segment: 'EWRAM_DATA', type: "struct LinkPlayerObjectEvent", name: 'gLinkPlayerObjectEvents', isArray: true, init: "{0}" },
] as const;

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'Overworld_ResetStateAfterWhiteOut', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToFieldLocal', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToFieldLink', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_LoadMapOnReturnToFieldCableClub', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_LoadMap2', ret: "void", arity: 0, params: "void" },
  { name: 'VBlankCB_Field', ret: "void", arity: 0, params: "void" },
  { name: 'SpriteCB_LinkPlayer', ret: "void", arity: 1, params: "struct Sprite *" },
  { name: 'ChooseAmbientCrySpecies', ret: "void", arity: 0, params: "void" },
  { name: 'DoMapLoadLoop', ret: "void", arity: 1, params: "u8 *" },
  { name: 'LoadMapInStepsLocal', ret: "bool32", arity: 2, params: "u8 *, bool32" },
  { name: 'LoadMapInStepsLink', ret: "bool32", arity: 1, params: "u8 *" },
  { name: 'ReturnToFieldLocal', ret: "bool32", arity: 1, params: "u8 *" },
  { name: 'ReturnToFieldLink', ret: "bool32", arity: 1, params: "u8 *" },
  { name: 'InitObjectEventsLink', ret: "void", arity: 0, params: "void" },
  { name: 'InitObjectEventsLocal', ret: "void", arity: 0, params: "void" },
  { name: 'InitOverworldGraphicsRegisters', ret: "void", arity: 0, params: "void" },
  { name: 'GetSpriteForLinkedPlayer', ret: "u8", arity: 1, params: "u8" },
  { name: 'KeyInterCB_SendNothing', ret: "u16", arity: 1, params: "u32" },
  { name: 'ResetMirageTowerAndSaveBlockPtrs', ret: "void", arity: 0, params: "void" },
  { name: 'ResetScreenForMapLoad', ret: "void", arity: 0, params: "void" },
  { name: 'OffsetCameraFocusByLinkPlayerId', ret: "void", arity: 0, params: "void" },
  { name: 'SpawnLinkPlayers', ret: "void", arity: 0, params: "void" },
  { name: 'SetCameraToTrackGuestPlayer', ret: "void", arity: 0, params: "void" },
  { name: 'ResumeMap', ret: "void", arity: 1, params: "bool32" },
  { name: 'SetCameraToTrackPlayer', ret: "void", arity: 0, params: "void" },
  { name: 'InitObjectEventsReturnToField', ret: "void", arity: 0, params: "void" },
  { name: 'InitViewGraphics', ret: "void", arity: 0, params: "void" },
  { name: 'SetCameraToTrackGuestPlayer_2', ret: "void", arity: 0, params: "void" },
  { name: 'CreateLinkPlayerSprites', ret: "void", arity: 0, params: "void" },
  { name: 'ClearAllPlayerKeys', ret: "void", arity: 0, params: "void" },
  { name: 'ResetAllPlayerLinkStates', ret: "void", arity: 0, params: "void" },
  { name: 'UpdateHeldKeyCode', ret: "void", arity: 1, params: "u16" },
  { name: 'UpdateAllLinkPlayers', ret: "void", arity: 2, params: "u16 *, s32" },
  { name: 'FlipVerticalAndClearForced', ret: "u8", arity: 2, params: "u8, u8" },
  { name: 'LinkPlayerGetCollision', ret: "u8", arity: 4, params: "u8, u8, s16, s16" },
  { name: 'CreateLinkPlayerSprite', ret: "void", arity: 2, params: "u8, u8" },
  { name: 'GetLinkPlayerCoords', ret: "void", arity: 3, params: "u8, u16 *, u16 *" },
  { name: 'GetLinkPlayerFacingDirection', ret: "u8", arity: 1, params: "u8" },
  { name: 'GetLinkPlayerElevation', ret: "u8", arity: 1, params: "u8" },
  { name: 'GetLinkPlayerIdAt', ret: "u8", arity: 2, params: "s16, s16" },
  { name: 'SetPlayerFacingDirection', ret: "void", arity: 2, params: "u8, u8" },
  { name: 'ZeroObjectEvent', ret: "void", arity: 1, params: "struct ObjectEvent *" },
  { name: 'SpawnLinkPlayerObjectEvent', ret: "void", arity: 4, params: "u8, s16, s16, u8" },
  { name: 'InitLinkPlayerObjectEventPos', ret: "void", arity: 3, params: "struct ObjectEvent *, s16, s16" },
  { name: 'RunTerminateLinkScript', ret: "void", arity: 0, params: "void" },
  { name: 'GetLinkSendQueueLength', ret: "u32", arity: 0, params: "void" },
  { name: 'ZeroLinkPlayerObjectEvent', ret: "void", arity: 1, params: "struct LinkPlayerObjectEvent *" },
  { name: 'GetDirectionForEventScript', ret: "u16", arity: 1, params: "const u8 *" },
  { name: 'InitLinkPlayerQueueScript', ret: "void", arity: 0, params: "void" },
  { name: 'InitLinkRoomStartMenuScript', ret: "void", arity: 0, params: "void" },
  { name: 'RunInteractLocalPlayerScript', ret: "void", arity: 1, params: "const u8 *" },
  { name: 'RunConfirmLeaveCableClubScript', ret: "void", arity: 0, params: "void" },
  { name: 'InitMenuBasedScript', ret: "void", arity: 1, params: "const u8 *" },
  { name: 'LoadCableClubPlayer', ret: "void", arity: 3, params: "s32, s32, struct CableClubPlayer *" },
  { name: 'IsCableClubPlayerUnfrozen', ret: "bool32", arity: 1, params: "struct CableClubPlayer *" },
  { name: 'CanCableClubPlayerPressStart', ret: "bool32", arity: 1, params: "struct CableClubPlayer *" },
  { name: 'PlayerIsAtSouthExit', ret: "bool32", arity: 1, params: "struct CableClubPlayer *" },
  { name: 'KeyInterCB_DeferToRecvQueue', ret: "u16", arity: 1, params: "u32" },
  { name: 'KeyInterCB_DeferToSendQueue', ret: "u16", arity: 1, params: "u32" },
  { name: 'ResetPlayerHeldKeys', ret: "void", arity: 1, params: "u16 *" },
  { name: 'KeyInterCB_SelfIdle', ret: "u16", arity: 1, params: "u32" },
  { name: 'KeyInterCB_DeferToEventScript', ret: "u16", arity: 1, params: "u32" },
  { name: 'GetDirectionForDpadKey', ret: "u16", arity: 1, params: "u16" },
  { name: 'CB1_OverworldLink', ret: "void", arity: 0, params: "void" },
  { name: 'SetFieldVBlankCallback', ret: "void", arity: 0, params: "void" },
  { name: 'FieldClearVBlankHBlankCallbacks', ret: "void", arity: 0, params: "void" },
  { name: 'TransitionMapMusic', ret: "void", arity: 0, params: "void" },
  { name: 'GetAdjustedInitialTransitionFlags', ret: "u8", arity: 3, params: "struct InitialPlayerAvatarState *, u16, u8" },
  { name: 'GetAdjustedInitialDirection', ret: "u8", arity: 4, params: "struct InitialPlayerAvatarState *, u8, u16, u8" },
  { name: 'GetCenterScreenMetatileBehavior', ret: "u16", arity: 0, params: "void" },
  { name: 'MovementEventModeCB_Normal', ret: "u8", arity: 3, params: "struct LinkPlayerObjectEvent *, struct ObjectEvent *, u8" },
  { name: 'MovementEventModeCB_Ignored', ret: "u8", arity: 3, params: "struct LinkPlayerObjectEvent *, struct ObjectEvent *, u8" },
  { name: 'MovementEventModeCB_Scripted', ret: "u8", arity: 3, params: "struct LinkPlayerObjectEvent *, struct ObjectEvent *, u8" },
  { name: 'FacingHandler_DoNothing', ret: "u8", arity: 3, params: "struct LinkPlayerObjectEvent *, struct ObjectEvent *, u8" },
  { name: 'FacingHandler_DpadMovement', ret: "u8", arity: 3, params: "struct LinkPlayerObjectEvent *, struct ObjectEvent *, u8" },
  { name: 'FacingHandler_ForcedFacingChange', ret: "u8", arity: 3, params: "struct LinkPlayerObjectEvent *, struct ObjectEvent *, u8" },
  { name: 'MovementStatusHandler_EnterFreeMode', ret: "void", arity: 2, params: "struct LinkPlayerObjectEvent *, struct ObjectEvent *" },
  { name: 'MovementStatusHandler_TryAdvanceScript', ret: "void", arity: 2, params: "struct LinkPlayerObjectEvent *, struct ObjectEvent *" },
  { name: 'DoWhiteOut', ret: "void", arity: 0, params: "void" },
  { name: 'Overworld_ResetStateAfterFly', ret: "void", arity: 0, params: "void" },
  { name: 'Overworld_ResetStateAfterTeleport', ret: "void", arity: 0, params: "void" },
  { name: 'Overworld_ResetStateAfterDigEscRope', ret: "void", arity: 0, params: "void" },
  { name: 'UpdateMiscOverworldStates', ret: "void", arity: 0, params: "void" },
  { name: 'ResetGameStats', ret: "void", arity: 0, params: "void" },
  { name: 'IncrementGameStat', ret: "void", arity: 1, params: "u8 index" },
  { name: 'GetGameStat', ret: "u32", arity: 1, params: "u8 index" },
  { name: 'SetGameStat', ret: "void", arity: 2, params: "u8 index, u32 value" },
  { name: 'ApplyNewEncryptionKeyToGameStats', ret: "void", arity: 1, params: "u32 newKey" },
  { name: 'LoadObjEventTemplatesFromHeader', ret: "void", arity: 0, params: "void" },
  { name: 'LoadSaveblockObjEventScripts', ret: "void", arity: 0, params: "void" },
  { name: 'SetObjEventTemplateCoords', ret: "void", arity: 3, params: "u8 localId, s16 x, s16 y" },
  { name: 'SetObjEventTemplateMovementType', ret: "void", arity: 2, params: "u8 localId, u8 movementType" },
  { name: 'InitMapView', ret: "void", arity: 0, params: "void" },
  { name: 'ApplyCurrentWarp', ret: "void", arity: 0, params: "void" },
  { name: 'ClearDiveAndHoleWarps', ret: "void", arity: 0, params: "void" },
  { name: 'SetWarpData', ret: "void", arity: 6, params: "struct WarpData *warp, s8 mapGroup, s8 mapNum, s8 warpId, s8 x, s8 y" },
  { name: 'IsDummyWarp', ret: "bool32", arity: 1, params: "struct WarpData *warp" },
  { name: 'Overworld_GetMapHeaderByGroupAndId', ret: "const", arity: 2, params: "u16 mapGroup, u16 mapNum" },
  { name: 'GetDestinationWarpMapHeader', ret: "const", arity: 0, params: "void" },
  { name: 'LoadCurrentMapData', ret: "void", arity: 0, params: "void" },
  { name: 'LoadSaveblockMapHeader', ret: "void", arity: 0, params: "void" },
  { name: 'SetPlayerCoordsFromWarp', ret: "void", arity: 0, params: "void" },
  { name: 'WarpIntoMap', ret: "void", arity: 0, params: "void" },
  { name: 'SetWarpDestination', ret: "void", arity: 5, params: "s8 mapGroup, s8 mapNum, s8 warpId, s8 x, s8 y" },
  { name: 'SetWarpDestinationToMapWarp', ret: "void", arity: 3, params: "s8 mapGroup, s8 mapNum, s8 warpId" },
  { name: 'SetDynamicWarp', ret: "void", arity: 4, params: "s32 unused, s8 mapGroup, s8 mapNum, s8 warpId" },
  { name: 'SetDynamicWarpWithCoords', ret: "void", arity: 6, params: "s32 unused, s8 mapGroup, s8 mapNum, s8 warpId, s8 x, s8 y" },
  { name: 'SetWarpDestinationToDynamicWarp', ret: "void", arity: 1, params: "u8 unusedWarpId" },
  { name: 'SetWarpDestinationToHealLocation', ret: "void", arity: 1, params: "u8 healLocationId" },
  { name: 'SetWarpDestinationToLastHealLocation', ret: "void", arity: 0, params: "void" },
  { name: 'SetLastHealLocationWarp', ret: "void", arity: 1, params: "u8 healLocationId" },
  { name: 'UpdateEscapeWarp', ret: "void", arity: 2, params: "s16 x, s16 y" },
  { name: 'SetEscapeWarp', ret: "void", arity: 5, params: "s8 mapGroup, s8 mapNum, s8 warpId, s8 x, s8 y" },
  { name: 'SetWarpDestinationToEscapeWarp', ret: "void", arity: 0, params: "void" },
  { name: 'SetFixedDiveWarp', ret: "void", arity: 5, params: "s8 mapGroup, s8 mapNum, s8 warpId, s8 x, s8 y" },
  { name: 'SetWarpDestinationToDiveWarp', ret: "void", arity: 0, params: "void" },
  { name: 'SetFixedHoleWarp', ret: "void", arity: 5, params: "s8 mapGroup, s8 mapNum, s8 warpId, s8 x, s8 y" },
  { name: 'SetWarpDestinationToFixedHoleWarp', ret: "void", arity: 2, params: "s16 x, s16 y" },
  { name: 'SetWarpDestinationToContinueGameWarp', ret: "void", arity: 0, params: "void" },
  { name: 'SetContinueGameWarp', ret: "void", arity: 5, params: "s8 mapGroup, s8 mapNum, s8 warpId, s8 x, s8 y" },
  { name: 'SetContinueGameWarpToHealLocation', ret: "void", arity: 1, params: "u8 healLocationId" },
  { name: 'SetContinueGameWarpToDynamicWarp', ret: "void", arity: 1, params: "int unused" },
  { name: 'SetDiveWarp', ret: "bool8", arity: 3, params: "u8 dir, u16 x, u16 y" },
  { name: 'SetDiveWarpEmerge', ret: "bool8", arity: 2, params: "u16 x, u16 y" },
  { name: 'SetDiveWarpDive', ret: "bool8", arity: 2, params: "u16 x, u16 y" },
  { name: 'LoadMapFromCameraTransition', ret: "void", arity: 2, params: "u8 mapGroup, u8 mapNum" },
  { name: 'LoadMapFromWarp', ret: "void", arity: 1, params: "bool32 a1" },
  { name: 'InitMap', ret: "else", arity: 0, params: "" },
  { name: 'ResetInitialPlayerAvatarState', ret: "void", arity: 0, params: "void" },
  { name: 'StoreInitialPlayerAvatarState', ret: "void", arity: 0, params: "void" },
  { name: 'Overworld_IsBikingAllowed', ret: "bool32", arity: 0, params: "void" },
  { name: 'SetDefaultFlashLevel', ret: "void", arity: 0, params: "void" },
  { name: 'SetFlashLevel', ret: "void", arity: 1, params: "s32 flashLevel" },
  { name: 'GetFlashLevel', ret: "u8", arity: 0, params: "void" },
  { name: 'SetCurrentMapLayout', ret: "void", arity: 1, params: "u16 mapLayoutId" },
  { name: 'SetObjectEventLoadFlag', ret: "void", arity: 1, params: "u8 flag" },
  { name: 'GetObjectEventLoadFlag', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'ShouldLegendaryMusicPlayAtLocation', ret: "bool16", arity: 1, params: "struct WarpData *warp" },
  { name: 'NoMusicInSootopolisWithLegendaries', ret: "bool16", arity: 1, params: "struct WarpData *warp" },
  { name: 'IsInfiltratedWeatherInstitute', ret: "bool16", arity: 1, params: "struct WarpData *warp" },
  { name: 'IsInfiltratedSpaceCenter', ret: "bool16", arity: 1, params: "struct WarpData *warp" },
  { name: 'GetLocationMusic', ret: "u16", arity: 1, params: "struct WarpData *warp" },
  { name: 'GetCurrLocationDefaultMusic', ret: "u16", arity: 0, params: "void" },
  { name: 'GetWarpDestinationMusic', ret: "u16", arity: 0, params: "void" },
  { name: 'Overworld_ResetMapMusic', ret: "void", arity: 0, params: "void" },
  { name: 'Overworld_PlaySpecialMapMusic', ret: "void", arity: 0, params: "void" },
  { name: 'Overworld_SetSavedMusic', ret: "void", arity: 1, params: "u16 songNum" },
  { name: 'Overworld_ClearSavedMusic', ret: "void", arity: 0, params: "void" },
  { name: 'FadeOutAndPlayNewMapMusic', ret: "else", arity: 2, params: "newMusic, 8" },
  { name: 'Overworld_ChangeMusicToDefault', ret: "void", arity: 0, params: "void" },
  { name: 'Overworld_ChangeMusicTo', ret: "void", arity: 1, params: "u16 newMusic" },
  { name: 'GetMapMusicFadeoutSpeed', ret: "u8", arity: 0, params: "void" },
  { name: 'TryFadeOutOldMapMusic', ret: "void", arity: 0, params: "void" },
  { name: 'BGMusicStopped', ret: "bool8", arity: 0, params: "void" },
  { name: 'Overworld_FadeOutMapMusic', ret: "void", arity: 0, params: "void" },
  { name: 'PlayAmbientCry', ret: "void", arity: 0, params: "void" },
  { name: 'UpdateAmbientCry', ret: "void", arity: 2, params: "s16 *state, u16 *delayCounter" },
  { name: 'GetMapTypeByGroupAndId', ret: "u8", arity: 2, params: "s8 mapGroup, s8 mapNum" },
  { name: 'GetMapTypeByWarpData', ret: "u8", arity: 1, params: "struct WarpData *warp" },
  { name: 'GetCurrentMapType', ret: "u8", arity: 0, params: "void" },
  { name: 'GetLastUsedWarpMapType', ret: "u8", arity: 0, params: "void" },
  { name: 'IsMapTypeOutdoors', ret: "bool8", arity: 1, params: "u8 mapType" },
  { name: 'Overworld_MapTypeAllowsTeleportAndFly', ret: "bool8", arity: 1, params: "u8 mapType" },
  { name: 'IsMapTypeIndoors', ret: "bool8", arity: 1, params: "u8 mapType" },
  { name: 'GetSavedWarpRegionMapSectionId', ret: "mapsec_u8_t", arity: 0, params: "void" },
  { name: 'GetCurrentRegionMapSectionId', ret: "mapsec_u8_t", arity: 0, params: "void" },
  { name: 'GetCurrentMapBattleScene', ret: "u8", arity: 0, params: "void" },
  { name: 'InitOverworldBgs', ret: "void", arity: 0, params: "void" },
  { name: 'CleanupOverworldWindowsAndTilemaps', ret: "void", arity: 0, params: "void" },
  { name: 'ResetSafariZoneFlag_', ret: "void", arity: 0, params: "void" },
  { name: 'IsOverworldLinkActive', ret: "bool32", arity: 0, params: "void" },
  { name: 'DoCB1_Overworld', ret: "void", arity: 2, params: "u16 newKeys, u16 heldKeys" },
  { name: 'CB1_Overworld', ret: "void", arity: 0, params: "void" },
  { name: 'OverworldBasic', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_OverworldBasic', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_Overworld', ret: "void", arity: 0, params: "void" },
  { name: 'SetMainCallback1', ret: "void", arity: 1, params: "MainCallback cb" },
  { name: 'SetUnusedCallback', ret: "void", arity: 1, params: "void *func" },
  { name: 'RunFieldCallback', ret: "bool8", arity: 0, params: "void" },
  { name: 'FieldCB_DefaultWarpExit', ret: "else", arity: 0, params: "" },
  { name: 'CB2_NewGame', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_WhiteOut', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_LoadMap', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToFieldContestHall', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToFieldCableClub', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToField', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToFieldFromMultiplayer', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToFieldWithOpenMenu', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToFieldContinueScript', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToFieldContinueScriptPlayMapMusic', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ReturnToFieldFadeFromBlack', ret: "void", arity: 0, params: "void" },
  { name: 'FieldCB_FadeTryShowMapPopup', ret: "void", arity: 0, params: "void" },
  { name: 'CB2_ContinueSavedGame', ret: "void", arity: 0, params: "void" },
  { name: 'InitMapFromSavedGame', ret: "else", arity: 0, params: "" },
  { name: 'InitCurrentFlashLevelScanlineEffect', ret: "void", arity: 0, params: "void" },
  { name: 'InitObjectEventPalettes', ret: "else", arity: 1, params: "1" },
  { name: 'ResetAllMultiplayerState', ret: "void", arity: 0, params: "void" },
  { name: 'CheckRfuKeepAliveTimer', ret: "void", arity: 0, params: "void" },
  { name: 'AreAllPlayersInLinkState', ret: "bool32", arity: 1, params: "u16 state" },
  { name: 'IsAnyPlayerInLinkState', ret: "bool32", arity: 1, params: "u16 state" },
  { name: 'HandleLinkPlayerKeyInput', ret: "void", arity: 4, params: "u32 playerId, u16 key, struct CableClubPlayer *trainer, u16 *forceFacing" },
  { name: 'KeyInterCB_ReadButtons', ret: "u16", arity: 1, params: "u32 key" },
  { name: 'KeyInterCB_Idle', ret: "u16", arity: 1, params: "u32 key" },
  { name: 'KeyInterCB_ExitingSeat', ret: "u16", arity: 1, params: "u32 key" },
  { name: 'KeyInterCB_Ready', ret: "u16", arity: 1, params: "u32 keyOrPlayerId" },
  { name: 'KeyInterCB_SetReady', ret: "u16", arity: 1, params: "u32 key" },
  { name: 'KeyInterCB_WaitForPlayersToExit', ret: "u16", arity: 1, params: "u32 keyOrPlayerId" },
  { name: 'KeyInterCB_SendExitRoomKey', ret: "u16", arity: 1, params: "u32 key" },
  { name: 'KeyInterCB_InLinkActivity', ret: "u16", arity: 1, params: "u32 key" },
  { name: 'GetCableClubPartnersReady', ret: "u32", arity: 0, params: "void" },
  { name: 'IsAnyPlayerExitingCableClub', ret: "UNUSED", arity: 0, params: "void" },
  { name: 'SetInCableClubSeat', ret: "u16", arity: 0, params: "void" },
  { name: 'SetLinkWaitingForScript', ret: "u16", arity: 0, params: "void" },
  { name: 'QueueExitLinkRoomKey', ret: "u16", arity: 0, params: "void" },
  { name: 'SetStartedCableClubActivity', ret: "u16", arity: 0, params: "void" },
  { name: 'Overworld_IsRecvQueueAtMax', ret: "bool32", arity: 0, params: "void" },
  { name: 'Overworld_RecvKeysFromLinkIsRunning', ret: "bool32", arity: 0, params: "void" },
  { name: 'Overworld_SendKeysToLinkIsRunning', ret: "bool32", arity: 0, params: "void" },
  { name: 'IsSendingKeysOverCable', ret: "bool32", arity: 0, params: "void" },
  { name: 'ClearLinkPlayerObjectEvents', ret: "void", arity: 0, params: "void" },
  { name: 'SetLinkPlayerObjectRange', ret: "UNUSED", arity: 2, params: "u8 linkPlayerId, u8 dir" },
  { name: 'DestroyLinkPlayerObject', ret: "UNUSED", arity: 1, params: "u8 linkPlayerId" },
  { name: 'GetLinkPlayerObjectStepTimer', ret: "UNUSED", arity: 1, params: "u8 linkPlayerId" },
] as const;

// ─── CB2_* (callback / scene entry points) ──────────────────────────────────
export const CB2_NAMES = [
  'CB2_ContinueSavedGame',
  'CB2_LoadMap',
  'CB2_LoadMap2',
  'CB2_LoadMapOnReturnToFieldCableClub',
  'CB2_NewGame',
  'CB2_Overworld',
  'CB2_OverworldBasic',
  'CB2_ReturnToField',
  'CB2_ReturnToFieldCableClub',
  'CB2_ReturnToFieldContestHall',
  'CB2_ReturnToFieldContinueScript',
  'CB2_ReturnToFieldContinueScriptPlayMapMusic',
  'CB2_ReturnToFieldFadeFromBlack',
  'CB2_ReturnToFieldFromMultiplayer',
  'CB2_ReturnToFieldLink',
  'CB2_ReturnToFieldLocal',
  'CB2_ReturnToFieldWithOpenMenu',
  'CB2_WhiteOut',
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'overworld.h',
  'battle_pyramid.h',
  'battle_setup.h',
  'berry.h',
  'bg.h',
  'cable_club.h',
  'clock.h',
  'event_data.h',
  'event_object_movement.h',
  'event_scripts.h',
  'field_camera.h',
  'field_control_avatar.h',
  'field_effect.h',
  'field_message_box.h',
  'field_player_avatar.h',
  'field_screen_effect.h',
  'field_special_scene.h',
  'field_specials.h',
  'field_tasks.h',
  'field_weather.h',
  'fieldmap.h',
  'fldeff.h',
  'gpu_regs.h',
  'heal_location.h',
  'io_reg.h',
  'link.h',
  'link_rfu.h',
  'load_save.h',
  'main.h',
  'malloc.h',
  'm4a.h',
  'map_name_popup.h',
  'match_call.h',
  'menu.h',
  'metatile_behavior.h',
  'mirage_tower.h',
  'money.h',
  'new_game.h',
  'palette.h',
  'play_time.h',
  'random.h',
  'roamer.h',
  'rotating_gate.h',
  'safari_zone.h',
  'save.h',
  'save_location.h',
  'script.h',
  'script_pokemon_util.h',
  'secret_base.h',
  'sound.h',
  'start_menu.h',
  'task.h',
  'tileset_anims.h',
  'time_events.h',
  'trainer_hill.h',
  'trainer_pokemon_sprites.h',
  'tv.h',
  'scanline_effect.h',
  'wild_encounter.h',
  'frontier_util.h',
  'constants/abilities.h',
  'constants/layouts.h',
  'constants/map_types.h',
  'constants/region_map_sections.h',
  'constants/songs.h',
  'constants/trainer_hill.h',
  'constants/weather.h',
] as const;
