// AUTO-GENERATED by scripts/transpile-callbacks.mjs
// Source : src/pokeblock_feed.c (via SPRITE_CALLBACKS / TASKS / SPRITE_CBS / CB2S)
// Generated : 2026-04-29
// DO NOT EDIT — re-run `node scripts/transpile-callbacks.mjs` to refresh.
//
// Symbol substitution rules in script header.
// Manual fixes may be needed for /* TODO */ markers and undefined constants below.

/* eslint-disable */
// @ts-nocheck

import type { DecompRuntime, DecompSprite, DecompTask } from '../../../decomp-runtime';
import {
  Sin, Cos, Q_8_8_TO_INT, SetOamMatrix, CalcCenterToCornerVec,
  ST_OAM_AFFINE_OFF, ST_OAM_AFFINE_NORMAL, ST_OAM_AFFINE_DOUBLE, ST_OAM_AFFINE_ERASE,
  ST_OAM_OBJ_NORMAL, ST_OAM_OBJ_BLEND, ST_OAM_OBJ_WINDOW,
  ST_OAM_4BPP, ST_OAM_8BPP,
  RGB, RGB_BLACK, RGB_WHITE, RGB_WHITEALPHA,
  PLTT_SIZEOF, PLTT_SIZE_4BPP, PLTT_SIZE_8BPP,
  OBJ_PLTT_ID_FADED, BG_PLTT_ID_FADED,
  BLDALPHA_BLEND, WIN_RANGE, GET_TRUE_SPRITE_INDEX, ANIM_SPRITES_START,
  gSineTable, PaletteBuffer, FreeAllSpritePalettes,
} from '../../../decomp-helpers';
import {
  FreeAllSpritePalettes,
  FreeAllWindowBuffers,
  FreeMonSpritesGfx,
  StringExpandPlaceholders,
  UpdatePaletteFade,
  gMPlayInfo_BGM,
  gSaveBlock1Ptr,
  gStringVar4,
} from '../../../decomp-globals';
// Constants resolved from decomp #defines / enums / TS data modules :
const FONT_NORMAL = 1;
const STATE_PRINT_MSG = 297;
const STATE_SPAWN_PBLOCK = 269;
const STATE_START_JUMP = 281;
const STATE_START_THROW = 255;
const TEXT_COLOR_DARK_GRAY = 2;
const TEXT_COLOR_LIGHT_GRAY = 3;
const TEXT_COLOR_WHITE = 1;
const TRACKS_ALL = 65535;

export type SpriteCallback = (sprite: DecompSprite, rt: DecompRuntime) => void;
export type TaskCallback = (task: DecompTask, rt: DecompRuntime) => void;
export type CB2Callback = (rt: DecompRuntime) => void;

const _emptySprite: any = { data: new Array(16).fill(0), invisible: false, x: 0, y: 0, x2: 0, y2: 0, oamIndex: 0, spriteId: -1 };
const _emptyTask: any = { data: new Array(16).fill(0), func: null, taskId: -1 };
function _gs(rt: DecompRuntime, id: number): DecompSprite { return (rt.gSprites.get(id) as DecompSprite) ?? _emptySprite; }
function _gt(rt: DecompRuntime, id: number): DecompTask { return (rt.gTasks.get(id) as DecompTask) ?? _emptyTask; }
function _palView(buf: PaletteBuffer, base: number): ArrayLike<number> {
  return new Proxy({ length: 512 }, { get(t, k) { if (k === 'length') return 512; const i = Number(k); return Number.isFinite(i) ? buf.get(base + i) : undefined; } }) as ArrayLike<number>;
}

/** Source: pokeblock_feed.c → SpriteCB_MonJumpForPokeblock */
export const SpriteCB_MonJumpForPokeblock: SpriteCallback = (sprite, rt) => {
  sprite.x += 4;
      sprite.y += sprite.data[0];
      sprite.data[0] += sprite.data[1];

       
      if (sprite.data[0] == 0)
          PlayCry_Normal(sprite.data[2], 0);

      if (sprite.data[0] == 9)
          sprite.callback = SpriteCallbackDummy;
};

/** Source: pokeblock_feed.c → SpriteCB_ThrownPokeblock */
export const SpriteCB_ThrownPokeblock: SpriteCallback = (sprite, rt) => {
  sprite.x -= 4;
      sprite.y += sprite.data[0];
      sprite.data[0] += sprite.data[1];
      if (sprite.data[0] == 10)
          rt.DestroySprite(sprite.spriteId);
};

/** Source: pokeblock_feed.c → Task_HandlePokeblockFeed */
export const Task_HandlePokeblockFeed: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          switch (task.data[0])
          {
          case 0:
              sPokeblockFeed.animRunState = 0;
              sPokeblockFeed.timer = 0;
              CalculateMonAnimLength();
              break;
          case STATE_START_THROW:
              DoPokeblockCaseThrowEffect(sPokeblockFeed.pokeblockCaseSpriteId, task.data[1]);
              break;
          case STATE_SPAWN_PBLOCK:
              sPokeblockFeed.pokeblockSpriteId = CreatePokeblockSprite();
              break;
          case STATE_START_JUMP:
              StartMonJumpForPokeblock(sPokeblockFeed.monSpriteId);
              break;
          case STATE_PRINT_MSG:
              task.func = (t) => Task_PrintAtePokeblockMessage(t, rt);
              return;
          }

          if (sPokeblockFeed.timer < sPokeblockFeed.monAnimLength)
              UpdateMonAnim();
          else if (sPokeblockFeed.timer == sPokeblockFeed.monAnimLength)
              task.data[0] = STATE_START_THROW - 1;

          sPokeblockFeed.timer++;
          task.data[0]++;
      }
};

/** Source: pokeblock_feed.c → Task_WaitForAtePokeblockMessage */
export const Task_WaitForAtePokeblockMessage: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (RunTextPrintersRetIsActive(0) != true)
          task.func = (t) => Task_FadeOutPokeblockFeed(t, rt);
};

/** Source: pokeblock_feed.c → Task_PrintAtePokeblockMessage */
export const Task_PrintAtePokeblockMessage: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let mon: any = gPlayerParty[gPokeblockMonId];
      let pokeblock: any = gSaveBlock1Ptr.pokeblocks[gSpecialVar_ItemId];

      gPokeblockGain = PokeblockGetGain(GetNature(mon), pokeblock);
      GetMonNickname(mon, gStringVar1);
      PokeblockCopyName(pokeblock, gStringVar2);

      if (gPokeblockGain == 0)
          StringExpandPlaceholders(gStringVar4, gText_Var1AteTheVar2);
      else if (gPokeblockGain > 0)
          StringExpandPlaceholders(gStringVar4, gText_Var1HappilyAteVar2);
      else
          StringExpandPlaceholders(gStringVar4, gText_Var1DisdainfullyAteVar2);

      gTextFlags.canABSpeedUpPrint = true;
      AddTextPrinterParameterized2(0, FONT_NORMAL, gStringVar4, GetPlayerTextSpeedDelay(), null, TEXT_COLOR_DARK_GRAY, TEXT_COLOR_WHITE, TEXT_COLOR_LIGHT_GRAY);
      task.func = (t) => Task_WaitForAtePokeblockMessage(t, rt);
};

/** Source: pokeblock_feed.c → Task_ExitPokeblockFeed */
export const Task_ExitPokeblockFeed: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          rt.ResetSpriteData();
          FreeAllSpritePalettes();
          m4aMPlayVolumeControl(gMPlayInfo_BGM, TRACKS_ALL, 0x100);
          rt.SetMainCallback2(gMain.savedCallback ?? null);
          rt.DestroyTask(taskId);
          FreeAllWindowBuffers();
          Free(sPokeblockFeed);
          FreeMonSpritesGfx();
      }
};

/** Source: pokeblock_feed.c → Task_FadeOutPokeblockFeed */
export const Task_FadeOutPokeblockFeed: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 16, "RGB_BLACK");
      task.func = (t) => Task_ExitPokeblockFeed(t, rt);
};

/** Source: pokeblock_feed.c → CB2_PokeblockFeed */
export const CB2_PokeblockFeed: CB2Callback = (rt) => {
  RunTasks();
      AnimateSprites();
      BuildOamBuffer();
      DoScheduledBgTilemapCopiesToVram();
      UpdatePaletteFade();
};
