// AUTO-GENERATED by scripts/transpile-callbacks.mjs
// Source : src/pokedex.c (via SPRITE_CALLBACKS / TASKS / SPRITE_CBS / CB2S)
// Generated : 2026-04-27
// DO NOT EDIT — re-run `node scripts/transpile-callbacks.mjs` to refresh.
//
// Symbol substitution rules in script header.
// Manual fixes may be needed for /* TODO */ markers and undefined constants below.

/* eslint-disable */
// @ts-nocheck

import type { DecompRuntime, DecompSprite, DecompTask } from '../../../decomp-runtime';
import {
  Sin, Cos, Q_8_8_TO_INT, SetOamMatrix, CalcCenterToCornerVec,
  ST_OAM_AFFINE_OFF, ST_OAM_AFFINE_NORMAL, ST_OAM_AFFINE_DOUBLE, ST_OAM_AFFINE_ERASE,
  ST_OAM_OBJ_NORMAL, ST_OAM_OBJ_BLEND, ST_OAM_OBJ_WINDOW,
  ST_OAM_4BPP, ST_OAM_8BPP,
  RGB, RGB_BLACK, RGB_WHITE, RGB_WHITEALPHA,
  PLTT_SIZEOF, PLTT_SIZE_4BPP, PLTT_SIZE_8BPP,
  OBJ_PLTT_ID_FADED, BG_PLTT_ID_FADED,
  BLDALPHA_BLEND, WIN_RANGE, GET_TRUE_SPRITE_INDEX, ANIM_SPRITES_START,
  gSineTable, PaletteBuffer,
} from '../../../decomp-helpers';
// Constants resolved from decomp #defines / enums / TS data modules :
const A_BUTTON = 1;
const AREA_SCREEN = 0;
const B_BUTTON = 2;
const CANCEL_SCREEN = 3;
const COPYWIN_FULL = 3;
const COPYWIN_GFX = 2;
const CRY_PRIORITY_NORMAL = 10;
const CRY_SCREEN = 1;
const CRY_VOLUME_RS = 125;
const DEX_MODE_HOENN = 0;
const DPAD_DOWN = 128;
const DPAD_LEFT = 32;
const DPAD_RIGHT = 16;
const DPAD_UP = 64;
const FLAG_GET_CAUGHT = 1;
const FLAG_GET_SEEN = 0;
const FONT_NORMAL = 1;
const L_BUTTON = 512;
const MAX_SEARCH_PARAM_CURSOR_POS = 5;
const MON_PAGE_X = 48;
const MON_PAGE_Y = 56;
const NUM_TASK_DATA = 16;
const OAM = 117440512;
const OAM_SIZE = 1024;
const OPTIONS_BUTTON_MODE_LR = 1;
const PAGE_AREA = 5;
const PAGE_CRY = 6;
const PAGE_INFO = 1;
const PAGE_MAIN = 0;
const PAGE_SEARCH = 2;
const PAGE_SEARCH_RESULTS = 3;
const PAGE_SIZE = 7;
const POKEBALL_ROTATION_BOTTOM = 48;
const POKEBALL_ROTATION_TOP = 64;
const R_BUTTON = 256;
const SEARCH_COLOR = 1;
const SEARCH_MODE = 5;
const SEARCH_NAME = 0;
const SEARCH_OK = 6;
const SEARCH_ORDER = 4;
const SEARCH_TOPBAR_CANCEL = 2;
const SEARCH_TOPBAR_SEARCH = 0;
const SEARCH_TOPBAR_SHIFT = 1;
const SEARCH_TYPE_LEFT = 2;
const SEARCH_TYPE_RIGHT = 3;
const SELECT_BUTTON = 4;
const SIZE_SCREEN = 2;
const START_BUTTON = 8;
const TRACKS_ALL = 65535;
const VRAM = 100663296;
const VRAM_SIZE = 98304;
const WIN_CRY_WAVE = 2;
const WIN_FOOTPRINT = 1;
const WIN_INFO = 1;
const WIN_VU_METER = 3;
// Unresolved constants (auto-stub at 0; replace with real values when needed) :
const _UNDEFINED = 0;
const JOY_NEW: any = _UNDEFINED; // TODO : not found in decomp /include or auto/src — possibly dynamic
const JOY_REPEAT: any = _UNDEFINED; // TODO : not found in decomp /include or auto/src — possibly dynamic
const OBJ_PLTT_ID2: any = _UNDEFINED; // TODO : not found in decomp /include or auto/src — possibly dynamic
const PIXEL_FILL: any = _UNDEFINED; // TODO : not found in decomp /include or auto/src — possibly dynamic

export type SpriteCallback = (sprite: DecompSprite, rt: DecompRuntime) => void;
export type TaskCallback = (task: DecompTask, rt: DecompRuntime) => void;
export type CB2Callback = (rt: DecompRuntime) => void;

const _emptySprite: any = { data: new Array(16).fill(0), invisible: false, x: 0, y: 0, x2: 0, y2: 0, oamIndex: 0, spriteId: -1 };
const _emptyTask: any = { data: new Array(16).fill(0), func: null, taskId: -1 };
function _gs(rt: DecompRuntime, id: number): DecompSprite { return (rt.gSprites.get(id) as DecompSprite) ?? _emptySprite; }
function _gt(rt: DecompRuntime, id: number): DecompTask { return (rt.gTasks.get(id) as DecompTask) ?? _emptyTask; }
function _palView(buf: PaletteBuffer, base: number): ArrayLike<number> {
  return new Proxy({ length: 512 }, { get(t, k) { if (k === 'length') return 512; const i = Number(k); return Number.isFinite(i) ? buf.get(base + i) : undefined; } }) as ArrayLike<number>;
}

/** Source: pokedex.c (failed: empty bodyC) */
export const SpriteCB_EndMoveMonForInfoScreen: SpriteCallback = (_sprite, _rt) => { /* TODO empty bodyC */ };

/** Source: pokedex.c → SpriteCB_SeenOwnInfo */
export const SpriteCB_SeenOwnInfo: SpriteCallback = (sprite, rt) => {
  if (sPokedexView.currentPage != PAGE_MAIN)
          rt.DestroySprite(sprite.spriteId);
};

/** Source: pokedex.c → SpriteCB_MoveMonForInfoScreen */
export const SpriteCB_MoveMonForInfoScreen: SpriteCallback = (sprite, rt) => {
  rt.gba.oam[sprite.oamIndex].priority = 0;
      rt.gba.oam[sprite.oamIndex].affineMode = ST_OAM_AFFINE_OFF;
      sprite.x2 = 0;
      sprite.y2 = 0;
      if (sprite.x != MON_PAGE_X || sprite.y != MON_PAGE_Y)
      {
          if (sprite.x > MON_PAGE_X)
              sprite.x--;
          if (sprite.x < MON_PAGE_X)
              sprite.x++;

          if (sprite.y > MON_PAGE_Y)
              sprite.y--;
          if (sprite.y < MON_PAGE_Y)
              sprite.y++;
      }
      else
      {
          sprite.callback = SpriteCB_EndMoveMonForInfoScreen;
      }
};

/** Source: pokedex.c → SpriteCB_PokedexListMonSprite */
export const SpriteCB_PokedexListMonSprite: SpriteCallback = (sprite, rt) => {
  let monId = sprite.data[1];

      if (sPokedexView.currentPage != PAGE_MAIN && sPokedexView.currentPage != PAGE_SEARCH_RESULTS)
      {
          FreeAndDestroyMonPicSprite(sPokedexView.monSpriteIds[monId]);
          sPokedexView.monSpriteIds[monId] = 0xFFFF;
      }
      else
      {
          let _var = 0;
          sprite.y2 = gSineTable[sprite.data[5]] * 76 / 256;
          _var = ((gSineTable[sprite.data[5] + 64]) === 0 ? 0 : ((0x10000) / (gSineTable[sprite.data[5] + 64])) | 0);
          if (_var > 0xFFFF)
              _var = 0xFFFF;
          SetOamMatrix(rt.gba, sprite.data[1] + 1, 0x100, 0, 0, _var);
          rt.gba.oam[sprite.oamIndex].affineParamIndex = monId + 1;

          if (sprite.data[5] > -64 && sprite.data[5] < 64)
          {
              sprite.invisible = false;
              sprite.data[0] = 1;
          }
          else
          {
              sprite.invisible = true;
          }

          if ((sprite.data[5] <= -64 || sprite.data[5] >= 64) && sprite.data[0] != 0)
          {
              FreeAndDestroyMonPicSprite(sPokedexView.monSpriteIds[monId]);
              sPokedexView.monSpriteIds[monId] = 0xFFFF;
          }
      }
};

/** Source: pokedex.c → SpriteCB_Scrollbar */
export const SpriteCB_Scrollbar: SpriteCallback = (sprite, rt) => {
  if (sPokedexView.currentPage != PAGE_MAIN && sPokedexView.currentPage != PAGE_SEARCH_RESULTS)
          rt.DestroySprite(sprite.spriteId);
      else
          sprite.y2 = sPokedexView.selectedPokemon * 120 / (sPokedexView.pokemonListCount - 1);
};

/** Source: pokedex.c → SpriteCB_ScrollArrow */
export const SpriteCB_ScrollArrow: SpriteCallback = (sprite, rt) => {
  if (sPokedexView.currentPage != PAGE_MAIN && sPokedexView.currentPage != PAGE_SEARCH_RESULTS)
      {
          rt.DestroySprite(sprite.spriteId);
      }
      else
      {
          let r0 = 0;

          if (sprite.data[1])
          {
              if (sPokedexView.selectedPokemon == sPokedexView.pokemonListCount - 1)
                  sprite.invisible = true;
              else
                  sprite.invisible = false;
              r0 = sprite.data[2];
          }
          else
          {
              if (sPokedexView.selectedPokemon == 0)
                  sprite.invisible = true;
              else
                  sprite.invisible = false;
              r0 = sprite.data[2] - 128;
          }
          sprite.y2 = gSineTable[r0] / 64;
          sprite.data[2] = sprite.data[2] + 8;
          if (sPokedexView.menuIsOpen == false && sPokedexView.menuY == 0 && sprite.invisible == false)
              sprite.invisible = false;
          else
              sprite.invisible = true;
      }
};

/** Source: pokedex.c → SpriteCB_DexListInterfaceText */
export const SpriteCB_DexListInterfaceText: SpriteCallback = (sprite, rt) => {
  if (sPokedexView.currentPage != PAGE_MAIN && sPokedexView.currentPage != PAGE_SEARCH_RESULTS)
          rt.DestroySprite(sprite.spriteId);
};

/** Source: pokedex.c → SpriteCB_RotatingPokeBall */
export const SpriteCB_RotatingPokeBall: SpriteCallback = (sprite, rt) => {
  if (sPokedexView.currentPage != PAGE_MAIN && sPokedexView.currentPage != PAGE_SEARCH_RESULTS)
      {
          rt.DestroySprite(sprite.spriteId);
      }
      else
      {
          let val = 0;
          let r3 = 0;
          let r0 = 0;

          val = sPokedexView.pokeBallRotation + sprite.data[1];
          r3 = gSineTable[val];
          r0 = gSineTable[val + 64];
          SetOamMatrix(rt.gba, sprite.data[0], r0, r3, -r3, r0);

          val = sPokedexView.pokeBallRotation + (sprite.data[1] + 64);
          r3 = gSineTable[val];
          r0 = gSineTable[val + 64];
          sprite.x2 = r0 * 40 / 256;
          sprite.y2 = r3 * 40 / 256;
      }
};

/** Source: pokedex.c → SpriteCB_DexListStartMenuCursor */
export const SpriteCB_DexListStartMenuCursor: SpriteCallback = (sprite, rt) => {
  if (sPokedexView.currentPage != PAGE_MAIN && sPokedexView.currentPage != PAGE_SEARCH_RESULTS)
      {
          rt.DestroySprite(sprite.spriteId);
      }
      else
      {
          let r1 = sPokedexView.currentPage == PAGE_MAIN ? 80 : 96;

          if (sPokedexView.menuIsOpen && sPokedexView.menuY == r1)
          {
              sprite.invisible = false;
              sprite.y2 = sPokedexView.menuCursorPos * 16;
              sprite.x2 = gSineTable[sprite.data[2]] / 64;
              sprite.data[2] += 8;
          }
          else
          {
              sprite.invisible = true;
          }
      }
};

/** Source: pokedex.c → SpriteCB_SlideCaughtMonToCenter */
export const SpriteCB_SlideCaughtMonToCenter: SpriteCallback = (sprite, rt) => {
  if (sprite.x < DISPLAY_WIDTH / 2)
          sprite.x += 2;
      if (sprite.x > DISPLAY_WIDTH / 2)
          sprite.x -= 2;

      if (sprite.y < DISPLAY_HEIGHT / 2)
          sprite.y += 1;
      if (sprite.y > DISPLAY_HEIGHT / 2)
          sprite.y -= 1;
};

/** Source: pokedex.c → SpriteCB_SearchParameterScrollArrow */
export const SpriteCB_SearchParameterScrollArrow: SpriteCallback = (sprite, rt) => {
  if (_gt(rt, sprite.data[0]).func == Task_HandleSearchParameterInput)
      {
          let val = 0;

          if (sprite.data[1])
          {
              if (SearchParamCantScrollDown(sprite.data[0]))
                  sprite.invisible = true;
              else
                  sprite.invisible = false;
          }
          else
          {
              if (SearchParamCantScrollUp(sprite.data[0]))
                  sprite.invisible = true;
              else
                  sprite.invisible = false;
          }
          val = sprite.data[2] + sprite.data[1] * 128;
          sprite.y2 = gSineTable[val] / 128;
          sprite.data[2] += 8;
      }
      else
      {
          sprite.invisible = true;
      }
};

/** Source: pokedex.c → Task_OpenPokedexMainPage */
export const Task_OpenPokedexMainPage: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  sPokedexView.isSearchResults = false;
      if (LoadPokedexListPage(PAGE_MAIN))
          task.func = (t) => Task_HandlePokedexInput(t, rt);
};

/** Source: pokedex.c → Task_HandlePokedexInput */
export const Task_HandlePokedexInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  rt.SetGpuReg(REG_OFFSET_BG0VOFS, sPokedexView.menuY);

      if (sPokedexView.menuY)
      {
          sPokedexView.menuY -= 8;
      }
      else
      {
          if (JOY_NEW(A_BUTTON) && sPokedexView.pokedexList[sPokedexView.selectedPokemon].seen)
          {
              UpdateSelectedMonSpriteId();
              rt.BeginNormalPaletteFade("~(1 << (rt.gba.oam[_gs(rt, sPokedexView.selectedMonSpriteId).oamIndex].paletteBank + 16))", 0, 0, 0x10, "RGB_BLACK");
              rt.setSpriteCallback(sPokedexView.selectedMonSpriteId, SpriteCB_MoveMonForInfoScreen);
              task.func = (t) => Task_OpenInfoScreenAfterMonMovement(t, rt);
              /* TODO sound PlaySE */;
              FreeWindowAndBgBuffers();
          }
          else if (JOY_NEW(START_BUTTON))
          {
              sPokedexView.menuY = 0;
              sPokedexView.menuIsOpen = true;
              sPokedexView.menuCursorPos = 0;
              task.func = (t) => Task_HandlePokedexStartMenuInput(t, rt);
              /* TODO sound PlaySE */;
          }
          else if (JOY_NEW(SELECT_BUTTON))
          {
              /* TODO sound PlaySE */;
              rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 0x10, "RGB_BLACK");
              task.data[0] = LoadSearchMenu();
              sPokedexView.screenSwitchState = 0;
              sPokedexView.pokeBallRotationBackup = sPokedexView.pokeBallRotation;
              sPokedexView.selectedPokemonBackup = sPokedexView.selectedPokemon;
              sPokedexView.dexModeBackup = sPokedexView.dexMode;
              sPokedexView.dexOrderBackup = sPokedexView.dexOrder;
              task.func = (t) => Task_WaitForExitSearch(t, rt);
              /* TODO sound PlaySE */;
              FreeWindowAndBgBuffers();
          }
          else if (JOY_NEW(B_BUTTON))
          {
              rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 0x10, "RGB_BLACK");
              task.func = (t) => Task_ClosePokedex(t, rt);
              /* TODO sound PlaySE */;
          }
          else
          {
               
              sPokedexView.selectedPokemon = TryDoPokedexScroll(sPokedexView.selectedPokemon, 0xE);
              if (sPokedexView.scrollTimer)
                  task.func = (t) => Task_WaitForScroll(t, rt);
          }
      }
};

/** Source: pokedex.c → Task_WaitForScroll */
export const Task_WaitForScroll: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (UpdateDexListScroll(sPokedexView.scrollDirection, sPokedexView.scrollMonIncrement, sPokedexView.maxScrollTimer))
          task.func = (t) => Task_HandlePokedexInput(t, rt);
};

/** Source: pokedex.c → Task_HandlePokedexStartMenuInput */
export const Task_HandlePokedexStartMenuInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  rt.SetGpuReg(REG_OFFSET_BG0VOFS, sPokedexView.menuY);

       
      if (sPokedexView.menuY != 80)
      {
          sPokedexView.menuY += 8;
      }
      else
      {
          if (JOY_NEW(A_BUTTON))
          {
              switch (sPokedexView.menuCursorPos)
              {
              case 0:  
              default:
                  gMain.newKeys |= START_BUTTON;   
                  break;
              case 1:  
                  sPokedexView.selectedPokemon = 0;
                  sPokedexView.pokeBallRotation = POKEBALL_ROTATION_TOP;
                  ClearMonSprites();
                  CreateMonSpritesAtPos(sPokedexView.selectedPokemon, 0xE);
                  gMain.newKeys |= START_BUTTON;   
                  break;
              case 2:  
                  sPokedexView.selectedPokemon = sPokedexView.pokemonListCount - 1;
                  sPokedexView.pokeBallRotation = sPokedexView.pokemonListCount * 16 + POKEBALL_ROTATION_BOTTOM;
                  ClearMonSprites();
                  CreateMonSpritesAtPos(sPokedexView.selectedPokemon, 0xE);
                  gMain.newKeys |= START_BUTTON;   
                  break;
              case 3:  
                  rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 0x10, "RGB_BLACK");
                  task.func = (t) => Task_ClosePokedex(t, rt);
                  /* TODO sound PlaySE */;
                  break;
              }
          }

           
          if (JOY_NEW(START_BUTTON | B_BUTTON))
          {
              sPokedexView.menuIsOpen = false;
              task.func = (t) => Task_HandlePokedexInput(t, rt);
              /* TODO sound PlaySE */;
          }
          else if (JOY_REPEAT(DPAD_UP) && sPokedexView.menuCursorPos != 0)
          {
              sPokedexView.menuCursorPos--;
              /* TODO sound PlaySE */;
          }
          else if (JOY_REPEAT(DPAD_DOWN) && sPokedexView.menuCursorPos < 3)
          {
              sPokedexView.menuCursorPos++;
              /* TODO sound PlaySE */;
          }
      }
};

/** Source: pokedex.c → Task_OpenInfoScreenAfterMonMovement */
export const Task_OpenInfoScreenAfterMonMovement: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (_gs(rt, sPokedexView.selectedMonSpriteId).x == MON_PAGE_X && _gs(rt, sPokedexView.selectedMonSpriteId).y == MON_PAGE_Y)
      {
          sPokedexView.currentPageBackup = sPokedexView.currentPage;
          task.data[0] = LoadInfoScreen(sPokedexView.pokedexList[sPokedexView.selectedPokemon], sPokedexView.selectedMonSpriteId);
          task.func = (t) => Task_WaitForExitInfoScreen(t, rt);
      }
};

/** Source: pokedex.c → Task_WaitForExitInfoScreen */
export const Task_WaitForExitInfoScreen: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (_gt(rt, task.data[0]).isActive)
      {
           
          if (sPokedexView.currentPage == PAGE_INFO && !IsInfoScreenScrolling(task.data[0]) && TryDoInfoScreenScroll())
              StartInfoScreenScroll(sPokedexView.pokedexList[sPokedexView.selectedPokemon], task.data[0]);
      }
      else
      {
           
          sLastSelectedPokemon = sPokedexView.selectedPokemon;
          sPokeBallRotation = sPokedexView.pokeBallRotation;
          task.func = (t) => Task_OpenPokedexMainPage(t, rt);
      }
};

/** Source: pokedex.c → Task_WaitForExitSearch */
export const Task_WaitForExitSearch: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!_gt(rt, task.data[0]).isActive)
      {
          ClearMonSprites();

           
          if (sPokedexView.screenSwitchState != 0)
          {
              sPokedexView.selectedPokemon = 0;
              sPokedexView.pokeBallRotation = POKEBALL_ROTATION_TOP;
              task.func = (t) => Task_OpenSearchResults(t, rt);
          }
           
          else
          {
              sPokedexView.pokeBallRotation = sPokedexView.pokeBallRotationBackup;
              sPokedexView.selectedPokemon = sPokedexView.selectedPokemonBackup;
              sPokedexView.dexMode = sPokedexView.dexModeBackup;
              if (!IsNationalPokedexEnabled())
                  sPokedexView.dexMode = DEX_MODE_HOENN;
              sPokedexView.dexOrder = sPokedexView.dexOrderBackup;
              task.func = (t) => Task_OpenPokedexMainPage(t, rt);
          }
      }
};

/** Source: pokedex.c → Task_ClosePokedex */
export const Task_ClosePokedex: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          gSaveBlock2Ptr.pokedex.mode = sPokedexView.dexMode;
          if (!IsNationalPokedexEnabled())
              gSaveBlock2Ptr.pokedex.mode = DEX_MODE_HOENN;
          gSaveBlock2Ptr.pokedex.order = sPokedexView.dexOrder;
          ClearMonSprites();
          FreeWindowAndBgBuffers();
          rt.DestroyTask(taskId);
          /* TODO scene transition: SetMainCallback2(CB2_ReturnToFieldWithOpenMenu) */;
          m4aMPlayVolumeControl(gMPlayInfo_BGM, TRACKS_ALL, 0x100);
          Free(sPokedexView);
      }
};

/** Source: pokedex.c → Task_OpenSearchResults */
export const Task_OpenSearchResults: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  sPokedexView.isSearchResults = true;
      if (LoadPokedexListPage(PAGE_SEARCH_RESULTS))
          task.func = (t) => Task_HandleSearchResultsInput(t, rt);
};

/** Source: pokedex.c → Task_HandleSearchResultsInput */
export const Task_HandleSearchResultsInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  rt.SetGpuReg(REG_OFFSET_BG0VOFS, sPokedexView.menuY);

      if (sPokedexView.menuY)
      {
          sPokedexView.menuY -= 8;
      }
      else
      {
          if (JOY_NEW(A_BUTTON) && sPokedexView.pokedexList[sPokedexView.selectedPokemon].seen)
          {
              let a = 0;

              UpdateSelectedMonSpriteId();
              a = (1 << (rt.gba.oam[_gs(rt, sPokedexView.selectedMonSpriteId).oamIndex].paletteBank + 16));
              rt.setSpriteCallback(sPokedexView.selectedMonSpriteId, SpriteCB_MoveMonForInfoScreen);
              rt.BeginNormalPaletteFade("~a", 0, 0, 0x10, "RGB_BLACK");
              task.func = (t) => Task_OpenSearchResultsInfoScreenAfterMonMovement(t, rt);
              /* TODO sound PlaySE */;
              FreeWindowAndBgBuffers();
          }
          else if (JOY_NEW(START_BUTTON))
          {
              sPokedexView.menuY = 0;
              sPokedexView.menuIsOpen = true;
              sPokedexView.menuCursorPos = 0;
              task.func = (t) => Task_HandleSearchResultsStartMenuInput(t, rt);
              /* TODO sound PlaySE */;
          }
          else if (JOY_NEW(SELECT_BUTTON))
          {
              rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 0x10, "RGB_BLACK");
              task.data[0] = LoadSearchMenu();
              sPokedexView.screenSwitchState = 0;
              task.func = (t) => Task_WaitForExitSearch(t, rt);
              /* TODO sound PlaySE */;
              FreeWindowAndBgBuffers();
          }
          else if (JOY_NEW(B_BUTTON))
          {
              rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 0x10, "RGB_BLACK");
              task.func = (t) => Task_ReturnToPokedexFromSearchResults(t, rt);
              /* TODO sound PlaySE */;
          }
          else
          {
               
              sPokedexView.selectedPokemon = TryDoPokedexScroll(sPokedexView.selectedPokemon, 0xE);
              if (sPokedexView.scrollTimer)
                  task.func = (t) => Task_WaitForSearchResultsScroll(t, rt);
          }
      }
};

/** Source: pokedex.c → Task_WaitForSearchResultsScroll */
export const Task_WaitForSearchResultsScroll: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (UpdateDexListScroll(sPokedexView.scrollDirection, sPokedexView.scrollMonIncrement, sPokedexView.maxScrollTimer))
          task.func = (t) => Task_HandleSearchResultsInput(t, rt);
};

/** Source: pokedex.c → Task_HandleSearchResultsStartMenuInput */
export const Task_HandleSearchResultsStartMenuInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  rt.SetGpuReg(REG_OFFSET_BG0VOFS, sPokedexView.menuY);

      if (sPokedexView.menuY != 96)
      {
          sPokedexView.menuY += 8;
      }
      else
      {
          if (JOY_NEW(A_BUTTON))
          {
              switch (sPokedexView.menuCursorPos)
              {
              case 0:  
              default:
                  gMain.newKeys |= START_BUTTON;
                  break;
              case 1:  
                  sPokedexView.selectedPokemon = 0;
                  sPokedexView.pokeBallRotation = POKEBALL_ROTATION_TOP;
                  ClearMonSprites();
                  CreateMonSpritesAtPos(sPokedexView.selectedPokemon, 0xE);
                  gMain.newKeys |= START_BUTTON;
                  break;
              case 2:  
                  sPokedexView.selectedPokemon = sPokedexView.pokemonListCount - 1;
                  sPokedexView.pokeBallRotation = sPokedexView.pokemonListCount * 16 + POKEBALL_ROTATION_BOTTOM;
                  ClearMonSprites();
                  CreateMonSpritesAtPos(sPokedexView.selectedPokemon, 0xE);
                  gMain.newKeys |= START_BUTTON;
                  break;
              case 3:  
                  rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 0x10, "RGB_BLACK");
                  task.func = (t) => Task_ReturnToPokedexFromSearchResults(t, rt);
                  /* TODO sound PlaySE */;
                  break;
              case 4:  
                  rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 0x10, "RGB_BLACK");
                  task.func = (t) => Task_ClosePokedexFromSearchResultsStartMenu(t, rt);
                  /* TODO sound PlaySE */;
                  break;
              }
          }

           
          if (JOY_NEW(START_BUTTON | B_BUTTON))
          {
              sPokedexView.menuIsOpen = false;
              task.func = (t) => Task_HandleSearchResultsInput(t, rt);
              /* TODO sound PlaySE */;
          }
          else if (JOY_REPEAT(DPAD_UP) && sPokedexView.menuCursorPos)
          {
              sPokedexView.menuCursorPos--;
              /* TODO sound PlaySE */;
          }
          else if (JOY_REPEAT(DPAD_DOWN) && sPokedexView.menuCursorPos < 4)
          {
              sPokedexView.menuCursorPos++;
              /* TODO sound PlaySE */;
          }
      }
};

/** Source: pokedex.c → Task_OpenSearchResultsInfoScreenAfterMonMovement */
export const Task_OpenSearchResultsInfoScreenAfterMonMovement: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (_gs(rt, sPokedexView.selectedMonSpriteId).x == MON_PAGE_X && _gs(rt, sPokedexView.selectedMonSpriteId).y == MON_PAGE_Y)
      {
          sPokedexView.currentPageBackup = sPokedexView.currentPage;
          task.data[0] = LoadInfoScreen(sPokedexView.pokedexList[sPokedexView.selectedPokemon], sPokedexView.selectedMonSpriteId);
          sPokedexView.selectedMonSpriteId = -1;
          task.func = (t) => Task_WaitForExitSearchResultsInfoScreen(t, rt);
      }
};

/** Source: pokedex.c → Task_WaitForExitSearchResultsInfoScreen */
export const Task_WaitForExitSearchResultsInfoScreen: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (_gt(rt, task.data[0]).isActive)
      {
           
          if (sPokedexView.currentPage == PAGE_INFO && !IsInfoScreenScrolling(task.data[0]) && TryDoInfoScreenScroll())
              StartInfoScreenScroll(sPokedexView.pokedexList[sPokedexView.selectedPokemon], task.data[0]);
      }
      else
      {
           
          task.func = (t) => Task_OpenSearchResults(t, rt);
      }
};

/** Source: pokedex.c → Task_ReturnToPokedexFromSearchResults */
export const Task_ReturnToPokedexFromSearchResults: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          sPokedexView.pokeBallRotation = sPokedexView.pokeBallRotationBackup;
          sPokedexView.selectedPokemon = sPokedexView.selectedPokemonBackup;
          sPokedexView.dexMode = sPokedexView.dexModeBackup;
          if (!IsNationalPokedexEnabled())
              sPokedexView.dexMode = DEX_MODE_HOENN;
          sPokedexView.dexOrder = sPokedexView.dexOrderBackup;
          task.func = (t) => Task_OpenPokedexMainPage(t, rt);
          ClearMonSprites();
          FreeWindowAndBgBuffers();
      }
};

/** Source: pokedex.c → Task_ClosePokedexFromSearchResultsStartMenu */
export const Task_ClosePokedexFromSearchResultsStartMenu: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          sPokedexView.pokeBallRotation = sPokedexView.pokeBallRotationBackup;
          sPokedexView.selectedPokemon = sPokedexView.selectedPokemonBackup;
          sPokedexView.dexMode = sPokedexView.dexModeBackup;
          if (!IsNationalPokedexEnabled())
              sPokedexView.dexMode = DEX_MODE_HOENN;
          sPokedexView.dexOrder = sPokedexView.dexOrderBackup;
          task.func = (t) => Task_ClosePokedex(t, rt);
      }
};

/** Source: pokedex.c → Task_LoadInfoScreen */
export const Task_LoadInfoScreen: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  switch (gMain.state)
      {
      case 0:
      default:
          if (!rt.gPaletteFade.active)
          {
              let r2 = 0;

              sPokedexView.currentPage = PAGE_INFO;
              gPokedexVBlankCB = gMain.vblankCallback;
              /* noop SetVBlankCallback */;
              r2 = 0;
              if (task.data[1])
                  r2 += DISPCNT_OBJ_ON;
              if (task.data[2])
                  r2 |= DISPCNT_BG1_ON;
              ResetOtherVideoRegisters(r2);
              gMain.state = 1;
          }
          break;
      case 1:
          DecompressAndLoadBgGfxUsingHeap(3, gPokedexMenu_Gfx, 0x2000, 0, 0);
          CopyToBgTilemapBuffer(3, gPokedexInfoScreen_Tilemap, 0, 0);
          FillWindowPixelBuffer(WIN_INFO, PIXEL_FILL(0));
          PutWindowTilemap(WIN_INFO);
          PutWindowTilemap(WIN_FOOTPRINT);
          DrawFootprint(WIN_FOOTPRINT, sPokedexListItem.dexNum);
          CopyWindowToVram(WIN_FOOTPRINT, COPYWIN_GFX);
          gMain.state++;
          break;
      case 2:
          LoadScreenSelectBarMain(0xD);
          HighlightScreenSelectBarItem(sPokedexView.selectedScreen, 0xD);
          LoadPokedexBgPalette(sPokedexView.isSearchResults);
          gMain.state++;
          break;
      case 3:
          gMain.state++;
          break;
      case 4:
          PrintMonInfo(sPokedexListItem.dexNum, sPokedexView.dexMode == DEX_MODE_HOENN ? false : true, sPokedexListItem.owned, 0);
          if (!sPokedexListItem.owned)
              LoadPalette(rt.gPlttBufferUnfaded.get(BG_PLTT_ID(0) + 1), BG_PLTT_ID(3) + 1, PLTT_SIZEOF(16 - 1));
          CopyWindowToVram(WIN_INFO, COPYWIN_FULL);
          CopyBgTilemapBufferToVram(1);
          CopyBgTilemapBufferToVram(2);
          CopyBgTilemapBufferToVram(3);
          gMain.state++;
          break;
      case 5:
          if (!task.data[1])
          {
              task.data[3] = CreateMonSpriteFromNationalDexNumber(sPokedexListItem.dexNum, MON_PAGE_X, MON_PAGE_Y, 0);
              rt.gba.oam[_gs(rt, task.data[3]).oamIndex].priority = 0;
          }
          gMain.state++;
          break;
      case 6:
          {
              let preservedPalettes = 0;

              if (task.data[2])
                  preservedPalettes = 0x14;  
              if (task.data[1])
                  preservedPalettes |= (1 << (rt.gba.oam[_gs(rt, task.data[3]).oamIndex].paletteNum + 16));
              rt.BeginNormalPaletteFade("~preservedPalettes", 0, 16, 0, "RGB_BLACK");
              /* noop SetVBlankCallback */;
              gMain.state++;
          }
          break;
      case 7:
          rt.SetGpuReg(REG_OFFSET_BLDCNT, 0);
          rt.SetGpuReg(REG_OFFSET_BLDALPHA, 0);
          rt.SetGpuReg(REG_OFFSET_BLDY, 0);
          rt.SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_1D_MAP | DISPCNT_OBJ_ON);
          HideBg(0);
          ShowBg(1);
          ShowBg(2);
          ShowBg(3);
          gMain.state++;
          break;
      case 8:
          if (!rt.gPaletteFade.active)
          {
              gMain.state++;
              if (!task.data[3])
              {
                  StopCryAndClearCrySongs();
                  PlayCry_NormalNoDucking(NationalPokedexNumToSpecies(sPokedexListItem.dexNum), 0, CRY_VOLUME_RS, CRY_PRIORITY_NORMAL);
              }
              else
              {
                  gMain.state++;
              }
          }
          break;
      case 9:
          if (!IsCryPlayingOrClearCrySongs())
              gMain.state++;
          break;
      case 10:
          task.data[0] = false;
          task.data[1] = false;  
          task.data[2] = true;
          task.data[3] = true;
          task.func = (t) => Task_HandleInfoScreenInput(t, rt);
          gMain.state = 0;
          break;
      }
};

/** Source: pokedex.c → Task_HandleInfoScreenInput */
export const Task_HandleInfoScreenInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (task.data[0])
      {
           
          rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 16, "RGB_BLACK");
          task.func = (t) => Task_LoadInfoScreenWaitForFade(t, rt);
          /* TODO sound PlaySE */;
          return;
      }
      if (JOY_NEW(B_BUTTON))
      {
          rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 16, "RGB_BLACK");
          task.func = (t) => Task_ExitInfoScreen(t, rt);
          /* TODO sound PlaySE */;
          return;
      }
      if (JOY_NEW(A_BUTTON))
      {
          switch (sPokedexView.selectedScreen)
          {
          case AREA_SCREEN:
              rt.BeginNormalPaletteFade("PALETTES_ALL & ~(0x14)", 0, 0, 16, "RGB_BLACK");
              sPokedexView.screenSwitchState = 1;
              task.func = (t) => Task_SwitchScreensFromInfoScreen(t, rt);
              /* TODO sound PlaySE */;
              break;
          case CRY_SCREEN:
              rt.BeginNormalPaletteFade("PALETTES_ALL & ~(0x14)", 0, 0, 0x10, "RGB_BLACK");
              sPokedexView.screenSwitchState = 2;
              task.func = (t) => Task_SwitchScreensFromInfoScreen(t, rt);
              /* TODO sound PlaySE */;
              break;
          case SIZE_SCREEN:
              if (!sPokedexListItem.owned)
              {
                  /* TODO sound PlaySE */;
              }
              else
              {
                  rt.BeginNormalPaletteFade("PALETTES_ALL & ~(0x14)", 0, 0, 0x10, "RGB_BLACK");
                  sPokedexView.screenSwitchState = 3;
                  task.func = (t) => Task_SwitchScreensFromInfoScreen(t, rt);
                  /* TODO sound PlaySE */;
              }
              break;
          case CANCEL_SCREEN:
              rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 0x10, "RGB_BLACK");
              task.func = (t) => Task_ExitInfoScreen(t, rt);
              /* TODO sound PlaySE */;
              break;
          }
          return;
      }
      if ((JOY_NEW(DPAD_LEFT)
       || (JOY_NEW(L_BUTTON) && gSaveBlock2Ptr.optionsButtonMode == OPTIONS_BUTTON_MODE_LR))
       && sPokedexView.selectedScreen > 0)
      {
          sPokedexView.selectedScreen--;
          HighlightScreenSelectBarItem(sPokedexView.selectedScreen, 0xD);
          /* TODO sound PlaySE */;
          return;
      }
      if ((JOY_NEW(DPAD_RIGHT)
       || (JOY_NEW(R_BUTTON) && gSaveBlock2Ptr.optionsButtonMode == OPTIONS_BUTTON_MODE_LR))
       && sPokedexView.selectedScreen < CANCEL_SCREEN)
      {
          sPokedexView.selectedScreen++;
          HighlightScreenSelectBarItem(sPokedexView.selectedScreen, 0xD);
          /* TODO sound PlaySE */;
          return;
      }
};

/** Source: pokedex.c → Task_SwitchScreensFromInfoScreen */
export const Task_SwitchScreensFromInfoScreen: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          FreeAndDestroyMonPicSprite(task.data[3]);
          switch (sPokedexView.screenSwitchState)
          {
          case 1:
          default:
              task.func = (t) => Task_LoadAreaScreen(t, rt);
              break;
          case 2:
              task.func = (t) => Task_LoadCryScreen(t, rt);
              break;
          case 3:
              task.func = (t) => Task_LoadSizeScreen(t, rt);
              break;
          }
      }
};

/** Source: pokedex.c → Task_LoadInfoScreenWaitForFade */
export const Task_LoadInfoScreenWaitForFade: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          FreeAndDestroyMonPicSprite(task.data[3]);
          task.func = (t) => Task_LoadInfoScreen(t, rt);
      }
};

/** Source: pokedex.c → Task_ExitInfoScreen */
export const Task_ExitInfoScreen: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          FreeAndDestroyMonPicSprite(task.data[3]);
          FreeInfoScreenWindowAndBgBuffers();
          rt.DestroyTask(taskId);
      }
};

/** Source: pokedex.c → Task_LoadAreaScreen */
export const Task_LoadAreaScreen: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  switch (gMain.state)
      {
      case 0:
      default:
          if (!rt.gPaletteFade.active)
          {
              sPokedexView.currentPage = PAGE_AREA;
              gPokedexVBlankCB = gMain.vblankCallback;
              /* noop SetVBlankCallback */;
              ResetOtherVideoRegisters(DISPCNT_BG1_ON);
              sPokedexView.selectedScreen = AREA_SCREEN;
              gMain.state = 1;
          }
          break;
      case 1:
          LoadScreenSelectBarSubmenu(0xD);
          HighlightSubmenuScreenSelectBarItem(0, 0xD);
          LoadPokedexBgPalette(sPokedexView.isSearchResults);
          rt.SetGpuReg(REG_OFFSET_BG1CNT, BGCNT_PRIORITY(0) | BGCNT_CHARBASE(0) | BGCNT_SCREENBASE(13) | BGCNT_16COLOR | BGCNT_TXT256x256);
          gMain.state++;
          break;
      case 2:
          ShowPokedexAreaScreen(NationalPokedexNumToSpecies(sPokedexListItem.dexNum), sPokedexView.screenSwitchState);
          /* noop SetVBlankCallback */;
          sPokedexView.screenSwitchState = 0;
          gMain.state = 0;
          task.func = (t) => Task_WaitForAreaScreenInput(t, rt);
          break;
      }
};

/** Source: pokedex.c → Task_WaitForAreaScreenInput */
export const Task_WaitForAreaScreenInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (sPokedexView.screenSwitchState != 0)
          task.func = (t) => Task_SwitchScreensFromAreaScreen(t, rt);
};

/** Source: pokedex.c → Task_SwitchScreensFromAreaScreen */
export const Task_SwitchScreensFromAreaScreen: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          switch (sPokedexView.screenSwitchState)
          {
          case 1:
          default:
              task.func = (t) => Task_LoadInfoScreen(t, rt);
              break;
          case 2:
              task.func = (t) => Task_LoadCryScreen(t, rt);
              break;
          }
      }
};

/** Source: pokedex.c → Task_LoadCryScreen */
export const Task_LoadCryScreen: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  switch (gMain.state)
      {
      case 0:
      default:
          if (!rt.gPaletteFade.active)
          {
              m4aMPlayStop(gMPlayInfo_BGM);
              sPokedexView.currentPage = PAGE_CRY;
              gPokedexVBlankCB = gMain.vblankCallback;
              /* noop SetVBlankCallback */;
              ResetOtherVideoRegisters(DISPCNT_BG1_ON);
              sPokedexView.selectedScreen = CRY_SCREEN;
              gMain.state = 1;
          }
          break;
      case 1:
          DecompressAndLoadBgGfxUsingHeap(3, gPokedexMenu_Gfx, 0x2000, 0, 0);
          CopyToBgTilemapBuffer(3, gPokedexCryScreen_Tilemap, 0, 0);
          FillWindowPixelBuffer(WIN_INFO, PIXEL_FILL(0));
          PutWindowTilemap(WIN_INFO);
          PutWindowTilemap(WIN_VU_METER);
          PutWindowTilemap(WIN_CRY_WAVE);
          gMain.state++;
          break;
      case 2:
          LoadScreenSelectBarSubmenu(0xD);
          HighlightSubmenuScreenSelectBarItem(1, 0xD);
          LoadPokedexBgPalette(sPokedexView.isSearchResults);
          gMain.state++;
          break;
      case 3:
          ResetPaletteFade();
          gMain.state++;
          break;
      case 4:
          PrintInfoScreenText(gText_CryOf, 82, 33);
          PrintCryScreenSpeciesName(0, sPokedexListItem.dexNum, 82, 49);
          gMain.state++;
          break;
      case 5:
          task.data[3] = CreateMonSpriteFromNationalDexNumber(sPokedexListItem.dexNum, MON_PAGE_X, MON_PAGE_Y, 0);
          rt.gba.oam[_gs(rt, task.data[3]).oamIndex].priority = 0;
          gDexCryScreenState = 0;
          gMain.state++;
          break;
      case 6:
          {
              let waveformWindow: any = null;

              waveformWindow.unk0 = 0x4020;
              waveformWindow.unk2 = 31;
              waveformWindow.paletteNo = 8;
              waveformWindow.yPos = 30;
              waveformWindow.xPos = 12;
              if (LoadCryWaveformWindow(waveformWindow, 2))
              {
                  gMain.state++;
                  gDexCryScreenState = 0;
              }
          }
          break;
      case 7:
          {
              let cryMeter: any = null;

              cryMeter.paletteNo = 9;
              cryMeter.xPos = 18;
              cryMeter.yPos = 3;
              if (LoadCryMeter(cryMeter, 3))
                  gMain.state++;
              CopyWindowToVram(WIN_VU_METER, COPYWIN_GFX);
              CopyWindowToVram(WIN_INFO, COPYWIN_FULL);
              CopyBgTilemapBufferToVram(0);
              CopyBgTilemapBufferToVram(1);
              CopyBgTilemapBufferToVram(2);
              CopyBgTilemapBufferToVram(3);
          }
          break;
      case 8:
          rt.BeginNormalPaletteFade("PALETTES_ALL & ~(0x14)", 0, 0x10, 0, "RGB_BLACK");
          /* noop SetVBlankCallback */;
          gMain.state++;
          break;
      case 9:
          rt.SetGpuReg(REG_OFFSET_BLDCNT, 0);
          rt.SetGpuReg(REG_OFFSET_BLDALPHA, 0);
          rt.SetGpuReg(REG_OFFSET_BLDY, 0);
          rt.SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_1D_MAP | DISPCNT_OBJ_ON);
          ShowBg(0);
          ShowBg(1);
          ShowBg(2);
          ShowBg(3);
          gMain.state++;
          break;
      case 10:
          sPokedexView.screenSwitchState = 0;
          gMain.state = 0;
          task.func = (t) => Task_HandleCryScreenInput(t, rt);
          break;
      }
};

/** Source: pokedex.c → Task_HandleCryScreenInput */
export const Task_HandleCryScreenInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  UpdateCryWaveformWindow(2);

      if (IsCryPlaying())
          LoadPlayArrowPalette(true);
      else
          LoadPlayArrowPalette(false);

      if (JOY_NEW(A_BUTTON))
      {
          LoadPlayArrowPalette(true);
          CryScreenPlayButton(NationalPokedexNumToSpecies(sPokedexListItem.dexNum));
          return;
      }
      else if (!rt.gPaletteFade.active)
      {
          if (JOY_NEW(B_BUTTON))
          {
              rt.BeginNormalPaletteFade("PALETTES_ALL & ~(0x14)", 0, 0, 0x10, "RGB_BLACK");
              m4aMPlayContinue(gMPlayInfo_BGM);
              sPokedexView.screenSwitchState = 1;
              task.func = (t) => Task_SwitchScreensFromCryScreen(t, rt);
              /* TODO sound PlaySE */;
              return;
          }
          if (JOY_NEW(DPAD_LEFT)
           || (JOY_NEW(L_BUTTON) && gSaveBlock2Ptr.optionsButtonMode == OPTIONS_BUTTON_MODE_LR))
          {
              rt.BeginNormalPaletteFade("PALETTES_ALL & ~(0x14)", 0, 0, 0x10, "RGB_BLACK");
              m4aMPlayContinue(gMPlayInfo_BGM);
              sPokedexView.screenSwitchState = 2;
              task.func = (t) => Task_SwitchScreensFromCryScreen(t, rt);
              /* TODO sound PlaySE */;
              return;
          }
          if (JOY_NEW(DPAD_RIGHT)
           || (JOY_NEW(R_BUTTON) && gSaveBlock2Ptr.optionsButtonMode == OPTIONS_BUTTON_MODE_LR))
          {
              if (!sPokedexListItem.owned)
              {
                  /* TODO sound PlaySE */;
              }
              else
              {
                  rt.BeginNormalPaletteFade("PALETTES_ALL & ~(0x14)", 0, 0, 0x10, "RGB_BLACK");
                  m4aMPlayContinue(gMPlayInfo_BGM);
                  sPokedexView.screenSwitchState = 3;
                  task.func = (t) => Task_SwitchScreensFromCryScreen(t, rt);
                  /* TODO sound PlaySE */;
              }
              return;
          }
      }
};

/** Source: pokedex.c → Task_SwitchScreensFromCryScreen */
export const Task_SwitchScreensFromCryScreen: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          FreeCryScreen();
          FreeAndDestroyMonPicSprite(task.data[3]);
          switch (sPokedexView.screenSwitchState)
          {
          default:
          case 1:
              task.func = (t) => Task_LoadInfoScreen(t, rt);
              break;
          case 2:
              task.func = (t) => Task_LoadAreaScreen(t, rt);
              break;
          case 3:
              task.func = (t) => Task_LoadSizeScreen(t, rt);
              break;
          }
      }
};

/** Source: pokedex.c → Task_LoadSizeScreen */
export const Task_LoadSizeScreen: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let spriteId = 0;

      switch (gMain.state)
      {
      default:
      case 0:
          if (!rt.gPaletteFade.active)
          {
              sPokedexView.currentPage = PAGE_SIZE;
              gPokedexVBlankCB = gMain.vblankCallback;
              /* noop SetVBlankCallback */;
              ResetOtherVideoRegisters(DISPCNT_BG1_ON);
              sPokedexView.selectedScreen = SIZE_SCREEN;
              gMain.state = 1;
          }
          break;
      case 1:
          DecompressAndLoadBgGfxUsingHeap(3, gPokedexMenu_Gfx, 0x2000, 0, 0);
          CopyToBgTilemapBuffer(3, gPokedexSizeScreen_Tilemap, 0, 0);
          FillWindowPixelBuffer(WIN_INFO, PIXEL_FILL(0));
          PutWindowTilemap(WIN_INFO);
          gMain.state++;
          break;
      case 2:
          LoadScreenSelectBarSubmenu(0xD);
          HighlightSubmenuScreenSelectBarItem(2, 0xD);
          LoadPokedexBgPalette(sPokedexView.isSearchResults);
          gMain.state++;
          break;
      case 3:
          {
              let string: number[] = new Array(64).fill(0);

              StringCopy(string, gText_SizeComparedTo);
              StringAppend(string, gSaveBlock2Ptr.playerName);
              PrintInfoScreenText(string, GetStringCenterAlignXOffset(FONT_NORMAL, string, DISPLAY_WIDTH), 121);
              gMain.state++;
          }
          break;
      case 4:
          ResetPaletteFade();
          gMain.state++;
          break;
      case 5:
          spriteId = CreateSizeScreenTrainerPic(PlayerGenderToFrontTrainerPicId(gSaveBlock2Ptr.playerGender), 152, 56, 0);
          rt.gba.oam[_gs(rt, spriteId).oamIndex].affineMode = ST_OAM_AFFINE_NORMAL;
          rt.gba.oam[_gs(rt, spriteId).oamIndex].affineParamIndex = 1;
          rt.gba.oam[_gs(rt, spriteId).oamIndex].priority = 0;
          _gs(rt, spriteId).y2 = gPokedexEntries[sPokedexListItem.dexNum].trainerOffset;
          SetOamMatrix(rt.gba, 1, gPokedexEntries[sPokedexListItem.dexNum].trainerScale, 0, 0, gPokedexEntries[sPokedexListItem.dexNum].trainerScale);
          LoadPalette(sSizeScreenSilhouette_Pal, OBJ_PLTT_ID2(rt.gba.oam[_gs(rt, spriteId).oamIndex].paletteBank), PLTT_SIZE_4BPP);
          task.data[5] = spriteId;
          gMain.state++;
          break;
      case 6:
          spriteId = CreateMonSpriteFromNationalDexNumber(sPokedexListItem.dexNum, 88, 56, 1);
          rt.gba.oam[_gs(rt, spriteId).oamIndex].affineMode = ST_OAM_AFFINE_NORMAL;
          rt.gba.oam[_gs(rt, spriteId).oamIndex].affineParamIndex = 2;
          rt.gba.oam[_gs(rt, spriteId).oamIndex].priority = 0;
          _gs(rt, spriteId).y2 = gPokedexEntries[sPokedexListItem.dexNum].pokemonOffset;
          SetOamMatrix(rt.gba, 2, gPokedexEntries[sPokedexListItem.dexNum].pokemonScale, 0, 0, gPokedexEntries[sPokedexListItem.dexNum].pokemonScale);
          LoadPalette(sSizeScreenSilhouette_Pal, OBJ_PLTT_ID2(rt.gba.oam[_gs(rt, spriteId).oamIndex].paletteBank), PLTT_SIZE_4BPP);
          task.data[3] = spriteId;
          CopyWindowToVram(WIN_INFO, COPYWIN_FULL);
          CopyBgTilemapBufferToVram(1);
          CopyBgTilemapBufferToVram(2);
          CopyBgTilemapBufferToVram(3);
          gMain.state++;
          break;
      case 7:
          rt.BeginNormalPaletteFade("PALETTES_ALL & ~(0x14)", 0, 0x10, 0, "RGB_BLACK");
          /* noop SetVBlankCallback */;
          gMain.state++;
          break;
      case 8:
          rt.SetGpuReg(REG_OFFSET_BLDCNT, 0);
          rt.SetGpuReg(REG_OFFSET_BLDALPHA, 0);
          rt.SetGpuReg(REG_OFFSET_BLDY, 0);
          rt.SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_1D_MAP | DISPCNT_OBJ_ON);
          HideBg(0);
          ShowBg(1);
          ShowBg(2);
          ShowBg(3);
          gMain.state++;
          break;
      case 9:
          if (!rt.gPaletteFade.active)
          {
              sPokedexView.screenSwitchState = 0;
              gMain.state = 0;
              task.func = (t) => Task_HandleSizeScreenInput(t, rt);
          }
          break;
      }
};

/** Source: pokedex.c → Task_HandleSizeScreenInput */
export const Task_HandleSizeScreenInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (JOY_NEW(B_BUTTON))
      {
          rt.BeginNormalPaletteFade("PALETTES_ALL & ~(0x14)", 0, 0, 0x10, "RGB_BLACK");
          sPokedexView.screenSwitchState = 1;
          task.func = (t) => Task_SwitchScreensFromSizeScreen(t, rt);
          /* TODO sound PlaySE */;
      }
      else if (JOY_NEW(DPAD_LEFT)
       || (JOY_NEW(L_BUTTON) && gSaveBlock2Ptr.optionsButtonMode == OPTIONS_BUTTON_MODE_LR))
      {
          rt.BeginNormalPaletteFade("PALETTES_ALL & ~(0x14)", 0, 0, 0x10, "RGB_BLACK");
          sPokedexView.screenSwitchState = 2;
          task.func = (t) => Task_SwitchScreensFromSizeScreen(t, rt);
          /* TODO sound PlaySE */;
      }
};

/** Source: pokedex.c → Task_SwitchScreensFromSizeScreen */
export const Task_SwitchScreensFromSizeScreen: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          FreeAndDestroyMonPicSprite(task.data[3]);
          FreeAndDestroyTrainerPicSprite(task.data[5]);
          switch (sPokedexView.screenSwitchState)
          {
          default:
          case 1:
              task.func = (t) => Task_LoadInfoScreen(t, rt);
              break;
          case 2:
              task.func = (t) => Task_LoadCryScreen(t, rt);
              break;
          }
      }
};

/** Source: pokedex.c → Task_DisplayCaughtMonDexPage */
export const Task_DisplayCaughtMonDexPage: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let spriteId = 0;
      let dexNum = task.data[1];

      switch (task.data[0])
      {
      case 0:
      default:
          if (!rt.gPaletteFade.active)
          {
              gPokedexVBlankCB = gMain.vblankCallback;
              /* noop SetVBlankCallback */;
              ResetOtherVideoRegisters(DISPCNT_BG0_ON);
              ResetBgsAndClearDma3BusyFlags(0);
              InitBgsFromTemplates(0, sNewEntryInfoScreen_BgTemplate, ((sNewEntryInfoScreen_BgTemplate)?.length ?? 0));
              SetBgTilemapBuffer(3, AllocZeroed(BG_SCREEN_SIZE));
              SetBgTilemapBuffer(2, AllocZeroed(BG_SCREEN_SIZE));
              InitWindows(sNewEntryInfoScreen_WindowTemplates);
              DeactivateAllTextPrinters();
              task.data[0] = 1;
          }
          break;
      case 1:
          DecompressAndLoadBgGfxUsingHeap(3, gPokedexMenu_Gfx, 0x2000, 0, 0);
          CopyToBgTilemapBuffer(3, gPokedexInfoScreen_Tilemap, 0, 0);
          FillWindowPixelBuffer(WIN_INFO, PIXEL_FILL(0));
          PutWindowTilemap(WIN_INFO);
          PutWindowTilemap(WIN_FOOTPRINT);
          DrawFootprint(WIN_FOOTPRINT, task.data[1]);
          CopyWindowToVram(WIN_FOOTPRINT, COPYWIN_GFX);
          ResetPaletteFade();
          LoadPokedexBgPalette(false);
          task.data[0]++;
          break;
      case 2:
          task.data[0]++;
          break;
      case 3:
          PrintMonInfo(dexNum, IsNationalPokedexEnabled(), 1, 1);
          CopyWindowToVram(WIN_INFO, COPYWIN_FULL);
          CopyBgTilemapBufferToVram(2);
          CopyBgTilemapBufferToVram(3);
          task.data[0]++;
          break;
      case 4:
          spriteId = CreateMonSpriteFromNationalDexNumber(dexNum, MON_PAGE_X, MON_PAGE_Y, 0);
          rt.gba.oam[_gs(rt, spriteId).oamIndex].priority = 0;
          rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0x10, 0, "RGB_BLACK");
          /* noop SetVBlankCallback */;
          task.data[3] = spriteId;
          task.data[0]++;
          break;
      case 5:
          rt.SetGpuReg(REG_OFFSET_BLDCNT, 0);
          rt.SetGpuReg(REG_OFFSET_BLDALPHA, 0);
          rt.SetGpuReg(REG_OFFSET_BLDY, 0);
          rt.SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_1D_MAP | DISPCNT_OBJ_ON);
          ShowBg(2);
          ShowBg(3);
          task.data[0]++;
          break;
      case 6:
          if (!rt.gPaletteFade.active)
          {
              PlayCry_Normal(NationalPokedexNumToSpecies(dexNum), 0);
              task.data[2] = 0;
              task.func = (t) => Task_HandleCaughtMonPageInput(t, rt);
          }
          break;
      }
};

/** Source: pokedex.c → Task_HandleCaughtMonPageInput */
export const Task_HandleCaughtMonPageInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (JOY_NEW(A_BUTTON | B_BUTTON))
      {
          rt.BeginNormalPaletteFade("PALETTES_BG", 0, 0, 16, "RGB_BLACK");
          rt.setSpriteCallback(task.data[3], SpriteCB_SlideCaughtMonToCenter);
          task.func = (t) => Task_ExitCaughtMonPage(t, rt);
      }
       
      else if (++task.data[2] & 16)
      {
          LoadPalette(gPokedexBgHoenn_Pal + 1, BG_PLTT_ID(3) + 1, PLTT_SIZEOF(7));
      }
      else
      {
          LoadPalette(gPokedexBgHoenn_Pal + 49, BG_PLTT_ID(3) + 1, PLTT_SIZEOF(7));
      }
};

/** Source: pokedex.c → Task_ExitCaughtMonPage */
export const Task_ExitCaughtMonPage: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          let species = 0;
          let otId = 0;
          let personality = 0;
          let paletteNum = 0;
          let lzPaletteData: any = null;
          let buffer: any = null;

          rt.SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_1D_MAP | DISPCNT_OBJ_ON);
          FreeAllWindowBuffers();
          buffer = GetBgTilemapBuffer(2);
          if (buffer)
              Free(buffer);
          buffer = GetBgTilemapBuffer(3);
          if (buffer)
              Free(buffer);

          species = NationalPokedexNumToSpecies(task.data[1]);
          otId = (task.data[13] << 16) | task.data[12];
          personality = (task.data[15] << 16) | task.data[14];
          paletteNum = rt.gba.oam[_gs(rt, task.data[3]).oamIndex].paletteNum;
          lzPaletteData = GetMonSpritePalFromSpeciesAndPersonality(species, otId, personality);
          LoadCompressedPalette(lzPaletteData, OBJ_PLTT_ID(paletteNum), PLTT_SIZE_4BPP);
          rt.DestroyTask(taskId);
      }
};

/** Source: pokedex.c → Task_LoadSearchMenu */
export const Task_LoadSearchMenu: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let i = 0;

      switch (gMain.state)
      {
      default:
      case 0:
          if (!rt.gPaletteFade.active)
          {
              sPokedexView.currentPage = PAGE_SEARCH;
              ResetOtherVideoRegisters(0);
              ResetBgsAndClearDma3BusyFlags(0);
              InitBgsFromTemplates(0, sSearchMenu_BgTemplate, ((sSearchMenu_BgTemplate)?.length ?? 0));
              SetBgTilemapBuffer(3, AllocZeroed(BG_SCREEN_SIZE));
              SetBgTilemapBuffer(2, AllocZeroed(BG_SCREEN_SIZE));
              SetBgTilemapBuffer(1, AllocZeroed(BG_SCREEN_SIZE));
              SetBgTilemapBuffer(0, AllocZeroed(BG_SCREEN_SIZE));
              InitWindows(sSearchMenu_WindowTemplate);
              DeactivateAllTextPrinters();
              PutWindowTilemap(0);
              DecompressAndLoadBgGfxUsingHeap(3, gPokedexSearchMenu_Gfx, 0x2000, 0, 0);

              if (!IsNationalPokedexEnabled())
                  CopyToBgTilemapBuffer(3, gPokedexSearchMenuHoenn_Tilemap, 0, 0);
              else
                  CopyToBgTilemapBuffer(3, gPokedexSearchMenuNational_Tilemap, 0, 0);
              LoadPalette(gPokedexSearchMenu_Pal + 1, BG_PLTT_ID(0) + 1, PLTT_SIZEOF(4 * 16 - 1));
              gMain.state = 1;
          }
          break;
      case 1:
          /* TODO LoadCompressedSpriteSheet — load via rt.LoadCompressedSpriteSheetsFromTable */;
          /* TODO LoadSpritePalettes — load via rt.LoadSpritePalettesFromTable */;
          CreateSearchParameterScrollArrows(taskId);
          for (i = 0; i < NUM_TASK_DATA; i++)
              task.data[i] = 0;
          SetDefaultSearchModeAndOrder(taskId);
          HighlightSelectedSearchTopBarItem(SEARCH_TOPBAR_SEARCH);
          PrintSelectedSearchParameters(taskId);
          CopyWindowToVram(0, COPYWIN_FULL);
          CopyBgTilemapBufferToVram(1);
          CopyBgTilemapBufferToVram(2);
          CopyBgTilemapBufferToVram(3);
          gMain.state++;
          break;
      case 2:
          rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 16, 0, "RGB_BLACK");
          gMain.state++;
          break;
      case 3:
          rt.SetGpuReg(REG_OFFSET_BLDCNT, 0);
          rt.SetGpuReg(REG_OFFSET_BLDALPHA, 0);
          rt.SetGpuReg(REG_OFFSET_BLDY, 0);
          rt.SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_OBJ_1D_MAP | DISPCNT_OBJ_ON);
          HideBg(0);
          ShowBg(1);
          ShowBg(2);
          ShowBg(3);
          gMain.state++;
          break;
      case 4:
          if (!rt.gPaletteFade.active)
          {
              task.func = (t) => Task_SwitchToSearchMenuTopBar(t, rt);
              gMain.state = 0;
          }
          break;
      }
};

/** Source: pokedex.c → Task_SwitchToSearchMenuTopBar */
export const Task_SwitchToSearchMenuTopBar: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  HighlightSelectedSearchTopBarItem(task.data[0]);
      PrintSelectedSearchParameters(taskId);
      CopyWindowToVram(0, COPYWIN_GFX);
      CopyBgTilemapBufferToVram(3);
      task.func = (t) => Task_HandleSearchTopBarInput(t, rt);
};

/** Source: pokedex.c → Task_HandleSearchTopBarInput */
export const Task_HandleSearchTopBarInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (JOY_NEW(B_BUTTON))
      {
          /* TODO sound PlaySE */;
          task.func = (t) => Task_ExitSearch(t, rt);
          return;
      }
      if (JOY_NEW(A_BUTTON))
      {
          switch (task.data[0])
          {
          case SEARCH_TOPBAR_SEARCH:
              /* TODO sound PlaySE */;
              task.data[1] = SEARCH_NAME;
              task.func = (t) => Task_SwitchToSearchMenu(t, rt);
              break;
          case SEARCH_TOPBAR_SHIFT:
              /* TODO sound PlaySE */;
              task.data[1] = SEARCH_ORDER;
              task.func = (t) => Task_SwitchToSearchMenu(t, rt);
              break;
          case SEARCH_TOPBAR_CANCEL:
              /* TODO sound PlaySE */;
              task.func = (t) => Task_ExitSearch(t, rt);
              break;
          }
          return;
      }
      if (JOY_NEW(DPAD_LEFT) && task.data[0] > SEARCH_TOPBAR_SEARCH)
      {
          /* TODO sound PlaySE */;
          task.data[0]--;
          HighlightSelectedSearchTopBarItem(task.data[0]);
          CopyWindowToVram(0, COPYWIN_GFX);
          CopyBgTilemapBufferToVram(3);
      }
      if (JOY_NEW(DPAD_RIGHT) && task.data[0] < SEARCH_TOPBAR_CANCEL)
      {
          /* TODO sound PlaySE */;
          task.data[0]++;
          HighlightSelectedSearchTopBarItem(task.data[0]);
          CopyWindowToVram(0, COPYWIN_GFX);
          CopyBgTilemapBufferToVram(3);
      }
};

/** Source: pokedex.c → Task_SwitchToSearchMenu */
export const Task_SwitchToSearchMenu: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  HighlightSelectedSearchMenuItem(task.data[0], task.data[1]);
      PrintSelectedSearchParameters(taskId);
      CopyWindowToVram(0, COPYWIN_GFX);
      CopyBgTilemapBufferToVram(3);
      task.func = (t) => Task_HandleSearchMenuInput(t, rt);
};

/** Source: pokedex.c → Task_HandleSearchMenuInput */
export const Task_HandleSearchMenuInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let movementMap: any = null;

      if (task.data[0] != SEARCH_TOPBAR_SEARCH)
      {
          if (!IsNationalPokedexEnabled())
              movementMap = sSearchMovementMap_ShiftHoennDex;
          else
              movementMap = sSearchMovementMap_ShiftNatDex;
      }
      else
      {
          if (!IsNationalPokedexEnabled())
              movementMap = sSearchMovementMap_SearchHoennDex;
          else
              movementMap = sSearchMovementMap_SearchNatDex;
      }

      if (JOY_NEW(B_BUTTON))
      {
          /* TODO sound PlaySE */;
          SetDefaultSearchModeAndOrder(taskId);
          task.func = (t) => Task_SwitchToSearchMenuTopBar(t, rt);
          return;
      }
      if (JOY_NEW(A_BUTTON))
      {
          if (task.data[1] == SEARCH_OK)
          {
              if (task.data[0] != SEARCH_TOPBAR_SEARCH)
              {
                  sPokeBallRotation = POKEBALL_ROTATION_TOP;
                  sPokedexView.pokeBallRotationBackup = POKEBALL_ROTATION_TOP;
                  sLastSelectedPokemon = 0;
                  sPokedexView.selectedPokemonBackup = 0;
                  gSaveBlock2Ptr.pokedex.mode = GetSearchModeSelection(taskId, SEARCH_MODE);
                  if (!IsNationalPokedexEnabled())
                      gSaveBlock2Ptr.pokedex.mode = DEX_MODE_HOENN;
                  sPokedexView.dexModeBackup = gSaveBlock2Ptr.pokedex.mode;
                  gSaveBlock2Ptr.pokedex.order = GetSearchModeSelection(taskId, SEARCH_ORDER);
                  sPokedexView.dexOrderBackup = gSaveBlock2Ptr.pokedex.order;
                  /* TODO sound PlaySE */;
                  task.func = (t) => Task_ExitSearch(t, rt);
              }
              else
              {
                  EraseAndPrintSearchTextBox(gText_SearchingPleaseWait);
                  task.func = (t) => Task_StartPokedexSearch(t, rt);
                  /* TODO sound PlaySE */;
                  CopyWindowToVram(0, COPYWIN_GFX);
              }
          }
          else
          {
              /* TODO sound PlaySE */;
              task.func = (t) => Task_SelectSearchMenuItem(t, rt);
          }
          return;
      }

      if (JOY_NEW(DPAD_LEFT) && movementMap[task.data[1]][0] != 0xFF)
      {
          /* TODO sound PlaySE */;
          task.data[1] = movementMap[task.data[1]][0];
          HighlightSelectedSearchMenuItem(task.data[0], task.data[1]);
          CopyWindowToVram(0, COPYWIN_GFX);
          CopyBgTilemapBufferToVram(3);
      }
      if (JOY_NEW(DPAD_RIGHT) && movementMap[task.data[1]][1] != 0xFF)
      {
          /* TODO sound PlaySE */;
          task.data[1] = movementMap[task.data[1]][1];
          HighlightSelectedSearchMenuItem(task.data[0], task.data[1]);
          CopyWindowToVram(0, COPYWIN_GFX);
          CopyBgTilemapBufferToVram(3);
      }
      if (JOY_NEW(DPAD_UP) && movementMap[task.data[1]][2] != 0xFF)
      {
          /* TODO sound PlaySE */;
          task.data[1] = movementMap[task.data[1]][2];
          HighlightSelectedSearchMenuItem(task.data[0], task.data[1]);
          CopyWindowToVram(0, COPYWIN_GFX);
          CopyBgTilemapBufferToVram(3);
      }
      if (JOY_NEW(DPAD_DOWN) && movementMap[task.data[1]][3] != 0xFF)
      {
          /* TODO sound PlaySE */;
          task.data[1] = movementMap[task.data[1]][3];
          HighlightSelectedSearchMenuItem(task.data[0], task.data[1]);
          CopyWindowToVram(0, COPYWIN_GFX);
          CopyBgTilemapBufferToVram(3);
      }
};

/** Source: pokedex.c → Task_StartPokedexSearch */
export const Task_StartPokedexSearch: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let dexMode = GetSearchModeSelection(taskId, SEARCH_MODE);
      let order = GetSearchModeSelection(taskId, SEARCH_ORDER);
      let abcGroup = GetSearchModeSelection(taskId, SEARCH_NAME);
      let bodyColor = GetSearchModeSelection(taskId, SEARCH_COLOR);
      let type1 = GetSearchModeSelection(taskId, SEARCH_TYPE_LEFT);
      let type2 = GetSearchModeSelection(taskId, SEARCH_TYPE_RIGHT);

      DoPokedexSearch(dexMode, order, abcGroup, bodyColor, type1, type2);
      task.func = (t) => Task_WaitAndCompleteSearch(t, rt);
};

/** Source: pokedex.c → Task_WaitAndCompleteSearch */
export const Task_WaitAndCompleteSearch: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!IsSEPlaying())
      {
          if (sPokedexView.pokemonListCount != 0)
          {
              /* TODO sound PlaySE */;
              EraseAndPrintSearchTextBox(gText_SearchCompleted);
          }
          else
          {
              /* TODO sound PlaySE */;
              EraseAndPrintSearchTextBox(gText_NoMatchingPkmnWereFound);
          }
          task.func = (t) => Task_SearchCompleteWaitForInput(t, rt);
          CopyWindowToVram(0, COPYWIN_GFX);
      }
};

/** Source: pokedex.c → Task_SearchCompleteWaitForInput */
export const Task_SearchCompleteWaitForInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (JOY_NEW(A_BUTTON))
      {
          if (sPokedexView.pokemonListCount != 0)
          {
               
              sPokedexView.screenSwitchState = 1;
              sPokedexView.dexMode = GetSearchModeSelection(taskId, SEARCH_MODE);
              sPokedexView.dexOrder = GetSearchModeSelection(taskId, SEARCH_ORDER);
              task.func = (t) => Task_ExitSearch(t, rt);
              /* TODO sound PlaySE */;
          }
          else
          {
              task.func = (t) => Task_SwitchToSearchMenu(t, rt);
              /* TODO sound PlaySE */;
          }
      }
};

/** Source: pokedex.c → Task_SelectSearchMenuItem */
export const Task_SelectSearchMenuItem: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let menuItem = 0;
      let cursorPos = 0;
      let scrollOffset = 0;

      DrawOrEraseSearchParameterBox(false);
      menuItem = task.data[1];
      cursorPos = task.data[sSearchOptions[menuItem].taskDataCursorPos];
      scrollOffset = task.data[sSearchOptions[menuItem].taskDataScrollOffset];
      task.data[14] = cursorPos;
      task.data[15] = scrollOffset;
      PrintSearchParameterText(taskId);
      PrintSelectorArrow(cursorPos);
      task.func = (t) => Task_HandleSearchParameterInput(t, rt);
      CopyWindowToVram(0, COPYWIN_GFX);
      CopyBgTilemapBufferToVram(3);
};

/** Source: pokedex.c → Task_HandleSearchParameterInput */
export const Task_HandleSearchParameterInput: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  let menuItem = 0;
      let texts: any = null;
      let cursorPos = 0;
      let scrollOffset = 0;
      let maxOption = 0;
      let moved = 0;

      menuItem = task.data[1];
      texts = sSearchOptions[menuItem].texts;
      cursorPos = task.data[sSearchOptions[menuItem].taskDataCursorPos];
      scrollOffset = task.data[sSearchOptions[menuItem].taskDataScrollOffset];
      maxOption = sSearchOptions[menuItem].numOptions - 1;
      if (JOY_NEW(A_BUTTON))
      {
          /* TODO sound PlaySE */;
          ClearSearchParameterBoxText();
          DrawOrEraseSearchParameterBox(true);
          task.func = (t) => Task_SwitchToSearchMenu(t, rt);
          CopyWindowToVram(0, COPYWIN_GFX);
          CopyBgTilemapBufferToVram(3);
          return;
      }
      if (JOY_NEW(B_BUTTON))
      {
          /* TODO sound PlaySE */;
          ClearSearchParameterBoxText();
          DrawOrEraseSearchParameterBox(true);
          cursorPos = task.data[14];
          scrollOffset = task.data[15];
          task.func = (t) => Task_SwitchToSearchMenu(t, rt);
          CopyWindowToVram(0, COPYWIN_GFX);
          CopyBgTilemapBufferToVram(3);
          return;
      }
      moved = false;
      if (JOY_REPEAT(DPAD_UP))
      {
          if (cursorPos != 0)
          {
               
              EraseSelectorArrow(cursorPos);
              (cursorPos)--;
              PrintSelectorArrow(cursorPos);
              moved = true;
          }
          else if (scrollOffset != 0)
          {
               
              (scrollOffset)--;
              PrintSearchParameterText(taskId);
              PrintSelectorArrow(cursorPos);
              moved = true;
          }
          if (moved)
          {
              /* TODO sound PlaySE */;
              EraseAndPrintSearchTextBox(texts[cursorPos + scrollOffset].description);
              CopyWindowToVram(0, COPYWIN_GFX);
          }
          return;
      }
      if (JOY_REPEAT(DPAD_DOWN))
      {
          if (cursorPos < MAX_SEARCH_PARAM_CURSOR_POS && cursorPos < maxOption)
          {
               
              EraseSelectorArrow(cursorPos);
              (cursorPos)++;
              PrintSelectorArrow(cursorPos);
              moved = true;
          }
          else if (maxOption > MAX_SEARCH_PARAM_CURSOR_POS && scrollOffset < maxOption - MAX_SEARCH_PARAM_CURSOR_POS)
          {
               
              (scrollOffset)++;
              PrintSearchParameterText(taskId);
              PrintSelectorArrow(5);
              moved = true;
          }
          if (moved)
          {
              /* TODO sound PlaySE */;
              EraseAndPrintSearchTextBox(texts[cursorPos + scrollOffset].description);
              CopyWindowToVram(0, COPYWIN_GFX);
          }
          return;
      }
};

/** Source: pokedex.c → Task_ExitSearch */
export const Task_ExitSearch: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  rt.BeginNormalPaletteFade("PALETTES_ALL", 0, 0, 16, "RGB_BLACK");
      task.func = (t) => Task_ExitSearchWaitForFade(t, rt);
};

/** Source: pokedex.c → Task_ExitSearchWaitForFade */
export const Task_ExitSearchWaitForFade: TaskCallback = (task, rt) => {
  const taskId = task.taskId;
  if (!rt.gPaletteFade.active)
      {
          FreeSearchWindowAndBgBuffers();
          rt.DestroyTask(taskId);
      }
};

/** Source: pokedex.c → CB2_OpenPokedex */
export const CB2_OpenPokedex: CB2Callback = (rt) => {
  switch (gMain.state)
      {
      case 0:
      default:
          /* noop SetVBlankCallback */;
          ResetOtherVideoRegisters(0);
          DmaFillLarge16(3, 0, VRAM, VRAM_SIZE, 0x1000);
          DmaClear32(3, OAM, OAM_SIZE);
          /* TODO DmaClear16 (memory clear) */;
          gMain.state = 1;
          break;
      case 1:
          ScanlineEffect_Stop();
          ResetTasks();
          rt.ResetSpriteData();
          ResetPaletteFade();
          /* TODO FreeAllSpritePalettes */;
          gReservedSpritePaletteCount = 8;
          ResetAllPicSprites();
          gMain.state++;
          break;
      case 2:
          sPokedexView = AllocZeroed(/* ((struct)?.length ?? 32) */ 0);
          ResetPokedexView(sPokedexView);
          rt.CreateTask((t) => Task_OpenPokedexMainPage(t, rt), 0);
          sPokedexView.dexMode = gSaveBlock2Ptr.pokedex.mode;
          if (!IsNationalPokedexEnabled())
              sPokedexView.dexMode = DEX_MODE_HOENN;
          sPokedexView.dexOrder = gSaveBlock2Ptr.pokedex.order;
          sPokedexView.selectedPokemon = sLastSelectedPokemon;
          sPokedexView.pokeBallRotation = sPokeBallRotation;
          sPokedexView.selectedScreen = AREA_SCREEN;
          if (!IsNationalPokedexEnabled())
          {
              sPokedexView.seenCount = GetHoennPokedexCount(FLAG_GET_SEEN);
              sPokedexView.ownCount = GetHoennPokedexCount(FLAG_GET_CAUGHT);
          }
          else
          {
              sPokedexView.seenCount = GetNationalPokedexCount(FLAG_GET_SEEN);
              sPokedexView.ownCount = GetNationalPokedexCount(FLAG_GET_CAUGHT);
          }
          sPokedexView.initialVOffset = 8;
          gMain.state++;
          break;
      case 3:
          EnableInterrupts(1);
          /* noop SetVBlankCallback */;
          /* TODO scene transition: SetMainCallback2(CB2_Pokedex) */;
          CreatePokedexList(sPokedexView.dexMode, sPokedexView.dexOrder);
          m4aMPlayVolumeControl(gMPlayInfo_BGM, TRACKS_ALL, 0x80);
          break;
      }
};

/** Source: pokedex.c → CB2_Pokedex */
export const CB2_Pokedex: CB2Callback = (rt) => {
  RunTasks();
      AnimateSprites();
      BuildOamBuffer();
      UpdatePaletteFade();
};
