// AUTO-GENERATED from src/scrcmd.c by extract-decomp-all.mjs
// Do not edit manually — re-run `npm run extract:decomp-all` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/src/scrcmd.c
// Generated: 2026-04-26

// ─── EWRAM/IWRAM/COMMON_DATA globals (initial values) ──────────────────────
export const SEGMENT_VARS = [
  { segment: 'EWRAM_DATA', type: "u32", name: 'sAddressOffset', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sPauseCounter', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sMovingNpcId', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sMovingNpcMapGroup', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sMovingNpcMapNum', isArray: false, init: "0" },
  { segment: 'EWRAM_DATA', type: "u16", name: 'sFieldEffectScriptId', isArray: false, init: "0" },
] as const;

// ─── Functions (declarations + definitions) ─────────────────────────────────
export const FUNCTIONS = [
  { name: 'CloseBrailleWindow', ret: "void", arity: 0, params: "void" },
  { name: 'ScrCmd_nop', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_nop1', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_end', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_gotonative', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_special', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_specialvar', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_callnative', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_waitstate', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_goto', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_return', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_call', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_goto_if', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_call_if', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setvaddress', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_vgoto', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_vcall', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_vgoto_if', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_vcall_if', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_gotostd', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_callstd', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_gotostd_if', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_callstd_if', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_returnram', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_endram', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setmysteryeventstatus', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_loadword', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_loadbytefromptr', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setptr', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_loadbyte', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setptrbyte', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_copylocal', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_copybyte', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setvar', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_copyvar', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setorcopyvar', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'Compare', ret: "u8", arity: 2, params: "u16 a, u16 b" },
  { name: 'ScrCmd_compare_local_to_local', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_compare_local_to_value', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_compare_local_to_ptr', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_compare_ptr_to_local', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_compare_ptr_to_value', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_compare_ptr_to_ptr', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_compare_var_to_value', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_compare_var_to_var', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_addvar', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_subvar', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_random', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_additem', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_removeitem', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkitemspace', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkitem', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkitemtype', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_addpcitem', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkpcitem', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_adddecoration', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_removedecoration', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkdecorspace', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkdecor', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setflag', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_clearflag', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkflag', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_incrementgamestat', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_animateflash', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setflashlevel', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'IsPaletteNotActive', ret: "bool8", arity: 0, params: "void" },
  { name: 'ScrCmd_fadescreen', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_fadescreenspeed', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_fadescreenswapbuffers', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'RunPauseTimer', ret: "bool8", arity: 0, params: "void" },
  { name: 'ScrCmd_delay', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_initclock', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_dotimebasedevents', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_gettime', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setweather', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_resetweather', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_doweather', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setstepcallback', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setmaplayoutindex', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_warp', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_warpsilent', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_warpdoor', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_warphole', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'SetWarpDestination', ret: "else", arity: 5, params: "mapGroup, mapNum, WARP_ID_NONE, x - MAP_OFFSET, y - MAP_OFFSET" },
  { name: 'ScrCmd_warpteleport', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_warpmossdeepgym', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setwarp', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setdynamicwarp', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setdivewarp', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setholewarp', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setescapewarp', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_getplayerxy', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_getpartysize', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_playse', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'WaitForSoundEffectFinish', ret: "bool8", arity: 0, params: "void" },
  { name: 'ScrCmd_waitse', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_playfanfare', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'WaitForFanfareFinish', ret: "bool8", arity: 0, params: "void" },
  { name: 'ScrCmd_waitfanfare', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_playbgm', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_savebgm', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_fadedefaultbgm', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_fadenewbgm', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_fadeoutbgm', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'FadeOutBGMTemporarily', ret: "else", arity: 1, params: "4" },
  { name: 'ScrCmd_fadeinbgm', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'FadeInBGM', ret: "else", arity: 1, params: "4" },
  { name: 'ScrCmd_applymovement', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_applymovementat', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'WaitForMovementFinish', ret: "bool8", arity: 0, params: "void" },
  { name: 'ScrCmd_waitmovement', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_waitmovementat', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_removeobject', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_removeobjectat', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_addobject', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_addobjectat', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setobjectxy', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setobjectxyperm', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_copyobjectxytoperm', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_showobjectat', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_hideobjectat', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setobjectsubpriority', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_resetobjectsubpriority', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_faceplayer', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_turnobject', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setobjectmovementtype', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_createvobject', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_turnvobject', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_lockall', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_lock', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_releaseall', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_release', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_message', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_pokenavcall', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_messageautoscroll', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_messageinstant', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_waitmessage', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_closemessage', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'WaitForAorBPress', ret: "bool8", arity: 0, params: "void" },
  { name: 'ScrCmd_waitbuttonpress', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_yesnobox', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_multichoice', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_multichoicedefault', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_drawbox', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_multichoicegrid', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_erasebox', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_drawboxtext', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_showmonpic', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_hidemonpic', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_showcontestpainting', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_braillemessage', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_closebraillemessage', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_vmessage', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_bufferspeciesname', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_bufferleadmonspeciesname', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_bufferpartymonnick', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_bufferitemname', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_bufferitemnameplural', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_bufferdecorationname', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_buffermovename', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_buffernumberstring', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_bufferstdstring', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_buffercontestname', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_bufferstring', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_vbuffermessage', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_vbufferstring', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_bufferboxname', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_givemon', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_giveegg', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setmonmove', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkpartymove', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_addmoney', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_removemoney', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkmoney', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_showmoneybox', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_hidemoneybox', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_updatemoneybox', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_showcoinsbox', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_hidecoinsbox', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_updatecoinsbox', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_trainerbattle', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_dotrainerbattle', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_gotopostbattlescript', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_gotobeatenscript', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checktrainerflag', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_settrainerflag', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_cleartrainerflag', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setwildbattle', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_dowildbattle', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_pokemart', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_pokemartdecoration', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_pokemartdecoration2', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_playslotmachine', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setberrytree', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'PlantBerryTree', ret: "else", arity: 4, params: "treeId, berry, growthStage, FALSE" },
  { name: 'ScrCmd_getpokenewsactive', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_choosecontestmon', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_startcontest', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_showcontestresults', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_contestlinktransfer', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_dofieldeffect', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setfieldeffectargument', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'WaitForFieldEffectFinish', ret: "bool8", arity: 0, params: "void" },
  { name: 'ScrCmd_waitfieldeffect', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setrespawn', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkplayergender', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_playmoncry', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_waitmoncry', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setmetatile', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'MapGridSetMetatileIdAt', ret: "else", arity: 3, params: "x, y, metatileId | MAPGRID_IMPASSABLE" },
  { name: 'ScrCmd_opendoor', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_closedoor', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'IsDoorAnimationStopped', ret: "bool8", arity: 0, params: "void" },
  { name: 'ScrCmd_waitdooranim', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setdooropen', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setdoorclosed', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_addelevmenuitem', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_showelevmenu', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkcoins', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_addcoins', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_removecoins', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_moverotatingtileobjects', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_turnrotatingtileobjects', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_initrotatingtilepuzzle', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_freerotatingtilepuzzle', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_selectapproachingtrainer', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_lockfortrainer', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setmodernfatefulencounter', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_checkmodernfatefulencounter', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_trywondercardscript', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_warpspinenter', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_setmonmetlocation', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_buffertrainerclassname', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'ScrCmd_buffertrainername', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
  { name: 'SetMovingNpcId', ret: "void", arity: 1, params: "u16 npcId" },
  { name: 'ScrCmd_warpwhitefade', ret: "bool8", arity: 1, params: "struct ScriptContext *ctx" },
] as const;

// ─── #include directives (dependency graph) ─────────────────────────────────
export const INCLUDES = [
  'global.h',
  'frontier_util.h',
  'battle_setup.h',
  'berry.h',
  'clock.h',
  'coins.h',
  'contest.h',
  'contest_util.h',
  'contest_painting.h',
  'data.h',
  'decoration.h',
  'decoration_inventory.h',
  'event_data.h',
  'field_door.h',
  'field_effect.h',
  'event_object_lock.h',
  'event_object_movement.h',
  'field_message_box.h',
  'field_player_avatar.h',
  'field_screen_effect.h',
  'field_specials.h',
  'field_tasks.h',
  'field_weather.h',
  'fieldmap.h',
  'item.h',
  'lilycove_lady.h',
  'main.h',
  'menu.h',
  'money.h',
  'mystery_event_script.h',
  'palette.h',
  'party_menu.h',
  'pokemon_storage_system.h',
  'random.h',
  'overworld.h',
  'rotating_tile_puzzle.h',
  'rtc.h',
  'script.h',
  'script_menu.h',
  'script_movement.h',
  'script_pokemon_util.h',
  'shop.h',
  'slot_machine.h',
  'sound.h',
  'string_util.h',
  'text.h',
  'text_window.h',
  'trainer_see.h',
  'tv.h',
  'window.h',
  'constants/event_objects.h',
] as const;
