// AUTO-GENERATED from asm/macros/battle_ai_script.inc by extract-decomp-asm.mjs
// Do not edit manually — re-run `npm run extract:decomp-asm` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/asm/macros/battle_ai_script.inc
// Generated: 2026-04-26

// ─── .macro definitions (asm macro → opcode mapping bodies) ─────────────────
export const MACROS = [
  { name: "if_random_less_than", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x0"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_random_greater_than", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x1"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_random_equal", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x2"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_random_not_equal", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x3"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "score", args: ["param0:req"], body: [{op:".byte",args:["0x4"]}, {op:".byte",args:["\\param0"]}] },
  { name: "if_hp_less_than", args: ["battler:req", "param1:req", "param2:req"], body: [{op:".byte",args:["0x5"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\param1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_hp_more_than", args: ["battler:req", "param1:req", "param2:req"], body: [{op:".byte",args:["0x6"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\param1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_hp_equal", args: ["battler:req", "param1:req", "param2:req"], body: [{op:".byte",args:["0x7"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\param1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_hp_not_equal", args: ["battler:req", "param1:req", "param2:req"], body: [{op:".byte",args:["0x8"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\param1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_status", args: ["battler:req", "status1:req", "param2:req"], body: [{op:".byte",args:["0x9"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_not_status", args: ["battler:req", "status1:req", "param2:req"], body: [{op:".byte",args:["0xa"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_status2", args: ["battler:req", "status2:req", "param2:req"], body: [{op:".byte",args:["0xb"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status2"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_not_status2", args: ["battler:req", "status2:req", "param2:req"], body: [{op:".byte",args:["0xc"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status2"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_status3", args: ["battler:req", "status3:req", "param2:req"], body: [{op:".byte",args:["0xd"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status3"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_not_status3", args: ["battler:req", "status3:req", "param2:req"], body: [{op:".byte",args:["0xe"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status3"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_side_affecting", args: ["battler:req", "sidestatus:req", "param2:req"], body: [{op:".byte",args:["0xf"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\sidestatus"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_not_side_affecting", args: ["battler:req", "sidestatus:req", "param2:req"], body: [{op:".byte",args:["0x10"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\sidestatus"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_less_than", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x11"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_more_than", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x12"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_equal", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x13"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_not_equal", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x14"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_less_than_ptr", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x15"]}, {op:".4byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_more_than_ptr", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x16"]}, {op:".4byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_equal_ptr", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x17"]}, {op:".4byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_not_equal_ptr", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x18"]}, {op:".4byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_move", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x19"]}, {op:".2byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_not_move", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x1a"]}, {op:".2byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_in_bytes", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x1b"]}, {op:".4byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_not_in_bytes", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x1c"]}, {op:".4byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_in_hwords", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x1d"]}, {op:".4byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_not_in_hwords", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x1e"]}, {op:".4byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_user_has_attacking_move", args: ["param0:req"], body: [{op:".byte",args:["0x1f"]}, {op:".4byte",args:["\\param0"]}] },
  { name: "if_user_has_no_attacking_moves", args: ["param0:req"], body: [{op:".byte",args:["0x20"]}, {op:".4byte",args:["\\param0"]}] },
  { name: "get_turn_count", args: [], body: [{op:".byte",args:["0x21"]}] },
  { name: "get_type", args: ["param0:req"], body: [{op:".byte",args:["0x22"]}, {op:".byte",args:["\\param0"]}] },
  { name: "get_considered_move_power", args: [], body: [{op:".byte",args:["0x23"]}] },
  { name: "get_how_powerful_move_is", args: [], body: [{op:".byte",args:["0x24"]}] },
  { name: "get_last_used_bank_move", args: ["battler:req"], body: [{op:".byte",args:["0x25"]}, {op:".byte",args:["\\battler"]}] },
  { name: "if_equal_", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x26"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_not_equal_", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x27"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_user_goes", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x28"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_user_doesnt_go", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x29"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "nop_2A", args: [], body: [{op:".byte",args:["0x2a"]}] },
  { name: "nop_2B", args: [], body: [{op:".byte",args:["0x2b"]}] },
  { name: "count_usable_party_mons", args: ["battler:req"], body: [{op:".byte",args:["0x2c"]}, {op:".byte",args:["\\battler"]}] },
  { name: "get_considered_move", args: [], body: [{op:".byte",args:["0x2d"]}] },
  { name: "get_considered_move_effect", args: [], body: [{op:".byte",args:["0x2e"]}] },
  { name: "get_ability", args: ["battler:req"], body: [{op:".byte",args:["0x2f"]}, {op:".byte",args:["\\battler"]}] },
  { name: "get_highest_type_effectiveness", args: [], body: [{op:".byte",args:["0x30"]}] },
  { name: "if_type_effectiveness", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x31"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "nop_32", args: [], body: [{op:".byte",args:["0x32"]}] },
  { name: "nop_33", args: [], body: [{op:".byte",args:["0x33"]}] },
  { name: "if_status_in_party", args: ["battler:req", "status1:req", "param2:req"], body: [{op:".byte",args:["0x34"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_status_not_in_party", args: ["battler:req", "status1:req", "param2:req"], body: [{op:".byte",args:["0x35"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "get_weather", args: [], body: [{op:".byte",args:["0x36"]}] },
  { name: "if_effect", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x37"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_not_effect", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x38"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_stat_level_less_than", args: ["battler:req", "stat:req", "param2:req", "param3:req"], body: [{op:".byte",args:["0x39"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\stat"]}, {op:".byte",args:["\\param2"]}, {op:".4byte",args:["\\param3"]}] },
  { name: "if_stat_level_more_than", args: ["battler:req", "stat:req", "param2:req", "param3:req"], body: [{op:".byte",args:["0x3a"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\stat"]}, {op:".byte",args:["\\param2"]}, {op:".4byte",args:["\\param3"]}] },
  { name: "if_stat_level_equal", args: ["battler:req", "stat:req", "param2:req", "param3:req"], body: [{op:".byte",args:["0x3b"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\stat"]}, {op:".byte",args:["\\param2"]}, {op:".4byte",args:["\\param3"]}] },
  { name: "if_stat_level_not_equal", args: ["battler:req", "stat:req", "param2:req", "param3:req"], body: [{op:".byte",args:["0x3c"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\stat"]}, {op:".byte",args:["\\param2"]}, {op:".4byte",args:["\\param3"]}] },
  { name: "if_can_faint", args: ["param0:req"], body: [{op:".byte",args:["0x3d"]}, {op:".4byte",args:["\\param0"]}] },
  { name: "if_cant_faint", args: ["param0:req"], body: [{op:".byte",args:["0x3e"]}, {op:".4byte",args:["\\param0"]}] },
  { name: "if_has_move", args: ["battler:req", "param1:req", "param2:req"], body: [{op:".byte",args:["0x3f"]}, {op:".byte",args:["\\battler"]}, {op:".2byte",args:["\\param1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_doesnt_have_move", args: ["battler:req", "param1:req", "param2:req"], body: [{op:".byte",args:["0x40"]}, {op:".byte",args:["\\battler"]}, {op:".2byte",args:["\\param1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_has_move_with_effect", args: ["battler:req", "param1:req", "param2:req"], body: [{op:".byte",args:["0x41"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\param1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_doesnt_have_move_with_effect", args: ["battler:req", "param1:req", "param2:req"], body: [{op:".byte",args:["0x42"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\param1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_any_move_disabled_or_encored", args: ["battler:req", "param1:req", "param2:req"], body: [{op:".byte",args:["0x43"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\param1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "if_curr_move_disabled_or_encored", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x44"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "flee", args: [], body: [{op:".byte",args:["0x45"]}] },
  { name: "if_random_safari_flee", args: ["param0:req"], body: [{op:".byte",args:["0x46"]}, {op:".4byte",args:["\\param0"]}] },
  { name: "watch", args: [], body: [{op:".byte",args:["0x47"]}] },
  { name: "get_hold_effect", args: ["battler:req"], body: [{op:".byte",args:["0x48"]}, {op:".byte",args:["\\battler"]}] },
  { name: "get_gender", args: ["battler:req"], body: [{op:".byte",args:["0x49"]}, {op:".byte",args:["\\battler"]}] },
  { name: "is_first_turn_for", args: ["battler:req"], body: [{op:".byte",args:["0x4a"]}, {op:".byte",args:["\\battler"]}] },
  { name: "get_stockpile_count", args: ["battler:req"], body: [{op:".byte",args:["0x4b"]}, {op:".byte",args:["\\battler"]}] },
  { name: "is_double_battle", args: [], body: [{op:".byte",args:["0x4c"]}] },
  { name: "get_used_held_item", args: ["battler:req"], body: [{op:".byte",args:["0x4d"]}, {op:".byte",args:["\\battler"]}] },
  { name: "get_move_type_from_result", args: [], body: [{op:".byte",args:["0x4e"]}] },
  { name: "get_move_power_from_result", args: [], body: [{op:".byte",args:["0x4f"]}] },
  { name: "get_move_effect_from_result", args: [], body: [{op:".byte",args:["0x50"]}] },
  { name: "get_protect_count", args: ["battler:req"], body: [{op:".byte",args:["0x51"]}, {op:".byte",args:["\\battler"]}] },
  { name: "nop_52", args: [], body: [{op:".byte",args:["0x52"]}] },
  { name: "nop_53", args: [], body: [{op:".byte",args:["0x53"]}] },
  { name: "nop_54", args: [], body: [{op:".byte",args:["0x54"]}] },
  { name: "nop_55", args: [], body: [{op:".byte",args:["0x55"]}] },
  { name: "nop_56", args: [], body: [{op:".byte",args:["0x56"]}] },
  { name: "nop_57", args: [], body: [{op:".byte",args:["0x57"]}] },
  { name: "call", args: ["param0:req"], body: [{op:".byte",args:["0x58"]}, {op:".4byte",args:["\\param0"]}] },
  { name: "goto", args: ["param0:req"], body: [{op:".byte",args:["0x59"]}, {op:".4byte",args:["\\param0"]}] },
  { name: "end", args: [], body: [{op:".byte",args:["0x5a"]}] },
  { name: "if_level_cond", args: ["param0:req", "param1:req"], body: [{op:".byte",args:["0x5b"]}, {op:".byte",args:["\\param0"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_target_taunted", args: ["param0:req"], body: [{op:".byte",args:["0x5c"]}, {op:".4byte",args:["\\param0"]}] },
  { name: "if_target_not_taunted", args: ["param0:req"], body: [{op:".byte",args:["0x5d"]}, {op:".4byte",args:["\\param0"]}] },
  { name: "if_target_is_ally", args: ["param0:req"], body: [{op:".byte",args:["0x5e"]}, {op:".4byte",args:["\\param0"]}] },
  { name: "is_of_type", args: ["battler:req", "type:req"], body: [{op:".byte",args:["0x5f"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\type"]}] },
  { name: "check_ability", args: ["battler:req", "ability:req"], body: [{op:".byte",args:["0x60"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\ability"]}] },
  { name: "if_flash_fired", args: ["battler:req", "param1:req"], body: [{op:".byte",args:["0x61"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\param1"]}] },
  { name: "if_holds_item", args: ["battler:req", "param1:req", "param2:req"], body: [{op:".byte",args:["0x62"]}, {op:".byte",args:["\\battler"]}, {op:".2byte",args:["\\param1"]}, {op:".4byte",args:["\\param2"]}] },
  { name: "get_curr_move_type", args: [], body: [{op:"get_type",args:["AI_TYPE_MOVE"]}] },
  { name: "get_user_type1", args: [], body: [{op:"get_type",args:["AI_TYPE1_USER"]}] },
  { name: "get_user_type2", args: [], body: [{op:"get_type",args:["AI_TYPE2_USER"]}] },
  { name: "get_target_type1", args: [], body: [{op:"get_type",args:["AI_TYPE1_TARGET"]}] },
  { name: "get_target_type2", args: [], body: [{op:"get_type",args:["AI_TYPE2_TARGET"]}] },
  { name: "if_ability", args: ["battler:req", "ability:req", "ptr:req"], body: [{op:"check_ability",args:["\\battler","\\ability"]}, {op:"if_equal",args:["1","\\ptr"]}] },
  { name: "if_no_ability", args: ["battler:req", "ability:req", "ptr:req"], body: [{op:"check_ability",args:["\\battler","\\ability"]}, {op:"if_equal",args:["0","\\ptr"]}] },
  { name: "if_type", args: ["battler:req", "type:req", "ptr:req"], body: [{op:"is_of_type",args:["\\battler","\\type"]}, {op:"if_equal",args:["1","\\ptr"]}] },
  { name: "if_no_type", args: ["battler:req", "type:req", "ptr:req"], body: [{op:"is_of_type",args:["\\battler","\\type"]}, {op:"if_equal",args:["0","\\ptr"]}] },
  { name: "if_target_faster", args: ["ptr:req"], body: [{op:"if_user_goes",args:["1","\\ptr"]}] },
  { name: "if_user_faster", args: ["ptr:req"], body: [{op:"if_user_goes",args:["0","\\ptr"]}] },
  { name: "if_double_battle", args: ["ptr:req"], body: [{op:"is_double_battle",args:[]}, {op:"if_equal",args:["1","\\ptr"]}] },
  { name: "if_not_double_battle", args: ["ptr:req"], body: [{op:"is_double_battle",args:[]}, {op:"if_equal",args:["0","\\ptr"]}] },
  { name: "if_any_move_disabled", args: ["battler:req", "ptr:req"], body: [{op:"if_any_move_disabled_or_encored",args:["\\battler","0","\\ptr"]}] },
  { name: "if_any_move_encored", args: ["battler:req", "ptr:req"], body: [{op:"if_any_move_disabled_or_encored",args:["\\battler","1","\\ptr"]}] },
] as const;
