// AUTO-GENERATED from asm/macros/battle_script.inc by extract-decomp-asm.mjs
// Do not edit manually — re-run `npm run extract:decomp-asm` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/asm/macros/battle_script.inc
// Generated: 2026-04-26

// ─── .macro definitions (asm macro → opcode mapping bodies) ─────────────────
export const MACROS = [
  { name: "attackcanceler", args: [], body: [{op:".byte",args:["B_SCR_OP_ATTACKCANCELER"]}] },
  { name: "accuracycheck", args: ["failPtr:req", "move:req"], body: [{op:".byte",args:["B_SCR_OP_ACCURACYCHECK"]}, {op:".4byte",args:["\\failPtr"]}, {op:".2byte",args:["\\move"]}] },
  { name: "attackstring", args: [], body: [{op:".byte",args:["B_SCR_OP_ATTACKSTRING"]}] },
  { name: "ppreduce", args: [], body: [{op:".byte",args:["B_SCR_OP_PPREDUCE"]}] },
  { name: "critcalc", args: [], body: [{op:".byte",args:["B_SCR_OP_CRITCALC"]}] },
  { name: "damagecalc", args: [], body: [{op:".byte",args:["B_SCR_OP_DAMAGECALC"]}] },
  { name: "typecalc", args: [], body: [{op:".byte",args:["B_SCR_OP_TYPECALC"]}] },
  { name: "adjustnormaldamage", args: [], body: [{op:".byte",args:["B_SCR_OP_ADJUSTNORMALDAMAGE"]}] },
  { name: "adjustnormaldamage2", args: [], body: [{op:".byte",args:["B_SCR_OP_ADJUSTNORMALDAMAGE2"]}] },
  { name: "attackanimation", args: [], body: [{op:".byte",args:["B_SCR_OP_ATTACKANIMATION"]}] },
  { name: "waitanimation", args: [], body: [{op:".byte",args:["B_SCR_OP_WAITANIMATION"]}] },
  { name: "healthbarupdate", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_HEALTHBARUPDATE"]}, {op:".byte",args:["\\battler"]}] },
  { name: "datahpupdate", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_DATAHPUPDATE"]}, {op:".byte",args:["\\battler"]}] },
  { name: "critmessage", args: [], body: [{op:".byte",args:["B_SCR_OP_CRITMESSAGE"]}] },
  { name: "effectivenesssound", args: [], body: [{op:".byte",args:["B_SCR_OP_EFFECTIVENESSSOUND"]}] },
  { name: "resultmessage", args: [], body: [{op:".byte",args:["B_SCR_OP_RESULTMESSAGE"]}] },
  { name: "printstring", args: ["id:req"], body: [{op:".byte",args:["B_SCR_OP_PRINTSTRING"]}, {op:".2byte",args:["\\id"]}] },
  { name: "printselectionstring", args: ["id:req"], body: [{op:".byte",args:["B_SCR_OP_PRINTSELECTIONSTRING"]}, {op:".2byte",args:["\\id"]}] },
  { name: "waitmessage", args: ["time:req"], body: [{op:".byte",args:["B_SCR_OP_WAITMESSAGE"]}, {op:".2byte",args:["\\time"]}] },
  { name: "printfromtable", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_PRINTFROMTABLE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "printselectionstringfromtable", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_PRINTSELECTIONSTRINGFROMTABLE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "seteffectwithchance", args: [], body: [{op:".byte",args:["B_SCR_OP_SETEFFECTWITHCHANCE"]}] },
  { name: "seteffectprimary", args: [], body: [{op:".byte",args:["B_SCR_OP_SETEFFECTPRIMARY"]}] },
  { name: "seteffectsecondary", args: [], body: [{op:".byte",args:["B_SCR_OP_SETEFFECTSECONDARY"]}] },
  { name: "clearstatusfromeffect", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_CLEARSTATUSFROMEFFECT"]}, {op:".byte",args:["\\battler"]}] },
  { name: "tryfaintmon", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_TRYFAINTMON"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["FALSE"]}, {op:".4byte",args:["NULL"]}] },
  { name: "tryfaintmon_spikes", args: ["battler:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYFAINTMON"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["TRUE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "dofaintanimation", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_DOFAINTANIMATION"]}, {op:".byte",args:["\\battler"]}] },
  { name: "cleareffectsonfaint", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_CLEAREFFECTSONFAINT"]}, {op:".byte",args:["\\battler"]}] },
  { name: "jumpifstatus", args: ["battler:req", "status1:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFSTATUS"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status1"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifstatus2", args: ["battler:req", "status2:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFSTATUS2"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status2"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifability", args: ["battler:req", "ability:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFABILITY"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\ability"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifsideaffecting", args: ["battler:req", "sidestatus:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFSIDEAFFECTING"]}, {op:".byte",args:["\\battler"]}, {op:".2byte",args:["\\sidestatus"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifstat", args: ["battler:req", "ifflag:req", "stat:req", "value:req", "ptr"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFSTAT"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\ifflag"]}, {op:".byte",args:["\\stat"]}, {op:".byte",args:["\\value"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifstatus3condition", args: ["battler:req", "status3:req", "condition:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFSTATUS3CONDITION"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status3"]}, {op:".byte",args:["\\condition"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpiftype", args: ["battler:req", "type:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFTYPE"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\type"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "getexp", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_GETEXP"]}, {op:".byte",args:["\\battler"]}] },
  { name: "checkteamslost", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_CHECKTEAMSLOST"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "movevaluescleanup", args: [], body: [{op:".byte",args:["B_SCR_OP_MOVEVALUESCLEANUP"]}] },
  { name: "setmultihit", args: ["value:req"], body: [{op:".byte",args:["B_SCR_OP_SETMULTIHIT"]}, {op:".byte",args:["\\value"]}] },
  { name: "decrementmultihit", args: ["value:req"], body: [{op:".byte",args:["B_SCR_OP_DECREMENTMULTIHIT"]}, {op:".4byte",args:["\\value"]}] },
  { name: "goto", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_GOTO"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifbyte", args: ["ifflag:req", "val:req", "byte:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFBYTE"]}, {op:".byte",args:["\\ifflag"]}, {op:".4byte",args:["\\val"]}, {op:".byte",args:["\\byte"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifhalfword", args: ["ifflag:req", "val:req", "hword:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFHALFWORD"]}, {op:".byte",args:["\\ifflag"]}, {op:".4byte",args:["\\val"]}, {op:".2byte",args:["\\hword"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifword", args: ["ifflag:req", "val:req", "word:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFWORD"]}, {op:".byte",args:["\\ifflag"]}, {op:".4byte",args:["\\val"]}, {op:".4byte",args:["\\word"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifarrayequal", args: ["val1:req", "val2:req", "size:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFARRAYEQUAL"]}, {op:".4byte",args:["\\val1"]}, {op:".4byte",args:["\\val2"]}, {op:".byte",args:["\\size"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifarraynotequal", args: ["val1:req", "val2:req", "size:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFARRAYNOTEQUAL"]}, {op:".4byte",args:["\\val1"]}, {op:".4byte",args:["\\val2"]}, {op:".byte",args:["\\size"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "setbyte", args: ["ptr:req", "byte:req"], body: [{op:".byte",args:["B_SCR_OP_SETBYTE"]}, {op:".4byte",args:["\\ptr"]}, {op:".byte",args:["\\byte"]}] },
  { name: "addbyte", args: ["ptr:req", "byte:req"], body: [{op:".byte",args:["B_SCR_OP_ADDBYTE"]}, {op:".4byte",args:["\\ptr"]}, {op:".byte",args:["\\byte"]}] },
  { name: "subbyte", args: ["ptr:req", "byte:req"], body: [{op:".byte",args:["B_SCR_OP_SUBBYTE"]}, {op:".4byte",args:["\\ptr"]}, {op:".byte",args:["\\byte"]}] },
  { name: "copyarray", args: ["dest:req", "src:req", "size:req"], body: [{op:".byte",args:["B_SCR_OP_COPYARRAY"]}, {op:".4byte",args:["\\dest"]}, {op:".4byte",args:["\\src"]}, {op:".byte",args:["\\size"]}] },
  { name: "copyarraywithindex", args: ["dest:req", "src:req", "index:req", "size:req"], body: [{op:".byte",args:["B_SCR_OP_COPYARRAYWITHINDEX"]}, {op:".4byte",args:["\\dest"]}, {op:".4byte",args:["\\src"]}, {op:".4byte",args:["\\index"]}, {op:".byte",args:["\\size"]}] },
  { name: "orbyte", args: ["ptr:req", "byte:req"], body: [{op:".byte",args:["B_SCR_OP_ORBYTE"]}, {op:".4byte",args:["\\ptr"]}, {op:".byte",args:["\\byte"]}] },
  { name: "orhalfword", args: ["ptr:req", "hword:req"], body: [{op:".byte",args:["B_SCR_OP_ORHALFWORD"]}, {op:".4byte",args:["\\ptr"]}, {op:".2byte",args:["\\hword"]}] },
  { name: "orword", args: ["ptr:req", "word:req"], body: [{op:".byte",args:["B_SCR_OP_ORWORD"]}, {op:".4byte",args:["\\ptr"]}, {op:".4byte",args:["\\word"]}] },
  { name: "bicbyte", args: ["ptr:req", "byte:req"], body: [{op:".byte",args:["B_SCR_OP_BICBYTE"]}, {op:".4byte",args:["\\ptr"]}, {op:".byte",args:["\\byte"]}] },
  { name: "bichalfword", args: ["ptr:req", "hword:req"], body: [{op:".byte",args:["B_SCR_OP_BICHALFWORD"]}, {op:".4byte",args:["\\ptr"]}, {op:".2byte",args:["\\hword"]}] },
  { name: "bicword", args: ["ptr:req", "word:req"], body: [{op:".byte",args:["B_SCR_OP_BICWORD"]}, {op:".4byte",args:["\\ptr"]}, {op:".4byte",args:["\\word"]}] },
  { name: "pause", args: ["time:req"], body: [{op:".byte",args:["B_SCR_OP_PAUSE"]}, {op:".2byte",args:["\\time"]}] },
  { name: "waitstate", args: [], body: [{op:".byte",args:["B_SCR_OP_WAITSTATE"]}] },
  { name: "healthbar_update", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_HEALTHBAR_UPDATE"]}, {op:".byte",args:["\\battler"]}] },
  { name: "end", args: [], body: [{op:".byte",args:["B_SCR_OP_END"]}] },
  { name: "end2", args: [], body: [{op:".byte",args:["B_SCR_OP_END2"]}] },
  { name: "end3", args: [], body: [{op:".byte",args:["B_SCR_OP_END3"]}] },
  { name: "jumpifaffectedbyprotect", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFAFFECTEDBYPROTECT"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "call", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_CALL"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpiftype2", args: ["battler:req", "type:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFTYPE2"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\type"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifabilitypresent", args: ["ability:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFABILITYPRESENT"]}, {op:".byte",args:["\\ability"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "endselectionscript", args: [], body: [{op:".byte",args:["B_SCR_OP_ENDSELECTIONSCRIPT"]}] },
  { name: "playanimation", args: ["battler:req", "animType:req", "arg=NULL"], body: [{op:".byte",args:["B_SCR_OP_PLAYANIMATION"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\animType"]}, {op:".4byte",args:["\\arg"]}] },
  { name: "playanimation_var", args: ["battler:req", "animType:req", "arg=NULL"], body: [{op:".byte",args:["B_SCR_OP_PLAYANIMATION_VAR"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\animType"]}, {op:".4byte",args:["\\arg"]}] },
  { name: "setgraphicalstatchangevalues", args: [], body: [{op:".byte",args:["B_SCR_OP_SETGRAPHICALSTATCHANGEVALUES"]}] },
  { name: "playstatchangeanimation", args: ["battler:req", "stats:req", "statchange:req"], body: [{op:".byte",args:["B_SCR_OP_PLAYSTATCHANGEANIMATION"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\stats"]}, {op:".byte",args:["\\statchange"]}] },
  { name: "moveend", args: ["endMode:req", "endState:req"], body: [{op:".byte",args:["B_SCR_OP_MOVEEND"]}, {op:".byte",args:["\\endMode"]}, {op:".byte",args:["\\endState"]}] },
  { name: "moveendall", args: [], body: [{op:"setbyte",args:["sMOVEEND_STATE","0"]}, {op:"moveend",args:["0","0"]}] },
  { name: "moveendcase", args: ["case:req"], body: [{op:"setbyte",args:["sMOVEEND_STATE","\\case"]}, {op:"moveend",args:["1","0"]}] },
  { name: "moveendfrom", args: ["from:req"], body: [{op:"setbyte",args:["sMOVEEND_STATE","\\from"]}, {op:"moveend",args:["0","0"]}] },
  { name: "moveendto", args: ["to:req"], body: [{op:"setbyte",args:["sMOVEEND_STATE","0"]}, {op:"moveend",args:["2","\\to"]}] },
  { name: "moveendfromto", args: ["from:req", "to:req"], body: [{op:"setbyte",args:["sMOVEEND_STATE","\\from"]}, {op:"moveend",args:["2","\\to"]}] },
  { name: "typecalc2", args: [], body: [{op:".byte",args:["B_SCR_OP_TYPECALC2"]}] },
  { name: "returnatktoball", args: [], body: [{op:".byte",args:["B_SCR_OP_RETURNATKTOBALL"]}] },
  { name: "getswitchedmondata", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_GETSWITCHEDMONDATA"]}, {op:".byte",args:["\\battler"]}] },
  { name: "switchindataupdate", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_SWITCHINDATAUPDATE"]}, {op:".byte",args:["\\battler"]}] },
  { name: "switchinanim", args: ["battler:req", "dontclearsubstitutebit:req"], body: [{op:".byte",args:["B_SCR_OP_SWITCHINANIM"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\dontclearsubstitutebit"]}] },
  { name: "jumpifcantswitch", args: ["battler:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFCANTSWITCH"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "openpartyscreen", args: ["battler:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_OPENPARTYSCREEN"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "switchhandleorder", args: ["battler:req", "state:req"], body: [{op:".byte",args:["B_SCR_OP_SWITCHHANDLEORDER"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\state"]}] },
  { name: "switchineffects", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_SWITCHINEFFECTS"]}, {op:".byte",args:["\\battler"]}] },
  { name: "trainerslidein", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_TRAINERSLIDEIN"]}, {op:".byte",args:["\\battler"]}] },
  { name: "playse", args: ["song:req"], body: [{op:".byte",args:["B_SCR_OP_PLAYSE"]}, {op:".2byte",args:["\\song"]}] },
  { name: "fanfare", args: ["song:req"], body: [{op:".byte",args:["B_SCR_OP_FANFARE"]}, {op:".2byte",args:["\\song"]}] },
  { name: "playfaintcry", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_PLAYFAINTCRY"]}, {op:".byte",args:["\\battler"]}] },
  { name: "endlinkbattle", args: [], body: [{op:".byte",args:["B_SCR_OP_ENDLINKBATTLE"]}] },
  { name: "returntoball", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_RETURNTOBALL"]}, {op:".byte",args:["\\battler"]}] },
  { name: "handlelearnnewmove", args: ["learnedMovePtr:req", "nothingToLearnPtr:req", "isFirstMove:req"], body: [{op:".byte",args:["B_SCR_OP_HANDLELEARNNEWMOVE"]}, {op:".4byte",args:["\\learnedMovePtr"]}, {op:".4byte",args:["\\nothingToLearnPtr"]}, {op:".byte",args:["\\isFirstMove"]}] },
  { name: "yesnoboxlearnmove", args: ["forgotMovePtr:req"], body: [{op:".byte",args:["B_SCR_OP_YESNOBOXLEARNMOVE"]}, {op:".4byte",args:["\\forgotMovePtr"]}] },
  { name: "yesnoboxstoplearningmove", args: ["noPtr:req"], body: [{op:".byte",args:["B_SCR_OP_YESNOBOXSTOPLEARNINGMOVE"]}, {op:".4byte",args:["\\noPtr"]}] },
  { name: "hitanimation", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_HITANIMATION"]}, {op:".byte",args:["\\battler"]}] },
  { name: "getmoneyreward", args: [], body: [{op:".byte",args:["B_SCR_OP_GETMONEYREWARD"]}] },
  { name: "updatebattlermoves", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_UPDATEBATTLERMOVES"]}, {op:".byte",args:["\\battler"]}] },
  { name: "swapattackerwithtarget", args: [], body: [{op:".byte",args:["B_SCR_OP_SWAPATTACKERWITHTARGET"]}] },
  { name: "incrementgamestat", args: ["stat:req"], body: [{op:".byte",args:["B_SCR_OP_INCREMENTGAMESTAT"]}, {op:".byte",args:["\\stat"]}] },
  { name: "drawpartystatussummary", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_DRAWPARTYSTATUSSUMMARY"]}, {op:".byte",args:["\\battler"]}] },
  { name: "hidepartystatussummary", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_HIDEPARTYSTATUSSUMMARY"]}, {op:".byte",args:["\\battler"]}] },
  { name: "jumptocalledmove", args: ["notChosenMove:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPTOCALLEDMOVE"]}, {op:".byte",args:["\\notChosenMove"]}] },
  { name: "statusanimation", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_STATUSANIMATION"]}, {op:".byte",args:["\\battler"]}] },
  { name: "status2animation", args: ["battler:req", "status2:req"], body: [{op:".byte",args:["B_SCR_OP_STATUS2ANIMATION"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\status2"]}] },
  { name: "chosenstatusanimation", args: ["battler:req", "isStatus2:req", "status:req"], body: [{op:".byte",args:["B_SCR_OP_CHOSENSTATUSANIMATION"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\isStatus2"]}, {op:".4byte",args:["\\status"]}] },
  { name: "yesnobox", args: [], body: [{op:".byte",args:["B_SCR_OP_YESNOBOX"]}] },
  { name: "cancelallactions", args: [], body: [{op:".byte",args:["B_SCR_OP_CANCELALLACTIONS"]}] },
  { name: "adjustsetdamage", args: [], body: [{op:".byte",args:["B_SCR_OP_ADJUSTSETDAMAGE"]}] },
  { name: "removeitem", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_REMOVEITEM"]}, {op:".byte",args:["\\battler"]}] },
  { name: "atknameinbuff1", args: [], body: [{op:".byte",args:["B_SCR_OP_ATKNAMEINBUFF1"]}] },
  { name: "drawlvlupbox", args: [], body: [{op:".byte",args:["B_SCR_OP_DRAWLVLUPBOX"]}] },
  { name: "resetsentmonsvalue", args: [], body: [{op:".byte",args:["B_SCR_OP_RESETSENTMONSVALUE"]}] },
  { name: "setatktoplayer0", args: [], body: [{op:".byte",args:["B_SCR_OP_SETATKTOPLAYER0"]}] },
  { name: "makevisible", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_MAKEVISIBLE"]}, {op:".byte",args:["\\battler"]}] },
  { name: "recordlastability", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_RECORDLASTABILITY"]}, {op:".byte",args:["\\battler"]}] },
  { name: "buffermovetolearn", args: [], body: [{op:".byte",args:["B_SCR_OP_BUFFERMOVETOLEARN"]}] },
  { name: "jumpifplayerran", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFPLAYERRAN"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "hpthresholds", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_HPTHRESHOLDS"]}, {op:".byte",args:["\\battler"]}] },
  { name: "hpthresholds2", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_HPTHRESHOLDS2"]}, {op:".byte",args:["\\battler"]}] },
  { name: "useitemonopponent", args: [], body: [{op:".byte",args:["B_SCR_OP_USEITEMONOPPONENT"]}] },
  { name: "various", args: ["battler:req", "id:req"], body: [{op:".byte",args:["B_SCR_OP_VARIOUS"]}, {op:".byte",args:["\\battler"]}, {op:".byte",args:["\\id"]}] },
  { name: "setprotectlike", args: [], body: [{op:".byte",args:["B_SCR_OP_SETPROTECTLIKE"]}] },
  { name: "tryexplosion", args: [], body: [{op:".byte",args:["B_SCR_OP_TRYEXPLOSION"]}] },
  { name: "setatkhptozero", args: [], body: [{op:".byte",args:["B_SCR_OP_SETATKHPTOZERO"]}] },
  { name: "jumpifnexttargetvalid", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFNEXTTARGETVALID"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "tryhealhalfhealth", args: ["ptr:req", "battler:req"], body: [{op:".byte",args:["B_SCR_OP_TRYHEALHALFHEALTH"]}, {op:".4byte",args:["\\ptr"]}, {op:".byte",args:["\\battler"]}] },
  { name: "trymirrormove", args: [], body: [{op:".byte",args:["B_SCR_OP_TRYMIRRORMOVE"]}] },
  { name: "setrain", args: [], body: [{op:".byte",args:["B_SCR_OP_SETRAIN"]}] },
  { name: "setreflect", args: [], body: [{op:".byte",args:["B_SCR_OP_SETREFLECT"]}] },
  { name: "setseeded", args: [], body: [{op:".byte",args:["B_SCR_OP_SETSEEDED"]}] },
  { name: "manipulatedamage", args: ["mode:req"], body: [{op:".byte",args:["B_SCR_OP_MANIPULATEDAMAGE"]}, {op:".byte",args:["\\mode"]}] },
  { name: "trysetrest", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSETREST"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifnotfirstturn", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFNOTFIRSTTURN"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "nop", args: [], body: [{op:".byte",args:["B_SCR_OP_NOP"]}] },
  { name: "jumpifcantmakeasleep", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFCANTMAKEASLEEP"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "stockpile", args: [], body: [{op:".byte",args:["B_SCR_OP_STOCKPILE"]}] },
  { name: "stockpiletobasedamage", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_STOCKPILETOBASEDAMAGE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "stockpiletohpheal", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_STOCKPILETOHPHEAL"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "negativedamage", args: [], body: [{op:".byte",args:["B_SCR_OP_NEGATIVEDAMAGE"]}] },
  { name: "statbuffchange", args: ["flags:req", "jumpptr:req"], body: [{op:".byte",args:["B_SCR_OP_STATBUFFCHANGE"]}, {op:".byte",args:["\\flags"]}, {op:".4byte",args:["\\jumpptr"]}] },
  { name: "normalisebuffs", args: [], body: [{op:".byte",args:["B_SCR_OP_NORMALISEBUFFS"]}] },
  { name: "setbide", args: [], body: [{op:".byte",args:["B_SCR_OP_SETBIDE"]}] },
  { name: "confuseifrepeatingattackends", args: [], body: [{op:".byte",args:["B_SCR_OP_CONFUSEIFREPEATINGATTACKENDS"]}] },
  { name: "setmultihitcounter", args: ["val:req"], body: [{op:".byte",args:["B_SCR_OP_SETMULTIHITCOUNTER"]}, {op:".byte",args:["\\val"]}] },
  { name: "initmultihitstring", args: [], body: [{op:".byte",args:["B_SCR_OP_INITMULTIHITSTRING"]}] },
  { name: "forcerandomswitch", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_FORCERANDOMSWITCH"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "tryconversiontypechange", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYCONVERSIONTYPECHANGE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "givepaydaymoney", args: [], body: [{op:".byte",args:["B_SCR_OP_GIVEPAYDAYMONEY"]}] },
  { name: "setlightscreen", args: [], body: [{op:".byte",args:["B_SCR_OP_SETLIGHTSCREEN"]}] },
  { name: "tryKO", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYKO"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "damagetohalftargethp", args: [], body: [{op:".byte",args:["B_SCR_OP_DAMAGETOHALFTARGETHP"]}] },
  { name: "setsandstorm", args: [], body: [{op:".byte",args:["B_SCR_OP_SETSANDSTORM"]}] },
  { name: "weatherdamage", args: [], body: [{op:".byte",args:["B_SCR_OP_WEATHERDAMAGE"]}] },
  { name: "tryinfatuating", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYINFATUATING"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "updatestatusicon", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_UPDATESTATUSICON"]}, {op:".byte",args:["\\battler"]}] },
  { name: "setmist", args: [], body: [{op:".byte",args:["B_SCR_OP_SETMIST"]}] },
  { name: "setfocusenergy", args: [], body: [{op:".byte",args:["B_SCR_OP_SETFOCUSENERGY"]}] },
  { name: "transformdataexecution", args: [], body: [{op:".byte",args:["B_SCR_OP_TRANSFORMDATAEXECUTION"]}] },
  { name: "setsubstitute", args: [], body: [{op:".byte",args:["B_SCR_OP_SETSUBSTITUTE"]}] },
  { name: "mimicattackcopy", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_MIMICATTACKCOPY"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "metronome", args: [], body: [{op:".byte",args:["B_SCR_OP_METRONOME"]}] },
  { name: "dmgtolevel", args: [], body: [{op:".byte",args:["B_SCR_OP_DMGTOLEVEL"]}] },
  { name: "psywavedamageeffect", args: [], body: [{op:".byte",args:["B_SCR_OP_PSYWAVEDAMAGEEFFECT"]}] },
  { name: "counterdamagecalculator", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_COUNTERDAMAGECALCULATOR"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "mirrorcoatdamagecalculator", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_MIRRORCOATDAMAGECALCULATOR"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "disablelastusedattack", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_DISABLELASTUSEDATTACK"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trysetencore", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSETENCORE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "painsplitdmgcalc", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_PAINSPLITDMGCALC"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "settypetorandomresistance", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_SETTYPETORANDOMRESISTANCE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "setalwayshitflag", args: [], body: [{op:".byte",args:["B_SCR_OP_SETALWAYSHITFLAG"]}] },
  { name: "copymovepermanently", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_COPYMOVEPERMANENTLY"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trychoosesleeptalkmove", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYCHOOSESLEEPTALKMOVE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "setdestinybond", args: [], body: [{op:".byte",args:["B_SCR_OP_SETDESTINYBOND"]}] },
  { name: "trysetdestinybondtohappen", args: [], body: [{op:".byte",args:["B_SCR_OP_TRYSETDESTINYBONDTOHAPPEN"]}] },
  { name: "remaininghptopower", args: [], body: [{op:".byte",args:["B_SCR_OP_REMAININGHPTOPOWER"]}] },
  { name: "tryspiteppreduce", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSPITEPPREDUCE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "healpartystatus", args: [], body: [{op:".byte",args:["B_SCR_OP_HEALPARTYSTATUS"]}] },
  { name: "cursetarget", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_CURSETARGET"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trysetspikes", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSETSPIKES"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "setforesight", args: [], body: [{op:".byte",args:["B_SCR_OP_SETFORESIGHT"]}] },
  { name: "trysetperishsong", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSETPERISHSONG"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "rolloutdamagecalculation", args: [], body: [{op:".byte",args:["B_SCR_OP_ROLLOUTDAMAGECALCULATION"]}] },
  { name: "jumpifconfusedandstatmaxed", args: ["stat:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFCONFUSEDANDSTATMAXED"]}, {op:".byte",args:["\\stat"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "furycuttercalc", args: [], body: [{op:".byte",args:["B_SCR_OP_FURYCUTTERCALC"]}] },
  { name: "friendshiptodamagecalculation", args: [], body: [{op:".byte",args:["B_SCR_OP_FRIENDSHIPTODAMAGECALCULATION"]}] },
  { name: "presentdamagecalculation", args: [], body: [{op:".byte",args:["B_SCR_OP_PRESENTDAMAGECALCULATION"]}] },
  { name: "setsafeguard", args: [], body: [{op:".byte",args:["B_SCR_OP_SETSAFEGUARD"]}] },
  { name: "magnitudedamagecalculation", args: [], body: [{op:".byte",args:["B_SCR_OP_MAGNITUDEDAMAGECALCULATION"]}] },
  { name: "jumpifnopursuitswitchdmg", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFNOPURSUITSWITCHDMG"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "setsunny", args: [], body: [{op:".byte",args:["B_SCR_OP_SETSUNNY"]}] },
  { name: "maxattackhalvehp", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_MAXATTACKHALVEHP"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "copyfoestats", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_COPYFOESTATS"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "rapidspinfree", args: [], body: [{op:".byte",args:["B_SCR_OP_RAPIDSPINFREE"]}] },
  { name: "setdefensecurlbit", args: [], body: [{op:".byte",args:["B_SCR_OP_SETDEFENSECURLBIT"]}] },
  { name: "recoverbasedonsunlight", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_RECOVERBASEDONSUNLIGHT"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "hiddenpowercalc", args: [], body: [{op:".byte",args:["B_SCR_OP_HIDDENPOWERCALC"]}] },
  { name: "selectfirstvalidtarget", args: [], body: [{op:".byte",args:["B_SCR_OP_SELECTFIRSTVALIDTARGET"]}] },
  { name: "trysetfutureattack", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSETFUTUREATTACK"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trydobeatup", args: ["endPtr:req", "failPtr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYDOBEATUP"]}, {op:".4byte",args:["\\endPtr"]}, {op:".4byte",args:["\\failPtr"]}] },
  { name: "setsemiinvulnerablebit", args: [], body: [{op:".byte",args:["B_SCR_OP_SETSEMIINVULNERABLEBIT"]}] },
  { name: "clearsemiinvulnerablebit", args: [], body: [{op:".byte",args:["B_SCR_OP_CLEARSEMIINVULNERABLEBIT"]}] },
  { name: "setminimize", args: [], body: [{op:".byte",args:["B_SCR_OP_SETMINIMIZE"]}] },
  { name: "sethail", args: [], body: [{op:".byte",args:["B_SCR_OP_SETHAIL"]}] },
  { name: "trymemento", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYMEMENTO"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "setforcedtarget", args: [], body: [{op:".byte",args:["B_SCR_OP_SETFORCEDTARGET"]}] },
  { name: "setcharge", args: [], body: [{op:".byte",args:["B_SCR_OP_SETCHARGE"]}] },
  { name: "callenvironmentattack", args: [], body: [{op:".byte",args:["B_SCR_OP_CALLENVIRONMENTATTACK"]}] },
  { name: "cureifburnedparalyzedorpoisoned", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_CUREIFBURNEDPARALYZEDORPOISONED"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "settorment", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_SETTORMENT"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "jumpifnodamage", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFNODAMAGE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "settaunt", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_SETTAUNT"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trysethelpinghand", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSETHELPINGHAND"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "tryswapitems", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSWAPITEMS"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trycopyability", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYCOPYABILITY"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trywish", args: ["turnNumber:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYWISH"]}, {op:".byte",args:["\\turnNumber"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trysetroots", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSETROOTS"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "doubledamagedealtifdamaged", args: [], body: [{op:".byte",args:["B_SCR_OP_DOUBLEDAMAGEDEALTIFDAMAGED"]}] },
  { name: "setyawn", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_SETYAWN"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "setdamagetohealthdifference", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_SETDAMAGETOHEALTHDIFFERENCE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "scaledamagebyhealthratio", args: [], body: [{op:".byte",args:["B_SCR_OP_SCALEDAMAGEBYHEALTHRATIO"]}] },
  { name: "tryswapabilities", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSWAPABILITIES"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "tryimprison", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYIMPRISON"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trysetgrudge", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSETGRUDGE"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "weightdamagecalculation", args: [], body: [{op:".byte",args:["B_SCR_OP_WEIGHTDAMAGECALCULATION"]}] },
  { name: "assistattackselect", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_ASSISTATTACKSELECT"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trysetmagiccoat", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSETMAGICCOAT"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trysetsnatch", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSETSNATCH"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "trygetintimidatetarget", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYGETINTIMIDATETARGET"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "switchoutabilities", args: ["battler:req"], body: [{op:".byte",args:["B_SCR_OP_SWITCHOUTABILITIES"]}, {op:".byte",args:["\\battler"]}] },
  { name: "jumpifhasnohp", args: ["battler:req", "ptr:req"], body: [{op:".byte",args:["B_SCR_OP_JUMPIFHASNOHP"]}, {op:".byte",args:["\\battler"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "getsecretpowereffect", args: [], body: [{op:".byte",args:["B_SCR_OP_GETSECRETPOWEREFFECT"]}] },
  { name: "pickup", args: [], body: [{op:".byte",args:["B_SCR_OP_PICKUP"]}] },
  { name: "docastformchangeanimation", args: [], body: [{op:".byte",args:["B_SCR_OP_DOCASTFORMCHANGEANIMATION"]}] },
  { name: "trycastformdatachange", args: [], body: [{op:".byte",args:["B_SCR_OP_TRYCASTFORMDATACHANGE"]}] },
  { name: "settypebasedhalvers", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_SETTYPEBASEDHALVERS"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "setweatherballtype", args: [], body: [{op:".byte",args:["B_SCR_OP_SETWEATHERBALLTYPE"]}] },
  { name: "tryrecycleitem", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYRECYCLEITEM"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "settypetoenvironment", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_SETTYPETOENVIRONMENT"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "pursuitdoubles", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_PURSUITDOUBLES"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "snatchsetbattlers", args: [], body: [{op:".byte",args:["B_SCR_OP_SNATCHSETBATTLERS"]}] },
  { name: "removelightscreenreflect", args: [], body: [{op:".byte",args:["B_SCR_OP_REMOVELIGHTSCREENREFLECT"]}] },
  { name: "handleballthrow", args: [], body: [{op:".byte",args:["B_SCR_OP_HANDLEBALLTHROW"]}] },
  { name: "givecaughtmon", args: [], body: [{op:".byte",args:["B_SCR_OP_GIVECAUGHTMON"]}] },
  { name: "trysetcaughtmondexflags", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYSETCAUGHTMONDEXFLAGS"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "displaydexinfo", args: [], body: [{op:".byte",args:["B_SCR_OP_DISPLAYDEXINFO"]}] },
  { name: "trygivecaughtmonnick", args: ["ptr:req"], body: [{op:".byte",args:["B_SCR_OP_TRYGIVECAUGHTMONNICK"]}, {op:".4byte",args:["\\ptr"]}] },
  { name: "subattackerhpbydmg", args: [], body: [{op:".byte",args:["B_SCR_OP_SUBATTACKERHPBYDMG"]}] },
  { name: "removeattackerstatus1", args: [], body: [{op:".byte",args:["B_SCR_OP_REMOVEATTACKERSTATUS1"]}] },
  { name: "finishaction", args: [], body: [{op:".byte",args:["B_SCR_OP_FINISHACTION"]}] },
  { name: "finishturn", args: [], body: [{op:".byte",args:["B_SCR_OP_FINISHTURN"]}] },
  { name: "trainerslideout", args: ["position:req"], body: [{op:".byte",args:["B_SCR_OP_TRAINERSLIDEOUT"]}, {op:".byte",args:["\\position"]}] },
  { name: "cancelmultiturnmoves", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_CANCEL_MULTI_TURN_MOVES"]}] },
  { name: "setmagiccoattarget", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_SET_MAGIC_COAT_TARGET"]}] },
  { name: "getifcantrunfrombattle", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_IS_RUNNING_IMPOSSIBLE"]}] },
  { name: "getmovetarget", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_GET_MOVE_TARGET"]}] },
  { name: "getbattlerfainted", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_GET_BATTLER_FAINTED"]}] },
  { name: "resetintimidatetracebits", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_RESET_INTIMIDATE_TRACE_BITS"]}] },
  { name: "updatechoicemoveonlvlup", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_UPDATE_CHOICE_MOVE_ON_LVL_UP"]}] },
  { name: "resetplayerfainted", args: [], body: [{op:"various",args:["BS_ATTACKER","VARIOUS_RESET_PLAYER_FAINTED"]}] },
  { name: "palaceflavortext", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_PALACE_FLAVOR_TEXT"]}] },
  { name: "arenajudgmentwindow", args: [], body: [{op:"various",args:["BS_ATTACKER","VARIOUS_ARENA_JUDGMENT_WINDOW"]}] },
  { name: "arenaopponentmonlost", args: [], body: [{op:"various",args:["BS_ATTACKER","VARIOUS_ARENA_OPPONENT_MON_LOST"]}] },
  { name: "arenaplayermonlost", args: [], body: [{op:"various",args:["BS_ATTACKER","VARIOUS_ARENA_PLAYER_MON_LOST"]}] },
  { name: "arenabothmonlost", args: [], body: [{op:"various",args:["BS_ATTACKER","VARIOUS_ARENA_BOTH_MONS_LOST"]}] },
  { name: "forfeityesnobox", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_EMIT_YESNOBOX"]}] },
  { name: "arenadrawreftextbox", args: [], body: [{op:"various",args:["BS_ATTACKER","VARIOUS_DRAW_ARENA_REF_TEXT_BOX"]}] },
  { name: "arenaerasereftextbox", args: [], body: [{op:"various",args:["BS_ATTACKER","VARIOUS_ERASE_ARENA_REF_TEXT_BOX"]}] },
  { name: "arenajudgmentstring", args: ["id:req"], body: [{op:"various",args:["\\id","VARIOUS_ARENA_JUDGMENT_STRING"]}] },
  { name: "arenawaitmessage", args: ["id:req"], body: [{op:"various",args:["\\id","VARIOUS_ARENA_WAIT_STRING"]}] },
  { name: "waitcry", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_WAIT_CRY"]}] },
  { name: "returnopponentmon1toball", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_RETURN_OPPONENT_MON1"]}] },
  { name: "returnopponentmon2toball", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_RETURN_OPPONENT_MON2"]}] },
  { name: "volumedown", args: [], body: [{op:"various",args:["BS_ATTACKER","VARIOUS_VOLUME_DOWN"]}] },
  { name: "volumeup", args: [], body: [{op:"various",args:["BS_ATTACKER","VARIOUS_VOLUME_UP"]}] },
  { name: "setalreadystatusedmoveattempt", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_SET_ALREADY_STATUS_MOVE_ATTEMPT"]}] },
  { name: "palacetryescapestatus", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_PALACE_TRY_ESCAPE_STATUS"]}] },
  { name: "setoutcomeonteleport", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_SET_TELEPORT_OUTCOME"]}] },
  { name: "playtrainerdefeatbgm", args: ["battler:req"], body: [{op:"various",args:["\\battler","VARIOUS_PLAY_TRAINER_DEFEATED_MUSIC"]}] },
  { name: "setstatchanger", args: ["stat:req", "stages:req", "down:req"], body: [{op:"setbyte",args:["sSTATCHANGER","\\stat | \\stages << 4 | \\down << 7"]}] },
  { name: "setmoveeffect", args: ["effect:req"], body: [{op:"setbyte",args:["cEFFECT_CHOOSER","\\effect"]}] },
  { name: "chosenstatus1animation", args: ["battler:req", "status:req"], body: [{op:"chosenstatusanimation",args:["\\battler","0x0","\\status"]}] },
  { name: "chosenstatus2animation", args: ["battler:req", "status:req"], body: [{op:"chosenstatusanimation",args:["\\battler","0x1","\\status"]}] },
  { name: "sethword", args: ["dst:req", "value:req"], body: [{op:"setbyte",args:["\\dst","(\\value) & 0xFF"]}, {op:"setbyte",args:["\\dst + 1","((\\value) >> 8) & 0xFF"]}] },
  { name: "setword", args: ["dst:req", "value:req"], body: [{op:"setbyte",args:["\\dst","(\\value) & 0xFF"]}, {op:"setbyte",args:["\\dst + 1","((\\value) >> 8) & 0xFF"]}, {op:"setbyte",args:["\\dst + 2","((\\value) >> 16) & 0xFF"]}, {op:"setbyte",args:["\\dst + 3","((\\value) >> 24) & 0xFF"]}] },
  { name: "copybyte", args: ["dst:req", "src:req"], body: [{op:"copyarray",args:["\\dst","\\src","0x1"]}] },
  { name: "copyhword", args: ["dst:req", "src:req"], body: [{op:"copyarray",args:["\\dst","\\src","0x2"]}] },
  { name: "copyword", args: ["dst:req", "src:req"], body: [{op:"copyarray",args:["\\dst","\\src","0x4"]}] },
  { name: "jumpifbytenotequal", args: ["byte1:req", "byte2:req", "jumpptr:req"], body: [{op:"jumpifarraynotequal",args:["\\byte1","\\byte2","0x1","\\jumpptr"]}] },
  { name: "jumpifbyteequal", args: ["byte1:req", "byte2:req", "jumpptr:req"], body: [{op:"jumpifarrayequal",args:["\\byte1","\\byte2","0x1","\\jumpptr"]}] },
  { name: "jumpifmove", args: ["move:req", "jumpptr:req"], body: [{op:"jumpifhalfword",args:["CMP_EQUAL","gCurrentMove","\\move","\\jumpptr"]}] },
  { name: "jumpifnotmove", args: ["move:req", "jumpptr:req"], body: [{op:"jumpifhalfword",args:["CMP_NOT_EQUAL","gCurrentMove","\\move","\\jumpptr"]}] },
  { name: "jumpifstatus3", args: ["battler:req", "status:req", "jumpptr:req"], body: [{op:"jumpifstatus3condition",args:["\\battler","\\status","FALSE","\\jumpptr"]}] },
  { name: "jumpifnostatus3", args: ["battler:req", "status:req", "jumpptr:req"], body: [{op:"jumpifstatus3condition",args:["\\battler","\\status","TRUE","\\jumpptr"]}] },
  { name: "jumpifmovehadnoeffect", args: ["jumpptr:req"], body: [{op:"jumpifbyte",args:["CMP_COMMON_BITS","gMoveResultFlags","MOVE_RESULT_NO_EFFECT","\\jumpptr"]}] },
  { name: "jumpifbattletype", args: ["flags:req", "jumpptr:req"], body: [{op:"jumpifword",args:["CMP_COMMON_BITS","gBattleTypeFlags","\\flags","\\jumpptr"]}] },
  { name: "jumpifnotbattletype", args: ["flags:req", "jumpptr:req"], body: [{op:"jumpifword",args:["CMP_NO_COMMON_BITS","gBattleTypeFlags","\\flags","\\jumpptr"]}] },
] as const;

// ─── Data directives (.byte/.2byte/.4byte/.string raw bytes) ───────────────
// Counts: .byte=1
export const DATA_DIRECTIVES = [
  { kind: '.byte', vals: ["B_SCR_OP_RETURN"] },
] as const;
