// AUTO-GENERATED from asm/macros/contest_ai_script.inc by extract-decomp-asm.mjs
// Do not edit manually — re-run `npm run extract:decomp-asm` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/asm/macros/contest_ai_script.inc
// Generated: 2026-06-10

// ─── .macro definitions (asm macro → opcode mapping bodies) ─────────────────
export const MACROS = [
  { name: "score", args: ["score:req"], body: [{op:".byte",args:["0x00"]}, {op:".byte",args:["\\score"]}] },
  { name: "get_appeal_num", args: [], body: [{op:".byte",args:["0x01"]}] },
  { name: "if_appeal_num_less_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x02"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_appeal_num_more_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x03"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_appeal_num_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x04"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_appeal_num_not_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x05"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_last_appeal", args: ["destination:req"], body: [{op:"if_appeal_num_eq",args:["CONTEST_LAST_APPEAL","\\destination"]}] },
  { name: "if_not_last_appeal", args: ["destination:req"], body: [{op:"if_appeal_num_not_eq",args:["CONTEST_LAST_APPEAL","\\destination"]}] },
  { name: "get_excitement", args: [], body: [{op:".byte",args:["0x06"]}] },
  { name: "if_excitement_less_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x07"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_excitement_more_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x08"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_excitement_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x09"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_excitement_not_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x0A"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_user_order", args: [], body: [{op:".byte",args:["0x0B"]}] },
  { name: "if_user_order_less_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x0C"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_user_order_more_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x0D"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_user_order_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x0E"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_user_order_not_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x0F"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_user_condition", args: [], body: [{op:".byte",args:["0x10"]}] },
  { name: "if_user_condition_less_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x11"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_user_condition_more_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x12"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_user_condition_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x13"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_user_condition_not_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x14"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_point_total", args: [], body: [{op:".byte",args:["0x15"]}] },
  { name: "if_points_less_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x16"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_points_more_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x17"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_points_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x18"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_points_not_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x19"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_preliminary_points", args: [], body: [{op:".byte",args:["0x1A"]}] },
  { name: "if_preliminary_points_less_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x1B"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_preliminary_points_more_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x1C"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_preliminary_points_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x1D"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_preliminary_points_not_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x1E"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_contest_type", args: [], body: [{op:".byte",args:["0x1F"]}] },
  { name: "if_contest_type_eq", args: ["type:req", "destination:req"], body: [{op:".byte",args:["0x20"]}, {op:".byte",args:["\\type"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_contest_type_not_eq", args: ["type:req", "destination:req"], body: [{op:".byte",args:["0x21"]}, {op:".byte",args:["\\type"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_move_excitement", args: [], body: [{op:".byte",args:["0x22"]}] },
  { name: "if_move_excitement_less_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x23"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_move_excitement_more_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x24"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_move_excitement_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x25"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_move_excitement_not_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x26"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_effect", args: [], body: [{op:".byte",args:["0x27"]}] },
  { name: "if_effect_eq", args: ["effect:req", "destination:req"], body: [{op:".byte",args:["0x28"]}, {op:".byte",args:["\\effect"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_effect_not_eq", args: ["effect:req", "destination:req"], body: [{op:".byte",args:["0x29"]}, {op:".byte",args:["\\effect"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_effect_type", args: [], body: [{op:".byte",args:["0x2A"]}] },
  { name: "if_effect_type_eq", args: ["type:req", "destination:req"], body: [{op:".byte",args:["0x2B"]}, {op:".byte",args:["\\type"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_effect_type_not_eq", args: ["type:req", "destination:req"], body: [{op:".byte",args:["0x2C"]}, {op:".byte",args:["\\type"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "check_most_appealing_move", args: [], body: [{op:".byte",args:["0x2D"]}] },
  { name: "if_most_appealing_move", args: ["destination:req"], body: [{op:".byte",args:["0x2E"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "check_most_jamming_move", args: [], body: [{op:".byte",args:["0x2F"]}] },
  { name: "if_most_jamming_move", args: ["destination:req"], body: [{op:".byte",args:["0x30"]}, {op:".4bye",args:["\\destination"]}] },
  { name: "get_num_move_hearts", args: [], body: [{op:".byte",args:["0x31"]}] },
  { name: "if_num_move_hearts_less_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x32"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_num_move_hearts_more_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x33"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_num_move_hearts_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x34"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_num_move_hearts_not_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x35"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_num_move_jam_hearts", args: [], body: [{op:".byte",args:["0x36"]}] },
  { name: "if_num_move_jam_hearts_less_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x37"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_num_move_jam_hearts_more_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x38"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_num_move_jam_hearts_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x39"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_num_move_jam_hearts_not_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x3A"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_move_used_count", args: [], body: [{op:".byte",args:["0x3B"]}] },
  { name: "if_move_used_count_less_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x3C"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_move_used_count_more_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x3D"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_move_used_count_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x3E"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_move_used_count_not_eq", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x3F"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "check_combo_starter", args: [], body: [{op:".byte",args:["0x40"]}] },
  { name: "if_combo_starter", args: ["destination:req"], body: [{op:".byte",args:["0x41"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_not_combo_starter", args: ["destination:req"], body: [{op:".byte",args:["0x42"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "check_combo_finisher", args: [], body: [{op:".byte",args:["0x43"]}] },
  { name: "if_combo_finisher", args: ["destination:req"], body: [{op:".byte",args:["0x44"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_not_combo_finisher", args: ["destination:req"], body: [{op:".byte",args:["0x45"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "check_would_finish_combo", args: [], body: [{op:".byte",args:["0x46"]}] },
  { name: "if_would_finish_combo", args: ["destination:req"], body: [{op:".byte",args:["0x47"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_would_not_finish_combo", args: ["destination:req"], body: [{op:".byte",args:["0x48"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_condition", args: ["mon:req"], body: [{op:".byte",args:["0x49"]}, {op:".byte",args:["\\mon"]}] },
  { name: "if_condition_less_than", args: ["mon:req", "num:req destination:req"], body: [{op:".byte",args:["0x4A"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_condition_more_than", args: ["mon:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x4B"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_condition_eq", args: ["mon:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x4C"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_condition_not_eq", args: ["mon:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x4D"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_used_combo_starter", args: ["mon:req"], body: [{op:".byte",args:["0x4E"]}, {op:".byte",args:["\\mon"]}] },
  { name: "if_used_combo_starter_less_than", args: ["mon:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x4F"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_used_combo_starter_more_than", args: ["mon:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x50"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_used_combo_starter_eq", args: ["mon:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x51"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_used_combo_starter_not_eq", args: ["mon:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x52"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_used_combo_starter", args: ["mon:req", "destination:req"], body: [{op:"if_used_combo_starter_eq",args:["\\mon","TRUE","\\destination"]}] },
  { name: "if_not_used_combo_starter", args: ["mon:req", "destination:req"], body: [{op:"if_used_combo_starter_eq",args:["\\mon","FALSE","\\destination"]}] },
  { name: "check_can_participate", args: ["mon:req"], body: [{op:".byte",args:["0x53"]}, {op:".byte",args:["\\mon"]}] },
  { name: "if_can_participate", args: ["mon:req", "destination:req"], body: [{op:".byte",args:["0x54"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_cannot_participate", args: ["mon:req", "destination:req"], body: [{op:".byte",args:["0x55"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_completed_combo", args: ["mon:req"], body: [{op:".byte",args:["0x56"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_completed_combo", args: ["mon:req", "destination:req"], body: [{op:".byte",args:["0x57"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_not_completed_combo", args: ["mon:req destination:req"], body: [{op:".byte",args:["0x58"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_points_diff", args: ["mon:req"], body: [{op:".byte",args:["0x59"]}, {op:".byte",args:["\\mon"]}] },
  { name: "if_points_more_than_mon", args: ["mon:req", "destination:req"], body: [{op:".byte",args:["0x5A"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_points_less_than_mon", args: ["mon:req", "destination:req"], body: [{op:".byte",args:["0x5B"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_points_eq_mon", args: ["mon:req", "destination:req"], body: [{op:".byte",args:["0x5C"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_points_not_eq_mon", args: ["mon:req", "destination:req"], body: [{op:".byte",args:["0x5D"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_preliminary_points_diff", args: ["mon:req"], body: [{op:".byte",args:["0x5E"]}, {op:".byte",args:["\\mon"]}] },
  { name: "if_preliminary_points_more_than_mon", args: ["mon:req", "destination:req"], body: [{op:".byte",args:["0x5F"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_preliminary_points_less_than_mon", args: ["mon:req", "destination:req"], body: [{op:".byte",args:["0x60"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_preliminary_points_eq_mon", args: ["mon:req", "destination:req"], body: [{op:".byte",args:["0x61"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_preliminary_points_not_eq_mon", args: ["mon:req", "destination:req"], body: [{op:".byte",args:["0x62"]}, {op:".byte",args:["\\mon"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_used_moves_effect", args: ["mon:req", "round:req"], body: [{op:".byte",args:["0x63"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}] },
  { name: "if_used_moves_effect_less_than", args: ["mon:req", "round:req", "effect:req", "destination:req"], body: [{op:".byte",args:["0x64"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}, {op:".byte",args:["\\effect"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_used_moves_effect_more_than", args: ["mon:req", "round:req", "effect:req", "destination:req"], body: [{op:".byte",args:["0x65"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}, {op:".byte",args:["\\effect"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_used_moves_effect_eq", args: ["mon:req", "round:req", "effect:req", "destination:req"], body: [{op:".byte",args:["0x66"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}, {op:".byte",args:["\\effect"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_used_moves_effect_not_eq", args: ["mon:req", "round:req", "effect:req", "destination:req"], body: [{op:".byte",args:["0x67"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}, {op:".byte",args:["\\effect"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_used_moves_excitement", args: ["mon:req", "round:req"], body: [{op:".byte",args:["0x68"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}] },
  { name: "if_used_moves_excitement_less_than", args: ["mon:req", "round:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x69"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_used_moves_excitement_more_than", args: ["mon:req", "round:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x6A"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_used_moves_excitement_eq", args: ["mon:req", "round:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x6B"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_used_moves_excitement_not_eq", args: ["mon:req", "round:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x6C"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "get_used_moves_effect_type", args: ["mon:req", "round:req"], body: [{op:".byte",args:["0x6D"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}] },
  { name: "if_used_moves_effect_type_eq", args: ["mon:req", "round:req", "type:req", "destination:req"], body: [{op:".byte",args:["0x6E"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}, {op:".byte",args:["\\type"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_used_moves_effect_type_not_eq", args: ["mon:req", "round:req", "type:req", "destination:req"], body: [{op:".byte",args:["0x6F"]}, {op:".byte",args:["\\mon"]}, {op:".byte",args:["\\round"]}, {op:".byte",args:["\\type"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "save_result", args: ["varId:req"], body: [{op:".byte",args:["0x70"]}, {op:".byte",args:["\\varId"]}] },
  { name: "setvar", args: ["varId:req", "num:req"], body: [{op:".byte",args:["0x71"]}, {op:".byte",args:["\\varId"]}, {op:".2byte",args:["\\num"]}] },
  { name: "add", args: ["varId:req", "num:req"], body: [{op:".byte",args:["0x72"]}, {op:".byte",args:["\\varId"]}, {op:".2byte",args:["\\num"]}] },
  { name: "addvar", args: ["varId1:req", "varId2:req"], body: [{op:".byte",args:["0x73"]}, {op:".byte",args:["\\varId1"]}, {op:".byte",args:["\\varId2"]}] },
  { name: "addvar_duplicate", args: ["varId1:req", "varId2:req"], body: [{op:".byte",args:["0x74"]}, {op:".byte",args:["\\varId1"]}, {op:".byte",args:["\\varId2"]}] },
  { name: "if_less_than", args: ["varId:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x75"]}, {op:".byte",args:["\\varId"]}, {op:".2byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_greater_than", args: ["varId:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x76"]}, {op:".byte",args:["\\varId"]}, {op:".2byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_eq", args: ["varId:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x77"]}, {op:".byte",args:["\\varId"]}, {op:".2byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_not_eq", args: ["varId:req", "num:req", "destination:req"], body: [{op:".byte",args:["0x78"]}, {op:".byte",args:["\\varId"]}, {op:".2byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_less_than_var", args: ["varId1:req", "varId2:req", "destination:req"], body: [{op:".byte",args:["0x79"]}, {op:".byte",args:["\\varId1"]}, {op:".byte",args:["\\varId2"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_greater_than_var", args: ["varId1:req", "varId2:req", "destination:req"], body: [{op:".byte",args:["0x7A"]}, {op:".byte",args:["\\varId1"]}, {op:".byte",args:["\\varId2"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_eq_var", args: ["varId1:req", "varId2:req", "destination:req"], body: [{op:".byte",args:["0x7B"]}, {op:".byte",args:["\\varId1"]}, {op:".byte",args:["\\varId2"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_not_eq_var", args: ["varId1:req", "varId2:req", "destination:req"], body: [{op:".byte",args:["0x7C"]}, {op:".byte",args:["\\varId1"]}, {op:".byte",args:["\\varId2"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_random_less_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x7D"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_random_greater_than", args: ["num:req", "destination:req"], body: [{op:".byte",args:["0x7E"]}, {op:".byte",args:["\\num"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "goto", args: ["destination:req"], body: [{op:".byte",args:["0x7F"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "call", args: ["destination:req"], body: [{op:".byte",args:["0x80"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "end", args: [], body: [{op:".byte",args:["0x81"]}] },
  { name: "check_user_has_exciting_move", args: [], body: [{op:".byte",args:["0x82"]}] },
  { name: "if_user_has_exciting_move", args: ["destination:req"], body: [{op:".byte",args:["0x83"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_user_doesnt_have_exciting_move", args: ["destination:req"], body: [{op:".byte",args:["0x84"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "check_user_has_move", args: ["move:req"], body: [{op:".byte",args:["0x85"]}, {op:".2byte",args:["\\move"]}] },
  { name: "if_user_has_move", args: ["move:req", "destination:req"], body: [{op:".byte",args:["0x86"]}, {op:".2byte",args:["\\move"]}, {op:".4byte",args:["\\destination"]}] },
  { name: "if_user_doesnt_have_move", args: ["move:req", "destination:req"], body: [{op:".byte",args:["0x87"]}, {op:".2byte",args:["\\move"]}, {op:".4byte",args:["\\destination"]}] },
] as const;
