// AUTO-GENERATED from asm/macros/music_voice.inc by extract-decomp-asm.mjs
// Do not edit manually — re-run `npm run extract:decomp-asm` to refresh.
//
// Source: D:/Projet 1/decomps/pokeemeraude/asm/macros/music_voice.inc
// Generated: 2026-06-10

// ─── .macro definitions (asm macro → opcode mapping bodies) ─────────────────
export const MACROS = [
  { name: "voice_directsound", args: ["base_midi_key:req", "pan:req", "sample_data_pointer:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:".byte",args:["0"]}, {op:"_voice_directsound",args:["\\base_midi_key","\\pan","\\sample_data_pointer","\\attack","\\decay","\\sustain","\\release"]}] },
  { name: "voice_directsound_no_resample", args: ["base_midi_key:req", "pan:req", "sample_data_pointer:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:".byte",args:["8"]}, {op:"_voice_directsound",args:["\\base_midi_key","\\pan","\\sample_data_pointer","\\attack","\\decay","\\sustain","\\release"]}] },
  { name: "voice_directsound_alt", args: ["base_midi_key:req", "pan:req", "sample_data_pointer:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:".byte",args:["16"]}, {op:"_voice_directsound",args:["\\base_midi_key","\\pan","\\sample_data_pointer","\\attack","\\decay","\\sustain","\\release"]}] },
  { name: "_voice_directsound", args: ["base_midi_key:req", "pan:req", "sample_data_pointer:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:".byte",args:["\\base_midi_key"]}, {op:".byte",args:["0"]}, {op:".if",args:["\\pan != 0"]}, {op:".byte",args:["(0x80 | \\pan)"]}, {op:".else",args:[]}, {op:".byte",args:["0"]}, {op:".endif",args:[]}, {op:".4byte",args:["\\sample_data_pointer"]}, {op:".byte",args:["\\attack"]}, {op:".byte",args:["\\decay"]}, {op:".byte",args:["\\sustain"]}, {op:".byte",args:["\\release"]}] },
  { name: "voice_square_1", args: ["base_midi_key:req", "pan:req", "sweep:req", "duty_cycle:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:"_voice_square_1",args:["1","\\base_midi_key","\\pan","\\sweep","\\duty_cycle","\\attack","\\decay","\\sustain","\\release"]}] },
  { name: "voice_square_1_alt", args: ["base_midi_key:req", "pan:req", "sweep:req", "duty_cycle:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:"_voice_square_1",args:["9","\\base_midi_key","\\pan","\\sweep","\\duty_cycle","\\attack","\\decay","\\sustain","\\release"]}] },
  { name: "_voice_square_1", args: ["type:req", "base_midi_key:req", "pan:req", "sweep:req", "duty_cycle:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:".byte",args:["\\type"]}, {op:".byte",args:["\\base_midi_key"]}, {op:".if",args:["\\pan != 0"]}, {op:".byte",args:["(0x80 | \\pan)"]}, {op:".else",args:[]}, {op:".byte",args:["0"]}, {op:".endif",args:[]}, {op:".byte",args:["\\sweep"]}, {op:".byte",args:["(\\duty_cycle & 0x3)"]}, {op:".byte",args:["0","0","0"]}, {op:".byte",args:["(\\attack  & 0x7)"]}, {op:".byte",args:["(\\decay   & 0x7)"]}, {op:".byte",args:["(\\sustain & 0xF)"]}, {op:".byte",args:["(\\release & 0x7)"]}] },
  { name: "voice_square_2", args: ["base_midi_key:req", "pan:req", "duty_cycle:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:"_voice_square_2",args:["2","\\base_midi_key","\\pan","\\duty_cycle","\\attack","\\decay","\\sustain","\\release"]}] },
  { name: "voice_square_2_alt", args: ["base_midi_key:req", "pan:req", "duty_cycle:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:"_voice_square_2",args:["10","\\base_midi_key","\\pan","\\duty_cycle","\\attack","\\decay","\\sustain","\\release"]}] },
  { name: "_voice_square_2", args: ["type:req", "base_midi_key:req", "pan:req", "duty_cycle:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:".byte",args:["\\type"]}, {op:".byte",args:["\\base_midi_key"]}, {op:".if",args:["\\pan != 0"]}, {op:".byte",args:["(0x80 | \\pan)"]}, {op:".else",args:[]}, {op:".byte",args:["0"]}, {op:".endif",args:[]}, {op:".byte",args:["0"]}, {op:".byte",args:["(\\duty_cycle & 0x3)"]}, {op:".byte",args:["0","0","0"]}, {op:".byte",args:["(\\attack  & 0x7)"]}, {op:".byte",args:["(\\decay   & 0x7)"]}, {op:".byte",args:["(\\sustain & 0xF)"]}, {op:".byte",args:["(\\release & 0x7)"]}] },
  { name: "voice_programmable_wave", args: ["base_midi_key:req", "pan:req", "wave_samples_pointer:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:"_voice_programmable_wave",args:["3","\\base_midi_key","\\pan","\\wave_samples_pointer","\\attack","\\decay","\\sustain","\\release"]}] },
  { name: "voice_programmable_wave_alt", args: ["base_midi_key:req", "pan:req", "wave_samples_pointer:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:"_voice_programmable_wave",args:["11","\\base_midi_key","\\pan","\\wave_samples_pointer","\\attack","\\decay","\\sustain","\\release"]}] },
  { name: "_voice_programmable_wave", args: ["type:req", "base_midi_key:req", "pan:req", "wave_samples_pointer:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:".byte",args:["\\type"]}, {op:".byte",args:["\\base_midi_key"]}, {op:".if",args:["\\pan != 0"]}, {op:".byte",args:["(0x80 | \\pan)"]}, {op:".else",args:[]}, {op:".byte",args:["0"]}, {op:".endif",args:[]}, {op:".byte",args:["0"]}, {op:".4byte",args:["\\wave_samples_pointer"]}, {op:".byte",args:["(\\attack  & 0x7)"]}, {op:".byte",args:["(\\decay   & 0x7)"]}, {op:".byte",args:["(\\sustain & 0xF)"]}, {op:".byte",args:["(\\release & 0x7)"]}] },
  { name: "voice_noise", args: ["base_midi_key:req", "pan:req", "period:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:"_voice_noise",args:["4","\\base_midi_key","\\pan","\\period","\\attack","\\decay","\\sustain","\\release"]}] },
  { name: "voice_noise_alt", args: ["base_midi_key:req", "pan:req", "period:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:"_voice_noise",args:["12","\\base_midi_key","\\pan","\\period","\\attack","\\decay","\\sustain","\\release"]}] },
  { name: "_voice_noise", args: ["type:req", "base_midi_key:req", "pan:req", "period:req", "attack:req", "decay:req", "sustain:req", "release:req"], body: [{op:".byte",args:["\\type"]}, {op:".byte",args:["\\base_midi_key"]}, {op:".if",args:["\\pan != 0"]}, {op:".byte",args:["(0x80 | \\pan)"]}, {op:".else",args:[]}, {op:".byte",args:["0"]}, {op:".endif",args:[]}, {op:".byte",args:["0"]}, {op:".byte",args:["(\\period & 0x1)"]}, {op:".byte",args:["0","0","0"]}, {op:".byte",args:["(\\attack  & 0x7)"]}, {op:".byte",args:["(\\decay   & 0x7)"]}, {op:".byte",args:["(\\sustain & 0xF)"]}, {op:".byte",args:["(\\release & 0x7)"]}] },
  { name: "voice_keysplit", args: ["voice_group_pointer:req", "keysplit_table_pointer:req"], body: [{op:".byte",args:["0x40","0","0","0"]}, {op:".4byte",args:["\\voice_group_pointer"]}, {op:".4byte",args:["\\keysplit_table_pointer"]}] },
  { name: "voice_keysplit_all", args: ["voice_group_pointer:req"], body: [{op:".byte",args:["0x80","0","0","0"]}, {op:".4byte",args:["\\voice_group_pointer"]}, {op:".4byte",args:["0"]}] },
  { name: "cry", args: ["sample:req"], body: [{op:".byte",args:["0x20","60","0","0"]}, {op:".4byte",args:["\\sample"]}, {op:".byte",args:["0xff","0","0xff","0"]}] },
  { name: "cry_reverse", args: ["sample:req"], body: [{op:".byte",args:["0x30","60","0","0"]}, {op:".4byte",args:["\\sample"]}, {op:".byte",args:["0xff","0","0xff","0"]}] },
] as const;
